### ISSUE TITLE
Using a hyphen ("-") in a parameter name with the saveParams option

### ISSUE THREAD

**Issue by bleutzinn** [froala/wysiwyg-editor#1002]
When I use a hyphen ("-") in a parameter name with the `saveParams` option, Froala doesn't initialize properly. For example this crashes the editor:
``` javascript
$('.selector').froalaEditor({
  saveParams: {
  form-nonce: 'a1824e512e76dd8ba1e5c1981b528b6d'
}
});
```
I was wondering whether this a (undocumented) feature or a bug? The version is 2.0.5

**Comment by stefanneculai** [comment]
You should use `'form-nonce'`.

**Comment by bleutzinn** [comment]
Thanks. I should have tried that before posting it as an issue. Sorry about that!
