### ISSUE TITLE
Uploading multiple images and files

### ISSUE THREAD

**Issue by vahtel** [froala/wysiwyg-editor#1004]
Uploading and inserting multiple images or files concurrently doesn't work. Simple test case is to try drag and drop multiple files to the editor, only the first one is inserted.

It isn't an issue with the picker because the <code>input type="file"</code> has multiple false.

**Comment by stefanneculai** [comment]
This is by design. For the moment we don't support multiple images/files upload.

**Comment by hackel** [comment]
Please re-open this as a feature request.  It would be quite easy to implement.  For now, I'm relying on a completely separate drop target that allows for multiple attachments, but this is a far less cohesive experience for end-users.

**Comment by stefanneculai** [comment]
@hackel we do not keep Feature requests here that's why this is closed. It is on our list, but I cannot tell you when it will be implemented. Although it might appear an easy thing to achieve, there are multiple things to consider. 
	- In order to have the images inserted correctly into the editor, the user should not type anything while the images are being uploaded. You can see that now when an image is uploaded we disable the editor input. This might result in having the user wait a long time for the images to be uploaded if there are several images there.
	- Another thing to be aware of is how images are being inserted. The editor inserts images at the cursor position so there is no problem with the first image. But after the first image is inserted you have to decide where the next one should fall.

**Comment by hackel** [comment]
I was thinking primarily about dropping multiple images on the drop target to appear in the image gallery, as opposed to directly in the editor itself, though I could see both being desirable, as well as the ability to select multiple images from the gallery to insert into the editor.  Inserting them one after the other at the cursor position makes the most sense to me, then they can be dragged around wherever needed.

In terms of a long upload time, I personally think that's fine.  A fancy progress bar would be nice, of course, but not strictly necessary.  Users can certainly be advised against long uploads, etc.

**Comment by stefanneculai** [comment]
@hackel Thank you for the feedback, really appreciate it a lot. I can assure you we're working on this feature, but we won't add it until we find a good way to address the things listed above plus few others. Adding new features is easy, but adding features that users love to use takes a bit of time and research.

**Comment by mukk85** [comment]
Is there any ETA for this?

**Comment by stefanneculai** [comment]
@mukk85 unfortunately, we don't have an ETA for this. Thank you.

**Comment by mukk85** [comment]
It has been over a year now. Any progress on this?

**Comment by sanjay-parmar-tatva** [comment]
Hi All, I have solved issue manually.

please find attached image.min.js and replace it with floara editor image.min.js.

it's work fine for me. And let me know if you have any issue so ill update it base on your requirement.
Please change image.min.txt to image.min.js.

[image.min.txt](https://github.com/froala/wysiwyg-editor/files/961527/image.min.txt)

Thanks.
Sanjay Parmar

**Comment by hackel** [comment]
@sanjay-parmar-tatva What exactly did you change?  How did you address the above mentioned issues?  I'm fairly certain you are not allowed to distribute derivative works per the disgusting, closed-source license of this product.

**Comment by mukk85** [comment]
Thanks, that seems to work for images being inserted, however I am more in need of having multiple files. It would seem I will have to do the same as @hackel and create a separate drop target.

**Comment by sanjay-parmar-tatva** [comment]
@hackel, yes, i have reverted my comment. and if any one need help to change allow multiple file please contact me directly.

Thanks

**Comment by a-kolybelnikov** [comment]
@sanjay-parmar-tatva how can I contact you? can't find your email, mate.

**Comment by shd188** [comment]
@sanjay-parmar-tatva  Please tell me your email，thanks

**Comment by GDanielRG** [comment]
@sanjay-parmar-tatva  can you contact me for having that js? danyrod94@gmail.com

**Comment by dcaliri** [comment]
can I have that js too? diegocaliri@gmail.com

**Comment by heymexa** [comment]
[My solution](https://github.com/heymexa/froala-images-multi-upload)

**Comment by nwyee** [comment]
@sanjay-parmar-tatva  can i have that js ?

**Comment by sanjay-parmar-tatva** [comment]
Hi nwyee,

sorry but i think it creates some distribution issue with floara. Because
it's product of froala editor.

**Comment by nwyee** [comment]
@sanjay-parmar-tatva  It's okay. thanks anyway.

**Comment by clarkorz** [comment]
@sanjay-parmar-tatva I'm a commerial user of Froala, could you send me your solution? thx. clark.wangs@gmail.com

**Comment by DoanVanThuong** [comment]
totally agree with you
can you give me that solution
doan van thuong196@gmail.com

**Comment by maddy-mangi** [comment]
Hi @sanjay-parmar-tatva  Can you please send me the updated library for uploading multiple files.
Thanks .. 
-maddy
**Mangipudi@gmail.com**

**Comment by lovelyelfpop** [comment]
@sanjay-parmar-tatva  Hi, can you please send me your library for uploading multiple images. Thanks. This is my email: lovelyelfpop@gmail.com

**Comment by Webinsane** [comment]
> 
> 
> For resolve this problem I have developed the plugin - [Images Multi Upload](https://github.com/heymexa/froala-images-multi-upload)
> 
> The plugin uses options from _image.js_ plugin and allows to send many images to the server.
> 
> Enjoy!

Thanks for the plugin. Did anyone tested it yet?

**Comment by sanjay-parmar-tatva** [comment]
@All, please contact me on sanjaykumar.parmar21@gmail.com to resolve this issue.

Thanks

**Comment by vpekarek** [comment]
Did not tested, but overriding the default image plugin is quite easy. Just add multiple attribute to image upload input and modify upload function in image.js to loop through images from input, instead of taking first one.

From: `if (typeof images != 'undefined' && images.length > 0) {`
To: `if (typeof images === 'undefined' || images.length === 0) {
                return;
            }
            for (var i = 0; i < images.length; i++) {`

This will work.
