### ISSUE TITLE
Double scrollbar issue when using iframe=true option

### ISSUE THREAD

**Issue by projectsphonegapdev1** [froala/wysiwyg-editor#1006]
Hi All,

in one of our application we are trying froala editor with following configuration:

toolbarButtons:   ['html', '|', 'bold', 'italic', 'underline', '|', 'align', '|', 'fontFamily', 'fontSize', '|', 'color', '|', 'imageGallery'],
        toolbarButtonsSM: ['html', '|', 'bold', 'italic', 'underline', '|', 'align', '|', 'fontFamily', 'fontSize', '|', 'color', '|', 'imageGallery'],
        toolbarButtonsMD: ['html', '|', 'bold', 'italic', 'underline', '|', 'align', '|', 'fontFamily', 'fontSize', '|', 'color', '|', 'imageGallery'],
        toolbarButtonsXS: ['html', '|', 'bold', 'italic', 'underline', '|', 'align', '|', 'fontFamily', 'fontSize', '|', 'color', '|', 'imageGallery'],
        fontSize: ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '22', '24', '26', '28', '30', '32', '34', '36', '38', '40', '45', '50', '55', '60', '65', '70', '75', '80', '85', '90', '95', '100'],
        iframe: true,
        language: 'en_us',
        placeholderText: '',
        height: 400

but it's showing two scrollbar 

![iframeoption_issue](https://cloud.githubusercontent.com/assets/8512746/12144047/2adf16ac-b4ab-11e5-8210-c3925a31a21a.png)

can anyone please help how we can handle it without any big changes.

Best Regards,
Imran

**Comment by stefanneculai** [comment]
Would it be possible to make a JSFiddle? What OS and browser are you using? 

Thanks.

**Comment by projectsphonegapdev1** [comment]
Ok i willl try.

I am using windows 8.1 and chrome version 47.
