### ISSUE TITLE
License version

### ISSUE THREAD

**Issue by ignaciovaldes** [froala/wysiwyg-editor#1009]
I pass the key as config var on Heroku but it doesn't work. What can I do?
<img width="562" alt="captura de pantalla 2016-01-07 a las 6 48 51 p m" src="https://cloud.githubusercontent.com/assets/6554443/12187192/55b430d2-b56f-11e5-9d83-f5b2a9c73917.png">

**Comment by stefanneculai** [comment]
Please contact us via our website.
