### ISSUE TITLE
Non breaking space is added after link and can't be removed

### ISSUE THREAD

**Issue by perzi** [froala/wysiwyg-editor#1011]
1. Insert a link
2. Press space
3. Write some text
4. Froala inserts a non breaking space between link and text after and it can't be removed with backspace. You have to add three spaces to get a soft space between link and text. Link and text after will always stick together and will not be word wrapped.

![froala link nbsp bug](https://cloud.githubusercontent.com/assets/812354/12195786/269780e8-b5fa-11e5-8f17-37f339463b6b.gif)

**Comment by stefanneculai** [comment]
That is the correct behaviour.

**Comment by perzi** [comment]
@stefanneculai Why is that correct behavior to tie the link and the following word together?

**Comment by perzi** [comment]
I understand that you might want to add &nbsp; when user adds many spaces. But the result now is 
1 space = &nbsp;
2 spaces = &nbsp;&nbsp;
3 spaces = &nbsp;<space>&nbsp;

I would expect the editor to add normal space for one space and then a combination of space and &nbsp;

**Comment by stefanneculai** [comment]
Actually it is an issue and that happens only as you type.

**Comment by perzi** [comment]
@stefanneculai Didn't preview my previous comment. Here's the updated one. But I guess you understood what I meant. 

"I understand that you might want to add nbsp  when user adds many spaces. But the result now is 

1 space = nbsp
2 spaces = nbsp + nbsp
3 spaces = nbsp + space + nbsp

I would expect the editor to add normal space for one space and then a combination of space and nbsp
