### ISSUE TITLE
Error in using Methods. for Angular Binding. 

### ISSUE THREAD

**Issue by modi28** [froala/wysiwyg-editor#1012]
I get this error in console:
TypeError: $scope.froalaOptions.froalaEditor is not a function
$scope.froalaOptions is working fine.

My Code:

    $scope.froalaOptions = {
              toolbarBottom: true,
              charCounterCount: false,
              toolbarButtons: ["bold", "italic", "underline"]
          };
    $scope.froalaOptions.froalaEditor("selection.get");

**Comment by stefanneculai** [comment]
Please open this on the Angular repo.
