### ISSUE TITLE
Pasting from Google Docs wraps all text in bold

### ISSUE THREAD

**Issue by wleklinski** [froala/wysiwyg-editor#1014]
If you copy content from a Google Document, then paste into an empty Froala editor, the resulting copy is wrapped in `strong` tags.

Steps to reproduce:

1. Open [a Google Doc](https://docs.google.com/document/d/18L3TOdNRyw0ggrkC0EFhTw3MFdaogBg9K3xsE4Z2JZA/edit?usp=sharing), select all, and copy the contents
2. Navigate to the [Froala homepage demo WYSIWYG](https://www.froala.com/wysiwyg-editor), select all, and delete existing content
3. Paste content

Can replicate in Chrome, Chrome Canary, Safari, and Opera on a Mac. Bug doesn't appear in Firefox.

**Comment by stefanneculai** [comment]
Last commit fixes this. You might notice that some formatting such as bold/italic might not appear. That is because Google Docs uses the `style` attribute to set them and by default the editor is stripping the `style` attribute on paste. However, you can change that through the [pasteDeniedAttrs](https://www.froala.com/wysiwyg-editor/docs/options#pasteDeniedAttrs) option.

**Comment by wleklinski** [comment]
Awesome, thanks for the heads up.

**Comment by ibtisamniche-vteams** [comment]
Hi there is some kind of issue with my froala editor. Whenever i copied a paragraph that contains bold words or sentences, on pasting it in froala editor it shows the text as simple the bold text also shows as simple not in bold.

**Comment by stefanneculai** [comment]
@ibtisamniche-vteams are you pasting from Google Docs?

**Comment by ibtisamniche-vteams** [comment]
@stefanneculai yes I was copying from google docs to froala editor but the bold formatting wasn't being preserved. After adding pasteDeniedAttrs:['class','id'] in froala configuration , the text is copying in froala as desired.

**Comment by ibtisamniche-vteams** [comment]
@stefanneculai there is an issue again , if I add pasteDeniedAttrs:['class','id'] in froala configuration on pasting the editor controls are not being updated.
