### ISSUE TITLE
If a tooltip is visible when froala is destroyed, it is not hidden

### ISSUE THREAD

**Issue by DallanQ** [froala/wysiwyg-editor#1015]
When the froala editor is destroyed, the `style="left: top: "` and the `fr-visible` class should be removed from all fr-tooltip divs.

**Comment by stefanneculai** [comment]
Could you please provide the exact steps to reproduce it? Thank you.

**Comment by stefanneculai** [comment]
@DallanQ Could you please explain the exact steps to reproduce this issue?

**Comment by stefanneculai** [comment]
We have rechecked this and on destroy the tooltip is set to be removed from the DOM. Please make sure you're using the latest version.

**Comment by DallanQ** [comment]
I can't reproduce it using the latest version of froala either. I'm using angular-froala and attaching the editor to a div in a popup. One of those may be the problem. I'll investigate more and let you know.
