### ISSUE TITLE
Link Popup Invisible

### ISSUE THREAD

**Issue by benjaminknox** [froala/wysiwyg-editor#1016]
This happens mostly just after adding a link to the froala editor, the edit link popup doesn't show up when the user opens, it seems to be invisible.

Steps to reproduce:
1) Open https://www.froala.com/wysiwyg-editor/docs/examples/fullscreen
2) Click fullscreen button
3) Paste text from [example_text.txt](https://github.com/froala/wysiwyg-editor/files/83398/example_text.txt)
4) Create a link using the link button
5) Edit any link below the fold
6) Result: Popup does not show up and user can't scroll unless the mouse is moved
7) Once the user is able to scroll the popup suddenly appears

Screencast attached:
![link-popup-invisible](https://cloud.githubusercontent.com/assets/5668789/12212083/6ab4b7b8-b623-11e5-8f14-0255c98e039b.gif)

[link-popup-invisible.mp4.zip](https://github.com/froala/wysiwyg-editor/files/83401/link-popup-invisible.mp4.zip)

**Comment by stefanneculai** [comment]
I have just tried it and it appears to be fixed on the master version. Could you please try it?

**Comment by benjaminknox** [comment]
Fixed! And works very well! Thanks.
