### ISSUE TITLE
Custom theme tooltip settings don't work

### ISSUE THREAD

**Issue by tyshkavets** [froala/wysiwyg-editor#1017]
Customizing a theme using https://www.froala.com/wysiwyg-editor/customize and setting custom background color for tooltips doesn't work.

Whenever you set custom theme during Froala initialization, class `custom-theme` is added to `fr-tooltip` elements. CSS generated by the website, however, holds specified tooltip settings in 
    `.custom-theme .fr-tooltip {`
block, as if `custom-theme` class is applied to `.fr-tooltip`'s parent. Manually removing this extra space between classes in generated CSS is a workaround.

**Comment by stefanneculai** [comment]
Last commit fixes it. The customizer will be updated just only when we'll make the release 2.0.6, in the following days.
