### ISSUE TITLE
HTML code formatting in one line

### ISSUE THREAD

**Issue by akhasanov** [froala/wysiwyg-editor#1018]
Hello,

Any HTML code formatted to one line. How to disable this option?

Thanks.

**Comment by stefanneculai** [comment]
Could you please provide more details?

**Comment by akhasanov** [comment]
Sure. Any code formatted in one line, like that: http://joxi.ru/brR8Xg7fQL19l2

I write any code: http://joxi.ru/YmEkQgLcZBWQBA 
then I switch modes (Code View) and got something like this: http://joxi.ru/V2Vey6qc08eyMm

**Comment by stefanneculai** [comment]
That's because, you're not including the Code Beautifier plugin.
