### ISSUE TITLE
Browserify plugin issue after 2.0.2

### ISSUE THREAD

**Issue by codymorrison** [froala/wysiwyg-editor#1021]
I noticed after 2.0.2 came out Froala plugins loaded through Browserify quit working. I assume this has to do with the new UMD definition at the top of each plugin, but without having a clear view of the source its tough to figure out whats happening.

When switching from 2.0.1 to anything beyond all plugins beyond bold, italic,underline and hr don't end up loading using a basic Browserify setup.

**Comment by stefanneculai** [comment]
Is that happening with 2.0.5 as well?

**Comment by codymorrison** [comment]
Yep. 2.0.1 is the last time this worked correctly.

**Comment by stefanneculai** [comment]
OK. We'll check it.

**Comment by stefanneculai** [comment]
I have just tested it with the master version and it works fine. Here is how I included it:
```js
var $ = require('jquery');
require('froala-editor/js/froala_editor.min.js')($);
require('froala-editor/js/plugins/link.min.js')($);

$(function() {
  var $target = $('<div>').appendTo('body');
  $target.froalaEditor()
});
```
