### ISSUE TITLE
Editor stops emitting blur on html view (tested in 1.2.7, 1.2.8)

### ISSUE THREAD

**Issue by biesiad** [froala/wysiwyg-editor#1023]
I'm not sure if you still support 1.2. If yes, there's this issue our users run into. Thanks for any help.

After I switch views to html, to wysiwyg, and back to html, the editor no longer emits `editable.blur` on html view.

`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36`

![froala_blur](https://cloud.githubusercontent.com/assets/513622/12363838/d8dc05a0-bb7f-11e5-8966-f2d625c6d026.gif)

**Comment by stefanneculai** [comment]
We have stopped support for V1 and we're no longer maintaining it.
