### ISSUE TITLE
Loading Image Stuck when using image.inserted event

### ISSUE THREAD

**Issue by viniciusmr3** [froala/wysiwyg-editor#1024]
The "Image Loading" pop up is stuck after implementing image.inserted event and manipulate the $img object.

This is what I'm trying to do:
```
.on('froalaEditor.image.inserted', function (e, editor, $img, response) {
    $img.parent().replaceWith('<div>' + $img[0].outerHTML + '<p>Insert caption here</p></div>');
});
```

**Comment by stefanneculai** [comment]
That's because you're removing the element from the DOM and the image would never finish to load. You could either use the `image.loaded` event instead, or wrap the image DOM object without replacing it.

**Comment by viniciusmr3** [comment]
Thanks for the support!
It's working perfectly now!
