### ISSUE TITLE
Nested list is wrapped in block tag when formatting parent item

### ISSUE THREAD

**Issue by mwtorkowski** [froala/wysiwyg-editor#1027]
Gif says it all

![froala-list-item-convert-bug](https://cloud.githubusercontent.com/assets/6072390/12478841/a46b2ee2-c037-11e5-8e69-500a2aa1f304.gif)

**Comment by stefanneculai** [comment]
I can confirm it, however that appears to happen only when the cursor is just before the nested list.

**Comment by mwtorkowski** [comment]
Any rough timeline for resolving this? We're holding with releasing to production until this one is taken care of.
