### ISSUE TITLE
New lines (br tag) gets removed from pre block

### ISSUE THREAD

**Issue by intellisense** [froala/wysiwyg-editor#1028]
When active paragraph format is code (pre block) add a new line in by pressing `shift+enter` click on code view the `br` gets removed. Similar thing happens when form is being submitted.

*Input:*
```
<pre>Testing the code block.<br>Ok?</pre>
```

*Output:*
```
<pre>Testing the code block.Ok?</pre>
```

*Expected Output:*
```
<pre>Testing the code block.<br>Ok?</pre>
```

**Comment by stefanneculai** [comment]
Actually, the expected output is:
`<pre>Testing the code block.\nOk?</pre>`
