### ISSUE TITLE
Documentation is wrong for htmlAllowedEmptyTags

### ISSUE THREAD

**Issue by intellisense** [froala/wysiwyg-editor#1031]
The documentation says that the default array for `htmlAllowedEmptyTags` is:
```
['textarea', 'a', 'iframe', 'object', 'video', 'style', 'script']
```
While it actually is (addition of `.fa`):
```
['textarea', 'a', 'iframe', 'object', 'video', 'style', 'script', '.fa']
```

**Comment by stefanneculai** [comment]
This was added in development only so far and that's why it is not updated on our website yet.
