### ISSUE TITLE
Unregister 'froala-editor' in Bower

### ISSUE THREAD

**Issue by Panman8201** [froala/wysiwyg-editor#1033]
I'm not sure you have ownership of the `froala-editor` package in Bower, but if you do I'd recommend [unregistering it](http://bower.io/docs/creating-packages/#unregister) or re-register to point to the current repo/version (currently distributing version 1.2.8). It caught me off-guard before realizing this is _actually_  in Bower as `froala-wysiwyg-editor`.

**Comment by stefanneculai** [comment]
That package was not created by us. We have emailed the author and asked him to unregister it.
