### ISSUE TITLE
Posibility to upload images to the server by link

### ISSUE THREAD

**Issue by kotmatpockuh** [froala/wysiwyg-editor#1034]
Please add a possibility to upload images via link to the server: http://i.imgur.com/utPpuzA.png like method with fileBrowser do.

**Comment by stefanneculai** [comment]
We use this repo for bug tracking only and we do not accept feature requests here. I put it on our feature list and if there will be further request for it, then we'll implement it.

**Comment by kotmatpockuh** [comment]
Sorry, any news about this feature request?

**Comment by stefanneculai** [comment]
We do not guarantee that feature requests will be implemented. It is on our list but has a very low priority and probably won't be implemented very soon.
