### ISSUE TITLE
image.min.js ImageDefaultWidth parameter = 0 -> style="width:auto" ?

### ISSUE THREAD

**Issue by VaShu** [froala/wysiwyg-editor#1035]
We support a system for our clients that works on Symfony2 and uses KMSFroalaEditorBundle. After updating Froala editor to the latest version (2.0.5) we are struggling with image default size. In the image.min.js there is a ImageDefaultWidth parameter that has 300px by default. When we change it from 300 to ‘0’ nothing happens. So we would like to know if there is a chance to set up 100% width parameter for the images.

**Comment by stefanneculai** [comment]
Setting `imageDefaultWidth` to `0` will not add any width to the image. We have just checked and it is no problem from the editor.

**Comment by VaShu** [comment]
The main question is how to set up a style=“width:auto” for any uploaded image by default? We need to upload images in its original size.

**Comment by stefanneculai** [comment]
The best way is to do that with CSS:
```CSS
.fr-view img {
  width: auto;
}
```

**Comment by mahalakshmisomasundaram** [comment]
File upload does not happen while pasting from the clipboard...how to resolve this??can someone help :)
