### ISSUE TITLE
Custom HTML Functionality

### ISSUE THREAD

**Issue by existence17** [froala/wysiwyg-editor#1037]
I would like to create a dropdown button, with 4 options for different column options.
I have created the dropdown and the functionality (check the code under)

```
$.FroalaEditor.DefineIcon('columns', {NAME: 'columns'});
$.FroalaEditor.RegisterCommand('columns', {
	title: 'Columns',
	type: 'dropdown',
	focus: true,
	undo: false,
	refreshAfterCallback: true,
	options: {
		'opt1': '1/2 + 1/2',
		'opt2': '2/3 + 1/3',
		'opt3': '1/3 + 2/3',
		'opt4': '1/3 + 1/3 + 1/3'
	},
	callback: function (cmd, val) {
	
		var output = '';
		output += '<div class="row">';
		
		switch (val) {
			case 'opt1':
				output += '<div class="col-md-6">Col1</div><div class="col-md-6">Col2</div>';
				break;
			case 'opt2':
				output += '<div class="col-md-8">Col1</div><div class="col-md-4">Col2</div>';
				break;
			case 'opt3':
				output += '<div class="col-md-4">Col1</div><div class="col-md-8">Col2</div>';
				break;
			case 'opt4':
				output += '<div class="col-md-4">Col1</div><div class="col-md-4">Col2</div><div class="col-md-4">Col3</div>';
				break;
			default:
				output += '<div class="col-md-12"></div>';
		}
		
		output += '</div>';
		this.html.insert(output);
		
	},
	refresh: function ($btn) {},
	refreshOnShow: function ($btn, $dropdown) {}
});
```
The code works fine but if i want to add an element inside one column, it adds the element wrong(e.g. if i wanna add a list inside one of the columns it will add the `<div class="col-md-6"></div>`  inside the list rather then the list inside the div). I also have the same issue if i would like to add new paragraphs (by pressing ENTER). It adds the paragraph wrong, inside the `<div class="row"></div>`

I was trying to find some documentation for how i can create elements like this, but i couldnt.
Is it possible to create something like this? Can you help me? Or can you guide me where i should look for my answers?

**Comment by stefanneculai** [comment]
You should use the class `fr-inner`. See: https://github.com/froala/wysiwyg-editor/blob/master/html/boostrap/content.html#L49.
