### ISSUE TITLE
Editor doesn't understand relative links

### ISSUE THREAD

**Issue by akhasanov** [froala/wysiwyg-editor#1038]
[![IMAGE ALT TEXT](http://img.youtube.com/vi/zMho-KyV4PQ/0.jpg)](http://www.youtube.com/watch?v=zMho-KyV4PQ "Froala Relative Links bug")

**Comment by stefanneculai** [comment]
See https://www.froala.com/wysiwyg-editor/docs/options#linkAutoPrefix.
