### ISSUE TITLE
Paragraph tags adds to script tag

### ISSUE THREAD

**Issue by akhasanov** [froala/wysiwyg-editor#1039]
[![IMAGE ALT TEXT](http://img.youtube.com/vi/g8EElAzNwnE/0.jpg)](http://www.youtube.com/watch?v=g8EElAzNwnE "Froala bug")

**Comment by stefanneculai** [comment]
With what options are you initializing the editor? Also, are you using the master version?

**Comment by akhasanov** [comment]
I'm using following options:

> height: $editor.data("height") || 250,
> theme: 'gray',
> direction: 'ltr',
> fileMaxSize: 1024 * 1024 * 3,
> placeholderText: '',
> linkAutoPrefix: '',
> 
> toolbarButtons: [ 'bold', 'italic', 'underline', 'strikeThrough', '|',
> 	'fontFamily', 'fontSize', 'color', '|',  
> 	'paragraphFormat', 'align', 'formatOL', 'formatUL', 'outdent', 'indent', 'quote', 'insertHR', '-', 
> 	'insertLink', 'insertImage', 'insertVideo', 'insertTable', 'undo', 'redo', 'clearFormatting', '|', 
> 	'html', 'fullscreen' ],
> 	
> toolbarButtonsMD: ['fullscreen', 'bold', 'italic', 'underline', 'fontFamily', 'fontSize', 'color', 'paragraphStyle', 'paragraphFormat', 'align', 'formatOL', 'formatUL', 'outdent', 'indent', 'quote', 'insertHR', 'insertLink', 'insertImage', 'insertVideo', 'insertFile', 'insertTable', 'undo', 'redo', 'clearFormatting', 'html'],
> 
> toolbarButtonsSM: 	['fullscreen', 'bold', 'italic', 'underline', 'fontFamily', 'fontSize', 'insertLink', 'insertImage', 'insertTable', 'undo', 'redo', 'html'],
> 
> toolbarButtonsXS: ['bold', 'italic', 'fontFamily', 'fontSize', 'undo', 'redo', 'html'],
> 
> htmlRemoveTags: [],
> enter: $.FroalaEditor.ENTER_P,
> 
> fontFamily: {
> 	'Arial,Helvetica,sans-serif': 'Arial',
> 	'Georgia,serif': 'Georgia',
> 	'Impact,Charcoal,sans-serif': 'Impact',
> 	'Tahoma,Geneva,sans-serif': 'Tahoma',
> 	"'Times New Roman',Times,serif": 'Times New Roman',
> 	'Verdana,Geneva,sans-serif': 'Verdana',
> 	'Comic Sans MS': 'Comic Sans',
> },
> fontFamilySelection: false,
> 
> htmlAllowedEmptyTags: [ 'textarea', 'a', 'iframe', 'object', 'video', 'style', 'script', 'div' ],
> 
> linkAttributes: { title: 'Title' },
> linkEditButtons: ['linkOpen', 'linkEdit', 'linkRemove'],
> linkInsertButtons: ['linkBack'],
> 
> imageDefaultWidth: 0,
> imageEditButtons: [ 'imageReplace', 'imageAlign', 'imageRemove', '|', 
> 	'imageLink', 'linkOpen', 'linkEdit', 'linkRemove', '|', 
> 	'imageDisplay', 'imageAlt', 'imageSize' ],
> 
> imageUploadParam: 'file',
> imageUploadURL: '/admin/api/files/upload',
> imageUploadParams: { uploader: 'editor' },
> imageManagerDeleteURL: '/admin/api/files/delete',
> imageManagerLoadURL: '/admin/api/files/images.json'

**Comment by akhasanov** [comment]
Btw, I'm using 2.0.6 version.
