### ISSUE TITLE
Ios scrolling editor content when keyboard is open

### ISSUE THREAD

**Issue by sahotataran** [froala/wysiwyg-editor#1043]
in my implementation i am using angular froala.
my issue is scrolling the editor when editor is focussed and  the keyboard is open.
if the editor is not focussed i am able to scroll the content inside but once i focus into the editor and try to swipe to scroll nothing happens.
i have specified height to the editor as well.

**Comment by b3na** [comment]
I am using it on Ionic Framework, I had no luck with version 1 of Froala and I was not aware that angular-froala was already on version 2 so I'm using the normal jquery froala.

I have had a lot of problems to make the editor work well on iOS, I don't know what are you working on, but what worked for me was:

- disable the scrolling of the keyboard (on cordova you can do this, don't know about your project)
- disable the scrolling on the view that is containing the editor, 
- specific height that is smaller than 100%, so you depend only on the editor's own scroll.

That worked for me after a lot of different configurations, if you tell me more about your project maybe we can help you out.

**Comment by stefanneculai** [comment]
@sahotataran We just tried this and cannot reproduce it, everything appears to work just fine on a pristine editor instance. Are you able to reproduce it on our website?
