### ISSUE TITLE
Japanese typing problem in the IOS

### ISSUE THREAD

**Issue by largeden** [froala/wysiwyg-editor#1044]
phone : iphone IOS
froala : Latest Commit (Past versions problem are the same.)
langauge : japanese only

When there is a blank toolbarButtons in a paragraph there is a problem with the first letters entered.

https://www.dropbox.com/s/54olorykjf92wuo/japanese_typing.mov?dl=0&preview=japanese_typing.mov
https://jsfiddle.net/largeden/0z62nhhx/

### The following is a method to reproduce.

![img_3166](https://cloud.githubusercontent.com/assets/5575931/12754525/edc75102-ca0e-11e5-904f-fe87f0763dcd.jpg)

### 3. input the key below.
kana mode: あ + か
Romaji mode: a + ka
(I think that both are the same cause.)

**Comment by stefanneculai** [comment]
What do you mean by _click on the blank toolbar buttons_?

**Comment by largeden** [comment]
@stefanneculai 

This presentation was not enough.

Click on the toolbar button (bold or italic) with a blank paragraph state.
If you enter the Japanese in the state, the problem occurs.

**Comment by stefanneculai** [comment]
Thanks. We'll check it.

**Comment by largeden** [comment]
@stefanneculai 

I confirmed that the issue appearing in past versions(v2.0.0 (no rc ver)). 
This problem has occurred is the same in the Chrome browser. (Also Korean, Japanese also occurred.)

but, The issue has already been resolved in the latest version. #904 
I think that this is a hint to solve the problem...

**Comment by stefanneculai** [comment]
Thanks for all the details. We'll try to fix it during this week.

**Comment by stefanneculai** [comment]
@largeden could you please check with the latest commit if it is fixed? It looks good to me now, but it's always better to get it double checked for Korean/Japanese issues.

**Comment by largeden** [comment]
Great! It has been resolved.

**Comment by stefanneculai** [comment]
@largeden Thanks.
