### ISSUE TITLE
Uncaught TypeError: Cannot use 'in' operator to search for 'media' in undefined

### ISSUE THREAD

**Issue by capir** [froala/wysiwyg-editor#1046]
i think the object in case is `css_beautify.NESTED_AT_RULE` that is null and throws this exception

**Comment by stefanneculai** [comment]
Could you please provide the steps to replicate the issue? Thanks.

**Comment by capir** [comment]
sure,

1. take [this instance](https://www.froala.com/wysiwyg-editor/docs/examples/full-page)

2. don't remove the `style` tag
   ```js
   $('div#froala-editor').data('froala.editor').opts.htmlRemoveTags = ['script']
   ```
3.  paste in the html from the #962 

and that should throw you the exception.
