### ISSUE TITLE
saveMethod: 'PATCH' sending 'POST' request 

### ISSUE THREAD

**Issue by rtcoms** [froala/wysiwyg-editor#1047]
We are in process of updating froala editor version to 2.1.0 from 1.2.8.

I am using following options for saving froala content .
    
    saveURL: element.data("froala-save-url"), element.data("froala-field-name")
    saveMethod: "PATCH"
    saveParams:
         field_name: element.data("froala-field-name")

Even after setting method type to 'PATCH' , froala still sends a 'POST' request to server . '

P.S. - Version 1 didn't have this issue and was updating content successfully.

**Comment by stefanneculai** [comment]
We have just checked and changing saveMethod to `PATCH` works correctly. Most probably there is something else not related to the editor.

<img width="399" alt="screen shot 2016-02-05 at 13 12 35" src="https://cloud.githubusercontent.com/assets/637004/12844774/30ecb394-cc0a-11e5-810a-2bb990b5fe35.png">
