### ISSUE TITLE
Syntax highlight and line numbers in code view

### ISSUE THREAD

**Issue by anudeepjusanu** [froala/wysiwyg-editor#1048]
Hi Is there any possibility for adding syntax highlight with line numbers for code view. I am planning to buy the commercial version but found that this feature doesn't exist. Do you have any plans to have this feature.

Thanks,
Anudeep

**Comment by stefanneculai** [comment]
We already have that. Isn't that what you're looking for?

<img width="1180" alt="screen shot 2016-02-05 at 18 37 29" src="https://cloud.githubusercontent.com/assets/637004/12852421/8ec42a7e-cc37-11e5-8d92-f6707f729714.png">
