### ISSUE TITLE
Insert Into New Block Method?

### ISSUE THREAD

**Issue by Zetal911** [froala/wysiwyg-editor#1049]
I've just started trying out Froala. Is there any way with the current framework to insert images into new blocks when they're inserted?

ie instead of: 
`<p>
Content of Test Post 1
<img src="http://i.froala.com/download/04bd9cb2ec86423be155753d2e13926f6c8d05a8.jpg?1454694908" style="width: 300px;" class="fr-dib">
</p>`

You would get:
`<p>Content of Test Post 1</p><p><img src="http://i.froala.com/download/04bd9cb2ec86423be155753d2e13926f6c8d05a8.jpg?1454694908" style="width: 300px;" class="fr-dib"></p>`

**Comment by stefanneculai** [comment]
We're currently working on such a feature. :-)
