### ISSUE TITLE
Clicking into FE field with inline editor on iPad adds 42px height fr-sticky-dummy div

### ISSUE THREAD

**Issue by rjsmith** [froala/wysiwyg-editor#1051]
If you click into a FE 2.1.0  field on iPad Air 2 (tested on Safari and Chrome, iOS 9.2.1) that has an inline toolbar, FE adds an additional  div with a height of 42px. 

![image](https://cloud.githubusercontent.com/assets/678653/12866098/09652b44-ccb9-11e5-8073-fc5b41762745.png)

This causes the field contents to be pushed down by 42px. When the user leaves the field, the sticky dummy element is removed, and the gap is closed up again. Note that this element is not added to the field contents; it is just rendered whilst the inline editor is displayed.

This can be reproduced on the FE examples, eg. here: https://www.froala.com/wysiwyg-editor/docs/examples/inline

Note also that the inline toolbar is rendered floating at the top of the visible page, not 'inline' within the bounds of the FE field, I guess that is intended?

**Comment by stefanneculai** [comment]
That is the desired behaviour. Without that `DIV` it wouldn't be possible to edit content when the editor is empty. 

Also, the toolbar was designed to appear at the top instead of floating next to the text on mobile devices.

**Comment by rjsmith** [comment]
OK, I see.
fyi in case anyone else comes across this issue, I have added code in my wrapper to remove this element within a FE on focus event handler. All of my FE fields have a placeholder text, which makes the fr-sticky-dummy div redundant, and annoying for my application's users.
