### ISSUE TITLE
Disable New Line Within Editor

### ISSUE THREAD

**Issue by Zetal911** [froala/wysiwyg-editor#1052]
Hey! Still trying out the Froala editor, really digging how customizable it is. I haven't yet been able to find any way to control the what the user can actually put into the field. Am I just missing something obvious?

Thanks!

**Comment by stefanneculai** [comment]
If you're looking to prevent multiple lines, then there is an option for that: https://www.froala.com/wysiwyg-editor/docs/options#multiLine.

**Comment by Zetal911** [comment]
Well that was silly. I even remember looking at that option and thinking "this will be perfect when I need to disable the newline stuff!" Whoops.

**Comment by gmacherey** [comment]
Hi all,

We just noticed that with multiLine option set to false, when pasting html into the editor, the pasted content has new lines if html has blocks. Would it be possible to not add newline while pasting if multilineset to false ?

Bests

**Comment by stefanneculai** [comment]
@gmacherey thanks for the suggestion. I added it to our feature-list.

**Comment by RLeDEV** [comment]
Hi there,
Is there any change according to @guillaumemach's request?
