### ISSUE TITLE
IE 11 Tables

### ISSUE THREAD

**Issue by rblin081** [froala/wysiwyg-editor#1054]
When editor is empty ( no content), add a table. User is not able to click out of table cell. User is also not able to click at end of table and press enter to go to new line.

**Comment by stefanneculai** [comment]
For such cases, there is the line breaker tool: https://www.froala.com/wysiwyg-editor/docs/examples/line-breaker

**Comment by gevgeny** [comment]
@stefanneculai But simple enter new line before/after table does work in other browsers.
