### ISSUE TITLE
Quick Insert Plugin Insert Table Not Inserting Table

### ISSUE THREAD

**Issue by Zetal911** [froala/wysiwyg-editor#1056]
When I click the "Insert table" button in the QuickInsert popup, no table is created. Image insertion works, however.

`//= require plugins/file.min.js
//= require plugins/image.min.js
//= require plugins/image_manager.min.js
//= require plugins/video.min.js
//= require plugins/link.min.js
//= require plugins/lists.min.js
//= require plugins/quote.min.js
//= require plugins/save.min.js
//= require plugins/table.min.js
//= require plugins/url.min.js
//= require plugins/quick_insert.min.js
//= require plugins/line_breaker.min.js`

These are the plugins I'm using.

**Comment by stefanneculai** [comment]
Unfortunately, we cannot replicate it. Please make a jsFiddle.

**Comment by Zetal911** [comment]
It was a personal configuration error. Can ignore.
