### ISSUE TITLE
"Method save.save does not exist in Froala Editor"

### ISSUE THREAD

**Issue by Zetal911** [froala/wysiwyg-editor#1057]
https://www.froala.com/wysiwyg-editor/docs/concepts/save-button 

I tried to follow this concept to a tee, but when clicking the button, I receive the error:

`Method save.save does not exist in Froala Editor`

Which seems odd. Also, sorry for spamming so many questions. If there is a better place for them, please let me know so I can use that. On the bright side, my org will pretty much definitely be purchasing Froala, so good news there. :)

**Comment by stefanneculai** [comment]
You're not including the save plugin most probably.

**Comment by Zetal911** [comment]
`//= require plugins/save.min.js`
I have this included, so save.min.js is being used. The file is also included in the `head` of the webpage when I inspect it.

**Comment by stefanneculai** [comment]
It's for sure a bad plugin inclusion. We offer tech support as part of the Advanced/OEM licenses. If you have one, please contact us via our website. Thank you.

**Comment by Zetal911** [comment]
It was a personal configuration error. Can ignore.
