### ISSUE TITLE
Image.insert

### ISSUE THREAD

**Issue by rblin081** [froala/wysiwyg-editor#1058]
Should have option to call image.insert with an inline flag otherwise image always inserts into the middle of the editor. This placement is not where the cursor is and could potentially disrupt content

**Comment by stefanneculai** [comment]
Could you please let us know the steps to reproduce the issue?

**Comment by rblin081** [comment]
v 2.0.6

$element.froalaEditor('image.insert', src , true);	inside an on click event for another element

**Comment by stefanneculai** [comment]
Is it reproducible on the master version?

**Comment by rblin081** [comment]
Didn't realize there was a image default display option, can close this
