### ISSUE TITLE
html.insert doesn't work

### ISSUE THREAD

**Issue by inexuscore** [froala/wysiwyg-editor#1059]
I've been using Froala for over a year now and everything was working fine. Until I updated the library (CSS, JS etc.). The API is changed so I had to refactor my project. I'm having trouble with a custom button of mine which opens up a modal dialog, accepts a code snippet (through a textarea) and inserts it at the selection in the editor.

Consider this:
```
var code = $("textarea#code").val();
$("#editor").froalaEditor("html.insert", code, true);
```

This works fine, but only if the editor is empty. If I enter some text and try to insert a code block I'll get a *TypeError: c is undefined*. What's the issue here? I googled around for a couple of minutes but couldn't find anything useful.

P.S If anyone knows how to insert code blocks properly (preserving new lines and everything) please provide a JSFiddle or something.

**Comment by stefanneculai** [comment]
Please make a jsFiddle for it.

**Comment by inexuscore** [comment]
@stefanneculai I'm making a Fiddle, I'll put the link here when its done.

**Comment by stefanneculai** [comment]
Closing this due to lack of response. We'll reopen it if there are enough details.
