### ISSUE TITLE
Re-sizing Image via CSS Class (image.applyStyle)

### ISSUE THREAD

**Issue by Zetal911** [froala/wysiwyg-editor#1060]
For flexibility reasons, I've been pursuing image resizing via setting their CSS `class` using the `image.applyStyle()` method, allow pre-set sizes. (Small, Medium, Large) Resizing works perfectly in the editor, but the CSS class doesn't seem to be converted to a style like the others. At first glance, `fr-image-resizer fr-active` seems to be associated with this issue, as it exists within the editor and updates when the image `class` is changed, but outside of the editor it seems that the `imageStyle` classes are meant to be converted into a lengthy `style` section containing the CSS modifications made in all of the classes, while the classes are stored in a temporary data field for later editing. 

This is all well and good, but the issue remains that width/height changes made using a `class` don't seem to be converted to a `style`. Hopefully I understand the situation sufficiently well, and am not just confused and making a silly mistake again.

Example CSS:
`
.small {
  width: 100px;
  height: 100px;
}
`

Example Code:
```
        this.image.get().removeClass("large medium");
        this.image.applyStyle('small');
```

**Comment by stefanneculai** [comment]
Have you disabled the `useClasses` option?

**Comment by Zetal911** [comment]
Yes. Enabling it solves my immediate issue, but it still seems a bit strange that things like the default image styles `bordered` and `rounded` work with `useClasses: false`, but not with other CSS classes.

**Comment by stefanneculai** [comment]
To get them work correctly, you should put the small, medium, large classes in a selector like this:
```css
.fr-view img.small {
}

.fr-view img.medium {
}

.fr-view img.large {
}
```
