### ISSUE TITLE
Attempting to call html.set "null" throws a Uncaught Type Error

### ISSUE THREAD

**Issue by rjsmith** [froala/wysiwyg-editor#1061]
Steps to reproduce:
1. Go to https://www.froala.com/wysiwyg-editor/docs/examples/full-featured
2. Open browser console and type: `$("div#froala-editor").froalaEditor("html.set", null)`

Console reports this error:

```
Uncaught TypeError: Cannot read property 'replace' of null(…)g @ application-2ff210532846b489e805d70c980ed4df.js:6C @ application-2ff210532846b489e805d70c980ed4df.js:7(anonymous function) @ application-2ff210532846b489e805d70c980ed4df.js:5at.extend.each @ application-2ff210532846b489e805d70c980ed4df.js:1at.fn.at.each @ application-2ff210532846b489e805d70c980ed4df.js:1e.fn.froalaEditor @ application-2ff210532846b489e805d70c980ed4df.js:5(anonymous function) @ VM526:2InjectedScript._evaluateOn @ VM524:875InjectedScript._evaluateAndWrap @ VM524:808InjectedScript.evaluate @ VM524:664
```

As a workround in froala-reactive wrapper, this seems to work:

`$("div#froala-editor").froalaEditor("html.set", someContent || "")`

**Comment by stefanneculai** [comment]
html.set expects a string as parameter, not null. It's not an issue.

**Comment by rjsmith** [comment]
Thanks for the clarification. I'll push a fix to froala-reactive.
