### ISSUE TITLE
Pasting from Word without any special formatting inserts double spaces in links in Chrome

### ISSUE THREAD

**Issue by manigandham** [froala/wysiwyg-editor#1062]
Here's a sample sentence:

> Harley was [introducing Project LiveWire](http://www.theverge.com/2014/6/19/5823818/harley-davidson-electric-motorcycle-project-livewire-tour), its first electric motorcycle, and it had brought over a dozen of them to its Manhattan store for a limited preview of the bikes before they go on tour around the US for the rest of the year, beginning today.

1. Copy this text into MS Word
1. Remove all formatting using the **Clear All Formatting** button in Word
1. Copy/paste into Froala editor
1. The link will have two spaces between "introducing" and "Project".

![image](https://cloud.githubusercontent.com/assets/457226/13026437/86e9dad8-d1dc-11e5-9d4f-85002066ee6a.png)

Tested on Chrome 47/48 on Windows 10 and Mac OSX El Capitan

**Comment by stefanneculai** [comment]
Could you please send us the Word document you're copying from? Thanks.

**Comment by manigandham** [comment]
Here is a Word document without any formatting and containing 2 links. When copy/pasting the entire text, both links have extra spaces.

[sample.docx](https://github.com/froala/wysiwyg-editor/files/129405/sample.docx)

**Comment by stefanneculai** [comment]
We just checked it and works fine on the master version. Probably, this issue was resolved sometime after the V2.1.0 release.
