### ISSUE TITLE
image and video resize outline in iframe

### ISSUE THREAD

**Issue by tonipepperoni** [froala/wysiwyg-editor#1065]
Think there's an issue when you click an image or a video and you have the typical video or image options popup, but then you perform a scroll, and the outline remains even though image/video is not visible.

**Comment by stefanneculai** [comment]
We cannot reproduce it. Could you please make a recording and check you're using the master version?

**Comment by tonipepperoni** [comment]
yes, i think it's also because i have set a pre-defined height also.

**Comment by tonipepperoni** [comment]
will get you a screen dump and a fiddle soon

**Comment by stefanneculai** [comment]
I am closing this because we cannot reproduce it. We'll reopen it if we get enough details.

**Comment by tonipepperoni** [comment]
Hey there, trying to get a codepen/fiddle for you. 

I think where I'm having issues is when I have a fullscreen editor, which does a html.set()

It only happens when there is a html.set() otherwise it works fine
