### ISSUE TITLE
Uncaught ReferenceError: acorn is not defined

### ISSUE THREAD

**Issue by Narzerus** [froala/wysiwyg-editor#1066]
I'm getting this error when adding a `script` tag into the editor in code view.

I have code mirror enabled. Tried adding acorn as a dependency but got a different error, any ideas on why this could be happening?

**Comment by stefanneculai** [comment]
Most probably the script you're trying to add is using `acron` which is not defined. It's not an editor issue.

**Comment by Narzerus** [comment]
@stefanneculai No... I'm adding the following:

```
<script>alert('hello');</script>
```
