### ISSUE TITLE
htmlAllowedAttrs option to remove attributes from existing content

### ISSUE THREAD

**Issue by timovanderzanden** [froala/wysiwyg-editor#1067]
In our current project we have imported content from a different platform, but no all content is clean. This primarily means `<span>` tags with style attributes and `<img>` tags with style attributes. 

We don't want to continue supporting these style tags. So I have removed `style` from the `htmlAllowedAttrs` option, hoping this would also get rid of any existing style attributes in the editor. However, this doesn't happen. This results in classes not working properly in the editor, because they are overruled. I would expect unallowed tags and attributes to be removed.

Is this currently impossible or have I missed a different way to achieve this result?

**Comment by stefanneculai** [comment]
Could you send us such an example to test it? Also, please make sure you're using the Github master.

**Comment by timovanderzanden** [comment]
It appears the latest version (including plugins?) fixes my issues!
