### ISSUE TITLE
Table html keeping blue highlight

### ISSUE THREAD

**Issue by rblin081** [froala/wysiwyg-editor#1068]
v2.1.1
When iframe : true
select a table cell so it has blue outline and then call html.get(false,false). Output html will have the blue outline on that cell. This is not an issue when iframe: false.

**Comment by stefanneculai** [comment]
I just tried it with the master version and I cannot reproduce it. If you could make a jsFiddle for it, then we can look over it.

**Comment by stefanneculai** [comment]
I managed to replicate it locally with `useClasses: true` option, therefore I'm reopening this.
