### ISSUE TITLE
Toolbar's tooltip shows below editor with iframe option

### ISSUE THREAD

**Issue by sz-tamas** [froala/wysiwyg-editor#1069]
When iframe is on and hovering a button on toolbar then the button's tooltip is shown below the editor. This bug also appears in the iframe example too: https://www.froala.com/wysiwyg-editor/docs/examples/iframe.

Tested on Chrome Version 47.0.2526.106 (64-bit), Linux

**Comment by stefanneculai** [comment]
It's fixed on Github master.
