### ISSUE TITLE
Block styles: adding a class to an image

### ISSUE THREAD

**Issue by lebart** [froala/wysiwyg-editor#107]
Hi, 

Block styles are really useful, it's easier for lazy developer like me to add some class for custom functionalities! But actually we can't target an image. We can target the paragraph where the image is but not directly the image.

Targeting the image can be great for lightbox option for instance.

We could easily do something like:

  $('.editor').editable({
    inlineMode: false,
    blockStyles: {
        'p': {
          'class1': 'Class 1',
          'class2': 'Class 2'
        },
        'h1': {
          'class3': 'Class 3',
          'class4': 'Class 4'
        },
        'img': {
            'lightbox': 'Add the lightbox effect on images',
        }
    },
});

Again, thanks for your support!

**Comment by lebart** [comment]
Hello 

I think that the version 1.2.5 give all those possibilities! 

Thanks a lot, version 1.2.5 is a great one, I appreciate your work more and more after each update!

**Comment by stefanneculai** [comment]
Yes, version 1.2.5 is a step forward for this. We don't have any official example for that, but it is possible.

**Comment by lebart** [comment]
Actually in the docs, you have an exemple about the custom image button, and your code is clear enough to find out quickly how to do this! 

One question, in this version is this possible to make a custom dropdown with custom image button? Like the new fa-star dropdown you added for inline or break text?

**Comment by stefanneculai** [comment]
We'll make a special option shortly for customImageDropdown so that dropdowns can be easily added for image, like customDropdowns.

**Comment by lebart** [comment]
Great!
