### ISSUE TITLE
Header background is not shown correctly when useClasses is disabled

### ISSUE THREAD

**Issue by rblin081** [froala/wysiwyg-editor#1070]
Create a table and it won't have any borders. 

https://jsfiddle.net/82uvp9kf/1/

v2..1.1 tested on Chrome

**Comment by stefanneculai** [comment]
When using `iframe: true` you should load all the CSS files from the same domain where the editor is. That's why the borders won't appear on jsFiddle.

**Comment by rblin081** [comment]
I'm pulling directly from you master branch, can you send me a fiddle that
is properly setup then ?

**Comment by stefanneculai** [comment]
Sure: https://jsfiddle.net/82uvp9kf/1/. It should load the CSS from the same domain and the only way to do that on jsFiddle is to paste it in the CSS panel. Getting the HTML does not keep the blue border for me, is it for you?

**Comment by rblin081** [comment]
You sent me the original fiddle. It's not keeping the blue border with the
latest, but table headers aren't keeping their background colors in our
application so I wanted to test on jsFiddle to reproduce.

**Comment by stefanneculai** [comment]
Sorry, probably I forgot to hit Update: https://jsfiddle.net/f87p3s65/. Anyway, if you are tying to reproduce it for #1068 it's no longer necessary because we reproduced that problem.

**Comment by rblin081** [comment]
No I'm having another problem with table header backgrounds. It can be
reproduced on the same fiddle where the background style is only being put
into fr-original-style and the actual style

Here's the output code

<table style="width: 100%; border: 0px; border-collapse: collapse;
empty-cells: show; max-width: 100%;" fr-original-style="width:
100%;"><thead><tr style="-webkit-user-select: none;"><th
*style="-webkit-user-select:
text; border: 1px solid rgb(221, 221, 221); background: rgb(230, 230,
230);"* *fr-original-style="background-color: rgb(61, 142,
185);"*><br></th></tr></thead><tbody><tr
style="-webkit-user-select: none;"><td style="width: 100%;
-webkit-user-select: text; border: 1px solid rgb(221, 221, 221);"
fr-original-style="width: 100.0000%;"><br></td></tr></tbody></table>

**Comment by stefanneculai** [comment]
I don't understand exactly what should I do to see the issue. Could you please let me know the steps to replicate the problem and explain which exactly is the problem? Thanks.

**Comment by rblin081** [comment]
Create a table and then add a header. Click on a header cell and add a cell
background. Click "Get HTML" button. For that cell in the outputted html
the style doesnt have the background-color, only the background set to
grey. The correct color is only represented in the fr-original-style attr
and not the style itself.

<th style="-webkit-user-select: text; border: 1px solid rgb(221, 221, 221);*
background: rgb(230, 230, 230)*;" fr-original-style="*background-color:
rgb(61, 142, 185)*;"><br></th>
