### ISSUE TITLE
Editor occasionally combines tags that are siblings to each other when using "Code View"

### ISSUE THREAD

**Issue by brendenpalmer** [froala/wysiwyg-editor#1073]
Seems to be an issue that occurs some of the time depending upon the structure of the HTML within "Code View". For example, pasting the following into the editor, then toggling back to WYSIWYG mode, then back to "Code View", you'll notice that the HTML structure is different than what was originally pasted in:

```
<div>
	<div>
		<div>
			<ul>
				<li>Test</li>
			</ul>
			
			<ul>
				<li>Test</li>
			</ul>
		</div>
	</div>
</div>
```

However, pasting the following code, then performing the same sequence of actions described above works as expected:

```
<div>
	<div>
		<div>
			<ul>
				<li>Test</li>
			</ul>

			<ul class="test">
				<li>Test</li>
			</ul>
		</div>
	</div>
</div>
```

In doing some initial debugging it looks to be an issue with the call to ```clean.lists()```:

![image](https://cloud.githubusercontent.com/assets/2276050/13088762/7134c8ce-d4a2-11e5-98c7-8098476c72e7.png)

**Comment by stefanneculai** [comment]
The editor is designed to join sibling lists that have the same attributes. If you want a different behaviour then you should modify the JS of the editor directly.
