### ISSUE TITLE
toolbarButtons[MD,SM,XS] not displaying on window resize

### ISSUE THREAD

**Issue by aemmons** [froala/wysiwyg-editor#1077]
This seems to have broken in v2.0.4 release. It is working fine in v2.0.3.

The toolbarButtons are not displaying when resizing window for MD, SM, XS settings. The do not display even when using defaults (not setting any toolbarButton* options).

Inspecting the DOM, it seems that the  fr-visible-xs, fr-visible-sm, and fr-visible-md CSS classes are not getting set on the <button> tool elements. If I manually alter the button class to add them, the toolbar item displays correctly.

//button element generated in v2.0.4 and above (broken):
<button type="button" tabindex="-1" class="fr-command fr-btn" data-cmd="bold"><i class="fa fa-bold"></i></button>

//button element generated in v2.0.3 (working)
<button type="button" tabindex="-1" class="fr-command fr-btn fr-visible-xs fr-visible-sm fr-visible-md fr-selected" data-cmd="bold"><i class="fa fa-bold"></i></button>

Here are my current options when initializing the Froala editor (but, as I said, even not setting toobarButtons has same result):

`{
              heightMin: 350,
              imageDefaultWidth: 750,
              imageEditButtons: ['imageAlign', 'imageRemove', '|', 'imageLink',
                  'linkOpen', 'linkEdit', 'linkRemove', '-', 'imageDisplay',
                  'imageStyle', 'imageAlt'],
              imagePaste: false,
              linkAlwaysBlank: true,
              linkAlwaysNoFollow: false,
              placeholderText: "Content",
              saveInterval: 0,
              tabSpaces: 4,
              paragraphFormat: {
                N: 'Normal',
                H1: 'Heading 1',
                H2: 'Heading 2',
                H3: 'Heading 3',
                H4: 'Heading 4'
              },
              paragraphStyles: {
                'caption-text': 'Image Caption'
              },
              toolbarButtons: ['fullscreen', 'bold', 'italic', 'underline',
                    'superscript', 'paragraphStyle', '|', 'paragraphFormat',
                    'align', 'formatOL', 'formatUL', 'insertLink', 'insertImage',
                    'insertVideo', '|', 'quote',
                    'insertHR', 'undo', 'redo', 'clearFormatting'],
              toolbarButtonsMD: ['fullscreen', 'bold', 'italic', 'underline',
                    'superscript', 'paragraphStyle',  '|',
                    'paragraphFormat', 'align', 'formatOL', 'formatUL',
                    'insertLink', 'insertImage', 'insertVideo', '|', 'quote', 'insertHR', 'undo',
                    'redo', 'clearFormatting'],
              toolbarButtonsSM: ['fullscreen', 'bold', 'italic', 'underline',
                    'superscript', 'paragraphStyle',  '|', 'paragraphFormat',
                    'align', 'formatOL', 'formatUL', 'insertLink',
                    'insertImage', 'insertVideo', '|', 'quote',
                    'insertHR', 'undo', 'redo', 'clearFormatting'],
              toolbarButtonsXS: ['bold', 'italic', 'underline', 'superscript',
                    'paragraphStyle',  '|', 'paragraphFormat', 'align',
                    'formatOL', 'formatUL', 'insertLink', 'insertImage',
                    'insertVideo', '|', 'quote', 'insertHR',
                    'undo', 'redo', 'clearFormatting'],
              toolbarSticky: true,
              toolbarStickyOffset: 50,
              htmlAllowedTags: ['script', 'a', 'abbr', 'address', 'area',
                    'article', 'aside', 'audio', 'b', 'base', 'bdi', 'bdo',
                    'blockquote', 'br', 'button', 'canvas', 'caption', 'cite',
                    'code', 'col', 'colgroup', 'datalist', 'dd', 'del',
                    'details', 'dfn', 'dialog', 'div', 'dl', 'dt', 'em',
                    'embed', 'fieldset', 'figcaption', 'figure', 'footer',
                    'form', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'header',
                    'hgroup', 'hr', 'i', 'iframe', 'img', 'input', 'ins',
                    'kbd', 'keygen', 'label', 'legend', 'li', 'link', 'main',
                    'map', 'mark', 'menu', 'menuitem', 'meter', 'nav',
                    'noscript', 'object', 'ol', 'optgroup', 'option', 'output',
                    'p', 'param', 'pre', 'progress', 'queue', 'rp', 'rt',
                    'ruby', 's', 'samp', 'script', 'style', 'section', 'select',
                    'small', 'source', 'span', 'strike', 'strong', 'sub',
                    'summary', 'sup', 'table', 'tbody', 'td', 'textarea',
                    'tfoot', 'th', 'thead', 'time', 'title', 'tr', 'track',
                    'u', 'ul', 'var', 'video', 'wbr'],
              htmlRemoveTags: ['style', 'base']
            }`

This have been testing in:
   Firefox 43.0.4
   Chrome 48.0.2564.109
   Safari 9.0.3

**Comment by stefanneculai** [comment]
You should also update the CSS for the editor, not only the JS files. :smile:

**Comment by aemmons** [comment]
FACE->PALM

damn build scripts. Thanks for the lightning fast reply.
