### ISSUE TITLE
Problem inserting complex html with html.insert method

### ISSUE THREAD

**Issue by markz440** [froala/wysiwyg-editor#1078]
We are developing a custom "Media insert" plugin for Froala and are having problems executing the **_html.insert_** method with a HTML string that has nested elements. We have no problem inserting `<img src="/path/to/image" />`, it however fails when trying to insert `<div><img src="/path/to/image" /></div>`. Any hints how we could resolve this issue?

**Comment by stefanneculai** [comment]
If the HTML you want to insert contains block elements (`'p', 'div', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'pre', 'blockquote', 'ul', 'ol', 'li', 'table', 'td', 'th', 'thead', 'tfoot', 'tbody', 'tr', 'hr', 'dl', 'dt', 'dd', 'form'`) then the editor will split the current tag. Instead you could use a `span` as a replacement for `div`.

**Comment by markz440** [comment]
I can use <span>, but a block level element surrounding an image would be more suitable. No workarounds?

**Comment by stefanneculai** [comment]
Unfortunately, that is not possible.
