### ISSUE TITLE
Custom Plugin _init not Running

### ISSUE THREAD

**Issue by Zetal911** [froala/wysiwyg-editor#1079]
I placed the custom plugin file (pulled from the Custom Plugin concept page in the documentation) in my javascripts/plugins folder. The file is run, as I have placed debug messages outside of the _init method and they work, but debug messages in the _init method do not run.

"THIS IS DEFINITELY RUNNING" gets printed, but "LOADED" does not.

Thanks!

```
$(function() {
  console.log ("THIS IS DEFINITELY RUNNING")
  // Add an option for your plugin.
  $.FroalaEditor.DEFAULTS = $.extend($.FroalaEditor.DEFAULTS, {
    myOption: false
  });

  // Define the plugin.
  // The editor parameter is the current instance.
  $.FroalaEditor.PLUGINS.fileManager = function (editor) {

    // The start point for your plugin.
    function _init () {
      console.log ("LOADED THE FILE MANAGER")
      alert("LOADED");
    }

    // Expose public methods. If _init is not public then the plugin won't be initialized.
    // Public method can be accessed through the editor API:
    // $('.selector').froalaEditor('myPlugin.publicMethod');
    return {
      _init: _init
    }
  }
});
```

**Comment by stefanneculai** [comment]
Are you using the option https://www.froala.com/wysiwyg-editor/docs/options#pluginsEnabled?

**Comment by Zetal911** [comment]
I have two editor instances on the page. One uses pluginsEnabled to disable all plugins except 'Save' via:
    `pluginsEnabled: ['save'],`
But the other leaves pluginsEnabled at the default, which according to the documentation should enable all plugins, correct? Thanks again, I appreciate all the help :)

**Comment by stefanneculai** [comment]
Could you make a jsFiddle?

**Comment by Zetal911** [comment]
Well it worked in the jsFiddle, and the only difference in my files and the jsFiddle was that I had my plugin in a separate .js file from the rest of my froala code. I moved my custom plugin over to the .js file with the rest of the code in it, and now _init is being called. Strange, and rather unfortunate since at this point my .js file is starting to get pretty crowded!
