### ISSUE TITLE
<br> getting added after evert <td>

### ISSUE THREAD

**Issue by swapnil002** [froala/wysiwyg-editor#1081]
Hi,

It seems a `<br>` gets added after every `<td>` tag. Can you help me out?

**Comment by stefanneculai** [comment]
Could you please provide few more details? Thank you.

**Comment by stefanneculai** [comment]
@swapnil002 I am closing this due to lack of response. If you can provide more details for us to reproduce it then we will reopen it. Thank you.

**Comment by swapnil002** [comment]
Hey, Not able to reproduce myself. Thanks for your reply.
