### ISSUE TITLE
Uncaught TypeError: Failed to execute 'scroll' on 'Window': 2 arguments required, but only 0 present.

### ISSUE THREAD

**Issue by farrrr** [froala/wysiwyg-editor#1082]
jQuery: v2.2.0
froala: v2.1.0

![screen shot 2016-02-22 at 10 50 02 am](https://cloud.githubusercontent.com/assets/1716558/13208312/7359ee0e-d952-11e5-8075-fecf85533802.png)

**Comment by stefanneculai** [comment]
When is that happening? Thank you.

**Comment by farrrr** [comment]
when use full-screen function.

**Comment by stefanneculai** [comment]
Are you experiencing this on [our website](https://www.froala.com/wysiwyg-editor)? What should we do after going to the fullscreen mode?

**Comment by stefanneculai** [comment]
@farrrr could you please let me know if you experience this on our website as well? Thank you.

**Comment by stefanneculai** [comment]
I am closing this due to lack of response.
