### ISSUE TITLE
tooltip issue in case of iframe= true - urgent

### ISSUE THREAD

**Issue by projectsphonegapdev1** [froala/wysiwyg-editor#1083]
Hello,

We have found a strange issue in case of iframe=true it's showing up button tool-tip in wrong place 

![issue](https://cloud.githubusercontent.com/assets/8512746/13249180/cb9c572c-da48-11e5-9223-88adb8e5a0e4.png)

**Comment by stefanneculai** [comment]
It's already fixed on the Github master. Will be included in the next release.

**Comment by projectsphonegapdev1** [comment]
so what should i merge in my code to resolve it.

**Comment by stefanneculai** [comment]
You should use the Github master JS and CSS.
