### ISSUE TITLE
Option to open URL plugin links with a blank target

### ISSUE THREAD

**Issue by jordancrawfordnz** [froala/wysiwyg-editor#1087]
The https://www.froala.com/wysiwyg-editor/docs/options#linkAlwaysBlank option is great when someone manually adds a link.

Could an option be added for the ``js/plugins/url.min.js`` plugin so the link created by this plugin will use the target blank option too?
This is super helpful as we don't want users heading away from our app when they click a link.

**Comment by stefanneculai** [comment]
We don't accept feature requests here, but I put it on our TODO list. Thank you.
