### ISSUE TITLE
strange issues in froala editor - Urgent

### ISSUE THREAD

**Issue by projectsphonegapdev1** [froala/wysiwyg-editor#1088]
Hi,

We have integrated froala in one of our application and facing some strange issue.

1. At a time toolbox got stuck in the top of view in place of sticking with the editor
![froala editor](https://cloud.githubusercontent.com/assets/8512746/13315473/e3dd0852-dbd0-11e5-8d40-b7ff32791c26.png)

2. At a time scroller not working properly, please refer URL for the same.(mostly comes on mac)
http://screencast.com/t/V79xPGcQBv

Have updated code from the master branch 
we are using following configurations for three different type of editor:
`
    var Basic = {
        toolbarButtons: ['html', '|', 'bold', 'italic', 'underline', '|', 'align', '|', 'fontFamily', 'fontSize', '|', 'color', '|', 'imageGallery', 'insertLinks'],
        toolbarButtonsSM: ['html', '|', 'bold', 'italic', 'underline', '|', 'align', '|', 'fontFamily', 'fontSize', '|', 'color', '|', 'imageGallery', 'insertLinks'],
        toolbarButtonsMD: ['html', '|', 'bold', 'italic', 'underline', '|', 'align', '|', 'fontFamily', 'fontSize', '|', 'color', '|', 'imageGallery', 'insertLinks'],
        toolbarButtonsXS: ['html', '|', 'bold', 'italic', 'underline', '|', 'align', '|', 'fontFamily', 'fontSize', '|', 'color', '|', 'imageGallery', 'insertLinks'],
        imageEditButtons: ['imageAlign', 'imageRemove', '|', 'imageLink', 'linkOpen', 'linkEdit', 'linkRemove', '-', 'imageDisplay', 'imageStyle', 'imageAlt', 'imageSize'],
        fontSize: ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '22', '24', '26', '28', '30', '32', '34', '36', '38', '40', '45', '50', '55', '60', '65', '70', '75', '80', '85', '90', '95', '100'],
        iframe: true,
        placeholderText: '',
        charCounterCount: false,
        imageMove: false
        height: 160
    };

    var Advanced = {
        toolbarButtons: ['html', 'undo', 'redo', 'clearFormatting', 'selectAll', '|', 'imageGallery', 'insertVideo', 'insertTable', 'insertLinks', '|', 'bold', 'italic', 'underline', '|', 'strikeThrough', 'subscript', 'superscript', '|', 'color', '|', 'formatOL', 'formatUL', 'outdent', 'indent', 'quote', '|', 'align', '|', 'fontFamily', 'fontSize', '|', 'emoticons', 'inlineStyle', 'paragraphStyle', '|', 'paragraphFormat', 'insertHR'],
        toolbarButtonsSM: ['html', 'undo', 'redo', 'clearFormatting', 'selectAll', '|', 'imageGallery', 'insertVideo', 'insertTable', 'insertLinks', '|', 'bold', 'italic', 'underline', '|', 'strikeThrough', 'subscript', 'superscript', '|', 'color', '|', 'formatOL', 'formatUL', 'outdent', 'indent', 'quote', '|', 'align', '|', 'fontFamily', 'fontSize', '|', 'emoticons', 'inlineStyle', 'paragraphStyle', '|', 'paragraphFormat', 'insertHR'],
        toolbarButtonsMD: ['html', 'undo', 'redo', 'clearFormatting', 'selectAll', '|', 'imageGallery', 'insertVideo', 'insertTable', 'insertLinks', '|', 'bold', 'italic', 'underline', '|', 'strikeThrough', 'subscript', 'superscript', '|', 'color', '|', 'formatOL', 'formatUL', 'outdent', 'indent', 'quote', '|', 'align', '|', 'fontFamily', 'fontSize', '|', 'emoticons', 'inlineStyle', 'paragraphStyle', '|', 'paragraphFormat', 'insertHR'],
        toolbarButtonsXS: ['html', 'undo', 'redo', 'clearFormatting', 'selectAll', '|', 'imageGallery', 'insertVideo', 'insertTable', 'insertLinks', '|', 'bold', 'italic', 'underline', '|', 'strikeThrough', 'subscript', 'superscript', '|', 'color', '|', 'formatOL', 'formatUL', 'outdent', 'indent', 'quote', '|', 'align', '|', 'fontFamily', 'fontSize', '|', 'emoticons', 'inlineStyle', 'paragraphStyle', '|', 'paragraphFormat', 'insertHR'],
        imageEditButtons: ['imageAlign', 'imageRemove', '|', 'imageLink', 'linkOpen', 'linkEdit', 'linkRemove', '-', 'imageDisplay', 'imageStyle', 'imageAlt', 'imageSize'],
iframe: true,
        placeholderText: '',
        charCounterCount: false,
        imageMove: false
        height: 400
    };

    var AdvancedWithoutImage = {
        toolbarButtons: ['html', 'undo', 'redo', 'clearFormatting', 'selectAll', '|', 'insertVideo', 'insertTable', 'insertLinks', '|', 'bold', 'italic', 'underline', '|', 'strikeThrough', 'subscript', 'superscript', '|', 'color', '|', 'formatOL', 'formatUL', 'outdent', 'indent', 'quote', '|', 'align', '|', 'fontFamily', 'fontSize', '|', 'emoticons', 'inlineStyle', 'paragraphStyle', '|', 'paragraphFormat', 'insertHR'],
        toolbarButtonsSM: ['html', 'undo', 'redo', 'clearFormatting', 'selectAll', '|', 'insertVideo', 'insertTable', 'insertLinks', '|', 'bold', 'italic', 'underline', '|', 'strikeThrough', 'subscript', 'superscript', '|', 'color', '|', 'formatOL', 'formatUL', 'outdent', 'indent', 'quote', '|', 'align', '|', 'fontFamily', 'fontSize', '|', 'emoticons', 'inlineStyle', 'paragraphStyle', '|', 'paragraphFormat', 'insertHR'],
        toolbarButtonsMD: ['html', 'undo', 'redo', 'clearFormatting', 'selectAll', '|', 'insertVideo', 'insertTable', 'insertLinks', '|', 'bold', 'italic', 'underline', '|', 'strikeThrough', 'subscript', 'superscript', '|', 'color', '|', 'formatOL', 'formatUL', 'outdent', 'indent', 'quote', '|', 'align', '|', 'fontFamily', 'fontSize', '|', 'emoticons', 'inlineStyle', 'paragraphStyle', '|', 'paragraphFormat', 'insertHR'],
        toolbarButtonsXS: ['html', 'undo', 'redo', 'clearFormatting', 'selectAll', '|', 'insertVideo', 'insertTable', 'insertLinks', '|', 'bold', 'italic', 'underline', '|', 'strikeThrough', 'subscript', 'superscript', '|', 'color', '|', 'formatOL', 'formatUL', 'outdent', 'indent', 'quote', '|', 'align', '|', 'fontFamily', 'fontSize', '|', 'emoticons', 'inlineStyle', 'paragraphStyle', '|', 'paragraphFormat', 'insertHR'],
        imageEditButtons: ['imageAlign', 'imageRemove', '|', 'imageLink', 'linkOpen', 'linkEdit', 'linkRemove', '-', 'imageDisplay', 'imageStyle', 'imageAlt', 'imageSize'],
iframe: true,
        placeholderText: '',
        charCounterCount: false,
        imageMove: false
        height: 400
    };
`

**Comment by stefanneculai** [comment]
Most probably it is in conflict with something else from your app. We use this repo for bug tracking, not for tech support. If you have a license which includes support (Advanced or OEM) please [contact us via our website](https://www.froala.com/wysiwyg-editor/contact). Thank you.
