### ISSUE TITLE
Opening File/Video From Area Other than Toolbar Results in 'Cannot read property' Error

### ISSUE THREAD

**Issue by Zetal911** [froala/wysiwyg-editor#1090]
```
  $.extend($.FroalaEditor.DEFAULTS, {
    popupButtons: ['popupClose', '|', 'insertFile', 'popupButton2'],
  });
```

Clicking the 'insertFile' button (which appears in the list) gives the `Cannot read property 'left' of undefined` because, from what I can tell, $tb does not exist for it to reference, since the button isn't located on the toolbar, it's located on my plugins action bar. Likewise, this is the reason that adding buttons such as insertFile and insertVideo do not work on the quickInsert plugin- the same error is given. 

Essentially, this boils down to the File/Video plugins referencing $tb, preventing them from being used in anything other than the toolbar. A notable exception is the Link plugin, which, while giving a warning, still creates the popup (anchored to the topleft corner of the screen instead of near where the button was pressed).

Thanks for your time!

**Comment by stefanneculai** [comment]
The file/video plugins are designed to use the buttons inside the toolbar. If you want to place them in other containers, then you should modify them accordingly.
