### ISSUE TITLE
Calling a method doesn't always trigger commands.after

### ISSUE THREAD

**Issue by thekris1234** [froala/wysiwyg-editor#1091]
I'm currently implementing a few custom controls for our implementation of Froala.

I've noticed that the documentation says that commands.after should be fired after calling commands such as bold and align.apply.

The problem I've noticed is that when I call bold, commands.after is fired. But if I call:

jQuery('.myEditor').froalaEditor('lists.apply', 'ol'); \\ OR
jQuery('.myEditor').froalaEditor('align.apply', 'left')

commands.after isn't called.

Could it be something I'm doing wrong?

**Comment by stefanneculai** [comment]
Those events are being triggered only when the commands are being called (e.g. button click, shortcut), not when calling methods directly.
