### ISSUE TITLE
Froala wysiwyg editor not support XHTML

### ISSUE THREAD

**Issue by NTMan** [froala/wysiwyg-editor#1095]
Demonstration: http://froala.sy24.ru/

Error occurred inside jquery code when you try innerHTML this
`&amp;&lt;&gt;&quot;&apos;&iexcl;&cent;&pound;&curren;&yen;&brvbar;&sect;&uml;&copy;&ordf;&laquo;&not;&shy;&reg;&macr;&deg;&plusmn;&sup2;&sup3;&acute;&micro;&para;&middot;&cedil;&sup1;&ordm;&raquo;&frac14;&frac12;&frac34;&iquest;&Agrave;&Aacute;&Acirc;&Atilde;&Auml;&Aring;&AElig;&Ccedil;&Egrave;&Eacute;&Ecirc;&Euml;&Igrave;&Iacute;&Icirc;&Iuml;&ETH;&Ntilde;&Ograve;&Oacute;&Ocirc;&Otilde;&Ouml;&times;&Oslash;&Ugrave;&Uacute;&Ucirc;&Uuml;&Yacute;&THORN;&szlig;&agrave;&aacute;&acirc;&atilde;&auml;&aring;&aelig;&ccedil;&egrave;&eacute;&ecirc;&euml;&igrave;&iacute;&icirc;&iuml;&eth;&ntilde;&ograve;&oacute;&ocirc;&otilde;&ouml;&divide;&oslash;&ugrave;&uacute;&ucirc;&uuml;&yacute;&thorn;&yuml;&OElig;&oelig;&Scaron;&scaron;&Yuml;&fnof;&circ;&tilde;&Alpha;&Beta;&Gamma;&Delta;&Epsilon;&Zeta;&Eta;&Theta;&Iota;&Kappa;&Lambda;&Mu;&Nu;&Xi;&Omicron;&Pi;&Rho;&Sigma;&Tau;&Upsilon;&Phi;&Chi;&Psi;&Omega;&alpha;&beta;&gamma;&delta;&epsilon;&zeta;&eta;&theta;&iota;&kappa;&lambda;&mu;&nu;&xi;&omicron;&pi;&rho;&sigmaf;&sigma;&tau;&upsilon;&phi;&chi;&psi;&omega;&thetasym;&upsih;&piv;&ensp;&emsp;&thinsp;&zwnj;&zwj;&lrm;&rlm;&ndash;&mdash;&lsquo;&rsquo;&sbquo;&ldquo;&rdquo;&bdquo;&dagger;&Dagger;&bull;&hellip;&permil;&prime;&Prime;&lsaquo;&rsaquo;&oline;&frasl;&euro;&image;&weierp;&real;&trade;&alefsym;&larr;&uarr;&rarr;&darr;&harr;&crarr;&lArr;&uArr;&rArr;&dArr;&hArr;&forall;&part;&exist;&empty;&nabla;&isin;&notin;&ni;&prod;&sum;&minus;&lowast;&radic;&prop;&infin;&ang;&and;&or;&cap;&cup;&int;&there4;&sim;&cong;&asymp;&ne;&equiv;&le;&ge;&sub;&sup;&nsub;&sube;&supe;&oplus;&otimes;&perp;&sdot;&lceil;&rceil;&lfloor;&rfloor;&lang;&rang;&loz;&spades;&clubs;&hearts;&diams;`

Because in XHTML not allowed HTML entity please use code instead https://dev.w3.org/html5/html-author/charref

For example `&nbsp;`  have valid `&#160;` code.

**Comment by stefanneculai** [comment]
No, the editor is not designed to support XTHML, but only HTML5.

**Comment by NTMan** [comment]
HTML5 does not mean inability layout into XML. If you see example used doctype is  `<!DOCTYPE html>`  The only difference in the file extension xhtml written instead of html  and the server sends header `Content-type: application/xhtml+xml; charset=utf-8` instead `Content-type: text/html; charset=utf-8`

**Comment by stefanneculai** [comment]
Thanks for the feedback, really appreciate it. However, it's not only that, but the editor output is not designed to be XHTML compatible. E.g.: the editor will output `<br>`, not `<br/>`. We have had request for XHTML before and if we're going to add it, then we'll make this change as well.

Anyway, if you want to use entity code instead, you could do that very handy by changing the [entities option](https://www.froala.com/wysiwyg-editor/docs/options#entities).

**Comment by NTMan** [comment]
Thanks, after disabling entities plugin error message which show in console before is gone, but editor still not working, pity.

**Comment by NTMan** [comment]
I would like to debug the code. Is it possible to get a version that does not suppressed errors. in the console everything is clean and the editor does not work.
