### ISSUE TITLE
imageStyles: class name with - in name breaks editor

### ISSUE THREAD

**Issue by connect-technologies** [froala/wysiwyg-editor#1097]
##### Actual behavior.
if the classname in the imageStyles has a "-" in it, the editor breaks loading.

##### Steps to reproduce the problem.
$('.selector').froalaEditor({
  imageStyles: {
    class-2: 'Class 2',
  }
});

##### OS version.
win7
##### Browser version.
latest FF

thanks

**Comment by stefanneculai** [comment]
You should initialize it like below. In JS when you use dash for properties they have to be wrapped with quotes.

```js
$('.selector').froalaEditor({
  imageStyles: {
    'class-2': 'Class 2',
  }
});
```

**Comment by connect-technologies** [comment]
yes. had no ' in it. thanks
