### ISSUE TITLE
How to set images to Base64

### ISSUE THREAD

**Issue by FrizzaUK** [froala/wysiwyg-editor#1100]
I am testing Froala version 2.2.1.  When I insert an image it automatically uploads the image to i.froala.com, however I would like the images to be Base64 and not uploaded.  There was an 'imageUpload' option on an older version so what do I need to do in order to get it working?

Thanks.

**Comment by stefanneculai** [comment]
If you want to store images as base64, then you could use the [image.beforeUploade](https://www.froala.com/wysiwyg-editor/docs/events#image.beforeUpload) event to prevent the default behaviour and insert image as base64. However, we do not recommend that because browsers tend to drop performance when using base64 images inside contenteditable.

**Comment by cybervanes** [comment]
FrizzaUK, did you ever get this figured out? if so can you share your solutions?

**Comment by FrizzaUK** [comment]
@cybervanes We ended up using the default behaviour which saves the image to disk rather than converting it to Base64.

**Comment by cybervanes** [comment]
Thanks for the reply!

**Comment by GlobeFuntion** [comment]
I'm use project Angular 2 and project Express JS. But I when I change options like this:
public options: Object = {
imageUploadURL: 'http://localhost:5000/post/image'
}
and my server side I have function from call POST/IMAGE:
saveImage: function (req, res) {
console.log('=======>>>>>')
FroalaEditor.Image.upload(req, '/uploads/', function (err, data) {
// Return data.
if (err) {
return res.send(JSON.stringify(err));
}
res.send(data);
console.log(data)
});
}
My problem is can't load image in Froala edtior normally but Image was added in server.

**Comment by FrizzaUK** [comment]
When you say you can't load the image, do you mean the image manager, here is an example config (client side):
```javascript
.froalaEditor({
	heightMax: 350,
	imageUploadURL: '/image/upload',
	imageUploadMethod: 'POST',
	imageUploadParam: 'upload_file',
	imageMaxSize: 1024 * 1024,
	fileUploadURL:  '/file/upload',
	fileUploadMethod: 'POST',
	fileUploadParam: 'upload_file',
	imageManagerLoadURL: '/image/list',
	imageManagerDeleteURL:  '/file/delete',
	linkAlwaysBlank: true,
	linkList
});
```

There is a separate route for the image manager which displays the thumbnails of previous uploaded files.

We return a json object with a link property to the location of the saved file:
`res.status(200).send({
			'link':  req.file.location
		});`
