### ISSUE TITLE
Restore function incorrect code order

### ISSUE THREAD

**Issue by rblin081** [froala/wysiwyg-editor#1102]
##### IE 11

**Comment by stefanneculai** [comment]
Has been fixed few hours ago.

**Comment by rblin081** [comment]
What's your policy about latest version of unminfied code for accounts ?

**Comment by stefanneculai** [comment]
We fixed this and then release V2.2.1. The unminified JS is available for the latest version official released (currently 2.2.1).

**Comment by rblin081** [comment]
So the fix is not in the official release ?

**Comment by stefanneculai** [comment]
It is included in V2.2.1 which we released today: https://www.froala.com/wysiwyg-editor/changelog.
