### ISSUE TITLE
Code for disabling right click has a typo

### ISSUE THREAD

**Issue by d3chapma** [froala/wysiwyg-editor#1105]
##### Expected behavior.
Froala should initialize without errors when disableRightClick is enabled

##### Actual behavior.

Uncaught TypeError: Cannot read property '$on' of undefined

##### Steps to reproduce the problem.
Initialize Froala editor with { disableRightClick: true } option

##### OS.
Mac OS El Capitan

##### Browser.
Chrome 48

**Comment by stefanneculai** [comment]
Already fixed by 54af264b8cba0070116c1940c98e8e0c44fe1192
