### ISSUE TITLE
Shame link to W3school instead W3C in documentation

### ISSUE THREAD

**Issue by masseuro** [froala/wysiwyg-editor#1106]
##### Expected behavior.
In the page https://www.froala.com/wysiwyg-editor/docs/options#entities there is a link to W3C have to go to W3C (https://dev.w3.org/html5/html-author/charref) or Wikipedia https://en.wikipedia.org/wiki/List_of_XML_and_HTML_character_entity_references than go to W3school. W3school isn't W3C they make a lot of confusion.
##### Actual behavior.
the link go to W3school （／_＼）

##### Steps to reproduce the problem.
Go here https://www.froala.com/wysiwyg-editor/docs/options#entities, click on the link **W3C**, cry a lot :(

##### OS.
any

##### Browser.
any

**Comment by stefanneculai** [comment]
Corrected. :+1:
