### ISSUE TITLE
Stripping out html entities

### ISSUE THREAD

**Issue by rblin081** [froala/wysiwyg-editor#1109]
##### Expected behavior.
Should allow entities as plain text when properly encoded

##### Actual behavior.
Strips out entity

##### Steps to reproduce the problem.
https://jsfiddle.net/f87p3s65/36/
Text is set as `"&lt;div&gt;&lt;/div&gt;"` but editor doesn't show any content

##### OS.
All

##### Browser.
All

**Comment by stefanneculai** [comment]
Inside textareas, entities should be escaped again: https://jsfiddle.net/rw85vbd8/.

**Comment by rblin081** [comment]
That code was generated by the WYSIWYG. The problem is entering <div></div>
generates &lt;div&gt;&lt;/div&gt;, and then when the page is saved and
reloaded with that value the WYSIWYG doesn't display anything

**Comment by stefanneculai** [comment]
Even though, it is necessary to escape them before putting in a textarea. You can read more about that here: https://github.com/froala/wysiwyg-editor/issues/482#issuecomment-83714915
