### ISSUE TITLE
Not work

### ISSUE THREAD

**Issue by atomoc** [froala/wysiwyg-editor#1110]
On mobile Chrome:
![2016-03-05 22 31 42](https://cloud.githubusercontent.com/assets/465108/13549919/35a906ce-e322-11e5-975d-2a4571361b77.png)

It does not work no element froala.

**Comment by stefanneculai** [comment]
Can you replicate this on our website?

**Comment by atomoc** [comment]
Yes

**Comment by atomoc** [comment]
[On this page](https://www.froala.com/wysiwyg-editor#inline-demo)

**Comment by atomoc** [comment]
@stefanneculai It does not work `toolbarInline`

**Comment by atomoc** [comment]
@stefanneculai Thank you so much!!! Indeed toolbarInline mode on the tablet with a keyboard on the entire screen is terrible.
