### ISSUE TITLE
Custom dropdown

### ISSUE THREAD

**Issue by atomoc** [froala/wysiwyg-editor#1111]
How can I achieve the same in the right format?
```
$.FroalaEditor.DefineIcon('my_dropdown', {NAME: 'list'});
$.FroalaEditor.RegisterCommand('my_dropdown', {
title: 'Advanced options',
type: 'dropdown',
focus: false,
undo: false,
refreshAfterCallback: true,
options: {
    'OL': '<i class=\'fa fa-list-ol\'></i>',
    'UL': '<i class=\'fa fa-list-ul\'></i>',
    'indent': '<button type=\'button\' tabindex=\'-1\' class=\'fr-command fr-btn\' data-cmd=\'indent\'><i class=\'fa fa-indent\'></i></button>',
    'outdent': '<button type=\'button\' tabindex=\'-1\' class=\'fr-command fr-btn\' data-cmd=\'outdent\'><i class=\'fa fa-outdent\'></i></button>'
},
callback: function (cmd, val) {
    if ( val == 'OL' || val == 'UL' )
        this.lists.format(val)

}
});
```

**Comment by atomoc** [comment]
https://www.froala.com/wysiwyg-editor/docs/examples/custom-popup

The answer is clear, but the execution is difficult. How can I make it easier?

**Comment by stefanneculai** [comment]
We use this repo for bug tracking only. If you have questions or need help integrating the editor please [contact us](froala.com/wysiwyg-editor/contact) instead of opening an issue.

**Comment by atomoc** [comment]
> We use this repo for bug tracking only. If you have questions or need help integrating the editor please contact us instead of opening an issue.
Ok!
