### ISSUE TITLE
korean letter input error

### ISSUE THREAD

**Issue by open2** [froala/wysiwyg-editor#1112]
##### Expected behavior.
i want to enter " 셨"
tuT (english keyboard)

##### Actual behavior
"ㅆ" was a long input.
셔ㅆ

##### Steps to reproduce the problem.
do korean keyboard (IME), press
tuT

##### OS.
windows 7

##### Browser.
IE 11 (latest)

##### froala version
2.2.1

**Comment by stefanneculai** [comment]
I just tried to reproduce this, but I couldn't. @open2 is this happening [our website](froala.com/wysiwyg-editor) as well?

**Comment by open2** [comment]
oops.
today it was not reproduced.


2016-03-08 0:55 GMT+09:00 Stefan Neculai <notifications@github.com>:

**Comment by open2** [comment]
Dear, I reproduce korean letter input error.

(test site 1)
login : test12 / test
http://www.opencode.co.kr/bbs/write.php?bo_table=qna

(test site 2)
login : test12 / test1212
http://www.2cpu.co.kr/bbs/write.php?bo_table=freeboard_2011

1. write " 한글 " (gksrmf)
2. upload image
3. write " 있어요 " (dlTdjdy)



2016-03-08 19:03 GMT+09:00 Stefan Neculai <notifications@github.com>:

**Comment by stefanneculai** [comment]
You're using an older version 2.0.4. Please upgrade to the latest one 2.2.1.

**Comment by open2** [comment]
Sorry.
uploaded 2.2.1.

please do again.

2016-03-11 19:01 GMT+09:00 Stefan Neculai <notifications@github.com>:

**Comment by stefanneculai** [comment]
@open2 unfortunately, we could not reproduce it. 

@largeden could you please take a look over it and let us know if you can reproduce it?

**Comment by open2** [comment]
if you can not reproduce isue,
you can login my system using teamviewer.




2016-03-11 19:50 GMT+09:00 Stefan Neculai <notifications@github.com>:

**Comment by open2** [comment]
do you test issue using IE 11?

one engineer told to me "it may be a bug of IE 11 - memory allocation
error".
In chrome no problem.

2016-03-11 21:00 GMT+09:00 Yunho Kang <echo4me@gmail.com>:

**Comment by stefanneculai** [comment]
Yes. Are you able to reproduce it on our website? Could you make a recording for it?

**Comment by open2** [comment]
I could not reproduce issue in froala.com.

See attached video.

2016-03-11 21:08 GMT+09:00 Stefan Neculai <notifications@github.com>:

**Comment by stefanneculai** [comment]
Could you let me know the options you're initializing the editor with? 

PS: There is not video attached.

**Comment by open2** [comment]
froala editor loading srcipt (two files are attached)

<? include("$g4[path]/froala/froala.lib.1.php")?>
<textarea id="wr_content" name="wr_content"
style='display:none;'><?=$content?></textarea>
<? include("$g4[path]/froala/froala.lib.2.php")?>


I attached avi file. if you can not download or get it, please download frm
this.
http://www.2cpu.co.kr/bbs/board.php?bo_table=PDS&wr_id=11312

after a imaged inserted you can see the issue (i did not use arrow keys)
when I press SPACE BAR key, problem was disappeared.



2016-03-11 21:29 GMT+09:00 Stefan Neculai <notifications@github.com>:

**Comment by stefanneculai** [comment]
I cannot download it from there. Could you please upload it somewhere with public access? 

Also, I would need only the options you're initializing with not the entire files. Thank you.

**Comment by open2** [comment]
I initialized froala options using frola.lib.2.php file.

    theme: 'gray',
    language: 'ko',     //
https://www.froala.com/wysiwyg-editor/docs/examples/language
    heightMin: 430,     //
https://www.froala.com/wysiwyg-editor/docs/examples/adjustable-height
    heightMax: 650,

    toolbarButtons :  ['fullscreen', 'bold', 'italic', 'underline',
'strikeThrough', 'subscript', 'superscript', 'fontFamily', 'fontSize',
'|', 'color', 'emoticons', 'inlineStyle', 'paragraphStyle', '|',
'paragraphFormat', 'align', 'formatOL', 'formatUL', 'outdent',
'indent', '-', 'quote', 'insertHR', 'insertLink', 'insertImage',
'insertVideo', 'insertTable', 'undo', 'redo', 'clearFormatting',
'selectAll', 'html'],
    toolbarButtonsMD: ['fullscreen', 'bold', 'italic', 'underline',
'strikeThrough', 'subscript', 'superscript', 'fontFamily', 'fontSize',
'|', 'color', 'emoticons', 'inlineStyle', 'paragraphStyle', '|',
'paragraphFormat', 'align', '-', 'formatOL', 'formatUL', 'outdent',
'indent', 'quote', 'insertHR', 'insertLink', 'insertImage',
'insertVideo', 'insertTable', 'undo', 'redo', 'clearFormatting',
'selectAll', 'html'],
    toolbarButtonsSM: ['fullscreen', 'bold', 'italic', 'underline',
'fontFamily', 'fontSize', 'color', 'emoticons', 'insertLink',
'insertImage', 'insertVideo', 'insertTable', 'clearFormatting',
'undo', 'redo'],
    toolbarButtonsXS: ['bold', 'italic', 'fontFamily', 'fontSize',
'insertLink', 'insertImage', 'insertVideo','clearFormatting', 'undo',
'redo'],

    // Set the image upload parameter.
    imageUploadParam: 'file',

    // Set the image upload URL.
    imageUploadURL: '<?=$g4[path]?>/froala/image_upload.php',

    // Additional upload params (bo_table ���� image_upload.php�� �ѱ��)
    imageUploadParams: {bo_table: '<?=$bo_table?>'},

    // Set request type.
    imageUploadMethod: 'POST',

    // Set max image size to 20MB.
    imageMaxSize: 20 * 1024 * 1024,

    // Allow to upload PNG and JPG. GIF
    imageAllowedTypes: ['jpeg', 'jpg', 'png', 'gif'],

    // image alignment
    imageDefaultAlign: 'left',

    // image width
    imageDefaultWidth: 0,

    // Set the file upload URL.
    fileUploadURL: '<?=$g4[path]?>/froala/file_upload.php',

    fileAllowedTypes: ['text/plain', 'application/pdf',
'application/x-pdf', 'application/msword',
'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
'application/vnd.openxmlformats-officedocument.presentationml.presentation',
'application/vnd.hancom.hwp', 'application/x-hwp',
'application/haansofthwp', 'application/vnd.ms-excel',
'application/vnd.ms-powerpoint'],

    fileMaxSize: 10* 1024 * 1024,

    fileUploadParams: {bo_table: '<?=$bo_table?>'}


http://www.opencode.co.kr/qna/4993
in this url, click ... bandicam_2016-03-11_21-25-27-998.avi (1.9M), Down :
0, 22:10



2016-03-11 21:47 GMT+09:00 Stefan Neculai <notifications@github.com>:

**Comment by stefanneculai** [comment]
None of the editor options you're using should affect typing. I cannot download the file from the link you sent - I get an alert message in Korean I assume.

If the issue is not replicable on our website, then probably there is some other JS on your page which breaks typing.

**Comment by largeden** [comment]
@open2 

http://www.opencode.co.kr/qna/4993

This account is can not download a file.
test12

![2016-03-11 22 51 57](https://cloud.githubusercontent.com/assets/5575931/13703833/f2b1a664-e7db-11e5-8152-914e3efb4841.png)

**Comment by open2** [comment]
after 2.2.0 this issue appeared.
So I rolled back to 2.1.4.

This issue appeared some smart phone like pantech vega2.

I use bootstrap, jquery, font-awesome, html5shiv, respond.
no special js with keyboard.

IE Edge on Windows 10 no problem.
Only for IE11 on windows 7 (latest)






2016-03-11 22:21 GMT+09:00 Stefan Neculai <notifications@github.com>:

**Comment by open2** [comment]
http://www.opencode.co.kr/css/262

you can download without signin.
I changed download priveledge.

2016-03-11 22:59 GMT+09:00 Ji-Yeon Choi <notifications@github.com>:
