### ISSUE TITLE
Unwanted Doctype

### ISSUE THREAD

**Issue by capir** [froala/wysiwyg-editor#1113]
How can i get rid off the Doctype?

##### Expected behavior.
If i paste a source without a doctype in fullPage it shouldn't add one for me

##### Actual behavior.
it adds `<!DOCTYPE html>` 

##### Steps to reproduce the problem.
1. [open editor](https://www.froala.com/wysiwyg-editor/docs/examples/full-page) 
2. paste the source
 ```html
 <html>
	<head>
		<title></title>
	</head>
	<body>test</body>
 </html>
 ```

3. open console and call `$('div#froala-editor').froalaEditor('html.get')`

it returns 
```html
<!DOCTYPE html><html><head> <title></title> </head><body><p>test</p></body></html>
```

**Comment by stefanneculai** [comment]
Currently, there is no option for that. We'll have to discuss to see if it actually makes sense to allow that or not.

**Comment by capir** [comment]
Hint: if you're using the editor for newsletter purposes. It kinda makes sense. 

Thanks

**Comment by stefanneculai** [comment]
> DOCTYPE Declaration is mandatory for most current markup languages and without one it is impossible to reliably validate a document. ([W3C Doctype Declaration](https://validator.w3.org/docs/help.html#faq-doctype))

When using the fullPage option, the editor is designed to edit an entire page. Also, the editor output is designed to be HTML valid so it doesn't make sense not to have DOCTYPE. Anyway, you could remove it using a RegEx in the HTML. Here is a JS on: `<!DOCTYPE ?([^ ]*) ?([^ ]*) ?"?([^"]*)"? ?"?([^"]*)"?>/i`
