### ISSUE TITLE
Inconsistent with refresh state button

### ISSUE THREAD

**Issue by blpcastanheira** [froala/wysiwyg-editor#1114]
##### Expected behavior.
The bold button needs to change the state to represent a selected text.

##### Actual behavior.
Sometimes the button state doesn't work correctly. Please, see the sample below.
![froala](https://cloud.githubusercontent.com/assets/4196666/13579539/da6b2862-e47c-11e5-9d16-49e4a2ea751b.gif)

##### Steps to reproduce the problem.
Select some text and hit bold button. After, select another text and go back to the bold text using a arrow keys and select them.

##### OS.
Windows 8.1

##### Browser.
Google Chrome 48.0.2564.116 m

**Comment by stefanneculai** [comment]
Nice catch. :+1:
