### ISSUE TITLE
Unordered List not showing bullets unless text is indented

### ISSUE THREAD

**Issue by gavinhorne** [froala/wysiwyg-editor#1116]
##### Expected behavior.
When applying an Unordered List I expect the selected text to be indented and bullets to appear for each line as per the ordered list

##### Actual behavior.
If the selected text is not indented then list mark-up is applied but the bullets do not appear

##### Steps to reproduce the problem.
Type some text in the editor, select the text and click the Unordered List toolbar button

To get the expected behaviour, select the text and click the Increase Indent toolbar button first, then the Unordered List toolbar button

##### OS.
Windows 10

##### Browser.
Chrome 48.0.2564.116 m

**Comment by stefanneculai** [comment]
Probably you have some CSS which is in conflict with the editor. Are you able to reproduce this on our website?

**Comment by gavinhorne** [comment]
Thanks Stefan, yes there was a conflict which I've now resolved.
