### ISSUE TITLE
Space character being added after nested <br>

### ISSUE THREAD

**Issue by rblin081** [froala/wysiwyg-editor#1117]
##### Expected behavior.

There should be no extra spacing
##### Actual behavior.

`&nbsp;` is being added after `<br>` in `<span>`
##### Steps to reproduce the problem.

https://jsfiddle.net/f87p3s65/38/
##### OS.

Windows
##### Browser.

Chrome

**Comment by rblin081** [comment]
Same thing with text after an image
https://jsfiddle.net/f87p3s65/43/

Is there an option to disable additional `&nbsp;` ?

**Comment by rblin081** [comment]
Same with spans nested in lists
https://jsfiddle.net/f87p3s65/44/

**Comment by stefanneculai** [comment]
We've just checked these 2 cases you reported. We don't consider them being an issue. The editor converts the space character to NBSP so that users can see changes when they actually edit something. We designed the editor to convert blank spaces when you initialize the editor, the same way it would work when you put a space in the editor. For example in the first case, if you have an image and press space after it, the editor will add a NBSP.

**Comment by aridlehoover** [comment]
Hi @stefanneculai.

I'm seeing the same behavior - even when there is no nesting - as long as there is a <br> tag followed by a carriage return. It appears that a &nbsp; is being appended after the carriage return.

Here's a fiddle: https://jsfiddle.net/aridlehoover/g92r66ru/

And, here's what I'm seeing in the editor: 

When I load this (perfectly valid) HTML into the editor:
```html
Text before BR tag looks fine. No leading space.
<br>
Text after a BR and a carriage return has a leading space. 
<br>Putting the text on the same line as the BR tag solves the issue.
<br>
It's like the non-breaking space is being appended right after the carriage return.
```

This is what the editor renders:
```html
Text before BR tag looks fine. No leading space.
<br>
&nbsp;Text after a BR and a carriage return has a leading space. 
<br>Putting the text on the same line as the BR tag solves the issue.
<br>
&nbsp;It's like the non-breaking space is being appended right after the carriage return.
```

I understand that the editor is trying to help me by saving inserting the &nbsp;. It's not helping. My users are actively complaining about this. I need a solution. I'd prefer an option to turn this behavior on/off.

**Comment by stefanneculai** [comment]
@aridlehoover indeed, it appears there is a problem. We'll fix it shortly.

**Comment by aridlehoover** [comment]
Hey @stefanneculai, just checking on status. Any idea when you'll publish the fix? A week? A month? A quarter? I won't hold you to it. But, I want to set expectations with my stakeholders. Thanks!

**Comment by karanjariwala** [comment]
we add this span tag to create variables. 
`<span class="fr-deletable variable-item-wrapper" contenteditable="false" id="businessLegalName-1-parent">&nbsp;<span class="variable-item" contenteditable="false" id="businessLegalName-1" name="businessLegalName">&nbsp;Business legal name&nbsp;</span>&nbsp;</span>`

&nbsp; is added to start and end of span tag

**Comment by YNDthn** [comment]
Hi, we are currently also having problems with inserted spaces (&nbsp;), exactly as @aridlehoover once described. The bug ticket has been closed for so long. Hence my question: Will this bug ever be fixed?
Kind regards
Stefan
