### ISSUE TITLE
Title is showing in display

### ISSUE THREAD

**Issue by rblin081** [froala/wysiwyg-editor#1118]
##### Expected behavior.
Title tag in head should not be displayed

##### Actual behavior.
Title tag is being displayed

##### Steps to reproduce the problem.
https://jsfiddle.net/f87p3s65/39/

##### OS.
Chrome

##### Browser.
Chrome

**Comment by stefanneculai** [comment]
You should use the fullPage option if you want that.

**Comment by rblin081** [comment]
If all of the rest of the <head> is being stripped out shouldn't the title as well ?

**Comment by stefanneculai** [comment]
No, that is the correct behaviour. You could add title to the htmlRemoveTags if you want it to be removed.
