### ISSUE TITLE
Toolbar in Inline Mode on iOS does not respond to touch

### ISSUE THREAD

**Issue by rjsmith** [froala/wysiwyg-editor#1119]
##### Expected behavior.
FE configured with inline toolbar should work on iOS / iPad browsers.  It definitely did work on a fairly recent release (2.1 at least?)

##### Actual behavior.
Inline toolbar buttons do not respond to touch.

##### Steps to reproduce the problem.
1. Open https://www.froala.com/wysiwyg-editor#inline-demo on iPad browser (I tried this with Safari and Chrome)
2. Click into the editor. 
3. Select some text in the editor. Inline toolbar appears at top of window.
4. Touch any of the toolbar buttons (e.g, Bold, paragraph style etc). Nothing happens.

##### OS.
IOS 9.2.1

##### Browser.

Safari, Chrome 48

**Comment by stefanneculai** [comment]
81e6a5686fb1caf588557f63bec3375a850f4511 is introducing back the toolbar inline next to the selection and fixes this issue as well. We had high request for this feature and many users were missing it after it was removed back in V2.0.0.
