### ISSUE TITLE
IE11 Korean, Japanese Typing Problem.

### ISSUE THREAD

**Issue by largeden** [froala/wysiwyg-editor#1120]
##### Expected behavior.
Select the block that contains the image.
Write Hangul and Japanese.

##### Actual behavior.
https://www.dropbox.com/s/36u0un4i5rmc9i4/typing4.mov?dl=0

##### Steps to reproduce the problem.
~~https://jsfiddle.net/largeden/0z62nhhx/2/~~
http://codepen.io/romanesque/pen/wGgEWP

Step1
Click on the image tag at the bottom
Backspace x 1

Step2
Please enter the following key.

pattern1(Enaglish) : abcd
pattern2(Korean) : rk + sk + ek + fk
pattern3(Japanes) : a + i + u + e + o

#Every running pattern should clear the "&nbsp".

##### OS.
Windows 7, Windows 10

##### Browser.
IE11 (firefox, chrome not problem)

--

Break text mode only occurs.
(display: block or table-row)

**Comment by largeden** [comment]
@stefanneculai 

This has not yet been resolved.

I tried to re-test the latest version.
https://www.dropbox.com/s/iml3dowqkognrx0/typing5.mov?dl=0

**Comment by stefanneculai** [comment]
Unfortunately we cannot do more than that. The issue with backspace is fixed, but can't do anything more because it appears that this the way IE IME is working when there is an image with display: block.

**Comment by largeden** [comment]
@stefanneculai 
Thanks for checking.

I have the same idea, this is akin to the problem of IE11.
(But, IME input problem is different from other editors...)

I reduced the IME problem by following the steps below.
```javascript
	$('#edit').on('froalaEditor.image.inserted', function (e, editor, $img, response) {
		if(editor.browser.msie == true) $img.parent().after('<p><br></p>');
	});
```
@open2 
#1112 
We can not improve any more problems.
