### ISSUE TITLE
Selected text is not replaced when inserting image

### ISSUE THREAD

**Issue by manttih** [froala/wysiwyg-editor#1121]
##### Expected behavior.
When i select text, and insert image via code, the selected text should be replaced with image

##### Actual behavior.
The selected text is not replaced

##### Steps to reproduce the problem.
http://demo.synergiafoxy.com/froala_selectionrestore.php . Select some text and click the folder-button. The selected text is not replaced

##### OS.
Windows 7.

##### Browser.
at least Firefox 45.0 and IE 11.0.9600.18230.

**Comment by stefanneculai** [comment]
We decided not to replace selected text anymore with the image, but collapse selection to start and insert image there.
