### ISSUE TITLE
image.insert in image.error method: wrong position

### ISSUE THREAD

**Issue by kotmatpockuh** [froala/wysiwyg-editor#1122]
##### Expected behavior.
In my app i'm using token and refresh token architecture. So: when token is invalid, i'm trying to renew this token and resend image to the server (this part work like a charm). And then in "image.error" callback i'm using **image.insert** method - all is ok, except one issue: every time this image is inserted to the beginning of my .Content model. In **v1.*** - all was ok, with the same logic image was inserted to the cursor position.

##### Actual behavior.
Image is inserted to the beginning all the time, not to the cursor position. If i use option **$existing_image** - image is replaced but class 'fr-error' is still there...

##### Steps to reproduce the problem.
Try to insert image via code.

##### OS.
Windows 7

##### Browser.
Chrome 48.0.2564.116 m

BTW: Would be great, if you implement image resend logic in your wysiwyg...

**Comment by stefanneculai** [comment]
This is not an editor issue, but a problem of how you're implementing it. For tech support, please [contact us](froala.com/wysiwyg-editor/contact) via our website if you own a license which includes support (Advanced/OEM).

Thank you.

**Comment by kotmatpockuh** [comment]
@stefanneculai  Problem of implementing? NO. Doc isn't saying anything about re-sending image.

_I like the way you are closing bugs..._

**Comment by stefanneculai** [comment]
No, it doesn't say anything about that, but that doesn't mean the images cannot be resend. It's a matter of how you're implementing it.

Please see below how we define a bug. In this case this is not considered a bug by us. Thanks for understanding.
> Bug shall mean a behavior in the Software's functionality that **we** do not consider intended;

**Comment by kotmatpockuh** [comment]
"it doesn't say anything about that"
"It's a matter of how you're implementing it."

Try to describe this in docs in the nearest feature, please. I think it's usable not only for me.

**Comment by stefanneculai** [comment]
Thanks for the feedback.
