### ISSUE TITLE
Link dialog no longer focuses on the URL field

### ISSUE THREAD

**Issue by euangoddard** [froala/wysiwyg-editor#1124]
##### Expected behavior.
When I trigger the insert/update link dialog either via the keyboard or by clicking on the appropriate button in the UI, the dialog is presented and focus is given to the first field in the dialog

##### Actual behavior.
No field in the dialog has focus

##### Steps to reproduce the problem.
Trigger the dialog in any of the supported ways

##### OS.
Firefox 45 for Windows 7
Chrome 49 Ubuntu 14.10 LTS

##### Browser.
Firefox 45 for Windows 7
Chrome 49 Ubuntu 14.10 LTS

##### Notes
This behaviour used to be present in version <2.0.5 but no longer seems to be there in 2.0.5 and 2.2.1

**Comment by stefanneculai** [comment]
Are you experiencing that on our website?

**Comment by euangoddard** [comment]
I checked this the other day when I raised the issue and it was the same behaviour, but now it appears to focus the URL field. I have quite a few of the default options for that dialog disabled so I wonder whether that makes a difference. The config is as follows:

`{
            allowComments: false,
            htmlAllowedAttrs: ['title', 'href', 'alt', 'src'],
            htmlAllowedTags: ['p', 'h1', 'h2', 'h3', 'a', 'br', 'ol', 'ul', 'li', 'strong', 'em', 'a'],
            paragraphFormat: {
                n: 'Normal',
                h1: 'Heading 1',
                h2: 'Heading 2'
            },
            toolbarButtons: TOOLBAR_BUTTONS,
            toolbarButtonsMD: TOOLBAR_BUTTONS,
            toolbarButtonsSM: TOOLBAR_BUTTONS,
            toolbarButtonsXS: [
                'paragraphFormat',
                'bold',
                'italic',
                'insertLink'
            ],
            charCounterCount: false,
            heightMin: 100,
            linkList: [],
            linkInsertButtons: [],
            linkEditButtons: ['linkOpen', 'linkEdit', 'linkRemove'],
            linkStyles: {},
            linkText: true,
            linkAlwaysBlank: true,
            toolbarInline: false,
            toolbarSticky: false,
            imagePaste: false,
            spellcheck: true,
            tabSpaces: false,
            key: FROALA_LICENCE_KEY
        }`

**Comment by stefanneculai** [comment]
None of the editor options should get in conflict with that.

**Comment by euangoddard** [comment]
I appreciate that it's hard for you to diagnose this if it can't be reproduced in any of your demos, but it is still broken for me. I'm using the downloaded (and paid for) package from your site without any modifications other than configuration so I think this is a genuine issue.

I'm happy to try to debug this myself if you can give me some pointers where I might need to look for when the focus is attempted on the URL field in the dialog and then I can at least discount any obvious issues.

**Comment by stefanneculai** [comment]
If you have a license that includes tech support (Advanced/OEM), please [contact us](froala.com/wysiwyg-editor/contact) via our website and we can definitely help you further.

**Comment by jamesmoss** [comment]
@euangoddard did you ever find a solution to this issue? I'm having the exact same problem.

**Comment by jamesmoss** [comment]
I did some more digging and found the issue if anybody has the same problem in the future. We have a custom theme that set `transition: 0.2s` on Froala's `<inputs />`. Removing this fixed the issue and the field autofocuses correctly now.
