### ISSUE TITLE
Spellcheck bug in IE 11

### ISSUE THREAD

**Issue by raerae13** [froala/wysiwyg-editor#1127]
I'm seeing an issue with spellcheck in the latest version of IE 11 (Windows 7 Pro). 

When the user right clicks on a misspelled word, a line break is created, and when the user selects a correctly spelled word from IE's right click menu, all of the content in the current line is replaced. I've set up my testing page exactly as seen in the Get Started section on froala.com.  

See video. 
[video spellcheck issue IE 11.zip](https://github.com/froala/wysiwyg-editor/files/174483/video.spellcheck.issue.IE.11.zip)

**Comment by stefanneculai** [comment]
Is that reproducible on our website?

**Comment by raerae13** [comment]
I was not able to repro on https://www.froala.com/wysiwyg-editor.

**Comment by raerae13** [comment]
It also behaves as expected on our site when using Chrome or Firefox.

**Comment by stefanneculai** [comment]
Most probably you're using an older version. Please use the latest one 2.2.1.
