### ISSUE TITLE
IE 11 video appears above menus for inserting image, video, document, etc.

### ISSUE THREAD

**Issue by raerae13** [froala/wysiwyg-editor#1128]
Toolbar flyout menus appear behind a linked or embedded video in Internet Explorer 11. This can be repro'ed on froala.com website editor examples. 

![image](https://cloud.githubusercontent.com/assets/13455017/13795372/a085e7f8-eabd-11e5-9fdd-fbf28701dd68.png)

**Comment by stefanneculai** [comment]
On which page can you reproduce it?

**Comment by raerae13** [comment]
https://www.froala.com/wysiwyg-editor

video example of behavior...
[video IE 11.zip](https://github.com/froala/wysiwyg-editor/files/176320/video.IE.11.zip)

I've tested in Chrome and Firefox, those are fine.

**Comment by stefanneculai** [comment]
Could you please clear your browser cache? We just tested it on IE11/Windows 8.1 and IE10/Windows 7 and couldn't replicate this.

**Comment by raerae13** [comment]
I cleared the browser cache and restarted the browser... still seeing the behavior here https://www.froala.com/wysiwyg-editor.

I'm on Windows 7 pro IE 11

**Comment by stefanneculai** [comment]
@raerae13 I just checked on Windows 7, IE 11 and I can confirm the issue. It appears that it is important to have exact this combination.

**Comment by stefanneculai** [comment]
Just tested this with a Virtual Machine from [Microsoft Developer](https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/mac/) and appears to work fine. I believe it is an isolated case with a very specific configuration.
