### ISSUE TITLE
Removing image width attribute

### ISSUE THREAD

**Issue by performatric** [froala/wysiwyg-editor#1129]
When I dynamically load a html content to editor, images have removed the width attribute.

I need it for Outlook newsletters.

Thanks!

**Comment by stefanneculai** [comment]
Last commit adds in the `imageOutputWidth` option which will output the width as attribute when enabled. By default it is disabled.

**Comment by escopecz** [comment]
@stefanneculai will the imageOutputWidth option find a way to the [docs](https://www.froala.com/wysiwyg-editor/docs/options) to get more info about it? In what Froala version is it available?

**Comment by chandon** [comment]
+1

**Comment by chandon** [comment]
@escopecz starting version 2.2.2

**Comment by escopecz** [comment]
@stefanneculai @chandon I'm using Froala 2.3.3 and if I search for `imageOutputWidth` in the whole (uncompressed) codebase of Froala, I get no results. Any example how to use it?

**Comment by stefanneculai** [comment]
`imageOutputWidth` was replaced by `imageOutputSize`. https://www.froala.com/wysiwyg-editor/docs/options#imageOutputSize
