### ISSUE TITLE
html mode does not save changes

### ISSUE THREAD

**Issue by rwaters71** [froala/wysiwyg-editor#113]
Editor does not let you save any changes when you submit the form in html mode:
1) changes are not being saved - it seems impossible to make any changes to urls or image tags and save the contents.

2) html code is being changed (wrapper elements and classes added for images and links, etc.).

(in my case a textarea, inline mode is disabled, "Show HTML" mode,  tested in both IE11 and Firefox 30)

**Comment by beyondcreed** [comment]
has this ever been fixed so you can actually save in HTML source view? I'd find it pretty odd you wouldn't let users do that. right now we have an ugly hack which basically switches editor to rendered view from source view and then saves when save button is hit. lot of times users need to directly customize HTML because editor will not recognize everything or not be able to deal with all the different situations so not letting them save that is extremely odd to me. textangular, summernote all let you do this.

**Comment by stefanneculai** [comment]
@beyondcreed I agree with you that switching to text view when saving is a bad UX. Last commit fixes that and it doesn't switch back to the text view on save. However, it will still do all the cleanup for consistency with the options the editor is initialized with (htmlAllowComments, htmlAllowedAttrs, htmlAllowedTags, etc.).

**Comment by shidhu40** [comment]
Editor automatically delete <form> tag in html mode

**Comment by stefanneculai** [comment]
If you're using the editor inside a `form` then it won't work to have another `form` tag inside the editor unless you use the `iframe: true` option.

**Comment by zvermike** [comment]
Same issue:
- when i'm trying to save something from code mode it doesn't save;
- in console i get next error: The given range isn't in document;
- check screencast: https://drive.google.com/file/d/1uRmh_kt_7o8D1s5UoT6Pdh9TsskPPzJz/view

**Comment by stefanneculai** [comment]
@zvermike Do you think it would be possible to make a jsFiddle to highlight the problem? That would speed-up things a lot. Here is a basic jsFiddle you could use as a starting point: https://jsfiddle.net/froala/wc5c3jhk/.

**Comment by EmanuelGenially** [comment]
Hello! I have same issue.

When i’m trying to save something from code mode, Froala doesn’t save it.

To save changes, I need to disable (close) code mode. This is not the behaviour I expected, I thought it will save also from code mode.

**Comment by silver-software** [comment]
How can I save the styles of images in Froala Editor?

**Comment by dchase-sir** [comment]
@stefanneculai isn't it better just to say it doesn't support it, than to say it makes no sense? In my case, the editor is seated in a modal dialog with an OK and Cancel button, and they edit HTML as part of their normal job.. So they switch to code-view, make their changes, click my "OK" button, then freak out when the changes aren't in their newsletter... Is there something I can trigger with my OK button?

**Comment by burtonrhodes** [comment]
If it helps anyone, I use the following code when a user clicks the "save" button in the form.

`    
prepareToSave() {
    if (froalaEditor.codeView && froalaEditor.codeView.isActive()) {
            froalaEditor.codeView.toggle();
    }
}
`
