### ISSUE TITLE
Losing cursor (unfocus) bug when delete custom html

### ISSUE THREAD

**Issue by myggul92** [froala/wysiwyg-editor#1130]
Hi,

https://jsfiddle.net/xLt305c3/

1. Init editor with custom html. ( or Insert html dynamic )
(no enter is at the beginning of the content of editor. only custom html)
2. Click editor.
3. Press Backspace.
4. Editor lose cursor! 
(Problem is User dont know this, 
and press backspace again to remove custom html
and browser is to go back to before page)

Above example, I add `<div><br></div>` at end of content to be possible to focus editor.
If no br tag is anywhere, No cursor, no focus in spite of clicking editor.
( https://jsfiddle.net/xLt305c3/1 )

**Comment by stefanneculai** [comment]
You could use the Line Breaker plugin `https://www.froala.com/wysiwyg-editor/docs/examples/line-breaker` and change the [lineBreakerTags](https://www.froala.com/wysiwyg-editor/docs/options#lineBreakerTags) option to include `quote` as well.

**Comment by myggul92** [comment]
@stefanneculai 
Thank you for answering. 
But I think it's still uncomfortable.

1. 
lineBreakerTags is only activated when mouse pointer is on the custom tag.
I think it's more natural to be on editing-mode with cursor when just click anywhere in editor zone.

2.
And lineBreakerTags resolve losing cursor problem.
But user can't remove custom tag.
Cursor is activating, but backspace is not working. (cannot remove custom tag!)

To remove the custom tag (included to lineBreakerTags),
1. Activate cursors above and below the custom tag.
2. Click below the custom tag.
3. cmd + shift (cursor block) + arrow up key  => and press backspce.

Check please.

**Comment by stefanneculai** [comment]
We're always looking forward to improve the editing experience, but that's all we can do in this direction for now. What we'd recommend instead is to make a custom button that would appear when you go with mouse over your non-editable content and remove it.
