### ISSUE TITLE
imageUpload

### ISSUE THREAD

**Issue by 440459012** [froala/wysiwyg-editor#1133]
##### want to parse response from the server.
from server i get response like this:
 file_name: name
 file_extension: extension

froala editor wait for response only like this:
 link: full/url/to/image.jpg

##### Steps to reproduce the problem.
can you add posibility for parsing the response, to change it..
like: {link : /full/url/reponse.file_name+response.file_extension}

##### OS.
MacOS

##### Browser.
Google Chrome

**Comment by stefanneculai** [comment]
We won't add such a feature, but you could use the [image.uploaded](https://www.froala.com/wysiwyg-editor/docs/events#image.uploaded) event to parse the response and then insert the image in the editor with image.insert method.

**Comment by 440459012** [comment]
thanks for reply, that's worked for me, but there is a problem , when i added a image through 'image.insert' there was added 2 images , one with opacity, like it's have a problem with upload, i think there anyway it's an error with parse my response

**Comment by stefanneculai** [comment]
We offer tech support via email under the Advanced/OEM license. If you have one, please contact us via our website. Thank you.

**Comment by cyrilepinat** [comment]
you can user image.get method to pass in image.insert as existing image
