### ISSUE TITLE
Froala + webpack

### ISSUE THREAD

**Issue by thedotedge** [froala/wysiwyg-editor#1134]
##### Expected behavior.
Possibility to use froala as CommonJS module.

##### Actual behavior.
```
ERROR in ./static/javascript/entry.js
Module not found: Error: Cannot resolve module 'froala-editor'
```

##### Steps to reproduce the problem.
```npm install froala-editor --save```

In ./static/javascript/entry.js:
```
require('froala-editor');
```

##### Environment

webpack 1.12.14

**Comment by stefanneculai** [comment]
See https://github.com/froala/wysiwyg-editor/tree/master/html/require_js for RequireJS. Using it with CommonJS is similar.

**Comment by Cydmi** [comment]
@thedotedge You're the solution.  cmd

**Comment by george-norris-salesforce** [comment]
That link no longer works. Is it possible to get a Webpack example?
