### ISSUE TITLE
Question: is it possible to make custom components?

### ISSUE THREAD

**Issue by rileylark** [froala/wysiwyg-editor#1137]
I'd like to make a plugin that allows the user to type math directly into the editor using mathquill (http://mathquill.com/). Does the editor give me the control I need to do this?

I have read all of the sections under https://www.froala.com/wysiwyg-editor/docs/concepts including "Custom Plugin" but I haven't seen how to affect the editor contents. Everything seems to be about the toolbar, and I don't yet understand how to make a command that would insert a custom widget into the editor.

Thanks for any help! We are considering text editors right now and would be looking to use the OEM version for our SaaS web app, with 1M+ users, but we need support for custom components like this.

**Comment by stefanneculai** [comment]
Definitely, you can find on our website a complete list of events and methods available in the editor:
https://www.froala.com/wysiwyg-editor/docs/methods
https://www.froala.com/wysiwyg-editor/docs/events

**Comment by Artenes** [comment]
Hello @rileylark, I am also looking for an editor that allows me to create and manage widgets inside of it. Did Froala solved your problemas or you have chosen another editor?

Thanks in advance.

**Comment by stefanneculai** [comment]
@Artenes for Math component, there are the guys from Wiris which made an integration http://www.wiris.com/plugins/demo/froala/php/. If you have any specific questions about achieving something, please don't hesitate to reach us via our website.

**Comment by Artenes** [comment]
Thanks for the answer @stefanneculai, I'd like to know if you have any in depth tutorial in how to make plugins for Froala, I need to know if what Froala provides to extends its functionality will be enough to the needs of my project. I saw the page that talks about plugins: https://www.froala.com/wysiwyg-editor/docs/concepts/custom/plugin, but from there I really don't know where to go.

**Comment by stefanneculai** [comment]
@Artenes Our support team can definitely offer more guidance. Please use the contact form from our website to provide more details: https://www.froala.com/wysiwyg-editor/contact. Thank you.
