### ISSUE TITLE
Multiple instances with single selector

### ISSUE THREAD

**Issue by alvarotrigo** [froala/wysiwyg-editor#1138]
It seems I'm not having luck trying to initialise multiple instances with a single selector (as I won't known how many elements will be editable)

##### Expected behavior.
Having two two `div` editable elements:
```javascript
$('div').froalaEditor(); 

//or a more real scenario  
$('[contenteditable]').froalaEditor();
```
##### Actual behavior.
Need to specify each of them:
```javascript
$('#div1, #div2').froalaEditor();
```
##### Steps to reproduce the problem.
Single selector (failing)
http://jsfiddle.net/yyjvkp4v/5/

Multiple selectors (working)
http://jsfiddle.net/yyjvkp4v/4/

##### OS.
OS X El Capitan

##### Browser.
Chrome

**Comment by stefanneculai** [comment]
That's because you're initializing the editor on a div which has contenteditable="true". Removing contenteditable="true" will work just fine.
