### ISSUE TITLE
Add upload file cancel button / Shortcut (Ex: ESC)

### ISSUE THREAD

**Issue by bionicvapourboy** [froala/wysiwyg-editor#1139]
##### Expected behavior.
When uploading file, I expect to be able to abort the operation during the upload

##### Actual behavior.
No button or shortcut available.

**Comment by aronsimo** [comment]
Could you please document? How is this possible? I know the Escape button works, but I would better call a function to do this.

**Comment by stefanneculai** [comment]
@aronsimo we're going to add a button to the editor upload window for that - it's on our list :)
