### ISSUE TITLE
Resize a image to width or height 0 make it unmanageable 

### ISSUE THREAD

**Issue by bionicvapourboy** [froala/wysiwyg-editor#1140]
##### Expected behavior.
Images never disappear after a resize, images always selectable and manageable without html code view.

##### Actual behavior.
Images disappears when width or height become 0, not selectable with mouse or keyboards.

##### Steps to reproduce the problem.
Upload an Image. Resize with handlers or by numeric values any dimension (width or/and height) to 0.

##### OS.
Osx Yosemite

##### Browser.
Chrome 49.0.2623.87

**Comment by stefanneculai** [comment]
Last commit adds `imageMinWidth` option that prevents image going smaller than that size.
