### ISSUE TITLE
Sometimes toolbar pop ups are off canvas

### ISSUE THREAD

**Issue by genyded** [froala/wysiwyg-editor#1141]
##### Expected behavior.
Toolbar pop ups can be seen in full
##### Actual behavior.
Depending on the alignment of the toolbar based on screen size, sometimes the pop ups are off canvas

##### Steps to reproduce the problem.
1. Get the screen size so that the 'link' toolbar item is the first item in the second row of the toolbar then click it.
2. You should see that the pop up if partly off the canvas (see attached screenshot) 

##### OS.
Windows 10

##### Browser.
Chrome 49.0.2623.87

![image](https://cloud.githubusercontent.com/assets/3081676/13919026/03007388-ef39-11e5-8c3b-f809d9222d0e.png)

**Comment by stefanneculai** [comment]
That's most likely because you have parent DOM elements which have CSS property `overflow: hidden`. Make sure you don't have any such rule set.

**Comment by SeokJinCheol** [comment]
link and image insert and table panel Can it be centered?
