### ISSUE TITLE
Calling editor.html.get(true) includes marker <span>, but removes <br> paragraphs

### ISSUE THREAD

**Issue by quintstoffers** [froala/wysiwyg-editor#1142]
##### Expected behavior.
Calling `editor.html.get` with both `true` and `false` should return similar output (with the exception of the marker `span` tag.

##### Actual behavior.
Calling `editor.html.get(true)` returns the HTML with the marker span, but without any <br> tags, whereas calling `editor.html.get(false)` doesn't return the marker does include the newlines.

##### Steps to reproduce the problem.
See http://jsfiddle.net/ycfexjxL/
- Run the JSFiddle.
- Type some text in the editor. Make sure you create some empty lines
- Wait 100ms.
- Observe the output with "keep markers" enabled doesn't contain any `<br>` tags.

##### OS.
OSX 10.11.4

##### Browser.
Chrome 49.0.2623.87 (64-bit)
Chrome 50.0.2661.37 beta (64-bit)
Chromium 51.0.2683.0 (64-bit)
Safari 9.1 (11601.5.17.1)
Firefox 45.0.1

##### Notes
It was necessary to call `editor.selection.save()`, otherwise even `get(true)` wouldn't return the marker.

**Comment by stefanneculai** [comment]
Yes, it is necessary to call `editor.selection.save` to have the markers there. `html.get(true)` would return the markers only if they are there - maybe we should clarify that in docs. Anyway, it doesn't remove any BR. Please see the attached screenshot.

<img width="960" alt="screen shot 2016-03-21 at 21 50 13" src="https://cloud.githubusercontent.com/assets/637004/13932036/f2c139f0-efae-11e5-926e-1d40f34527d4.png">

**Comment by quintstoffers** [comment]
Please try to create some paragraphs containing only <br>s, that seems to trigger the issue:
![froala_editor_-_jsfiddle_-_google_chrome_2016-03-21_22-06-09](https://cloud.githubusercontent.com/assets/147345/13934210/30528ce0-efb1-11e5-80e7-57ca7757148c.png)

Notice how there's no empty line between "test" and "abc" in the output that contains the marker? I have updated the original steps to reproduce to include having at least a single white line.

**Comment by jamiter** [comment]
+1 this still occurs with multiple empty lines...
