### ISSUE TITLE
How to prevent popup closing

### ISSUE THREAD

**Issue by Qlipoth** [froala/wysiwyg-editor#1144]
##### Expected behavior.
popup closing by clicking inside the popup area
https://s14.postimg.org/4453b83mp/bug.gif
##### Actual behavior.
popup closing only by clicking "close" button

**Comment by stefanneculai** [comment]
Please make a jsFiddle for it.

**Comment by stefanneculai** [comment]
I am closing this due to lack of information to reproduce it.

**Comment by lym8356** [comment]
I think this feature is not supported, the popup closes when I click outside of the popup, is there way to make it stay opened and only close it when you click on a close button?
