### ISSUE TITLE
Image editing popup appears at the bottom even if there is not enough space to place it

### ISSUE THREAD

**Issue by ygwain** [froala/wysiwyg-editor#1145]
Is there any way to force place the popup at the top?

##### Expected behavior.
The popup appears at top of the image

##### Actual behavior.
The popup appears at bottom of the image

##### Steps to reproduce the problem.
https://file.io/MUQ0tb

##### OS.
Ubuntu 14.04

##### Browser.
Google Chrome version 49.0.2623.87 (64-bit)

**Comment by stefanneculai** [comment]
There is no built-in way of doing that.

**Comment by ygwain** [comment]
But is it correctly that popup appears out of screen?

**Comment by stefanneculai** [comment]
Could you send a screenshot?

**Comment by ygwain** [comment]
I have uploaded a video (link in the first message) but seems like it was deleted for some reasons. Will upload it somewhere else tomorrow. A way to reproduce it: insert an image and move it to bottom of the screen and insert some empty lines after the image (5 is enough I think) then scroll up so bottom of the image would hidden. After that click on the image, the popup will be place out of screen.

**Comment by ygwain** [comment]
http://imgur.com/3OBy99m

**Comment by stefanneculai** [comment]
That is the correct behaviour.

**Comment by ygwain** [comment]
Got it. I use it in some project and the client complains for this behavior. He asks a feature to force place at the top.

**Comment by stefanneculai** [comment]
You'd have to make some changes in the editor core. If you want to do that, we can explain you what should be changed, under the tech support we offer with the Advanced/OEM license. If you have such a license please contact us via our website. Thank you.

**Comment by ygwain** [comment]
I will, thanks.
