### ISSUE TITLE
Iam using froala editor in my ember app. I created a custom button. On clicking it only particular toolbar buttons need to hide and disable. But i can only hide the entire toolbar . how to make a certain toolbarbuttons to disappear ?

### ISSUE THREAD

**Issue by Rudie07** [froala/wysiwyg-editor#1147]
##### Expected behavior.
(Describe expected behaviour here)

##### Actual behavior.
(Describe actual behaviour here)

##### Steps to reproduce the problem.
(Describe the steps to reproduce the problem here)

##### OS.
(OS name and version here)

##### Browser.
(Browser name an version here)

**Comment by stefanneculai** [comment]
A button can be disabled by adding the class fr-hidden. The button can be searched by using data-cmd attribute. We use this repo for bug tracking. For tech support, please [contact us via our website](froala.com/wysiwyg-editor/contact).

**Comment by Rudie07** [comment]
thanks @stefanneculai
