### ISSUE TITLE
The content doesn't change on 'froalaEditor.contentChanged' event after image inserting (ver 2.1.0+)

### ISSUE THREAD

**Issue by ygwain** [froala/wysiwyg-editor#1148]
##### Expected behavior.
After the event triggering HTML content contain the image tag.

##### Actual behavior.
HTML content doesn't contain the image tag. But if you making any changes after inserting the image   HTML content contain the image tag. It's true for ver. 2.1.0+, 2.0.5 works as expected.

##### Steps to reproduce the problem.
Bind 'froalaEditor.contentChanged' event to the editor, log the content there. Insert the image.

**Comment by stefanneculai** [comment]
It's fixed on master.
