### ISSUE TITLE
Add posibility for adding material effects

### ISSUE THREAD

**Issue by kotmatpockuh** [froala/wysiwyg-editor#1149]
For example so that i can set ripple effects on the toolbar buttons.

**Comment by stefanneculai** [comment]
It's up to you to implement it if you want such a thing. When we designed V2, we used those Material Design parts that we consider useful. You can read more about our vision regarding Material Design on our blog post: https://www.froala.com/blog/material-design-another-face-of-flat-design.

**Comment by kotmatpockuh** [comment]
there is no way to set custom attr and class to the buttons

**Comment by kotmatpockuh** [comment]
@stefanneculai there is no way to set custom attr and class to the buttons

**Comment by stefanneculai** [comment]
You can get the buttons from the toolbar using the following selector: `editor.$tb.find('[data-cmd="command_name"]')`.
