### ISSUE TITLE
codeView.toggle doesn't toggle

### ISSUE THREAD

**Issue by Rudie07** [froala/wysiwyg-editor#1150]
I created a custom button. And i gave the following line in its callback function.
`Ember.$('.froalaEditor').froalaEditor('codeView.toggle');`
And also i imported both code_view.min.css and code_view.min.js. But when i click on the button all the icons are disabled including the button i created. It doesn't toggle.

**Comment by stefanneculai** [comment]
`codeView.toggle` works fine. When the switch is made to the code-view, all the buttons from the toolbar are disabled, except those buttons which have the `data-cmd="html"` attribute.
