### ISSUE TITLE
Will not be edited in IE11.

### ISSUE THREAD

**Issue by largeden** [froala/wysiwyg-editor#1151]
##### Steps to reproduce the problem.
In the example(html/full.html), click on the image.
After that it will not be edited.

##### Cause.
https://github.com/froala/wysiwyg-editor/commit/9e5c3ba5ae2e5717c0ffb5160d2b484f1e35cebe
This commits the cause.

##### OS.
Windows 10

##### Browser.
IE11

**Comment by stefanneculai** [comment]
Nice catch :+1:
