### ISSUE TITLE
Translation mistake in table menu

### ISSUE THREAD

**Issue by masseuro** [froala/wysiwyg-editor#1152]
##### Expected behavior.
All tooltip in table menu have to be translate

##### Actual behavior.
In table menu translation for "table header" and "remove table" doesn't exist because in translate file the key is "header" and "table remove" doesn't existe (see https://github.com/froala/wysiwyg-editor/blob/master/js/languages/fr.js#L109)

##### Steps to reproduce the problem.

1. Use a froala wisywig with french languages (fr.js)
2. Create a table.
3. Select a cell
4. Watch the tooltip for table header or remove table.

<img width="219" alt="capture d ecran 2016-03-24 a 16 19 00" src="https://cloud.githubusercontent.com/assets/131135/14021693/e67aea1c-f1dc-11e5-9f76-b7e819a1db5c.png">
<img width="242" alt="capture d ecran 2016-03-24 a 16 19 07" src="https://cloud.githubusercontent.com/assets/131135/14021722/0117a7ca-f1dd-11e5-9acd-5f4c3ad8b670.png">

##### OS.
Macos

##### Browser.
Chrome 49

**Comment by stefanneculai** [comment]
We added the Table word a bit later to clarify the button actions and probably we missed to update the translations. A PR on this would be highly appreciated.

**Comment by masseuro** [comment]
Did it ;)
