### ISSUE TITLE
isURL() returns false incorrectly if the passed url has not scheme

### ISSUE THREAD

**Issue by fumila** [froala/wysiwyg-editor#1155]
Hi,

The code:

    function isURL (url) {
      if (!/^(https?:|ftps?:|)\/\//.test(url)) return false;

      ......

      var test_reg = /(http|ftp|https):\/\/[\w-]+(\.[\w-]*)*([\w.,@?^=%&amp;:\/~+#-]*[\w@?^=%&amp;\/~+#-])?/gi;

      return test_reg.test(url);
    }

I think test_reg should be defined like this:

      var test_reg = /((http|ftp|https):)?\/\/[\w-]+(\.[\w-]*)*([\w.,@?^=%&amp;:\/~+#-]*[\w@?^=%&amp;\/~+#-])?/gi;

**Comment by stefanneculai** [comment]
No, isURL method works correctly just as it is because it is designed to check for absolute path URLS. For example `www.google.com` is not a valid URL because without protocol it is interpreted as a relative URL.

**Comment by fumila** [comment]
well.. //www.google.com is a valid and absolute URL. For example one could use 

<img src="//domain.com/img/logo.png">

 Shouldn't isURL returns true in these cases?

Thanks.
