### ISSUE TITLE
Better file/image upload options (enhancement)

### ISSUE THREAD

**Issue by lebart** [froala/wysiwyg-editor#1156]
Hello

Giving the opportunity to choose different file/image upload strategies can be useful. 

For instance if someone want to disable the uploading process but keep the option to add an image via URL. 

Actually to disable the upload we have to use this:
.on('froalaEditor.image.beforeUpload', function (e, editor, images) { return false })

But the editor shows the uploading progression bar and never stops if you drop an image into the editor. Moreover the icon in the tool bar still shows the upload action which is confusing for the user. 

I think a good enhancement would be an option to select easily the way we allow images to be added.
imageInsertingStrategy: "url | upload | both"
imageAllowDragAndDrop: "false | true"

**Comment by AhHa45** [comment]
Can you explain how the `imageInsertButtons` solves this issue??

**Comment by stefanneculai** [comment]
@AhHa45 I believe this is what you're looking for: https://wysiwyg-editor.froala.help/hc/en-us/articles/115000555949-Can-I-insert-images-as-base64-.

**Comment by AhHa45** [comment]
@stefanneculai thanks, I already do it this way, however the file/image drop zone does not get closed when you return false in the `beforeUpload` event of image/file 👎

**Comment by stefanneculai** [comment]
@AhHa45 the popups should be hidden by calling the `editor.popups.hideAll` method in the callback. https://wysiwyg-editor.froala.help/hc/en-us/articles/115000555949

**Comment by AhHa45** [comment]
@stefanneculai thank you so much, I have over overlooked that :)
