### ISSUE TITLE
Editor is disabled while using with bootstrap modal

### ISSUE THREAD

**Issue by mitulgolakiya** [froala/wysiwyg-editor#1157]
##### Expected behavior.
I am using froala with bootstrap modal within one form. When I use it with chrome, its working fine but it's not working in firefox. An editor is disabled and we can not write anything. Even what I found interesting is, once I click anything from toolbar like bold, Italic or any other tool then it starts working fine.

If I set `fullPage` and `iframe` options to `false` then it works fine.

##### Actual behavior.
It should work fine with firefox

##### Steps to reproduce the problem.
Here I have created one fiddle: https://jsfiddle.net/8c1m128w/3/ where you can reproduce the problem.

##### OS.
Mac OS X El Capitan 10.11.4

##### Browser.
Firefox 45.0.1

**Comment by poul-kg** [comment]
I have the same issue:

**OS**: Windows 10 (64bit)
**Browser**: Firefox 45.0.1

**Comment by stefanneculai** [comment]
That is happening because having the editor hidden, in FF it's not possible to compute it's size. Unfortunately, this is an issue from the browser that we can't do nothing about. To fix your problem, you should call the `size.refresh` method after the modal is shown.

**Comment by mitulgolakiya** [comment]
@stefanneculai I just tested it with modal show event. But still its now working: https://jsfiddle.net/8c1m128w/6/

**Comment by stefanneculai** [comment]
Sorry, it should be: `$('#froala').froalaEditor('size.syncIframe');`.

**Comment by mitulgolakiya** [comment]
@stefanneculai thanks, it fixed the issue.
