### ISSUE TITLE
Cursor disappears when using BR/Enter option

### ISSUE THREAD

**Issue by DubHunt** [froala/wysiwyg-editor#1158]
##### Expected behavior.
Cursor is visible

##### Actual behavior.
Cursor disappears when using `BR` tags on Enter and an error is raised: "The given range isn't in document".

##### Steps to reproduce the problem.
1) Visit the Enter Key Example page: https://www.froala.com/wysiwyg-editor/docs/examples/enter

2) Type spaces on new lines in the third editor which demonstrates the insertion of `BR` for Enter. The pattern which causes the error is not really clear, but I'm including a gif to demonstrate: 
http://g.recordit.co/2o4thj25cG.gif

##### OS.
OSX 10.11.3

##### Browser.
Chrome 49.0.2623.87 (64-bit)

**Comment by stefanneculai** [comment]
I have just tried and couldn't replicate it. Have you done anything else before?

**Comment by mgodwin** [comment]
I can reproduce this error as well.

Here's exact steps to replicate:

1.  Put cursor at end of line for the `<BR>` mode example.
2.  Press <kbd>Enter</kbd> two times
3.  Hit the <kbd>up-arrow</kbd>
4.  Press <kbd>space</kbd>

You get the following error:  'The given range isn't in document'

![image](https://cloud.githubusercontent.com/assets/1121058/14118101/0f0cf83c-f5a5-11e5-9ddb-6a41b90fceec.png)

**Comment by stefanneculai** [comment]
@mgodwin thanks for the details!

**Comment by mgodwin** [comment]
Hey @stefanneculai, I just downloaded the new version (2.2.2) and I'm not seeing that this problem is resolved - are you not seeing this behavior anymore in `<BR>` mode?

**Comment by stefanneculai** [comment]
Have you downloaded the Github master?

**Comment by mgodwin** [comment]
Sorry, I tried 2.2.2 - wasn't sure if that was master or not, I'll try master and report back - thanks

**Comment by mgodwin** [comment]
Yep, fixed on master - :ok_hand: :100: :confetti_ball: 

Thanks!
