### ISSUE TITLE
Changing image alignment leaves image tool in previous position

### ISSUE THREAD

**Issue by barrydoyle18** [froala/wysiwyg-editor#1159]
##### Expected behavior.
When image alignment changes the image editing UI in it's initial position should disappear.

##### Actual behavior.
It doesn't disappear.

##### Steps to reproduce the problem.
Add an image by dropping it in and change it's alignment.

##### OS.
Windows 10

##### Browser.
Google Chrome

**Comment by stefanneculai** [comment]
Is that happening on our website?
