### ISSUE TITLE
Gmail CSS height/min-height issue

### ISSUE THREAD

**Issue by ideaweb** [froala/wysiwyg-editor#1160]
##### Expected behavior.
Add image dimensions (by optional param) as html attributes like 

`<img width="100" height="200" style="width: 100px; height: 200px" />`

##### Actual behavior.
Added and resized images contains the set dimensions only in style attribute like 

`<img style="width: 100px; height: 200px" />`

Any height and with attributes will be removed by Froala automatically.

GoogleMail is replacing "height: 20px" to "min-height: 20px" and makes Froala useless for e.g. developing newsletter tools w/o hacking image.js. 

##### Steps to reproduce the problem.
Upload an image, reduce the size in Froala and sent the HTML to GoogleMail.

**Comment by stefanneculai** [comment]
Does [imageOutputWidth](https://www.froala.com/wysiwyg-editor/docs/options#imageOutputWidth) fixes your problem?

**Comment by ideaweb** [comment]
Sorry, i did not recognised resent update 2.2.2. The recent version does not contain your suggest option. I try to update my implementation (because i used an own "patched" version) and let you know soon if its working.

**Comment by ideaweb** [comment]
I made an update and checked the new code. ImageOutputWidth is handling only the width and does not solve my problem with Gmail:

`if (editor.opts.imageOutputWidth) {
  ...
  imgs[i].setAttribute('width', $(imgs[i]).width());
`

Maybe an option imageOutputHeight would help in next version. But you new code is much easier to patch. I need only to add
