### ISSUE TITLE
Code formatting adding additional br tag

### ISSUE THREAD

**Issue by rblin081** [froala/wysiwyg-editor#1163]
##### Expected behavior.
Flipping between code and html view should not add additional spacing or breaks

##### Actual behavior.
BR tag is being added after first div

##### Steps to reproduce the problem.
Paste following html into code view

```
<div style="text-align: justify;">
	<br>
</div>
<table border="0" cellpadding="0" cellspacing="0" style="font-family: Arial, Helvetica, sans-serif; line-height: 18px; color: rgb(65, 64, 66); margin: 0px; padding: 0px; width: 540px; font-size: 14px; background-color: rgb(255, 255, 255);"></table>
```

Flip to html view and back to code view. Additional br tag will be after first div.

https://jsfiddle.net/f87p3s65/47/
##### OS.
Windows

##### Browser.
Chrome

**Comment by PaulDaviesC** [comment]
Issue persists in version 2.3.3
