### ISSUE TITLE
Can't edit link

### ISSUE THREAD

**Issue by rblin081** [froala/wysiwyg-editor#1165]
##### Expected behavior.
Link edit popup should function and not flash

##### Actual behavior.
Edit link popup flashes but does not do anything functional

##### Steps to reproduce the problem.
Insert link using button. Click on link in html and will bring up link popup. Click edit html button in popup. Popup will flash and reappear but not do anything

https://jsfiddle.net/f87p3s65/51/

##### OS.
Windows

##### Browser.
Chrome

**Comment by dashawk** [comment]
Why is this closed? there is no solution on this or even just a comment. What is going on? I have this issue in current version 3.2.2
