### ISSUE TITLE
Unable to get property 'nextSibling' of undefined or null reference

### ISSUE THREAD

**Issue by rblin081** [froala/wysiwyg-editor#1166]
##### Expected behavior.
No exceptions thrown

##### Actual behavior.
Cursor behavior is erractic

##### Steps to reproduce the problem.
Can't replicate on fiddle but in our application there is a undefined reference being consistently thrown. The line in question is in the _atEnd function. The node needs to be checked if it is null before trying to access it's nextSibling

##### OS.
Windows

##### Browser.
IE11

**Comment by stefanneculai** [comment]
Are you able to reproduce it on our website?

**Comment by rblin081** [comment]
Able to replicate in Chrome. Expect the fix will resolve the IE issue as well

Just type into the editor and press enter, won't be able to go to next line and will throw "cannot read property" exception
https://jsfiddle.net/f87p3s65/54/

**Comment by stefanneculai** [comment]
It's hard to track it down without having the possibility to replicate it. Anyway, could you try the latest commit and let me know if it fixes the problem?

**Comment by stefanneculai** [comment]
@rblin081 Thanks for the jsFiddle. Last commit fixes it.

**Comment by rblin081** [comment]
Awesome, thanks

**Comment by rblin081** [comment]
https://jsfiddle.net/f87p3s65/58/

Click at end of line and start typing. Will put characters at correct position, but cursor is at beginning of line

IE 11 / Windows

**Comment by nupurkamble** [comment]
@stefanneculai @rblin081  How to use the commit to fix this problem? Because im facing the same issue
