### ISSUE TITLE
Paste from Word or Powerpoint removes some spaces throughout the contet

### ISSUE THREAD

**Issue by DigitalCakeNZ** [froala/wysiwyg-editor#1167]
##### Expected behavior.
You should be able to paste from Word and other microsoft products, as per features and documentation.

##### Actual behavior.
While the paste does work, it removes randomly spaces in the content.

##### Steps to reproduce the problem.
Copy and mildly formatted text or content from microsoft word.
Paste to Froala, observe some spaces being removed, words joined together etc

##### OS.
OSX & windows

##### Browser.
All major browsers, latest microsoft word and powerpoint

**Comment by stefanneculai** [comment]
Please send us the document you're copying from.

**Comment by benjaminknox** [comment]
This is happening for us too, here is a sample word document:

[Sample word.docx](https://github.com/froala/wysiwyg-editor/files/216096/Sample.word.docx)

**Comment by benjaminknox** [comment]
Anything happening with this ticket?

**Comment by stefanneculai** [comment]
@benjaminknox the doc you sent has only a line with a single word.

**Comment by benjaminknox** [comment]
Strange, try this document: 
[Sample word (2).docx](https://github.com/froala/wysiwyg-editor/files/230816/Sample.word.2.docx)

**Comment by stefanneculai** [comment]
@benjaminknox I am not able to reproduce it with the master version. Could you please make a recording?

**Comment by stefanneculai** [comment]
I am closing this due to lack of response.

**Comment by benjaminknox** [comment]
New froala release fixed it

**Comment by DigitalCakeNZ** [comment]
Can also confirm the latest release seems to have fixed it!

**Comment by DenisaSurdu** [comment]
This is not fixed on Edge (I'm using Edge: Microsoft Edge 38.14393.0.0 & Microsoft EdgeHTML 14.14393).

How to replicate: 
- Open https://www.froala.com/wysiwyg-editor using Edge.
- Remove the pre-populated text
- Go to https://www.ucl.ac.uk/amyloidosis/pdfs/nac_newsletter_1
- Copy the fist paragraph from the PDF and paste it in Froala editor (Edge browser)
- Notice some words lack spacing (see below screenshot as well). 

![image](https://cloud.githubusercontent.com/assets/4330214/20839465/9c8e0b66-b8a4-11e6-8c43-df714a427ce0.png)
