### ISSUE TITLE
Using editor in IFRAME mode pollutes classes/styles of elements

### ISSUE THREAD

**Issue by cearny** [froala/wysiwyg-editor#1168]
##### Expected behavior.
The HTML source should not be polluted with editor-specific styles that seem to be required for the context menu /etc. Especially when we want inline styles (no CSS)

##### Actual behavior.
We get added styles e.g. for images `style="z-index: 3; position: relative; overflow: auto; cursor: pointer;"`. Also I see that fr-tag has made a comeback and there is no way to control that.

##### Steps to reproduce the problem.
Use editor inside IFRAME with inline styles enabled is all that's required, I think. We are also using the codeMirror plugin, if it amounts to anything.

##### OS.
n/a

##### Browser.
Chrome, tested with version 2.2.2

**Comment by stefanneculai** [comment]
`fr-tag` from V1 is no longer used in V2. The editor is using classes to style the content inside id (images, videos). If you don't want these to be included in the output, then you can use the [useClasses option](https://www.froala.com/wysiwyg-editor/docs/options#useClasses).

**Comment by cearny** [comment]
Then maybe that's a left-over. We do have useClasses set to false, mind. The other part, with inline styles polluting the IMG elements for example is still outstanding, though. And I don't think you can consider the inline Froala toolbar itself as external CSS properties.

Strangely enough, we do have toolbarInline set to false but it still shows up when clicking an image for example.

**Comment by stefanneculai** [comment]
While I appreciate your feedback, we won't remove those classes which are being used to align and change image display. If you don't want to have the image styles being changed, not including the imageAlign and imageDisplay buttons won't use classes for images anymore.

The toolbarInline option refers only to the main toolbar, not the image/link/videos etc.

**Comment by cearny** [comment]
You have to understand that the problem is related to e.g. images getting extra styles like the `cursor: pointer` and `z-index: 3` added to them.

I'm pretty sure the extra cursor and z-index styles are related to your inline image properties editor and that they don't get properly cleaned up when switching to HTML view. I'm wondering whether that will get stored when saving the HTML and whether that will cause the images to have cursors and weird z-index when that HTML is displayed in a different context.

**Comment by stefanneculai** [comment]
@cearny that makes sense. It wasn't totally clear from your initial description.

**Comment by cearny** [comment]
I'm sorry about that, I sort of stitched the two things together because I only noticed the `fr-*` classes and the style additions at the same time.

I'll paste our editor config below, maybe it helps:

```
$('#contents').froalaEditor({
			// Set the language code.
			language: 'ro',
			height: 600,
			// Colors list.
			colors: [
				'#15E67F', '#E3DE8C', '#D8A076', '#00AEEF', '#76B6D8', 'REMOVE',
				'#1C7A90', '#249CB8', '#4ABED9', '#FBD75B', '#FBE571', '#FFFFFF'
			],
			toolbarInline: false,
			iframe: true,
			iframeStyle: 'html{margin: 0px;height: 100%;display:table; width:100%;}body{height:100%;padding:10px;background:transparent;color:#000000;position:relative;z-index: 2;-webkit-user-select:auto;margin:0px;display:table-cell; text-align:center; vertical-align:middle;max-width: 700px;}body:after{content:"";clear:both;display:block}',
			useClasses: false,
			codeMirrorOptions: {
				mode: 'html',
				theme: 'material',
				lineNumbers: true,
				tabMode: 'indent',
				indentWithTabs: true,
				lineWrapping: true,
				tabSize: 2
			}
        });
```

This is used for editing the contents of an e-mail by the way (hence the IFRAME, we want it in an isolated environment), so that's why I'm really careful with any style attribute issues.

**Comment by stefanneculai** [comment]
Last commit removes `z-index: 3; overflow: auto;`. 

`position: relative;` is necessary for displaying the image correctly.

`cursor: pointer;` is a `wontfix`. It is being used for displaying the hand when going over the image to show interaction, but it's not possible to remove it from the inline output. Maybe in the future we'll add an option to reject certain styles from the output when using useClasses.

**Comment by cearny** [comment]
OK, thanks a lot; any idea when a new release will be out?

Related to the inline styles -- wouldn't it be easier to just inject Froala-specific classes when displaying the WYSIWYG editor and then remove them when displaying the HTML source?

I'm not sure how the editor is coded, but this is what I'm thinking would be most feasible.

**Comment by stefanneculai** [comment]
The release will be made today. 

That's how we designed it initially, but after-while we decided that current way is cleaner.

**Comment by cearny** [comment]
Ah so that's why it seemed like a regression to me :smile: thanks for the clarification!

**Comment by cearny** [comment]
By the way this also causes grey borders to be added as styles to tables (I suspect these are the guidelines in the WYSIWYG).

**Comment by stefanneculai** [comment]
The borders are being added from froala_style CSS file. That is style which should appear both inside and outside the editor.

**Comment by berzniz** [comment]
I recommend re-opening this.

Our users are reporting this to us as a bug... they add images and get them with a pointer on their output which confuses visitors to think it is clickable.

Using inline styles, it means we have to use `!important` which isn't something we want to do. 

I'm sure there's a better way to address this and tell between styles used for the editor vs. styles used for end result.

**Comment by stefanneculai** [comment]
@berzniz If you want not to have those I would recommend to you use a RegEx maybe to remote that for images.
