### ISSUE TITLE
Image edit popup does not show

### ISSUE THREAD

**Issue by rblin081** [froala/wysiwyg-editor#1170]
##### Expected behavior.
Clicking on image should bring image options popup

##### Actual behavior.
Outline around image partially shows up, no image options popup
##### Steps to reproduce the problem.
Click on pikachu
https://jsfiddle.net/f87p3s65/60/

##### OS.
Windows

##### Browser.
IE 11

**Comment by stefanneculai** [comment]
You're not including the `image` plugin.

**Comment by rblin081** [comment]
Updated, same problem

https://jsfiddle.net/f87p3s65/63/
