### ISSUE TITLE
Moving cursor issue

### ISSUE THREAD

**Issue by rblin081** [froala/wysiwyg-editor#1171]
##### Expected behavior.
Cursor should stay on current line and behavior should switch ( bold -> not bold )

##### Actual behavior.
Cursor goes to next line and bold stays on

##### Steps to reproduce the problem.
https://jsfiddle.net/f87p3s65/64/

Click bold and type into first line
press enter
click bold again ( to get rid of bold text )
cursor moves back up to previous line and bold is re-enabled

This also happens with italics, underline, strikethrough

##### OS.
Windows

##### Browser.
IE 11, Chrome , Edge

**Comment by stefanneculai** [comment]
I am missing something or there is no issue. Would it be possible to make a recording? Thanks.

**Comment by rblin081** [comment]
I can't make a recording at this moment. If you follow the steps provided it happens every time where the cursor is on the second line, press the bold button ( so that the second line doesnt receive bold styiling ) and the cursor moves back up to the first line.

**Comment by stefanneculai** [comment]
Well.. I've tried it for about 5 minutes without luck. I'll wait for the video when you can.

**Comment by rblin081** [comment]
The original reported bug has been fixed, but in my testing I have found another. While using bold on a line press the bold button(to make following text not bold) and type more characters without a space in between. The text will be bold again even tho the bold button was turned off.

**Comment by stefanneculai** [comment]
@rblin081 What browser and os?

**Comment by rblin081** [comment]
Chrome and windows

**Comment by stefanneculai** [comment]
Could you make a jsFiddle for it and explain the steps to reproduce it? I couldn't replicate it on a blank editor instance.

**Comment by rblin081** [comment]
Ya sorry the browser is IE 11

https://jsfiddle.net/f87p3s65/113/

Press Bold button
Type some text
Press Bold button again to disable
Without putting in a space type some text
Will still be bold and bold option has been re-enabled

**Comment by stefanneculai** [comment]
This appears to be a completely other thing. Could you please fill a new issue for it?

**Comment by rblin081** [comment]
You got it
