### ISSUE TITLE
Paragraph formatting does not work 

### ISSUE THREAD

**Issue by rblin081** [froala/wysiwyg-editor#1173]
##### Expected behavior.
Should change content to selected paragraph style

##### Actual behavior.
Nothing happens

##### Steps to reproduce the problem.
Click bold and type hi on first line
Highlight text and click paragraph option from dropdown (h1)
Should change highlighted content to h1 formatting 

https://jsfiddle.net/f87p3s65/64/

##### OS.
Windows

##### Browser.
Chrome

**Comment by stefanneculai** [comment]
That's because you put the `strong` tag into `htmlDoNotWrapTags`.
