### ISSUE TITLE
Underline + img.insert is removing previous image

### ISSUE THREAD

**Issue by rblin081** [froala/wysiwyg-editor#1174]
##### Expected behavior.
Both images should still be there

##### Actual behavior.
Underline and img.insert is removing first image

##### Steps to reproduce the problem.
Go to a line below snorlax. Press underline button. Press insert img button which will insert a pikachu img. Flip to code view and back. Snorlax is gone

https://jsfiddle.net/f87p3s65/69/

##### OS.
Windows

##### Browser.
Chrome and Edge

**Comment by stefanneculai** [comment]
Fixed by 2c1c3560f36b69ec21cf1e9f076d69c589a1a1f5.
