### ISSUE TITLE
Wrong cursor position with contenteditable=false

### ISSUE THREAD

**Issue by cgallarno** [froala/wysiwyg-editor#1175]
##### Expected behavior.
When a cursor is next to a contenteditable=false element is should still be in place next to it. Preferably using the arrows I would be able to navigate the cursor around the element, right now it seems stuck on one side of it.

##### Actual behavior.
The cursor jumps to the top right of the editor. note: focus is still in the correct place, continuing to type insert the text where expected, this seems to be a visual bug.

##### Steps to reproduce the problem.
https://jsfiddle.net/d29LcLb1/1/
begin by backspacing the text after the un-editable element, and when the cursor reaches the element it jumps to the right.

##### OS.
OSX 10.11.4

##### Browser.
Chrome

**Comment by stefanneculai** [comment]
Same thing happens when you edit directly on a contenteditable element without using the editor (https://jsfiddle.net/froala/d29LcLb1/2/). Unfortunately, this is a Chrome caret display issue and we couldn't find any fix to it.

**Comment by cgallarno** [comment]
Oh, thanks for the clarification, that sucks! But also I noticed in the plain content editable I can continue to backspace and delete the entire 'non-editable' span, but in the editor it stops the caret. Would it be possible to delete the element as a whole but not edit the content inside of it?

**Comment by stefanneculai** [comment]
That behaviour isn't consistent by default in all browsers and that's why we disabled it. Currently, we're working on a feature which would disable/enable such a behaviour.

**Comment by cgallarno** [comment]
Thanks!

**Comment by decherneyge** [comment]
I am running into the same thing and I see that it is a chrome thing but just thought I would pass along my findings. If there is an empty span tag after the 'non-editable' span the cursor is placed in the correct location.

**Comment by deshiknaves** [comment]
To anyone who's looking for a solution. I've never used this editor, but as I was investigating a fix for CKEditor, I've come across a solution to this cursor bug. In this example, add:

```css
.fr-element {
  display: inline-block;
}
```
Making the main element `display: inline-block;` puts the cursor in the right position.

**Comment by deshiknaves** [comment]
Actually, that only works because the width of the editor is reduced. Not the right solution. However, I have found that entering a `&zwj;` after the content editable will put the cursor in the right spot. This gets filtered out in the editor that I'm using, so whenever the editor is focused and the item before the selection is a content editable false, I add one of those in there.

**Comment by zifeiyuSun** [comment]
> Actually, that only works because the width of the editor is reduced. Not the right solution. However, I have found that entering a `&zwj;` after the content editable will put the cursor in the right spot. This gets filtered out in the editor that I'm using, so whenever the editor is focused and the item before the selection is a content editable false, I add one of those in there.

If the `&zwj;` is deleted, the issue still exists. emm, so sigh..

**Comment by sixiakun** [comment]
i resolve this by add css display:inline-bolck & add <br> to the end of div.
https://stackoverflow.com/questions/27786048/why-is-my-contenteditable-caret-jumping-to-the-end-in-chrome
