### ISSUE TITLE
Not possible to set a direct DOM node as toolbarContainer or scrollableContainer

### ISSUE THREAD

**Issue by patrinhani-ciandt** [froala/wysiwyg-editor#1178]
##### Expected behavior.
I would like to set a node on the options instead a selector string
toolbarContainer: $('some-node'),
scrollableContainer: : $('some-node-scroller'),

##### Actual behavior.
I can set a string selector only:

toolbarContainer: 'some-node',
scrollableContainer: : 'some-node-scroller',

##### OS.
ALL

##### Browser.
(Browser name an version here)

**Comment by stefanneculai** [comment]
It works just find if you pass the DOM node, instead of the jQuery object: `$('some-node').get(0)`. Our long term plan is to remove the jQuery dependency. 😄
