### ISSUE TITLE
Block element inside inline element

### ISSUE THREAD

**Issue by ur92** [froala/wysiwyg-editor#1179]
Hi, 
According to HTML5, it might be valid to place `div` tag inside `a` tag.
But when I try to do it in the editor my html code will parsed and `a` tag will be wrapped around every element separately.

**More general question is if I can disable or tweak the html compile process, so if I pasted invalid html, the html will not be processed and I will stay with the original html.**

Thanks!

##### Expected behavior.
```
<a href="#">
	<div>
		<h2>Hello world!</h2>
	</div>
</a>
```

##### Actual behavior.
```
<p><a href="#">&nbsp;</a></p>
<div>
	<h2><a href="#">Hello world!</a></h2>
</div><a href="#">&nbsp;</a>
<p></p>
```

##### Steps to reproduce the problem.
Paste the expected code into html editor.
Go to preview.
Go back to html editor.

##### OS.
Win7

##### Browser.
Chrome

**Comment by stefanneculai** [comment]
You should get it work just the way you want by setting the following option: `enter: $.FroalaEditor.ENTER_BR`.
