### ISSUE TITLE
Wrong cursor position after image delete

### ISSUE THREAD

**Issue by kotmatpockuh** [froala/wysiwyg-editor#1183]
##### Expected behavior.
After image delete cursor appears near deleted image

##### Actual behavior.
Cursor disappears

##### Steps to reproduce the problem.
Navigate to https://www.froala.com/wysiwyg-editor
Add some text and image: http://i.imgur.com/IrHbCe5.png
Remove image
As result: cursor disappears

##### OS.
Windows 7

##### Browser.
Chrome 49.0.2623.110 m

BTW: guys ireported this issue some time ago: https://github.com/froala/wysiwyg-editor/issues/591

**Comment by stefanneculai** [comment]
Could you confirm this is happening only when you have image inside a blank paragraph? I mean something like this `<p><img></p>`.

**Comment by kotmatpockuh** [comment]
Yes.

**Comment by kotmatpockuh** [comment]
@stefanneculai 
maybe you have an information: is it possible that this bug will be fixed in the nearest 10 days?
just wanna to know and plan my future work...

**Comment by stefanneculai** [comment]
Issues marked with `bug` tag are the ones which are fixed first. Yes, it might be fixed in the following days.
