### ISSUE TITLE
It's impossible to add 2+ videos continiously

### ISSUE THREAD

**Issue by kotmatpockuh** [froala/wysiwyg-editor#1184]
##### Expected behavior.
It's possible to add 2+ videos

##### Actual behavior.
It's impossible

##### Steps to reproduce the problem.
Navigate to froala demo
Add video (don't click or add anything else)
Add second video
Result: nothing - the second video wasn't added

##### OS.
Windows 7

##### Browser.
Chrome 49.0.2623.110 m

**Comment by stefanneculai** [comment]
Could you confirm that this is happening only when the editor is blank (no content inside it)? Thank you.

**Comment by kotmatpockuh** [comment]
Yes, i confirm that.
