### ISSUE TITLE
Line break bar issue when image exists already on page when it's loaded

### ISSUE THREAD

**Issue by rjk** [froala/wysiwyg-editor#1185]
##### Expected behavior.
Line break bar (is there a proper name for this thing?) appears below an image.

##### Actual behavior.
If the image is in the editor when the page loads the line break bar appears in the wrong vertical position, halfway up the image instead of beneath the image. Hovering the mouse in the expected place does show the line break bar but the bar appears in the wrong place.

##### Steps to reproduce the problem.
* Go to https://www.froala.com/wysiwyg-editor/docs/examples/custom-image-button
* Hover mouse over the bottom of the image
* Line break bar appears halfway up the image instead of where mouse is hovering. Therefore it's not possible to click the line break bar as it disappears when you stop hovering over that position.

##### OS.
Windows 10

##### Browser.
Chrome 49.0.2623.110 m or Internet Explorer 11.

<img width="692" alt="froala-line-break-bar-1" src="https://cloud.githubusercontent.com/assets/29672/14460952/4767778e-00b8-11e6-8332-3532d2087497.png">

**Comment by stefanneculai** [comment]
https://github.com/froala/wysiwyg-editor/issues/1188
