### ISSUE TITLE
Line break bar shown at top of image in IE 

### ISSUE THREAD

**Issue by rjk** [froala/wysiwyg-editor#1186]
##### Expected behavior.
As I understand it, the line break bar should only show beneath an image. 

##### Actual behavior.
Line break bar sometimes appears above an image. See screenshot.
<img width="525" alt="froala-line-break-bar-2" src="https://cloud.githubusercontent.com/assets/29672/14460981/7961cc8a-00b8-11e6-918f-ed06a6a155e3.png">

##### Steps to reproduce the problem.
* navigate to https://www.froala.com/wysiwyg-editor/docs/examples/custom-image-button in Internet Explorer 11
* type a couple of line breaks after the text. Ensure cursor is on the line above the existing image.
* drag and drop an image from File Explorer onto the froala editor, so it appears after the text and before the image.
* hover the mouse over the top of the newly-inserted image. Notice the line break bar appears here at the point where you're hovering. If you click the line break bar it inserts a line break above the image.
* hover the mouse over the bottom of the newly-inserted image. The line break bar correctly appears here too. 

##### OS.
Windows 10

##### Browser.
Internet Explorer 11

**Comment by stefanneculai** [comment]
Improved as part of https://github.com/froala/wysiwyg-editor/issues/1188.
