### ISSUE TITLE
Get HTML with markers when using line breaks instead of paragraphs

### ISSUE THREAD

**Issue by jannacs7** [froala/wysiwyg-editor#1189]
##### Expected behavior.
Froala should return the output with markers

##### Actual behavior.
Froala returns only the markers

##### Steps to reproduce the problem.
https://jsfiddle.net/vspan7/r3oeopkc/
Add any text and wait for the output

The issue exists when using line breaks instead of paragraphs(Froala option: enter: $.FroalaEditor.ENTER_BR)

The bug exists on versions 2.2.2 & 2.2.3 and NOT on 2.2.1

##### Browser.
Google Chrome

**Comment by stefanneculai** [comment]
It's fixed on master: 2.2.4 development. https://jsfiddle.net/r3oeopkc/2/
