### ISSUE TITLE
Whitespace not preserved after break tags

### ISSUE THREAD

**Issue by rblin081** [froala/wysiwyg-editor#1190]
##### Expected behavior.
All whitespace converted to `&nbsp;` 

##### Actual behavior.
Whitespace not being kept / converted after break tags
##### Steps to reproduce the problem.
https://jsfiddle.net/f87p3s65/81/

##### OS.
Windows
##### Browser.
Chrome

**Comment by stefanneculai** [comment]
Actually that is the correct behaviour. The incorrect behaviour was to keep spaces at the beginning of the line.
