### ISSUE TITLE
Break tag added to empty p tag

### ISSUE THREAD

**Issue by rblin081** [froala/wysiwyg-editor#1191]
##### Expected behavior.
Don't add additional breaks

##### Actual behavior.
Break tag added to empty p tag even when p is in list of allowedEmptyAttrs

##### Steps to reproduce the problem.
https://jsfiddle.net/f87p3s65/83/

##### OS.
Windows

##### Browser.
Chrome

**Comment by stefanneculai** [comment]
`P` is a block tag. Not adding a BR in it will make impossible to type inside. If you want to prevent that you can change the behaviour of the `fillEmptyBlocks` method.

**Comment by akg-sc** [comment]
Thanks for the explanation @stefanneculai, but how do you change the behavior of the `fillEmptyBlocks` method?
