### ISSUE TITLE
Font-size and paragraph styling isn't working

### ISSUE THREAD

**Issue by rblin081** [froala/wysiwyg-editor#1192]
##### Expected behavior.
Expect that content formatting will change with current selected toolbar button

##### Actual behavior.
Font-size than paragraph button does not use paragraph style

##### Steps to reproduce the problem.
Click font-size toolbar button and select a size (36). Type some characters. Click on paragraph toolbar button. Select heading 4. Type text, text is not an h4. This is true for all font-size / paragraph combinations.

http://jsfiddle.net/f87p3s65/88/

##### OS.
Windows
##### Browser.
Chrome

**Comment by stefanneculai** [comment]
Font size changes the font size of the text where the cursor is, while paragraph format is changing the type of the paragraph. The current behaviour is the correct one.

**Comment by rblin081** [comment]
Paragraph format does not work if font-size is being used. Can look at
output code to see the <h4> tag is never applied

**Comment by stefanneculai** [comment]
That's because you are adding `span` to `htmlDoNotWrapTags`.

**Comment by rblin081** [comment]
Even if span is removed from htmlDoNotWrapTags if I highlight part of the
content and apply a paragraph style it wraps the entire piece in the
paragraph style.

**Comment by stefanneculai** [comment]
Paragraph format is converting the entire paragraph, not only the selected part of text. Isn't it working this way?

**Comment by rblin081** [comment]
I would expect the highlighted text to only receive the styling being
applied.

**Comment by stefanneculai** [comment]
Paragraph format is referring to the entire paragraph. That's exactly how Word/Google Docs works. We won't change this behaviour that users are familiar with.

**Comment by rblin081** [comment]
In that case this is an entirely different bug. For the previous scenario,
font-size and than paragraph applied the content is holding onto the
font-size and not applying the paragraph style. In Google Docs the
font-size is overwritten in favor of the paragraph tag

**Comment by stefanneculai** [comment]
They are doing this only when the entire paragraph has that font size height. I added this on our feature list and we'll review it.
