### ISSUE TITLE
Editor output images keep pointer style

### ISSUE THREAD

**Issue by rblin081** [froala/wysiwyg-editor#1195]
##### Expected behavior.
Only images that are links should have a cursor pointer

##### Actual behavior.
All images have cursor pointer, not just links 

##### Steps to reproduce the problem.
http://jsfiddle.net/f87p3s65/92/

Press "Get HTML" button to get output html. Put into JSFiddle / HTML doc. 

##### OS.
Windows

##### Browser.
Chrome

**Comment by stefanneculai** [comment]
That is by design so that the user would know that the image is clickable. If you want to customize that then you could add the following css rule: `.fr-element img { cursor: default !important; }`

**Comment by rblin081** [comment]
In the editor it's important to know what image is clickable but the output html ( and where it goes ) is static. I understand that the content keeps the same css it has in the editor, it just seems wonky for it to be applied in a situation where the content is not editable.

**Comment by stefanneculai** [comment]
See https://github.com/froala/wysiwyg-editor/issues/1168#issuecomment-205298672.
