### ISSUE TITLE
Code View Changing content format

### ISSUE THREAD

**Issue by rblin081** [froala/wysiwyg-editor#1196]
##### Expected behavior.
Content should hold same formatting and spacing when flipping between code view
##### Actual behavior.
Flipping to code view adds additional spacing
##### Steps to reproduce the problem.

http://jsfiddle.net/f87p3s65/95/

Flip to code view and back. There is additional spacing between the first line and first list item

##### OS.
Windows

##### Browser.
Chrome

**Comment by stefanneculai** [comment]
That's happening because you're wrapping everything inside a SPAN. Inside contenteditable span tags are highly sensitive and it's always better to use a DIV for such situations. You can read more about that here too: http://stackoverflow.com/questions/18492256/displaying-an-element-similar-to-p-inside-a-span.

**Comment by rblin081** [comment]
Stefan,
I don't have control of the content. I understand the html structure is
less than ideal, but can you explain why it displays consistently on load
but code view consistently adds spaces ?
The code is actually from V1 and consistently displays in that editor when
toggling between code and html view

**Comment by rblin081** [comment]
Also the more I toggle between code and html view the more `&nbsp;` are added after the first p tag

**Comment by stefanneculai** [comment]
When code is loaded initially in the application, it doesn't have new lines between the P an UL. When it gets to the code view, then it gets a new line and that new line would further on get converted to a NBSP. In V2, we added in a new way for handling spaces which converts to non-breaking spaces where necessary. 

I am reopening this for now and marking it as `enhancement` and will be rechecked/improved later on.

**Comment by stefanneculai** [comment]
That has been fixed in a commit yesterday.
