### ISSUE TITLE
Upload Multiple Images

### ISSUE THREAD

**Issue by ltullman** [froala/wysiwyg-editor#1197]
Per https://github.com/froala/wysiwyg-editor/issues/643, this is not on your roadmap.  I'd like to request it be added.  Is that possible?

**Comment by stefanneculai** [comment]
This is already on our feature list and there is high interest for it. Unfortunately, I cannot tell you an ETA for it. I am closing this here because we're not keeping Feature Requests anymore on the Github repo.

**Comment by ltullman** [comment]
Ok, thank you for the update.

**Comment by heymexa** [comment]
@ltullman can use the custom plugin https://github.com/heymexa/froala-images-multi-upload
