### ISSUE TITLE
Removing last list item

### ISSUE THREAD

**Issue by rblin081** [froala/wysiwyg-editor#1198]
##### Expected behavior.
Last list item should stay a list item

##### Actual behavior.
When pressing toolbar list button (to not create another) after a list, the last list item loses its bullet and place in the list

##### Steps to reproduce the problem.
Create a list (ol/ul) and add a few list items. Press Shift + Enter to exit the list and move to next line. Press enter a couple of times to add some space between current line and last list item. Press toolbar list button ( is still blue meaning list insert is one). Last list item loses its bullet / place in the list.

http://jsfiddle.net/f87p3s65/97/

##### OS.
Windows

##### Browser.
Chrome & IE 11

**Comment by stefanneculai** [comment]
And a quick note: to exit from lists mode you should hit ENTER only on a blank line. SHIFT + ENTER will add new lines inside the last list item, but won't get out of list mode.
