### ISSUE TITLE
Wrong editor.selection.isFull() output when saving selection

### ISSUE THREAD

**Issue by jannacs7** [froala/wysiwyg-editor#1203]
##### Expected behavior.
editor.selection.isFull() should return true when all text is selected

##### Actual behavior.
editor.selection.isFull() returns false when all text is selected and editor.selection.save() was executed

##### Steps to reproduce the problem.
https://jsfiddle.net/vspan7/axsqukd4/1/

##### OS.
El Capitan

##### Browser.
Chrome latest

**Comment by stefanneculai** [comment]
That is the correct behaviour because markers are being added before and after the selection. `selection.isFull` is designed to check if everything inside the editable area is selected and in this case markers are not.
