### ISSUE TITLE
<br> autogenerated by wysiwyg

### ISSUE THREAD

**Issue by ignaciochiazzo** [froala/wysiwyg-editor#1204]
##### Expected behavior.
Load HTML as the source HTML

##### Actual behavior.
WYSIWYG is writting some <br> inside the HTML code. Particularly this br tags are writing in some cases such as :
    - after the first li tag inside a ul 

```html
<ul class="X">
  <li><span class="X1">✔</span>span: </li>
  <li>
    <ul>
      /*THE BR TAG IS INSERTED HERE*/
      <li>Something</li>         
      <li>Something</li>         
      <li>Something</li>   
   </ul>
 </li>
 <li>Something</li>
<ul>

##### Steps to reproduce the problem.
(Describe the steps to reproduce the problem here)

##### OS.
(OS name and version here)
MAC, Yosemite 10.10.5 

##### Browser.
(Browser name an version here)
CHROME v 49.0

**Comment by stefanneculai** [comment]
Is the `LI` tag empty? If the `LI` tag is empty, then a `BR` is being added inside it because other-way it is not possible to type in it. Also, inside `UL` according to the HTML specs, you should not have other child than `LI`.

**Comment by ignaciochiazzo** [comment]
@stefanneculai  I updated the code, the LI is not empty, and the li has another ul insde maybe is that the problem.

**Comment by stefanneculai** [comment]
Actually, the `BR` tag is being inserted before the nested list. That is the correct behaviour and it is done in order to allow users to type text inside the nested `LI`. If you want to change this behaviour, you could change the editor JS, but we won't make such a change.
