### ISSUE TITLE
Superscript/Subscript issue with Bootstrap

### ISSUE THREAD

**Issue by mrjlynch** [froala/wysiwyg-editor#1209]
##### Expected behavior.
Superscript/subscript buttons to remain 'active' when clicked, as displayed on the froala website. 

##### Actual behavior.
Superscript/subscript buttons do not become 'active', user can not exit superscript/subscript mode

##### Steps to reproduce the problem.

Simple add bootstrap css

http://jsfiddle.net/rb8gn61d/

##### OS.
Mac el Capitan

##### Browser.
Chrome and Safari

**Comment by stefanneculai** [comment]
The editor is using the default browser commands for subscript/superscript. The problem is caused by Boostrap adding the following CSS rule which makes the browser not recognize the text as beign sub/sup.
```css
sub, sup {
  vertical-align: baseline;
}
```
