### ISSUE TITLE
Custom button to show toolbar for Inline mode 

### ISSUE THREAD

**Issue by nishantbeans** [froala/wysiwyg-editor#121]
I am using the Editor with Inline mode that means Toolbar is only visible when selecting text, Is there a possibility to show a tool bar on a button click. 

Or Is there a possibility to view image upload wrapper on custom button click without selecting text ?

**Comment by ahmadajmi** [comment]
To show the image upload wrapper, here is a little thing I use. Hope it works with you.
``` html
<a class="ion-image" href="#" id="insert-image">Upload Image</a>
```
``` javascript
$('#insert-image')
  .on('click', function (e) {
    e.preventDefault()
    $('#edit').editable("show", null);
    $('.froala-image-popup').css("display", "block");
    $('.bttn-wrapper').css("display", "none");
  });
```
