### ISSUE TITLE
Line is holding bold text when iframe and ENTER_BR options are enabled

### ISSUE THREAD

**Issue by rblin081** [froala/wysiwyg-editor#1211]
##### Expected behavior.
When unclicking Bold button the following text should not be bold

##### Actual behavior.
Unclicking Bold button and typing more characters onto line with bold, the following characters are also bold and the Bold button has been turned back on

##### Steps to reproduce the problem.
https://jsfiddle.net/f87p3s65/115/

Press Bold button
Type some text
Press Bold button again to disable
Without putting in a space type some text
Will still be bold and bold option has been re-enabled

##### OS.
Windows

##### Browser.
IE 11

**Comment by stefanneculai** [comment]
Could you confirm that if you hit the Bold button twice to disable it, then it works fine?

**Comment by rblin081** [comment]
Hitting the Bold button twice to disable did not work

**Comment by stefanneculai** [comment]
Are you hitting ENTER?

**Comment by rblin081** [comment]
I am following the steps as listed. Hitting bold, typing text on a line,
hitting bold again, and typing text again on that same line

**Comment by stefanneculai** [comment]
Where do you have the cursor initially?

**Comment by rblin081** [comment]
Very first line

**Comment by stefanneculai** [comment]
There is text on the first line. Are you putting it at the start of the line, middle of the line or end of the line?

**Comment by rblin081** [comment]
https://jsfiddle.net/f87p3s65/116/

**Comment by rblin081** [comment]
Must have sent you an earlier version

**Comment by stefanneculai** [comment]
At a further check this appears to be an issue which happens on IE when using iframe https://jsfiddle.net/m4u5d5j7/. We'll try to see if there is any possible workaround for it or we have to wait until Microsoft will fix it.

**Comment by stefanneculai** [comment]
Reported to Microsoft: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/7304837/

**Comment by stefanneculai** [comment]
Last commit should fix it. Could you confirm that?

**Comment by rblin081** [comment]
Fixes the original issue, however after entering a few characters of
unbolded text (3-4 chars tops) I can no longer enter any more characters.
Cursor still blinks and editor is still responsive, just can't enter any
more input.
