### ISSUE TITLE
Bugs related to 'add video'

### ISSUE THREAD

**Issue by kotmatpockuh** [froala/wysiwyg-editor#1213]
##### Expected behavior.
Videos are added. Cursor appears.

##### Actual behavior.
Add video from youtube link-share block: http://prntscr.com/awijgn
(video can't be added)
Add two+ videos:
http://prntscr.com/awijp7
(it's impossible to add something new -> cursor didn't appear)

##### Steps to reproduce the problem.
Use any youtube video and froala demo-wysiwyg.

##### OS.
Windows 7

##### Browser.
Chrome 49.0.2623.112 m

**Comment by kotmatpockuh** [comment]
Why it is with the label `enhancement`?)
It's a bug)

**Comment by stefanneculai** [comment]
We consider this an enhancement and not a bug because this is how browsers treat `contenteditable="false"` inside `contenteditable="true"`. It is the same thing as https://github.com/froala/wysiwyg-editor/issues/1188 which was fixed during last week. This issue will be addressed shortly as well.

**Comment by stefanneculai** [comment]
Last commit is fixing this by changing the way line breaker can insert new lines. Now, if you will go with mouse at the top/bottom of the video you will be able to insert a line break there. Ideally, it would have been to have this implemented the way image works, but the info we get from the browser on click is not relevant enough for this case.

**Comment by kotmatpockuh** [comment]
Are you sure this issue was fixed in 2.3.0?

**Comment by kotmatpockuh** [comment]
Oh, now i see.

Maybe there is a way to change timeout, when icon "break" hide?

**Comment by kotmatpockuh** [comment]
@stefanneculai 

Oh, now i see.

Maybe there is a way to change timeout, when icon "break" hide?
