### ISSUE TITLE
Custom button to add HTML Tag

### ISSUE THREAD

**Issue by mrjlynch** [froala/wysiwyg-editor#1218]
Is there a way to easily wrap and unwrap a string with a html tag (eg. `<code></code>`)? 

```
$.FroalaEditor.DefineIcon('code-highlight', {NAME: 'i-cursor'});
$.FroalaEditor.RegisterCommand('code-highlight', {
  title: 'Highlight',
  focus: true,
  undo: true,
  refreshAfterCallback: true,
  callback: function (cmd) {
    html = this.selection.get();
    this.html.insert('<code>' + html + '</code>');
  }
});
```

**Comment by stefanneculai** [comment]
No, there is not builtin way in the editor for doing that. You'd have to play with the [commands.applyProperty](https://www.froala.com/wysiwyg-editor/docs/methods#commands.applyProperty) for achieving that.

**Comment by mrjlynch** [comment]
It would be possible to achieve this using the commands.applyProperty, however, this would apply inline styling, and is not good practice if it is used frequently. Is there any chance that something builtin could be considered?

**Comment by stefanneculai** [comment]
Yes, we're currently working on something built-in.

**Comment by george-norris-salesforce** [comment]
Any progress on this?

**Comment by stefanneculai** [comment]
@george-norris-salesforce see `format.apply` option.
