### ISSUE TITLE
Autoformatting --> into →

### ISSUE THREAD

**Issue by mrjlynch** [froala/wysiwyg-editor#1219]
I would like to convert `-->` into `→`

I tried to achieve this with the following: 

```
$('#froala-editor').on('froalaEditor.keyup', function (e, editor, keyupEvent) {
    html = editor.html.get()
    parsed_html = html.replace(/-->/g, '→')
    editor.html.set(parsed_html)
});
```

jdfiddle: https://jsfiddle.net/yt3942g3/

Thanks

**Comment by stefanneculai** [comment]
That is not the correct approach. If you want to do such a thing, then you can use the URLs plugin where we're converting text to URLs as a starting point.
