### ISSUE TITLE
Image cursor

### ISSUE THREAD

**Issue by rblin081** [froala/wysiwyg-editor#1220]
##### Expected behavior.
Text should be typed where cursor is

##### Actual behavior.
Text is being putting to right of image
##### Steps to reproduce the problem.
https://jsfiddle.net/f87p3s65/121/
Click below image, cursor should be to bottom left of image. 
Begin typing
Text will be put to bottom right of image
##### OS.
Windows
##### Browser.
IE 11

**Comment by stefanneculai** [comment]
Unfortunately, we can't do nothing about it. We've played around with that few months ago and there is no workaround because that's how IE is placing the cursor incorrectly. Same thing happens in a blank contenteditable element: https://jsfiddle.net/f87p3s65/133/.
