### ISSUE TITLE
Feature request: removeProperty method

### ISSUE THREAD

**Issue by roguejack** [froala/wysiwyg-editor#1221]
The API gives a way to applyProperty, but none to remove the same that was added. clearFormatting() is not an option because that would remove other inline styles as well.

```js
$(element).froalaEditor('commands.applyProperty', 'font-weight', '700');
//Now how to remove it (without clearing other formats)?
```
Other alternative is to allow the applyProperty to accept null (which would then internally remove the property and clean up if necessary).
```js
$(element).froalaEditor('commands.applyProperty', 'font-weight', null);
```

**Comment by stefanneculai** [comment]
Not documented yet, but last commit is adding a new method called `format.removeStyle(prop)` which can be used for this purpose.
