### ISSUE TITLE
Indent cursor issue

### ISSUE THREAD

**Issue by rblin081** [froala/wysiwyg-editor#1223]
##### Expected behavior.
Pressing enter on a line should bring cursor to beginning of next line
##### Actual behavior.
Pressing enter, the cursor stays on current line

##### Steps to reproduce the problem.
https://jsfiddle.net/f87p3s65/122/

Enter text on first line
Press "Increase Indent" button
Press enter to go to next line, cursor will still be on first line

##### OS.
Windows

##### Browser.
IE 11

**Comment by stefanneculai** [comment]
Works fine with master branch.
