### ISSUE TITLE
HtmlAllowedAttrs without style attr accept indent and outdent margin-left

### ISSUE THREAD

**Issue by masseuro** [froala/wysiwyg-editor#1224]
##### Expected behavior.
If attribute style is not available (not in HtmlAllowedAttrs), indent text should work only for list not for text.

##### Actual behavior.
Indent button add a style attribute on text with margin-left

##### Steps to reproduce the problem.

- see here https://jsfiddle.net/f87p3s65/123/
- Add text, use indent button
- Inspect text (attr style="margin-left")

##### OS.
Macos

##### Browser.
Last Chrome and last Firefox dev

**Comment by stefanneculai** [comment]
It doesn't make sense to actually do that. There might be users who remove the `style` attribute by a mistake and this way they get bunch of features not working: indent, font size, alignment, etc. Removing `style` attribute from `htmlAllowedAttrs` is a big customization and who does that should change the other things in the editor. Indent/outdent methods can be easily overwritten to do nothing like this: 

```js
$.FE.MODULES.commands.indent = function () {};
$.FE.MODULES.commands.outdent = function () {};
```
