### ISSUE TITLE
relative url's shouldn't get a url prefix

### ISSUE THREAD

**Issue by lemnis** [froala/wysiwyg-editor#1226]
relative url's shouldn't get a prefix

![froala](https://cloud.githubusercontent.com/assets/3999815/14912259/4af699e8-0dfb-11e6-98b0-61834eea2bb1.gif)  
(example of the current behavior, used editor: https://www.froala.com/wysiwyg-editor)

##### Expected behavior.
When there is no dot in the url it should behave like a relative url and get no prefix:

Should get prefixed:
* google.com
* google.com/test

Shouldn't get prefixed:
* /
* /test
* test
* test/other_test

##### Steps to reproduce the problem.
1. Create a link with a relative path
* When you edit the url or look in the code view you will see that relative url got prefixed

**Comment by stefanneculai** [comment]
Actually `test` and `test/other_test` is considered as being an URL and it should be prefixed. There are several developers using the editor in LAN and they have a short domain name set.

**Comment by forum-is** [comment]
On the other hand, `test/other_test` could also be a perfectly valid relative URL in an application that would become invalid after prefixing.

So maybe the user should have an option to actively mark a URL as relative by providing an additional checkbox in the **Add Link** dialog?

**Comment by lemnis** [comment]
We use the editor only to edit content on public sites. It would be weird to link to short domains. That's why I would prefer an option to toggle this behavior.

But you could (also) implement the behavior that is stated in the comment above. Only in that solution I would like to see that the checkbox is only visible if the URL field has a short domain.

**Comment by stefanneculai** [comment]
@lemnis @forum-is there are definitely different possible scenarios. The one we have currently implemented is what works best based on the feedback we received. If you want to achieve a different behaviour, I would recommend you to create a wrapper over the link insert method and change the href based on your needs.
