### ISSUE TITLE
froala crashes when commenting html in code mode

### ISSUE THREAD

**Issue by trakdesk** [froala/wysiwyg-editor#1227]
We are using froala v1 and noticed an issue. for some reason, when commenting html in code view and switching back to html view, it completely freezes the browser. 

Example: if i do this `<!--<span style="color: #ccc;">{{ data }}</span>-->` it freezes the browser however if i do  it works fine. 

Tested in chrome, IE and ff, same issue.

**Comment by stefanneculai** [comment]
We're no longer supporting v1. Please upgrade to v2.
