### ISSUE TITLE
Popup in IE10 are below added video

### ISSUE THREAD

**Issue by kotmatpockuh** [froala/wysiwyg-editor#1228]
##### Expected behavior.
Popup appears above any container object

##### Actual behavior.
Popup appears under video

##### Steps to reproduce the problem.
Navigate to test-environment
Add any youtube video
Try to click on the button, which will cause popup open
Result: http://prntscr.com/azb42a

##### OS.
Windows 7

##### Browser.
IE 10

**Comment by kotmatpockuh** [comment]
as was mentioned here: https://github.com/froala/wysiwyg-editor/issues/895

**Comment by stefanneculai** [comment]
What IE version are you using exactly? I couldn't reproduce it with IE 10.0.9200.17148.

**Comment by kotmatpockuh** [comment]
Default ie10

i'll tell you version tomorrow

**Comment by kotmatpockuh** [comment]
10.0.9200.17267
http://bit.ly/21wvqfS
