### ISSUE TITLE
Spellcheck freezes up Table

### ISSUE THREAD

**Issue by mrjlynch** [froala/wysiwyg-editor#1230]
##### Expected behavior.
Correcting text in table with Spellcheck should not freeze up editor. 

##### Actual behavior.
Correcting text in table with Spellcheck 'freezes' editor. 

##### Steps to reproduce the problem.
Create a table and in a cell type a word that is spelt incorrectly eg. `wron`
Correct the spelling error using spellcheck. Editor should 'freeze' and edits can no longer be made. 

##### OS.
Mac osX El Capitan

##### Browser.
Chrome 50.0.2661.86 (64-bit)

**Comment by stefanneculai** [comment]
I cannot reproduce it. Could you please make a recording? Thank you.

**Comment by mrjlynch** [comment]
![github 1](https://cloud.githubusercontent.com/assets/3665457/14985936/2571a556-118d-11e6-8a4a-adefcbbcaa2e.gif)

**Comment by stefanneculai** [comment]
Can you reproduce it on our website?

**Comment by mrjlynch** [comment]
That recording is from your website

**Comment by stefanneculai** [comment]
Is it from the main page or other page?

**Comment by mrjlynch** [comment]
From your main page

**Comment by dianaprajescu** [comment]
This happens only when you try to correct the spelling using `ctrl + left click` and not on `right click`.
