### ISSUE TITLE
Enhancement : Link creation tab down

### ISSUE THREAD

**Issue by rblin081** [froala/wysiwyg-editor#1232]
##### Expected behavior.
In the "Insert Link" popup after entering a URL, pressing tab would bring cursor down to text field

##### Actual behavior.
When cursor is in URL field pressing tab doesn't do anything

**Comment by stefanneculai** [comment]
Hi Rob! Is this happening on V2.2.4? I can't replicate it on our website.

**Comment by rblin081** [comment]
iframe:true seems to do it

**Comment by stefanneculai** [comment]
No change: https://www.froala.com/wysiwyg-editor/docs/examples/iframe

**Comment by rblin081** [comment]
Doesn't work in this, not sure what the difference is
http://jsfiddle.net/f87p3s65/125/

**Comment by stefanneculai** [comment]
It works locally with the same editor options, but not on jsFiddle. Most likely it has something to do with the way jsFiddle is displaying the output.

**Comment by rblin081** [comment]
It's also not working in my application (Chrome, IE 11, FF )

**Comment by stefanneculai** [comment]
Could you try to reproduce it on a basic example and send a ZIP with the files? Or maybe send a link to the exact page where you have this problem? Thank you.

**Comment by rblin081** [comment]
You can close this, it was an error on our end
