### ISSUE TITLE
Option to allow links to contain invalid URLs

### ISSUE THREAD

**Issue by philfreo** [froala/wysiwyg-editor#1235]
We use the editor to allow people to define email templates, where people can fill in mail-merge template tags like `{{user.name}}`. This works fine in the simple case since it's nothing special for Froala other than text.

However people also often want to insert these template tags as the `href` in links since the tags could include a URL (or part of a URL). The problem is that Froala strips out this link href since it's an "invalid" URL.

Steps to reproduce:
Create a link with `{{custom.foo}}` as the `href`.

Desired behavior:
HTML that looks like `<a href="{{custom.foo}}">my text</a>`

Actual behavior:
(no anchor link created)

**Comment by philfreo** [comment]
Thanks!

**Comment by philfreo** [comment]
Using these values as href works:

```
{{lead.display_name}}
{{lead.custom.[Leads]}}
```

However values with spaces, etc. get HTML escaped:

e.g. Using an href of:

`{{lead.custom.[Org Discount $]}}` 

produces an href of:

`{{lead.custom.[Org%20Discount%20%24]}}`

Is this fixable?

**Comment by philfreo** [comment]
@stefanneculai Any thoughts on this comment above?

**Comment by stefanneculai** [comment]
@philfreo the editor is sanitizing the urls in order to prevent XSS attacks. If you want to permit different URLs, you could use the following code to change the default behavior. Just make sure you include it before initializing the editor.

```js
var original_helpers = $.FE.MODULES.helpers; 
$.FE.MODULES.helpers = function (editor) { 
  var helpers = original_helpers(editor); 

  var isURL = helpers.isURL();  

  // This is the original sanitizer.
  helpers.sanitizeURL = function (url) { 
      if (/^(https?:|ftps?:|)\/\//i.test(url)) {
        if (!isURL(url) && !isURL('http:' + url)) {
          return '';
        }
      }
      else {
        url = encodeURIComponent(url)
                  .replace(/%23/g, '#')
                  .replace(/%2F/g, '/')
                  .replace(/%25/g, '%')
                  .replace(/mailto%3A/gi, 'mailto:')
                  .replace(/file%3A/gi, 'file:')
                  .replace(/sms%3A/gi, 'sms:')
                  .replace(/tel%3A/gi, 'tel:')
                  .replace(/notes%3A/gi, 'notes:')
                  .replace(/data%3Aimage/gi, 'data:image')
                  .replace(/blob%3A/gi, 'blob:')
                  .replace(/webkit-fake-url%3A/gi, 'webkit-fake-url:')
                  .replace(/%3F/g, '?')
                  .replace(/%3D/g, '=')
                  .replace(/%26/g, '&')
                  .replace(/&amp;/g, '&')
                  .replace(/%2C/g, ',')
                  .replace(/%3B/g, ';')
                  .replace(/%2B/g, '+')
                  .replace(/%40/g, '@')
                  .replace(/%5B/g, '[')
                  .replace(/%5D/g, ']')
                  .replace(/%7B/g, '{')
                  .replace(/%7D/g, '}');
      }

      return url;
  }; 

  return helpers;
} 
```

**Comment by fyneworks** [comment]
The code above seems to break the editor and create an infinite self-referencing loop.

```
var original_helpers = $.FE.MODULES.helpers; 
$.FE.MODULES.helpers = function (editor) { 
  var helpers = original_helpers(editor);  // this causes an endless loop
```

I've changed it to this instead and it seems to work:
`$.FE.MODULES.helpers.sanitizeURL = function (url) { return url; };`

**Comment by jhubert** [comment]
Just a heads up for anyone that uses the code above from fyneworks, this will allow XSS attacks in the editor because the urls are not getting sanitized at all.

**Comment by fyneworks** [comment]
Thanks for the heads up! We went on to implement the following:
```
var original_sanitizeURL = $.FE.MODULES.helpers.sanitizeURL;
$.FE.MODULES.helpers.sanitizeURL = function (url) {
	if(url.match(/^\#\w+\#$/gi)) return url; // special cms markup
	return original_sanitizeURL(url); // use FE's original 
};
```
:-)

**Comment by dularion** [comment]
Hi there, so i tried the above suggestion but I couldnt get it to work. see this jsfiddle. https://jsfiddle.net/63qq3uqk/

We have the same usecase with invalid urls because they are used as template-variables and later injected, so we need this as well!

**Comment by stefanneculai** [comment]
@dularion please see: https://jsfiddle.net/63qq3uqk/3/

**Comment by dularion** [comment]
Thank you very much @stefanneculai

**Comment by limuel567** [comment]
> @philfreo the editor is sanitizing the urls in order to prevent XSS attacks. If you want to permit different URLs, you could use the following code to change the default behavior. Just make sure you include it before initializing the editor.
> 
> ```js
> var original_helpers = $.FE.MODULES.helpers; 
> $.FE.MODULES.helpers = function (editor) { 
>   var helpers = original_helpers(editor); 
> 
>   var isURL = helpers.isURL();  
> 
>   // This is the original sanitizer.
>   helpers.sanitizeURL = function (url) { 
>       if (/^(https?:|ftps?:|)\/\//i.test(url)) {
>         if (!isURL(url) && !isURL('http:' + url)) {
>           return '';
>         }
>       }
>       else {
>         url = encodeURIComponent(url)
>                   .replace(/%23/g, '#')
>                   .replace(/%2F/g, '/')
>                   .replace(/%25/g, '%')
>                   .replace(/mailto%3A/gi, 'mailto:')
>                   .replace(/file%3A/gi, 'file:')
>                   .replace(/sms%3A/gi, 'sms:')
>                   .replace(/tel%3A/gi, 'tel:')
>                   .replace(/notes%3A/gi, 'notes:')
>                   .replace(/data%3Aimage/gi, 'data:image')
>                   .replace(/blob%3A/gi, 'blob:')
>                   .replace(/webkit-fake-url%3A/gi, 'webkit-fake-url:')
>                   .replace(/%3F/g, '?')
>                   .replace(/%3D/g, '=')
>                   .replace(/%26/g, '&')
>                   .replace(/&amp;/g, '&')
>                   .replace(/%2C/g, ',')
>                   .replace(/%3B/g, ';')
>                   .replace(/%2B/g, '+')
>                   .replace(/%40/g, '@')
>                   .replace(/%5B/g, '[')
>                   .replace(/%5D/g, ']')
>                   .replace(/%7B/g, '{')
>                   .replace(/%7D/g, '}');
>       }
> 
>       return url;
>   }; 
> 
>   return helpers;
> } 
> ```

I got: Uncaught TypeError: isURL is not a function

**Comment by doktordirk** [comment]
after a babel update the syntax proposed here failed for me (`t[e] is not a constructor`). 

following still worked:
```js
const original_helpers = $.FE.MODULES.helpers; 
$.FE.MODULES.helpers = function(editor) {
  return {
   ...original_helpers(editor),
   sanitizeURL(url) { 
     /* .do you stuff */ 
    return url;
   },
}
  
```

**Comment by acnowland** [comment]
currently trying the above code from @doktordirk  but I am getting an error - Uncaught TypeError: Cannot read properties of undefined (reading 'MODULES'). Trying to implement in a Vue application

**Comment by doktordirk** [comment]
sounds like bundling resp importing issue where `$` isn't what you think it is. that snipped either assumes there's as global `window.$` or or has be imported/required above and that it is the same jquery instance which froala uses.

**Comment by Nelaach** [comment]
I've come across an issue where the editor.helpers.sanitizeURL method is called twice — first on the raw string entered by the user, and then again on the encoded version of that string. This behavior is currently present in version 4.5.1.

While debugging, I noticed that sanitizeURL is first called, then the input is encoded using encodeURI(e), and later on, sanitizeURL is called again — this time on the encoded input.

Could it be that this method has recently been changed to support encoding done outside the function?

Specifically, I'm having trouble with placeholders that I insert using curly braces, like:
{{test}}

The curly braces are being encoded, but they are not being decoded later. I haven't encountered this issue in Froala's fiddle examples, so I'm wondering if this might be a bug or if I'm missing something.
