### ISSUE TITLE
Impossible to add video from YouTube (short link)

### ISSUE THREAD

**Issue by kotmatpockuh** [froala/wysiwyg-editor#1236]
##### Expected behavior.
User can add any video from YouTube

##### Actual behavior.
User can't add video (https://youtu.be/sqhi1IyjGuM for example)

##### Steps to reproduce the problem.
Navigate to froala test environment
Try to add video from YouTube

##### OS.
Windows 7

##### Browser.
Chrome 50.0.2661.94 m

**Comment by stefanneculai** [comment]
It's already fixed on the master version from Github. 7a96c27f3002d69859a4254345ea6487679903de
