### ISSUE TITLE
Access editor in the callback

### ISSUE THREAD

**Issue by mrjlynch** [froala/wysiwyg-editor#1243]
Is it possible to access the editor in the callback function when registering a custom button. See the following example: 

```
$.FroalaEditor.RegisterCommand('destroy', {
  callback: function (editor) {
    editor.froalaEditor('destroy');
  }
});
```

Thanks!

**Comment by stefanneculai** [comment]
See https://www.froala.com/wysiwyg-editor/docs/concepts/custom-button. 
```js
  // Called when the button is hit.
  callback: function () {
    // The current context is the editor instance.
    console.log (this.html.get());
  }
```

PS: For tech support please contact us via our website. We use this repo only for bug tracking. Thank you.
