### ISSUE TITLE
Spellcheck problem on Safari

### ISSUE THREAD

**Issue by SempaChoo** [froala/wysiwyg-editor#1244]
##### Expected behavior.
When adding wrong spelled word in text editor, google chrome shows the red line underneath the word and after I press "ENTER" that red line is still there but, on the safari red line disappears just after I proceed to next row.

##### Steps to reproduce the problem.
Open up Safari and start typing words in froala editor. Type something like "sucesful" or any other wrong spelled word. Right after that press enter and red line underneath the wrong spelled word disappears.

##### OS.
MAC OS X

##### Browser.
Safari latest version

Can you please provide me with fix or something because I am in a hurry and i already bought a licence. Cheers!

**Comment by stefanneculai** [comment]
The editor is using the browser spellcheck option and it appears Safari and IE work different than Chrome and they show the error when you go with the cursor over. Unfortunately, we cannot do anything to address it for now.
