### ISSUE TITLE
Selecting all text and pressing any char on the keyboard 

### ISSUE THREAD

**Issue by yiannakasgeorge** [froala/wysiwyg-editor#1249]
##### Expected behavior.
It should delete the text and replace it with the character pressed

##### Actual behavior.
Removes the text but loosing the character pressed

##### Steps to reproduce the problem.
https://www.froala.com/wysiwyg-editor#inline-demo
Focus in the Froala editor
Press command + a(Mac) OR ctrl + a (Windows) to select all text
Press 'A' on your keyboard
Text is removed but  no 'A' 

##### OS.
ElCapitan

##### Browser.
Chrome latest 

p.s Seems a minor issue but it is actually really important since most of the times the user looses the first character pressed.

**Comment by stefanneculai** [comment]
It's already fixed here on master.

**Comment by yiannakasgeorge** [comment]
Thank you Stefan.
