### ISSUE TITLE
Selecting all content then pressing a letter removes the text but does not add the letter

### ISSUE THREAD

**Issue by theknet** [froala/wysiwyg-editor#1253]
##### Expected behavior.
All content should be removed and replaced with the letter I press

##### Actual behavior.
All content is removed but Froala ignores the key pressed

##### Steps to reproduce the problem.
1. Enter content into a Froala editor
2. Highlight all text (CMD+A or manually)
3. Press a letter on the keyboard

##### OS.
Mac OS X 10.11.4

##### Browser.
Safari 9.1.1, Chrome 50.0.2661.94, Firefox 46.0.1

This only happens when selecting all content

**Comment by stefanneculai** [comment]
It's already fixed on master.
