### ISSUE TITLE
space stripped between tags when editor loads

### ISSUE THREAD

**Issue by in0ni** [froala/wysiwyg-editor#1254]
if i write the following using the editor (attached to `textarea`):
> This is **bold** _italic_ a test

the markup is properly inserted in `textarea`, and stored to the db:
`<p>This is <strong>bold</strong> <em>italic</em> a test</p>`

when the form is reloaded, froala removes the space between the **bold** and _italic_ elements like so:
`<p>This is <strong>bold</strong><em>italic</em> a test</p>`

if i load the form without the editor, it loads properly -- with the space preserved.

##### Expected behavior.
markup should load as follows:
`<p>This is <strong>bold</strong> <em>italic</em> a test</p>`

##### Actual behavior.
space is being stripped between strong/em tags:
`<p>This is <strong>bold</strong><em>italic</em> a test</p>`

even though in the db it's stored as:
`<p>This is <strong>bold</strong> <em>italic</em> a test</p>`

##### Steps to reproduce the problem.
I am using meteor-froala (2.2.4). I simply write the text mentioned above, save it and when the form reloads the space is stripped between strong/em tags. If I reload the same form -- unedited, and untouched -- but without loading froala, the text area displays the markup properly, as it's stored in the db.

##### OS.
Linux 4.5.3-1-ARCH x86_64

##### Browser.
Firefox 46.0.1 & Chrome 50.0.2661.94

**Comment by stefanneculai** [comment]
This should be fixed on master.
