### ISSUE TITLE
linkConvertEmailAddress - should accept all tld

### ISSUE THREAD

**Issue by wwlsascha** [froala/wysiwyg-editor#1257]
##### Expected behavior.
Links with email addresses with a tld size > 3 should be converted too. 

For example "some@domain.tips"

##### Actual behavior.
Due to the regex check for a tld size of 2 or 3, all newer domains won't be accepted. 

```javascript
if (b.opts.linkConvertEmailAddress) {
  var k = /^[\w._]+@[a-zA-Z0-9_-]+?\.[a-zA-Z0-9]{2,3}$/i;
  k.test(f) && !/^mailto:.*/i.test(f) && (f = "mailto:" + f)
}
```

##### Steps to reproduce the problem.
Create a link with "some@domain.tips".

##### Possible solution

```javascript
if (b.opts.linkConvertEmailAddress) {
  var k = /^[\w._]+@[a-zA-Z0-9_-]+?\.[a-zA-Z0-9]{2,}$/i;
  k.test(f) && !/^mailto:.*/i.test(f) && (f = "mailto:" + f)
}
```

**Comment by FinesseRus** [comment]
I would like to extend this issue. Email address can have a 3-, 4- or more-level domain. Also domain can have unicode characters inside ([related issue](https://github.com/froala/wysiwyg-editor/issues/1256)).
