### ISSUE TITLE
Ability to remove "Open in new tab" on links

### ISSUE THREAD

**Issue by philfreo** [froala/wysiwyg-editor#1262]
I'm using the editor in the context of an email compose window, and it doesn't make sense to present the "Open in new tab" option on links.

I see you have a `linkAlwaysBlank` option however there should also be an option to remove the setting altogether without having to resort to hiding it in CSS.

**Comment by stefanneculai** [comment]
Hi Phil! Setting `linkAlwaysBlank` to `true` removes the "Open in new tab" checkbox altogether and sets `target="_blank"` to links.
