### ISSUE TITLE
Selecting multiple cells in table header freezes table

### ISSUE THREAD

**Issue by mrjlynch** [froala/wysiwyg-editor#1264]
##### Expected behavior.
When selecting multiple cells from the table header, the table shouldn't freeze up

##### Actual behavior.
When selecting multiple cells from the table header, the table freezes up. 
![froala2](https://cloud.githubusercontent.com/assets/3665457/15274095/84a1eaf8-1aee-11e6-8c43-557c1360dac6.gif)

##### OS.
Mac OS X

##### Browser.
Chrome

**Comment by dianaprajescu** [comment]
The editor toolbar should freeze when selecting multiple cells, but shouldn't freeze when selecting only one cell. This may be the same with #1265.

Additionally, the editor is not designed to select both header and body cells, because you can't merge them and they also have different styles.

**Comment by mrjlynch** [comment]
I understand that editor should not select both header and body. However, users cannot be expected to know this. Perhaps selecting both should be prevented?

**Comment by dianaprajescu** [comment]
Selecting both is prevented (a selected cell has the blue border). The issue you recorded is related to the fact that the editor toolbar freezes, which is not happening anymore on the master branch.

Please try this with the master branch and let me know if it still happens. Closing this until then.
