### ISSUE TITLE
Using ember addon (ember-froala-editor) and trying to change shortcutsEnabled have no effect

### ISSUE THREAD

**Issue by RuslanZavacky** [froala/wysiwyg-editor#1266]
##### Expected behavior.
Limiting `shortcutsEnabled: ['redo', 'undo']` should not allow to change bold or any other styles by shortcuts

##### Actual behavior.
Actually changing shortcutsEnabled have no effect.

##### Steps to reproduce the problem.
1. Set option shortcutsEnabled: ['redo', 'undo']
2. Try to select text and click CMD+B
3. It should not make text bold

##### OS.
OSX El Capitan

##### Browser.
Chrome 51

I post here, instead of ember-froala-editor as I suspect its not really related to the ember addon as other options work well.

**Comment by stefanneculai** [comment]
When shortcuts are disabled, it means that the editor doesn't interfere with the browser behaviour. Chrome for example is doing bold when you hit CTRL+B inside a contenteditable and the editor behaviour is correct. If you want to prevent that, then you should listen to the keydown event and prevent it from doing that.

**Comment by RuslanZavacky** [comment]
I see, Thanks @stefanneculai!
