### ISSUE TITLE
Inconsistent Behavior with setting font sizes

### ISSUE THREAD

**Issue by d3chapma** [froala/wysiwyg-editor#1267]
##### Expected behavior.
Selecting text and setting the font size vs Setting the font size and entering text should produce the same markup.

##### Actual behavior.
Selecting text and setting the font size vs Setting the font size and entering text should produces different  markup.

Example:

`<span font-size='18px'>This is my example</span>`

If I select *my* and change the font size to 14px I end up with:

```
<span font-size='18px'>This is </span>
<span font-size='14px'>my</span>
<span font-size='18px'> example</span>
```

However, if I start with:

`<span font-size='18px'>This is  example</span>`

and I put my cursor between *is* and *example*, change the font size to 14px and type *my* I end up with:

`<span font-size='18px'>This is <span font-size='14px'>my</span> example</span>`

This is inconsistent and causes an issue when trying to have font sizes using `em` because font-size tags are being nested. Ideally changing the font size when inside of a tag with a font-size would always split the tag.

**Comment by stefanneculai** [comment]
Have you tested this on master?

**Comment by d3chapma** [comment]
No I have not. Should it be fixed on master?

**Comment by stefanneculai** [comment]
Yes, it might be fixed. Would appreciate if you can give it a go.

**Comment by d3chapma** [comment]
Will do

**Comment by d3chapma** [comment]
Just tried changing `froala_editor.js` and `font_size.js` to be the latest from master and I still get the same behavior for my example.

**Comment by stefanneculai** [comment]
That is right, it's still happening on master. We've checked it yesterday when added the `enhancement` label. Thanks for checking.
