### ISSUE TITLE
Can't write after inserting video into empty editor

### ISSUE THREAD

**Issue by vanpav** [froala/wysiwyg-editor#1268]
##### Expected behavior.
Video insert moves cursor on next line

##### Actual behavior.
Can't do anything in the editor after video added

##### Steps to reproduce the problem.
Insert video into blank editor

##### OS.
Mac OS X

##### Browser.
Chrome 50 and I believe only chrome

**Comment by stefanneculai** [comment]
This has been fixed few days ago here on the master version. Please see: https://github.com/froala/wysiwyg-editor/issues/1213#issuecomment-218776967.
