### ISSUE TITLE
Unspecified error while uploading Image

### ISSUE THREAD

**Issue by Dattaprasad-Choukekar** [froala/wysiwyg-editor#1269]
We have intergrated Froala edior in our application.
##### Expected behavior.

When clicked on insert image button, popup for drop image opens.
Select an image from local drive and image is added in the editor.

##### Actual behavior.

When clicked on insert image button, popup for drop image opens.
When an image is selected from local drive, nothing happens.
On the console of the browser we get below errors.

SCRIPT16389: Erreur non spécifiée.    
image.min.js (7,27635)
SCRIPT5007: Impossible d’obtenir la propriété  « removeClass » d’une référence null ou non définie
image.min.js (7,26266)

Sometimes leave image upload popup in below state
![error](https://cloud.githubusercontent.com/assets/13338032/15327967/98962fea-1c53-11e6-9f80-c10adf60e32a.png)

For smaller images its working filne.
But for images (say more than 100kb),  error occurs.

Translation 
Erreur non spécifiée. : unspecified error
Impossible d’obtenir la propriété  « removeClass » d’une référence null ou non définie : Unable to obtain property "removeClass" of a reference null or undefined

##### OS.
Windows 10 64 bit

##### Browser.
Error only on IE (11.306.10586) not on Chrome or Firefox

**Comment by stefanneculai** [comment]
Are you able to reproduce it on our website?

**Comment by Dattaprasad-Choukekar** [comment]
Non. I was not able to reproduce it on exemples or your website.

**Comment by stefanneculai** [comment]
Please make sure you're using latest editor version V2.2.4.
