### ISSUE TITLE
Skewed image dimensions on paste

### ISSUE THREAD

**Issue by thedotedge** [froala/wysiwyg-editor#1271]
##### Expected behavior.
Select and paste part of the page with images from a webpage, image dimensions are retained as per original size on the source page.

##### Actual behavior.
Image width is set to 300px.

##### Steps to reproduce the problem.

1. Navigate to https://angularjs.org/
2. Select and copy to clipboard
![image](https://cloud.githubusercontent.com/assets/227241/15355986/4b019910-1cf6-11e6-8db1-f2724bd3e7d3.png)
3. Navigate to https://www.froala.com/wysiwyg-editor/docs/examples/full-featured
4. Paste into editor
5. End result
![image](https://cloud.githubusercontent.com/assets/227241/15356018/7343224a-1cf6-11e6-8e9a-5902219edca6.png)

##### OS.
Mac OS 10.11.4

##### Browser.
Chrome 50.0.2661

**Comment by thedotedge** [comment]
@stefanneculai when do you have next patch release planned?

**Comment by stefanneculai** [comment]
Don't have an ETA for it yet.
