### ISSUE TITLE
Table menu, bug on header button with two instance of editor

### ISSUE THREAD

**Issue by masseuro** [froala/wysiwyg-editor#1273]
##### Expected behavior.
With two instances of FroalaEditor, bug appear on Header button of table submenu

##### Actual behavior.
![table-2](https://cloud.githubusercontent.com/assets/131135/15358306/f910db94-1d03-11e6-9fde-653e41302a0e.gif)

And file code to reproduce 
[table.html 2.zip](https://github.com/froala/wysiwyg-editor/files/270460/table.html.2.zip)

##### Steps to reproduce the problem.
Two editor with two table inside in the same page
Could only be reproduce with v2.2.4 because table submenu is not visible with master version #1272 

##### OS.
Mac Os 10.11.4

##### Browser.
Chrome 50 and Firefox 46

**Comment by masseuro** [comment]
This bug appear in version v2.2.0, it's ok with version v2.1.0

**Comment by stefanneculai** [comment]
Nice catch 👍 .

**Comment by masseuro** [comment]
oh great !
