### ISSUE TITLE
From HTML to Text with persisted break lines

### ISSUE THREAD

**Issue by RuslanZavacky** [froala/wysiwyg-editor#1274]
We are currently implementing a way how to get froala HTML and translate it to Text, so I have couple questions and you might know the answers :)

1. Is there a native Froala way, how to get text from Froala HTML?
2. We are currently removing HTML tags by ourselves, this leads to a problem, where froala don't have "specific" new lines, and when we have content `<p>one line</p><p>second line</p>` visually on two lines, when we remove tags, this content gets concatenated. We know, that we can do some replacements, but hopefully there is a better path?

Thanks,
Ruslan.

**Comment by masseuro** [comment]
Maybe try with pandoc ? a html to markdown converter

**Comment by RuslanZavacky** [comment]
@masseuro we need to do it on frontend side, as the issue here is, we have some logic with switching between Email and Twitter channels, and if person was typing something to email channel, with HTML, and then switched back to Twitter, to get correct data, we have to remove HTML tags and count text differently, but to preserve "visual context" of new lines.

**Comment by stefanneculai** [comment]
No, there is no built-in method in editor for getting the text only and we believe this is out of the editor's scope. Converting HTML to TEXT is not as easy as it might look because of the way new lines have to be placed. https://github.com/werk85/node-html-to-text is a library which does that.
