### ISSUE TITLE
With BR enabled mode, first line is anyway <p> tag

### ISSUE THREAD

**Issue by RuslanZavacky** [froala/wysiwyg-editor#1275]
##### Expected behavior.
If we enable `enter: $.FroalaEditor.ENTER_BR`, I expect that when I write first line and hit Enter, I'll get something like:

```
one<br/>
two<br/>
three<br/>
```

##### Actual behavior.
Instead, what we are getting is:

```
<p>one</p>
two
<br/>
three
```

##### Steps to reproduce the problem.
1. Enable `enter: $.FroalaEditor.ENTER_BR`
2. type several lines of text

##### OS.
OSX El Capitan

##### Browser.
Chrome 51

**Comment by stefanneculai** [comment]
What are you initializing the editor with?

**Comment by RuslanZavacky** [comment]
@stefanneculai empty line

**Comment by stefanneculai** [comment]
I cannot reproduce it with the current master. Could you make a jsFiddle? Thank you.

**Comment by RuslanZavacky** [comment]
@stefanneculai I can't reproduce it with jsfiddle for pure editor, but I think the problem is in ember addond, here:

https://github.com/froala/ember-froala-editor/blob/master/addon/components/froala-editor.js#L31

if the content is empty, it will always initialize it with <p><br/></p>, regardless of component option set to be just <br/>

**Comment by stefanneculai** [comment]
That is right, is should be a blank string instead. Could you please make a PR there? Thank you.
