### ISSUE TITLE
Is there a way how to trigger Media dropdown from external button?

### ISSUE THREAD

**Issue by RuslanZavacky** [froala/wysiwyg-editor#1276]
We use only content area of Froala right now, because our toolbar is quite complicated with different other options. So we build buttons manually, is there a way, how we can trigger on custom external button a this Media dropdown:

![screen shot 2016-05-18 at 18 24 43](https://cloud.githubusercontent.com/assets/103556/15368517/131e2ede-1d26-11e6-80b5-2d9deb4d4aea.png)

Thanks!

**Comment by stefanneculai** [comment]
Hi Ruslan! We use this repo for bug tracking only. For tech support please contact us via [our website](https://www.froala.com/wysiwyg-editor/contact). Thanks!
