### ISSUE TITLE
Image Upload in Laravel

### ISSUE THREAD

**Issue by JoshuaBedford** [froala/wysiwyg-editor#1280]
##### Expected behavior.
I have a FileUploadsController where I handle the file and store it, but it never reaches the FileUploadsController. Regular html file upload buttons work fine, but I tried a dd() before anything else and it did nothing. I have a route setup to accept a post request to fileUpload/{id}/post, and I'm sending it to fileUpload/9/post via the imageUploadURL option. It never reaches the controller. I can't figure out why.

##### Actual behavior.
Regular html file upload buttons work fine, but I tried a dd() before anything else and it did nothing. I figured maybe because its an ajax request. So I then tried flashing a message to the session and accessing it, but it never flashed to the session.

##### Steps to reproduce the problem.
(Describe the steps to reproduce the problem here)

##### OS.
OSX Yosemite Version 10.10.5

##### Browser.
Chrome - Version 50.0.2661.102 (64-bit)

**Comment by stefanneculai** [comment]
Hi Joshua! This looks like a problem on your server side, not editor. We use this repo for bug tracking only. If you have questions or need help integrating the editor please [contact us](https://www.froala.com/wysiwyg-editor/contact) instead of opening an issue.
