### ISSUE TITLE
Toolbar is not showing at the bottom on iOS

### ISSUE THREAD

**Issue by modev32** [froala/wysiwyg-editor#1281]
##### Expected behavior.
Toolbar to be set at the bottom of the editor using `toolbarBottom: true`

##### Actual behavior.
Toolbar stay at the top

##### OS.
iOS 9.3.2 iPhone SE

##### Browser.
Chrome and Safari

**Comment by stefanneculai** [comment]
Unfortunately, this option is not available on touch devices because of system limitations.

**Comment by modev32** [comment]
It dose work on Android

**Comment by stefanneculai** [comment]
Sorry, by touch devices in the last email, I was referring to the iOS ones.

**Comment by jturmel** [comment]
Is there anymore reason on this? Or worth looking at again?

**Comment by weerdm** [comment]
Bump. I don't see any reason why this would not work on IOS.
