### ISSUE TITLE
Accessibility: Can't tab to controls

### ISSUE THREAD

**Issue by dlo83** [froala/wysiwyg-editor#1284]
##### Expected behavior.
Should be able to tab to text editor controls

##### Actual behavior.
Skipped right to text editor window

**Comment by stefanneculai** [comment]
Actually, you should be able to bring focus to the toolbar from the editable area. It's not a good idea to have to tab through buttons before getting the focus to the main editable area.

**Comment by dlo83** [comment]
Fair enough, but I wasn't able to figure out how to bring focus to the toolbar from the editable area, at least through tabbing.

**Comment by jaxyeh** [comment]
@stefanneculai This "accessibility" issue was the only issue when we evaluated the Froala wysiwyg-editor solution. We were not able to gain "focus" on the toolbar. We also tried to "tab" over inline toolbar after pressing `CTRL + E` keyboard shortcuts, but it did not work either. Hopefully you can consider this a prioirity feature request.

**Comment by stefanneculai** [comment]
I changed this to `feature-request` and it will come over the following months. We're currently working on this feature.
