### ISSUE TITLE
Extra characters ("") are being added in iframe's body when applying bold/italic 

### ISSUE THREAD

**Issue by yiannakasgeorge** [froala/wysiwyg-editor#1287]
##### Expected behavior.
Shouldn't add extra chars to iframe's body

##### Actual behavior.
Every time you apply bold/italic, an extra "" is added to the iframe's body

##### Steps to reproduce the problem.
https://jsfiddle.net/vspan7/uh5xm8d3/13/

##### OS.
El capitan

##### Browser.
Chrome Version 50.0.2661.102 (64-bit)

**Comment by stefanneculai** [comment]
It's not actually an issue because it doesn't affect in any way the output. I marked it as `enhancement`.

**Comment by stefanneculai** [comment]
I just checked this and we believe that this is actually a render problem of the browser console. If you would search for the parent of that element in DOM and check the childNodes then those `""` are not there.
