### ISSUE TITLE
Firefox hangs in code view with large base64 encoded images

### ISSUE THREAD

**Issue by nozpheratu** [froala/wysiwyg-editor#1292]
##### Expected behavior.
Functioning code view with base64 encoded image tag.

##### Actual behavior.
Script becomes unresponsive.

##### Steps to reproduce the problem.
Use code view with code mirror plugin enabled when a large base64 encoded image is present.

Here's a sample snippet that can be used to reproduce the issue:
https://gist.github.com/nozpheratu/c3dd047467de27fd7a047bad394ddda0

##### OS.
Ubuntu 12.04

##### Browser.
Firefox 46.0

**Comment by stefanneculai** [comment]
That is because there is a very high amount of text there to render. That is why we don't recomment at all to use images as base64.
