### ISSUE TITLE
Is it possible to convert html code(s) in real time?

### ISSUE THREAD

**Issue by freeads777** [froala/wysiwyg-editor#1293]
For instance instead of:

`<a href="http://somedomain.com">Some Text</a>`

it would show a clickable Some Text.

My users post quite a bit of html code (copy and paste) and it would be a huge turn off to them if it's not converted in real time.

Would appreciate any help.

**Comment by stefanneculai** [comment]
We use GitHub Issues as the official bug tracker for the Froala WYSIWYG HTMl Editor. For questions or need help integrating the editor please [contact us](https://www.froala.com/wysiwyg-editor/contact) instead of opening an issue.
