### ISSUE TITLE
Enter on bullet should unindent

### ISSUE THREAD

**Issue by mrjlynch** [froala/wysiwyg-editor#1294]
##### Expected behavior.
![ezgif com-video-to-gif 2](https://cloud.githubusercontent.com/assets/3665457/15537263/baf28596-22b8-11e6-88ca-e1c6db55282f.gif)

##### Actual behavior.
![ezgif com-video-to-gif 1](https://cloud.githubusercontent.com/assets/3665457/15537177/3b10d422-22b8-11e6-9a32-1f732d89acd9.gif)

**Comment by stefanneculai** [comment]
The current behaviour is correct. 
- Hitting enter at the beginning of a list item (as you do in the 2nd recording) should create a new empty list item above. 
- Hitting enter at the end of a list item (as you do in the first recording) should create a new empty line an put the cursor inside it and hitting enter again should get you out of the list.

**Comment by mrjlynch** [comment]
The first recording is from msword. Changing the behaviour would improve compatibility with word.

**Comment by stefanneculai** [comment]
In the 2nd recording you're hitting enter in a different place: at the beginning of a list item instead of at the end of a list item.

**Comment by mrjlynch** [comment]
Very true, my apology.
