### ISSUE TITLE
Wrap selection in HTML tag inside of a custom Popup

### ISSUE THREAD

**Issue by cristianst** [froala/wysiwyg-editor#1295]
##### Expected behavior.
I expect to have the selection stored somewhere and somehow in order to use it inside of a popup.

##### Actual behavior.

![toolbar](https://cloud.githubusercontent.com/assets/11995461/15544034/922c0b80-2297-11e6-8a3f-bd1754245aa4.png)

After clicking the Tooltip Button (Last one). It seems like the selection gets lost.

![toolbar2](https://cloud.githubusercontent.com/assets/11995461/15544109/e173c502-2297-11e6-9de8-b51f0966b4a1.png)

The code inside of the initPopup function: 

```javascript
editor.popups.onHide('tooltipPlugin.popup', function () {
     editor.selection.restore() // this returns false 
     // at this part of the code editor.selection.get() returns empty values
     editor.format.apply('span', { class: 'foo' });
     editor.selection.save();
});
```

##### OS.
MAC

##### Browser.
Chrome

**Comment by cristianst** [comment]
How do you do it e.g with the Link creator? Its actually the same thing isnt it? href is the text that the user enters and the selection gets "wrapped" in a <a> tag.

**Comment by stefanneculai** [comment]
We use GitHub Issues as the official bug tracker for the Froala WYSIWYG HTMl Editor. For questions or need help integrating the editor please [contact us](https://www.froala.com/wysiwyg-editor/contact) instead of opening an issue.
