### ISSUE TITLE
Language isn't changing until page refresh

### ISSUE THREAD

**Issue by kotmatpockuh** [froala/wysiwyg-editor#1300]
##### Expected behavior.
When i run such command:

```
$('.myEditor').froalaEditor({
  language: 'en'
});
```
the language is changing

##### Actual behavior.
Language isn't changing. It's changing only after setting editor options and page refresh

##### Steps to reproduce the problem.
Try to run code above

##### OS.
Windows 7

##### Browser.
Chrome 50.0.2661.102 m

**Comment by stefanneculai** [comment]
Language cannot be set after initializing the editor. It has to be destroyed and initialized again with the new option.

**Comment by kotmatpockuh** [comment]
@stefanneculai  how is it possible to re-init wysiwyg in angular?

**Comment by stefanneculai** [comment]
You can destroy the editor instance by calling the `destroy` method. Then you can reinitialize it manually: https://github.com/froala/angular-froala/blob/master/demo/index.html#L82.
