### ISSUE TITLE
Unnecessary console.log on paste

### ISSUE THREAD

**Issue by yivo** [froala/wysiwyg-editor#1301]
When you paste something editor outputs this in console. (js/froala_editor.min.js)
<img width="866" alt="screen shot 2016-05-26 at 2 14 24 pm" src="https://cloud.githubusercontent.com/assets/7421323/15572953/7ff8fc06-234c-11e6-9af9-26e8080c792d.png">

**Comment by stefanneculai** [comment]
That is fixed in the current master.
