### ISSUE TITLE
Possible duplicate or broken CSS in froala_style.css

### ISSUE THREAD

**Issue by yivo** [froala/wysiwyg-editor#1304]
Please [this](https://github.com/froala/wysiwyg-editor/blob/master/css/froala_style.css#L115) and [this](https://github.com/froala/wysiwyg-editor/blob/master/css/froala_style.css#L226)

**Comment by stefanneculai** [comment]
Both rules are necessary: one is for images inside the editable area and one is for using the editor initialized directly on the image.
