### ISSUE TITLE
Fullscreen plugin adds z-index: 9990 to every parent node

### ISSUE THREAD

**Issue by yivo** [froala/wysiwyg-editor#1305]
<img width="968" alt="screen shot 2016-05-26 at 4 54 03 pm" src="https://cloud.githubusercontent.com/assets/7421323/15576869/a735dcba-2362-11e6-81dd-7fae008ca2b1.png">

This breaks my layout and this may have other side effects. Previously I was using version 2.0.1 and there was no such behaviour. Can this be optionally disabled? What if I want to control z-indexes, not froala?

**Comment by stefanneculai** [comment]
Fullscreen plugin is adding that `zIndex` when it gets to the fullscreen, but as soon as you toggle back, the `zIndex` is reset back to its original value.
