### ISSUE TITLE
Feature Request: insert font-awesome icons

### ISSUE THREAD

**Issue by mrjlynch** [froala/wysiwyg-editor#1307]
I would like to request the possibility to add font-awesome icons as a plugin like emoticons. 

These icons are already loaded by default, and they could complement the existing emoticons.

**Comment by stefanneculai** [comment]
The emoticons plugin is fairly easy to extend further. I put this on our TODO list and we'll add it if there is interest for it.

**Comment by connect-technologies** [comment]
yes. I'd like that too.

**Comment by joeworkman** [comment]
+1

**Comment by jeremylynch** [comment]
Hi @stefanneculai it looks like there is some interest in this. Any chance this is still on the TODO list? 

Thanks

**Comment by matsientst** [comment]
+1

**Comment by mr-manuel** [comment]
+1

**Comment by divdax** [comment]
+1

**Comment by poka4alov** [comment]
+1

**Comment by AhHa45** [comment]
+1

**Comment by divdax** [comment]
@stefanneculai any news on this request? 😄

**Comment by brycemelvin** [comment]
+1

**Comment by stefanneculai** [comment]
We've just put together a public roadmap with the most popular features. 😍 There you can vote your favorite one, provide feedback or make new suggestions: https://wysiwyg-editor-roadmap.froala.com/public.
