### ISSUE TITLE
Broken when having long text

### ISSUE THREAD

**Issue by Dielz98** [froala/wysiwyg-editor#1310]
##### Expected behavior.
Editor should stay still

##### Actual behavior.
![output_fny2zj](https://cloud.githubusercontent.com/assets/17416861/15610579/24f5f78c-2450-11e6-9a59-fea41f556c32.gif)

##### Steps to reproduce the problem.
See gif above

##### OS.
OSX El capitan

##### Browser.
Chrome

How to fix this?

**Comment by stefanneculai** [comment]
Please let us know the steps to reproduce this. Is it happening on our website as well?

**Comment by Dielz98** [comment]
Maybe should fix by not to sticky the toolbar. Have option to do that?

**Comment by stefanneculai** [comment]
There is an option to disable it: `toolbarSticky`. But how can we reproduce it?

**Comment by Dielz98** [comment]
`toolbarSticky: false` fixed the issue.

Something went wrong with my layout I guess

Thanks
