### ISSUE TITLE
Iframe ignoring min-height attr

### ISSUE THREAD

**Issue by rblin081** [froala/wysiwyg-editor#1311]
##### Expected behavior.
Body min-height should be same as minHeight init attr

##### Actual behavior.
min-height is not set to minHeight attr

##### Steps to reproduce the problem.

http://jsfiddle.net/f87p3s65/140/

![image](https://cloud.githubusercontent.com/assets/10778058/15619241/1ba9a590-2421-11e6-97dc-16ec82f06f0f.png)

##### OS.
Windows 7

##### Browser.
Chrome

**Comment by stefanneculai** [comment]
The option is called `heightMin`, not `minHeight`. When option `height` is set, the option `heightMin` and `heightMax` are ignored.
