### ISSUE TITLE
 froala Cannot read property 'fn' of undefined 

### ISSUE THREAD

**Issue by Cydmi** [froala/wysiwyg-editor#1312]
#``  {
                test: require.resolve("./src/plugins/froala_editor.min"),
                loader: "imports?$=jQuery"
            }
``
var $=require("jquery");
 
webpack  chrome console error :  Uncaught TypeError: $(...).editable is not a function 

@stefanneculai

**Comment by stefanneculai** [comment]
See https://github.com/froala/wysiwyg-editor/issues/1134.
