### ISSUE TITLE
Make a word bold, delete a letter of that word and then type

### ISSUE THREAD

**Issue by yiannakasgeorge** [froala/wysiwyg-editor#1314]
##### Expected behavior.
New letter should be in bold

##### Actual behavior.
New letter is not in bold

##### Steps to reproduce the problem.
http://g.recordit.co/u2GpytAtrD.gif

##### OS.
Elcapitan

##### Browser.
Version 50.0.2661.102 (64-bit)

**Comment by stefanneculai** [comment]
Unfortunately, that's a `wontfix`. This is the way browsers recognize it.
