### ISSUE TITLE
requirejs  AMD editable. afterImageUpload events can not be executed!!

### ISSUE THREAD

**Issue by Cydmi** [froala/wysiwyg-editor#1315]
`define(["jquery","froala_editor"], function($) {`
    `$(function() {`
     ` $('#edit').editable({inlineMode: false});`
      `$('#edit').on('editable.afterImageUpload', `
	` function (e, editor, response) {`
           ` console.log(response);`
   ` });`
    `});`
`});`
froala_editor v 1.2.0

Your examples directory require_js

**Comment by stefanneculai** [comment]
We do not maintain V1 of the editor anymore. Please upgrade to V2 instead.
