### ISSUE TITLE
mouseup unbindung in custom popup

### ISSUE THREAD

**Issue by henningborchers** [froala/wysiwyg-editor#1316]
##### Expected behavior.
I need to create a colorpicker plugin for your editor. The spectrum colorpicker (https://github.com/bgrins/spectrum) should work in the popup in inline mode

##### Actual behavior.
The colorpicker selection dont stops on mouseup, because the mouseup event is overwritten by froala.

##### Steps to reproduce the problem.
(Describe the steps to reproduce the problem here)

##### OS.
OSX

##### Browser.
Chrome, latest

**Comment by stefanneculai** [comment]
Indeed, the popups are stopping some mouseup/mousedown events inside the popups so that the focus/blur events work correctly. However there are some possible workarounds. We got your email and we're waiting more details there. Thank you.
