### ISSUE TITLE
FontSizeSelection, FontFamilySelection, and ParagraphFormatSelection do not refresh.

### ISSUE THREAD

**Issue by Spicykoala** [froala/wysiwyg-editor#1318]
##### Expected behavior.
When clicking around in the editor the fontSizeSelection, fontFamilySelection, and paragraphFormatSelection in the toolbar should update their respective values.

##### Actual behavior.
They toolbar doesn't change.

##### Steps to reproduce the problem.
https://jsfiddle.net/j62m8b8n/

##### OS.
Mac El Capitan 10.11.3
Windows 10

##### Browser.
Chrome Version 50.0.2661.102 (64-bit)
Firefox 46.0.1

**Comment by stefanneculai** [comment]
It's not an editor problem. This is happening because you have `contenteditable` property set to the div on which you're initializing the editor. Removing that will make it work just fine.
