### ISSUE TITLE
Text Jumps Around When Applying Font Size/Color/Family

### ISSUE THREAD

**Issue by Spicykoala** [froala/wysiwyg-editor#1319]
This bug can be reproduced here: https://www.froala.com/wysiwyg-editor

##### Expected behavior.
1) Highlight word "users" and set font size to 30: "users" should have font size 30 and remain in place.
2) Highlight word "easy" and set font size to 30: "easy" should have font size 30 and remain in place.

##### Actual behavior.
Highlighting "users" and setting font size works as expected. However, afterwards, when you highlight "easy" and set the font size - it jumps next to the word "users".

##### Steps to reproduce the problem.
See Above - This bug happens for font size, color, and font family.

##### OS.
Mac El Capitan 10.11.3

##### Browser.
Chrome Version 50.0.2661.102 (64-bit)

**Comment by maxmas** [comment]
1) Set "users" font size to 30: "users" have font size 30 and remain in place.
2) Set "easy" font size to 30: "easy" jumps next to the word "users".
