### ISSUE TITLE
toolbarSticky true only works on unfocus -> focus

### ISSUE THREAD

**Issue by jpgilchrist** [froala/wysiwyg-editor#1322]
##### Expected behavior.
The toolbar should be sticky in the screen according to it's toolbarStickyOffset as scrolling is happening.

##### Actual behavior.
The toolbar is not sticky until you unfocus, then refocus the editable area. 

##### Steps to reproduce the problem.

Observe that I "click" outside the editor and then click back in and voila the toolbar snaps to it's appropriate position. I'm assuming I have something wrong or our webpage is hijacking an event of sorts, but I'm looking for reasons why this could/would break like this.

I'm not sure how long this url will last (using a free version to screen capture). Let me know if I need to get something better together.

![froala sticky issue](https://cloud.githubusercontent.com/assets/5065660/15782263/98122048-2977-11e6-8e4e-812f0f8fce37.gif)

##### OS.
OS X El Capitan

##### Browser.
Chrome Version 51.0.2704.63 (64-bit)

**Comment by stefanneculai** [comment]
It is impossible for us to help you with that without having the steps to reproduce the issue.

**Comment by jpgilchrist** [comment]
@stefanneculai what information do you need? My question to you is mainly, what could potentially cause this? I assume you have a piece of code that runs on scroll event that should toggle .fr-sticky-on and .fr-sticky-off? That trigger is not happening until the focus, unfocus event. 

I honestly don't expect you to be able to reproduce it. I'm just looking for some insight as to why or how this could happen. I guess I'll download the  un-minified copy of the source code and read it for myself. Would this be more appropriate to submit as a ticket to our paid account support?

Here are my options: 

```
        var opt = {
                heightMax: this.options.maxHeight,
                heightMin: this.options.minHeight,
                toolbarBottom: this.options.toolbarBottom || false,
                toolbarSticky: this.options.toolbarSticky || false,
                toolbarStickyOffset: 66, // the height of the bread crumb wrapper
                toolbarInline: false,
                theme: 'gray',
                spellcheck: true,
                enter: $.FroalaEditor.ENTER_BR,
                htmlRemoveTags: ['script'],
                imageDefaultDisplay: 'inline',
                imagePaste: false,
                imageMove: false,
                imageResize: false,
                imageDefaultWidth: 200,
                // image upload options
                imageUploadParam: "files[]",
                imageUploadURL: top.CONTEXT + '/api/' + self.options.container().id + '/files/?_st=' + top.CSRF_TOKEN + "&inline=true&editor=froalaV2",
                imageUploadMethod: "POST",
                imageMaxSize: maxUploadSize,
                imageAllowedTypes: ["gif", "jpeg", "jpg", "png"],
                // file upload options
                fileUploadParam: "files[]",
                fileUploadURL: top.CONTEXT + '/api/' + self.options.container().id + '/files/?_st=' + top.CSRF_TOKEN + "&inline=true&editor=froalaV2",
                fileUploadMethod: "POST",
                fileMaxSize: maxUploadSize,
                fileAllowedTypes: this.options.imageOnly ? ["image/gif", "image/jpeg", "image/png"] : ["*"],
                // toolbar options
                toolbarButtonsXS: this.options.froalaV2Buttons,
                toolbarButtonsSM: this.options.froalaV2Buttons,
                toolbarButtonsMD: this.options.froalaV2Buttons,
                toolbarButtons: this.options.froalaV2Buttons,
            };
```

**Comment by stefanneculai** [comment]
It is hard to tell what could be without being able to reproduce it. The toolbar is being positioned based on the scrollableContainer scrolling in the page.

**Comment by jpgilchrist** [comment]
That was it! I hadn't set the scrollableContainer option. I hadn't set the "scrollableContainer" option; the default of "body" was invalid because it wasn't the body that was scrolling.
