### ISSUE TITLE
Editor in Jquery UI Dialog Edit Link - bad selector?

### ISSUE THREAD

**Issue by jpgilchrist** [froala/wysiwyg-editor#1327]
##### Expected behavior.
1. Create a link
2. Click edit link in inline popup
3. Be able to see the link-insert-layer popup.

##### Actual behavior.
1. Create a link
2. Click edit link in inline popoup
3. link-insert-layer popup is added to the DOM, but fr-active is not added to the root of the popup's tree.

##### Steps to reproduce the problem.
If you need more information please request. Here's a gif to show the steps.

https://download.veoci.com/Q2cMTDZ8Hn6qgQ9R/froala-link-insert-layer-issue.gif

##### OS.
OSX El Capitan

##### Browser.
Chrome Latest

**Comment by stefanneculai** [comment]
Could you please make a jsFiddle for it?

**Comment by jpgilchrist** [comment]
Do you have a base jsfiddle with all the libraries included?

**Comment by stefanneculai** [comment]
https://jsfiddle.net/zz5zew0o/

**Comment by jpgilchrist** [comment]
This is purely a scrollableContainer issue. I didn't realize how important this option is... perhaps it should be heavily emphasized in the documentation. But as far as this issue is concerned, it's not a problem.
