### ISSUE TITLE
Font-size generating extra span

### ISSUE THREAD

**Issue by rblin081** [froala/wysiwyg-editor#1328]
##### Expected behavior.
Wrapper span's should only be around content and not be empty

##### Actual behavior.
Changing font size is generating a trailing span tag with no content

##### Steps to reproduce the problem.

1) Type Hello
2) Set font-size of entire word 60px
3) Highlight part of the word and change the font size to 24px
4) View code, there will be a trailing span tag with no content

`<span style="font-size: 60px;">He</span><span style="font-size: 24px;">llo</span><span style="font-size: 60px;"></span>
`

##### OS.
Windows

##### Browser.
Chrome

**Comment by stefanneculai** [comment]
We couldn't reproduce it. Are there any specific configurations?

**Comment by rblin081** [comment]
I consistently reproduce on the provided fiddle on Chrome using the steps I
listed

**Comment by stefanneculai** [comment]
@rblin081 there is no jsFiddle there. I believe you missed it :-)

**Comment by rblin081** [comment]
Arghhh. That's what I get for not looking at the original thread.
http://jsfiddle.net/f87p3s65/142/
