### ISSUE TITLE
Paragraph formatting is lost when the text of the single paragraph is replaced

### ISSUE THREAD

**Issue by FinesseRus** [froala/wysiwyg-editor#1329]
##### Expected behavior.
The paragraph doesn't lose it's formatting.

##### Actual behavior.
The paragraph's formatting is reset.

##### Steps to reproduce the problem.
1. Type a single paragraph of text.
2. Apply some formatting to it (style, align, etc.).
3. Select the whole text of the paragraph.
4. Type or paste something.

Here is a video of reproducing: https://yadi.sk/i/Zl7uB8hesJbAP

This bug doesn't appear if the paragraph is not single (and only one paragraph is selected). Here is a video of an expected behavior: https://yadi.sk/i/-gKilBSdsJbL8

##### OS.
OS X 10.11.5

##### Browser.
Safari 9.1.1, Chrome 50, Firefox 46.0.1

**Comment by masseuro** [comment]
Did you try with this option https://www.froala.com/wysiwyg-editor/docs/options#keepFormatOnDelete

**Comment by stefanneculai** [comment]
Enabling the option @masseuro suggested should get it work the way you want.

**Comment by FinesseRus** [comment]
@masseuro It works. Thank you!
