### ISSUE TITLE
Bullet error with pasted content

### ISSUE THREAD

**Issue by mrjlynch** [froala/wysiwyg-editor#1332]
##### Expected behavior.
Occasionally, when pasting in content (eg. from MSWORD), HTML in froala looks like the following: 

```html
<ul>
	<li>

		<p>Test
			<br>First Bullet
			<br>Another Bullet
        </p>
	</li>
</ul>
```

This HTML causes errors when creating bullets (see the below GIF)

##### Actual behavior.
![ezgif com-video-to-gif 6](https://cloud.githubusercontent.com/assets/3665457/15915030/2d9a3ca8-2e29-11e6-9fb5-74c5995e5a49.gif)

##### Steps to reproduce the problem.

Watch the included video. 

##### OS.
El Capitan

##### Browser.
Chrome

**Comment by stefanneculai** [comment]
That is the correct behaviour because you have new lines with BR inside a paragraph block. It is the same as having one line, converting it to list and then hitting SHIFT+ENTER at the end of the line.
