### ISSUE TITLE
Feature Request: Resizable Iframe

### ISSUE THREAD

**Issue by rblin081** [froala/wysiwyg-editor#1333]
Much like with images, the ability to dynamically resize iframes by selecting and dragging corners to increase / decrease size.

**Comment by stefanneculai** [comment]
That is already done for videos. It's unlikely to add such a feature in the editor because it can be easily achieved with a plugin.

**Comment by rblin081** [comment]
Interesting I did not know that. I have a couple of widgets that are
regularly used, wondering how easy it'd be to apply the code for the video
resize to these
