### ISSUE TITLE
Inserting contenteditable="false" elements causes unexpected behavior.

### ISSUE THREAD

**Issue by Spicykoala** [froala/wysiwyg-editor#1334]
##### Expected behavior.
- When a user places their cursor after 'B' and hits backspace. B should be removed.
- When a user places their cursor before 'A' and hits their right arrow twice, the cursor should be between 'B' and 'C'.
- When a user places their cursor after 'C' and hits their left arrow twice, the cursor should be between 'A' and 'B'.
- When a user places their cursor after 'C' and hits backspace, the cursor should be before B

##### Actual behavior.
- When a user places their cursor after 'B' and hits backspace nothing happens.
- When a user places their cursor before 'A' and hits their right arrow twice, the cursor ends up after 'C'.
- When a user places their cursor after 'C' and hits their left arrow twice, the cursor ends up before 'A'.
- When a user places their cursor after 'C' and hits backspace, the cursor jumps to the far right.

##### Steps to reproduce the problem.
Attempt expected behavior here in the Froala editor:
https://jsfiddle.net/5L5xytds/4/
I provided a straight html example that demonstrates what I would expect to see.

##### OS.
Mac El Capitan 10.11.3

##### Browser.
Chrome 51.0.2704.79 (64-bit)

**Comment by mwtorkowski** [comment]
I'm glad someone already raised this issue (less typing for me ;) ).

I just fixed it locally as I need to upgrade to latest version and maintain ability to remove contenteditable=false blocks.

I hope you can excuse screenshot with git diff from non-minified source (not saying this is a great fix, but for now it will do me fine until this is properly addressed by the Froala team; being able to remove non-editable blocks shouldn't be an enhancement, in my mind this is obvious bug; but I digress..):
![804](https://cloud.githubusercontent.com/assets/6072390/15962627/ba62c25c-2f0c-11e6-8ed4-9a998e09d6ab.png)

**Comment by stefanneculai** [comment]
@mwtorkowski we plan to add an option there for this behaviour. There are lots of users who want to prevent deleting these blocks.

**Comment by mwtorkowski** [comment]
@stefanneculai Got ya. I guess introducing and checking for `fr-deletable` is a start. There definitely should be a way to differentiate between non-editable and non-deletable blocks.

**Comment by stefanneculai** [comment]
Indeed and `fr-deletable` is experimental for now. Although, there are no known issues, we haven't had enough time to test it and that's why it is not documented anywhere on our website.

**Comment by Spicykoala** [comment]
Awesome. Thanks @mwtorkowski for that temporary solution and insight in to the problem. I should be able to make something work for now until there's a production ready solution.

**Comment by stefanneculai** [comment]
@Spicykoala @mwtorkowski `fr-deletable` should work without problems now with the current master.
