### ISSUE TITLE
custom dropdown missing `fr-selection` class

### ISSUE THREAD

**Issue by scottbarrow** [froala/wysiwyg-editor#1335]
##### Expected behavior.
expect button class to eq `fr-command fr-btn fr-dropdown fr-selection`

##### Actual behavior.
got `fr-command fr-btn fr-dropdown`

##### Steps to reproduce the problem.
Create a dropdown with `RegisterCommand`
View DOM

**Comment by stefanneculai** [comment]
`fr-selection` class is added if `displaySelection` property is passed as true when calling RegisterCommand.
