### ISSUE TITLE
Editor buttons bar takes up full height when resizing webpage in Chrome

### ISSUE THREAD

**Issue by DenisaSurdu** [froala/wysiwyg-editor#1336]
##### Expected behavior.
When resizing a page that has the editor, the editor buttons should not take up the full height of the webpage.

##### Actual behavior.
I'm using froala editor with angular within a web application. When I resize the Chrome webpage, the editor buttons bar takes up the full height of the page.

![image](https://cloud.githubusercontent.com/assets/4330214/15960149/6e18b84a-2ef6-11e6-9c84-d0bfd894d433.png)

From dev tools:

![image](https://cloud.githubusercontent.com/assets/4330214/15960310/225ccb02-2ef7-11e6-910a-c43d0d807408.png)

Froala version: froala_editor v2.2.4

My Froala config:
`
app.value('froalaConfig', {
'&quot;&iexcl;&cent;&pound;&curren;&yen;&brvbar;&sect;&uml;&copy;&ordf;&laquo;&not;&shy;&reg;&macr;&deg;&plusmn;&sup2;&sup3;' +
'&acute;&micro;&para;&middot;&cedil;&sup1;&ordm;&raquo;&frac14;&frac12;&frac34;&iquest;&Agrave;&Aacute;&Acirc;&Atilde;&Auml;&Aring;&AElig;&Ccedil;' +
'&Egrave;&Eacute;&Ecirc;&Euml;&Igrave;&Iacute;&Icirc;&Iuml;&ETH;&Ntilde;&Ograve;&Oacute;&Ocirc;&Otilde;&Ouml;&times;&Oslash;&Ugrave;&Uacute;&Ucirc;' +     '&Uuml;&Yacute;&THORN;&szlig;&agrave;&aacute;&acirc;&atilde;&auml;&aring;&aelig;&ccedil;&egrave;&eacute;&ecirc;&euml;&igrave;&iacute;&icirc;&iuml;' +  '&eth;&ntilde;&ograve;&oacute;&ocirc;&otilde;&ouml;&divide;&oslash;&ugrave;&uacute;&ucirc;&uuml;&yacute;&thorn;&yuml;&OElig;&oelig;&Scaron;&scaron;' +    '&Yuml;&fnof;&circ;&tilde;&Alpha;&Beta;&Gamma;&Delta;&Epsilon;&Zeta;&Eta;&Theta;&Iota;&Kappa;&Lambda;&Mu;&Nu;&Xi;&Omicron;&Pi;&Rho;&Sigma;&Tau;&Upsilon;' +
'&Phi;&Chi;&Psi;&Omega;&alpha;&beta;&gamma;&delta;&epsilon;&zeta;&eta;&theta;&iota;&kappa;&lambda;&mu;&nu;&xi;&omicron;&pi;&rho;&sigmaf;&sigma;&tau;' +    '&upsilon;&phi;&chi;&psi;&omega;&thetasym;&upsih;&piv;&ensp;&emsp;&thinsp;&zwnj;&zwj;&lrm;&rlm;&ndash;&mdash;&lsquo;&rsquo;&sbquo;&ldquo;&rdquo;' +   '&bdquo;&dagger;&Dagger;&bull;&hellip;&permil;&prime;&Prime;&lsaquo;&rsaquo;&oline;&frasl;&euro;&image;&weierp;&real;&trade;&alefsym;&larr;&uarr;' +
'&rarr;&darr;&harr;&crarr;&lArr;&uArr;&rArr;&dArr;&hArr;&forall;&part;&exist;&empty;&nabla;&isin;&notin;&ni;&prod;&sum;&minus;&lowast;&radic;&prop;' +
 '&infin;&ang;&and;&or;&cap;&cup;&int;&there4;&sim;&cong;&asymp;&ne;&equiv;&le;&ge;&sub;&sup;&nsub;&sube;&supe;&oplus;&otimes;&perp;&sdot;&lceil;' +
'&rceil;&lfloor;&rfloor;&lang;&rang;&loz;&spades;&clubs;&hearts;&diams;',
        charCounterCount: false,
        theme: 'gray',
        height: '250',
        inlineMode: false,
        imagePaste: true,
        linkAlwaysBlank: true,
        zIndex: 999,
        // We have to specify all 'toolbarButtons' options otherwise it will set the default values
        // see here https://www.froala.com/wysiwyg-editor/docs/options#toolbarButtons
        toolbarButtons: ['bold', 'italic', 'underline', 'color', 'paragraphFormat', 'align', 'formatOL', 'formatUL', 'outdent', 'indent',
                     'insertLink', 'insertImage', 'insertTable', 'undo', 'redo', 'html'],
        toolbarButtonsMD: ['bold', 'italic', 'underline', 'color', 'paragraphFormat', 'align', 'formatOL', 'formatUL', 'outdent', 'indent',
                     'insertLink', 'insertImage', 'insertTable', 'undo', 'redo', 'html'],
        toolbarButtonsSM: ['bold', 'italic', 'underline', 'color', 'paragraphFormat', 'align', 'formatOL', 'formatUL', 'outdent', 'indent',
                     'insertLink', 'insertImage', 'insertTable', 'undo', 'redo', 'html'],
        toolbarButtonsXS: ['bold', 'italic', 'underline', 'color', 'paragraphFormat', 'align', 'formatOL', 'formatUL', 'outdent', 'indent',
                     'insertLink', 'insertImage', 'insertTable', 'undo', 'redo', 'html'],
        paragraphFormat: {
            h2: 'Heading 1',
            h3: 'Heading 2',
            n: 'Normal',
            h6: 'Small'
        },
        imageInsertButtons: ['imageBack', '|', 'imageUpload', 'imageByURL'],
        imageEditButtons: ['imageDisplay', 'imageAlign', 'imageReplace', 'imageRemove', '|', 'imageLink', 'linkOpen', 'linkEdit', 'linkRemove', 'imageAlt', 'imageSize'],
        linkInsertButtons: ['linkBack'],
        useClasses: false
    });
`

##### Steps to reproduce the problem.
I have tried to replicate it on Froala website but for now, I am unable to do so.
In my application, I have managed to replicate it by:
- Opening a page in Chrome with the editor inside
- Resize the page - see the editor buttons bar taking up the full height of the page.

##### OS.
Widows 10

##### Browser.
Chrome Version 51.0.2704.84 m

**Comment by stefanneculai** [comment]
This is a Chrome problem that we reported to them (https://bugs.chromium.org/p/chromium/issues/detail?id=606331). We made a workaround for it in V2.3.0, so if you upgrade to the latest version you shouldn't have it anymore.

**Comment by DenisaSurdu** [comment]
Thanks, I will upgrade. 
Do you have a mailing list I can subscribe to for release notes - with explicit bug fixes? Unfortunately, the changelog https://www.froala.com/wysiwyg-editor/changelog is not helpful understanding what has been fixed and what was the bug.
It is painful have clients reporting bugs because they've updated their Chrome (in the above case) when I could have upgraded to a newer version of Froala and clients would have never been aware of this being a bug.

**Comment by stefanneculai** [comment]
We do our best to make the changelog as explicit as possible. Unfortunately, we don't have any mailing list with more explicit details.

**Comment by DenisaSurdu** [comment]
Could you provide the code change for just this fix - without doing a full upgrade? I would like to have only the fix for this bug within the  froala v2.2.4.
