### ISSUE TITLE
Editor not loading plugin buttons when the HTML-page is loaded as a iframe

### ISSUE THREAD

**Issue by rauwebieten** [froala/wysiwyg-editor#1338]
##### Expected behavior.
A html-page with a working froala editor: when this page is loaded inside a iframe, it should behave just like when not loaded inside a iframe.

##### Actual behavior.
No errors thrown, but editor buttons are not loaded (only bold/italic/undo/redo)

##### Steps to reproduce the problem.
create a page with an editor.
Run this page, works fine.
create a page with previous page inside a iframe, run this page and see problem.
See: http://jsbin.com/qoxaba/edit?html,js,output

##### OS.
win 10

##### Browser.
chrome 50.0
firefox 47.0

**Comment by stefanneculai** [comment]
That iframe has a small width and because of that the editor is showing the buttons for that specific screen size. See https://www.froala.com/wysiwyg-editor/docs/examples/custom-toolbar.
