### ISSUE TITLE
Block element with a toolbar covering the whole editor in Google Chrome and Opera

### ISSUE THREAD

**Issue by grrinch** [froala/wysiwyg-editor#1339]
##### Expected behavior.
As seen here:

[Froala expected layout](http://paluszak.me/github/froala/froala-expected-bc500c.png)

##### Actual behavior.
This is how it produces in Chrome:

[Froala actual look - everything is covered by a grey block div](http://paluszak.me/github/froala/froala-actual-97bb23.png)

##### Steps to reproduce the problem.
Create Froala instance with the below code:

`$('#content').froalaEditor({"height":800,"theme":"gray","language":"en_gb","charCounterCount":true,"placeholderText":"Write your content here...","spellcheck":true,"toolbarButtons":["bold","italic","underline","insertLink","|","paragraphFormat","align","fontSize","color","|","formatOL","formatUL","outdent","indent","|","insertTable","strikeThrough","subscript","superscript","insertHR","quote","|","undo","redo","|","html","fullscreen"],"toolbarInline":false});`

Output is ok, but a strange behaviour occurs (huge grey div) which covers the whole page.

See screenshot with the Inspect Element visible:

[This is the big grey block](http://paluszak.me/github/froala/froala-inspectcode-3ea2ca.png)

Not sure if it is applicable, but I'm using Yii2 plugin [from here.](https://github.com/froala/yii2-froala-editor). However the code it produces is just fine (snippet above).

I managed to discover that when the whole editor does not fit in the viewport, it's when this occurs. If I decrease the height so it fits in the window OR I decrease the magnification of the page, then it fits in the viewport and looks ok.

[Fits in viewport - OK](http://paluszak.me/github/froala/froala-fits-in-viewport-1a9064.png)
[Does not fit - the block appears](http://paluszak.me/github/froala/froala-does-not-fit-in-viewport-193878.png)

I also deleted my fixed header and found out that Froala's toolbar is just 100% in height and sticks to the top and bottom of the viewport.

[Looks like it's 100% in height](http://paluszak.me/github/froala/froala-the-toolbar-is-there-100percent-high-318000.png)

Additionally what might be worth mentioning, when I scroll the window, this grey "toolbar" block is flickering (visible/invisible).

**It is also important that Firefox is OK - the issue occurs in Google Chrome and Opera**.

##### OS.
Ubuntu 16.04 64bit
Windows 10 64bit

##### Browser.
Google Chrome 51.0.2704.84 (64-bit) (Ubuntu)
Google Chrome 51.0.2704.84 m (64-bit) (Windows 10)
Opera 38.0.2220.29 (Ubuntu)

##### JS libs
jQuery v2.2.3
froala_editor v2.2.4

**Comment by stefanneculai** [comment]
@grrinch What editor version are you using?

**Comment by grrinch** [comment]
@stefanneculai I updated the first comment:
jQuery v2.2.3
froala_editor v2.2.4

And also checked Opera producing the same behaviour.

**Comment by stefanneculai** [comment]
This is an issue introduced there in Chrome recently. We put a fix for it on V2.3.0 and also filled an issue to Chrome to report it: https://bugs.chromium.org/p/chromium/issues/detail?id=606331. Upgrading from V2.2.4 to V2.3.0 should fix the problem for you.

**Comment by grrinch** [comment]
Yes, it did fix the issue. Thanks :+1:
