### ISSUE TITLE
Placeholder text does not display correctly

### ISSUE THREAD

**Issue by Whyves** [froala/wysiwyg-editor#1340]
![froala placeholder error](https://cloud.githubusercontent.com/assets/11150345/16030842/4c8db19c-31c3-11e6-9846-3f41ad56e23b.png)
##### Expected behavior.
Display placeholder text correctly on one line

##### Actual behavior.
Upon load, the placeholder span has an harcoded style width of 0 pixels (see attached image) which displays the placeholder text on multiple lines. As soon as the editor gets the focus, the style width get recalculated and the placeholder text gets correctly displayed. Happens in Froala v2.3.2 and it didn't happen in v2.0.5. Actually v2.0.5 didn't have a CSS width set at all.

##### Steps to reproduce the problem.
Appears at load time

##### OS.
Ubuntu 14.04

##### Browser.
Chrome 50.0.2661.102 (64-bit)

**Comment by stefanneculai** [comment]
This should be fixed on the current master.

**Comment by justincy** [comment]
I'm still seeing this on v2.3.3

**Comment by dianaprajescu** [comment]
@justincy could you please make a jsFiddle?

**Comment by justincy** [comment]
Do you have a base example jsfiddle I could fork?

**Comment by justincy** [comment]
I figured out my issue. I had custom padding being applied to `<p>` tags. Which means my issue is not the same as the original issue. Sorry.

**Comment by kmkanagaraj** [comment]
Its still missing, 
https://www.froala.com/wysiwyg-editor/docs/examples/placeholder

**Comment by Whyves** [comment]
Same here, actually, if the textarea is a little bit taller, you get to see the placeholder text truncated and it only appears when you focus on the textarea.

**Comment by stefanneculai** [comment]
It's fixed on master.

**Comment by Whyves** [comment]
When do you intend on making an official release. It is easier for deployment :-)

**Comment by stefanneculai** [comment]
@Whyves  In the following days.
