### ISSUE TITLE
Pressing backspace while in table cell removes all content in that cell

### ISSUE THREAD

**Issue by mwtorkowski** [froala/wysiwyg-editor#1343]
##### Expected behavior.
When I press backspace while editing some content inside table cell I expect one character to be deleted.

##### Actual behavior.
Cell's entire content is removed on a single backspace press

##### Steps to reproduce the problem.
Insert table, put content (some random text will do) in some cells; focus on one cell (**by clicking on it!**), try to remove single character.

##### OS.
Ubuntu 14.10

##### Browser.
Chrome (latest)

Note I tried it both in our app and on froala's editor homepage - same result.

Edit:
Weird stuff - I took a look at the table plugin source and you purposely remove all content on backspace press - perhaps it was meant to remove all *selected* (highlighted) content?
![805](https://cloud.githubusercontent.com/assets/6072390/16108838/d6958372-33a5-11e6-9c0d-12f2d5094285.png)

Edit2:
It only happens if I click-to-focus on the cell content's I want to edit (blue highlight around cell appears). It DOES NOT happen if I focus on the cell using TAB key (for example)

For now, just to fix immediate issue I wrapped the block of code shown on screenshot above inside: `if (selected_cells.length > 1) {...}`. This way backspace only clears table cells content IF there's more than one cell selected, otherwise it doesn't interfere with editing the content (namely deleting some characters using backspace).

**Comment by stefanneculai** [comment]
Same with https://github.com/froala/wysiwyg-editor/issues/1331 and fixed.
