### ISSUE TITLE
Overflow-x auto on fr-element (should be visible)

### ISSUE THREAD

**Issue by jpgilchrist** [froala/wysiwyg-editor#1346]
##### Expected behavior.
Horizontal scrollbar should always be visible on an editor when the content is overflowing...

##### Actual behavior.
Horizontal scrollbar is only visible if you scroll to the bottom of the editor first...

##### Steps to reproduce the problem.

Paste this content into the editor on this page: [froala predefined height example](https://www.froala.com/wysiwyg-editor/docs/examples/predefined-height) (in html mode)

Then go back to view mode (non html code mode) and scroll to the bottom. Notice the horizontal scrollbar is only visible when scrolled all the way to the bottom. 

We solved this by overriding css:

```css
.fr-element {
  overflow-x: visible !important;
}
```

=====

```html
<p>Set a specific height to the WYSIWYG HTML editor using the <a href="../options#height" target="_blank" title="height option">height</a> option. If the text inside is longer, then the rich text editor will get a vertical scrollbar.</p>

<p>
	<br>
</p>

<p>
	<br>
</p>

<p>
	<br>
</p>

<p>
	<br>
</p>

<p>
	<br>
</p>

<p>
	<br>
</p>

<p>
	<br>
</p>

<p>
	<br>
</p>

<p>
	<br>
</p>

<p>
	<br>
</p>

<p>
	<br>
</p>

<p>
	<br>
</p>

<p>
	<br>
</p>

<p>
	<br>
</p>

<p>
	<br>
</p>

<table>
	<tbody>
		<tr>
			<td>asdfasdfasdfasdfasdfasfasdfasdfasdfasdfasdfadsfasdfasdf</td>
			<td>asdfasdfasdfasdfasdfasfasdfasdfasdfasdfasdfadsfasdfasdf</td>
			<td>asdfasdfasdfasdfasdfasfasdfasdfasdfasdfasdfadsfasdfasdf</td>
			<td>asdfasdfasdfasdfasdfasfasdfasdfasdfasdfasdfadsfasdfasdf</td>
			<td>asdfasdfasdfasdfasdfasfasdfasdfasdfasdfasdfadsfasdfasdf</td>
			<td>asdfasdfasdfasdfasdfasfasdfasdfasdfasdfasdfadsfasdfasdf</td>
			<td>asdfasdfasdfasdfasdfasfasdfasdfasdfasdfasdfadsfasdfasdf</td>
			<td>asdfasdfasdfasdfasdfasfasdfasdfasdfasdfasdfadsfasdfasdf</td>
			<td>asdfasdfasdfasdfasdfasfasdfasdfasdfasdfasdfadsfasdfasdf</td>
			<td>asdfasdfasdfasdfasdfasfasdfasdfasdfasdfasdfadsfasdfasdf</td>
			<td>asdfasdfasdfasdfasdfasfasdfasdfasdfasdfasdfadsfasdfasdf</td>
		</tr>
	</tbody>
</table>
```
=====

##### OS.
Mac OSX

##### Browser.
Chrome, Firefox, IE *

**Comment by stefanneculai** [comment]
The editor has by default `overflow-x: auto` and the scroll gets active if the width is larger.

<img width="343" alt="screen shot 2016-06-20 at 14 45 30" src="https://cloud.githubusercontent.com/assets/637004/16193075/b0808ea4-36f5-11e6-8f84-ab3bea4a059e.png">

**Comment by javeriaanwer** [comment]
Hi,

Same issue is occurring on my side , I am using froala in iframe (i.e set iframe: true), after that it is not setting class .fr-element on body, therefore overflow-x: auto is not set on froala editor. 

What's the work around?

Regards,

**Comment by javeriaanwer** [comment]
Hi,

I am still waiting for your response.

**Comment by stefanneculai** [comment]
@javeriaanwer please see: https://www.froala.com/wysiwyg-editor/docs/options#iframeStyle.

**Comment by satchamo** [comment]
@stefanneculai I have the same problem as the OP, and fixed it with the `overflow-x: visible` trick. Seems like a legitimate bug to me.

I think this example better illustrates the issue (follow the OP's instructions but use this code instead):
```<p>
	<br>
</p>

<p>
	<br>
</p>

<p>
	<br>
</p>

<p>
	<br>
</p>

<p>
	<br>
</p>

<p>
	<br>
</p>

<p>
	<br>
</p>

<p>
	<br>
</p>

<p>
	<br>
</p>

<p>
	<br>
</p>

<p>
	<br>
</p>

<p>
	<br>
</p>

<p>
	<br>
</p>

<p>
	<br>
</p>

<p>
	<br>
</p>

<p>
	<br>
</p>

<p>
	<br>
</p>

<p>
	<br>
</p>

<p>
	<br>
</p>

<p>
	<br>
</p>

<p>
	<br>
</p>

<p>
	<br>
</p>

<p>
	<br>
</p>

<p>
	<br>
</p>

<p>
	<br>
</p>

<p>
	<br>
</p>

<p>
	<br>
</p>

<p>
	<br>
</p>

<p>
	<br>
</p>

<p>
	<br>
</p>

<p>
	<br>
</p>

<p>
	<br>
</p>

<p>
	<br>
</p>

<p>
	<br>
</p>

<p>
	<br>
</p>

<p>
	<br>
</p>

<p>
	<br>
</p>

<p>
	<br>
</p>

<p>
	<br>
</p>

<p>
	<br>
</p>
<div style="width:10000px; border:1px solid black;">hi</div>
```
