### ISSUE TITLE
Feature? html.get vs codeView.get

### ISSUE THREAD

**Issue by jpgilchrist** [froala/wysiwyg-editor#1347]
##### Expected behavior.
I would like a way to generically get the codeView contents even if the codeView itself hasn't been initialized. The problem is that if you call `editor.html.get` while the `editor.codeView.isActive === true` then you don't get the changes. Additionally you cannot call `editor.codeView.get` universally because if the codeView hasn't been initialized then it throws an error:

```
VM463 code_view.min.js:7 Uncaught TypeError: Cannot read property 'val' of undefined(…)d @ VM463 code_view.min.js:7(anonymous function) 
```

I can do the following to semi resolve the issue:

```javascript
if (editor.codeView.isActive()) {
  return editor.codeView.get();
}
return editor.html.get();
```

The problem with this is that the contents are formatted differently. And I would to access the contents in a more consistent manner.

##### OS.
El Capitan

##### Browser.
Chrome

**Comment by jpgilchrist** [comment]
I also can do this, but it's kind of ugly.

```javascript
 this.editor.codeView.get().replace(/[\t\n]+/, "");
```

to normalize the output, but I don't really like that... what if it's formatted with spaces per the codeMirrorOptions, etc.

**Comment by stefanneculai** [comment]
@jpgilchrist `html.get` is designed to return the current HTML from the editor. While editing in code view mode, we consider that being an intermediary step and not the final HTML. Please read more about that on https://github.com/froala/wysiwyg-editor/issues/1297#issuecomment-221818721.
