### ISSUE TITLE
Multiple editors flickering on Chrome when scrolling

### ISSUE THREAD

**Issue by alexsup** [froala/wysiwyg-editor#1348]
##### Expected behavior.
Until recently, as I scrolled down the page, each editor would snap to a fixed position and I would happily edit the page.

**Note:** This only happens in Chrome and I am using Froala v2.3.2.

##### Actual behavior.
Now, the editor flicks between the top of the screen and the original element position. When it is fixed to the top of the screen, the editor is empty. When it is at the original element position, it has text visible.

##### Steps to reproduce the problem.
With Chrome version 51.0.2704.103 (64-bit), create two instances of Froala and pre-fill with text longer than the screen (I have 447 chars in first and 6000 chars in second).

Then scroll.

##### OS.
OSX 10.11.4 (15E65)

##### Browser.
51.0.2704.103 (64-bit)

**Comment by alexsup** [comment]
@stefanneculai Of course.

**Comment by alexsup** [comment]
@stefanneculai Here you go: https://jsfiddle.net/2zywqjj9/2/

**Comment by stefanneculai** [comment]
The jsFiddle you sent is using V2.0.0-rc3. Using any version higher than 2.3.0 doesn't have this problem.
