### ISSUE TITLE
image list/upload/delete

### ISSUE THREAD

**Issue by yarb2221** [froala/wysiwyg-editor#1353]
##### Expected behavior.
Using the image manager plugin I would expect to be able to list, upload and delete images

##### Actual behavior.
When using drag and drop or click to select image, always getting error that the "object does not support this property or method". This occurs in IE 10-11, same code is working as expected in Chrome,Safari and Firefox. 
Selecting browse option to list images produces error "The data necessary to complete this operation is not yet available". This also occurs in IE 10-11, same code is working as expected in Chrome, Safari and Firefox.

I am using froala version 2.3.3 

##### Steps to reproduce the problem.
Use image manager plugin in IE 10-11 to list, upload or delete images

##### OS.
Windows

##### Browser.
IE 10-11

**Comment by stefanneculai** [comment]
Are you experiencing the same problem on our website as well?

**Comment by yarb2221** [comment]
I have not tried it there. The problems seems to persist from froala_editor.js from the xhr request, line 4868. It acts like an issue related to CORS but it is not crossing domains as the upload path is a relative path.

Sent from my iPhone

On Jun 22, 2016, at 12:34, Stefan Neculai <notifications@github.com<mailto:notifications@github.com>> wrote:


Are you experiencing the same problem on our website as well?

-

**Comment by stefanneculai** [comment]
I am closing this due to lack of response. In case you can provide the details for us to reproduce it, we're happy to check it further.
