### ISSUE TITLE
Incorrect image editing menu position

### ISSUE THREAD

**Issue by Dattaprasad-Choukekar** [froala/wysiwyg-editor#1354]
##### Expected behavior.
We use "scrollableContainer" option while initializing editor.

When clicked on image in the editor, edit image menu should appear just above or below the image.

##### Actual behavior.

When clicked on image in the editor, edit image menu appears always aligned right side of the editor.
![popup](https://cloud.githubusercontent.com/assets/13338032/16275294/b78d8c1e-38a9-11e6-95a2-949b847afe65.jpg)

##### Steps to reproduce the problem.
use "scrollableContainer" option.
Place html file in 'html' folder in examples.

[Froala_Error_Menu.zip](https://github.com/froala/wysiwyg-editor/files/328352/Froala_Error_Menu.zip)

##### OS.
Windows 10

##### Browser.
Chrome latest

**Comment by stefanneculai** [comment]
That has been fixed in commit 4113307. Please upgrade to the Github master to fix it.

**Comment by Dattaprasad-Choukekar** [comment]
This issue is occuring in latest version 2.3.3. As far as I know version 2.3.3 contains fix 4113307.
Note that its not the duplicate of  #1342. Its different issue. Kindly refer to html exemple attached.

**Comment by stefanneculai** [comment]
@Dattaprasad-Choukekar, there was indeed a small problem that we fixed. However, please be aware that in the zip you sent you are setting the scrollable container to `#edit` which is the same element you're initializing the editor on which is not correct. scrollableContainer should be a parent of the element on which you're initializing the editor.

**Comment by Dattaprasad-Choukekar** [comment]
Thanks for the quick fix! I got your point about the parent container.
I would like to know how to get this fix in version 2.3.3 or do I have to wait until release of version 2.3.4?

**Comment by stefanneculai** [comment]
That is going to be included in V2.3.4. In the meanwhile you could download it from Github and use it.

**Comment by sangyoo91** [comment]
I'm having a same problem when `overflow-x: hidden` is added to the `body`.
