### ISSUE TITLE
Async call to retrieve file upload url

### ISSUE THREAD

**Issue by antho1404** [froala/wysiwyg-editor#1356]
##### Expected behavior.
I want to create a specific upload url with some parameters specific to the file (fetched from an api with something similar to [this](https://devcenter.heroku.com/articles/s3-upload-node)) so it could be nice to have one of those solutions:
- **imageUploadURL** accepting a function with the file in parameter that return either a string or a promise with a string as response
- **image.imageUploadURL** accept promise as result of the function and reject upload is the promise is rejected or the function return false like right now (the upload url can be directly updated in the promise, accessing the editor in parameter)

##### Actual behavior.
Right now the upload url can be only a string given in a syncrone way so it's not possible to fetch any url from server or any asyncrone call.

##### Steps to reproduce the problem.
Create an editor with the image plugin, and upload an image

##### OS.
any

##### Browser.
any

**Comment by stefanneculai** [comment]
Thanks for the suggestion @antho1404. Actually we're currently working on a new feature for that. I am closing this for now because we keep here only bugs/enhancements not feature requests.

**Comment by vanerleo** [comment]
Has this been released?

**Comment by stefanneculai** [comment]
@vanerleo not yet.

**Comment by markedmondson** [comment]
I'd love to see promises implemented on the afterPaste event too!

**Comment by kristian-puccio** [comment]
same...

**Comment by kristian-puccio** [comment]
same

**Comment by stefanneculai** [comment]
We've just put together a public roadmap with the most popular features. 😍 There you can vote your favorite one, provide feedback or make new suggestions: https://wysiwyg-editor-roadmap.froala.com/public.

**Comment by sivaraman-27** [comment]
Is this implemented?
