### ISSUE TITLE
Custom error message can't be display while upload the image

### ISSUE THREAD

**Issue by muthukumarg** [froala/wysiwyg-editor#1358]
#### Custom error message

       i can't able to display the custom error message, it's  **Something went wrong. Please try again**   in the image upload popup/popover 

we need to display the custom error message there

**Comment by stefanneculai** [comment]
Here is how you can edit it:
```js
var $popup = editor.popups.get('image.insert');
var $layer = $popup.find('.fr-image-progress-bar-layer');
$layer.find('h3').text('Your message';
```

*We use GitHub Issues as the official bug tracker for the Froala WYSIWYG HTMl Editor therefore for tech support please contact us via our website.*
