### ISSUE TITLE
Internet Explorer html4 issue

### ISSUE THREAD

**Issue by rwaters71** [froala/wysiwyg-editor#136]
This html4 code in the textarea breaks the editor in Internet Explorer (Windows 7 x64, IE v.11 in my case). Firefox/Chrome are not affected, it seems.

``` html
<table>
  <tr>
    <td valign="top" align="left">text</td>
  </tr>
</table>
```

Other non-HTML5 attributes may have similar effect, such as: cellspacing=.. cellpadding=...

Here is another snippet that breaks the editor in IE for me:

``` html
<font color="#808000" size="2">text</font>
```

**Comment by sngmanish** [comment]
Is there a workaround for this issue? 
Many tools still export code in HTML4, and when this code is pasted into Froala, it causes the template to break due to deprecated attributes and tags in HTML5.
