### ISSUE TITLE
Image src is escaping blob URLs

### ISSUE THREAD

**Issue by rubyruy** [froala/wysiwyg-editor#1360]
The content I am setting using `html.set` uses `<img src="blob:..." />` but getting it back using `html.get` I see the `:` is being escaped. 

We need to use blob URLs for images because of the way our content management backend works.

**Comment by rubyruy** [comment]
I will also note that this behavior is somewhat inconsistent with the `image.insert` command which by default does not sanitize image URLs. It means images inserted with the editor's own API cannot be re-displayed by itself.

**Comment by stefanneculai** [comment]
@rubyruy last commit fixes it. Regarding `image.insert`, it takes a 2nd parameter `sanitize` which when is `true` the URL is sanitized.
