### ISSUE TITLE
html.get returns all HTML code into single line

### ISSUE THREAD

**Issue by mitulgolakiya** [froala/wysiwyg-editor#1361]
##### Expected behavior.
When I call `html.get` method it should return HTML code into the formatted format. Even I am using code mirror and code_beautifier plugin.

##### Actual behavior.
It's returning the whole code into just single line.

##### Steps to reproduce the problem.
Just normal steps. Use simple example of getting started page and insert some code. Then call,
`$('#edit').froalaEditor('html.get', true)`

##### OS.
MacOS, Version 2.3.2

##### Browser.
Google Chrome

OR Is there any way to get formatted HTML code ?

**Comment by stefanneculai** [comment]
The code beautifier is just for showing the code beautified in code view. It is not possible to get the code beautified and actually I don't see any reason for doing that. If you want to have to code beautified, I would recommend to use a 3rd party plugin to format the outputted HTML.
