### ISSUE TITLE
editor.commands.applyProperty is not a function

### ISSUE THREAD

**Issue by escopecz** [froala/wysiwyg-editor#1362]
##### Expected behavior.

A user should be able to change the color.

##### Actual behavior.
Instead it does nothing and this error message appears in the console:

`editor.commands.applyProperty is not a function`

##### Steps to reproduce the problem.
A Froala editor initiated on a textarea. Type something in it, select it, try to change the font color or the background color.

##### OS.
Ubuntu 16.04
but reported also by user who uses OSX.

##### Browser.
Chromium 50

**Comment by stefanneculai** [comment]
commands.applyProperty was removed in v2.3.0. format.appleStyle can be used instead.

**Comment by escopecz** [comment]
Thanks, that'll be it! As soon as I will be able to uzip the Froala V2 package, I'll test it. I've sent you a request via contact form with my uzip issue.
