### ISSUE TITLE
Code view removing script tag

### ISSUE THREAD

**Issue by rblin081** [froala/wysiwyg-editor#1363]
##### Expected behavior.
Unless specified as an un-allowed tag, script tag should not be removed
##### Actual behavior.
When inserting code with a script tag it is removed when flipping between code and html view

##### Steps to reproduce the problem.
http://jsfiddle.net/f87p3s65/145/
1) Enter `<script>console.log('hello');</script>` into code view
2) flip to html view and back to code view. script tag is removed

##### OS.
Windows

##### Browser.
Chrome

**Comment by stefanneculai** [comment]
See https://www.froala.com/wysiwyg-editor/docs/options#htmlRemoveTags.

**Comment by rblin081** [comment]
Same exact steps as above
http://jsfiddle.net/f87p3s65/147/

The JS runs when toggling between code and html view (which is undesirable), and the JS also can't be seen in code view anymore when toggling

**Comment by stefanneculai** [comment]
Are you experiencing this outside of jsFiddle? I have just tried it on a blank editor instance on local environment and this problem doesn't seem to happen. I believe jsFiddle might block somehow that script.

**Comment by rblin081** [comment]
Yes I was testing on a local environment and was seeing the script being
removed, which prompted me to create a ticket. The reason the fiddle isn't
working is because the JS version is set to 1.8.3

**Comment by stefanneculai** [comment]
The editor requires jQuery at least 1.11.0.

**Comment by drdaemos** [comment]
@stefanneculai 
http://jsfiddle.net/f87p3s65/158/

Still happening even on the edge jQuery. I guess it is because textarea content isn't escaped.
Can it fixed?

**Comment by sandhyapillai** [comment]
<script><script>
