### ISSUE TITLE
keepFormatOnDelete Bug

### ISSUE THREAD

**Issue by delian7** [froala/wysiwyg-editor#1365]
##### Expected behavior.
Deleting all formatted text and hitting the backspace key again resets the formatting of the paragraph **despite the keepFormatOnDelete set to true**. Also styling gets stripped when deleting all text, undoing the text and deleting it again. 

##### Actual behavior.
Deleting text (as described above) causes the paragraph format to reset. 

##### Steps to reproduce the problem.
[See CodePen here](http://codepen.io/delian7/pen/YWZWrp). The steps will outline how to produce on CodePen. 

1. Select the first line and delete with backspace. 
2. Press backspace a second time.
3. Typed content will not have previous formatting.

**Related:** 

1. Select the first line and delete with backspace. 
2. Type in one letter
3. Delete the letter. 
4. Typed content will not have previous formatting.

##### OS.
macOS 10.11.5 (El Capitan). 

##### Browser.
Google Chrome v 51.0.2704.103

##### Froala Editor Version
2.3.4 (off GitHub Master). 2.3.3 also has the bug on it. 

![froala bug](https://cloud.githubusercontent.com/assets/4530694/16399890/3c9b6e0a-3c8b-11e6-9170-f3153a9fea91.gif)

**Comment by delian7** [comment]
@stefanneculai also seeing behavior where a <font> entity appears replacing the <span>. In the [above CodePen](http://codepen.io/delian7/pen/YWZWrp) to reproduce this: 

1. Set cursor at end. 
2. CMD-Backspace (or windows equivalent) to delete all characters. 
3. Type something. 
4. Hit GET HTML. 

![screen shot 2016-07-01 at 2 05 07 pm](https://cloud.githubusercontent.com/assets/4530694/16534473/d7c38064-3f94-11e6-8b8a-b681aa764fb8.png)

**Comment by delian7** [comment]
Hi @stefanneculai do you have an ETA of when this bug would be resolved?

**Comment by stefanneculai** [comment]
Last commit fixes it. When you hit backspace for the 2nd time and it is resetting the format that is the correct behavior - it was designed to work that way.
