### ISSUE TITLE
A code typed in the code view mode isn't applied to the original textarea until the code view mode is turned off.

### ISSUE THREAD

**Issue by FinesseRus** [froala/wysiwyg-editor#1366]
##### Expected behavior.
Typed code is applied to the original textarea and to the `html.get` output value on every change in the code view mode. Or at least there is an API method that applies typed code like is happens when an editor is inside a `<form>` and the form is submitted.

##### Actual behavior.
Typed code is applied only when the code view mode is turned off.

##### Steps to reproduce the problem.
1. Go to http://codepen.io/anon/pen/vKxmJo?editors=1010
2. Switch to the code view mode.
3. Type something.
4. Click "Send".  The typed code should be displayed. Instead the code that was typed before switching to the code view mode is displayed.

##### OS.
OS X 10.11.5

##### Browser.
Safari 9.1.1

**Comment by stefanneculai** [comment]
This is by design. Please see https://github.com/froala/wysiwyg-editor/issues/1297#issuecomment-221818721.
