### ISSUE TITLE
Using Froala to Draft an Email - Not scoped to fr-view so nothing shows as expected

### ISSUE THREAD

**Issue by jpgilchrist** [froala/wysiwyg-editor#1367]
This is more a question about why you chose to do it this way. Everything to be rendered as seen in the editor has to be wrapped in an fr-view. However, we are trying to send this content to a user via email. Since, we cannot include external stylesheets in an email, how do you propose we display the content in such a way to get this to work?

Appreciate your thoughts! :)

**Comment by stefanneculai** [comment]
https://www.froala.com/blog/styling-emails-with-wysiwyg-html-editors

**Comment by jpgilchrist** [comment]
Excellent thank you!
