### ISSUE TITLE
Is it or will it be possible to load the linkList asynchronously?

### ISSUE THREAD

**Issue by escopecz** [froala/wysiwyg-editor#1368]
##### Expected behavior.
Push the linkList to the Froala editor when the link list is fetched. The link list will refresh.

##### Actual behavior.
The whole Froala cannot be initialized until the linkList is fetched. Or it must be initialized and destroyed, reinitialized when the linkList is fetched. Or is there a better way?

**Comment by stefanneculai** [comment]
No, there is no such way built-in the editor. I marked this as `feature-request`, but I will close this issue because we don't keep FR here.

**Comment by stefanneculai** [comment]
We've just put together a public roadmap with the most popular features. 😍 There you can vote your favorite one, provide feedback or make new suggestions: https://wysiwyg-editor-roadmap.froala.com/public.
