### ISSUE TITLE
Indentation is not maintained when pasting bullets

### ISSUE THREAD

**Issue by mrjlynch** [froala/wysiwyg-editor#1370]
##### Expected behavior.

![ezgif com-video-to-gif 8](https://cloud.githubusercontent.com/assets/3665457/16454288/7dabe6f8-3e53-11e6-83c2-6504111ec03b.gif)
##### Actual behavior.

![ezgif com-video-to-gif 7](https://cloud.githubusercontent.com/assets/3665457/16454173/f72fbaa0-3e52-11e6-9325-dff2cb451c7e.gif)

**Comment by reallyrobkerr** [comment]
have also encountered this issue in reverse, where nested bullets are losing their indentation when pasted from microsoft word

**Comment by kmacampbell** [comment]
Any update on these issues? We have a number of customers who are unhappy about this behaviour. Thanks!

**Comment by stefanneculai** [comment]
@mrjlynch this issue appears to be fixed, most probably by a different previous commit with a related problem. @reallyrobkerr we're working on an improved Word Paste that will come shortly.
