### ISSUE TITLE
Froala does not keep formatting between line breaks.

### ISSUE THREAD

**Issue by delian7** [froala/wysiwyg-editor#1371]
##### Expected behavior.

Formatting should be kept between two line breaks. Hopefully there's an configuration option that I missed. 
##### Actual behavior.

Formatting is stripped if typing between two formatted line breaks. 
##### Steps to reproduce the problem.

See [CodePen linked here](http://codepen.io/delian7/pen/vKxRrx). Steps described are for CodePen. 
1. At the end of the "Froala text editor is cool" line hit return **twice**. 
2. Start typing anything and style will be kept. 
3. Press Arrow Up key and start typing; style will be stripped. 
##### OS.

macOS 10.11.5 (El Capitan). 
##### Browser.

Google Chrome v 51

![froala-no-style-on-return](https://cloud.githubusercontent.com/assets/4530694/16460455/4a1c6852-3ddc-11e6-990c-0a48eb7e4e6c.gif)

**Comment by delian7** [comment]
Hey @stefanneculai I am seeing this issue pop-up again in the newest 2.6.5 editor. I updated the [Codepen](https://codepen.io/delian7/pen/yorQbg) to use the newest editor. Can you please confirm?

**Comment by delian7** [comment]
I made a GIF to explain the bug that we are seeing when we tried to upgrade to 2.6.2 (this bug is also reproducible in the 2.6.5). The localhost:3000 is using the 2.6.2 and the create.visage.co screenshot is using the 2.3.5 editor.

![line-break](https://user-images.githubusercontent.com/4530694/30087626-959ed466-9256-11e7-9ffa-3fe6c7dc66d2.gif)

Can we simply re-open this issue or should i make a new one?

**Comment by stefanneculai** [comment]
@delian7 we cannot reproduce it on the codepen you provided. Could you please check?

**Comment by delian7** [comment]
@stefanneculai ahh, I see that there is a slight discrepancy in my original instructions. 

If you place the cursor in the middle of the sentence "Froala Text Editor is Cool", and you hit enter twice, clicking the up-arrow will lose the style. 

![line-break](https://user-images.githubusercontent.com/4530694/30125455-4ae67fc2-92ed-11e7-9f9a-c85f90013a2f.gif)

**Comment by stefanneculai** [comment]
Latest commit fixes it.
