### ISSUE TITLE
webkitallowfullscreen mozallowfullscreen allowfullscreen attributes are stipped

### ISSUE THREAD

**Issue by kashifimran** [froala/wysiwyg-editor#1373]
##### Expected behavior.
After setting $.FroalaEditor.DEFAULTS.htmlAllowedAttrs = $.FroalaEditor.DEFAULTS.htmlAllowedAttrs.concat(['webkitallowfullscreen', 'mozallowfullscreen', 'allowfullscreen']) I expect Froala would not remove these attributes. 

##### Actual behavior.
The above attributes are removed. 

##### Steps to reproduce the problem.
Add `<iframe src="https://player.vimeo.com/video/abc" width="640" height="353" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>`

##### OS.
Any.

##### Browser.
Any.

**Comment by stefanneculai** [comment]
Most probably you are not setting those attributes correctly, adding that code after initializing the editor. Could you please make a jsFiddle?

**Comment by kashifimran** [comment]
Thanks for your response Stefan. I am not able to set up jsFiddle, as I get the "unlicensed error". Is there a key to be used on jsFiddle?

Anyhow, the thing is that I am doing all initialization in one place and other things are working. The only thing not working is the above. 

Here's how I am setting it up (before initializing any editor). 

```
$.FroalaEditor.DEFAULTS = $.extend($.FroalaEditor.DEFAULTS, {
      key: 'my-key',
      fontSize: ['8', '9', '10', '11', '12', '14', '16', '18', '24', '30', '36', '48', '60', '72', '96'],
      imageAllowedTypes: ['jpeg', 'jpg', 'png', 'gif'],
      htmlAllowedAttrs: $.FroalaEditor.DEFAULTS.htmlAllowedAttrs.concat(['webkitallowfullscreen', 'mozallowfullscreen', 'allowfullscreen'])
    }); 
```

**Comment by stefanneculai** [comment]
You can just create a jsFiddle and ignore the unlicensed message. That doesn't limit any of the editor's features. Just set a height to the editor so that it makes the editable area high enough.

**Comment by kashifimran** [comment]
Hi again, I found out the issue. A security library I am using deep down the line was stripping those. Thank you so much for your help & sorry for wasting your time!
