### ISSUE TITLE
No contentChanged event, on action > undo > same action

### ISSUE THREAD

**Issue by zalos** [froala/wysiwyg-editor#1374]
This can be a CRITICAL error due to most model binding occurs on this event. I will get around this by interval timers that will update the data on my models, but this can cause data-loss

##### Expected behavior.
Editor would still throw contentChanged Event

##### Actual behavior.
editor does not throw the contentChanged Event.

##### Steps to reproduce the problem.
[http://jsfiddle.net/p4b84pqu/](http://jsfiddle.net/p4b84pqu/ )

1. insert link with text "asdf" 
2. press the undo button
3. insert link with text "asdf" (same action)

Note that the change event does not fire, and the data is blank. 

##### OS.
Windows 10

##### Browser.
Chrome

**Comment by stefanneculai** [comment]
We're aware of this and it has a high priority. Will be fixed before releasing the next version 2.3.4.

**Comment by zalos** [comment]
Great! Thanks for the fast response too! I have a workaround that has a timer every 500ms to check for any differences and call that event to force the data model updates for the time being.
