### ISSUE TITLE
If Froala is loaded by jquery .load function strange issues happens on edit popups

### ISSUE THREAD

**Issue by ikurpis** [froala/wysiwyg-editor#1375]
##### Expected behavior.

When Froala is loaded by jquery .load function in scrollable div element video and link edit popups should work normal.

##### Actual behavior.

When Froala is loaded by jquery .load function in scrollable div element video and link edit popups works normal just first time Froala initialise.
On second load and more, edit popups for video and links cannot be clicked.

##### Steps to reproduce the problem.

I made enviroment on my server for testing - http://froala.spiza.net/ (latest master version)

1. click on any link on the left to load Froala in the DIV on the right side
2. Try to edit links and video - everything works as expected on 1st load
3. Click another link to load same froala again (both links are identical)
4. Now try to edit links and video - popup appears but you cannot click any option

Options for froala are mostly default except scrollable container option:

toolbarSticky: true,
heightMin: 1500,
placeholderText: '',
language: 'en',
scrollableContainer: '#container'

##### OS.
Tested on Win 10

##### Browser.
Tested on the latest Chrome and Firefox

**Comment by ikurpis** [comment]
Is there any statement on this issue with loading editor with jquery .load function?
I did some further tests, and I  don't have a clue what is cause of this issues.

Also if you initialise froala with default "scrollableContainer: body" option, some other issues happens  on clean tests (like broken functionality of insterting a table, broken dropdown).
On first page load everything is fine, then it begins, but console shows no errors.

In my more complex project if I leave 'body' as scrollableContainer (which it is) i dont see popups and button popovers, they show as empty div elements in DOM, without button elements inside. Best case is when I put 'html' as scrollable container (except toolbarSticky not working then).

Is there something I am missing or doing wrong?

**Comment by dianaprajescu** [comment]
@ikurpis the editor is designed to use shared elements so that you don't end up with 10 image popups on the page in DOM if you have 10 editor instances. What happens in your case is that the editor initializes when you load it first time, but you never destroy that instance. This leaves the elements outside of the DOM and causes the problem. To avoid it, you should destroy the current instances before loading the other page.

**Comment by ikurpis** [comment]
Thank you @dianaprajescu, I already tried destroying editor in wrong place. My bad, sorry.

**Comment by ecuanaso** [comment]
ikurpis can you provide how you set up the destroy command?

**Comment by ikurpis** [comment]
As Diana said, every time you leave ajax loaded page you need to destroy initialised instance of Froala editor. In my specific case I have an ajax function for navigation and loading URLs so I destroy Froala in  "beforeSend" callback in that function.

**Comment by ecuanaso** [comment]
ikurpis, I've tried to do what Diana has said but I'm still having issues with the froala initialization/removing prior elements.

Here's a clip of what's going on
https://drive.google.com/file/d/0B0ya_PxZy9mMT0dWeTAzV2NGdkE/view

I'm on the meteor framework

**Comment by ikurpis** [comment]
This is happening because you didn't manage to destroy Froala **right before** you leave initial page.
I'm not sure about meteor way but jquery ajax events are explained here https://api.jquery.com/Ajax_Events/.
You would need "before send" event to destroy FE instance when navigating away.
