### ISSUE TITLE
Copy paste templates into froala error in Editor

### ISSUE THREAD

**Issue by MotorFu** [froala/wysiwyg-editor#1376]
##### Actual behavior.
Copy paste templates into froala error in Editor

##### Steps to reproduce the problem.
Use XIUMI (http://xiumi.Us/Studio/V5/paper#/for/new) publishing website, after publishing good content is copied to the froala Editor, style disorder occurred, because of "&nbsp;" And lead to errors in style, and hoping. to get repairs.Added: use other content publishing Web site, are experiencing the same problem.
Thank you.

##### OS.
macbook pro
##### Browser.
chrome

**Comment by stefanneculai** [comment]
Please let us know the steps to reproduce this problem. It would be great if you can make a jsFiddle for it.

**Comment by MotorFu** [comment]
Sorry ,I dont`t konw How to use jsFiddle complete it.
I only tell you the steps to reproduce this problem.
I hope you can see.
Thanks. 

step 1:use XIUMI website(http://xiumi.Us/Studio/V5/paper#/for/new), 
Using the template.
Please see picture:
(http://pub.img.shadowvc.com/F21Ra0cP)

step 2 copy template to froala editor
Please see picture:
(http://pub.img.shadowvc.com/hQLJE698)

Please see code:
(http://pub.img.shadowvc.com/1wFSIgcF)

By the three pictures results found:

reason: The third picture in the "&nbsp" caused by.
But I will the template copy to summernote editor ,
the typography is good.
Please see picture:
(http://pub.img.shadowvc.com/ETa1k8Y2)

**Comment by stefanneculai** [comment]
@MotorFu Could you please send us the HTML you're inserting into the editor?

**Comment by MotorFu** [comment]
`<section><section class="Powered-by-XIUMI V5" style="position: static;"><section class="" style="font-size: 12.8px; position: static;"><section class="" style="display: inline-block;"> <section class="" style="height: 2em; line-height: 2em; display: inline-block; vertical-align: top; color: rgb(255, 255, 255); font-size: 16px; text-align: center; padding-left: 8px; padding-right: 8px; background-color: rgb(239, 66, 119);"><section>输入标题</section></section><section style="display: inline-block; vertical-align: top; width: 0px; border-left-width: 1em; border-left-style: solid; border-left-color: rgb(239, 66, 119); font-size: 16px; border-top-width: 1em !important; border-top-style: solid !important; border-top-color: transparent !important; border-bottom-width: 1em !important; border-bottom-style: solid !important; border-bottom-color: transparent !important;"> </section> <section style="width: 0px; border-right-width: 0.6em; border-right-style: solid; border-right-color: rgb(2, 32, 99); border-top-width: 0.6em; border-top-style: solid; border-top-color: rgb(2, 32, 99); border-left-width: 0.6em !important; border-left-style: solid !important; border-left-color: transparent !important; border-bottom-width: 0.6em !important; border-bottom-style: solid !important; border-bottom-color: transparent !important;"></section></section></section></section></section>`

**Comment by MotorFu** [comment]
editor config option: pasteDeniedAttrs: ['class', 'id']

I already send email to you. Please check out it.

**Comment by stefanneculai** [comment]
The problem actually comes from adding `BR` tag inside the section. There are 2 possible approaches for this:
1) Remove `section` from `$.FE.BLOCK_TAGS`.
2) Use `span` tag instead of `section`.
