### ISSUE TITLE
When editing is off, can not play videos in editor

### ISSUE THREAD

**Issue by Dattaprasad-Choukekar** [froala/wysiwyg-editor#1383]
##### Expected behavior.
When editing is off, if clicked on video in the editor which was already added, it does should play.

##### Actual behavior.
When editing is off, if clicked on video in the editor which was already added, it does not play.

##### Steps to reproduce the problem.

`      <div id='edit' style="margin-top: 30px;">
       <p><span class="fr-video fr-dvb fr-draggable" contenteditable="false" draggable="true"><iframe width="640" height="360" src="//www.youtube.com/embed/6AJxuXyNfRs" frameborder="0" allowfullscreen=""></iframe></span></p>
	  </div>`

`$('#edit').froalaEditor({
        fullPage: true,
		height: 800
      });`

`    
	  $('#edit').froalaEditor('edit.off');`

[video.zip](https://github.com/froala/wysiwyg-editor/files/349418/video.zip)

##### OS.
Windows 10

##### Browser.
chrome latest

**Comment by stefanneculai** [comment]
That is the intended behaviour. When edit is off, you shouldn't be able to do anything inside the editable area.

**Comment by Dattaprasad-Choukekar** [comment]
I agree that user should not be able to resize or remove video in edit off mode.
But I think user should be able to at least play video.
Could you suggest me if there is any workaround for this?
