### ISSUE TITLE
Destroy with inline: true doesn't remove toolbar HTML

### ISSUE THREAD

**Issue by nicooprat** [froala/wysiwyg-editor#1385]
##### Expected behavior.

When destroying an editor, the inline toolbar HTML should be removed from the DOM.

##### Actual behavior.

When destroying an editor, the inline toolbar HTML is still in the DOM.

##### Steps to reproduce the problem.

Init an editor:
````js
$('textarea').froalaEditor({
  toolbarInline: true
});
`````

Then destroy it:
````js
$('textarea').froalaEditor('destroy');
````

Look at the HTML:
````html
<div class="fr-toolbar fr-desktop fr-inline">...</div>
````

##### OS.
Mac OS 10.11.5

##### Browser.
Chrome 51.0.2704.103

PS. is it possible to create a example on jsFiddle without having the "Unlicensed Froala Editor" error?

**Comment by stefanneculai** [comment]
@nicooprat We cannot reproduce it. Could you please make a jsFiddle?

PS: With the master version jsFiddle is no longer showing that unlicensed message.

**Comment by nicooprat** [comment]
Here's the fiddle: https://jsfiddle.net/nicooprat/gxoh9xL9/

Indeed the toolbar is removed. There actually was an issue with my code. I'm using Meteor, and the DOM is *sort of* removed before the template's `onDestroyed` hook is called... Needed to wrap the editor into its own template to make it work correctly.

Hope it help someone else, and sorry for the false alert ;)
