### ISSUE TITLE
HTML is lost during initial load

### ISSUE THREAD

**Issue by philfreo** [froala/wysiwyg-editor#1387]
Still working on upgrading from v1 to v2... might be missing something obvious.

##### Expected behavior.

Visit http://jsfiddle.net/s46sbc1v/ and the text should be bold

##### Actual behavior.
The HTML tag is lost.

##### Browser.
Chrome

**Comment by stefanneculai** [comment]
The option is called `htmlAllowedTags` in V2.

**Comment by philfreo** [comment]
thanks, fixed here http://jsfiddle.net/wzttb2vu/
