### ISSUE TITLE
HTML is lost switching to code view

### ISSUE THREAD

**Issue by philfreo** [froala/wysiwyg-editor#1388]
##### Expected behavior.
HTML formatting isn't lost when switching from HTML to WYIWYG view

##### Actual behavior.
HTML formatting is lost when switching from HTML to WYIWYG view

##### Steps to reproduce the problem.
Visit http://jsfiddle.net/dm8gLymh/
Type "hi" three times with a line break in between each
Switch to code view
Switch back

##### Browser.
Chrome OS X

**Comment by stefanneculai** [comment]
The option `htmlAllowedTags` in V2. 😄

**Comment by philfreo** [comment]
thanks! fixed here http://jsfiddle.net/yf6f9e6a/
