### ISSUE TITLE
Code view needs more specific CSS to hide textarea

### ISSUE THREAD

**Issue by philfreo** [froala/wysiwyg-editor#1389]
##### Expected behavior.
Switching from HTML mode to WYIWYG mode should hide code view. Some general CSS rules on the page shouldn't break core Froala functionality.

##### Actual behavior.
If there's a `textarea` `display: block;` rule on the page, this doesn't work anymore.

##### Steps to reproduce the problem.
Visit http://jsfiddle.net/32cfnjbv/
Go to code view
Go back to regular view

##### OS.
OS X Chrome

**Comment by stefanneculai** [comment]
It is specific enough but it can't be more specific than a rule for the same area which contains an id. For that you'd need 10 classes according to the specs (http://www.w3.org/TR/selectors/#specificity).
