### ISSUE TITLE
Image edit menu has missing icon

### ISSUE THREAD

**Issue by philfreo** [froala/wysiwyg-editor#1390]
Visit http://jsfiddle.net/rtte3h4c/
Click Insert Image
Drag image into dropzone
Weird popover option / missing icon:

<img width="199" alt="screenshot 2016-07-06 15 44 40" src="https://cloud.githubusercontent.com/assets/97612/16632123/99b7bed4-4390-11e6-9cf6-6f889a019ad1.png">

Chrome OS X 

I was trying to customize this icon to something in Glyphicons, then I realized it seems to be broken in your default icon pack too.

**Comment by dianaprajescu** [comment]
The icons for alignment are defined in the Align plugin. It appears that this problem comes when using the image plugin without the align one. Defining the icons in JS should fix it http://jsfiddle.net/rtte3h4c/1/:
```js
$.FE.DefineIcon('align', { NAME: 'align-left' });
$.FE.DefineIcon('align-left', { NAME: 'align-left' });
$.FE.DefineIcon('align-right', { NAME: 'align-right' });
$.FE.DefineIcon('align-center', { NAME: 'align-center' });
$.FE.DefineIcon('align-justify', { NAME: 'align-justify' });
```

**Comment by philfreo** [comment]
This is a bug, no? If not, then the documentation should be update...

**Comment by dianaprajescu** [comment]
I marked it as `enhancement`. There should be a check in place to see if the icons is already defined.

**Comment by philfreo** [comment]
Is the alignment plugin necessary for these buttons to work?

If so then I'd suggest you not display these buttons at all if the alignment plugin isn't included.

**Comment by stefanneculai** [comment]
@philfreo The image plugin is using the same icons as the ones from the align plugin. We added there a check to define the icons if they are not already defined when using the image plugin.

**Comment by philfreo** [comment]
Okay. But it's not obvious to me: is the align plugin necessary for the align buttons to actually function on images?

**Comment by stefanneculai** [comment]
It is not anymore.

**Comment by philfreo** [comment]
Okay cool. I just wasn't sure if you fixed the actual displaying of the buttons and was asking about the actual functionality of image alignment.

Thx.

**Comment by jhubert** [comment]
@philfreo Did you ever manage to swap the icons to glyphicons? We're looking at doing that with Froala now.

**Comment by philfreo** [comment]
I can't remember if we solved this particular icon or just removed it, but yes we do use Glyphicons (only) for all our Froala icons in production -- here's the code we use:

```
        // Configure Froala to use Glyphicons instead of Font Awesome, since we already use it.
        // https://www.froala.com/wysiwyg-editor/v2.0/docs/concepts/custom-icon
        // We use a mix of Halfings and Glyphicons because:
        // - Halflings are designed for the size we are showing them at and the Glyphicons version of some
        //   icons (e.g. list-numbered) isn't clear enough compared to the designed-for-small Halflings version.
        // - Some icons aren't in the Halflings pack so we use Glyphicons for those.
        $.FroalaEditor.DefineIconTemplate('glyphicons', '<span class="glyphicons glyphicons-[NAME]"></span>');
        $.FroalaEditor.DefineIconTemplate('halflings', '<span class="halflings halflings-[NAME]"></span>');
        $.FroalaEditor.ICON_DEFAULT_TEMPLATE = 'halflings';

        $.FroalaEditor.DefineIcon('bold', { NAME: 'bold' });
        $.FroalaEditor.DefineIcon('italic', { NAME: 'italic' });
        $.FroalaEditor.DefineIcon('insertLink', { NAME: 'link' });
        $.FroalaEditor.DefineIcon('linkOpen', { NAME: 'new-window' });
        $.FroalaEditor.DefineIcon('linkRemove', { NAME: 'trash' });
        $.FroalaEditor.DefineIcon('insertImage', { NAME: 'picture' });
        $.FroalaEditor.DefineIcon('templateTags', { NAME: 'magic', template: 'glyphicons' });
        $.FroalaEditor.DefineIcon('html', { NAME: 'embed', template: 'glyphicons' });
        $.FroalaEditor.DefineIcon('formatOL', { NAME: 'list-numbered' });
        $.FroalaEditor.DefineIcon('formatUL', { NAME: 'list' });
        $.FroalaEditor.DefineIcon('imageAlt', { NAME: 'info-sign' });
        $.FroalaEditor.DefineIcon('imageSize', { NAME: 'resize-full' });
```

**Comment by jhubert** [comment]
@philfreo Awesome. Thanks for the fast response!
