### ISSUE TITLE
useClasses: false still has fr- classes on images

### ISSUE THREAD

**Issue by philfreo** [froala/wysiwyg-editor#1391]
Visit http://jsfiddle.net/rtte3h4c/
Click Insert Image
Drag image into dropzone
Switch to HTML mode

Expected: no fr- classes

Actual: `<img class="fr-dib fr-draggable" src="https://i.froala.com/download/...">`

Chrome OS X

**Comment by stefanneculai** [comment]
That is the intende behaviour. The classes are converted to inline just when you take the HTML using html.get or from the textarea.

**Comment by philfreo** [comment]
Okay, this is unexpected / less than desirable for a HTML email editor where you'd like to preview the exact HTML that's going to be sent.

**Comment by stefanneculai** [comment]
We designed this feature similar to how a CSS inliner tool would work. When you use such a tool you're not checking e output using a code view like tool.

**Comment by philfreo** [comment]
I understand, but to me CSS inliner is more of a raw coder's tool where you are intentionally typing custom html/css and then you just want it "ready for email" at the end. Whereas in a WYSIWYG editor I'd expect the code view to accurately reflect what code is going to be sent to the server, etc.

**Comment by philfreo** [comment]
I'd just like to reiterate that it's very much undesired to have "fr-" classes show up in the HTML/source view of the editor. The HTML is ugly / unnecessary from the user's point of view, and confuses users why undesired classes get added to their HTML.
