### ISSUE TITLE
td with 'width: 100%' will expend to full row width regardless other td's

### ISSUE THREAD

**Issue by ur92** [froala/wysiwyg-editor#1394]
##### Expected behavior.
td with 'width: 100%' will expend to the width that remain, considering other td's 

##### Actual behavior.
td with 'width: 100%' is expend to full row width and make other td elements to be 0 width
![capture](https://cloud.githubusercontent.com/assets/6205315/16648840/9c28b17e-443e-11e6-9172-ae37a33ad959.JPG)

##### Steps to reproduce the problem.
reproduced here
https://codepen.io/anon/pen/akywkG

##### OS.
Windows 10

##### Browser.
Chrome 51

**Comment by stefanneculai** [comment]
It's because there is a padding set on the other `TD` elements. That's how tables work.

**Comment by ur92** [comment]
Didn't understand what padding have to do with the fact that the first td's width in the icons row calculated to the wrong width.
In addition, it looks good outside of the editor, so I can't find what is the difference inside and outside the editor.

**Comment by stefanneculai** [comment]
First of all if you want to use `html`, `head` and `body` tags you'd have to initialize the editor with `fullPage` option enabled. 

Secondly, in the HTML you're using you have a TD with `width: 100%` and 3 others with `width: 35px`. That's incorrect.

**Comment by ur92** [comment]
Thanks.
You are right about the TD width, but unfortunately, it's not our HTML...
