### ISSUE TITLE
Froala strips style tag even though it is listed in htmlAllowedTags

### ISSUE THREAD

**Issue by escopecz** [froala/wysiwyg-editor#1396]
##### Expected behavior.
The style tags should remain in the HTML when listed in htmlAllowedTags (which they are by default) 

##### Actual behavior.
Style tags in the head are gone when Froala messes with the HTML.

##### Steps to reproduce the problem.
1. https://jsfiddle.net/htcg6twz/1/
2. Click the button below the editor.
3. Compare the styles in the head tag from the source HTML with the resulted HTML.

##### OS.
Ubuntu 16.04

##### Browser.
Chromium 10

**Comment by stefanneculai** [comment]
You should also check the `htmlRemoveTags` option.

**Comment by escopecz** [comment]
![froala-style-tag](https://cloud.githubusercontent.com/assets/1235442/16660884/9b920490-4470-11e6-929f-5d85abd7bcd5.png)

**Comment by stefanneculai** [comment]
`htmlAllowedTags` is removing only the tag, but keeps the content. `htmlRemoveTags` is removing the tag together with its content. `script` and `tags` are in htmlAllowedTags so that if you change `htmlRemoveTags` then you don't have to change another option.

**Comment by escopecz** [comment]
Aha, I did not understand it from the docs. Thanks for explanation!

**Comment by FinesseRus** [comment]
I confirm that the docs are misleading. The description *"The list of tags that are removed together with their content."* of the `htmlRemoveTags` options loose it's sense when there is the `htmlAllowedTags` option.

**Comment by shnigi** [comment]
I still have this problem. I added "style" in allowedTags and made sure the removeTags array is empty. Still froala is stripping off all inline styles. using version 3.2.4
