### ISSUE TITLE
Selection methods don't work

### ISSUE THREAD

**Issue by nicooprat** [froala/wysiwyg-editor#1397]
##### Expected behavior.

`editor.selection.setAtEnd | setAtEnd | setBefore | setAfter` should work.

##### Actual behavior.

`editor.selection.setAtEnd | setAtEnd | setBefore | setAfter` don't work. Cursor stays where it is, no error in console.

Am I missing something ?

##### Steps to reproduce the problem.

Fiddle: https://jsfiddle.net/nicooprat/gxoh9xL9/4/

When running, you have 2 seconds to focus the text. After 2s, cursor should move to the end of the text. You can watch the console to know if the function has run.

Here's another try using string based method: https://jsfiddle.net/nicooprat/gxoh9xL9/5/

##### OS.

Mac OS 10.11.5

##### Browser.

Chrome 51.

**Comment by nicooprat** [comment]
Actually I just found the solution, after struggling for hours: http://stackoverflow.com/a/35191761/758728

I just needed `editor.selection.restore()` after `editor.selection.setAtEnd(node)`. I deliberately posted the issue anyway because I think the docs could be more clear (or even include an example?) and it could help someone else.

**Comment by dianaprajescu** [comment]
@nicooprat Indeed, after calling `selection.setAtEnd` the `selection.restore` method should be called. We'll update the docs to make that a bit more clear. Thanks for the feedback!
