### ISSUE TITLE
editor.selection.save messes up letter-spacing

### ISSUE THREAD

**Issue by delian7** [froala/wysiwyg-editor#1398]
##### Expected behavior.
When I use the selection.save() method, the range is saved and no content is shifted.  

##### Actual behavior.
Content (that has letter-spacing and wraps) shifts. 

##### Steps to reproduce the problem.
Refer to [this CodePen](http://codepen.io/delian7/pen/kXGPBA?editors=1010) for reproduction steps. 

1. With cursor, select "Spacing" (no leading/trailing space). 
2. Click "Save Selection" button

##### OS.
macOS 10.11.5 (El Capitan)

##### Browser.
Chrome v 51

**Comment by dianaprajescu** [comment]
By shifts, do you mean page scroll?

**Comment by delian7** [comment]
@dianaprajescu This is what I mean: 

![froala](https://cloud.githubusercontent.com/assets/4530694/16700229/b44ae900-450d-11e6-9283-a7c5f92d38a8.gif)
