### ISSUE TITLE
Firefox Bug: selection.element() sometimes gets the whole div contents

### ISSUE THREAD

**Issue by delian7** [froala/wysiwyg-editor#1399]
##### Expected behavior.
When element is selected, selection.element() should return the selected element. 

##### Actual behavior.
selection.element() returns the whole froala container html. In other words selection.element() returns the same as html.get() **in FIREFOX only.**

##### Steps to reproduce the problem.
Steps reference **[CodePen here](http://codepen.io/delian7/pen/NAwqXE?editors=1111)**: 

1. Open Firefox. 
2. Double-click on "100" to select the element. Sometimes dragging to select works but sometimes it doesn't. However, double-clicking on "100" will make it fail.
3. Click "Get Element"

##### OS.
macOS 10.11.5 (El Capitan)

##### Browser.
Firefox v. 47.0.1

works in Chrome v 51 & Safari v 9.1.1

##### Froala Editor Version
2.3.4 (latest version)

**Comment by stefanneculai** [comment]
Nice catch 👍
