### ISSUE TITLE
Missing Icons

### ISSUE THREAD

**Issue by BryanAvery** [froala/wysiwyg-editor#14]
When viewing you website in IE10, the editor icons are not displaying correctly

![image](https://f.cloud.github.com/assets/2764907/2387095/675e0564-a933-11e3-8669-3c29e9622374.png)

This is on the home page http://editor.froala.com/

**Comment by thanhnhutkmt** [comment]
just add this font-awesome css to your page and magic will happen 
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.min.css" />

> <textarea id="froala-editor">Initialize the Froala WYSIWYG HTML Editor on a textarea.</textarea>

> 	<link rel="stylesheet" href="${contextRoot}/css/froala_editor.pkgd.min.css">	
> 	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.min.css" />	  	
>   	<script type="text/javascript" src="${contextRoot}/js/froala_editor.pkgd.min.js"></script> 	   	
> 	<script>
> 	   $(function() {
> 	    $('textarea#froala-editor').froalaEditor({
> 	      toolbarButtons: ['fullscreen', 'bold', 'italic', 'underline', 'strikeThrough', 'subscript', 
> 	    	  'superscript', '|', 'fontFamily', 'fontSize', 'color', 'inlineStyle', 'paragraphStyle', 
> 	    	  '|', 'paragraphFormat', 'align', 'formatOL', 'formatUL', 'outdent', 'indent', 'quote', 
> 	    	  '-', 'insertLink', 'insertImage', 'insertVideo', 'insertFile', 'insertTable', '|', 'emoticons', 
> 	    	  'specialCharacters', 'insertHR', 'selectAll', 'clearFormatting', '|', 'print', 'help', 
> 	    	  'html', '|', 'undo', 'redo'] 	  
> 	    })
> 	  });   
> 	</script>
