### ISSUE TITLE
Safari Bug: Line Wrapping Inconsistent When Destroying/Initializing 

### ISSUE THREAD

**Issue by delian7** [froala/wysiwyg-editor#1400]
##### Expected behavior.
The content should be the same when destroying and initializing. 

##### Actual behavior.
Upon destroy/init the content's line-wrapping is inconsistent. 

##### Steps to reproduce the problem.
Refer to the [CodePen here for steps](http://codepen.io/delian7/pen/mEqZwv). 

1. Click "Destroy"
2. Click "Init"

##### OS.
macOS 10.11.5 (El Capitan)

##### Browser.
Safari v 9.1.1

##### Froala Editor Version
2.3.4 (Latest Version)

**Comment by stefanneculai** [comment]
This is not an editor glitch, but a Safari issue caused by the `contenteditable` attribute (see the top part where the editor is not used): http://codepen.io/anon/pen/PzOJxB. We'll report it to Apple as soon as possible.

**Comment by delian7** [comment]
@stefanneculai Thank you. Will this github issue be updated once Apple says something back?

**Comment by stefanneculai** [comment]
Definitely. However, based on the response we got from them for other issues we reported, I don't think that will happen very soon.
