### ISSUE TITLE
Uncaught TypeError: Cannot read property 'get' of undefined

### ISSUE THREAD

**Issue by moinism** [froala/wysiwyg-editor#1401]
##### Expected behavior.
Should not throw an exception while cutting/copy.

##### Actual behavior.
It is showing an `Uncaught TypeError: Cannot read property 'get' of undefined` error in console whenever text is copied or cut (Win: CTRL+X) from editor. 
On Firefox it says `TypeError: mt is undefined`.

##### Steps to reproduce the problem.
[open this link](https://www.froala.com/wysiwyg-editor), keep your devtools (console tab) open and try to copy or cut a text from the demo editor.

##### OS.
Windows 10, macOS

##### Browser.
Chrome, Opera, Firefox

**Comment by stefanneculai** [comment]
It has been fixed on the Github master and will be included in the release V2.3.4.

**Comment by stefanneculai** [comment]
This has been fixed on the Github master and the changes will be included in V2.3.4.

**Comment by stefanneculai** [comment]
In couple of days.
