### ISSUE TITLE
"imagePaste: false" not working with mixed content

### ISSUE THREAD

**Issue by delian7** [froala/wysiwyg-editor#1403]
##### Expected behavior.
when imagePaste is set to **false** no images should be pasted.

##### Actual behavior.
If pasting in mixed text (text and images) pastes in images. 

![selection](https://cloud.githubusercontent.com/assets/4530694/16777923/885a8c86-4820-11e6-84e6-376ff2ea3bb0.gif)

##### Steps to reproduce the problem.
Steps Reference this [CodePen](http://codepen.io/delian7/pen/OXOjzb):

1. Go to any website that has mixed content (like above screenshot) and copy them.
2. Paste the content in the editor. 

##### OS.
macOS 10.11.5

##### Browser.
Chrome v 51

**Comment by stefanneculai** [comment]
Actually there is setting for that: https://www.froala.com/wysiwyg-editor/docs/options#imagePaste.

**Comment by delian7** [comment]
@stefanneculai I am using imagePaste. That is getting set to **false**.

**Comment by stefanneculai** [comment]
`imagePaste` option requires the image plugin. If you don't want to use the image plugin, you could as well use the `pasteDeniedTags` option.

**Comment by delian7** [comment]
Hi Stefan,
Thanks for looking into this. That method works.
Cheers, Delian Petrov

On Fri, Jul 15, 2016 at 3:57 AM, Stefan Neculai <notifications@github.com> wrote:
imagePaste option requires the image plugin. If you don't want to use the image plugin, you could as well use the pasteDeniedTags option.

**Comment by delian7** [comment]
thanks for looking into this. that works.
