### ISSUE TITLE
ImageUploadToS3 timing out

### ISSUE THREAD

**Issue by brokyo** [froala/wysiwyg-editor#1404]
I've followed [this](https://github.com/froala/wysiwyg-editor/issues/459) to set up the backend call for my credentials and updated my CORS configuration as described [here](https://gist.github.com/stefanneculai/deed108fad534d0db3ff#file-cors-file) but whenever I attempt to upload something I eventually get a request timeout and a "something went wrong" error in the editor. While I certainly can't be sure my code is correct I feel confident in the implementation as I'm mostly just taking code confirmed to work here.

The request just looks like this:

`Request URL:https://s3-us-east-1.amazonaws.com/[mybucket]`

with the following headers

```
Access-Control-Request-Headers:content-type
Access-Control-Request-Method:POST
Origin:http://127.0.0.1:3000
Referer:http://127.0.0.1:3000/post/create
User-Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36
```
Am I missing something obvious or is there a working code sample? I've seen the need for more in-depth explanations alluded to [here](https://github.com/froala/wysiwyg-editor/issues/404) so I'm hoping there's just something I've missed that spells it out.

Apologies for what I'm sure is an obvious question but I'm totally confused by this error and there just isn't much documentation to point me in the correct direction so hoping I can find answers here.

-- Don't know if it's relevant but in the off-chance this is a bug I'm using angular-froala 2.3.0 on OSX 10.11.5 and Chrome 51.0.2704.103

**Comment by stefanneculai** [comment]
We're using this repo for bug tracking only, not for tech support. If you have questions or need help integrating the editor please [contact us](https://www.froala.com/wysiwyg-editor/contact) instead of opening an issue.

**Comment by brokyo** [comment]
Totally understand that - thanks for the headsup. However I'm not clear that this is improper implementation (though I'd certainly believe it!) as I'm just copying from things that are marked here as good examples and everything logs correctly on the front end. 

Won't reopen another one or anything to keep this clean but is there an example or something I'm missing?
