### ISSUE TITLE
Copy/Paste strips styling if there is a line-break in the text

### ISSUE THREAD

**Issue by delian7** [froala/wysiwyg-editor#1405]
##### Expected behavior.
All pasted text (since **pastePlain** is set to true) should have previous paragraph styling. 

##### Actual behavior.
Pasted text that has line-break strips styling

##### Steps to reproduce the problem.
Steps reference this [CodePen](http://codepen.io/delian7/pen/jAakrZ). 

_(1.) Copy this block (notice the line-break)_

> Pokémon GO allows you to find and catch more than a hundred species of Pokémon as you explore your surroundings.

> The Pokémon video game series has used real-world locations

_(2.) Paste this code in the [CodePen](http://codepen.io/delian7/pen/jAakrZ). Pasted content should be red_

##### OS.
macOS 10.11.5

##### Browser.
Chrome v 51

I looked at all the options and I didn't one that fit my case.

**Comment by stefanneculai** [comment]
Unfortunately, there is no such feature implemented in the editor so that the pasted content match the existing one. This is a `feature request` therefore I am closing this for now.

**Comment by delian7** [comment]
@stefanneculai is there something I should create or is the feature request created internally?

**Comment by stefanneculai** [comment]
We keep feature requests internally. There is no need to do anything else. Thanks for posting it here.
