### ISSUE TITLE
Header expanding when clicking on the placeholder

### ISSUE THREAD

**Issue by chenbrand** [froala/wysiwyg-editor#1406]
##### Expected behavior.
When clicking the placeholder, the user should be able to type things into the editor

##### Actual behavior.
when clicking the header expands and the text area is not seen.
Before click:
![editor_bug_before_click](https://cloud.githubusercontent.com/assets/449640/16788314/424e3e3c-48e7-11e6-88f0-370cf42e37e0.png)

After click:
![editor_bug](https://cloud.githubusercontent.com/assets/449640/16788318/4e5eab94-48e7-11e6-8d15-6d9dec551423.png)

##### Steps to reproduce the problem.
It's just a simple editor form field in django inside a bootstrap modal, can't reproduce on other machines.
This only happens to me on a dell machine with 1366x768 resolution on chrome 51 but happens consistently.

##### OS.
Windows

##### Browser.
Chrome 51

**Comment by chenbrand** [comment]
After investigation it seems that for some reason in that machine it was adding fr-sticky-on instead of fr-sticky in other machines where it worked. that made the position fixed and resulted in the image above.
I changed the js to add fr-sticky instead of fr-sticky-on as a patch since it's in production. I'd be happy to hear what the actual problem is and if there's anything I missed.
Thanks.

**Comment by stefanneculai** [comment]
@chenbrand Please read https://www.froala.com/blog/notice-of-chrome-browser-problem.
