### ISSUE TITLE
Embedded image option dropdown shows below editor when editor has a maxHeight less than imageHeight

### ISSUE THREAD

**Issue by joeldaigle05** [froala/wysiwyg-editor#1409]
##### Expected behavior.
When embedding an image, only show image option dropdown when it can be anchored to the bottom of the image inside the editor area.

##### Actual behavior.
When embedding a tall image that is larger than editor height, when the image dropdown automatically shows after uploadComplete, the drop down is anchored to the bottom of the image far below editor. This creates a visual disconnect that may confuse users.

##### Steps to reproduce the problem.
- Configure Froala editor to have a maxHeight of 200px.
- Embed an image with a width less than 300px and height greater than 400px.
- On uploadComplete the image option dropdown will display 100px below the editor.

##### OS.
OSX 10.11.5

##### Browser.
Chrome 51

![floating_menu](https://cloud.githubusercontent.com/assets/20441785/16808497/be1dea1e-48ea-11e6-83ae-25266d9ce161.png)

**Comment by stefanneculai** [comment]
This is not happening with the master version. I believe you're using a version older than V2.3.3.
