### ISSUE TITLE
Froala creates non-breaking space in place of spaces and CRLFs.

### ISSUE THREAD

**Issue by Spicykoala** [froala/wysiwyg-editor#1410]
##### Expected behavior.
Source code doesn't replace a space with `&nbsp;` between spans.

##### Actual behavior.
Source code replaces spaces with `&nbsp;` between spans.

##### Steps to reproduce the problem.
Paste the following code in the editor found [here](https://www.froala.com/wysiwyg-editor).
`<p><span>ONE</span> <span>ONE</span></p>`

This is causing html to be incorrectly formatted and to me is a bug (unless I'm missing a froala option to disable this behavior).

##### OS.
Mac OS. El Capitan 10.11.3

##### Browser.
Version 51.0.2704.103 (64-bit)

**Comment by stefanneculai** [comment]
This is already fixed on the Github master.
