### ISSUE TITLE
Add support for calling upload function

### ISSUE THREAD

**Issue by canesin** [froala/wysiwyg-editor#1412]
Now with app APIs like [Firebase supporting file upload](https://firebase.google.com/docs/storage/web/upload-files) there should be a option to provide a function that handle the upload, it need to be able to receive a File or Blob object. It could expect to receive a return of res and error object, the res a normal URL to use in img src tag and error the same error.code.
There would be need to add a error.code == 8  for permission denied.

UX suggestion:
```
 $(function() {
    $('.selector')
      .froalaeditor({
        // Set the image upload parameter.
        imageUploadParam: 'image_param',

        // Set the image upload URL.
        imageUploadFunction: myuploadFunction,

        // Set request type.
        imageUploadMethod: 'BLOB',

```
The function signature would be something like:
myuploadFunction(image_obj : Blob) : URLstring

**Comment by stefanneculai** [comment]
Thank you the suggestion, @canesin. We use this repo only for bug tracking and not for feature requests, therefore I am closing this.
