### ISSUE TITLE
Add basic image crop functionality 

### ISSUE THREAD

**Issue by canesin** [froala/wysiwyg-editor#1413]
There could be a minimal editing functionality, cropping. A familiar style of MS word would be great

![image](https://cloud.githubusercontent.com/assets/353648/16884391/1db3cb6c-4a97-11e6-9763-6176ca7d3a33.png)

**Comment by stefanneculai** [comment]
Thank you the suggestion, @canesin. We use this repo only for bug tracking and not for feature requests, therefore I am closing this.
