### ISSUE TITLE
paste HTML code,Keep original format

### ISSUE THREAD

**Issue by MotorFu** [froala/wysiwyg-editor#1415]
please tell me  froala editor have keep  original format when paste html?

just now,froala editor always changed my paste the html code.

I don't know how to write editor's option for keeping original format.

Are you tell me how to configure editor?

Thank you.

My advice:
Could you add a property to indicate whether the paste to keep the original code？
Making life too difficult, but a bit around.

**Comment by stefanneculai** [comment]
Please see `pasteDeniedTags` and `pasteDeniedAttributes` options.
