### ISSUE TITLE
Free usage

### ISSUE THREAD

**Issue by KiarashS** [froala/wysiwyg-editor#1416]
Dear,

First, very thanks for development of froala editor.
Second, froala is free? 

Thanks

**Comment by stefanneculai** [comment]
No, the editor is not free. In order to use it, you should purchase a license: https://www.froala.com/wysiwyg-editor/pricing

**Comment by KiarashS** [comment]
So, what is github repository?

**Comment by stefanneculai** [comment]
Here we keep track of bugs and developers can download and take the editor for a spin before purchasing a license.

**Comment by KiarashS** [comment]
So this means we can use minified version in github, But for supporting authors we must purchase that?

**Comment by stefanneculai** [comment]
You can use the minified version to test the editor, not on production website. To use it inside your app, you should purchase a license that fits your needs: https://www.froala.com/wysiwyg-editor/pricing.

**Comment by KiarashS** [comment]
OK, very good.
Thanks
