### ISSUE TITLE
useClasses: false inserts undesired/unnecessary styles

### ISSUE THREAD

**Issue by philfreo** [froala/wysiwyg-editor#1418]
(Related to #1391)

I want to use `useClasses: false` because I'm sending email and I don't want any `fr-` classes showing up in the code. 

1. Go to http://jsfiddle.net/er0ee3n1/ and open your console
2. Paste a URL into the editor

Expected in console:

`<a href="http://jsfiddle.net/er0ee3n1/">http://jsfiddle.net/er0ee3n1/</a>`

Actual:

`<a href="http://jsfiddle.net/er0ee3n1/" style="color: blue;">http://jsfiddle.net/er0ee3n1/</a>`

Random page styles shouldn't affect the HTML output.

**Comment by stefanneculai** [comment]
You should use the iframe option if you don't want this. By default all the styles from the page affect what appears in the editor without the iframe option.

**Comment by philfreo** [comment]
This seems dumb. Even with an iframe, shouldn't I be able to use CSS to apply some basic styles to control what font & color the Froala editor displays, without having to have every page style outputted as inline styles and polluting the HTML?

Overall I _want_ to use 'useClasses: false' because the outputted HTML should not have any `fr-` classes in it since they pollute the HTML and the stylesheet with those classes won't appear in the result. However that doesn't mean I suddenly need you to try to pull in every computed style. 

My goal of using Froala editor is not to have a pixel for pixel match of every character in the outputted HTML. Rather the editor should give users a way to provide some very basic/limited formatting options (as setup by allowedTags, toolbar buttons, etc.) and output clean HTML with just enough styles needed to make those options work.

**Comment by stefanneculai** [comment]
The useClasses transforms all the CSS style that is applied to the elements inside the editable area to inline CSS. That is how we believe it should work because when you see something in the editable area which has green color then that same color should appear in the output. 

If you use the iframe option you could use the `iframeStyle` or `iframeStyleFiles` to set CSS only internal for the iframe. The iframe option is designed to isolate the editor CSS from the rest of the page and we actually encourage to enable it for email editing.

**Comment by philfreo** [comment]
I'm gave `iframe: true` a shot, per your recommendation (and can workaround #1419), however extra styles are appearing in the iframe `<head>` even though I'm not setting any custom `iframeStyle`:

```
html{margin: 0px;}body{padding:10px;background:transparent;color:#000000;position:relative;z-index: 2;-webkit-user-select:auto;margin:0px;overflow:hidden;min-height:20px;}body:after{content:"";display:block;clear:both;}body, body:focus{outline: transparent solid 0px;}body{position: relative; z-index: 2; -webkit-user-select: auto; background: transparent;}body a{-webkit-user-select: auto;}body.fr-disabled{-webkit-user-select: none;}body [contenteditable="false"]{-webkit-user-select: none;}body [contenteditable="true"]{outline: transparent solid 0px;}body img{cursor: pointer;}body ul{list-style-type: disc; margin-left: 25px;}body ol, body ul{margin-bottom: 10px;}
```

This is causing `useClasses: false` to inherit unnecessary styles such that a simple link causes a $textarea.val() to have this HTML:

`<a href="http://example.com/" style="-webkit-user-select: auto;">link</a>`

My real goal is just to have the outputted HTML to be as simple and clean as possible. I don't want any fr- classes in the output since these are emails. And I only want the bare minimum styles needed to display the basic formatting options I've provided my users (bold, italic, lists, links, img). I'm not trying to create a pixel for pixel match (email clients would probably mess this up anyway) and I want to be able to customize basic styles in the editor (e.g. font family or font color during composition) without those styles polluting the HTML.

**Comment by philfreo** [comment]
The previously [suggested workaround](https://github.com/froala/wysiwyg-editor/blob/b46df3fd524b9ac9a1f443d74d417bf67d3a55e9/examples/events/getHTML.html#L56-L60) from v1, while very ugly, at least worked better than the options I'm seeing in v2 so far.
