### ISSUE TITLE
Error when initializing Froala (iframe: true) on an element not yet in the DOM

### ISSUE THREAD

**Issue by philfreo** [froala/wysiwyg-editor#1419]
##### Expected behavior.
I should be able to setup an element with Froala (iframe: true or false) before it's in the DOM

##### Actual behavior.
It throws an error

##### Steps to reproduce the problem.
- http://jsfiddle.net/ddm4ttvu/
- View error in console

**Comment by stefanneculai** [comment]
Actually not, because the editor needs the document object in order to work correctly. The document is one of the main objects that are required.

**Comment by philfreo** [comment]
This should be documented then. I have always initialized Froala on elements not yet in DOM, so suddenly switching to iframe: true shouldn't led to a Froala internal error without documentation or a better error message.

**Comment by philfreo** [comment]
Before I was using `iframe: true` there was another case where I was able to initialize the editor outside of the DOM and then once it was added to the DOM I had to "refresh" something. Here's my code snippet (in order for the placeholder to appear properly):

```
        // If the HTML editor is initalized on a textarea that wasn't in the DOM at the time
        // then call this method after it is in the DOM.
        htmlEditorAddedToDom: function() {
            var $textarea = this._htmlEditorTextarea;

            // Fixes a font-size issue of the placeholder text where it changes size upon first focus
            $textarea.froalaEditor('placeholder.refresh');

            // ... some other smarter height-adjustment code I set
        },
```

Would it make sense or be possible to do some or the bulk of the initialization work on an iframe froala element before the element is in the DOM, as long as we notified Froala once it was in the DOM?

**Comment by stefanneculai** [comment]
The problem with the iframe is that it requires to be in the DOM in order to set the data to it.
