### ISSUE TITLE
Strange behaviour on a href value in the editor

### ISSUE THREAD

**Issue by jovana** [froala/wysiwyg-editor#1422]
If you create a href (link) use:
`<a href="http://test.com/samefile.php">test link</a>` is working correctly!
`<a href="{{automated_href}}/samefile.php">test link</a>` is working correctly!
`<a href="http://{{automated_href}}/samefile.php">test link</a>` is not working! It clears the href="" tag. And it saves like this:
`<a href="">test link</a>`

So the combination of http:// and {{}} is not accepted.

We have tested on MacOSX white google Chrome and Safari browser. This is on the latest version of Froala v2.3.4. This can also be reproduced using this example: https://www.froala.com/wysiwyg-editor

**Comment by stefanneculai** [comment]
Indeed, it appears there is a glitch from our side. We'll address it shortly.
