### ISSUE TITLE
doesn't work inside angularjs loop ( ng-repeat ) 

### ISSUE THREAD

**Issue by mohmedsalem19** [froala/wysiwyg-editor#1423]
##### Expected behavior.
actually i expected when i use wysiwyg inside an angular editor will work instantly without an error but it didn't work i tried it outside the loop and it worked so i don't understand why or maybe the editor doesn't support angular 
`<textarea id="edit" class="form-control" name="content">
	    	{[ topic.content ]}
	    </textarea>`
`$(function() {
          $('#edit').froalaEditor()
      });`
##### Actual behavior.
it did't work
<img src="http://i.imgur.com/fdbESqA.png" />

##### Browser.
chrome

**Comment by stefanneculai** [comment]
This is happening because you are calling the initialization on the editor only when your page is loaded. Instead, you should call this after each new rendering of the loop.

**Comment by mohmedsalem19** [comment]
yes it works thank you
