### ISSUE TITLE
Cannot drag an image from the Chrome Downloaded Files Bar

### ISSUE THREAD

**Issue by patrinhani-ciandt** [froala/wysiwyg-editor#1427]
##### Expected behavior.
Should be able to drag an image to the Image Upload Drag n' Drop area from the Chrome Downloaded Files Bar

##### Actual behavior.
Nothing happens when try to drag!

##### Steps to reproduce the problem.
Try to drag an image to the Drag image upload area from the Chrome Downloaded Bar
![froala_record](https://cloud.githubusercontent.com/assets/5272569/17114096/dd424a5a-5283-11e6-99e2-9f1d4e1c3123.gif)

##### OS.
MAC-OSX 10.11.5

##### Browser.
Google Chrome Version 52.0.2743.82

**Comment by Spicykoala** [comment]
I had to fix this for something else, just thought I'd leave this here to maybe save a dev some time:
http://stackoverflow.com/questions/19526430/drag-and-drop-file-uploads-from-chrome-downloads-bar

**Comment by philfreo** [comment]
If it works when dragging from Finder / filesystem but not from Chrome, then it may be due to this bug: https://bugs.chromium.org/p/chromium/issues/detail?id=234931

**Comment by stefanneculai** [comment]
@philfreo is right. The issues is from Chrome and has been fixed in Canary.
