### ISSUE TITLE
Defining Toolbar Buttons Not Working on iPad

### ISSUE THREAD

**Issue by cybervanes** [froala/wysiwyg-editor#1428]
##### Expected behavior.
both inline and regular editors should show only the tool bar buttons defined in the instantiation config

##### Actual behavior.
looks like the plug-in config extention is ignoring toolbarButtons: [] and brings in all buttons

##### Steps to reproduce the problem.
$('#internalNotesWYSIWYG').froalaEditor({
toolbarButtons: ['bold', 'italic', 'underline', 'color', 'align', 'formatOL', 'formatUL', 'indent', 'outdent', 'insertImage']
});

##### OS.
iOS 9.3.3 (13G34)

##### Browser.
Chrome
Firefox
Safari

**Comment by stefanneculai** [comment]
Please see: https://www.froala.com/wysiwyg-editor/docs/examples/custom-toolbar
