### ISSUE TITLE
When loading via SystemJS & JSPM, getting "jquery is not defined"

### ISSUE THREAD

**Issue by atrauzzi** [froala/wysiwyg-editor#1429]
I've got jquery installed in my project, but I suspect the project isn't correctly configured to be loaded as part of SystemJS.

I'm not sure what the solution is in this scenario, all I know is that this particular package isn't working (and others are).

**Comment by stefanneculai** [comment]
Here is how you can import it for JSPM:
```js
import jQuery from 'jquery';
import froala from 'froala-editor/js/froala_editor.min';
froala(jQuery);

jQuery('#editor').froalaEditor()
```

**Comment by atrauzzi** [comment]
That doesn't work because the detection is done when the file is parsed.

**Comment by stefanneculai** [comment]
Here is how I do it and it works fine:

**HTML**
```html
<html>
<head></head>
<script type="text/javascript" src="jspm_packages/system.js"></script>
<script type="text/javascript" src="config.js"></script>
<body>
  <div id="editor">
    foo
  </div>

  <script>
    System.import('jspm/main');
  </script>
</body>
</html>
```

**JS**
```js
import jQuery from 'jquery';
import froala from 'froala-editor/js/froala_editor.min';
froala(jQuery);

jQuery('#editor').froalaEditor()
```

**Comment by atrauzzi** [comment]
I'm actually shimming froala to work with some legacy scripts.  So I'm not sure this style of import applies anymore?
