### ISSUE TITLE
Toolbar alignment issue

### ISSUE THREAD

**Issue by ravindueranga** [froala/wysiwyg-editor#1430]
**Steps to reproduce the problem.**
```
        <div class="row form-group" show-errors>
			<label for="issue" class="col-md-2 control-label text-right">Text 1<span class="redErrMsg italic">*</span>
			</label>
			<div class="col-md-8 ">
				<textarea froala class="form-control"
					ng-model="text1" name="issue" id="issue" required></textarea>
				<p class="help-block" ng-if="form.issue.$error.required">Required</p>
				<p class="help-block" ng-if="form.issue.$error.maxlength">Exceeds
					Max Length</p>
			</div>
		</div>

		<div class="row form-group" show-errors>
			<label for="reason" class="col-md-2 control-label text-right">Text 2 </label>
			<div class="col-md-8 ">
				<textarea froala rows='6' class="form-control"
					ng-model="text2" name="reason" id="reason"
					ng-maxlength="250"></textarea>
				<p class="help-block" ng-if="form.reason.$error.maxlength">Exceeds
					Max Length</p>
			</div>
		</div>

		<div class="row form-group" show-errors>
			<label for="capabilities" class="col-md-2 control-label text-right">Text 3</label>
			<div class="col-md-8 ">
				<textarea froala rows='6' class="form-control"
					ng-model="text3" name="capabilities"
					id="capabilities" ng-maxlength="250"></textarea>
				<p class="help-block" ng-if="form.capabilities.$error.maxlength">Exceeds
					Max Length</p>
			</div>
		</div>
```

When have multiple editors(3) in a modal dialog in an Angularjs application, the first editor's toolbar is not aligned properly until click on that editor. **Occurs in Chrome**. In Firefox works fine.

![capture](https://cloud.githubusercontent.com/assets/8927438/17173458/99353cfa-5418-11e6-84da-abc730519f5c.PNG)

**Comment by stefanneculai** [comment]
Please provide a way to replicate the problem, other way there is nothing we could do to help you with it.

**Comment by ravindueranga** [comment]
Add three editors in to a single view and you can see the error yourself. I used bootsrap modals and Anugularjs framework

**Comment by stefanneculai** [comment]
@ravindueranga Yes, we could do that, but we look at issues which have full details about how to reproduce first. Providing that would make this issue be fixed faster.

**Comment by ravindueranga** [comment]
Issue updated

**Comment by stefanneculai** [comment]
@ravindueranga that is not enough. Please create a jsFiddle or provide a URL where we can reproduce it right away. Thank you.
