### ISSUE TITLE
additional button to load charts from the database as image?

### ISSUE THREAD

**Issue by Shermaine98** [froala/wysiwyg-editor#1431]
##### Expected behavior.
I want to render charts from my database to the text editor, I there is a way to do it currently but an additional feature is not bad. 

http://jsfiddle.net/syshermaine/hs8qufnw/1/ since there is already a way to render charts in highcharts

**Comment by stefanneculai** [comment]
Thanks for this `feature request`. We keep here only the bugs and enhancements, therefore I will close this for now.
