### ISSUE TITLE
Firefox > Spellcheck only underlining a single word until blurring the input

### ISSUE THREAD

**Issue by ConorHiggins** [froala/wysiwyg-editor#1432]
##### Expected behavior.

Misspelling multiple words while typing in an instance of Froala should cause all items to be underlined in red. This occurs on Chrome but not on Firefox.
##### Actual behavior.

Only the last word to be typed incorrectly will be underlined (until the user blurs the input)
##### Steps to reproduce the problem.

Type the following (without pasting):
"The qiukc bwron fox jmpus over the lzay dog"
##### OS.

OS X
##### Browser.

Firefox

**Comment by chrisdeeming** [comment]
I mistakenly opened a duplicate issue, as you can see. I've now closed that.

Just to add further details to this, there's a slight quirk in Chrome too wherein the editor loses all of the underlines when you hit backspace.

Here's a screencap of the issue being reproduced in Firefox: http://i.imgur.com/jqKCrUW

I can reproduce the issue on Windows 10 too.

It seems to work fine in other editors.

**Comment by chrisdeeming** [comment]
@stefanneculai just curious as to why this is considered an enhancement rather than a bug? Do you know if there are any workarounds?

Many thanks

**Comment by stefanneculai** [comment]
@chrisdeeming On a further check it appears that Firefox has some problems in how they trigger the spell check mechanism and that's why we marked it as an enhancement.

**Comment by stefanneculai** [comment]
We added an integration with WebSpellChecker: https://github.com/froala/wysiwyg-editor/blob/master/html/3rd-party/spell-checker/spell-checker.html. This will be live starting with version 2.5.2 that we're going to release in couple of days.
