### ISSUE TITLE
Suspend automatic text refactoring for empty i tags used for icons

### ISSUE THREAD

**Issue by philrykoff** [froala/wysiwyg-editor#1433]
I am using At.js (http://ichord.github.io/At.js/) to create something similar to "mentions".

For users, those include an image in the code inserted to the froala editor and everything works fine:

`<a class="ui user image mention label" data-fr-verified="true" data-id="' + user.id + '"><img src="/api/avatar/' + user.id + '"> ' + user.name + '</a>`

For another kind of mentions, an icon is inserted instead of an image (with a port of Font Awesome):

`<a class="ui element mention label" data-fr-verified="true" data-id="' + element.id + '"><i data-fr-verified="true" class="' + element.icon + ' icon"></i> ' + element.name + '</a>`

##### Expected behavior.
The icon will show and keep showing.

##### Actual behavior.
The icon is succesfully inserted and visible, but as soon as the user starts typing any more text, the `<i data-fr-verified="true" class="' + element.icon + ' icon"></i> ` part of the above snippet is being replaced by `&nbsp;`. This of course somehow makes sense 😁 . Yet, is there any way to come around that automatic refactoring? As you see, I had high hopes in data-fr-verified, but this did not help.

I am using Mac OS 10.10.5 with Chome 51, but that's probably uninteresting here.

**Comment by stefanneculai** [comment]
@philrykoff are you using the editor V1 or V2? `data-fr-verified` is no longer used in V2.

**Comment by philrykoff** [comment]
V2. So data-fr-verified can be left off?

**Comment by stefanneculai** [comment]
Yes, please see: https://www.froala.com/wysiwyg-editor/docs/examples/at-js. Could you please create a jsFiddle?

Thank you

**Comment by philrykoff** [comment]
Okay, so I got rid of data-fr-verified. 

Based on a hunch, I replaced `<i class="' + element.icon + ' icon"></i>` (which got removed) by `<i class="' + element.icon + ' icon">&nbsp;</i>`, which still shows a proper icon AND does not get removed by froala, probably as it is not empty.
