### ISSUE TITLE
Froala explodes vertically when resizing Chrome window

### ISSUE THREAD

**Issue by hackel** [froala/wysiwyg-editor#1434]
I'm running froala_editor v2.3.4.  When using Chrome, resizing the browser window sometimes causes the Froala editor widget to expand to full-height and solid grey, no longer editable.  This is always reproduceable when switching from full-screen to a regular window, otherwise when dragging the window manually it seems to happen randomly.  While resizing, I can see the widget flash a lot between regular and full-height, but sometimes it does return to normal and function normally.  

![screenshot from 2016-08-02 16-48-11](https://cloud.githubusercontent.com/assets/583677/17347261/788a58f8-58d4-11e6-82c1-924247068d8e.png)

This is on Chromium 51 on Ubuntu, however the user who first reported the issue was running Chrome on OSX.  I'm not able to reproduce the issue in Firefox at all.  Here is my config:
```js
export default {
    key:                envData.$env.froalaKey,
    inlineMode:         false,
    placeholderText:    'Enter Text Here',
    theme:              'gray',
    heightMin:          200,
    toolbarButtons:     [
        'paragraphFormat',
        'fontFamily',
        'fontSize',
        '|',
        'bold',
        'italic',
        'underline',
        'strikeThrough',
        'subscript',
        'superscript',
        '|',
        'color',
        'inlineStyle',
        'paragraphStyle',
        '-',
        'align',
        'formatUL',
        'formatOL',
        'outdent',
        'indent',
        'insertHR',
        '|',
        'insertLink',
        'insertImage',
        'insertVideo',
        'insertTable',
        '|',
        'clearFormatting',
        'fullscreen'
    ],
    linkInsertButtons:  [],
    imageInsertButtons: ['imageBack', '|', 'imageByURL'],
    toolbarSticky:      false,
};
```

**Comment by stefanneculai** [comment]
Please read https://www.froala.com/blog/notice-of-chrome-browser-problem

**Comment by hackel** [comment]
@stefanneculai According to that link, "I don't have to do anything," since I am running v2.3.4 *and* I have disabled toolbarSticky.  Yet the problem persists.  So perhaps this is a different issue?
