### ISSUE TITLE
Font lost when pasting from WOrd

### ISSUE THREAD

**Issue by pp5275388** [froala/wysiwyg-editor#1435]
##### Expected behavior.
(When copy from Word, I hope font of text can be kept, like text color, background color, and other styles)

##### Actual behavior.
(plain text, good thing is numbering or bullet-ting will be kept)

##### Steps to reproduce the problem.
Copy text with styles from word)

##### OS.
(cWindows 7)

##### Browser.
(Chrome)

**Comment by stefanneculai** [comment]
Indeed, those styles are not kept. It is on our TODO list to create a better Word cleaning algorithm and we expect to have it in place in the following months.
