### ISSUE TITLE
Blockquotes are unable to be nested

### ISSUE THREAD

**Issue by jaredhughes** [froala/wysiwyg-editor#1437]
##### Expected behavior.
- Blockquotes should wrap only current selection's block<br>
  e.g., `<div><blockquote><p>quote</p></blockquote></div>`
##### Actual behavior.
- Blockquotes wrap outermost of block, ignoring any nesting<br>
  e.g., `<blockquote><div><p>quote</p></div></blockquote>`
##### Steps to reproduce the problem.
1. Div-based
   - Create a nested div structure
   - Type a paragraph within nested divs
   - Apply blockquote
   - Blockquote wraps all divs
2. Table-based
   - Create table
   - Add paragraph to cell
   - Apply blockquote
   - Blockquote wraps table, as opposed to being inserted within the cell
##### OS.

Max OS X 10.11.6
##### Browser.

Chrome 52.0.2743.82 (all)

**Comment by ConorHiggins** [comment]
Just encountered this issue too and it has been reported by a customer so it's obviously the end of the world :). Will try and hack something usable into place.

**Comment by stefanneculai** [comment]
@jaredhughes @ConorHiggins this is how block-quotes were designed to work by default in the editor. This is how email clients and forum comments usually work. To get it work the way you want, it would be better to add a new option to Paragraph Format plugin and this way you can get quotes to work just like that.
