### ISSUE TITLE
ES6 imports of plugins not working

### ISSUE THREAD

**Issue by stoplion** [froala/wysiwyg-editor#1438]
How do you use plugins with ES6 (Browserify) import syntax? 
I'm attempting to use tables and lists but things don't seem to work..

# Tables

JS
```
import jQuery from 'jquery';
import froala from 'froala-editor/js/froala_editor.min';
import insertTable from 'froala-editor/js/plugins/table.min';
```
Scss
```
@import "node_modules/froala-editor/css/froala_editor";
@import "node_modules/froala-editor/css/plugins/table";
```

```
this.EditorNode = $('#rich-editor');
this.EditorNode.froalaEditor({
     toolbarButtons: ['bold', 'italic', 'underline', 'strikeThrough', 'insertTable', 'insertImage'],
     toolbarButtonsMD: ['bold', 'italic', 'underline', 'strikeThrough', 'insertTable', 'insertImage'],
     toolbarButtonsSM: ['bold', 'italic', 'underline', 'strikeThrough', 'insertTable', 'insertImage'],
     toolbarButtonsXS: ['bold', 'italic', 'underline', 'strikeThrough', 'insertTable', 'insertImage']
});
```

Table button appears, 
![image](https://cloud.githubusercontent.com/assets/231343/17420736/7683682a-5a59-11e6-90be-7b493ade94cd.png)
![image](https://cloud.githubusercontent.com/assets/231343/17420764/b244bc1a-5a59-11e6-9f5d-60f46b8eddfc.png)
**but after clicking it the table has no style (can't see it)**

# Lists
```
import froala from 'froala-editor/js/froala_editor.min';;
import lists from 'froala-editor/js/plugins/lists.min';
```

```
let editorOptions = [
      'bold',
      'italic',
      'underline',
      'strikeThrough',
      'insertTable',
      'image',
      'lists'
    ];

this.EditorNode = $('#rich-editor');
this.EditorNode.froalaEditor({
   toolbarButtons: editorOptions,
   toolbarButtonsMD: editorOptions,
   toolbarButtonsSM: editorOptions,
   toolbarButtonsXS: editorOptions
});
```

![image](https://cloud.githubusercontent.com/assets/231343/17420813/0fd5f09c-5a5a-11e6-9d8c-89a4b6ac9b48.png)

**No lists in the toolbar**

This also happens for images too. 
Is this an issue with ES6 imports or is there a step I am missing to get this to work?

`"froala-editor": "^2.3.4"`

**Comment by stoplion** [comment]
froala(jQuery);
insertTable(jQuery);
passing in Jquery did the trick! Closing..

**Comment by stefanneculai** [comment]
The options for lists are called `formatUL` and `formatOL`. You are not passing them correctly.
