### ISSUE TITLE
Double-clicking on words/text in editor does not select/highlight them

### ISSUE THREAD

**Issue by herringtown** [froala/wysiwyg-editor#144]
_Description_: User intends to highlight/select a word in the froala editor by double clicking on it (basis for this expectation: standard word processor & webpage text behavior)

_Steps to recreate_: 
- type three words into Froala
- double click on the second word

_Expected result_: text is highlighted/selected

_Actual result_: text is **not** highlighted

Curious if this is by design? If so, I find preventing the intentional selection of text via double click to be an odd "feature"..

![froala-highlight-text](https://cloud.githubusercontent.com/assets/2006761/3972710/1c3c12ac-27e0-11e4-9d4f-1ee8ac54f30f.gif)

**Comment by GirishKumar-Muniraju** [comment]
(Incase someone end up having this issue).


In my case, I had enabled '[edit.on](https://froala.com/wysiwyg-editor/docs/methods/#edit.on)' method. By removing that it worked.

Similarly, Please check the method based your use case and enable them accordingly
[Document Reference for wysiwyg-editor methods](https://froala.com/wysiwyg-editor/docs/methods/)

Hope it helps :)
