### ISSUE TITLE
why is / replaced with %2F when image is uploaded?

### ISSUE THREAD

**Issue by bonesoul** [froala/wysiwyg-editor#1440]
I get a strange file output when i image upload to s3 using froala.

https://s3.amazonaws.com/somebucket/ekipman%2Fliste%2F1470248611495-kolay-baslangic-seti.jpg

Why is "/" getting replaced by %2F instead of getting consistent?

**Comment by stefanneculai** [comment]
That is the way Amazon returns the key for the file.

**Comment by bonesoul** [comment]
is there any way i can fix this manually?
