### ISSUE TITLE
Froala not handling nested lists properly

### ISSUE THREAD

**Issue by HusseinElMotayam** [froala/wysiwyg-editor#1442]
##### Expected behavior.
When editing the "Edit me" text in the following jsFiddle, the new text should replace the old one.

##### Actual behavior.
Froala is not properly maintaining the nested list. Replacing the "edit me" text causes the underlying HTML to be malformed and the edits go to the nested `<ul>` instead.
The expected behavior is to maintain the structure of the nested list and edit the element under selection.

##### Steps to reproduce the problem.
Go to: https://jsfiddle.net/husseinelmotayam/n3z8rkte/
Try to replace the "Edit me" text.

##### OS.
Ubuntu 16.04

##### Browser.
Tested in Opera, FF and Chrome

**Comment by stefanneculai** [comment]
@HusseinElMotayam actually it's not an editor issue. The HTML inserted is not just correct for nested lists because you have there the `UL` wrapped with a `DIV`. Instead, it should be like this: https://jsfiddle.net/froala/n3z8rkte/2/.

**Comment by HusseinElMotayam** [comment]
@stefanneculai Well, in that case, the first item gets removed from the nested list and is inserted as a new item in the parent one.
I just tried your fiddle and replaced the first item.
I guess that's the same behavior but the opposite effect.

Shouldn't that be a bug?

**Comment by stefanneculai** [comment]
It depends on how you select it. To me it looks fine. Could you please make a recording?
