### ISSUE TITLE
Hide toolbar and show border

### ISSUE THREAD

**Issue by dungphanxuan** [froala/wysiwyg-editor#1445]
Hello, when i set  'toolbarInline'=> true, so all button hide, so i need border show. 
How can i fix it?
thank!
![62ddcf1c376c430793a895603e318343](https://cloud.githubusercontent.com/assets/10725732/17467651/9eb4d02e-5d4a-11e6-8283-6fc305927c6b.png)

**Comment by chamnap** [comment]
@dungphanxuan How do you fix it?

**Comment by stefanneculai** [comment]
@chamnap we would recommend using CSS to hide stuff related to the toolbar.
