### ISSUE TITLE
Table: insert-helper fails on IE/Edge

### ISSUE THREAD

**Issue by kgram** [froala/wysiwyg-editor#1446]
##### Expected behavior.
Insert-helper is shown

##### Actual behavior.
An error is thrown

##### Steps to reproduce the problem.
Create a table. Do not focus a cell. Hover where an insert-helper should be shown.

##### OS.
Reproduced with browserstack, Windows 8

##### Browser.
IE 10. According to error logging, this can be reproduced in all IE/Edge versions.

This happens because `plugins/table.js` relies on native `.closest` in line 2360/2373 (v2.3.4). This is not supported in any version of IE/Edge.

**Comment by stefanneculai** [comment]
That has been fixed in 9c66afc2fcc657732420d37238802e4f26a146be.

**Comment by kgram** [comment]
Great, any idea when it will be released :)

**Comment by stefanneculai** [comment]
End of August most likely.

**Comment by kgram** [comment]
Ok, thanks.
