### ISSUE TITLE
Customize & Hide options

### ISSUE THREAD

**Issue by array-addu** [froala/wysiwyg-editor#1447]
Hey! Trying out the Froala editor, really digging how customizable it is. I haven't yet been able to find any way to control the what options we can actually put in the toolbar rather than disabling it. Am i missing something?

Thanks!

**Comment by stefanneculai** [comment]
Please see: https://www.froala.com/wysiwyg-editor/docs/examples/custom-toolbar.

**Comment by array-addu** [comment]
It's not working, i'm with latest version.

**Comment by stefanneculai** [comment]
You are most likely using it incorrectly. We offer tech support via email for customers with Advanced/OEM licenses. If you have one, please contact us via our website https://www.froala.com/wysiwyg-editor/contact.

**Comment by array-addu** [comment]
It worked with `buttons` instead of `toolbarButtons`

**Comment by stefanneculai** [comment]
@array-addu that is because you're using V1, not V2.

**Comment by array-addu** [comment]
yes, this is because i'm using meteor package for this and it is updated to it's latest version i.e. 1.2.8.

**Comment by stefanneculai** [comment]
https://github.com/froala/meteor-froala this is updated to `V2.3.4`.
