### ISSUE TITLE
FireFox - text editor fails to initialize properly if not visible at initial page load

### ISSUE THREAD

**Issue by fmooreNS** [froala/wysiwyg-editor#1449]
##### Expected behavior.
When the Froala editor is initialized while not visible at page load, it should allow the user to select and type in the editor once it becomes visible on screen.

##### Actual behavior.
In FireFox 47 and 48, when the Froala editor is not visible at page load and becomes visible after the initial page load (switching tabs, clicking a button to show editor, etc.), the editor does not allow the user to click into it and start typing.  The user must take some additional action to force the editor to update (maybe blur?) like switching to code view or launching the insert video dialog.

##### Steps to reproduce the problem.

1. Create a page that contains an instance of the Froala text editor where the editor is not visible on the initial page load.  For instance, it could be a tabbed interface with the editor on an inactive tab.
2. Using FireFox 47 or 48, take some action that results in the editor being shown on screen.
3. Try to click into the editor and type.

##### OS.
Windows 7, OSX

##### Browser.
FireFox 47, 48

**Comment by stefanneculai** [comment]
I assume you're using the `iframe: true` option. Unfortunately, there is a browser limitation on this and you'd have to call the `size.refresh` method after you show the editor for the height to work correctly.

**Comment by fmooreNS** [comment]
Yes, we are using iframe: true.  Thank you for the tip on size.refresh.

**Comment by fmooreNS** [comment]
Just wanted to leave an update.  The size.refresh method did not work for me, but size.syncIframe did work.
