### ISSUE TITLE
Reverse logic on html.insert 

### ISSUE THREAD

**Issue by scottbarrow** [froala/wysiwyg-editor#1450]
##### Expected behavior.
Dirty HTML should be cleaned

##### Actual behavior.
Dirty HTML remains dirty

##### Steps to reproduce the problem.
call `editor.html.insert <a href='http://www.google.com'>Click Here</a>"`
should match documentation https://www.froala.com/wysiwyg-editor/docs/methods#html.insert

##### Cause
froala.js line 4387, insert function, logic is reversed with `if(!clean)`

**Comment by stefanneculai** [comment]
It appears there is a documentation problem. Actually the 2nd param specifies if the HTML is clean or not.
