### ISSUE TITLE
Impossible to capture cmd-enter keydown without creating newline

### ISSUE THREAD

**Issue by philfreo** [froala/wysiwyg-editor#1451]
##### Expected behavior.
Just like I can do in a textarea, in Froala I should be able to listen for cmd-enter or ctrl-enter keydown events for special behavior and have a line break not occur in the editor

##### Actual behavior.
Froala processes the Enter keydown as a new line no matter what

##### Steps to reproduce the problem.

1. Visit http://jsfiddle.net/s49f06mu/
2. Type "hello" in the simple textarea and press cmd-enter or ctrl-enter. You'll notice that after closing the alert, the cursor is still on the same "hello" line.
3. Do the same in the Froala editor and you'll notice the cursor dropped down a line.

##### OS.
OS X Chrome

**Comment by stefanneculai** [comment]
Here you go: http://jsfiddle.net/froala/s49f06mu/1/. You should use the `events.on` method for that and get it run before the other internal events by passing the 3rd param as `true`.

**Comment by philfreo** [comment]
Thanks. Later when I want to cleanup the editor, can I simply run `$textarea.off('froalaEditor.initialized')` and it will fully clean everything up, or do I also need to somehow unbind the `keydown` event too, since you're binding that also?

**Comment by stefanneculai** [comment]
Today we put an update here on Github which also clears these events automatically on destroy. If you are using an older version, what you should do is to call `$textarea.off('froalaEditor');`. This will clear all the events having the `froalaEditor` namespace.

**Comment by philfreo** [comment]
Okay, to confirm - on latest master, I can simply call `$textarea.froalaEditor('destroy')` without ever having to separately call `$textarea.off('froalaEditor.contentChanged');` or `     $textarea.off('froalaEditor.initialized');` -- those will automatically be cleaned up now?

**Comment by stefanneculai** [comment]
That is right.

**Comment by philfreo** [comment]
I'm looking into this `keydown` further and was pretty surprised by what I saw. 

See the comment block inside `froala.initialized` in http://jsfiddle.net/pnm9khrd/

Basically, `return false;` is both _preventing_ the default newline (this is kind of expected) _and_ it's _**un-**preventing_ the `keydown` event from bubbling up to the form's handler.

Is this how you expect it to work?

**Comment by stefanneculai** [comment]
@philfreo yes, this is the way it was intended. `return false` only prevents that event from being triggered inside the editor. To prevent bubbling up, you should use `e.stopPropagation()`.
