### ISSUE TITLE
Centering an image does not work

### ISSUE THREAD

**Issue by escopecz** [froala/wysiwyg-editor#1453]
##### Expected behavior.
- The image should be in the center.
- The `useClasses: false` option should not use classes, but inline styles, shouldn't it? It adds `class="fr-view fr-dii fr-draggable"` doesn't matter if useclasses is true or false. It might do something in the editor, but in the most email clients the classes does nothing.
##### Actual behavior.
- The image does not center.
- The `useClasses: false` option use classes anyway. 
##### Steps to reproduce the problem.
1. Go to https://jsfiddle.net/mxu605c2/
2. Try to center the kitten.
3. Check the source code that there are classes, not inline style.
##### OS.

Ubuntu 16.04
##### Browser.

Chromium 10

**Comment by stefanneculai** [comment]
When the display of the image is `Inline block`, then the center option of the alignment inherits the property of the parent. Changing that to `Break text` will display it centered. 

Regarding the `useClasses: false`, indeed it appears that is not working correctly when the editor is initialized on image.

**Comment by Soulwest** [comment]
I have the same issue. When I set `useClasses: false` editor takes inline classes not block classes.

**Comment by stefanneculai** [comment]
It is fixed in the latest 2.6.0 version.
