### ISSUE TITLE
iframeStyleFiles removes all remote assets from the head

### ISSUE THREAD

**Issue by escopecz** [froala/wysiwyg-editor#1454]
##### Expected behavior.
At least the original assets from the HTML source should remain there.

##### Actual behavior.
The `iframeStyleFiles` option removes all remote assets from the `<head/>`.

##### Steps to reproduce the problem.
1. Go to https://jsfiddle.net/j7s3xvjn/
2. Notice that there is one CSS in the HTML source in the `<head/>` and one should be added via the `iframeStyleFiles` option.
3. Hit the **Get HTML** button to get the restult - the `<head/>` doesn't contain either of the CSS files.

##### OS.
Ubuntu 16.04

##### Browser.
Chromium 10

**Comment by stefanneculai** [comment]
@escopecz you should also make sure you remove the `style` tag from `htmlRemoveTags`.
