### ISSUE TITLE
HTML comments are removed even when setting htmlAllowComments

### ISSUE THREAD

**Issue by HusseinElMotayam** [froala/wysiwyg-editor#1455]
##### Expected behavior.
Switching to code view, adding a comment then going back should preserve the HTML comment.

##### Actual behavior.
The HTML comment is removed even if the editor was initialized with the htmlAllowComments = true

##### Steps to reproduce the problem.
1. Go to code view
2. Add `<!-- comment -->` anywhere
3. Get back to the HTML view
4. Get back to the code view. Notice the comment is gone. 

##### OS.
Ubuntu 16.04

##### Browser.
Tested in Chrome and Opera

**Comment by stefanneculai** [comment]
It would be great if you could provide more details because this cannot be reproduced on our website.

**Comment by HusseinElMotayam** [comment]
@stefanneculai Thank you for taking the time to review this.

For the comment to disappear, it has to be placed in the head tag for example (or anything other than the body tag). For some reason, Froala will forcefully move it inside the body tag.

To have a better look at the issue:
1. Go to http://jsfiddle.net/husseinelmotayam/qc16ncgy/1/
2. Open the code view of Froala
3. Place `<!-- comment -->` inside the head tag
4. Go to the WYSIWYG view.
5. Get back to the code view. Notice the HTML comment is moved to the body.

Let me know if the issue is still irreproducible.

**Comment by stefanneculai** [comment]
@HusseinElMotayam I just checked this and I can confirm that there is a problem when you put a comment inside the `head` tag, but it works fine in the` body` one.

**Comment by escopecz** [comment]
What Froala version will contain this fix?

**Comment by stefanneculai** [comment]
V2.3.5.

**Comment by drewkiimon** [comment]
I'm having this problem in v2.7.5.
