### ISSUE TITLE
P tag removed when you copy paste in Firefox

### ISSUE THREAD

**Issue by twalia** [froala/wysiwyg-editor#1456]
##### Expected behavior.
if you copy paste a sentence in editor "How are you doing". After paste the cursor displays at first character. Now delete the first character by using delete  button. 

The string returned is without the  p tag

##### Actual behavior.
HTML string should retain the p tags

##### Steps to reproduce the problem.
Go to https://www.froala.com/wysiwyg-editor/docs/examples/live-code-preview
Copy paste a sentence in editor "How are you doing". 
After paste the cursor displays at first character
Now delete the first character by using delete  button
The html string returned is without the p tags.

##### OS.
Windows 7 Professional

##### Browser.
Firefox  - v48
Does not happens in Chrome

**Comment by stefanneculai** [comment]
Would it be possible to create a recording?

**Comment by stefanneculai** [comment]
@twalia could you please make a recording?

**Comment by twalia** [comment]
Attached is the video and word document.

Thanks,
[FroalaEditor_PtagError.zip](https://github.com/froala/wysiwyg-editor/files/432682/FroalaEditor_PtagError.zip)

**Comment by twalia** [comment]
Attached is the zip document with video and word file.

[FroalaEditor_PtagError.zip](https://github.com/froala/wysiwyg-editor/files/432685/FroalaEditor_PtagError.zip)
