### ISSUE TITLE
Drag & drop folder upload

### ISSUE THREAD

**Issue by vahtel** [froala/wysiwyg-editor#1457]
##### Expected behavior.
Drag & drop folder upload should not return an error to user.
The editor should either support folder upload or ignore folder uploads to the editor.

##### Actual behavior.
User sees an error "Something went wrong. Please try again"

##### Steps to reproduce the problem.
Go to https://www.froala.com/wysiwyg-editor and drag&drop folder from your computer to the editor.

##### OS.
OS X 10.11.6

##### Browser.
Chrom  52.0.2743.116 (64-bit)

**Comment by stefanneculai** [comment]
@vahtel We did some research on this matter and, unfortunately, it is not possible to detect if a dropped file is file or folder.

**Comment by vahtel** [comment]
Haven't looked into this much but it should be possible.

There are 2 methods on dataTransfer object - webkitGetAsEntry and getAsEntry . This how Jquery file upload http://blueimp.github.io/jQuery-File-Upload/ detects it.

Here's a code snipped:
```
            dataTransfer = dataTransfer || {};
            var items = dataTransfer.items;
            if (items && items.length && (items[0].webkitGetAsEntry ||
                    items[0].getAsEntry)) {
                return this._handleFileTreeEntries(
                    $.map(items, function (item) {
                        var entry;
                        if (item.webkitGetAsEntry) {
                            entry = item.webkitGetAsEntry();
                            if (entry) {
                                // Workaround for Chrome bug #149735:
                                entry._file = item.getAsFile();
                            }
                            return entry;
                        }
                        return item.getAsEntry();
                    })
                );
            }
```

**Comment by stefanneculai** [comment]
http://stackoverflow.com/a/25095250/1806855

**Comment by vahtel** [comment]
https://developers.google.com/web/updates/2012/07/Drag-and-drop-a-folder-onto-Chrome-now-available

**Comment by stefanneculai** [comment]
Indeed, it appears there there might be some workarounds lately. However, we had a quick discussion about this and, for UX, we believe that there should be an error message shown instead of not doing nothing.

**Comment by vahtel** [comment]
Maybe then a some other message instead of "Something went wrong. Please try again" ?

**Comment by stefanneculai** [comment]
We have in plan to create custom messages for each error. This will roll out in few months.

**Comment by vahtel** [comment]
OK, good.

We monkey patched this from our side with this:

```
var items = dt.items;
if (items && items.length && (items[0].webkitGetAsEntry || items[0].getAsEntry)) {
    if (items[0].webkitGetAsEntry().isDirectory) return;
}
```
