### ISSUE TITLE
Destroy and Initialised events only firing once

### ISSUE THREAD

**Issue by mrjlynch** [froala/wysiwyg-editor#1458]
*<b>Note</b>: ca300f6 appears to have changed this (pertaining to #1444), is this the expected functionality?*

##### Expected behavior.
The `froalaEditor.initialized` and `froalaEditor.destroy` events should not be unbound after they are called.

##### Actual behavior.
The `froalaEditor.initialized` and `froalaEditor.destroy` events are unbound after they are called. 

##### Steps to reproduce the problem.
Using the master version of froala (after ca300f6) **: 

``` js
// 1. Set the event (in the console): 
$('#froala-editor').on('froalaEditor.destroy', function (e, editor) {
    console.log('Destroy event working')
})
// 2. Destroy the editor
$('#froala-editor').froalaEditor('destroy');
// 3. Inspect console for "Destroy event working"
// 4. Reinitialize the editor
$('#froala-editor').froalaEditor();
// 5. Destroy again
$('#froala-editor').froalaEditor('destroy');
// 6. Inspect console for "Destroy event working"
```
**Note: Works fine before ca300f6

##### OS.
Os X

##### Browser.
Chrome

**Comment by stefanneculai** [comment]
On destroy all the events attached to the editor instance are being destroyed. That is the correct behaviour which was introduced by https://github.com/froala/wysiwyg-editor/commit/ca300f606500444b244361e85591e58f61e083ea.
