### ISSUE TITLE
Caret disappears after insertion of an image on Firefox beta

### ISSUE THREAD

**Issue by axelduch** [froala/wysiwyg-editor#1460]
##### Expected behavior.
Caret should be placed at the correct insertion point when you click or move with the keyboard arrows.

##### Actual behavior
The caret disappears until you insert a character, then blur the editor and focus it again.

##### Steps to reproduce the problem.
- Type a few lines in the editor
- Insert an image in the middle(ish) of the text
- Caret disappears

##### OS.
Might be cross platform, but encountered on OS X El Captain.

##### Browser.
Firefox beta (49+)
Firefox developer edition (aurora)

### Fix
Force `-moz-user-select` css property to `text`

**Comment by stefanneculai** [comment]
@axelduch Would it be possible to make a recording of this? Thank you.

**Comment by stefanneculai** [comment]
I am closing this due to lack of response and because we cannot reproduce it. If you could make a recording we would be happy to look into it.

**Comment by axelduch** [comment]
@stefanneculai So sorry for the delay. Today I can say my tests were biased and it is surely not coming from the Froala editor itself. Cheers
