### ISSUE TITLE
iframe mode inserts unnecessary styles

### ISSUE THREAD

**Issue by philfreo** [froala/wysiwyg-editor#1461]
Not sure if this is a duplicate of #1168 or not.

Extracting my comments from https://github.com/froala/wysiwyg-editor/issues/1418#issuecomment-236342021 to its own issue here.

I'm trying out `iframe: true` since I'm using the editor in the context of sending email. Extra styles are appearing in the iframe `<head>` even though I'm not setting any custom `iframeStyle`:

```
html{margin: 0px;}body{padding:10px;background:transparent;color:#000000;position:relative;z-index: 2;-webkit-user-select:auto;margin:0px;overflow:hidden;min-height:20px;}body:after{content:"";display:block;clear:both;}body, body:focus{outline: transparent solid 0px;}body{position: relative; z-index: 2; -webkit-user-select: auto; background: transparent;}body a{-webkit-user-select: auto;}body.fr-disabled{-webkit-user-select: none;}body [contenteditable="false"]{-webkit-user-select: none;}body [contenteditable="true"]{outline: transparent solid 0px;}body img{cursor: pointer;}body ul{list-style-type: disc; margin-left: 25px;}body ol, body ul{margin-bottom: 10px;}
```

This is causing `useClasses: false` to inherit unnecessary styles such that a simple link causes a $textarea.val() to have this HTML:

`<a href="http://example.com/" style="-webkit-user-select: auto;">link</a>`

My real goal is just to have the outputted HTML to be as simple and clean as possible. I don't want any fr- classes in the output since these are emails. And I only want the bare minimum styles needed to display the basic formatting options I've provided my users (bold, italic, lists, links, img). I'm not trying to create a pixel for pixel match (email clients would probably mess this up anyway) and I also want to be able to customize basic default styles in the editor (e.g. font family or font color during composition) without those styles polluting the HTML.

**Comment by stefanneculai** [comment]
@philfreo that is the `iframeStyle` option which is set by default by the editor. It makes sense to have an option there that would mention what kind of attributes someone wants to be ignored in the outputted style. I marked this as `enhancement`.

The classes are kept so that they can be used when the content is being added back in the editor to edit it again. Not all the inline style can be converted back to classes while the other way is possible all the time. Since you're sending emails, if you don't have an autosave feature then it would make sense to use a regex on the output to remove all the fr- classes.

**Comment by philfreo** [comment]
Just to provide a bit more context of what I'd ideally be looking for

- I'm using Froala for email composition so using `iframe: true` sounds like it makes sense to keep it isolated from the container page's styles.
- I'd like to be able to make some minor customizations to the default CSS that is used in the editor itself, without having all of those changes propagate in the output HTML. 
- Gmail is a great example of this. In Gmail I can compose HTML email and have the "default" font during composition display as Arial (instead of Times Roman) in my browser. However if you inspect the HTML of the emails they send, they aren't hardcoding any font styles in the sent email.

**Comment by stefanneculai** [comment]
Last commit is adding the `htmlIgnoreCSSProperties` option. You can use it to tell the editor what CSS properties you want to ignore in the conversion from CSS styles to inline styles. E.g.:
```js
htmlIgnoreCSSProperties: ['font-family', 'font-size']
```
