### ISSUE TITLE
IE11 Popups - Don't Detect Collisions

### ISSUE THREAD

**Issue by jpgilchrist** [froala/wysiwyg-editor#1463]
Editing a link (and I'm sure others) popup. 

**note chrome handles this perfectly**

##### Expected behavior.

Detect collision with bottom of page, and render above the link as opposed to under. 

##### Actual behavior.

Doesn't detect the collision and renders in such a manner, that half the popup is visible (off the bottom of the page).

##### Steps to reproduce the problem.

Have a editor positioned towards the bottom of the page and put a link in it. Edit the link, and the popup is off the page in IE11 (perhaps lower versions as well)

##### OS.
Windows 7

##### Browser.
IE11

**Comment by stefanneculai** [comment]
Would it be possible to send us an example where this is happening?

**Comment by jpgilchrist** [comment]
Just spent a few minutes trying to get what I thought were the conditions that would cause it in a jsfiddle, but no luck. I'll see if there's anything else I can do to get it into a nice example.

**Comment by jpgilchrist** [comment]
@stefanneculai I cannot seem to reproduce in jsfiddle. Perhaps it's something we are doing, I'll investigate that further. If at some point I can reproduce in an environment  you can see, I'll reopen.
