### ISSUE TITLE
Remove unnecessary 'region' param for S3 upload

### ISSUE THREAD

**Issue by philfreo** [froala/wysiwyg-editor#1464]
Currently you have this in image.js:

```js
url = 'https://' + editor.opts.imageUploadToS3.region + '.amazonaws.com/' + editor.opts.imageUploadToS3.bucket;
```

You could remove the requirement to know/pass the region if you changed that line to this:

```js
 url = 'https://' + editor.opts.imageUploadToS3.bucket + '.s3.amazonaws.com/';
```

I tested this on a non-default, us-west-2 region bucket and it worked.

**Comment by stefanneculai** [comment]
Indeed, that works as well. However, the problem with it is that you cannot use it with buckets that are Non–DNS-Compliant. Please see more there: http://docs.aws.amazon.com/AmazonS3/latest/dev/BucketRestrictions.html#non-dns-compliant-bucketname-challenges.

**Comment by philfreo** [comment]
Looks like they are moving away from allowing those.

But regardless, it'd be nice if you could allow me to just specify a URL rather than having you construct it yourself. I should not have to provide Froala both a bucket name and region... it complicates things in multi-region setups.

**Comment by stefanneculai** [comment]
@philfreo that is right. We'll see what we can do.

**Comment by vahtel** [comment]
+1

This would make it easier to use S3 transfer acceleration. [http://docs.aws.amazon.com/AmazonS3/latest/dev/transfer-acceleration.html](url)

It uses a different subdomain `bucketname.s3-accelerate.amazonaws.com`

**Comment by bonesoul** [comment]
👍

**Comment by stefanneculai** [comment]
With the last commit you can pass the upload url for S3, by adding the `uploadURL` property to `imageUploadToS3` object.

**Comment by philfreo** [comment]
@stefanneculai Thanks. I assume that also applies to `fileUploadToS3`, correct?

**Comment by stefanneculai** [comment]
That is right.

**Comment by philfreo** [comment]
Thanks. Final question (just confirming since the source isn't online) -- by adding `uploadURL` I can remove both `region` _and_ `bucket`, right?

**Comment by stefanneculai** [comment]
Right.

**Comment by kristian-puccio** [comment]
Just to confirm can we use this to upload to pre-signed s3 urls, where the url will be different for each upload ?

https://docs.aws.amazon.com/AmazonS3/latest/dev/PresignedUrlUploadObject.html
