### ISSUE TITLE
Drop event doesn't fire?

### ISSUE THREAD

**Issue by philfreo** [froala/wysiwyg-editor#1466]
http://jsfiddle.net/ab24frkd/

drop an image onto the editor

no alert appears

**Comment by stefanneculai** [comment]
It appears you're not including the draggable plugin which handles that event.

**Comment by stefanneculai** [comment]
@philfreo Please see: http://jsfiddle.net/froala/ab24frkd/1/.

**Comment by philfreo** [comment]
Thanks - I didn't really want to include the droppable plugin, but I see that by using `froalaEditor.initialized` to do the event binding, droppable isn't necessary.

Just FYI, here's the actual use case I was dealing with:
http://jsfiddle.net/1kL1prmc/

Without the Froala drop event, I had the following situation:
- (GOOD) drag a file somewhere on the page, my custom dropzone appears
- (GOOD) stop dragging a file over the page, my dropzone disappears
- (GOOD) drop the image in the Froala Image Popup "Drop Image" section -- my dropzone disappears after
- (BAD) drop the image in the Froala Editor section -- my dropzone did NOT disappear after

If you have a better idea on how to solve that, let me know.
