### ISSUE TITLE
IE 11 - Popup Formatting Issue

### ISSUE THREAD

**Issue by jpgilchrist** [froala/wysiwyg-editor#1468]
##### Expected behavior.

<img width="303" alt="screen shot 2016-08-18 at 9 49 09 am" src="https://cloud.githubusercontent.com/assets/5065660/17776084/14fd2944-6529-11e6-8f61-9e98e5ad44d3.png">
##### Actual behavior.

![rte1](https://cloud.githubusercontent.com/assets/5065660/17776058/fa0448f2-6528-11e6-9d3d-af13a1d24ffe.png)
##### Steps to reproduce the problem.

https://jsfiddle.net/jpegz/oqoy0um9/
##### OS.

Windows 10 pro
##### Browser.

![ie11](https://cloud.githubusercontent.com/assets/5065660/17776278/c9aeb074-6529-11e6-84dd-0e5d83ec6a40.png)

**Comment by stefanneculai** [comment]
Hi @jpgilchrist! We just checked this and it seems that we cannot reproduce it. We tried both the jsFiddle and our website.
