### ISSUE TITLE
SVG tags in code view are deleted

### ISSUE THREAD

**Issue by Tgoh** [froala/wysiwyg-editor#1469]
##### Expected behavior.
SVG tags typed in code remain in the editor.

##### Actual behavior.
After swapping back from code view, the SVG tags disappear.

##### Steps to reproduce the problem.
Paste:
<div>
    <svg id="circle" height="20mm" xmlns="http://www.w3.org/2000/svg">
        <circle id="greencircle" cx="30" cy="30" r="30" fill="red" />
    </svg>
</div>

Into the code editor, then go back to the designer.

##### OS.
Windows 10

##### Browser.
Chrome, Firefox

**Comment by stefanneculai** [comment]
Could you please make a jsFiddle? Thank you.

**Comment by stefanneculai** [comment]
I'm closing this due to lack of response. You should make sure that you allow them in the `htmlAllowedTags` and `htmlAllowedEmptyTags`.

**Comment by SeanKendle** [comment]
I want to jump in late here and say that you also want to allow their attributes:
`htmlAllowedAttrs` should include `"xmlns", "viewbox", "d"`
