### ISSUE TITLE
Copy-Paste from word loses color and font formatting 

### ISSUE THREAD

**Issue by danielwallace1** [froala/wysiwyg-editor#1472]
##### Expected behavior.

Colors and fonts should remain
##### Actual behavior.

Colors and fonts are lost
##### Steps to reproduce the problem.

Copy word document with colors and/or fonts and paste in editor
##### OS.

windows 7
##### Browser.

chrome 52

**Comment by stefanneculai** [comment]
I am closing this because it will be implemented as feature which adds the possibility to keep advanced formatting on paste.

**Comment by maverick42** [comment]
+1

**Comment by pelizza** [comment]
+1

Hey @stefanneculai , any news on this one?

Thanks!

**Comment by ingpdw** [comment]
+1

**Comment by stefanneculai** [comment]
@maverick42 @pelizza @ingpdw please make sure you are using the latest 2.6.0 version.

**Comment by pelizza** [comment]
It's working fine on latest versions! Thanks!

**Comment by maverick42** [comment]
Hi,
very good work ! Many people will be happy :) !

Frédérik

**Comment by mkerkeni** [comment]
I reproduce the problem in IE11

**Comment by stefanneculai** [comment]
@mkerkeni we would be happy to look into if you can send us the document you're pasting from. Thanks in advance.

**Comment by mkerkeni** [comment]
![capturefroala](https://user-images.githubusercontent.com/13117542/31241507-ed424e70-a9fb-11e7-9d29-512927446eee.PNG)
Thank you for your response. 
You will find the word file and the result in IE11.
[froala.docx](https://github.com/froala/wysiwyg-editor/files/1360306/froala.docx)

**Comment by SwapnilMane** [comment]
I am facing the same issue in IE11
Whereas in chrome it is working fine.
In IE11 it loses font, size and color of the text copied.

[Meeting notes (1).docx](https://github.com/froala/wysiwyg-editor/files/1722895/Meeting.notes.1.docx)

**Comment by stefanneculai** [comment]
@SwapnilMane are you facing this on our website as well?

**Comment by SwapnilMane** [comment]
Yes, I tried on your website using my IE browser.

**Comment by stefanneculai** [comment]
@SwapnilMane are you getting the Word Paste modal?

**Comment by amerrnath-murugan-E0711** [comment]
Any update on this issue

**Comment by SwapnilMane** [comment]
This issue is only regarding to IE browser.


[image: Headfitted Solutions Pvt Ltd] <http://www.headfitted.com/>


*SWAPNIL B. MANE* / SOFTWARE ENGINEER
swapnil@headfitted.com / +91-9403968396

Headfitted Solutions Pvt Ltd
+91 20 6410 4444
C 904, Pune IT Park, Off Aundh RoadPune, Maharashtra
http://www.headfitted.com
