### ISSUE TITLE
Add 'linkAlwaysBlank' behavior for the inserted links

### ISSUE THREAD

**Issue by alpha1988** [froala/wysiwyg-editor#1474]
I know that it can be a stupid question, but please say to me what should I do to apply editor's behavior of the active 'link Always Blank' parameter, also to the links that I add into the editor without using a special button ? (Without using the checkbox 'Open in new tab'. Only automatically , at the adding when text converting into the link tag.)

**Comment by alpha1988** [comment]
Yes, it is so but if we are talking only about typing the link into the Editor but if we will posting the link it doesn't add type="_blank". Tell me please if your will fix this in the future. Or it won't be fixed.


______________________________________________
З повагою
Саламаха Артем Валерійович

**Comment by stefanneculai** [comment]
It's fixed on the current master.

**Comment by alpha1988** [comment]
I made updating but it didn't change the logic of adding the "target". Please tell me what am I doing wrong ?

**Comment by stefanneculai** [comment]
In case you believe it doesn't work with the master version, please make a jsFiddle. Thank you.

Please make sure you update all the editor JS files.

**Comment by alpha1988** [comment]
https://jsfiddle.net/Alpha13/rLuehasx/6/  


______________________________________________
З повагою
Саламаха Артем Валерійович

**Comment by stefanneculai** [comment]
That is using the version 2.3.4. The current master branch is V2.3.5 which is under development.

**Comment by alpha1988** [comment]
ОК, and how or when can I use it ?

______________________________________________

Regards from Artem Salamakha

**Comment by stefanneculai** [comment]
You can download it from here at anytime. https://github.com/froala/wysiwyg-editor/archive/master.zip

**Comment by alpha1988** [comment]
I excuse but I got your archive, put files into my folder on the bower_components, restarting the project, but inserting the link still not working.
Tell me, what I doing wrong?


______________________________________________

Regards from Artem Salamakha

**Comment by stefanneculai** [comment]
I believe that you're not updating it correctly.. Please see: https://jsfiddle.net/rLuehasx/7/

**Comment by alpha1988** [comment]
I see that It also doesn't has target="_blank"


______________________________________________

Regards from Artem Salamakha

**Comment by stefanneculai** [comment]
Could you please make a recording? It works at my end.

**Comment by alpha1988** [comment]
https://www.youtube.com/watch?v=ZPIx3d3_F6M  


______________________________________________

Regards from Artem Salamakha

**Comment by alpha1988** [comment]
You've got the video ?
So what do you think , am I right or I am wrong and doing something wrong ?
______________________________________________

Regards from Artem Salamakha

**Comment by stefanneculai** [comment]
It appears that is not working for pasted links, not for the ones when you type.

**Comment by alpha1988** [comment]
Yes , it's what I want's to say. I think I badly explained. If it's so, sorry, please.


______________________________________________

Regards from Artem Salamakha

**Comment by alpha1988** [comment]
Hello. I want to know about the progress of this issue. How soon will it be fixed?
