### ISSUE TITLE
Restore 'sync' method?

### ISSUE THREAD

**Issue by philfreo** [froala/wysiwyg-editor#1475]
In v1 we had the `sync` method that I believe, when called, would immediately sync the editor's HTML to the textarea's `value`. In the v2 migration guide it says the event went away because it's no longer needed since it's automatically triggered upon `contentChanged`.

However this isn't a sufficient substitute because `contentChanged` is buffered/debounced/delayed from changes. In my case I need Cmd-Enter to save the form with the latest changes, and it's unacceptable that the last keystrokes you type before immediately hitting Cmd-Enter aren't saved.

Previously I'd call 'sync' in the save method. Now I do the following to tell Froala to flush out changes because I need it _now_:

```js
// Flush Froala Editor's latest HTML value into the textarea
// This would happen within a second or so anyway, but we need it done NOW
// so user doesn't lose changes
$textarea.val($textarea.froalaEditor('html.get'));
```

If you think writing the code above is a good idea, feel free to close this, but manually editing editing Froala's element's value felt like a bad practice to me. Perhaps you want to restore a 'sync' method to encapsulate this?

**Comment by stefanneculai** [comment]
You could use `undo.saveStep` which is forcing the sync in case there are any changes.

**Comment by philfreo** [comment]
thanks, that works

**Comment by philfreo** [comment]
For anyone reading this ticket, using `$(selector).froalaEditor('events.trigger', 'form.submit');` may be a better approach for you. See https://github.com/froala/wysiwyg-editor/issues/1465#issuecomment-248628572
