### ISSUE TITLE
<span lang=""> is added to each <p>. Why?

### ISSUE THREAD

**Issue by connect-technologies** [froala/wysiwyg-editor#1476]
##### Expected behavior.
No lang for each element. Lang should be set in the document header once.

##### Actual behavior.
If the editor language is set, each paragraph gets a extra <span lang="">...</span> element.
I think it is not necessary and it causes some problems here.

##### Steps to reproduce the problem.
Save some text in different editor languages.

##### OS.
--

##### Browser.
FF48.0.1

**Comment by stefanneculai** [comment]
Are you able to reproduce this on our website?

**Comment by connect-technologies** [comment]
Right now ... i tried - but no.
But my employees did it 4063 times in the last 2 weeks ... :)
They are all translating with different browsers, different windows/browser languages, different UI (editor) languages ... and so on... 
I'll ask them how they use the editor and will report this here.
But I thought you know, when this could happen.
Thanks.

(btw I use v2.1.0)

**Comment by stefanneculai** [comment]
I believe this is an issue that was there in an older version. Please upgrade to the latest one: 2.3.4.
