### ISSUE TITLE
Editor is not scrolling on pressing enter key

### ISSUE THREAD

**Issue by MartinHlavna** [froala/wysiwyg-editor#1477]
Hello,
we are using your editor. We have set up a fixed height for edit area and noticed that scroll is not working.
##### Expected behavior.

If I have content in editor larger than the actual viewport, on pressing ENTER key and thus adding new line at the bottom of area, element should scroll so I can see where is my caret.
##### Actual behavior.

Element is scrolled upon next text input (non-ENTER key press)
##### Steps to reproduce the problem.
1. Set up froala editor with fixed height
2. Press ENTER key enough times so scrollbar apears
##### OS.

Windows 7
##### Browser.

Tested and reproduced in:
Chrome 52.0.2743.116 m
Firefox 48.0.1

but I beleive it is reproducible in all Major browsers

**Comment by stefanneculai** [comment]
Is that happening on our website as well https://www.froala.com/wysiwyg-editor/docs/examples/predefined-height?

**Comment by MartinHlavna** [comment]
Thank you for quick reply.
It is not happening if I set height via config - but when height is set up via css ( in our case it is flex ). By fixed I meant that the editor is not enlarging itself as seen here: https://www.froala.com/wysiwyg-editor

**Comment by stefanneculai** [comment]
The option should be set via the `height` editor option, not using CSS.

**Comment by MartinHlavna** [comment]
height option is not much applicable to our case as editor should occupy rest of available height.

**Comment by stefanneculai** [comment]
Having the cursor set correctly depends on the height option. You can always set the height option after initializing the editor this way:
```js
$(selector).data('froala.editor').opts.height = new_height;
$(selector).data('froala.editor').size.refresh();
```

**Comment by sandeepsukhija** [comment]
Hello Stefan,
Even we are facing the same issue using the Froala editor. Please find the attached image illustrating the application structure
![applicationstructure_and_froalaeditor 1](https://cloud.githubusercontent.com/assets/3963603/18043259/546e333e-6de4-11e6-9817-7efa3a3e9e5d.png)

As illustrated in fig 1, the container contains the editor and other elements, there is a single scrollbar to scroll the data. After reaching at the bottom of the viewport(illustrated in fig 2), if user presses enter, the element doesn't scroll but when any other input key is pressed, the element scrolls. Can you help us on this as the size of the editor cannot be kept fixed.

**Comment by sandeepsukhija** [comment]
@stefanneculai, can you please help on this. I have mentioned the case in the above comment which illustrates the editor cannot have a fixed height. Is there any other workaround which can solve the issue for us.

**Comment by MartinHlavna** [comment]
@stefanneculai I have tried to apply your suggestion, to set froala height option according to actual editor height, but it does not solve the issue. I can see that height option is being set in style attribute by editor, but ENTER is not moving scrollbar anyway.

**Comment by stefanneculai** [comment]
@sandeepsukhija @MartinHlavna please make a jsFiddle. Thank you.

**Comment by MartinHlavna** [comment]
I have created fiddle which shows simplified layout and our problem.

https://jsfiddle.net/uh6ma9cf/

**Comment by ethael** [comment]
@stefanneculai We have the same issue here in our project. Any progress or fix date available?

**Comment by MartinHlavna** [comment]
@stefanneculai Any update on this?

**Comment by sandeepsukhija** [comment]
@stefanneculai can we get updates on this?

**Comment by stefanneculai** [comment]
@MartinHlavna on a closer look, it appears the problem is not coming from the editor, but from some CSS that you added there which breaks the way heights are computed. Here is a fix for it: https://jsfiddle.net/uh6ma9cf/3/.
