### ISSUE TITLE
S3 Upload is missing Security Token for Federated Users

### ISSUE THREAD

**Issue by tomcornall** [froala/wysiwyg-editor#1478]
Using an STS federated user requires the AWS_SESSION_TOKEN in requests made to S3. The header is called `x-amz-security-token`.

Is there anyway currently to include this header in the `imageUploadToS3` function? Otherwise is this something that warrants a fix? 

It seems odd that current Froala users are using root account credentials or IAM users to upload to S3.

Error msg without this token is as follows: `<Message>The AWS Access Key Id you provided does not exist in our records.</Message>`, confirmed through testing

**Comment by stefanneculai** [comment]
Sure, you can add it here:
https://github.com/froala/wysiwyg-editor/blob/master/html/file_s3_upload.php#L18
https://github.com/froala/wysiwyg-editor/blob/master/html/file_s3_upload.php#L167 (params are set as headers)

**Comment by tomcornall** [comment]
Ok thanks! For anyone running into this issue, policy and params look like this:

```
$policy = base64_encode(json_encode(array(
    // ISO 8601 - date('c'); generates uncompatible date, so better do it manually
    'expiration' => date('Y-m-d\TH:i:s.000\Z', strtotime('+1 day')),
    'conditions' => array(
        array('bucket' => $bucket),
        array('acl' => $acl),
        array('success_action_status' => '201'),
        array('x-requested-with' => 'xhr'),
        array('starts-with', '$key', $keyStart),
        array('starts-with', '$Content-Type', ''), // accept all files
        array('starts-with', '$x-amz-security-token', <session token>)
    )
)));
```


```
params: {
  acl: S3data.acl, // ACL according to Amazon Documentation.
  AWSAccessKeyId: S3data.accessKeyId, // Access Key from Amazon.
  policy: S3data.policy, // Policy string computed in the backend.
  signature: S3data.signature, // Signature computed in the backend.
  "x-amz-security-token": S3data.token
}
```
