### ISSUE TITLE
Froala strips out some tags that are required for email to be responsive and/or compatible with Outlook on some hi-dpi devices

### ISSUE THREAD

**Issue by snowcoda** [froala/wysiwyg-editor#1479]
##### Expected behavior.
Responsive emails require additional markup in the html tag and comments in the head. Froala should not remove this markup. I'm using Froala within Mautic but the behaviour will be the same elsewhere.

##### Actual behavior.
Froala strips out almost all of the head markup in the example given below.

##### Steps to reproduce the problem.
1. Enter the following HTML into the Froala HTML view:

```
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office">
	<head>
    	<!--[if gte mso 9]><xml>
 			<o:OfficeDocumentSettings>
  				<o:AllowPNG/>
  				<o:PixelsPerInch>96</o:PixelsPerInch>
 			</o:OfficeDocumentSettings>
		</xml><![endif]-->
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
```

2. Save the content and then view again.
3. Froala will have changed the HTML to the following:

```
<!DOCTYPE html>
<html>
	<head>
```

##### OS.
Tested with Windows 10 and OSX Yosemite.

##### Browser.
Tested with latest Google Chrome, Firefox, IE11 and Microsoft Edge.

Related:
https://github.com/mautic/mautic/issues/2370

**Comment by stefanneculai** [comment]
Are you testing using the Github master? This issue was fixed few days ago. https://github.com/froala/wysiwyg-editor/issues/1455

**Comment by drewkiimon** [comment]
I'm still having this problem in 2.7.5

**Comment by zachs77** [comment]
I am experiencing this as well in 2.15
