### ISSUE TITLE
Alignment on list itself rather than on indiviual Items

### ISSUE THREAD

**Issue by twalia** [froala/wysiwyg-editor#1480]
##### Expected behavior.
(Describe expected behaviour here)

##### Actual behavior.
(Describe actual behaviour here)

##### Steps to reproduce the problem.
Create a Ordered List in editor. 
Then click "Align Left" or Align Right" 
the list is displayed in the editor accordingly.
and the HTML that is generated is 
 <ol>
       <li style="text-align: center;">this is line 1</li>
        <li style="text-align: center;">line two</li>
      <li style="text-align: center;">line three</li>
</ol>

Is it possible to have alignment on the OL itself also ? reason im asking this is because we generate word document based whats in editor and when the word document is generated the list itself is not aligned.  it displays in center  etc.

Thanks

##### OS.
Windows 7 Prof

##### Browser.
Firefox 48.01

**Comment by twalia** [comment]
`<ol>
<li style="text-align: left;">this is line 1</li>
<li style="text-align: left;">this is line 2</li>
<li style="text-align: left;">this is line 3</li>
</ol>`

**Comment by stefanneculai** [comment]
There is no built-in way for this. I put this on our list and if there is more interest for it, then we'll see if it makes sense to implement it. In the meanwhile, I would recommend you to create a custom dropdown for it: https://www.froala.com/wysiwyg-editor/docs/examples/custom-dropdown
