### ISSUE TITLE
 Copy & Paste not adding extra lines between pasted sentences...

### ISSUE THREAD

**Issue by twalia** [froala/wysiwyg-editor#1481]
##### Expected behavior.
 Copy & Paste not adding extra lines between pasted sentences...

##### Actual behavior.
removes the line between paragraphs

##### Steps to reproduce the problem.
When I copy and paste from Word its not carrying over the breaks from one set of sentences to the next.
Example -
This sentence is in Word doc.

11/24/2014 Generally, when Tesla Motors makes an announcement about a new product or a future plan, its fans and advocates cheer lustily. The rest of the industry grunts, takes quiet notice, and carries on.

12/15/2014 if a recent report from a tried and true source is to be believed, Apple's upcoming new iPhone 7 and iPhone 7 Plus are now less than a month away from being released on September 16th

Instead it pasted as 
<p>11/24/2014 Generally, when Tesla Motors makes an announcement about a new product or a future plan, its fans and advocates cheer lustily. The rest of the industry grunts, takes quiet notice, and carries on.</p>
<p>&nbsp;12/15/2014 if a recent report from a tried and true source is to be believed, Apple&apos;s upcoming new iPhone 7 and iPhone 7 Plus are now less than a month away from being released on September 16th</p>

##### OS.
Windows 7 Prof

##### Browser.

Firefox 48.1

**Comment by twalia** [comment]
[TestFile-NoSpace.zip](https://github.com/froala/wysiwyg-editor/files/435183/TestFile-NoSpace.zip)

**Comment by stefanneculai** [comment]
New lines are converted to paragraphs. I just tested on the file you sent us and that is the way it is supposed to work.
