### ISSUE TITLE
Cloudflare minification breaks Froala due to `use strict`

### ISSUE THREAD

**Issue by alanhartless** [froala/wysiwyg-editor#1482]
It seems that something with `use strict;` and sites behind Cloudflare do not get along. https://github.com/mautic/mautic/issues/2286#issuecomment-242175240 Removing the `use strict;` lines seems to resolve the issue.

##### Expected behavior.
(Describe expected behaviour here)

Froala to work.

##### Actual behavior.
(Describe actual behaviour here)

Froala throws a JS error:
froala_editor.js:552SyntaxError: Unexpected string literal 'use strict'
(anonymous function) — froala_editor.js:552

##### Steps to reproduce the problem.
(Describe the steps to reproduce the problem here)

Use a site with Froala embedded and is behind Cloudflare with minification turned on.

##### OS.
(OS name and version here)

Mac

##### Browser.
(Browser name an version here)

Safari 9

**Comment by boynet** [comment]
@alanhartless Hi did you try to report this to Cloudflare?
