### ISSUE TITLE
cannot upload another image while the first one is being uploaded

### ISSUE THREAD

**Issue by yairpe** [froala/wysiwyg-editor#1483]
##### Expected behavior.
better - allow upload more than image at the same time 
good - prevent user from uploading another photo while it is still loading

##### Actual behavior.
dragging the second photo oens it in a new browser window. 

##### Steps to reproduce the problem.
1. drag a big image to the editor
2. drag another image while the first one is uploading

##### OS.
win 7

##### Browser.
Chrome 52

**Comment by stefanneculai** [comment]
It is not possible to upload multiple images at the same time for the moment. This feature is on our list and it will be implemented over the following months.
