### ISSUE TITLE
Lists do not get displayed when editor is on textarea. The ul, ol, li tags can be seen on a simple text area

### ISSUE THREAD

**Issue by raghuramvenkat** [froala/wysiwyg-editor#1484]
##### Expected behavior.
Expect list markers to be displayed

##### Actual behavior.
The tags are there but the list marker is not displayed in editor. The text is there but when the editor content is retrieved and displayed on text area, one can see all the list tags

##### Steps to reproduce the problem.
(Describe the steps to reproduce the problem here)

##### OS.
Mac elcapitan

##### Browser.
Chrome Version 52.0.2743.116 (64-bit)

**Comment by stefanneculai** [comment]
Could you please make a jsFiddle?

**Comment by stefanneculai** [comment]
I am closing this due to lack of response. We would be happy to look over it as soon as we get enough details to reproduce it.
