### ISSUE TITLE
Cannot insert image from a smartphone: "Something went wrong. Please try again"

### ISSUE THREAD

**Issue by yairpe** [froala/wysiwyg-editor#1487]
##### Expected behavior.
being able to upload an image from a mobile

##### Actual behavior.
receive an error message: "Something went wrong. Please try again" and the image is not inserted

##### Steps to reproduce the problem.
try to upload an image from a a mobile smartphone

##### OS.
Android Samsung S7

##### Browser.
Android browser and also same thing with Chrome browser

**Comment by stefanneculai** [comment]
Are you experiencing that on our website?

**Comment by yairpe** [comment]
Yes. I was testing at https://www.froala.com/wysiwyg-editor

**Comment by stefanneculai** [comment]
It should be fixed now. Could you please try again?

**Comment by yairpe** [comment]
Thank you. Now it works nicely :)

Is there a way to make the upload in the background? I mean that I can keep on writing text while it uploads? Since images size in mobile phones are few MB typically, it may take quite a long time to upload an image with 3G network

**Comment by stefanneculai** [comment]
We're working on a solution for allowing this.
