### ISSUE TITLE
requirejs------'LANGUAGE' of undefined

### ISSUE THREAD

**Issue by 79229788** [froala/wysiwyg-editor#1488]
Optimize RequireJS projects using r.js

 But console show “Uncaught TypeError: Cannot read property 'LANGUAGE' of undefined”

**Comment by stefanneculai** [comment]
Please see: https://github.com/froala/wysiwyg-editor/tree/master/html/require_js.

**Comment by for2B** [comment]
The page https://github.com/froala/wysiwyg-editor/tree/master/html/require_js 404

**Comment by stefanneculai** [comment]
@for2B the links changed in the meanwhile: https://github.com/froala/wysiwyg-editor/tree/master/html/3rd-party/require_js.
