### ISSUE TITLE
Meta tags are modified

### ISSUE THREAD

**Issue by allmkts** [froala/wysiwyg-editor#1492]
##### Expected behavior.
Do not modify the meta tag at all;  do not interfere with any custom html.   There are open graph properties for facebook and twitter that play a crucial role in web pages.  Your best expected policy is to leave the code alone, user is not served better by trying to second-guess his/her intentions, knowledge, use-case etc... Froala meta tags were recently enabled due to a previous issue, would be nice to just keep it simple, please.

##### Actual behavior.
Meta tag is modified, properties are removed

##### Steps to reproduce the problem.
1. go to code view '</>' to enter custom html
2. enter facebook open graph meta tag in the `<head>` section:

	`<meta property="og:description"   content="Our Landing Page" />`

3. save, and return to view custom html to find:

`<meta  content="Our Landing Page" >`

##### OS.
Win7, Linux

##### Browser.
Chrome, Firefox

**Comment by allmkts** [comment]
On a related Note, I can't modify my html tag either:
This:
`<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:og="http://ogp.me/ns#"
      xmlns:fb="https://www.facebook.coml">`
Becomes:
 `<html>`

**Comment by allmkts** [comment]
Further related note, a valid background image on the body tag can't be specified either:
This:
`<body style="background-image: url(http://someurl/image/bkg.jpg); background-repeat: no-repeat;>`
Becomes:
`<body style="background-image: url(&quot;&quot;); min-height: 300px;">`

All above issues are related in that they modify perfectly valid code.

**Comment by stefanneculai** [comment]
Please make sure you have your attributes added in `htmlAllowedAttrs` option.

**Comment by allmkts** [comment]
I have all of the htmlAllowedAttrs added as per the options documentation on your site.  Which specific htmlAllowedAttrs are you referring to for "<meta property = " ?  I've tried adding "property"  to  the list.  

The full list from your options is added, if there's a new one,  please indicate:

['accept', 'accept-charset', 'accesskey', 'action', 'align', 'alt', 'async', 'autocomplete', 'autofocus', 'autoplay', 'autosave', 'background', 'bgcolor', 'border', 'charset', 'cellpadding', 'cellspacing', 'checked', 'cite', 'class', 'color', 'cols', 'colspan', 'content', 'contenteditable', 'contextmenu', 'controls', 'coords', 'data', 'data-.*', 'datetime', 'default', 'defer', 'dir', 'dirname', 'disabled', 'download', 'draggable', 'dropzone', 'enctype', 'for', 'form', 'formaction', 'headers', 'height', 'hidden', 'high', 'href', 'hreflang', 'http-equiv', 'icon', 'id', 'ismap', 'itemprop', 'keytype', 'kind', 'label', 'lang', 'language', 'list', 'loop', 'low', 'max', 'maxlength', 'media', 'method', 'min', 'multiple', 'name', 'novalidate', 'open', 'optimum', 'pattern', 'ping', 'placeholder', 'poster', 'preload', 'pubdate', 'radiogroup', 'readonly', 'rel', 'required', 'reversed', 'rows', 'rowspan', 'sandbox', 'scope', 'scoped', 'scrolling', 'seamless', 'selected', 'shape', 'size', 'sizes', 'span', 'src', 'srcdoc', 'srclang', 'srcset', 'start', 'step', 'summary', 'spellcheck', 'style', 'tabindex', 'target', 'title', 'type', 'translate', 'usemap', 'value', 'valign', 'width', 'wrap']

**Comment by edelciomolina** [comment]
Hi @allmkts! Please, did you discover how resolve that?

**Comment by allmkts** [comment]
No, we abandoned froala due to its extensive interference with html; it seemed unreasonable and cumbersome, plus support as you can see is not efficient for any type of professional development.  Search for other tools, CKeditor is a good one, it allows to add modules.  Good luck.

**Comment by stefanneculai** [comment]
@edelciomolina if you could provide a jsFiddle, we would be happy to assist with it.
