### ISSUE TITLE
Pasted content uses the wrong tag in enter_div & enter_br

### ISSUE THREAD

**Issue by mrjlynch** [froala/wysiwyg-editor#1493]
##### Expected behavior.

When content is pasted, if the `enter: $.FroalaEditor.ENTER_DIV` or `enter: $.FroalaEditor.ENTER_BR` is set, the pasted content should either be wrapped with a `div` or `br` tag. 
##### Actual behavior.

When content is pasted,  when the `enter: $.FroalaEditor.ENTER_DIV` or `enter: $.FroalaEditor.ENTER_BR` is set, the content is wrapped with a `p` tag. 

The only way to overcome this is to use the paragraph format dropdown in the toolbar to change the content to `normal`. 
##### Steps to reproduce the problem.
1. Visit https://www.froala.com/wysiwyg-editor/docs/examples/enter
2. Copy content from a document (eg. Word, PDF) into the editor which uses `br` or `div` tags
##### OS.

Chrome
##### Browser.

Mac

**Comment by stefanneculai** [comment]
Could you please send us a document to copy from?

**Comment by mrjlynch** [comment]
[sample doc.pdf](https://github.com/froala/wysiwyg-editor/files/456502/sample.doc.pdf)

**Comment by mrjlynch** [comment]
[Sample Doc.docx](https://github.com/froala/wysiwyg-editor/files/456512/Sample.Doc.docx)
[sample.doc.pdf](https://github.com/froala/wysiwyg-editor/files/456521/sample.doc.pdf)

**Comment by mrjlynch** [comment]
I am still getting this error in master when copying from either of the above documents. (Using Preview and Word 2016)

**Comment by stefanneculai** [comment]
@mrjlynch "Preview", that's the magic word that you added later on. 😃

**Comment by mrjlynch** [comment]
I have tried this in master as of 22nd September. 

I am using preview in mac `10.11.4` and when I copy paste into the editor (using the above PDF document) the pasted content still is entered with `<p>` tags.

**Comment by mrjlynch** [comment]
I have reviewed this today in master, content is still being pasted with `<p>` tags under the same conditions as above ^

Thanks for your help.

**Comment by stefanneculai** [comment]
@mrjlynch please make sure you updated it correctly. With the master version opening the document with the Preview and pasting in ENTER_BR mode, it uses no tag, just as it should.

**Comment by mrjlynch** [comment]
I can confirm I updated froala correctly. 

Please see the video:
![ezgif com-video-to-gif 16](https://cloud.githubusercontent.com/assets/3665457/18873662/e06d92ea-8503-11e6-901b-21927f11bcf3.gif)

**Comment by mrjlynch** [comment]
Any chance we could review this? Thanks

**Comment by mrjlynch** [comment]
@stefanneculai this issue is still occuring. Please view the below video: 
![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/3665457/22774495/24de5640-eef3-11e6-8bb3-e7431269b83e.gif)

It seems as though the second (or last) paragraph still is wrapped with `<p>` tags. 
For instance, if you copy the above paragraph and this paragraph into [the enter-div example here](https://www.froala.com/wysiwyg-editor/examples/enter), this paragraph will be wrapped with `<p>` tags but the above won't.

**Comment by mrjlynch** [comment]
@stefanneculai just wondering if you've had the chance to review this? Thanks

**Comment by mrjlynch** [comment]
Hi @stefanneculai just following up to see if you have reviewed this? Any chance we could reopen this. Thanks
