### ISSUE TITLE
imageOutputSize doesn't work with width:100%

### ISSUE THREAD

**Issue by escopecz** [froala/wysiwyg-editor#1494]
When I paste to the editor when `imageOutputSize: true`:
`<img style="height: 10px; width: 100%;" src="some.gif">`

##### Expected behavior.
The output should be the same, the height and width attributes should be added. Like
`<img style="height: 10px; width: 100%;" src="some.gif" height="10" width="100%">`

##### Actual behavior.
But editor creates this:
`<img style="height: 10px; width: 100%; z-index: 3; position: relative; overflow: auto; cursor: pointer; margin: 5px auto; display: inline-block; float: none;" src="some.gif" width="813" height="10" fr-original-style="height: 10px; width: 100%;" fr-original-class="fr-dii fr-draggable">`

Notice that `width: 100%` is turned into `width="813"`.

I have asked this before and I ask again. Why are you mess with styles and classes? The original answer was because the editor needs it when the content is loaded for the second time. Well, the editor will modify the code like this every time, so why can't it do it every time and every time also clear it up before save? Our users hate the fact that the editor messes up with their hand-crafted super-optimized email themes.

##### Steps to reproduce the problem.
https://jsfiddle.net/L7ca17g1/

##### OS.
Ubuntu 16.10

##### Browser.
Chromium 10

**Comment by stefanneculai** [comment]
The editor is using the `fr-original-style` and `fr-original-class` to revert back the style that was there before converting the CSS to inline style. What I would recommend if you want not to have those in the output is to use a RegEx to remove these 2 attributes from the outputted HTML when you send the email.

**Comment by philfreo** [comment]
> I have asked this before and I ask again. Why are you mess with styles and classes? The original answer was because the editor needs it when the content is loaded for the second time. Well, the editor will modify the code like this every time, so why can't it do it every time and every time also clear it up before save? Our users hate the fact that the editor messes up with their hand-crafted super-optimized email themes.

This. 👍
