### ISSUE TITLE
Images are scaling wrong

### ISSUE THREAD

**Issue by LRAnimations** [froala/wysiwyg-editor#1495]
##### Expected behavior.
When i resize the width of my browser window, the height of the image should shrink aswell.

##### Actual behavior.
The height of the image doesn't change => The image stretches :(

##### Steps to reproduce the problem.
Just paste an image into the editor and scale the output window down.

The reason for this behaviour is that the height and width of the image are set in "px"... So its not surprising to have this ugly behaviour.. :( 

And I didn't change any settings like "imageOutputSize" or so. And I guess the default value should be false.... 

##### OS.
Windows 10

##### Browser.
Chrome 53

**Comment by stefanneculai** [comment]
By default, the images inside the editor have the property `max-width: auto`. If you want to keep that ration, then add the following css code:
```css
.fr-view img {
  height: auto !important;
}
```
