### ISSUE TITLE
Froala crashes on parsing sibling lists separated by text when using ENTER_BR

### ISSUE THREAD

**Issue by rhaynes** [froala/wysiwyg-editor#1496]
##### Expected behavior.
Editor should be able to parse `<ul><li>item 1</li></ul>some text<ul><li>item 2</li></ul>`
i.e, two lists separated by some text

##### Actual behavior.
Editor crashes with `Uncaught (in promise) DOMException: Failed to execute 'appendChild' on 'Node': This node type does not support this method.` in Chrome. Happens in Safari and Firefox as well with different message.

##### Steps to reproduce the problem.
```
  $('.editor').append('<ul><li>item 1</li></ul>some text<ul><li>item 2</li></ul>');
  $('.editor').froalaEditor({
    enter: $.FroalaEditor.ENTER_BR, // this is the key, the default <p> tags work fine
    multiLine: true,
    heightMin: 100,
    heightMax: 400,
  });
```

##### Solution
The problem occurs in this code block:
```
    function _listsJoinSiblings () {
      // Join lists.
      var sibling_lists = editor.$el.get(0).querySelectorAll('ol + ol, ul + ul');
      for (var k = 0; k < sibling_lists.length; k++) {
        var list = sibling_lists[k];
        if (editor.node.attributes(list) == editor.node.attributes(list.previousSibling)) {
          var childs = editor.node.contents(list);
          for (var i = 0; i < childs.length; i++) {
            list.previousSibling.appendChild(childs[i]);
          }
          list.parentNode.removeChild(list);
        }
      }
    }
```
I fixed it by changing the line 
```
if (editor.node.attributes(list) == editor.node.attributes(list.previousSibling)) {
```
to
```
if (editor.node.attributes(list) == editor.node.attributes(list.previousSibling) && list.previousSibling.tagName) {
```
This just checks to make sure the previous sibling is actually a list rather than just a plain text node.

##### OS.
Mac but probably happens everywhere

##### Browser.
Chrome, Firefox, Safari

**Comment by stefanneculai** [comment]
This is fixed on the master version. Please make sure you're using V2.3.4.
