### ISSUE TITLE
Issue with html being modified by Froala plugins when it shouldn't

### ISSUE THREAD

**Issue by ncmancuso** [froala/wysiwyg-editor#1499]
##### Expected behavior.
Font color changes but only selected content is modified

##### Actual behavior.
Changing the font color modifies things not even selected

##### Steps to reproduce the problem.
![froalabug](https://cloud.githubusercontent.com/assets/6825718/18326309/24226412-7513-11e6-8bfc-8b2ef2a4ae7b.gif)

##### OS.
Windows/OSx

##### Browser.
Chrome

**Comment by stefanneculai** [comment]
We do not consider this an issue. The editor is designed to clean those spans that have no attributes.

**Comment by ncmancuso** [comment]
We have users that rely on the ability to do this without their work being modified. As well as, when content is wrapped in a <div>, there is an issue with highlighting multiple lines to delete causes the editor to wipe out all conent.

![froalabug2](https://cloud.githubusercontent.com/assets/6825718/18351911/1b55d796-75aa-11e6-849f-cecce355fca1.gif)

**Comment by ncmancuso** [comment]
Moving the above comment to it's own issue.
