### ISSUE TITLE
Highlighting and deleting content is wiping everything in the editor

### ISSUE THREAD

**Issue by ncmancuso** [froala/wysiwyg-editor#1500]
When content is wrapped in a div, there is an issue with highlighting multiple lines to delete causes the editor to wipe out all conent. (ignore the typo :P)

##### Steps to reproduce the problem.
![froalabug2](https://cloud.githubusercontent.com/assets/6825718/18354751/bebd8a64-75b4-11e6-93b1-e634a20522c7.gif)

##### OS.
Windows/OSx

##### Browser.
Chrome

**Comment by JordanAtIgloo** [comment]
Any movement on this? We're still seeing this issue.
