### ISSUE TITLE
Get rid of jQuery dependency

### ISSUE THREAD

**Issue by FinesseRus** [froala/wysiwyg-editor#1505]
Hello. This is feature request.

According to [this page](https://www.froala.com/wysiwyg-editor/browsers) Froala Editor supports only modern browsers. They all implement browser API the same way and have useful stuff like `Array.prototype.map`. So there is no need in jQuery anymore.  jQuery is also an additional 100KB of traffic.

Today we have to use jQuery layer to interact with an editor:

```javascript
$.FroalaEditor.DefineIcon( 'restoreSelection', { NAME: 'upload' });
var $block = $( '#block' );
$block.froalaEditor();
$block.froalaEditor( 'html.set', '<h1>Hello, world!</h1>' );
```

This is very inconvenient especially in jQuery-free projects (hello, React).

It would be great if it works this way:

```javascript
FroalaEditor.defineIcon( 'restoreSelection', { NAME: 'upload' });
var editor = new FroalaEditor( document.querySelector( '#block' ));
editor.html.set( '<h1>Hello, world!</h1>' );
```

And there could be a jQuery wrap for `FroalaEditor` for backward compatibility, which appears if jQuery is included to the page.

Do you plan to remove jQuery dependency (maybe in future major version)?

**Comment by stefanneculai** [comment]
It is on our plan to remove the jQuery dependency, however that is unlikely to happen in V2.

**Comment by FinesseRus** [comment]
Got it. Thanks!

**Comment by monolithed** [comment]
@stefanneculai, could you tell when the 2nd version will be reached?

**Comment by guillaume86** [comment]
Is it on the roadmap? I'm considering this editor for a SaaS product but the jQuery dependency is annoying. (I've just finished to remove jQuery from the code base, even forking/rewriting some dependencies in the process, I'd like to keep it out now.)

**Comment by obrienmd** [comment]
+1

**Comment by philippkuehn** [comment]
Please.

**Comment by ringodotnl** [comment]
Bump

**Comment by pgib** [comment]
Bueller?

**Comment by stefanneculai** [comment]
We're working on it and you can see progress here: https://wysiwyg-editor-roadmap.froala.com/public/ideas/3597.

**Comment by Finesse** [comment]
jQuery is now inside the main editor script. You can get an instance this way:

```
const editor = new FroalaEditor(/* ... */);
const jQuery = editor.$;
```

> You can quit jQuery, but jQuery can't quit you

**Comment by chrisdeeming** [comment]
@stefanneculai I think this was an odd move, if I'm honest.

I know you haven't included the entirety of the jQuery code, but there's a good few thousand lines of code which, if you do actually already use jQuery, is now duplicated by the polyfills included with Froala v3.

Are there plans to properly remove jQuery at some point?
