### ISSUE TITLE
Pasting rich text from Google Docs loses formatting

### ISSUE THREAD

**Issue by philfreo** [froala/wysiwyg-editor#1506]
Here's a GDoc with some bold text: 

https://docs.google.com/document/d/1uGSFhPuGYFjAMUeOGkB1A5JSoQ6tuHboB_IHCGqEd7o/edit?usp=sharing

This copy/paste flow _keeps_ the bold formatting:

- GDocs -> OS X TextEdit -> Froala

This flow _loses_ the bold formatting:

- GDocs -> Froala

Is this expected?

**Comment by stefanneculai** [comment]
This is expected because when pasting from Google Docs, the font weight comes as inline style, while when you paste from TextEdit it comes as a `b` tag.

**Comment by philfreo** [comment]
@stefanneculai Is there a workaround or any way to make this work or do I really need to tell our customers "we don't support pasting from Google Docs"?

**Comment by muslim-niche** [comment]
any update on this issue please?

**Comment by dianaprajescu** [comment]
@muslim-niche please see issue #2545.
