### ISSUE TITLE
table tr tag bug

### ISSUE THREAD

**Issue by highca** [froala/wysiwyg-editor#1507]
if there are some of empty `<tr>` tags in `<table>, <br>` or`'<p>` tags inserted on the top of `<table>` tag by Froala editor.

Even if i delete the `<br>` or `<p>` tags, Froala insert again.

##### Steps to reproduce the problem.

1. insert table and create empty `<tr>` tags.

`<table>
<tr>
<td>something</td>
<tr>
<tr></tr>
<tr></tr>
<tr></tr>
</table>`

2. focus out of editor or switch from Code view.

3. some `<br>` or `<p>` tags created by froala editor.

##### OS.
Mac  OS 10.11.6
##### Browser.
Google Chrome 50+

**Comment by stefanneculai** [comment]
This should be fixed on Github master. Could you please give it a try?

**Comment by stefanneculai** [comment]
I am closing this due to lack of response.
