### ISSUE TITLE
reinitialize editor toolbar

### ISSUE THREAD

**Issue by Edisson** [froala/wysiwyg-editor#1508]
##### Expected behavior.
for example I initiate editor with inline toolbar
``
toolbarInline: true
``
when I click fullscreen mode, I'd like to change this option to false and use the toolbar normally at the top

##### Actual behavior.
calling fullscreen I tried a piece of code:
``
input.froalaEditor({
    toolbarInline: false
});
``
but it wasn't helpful

I'm not sure if it's possible to change this option on the fly?
if so how to achieve this behaviour?
##### OS.
Windows 

##### Browser.
Chrome: 53.0.2785.101
Opera: 39.0.2256.71

**Comment by stefanneculai** [comment]
Unfortunately, it is not possible to change that option after the editor has been initialized.
