### ISSUE TITLE
Inconsistencies with html.get encoding html enditites when requesting markers

### ISSUE THREAD

**Issue by scazz10** [froala/wysiwyg-editor#1509]
https://www.froala.com/wysiwyg-editor/docs/methods#html.get

##### Expected behavior.

`$('.selector').froalaEditor('html.get', true);` and `$('.selector').froalaEditor('html.get', false);` should return the same content (except for the addition of the selection markers) 

##### Actual behavior.
Froala returns encoded html when including the selection markers

##### Steps to reproduce the problem.

* Fill Froala with the content: `>  &gt;`  
* Save the selection markers: `this.getFroalaElement().froalaEditor('selection.save');`
* Grab the html without selection markers: 
`this.getFroalaElement().froalaEditor('html.get');` 
which returns: 
`"&gt; &nbsp;&amp;gt;&nbsp;"` (this is correct) 
* grab the HTML with the selection markers: 
`this.getFroalaElement().froalaEditor('html.get', true);` 
which returns
`"&gt; &nbsp;&gt;&nbsp;<span class="fr-marker" data-id="0" data-type="false" style="display: none; line-height: 0;">​</span><span class="fr-marker" data-id="0" data-type="true" style="display: none; line-height: 0;">​</span>"` 

Here, we lose our `&gt;` - it's encoded and becomes a > 

##### OS.
OS X Yosemite 10.10.5

##### Browser.
Chrome Version 52.0.2743.116 (64-bit)

**Comment by stefanneculai** [comment]
Would it be possible to create a jsFiddle?

**Comment by scazz10** [comment]
I can almost do a jsFiddle ;) 

https://jsfiddle.net/aw9t3ewh/1/

You need to type in the editor `>  &gt;` , then click the `testMarkerEncoding` button.

In the console, you'll see the different coding `&ampgt;` VS `&gt;` 


![image](https://cloud.githubusercontent.com/assets/16538287/18508895/132859a4-7a6e-11e6-9b7d-a55c625ea7f8.png)
