### ISSUE TITLE
Image manager: Folder listing support

### ISSUE THREAD

**Issue by horatiua** [froala/wysiwyg-editor#1510]
##### Expected behavior.
A way to add folder listings in Image manager browser.

##### Actual behavior.
Only image listings are available.

##### Steps to reproduce the problem.
Editor > Insert Image > Browse

##### OS.
Mac OS X El Capitan

##### Browser.
Google Chrome

**Comment by stefanneculai** [comment]
For the moment this feature is not available. If you want you could group images by tags and us tags just like folders.

**Comment by sbosell** [comment]
The image manager becomes useless when you have a large media library.  I hope you reconsider adding a better way than tags to manage images like folders or nested tags.

**Comment by stefanneculai** [comment]
@sbosell an improved Image Manager is on it's way.

**Comment by sbosell** [comment]
Any update on this?

**Comment by StefanNeuser** [comment]
+1 what @sbosell mentioned. A possible behaviour could be

1. if tags are available within the imageManagerLoadURL response than group them  the tags and just load and show the images of the first (alphabetic order) tag. 
2. if you browse to another tag, froala should load and show the images assigned to this tag

At the moment the current Froala loads and show all images if the file manager gets open. In our case for example we get images from pages, news, newsletters which ends in a messed up overview within image browsing
