### ISSUE TITLE
File manager same as Image manager

### ISSUE THREAD

**Issue by horatiua** [froala/wysiwyg-editor#1511]
Is there a way to add a File Manager plugin that is similar to Image Manager plugin?

Thanks!

**Comment by stefanneculai** [comment]
No, we're working on a solution for this. Unfortunately, I don't have an ETA to share with you for this.

**Comment by clwolcott** [comment]
Is there any updates on this?

**Comment by cshehadi** [comment]
just putting in another vote of support for this.

**Comment by StefanNeuser** [comment]
Is there a vote about this?

**Comment by StefanNeuser** [comment]
Why this this ticket is closed? The mentioned feature request has nothing to do with this. Can you check this please?

**Comment by stefanneculai** [comment]
@StefanNeuser we do not use this repo for feature-requests, but for bug tracking.

**Comment by daneshka** [comment]
I still can't find this feature. Is it still under development?
