### ISSUE TITLE
tag br inside empty div

### ISSUE THREAD

**Issue by emanueleparati** [froala/wysiwyg-editor#1514]
We open an HTML source code with froala. This code contains tag like: 

`<div class="clear fix"></div>`

Froala inserts inside this code a <br> tag, changing the source HTML in this way:

`<div class="clear fix"><br></div>`

Often this behaviour changes what the user sees. Can we turn off this behaviour?

Mac Osx 10.11
Safari, Chrome, FF

**Comment by stefanneculai** [comment]
You could add the `div.clear.fix` tag to the `htmlAllowedEmptyTags` option if you want to avoid that.

**Comment by emanueleparati** [comment]
Sorry but it doesn't work.
As you can see, whenever I load the content from db the `<br>` tag appears. I tried with `<div></div>` too, without class attribute, but doesn't work anyway.

<img width="901" alt="screen shot 2016-09-15 at 15 08 34" src="https://cloud.githubusercontent.com/assets/15732159/18554063/4f8db088-7b63-11e6-809d-fbc79155e55a.png">
