### ISSUE TITLE
br tags inserted automatically

### ISSUE THREAD

**Issue by emanueleparati** [froala/wysiwyg-editor#1515]
##### Expected behavior.
When we have an HTML code containing empty tags, like for example `<div></div>`, we don't want froala editor inserts a `<br>` tag inside it like: `<div><br></div>`. 

##### Actual behavior.
Now, froala editor when encounters a tag like `<div></div>` changes it in `<div><br></div>`.

##### Steps to reproduce the problem.
Open an html field with `<div></div>` inside and switch to code view. The following code appears: `<div><br></div>` instead of `<div></div>`.

##### OS.
Mac Osx 10.11
##### Browser.
Safari, Chrome, FF

**Comment by stefanneculai** [comment]
The DIV tag has been designed to be a block tag and block tags should have BR tags inside in order to be editable. If you want to change this behaviour you could add the following line before initializing the editor, but you should be aware that this might cause unexpected editing behaviours.

```js
$.FE.BLOCK_TAGS = ['address', 'article', 'aside', 'audio', 'blockquote', 'canvas', 'dd', 'dl', 'dt', 'fieldset', 'figcaption', 'figure', 'footer', 'form', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'header', 'hgroup', 'hr', 'li', 'main', 'nav', 'noscript', 'ol', 'output', 'p', 'pre', 'section', 'table', 'tbody', 'td', 'tfoot', 'th', 'thead', 'tr', 'ul', 'video'];
```

**Comment by gmacherey** [comment]
Hi guys, I'm having the same problem and no solution so far. Any solution on this ? the $.FE.BLOCK_TAGS is not doing anything.

Thanks
