### ISSUE TITLE
Words Running together when copy paste from word doc

### ISSUE THREAD

**Issue by twalia** [froala/wysiwyg-editor#1517]
##### Expected behavior.
When I copy paste text from word document. Certain words gets combined together

##### Actual behavior.
Should not combine words

##### Steps to reproduce the problem.
attached is the zip file. which contains two word document. I reported this earlier but it was fixed. (so i attached the original word document too). I have another word document, but when i copy paste from there it broken again  

##### OS.
(OS name and version here)
Win 7 prof

##### Browser.
(Browser name an version here)
Firefox; v48.02
[Froala_WordsRunningTogether_Test2.zip](https://github.com/froala/wysiwyg-editor/files/477533/Froala_WordsRunningTogether_Test2.zip)

**Comment by stefanneculai** [comment]
Are you using the Github master? Could you also please make a recording for it?

**Comment by twalia** [comment]
Hi,

Thanks for fixing it.

Is there a way to get only this changes  or unminified js  ? I’m not using the minified version of “froala_editor.min.js” in our project.

Any help would be appreciated.

Thanks

**Comment by stefanneculai** [comment]
The unminified JS will be available inside your account as soon as we make the official release. Most likely next week.
