### ISSUE TITLE
Cannot change colour of text directly next to text 

### ISSUE THREAD

**Issue by SCCarl** [froala/wysiwyg-editor#1519]
##### Expected behavior.
After inputting text and changing the first half to one colour, changing the second half to a different colour should change text to that colour.

##### Actual behavior.
text doesn't change colour

##### Steps to reproduce the problem.
Type in some text
Change first half of text to one colour
Try to change second half of text to a different colour (all one word)

##### OS.
Windows 10

##### Browser.
IE11 11.589

**Comment by stefanneculai** [comment]
Could you please make a recording?

**Comment by SCCarl** [comment]
Hello sorry about long delay, had some time off but github won't let me attach the recording. Tried as gif but resolution quite small, is there an email address I can send the file too?

**Comment by stefanneculai** [comment]
@SCCarl you can upload it somewhere (Youtube / Dropbox) and send a link from there as well. We just tried it again with different setups and we couldn't replicate this problem with the master version. Please make sure you're using the master version. I am closing this until we get more details.
