### ISSUE TITLE
Can't insert thin space

### ISSUE THREAD

**Issue by masseuro** [froala/wysiwyg-editor#1523]
##### Expected behavior.

When insert thinspace (option + space on macos, ALT+0160 on windows) 
Or copy paste text with thin space will be keep as thin space 
##### Actual behavior.

All thin space are replace by simple space on windows. 
Not all thin space on macos, can find a schema for explain why
##### Steps to reproduce the problem.

You can reproduce here https://www.froala.com/wysiwyg-editor
write text with all space writting with thinspace, watch code view or copy past on word (or libreoffice) with special characters mode active, to see if thinspace was not transform.
##### OS.

Windows 10
OSX 10.11.6
##### Browser.

 Chrome 53

**Comment by stefanneculai** [comment]
Could you please send a text that includes thin space? When you use option + space it doesn't insert thin space either (I tried in Pages).

**Comment by stefanneculai** [comment]
Closing this due to lack of response.
