### ISSUE TITLE
image tag width attribute is converted into style attribute

### ISSUE THREAD

**Issue by cecilialam** [froala/wysiwyg-editor#1525]
##### Expected behavior.
The width attribute in the IMG tag is left alone. e.g. `<img src="/assets/editor/docs/photo14.jpg" class="fr-fil" alt="book" width="150"/>`

##### Actual behavior.
The width attribute in the IMG tag is converted to style attribute with width property. `<img src="/assets/editor/docs/photo14.jpg" class="fr-fil fr-dii fr-draggable" alt="book" style="width: 150px;">`

##### Steps to reproduce the problem.

1. on https://www.froala.com/wysiwyg-editor/docs/examples/image-styles documentation, copy the  HTML sample and paste it to the HTML mode of the editor on the page.
2. switch to WYSIWYG mode.
3. switch to HTML mode again.
4. Inspect and compare the IMG tag. 

##### OS.
OS X version 10.11.5 (15F34)

##### Browser.
Chrome Version 52.0.2743.116 (64-bit)

##### NOTE:
This created an issue with the image we have in the email content received by Microsoft Outlook v2007, 2010, and 2013.

**Comment by stefanneculai** [comment]
If you want to keep the image `width` attribute in the output, then you should use the https://froala.com/wysiwyg-editor/docs/options#imageOutputSize option.
