### ISSUE TITLE
Table context menu makes cell selection difficult

### ISSUE THREAD

**Issue by kmacampbell** [froala/wysiwyg-editor#1528]
##### Expected behavior.
When working with tables, I would expect the context menu to be non-intrusive so that it doesn't get in the way when selecting other cells - for example when I'm copy/pasting data down multiple cells within the same column.

##### Actual behavior.
The context menu gets in the way, making it hard to select the next cell I want to work with. (See attached gif.)

##### Steps to reproduce the problem.
1) Create a table with multiple rows
2) Type some characters within a cell in the top row. Copy the characters.
3) Select the cell immediately below. Paste.
4) Select the cell immediately below. Paste. (Notice it is difficult to select this cell due to the context menu.)

##### OS.
Windows 10 pro

##### Browser.
Chrome 53.0.2785.116 m (64-bit)

![froala_context_menu_makes_cell_selection_difficult](https://cloud.githubusercontent.com/assets/22326825/18681605/d5e25004-7f36-11e6-811b-7fc045000a69.gif)

**Comment by stefanneculai** [comment]
Thank you for the feedback. We are continuously looking forward to change the way it works. For now you can close the popup using the ESC key.

**Comment by gthomas82** [comment]
Is there any other work around for this ?

Can we add a close icon on the right side of the dialog ? 

How do we collapse this dailog
