### ISSUE TITLE
Iframe mode - image resize feature not working properly

### ISSUE THREAD

**Issue by fmooreNS** [froala/wysiwyg-editor#1529]
##### Expected behavior.
When the editor is in iframe mode, if an image is selected and the user is trying to resize it, the image resize behavior should work the same way it does when the editor is not in iframe mode.

##### Actual behavior.
When the editor is in iframe mode, if an image is selected and the user is trying to resize it, it is very easy to get the mouse pointer outside of the drag handler bounds.  If the mouse gets outside of the bounding rectangle of the image, the resize function stops working.  Then, if the mouse pointer is moved back over the image, the resize function begins working again.  It is somewhat difficult to get the image state back to normal at this point.

##### Steps to reproduce the problem.
1. Set iframe: true option when initializing the Froala editor.
2. Insert an image into the editor.
3. Select the image and try to resize it.

##### OS.
Windows 7

##### Browser.
FireFox 48, Chrome 53

**Comment by stefanneculai** [comment]
After checking more details on the email received, it appears that the CSS stylesheet for the image plugin was not included.

**Comment by fmooreNS** [comment]
Thank you!
