### ISSUE TITLE
Ability to edit <ol> to add classes and 'start' attribute

### ISSUE THREAD

**Issue by Sly-Ripper** [froala/wysiwyg-editor#1530]
Switching from ckeditor this option would be nice to see. Classes would allow for "list-style-type" to be changed and the start attribute would be ideal for lists that need to start at something other than 1.

**Comment by stefanneculai** [comment]
We use this repo for bug tracking only, therefore I marked this as a `feature-request` and the issue is going to be closed. Thank you for sending it over to us.
