### ISSUE TITLE
How to set default on checkbox "Open in new tab" as checked?

### ISSUE THREAD

**Issue by karuzela** [froala/wysiwyg-editor#1531]
I would like to set the checkbox "Open in new tab" as automatically checked, unfortunately the only available option regarding the matter (linkAlwaysBlank) doesn't cover this aspect. Is there any way to do it?

**Comment by stefanneculai** [comment]
There is no such feature built-in the editor for that. What you could do is to register to the `popups.show` event and mark it that way the popup is shown. Here is some code that 

```js
  $('selector').on('froalaEditor.initialized', function (e, editor) {
    editor.popups.onShow('link.insert', function () {
      var $popup = editor.popups.get('link.insert');
      console.log ($popup);
      $popup.find('input[type="checkbox"]').prop('checked', true);
    });
  }).froalaEditor();
```

**Comment by Hillcow** [comment]
This really should be an option.

**Comment by salali** [comment]
Agree that this should be an option

**Comment by jfadich** [comment]
I also agree this should be an option.

**Comment by kevin-lin-enovational** [comment]
> There is no such feature built-in the editor for that. What you could do is to register to the `popups.show` event and mark it that way the popup is shown. Here is some code that
> 
> ```js
>   $('selector').on('froalaEditor.initialized', function (e, editor) {
>     editor.popups.onShow('link.insert', function () {
>       var $popup = editor.popups.get('link.insert');
>       console.log ($popup);
>       $popup.find('input[type="checkbox"]').prop('checked', true);
>     });
>   }).froalaEditor();
> ```

This might be breaking when _editing_ a link, do test that before shipping.

**Comment by shnigi** [comment]
Dunno why this is closed, I would also need this feature.

**Comment by daanishraj** [comment]
Can we please reopen this ticket? At my company, this functionality is in high demand among users

**Comment by frompxkrat** [comment]
i miss this option since version froala 2.7.
today is the version 4.0.18 current and unfortunately still nothing has done in this regard. very sad!

**Comment by frompxkrat** [comment]
if i set option "linkAlwaysBlank: true", then i can't choice a checkbox for it and then if i save the content, there are no target='_blank' .. with this option target is always _self

**Comment by sergeyandrogogic** [comment]
This definitely should be an option, the code above is too clunky for such a simple thing.

**Comment by WeihanLi** [comment]
Seemed still no option to configure for this?

**Comment by Nithin0104** [comment]
If you add this 
`{ linkAlwaysBlank: true,
        linkEditButtons: ["linkOpen", "linkEdit", "linkRemove"],
        linkInsertButtons: ["linkBack"]}`
to your config Options. You will not get the "Open in new Tab" options at all. And "Open Link" button will automatically open the link in new page.
