### ISSUE TITLE
Slow performance with Froala on browsers edge, Internet explorer 10 and 11

### ISSUE THREAD

**Issue by bpetersenmw** [froala/wysiwyg-editor#1532]
**Problem**
It seems froala 2.3.4 using the angular 1 editor (https://www.froala.com/wysiwyg-editor/docs/framework-plugins/angular1) is slow when using IE 10, IE 11, and edge.

I can move this to the froala angular git hub (maybe more appropriate)

**Work Around**
If I just use the javascript for froala 2.3.4 and interact with it using jquery in my angular application, performance is acceptable across all browsers. 

This may be the solution we use for now. 
Based out of this example:
https://www.froala.com/wysiwyg-editor/examples/full-featured
##### Expected behavior.

Using the angular editor should be just as fast as the javascript one.
https://www.froala.com/wysiwyg-editor/docs/framework-plugins/angular1
##### Actual behavior.

Using the angular froala editor is very slow in IE 10, 11, and edge.
Just the act of typing text is very unresponsive. The user sees a large lag time between typing and updating in the editor.
##### Steps to reproduce the problem.

(Describe the steps to reproduce the problem here)
Include the angular-froala code and create an instance in the application
Include the 2.3.4 froala editor javascript files in the application

`<div id="composeScrollable" class="container">
  <div class="newsletterTabHeader">
    <div translate="newsletter-summary__summary-component--title" class="newsletterTabHeaderText"></div>
  </div>
  <div class="newsletterSummaryBody">
    <div translate="newsletter-summary__summary-component--header-label" class="newsletterLabels"></div>
    
    <textarea id="froalaEditor" ng-model="summary" froala="froalaOptions"></textarea>
    <div class="newsletterLabels">{{charCounter}}</div>
  </div>
</div>`

Inject 'froala' into controller

`$scope.froalaOptions = {
        key: "mykey",
        heightMin: 60,
        heightMax: 200,
        charCounterMax: 500,
        scrollableContainer: '#composeScrollable',
        toolbarButtons: ['bold', 'italic', 'underline', '|', 'fontFamily', 'fontSize', 'color','|', 'undo'],
        placeholderText : $scope.placeHolderText,
        linkInsertButtons:[],
        requestWithCORS: false,
        useClasses: false,
        imageOutputWidth: true,
        imageStyles: {
            'fr-bordered': 'Bordered'
        }
    };`
##### OS.

Windows 7
##### Browser.

IE 10, IE 11, Edge

**Comment by stefanneculai** [comment]
We just tested this and there doesn't appear to be any difference. Are you using the latest angular plugin version (v2.3.4) or only the editor V2.3.4? Could you provide a demo?

**Comment by stefanneculai** [comment]
@bpetersenmw are you having the Developer Tools enabled? We are noticing a considerable performance drop-off with the DT enabled.
