### ISSUE TITLE
Froala inserts fr-marker into outside of editor elements on blur

### ISSUE THREAD

**Issue by RuslanZavacky** [froala/wysiwyg-editor#1533]
##### Expected behavior.
Happens only in FF.
When on blur, we do selection.save and click on outside element of Froala editor, Froala shouldn't insert fr-marker into that element.

##### Actual behavior.
Behaviour should be exactly the same for different browsers. Clicking on outside element of froala editor, should not add fr-marker.

##### Steps to reproduce the problem.
**JS Fiddle**
https://jsfiddle.net/jbLwuqx5/2/

**Recoding**
Firefox (bug present): http://quick.as/nRD6Cy6b0
Chrome (work fine): http://quick.as/b3poudpjx

In Chrome looks like nothing is happening, but 2nd block is getting all DOM nodes and pasting them, and nothing 

##### OS.
OS X El Capitan 10.11.6

##### Browser.
Firefox (latest) and Firefox Developers Edition
Chrome (latest)

**Comment by RuslanZavacky** [comment]
Any news?

**Comment by stefanneculai** [comment]
You can check if the editor has focus before adding the markers like this: https://jsfiddle.net/9deh2f09/. The `selection.save` method is not designed to check if the editor has focus, it can be used on other editable elements as well.

**Comment by RuslanZavacky** [comment]
@stefanneculai I am not sure, that what you've suggested might be treated as a fix. 

Our use case:

when you are working with editor, and then clicking somewhere outside of it, we want to preserve cursor position. To do that, we have to rely on blur event. When blur even happens, we "save" editor focus position and then restore it later.

With your suggested fix, editor.core.hasFocus() is always false, and selection.save won't be executed. 
It will work as "true" only if the place where we click, has stopPropagation for mouse down event, which we can't do for every place where we click, eg. this means, that editor won't loose focus.

----

Also, the main issue is, that it **doesn't** work **only** in Firefox, Chrome, IE, Safari works well. So I suppose, it is a still problem, how Froala works with Firefox Selection API

**Comment by stefanneculai** [comment]
@RuslanZavacky please make a jsFiddle. Thank you. Browsers work different and handle selection differently.

**Comment by RuslanZavacky** [comment]
@stefanneculai thats in your jsFiddle actually:

https://jsfiddle.net/9deh2f09/1/ (I've updated it slightly, added alert(1))
editor.core.hasFocus() is always false on blur. 

So, maybe we are doing something wrong - what we want to achieve: whenever editor looses focus, we want to preserve cursor. Next time when someone clicks B, I or like adding a link, it should be added at the position, where it was before.

What we think of now: if blur event is not working with selection, we can preserve selection on key press, focus, mouse down - events that happens while you are still inside an editor.

**Comment by stefanneculai** [comment]
Unfortunately, it is not possible to do that in Firefox and is browser specific. That is because the blur event is being triggered after the editor has already lost the selection and you cannot save it any longer. What you could do is to put there a mousedown event for other elements on the page and store selection there if the selection is inside editor.

**Comment by RuslanZavacky** [comment]
Okey, thank you @stefanneculai thats how we will proceed with that then.
