### ISSUE TITLE
Tab key not working as expected

### ISSUE THREAD

**Issue by mrjlynch** [froala/wysiwyg-editor#1534]
##### Expected behavior.
1. `Tab` key should indent naked text
2. `Tab` key should indent list item when previous item is **bold**
##### Actual behavior.
1. `Tab` key has no action on naked text
2. `Tab` key has no action when previous bullet is **bold** (_only on master_)

**Comment by stefanneculai** [comment]
By default the tab is designed to make the editor loose focus, not add indentation. If you enable the `tabSpaces` option then you'll get indentation.

**Comment by mrjlynch** [comment]
Thankyou for clarification. That solves `1`. 

However, I understand there is still a bug with `2`, as demonstrated here:
![ezgif com-video-to-gif 18](https://cloud.githubusercontent.com/assets/3665457/19105915/fe4ba62e-8b27-11e6-862b-e04ed3532ed4.gif)

The `tab` key does not work when the parent bullet is bold.
