### ISSUE TITLE
Backspace on indented bullet should decrease indent

### ISSUE THREAD

**Issue by mrjlynch** [froala/wysiwyg-editor#1535]
##### Expected behavior.
Backspace on indented bullet should unindent bullet

##### Actual behavior.
![ezgif com-video-to-gif 17](https://cloud.githubusercontent.com/assets/3665457/18913809/4bb11670-85cd-11e6-8a8a-dbd1071a623c.gif)

**Comment by stefanneculai** [comment]
We consider the current behavior as being the correct one, the list item should be removed when it's the first one, not unindented.

**Comment by mrjlynch** [comment]
Would you consider making the behaviour consistent with Microsoft Word? 

![ezgif com-video-to-gif 19](https://cloud.githubusercontent.com/assets/3665457/19106060/aacad762-8b28-11e6-857f-ba04275db6f5.gif)

**Comment by stefanneculai** [comment]
We're implementing it the way we consider as being correct, not how Word works. When you are at the beginning of list and hit backspace, it will get out of the bullet list. That should happen here as well.
