### ISSUE TITLE
Quick Insert Button should use an icon instead of inline SVG

### ISSUE THREAD

**Issue by addbrick** [froala/wysiwyg-editor#1537]
## Expected behavior.
To be able to replace the Quick Insert Icon with our own custom one using
`$.FroalaEditor.DefineIcon('quickInsert', {NAME: 'add-22'})`

## Actual behavior.
Quick insert icon is a hard coded SVG so we have to hack in our own icon
`editor.shared.$quick_insert = $('<div class="fr-quick-insert"><a class="fr-floating-btn" role="button" tabindex="-1" title="' + editor.language.translate('Quick Insert') + '">' + editor.icon.create('quickInsert') + '</a></div>');`

**Comment by stefanneculai** [comment]
Unfortunately, the icons from Font Awesome don't look great for this and that's why we used a SVG. Indeed, it makes sense to have defined the same way because they are an icon.
