### ISSUE TITLE
URL input in hyperlink popup should not allow empty string

### ISSUE THREAD

**Issue by addbrick** [froala/wysiwyg-editor#1538]
## Expected behavior.
URL input to not accept empty strings as valid input. If not possible then it would be nice to expose a callback to validate the link input, so we can decide what validation we want

## Actual behavior.
URL input allows empty string links to be created

**Comment by stefanneculai** [comment]
The way described here can be used for this: https://github.com/froala/wysiwyg-editor/issues/1235#issuecomment-251943999.
