### ISSUE TITLE
Add option to disable drag'n'drop upload for files and images

### ISSUE THREAD

**Issue by addbrick** [froala/wysiwyg-editor#1540]
## Expected behavior.
To be able to set an option which disables the ability to upload files via the user dragging and dropping them into the editor.

In my hack implementation I called these options `fileDropUpload` and `imageDropUpload`, both `true` by default

**Comment by stefanneculai** [comment]
That can easily be done by returning false in the callback of the `drop` event.

**Comment by strokirk** [comment]
Hi @stefanneculai , can you provide a fiddle illustrating how this should be done?

In the [documentation](https://www.froala.com/wysiwyg-editor/docs/events#drop) it says we are supposed to use `on('froalaEditor.drop', fn)`, but I don't get any event on the callbacks I register there. However, in issue #1466, you show that we can register a callback in the `froalaEditor.initialized` handler, that will receive the `drop` event, but only when `true` is passed as the third argument.
Please check out my fiddle which shows the issue more clearly:
http://jsfiddle.net/4ho3afgu/

Is this usage correct? And if so, would it be possible to update the docs to say how `drop` events are supposed to be caught?

**Comment by stefanneculai** [comment]
https://github.com/froala/wysiwyg-editor/blob/master/html/events/drop.html#L78

**Comment by strokirk** [comment]
@stefanneculai Following that example does not work for me unfortunately, see this fiddle:
http://jsfiddle.net/mm9sn0h9/

**Comment by stefanneculai** [comment]
That is because on image drop, the editor is designed to upload it inside the image plugin. If you want to prevent that, then you could listen to the event a bit different:

```js
  $(selector).on('froalaEditor.initialized', function(e, editor) {
    editor.events.on('drop', function (dropE) {
    	// Does print.
      console.log('drop')
      
      // Prevent default behavior.
      return false;
    }, true)
  })
  .froalaEditor()
```

**Comment by strokirk** [comment]
Ok! Thank you for that explanation. Is there any documentation for when to use `editor.events`? The  events? The docs currently only mention using `froalaEditor.*` events.
