### ISSUE TITLE
(IE11) - Extra click needed to enable content edit when image is the first thing added

### ISSUE THREAD

**Issue by JordanAtIgloo** [froala/wysiwyg-editor#1544]
##### Expected behavior.
Upon inserting a new image and clicking away to clear the edit controls, users should be able to start typing to add new content with no further actions. 

##### Actual behavior.
When using IE11, an extra click is needed in the editor area before the cursor will appear and allow the user to start typing. Chrome and FF don't show the cursor right away either, but they default to a new line when you start typing. 

##### Steps to reproduce the problem.
Tested against Froala version 2.3.4 and reproducible in the JSFiddle [here](https://jsfiddle.net/JordanAtIgloo/v61xgcdw/)

1) From the toolbar in an empty editor, click 'Insert Image'
2) Choose an image and upload it. (I used a local file, but inserting via URL produces the same 		results.)
3) When the upload finishes, click away from the image (one click) to clear the image edit controls
4) Begin typing to add text content

##### OS.
Windows 8.1

##### Browser.
IE11

Possibly related: [https://github.com/froala/wysiwyg-editor/issues/1543](https://github.com/froala/wysiwyg-editor/issues/1543)

If it helps, I was able to fix this by adding an extra call to _placeCursor() in the image plugin in _exitEdit().

So just: 
`
if (editor.browser.msie) {
  _placeCursor();
}
_unmarkExit();
`
It isn't a perfect solution, since it means that IE has slightly different behaviour compared to other browsers, but it's working well enough for now. 

Edit: I noticed that in Firefox (49) the 'Unlicensed Froala Editor' warning does not appear. Just FYI :)

**Comment by stefanneculai** [comment]
Unfortunately, this will remains as a `wontfix`. IE has a very strange way of handling selection next to image.

**Comment by JordanAtIgloo** [comment]
@stefanneculai , any thoughts on just making an extra call to _placeCursor()? That's the solution we currently use. It's a slightly different experience between IE and Chrome/Firefox, but at least users aren't frustrated by starting to type and not seeing their work.

**Comment by stefanneculai** [comment]
@JordanAtIgloo we tried with _placeCursor and in our tests it is not doing any difference.

**Comment by JordanAtIgloo** [comment]
@stefanneculai that's very strange, but thanks for looking into it. I'll take another look when I have a chance, and provide more details if possible. 

Thanks for your help!

**Comment by JordanAtIgloo** [comment]
@stefanneculai I took another look at this one, and I am still able to replicate this bug against Froala version 2.3.5. Users who insert images before any other content in IE are required to click a second time after clearing the image editor controls before the cursor appears. 

I modified _exitEdit() slightly to fix the issue for our users. The entire (modified) function looks like this: 

```javascript
function _exitEdit (force_exit) {
  if ($current_image && (_canExit() || force_exit === true)) {
    editor.toolbar.enable();

    $image_resizer.removeClass('fr-active');

    editor.popups.hide('image.edit');

    $current_image = null;
    
    // Cursor positioning fix
    if (editor.browser.msie) {
      _placeCursor();
    }

    _unmarkExit();
  }
}
```

The extra call to _placeCursor() puts the cursor on a new line, all ready to accept new input. We have had this change in place for several months now with no unwanted side-effects being reported. 

Please let me know if there is any more information I can provide. 

Thank you!
