### ISSUE TITLE
HTML code snippets are ignored on load

### ISSUE THREAD

**Issue by escopecz** [froala/wysiwyg-editor#1546]
##### Expected behavior.
When writing a HTML snippet in the editor, for example:
```
<html>html</html>
```
If I switch to the code view, the editor will correctly decode it like this:
```
&lt;html&gt;html&lt;/html&gt;
```
So I save the result, but when I load this very same code back to the editor, it strips it to:
```
html
```
##### Actual behavior.
The encoded code snippet should not be stripped.

##### Steps to reproduce the problem.
See the problem in https://jsfiddle.net/ws7d3757/

##### OS.
Ubuntu 16.10

##### Browser.
Chromium 10

**Comment by stefanneculai** [comment]
Please see: https://github.com/froala/wysiwyg-editor/issues/482#issuecomment-83714915. Entities should be escaped before adding in textarea.
