### ISSUE TITLE
user custom html tags are being removed

### ISSUE THREAD

**Issue by esmonica** [froala/wysiwyg-editor#1547]
Hello,

I have just downloaded the editor for evaluation and I am wondering how to be able to allow user custom html tags

##### Expected behavior.
The user custom  html tags (< newscontent > </ newscontent >) should remain in place

##### Actual behavior.
When loading the html page, the custom tag < newscontent > </ newscontent > gets removed.

##### Steps to reproduce the problem.

I am loading a html document which has some custom tags <newscontent>
I have tried adding this tag to the option "htmlAllowedTags":

htmlAllowedTags: ['a', 'abbr', 'address', 'area', 'article', 'aside', 'audio', 'b', 'base', 'bdi', 'bdo', 'blockquote', 'br', 'button', 'canvas', 'caption', 'cite', 'code', 'col', 'colgroup', 'datalist', 'dd', 'del', 'details', 'dfn', 'dialog', 'div', 'dl', 'dt', 'em', 'embed', 'fieldset', 'figcaption', 'figure', 'footer', 'form', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'header', 'hgroup', 'hr', 'i', 'iframe', 'img', 'input', 'ins', 'kbd', 'keygen', 'label', 'legend', 'li', 'link', 'main', 'map', 'mark', 'menu', 'menuitem', 'meter', 'nav', 'noscript', 'object', 'ol', 'optgroup', 'option', 'output', 'p', 'param', 'pre', 'progress', 'queue', 'rp', 'rt', 'ruby', 's', 'samp', 'script', 'style', 'section', 'select', 'small', 'source', 'span', 'strike', 'strong', 'sub', 'summary', 'sup', 'table', 'tbody', 'td', 'textarea', 'tfoot', 'th', 'thead', 'time', 'title', 'tr', 'track', 'u', 'ul', 'var', 'video', 'wbr', 'newscontent']

also I have tried:

  htmlAllowedTags:['.*']

but the newscontent tag is still being removed by the editor

##### OS.
Windows 10 64 bit

##### Browser.
Chrome Version 53.0.2785.143 m

**Comment by esmonica** [comment]
I found out the problem...The tag has empty, thus it was being removed. I have now added:

 htmlAllowedEmptyTags: ['newscontent']

and the tag is not being removed :)

**Comment by SeanKendle** [comment]
Have you been able to make custom elements draggable? I've tried and can drag them, but dropping them results in them being deleted.

I also have my custom tag in "htmlAllowedEmptyTags" and "htmlAllowedTags".

Also, fyi,  you can make your code easier to read and edit by doing this (if you're just adding new tags to the arrays):

```
let newHtmlAllowed = $.FE.DEFAULTS.htmlAllowedTags;
newHtmlAllowed.push("div p", "div div p", "module-jbl");
var froalaDefaultOptions = {
    htmlAllowedTags: newHtmlAllowed
}

$("#target").froalaEditor(froalaDefaultOptions);
```

**Comment by SeanKendle** [comment]
Ok, I've got it figured out.  I had put `contenteditable="false"` in the element to prevent it from having anything inside of it.  This prevented it from being dropped.  I removed it and now it works.  I wonder how I'll prevent adding anything into my custom element.  Back to the drawing board.
