### ISSUE TITLE
Is Templating supported by Froala. If yes, How can be that acheived ?

### ISSUE THREAD

**Issue by KhanSangeeta** [froala/wysiwyg-editor#1548]
##### Expected behavior.
There would be set of custom templates in a dropdown over the Froala toolbar. User selects the template, which can populated inside the body of editor with dummy text. User should able to edit and enter its own text.

##### OS.
(OS name and version here)

##### Browser.
(Browser name an version here)

**Comment by stefanneculai** [comment]
There is no built-in feature for that, but you can easily achieve it by creating a [custom dropdown](https://froala.com/wysiwyg-editor/docs/concepts/custom/dropdown) and using the `html.set` method.
