### ISSUE TITLE
Unexpected behavior when creating a link on an inline SVG+use

### ISSUE THREAD

**Issue by ndimatteo** [froala/wysiwyg-editor#1552]
I created a pretty simple dropdown that inserts an inline SVG+use, wrapped in a link tag. Code is here:
````javascript
$.FroalaEditor.RegisterCommand('insertSocial', {
  title: 'Insert Social Icon',
  focus: true,
  undo: true,
  type: 'dropdown',
  refreshAfterCallback: true,
  options: {
    'facebook': "<svg class='icon'><use xlink:href='#icon-facebook'></use></svg> Facebook",
    'twitter': "<svg class='icon'><use xlink:href='#icon-twitter'></use></svg> Twitter",
    'instagram': "<svg class='icon'><use xlink:href='#icon-instagram'></use></svg> Instagram",
    'linkedin': "<svg class='icon'><use xlink:href='#icon-linkedin'></use></svg> Linkedin",
    'google': "<svg class='icon'><use xlink:href='#icon-google'></use></svg> Google",
    'youtube': "<svg class='icon'><use xlink:href='#icon-youtube'></use></svg> YouTube",
    'vimeo': "<svg class='icon'><use xlink:href='#icon-vimeo'></use></svg> Vimeo",
    'tumblr': "<svg class='icon'><use xlink:href='#icon-tumblr'></use></svg> Tumblr",
    'yelp': "<svg class='icon'><use xlink:href='#icon-yelp'></use></svg> Yelp",
    'rss': "<svg class='icon'><use xlink:href='#icon-rss'></use></svg> RSS Feed",
  },
  callback: function(cmd, val) {
    this.html.insert('<a href="#'+val+'" target="_blank" class="social-link"><svg class="icon"><use xlink:href="#icon-'+val+'"></use></svg></a>');
  }
});
````
It inserts great, but once it's inserted the link+SVG icon are near impossible to edit and the cursor is totally jacked.

##### Expected behavior.
The expected behavior should be similar to that of a text link or an IMG link:
1. I should be able to click the linked item and bring up the link options consistently
2. I should be able to move my cursor before and after each link+svg
3. I should be able to freely delete the link+svg on backspace

##### Actual behavior.
- After inserting a second icon, the cursor randomly jumps to between the first and second icon, and then I can't move the cursor after the second icon anymore:
![2010-insert_multiple](https://cloud.githubusercontent.com/assets/737188/19218696/d94eb59c-8dce-11e6-9e7c-b39c59d4fcbc.gif)

- I'm unable to click and edit the link, the link options seem to arbitrarily show sometimes and other times not at all:
![2010-click_issue](https://cloud.githubusercontent.com/assets/737188/19218698/e5170df2-8dce-11e6-867d-687ab03bdd20.gif)

- If I arrow the cursor back from a different line it sporadically skips place and jumps to the far left of the line (you'll see it show between both icons for a split second then jump to the far left, all on it's own):
![2010-cursor_jumping](https://cloud.githubusercontent.com/assets/737188/19218703/f3213ba2-8dce-11e6-9c8e-b59fb3520a59.gif)

- If I backspace from another line it removes all of the SVG links, rather than one at a time:
![2010-deleting_all](https://cloud.githubusercontent.com/assets/737188/19218707/fc697e90-8dce-11e6-9a25-959e27d8801a.gif)

Let us know if you can assist, as adding icons like this is a pretty big feature for us. Thanks!

##### Steps to reproduce the problem.
Simply insert an inline SVG with the <use> tag and with a link wrapped around it then try to interact with it via the editor.

##### OS.
Mac / OSX Yosemite 10.10.5 (14F27)

##### Browser.
Google Chrome / Version 53.0.2785.143 (64-bit)

**Comment by stefanneculai** [comment]
The problem comes because of the way the selection is placed by the browser inside the link elements in this case. Here is what you can do to overcome this problem.

```js
$(editor_selector).on('froalaEditor.initialized', function (e, editor) {
        // Mouse down on link.
        editor.events.$on(editor.$el, editor._mousedown, 'YOUR_BTN_SELECTOR', function () {
          var range = editor.doc.createRange();
          range.selectNodeContents(this);

          if ($(this).text().length == 0) {
            $(this).prepend($.FE.INVISIBLE_SPACE);
          }

          var sel = editor.win.getSelection();
          sel.removeAllRanges();
          sel.addRange(range);
        })

        // Mouseup on link.
        editor.events.$on(editor.$el, editor._mouseup, 'YOUR_BTN_SELECTOR', function (e) {
          e.preventDefault();
        });
});
```

**Comment by ndimatteo** [comment]
Hmm,

This isn't working at all. I've added the following and none of the console.logs even fire:

````javascript
$('.editable').on('froalaEditor.initialized', function (e, editor) {

  console.log('working? (initalized');
  
  // Mouse down on link.
  editor.events.$on(editor.$el, editor._mousedown, '.social-link, svg', function () {
    var range = editor.doc.createRange();
    range.selectNodeContents(this);
    console.log('working? (down)');

    if ($(this).text().length == 0) {
      $(this).prepend($.FE.INVISIBLE_SPACE);
      console.log('working? (invisible space)');
    }

    var sel = editor.win.getSelection();
    sel.removeAllRanges();
    sel.addRange(range);
  })

  // Mouseup on link.
  editor.events.$on(editor.$el, editor._mouseup, '.social-link, svg', function (e) {
    e.preventDefault();
    console.log('working? (up)');
  });

});
````

**Comment by stefanneculai** [comment]
We're using it for a similar case and works fine just this way. Could you please make a jsFiddle? Thank you.

**Comment by stefanneculai** [comment]
One thing to try first. Make sure you are setting the initialized event before the editor is initialized. Other way, that event might get assigned after the editor is already initialized.

**Comment by ndimatteo** [comment]
@stefanneculai Ah good call, it was because I set it after. However now that it's in there, and I can confirm all the events are firing properly, the original issue still remains... The cursor is sporadic and I still can't really click and edit the URL with ease... am I missing something here?

**Comment by stefanneculai** [comment]
Could you please make a jsFiddle? We are shooting in the dark without having the hands on the code to play with it. Thank you.

**Comment by ndimatteo** [comment]
@stefanneculai sorry about that. I've managed to put an example together on codepen, which should give you access to everything: http://codepen.io/ndimatteo/pen/ozdPpO

**Comment by ndimatteo** [comment]
You can see that you can't consistently click on the icons after they're inserted and after inserting 2 icons the cursor jumps between them and you can't move the cursor after it, nor traverse the content in an expected way.

**Comment by stefanneculai** [comment]
With the latest commit the following code should work just fine for selecting the link:
```js
.on('froalaEditor.initialized', function (e, editor) {
  // Mouse down on link.
  editor.events.$on(editor.$el, editor._mousedown, '.social-link', function (e) {
    e.preventDefault();

    var range = editor.doc.createRange();
    range.selectNodeContents(this);

    var sel = editor.win.getSelection();
    sel.removeAllRanges();
    sel.addRange(range);
  })

  // Mouseup on link.
  editor.events.$on(editor.$el, editor._mouseup, '.social-link', function (e) {
    e.preventDefault();
  });
})
```

Also, it would be good to add the class `fr-deletable` to the links because this way the link will be deleted all together when you hit backspace. Because of the way the browser `contenteditable` selection works when you have a `svg` inside a link and navigate using the arrows, the cursor would jump over that tag. Unfortunately, we don't have a workaround for this.

**Comment by ndimatteo** [comment]
Hey guys, saw you pushed up to NPM so I was able to finally test this out.

While it seems I can add more than one icon now without it going haywire, there's still some glaring issues unfortunately :(

1. I can't get the cursor to go between the icons, so if I need to remove one or add a new one between two icons I can't without having to delete the entire thing, since the cursor just jumps to the line before when I try to navigate:
<img width="288" alt="screen shot 2016-10-25 at 11 40 03 pm" src="https://cloud.githubusercontent.com/assets/737188/19712506/917cc880-9b0c-11e6-86d0-1d9ebbd5d963.png">

2. If I try to mitigate the above issue by putting a space after each insert, it goes haywire like it did before after the second insert by placing the cursor between the first and second with no way to get it to go at the end of the latest insert:
<img width="283" alt="screen shot 2016-10-25 at 11 37 24 pm" src="https://cloud.githubusercontent.com/assets/737188/19712528/b21f3640-9b0c-11e6-9c62-ebf7e36404b9.png">

3. It also appears that the popup is showing up multiple times, layered on top of one another? Seems odd.

All-in-all I really hope we can come up with a solution here. It pains me that tinyMCE, with all of it's flaws, didn't have any issues adding something simple like this; yet we're encountering lots of issues here with froala just trying to insert some custom html links.

Thoughts?

**Comment by stefanneculai** [comment]
Hi @ndimatteo, have you followed my last comment? https://github.com/froala/wysiwyg-editor/issues/1552#issuecomment-253158819

**Comment by ndimatteo** [comment]
hey @stefanneculai, yea I updated the ````.on(''froalaEditor.initialized')```` as you outlined and I'm using the latest on NPM.

I can update the codepen we were referencing before so you can see if you want?

**Comment by stefanneculai** [comment]
@ndimatteo if you could update the codepen it would be great. Thank you.

**Comment by ndimatteo** [comment]
@stefanneculai sure, here's the updated pen: http://codepen.io/ndimatteo/pen/ozdPpO

For some reason with this stripped down version the link popup doesn't appear twice, but it absolutely does in our dev environment. Same issues otherwise.

Also appears you have to have some text typed out first before beginning to insert the icons, otherwise it for some reason throws them individually within their own `<p>` tags.

**Comment by stefanneculai** [comment]
@ndimatteo please try this: http://codepen.io/anon/pen/dpxjER.

**Comment by ndimatteo** [comment]
hey @stefanneculai thanks, this is reallyyyyy close!

The only issue I see is that if the icons are the **first** thing in the editor, I can't get the cursor to move in front of the first icon. Meaning, if I want to add text or something else before the icons I can't (without of course going into the code view and manually adding a new element before the icons).

Any ideas there?
