### ISSUE TITLE
froalaEditor.contentChanged with accented characters or empty initial text

### ISSUE THREAD

**Issue by maverick42** [froala/wysiwyg-editor#1555]
Hello,

There is a strange behavior that I have found. When the editor contains accented characters (French by example) the "froalaEditor.contentChanged" event is fired systematically when you click outside the editor even if you do not change the original text !

The same happens with an empty INITIAL text ...

With a text without accented  all works fine :)

My Code

> }).on('froalaEditor.save.after', function (e, editor, response) {
>     // sauvegardé, effacement bouton sauvegarder
>     $.myLib.forceVisibility('#btn-froala-save', false);
> }).on('froalaEditor.save.error', function (e, editor, error) {
>    $.myLib.AlertNotUpdate();
> }).on('froalaEditor.contentChanged', function (e, editor) {
>    // contenu changé, affichage bouton sauvegarder ...
>    $.myLib.forceVisibility('#btn-froala-save', true);
>  });

Best
Frédérik

##### OS.
Windows 7
Chromium

**Comment by stefanneculai** [comment]
Could you please let us know the exact steps to reproduce this? Thank you.

**Comment by maverick42** [comment]
Hi,

I tried to reproduce but I did not arrive...  I made a jsFiddle

[test](https://jsfiddle.net/maverick42/en22td16/23/)

You must click first in one froala editor and then outside

With FireFox 49.0.1  all save buttons appear.
With Chromium Version 46.0.2489.0 (64-bit) only the buttonBlank appear
With Chrome Version 53.0.2785.143 m only the buttonBlank appear

With my application on ALL browser ! (with more froala editor options an include js/css) the save button appear only if I set an accented or empty string .... ????

Best regards
Frédérik

**Comment by stefanneculai** [comment]
It's already fixed on master: https://jsfiddle.net/en22td16/24/.
