### ISSUE TITLE
Cursor or marker disappears

### ISSUE THREAD

**Issue by M-Knobloch** [froala/wysiwyg-editor#1557]
Cursor disappears, when switching to code view and then back to wysiwyg view

##### Expected behavior.
Cursor remains on selected position

##### Actual behavior.
Cursor disappears

##### Steps to reproduce the problem.
Try it on your online sampe instance

ps. answering to support questions will probably reduce filed issues

**Comment by stefanneculai** [comment]
We consider this as a `feature-request` and we keep here only bugs and enhancements. It is already on our TODO list.
