### ISSUE TITLE
Add option to disable button tooltips

### ISSUE THREAD

**Issue by rdrenth** [froala/wysiwyg-editor#1558]
I've looked for this option, but i can't seem to find it. Anyways it would be very nice to have an option to disable button tooltips

We're using the editor in a rather minimalistic way (only undo, redo, bold, italic and underline buttons) and the tooltips are a bit overkill there.

What do you guys think about this?

**Comment by dianaprajescu** [comment]
The option is called `tooltips` and the default value is `true`. Just set it to `false` if you don't wish to use tooltips.

```javascript
$('.selector').froalaEditor({
    tooltips: false
})
```

**Comment by rdrenth** [comment]
Awesome, thanks for implementing this option.

I'll await the next tagged release.
