### ISSUE TITLE
styling lost when copy/pasting from Microsoft OneNote

### ISSUE THREAD

**Issue by reallyrobkerr** [froala/wysiwyg-editor#1559]
##### Expected behavior.

extra lines are not added
bold, italic, underline, etc formatting is preserved
##### Actual behavior.

extra blank lines are added
bold, italic formatting is lost
##### Steps to reproduce the problem.

copy from Microsoft OneNote into Froala
##### Browser.

Chrome, Firefox, IE

OneNote original:
![onenote](https://cloud.githubusercontent.com/assets/16905960/19277771/e5dc4bfe-8fa8-11e6-926e-33e5662ad466.png)

OneNote paste:
![onenotepaste](https://cloud.githubusercontent.com/assets/16905960/19277792/f9c38506-8fa8-11e6-900d-5ef484c4faea.png)

**Comment by stefanneculai** [comment]
Could you please send over to us the document you're copying from? Thank you.

**Comment by reallyrobkerr** [comment]
Here you go - apparently GitHub doesn't support .one files as attachments, so I had to zip it

[Test Notes.one.zip](https://github.com/froala/wysiwyg-editor/files/522921/Test.Notes.one.zip)

**Comment by stefanneculai** [comment]
There is going to be an update for all Office pasting over the following weeks. We are working on an improved pasting from Office.
