### ISSUE TITLE
Add plugin source un-minified.

### ISSUE THREAD

**Issue by somazx** [froala/wysiwyg-editor#1560]
I'm interested in developing a custom plugin that would work similar to the Table plugin where clicking on tables/cells triggers a popup with further options for that table.

But since the plugin source isn't available un-minified I can't really read it as a reference, and the official plugin documentation is a bit sparse.

It would also be great if the internal API were better documented. For example, what entirely does 'RegisterCommand' do? What are all the possible options, their default values, etc?

Thanks

**Comment by stefanneculai** [comment]
The `RegisterCommand` method is detailed in our docs: https://www.froala.com/wysiwyg-editor/docs/concepts/custom/button. The unmnified JS is available under the Advanced and OEM licenses.

**Comment by dankantor** [comment]
@stefanneculai I'm having the same issue and have been struggling for days. The link you posted is not very detailed. I have a custom button that inserts some custom HTML. I want to show inline edit buttons when the custom html element is clicked. I don't see any example that shows how to do it.

**Comment by stefanneculai** [comment]
@dankantor the `toolbar.showInline` method does just that: https://www.froala.com/wysiwyg-editor/docs/methods#toolbar.showInline.

**Comment by dankantor** [comment]
@stefanneculai thanks. I ended up writing a custom plugin with two different popups. One that is triggered off a custom toolbar button and one which is triggered when my custom html element is clicked.

**Comment by cbadger-montecitobank** [comment]
I'm in the same situation as @dankantor and the OP.  I want to show a inline toolbar (separate from the main toolbar) that only displays when I hover over my custom element.  Similar to how the Table/Link plugins works, where clicking on a table/link in the wysiwyg shows a toolbar for editing that particular element.

I don't see any Froala examples for accomplishing this in Froala 4.x.  I understand you can set the main toolbar to be inline, but I'm looking for a secondary toolbar similar to what the aforementioned plugins provide.

Thanks!
