### ISSUE TITLE
Custom Dropdown Button Width for template text

### ISSUE THREAD

**Issue by connect-technologies** [froala/wysiwyg-editor#1561]
##### Expected behavior.
Button should have not a specific width
<img src="http://connect-technologies.de/froala_dropdown_2_right.png">

##### Actual behavior.
css: width:38px
<img src="http://connect-technologies.de/froala_dropdown_2_wrong.png">

##### Steps to reproduce the problem.
Its quite a copy&paste from the custom dropdown example from the docs.

```
$.FroalaEditor.DefineIcon('languageDropdownIcon', { NAME: iconName, template: 'text'})
$.FroalaEditor.RegisterCommand('languagesDD', {
			title: 'Language',
			type: 'dropdown',
			icon: 'languageDropdownIcon',
			refreshAfterCallback: false,
			options: {
				<?php
				foreach($qLanguages as $froalaLang)
				{
					echo "'".$froalaLang['id']."': '".$froalaLang['name']."',";
				}
				?>
			},
			focus: true,
			callback: function (cmd, val, params) {
				console.log($.FroalaEditor);
				var dropDownElement = $('#answer-form button[data-cmd="languagesDD"]');
				var langName = languages[val];
				dropDownElement.html('<span>' + langName + '</span>');
				$('.answer-langid').val(val);
			}
		});
```

##### OS.
(OS name and version here)

##### Browser.
FF49

Froala v2.3.5

**Comment by connect-technologies** [comment]
Hi Stefan,
thanks for the fix, but are you sure the button gets the class "fr-btn-text"? I just got a "fr-btn-" with my example.
thanks

**Comment by stefanneculai** [comment]
@connect-technologies please try again with the latest commit. Thanks for testing it.

**Comment by poddarkhushbu07** [comment]
@stefanneculai Hi, I am having this same issue while working with Froala v2.9.2

![Froala_dropdown](https://user-images.githubusercontent.com/31128078/55539252-d69ec000-56dd-11e9-9991-8e17901597cd.png)
