### ISSUE TITLE
closing tag img

### ISSUE THREAD

**Issue by maverick42** [froala/wysiwyg-editor#1563]
Hi,

I have a problem with img tag generated by froala and the conversion to PDF with itext/xmlworker.

Exemple html
`<p style="box-sizing: border-box;"><img src="http://localhost:8080/photos/1/5/1/3/5/15135.jpg" style="width: 300px;" class="fr-dib fr-draggable">fred</p>
`

With this, I have an exception in xmlworker
`RuntimeWorkerException: Invalid nested tag p found, expected closing tag img.`

xmlworker expects there to be a closing img tag like this  (everything works perfectly if it is present)

`..class="fr-dib fr-draggable" /> fred</p>`

how can do this without changing the contents of the editor manually ?  

Best
Frédérik

Windows 7 / Chromium

**Comment by maverick42** [comment]
You  can test any modification with this link :

[demo xmlworker](http://demo.itextsupport.com/xmlworker/)

**Comment by stefanneculai** [comment]
The editor output is HTML5, not XML valid. In HTML5, self closing tags do not have to be closed. If you want to close them, you could use the html.get event and add that closing tag using a regex.

**Comment by maverick42** [comment]
Hi Stefan,

I agree with you that the froala output is HTML5. But I understand that to close these tags is not "forbidden". There might have been an option in froala like : 

`"SelfClosingTags": false`

Your solution is not very "elegant" even it would work. 

I preferred to use the java parser jsoup (with the XML parser) to perform this operation properly just before PDF conversion. And it works perfectly :)

[like this](http://try.jsoup.org/~zX8frwf0qMJxjhNGTLtDX4SethM)

Best regards
Frédérik

**Comment by AbdeljabbarProgrammer** [comment]
how to do Jsoup in java

**Comment by AbdeljabbarProgrammer** [comment]
I did it and did not give me a result. How can I do it? Maybe I did not know how to do it

**Comment by maverick42** [comment]
Hi,

Indeed, I have not used jsoup finally. I chose htmlcleaner. It works very well.
http://htmlcleaner.sourceforge.net/index.php

Best, Frédérik
