### ISSUE TITLE
Cannot Trigger Image Manager Page Load

### ISSUE THREAD

**Issue by mattpwest** [froala/wysiwyg-editor#1564]
##### Expected behavior.
Expect image manager to load an additional page of images if the initial page fits in the available space or on scroll.

##### Actual behavior.
Unable to trigger an additional page load to see if my back-end endpoint is correct.

##### Steps to reproduce the problem.
Tried increasing images in a page up to 20, but it still fits on a full HD screen so the area isn't scrollable. Doesn't try to load the next page of images when the first page fits in the available area.

Tried changing my browser to run in a smaller window so that modal contents is scrollable. Scrolled down to the bottom but no additional loading was triggered.

##### OS.
Windows 10

##### Browser.
Google Chrome 53.0.2785.143 (Official Build) m (64-bit)

**Comment by mattpwest** [comment]
As a side note the documentation also doesn't specify how the page request will be made... I assumed a URL parameter with 0 based paging so first request was to /api/media/froala and second request should be to /api/media/froala?page=1.

**Comment by stefanneculai** [comment]
The image manager plugin is not making requests to load a new page, it is expecting to get the full list with the path to the images and when you scroll it will make requests to load the additional images.

**Comment by mattpwest** [comment]
Ah ok, I understand, thank you!
