### ISSUE TITLE
Copy and Paste a link from Froala adds an extra empty link

### ISSUE THREAD

**Issue by joeldaigle05** [froala/wysiwyg-editor#1565]
##### Expected behavior.

Copy and pasting of a link will add a new link without extra markup.
##### Actual behavior.

Pasting a link external to Froala content _usually_ pastes correctly with the new single link.
Pasting a link already in Froala content will paste the new link with an empty duplicated link as well.
##### Steps to reproduce the problem.
- Copy URL or link and paste into Froala editor.
- Select pasted link in Froala, copy and paste again in the editor.
- More times than not, the link is added with the extra empty link above it.
##### OS.

OSX 10.11.6 / Windows 10
##### Browser.

Chrome 53

![pastelinkfromfroalatodfroala](https://cloud.githubusercontent.com/assets/20441785/19391432/90f777cc-91fa-11e6-966f-a564a895baa0.gif)

**Comment by stefanneculai** [comment]
This is fixed in V2.3.5.
