### ISSUE TITLE
Tab within table

### ISSUE THREAD

**Issue by raerae13** [froala/wysiwyg-editor#1566]
##### Expected behavior.

My users are familiar with Word. When they create a table, they are expecting to be able to tab between the cells. When they type a paragraph, they expect that tabbing will indent the paragraph. Is there a way to preserve tabbing between cells when tabSpaces is greater than 0?
##### Actual behavior.

Tabbing within a tablecell when tabSpaces is greater than 0 indents the text rather than moves to the next cell.
##### Steps to reproduce the problem.

Set tabSpaces to a number greater than 0. Create a table in the editor. Click in a table cell. Hit the tab key.
##### OS.

Windows 10
##### Browser.

Chrome, IE

**Comment by stefanneculai** [comment]
Last commit makes it as default behavior.
