### ISSUE TITLE
undo button and contentChanged event with ipad voice recorder

### ISSUE THREAD

**Issue by maverick42** [froala/wysiwyg-editor#1567]
Hi,

On your web demo site in any froala editor, instead of writing text with the virtual keyboard I use the voice recorder.

In this case, after text appear in froala editor and I click on the Ipad OK button, the undo button is still inactive and the contentChanged event is not fired ! (It's important for me because I displays a button "save" only when the text is modified)

Best regards
Frédérik

IPAD/CHROME & SAFARI

**Comment by stefanneculai** [comment]
@maverick42 it should be fixed on the Github master.
