### ISSUE TITLE
path upload image get error

### ISSUE THREAD

**Issue by Dark-Kun** [froala/wysiwyg-editor#1568]
Hi !

After install Froala Editior, i want to change the upload directory. I get help in [this page](https://www.froala.com/wysiwyg-editor/docs/concepts/image/upload) and i paste this code in my file : 

```
<script>

	$(function() {
		$('#article-edit')
			.froalaEditor({
			// Set the image upload parameter.
			imageUploadParam: 'file',

			// Set the image upload URL.
			imageUploadURL: '/'
		});
	});
</script>
```

but, i get this error : "Something went wrong. Please try again." I have been try other path but no one work.

Thanks.

**Comment by stefanneculai** [comment]
You should implement image upload on server side and return a JSON with the path to the uploaded image.
