### ISSUE TITLE
thousands of errors for a user with IE9

### ISSUE THREAD

**Issue by dunkoh** [froala/wysiwyg-editor#1569]
#### Actual behavior.

thousands of js errors from one user:

> (unknown): 无法获取属性“pageX”的值: 对象为 null 或未定义
> File /js/froala_editor_2/js/plugins/line_breaker.min.js line 7 in [anonymous]

The user appears to be chinese, so the error is always in chinese. He submits text on the page in english though. Error translates to "Can not get the value of the property "pageX": Object is null or undefined"
Relates to this bit of code I believe?
```
function f(c) {
            p = null;
            var f, g, h, i = null, j = b.doc.elementFromPoint(c.pageX - b.win.pageXOffset, c.pageY - b.win.pageYOffset);
            if (j && ("HTML" == j.tagName || "BODY" == j.tagName || b.node.isElement(j)))for (f = 1; f <= b.opts.lineBreakerOffset; f++) {
                if (g = b.doc.elementFromPoint(c.pageX - b.win.pageXOffset, c.pageY - b.win.pageYOffset - f), g && !b.node.isElement(g) && g != b.$wp.get(0) && a(g).parents(b.$wp).length) {
                    i = e(g);
                    break
                }
                if (h = b.doc.elementFromPoint(c.pageX - b.win.pageXOffset, c.pageY - b.win.pageYOffset + f), h && !b.node.isElement(h) && h != b.$wp.get(0) && a(h).parents(b.$wp).length) {
                    i = e(h);
                    break
                }
            } else i = e(j);
            i ? d(i, c.pageY) : b.core.sameInstance(n) && n.removeClass("fr-visible").removeData("instance")
        }
```

#### Steps to reproduce the problem.

latest 2.3.4 version of froala

This is the init for the textareas on that page:
```
$('textarea.editor').froalaEditor({
        language: 'en',
		heightMin: 200,
		heightMax: 500,
		toolbarButtons: ['undo', 'redo', '|', 'bold', 'italic', 'underline', 'formatOL', 'formatUL', 'insertLink']
	});
```

When I try to reproduce it in a VM with IE9, I get these errors (one being the same as above) just by loading the page.  Not even interacting with the editor.
```
SCRIPT5007: Unable to get value of the property 'pageX': object is null or undefined   line_breaker.min.js, line 7 character 2019
SCRIPT5007: Unable to get value of the property 'pageX': object is null or undefined   student.php?id=xxxxxx&studentassignment=xxxxxxx, line 1 character 1
```

#### OS.

Windows 7

#### Browser.

IE 9

**Comment by dunkoh** [comment]
Using a VM with IE9/Windows7 I get thousands of errors on your website too: https://www.froala.com/wysiwyg-editor

```
SCRIPT5007: Unable to get value of the property 'pageX': object is null or undefined 
wysiwyg-editor, line 1 character 1
```

Browser Mode: IE9
Document Mode: IE9 standards

(still happens with IE 9 compatibility view also)

**Comment by dunkoh** [comment]
an thoughts or fixes in upcoming point releases for this?

**Comment by stefanneculai** [comment]
Editor V2 support IE10+.
