### ISSUE TITLE
Inconsistent Cursor and Placeholder Position

### ISSUE THREAD

**Issue by cristianst** [froala/wysiwyg-editor#1571]
##### Expected behavior.

I expect that the editor aligns the placeholder as normal text and respect the position of the cursor.
##### Actual behavior.

**Case 1**
1. When the text is centered, the cursor appears  but the placeholder is still aligned to the left.

**This issue is happening also in your example page**
https://www.froala.com/wysiwyg-editor/inline

![image](https://cloud.githubusercontent.com/assets/11995461/19510666/7e4a8c5c-95e4-11e6-9b94-624aff9102dd.png)

**Case 2**
Since there is no `textDefaultAlign` option in the docs. The only way to center the text within the editor is : 
1. Overwriting the fr-view class 
2. Setting a container. 

Both cases with `text-align:center`.

But when you enter some text and the use the alignment button, the cursor and placeholder position is weird again. 
##### Steps to reproduce the problem.

**Case 1**
1. Go to https://www.froala.com/wysiwyg-editor/inline
2. Delete all the text
3. See the cursor and placeholder position (Confusing isnt it?)

**Case 2**
1. Go to https://jsfiddle.net/124c4cqp/12/ (By default the text (placeholder) is centered)
2. Write some text
3. Select text and align left or right 
4. Delete Text
5. See the cursor and placeholder position 
##### OS.

OSX El Capitan v 10.11.2
##### Browser.

Google Chrome Version 53.0.2785.143 (64-bit)

**Comment by stefanneculai** [comment]
It is already on our TODO list as an `enhancement` and it will be updated shortly.
