### ISSUE TITLE
Wrong toolbar position with multiline text

### ISSUE THREAD

**Issue by cristianst** [froala/wysiwyg-editor#1572]
##### Expected behavior.

The toolbar position should appear above the selected text (as usual)
##### Actual behavior.

The toolbar position is wrong. In this case it is centered.
##### Steps to reproduce the problem.
1. https://jsfiddle.net/124c4cqp/13/
2. Write some multi line text (breaklines)
3. Select Text
4. See toolbar position 

![image](https://cloud.githubusercontent.com/assets/11995461/19512148/c327aa5c-95ea-11e6-8ccf-a35cf4e3df9e.png)
##### OS.

OSX El Capitan v 10.11.2
##### Browser.

Google Chrome Version 53.0.2785.143 (64-bit)

**Comment by cristianst** [comment]
You can also reproduce this behaviour in your page https://www.froala.com/wysiwyg-editor/inline

But first remove the container div with the class `text-center` that forces the centered alignment. 

![image](https://cloud.githubusercontent.com/assets/11995461/19512242/3af8f054-95eb-11e6-8ef5-76fddbd48393.png)

**Comment by cristianst** [comment]
Why is this an enhancement? 
According to the definition of bug : 

> A software bug is an error, flaw, failure or fault in a computer program or system that causes it to produce an incorrect or unexpected result, or to behave in unintended ways.

Source: https://en.wikipedia.org/wiki/Software_bug

This seems to bee a bug IMO since the toolbar appears in a completely wrong position, as a user I expect the toolbar to appear above or below the selected text (its a inline toolbar after all).

**Comment by stefanneculai** [comment]
We consider it an enhancement because the browser returns the selection as being from side to side when using clientBoundingRect for the selection object: https://developer.mozilla.org/en/docs/Web/API/Element/getBoundingClientRect.

**Comment by stefanneculai** [comment]
Unfortunately, this will remain as a `wontfix`. We are using `getBoundingClientRect` method (https://developer.mozilla.org/en/docs/Web/API/Element/getBoundingClientRect) which it appears is returning a wrong attribute. We'll investigate further what is causing that in browsers and report this to Chrome/Mozilla.
