### ISSUE TITLE
Add "destroyed" event

### ISSUE THREAD

**Issue by Panman8201** [froala/wysiwyg-editor#1573]
While the existing "destroy" event fires before the editor is fully tore down, it would be nice (for integration with other frameworks) to have an event fired _after_ the editor is destroyed. This handler obviously wouldn't have access to the editor instance at that point, but is at least a life cycle hook to tie into.

**Comment by stefanneculai** [comment]
Unfortunately, that is not something will add because all events are unbinded on destroy.

**Comment by Panman8201** [comment]
Another reason why [that approach is flawed](https://github.com/froala/wysiwyg-editor/issues/1444#issuecomment-255219979). 😒

**Comment by stefanneculai** [comment]
The editor should unbind on destroy all the events that are attached to it. That means everything from `froalaEditor` namespace. On destroy things are done synchronously, therefore the instance is destroyed as soon as the destroy method has finished to run.

**Comment by Panman8201** [comment]
Sure, but if you didn't removed event listeners that dev's added on their own, the last thing that the editor could do is trigger `froalaEditor.destroyed`.

> The editor should unbind on destroy all the events that are attached to it.

This is the main disagreement, which I tried to explain in the other issue. In short (for event listeners), if the developer added it then the developer should remove it, but if the editor added it then the editor should remove it. This is a philosophical difference that I don't think we'll agree on. ¯\\_ (ツ) _/¯

**Comment by stefanneculai** [comment]
That is right, there is a difference in how we vs you believe this should work. 😄 However, we might have a workaround for you (there is always one).

```js
$.FroalaEditor.prototype.destroy = function () {
    this.shared.count--;

    this.events.$off();

    // HTML.
    var html = this.html.get();

    this.events.trigger('destroy', [], true);
    this.events.trigger('shared.destroy', undefined, true);

    // Remove shared.
    if (this.shared.count === 0) {
      for (var k in this.shared) {
        if (this.shared.hasOwnProperty(k)) {
          this.shared[k] == null;
          $.FE.SHARED[this.sid][k] = null;
        }
      }

      $.FE.SHARED[this.sid] = {};
    }

    this.$oel.parents('form').off('.' + this.id);
    this.$oel.off('click.popup');
    this.$oel.removeData('froala.editor');

    // this.$oel.off('froalaEditor');

    // Destroy editor basic elements.
    this.core.destroy(html);

    $.FE.INSTANCES.splice($.FE.INSTANCES.indexOf(this), 1);
  }
```
