### ISSUE TITLE
Disable quickinsert button

### ISSUE THREAD

**Issue by henning-krause** [froala/wysiwyg-editor#1577]
I have two editor instances on a single page. One should have the "quick insert" button, the other one should not.

I've tried setting "quickInsertButtons" in the config to either "null" or an empty array, but neither removes the quick insert button from the editor.

Is this possible?

**Comment by stefanneculai** [comment]
The option `pluginsEnabled` can be used for that.

**Comment by starikovs** [comment]
Hey, how can I use pluginsEnabled to disable this quick insert feature?

**Comment by stefanneculai** [comment]
@starikovs pass the other plugins except the quick insert one.

**Comment by AhHa45** [comment]
can you please add a feature to disable the quick insert button?

**Comment by dianaprajescu** [comment]
There are 2 ways to disable the Quick Insert Button:
1. Don't include the Quick Insert plugin (you can include only the plugins that you are using).
2. If you include all the plugins and want to use just some of them, then use the `pluginsEnabled` option.

**Comment by AhHa45** [comment]
@dianaprajescu I know this options,
however, if you want to use all options but the quick insert button you have to this:

`this.froalaOptions = {
            pluginsEnabled: ["align", "charCounter", "codeBeautifier", "codeView", "colors", "draggable",
                "embedly", "emoticons", "entities", "file", "fontFamily", "fontSize", "fullscreen", "image",
                "imageManager", "inlineStyle", "lineBreaker", "link", "lists", "paragraphFormat",
                "paragraphStyle", "quote", "save", "table", "url", "wordPaste"],
`

instead of something like:

`this.froalaOptions = {
            pluginsDisable: ["quickInsert"]
`

**Comment by dianaprajescu** [comment]
@AhHa45, that is true. I'm adding this to our TODO list.

**Comment by inxilpro** [comment]
I was just looking for this. Looking forward to when it gets added.

**Comment by JMavs** [comment]
This would be so nice! 👏

**Comment by pixelshaded** [comment]
It seems to already be an option in Froala. https://froala.com/wysiwyg-editor/docs/options/?#quickInsertEnabled
