### ISSUE TITLE
Content.Changed not fired after using html.set

### ISSUE THREAD

**Issue by skimonkey** [froala/wysiwyg-editor#1578]
##### Expected behavior.
open an editor with no data in chrome
type the letter "t"
open developer tools and run 
$('#froala-editor').froalaEditor('html.set','')
this clears the editor
type the letter "t"
the contentChanged event is fired

##### Actual behavior.
open an editor with no data in chrome
type the letter "t"
open developer tools and run 
$('#froala-editor').froalaEditor('html.set','')
this clears the editor
type the letter "t"
the contentChanged event is **NOT** fired

##### Steps to reproduce the problem.
As above
Calling $('#froala-editor').froalaEditor('html.set','') does not fire the contentChanged. 
So it looks like even though the editor has changed the contents visually, internally the editor still thinks it has the previous value

The event is only fired if I set to a different value - not "t"
Having set the content to blank via code I would expect the Content.Changed event to get fired when the content changes again

##### OS.
windows 10 and windows 7

##### Browser.
Chrome Version 54.0.2840.71 m

**Comment by stefanneculai** [comment]
`html.set` is not designed to trigger the contentChanged event. If you want to have contentChanged triggered you should call `undo.saveStep` after `html.set`.
