### ISSUE TITLE
Explorer 11/Edge Freeze up when entering Source/Code view

### ISSUE THREAD

**Issue by somazx** [froala/wysiwyg-editor#1579]
##### Expected behavior.

Clicking the Code view button should successfully enter Code view.
##### Actual behavior.

Explorer 11/Edge Freeze up when entering Source/Code view
##### Steps to reproduce the problem.

Initiate editor without specifying height, heightMax, or heightMin
enter multiple lines of test data - at least 10 -20 lines of junk data and carriage returns - enough to trigger the editor to grow in height significantly. Press source code view button. Browser locks.
##### OS.

Windows
##### Browser.

Edge/Explorer 11

By experimenting I determined that adding a fixed height value when initiating the editor prevents the freezing.

```
//= require froala_editor.min.js
//= require plugins/code_beautifier.min.js
//= require plugins/code_view.min.js

  var froalaButtons = [
    'html'
  ]

  $('#editor').froalaEditor(
    {
      // height: 600, // fixes IE/Edge browser locking up in source code view
      toolbarButtons: froalaButtons,
      toolbarButtonsMD: froalaButtons,
      toolbarButtonsSM: froalaButtons,
      toolbarButtonsXS: froalaButtons
    }
  );
```

**Comment by somazx** [comment]
http://recordit.co/B7CkoUbI3U

**Comment by stefanneculai** [comment]
@somazx could you please confirm you're using the V2.3.5?

**Comment by somazx** [comment]
Confirmed v2.3.5.

**Comment by somazx** [comment]
Also, I can't reproduce it on your site.

**Comment by stefanneculai** [comment]
@somazx if you could create a jsFiddle to reproduce it, then we would be happy to look into this.

**Comment by caiotarifa** [comment]
I'm having the same issue with **Chrome 56** and Froala 2.4.2.1.

http://recordit.co/31gfwTxwcC

However, I can't reproduce this outside of my application. Maybe it's a problem with Rails, since apparently @sazazx is also using it.

-> Setting a fixed height solve the problem. But that's not cool. 😢
