### ISSUE TITLE
'Add Video' via embed code does not work

### ISSUE THREAD

**Issue by moinism** [froala/wysiwyg-editor#1580]
##### Expected behavior.

After adding embed code for video from a site like Vimeo, it should add the video to editor.
##### Actual behavior.

Clicking 'Insert' on the video popup does nothing. No errors in the console either. 

![bug](https://cloud.githubusercontent.com/assets/2242528/19739712/7c36e626-9bd5-11e6-9cc0-4f1f0ea96227.png)
##### Steps to reproduce the problem.

Go to [Froala site](https://www.froala.com/wysiwyg-editor), Click 'Add Video' button, switch to embed code view on the appeared popup, add a video code like:

``` html
<iframe src="https://player.vimeo.com/video/187823706?color=5c5a5a&title=0&byline=0&portrait=0" width="640" height="360" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
<p><a href="https://vimeo.com/187823706">Bug Man</a> from <a href="https://vimeo.com/iqbalahmed">Iqbal Ahmed</a> on <a href="https://vimeo.com">Vimeo</a>.</p>
```

Click 'Insert'.
##### OS.

Windows 10
##### Browser.

Chrome 53, Firefox 48

**Comment by stefanneculai** [comment]
The editor is testing the embedded code using a regular expression: `/^\W*((<iframe.*><\/iframe>)|(<embed.*>))\W*$/i`. If you want to allow other things such as P tags, then you should change it by adding the following line before initializing the editor.

```js
$.FroalaEditor.VIDEO_EMBED_REGEX = your_reg_ex_here;
```

**Comment by olliegardener** [comment]
Hi. I have customers wanting to embed presentations into the text editor and I have made it work with the video embed options for google slides. If I try with slideshare however, I get the same issue as is described above. 
I realise the video embed wasn't really intended for other formats or services, but is there any way to circumvent this issue or other functionality/plugins which would allow slideshare embeds?
Thanks!
