### ISSUE TITLE
Events Not Firing - froalaEditor.image.X

### ISSUE THREAD

**Issue by arist0tl3** [froala/wysiwyg-editor#1581]
I'm currently experiencing this behavior for multiple `froalaEditor.image` events:

##### Expected behavior.
`froalaEditor.image.X` event fires

##### Actual behavior.
`froalaEditor.image.X` event does not fire

##### Steps to reproduce the problem.
Visit the [jsFiddle](https://jsfiddle.net/177Lsvbm/2/), and paste in an image. The `paste.before` event fires, but none of the `image.X` events fire.

##### OS.
Ubuntu 15.04

##### Browser.
Chrome Version 54.0.2840.71 (64-bit)

**Comment by stefanneculai** [comment]
That's because you're not including the Image plugin.
