### ISSUE TITLE
Event callbacks do not get the same args as event listeners

### ISSUE THREAD

**Issue by Panman8201** [froala/wysiwyg-editor#1585]
##### Expected behavior.
I would expect event handlers to receive the same arguments (as noted in the [event docs](https://www.froala.com/wysiwyg-editor/docs/events)) weather they were attached as callbacks or listeners. Ex:

```js
// Callback
$('#e').froalaEditor('events.on', 'contentChanged', function(){ console.log(arguments); });
// Listener
$('#e').on('froalaEditor.contentChanged', function(){ console.log(arguments); });
```

##### Actual behavior.
I noticed a couple differences;

1. An event is only passed to the callback if it is a native event (eg; `keydown`, `focus`) but omitted otherwise (eg; `contentChanged`, `paste.after`)
2. The `editor` instance (always documented as the second argument) is _never_ passed into the callback but _is_ for the listener

##### Steps to reproduce the problem.
Add the example code above to any demo.

##### OS.
Mac/Win

##### Browser.
All; Firefox, Chrome, etc.

**Comment by stefanneculai** [comment]
Using events.on, you get only the parameters starting with the 3rd one. That's because `events.on` is designed more for internal usage where you already have an instance of the editor and the first param is `e` which you get using the other way is jQuery specific.

**Comment by Panman8201** [comment]
Oh, I see. The `keydownEvent` is the third arg. IMO this should be noted on the [`events.on` method doc](https://www.froala.com/wysiwyg-editor/docs/methods#events.on), that the first two args noted in the [event docs](https://www.froala.com/wysiwyg-editor/docs/events) (`event` and `editor`) are not passed to the callback using this method.
