### ISSUE TITLE
Option linkDefaultBlank is missing

### ISSUE THREAD

**Issue by thomaslhostis** [froala/wysiwyg-editor#1588]
It would be nice to have an option that automatically checks the "Open in a new tab" checkbox for links.

**Comment by stefanneculai** [comment]
No, it is not available because that can be implemented easily, by using the `popups.onShow('link.insert', function () { ... }` event.

**Comment by thomaslhostis** [comment]
From the [docs](https://www.froala.com/wysiwyg-editor/docs/events#popups), I can see that there is a "popups.hide" event, but no "popups.show" (or "popups.onShow"). Specifically, if I do this:

    $('.selector').on('froalaEditor.popups.show.link.insert', function (e, editor) {
        console.log('Link popup opened');
    });

Nothing happens when I click on the link button. Whereas the "popups.hide" event gets triggered fine.

I am currently using version 2.4.0-rc.1.
