### ISSUE TITLE
Cannot add video from Twitter via embed code

### ISSUE THREAD

**Issue by kmacampbell** [froala/wysiwyg-editor#1590]
##### Expected behavior.
Embedding a video from Twitter should embed the video as expected or (at least) provide an alert that this type of embed is not supported.

##### Actual behavior.
Embedding a video from Twitter does not work. Nothing happens when Insert is pressed within the video upload plugin.

##### Steps to reproduce the problem.
1) Grab an embed code for a Twitter video (e.g., from here: https://twitter.com/twitter/status/560070183650213889) 
2) Paste it into the embed option of the video upload plugin
3) Click Insert

##### OS.
Windows 10

##### Browser.
Chrome 54.0.2840.71 m (64-bit)

**Comment by stefanneculai** [comment]
The Twitter embed contains `<script>` tag which by default the editor doesn't allow.

**Comment by kmacampbell** [comment]
After further investigation, it appears that presence of <script> tags aren't the issue. The video uploader does not appear to accept an embed code unless it contains an <iframe> tag. Presumably this change was made here:
https://github.com/froala/wysiwyg-editor/issues/1092

Any comments on this? There's a usability problem with the current behaviour as there is no cue to the user re: what's wrong when they attempt to insert a valid embed code which uses a different mechanism than an iframe. Thanks!
