### ISSUE TITLE
Multiple editors w/ shared toolbarContainer - Toolbar fails to reinitialize

### ISSUE THREAD

**Issue by iseem** [froala/wysiwyg-editor#1591]
##### Expected behavior.
When two editors share a toolbarContainer, it should be possible to destroy and reinitialize one of the editor instances.

##### Actual behavior.
Destroying and reinitializing a single editor instance causes the toolbar to be permanently removed from the page.

##### Steps to reproduce the problem.
I made a fiddle. Click the "Destroy" button:
https://jsfiddle.net/xkfp2ke2/3/

##### OS.
MacOS 10.9.5

##### Browser.
Chrome 54.0.2840.71
FireFox 49.0.2

**Comment by CodeXtinction** [comment]
still happening on the version 2.8.5
