### ISSUE TITLE
It is impossible to continue typing after inserting horizontal line 

### ISSUE THREAD

**Issue by adi-darachi** [froala/wysiwyg-editor#1593]
##### Expected behavior.
It should be possible to continue typing after inserting of horizontal line

##### Actual behavior.
It is impossible to continue typing after inserting of horizontal line

##### Steps to reproduce the problem.
1. Type any text, **And make sure your cursor stays on the line you typed**
2. Insert horizontal line via click on appropriate icon in the toolbar
3. Try to continue typing on the first line ( above the line ) ( Move the cursor to the ling if nessecery)

##### OS.
Windows 10

##### Browser.
Chrome 54.0.2840.71 m (64-bit)

**Comment by stefanneculai** [comment]
Are you able to reproduce this on our website?

**Comment by stefanneculai** [comment]
Closing this due to lack of response.
