### ISSUE TITLE
It is possible to insert links with empty URL and empty TEXT

### ISSUE THREAD

**Issue by adi-darachi** [froala/wysiwyg-editor#1594]
##### Expected behavior.
Should be impossible to insert links with empty URL or empty TEXT

##### Actual behavior.
It is possible to insert links with empty URL 
It is possible to insert links with empty TEXT 

** Solution might be to let the user add validation to the controls.

##### Steps to reproduce the problem.
1. Click on the insert  link button
2. Click "INSERT"

##### OS.
Windows 10

##### Browser.
Chrome 54.0.2840.71 m (64-bit)

**Comment by stefanneculai** [comment]
I initially marked this as a bug, however it is not really the case. There might be users who just want to put there a link only with attributes. However, you could override easily the default behavior this way:

```js
var original_link = $.FE.FroalaEditor.link; 
$.FroalaEditor.PLUGINS.link = function (editor) { 
  var link = original_link(editor); 

  var insert = link.insert;  

  // This is the original sanitizer.
  link.insert = function (href, text, attrs) {
      // Make any changes you want.
      if (!href.length && !text.length) return false;

      // Call the original insert.
      insert(href, text, attrs);
  }; 

  return link;
} 
```

**Comment by adi-darachi** [comment]
Your answer kind of solves my problem (I don't mind doing the validation myself).
FYI
I really think that the following is still an issue:

**"It is possible to insert links with empty TEXT"**

**Comment by davidtorroija** [comment]
yes, the solution provided to override not working as expected

**Comment by stefanneculai** [comment]
@davidtorroija recently we added a new event `link.beforeInsert` which could be used: https://www.froala.com/wysiwyg-editor/docs/events#link.beforeInsert.

**Comment by davidtorroija** [comment]
Ok thanks, but I resolved adding events to the inputs in the link popup so if there is no text entered the insert button dissapears.
