### ISSUE TITLE
Black listed style properties causes errors for text nodes

### ISSUE THREAD

**Issue by ConorHiggins** [froala/wysiwyg-editor#1595]
##### Expected behavior.
Blacklisting style properties will ignore text nodes

##### Actual behavior.
Console errors are thrown.

##### Steps to reproduce the problem.
Recently had to black list style properties for pasted content in particular - to avoid fixed positioned elements, etc. Encountered an issue immediately where text nodes are not ignored and accessing the style property of any text node results in a JS error (obviously). 

A quick fix for this is to simply check that the node has a style attribute.

```
if (editor.opts.blackListedStyleProperties) {
        for (var i = editor.opts.blackListedStyleProperties.length - 1; i >= 0; i--) {
            if (node.style != undefined){
                node.style[editor.opts.blackListedStyleProperties[i]] = ""
            }
        }
      }
```

##### OS.
OS X

##### Browser.
Chrome 54.0.2840.71

**Comment by stefanneculai** [comment]
Thanks for the suggestion. I am closing this because it doesn't appear to be an editor issue, but rather a new feature.
