### ISSUE TITLE
froala options dynamicly change

### ISSUE THREAD

**Issue by Avocado20** [froala/wysiwyg-editor#1596]
I would like to make language in froala editor dynamicly changing based on Angular 2 translate.currentLang. I found a following example

`editorOptions = {
    language: 'de',
    events: {
      "froalaEditor.click" : function(e, event) {
        event.opts.language = 'fr';
        /*some code changing value of language
       this.editorOptions.language = this.translate.currentLang doesnt work */
      }
    }
  };`

 There is no way to make editorOptions observable, and i don't know how to catch change language event for editorOptions

**Comment by stefanneculai** [comment]
The language option cannot be changed after the editor was initialized. To change the language you should destroy the instance and initialize it again.
