### ISSUE TITLE
Select-all and Paste removes styles

### ISSUE THREAD

**Issue by delian7** [froala/wysiwyg-editor#1597]
##### Expected behavior.
If you have a styled paragraph: select-all and paste in something removes the styles.   

##### Actual behavior.
Should keep the styles that were previously defined. 

##### Steps to reproduce the problem.
Please refer to this [codepen](http://codepen.io/delian7/pen/QGbEBv). It is using v2.3.5. 

1. Copy something into your clipboard
2. select-all using keyboard shortcut (cmd-a/ctrl-a)
3. paste using keyboard shortcut. 
4. Styling is removed. 

![bug](https://cloud.githubusercontent.com/assets/4530694/20076117/0f3180ca-a4ec-11e6-8dd9-62bec896bc7a.gif)

##### OS.
macOS 10.12.1

##### Browser.
Chrome v54

**Comment by GMiLL5** [comment]
@stefanneculai I believe I found the source of this in the `_processPaste( )` method:
![screen shot 2016-12-07 at 9 07 09 am](https://cloud.githubusercontent.com/assets/1800407/20968821/9d3ddbac-bc5c-11e6-8c55-c06f546cfb9d.png)

The `['OL', 'UL'].indexOf(list[0].tagName)` returns -1 when a match isn't found which technically evaluates to a truthy value

**Comment by GMiLL5** [comment]
Also a note that this worked in v2.3.4
