### ISSUE TITLE
Table cell option not shown in mobile device

### ISSUE THREAD

**Issue by merbin2012** [froala/wysiwyg-editor#1599]
When select the table cell, then tools not showing in mobile device. But it is perfectly working in desktop chrome browser. In desktop browser "fr-selected-cell" class is applied when select the table cell, but it is not applied in mobile device. Please help me.

![bug](https://cloud.githubusercontent.com/assets/3687184/20153529/2197c43c-a6e9-11e6-9bff-4933aa7201c3.jpg)

**Comment by stefanneculai** [comment]
The table tool is designed not to appear on mobile devices mainly because of the fact that multiple cells cannot be selected and that the space there is very limited.

**Comment by merbin2012** [comment]
If I want to display, what can I do?
