### ISSUE TITLE
<br> elements being misplaced

### ISSUE THREAD

**Issue by robsix** [froala/wysiwyg-editor#1600]
##### Expected behavior.
with content in the editor as
`one<br>two<br>three<br>four`
selecting the top line and choosing to format as a heading should format the `one` to be a heading and leave the other elements as they were

##### Actual behavior.
the `<br>` element is removed from between the two and three

##### Steps to reproduce the problem.
see above

##### OS.
n/a

##### Browser.
n/a

##### Fix
On line 3768 put the `<br>` element before the $(this).html() as in:
`$(this).replaceWith('<br>' + $(this).html())`

**Comment by stefanneculai** [comment]
This should be fixed on master.
