### ISSUE TITLE
HTML code to WYSIWYG HTML Editor 

### ISSUE THREAD

**Issue by merbin2012** [froala/wysiwyg-editor#1601]
Can I give HTML code to WYSIWYG HTML Editor ? Because I have a html editor application there user can create html code through wysiwyg editor and convert the created html code to wysiwyg 
 If yes how?

**Comment by stefanneculai** [comment]
Sure, you can initialize the editor on any HTML. If you want to have HTML displayed in the editor, then you should pass the HTML sanitized. E.g. `<b>bold</b>` should be `&lt;b&gt;bold&lt;/b&gt;`.

**Comment by merbin2012** [comment]
Can you please give me the method name? I mean how can I pass the value(&lt;b&gt;bold&lt;/b&gt;) to WYSIWYG  editor?
