### ISSUE TITLE
HTML sanitizer produces unpredictable output

### ISSUE THREAD

**Issue by bocasfx** [froala/wysiwyg-editor#1606]
Switching back and forth between wysiwyg and code views triggers the HTML sanitizer producing different output each time.

##### Expected behavior.
HTML code should be sanitized once. Sanitizing already sanitized code should produce the exact same code.

##### Actual behavior.
Sanitizing sanitized code produces a different output every time.

##### Steps to reproduce the problem.
1. Add a few paragraphs.
2. Wrap those paragraphs in span tags.
3. Switch back and forth between wysiwyg and code views.

See [GIF](http://pasteboard.co/q1dQ1Qxzy.gif) 

##### OS.
OSX

##### Browser.
Chrome 54.0.2840.71 (64-bit)

**Comment by stefanneculai** [comment]
The editor is allowing inside the main editable area direct tags only the ones from `$.FroalaEditor.BLOCK_TAGS` variable. By default `SPAN` is not there and when you have the `enter` option set to `$.FroalaEditor.ENTER_P` it would wrap the span with a `P` tag and that is why you get that behavior.
