### ISSUE TITLE
imageResizeWithPercent set to true  but resize in pixel

### ISSUE THREAD

**Issue by maverick42** [froala/wysiwyg-editor#1607]
Hi

When you set **imageResizeWithPercent** to true. you have this choice in percent

![image](https://cloud.githubusercontent.com/assets/2311642/20244868/56e8b32a-a992-11e6-9c21-1d6fc13515be.png)

but in fact the image is resized in pixel ...

Chromium Version 46.0.2489.0 (64-bit)

Regards

Frédérik

**Comment by stefanneculai** [comment]
@maverick42 we cannot reproduce this. Could you please make a jsFiddle? Thank you.

**Comment by maverick42** [comment]
Hi stefan, 

I created my jsFiddle and tested. I just .... understood :) 
I thought that by setting the imageResizeWithPercent option to true the resize would always be in percentage... In fact, I must always add "%" if I want to adjust the size in percentage. 
For me it was not very clear and I would have preferred an option like : 
Size: 50        (o) pixel  ( ) Percent

To validate ...

Bests
Frédérik

Thanks
