### ISSUE TITLE
Jquery UI Sortable is not working with froala editor

### ISSUE THREAD

**Issue by ajaykr089** [froala/wysiwyg-editor#1608]
Hey All,

##### Expected behavior.
(Describe expected behaviour here)
I am using froala 2.3.5 inline editor for editing my page, i applied editor in the two different blocks and i wanted to sort(Jquery UI Sortable) both editors
##### Actual behavior.
(Describe actual behaviour here)
but it seems editor is not working for the blocks as i applied sortable method on it.
##### Steps to reproduce the problem.
(Describe the steps to reproduce the problem here)

##### OS.
(OS name and version here)

##### Browser.
(Browser name an version here)

It would be great, if you guys can solve my issue.

Thanks,

**Comment by stefanneculai** [comment]
You cannot use the jQuery UI Sortable on the element on which you're using the editor because both rely on the mouse clicks and they are not compatible. As an alternative, you could use a handler in jQuery UI and use that handler to sort the elements.
