### ISSUE TITLE
Navigating within a code tag with arrow keys causes a random new line to appear and disappear

### ISSUE THREAD

**Issue by dkfann** [froala/wysiwyg-editor#1609]
##### Expected behavior.
Moving the arrow keys (especially only left and right on the first character) should not create any line breaks.

##### Actual behavior.
Moving with the arrow keys causes a random new line to appear or disappear.

##### Steps to reproduce the problem.
1. Create a button assigned to a plugin that when clicked will insert something like the following when clicked:

```js
const codeBlock = `<code>Insert Code${$.FE.MARKERS}<br></code>`;
editor.html.insert(codeBlock);
editor.selection.restore();
```

2. Within the code block, navigate to the first character in the code block.
3. Use the arrow keys to move left and right. As you do this, the block will add and remove a new line randomly.

Example HTML result:

```html
<code>
    "Insert Code"
    ""
    ""
    ""
    ""
    ""
    ""
    <br>
<code>
```

##### OS.
Windows 10

##### Browser.
Version 54.0.2840.99 m

**Comment by stefanneculai** [comment]
It is not happening in V2.3.5. Could you please make sure you're using the latest version? If so, then please make a jsFiddle.

**Comment by stefanneculai** [comment]
Closing this due to lack of response.
