### ISSUE TITLE
IE11 - link popup / image popup sometimes hides itself

### ISSUE THREAD

**Issue by manttih** [froala/wysiwyg-editor#1611]
##### Expected behavior.
When clicking INSERT LINK in IE, popup opens. 

##### Actual behavior.
Sometimes popups hide automatically. This happens at least in inline mode - it's really annoying for basic users as this sometimes happens and sometimes not.

##### Steps to reproduce the problem.
Inline editor, enter paragraphs and select text, INSERT LINK. Video explains better.

##### OS.
Windows 7

##### Browser.
IE 11.0.9600.18524

VIDEO: http://synergiafoxy.fi/julkinensiirto/IE_bug.mp4

**Comment by stefanneculai** [comment]
We were able to reproduce it only sporadically and when developer tools was opened and in Compatibility View with IE 10. If you could find a way to reproduce this all the time, we would be happy to look further into it.

**Comment by JordanAtIgloo** [comment]
@stefanneculai we had the same issue here. One or two specific machines seemed to have this issue regularly (maybe 50% of the time), but we were never able to figure out why. The one consistent factor was that these were older, slower Windows machines, but that's not too much to go on.

**Comment by stefanneculai** [comment]
@JordanAtIgloo thanks for the additional details. We'll try to figure it out.

**Comment by stefanneculai** [comment]
Unfortunately we cannot find a way to reproduce this. It might be related to #1694, but we couldn't reproduce that either.

**Comment by maniwadhwa26** [comment]
@stefanneculai 

I was also facing the same issue on IE 11 version - 11.0.9600.19204.
Froala Version - 2.9.1. I tried 2.9.3 also but behavior was same.

For me none of the pop up - Insert Link, Insert Image, Edit link was working. When ever I click on insert image or insert link button, pop up shows up and hides itself within seconds. It's working fine on other browser. I realized may be my IE version on server is ram consuming and something is happening at the back.

I opened froala_editor.pkgd.min.js and saw showInsertPopup function is the one which gets executed and calculate all the offset values and positioning of popup. I put the entire the function into the setTimeout method and provided 0 secs time out. After this pop up started working even on IE. May be IE is not able to handle all the statements and setTimeout helped in executing all this separately after some interval. Following is what I added for all Pop up show function - 
**Before : **
 showInsertPopup: function() {
                var e = f.$tb.find('.fr-command[data-cmd="insertLink"]')
                  , t = f.popups.get("link.insert");
                if (t || (t = s()),
                !t.hasClass("fr-active"))
                    if (f.popups.refresh("link.insert"),
                    f.popups.setContainer("link.insert", f.$tb || f.$sc),
                    e.is(":visible")) {
                        var n = e.offset().left + e.outerWidth() / 2
                          , r = e.offset().top + (f.opts.toolbarBottom ? 10 : e.outerHeight() - 10);
                        f.popups.show("link.insert", n, r, e.outerHeight())
                    } else
                        f.position.forSelection(t),
                        f.popups.show("link.insert")
            }

**After :**
showInsertPopup: function() {
	setTimeout(function(){
					
                var e = f.$tb.find('.fr-command[data-cmd="insertLink"]')
                  , t = f.popups.get("link.insert");
                if (t || (t = s()),
                !t.hasClass("fr-active"))
                    if (f.popups.refresh("link.insert"),
                    f.popups.setContainer("link.insert", f.$tb || f.$sc),
                    e.is(":visible")) {
                        var n = e.offset().left + e.outerWidth() / 2
                          , r = e.offset().top + (f.opts.toolbarBottom ? 10 : e.outerHeight() - 10);
                        f.popups.show("link.insert", n, r, e.outerHeight())
                    } else
                        f.position.forSelection(t),
                        f.popups.show("link.insert")
	     },0);
 }

Would like Team to take this into consideration and can provide setTimeout in all the show pop up method in their next release of Froala.
