### ISSUE TITLE
codeView does not show inserted text from editor.html.insert 

### ISSUE THREAD

**Issue by sinaigross** [froala/wysiwyg-editor#1612]
I insert some text with editor.html.insert.
Would expect to see the code text area getting updated.
That happens **only when the insert is done while the code view is toggled**.
If the insert is done while the text view is active, the insert is updated both on text view and on code view.

Actual behavior is the html.get sees the update but codeView doesn't.
Found on chrome, windows 10.

Triggering 'contentChanged' event doesn't help.
doing editor.html.set(editor.html.get()) after the insert does work, however that pushes back the cursor to beginning of the body (without option to save/restore selection because of the change in html) so doesn't help me so much.

Any advice? Am I doing something wrong here?

**Comment by stefanneculai** [comment]
The code view is designed to be updated only when you toggle the code view button. If you are doing changes in the text view while you're in code view, those changes won't reflect there.

**Comment by sinaigross** [comment]
I used wrong terminology, I apologize.
"Would expect to see the code text area getting updated." - I meant the text area of the code view.
In short, the problem is I am in code view -> I run editor.html.insert("ABC") -> I don't see the code view getting updated.
More specifically I am trying to update the src attribute of am img tag.
Toggle to text and back to code does not help.

**Comment by merveartut** [comment]
is that fixed ? I have the same problem
