### ISSUE TITLE
Documentation on toolbarButtons is misleading

### ISSUE THREAD

**Issue by f3r** [froala/wysiwyg-editor#1613]
Please update the documentation at

https://www.froala.com/wysiwyg-editor/docs/options#toolbarButtons

When reads:
> html button requires code_view.min.js plugin;

And if you want to add a plugin using the [pluginsEnabled](https://www.froala.com/wysiwyg-editor/docs/options#pluginsEnabled) option, the plugin name is not `code_view` (as you would expect), but rather `codeView`

Thanks!!

**Comment by dianaprajescu** [comment]
Thanks for your suggestion, our documentation has been updated.

The confusion was generated by our internal naming convention: use underscores for file names and camel case for variables, options, methods, plugin names and so on.

The <a href="https://www.froala.com/wysiwyg-editor/docs/options#toolbarButtons" target="_blank" title="toolbarButtons">toolbarButtons</a> option now states the plugin name required by each button and a link to the complete list of plugins with files required by each of them. The <a href="https://www.froala.com/wysiwyg-editor/docs/options#pluginsEnabled" target="_blank" title="pluginsEnabled">pluginsEnabled</a> option also specified the available plugins
