### ISSUE TITLE
selection.element after format.applyStyle inaccurate result

### ISSUE THREAD

**Issue by delian7** [froala/wysiwyg-editor#1614]
##### Expected behavior.
selection.element should return the selected element if there is a selection. 

##### Actual behavior.
after `format.applyStyle` is called, `selection.element` returns the parent div and not the selection. 

##### Steps to reproduce the problem.
Following this [codepen.io](http://codepen.io/delian7/pen/RoGdLp):

1. Select all text
2. Click "get selected element" button (console logs the expected result)
3. Hit the "set font to 32 px" button
4. Click "get selected element" button (console logs incorrect results). 

##### OS.
macOS 10.12

##### Browser.
Chrome v. 54

**Comment by xPrzybyLx** [comment]
I have the same issue. 

OS: Linux (Ubuntu XFCE).
Browser: Chrome  57.0.2946.0

Video of the issue:  https://www.screencast.com/t/Ct8ooExl

**Comment by stefanneculai** [comment]
Fixed in 498f1dc923cdafbcb2b525811a92f83fced845e4
