### ISSUE TITLE
Indent buttons cause the placeholder text to be indented

### ISSUE THREAD

**Issue by chrisdeeming** [froala/wysiwyg-editor#1615]
##### Expected behavior.
Arguably, clicking the indent button in an empty editor should count as content and should cause the placeholder text to disappear.

##### Actual behavior.
The placeholder text is indented.

##### Steps to reproduce the problem.
https://www.froala.com/wysiwyg-editor/examples/placeholder - With no text in the editor, click the indent button, the placeholder will indent.

##### OS.
macOS Sierra

##### Browser.
Chrome 54

**Comment by stefanneculai** [comment]
@chrisdeeming we consider this as correct behavior and the placeholder was designed to work that way. Same happens if you select H1 or H2 for instance.
