### ISSUE TITLE
When initialising Froala on an empty textarea in IE11, the placeholder is editable text

### ISSUE THREAD

**Issue by chrisdeeming** [froala/wysiwyg-editor#1616]
##### Expected behavior.
The placeholder should act as a placeholder.

##### Actual behavior.
In IE11 if the editor is empty and has a placeholder upon initialisation, the placeholder text is actual editable text. If the text is removed, the actual placeholder reappears.

##### Steps to reproduce the problem.
Wasn't sure of the best way to demonstrate a reproduction case, but essentially if you start with your textarea.html example, and edit it so it has no initial content and run this in IE11 you will see that the initial placeholder text becomes actual editable text within the editor.

##### OS.
Windows 10

##### Browser.
Internet Explorer 11 - haven't been able to reproduce in any other browser.

**Comment by stefanneculai** [comment]
We couldn't reproduce this. Are you using v.2.3.5?

**Comment by chrisdeeming** [comment]
Did you follow the exact steps to reproduce the issue?

Froala needs to be initialised on a textarea element.
The contents of the editor should be empty.
Should have placeholder text.
Be using IE11.

I can reproduce it every time, but only if all of the above conditions are true.

**Comment by stefanneculai** [comment]
@chrisdeeming yes, we did just this in IE11 and tested on both Windows 10 and Windows 7. Could you make a jsFiddle for it?

**Comment by chrisdeeming** [comment]
Yes here we go:

https://jsfiddle.net/chrisxf/783qocq3/

My apologies, my reproduction steps weren't 100% accurate. It doesn't do it with the `placeHolderText` config option, it only does it if the placeholder comes from the textarea's `placeholder` attribute.
