### ISSUE TITLE
Cursor Not visible while press enter and CNTRL(CNTRL+A), SHIFT(SHIFT+leftarrow) shortcuts not working

### ISSUE THREAD

**Issue by aberamgd** [froala/wysiwyg-editor#1617]
1. When cursor is positioned at end of current line and enter is pressed, a blinking cursor does not appear on the first position of the newly created next line as expected.

If pressing enter from empty line, the blinking cursor will appear as expected.

2. Control & Shift shortcut controls are not working, example: Cntrl+A, Shift+leftarrow, Shift+toparrow, etc..

3. Image uploading not working, if we click on the Upload by URL and clicks again upload button, its working as expected else its showing error --- Unspecified error. in file image.min.js (7,29226)

Please help me with this issues, I tried hard but unable to fix it

Tested on:

Using froala_editor v2.3.5
Windows 10
Internet Explorer 11
Google Chrome  53.0.2785.89 m (64-bit)

**Comment by stefanneculai** [comment]
@aberamgd are you able to reproduce this on our website? Thank you.

**Comment by stefanneculai** [comment]
Closing this due to lack of response.
