### ISSUE TITLE
Safari > Unable to edit text with link on Safari

### ISSUE THREAD

**Issue by gandisama** [froala/wysiwyg-editor#1618]
##### Expected behavior.
Modal should appear, modal should move while scrolling (like on Chrome), user should be able to edit text 

##### Actual behavior.
Unable to place caret next to the text, modal does not appear

##### Steps to reproduce the problem.

1. Add text
2. Select text
3. Click on insert
4. Add url
5. Click on insert
6. Try to place caret next to the text

##### OS.
Sierra, El Capitan

##### Browser.
Safari 9, 10

##### Additional info:

Froala version 2.3.5

Very strange bug, when i want to edit a created link, or even after creation the special tooltip buttons
do not appear. There should be two divs that have classess "fr-popup fr-desktop" but in Safari only one appears. Only the tooltip from the toolbar appears in the source http://www.screencast.com/t/4SspLF6z. Funny thing though because on your site it works perfectly ... any ideas what could be causing the problem?

**Comment by stefanneculai** [comment]
If it works on our website, then most likely there is a problem from your configuration. Please make a jsFiddle so that we can help you.
