### ISSUE TITLE
'Cannot read property 'find' of null TypeError: Cannot read property 'find' of null

### ISSUE THREAD

**Issue by andyharjanto2** [froala/wysiwyg-editor#1620]
##### Expected behavior.
Should not raise exception

##### Actual behavior.
Exception occurs in this minimized js
function o() {
            var e = i();
            **_t.$tb.find(".fr-separator").remove(),
            t.$tb.find("> .fr-command").addClass("fr-hidden");_**
            for (var n = 0; n < e.length; n++)
                if ("|" == e[n] || "-" == e[n])
                    t.$tb.append(t.button.buildList([e[n]]));
                else {
                    var r = t.$tb.find('> .fr-command[data-cmd="' + e[n] + '"]')
                      , o = null ;
                    r.next().hasClass("fr-dropdown-menu") && (o = r.next()),
                    r.removeClass("fr-hidden").appendTo(t.$tb),
                    o && o.appendTo(t.$tb)
                }
        }

##### OS.
Windows 10 1607

##### Browser.
Chrome 54.0.2840.99 m

**Comment by andyharjanto2** [comment]
BTW. A similar issue was reported at #1436 (last thread), but no one responded.

**Comment by stefanneculai** [comment]
@andyharjanto2 could you please send us a link to a page where we can reproduce it? A jsFiddle would be great. Thank you.

**Comment by stefanneculai** [comment]
This is no longer a problem in V2.3.5. Please upgrade to it.
