### ISSUE TITLE
Inline toolbar moves inadvertently in Korean

### ISSUE THREAD

**Issue by dhguswns23** [froala/wysiwyg-editor#1621]
##### Actual behavior.

![11 -21-2016 23-35-51](https://cloud.githubusercontent.com/assets/8558899/20486497/55e9e50e-b043-11e6-83ba-7ee6fcccc783.gif)

##### Steps to reproduce the problem.
When user changes style using inline toolbar button(like bold, italic, etc.)  on korean not english, inline toolbar moves inadvertently.()

##### OS.
mac os

##### Browser.
Chrome lastest version

**Comment by stefanneculai** [comment]
Are you pressing anything on the keyboard after hitting the Bold button?

**Comment by dhguswns23** [comment]
No. I just click left mouse. Autually, this bug has occurred at demo page as well.

**Comment by stefanneculai** [comment]
Same with: https://github.com/froala/wysiwyg-editor/issues/1572#issuecomment-259158876.
