### ISSUE TITLE
Font Awesome icons lose sharpness at font-size: 15px

### ISSUE THREAD

**Issue by chrisdeeming** [froala/wysiwyg-editor#1623]
##### Expected behavior.
Font Awesome icons should appear sharp

##### Actual behavior.
Due to the default Froala font size of 15px, and the way FA is designed (it uses a 1792 x 1792 grid) the icons do not appear to be very sharp.

##### Steps to reproduce the problem.
![image](https://cloud.githubusercontent.com/assets/2158514/20537826/8ff67ade-b0e6-11e6-9724-35b5e75cc615.png)
This is a focused area of a couple of screenshots which demonstrated the issue to us. You can see the icons on the top row suffer a loss of sharpness. The bottom row has been adjusted down to 14px and looks a lot better.

##### OS.
Any

##### Browser.
Any

**Comment by stefanneculai** [comment]
What OS and Browser are you using? On MacOS, any browser they look just fine.

**Comment by chrisdeeming** [comment]
That screenshot may have been taken with Windows, but I'm on macOS and I can see it in all browsers. I have to be honest, it's so subtle it took someone pointing it out to me for me to see it. Let me see if I can make it clearer.

This is a screenshot of your homepage demo on macOS Sierra Firefox:
![image](https://cloud.githubusercontent.com/assets/2158514/20538505/7699f536-b0e9-11e6-9543-e8e0fa3c10ed.png)

This is the same screenshot but adjusting the font size down to 14px:
![image](https://cloud.githubusercontent.com/assets/2158514/20538549/a4c99cb8-b0e9-11e6-8aaa-877d4ba3159a.png)

If you zoom those screenshots in, and pay particular attention to the second line of the icon, you'll see at 15px it's actually quite noticeable. Unfortunately once you see it you can't unsee it so, sorry about that 🙂 

It's the same in all browsers on macOS, including Safari. I have a 2012 MacBook Pro so I have a non retina display; it may be less noticeable if you're using a high DPI display. It certainly seems better on iOS, for example. It's the same on Windows too (all browsers).
