### ISSUE TITLE
Images pasted from Snipping Tool or Grab (or similar) using Firefox results in two images being displayed

### ISSUE THREAD

**Issue by chrisdeeming** [froala/wysiwyg-editor#1624]
##### Expected behavior.
Only the image you paste should be uploaded and appear in the editor.

##### Actual behavior.
Using Firefox, after upload, you're left with two images in the editor:

```
<p>
    <img src="data:image/png;base64,i..." alt="" class="fr-dib fr-draggable">
    <img class="fr-dib fr-draggable" src="https://s3.amazonaws.com/froala/temp_files%2F1479841816925-untitled" style="width: 300px;">
</p>
```

(The first image is a full data URI representation of the image, obviously shortened here)

##### Steps to reproduce the problem.
Using Firefox, paste an image into the editor from a screengrab tool such as Window's Snipping tool or macOS' Grab.

##### OS.
Any

##### Browser.
Firefox

**Comment by stefanneculai** [comment]
Are you doing anything while the image is being uploaded?

**Comment by chrisdeeming** [comment]
Nope, nothing special.

Here's a screen recording demonstrating:

![froala-doubleimage](https://cloud.githubusercontent.com/assets/2158514/20539632/9d10ca38-b0ed-11e6-8185-0abb066f687f.gif)

In case the GIF doesn't come out very well:

1) Launched Grab
2) Went into Selection mode
3) Took a screenshot of part of the page, and did Cmd+C to copy it
4) Cleared the editor contents
5) Pasted image into the editor with Cmd+V
6) Two images appear

I can only reproduce this in Firefox (mac or Windows). Interestingly pasting into the editor doesn't work at all on your demo using Safari on macOS, that might be another issue.
