### ISSUE TITLE
font-size does not have a relative option

### ISSUE THREAD

**Issue by tmpg** [froala/wysiwyg-editor#1626]
##### Expected behavior.
Option to use rem, em or % for font size

##### Actual behavior.
can only use pixel

##### Steps to reproduce the problem.
Change font size and look at html.

##### OS.
All

##### Browser.
All

**Comment by stefanneculai** [comment]
We keep on this repo only issues, not feature-requests. I marked this as a `feature-request` and added it to our list.

**Comment by aarndt** [comment]
@stefanneculai Is there a place that we can view the status of feature requests or a roadmap? This feature would be very useful to us as well.
