### ISSUE TITLE
Froala not working with event.drag library

### ISSUE THREAD

**Issue by dandormont** [froala/wysiwyg-editor#1627]
My system uses the Froala v2 editor in conjunction with a number of libraries and tools, one of which is the popular SlickGrid tool: https://github.com/6pac/SlickGrid 
That tool in turn uses a library called event.drag from http://threedubmedia.com/code/event/drag

##### Expected behavior.
This library would not interfere with Froala Editor's operation.

##### Actual behavior.
When this library is merely present, the editor is inoperable. Specifically, just clicking into the editor's body does not seem to respond. I made an example at https://jsfiddle.net/z9t4ya0b/2/

##### Steps to reproduce the problem.
Simply include event.drag library on a document where Froala is invoked.

##### OS.
Mac OS 10.9, but is reproducible in others

##### Browser.
Chrome, but is reproducible in others.

**Comment by stefanneculai** [comment]
Please see: https://github.com/froala/wysiwyg-editor/issues/205#issuecomment-56945267. It appears that you should tell jquery drag not to target the editor elements. All editor elements start with the `fr-` class so you could use something like `[class*=' fr-']`.
