### ISSUE TITLE
[Feature Request] Improve "froalaEditor.video.inserted" event, showing if the video was embedded or inserted by url

### ISSUE THREAD

**Issue by ProGM** [froala/wysiwyg-editor#1630]
When inserting a video, the froala editor triggers the "froalaEditor.video.inserted" event, that returns the inserted video tag.
I tried to inspect the returned event object, but I couldn't find out how to understand if the video was inserted using an url or by adding the embed code.

Can you add some kind of attribute, like `"embedded" : true`, to deal with it?

I would find it very useful. I'm trying to add a custom attribute to iframes that are embedded.

**Comment by stefanneculai** [comment]
It's unlikely to have such a feature added in the editor. I would recommend you instead to write a wrapper over the insertEmbed and insertByURL methods in order to find out how a video was inserted.
