### ISSUE TITLE
Caret jumps to the beginning of the editor after cutting text (Ctrl/Cmd + X or context menu)

### ISSUE THREAD

**Issue by chrisdeeming** [froala/wysiwyg-editor#1634]
##### Expected behavior.
The caret position should not move to the start of the editor when cutting text to the clipboard. The caret should be at the start of the previous selection (that has just been cut to the clipboard).

##### Actual behavior.
The text is cut, but the caret jumps to the beginning of the editor

##### Steps to reproduce the problem.
This is reproducible on the front page demo here: https://www.froala.com/wysiwyg-editor

* Empty all text from the editor
* Type `12345 12345 12345`
* Highlight the middle block of `12345`
* Cut the text to the clipbard

The caret will jump to the start of the editor content (before the first block of `12345`)

##### OS.
macOS Sierra (and I believe Windows too)

##### Browser.
Safari, Chrome and Firefox

**Comment by CyberAP** [comment]
Same for iOS
