### ISSUE TITLE
Emoji keyboard shortcut on macOS (Ctrl + Cmd + Space) does not work

### ISSUE THREAD

**Issue by chrisdeeming** [froala/wysiwyg-editor#1636]
##### Expected behavior.
The emoji keyboard should appear:

![image](https://cloud.githubusercontent.com/assets/2158514/20902713/4dd32fcc-bb30-11e6-9ad9-cdb637fd6990.png)

##### Actual behavior.
A space is inserted instead.

##### Steps to reproduce the problem.
In any Froala editor, press the shortcut keys. A space is inserted instead of displaying the emoji keyboard.

##### OS.
macOS Sierra

##### Browser.
Chrome / Safari

I have tested this in some other editors and the support is hit and miss, but it does work in standard `contenteditable` elements, so ideally it should work elsewhere.

**Comment by stefanneculai** [comment]
It is fixed on the master branch.
