### ISSUE TITLE
`img` is undefined

### ISSUE THREAD

**Issue by GMiLL5** [froala/wysiwyg-editor#1637]
##### Issue

In the image plugin, `_placeCursor( )` method there's reference to an `img` variable that isn't defined. 

I haven't tracked down where this will throw an error yet, but thought I should bring it up

**Comment by JordanAtIgloo** [comment]
@GMiLL5 I saw this same thing, and I was also unable to get it to throw an error. I did end up changing the line: 
```javascript
$(img).after('<br>' + $.FE.MARKERS);
```
to: 
```javascript
$($(p_node).find('img')[0]).after('<br>' + $.FE.MARKERS);
```
which uses the already located element for the cursor placement instead. It's been a few months, and no problems so far, but it would be nice to get an official call from the developer as to what's going on here.

**Comment by GMiLL5** [comment]
@JordanAtIgloo Thanks for the heads up!

**Comment by JordanAtIgloo** [comment]
@stefanneculai thanks for looking into this.
