### ISSUE TITLE
IE - Images not inserted in right place

### ISSUE THREAD

**Issue by jchautreux** [froala/wysiwyg-editor#1640]
##### Expected behavior.
When choose an image, the img tag should be inserted where the cursor is

##### Actual behavior.
The img tag is always inserted at top of the editor

##### OS.
Windows 7 -> 8.1

##### Browser.
Microsoft Internet Explorer 11 (not tested on older version but maybe necessary)

**Comment by stefanneculai** [comment]
@jchautreux how are you inserting the image? Is that reproducible on our website as well?

**Comment by jchautreux** [comment]
Sorry for not responding earlier, and thank to correct this bug
