### ISSUE TITLE
Feature request: Bullet shortcut

### ISSUE THREAD

**Issue by mrjlynch** [froala/wysiwyg-editor#1643]
##### Expected behavior.
Microsoft Word and Google Docs have a bullet shortcut: `* + space` . 

This shortcut has been requested by my users and would be of great benefit

**Comment by stefanneculai** [comment]
Thanks for the feature suggestion.

**Comment by mrjlynch** [comment]
May I ask the likelihood this will be added? Thanks

**Comment by stefanneculai** [comment]
We've just put together a public roadmap with the most popular features. 😍 There you can vote your favorite one, provide feedback or make new suggestions: https://wysiwyg-editor-roadmap.froala.com/public.
