### ISSUE TITLE
Can't delete newlines after splitting nested divs 

### ISSUE THREAD

**Issue by strokirk** [froala/wysiwyg-editor#1645]
##### Expected behavior.
We are editing HTML that is nested a few levels, usually `div > div > div > blockquote > p`. Pressing enter inte the `p` tag should split the `p` tag, keeping one `blockquote` tag. Pressing backspace again should recombine the two `p` tags into one again.

##### Actual behavior.
When pressing enter inside the `p` tag, the text is split at the `div` element, creating a new `blockquote` element. It can't be recombined again with backspace.

##### Steps to reproduce the problem.
See this fiddle: https://jsfiddle.net/11csLex6/3/

##### OS.
Any OS.

##### Browser.
Any browser.

**Comment by stefanneculai** [comment]
@strokirk Please use the `class='fr-inner'`. See: https://jsfiddle.net/11csLex6/4/.
