### ISSUE TITLE
Not possible to copy/paste or insert images on IE11 with imageUploadURL option

### ISSUE THREAD

**Issue by pelizza** [froala/wysiwyg-editor#1651]
##### Expected behavior.
- Paste an image on Froala editor, wait for it to upload it and replace the current "base64" image with the URL of uploaded image.
- Insert an image on Froala editor using the toolbar, wait for it to upload and see the image inside the editor with the uploaded image URL.

##### Actual behavior.
Even after the successful request to upload the image, an error happens after that and the URL is not replaced (when using copy/paste) or not inserted (when using the toolbar).

##### Steps to reproduce the problem.
1) Open Edge with IE11 compatibility mode
2) Initialize a Froala editor using the option `imageUploadURL: <someUrl>`
3) Paste an image inside the editor
4) Check that the upload POST request is successful but an error occurs and the URL of the base64 image is not replaced.

Even when inserting an image using the toolbar, the error message is the same. The difference is that the base64 image is not inserted as well.

Check out [this video](http://recordit.co/e2I6xOmvbA).

##### OS.
Windows 10.

##### Browser.
Edge with IE11 compatibility mode.

##### Froala version
2.3.5. It should be fixed on a 2.3.6 version, since the latest version (2.4.0) has a lot of issues when using combined with angular-froala.

**Comment by stefanneculai** [comment]
Are you experiencing it on our website?

**Comment by pelizza** [comment]
Actually, you can close this ticket. We put Froala 2.4.0 to work and noticed this issue is already resolved. However, I have created this other issue to fix a bug with Froala 2.4.0: #1658

Thanks!
