### ISSUE TITLE
Froala editor destroy issue in Edge browser

### ISSUE THREAD

**Issue by SiddiquiImran** [froala/wysiwyg-editor#1652]
##### Expected behavior.
(Describe expected behaviour here)
when we have multiple instance of froala editor for different fields it should delete without any error.
 

##### Actual behavior.
(Describe actual behaviour here)
I am calling destroy method for instance one by one 
so destroy method get called for first instance of the editor but it throws error when get called for second instance.

throws error:
Object expected
![e97fc8be-c38b-11e6-91f2-a5f750c88379](https://cloud.githubusercontent.com/assets/20870175/21254683/ed2f1fea-c38c-11e6-8377-9bcb4634783e.png)

##### Steps to reproduce the problem.
(Describe the steps to reproduce the problem here)

create two editor an on navigate on some other page or on button click delete it.
var GetEditorMethods = function (el) {
        return el && el.data('froala.editor');
    };

var HeaderEditor = GetEditorMethods($('#txtHeaderEditor'));
            console.log('HeaderEditor', HeaderEditor);
            if (HeaderEditor) {
                HeaderEditor.destroy();
            }
            var FooterEditor = GetEditorMethods($('#txtFooterEditor'));
            console.log('FooterEditor', FooterEditor);
            if (FooterEditor) {
                FooterEditor.destroy();
            }

##### OS.
(OS name and version here)
windows 10 pro

##### Browser.
(Browser name an version here)
Edge browser
Microsoft Edge 38.14393.0.0
Microsoft EdgeHTML 14.14393

**Comment by stefanneculai** [comment]
@SiddiquiImran We just tried to reproduce this without success. Please make a jsFiddle.

**Comment by stefanneculai** [comment]
Closing this due to lack of response.
