### ISSUE TITLE
Froala editor copy paste issue in safari(mac)  browser

### ISSUE THREAD

**Issue by SiddiquiImran** [froala/wysiwyg-editor#1654]
##### Expected behavior.
(Describe expected behaviour here)
when we copy some text from anywhere and paste it in the editor the cursor should be in the last position in the pasted code an should blink.

##### Actual behavior.
(Describe actual behaviour here)
when we copy some text from anywhere and paste it in the editor the text is got pasted but cursor is not showing up.

##### Steps to reproduce the problem.
(Describe the steps to reproduce the problem here)

##### OS.
(OS name and version here)
OS X EI Capitan Version 10.11.6

##### Browser.
(Browser name an version here)
Safari Version 9.1.2 (11601.7.7)

**Comment by stefanneculai** [comment]
@SiddiquiImran are you experiencing that on our website? Could you please make a recording?

**Comment by SiddiquiImran** [comment]
Hi @stefanneculai ,
yes you can test it on this url
https://www.froala.com/wysiwyg-editor/examples/iframe

**Comment by stefanneculai** [comment]
@SiddiquiImran thanks for the additional details. We just fixed it in a previous commit. It was the same with #1653.
