### ISSUE TITLE
New line inserted when typing inside table cell (Firefox/mac)

### ISSUE THREAD

**Issue by manuelkalman** [froala/wysiwyg-editor#1657]
When entering content in table cell, text jumps in to the second line because <br> is inserted before the text. It only works fine on first cell in first column immediately after you create table. When you change the cell the bug appears.

Also tested on your website. Firefox only, Chrome/Safari is working OK. Didn't test other browsers or Windows versions. 

##### OS.
macOS

##### Browser.
Firefox 50 0 2

**Comment by stefanneculai** [comment]
Could you please make a recording? Thank you.

**Comment by manuelkalman** [comment]
I attached the file.

I also notice, when you switch to code view, it doesn't position you in the clicked line, but on the top of the code. 

[froala-newline.zip](https://github.com/froala/wysiwyg-editor/files/663152/froala-newline.zip)

**Comment by stefanneculai** [comment]
This is already fixed on the current master.
