### ISSUE TITLE
Should it be possible to drag highlighted text within the editor to another location in the editor?

### ISSUE THREAD

**Issue by chrisdeeming** [froala/wysiwyg-editor#1659]
##### Expected behavior.
Some editors allow you to highlight text within the editor, and then drag that text to another position within the editor.

##### Actual behavior.
Dragging on highlighted text just cancels the existing highlight and does not move the text.

##### Steps to reproduce the problem.
Highlight text within the editor and drag, no text is moved.

##### OS.
Any

##### Browser.
Any

The support for this amongst other editors seems to be lacking, but it is a standard feature of plain textarea and contenteditable div elements, and common generally within word processors/text editors as OS applications.

**Comment by stefanneculai** [comment]
Unfortunately, this is a limitation of the browser `contenteditable` feature.

**Comment by chrisdeeming** [comment]
@stefanneculai, unfortunately, that doesn't appear to be the case. This test is totally unrelated but as a demonstration, the following URL contains a plain `contenteditable` div, and in Chrome and Firefox (on macOS and Windows) the text is draggable within the div.

https://xenforo.com/bugs/chrome-ios-contenteditable-scroll.html

**Comment by stefanneculai** [comment]
I was testing in Chrome and in Chrome in native content editable drag isn't working. I am reopening this and we'll check it once over again.

**Comment by chrisdeeming** [comment]
I am using pre-release Chrome in case it makes any difference: `Version 56.0.2924.28 beta (64-bit)`

**Comment by stefanneculai** [comment]
@chrisdeeming they might be added it in beta. we'll check.
