### ISSUE TITLE
Can't select text or put cursor in inline-editor using IE Edge / IE11 and FF in Angular2 app

### ISSUE THREAD

**Issue by webtrix** [froala/wysiwyg-editor#1660]
##### Expected behavior.
Being able to select text and set the cursor where clicked in the editor box. 

##### Actual behavior.
Can't select any text, besides using CTRL+A, can't put the cursor where I want to. It will always be place at the start of the text

##### Steps to reproduce the problem.
(Describe the steps to reproduce the problem here)

##### OS.
Windows 8.1

##### Browser.
(Browser name an version here)
, IE Edge, IE11, FF 50.1.0

I'm using Froala with jQuery in an Angular 2 project, in Chrome everything works perfectly fine, but in IE and FF that isn't the case. I don't know if it has anything to do with ShadowDom or so.

But what I did is, I created a directive, that create the editor when clicked on an element that uses that directive. This is the init code of Froala, I'm using.

```
jQuery(this.wysiwyg.element).froalaEditor({
        key: key,
        useClasses: true,
        toolbarContainer: '#toolbarContainer',
        toolbarButtons: toolbar,
        toolbarButtonsMD: toolbar,
        toolbarButtonsSM: toolbar,
        toolbarButtonsXS: toolbar,
        htmlRemoveTags: ['script', 'base'],
        toolbarSticky: false,
        linkEditButtons: ['linkEdit', 'linkRemove'],
        linkInsertButtons: ['linkBack'],
        linkMultipleStyles: false,
        linkText: true,
        linkAlwaysBlank: true,
        keepFormatOnDelete: true,
        placeholderText: ''
});
```

When the editor isn't used anymore, i just do `jQuery(this.wysiwyg.element).froalaEditor('destroy');`

It's kinda strange that this all works without any problem in Chrome, but not in FF and IE Edge / IE11, could you guys maybe have some suggestions?

**Comment by stefanneculai** [comment]
Please open this issue on the Angular 2 plugin for the editor: https://github.com/froala/angular2-froala-wysiwyg.
