### ISSUE TITLE
Best approach for embedding twitter, facebook  and other widgets

### ISSUE THREAD

**Issue by tomalex0** [froala/wysiwyg-editor#1661]
##### Expected behavior.
(Describe expected behaviour here)
 Need a froala  plugin  or define approach  to embed  tweets, facebook  post  etc and  show data as part of content preview

http://plnkr.co/edit/rQUThnZNAyJQGFIwflGk?p=preview
https://developers.facebook.com/docs/plugins/embedded-posts

As of now i opened  html edit view and embedded the html.  and did 

##### Actual behavior.
(Describe actual behaviour here)
As of  now tweets and facebook posts are considered as simple url.

##### Steps to reproduce the problem.
(Describe the steps to reproduce the problem here)

##### OS.
(OS name and version here)

##### Browser.
(Browser name an version here)

**Comment by tomalex0** [comment]
![image](https://cloud.githubusercontent.com/assets/208168/21363614/3907a0b4-c6a2-11e6-9a7a-e01dac806143.png)

I'm also trying to develop have dropdown which accepts url and based on the type i will wrap the url

**Comment by stefanneculai** [comment]
@tomalex0 at this moment we're working on a new feature that would allow to embed rich content such as Twitter or Facebook posts, however I don't have an ETA at this moment for it.

**Comment by selfagency** [comment]
it's two months later, do you have an eta yet?

**Comment by traber333** [comment]
Do we know if this is an option yet?

**Comment by stefanneculai** [comment]
@tomalex0 @traber333 @selfagency It is possible starting with version 2.7.0. See https://www.froala.com/blog/wysiwyg-editor/most-wanted-froala-editor-release.
