### ISSUE TITLE
Code view plugin error in Edge browser

### ISSUE THREAD

**Issue by palich12** [froala/wysiwyg-editor#1666]
##### Actual behavior.
When push code view plugin button in edge browser, have error in browser console. Use Angular 1
SCRIPT87: Недопустимый аргумент.
code_view.min.js (7,1272)

##### Steps to reproduce the problem.
In edge browser push code view plugin button on froala toolbar. Use Angular 1
SCRIPT87: Недопустимый аргумент.
code_view.min.js (7,1272)

##### OS.
Widows

##### Browser.
Edge

**Comment by stefanneculai** [comment]
@palich12 are you experiencing that on our website?

**Comment by palich12** [comment]
No, I not found on your site workable demo whith using Angular 1

**Comment by palich12** [comment]
I'm imitate this bug on simple page examle. When it opened in Edge. And push code_view button. I have error in console.
[https://static.fabuza.ru/froala_edge_bug/](url)

**Comment by FletcherPink** [comment]
I have an eror too using Jquery on Firefox 50.1.0 Mac Os El Capitan:
`Error : IndexSizeError: Index or size is negative or greater than the allowed amount
Script : https://cdnjs.cloudflare.com/ajax/libs/froala-editor/2.4.0/js/plugins/code_view.min.js
Line : 7
Column : 0
StackTrace : IndexSizeError: Index or size is negative or greater than the allowed amount`

**Comment by stefanneculai** [comment]
You are using an older version of jQuery (1.9.1). The editor requires jQuery at least 1.11.0.

**Comment by FletcherPink** [comment]
I'm sorry but i'm using JQuery 2.2.4. Here is part of my header:

`<script src="https://code.jquery.com/jquery-2.2.4.min.js" integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44=" crossorigin="anonymous"></script>`
`<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js" integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU=" crossorigin="anonymous"></script>`
`<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/froala-editor/2.4.0/js/froala_editor.min.js"></script>`
`<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/froala-editor/2.4.0/js/froala_editor.pkgd.min.js"></script>`
`<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/froala-editor/2.4.0/js/languages/fr.js"></script>`
`<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/froala-editor/2.4.0/js/plugins/align.min.js"></script>`
`<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/froala-editor/2.4.0/js/plugins/char_counter.min.js"></script>`
`<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/froala-editor/2.4.0/js/plugins/code_beautifier.min.js"></script>`
`<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/froala-editor/2.4.0/js/plugins/code_view.min.js"></script>`
`<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/froala-editor/2.4.0/js/plugins/colors.min.js"></script>`
`<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/froala-editor/2.4.0/js/plugins/draggable.min.js"></script>`
`<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/froala-editor/2.4.0/js/plugins/emoticons.min.js"></script>`
`<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/froala-editor/2.4.0/js/plugins/entities.min.js"></script>`
`<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/froala-editor/2.4.0/js/plugins/file.min.js"></script>`
`<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/froala-editor/2.4.0/js/plugins/font_family.min.js"></script>`
`<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/froala-editor/2.4.0/js/plugins/font_size.min.js"></script>`
`<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/froala-editor/2.4.0/js/plugins/forms.min.js"></script>`
`<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/froala-editor/2.4.0/js/plugins/fullscreen.min.js"></script>`
`<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/froala-editor/2.4.0/js/plugins/help.min.js"></script>`
`<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/froala-editor/2.4.0/js/plugins/image_manager.min.js"></script>`
`<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/froala-editor/2.4.0/js/plugins/image.min.js"></script>`
`<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/froala-editor/2.4.0/js/plugins/inline_style.min.js"></script>`
`<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/froala-editor/2.4.0/js/plugins/line_breaker.min.js"></script>`
`<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/froala-editor/2.4.0/js/plugins/link.min.js"></script>`
`<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/froala-editor/2.4.0/js/plugins/lists.min.js"></script>`
`<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/froala-editor/2.4.0/js/plugins/paragraph_format.min.js"></script>`
`<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/froala-editor/2.4.0/js/plugins/paragraph_style.min.js"></script>`
`<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/froala-editor/2.4.0/js/plugins/quick_insert.min.js"></script>`
`<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/froala-editor/2.4.0/js/plugins/quote.min.js"></script>`
`<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/froala-editor/2.4.0/js/plugins/save.min.js"></script>`
`<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/froala-editor/2.4.0/js/plugins/table.min.js"></script>`
`<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/froala-editor/2.4.0/js/plugins/url.min.js"></script>`
`<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/froala-editor/2.4.0/js/plugins/video.min.js"></script>`

**Comment by stefanneculai** [comment]
@FletcherPink that is right. The last commit fixes it.

**Comment by FletcherPink** [comment]
Thanks! 👍

**Comment by palich12** [comment]
I update jquery, but it not solve the problem. You can see this demo by link
[https://static.fabuza.ru/froala_edge_bug/](https://static.fabuza.ru/froala_edge_bug/)

**Comment by stefanneculai** [comment]
@palich12 please update tot the Github master.

**Comment by palich12** [comment]
@stefanneculai  ok, thanks! Problem is solved :)
