### ISSUE TITLE
IE11 can't insert text between image and image.

### ISSUE THREAD

**Issue by highca** [froala/wysiwyg-editor#1667]
##### Expected behavior.
Insert text between image and image.

##### Actual behavior.
Text is inserted only at the bottom of the last image.

##### Steps to reproduce the problem.

The html is like below,

<p><img width="150" class="fr-fil fr-dib fr-draggable" alt="book" src="/assets/editor/docs/photo14.jpg"></p>

<p><img width="150" class="fr-fil fr-dib fr-draggable" alt="book" src="/assets/editor/docs/photo15.jpg"></p>

<p><img width="150" class="fr-fil fr-dib fr-draggable" alt="book" src="/assets/editor/docs/photo16.jpg"></p>

I can't insert text between image and image.
If I try insert text between image and image, the cursor made new empty line(p tag) at the bottom of the last image.

Tested on froala.com and my site.

##### OS.
Windows 10
Windows 8.1

##### Browser.
Internet Explorer 11

**Comment by stefanneculai** [comment]
Unfortunately because of some browser limitations it is not possible to place cursor between the images. For that we just made the editor to insert a new line just above the image when you have the image selected and hit enter.
