### ISSUE TITLE
Incorrect toolbar and tooltip positioning when editing element inside iframe

### ISSUE THREAD

**Issue by UCIS** [froala/wysiwyg-editor#1670]
We would like to use the Froala editor to edit individual elements inside an iframe, while keeping the Froala scripts and CSS outside of the iframe. This is a re-post of #1619 because I believe the previous issue was incorrectly closed. #1619 also describes a possible fix.

##### Expected behavior.
The editor toolbar should follow the iframe scroll position. Preferably the tooltip should be positioned outside of the iframe so it if not affected by inner styling and bounds.

##### Actual behavior.
The froala toolbar does not take the iframe's scroll position into consideration and the tooltip is often clipped by the iframe.

##### Steps to reproduce the problem.
https://jsfiddle.net/rdg5yL0p/7/

The problem also occurs with Froala editor 2.4.0, which in addition does not show the Paragraph style button in the toolbar: https://jsfiddle.net/rdg5yL0p/8/

##### OS.
Linux Mint x64

##### Browser.
Google Chrome 55.0.2883.87 (64-bit)

**Comment by stefanneculai** [comment]
That is because you are not setting the `scrollableContainer` option: https://jsfiddle.net/bysp4rxv/.

**Comment by UCIS** [comment]
Unfortunately this forces the toolbar to be inside the iframe, making it dependent on styling inside the iframe and clipping by the iframe.

Also the scrollableContainer option is listed as a string in the documentation, and setting this to an element/jquery object may cause problems during JSON serialization as shown here: https://jsfiddle.net/bysp4rxv/3/
