### ISSUE TITLE
Loading Image Pop Up bad position

### ISSUE THREAD

**Issue by FletcherPink** [froala/wysiwyg-editor#1672]
##### Expected behavior.
When inserting image from image manager, if editor is empty, the loading pop up is positionning far over the editor.

##### Actual behavior.
As this popup disapear quickly, i can't get its class or anything else to solve the problem by my own. Is there a way to put a stop to manage it ?

And can i edit it css ?
 
##### OS.
El Capitan

##### Browser.
Firefox 50.1

**Comment by stefanneculai** [comment]
Are you able to reprouce it on our website?

**Comment by FletcherPink** [comment]
No, i can't because images are smallest and it disappear too fast. Is there a documentation about this loader popup ? Can i add step to understand why my css conflict with this pop up ?

**Comment by stefanneculai** [comment]
@FletcherPink what options are you initializing the editor with?

**Comment by FletcherPink** [comment]
Do you mean Froala options ?
`initOnClick: false,`
`inlineStyles: { xxxx },`
`charCounterCount: true,`
`codeMirror: true,`
`colorsBackground: xxx,`
`colorsText: xxx,`
`colorsStep: 5,`
`editorClass: xxx,`
`enter: $.FroalaEditor.ENTER_P,`
`height: 'auto',`
`heightMin: 200,`
`imageEditButtons: ['imageAlign', 'Clear', '|', 'imageLink', 'linkEdit', 'linkRemove', '|', 'imageAlt', '|', 'ChangeImage', 'imageRemove', '|', 'LargeurImage', 'ZoomImage', 'ClassImage'],`
`imageAltButtons: ['imageBack'],`
`imageInsertButtons: ['imageBack', '|', 'imageManager'],`
`imageSizeButtons: ['imageBack'],`
`imageDefaultDisplay: 'inline',`
`imageDefaultWidth: 360,`
`imageDefaultAlign: 'left',`
`imageManagerLoadURL: xxx,`
`imageManagerLoadParams: { xxx },`
`imageManagerDeleteParams: { xxx },`
`imageManagerPreloader: 'xxx.gif',`
`imageManagerPageSize: 10,`
`imageManagerScrollOffset: 10,`
`imageMinWidth: 32,`
`imageMove: false,`
`imageMultipleStyles: false,`
`imageOutputSize: false,`
`imagePaste: false,`
`imageResizeWithPercent: false,`
`imageRoundPercent: false,`
`imageSplitHTML: true,`
`imageTextNear: true,`
`htmlRemoveTags: ['style', 'base'],`
`language: 'fr',`
`linkEditButtons: ['linkStyle', 'linkOpen', 'linkEdit', 'linkRemove'],`
`linkInsertButtons: ['linkBack', 'linkStyle'],`
`linkList: [
			{ text: 'xxx', href: 'xxx', target: '_blank', rel: 'nofollow' },
			{ displayText: 'xxx', href: 'xxx', target: '_blank' }
		],`
`linkMultipleStyles: false,`
`linkAlwaysNoFollow: false,`
`linkText: true,`
`linkStyles: { xxx: 'xxx', xxx: 'xxx' },`
`multiLine: true,`
`paragraphFormat: { xxx },`
`paragraphFormatSelection: false,`
`pastePlain: true,`
`placeholderText: xxx,`
`tabSpaces: false,`
`theme: 'gray',`
`useClasses: xxx,`
`tableColors: xxx,`
`tableColorsStep: 5,`
`tableEditButtons: ['tableRows', 'tableColumns', 'tableCells', '|', 'tableCellVerticalAlign', 'tableCellHorizontalAlign', '|', 'tableStyle', 'tableCellBackground', '|', 'tableRemove'],`
`tableResizer: false,`
`tableResizingLimit: 20,`
`tableStyles: { xxx },`
`toolbarButtons: ['bold', 'italic', 'underline', 'strikeThrough', 'superscript', 'color', '|', 'paragraphFormat', 'align', 'formatOL', 'formatUL', '|', 'PanneauImage', 'MenuLien', 'insertVideo', '|', 'insertHR', 'insertTable', '|', 'undo', 'clearFormatting', 'redo', 'html'],`
`toolbarButtonsMD: ['bold', 'italic', 'underline', 'strikeThrough', 'superscript', 'color', '|', 'paragraphFormat', 'align', 'formatOL', 'formatUL', '|', 'PanneauImage', 'MenuLien', 'insertVideo', '|', 'insertHR', 'insertTable', '|', 'undo', 'clearFormatting', 'redo', 'html'],`
`toolbarButtonsSM: ['bold', 'italic', 'underline', 'strikeThrough', 'superscript', 'color', '|', 'paragraphFormat', 'align', 'formatOL', 'formatUL', '|', 'PanneauImage', 'MenuLien', 'insertVideo', '|', 'insertHR', 'insertTable', '|', 'undo', 'clearFormatting', 'redo', 'html'],`
`toolbarButtonsXS: ['bold', 'italic', 'underline', 'strikeThrough', 'superscript', 'color', '|', 'paragraphFormat', 'align', 'formatOL', 'formatUL', '|', 'PanneauImage', 'MenuLien', 'insertVideo', '|', 'insertHR', 'insertTable', '|', 'undo', 'clearFormatting', 'redo', 'html'],`
`toolbarInline: inline,`
`toolbarStickyOffset: 0,`
`toolbarVisibleWithoutSelection: true,`
`tooltips: false,`
`shortcutsEnabled: ['show', 'bold', 'italic', 'underline', 'strikeThrough', 'indent', 'outdent', 'undo', 'redo', 'insertImage', 'createLink'],`
`videoDefaultAlign: 'center',`
`videoDefaultDisplay: 'inline',`
`videoMove: false,`
`videoResize: true,`
`videoSplitHTML: true,`
`videoTextNear: true`

**Comment by FletcherPink** [comment]
It seems that the loading popup is positioned according to the clicked image to be added from the image manager.
And as the manager is removed before the popup appears, his position appears incorrect.

This loading popup should appear on the call button of the image manager, for example.

**Comment by FletcherPink** [comment]
Thanks! 👍
