### ISSUE TITLE
[RFC] Media upload text customization

### ISSUE THREAD

**Issue by yann-eugone** [froala/wysiwyg-editor#1675]
##### Expected behavior.
I many case, you need to display information about the media you allow your users to upload : size, file type, dimensions, etc...

![froala-upload-wanted](https://cloud.githubusercontent.com/assets/1303838/21635450/0edf626e-d25e-11e6-9553-ff259518c9c1.png)

##### Actual behavior.
The texts in the upload area are not really customizable.
There is 2 strings you can translate, and thus approching the expected behavior : 

- `Drop image`
- `or click`

But you cannot remove the parenthesis, neither the <br/> between the two translations keys.

![froala-image-uploader](https://cloud.githubusercontent.com/assets/1303838/21635339/63cda192-d25d-11e6-8594-c721921ef3d4.png)

##### Steps to reproduce the problem.
Just use the image upload feature.

##### OS.
_ALL_

##### Browser.
_ALL_

**Comment by stefanneculai** [comment]
You could do something like this:
```
$(selector).on('froalaEditor.initialized', function (e, editor) {
  editor.popups.onShow('image.insert', function () {
    var $popup = editor.popups.get('image.insert');

    // Replace the text here.
  })
});

**Comment by yann-eugone** [comment]
Ok, thanks for your answer. I will do something like this.
Just want to say that **this is not a solution**, just a little trick to do the job...
