### ISSUE TITLE
Up/Down arrow keys not working properly for tables with row groups: thead, tfoot, tbody

### ISSUE THREAD

**Issue by robmack** [froala/wysiwyg-editor#1676]
Thanks for all your hard work on the Froala editor. It's great!

I ran across this today and I think it's a bug.

The up/down arrow keys don't behave properly when used in a table with row groups.

The HTML spec says tfoot should follow thead in the source so the browser can render the table header and footer before rendering what could be a large number of body rows: "TFOOT must appear before TBODY within a TABLE definition" (https://www.w3.org/TR/html401/struct/tables.html#h-11.2.3 )

The logic for the up and down arrows movement inside tables doesn't appear to consider row groups.

## Steps to reproduce the problem

Tested against version 2.4.0

1. In the source view of a froala editor (you can use the one on: https://www.froala.com/wysiwyg-editor) paste the following:

```
<table>
  <thead>
    <tr>
      <td>the table header</td>
    </tr>
  </thead>
  <tfoot>
    <tr>
      <td>the footer</td>
    </tr>
  </tfoot>
  <tbody>
    <tr>
      <td>the table body</td>
    </tr>
  </tbody>
</table>
```
2. Click the source button to return to the wysiwyg mode
3. Place cursor in the "the table header" cell
4. Press the down arrow

## Expected behavior

Cursor should move to next cell below, which is the "the table body" cell.

## Actual behavior

Cursor moves to the "the table footer" cell

The cursor seems to be moving to the next tr tag in the source code.

## OS
Mac Sierra

## Browser
Chrome Version 55.0.2883.95 (64-bit)

**Comment by stefanneculai** [comment]
This is a bug from browsers. We just reported them over to Chrome, Mozilla and Safari in order to be fixed: https://bugs.chromium.org/p/chromium/issues/detail?id=725464.

**Comment by GraemeFulton** [comment]
this bug still exists :( , fine in firefox though
