### ISSUE TITLE
html in code view is not displayed as code block when switching back to normal mode

### ISSUE THREAD

**Issue by xPrzybyLx** [froala/wysiwyg-editor#1677]
##### Expected behavior.
When pasting code like `<pre><strong>testing</strong></pre>` into the "Code View" mode this html should be displayed as code block.

##### Actual behavior.
When pasting code like `<pre><strong>testing</strong></pre>` into the "Code View" mode and then switching back to normal view the pasted html is not displayed as a code but interpreted as html (ie. strong is applied to text "testing").

##### Steps to reproduce the problem.
Click "Code View"
Paste or enter `<pre><strong>testing</strong></pre>`
Click "Code View" again

##### OS.
Ubuntu 16.10 x64 XFCE

##### Browser.
Chrome Version 57.0.2970.0 (Official Build) dev (64-bit)

**Comment by stefanneculai** [comment]
In order to display the < and > characters you should have to use their HTML. See: https://jsfiddle.net/msbwv6pb/1/.
