### ISSUE TITLE
placeholder.refresh not working

### ISSUE THREAD

**Issue by connect-technologies** [froala/wysiwyg-editor#1678]
##### Expected behavior.
I'd like to update the placeholderText on an existing froalaEditor:
`$('.selector').froalaEditor({
placeholderText: 'foobar'
});`
and then
`$('.selector').froalaEditor('placeholder.refresh');`

##### Actual behavior.
but nothing happens. The old placeholder is still there.

##### OS.
v2.4.0

##### Browser.
newest FF

**Comment by stefanneculai** [comment]
To set an option after the editor was initialized, you would have to do it like this: `$('.selector').data('froala.editor').opts.placeholderText = 'foobar';`.

**Comment by connect-technologies** [comment]
Hi, yes thank you.
And after that i still have to call
`$('.selector').froalaEditor('placeholder.refresh');`

**Comment by varunzxzx** [comment]
Is there any solution available for react too?
