### ISSUE TITLE
Using on a "required" textarea breaks native browser form validation.

### ISSUE THREAD

**Issue by jgerigmeyer** [froala/wysiwyg-editor#1681]
##### Expected behavior.
When submitting a form with an empty Froala `textarea["required"]`, the native browser form validation error message should display on the Froala `contenteditable`.

##### Actual behavior.
Firefox displays the message in the far top-left of the browser window. Chrome simply throws an error: `An invalid form control with name='body' is not focusable.`

This could be fixed by positioning the `textarea` behind the `contenteditable` or something, instead of hiding it with `display: none`.

##### Steps to reproduce the problem.
https://jsfiddle.net/jgerigmeyer/dffhnu7L/1/

##### OS.
macOS Sierra 10.12.2

##### Browser.
Chrome 55.0.2883.95 (64-bit)
Firefox 52.0a2 (2017-01-05) (64-bit)
Firefox 50.1.0 (2017-01-05) (64-bit)

**Comment by stefanneculai** [comment]
The default browser required cannot be used on the editor. If you want to implement a custom checker for an empty editor, you could use the `core.isEmpty` method.
