### ISSUE TITLE
Problem with pasting tables from excel

### ISSUE THREAD

**Issue by henningborchers** [froala/wysiwyg-editor#1682]
##### Expected behavior.
Pasting tables from excel into the editor should create a html table structure

##### Actual behavior.
The table creates plain text in the editor

##### Steps to reproduce the problem.
Paste some Table Cells in the demo editor: https://www.froala.com/wysiwyg-editor

##### OS.
OSX, Windows 7
Excel, Libre Office

##### Browser.
Chrome

**Comment by stefanneculai** [comment]
@henningborchers would it be possible to send us the document you're copying from?

**Comment by henningborchers** [comment]
@stefanneculai 

here we go:
[test.xls.zip](https://github.com/froala/wysiwyg-editor/files/689995/test.xls.zip)

**Comment by sandeepsukhija** [comment]
@stefanneculai 

any update on this

**Comment by stefanneculai** [comment]
@henningborchers @sandeepsukhija there is going to be an update for all Office pasting over the following weeks.
