### ISSUE TITLE
Documented event link.beforeInsert is not triggered

### ISSUE THREAD

**Issue by tyclipso** [froala/wysiwyg-editor#1684]
##### Expected behavior.
event link.beforeInsert is triggered if one is inserting a link.

##### Actual behavior.
event link.beforeInsert is not triggered if one is inserting a link.

##### Steps to reproduce the problem.
Insert a link.
The event cannot be found in uncompressed JS-sources.

##### OS.
Windows 10

##### Browser.
Chrome 55

**Comment by stefanneculai** [comment]
This has been added in V2.4.0. Please make sure you're using that version.
