### ISSUE TITLE
fr-popup inputs closing after replacing the html that contains the froala editor

### ISSUE THREAD

**Issue by Stormtv** [froala/wysiwyg-editor#1685]
##### Expected behavior.
When clicking inside the link fr-popup on an input the fr-popup should stay fr-active.

##### Actual behavior.
The fr-popup losses the fr-active class.

##### Steps to reproduce the problem.
I've created a test case here in jsfiddle.
https://jsfiddle.net/br3gwtn0/4/

1. Click the link button.
2. Clear the zone.
3. Click the link button again.
4. Try to click on the input text field

##### OS.
Ubuntu 16.04

##### Browser.
Chrome Version 55.0.2883.87 (64-bit)

**Comment by stefanneculai** [comment]
You should destroy the editor instance before replacing the HTML. See: https://jsfiddle.net/froala/br3gwtn0/5/.
