### ISSUE TITLE
Code View - <a> wrapping <div> is reformatted when toggled between code view

### ISSUE THREAD

**Issue by jkeatingatigloo** [froala/wysiwyg-editor#1686]
### Expected behavior.
As per HTML5 specification 

> The < a > element may be wrapped around entire paragraphs, lists, tables, and so forth, even entire sections, so long as there is no interactive content within (e.g. buttons or other links). 

We should be able to (in code view) create markup where an < a > wraps a < div > and Froala should preserve our markup when toggling between code view.

### Actual behavior.
Unfortunately, if you try and wrap an < div > with an < a > tag and toggle off/on code view the editor generates multiple <a> tags wrapped INSIDE elements.

### Steps to reproduce the problem.

1. Navigate to Froala home page demo
2. Toggle "code view" on
3. Replace contents with the following

```
<a href=“immalink">
  <div>
    <p>lots of contents goes here</p>
  </div>
</a>
```
4. Toggle code view off and then on again
5. Inspect code - notice how the markup has significantly changed 

##### OS.
Windows 10

##### Browser.
Chrome Version 55.0.2883.8
![froala-codeview-anchor-markup](https://cloud.githubusercontent.com/assets/24943924/21775287/791fbf94-d663-11e6-9f09-b638b9d3ea5b.gif)
7 m (64-bit)

**Comment by stefanneculai** [comment]
That is because you are trying to put a DIV inside an A tag which is inside a P tag. P tags do not allow DIV tags inside them. For this scenario, it would be better to use the `enter: $.FroalaEditor.ENTER_DIV` option: https://www.froala.com/wysiwyg-editor/examples/enter
