### ISSUE TITLE
Save error response does not container server response data

### ISSUE THREAD

**Issue by desheikh** [froala/wysiwyg-editor#1687]
##### Expected behavior.
Save errors event should contain any response data returned from the call

##### Actual behavior.
A generic error object is returned.
{code: 2, message: "Something went wrong during save."}

##### Steps to reproduce the problem.
call save.save() on a froala editor with a froalaEditor.save.error event attached. The error argument will not contain and response data returned by the server.

##### OS.
(OS name and version here)
OSX - 10.12.2

##### Browser.
Chrome

**Comment by stefanneculai** [comment]
It appears to be missing from the documentation. There is a 4th parameter response for the save.error event.

**Comment by desheikh** [comment]
Nice, thanks for the tip

**Comment by stefanneculai** [comment]
It's updated.
