### ISSUE TITLE
Code in script tag is raninig when editor loading and after code_view using

### ISSUE THREAD

**Issue by palich12** [froala/wysiwyg-editor#1688]
When editing HTML contain script tag. Code in script tag is raninig when editor loading and after code_view using.
Some times editing code can contein errors, so if I'm using code_view  Iit's crased editor and lost data after using code_view  

Link for demo bug whith alert message
[https://static.fabuza.ru/froala_edge_bug/](https://static.fabuza.ru/froala_edge_bug/)

**Comment by stefanneculai** [comment]
That is because you have removed the `SCRIPT` tag from the `htmlRemoveTags` option. It is the intended behavior with `htmlRemoveTags: []`.

**Comment by palich12** [comment]
@stefanneculai Yes, but if I add `htmlRemoveTags: ['script']` I lost this tag in model, and can't adit it by code_view. I need edit code in aditor, but this code must runing at another place, not in editor. And if  it running in editor with errors, this crashed editor
