### ISSUE TITLE
charCounterMax does not work on mobile

### ISSUE THREAD

**Issue by tmpg** [froala/wysiwyg-editor#1689]
##### Expected behavior.
Disable input once max characters are met.

##### Actual behavior.
On mobile, the user can go over the character limit.

##### Steps to reproduce the problem.
Use a mobile phone and set a max character limit on the froala editor. On IOS it is harder to go over but if you use AUTO complete it will easily go over. For Android regular typing will make it go over and auto complete.

##### OS.
Android, IOS

##### Browser.
Chrome 55 or Safari 10 (iOS only)

![screenshot_20170110-075018](https://cloud.githubusercontent.com/assets/7082248/21807125/217cebb0-d70b-11e6-8354-986f29c1afd6.png)

**Comment by stefanneculai** [comment]
Unfortunately, this is a problem of the browsers on mobile, mainly because of the predictive keyboard. Same problem can be easily reproduced on https://jsfiddle.net/xmtmg5kn/3/. We'll report it further to see if we can get the browser developers to fix it.
