### ISSUE TITLE
Outdenting first list item with nested list should put text content in defaultTag( ) wrapper

### ISSUE THREAD

**Issue by GMiLL5** [froala/wysiwyg-editor#1692]
##### Expected behavior.
When outdenting the first item in a non-nested list, it should always wrap the contents in the defaultTag

##### Actual behavior.
If the first list item has a child list, the text content of the outdented list item is added to the editor without being wrapped in the defaultTag
![screen shot 2017-01-11 at 1 36 22 pm](https://cloud.githubusercontent.com/assets/1800407/21859439/ff50fa1a-d802-11e6-94e0-5a96651a2cac.png)

##### Steps to reproduce the problem.
1. Create a list with 2 items
2. Indent the second item
3. Put your cursor at the start of the first item and outdent it (backspace)

##### OS.
Any

##### Browser.
Any

**Comment by stefanneculai** [comment]
It is fixed on master now.
