### ISSUE TITLE
Autosave removes br tags

### ISSUE THREAD

**Issue by mattiaslundberg** [froala/wysiwyg-editor#1696]
##### Expected behavior.
Autosave should save the html as is in the editor / textarea

##### Actual behavior.
Autosave removes br tags in some circumstances

##### Steps to reproduce the problem.

1. Open https://jsfiddle.net/cp9t0428/1/
2. Write something in the editor
3. In list of network requests find the request and notice that the br tag after Second is missing

##### OS.
macOS

##### Browser.
Chrome

**Comment by stefanneculai** [comment]
That is the intended behavior. The editor is designed to remove BR tags at the end of the block tags (e.g. DIV, P, H1, H2, etc.) when there is text inside that block tag.
