### ISSUE TITLE
Can't destroy froalaEditor when initialized on body

### ISSUE THREAD

**Issue by KarolMilewski** [froala/wysiwyg-editor#1697]
I'm trying to destroy Froala editor then I initialize on body element.
Always I have the same error
`Uncaught TypeError: Cannot read property 'trim' of undefined`
When I use some element and initialize froala its works fine. But I need initialize on body. This is bug or feature 💃

**Comment by stefanneculai** [comment]
There doesn't appear to be any problem from the editor: https://jsfiddle.net/froala/1otp8rdt/.
