### ISSUE TITLE
enlarge the image attachments 

### ISSUE THREAD

**Issue by ErdemAkin** [froala/wysiwyg-editor#1698]
##### Expected behavior.
we have attachment image in editor. we want to enlarge it after mouse click.

##### Actual behavior.
with mouse there is no action.

##### Steps to reproduce the problem.
1. add image to editor
2. save the message
3. read the message and image in editor
4. click the image
requirement : we want to represent the image with actual size.

##### OS.
windows 10
##### Browser.
chrome

customer information : Logo B.S.

**Comment by stefanneculai** [comment]
For tech support, please reach us via our website: https://www.froala.com/wysiwyg-editor/contact.
