### ISSUE TITLE
Applying inline styles with <span> tags with same selection creates multiple <span> tags instead of reusing

### ISSUE THREAD

**Issue by GMiLL5** [froala/wysiwyg-editor#1700]
##### Expected behavior.
When applying multiple inline styles to the same text, only one span tag should be added with all the inline styles

##### Actual behavior.
Multiple span tags are created, each one wrapping the existing <span>'s in the selection

##### Steps to reproduce the problem.
1. Select text
2. Change font size
3. Change text color

Note: This works with all buttons that change inline styles using <span> tags

##### OS.
OSX Yosemite 10.10.5

##### Browser.
Firefox 50.1.0
Chrome 55.0.2883.95

In `format.applyStyle` there's a check for the parent node being a span, and merging if that's the case - but in my testing the new span is added as the parent node of the existing span

**Comment by anthonyborell** [comment]
+1 Can confirm same issue. 
Depending on the hierarchy of spans, background color wont be 100% of the paragraphs height.

**Comment by GMiLL5** [comment]
@anthonyborell 

I fixed it locally with the following code in `applyStyle` after the check where it's looking up at the parent node to try to merge:
```
var tmp = editor.node.contents( $span.get( 0 ) );
var contents = [ ];

for ( var i = 0, len = tmp.length; i < len; i++ ) {
    if ( editor.node.hasClass( tmp[ i ], 'fr-marker' ) === false ) {
        contents.push( tmp[ i ])
    }
}

$span.get( 0 ).normalize( );
if ( contents.length === 1 && $( contents[ 0 ] ).is( 'span' ) === true ) {
    var $child = $( contents[ 0 ] );
    $child.css( prop, val );
    $span.replaceWith( tmp );
    $span = $child;
}
```

**Comment by moinism** [comment]
This is creating a lot of problems for us (we have a licensed version). We have large documents and now on some of them its creating a 2 sec lag in just scroll. Annoying for our clients.

![spans](https://cloud.githubusercontent.com/assets/2242528/22548285/94e629ae-e967-11e6-8a0a-7845a4527279.png)
