### ISSUE TITLE
inputs not working after edit off

### ISSUE THREAD

**Issue by johnstonmatt** [froala/wysiwyg-editor#1701]
##### Expected behavior.
When inline editor is off I can use an input normally

##### Actual behavior.
when inline editor is enabled but edit is off, the toolbar still shows up and I cant interact with the input

##### Steps to reproduce the problem.
enable inline editor, create an input tag using codeview (html) call edit.off, try to interact with input

##### OS.
MacOS

##### Browser.
Chrome

**Comment by stefanneculai** [comment]
@johnstonmatt please make sure that you are not including the forms plugin. The forms plugin is the one responsible for interacting with inputs.
