### ISSUE TITLE
 When you apply a style to Korean, the text disappears.

### ISSUE THREAD

**Issue by studiotemple** [froala/wysiwyg-editor#1702]
##### Expected behavior.
Text should not disappear randomly when entering text

##### Actual behavior.
Select the underline button and enter Korean.

##### Steps to reproduce the problem.
1. Press the Text Style button in the editor (No matter what text style button. ex: underline)
2. Enter Korean in the editor (the style selected in 1 applies)
3. Enter to change the line.
4. Continue to enter Korean (still the style you selected in 1)
5. Part of the text you are writing suddenly disappears. (Problems occur)

##### OS.
windows 10
windows 7

##### Browser.
chrome 55.0.2883.87 m (64-bit)

*Does not occur in 'Explorer 11'
*Does not occur on 'edge'
*Does not occur on 'firefox 50.1.0'

**Comment by hyeonsuleee** [comment]
I also experienced this also.
lease fix this bug..

**Comment by stefanneculai** [comment]
It is fixed on the current master.
