### ISSUE TITLE
When using editor in an iframe , dropdown menus not getting toggled and when select an option from dropdown previous options also shown as highlighted.

### ISSUE THREAD

**Issue by ravitejabommakanti** [froala/wysiwyg-editor#1703]
##### Expected behavior.
1) In Drop down menu, when the user selects an option previous selected option should become to default state.
2) At a time only single dropdown should be shown.

##### Actual behavior.
1) Drop down menus not getting toggled(Selected state and default state) and when the user selects an option from the dropdown, previously selected options also showing as highlighted.
2) Multiple dropdowns are getting opened at same time. 
##### Steps to reproduce the problem.
Load froala editor in an iframe and click on dropdowns, select options.

##### OS.
Mac OS Sierra version 10.12.2

##### Browser.
Google Chrome  55.0.2883.95

**Comment by ravitejabommakanti** [comment]
When using editor in an iframe , dropdown menus not getting toggled and when select an option from dropdown previous options also shown as highlighted.

https://jsfiddle.net/jrdys8zc/

**Comment by ravitejabommakanti** [comment]
May i know is there alternative to fix the issues ?

**Comment by stefanneculai** [comment]
It's already fixed on master.
