### ISSUE TITLE
The Emoticon function is not a single unit (contains an emoitcon and a space) leading to problematic functionality

### ISSUE THREAD

**Issue by tmpg** [froala/wysiwyg-editor#1704]
##### Expected behavior.
An emoticon should be a single unit

##### Actual behavior.
An emoticon is inserts a pseudo-space and the emoticon, not just an emoticon. Without a space, emoticons stack on each other.

##### Steps to reproduce the problem.
Go to froala.com and enter an emoticon, it will contain an emoticon and a space. Without the space (&nbsp), emoticons stack together.

##### OS.
All

##### Browser.
All

**Comment by FinesseRus** [comment]
There is no such bug on macOS

**Comment by tmpg** [comment]
Which OS and browser? I have tested on El Cap (latest Safari and Chrome) 

![image](https://cloud.githubusercontent.com/assets/7082248/22193667/e479b1ee-e10a-11e6-9983-7f5e981bf5d9.png)

**Comment by FinesseRus** [comment]
@tmpg the latest Sierra with the latest Safari, Chrome and Firefox. When I click an emoticon, one emoticon and spaces around are added. The emoticon itself is removed by one Backspace button click.

[Emoticon.mov.zip](https://github.com/froala/wysiwyg-editor/files/722768/Emoticon.mov.zip)

**Comment by tmpg** [comment]
Then I guess functionality is the problem here. An emoticon should be an emoticon, not an emoticon and a space. Without that space, it leads to problematic behavior such as above.

**Comment by stefanneculai** [comment]
I am adding some clarification here after we tested it. To reproduce this problem we should:
- insert an emoticon
- hit backspace
- insert a new emoticon
