### ISSUE TITLE
Line breaker plugin displays line breaker when editor is disabled

### ISSUE THREAD

**Issue by GMiLL5** [froala/wysiwyg-editor#1705]
##### Expected behavior.
Line breaker shouldn't display when editor is disabled

##### Actual behavior.
Line breaker displays when editor is disabled

##### Steps to reproduce the problem.
1. Include line breaker plugin
2. Disable the editor
3. Hover over an element that would show the line breaker

##### OS.
All

##### Browser.
All

**Comment by stefanneculai** [comment]
@GMiLL5 by disabled do you mean that you have called `edit.off` method?

**Comment by GMiLL5** [comment]
@stefanneculai Sorry, yes - and `edit.isDisabled( )` returns `true`
