### ISSUE TITLE
ENTER crashes IE11 on Win8.1phone

### ISSUE THREAD

**Issue by connect-technologies** [froala/wysiwyg-editor#1706]
##### Expected behavior.
add a new paragraph

##### Actual behavior.
crashes browser

##### Steps to reproduce the problem.
e.g. on https://www.froala.com/wysiwyg-editor go to the last char in the text and hit ENTER
-> crash

If i want to add a new paragraph in the text it just jumps to the last char in the editor.

On an empty editor -> ENTER -> crash

##### OS.
Win 8.1 phone / mobile

##### Browser.
IE 11

**Comment by stefanneculai** [comment]
For the moment we do not support Windows Phone officially. This is in our attention, however I am going to close it for now here.
