### ISSUE TITLE
video.js plugin fails to insert videos using the default Vimeo embed code

### ISSUE THREAD

**Issue by IvanTrendafilov** [froala/wysiwyg-editor#1707]
##### Expected behavior.

I go to a video and I copy the default embed code, video.js should be able to insert it.

##### Actual behavior.
video.js fails to insert the video.

##### Steps to reproduce the problem.
1. Go to vimeo.com, pick a video, copy the embed code, e.g.

```
<iframe src="https://player.vimeo.com/video/179806387" width="640" height="360" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
<p><a href="https://vimeo.com/179806387">TRACTION</a> from <a href="https://vimeo.com/roryuphold">Rory Uphold</a> on <a href="https://vimeo.com">Vimeo</a>.</p>
```

2. Paste it into Insert video -> Embed code.

3. Nothing happens.

If I manually remove the code outside of the `<iframe>`, it works. But, I shouldn't have to do that. Users will not know the insert fails because of it (no error message is given) and it is the default embed code for vimeo. The plugin should be able to handle this automatically.

##### OS.
MacOS Sierra

##### Browser.
Chrome 55

**Comment by stefanneculai** [comment]
There is a reg ex in place that is designed to filter what code is allowed to be embedded. If you want to allow other tags, then you could change the following like of code and include it just before initializing the editor:

```js
$.FroalaEditor.VIDEO_EMBED_REGEX = /^\W*((<iframe.*><\/iframe>)|(<embed.*>))\W*$/i;
```

**Comment by ncmancuso** [comment]
@stefanneculai We're having the same issue, and after reading your comments we've decided to implement your suggested change.

However, we'd love to see feedback for the user when invalid embedded code is inserted. This would be a huge UX improvement from the current functionality.

![videopluginexample](https://user-images.githubusercontent.com/6825718/30218917-6fc9dd9c-9488-11e7-8f07-50861c2b5379.gif)

**Comment by stefanneculai** [comment]
@ncmancuso thanks for the suggestion.
