### ISSUE TITLE
Unwanted <p> tags around <link ...> tags

### ISSUE THREAD

**Issue by daisylaflamme** [froala/wysiwyg-editor#1708]
##### Expected behavior.
In the code mode of Froala editor, I use few link tags to link to an external style sheet and fonts.  I expect on save or toggle between visual and code view to see the link tags on top without additional tags added.

##### Actual behavior.
I see <p> tags around the link tags. The <p> tags are not around each link tag but around the two of them:
<p>
	<link rel="stylesheet" type="text/css" href="...">&nbsp;
	<link href="..." type="text/css">
</p>
Also, it adds &nbsp;

##### Steps to reproduce the problem.
It was easy for me to reproduce here:
https://www.froala.com/wysiwyg-editor/examples/init-on-click
by just going to code mode of the editor, add the link tags on the top and then toggle between visual and code mode. The result is <p> tags around the <link> tags

##### OS.
My specific OS is Windows 10

##### Browser.
Last version of Chrome

**Comment by stefanneculai** [comment]
@daisylaflamme you can change the `enter` option to `$.FroalaEditor.ENTER_BR` in order to avoid this problem.

**Comment by daisylaflamme** [comment]
Thank you for the suggestion! I also want to share another solution:
htmlDoNotWrapTags: ['script', 'style', 'link', 'a']
This prevents auto <p> tags around <link> and <a> tags
