### ISSUE TITLE
Can't paste on Safari after configuring br

### ISSUE THREAD

**Issue by Tom29** [froala/wysiwyg-editor#1711]
##### Expected behavior.
Paste normally on Safari

##### Actual behavior.
Couldn't paste on Safari with rich text

##### Steps to reproduce the problem.
Config the froala with this line: `enter: $.FroalaEditor.ENTER_BR,`
Copy any text from the web that contains image, new line, marked up text ...
Paste on the editor

##### OS.
Mac Sierra

##### Browser.
Safari 10.0.2

**Comment by stefanneculai** [comment]
It's fixed on master.
