### ISSUE TITLE
Scrolling on the image inside froala editor does not work on mobile

### ISSUE THREAD

**Issue by kmkanagaraj** [froala/wysiwyg-editor#1712]
##### Expected behavior.
When there are images inside froala editor, touch + scroll on top of the images should work.

##### Actual behavior.
Scroll is not happening when it's done on top of an image on mobile

##### Steps to reproduce the problem.
Codepen example - http://codepen.io/kmkanagaraj/full/xgLdMz/
Please open this on a mobile device.

##### OS.
Android

##### Browser.
Chrome 55

**Comment by kmkanagaraj** [comment]
Issue persists in the recent version(2.4.1) - http://codepen.io/kmkanagaraj/full/RKLpYZ/

Please open it on a mobile device and try scrolling on top of the image.

**Comment by tk5641** [comment]
+1

**Comment by nazonohito51** [comment]
+1
