### ISSUE TITLE
Replacing auto br tags in block elements with &nbsp;

### ISSUE THREAD

**Issue by daisylaflamme** [froala/wysiwyg-editor#1713]
##### Expected behavior.
 I expect non breaking space instead of br tag between empty p or div tags. The non breaking space is more friendly and will not break the client's layouts by adding additional line and space as the br tag.

##### Actual behavior.
Our customers often use empty div tags where they inject some dynamic content. The br tag is auto placed in the empty div tag. I know that the empty div tag will disappear if it is completely empty.

##### Steps to reproduce the problem.
In the Froala editor add an empty div tag, a div tag with br and a div tag with non breaking space.
 For web pages with complex layouts, the last is very desired.

##### OS.
Windows 10, Chrome last version

**Comment by stefanneculai** [comment]
Thanks for the feedback! However, one of the core things we're designing the editor on is "a true WYSIWYG". This is the reason why if someone sees an empty line while editing that line should be kept when the HTML is saved as well.

**Comment by sahilkumar1012** [comment]
how to replace <br> tags with <p>&nbsp;</p>

**Comment by sahilkumar1012** [comment]
`how to replace \<br\>  tag with &nbsp;`
