### ISSUE TITLE
Enable Travis CI for the ember-froala-editor repo

### ISSUE THREAD

**Issue by Panman8201** [froala/wysiwyg-editor#1714]
Sorry, not sure how to get more attention for my [issue over on the `ember-froala-editor` repo](https://github.com/froala/ember-froala-editor/issues/23). But I'm unable to do this myself since I cannot access the repo Settings tab. Hoping someone with full froala org access can help here. Thanks!

**Comment by stefanneculai** [comment]
Done. Thanks @Panman8201 !
