### ISSUE TITLE
Link Style

### ISSUE THREAD

**Issue by ChinesePeanuts** [froala/wysiwyg-editor#1717]
Hi !
Here's my problem

##### Expected behavior.
When having a link with multiple words, changing the color of one word should work normally.

##### Actual behavior.
When changing the color of a word in a link, the link can split, creating multiple `<a>` tag and the color doesn't apply. It will also happen when you want to color only a part of a word, splitting the word in two tags.

I've noticed that if you write a text, color it, then set it as a link, this problem won't occur.

##### Steps to reproduce the problem.
Create a link from the toolbar with at least two words and try to color one of them, or a part, multiple times.

##### OS.
Linux/Debian Jessie

##### Browser.
Firefox 50.1.0

**Comment by stefanneculai** [comment]
@ChinesePeanuts Please make sure you're using the latest 2.4.1 version. We cannot replicate it there.
