### ISSUE TITLE
How to simulate editor input for integration testing?

### ISSUE THREAD

**Issue by Panman8201** [froala/wysiwyg-editor#1718]
I'm building out tests for `ember-froala-editor` and struggling with simulating input (such as typing in "a"). I've tried triggering a jQuery event on the inner most block without any luck. The code runs without error but the editor never updates to show what I typed. So what is the proper way to simulate editor input for testing reasons?

```
$('div.fr-element.fr-view p').trigger({ type:'keyup', which:'a'.charCodeAt(0) });
```

**Comment by stefanneculai** [comment]
@Panman8201 Unfortunately, it's not possible to do a trigger for that. There are some libs which simulate typing inside inputs, however they produce unexpected outputs and you won't get something consistent.

**Comment by Panman8201** [comment]
@stefanneculai Humm... since I'm using the `<div contenteditable>` version, if I change the inner html of `.fr-element.fr-view` and then `$('#editor').froalaEditor('events.trigger', 'contentChanged');`, would you expect a `$('#editor').froalaEditor('html.get');` from within the `contentChanged` event handler to return my new inner html that I set just before?

**Comment by stefanneculai** [comment]
Yes, that should work. You can use the following to easily set some HTML: `$('#editor').data('froala.editor').$el.html('your_html');`.

**Comment by hariharasuthan-balaji** [comment]
How can I achieve the same for v3 ?
