### ISSUE TITLE
Form label in popups hides popup dropdown option

### ISSUE THREAD

**Issue by moinism** [froala/wysiwyg-editor#1722]
##### Expected behavior.
The dropdown options in a popup should be visible for click

##### Actual behavior.
Dropdowns are hidden due to labels of form in that popup.

##### Steps to reproduce the problem.
[Go over to demo](https://www.froala.com/wysiwyg-editor) on main site and click any icon that would trigger a popup, e.g. 'Link'. Now in that popup click the 'spyglass' icon to show the dropdown.
![example](https://cloud.githubusercontent.com/assets/2242528/22417839/11f341ba-e6f8-11e6-8ec3-48c594366ac0.PNG)

##### OS.
Windows 10. Mac 10.12.2

##### Browser.
Chrome 55

**Comment by stefanneculai** [comment]
It is fixed on the current master.
