### ISSUE TITLE
More flexible pricing

### ISSUE THREAD

**Issue by monolithed** [froala/wysiwyg-editor#1724]
Have you got any plans to provide more flexible pricing for small teams and startups? 
I mean SaaS is the most popular kind of IT business and probably there is a reason to meet some halfway for such companies... 
I don't want to use your work without any payment, of course, but maybe you have any ideas how to reduce the cost of your product. $200 is ok, but $800 for small teams is a very expensive purchase.   It would be economically feasible for you as well.

Thanks for your work.

**Comment by stefanneculai** [comment]
Thanks for the suggestion, @monolithed.
