### ISSUE TITLE
Froala text editor image upload Image cannot be loaded from the passed link

### ISSUE THREAD

**Issue by finfon** [froala/wysiwyg-editor#1728]
First of all the Froala editor is the best I found, I really like the upload concept and the editor at all.

My question is:
The Froala editor image upload works like this, the client has to upload file to the server and the server needs to send back to the client the image path in the server.

I'm using c# web api and the request is reached to the server, after I save the image in the server I have to return a link to the server in the next JSON format:

{ "link": "path/to/image.jpg" }
I tried to do this in a lot of ways but none of them work for me:

public IHtttActionResult imageUpload()
{
    //Saving the image in the path C:/images/image.jpg.
    string imagePath = "C:/images/image.jpg"; //I tried also with backslashes
    return Json(new {link = imagePath});
    //or
    retrun Ok(new {link = imagePath});
    //or
    return Json("{\"link\": \"" + imagePath + "\"}");
    //or 
    return Ok("{\"link\": \"" + imagePath + "\"}");
    //or (after I set the return statement to string)
    return "{\"link\": \"" + imagePath + "\"}";
}
The Froala editor returns an error:

Image cannot be loaded from the passed link
The error appears although the image is exist in the path. How can I pass the link properly?

**Comment by finfon** [comment]
I solved that by replaceing the image path the the project directory, sorry for this question.

**Comment by clubbavi** [comment]
Hi @finfon ... I am facing the same issue. Could you please elaborate your answer?
