### ISSUE TITLE
incorrect popup position on sticky toolbar chrome v.56

### ISSUE THREAD

**Issue by 440459012** [froala/wysiwyg-editor#1729]
##### Expected behavior.
![2017-02-01_15-29-18](https://cloud.githubusercontent.com/assets/8831983/22508638/86c4d584-e893-11e6-97f1-d6d0d86c9b2b.png)

##### Actual behavior.
![2017-02-01_15-29-34](https://cloud.githubusercontent.com/assets/8831983/22508645/8e758a1c-e893-11e6-88c3-07754de56068.png)
in firefox is allright

##### Steps to reproduce the problem.
scroll page down with sticky toolbar, must close and reopen popup to change it position
![2017-02-01_15-29-48](https://cloud.githubusercontent.com/assets/8831983/22508660/a1963808-e893-11e6-9e53-13096d6014a5.png)

##### OS.
MacOSX

##### Browser.
Google Chrome Version 56.0.2924.76 (64-bit)

**Comment by steefaan** [comment]
I have exactly the same issue. It's independent of the OS, I have tested it on MAC and Windows. This error only occurs in chrome version 56, with chrome version 55 everything works fine.

**Comment by steefaan** [comment]
@stefanneculai Could you tag a new release?

**Comment by stefanneculai** [comment]
It will come in the following hours.

**Comment by 440459012** [comment]
@stefanneculai , from where i can download the new release, with this bug fixed?

**Comment by stefanneculai** [comment]
You can download it from Github for now and shortly it will be available on our website too.

**Comment by 440459012** [comment]
i have bought a license from you, and want to download source files, non-minified

**Comment by stefanneculai** [comment]
@440459012 They will be available inside your account as soon as we make the official release in couple of hours.

**Comment by 440459012** [comment]
ok, thanks
