### ISSUE TITLE
Pasting into empty nested list item deletes list item and doesn't paste

### ISSUE THREAD

**Issue by GMiLL5** [froala/wysiwyg-editor#1730]
##### Expected behavior.
Pasting into empty nested list item should paste content

##### Actual behavior.
Pasting into empty nested list item removes list item and doesn't paste content

##### Steps to reproduce the problem.
1. Create list, add content
2. Press enter, tab to create nested item
3. Select content to paste
4. Paste into nested item

![pasting into nested list](https://cloud.githubusercontent.com/assets/1800407/22511060/b268c976-e86a-11e6-855f-97c468e4c015.gif)

##### OS.
OSX 10.10.5

##### Browser.
Firefox 51.0.1
Chrome 55.0.2883.95
Safari 10.0.3

**Comment by stefanneculai** [comment]
It's fixed on master.
