### ISSUE TITLE
Click on Image Upload does not work (Safari Only)

### ISSUE THREAD

**Issue by joeworkman** [froala/wysiwyg-editor#1733]
##### Expected behavior.
On Safari Mac, I would expect that the open file dialog would open from the browser when you click on the Image upload area. The label even says that you can click. 

##### Actual behavior.

The popup closes instead of the expected behavior. You can only drag and drop an image. 

##### Steps to reproduce the problem.

Go to https://www.froala.com/wysiwyg-editor click on the Image toolbar item. Click on the box and the popup just closes. 

##### OS.

Mac 10.12.3

##### Browser.

Safari 10.0.3

**Comment by stefanneculai** [comment]
It is fixed on the current master.
