### ISSUE TITLE
Link make underline space

### ISSUE THREAD

**Issue by KarolMilewski** [froala/wysiwyg-editor#1736]
Have froblem with froala and links render.

Example:
I use this code on your website

```
<p><a href="#">&nbsp;<img alt="" src="https://lh6.ggpht.com/af_jg6G97R6eAVGWXMFDCvwObk4bFMg-ScL0eZWpOEBBMgsAQk65BN44w-A9jljT5yn0LVDzaV3Tl-8Bwr-c5Cgn4Q=s0" border="0" width="198" class="fr-fic fr-dib"></a>
	<a href="#">&nbsp;<img alt="" src="https://lh6.ggpht.com/af_jg6G97R6eAVGWXMFDCvwObk4bFMg-ScL0eZWpOEBBMgsAQk65BN44w-A9jljT5yn0LVDzaV3Tl-8Bwr-c5Cgn4Q=s0" border="0" width="198" class="fr-fic fr-dib"></a>
	<a href="#">&nbsp;<img alt="" src="https://lh6.ggpht.com/af_jg6G97R6eAVGWXMFDCvwObk4bFMg-ScL0eZWpOEBBMgsAQk65BN44w-A9jljT5yn0LVDzaV3Tl-8Bwr-c5Cgn4Q=s0" border="0" width="198" class="fr-fic fr-dib"></a></p>

<p>qwe qwe qwe qwe</p>
```

Result:
![froala1](https://cloud.githubusercontent.com/assets/11610485/22589802/720cea4e-ea0c-11e6-9286-5b489b159cc7.png)

On the left site all time I get the blue underline like &nbsp;
You dont see on yours website becouse in the css have a{ text-decoration: none }

I use froala to render email template and I have all time the same problem.

**Comment by stefanneculai** [comment]
@KarolMilewski you could add a CSS rule like this: 
```css
.fr-view a {
  text-decoration: none;
}
```

**Comment by KarolMilewski** [comment]
@stefanneculai this solution not working for me.
This trick works fine if you display content in froala editor, but if I all the content send via mail don't work.
In froala editor:
![screenshot 4](https://cloud.githubusercontent.com/assets/11610485/22778385/0329e71c-eeb7-11e6-8c9e-b27bee0f252e.png)
and when I send this content on my email:
![screenshot 3](https://cloud.githubusercontent.com/assets/11610485/22778394/113a8c4e-eeb7-11e6-8be2-d0eed9d88993.png)

I add this rule on froala_style.css and froala_editor.css

**Comment by stefanneculai** [comment]
Are you using `useClasses: false`? Also, that line might appear from the following: http://stackoverflow.com/questions/814366/how-can-i-remove-the-outline-around-hyperlinks-images.

**Comment by KarolMilewski** [comment]
Yes, have useClasses: false

>var froalaSettings = {
    toolbarInline: true,
    useClasses: false,
    ...

**Comment by stefanneculai** [comment]
See http://stackoverflow.com/questions/814366/how-can-i-remove-the-outline-around-hyperlinks-images. Most likely that is causing the underline.

**Comment by KarolMilewski** [comment]
Maybe this is all correct and the problem is not witch <a> text-decoration: underline
If the code look like this, froala add on the space &nbsp; and I have white space (<a href="">&nbsp;<img /></a>) and this is not correctly.
>
    <a href="">
        <img />
    </a>

but if enter code inline, this "_" don't show in froala and email.
>
    <a href=""><img/></a>

**Comment by stefanneculai** [comment]
This looks like a config problem and not a bug. Please contact us via support if you have a license that includes tech support for more help.
