### ISSUE TITLE
Image toolbar not always visible on fixed height editor

### ISSUE THREAD

**Issue by markedmondson** [froala/wysiwyg-editor#1737]
##### Expected behavior.
(Describe expected behaviour here)
Using a fixed height editor, when I insert or select an image I expect the image toolbar to be visible.

##### Actual behavior.
(Describe actual behaviour here)
Using a fixed height editor, if the inserted is larger or selected image is towards the end of the visible content, the image toolbar is hidden.

##### Steps to reproduce the problem.
(Describe the steps to reproduce the problem here)
Using a fixed height editor, adding an image and clicking it so the image toolbar appears, scrolling down so the toolbar it outside the viewable area hides the toolbar. 

This is particularly tricky for users if they drag and drop a large image and expect to be able to interact with the options but they're initially hidden off screen.

![froala](https://cloud.githubusercontent.com/assets/1653699/22610792/1d59159e-ea1c-11e6-9564-f2bfe266d6a0.gif)

This may be a dup of #1145 but I wonder if the toolbar shouldn't adapt to the view as opposed to hard-coding its position, alternatively an event hook on select image would allow us to scroll the image into view.

##### OS.
(OS name and version here)
OSX Sierra

##### Browser.
(Browser name an version here)
Chrome 55

**Comment by stefanneculai** [comment]
We consider this as being the correct behavior. It should disappear because is under the image and the image passes the bottom of the editor.
