### ISSUE TITLE
List button become unselected when removing bold

### ISSUE THREAD

**Issue by JSteunou** [froala/wysiwyg-editor#1740]
On a list with all in bold and all selected (like ctrl+a)

##### Expected behavior.

removing bold should only unselect bold button

##### Actual behavior.

removing bold unselect list button along

##### Steps to reproduce the problem.

Write a list, several lines, ctrl+a, hit bold, hit bold again
List button become unselected *but* become selected again when you click inside the wysiwyg to remove the selection of all the text.

##### OS.

 ubuntu

##### Browser.

Chrome

**Comment by stefanneculai** [comment]
@JSteunou could you please make a recording?

**Comment by JSteunou** [comment]
I just select all with ctrl+a

![froala_1740](https://cloud.githubusercontent.com/assets/2323127/22888219/35b740a2-f205-11e6-9e87-5688feca4184.gif)

At the end I just click inside the list and the button appeared selected again
