### ISSUE TITLE
Label z-index positioning overlaps menu items in dropdown for insert link

### ISSUE THREAD

**Issue by daniellevautier** [froala/wysiwyg-editor#1741]
##### Expected behavior.
When clicking on insert link > choose link I would expect to see the menu items

##### Actual behavior.
When clicking on insert link > choose link The label URL overlaps the item

##### Steps to reproduce the problem.
Go to insert link > Choose link 
https://cl.ly/041l371a083C

##### OS.
Windows 10

##### Browser.
Chrome (latest)

**Comment by stefanneculai** [comment]
It's already fixed here on the master branch.
