### ISSUE TITLE
destroyEditor while in fullscreen mode does not remove z-index: 9990 from ancestors

### ISSUE THREAD

**Issue by sjoerdvisscher** [froala/wysiwyg-editor#1744]
When enabling fullscreen mode, Froala sets `z-index: 9990` on all ancestor elements to be sure it is always on top. But when destroyEditor is called (because componentWillUnmount is called in my case in React) and the editor was still in fullscreen mode, Froala does not clear all these z-index properties.

I was able to work around the issue by calling `fullscreen.toggle` in componentWillUnmount when fullscreen is active.

**Comment by stefanneculai** [comment]
It's fixed on master.
