### ISSUE TITLE
doNotJoinTags

### ISSUE THREAD

**Issue by selfagency** [froala/wysiwyg-editor#1745]
i see that doNotJoinTags was removed in froala 2.0 because it is 'no longer required.' well, i require it because i don't see any other way to specify an option to not merge tags automatically. this functionality presently makes embedding objects like tweets and instagram images impossible. 

i have a paid license.

##### Expected behavior.
to not have tags automatically merged

##### Actual behavior.
tags are automatically merged

##### Steps to reproduce the problem.
post two blockquotes (twitter embeds) in a row

##### OS.
mac os 10.12

##### Browser.
chrome whatever is latest

**Comment by stefanneculai** [comment]
If you don't want to have them joined together, you could put them a different ID and the editor will keep them separate.
