### ISSUE TITLE
Using <br> line break mode, extra line breaks remove when changing other text to Header

### ISSUE THREAD

**Issue by alassiter** [froala/wysiwyg-editor#1746]
I'm using the 2.4.2 release in react.

##### Expected behavior.
If I set the editor to use `<br>` instead of `<p>` with new lines, and I happen to want extra space for a new section, I expect that those empty lines will remain.

```
Item 1

Item 2
```

##### Actual behavior.
If I create Item 1 and 2, then later in the text, change some text to be a Heading, the empty <br> line disappears.

```
Item 1
Item 2

Heading
```

##### OS.
Mac OS 10.11.6

##### Browser.
Chrome 56.0.2924.87 (64-bit)

##### Animated Gif Example
https://cl.ly/020N181t1w1H/Screen%20Recording%202017-02-08%20at%2009.19%20AM.gif

**Comment by stefanneculai** [comment]
You're not using V2.4.2 for the editor most likely because this problem cannot be reproduced here: https://www.froala.com/wysiwyg-editor/examples/enter.
