### ISSUE TITLE
Tabbing into uninitialised editor resets cursor to position 0 after a second or two

### ISSUE THREAD

**Issue by will-newmarch** [froala/wysiwyg-editor#1747]
##### Expected behavior.
Starting to type fairly quickly after tabbing into an instance of the editor should not affect cursor position.
 
##### Actual behavior.
When tabbing into editor before it has initialised (on focus or click) then quickly typing, the cursor resets to the beginning of the input, on what looks like the initialisation of the editor. 

##### Steps to reproduce the problem.
Tab from somewhere such as another input, into an instance of the editor that initialises on focus and type something quickly. The cursor will reset to the beginning of the input after a second or two.

##### OS.
MacOS Sierra 10.12.3

##### Browser.
Chrome Version 55.0.2883.95 (64-bit)

**Comment by stefanneculai** [comment]
@will-newmarch could you please make a jsFiddle?

**Comment by will-newmarch** [comment]
@stefanneculai after some messing this seems to be related to another issue, sorry!
