### ISSUE TITLE
Drag and Drop image adds does not upload image

### ISSUE THREAD

**Issue by mrjlynch** [froala/wysiwyg-editor#1748]
##### Expected behavior.
When images are dragged and dropped into the editor, they should be uploaded for sustainability, rather than adding the image path. 

##### Actual behavior.
![ezgif com-video-to-gif 1](https://cloud.githubusercontent.com/assets/3665457/22784108/7301bbe2-ef1a-11e6-82ed-71d1b4f8528e.gif)

**Comment by stefanneculai** [comment]
The image is insert as link and in this case it shouldn't be uploaded. We consider the current behavior as being the correct one.

**Comment by mrjlynch** [comment]
I would consider that the behaviour is correct if it is dragged and dropped from within another or the same froala editor. But if it is dragged from outside the editor (eg. from a different tab) then adding the link is unstable. Would you agree?

**Comment by stefanneculai** [comment]
Dragging it there is like inserting the image via URL or pasting it and it should not be uploaded.

**Comment by mrjlynch** [comment]
Well I can speak for my users that this has been an issue. They drag things in from other sources (eg. Facebook) and the facebook links do not work for other people (privacy reasons). 

If they are uploaded no matter where the image comes from, we are protected right?

**Comment by stefanneculai** [comment]
I understand that it might not work for all cases, but images dropped this way cannot always be uploaded. If they are private or from a different domain, the browsers do not allow to access them for being uploaded.

**Comment by mrjlynch** [comment]
Sorry to be persistent @stefanneculai but google docs is able to handle this over drag and drop.

**Comment by stefanneculai** [comment]
Google Docs has their built-in rendering engine which might make such things possible.

**Comment by mrjlynch** [comment]
Thanks @stefanneculai, I guess this isn't possible then 😕
