### ISSUE TITLE
Text color change not visible with text highlighted

### ISSUE THREAD

**Issue by mrjlynch** [froala/wysiwyg-editor#1749]
Is there any way around this? 
![ezgif com-video-to-gif 2](https://cloud.githubusercontent.com/assets/3665457/22785341/a0d1d7dc-ef1f-11e6-9096-7a898d523a27.gif)

**Comment by stefanneculai** [comment]
There is a CSS rule that you could remove:

```css
.fr-wrapper ::selection 
```
