### ISSUE TITLE
Special Characters demo

### ISSUE THREAD

**Issue by danielgranat** [froala/wysiwyg-editor#1751]
The recent addition of Special Characters plugin sounds like something I need, but I can't get it to work.
Is there a Demo to see it in action?

**Comment by stefanneculai** [comment]
Please find it in action here: https://www.froala.com/wysiwyg-editor/examples/full-featured

**Comment by danielgranat** [comment]
@stefanneculai thanks. I found my problem. The special_characters plugin file isn't pulled by bower, because it's not in froala bower file.

**Comment by stefanneculai** [comment]
Oh, we should update it.

**Comment by danielgranat** [comment]
#1773 
:)

**Comment by danielgranat** [comment]
I still have one more issue with this. I see that the specialCharacters command definition is for 'help' plugin

``` javascript
    modal: true,
    callback: function () {
      this.specialCharacters.show();
    },
    plugin: 'help',
```

Shouldn't it be?
``` javascript
    modal: true,
    callback: function () {
      this.specialCharacters.show();
    },
    plugin: 'specialCharacters',
```

**Comment by danielgranat** [comment]
Thanks, @stefanneculai!
Can you please confirm the above issue with the plugin name as well?
