### ISSUE TITLE
A typo: strikethrough -> strikeThrough

### ISSUE THREAD

**Issue by monolithed** [froala/wysiwyg-editor#1752]
##### Expected behavior.
strikeThrough

##### Actual behavior.
strikethrough

##### Steps to reproduce the problem.
https://www.froala.com/wysiwyg-editor/examples/toolbar-buttons

PS: could you please add the link where the toolbar specifiers are located? I don't like to use Web Inspector to know that.

**Comment by stefanneculai** [comment]
@monolithed what do you mean by "toolbar specifiers"?

**Comment by monolithed** [comment]
> what do you mean by "toolbar specifiers"?

I meant these specifiers:

```
toolbarButtons: [
	'paragraphFormat',
	'bold',
	'italic',
	'underline',
	'strikeThrough',
	'color',
	'emoticons',
	'quote',
	'align',
	'formatOL',
	'formatUL',
	'insertLink',
	'insertImage',
	'insertVideo',
	'insertFile',
	'clearFormatting',
	'insertTable',
	'fullscreen',
	'html',
	'help',
       .... 
]
```

**Comment by stefanneculai** [comment]
If you click on the toolbarButton it will get you to the docs where all the options are: https://www.froala.com/wysiwyg-editor/docs/options#toolbarButtons

**Comment by monolithed** [comment]
Oh, I got it, thanks! There were no so obvious for me :)
