### ISSUE TITLE
Could not change language

### ISSUE THREAD

**Issue by monolithed** [froala/wysiwyg-editor#1753]
##### Example

```jsx
<Editor config={ { language: 'ru' } } />
```

Also, I've already tried:

```jsx
<Editor language='ru' />
```

##### OS.
macOS, Chrome

Maybe is a `react-froala-wysiwyg` issue, I don't know.

**Comment by stefanneculai** [comment]
Please make sure you have included the language file. If you still have problems please [reach tech support](https://www.froala.com/wysiwyg-editor/contact) if you own an Advanced/OEM license.

**Comment by monolithed** [comment]
@stefanneculai, is there any documentation? The page https://www.froala.com/wysiwyg-editor/languages does not answer to my question.

**Comment by stefanneculai** [comment]
You should include the language translation file as it explains on the link you sent as well:
```html
<!-- Include the language file. -->
<script src='../langs/es.js'></script>
```

**Comment by monolithed** [comment]
Got it, thanks. It would be nice to include the following link https://github.com/froala/wysiwyg-editor/tree/master/js/languages though.
