### ISSUE TITLE
Not possible to add links to Windows file server

### ISSUE THREAD

**Issue by retoheusser** [froala/wysiwyg-editor#1754]
##### Expected behavior.
Inserting a link to a file on a Windows file server (`\\drive\path\file.txt`) into the WYSIWYG editor should properly link the file and set the `href` attribute to the specified url.

##### Actual behavior.
Inserting a link to a file on a Windows file server (`\\drive\path\file.txt`) into the WYSIWYG editor sets the `href` attribute to an empty string (`""`).
![screen shot 2017-02-13 at 17 01 06](https://cloud.githubusercontent.com/assets/13115462/22890948/12148bf6-f20e-11e6-9318-7d9146d45b54.png)
![screen shot 2017-02-13 at 17 01 18](https://cloud.githubusercontent.com/assets/13115462/22890954/16106810-f20e-11e6-9948-4d8da619959a.png)

##### Steps to reproduce the problem.
Paste the link into the WYSIWYG editor, select it, click "Insert Link" and add the same link as the URL. The linked text looks like a link. Go to HTML edit mode and look at the `href`-attribute of the link. It is an empty string (`""`).
##### OS.
OS X & Windows 10, 8.1, 8, 7

##### Browser.
Tested on Chrome and IE11 & IE10

**Comment by stefanneculai** [comment]
Please see: https://github.com/froala/wysiwyg-editor/issues/1235#issuecomment-251943999.

**Comment by retoheusser** [comment]
@stefanneculai thank you
