### ISSUE TITLE
add non-breaking space 

### ISSUE THREAD

**Issue by electroheadfx** [froala/wysiwyg-editor#1755]
##### Expected behavior.
I want add non-breaking space from editor with a button

##### Actual behavior.
It doesn't create the HTML non-breaking space and replace with a regular space, 
when I add from editor code, the space is breaking in text 

##### Steps to reproduce the problem.
Create a text with breaking space and try to add non-breaking space from froala code or code with a button (add HTML)

##### OS.
OSX 10.11.6 

##### Browser.
Safari 10.0.3

**Comment by stefanneculai** [comment]
It is possible to do that only if you are using a `<span style="white-space: nowrap;"> </span>` for those spaces that you want to stay together. Other way, the editor will alternate them with regular spaces to improve typing.
