### ISSUE TITLE
Orthography in RU locale

### ISSUE THREAD

**Issue by monolithed** [froala/wysiwyg-editor#1757]
##### Expected behavior.

* Colors: цвета -> Цвета
* Grimacing face: Гримасничая лицо  -> Гримаса на лице
* Grinning face: Grinning face -> Ухмылка на лице
* Astonished face: Удивленный лицо -> Удивленное лицо
* Confused face: Путать лицо -> Смущенное лицо
* Crying face: Плач лицо -> Плачущее лицо
* Confounded face: Да постыдятся лицо -> Постыдное лицо
* Disappointed but relieved face: Разочарованное, но спокойное лицо
* Disappointed face: Разочарованный лицо -> Разочарованное лицо
* Expressionless face : невыразительные лица -> Невыразительное лицо
* Face savoring delicious food : Лицо смакуя вкусную еду -> Лицо смакующее вкусную еду
* Face screaming in fear : Лицо кричать в страхе -> Лицо кричащее от страха
* Face throwing a kiss : Лицо бросали поцелуй -> Лицо отправляющее поцелуй
* Face with cold sweat : Лицо с холодного пота -> Лицо в холодном поту
* Face with open mouth and cold sweat : Лицо с открытым ртом и холодный пот -> Лицо с открытым ртом в холодном поту
* Face with stuck out tongue : Лицо с торчали языка -> Лицо с торчащим языком
* Face with stuck out tongue and tightly-closed eyes : Лицо с торчали язык и плотно закрытыми глазами -> Лицо с торчащим языком и плотно закрытыми глазами
* Face with stuck out tongue and winking eye: Лицо с торчали язык и подмигивая глазом -> Лицо с торчащим языком и подмигивающим глазом
* Fearful face : Опасаясь лицо -> Напуганное лицо
* Flushed face : "Прилив крови к лицу" -> Покрасневшее лицо
* Frowning face with open mouth : Нахмурившись лицо с открытым ртом -> Нахмуренное лицо с открытым ртом
* Grinning face with smiling eyes : Усмехнувшись лицо с улыбающимися глазами -> Усмехнувшееся лицо с улыбающимися глазами
* Hushed face : Затихший лицо -> Утихомиренное лицо
* Kissing face : Поцелуи лицо -> Целующееся лицо
цитата -> Цитата
* Back: назад -> Назад
* Help: Help -> Помощь 

You had better consult native speakers about other languages 😧

**Comment by stefanneculai** [comment]
@monolithed Thank you for this!
