### ISSUE TITLE
jquery Ui Sortable and froala Editor use not working

### ISSUE THREAD

**Issue by tteongi** [froala/wysiwyg-editor#1758]
##### Expected behavior.
(Describe expected behaviour here)

##### Actual behavior.
jquery Ui Sortable and froala Editor use not working

Ck Editor resolved in 2014.
Is it patchable?

I want you to handle it.

##### Steps to reproduce the problem.
(Describe the steps to reproduce the problem here)

##### OS.
(OS name and version here)

##### Browser.
(Browser name an version here)

**Comment by stefanneculai** [comment]
jQuery sortable requires to have `text-selection: none` on the element that is being dragged, while the editor needs `text-selection: auto`. To integrate jQuery Sortable with Froala Editor, you can use a handler to move the elements that contain the editor.
