### ISSUE TITLE
Font Size selection not working in IE10, IE11 and Edge browsers

### ISSUE THREAD

**Issue by binod12** [froala/wysiwyg-editor#1759]
##### Expected behavior.
The font size should be hidden after selecting the font size

##### Actual behavior.
The font size pop up does not hide after selection, it shows a blank popup.

##### Steps to reproduce the problem.
1)Open font size change dropdown by clicking on it.
2) Apply any font size
3) It should close, after applying
![image](https://cloud.githubusercontent.com/assets/6301387/22968234/9faa449c-f38f-11e6-9217-8454167c4dc9.png)

##### OS.
Windows 10

##### Browser.
IE10, IE11 and Edge

**Comment by stefanneculai** [comment]
@binod12 are you able to reproduce that on our website?

**Comment by binod12** [comment]
Unfortunately, we are not able to reproduce on your website, but do you have any recommendation for such a case.

**Comment by stefanneculai** [comment]
Unfortunately, not. For tech support, please reach us via our website.

**Comment by binod12** [comment]
There is some issue while the font size selection requires scroll bar to be generated. When I put the font size fontSize: ['10', '11', '12', '14', '18', '24', '30', '36'], i.e. 8 font-sizes, which does not require the scroll bar, it works perfectly.
