### ISSUE TITLE
Image Upload broken in Safari

### ISSUE THREAD

**Issue by cshehadi** [froala/wysiwyg-editor#1763]
##### Expected behavior.
User should be able to click in the "Drop Image (or click)" area and get a file picker dialog

##### Actual behavior.
You click, but file picker dialog never appears (Safari only)

##### Steps to reproduce the problem.
In Safari, on your demo page: https://www.froala.com/wysiwyg-editor, click on image upload icon, dialogue will open, click "Drop Image (or click)" and dialogue disappears, but file picker does not appear.  If I try this in Chrome it works fine.

##### OS.
Mac OS 10.11.6

##### Browser.
Safari 10.0.3

Thanks!

**Comment by stefanneculai** [comment]
It was fixed on master few days ago.
