### ISSUE TITLE
Losing paragraph format on a list after removing list

### ISSUE THREAD

**Issue by JSteunou** [froala/wysiwyg-editor#1765]
##### Expected behavior.

if I have a list and I set a paragraph style (like a color) on a list item and then remove the list format on this item I expect the item to keep the color

##### Actual behavior.

The list item lose the color when I remove the list format

##### Steps to reproduce the problem.

Write a *list*, apply the list format, cursor on a list item, apply a paragraph style (like grey), remove the list format.

**Comment by stefanneculai** [comment]
@JSteunou Could you please provide few more details? We cannot reproduce it.

**Comment by JSteunou** [comment]
If you follow exactly what I said you will reproduce it.

* got to https://www.froala.com/wysiwyg-editor
* click inside the editor
* ctrl+a
* del
* click on list button
* write a line
* hit enter
* write a second line
* hit enter
* write a third line
* click on paragraph format / gray
* click on list button

The 3rd paragraph is now not a list but also not gray
