### ISSUE TITLE
Set default font-family with paste

### ISSUE THREAD

**Issue by mrjlynch** [froala/wysiwyg-editor#1766]
##### Expected behavior.
I note that pasting is recently significantly improved in Froala and I welcome these changes. 

However, for my users and I there are some convenient features of the former "plainer" paste. For instance, there was consistency with font family. Is there any chance a default `font-family` could be applied for pasting?

**Comment by stefanneculai** [comment]
If you want to do that, the best way would be to use the paste.beforeCleanup event and make the changes you need on the HTML.
