### ISSUE TITLE
I can't upload videos by url

### ISSUE THREAD

**Issue by davidtorroija** [froala/wysiwyg-editor#1768]
Expected behavior.

The video plugin inserts a video from: http://vjs.zencdn.net/v/oceans.mp4

Actual behavior.

The video plugin doesn't insert a video block.

Steps to reproduce the problem.

Go to https://www.froala.com/wysiwyg-editor
Click the Insert Video button in the toolbar.
Input this URL: http://vjs.zencdn.net/v/oceans.mp4
OS.

All

Browser.

All

**Comment by stefanneculai** [comment]
At this moment we support the following video providers for inserting via URL: Youtube, Vimeo, DailyMotion, Yahoo, Rutube and Vidyard. There is no option for using MP4 links.
