### ISSUE TITLE
froalaEditor.input is not triggered

### ISSUE THREAD

**Issue by monolithed** [froala/wysiwyg-editor#1769]
##### Steps to reproduce the problem

```js
{
	'froalaEditor.input' (event, editor) {
		console.log('event');
	}
}
```

1. Copy: **foo**
2. Press **cmd+v** or **backspace**

##### Expected behavior.
The event `froalaEditor.input` is triggered.

##### Actual behavior.

The event `froalaEditor.input` is **not** triggered.

##### The problem

I want to change the current font size dynamically using my CSS class. 
I've already tried to use `froalaEditor.contentChanged`, but it does not trigger any event on hold keys as well. 

##### OS.
macOs

##### Browser.
Chrome

![rw57aekalx](https://cloud.githubusercontent.com/assets/803674/23094539/086b7d92-f60c-11e6-8316-7ff87e0f5f2f.gif)

**Comment by stefanneculai** [comment]
The `input` event is being triggered only if it is not being stopped by other actions inside the editor. If you want to have it triggered before the editor actions, you should use the https://www.froala.com/wysiwyg-editor/docs/methods#events.on and use the `first` parameter

**Comment by monolithed** [comment]
@stefanneculai, thanks for the response. Could you provide an example how to pass these parameters in `react-froala-wysiwyg`?

**Comment by stefanneculai** [comment]
It's best to use the `initialized` event and bind your listener inside the callback, like this:
`editor.events.on('input', function () { ... }, true);`.

**Comment by monolithed** [comment]
```ts
import * as React from 'react';
import * as ReactBlock from 'react-bem-helper';
import bind from 'bind-decorator';
import Editor from 'react-froala-wysiwyg';
import { Constants } from './constants';
import './index.css';

export interface Props { }

export interface State {
	modifiers?: {
		[name: string]: boolean
	};
}

class Compose extends React.Component<Props, State> {
	constructor () {
		super();

		this.state = {
			modifiers: {}
		}
	}

	private block = new ReactBlock({
		name: 'editor'
	})

	@bind
	onInit (event: JQueryEventObject, editor) {
		editor.events.on('input', event => this.onInput(event, editor), true);
	}

	onInput (event: JQueryInputEventObject, editor) {
		let size: number = editor.charCounter.count();

		this.setState({
			modifiers: {
				scale: size > Constants.MAX_SCALE_VALUE
			}
		});
	}

	render () {
		let block = this.block({ modifiers: this.state.modifiers });

		return <div { ...block }>
					<Editor tag='textarea' config={
						{
							placeholderText: 'Enter your text here!',

							events : {
								'froalaEditor.initialized': this.onInit
							}
						}
					}/>
				</div>;
	}
}

export default Compose;
```

@stefanneculai, the same result 😞

The Backspace key and "Cmd+v" are not 
![vd2xji9wnr](https://cloud.githubusercontent.com/assets/803674/23103369/9daf16b0-f6cb-11e6-9fbf-afecf200d0d6.gif)

**Comment by brandonmp** [comment]
same outcome, the posted solution does not work. 

@stefanneculai  can you re-open this?

**Comment by kushalchoksi** [comment]
I agree, @stefanneculai this doesn't work anymore, attempted this in angular and get the same result where it only tracks inputs of type 'insertText' and 'deleteWordBackward' but nothing else. For example, the backspace/delete inputs should capture 'deleteContentBackward/Forward' respectively.

**Comment by RamGupta07** [comment]
@kushalchoksi I'm facing same issue with vuejs. @stefanneculai do you have any event that triggers an event whenever anything is inserted and deleted from the editor.
