### ISSUE TITLE
[BUG] Safari - File Upload / Insert Image (From Computer) Doesn't Open File Browser

### ISSUE THREAD

**Issue by jpgilchrist** [froala/wysiwyg-editor#1770]
Tested on welcome example: https://www.froala.com/wysiwyg-editor

##### Expected behavior.
Clicking the insert image or file upload  popup should open the file browser dialog...
![image](https://cloud.githubusercontent.com/assets/5065660/23073765/8caa307a-f504-11e6-8f2b-f3fbd7ae41bd.png)

##### Actual behavior.
Does nothing.

##### Steps to reproduce the problem.
* Go here: https://www.froala.com/wysiwyg-editor
* Click file upload or image upload
![image](https://cloud.githubusercontent.com/assets/5065660/23073825/b7146204-f504-11e6-9d48-a4de4c43b663.png)
* click instead of dropping a file
* notice it doesn't open the file browser like it should

The following screenshot from chrome to demonstrate exactly what I mean:
![image](https://cloud.githubusercontent.com/assets/5065660/23073896/05e31c40-f505-11e6-95b5-973cd7225d7d.png)

##### OS.
Mac OS Sierra

##### Browser.
Safari 10.0.3

**Comment by stefanneculai** [comment]
It has been fixed here last week and will be updated on the public website shortly.

**Comment by jpgilchrist** [comment]
Excellent thank you! I always appreciate how fast you guys are to respond!

**Comment by wenzou** [comment]
@stefanneculai We have the same issue except on firefox too, but for firefox, it works the first time, and its broken for all sequent clicks.
