### ISSUE TITLE
Image width set automatically on paste

### ISSUE THREAD

**Issue by mpatelj** [froala/wysiwyg-editor#1777]
```
Version 2.4.1
```

##### Expected behavior.
Do not want any max width or any other attribute set to the image automatically.

##### Actual behavior.
Image somehow has max width set to 300px.

##### Steps to reproduce the problem.
Copy an image to the clipboard and paste it into the editor

##### OS.
Windows 10

##### Browser
Chrome 56

**Comment by stefanneculai** [comment]
Please see: https://www.froala.com/wysiwyg-editor/docs/options#imagePasteProcess
