### ISSUE TITLE
Image pasting twice in Microsoft Edge

### ISSUE THREAD

**Issue by mpatelj** [froala/wysiwyg-editor#1778]
```
Version 2.5.0
```

##### Expected behavior.
Image should be pasted just once

##### Actual behavior.
Image pasted twice

##### Steps to reproduce the problem.
Try cut or copy of an image and paste it into the editor again.  This pastes the image twice.  It's just the images that are getting paste twice and not the text content.

##### OS.
Windows 10

##### Browser.
Microsoft Edge

**Comment by mpatelj** [comment]
Any updates on this?

**Comment by stefanneculai** [comment]
@mpatelj this doesn't happen on our website. Please make sure you have your Edge version up to date and Froala Editor as well.
