### ISSUE TITLE
When htmlUntouched enabled weird spacing is added (Froala 2.4.2 and 2.4.3)

### ISSUE THREAD

**Issue by dswitzer** [froala/wysiwyg-editor#1780]
We're seeing a very strange behavior with Froala 2.4.2 and 2.4.3. We want to use the `htmlUntouched: true` option, but when we enable the feature we're seeing weird spacing being added to the document. I was able to put together the follow sample:

https://jsfiddle.net/dswitzer/xyjgy2bz/6/

Go to any of the bullet points and press space (or event CTRL+C) and you'll see the content in the block element is altered and a lot of extra spacing is added.

This happens in every browser we've tested.

**Comment by stefanneculai** [comment]
@dswitzer could you please make a recording? I just tried to reproduce it, but looks good to me.

**Comment by dswitzer** [comment]
Here's a video of the problem. I illustrate the behavior in both FF 51.0.1 and Chrome 56.0.2924.87 on Windows 10. However, I see the same behavior in every browser I've tested so I'm pretty sure it's some kind of parsing issue.

https://youtu.be/4kTP9oOO9Ck

**Comment by dswitzer** [comment]
Still working on debugging, but the problem appears to be in the function restore () {} method. The problem is in the following code when I press the space bar. The `prev_node.textContent = prev_node.textContent + next_node.textContent;` code is altering the block element and then the call to `editor.spaces.normalize(prev_node);` is corrupting the spacing.

```
// Previous node and next node are both text.
if (prev_node && next_node && prev_node.nodeType == Node.TEXT_NODE && next_node.nodeType == Node.TEXT_NODE) {
  // Remove markers.
  $(start_marker).remove();
  $(end_marker).remove();

  // Save cursor position.
  var len = prev_node.textContent.length;
  prev_node.textContent = prev_node.textContent + next_node.textContent;
  $(next_node).remove();

  // Normalize spaces.
  editor.spaces.normalize(prev_node);

  // Restore position.
  range.setStart(prev_node, len);
  range.setEnd(prev_node, len);

  special_case = true;
}
```

**Comment by stefanneculai** [comment]
@dswitzer thanks for the additional details. We were able to reproduce it and now we're fixing it. :)

**Comment by stefanneculai** [comment]
@dswitzer could you check with the current master? It should be fixed. Thank you.

**Comment by dswitzer** [comment]
Thanks. That seems to fix it.
