### ISSUE TITLE
Vertical alien element appears after uploading file in editor

### ISSUE THREAD

**Issue by livinginthetrumpisphere** [froala/wysiwyg-editor#1782]
##### Expected behavior.
After uploading a file, there should be a blue string of text...link to the file.

##### Actual behavior.
After uploading a file, there is a blue string of text AND the vertical alien element.

##### Steps to reproduce the problem.
Click the file upload icon in the editor and select a file from your desktop....upload and the alien will appear.
![bug](https://cloud.githubusercontent.com/assets/26000248/23296484/1f9174e6-fa2a-11e6-84c6-8738789f79e1.png)

##### OS.
Windows 10 Version	10.0.14393 Build 14393

##### Browser.
Firefox 51.0.1

**Comment by stefanneculai** [comment]
That is a paperclip which shows that the link is a file. If you want to disable this, you could use the following CSS rule:
```CSS
.fr-view .fr-file::after {
  content: "";
}

**Comment by livinginthetrumpisphere** [comment]
if you remove the black from the paperclip image, it would look more like a paperclip. 
the android paperclip looks like a paperclip....

**Comment by stefanneculai** [comment]
We're using the default browser character for that, we don't make any changes to it.

**Comment by livinginthetrumpisphere** [comment]
Good to know..thanks.
it’s not a great icon, as it isn’t clear what it is unless I zoom the browser (firefox) to a much higher magnification.

 

Appreciate the clarification.

Best

pat
