### ISSUE TITLE
Losing keyboard focus when erasing empty line

### ISSUE THREAD

**Issue by JSteunou** [froala/wysiwyg-editor#1783]
##### Expected behavior.

Keeping the virtual keyboard open while having focus / writing inside the editor

##### Actual behavior.

The virtual keyboard is closing itself while deleting previous empty line

##### Steps to reproduce the problem.

* Go into editor
* hit enter
* hit enter
* hit enter
* hit backspace

virtual keyboard close itself

##### OS.

only Android 7+

##### Browser.

Chrome 56

**Comment by dianaprajescu** [comment]
Are you able to reproduce this on our [website](https://www.froala.com/wysiwyg-editor)?

**Comment by JSteunou** [comment]
nope, seems like the issue is solved!
You can close this @stefanneculai @dianaprajescu
