### ISSUE TITLE
Page scroll to the bottom when erasing empty line

### ISSUE THREAD

**Issue by JSteunou** [froala/wysiwyg-editor#1784]
##### Expected behavior.

Entire page scroll should not move

##### Actual behavior.

Entire page scroll goes to the bottom

##### Steps to reproduce the problem.

* go to https://www.froala.com/wysiwyg-editor
* focus between 2 paragraphs
* hit enter several time until the cursor is under the virtual keyboard (hidden)
* hit backspace

page scroll goes to the bottom while you still have focus in the editor

##### OS.

Android 6

##### Browser.

Chrome 56

**Comment by stefanneculai** [comment]
We couldn't reproduce this with the current master.

**Comment by JSteunou** [comment]
I still reproduce it when following the steps to reproduce the issue. Is https://www.froala.com/wysiwyg-editor using the current master?

**Comment by stefanneculai** [comment]
Couls you please make a recording?

Stefan

**Comment by JSteunou** [comment]
I dont know how to record on Android but I could try I guess... Did you try with the same steps, same Android version, same Chrome version like I wrote above?

**Comment by stefanneculai** [comment]
Yes, we tried just the same steps. Maybe you can record with another device.

**Comment by TK-one** [comment]
anything more about this ?
When using English, I could not find any problem.
But, When I hit Korean or Japanese, this issue occur.

When I hit Korean 2 paragraphs and hit backspace, scroll goes to bottom.
I tried in [https://www.froala.com/wysiwyg-editor](url)

**Comment by stefanneculai** [comment]
@JSteunou @TK-one could you please try to record the screen? Thank you.

**Comment by TK-one** [comment]
[issue#1784.zip](https://github.com/froala/wysiwyg-editor/files/934780/issue.1784.zip)

Thank you.

**Comment by TK-one** [comment]
I am sorry to mention this issue again,  When this issue will be fixed?

Many users who use froala-editor in my App are uncomfortable with this bug in android mobile.

**Comment by tmpg** [comment]
I have this same issue but it happens when I press enter.

**Comment by TK-one** [comment]
Oh, right. For reference, I could reproduce this with mobile view in chrome development tools.
