### ISSUE TITLE
New Word pasting routines in 2.5.0 are pasting invalid data URI images

### ISSUE THREAD

**Issue by dswitzer** [froala/wysiwyg-editor#1785]
We're seeing an issue with the new Word pasting code where it's generating data URI for images that are invalid. For example, here is the raw HTML that's being generated from one of our Word documents.

```
<p><span><img data-fr-image-pasted="true" src="data:image/png;base64,6Iz0tYe9Pj4EidBJXj6hSw==" alt="create_ticket" width="714" height="117"></span></p>
<p><span><img data-fr-image-pasted="true" src="data:image/png;base64,qBGXKUlkAcB7pO5OArjzig==" alt="ticket_grid_001a" width="714" height="202"></span></p>
```

Since the code sees data URIs being pasted, it's trying to upload them to the server. However, the current image pasting code assumes that all data URIs are valid, so the upload silently fails and the "Uploading" dialog stays open.

As a temporary fix, I was able to modify the `_startUpload()` function with the following:

```
$current_image.on('error', _imageUploadError);
```

I placed this in the code write after the line:

```
$current_image.on('load', _sendRequest);
```

This at least allows kills the dialog and reports the error.

The better fix would be to check that the image is valid *before* starting the upload process.

**Comment by stefanneculai** [comment]
@dswitzer could you please send us the Word document you're using.

**Comment by dswitzer** [comment]
@stefanneculai 

I'm sending you the file offline.

**Comment by dswitzer** [comment]
Just to be clear, I'm seeing this when I select the entire Word document into the clipboard and paste the contents into Froala. 

I'm using an Office 365 subscription and an I'm on Word 2016 v1611 (build 7571.2109).

**Comment by stefanneculai** [comment]
Closing this as we're tracking it offline.
