### ISSUE TITLE
The froalaEditor.image.error event should return a reference to the image

### ISSUE THREAD

**Issue by dswitzer** [froala/wysiwyg-editor#1787]
The `froalaEditor.image.error` event should return a reference to the `img` element that generated an error, that way an programmatically access the element. 

For example, in my case I'm seeing issues in 2.5.0 where pasting from a Word document is generating invalid base64 images. Since the images are invalid, I'd like to remove the elements from the DOM or replace them with a placeholder element that indicates there was an invalid image.

> **NOTE:** Froala 2.5 doesn't currently correctly handle invalid base64 images. I've reported the issue, but had to put a fix in place to correct the issue.

**Comment by stefanneculai** [comment]
You could use `image.get` method to get the current active image inside the editable area.

**Comment by dswitzer** [comment]
@stefanneculai 

When I do the following:

```
.on('froalaEditor.image.error', function (e, editor, error, response){
	console.log(editor.image.get());
});
```

I'm not seeing references to the actual image in the DOM, which is what I want. I'm also seeing `null` returned for a most of the images.

Keep in mind that this error is being triggered during a paste operation, so there could be multiple images being processed in a single operation.

**Comment by stefanneculai** [comment]
We're going to close this for now and reopen it if there is more interest on that. Most likely this feature would get implemented together with image multiple files upload.
