### ISSUE TITLE
Table does not work!

### ISSUE THREAD

**Issue by noise2** [froala/wysiwyg-editor#1790]
The table toolbox does not work as it is supposed to.
 
##### Expected behavior.
![image](https://cloud.githubusercontent.com/assets/2348936/23403916/a7b19126-fdc7-11e6-8ea0-280080d37d74.png)

##### Actual behavior.
![image](https://cloud.githubusercontent.com/assets/2348936/23403862/5994c2ec-fdc7-11e6-995d-f748d1935b46.png)

##### CSS
![image](https://cloud.githubusercontent.com/assets/2348936/23403929/ba86710e-fdc7-11e6-95e6-c7d4490a0aed.png)

##### JS
![image](https://cloud.githubusercontent.com/assets/2348936/23403940/c8aa6920-fdc7-11e6-9f5e-fdd808a42b3b.png)

##### OS.
Linux

##### Browser.
Chrome v55

## Questions:
1. What is the problem?
2. How can I fix the problem?

**Comment by stefanneculai** [comment]
This looks like a problem from your side. Please contact us via our website for tech support.
