### ISSUE TITLE
Option useClasses has no effect

### ISSUE THREAD

**Issue by yivo** [froala/wysiwyg-editor#1791]
##### Expected behavior.
If useClasses set to true editor will add CSS classes instead inline styles where possible.

##### Actual behavior.
There are no classes added. Only inline styles.

##### Steps to reproduce the problem.
1. Upload image
2. Use inspector to view img tag markup
3. You will ses inline styles

##### OS.
OS X 10.12.2

##### Browser.
Tested only in Chrome 56

##### Editor version
2.4.2, 2.5.0

**Comment by stefanneculai** [comment]
@yivo are you using htmlUntouched option?

**Comment by yivo** [comment]
@stefanneculai yes. If set to `false` classes are added as expected.

**Comment by stefanneculai** [comment]
The `htmlUntouched: true` option cannot be used together with the `useClasses: true` because useClasses convert the inline style to classes for images which you don't want because of the htmlUntouched.

**Comment by yivo** [comment]
Is `htmlUntouched` really necessary option? At most all special processing we can control through `htmlAllowed*`, `htmlRemoveTags`, `htmlIgnoreCSSProperties`, `useClasses`, `pasteAllowedStyleProps`, `pasteDeniedAttrs`, 'pasteDeniedTags' and so on.
