### ISSUE TITLE
Image uploaded in my folder but not inserted image in editor. What is a problem?

### ISSUE THREAD

**Issue by celalnuriakgun** [froala/wysiwyg-editor#1793]
Likely problematic function:

$('textarea#editorf').on('froalaEditor.image.inserted', function (e, editor, $img, response) {
       alert("Resim editöre yerleştirildi");
})

**Comment by stefanneculai** [comment]
@celalnuriakgun please reach us through our website for tech support. Thank you.

**Comment by celalnuriakgun** [comment]
I'm this problem is solved, but now I have another problem: I want you to save it when I click on the button. How to i do? Can you write small sample code? @stefanneculai
