### ISSUE TITLE
page scroll to top when deleting selected line

### ISSUE THREAD

**Issue by cshehadi** [froala/wysiwyg-editor#1794]
##### Expected behavior.
When deleting a highlighted paragraph, the page should not scroll

##### Actual behavior.
page scrolls to top

##### Steps to reproduce the problem.
Highlight a paragraph, delete it.

##### OS.
Mac OS 10.11.6

##### Browser.
Chrome 56

**Comment by cshehadi** [comment]
I should have noted that this is in Froala version 2.5

**Comment by stefanneculai** [comment]
@cshehadi are you able to reproduce this on our website? If so, you could please provide few more details?

**Comment by cshehadi** [comment]
Hi Stefan,

No I can't reproduce it on your site, but I've narrowed down the cause and you can recreate it easily.  It only happens when the iframe option is set to true.

So just to simplify matters, for the test you can use:

```
    <script>
    jQuery(document).ready(function () {
        $('#test').froalaEditor(
            {
                "iframe":true,
            });
    });
    </script>
```

and create a froala input box.  Then paste in the text from the attached file: page_scroll_test.txt.

scroll down to the bottom.  select the line:

"And you know what will help—have fun messing around with this!"

and then hit the delete key.  

It'll scroll back to near the top (this is Chrome 56 on Mac OS 10.11.6)

if you set iframe to false, it will not do this.

-Charlie

[page_scroll_test.txt](https://github.com/froala/wysiwyg-editor/files/822366/page_scroll_test.txt)
[page_scroll_test_html.txt](https://github.com/froala/wysiwyg-editor/files/822371/page_scroll_test_html.txt)
