### ISSUE TITLE
New transition animations for editor toolbar

### ISSUE THREAD

**Issue by tindiep** [froala/wysiwyg-editor#1795]
##### Expected behavior.
I am using your sticky toolbar for my project. However, the library only has 2 methods to show and hide the toolbar without any transition animations. 

##### Actual behavior.
Could you please add more methods to support animations such as slideUp(), slideDown(), fadeIn() and fadeOut() with duration parameter like JQuery?

Thanks,
Tin Diep

**Comment by stefanneculai** [comment]
I marked this as a feature request, however it is unlikely to have this added.
