### ISSUE TITLE
Option to remove resource/reference when content pasted

### ISSUE THREAD

**Issue by jeremylynch** [froala/wysiwyg-editor#1798]
![ezgif com-video-to-gif 5](https://cloud.githubusercontent.com/assets/3665457/23583350/d00e6a80-018d-11e7-9322-ef75b6ea157f.gif)

Previously, the resource of the pasted content was not included. Is it possible to bring back this functionality?

**Comment by stefanneculai** [comment]
@jeremylynch could you please let us know where you're copying from? Thank you.

**Comment by jeremylynch** [comment]
Here is a sample PDF document: http://www.harrisonsim.com/chapters/CH27_final.pdf

I am copying from **Preview** on MacOS. Interestingly, when copying from a PDF open in chrome, the paste result is very different.

**Comment by stefanneculai** [comment]
This should be fixed on the current master.
