### ISSUE TITLE
Can we use this editor without using jquery or angular ... 

### ISSUE THREAD

**Issue by suryaiiit** [froala/wysiwyg-editor#1799]
Is it possible to use the Froala Editor using Plain Javascript??

Thanks

**Comment by stefanneculai** [comment]
At this moment the editor requires the jQuery dependency.

**Comment by Panman8201** [comment]
(Commenting here since it's the latest issue for this question, and as a framework plugin/addon contributor.)

The Ember.js direction (and front-end development in general) is to move away from having a jQuery dependency. I think it's important that Froala follow this trend to stay reliant. Perhaps Froala Editor 3.x.?. 😉

**Comment by caJaeger** [comment]
@Panman8201 I agree 100%, jQuery dependencies are preventing us from using this.

**Comment by Ardeshir81** [comment]
Same thing here. We use `AngularJS` with `Angular-Material` and we have no dependency to `jquery`, and we don't want it. and its preventing us from using your `froala`'s `wysiwyg-editor`. It would be great if you had a version released with dependencies to a subset of `jquery` pre-bundled with `wysiwyg-editor`, itself.

**Comment by 6matko** [comment]
I have to add that our use case also requires version without ```jquery```. :(

**Comment by TomMettam** [comment]
I completely agree. Lose jQuery.

**Comment by ryantbrown** [comment]
We were just about to purchase a wildcard license for this until I did a last minute check for a jQuery dependency. It is misleading to say you support all of the modern client frameworks (Vue, React) while still depending on jQuery. This has got to be a deal breaker for anyone using a modern framwork.

On the other hand this editor is amazing - are there any plans to remove the dependency on jQuery?

**Comment by Pab89** [comment]
We where also about to buy a license but the jQuery requirement prevent it.

**Comment by dgroh** [comment]
what is the most stable jQuery version to use with Froala?

**Comment by ShaneHowell** [comment]
@stefanneculai Are there any plans on removing the jQuery dependency? 

Pretty much the entire industry has moved away from requiring jQuery and is clearly a hinderance to many potential customers, including myself.

**Comment by stefanneculai** [comment]
Sure: https://wysiwyg-editor-roadmap.froala.com/public/ideas/3597.
