### ISSUE TITLE
show and hide methods not working

### ISSUE THREAD

**Issue by archonic** [froala/wysiwyg-editor#180]
I believe the [show](http://editor.froala.com/methods#show) and [hide](http://editor.froala.com/methods#hide) methods are meant to show and hide the toolbar. [This guy](https://github.com/froala/wysiwyg-editor/issues/121) was looking for something like that as well. They appear to do nothing :(.

**Comment by stefanneculai** [comment]
Just a head up regarding this. In the version 1.2.7 it is possible to hide/show the toolbar this way:
 - listen to the [focus](https://www.froala.com/wysiwyg-editor/docs/events#focus)/[blur](https://www.froala.com/wysiwyg-editor/docs/events#blur) events
 - inside the listener you can get the toolbar using editor.$editor and call hide or show on it.

**Comment by magician11** [comment]
If anybody is still looking how to do this.. this works...

```
      events: {
        'froalaEditor.initialized': (e, editor) => {
          editor.toolbar.hide();
        },
        'froalaEditor.focus': (e, editor) => {
          editor.toolbar.show();
        },
        'froalaEditor.blur': (e, editor) => {
          editor.toolbar.hide();
        },
      },
```

**Comment by grid-100** [comment]
I use this code to toggle Edit or View mode from external button
```
//--------- Hide Editor -----------------
$("#editor").froalaEditor('edit.off');
$("#editor").froalaEditor('toolbar.hide');

//--------- Show Editor -----------------
$("#editor").froalaEditor('edit.on');
$("#editor").froalaEditor('toolbar.show');
```
