### ISSUE TITLE
Toolbar mis-aligned in bootstrap modal panels on Desktop/Chrome

### ISSUE THREAD

**Issue by RHinderiks** [froala/wysiwyg-editor#1800]
##### Expected behavior.
Toolbar aligned with textarea

##### Actual behavior.
slightly off to the right on a modal panel with a scrollbar

##### Steps to reproduce the problem.
Create an modal panel with enough content to get a scrollbar, Make sure the editor is out of sight but not at the bottom (easier for reproducing) When scrolling down the toolbar wil be off until you reach the bottom of the modal panel or select anything in any way, it then just pops into place. It seems to happen on high resolution screens only (3200x1800) and (2880 by 1800 pixels (Retina)) 

![image](https://cloud.githubusercontent.com/assets/26223525/23611057/aeb71240-0275-11e7-87de-3ce5ef2e0142.png)

##### OS.
Windows 10 / MacOS Sierra

##### Browser.
Chrome Version 56.0.2924.87 (64-bit)

**Comment by stefanneculai** [comment]
Please upgrade to at least v2.4.2.

**Comment by RHinderiks** [comment]
Running on v2.5.0

**Comment by stefanneculai** [comment]
Do you have a page to test it?
