### ISSUE TITLE
I want you to save it when I click on the button. How to i do? Can you write small sample code?

### ISSUE THREAD

**Issue by celalnuriakgun** [froala/wysiwyg-editor#1801]
# My code: 

<script type="text/javascript" src="http://localhost/onebilderass/js/froala/js/plugins/video.min.js"></script>
        <script type="text/javascript" src="http://localhost/onebilderass/js/froala/js/plugins/image.min.js"></script>
        <script type="text/javascript" src="http://localhost/onebilderass/js/froala/js/plugins/save.min.js"></script>
        <script type="text/javascript">
            $(function(){
                $('froala').froalaEditor({
                    language: 'tr',
                    pastePlain: true,
                    toolbarButtons: ['bold', 'italic', 'underline', 'strikeThrough', 'subscript', 'superscript', 'fontFamily', 'fontSize', '|', 'specialCharacters', 'color', 'emoticons', 'inlineStyle', 'paragraphStyle', '|', 'paragraphFormat', 'align', 'formatOL', 'formatUL', 'outdent', 'indent', '-', 'quote', 'insertHR', 'insertLink', 'insertImage', 'insertVideo', 'insertFile', 'insertTable', '|', 'undo', 'redo', 'clearFormatting', 'selectAll', 'html', 'applyFormat', 'removeFormat', 'fullscreen', 'print', 'help'],
                    toolbarButtonsMD: ['bold', 'italic', 'underline', 'strikeThrough', 'subscript', 'superscript', 'fontFamily', 'fontSize', '|', 'specialCharacters', 'color', 'emoticons', 'inlineStyle', 'paragraphStyle', '|', 'paragraphFormat', 'align', 'formatOL', 'formatUL', 'outdent', 'indent', '-', 'quote', 'insertHR', 'insertLink', 'insertImage', 'insertVideo', 'insertFile', 'insertTable', '|', 'undo', 'redo', 'clearFormatting', 'selectAll', 'html', 'applyFormat', 'removeFormat', 'fullscreen', 'print', 'help'],
                    toolbarButtonsSM: ['bold', 'italic', 'underline', 'strikeThrough', 'subscript', 'superscript', 'fontFamily', 'fontSize', '|', 'specialCharacters', 'color', 'emoticons', 'inlineStyle', 'paragraphStyle', '|', 'paragraphFormat', 'align', 'formatOL', 'formatUL', 'outdent', 'indent', '-', 'quote', 'insertHR', 'insertLink', 'insertImage', 'insertVideo', 'insertFile', 'insertTable', '|', 'undo', 'redo', 'clearFormatting', 'selectAll', 'html', 'applyFormat', 'removeFormat', 'fullscreen', 'print', 'help'],
                    toolbarButtonsXS: ['bold', 'italic', 'underline', 'strikeThrough', 'subscript', 'superscript', 'fontFamily', 'fontSize', '|', 'specialCharacters', 'color', 'emoticons', 'inlineStyle', 'paragraphStyle', '|', 'paragraphFormat', 'align', 'formatOL', 'formatUL', 'outdent', 'indent', '-', 'quote', 'insertHR', 'insertLink', 'insertImage', 'insertVideo', 'insertFile', 'insertTable', '|', 'undo', 'redo', 'clearFormatting', 'selectAll', 'html', 'applyFormat', 'removeFormat', 'fullscreen', 'print', 'help'],

                    videoUploadURL: 'http://localhost/onebilderass/js/froala/upload.php',
                    videoUploadMethod: 'POST',
                    videoUploadParams: {id: 'froala'},
                    videoAllowedTypes: ['mp4'],
                    videoMaxSize: 20 * 1024 * 1024,
              
                    fileUploadURL: 'http://localhost/onebilderass/js/froala/upload.php',
                    fileUploadParams: {id: 'froala'},
                    fileUploadMethod: 'POST',
                    fileMaxSize: 20 * 1024 * 1024,
                    fileAllowedTypes: ['*'],

                    imageUploadURL: 'http://localhost/onebilderass/js/froala/upload.php',
                    imageUploadParams: {id: 'froala'},
                    imageUploadMethod: 'POST',
                    imageMaxSize: 20 * 1024 * 1024,
                    imageAllowedTypes: ['jpeg', 'jpg', 'png'],
                });
            });
        </script>

**Comment by stefanneculai** [comment]
Please find more about that here: https://www.froala.com/wysiwyg-editor/docs/concepts/save/button.
