### ISSUE TITLE
Clicking Horizontal Bar button results in JS error

### ISSUE THREAD

**Issue by irphilli** [froala/wysiwyg-editor#1803]
##### Expected behavior.
Horizontal Bar correctly added to content

##### Actual behavior.
Javascript error:
Uncaught TypeError: Cannot read property 'nextSibling' of undefined

##### Steps to reproduce the problem.

1. Enable 'insertHR' toolbar button
2. Click Button

##### OS.
macOS Sierra

##### Browser.
Chrome Latest (Version 56.0.2924.87)

**Comment by stefanneculai** [comment]
@irphilli Are you able to reproduce it here? https://www.froala.com/wysiwyg-editor/examples/full-featured. If yes, then could you please provide few more details?

**Comment by irphilli** [comment]
I cannot!  I was looking for another place to test it out - thanks for that.  I will get back if I could figure out what combination of settings is causing the error.  Thanks.

**Comment by irphilli** [comment]
Whoops! Didn't have `<hr>` in the list of allowed HTML tags.  That would do it :). Thanks again for checking.
