### ISSUE TITLE
How can I get a video source?

### ISSUE THREAD

**Issue by celalnuriakgun** [froala/wysiwyg-editor#1805]
This applies to images, but not for video. For example:
$ .ajax ({
                // Request method.
                Method: "POST",

                // Request URL.
                Url: "http: //localhost/delete.php",

                // Request params.
                Data: {
                            Src: $ img.attr ('src'),
                           Operation: 'delete'
                         }
             }}
             .done (function (data) {
                 Console.log ('image was deleted');
              }}
             .fail (function () {
                 Console.log ('image delete problem');
              }}
How can I do for video?

**Comment by stefanneculai** [comment]
Same thing applies to videos that are uploaded by the editor.

**Comment by celalnuriakgun** [comment]
I writing this code but not working and I am getting this error in my browser, chrome console: undefined. Say this for console.log($video.attr('src'))
what can I do? :( please help me

froala').on('froalaEditor.video.removed', function (e, editor, $video) {
                    // console.log($video);
                    // console.log(editor);
                    // console.log(e);
                    // console.log($video.attr('src'));
                    $.ajax({
                      // Request method.
                      method: "POST",
                      // Request URL.
                      url: "my_url.php",
                      // Request params.
                      data: {
                        src: $video.attr('src'),
                        operation: 'delete'
                      }
                    })
                    .done (function (data) {
                        // console.log(data)
                        console.log ('image was deleted');
                    })
                    .fail (function () {
                        console.log ('image delete problem');
                    })
                });

**Comment by celalnuriakgun** [comment]
@stefanneculai

**Comment by roohial57** [comment]
salam
I use this code and work correctly
```
            .on('froalaEditor.video.beforeRemove', function (e, editor, $video) {
                src=$($('#edit').froalaEditor('selection.element')).find('video').attr('src');
            })
```

**Comment by fwfabricio** [comment]
Olá, o seu método não é o mais indicado, por que se você tiver dois ou mais videos adicionados, ele sempre irá excluir o ultimo video, mesmo que a intenção tenha sido deletar o primeiro. 
Para resolver isso, use a variavel $video, segue exemplo abaixo:

.on('froalaEditor.video.beforeRemove', function (e, editor, $video) {
   $.ajax({method: "POST",url: "delete_video.php",data: {src: $video.find('video').attr('src')}})
})

Assim irá excluir somente o vídeo pretendido
