### ISSUE TITLE
Chrome crashes when trying to upload image by drag and drop

### ISSUE THREAD

**Issue by binod12** [froala/wysiwyg-editor#1808]
##### Expected behavior.
Image should be uploaded when we try to drag and drop any image

##### Actual behavior.
The chrome browser hangs and it stops responding when we try to drag and drop images

##### Steps to reproduce the problem.
Click on the image icon, it opens the file dialogue, instead of selecting the file, drag some random image files inside the editor repeatedly in normal way, close the dialogue box by clicking cancel button and when we click on the editor again it stops responding.

##### OS.
Windows 10

##### Browser.
Chrome Version 57.0.2987.88

Recorded video is attached
[1808.zip](https://github.com/froala/wysiwyg-editor/files/827439/1808.zip)

**Comment by stefanneculai** [comment]
@binod12 we just checked this and it doesn't appear to be an issue. When the image is alone in the editor, you can add a new line by clicking the image and hitting enter, or click above/below it.
