### ISSUE TITLE
The shortcut key for imageInsert not working for IE

### ISSUE THREAD

**Issue by binod12** [froala/wysiwyg-editor#1809]
##### Expected behavior.
Pressing ctrl + P key should open the image image upload area.

##### Actual behavior.
It is opening the image upload area along with OS print dialogue

##### Steps to reproduce the problem.
open the editor in Internet explorer and press the keys ctrl + P

##### OS.
Windows 10

##### Browser.
IE10 and IE11
![1809](https://cloud.githubusercontent.com/assets/6301387/23703068/190dbe46-0424-11e7-9191-e0df802eeb16.png)

**Comment by stefanneculai** [comment]
We can confirm there is a problem with this, it looks somehow the default behavior for print is not being stopped. Until we fix this, as a workaround, we would suggest changing the shortcut for the image: https://www.froala.com/wysiwyg-editor/docs/concepts/custom/shortcut.

**Comment by stefanneculai** [comment]
@binod12 this behavior is by design: https://support.microsoft.com/en-us/help/3167077/browser-default-action-for-ctrl-p-cannot-be-prevented.
