### ISSUE TITLE
How to disable drag and drop image upload

### ISSUE THREAD

**Issue by binod12** [froala/wysiwyg-editor#1811]
Question:
We are finding many issue in different browsers when we try to upload image by drag and drop by various means i.e. draging and dropping in drop area or inside the editor, so is it possible to disable drag and drop of image upload completely by froala configuration?

**Comment by stefanneculai** [comment]
You could bind to the drop event inside the editor and return false to prevent all the dropping chain:
```js
$(selector).on('froalaEditor.initialized', function (e, editor) {
  editor.events.on('drop', function () {
    return false;
  }, true);
});

**Comment by binod12** [comment]
When I apply the above changes, it stops drag and drop of image in editor area, however, it allows the drag and drop inside the Image Insert popup. It also cause different behaviour in chrome and firefox, the chrome just replaces the image in the address bar, and firefox renders it as base64 image. IE does not allow drag and drop inside editor.
Is it possible to entirely disable the drag and drop image?

**Comment by namirsab** [comment]
@stefanneculai we are having the same issue.
The proposed solution also disables drag and dropping images that are already part of the content.
We only need to disable the drop from external places (such as the file system).
Either that or removing the current behavior (uploading the image to the froala servers) by our custom behavior.

Any help would be really appreaciated :smile:

**Comment by florenperetti** [comment]
You may add e.preventDefault() to @stefanneculai code so it doesn't render the image in the browser:
`
$(selector).on('froalaEditor.initialized', function (e, editor) {
  editor.events.on('drop', function (e) {
    e.preventDefault();
    return false;
  }, true);
});
`
