### ISSUE TITLE
How can I get video source?

### ISSUE THREAD

**Issue by celalnuriakgun** [froala/wysiwyg-editor#1813]
I writing this code but not working and I am getting this error in my browser, chrome console: undefined. Say this for console.log($video.attr('src'))
what can I do? :( please help me

froala').on('froalaEditor.video.removed', function (e, editor, $video) {
// console.log($video);
// console.log(editor);
// console.log(e);
// console.log($video.attr('src'));
$.ajax({
// Request method.
method: "POST",
// Request URL.
url: "my_url.php",
// Request params.
data: {
src: $video.attr('src'),
operation: 'delete'
}
})
.done (function (data) {
// console.log(data)
console.log ('video was deleted');
})
.fail (function () {
console.log ('video delete problem');
})
});

**Comment by stefanneculai** [comment]
`video.removed` doesn't return the video itself, but the wrapper of the video. It looks like this: `<span class="fr-video">VIDEO_OBJECT_HERE</span>`.
