### ISSUE TITLE
Font sizes lost when navigating with multiple return characters

### ISSUE THREAD

**Issue by nmcbryde** [froala/wysiwyg-editor#1815]
##### Expected behavior.
A non-default font size should be kept when navigating with multiple returns present.

##### Actual behavior.
Font size will revert to the default size.

##### Steps to reproduce the problem.
Set the font size to a non-default size on a line with text, press return twice, then hit the up arrow. Font size will be changed.

##### OS.
All

##### Browser.
All

**Comment by stefanneculai** [comment]
For that please use: https://www.froala.com/wysiwyg-editor/docs/options#keepFormatOnDelete.
