### ISSUE TITLE
iFrameStyle appends default stylesheet

### ISSUE THREAD

**Issue by szaib1986** [froala/wysiwyg-editor#1816]
##### Expected behavior.
I have set the 
iframe: true,
iframeStyle: styleSheet

so it should use the stylesheet that I have provided

##### Actual behavior.
When I inspected the elements, I found that editor is appending the default style at the end of my custom style.

**Comment by stefanneculai** [comment]
Could you please provide a jsFiddle?

**Comment by stefanneculai** [comment]
By default the editor is injecting inside the iframe the styles found in CSS files. If you don't want those styles, then you should remove the CSS rules from the files.
