### ISSUE TITLE
Wrong style for align-justify for video element options

### ISSUE THREAD

**Issue by ypanyukov** [froala/wysiwyg-editor#1817]
##### Expected behavior.
As other buttons

##### Actual behavior.
![image](https://cloud.githubusercontent.com/assets/2107485/23748577/3bd0dc9a-04d5-11e7-952e-cce47a5b58b8.png)

##### Steps to reproduce the problem.
Insert a video, try to edit options

##### OS.
MacOS Sierra 10.12.3

##### Browser.
Chrome 56.0.2924.87 (64-bit)

**Comment by stefanneculai** [comment]
It looks like you don't have the video plugin version aligned with the main version.
