### ISSUE TITLE
Chome 56 adding extra characters when pasting from Word 2016 in v2.5.0

### ISSUE THREAD

**Issue by dswitzer** [froala/wysiwyg-editor#1818]
In testing Chrome 56.0.2924.87, when I paste RTF copied from a Word document I'm seeing extra characters being included at the bottom of pasted text.

In researching the issue, it appears when pasting the RTF into Chrome, there it sometimes adds extra information after the ending `</html>` element. For example, when debugging the `_wordClean()` function I'm seeing the value of `html` argument ending in the following:

```
<!--EndFragment-->
</body>

</html>
ports_�rt����
```

When the string is parsed with `(new DOMParser()).parseFromString()` the `ports_�rt����` string gets added to the end of the `<body>` element, thus the string ends up at the end of the document.

I'm only seeing the behavior in Chrome and it seems to only happen when the RTF string has mixed content, such as images in it.

This could be fixed by stripping out any text after the last occurrence of `</html>`, but perhaps there are cases where malformed HTML might end up getting pasted in and that fix might have ramifications.

**Comment by stefanneculai** [comment]
It should be fixed on master.

**Comment by dswitzer** [comment]
Great work! This is fixed in the new 2.5.1 release. Thanks!
