### ISSUE TITLE
keyup event not registered for ENTER keypress with events.on( 'keyup', function( ) { } )

### ISSUE THREAD

**Issue by GMiLL5** [froala/wysiwyg-editor#1819]
##### Expected behavior.
The following code would log 'keyup' in the console for every keyup event
```
editor.events.on( 'keyup', function( ) {
   console.log( 'keyup' );
});
```

##### Actual behavior.
When pressing enter, 'keyup' is not logged in the console

##### Steps to reproduce the problem.
1. Add the event listener
2. Press enter in the editor

##### OS.
All

##### Browser.
All

Note: The following does still work
```
editor.events.$on( editor.$el, 'keyup', function( ) {
   console.log( 'keyup' );
});
```

**Comment by stefanneculai** [comment]
The code triggers the event if it is not being stopped by another listener. If you want to have your code called first, you should do the following:
```js
editor.events.on( 'keyup', function( ) {
   console.log( 'keyup' );
}, true);
```

**Comment by GMiLL5** [comment]
@stefanneculai `editor.keys._mapKeyUp` Makes several checks for `e.which == $.FE.KEYCODE.ENTER` that are always false because it's also not triggered for the enter key

**Comment by stefanneculai** [comment]
There might be other places where the keyup event is being stopped.
