### ISSUE TITLE
Word Paste plugin issue in IE11

### ISSUE THREAD

**Issue by dswitzer** [froala/wysiwyg-editor#1821]
Right now, the Word Paste plugin does not work in IE11. Pasting content from a RTF leads to errors. It appears the problem is around the usage of `node.remove()`, which is non-standard method and breaks in IE11:

http://stackoverflow.com/questions/23136551/removing-a-text-node-with-remove-doesnt-work-in-ie

Instead the code should be using:

```
node.parentNode.removeChild(node);
```

**Comment by stefanneculai** [comment]
It's fixed on master.

**Comment by dswitzer** [comment]
Great work! This is fixed in the new 2.5.1 release. Thanks!
