### ISSUE TITLE
How to close a inline wysiwyg and return to previous state?

### ISSUE THREAD

**Issue by renatosousafilho** [froala/wysiwyg-editor#1822]
I added a wysiwing with the initOnClick option and a custom buttons to save or cancel the operation. Both way, I need that callback are able to close or back the orginal state before the element turn a wysiwyg. How can i do It, there's somethind linke `closeBox()` method to do it?

**Comment by stefanneculai** [comment]
You can use the destroy method to turn off the editor. To get it back into the state before initOnClick, you should reinitialize it.

**Comment by renatosousafilho** [comment]
In this [documentation](https://www.froala.com/wysiwyg-editor/v1.2/docs/methods) from version there's description from a method. 
```
$('.selector').editable('disable');
```

Why in this new version this method this version doest exists more?

**Comment by stefanneculai** [comment]
It is, but has a different name: `edit.off`. Please see: https://www.froala.com/wysiwyg-editor/docs/migrate-from-v1.

**Comment by renatosousafilho** [comment]
@stefanneculai How i could reinitialize the component without enter a edit mode. I'm trying to do something like it:

```javascript
$.FroalaEditor.DefineIcon('cancel', {NAME: 'close'});
$.FroalaEditor.RegisterCommand('cancelButton', {
    title: 'Cancel',
    icon: 'cancel',
    callback: function() {
        //here I close the editor but it should be enable to open again.
        $("#froala-editor").froalaEditor('destroy');
    }
});
$('#froala-editor').froalaEditor({
    initOnClick: true,
    toolbarButtons: ['bold', 'italic', 'underline', '|', 'subscript', 'superscript', 'indent', 'outdent', 'fontSize', 'insertImage', 'insertLink', 'insertTable', '|',, 'cancelButton']
});
```

**Comment by stefanneculai** [comment]
@renatosousafilho for tech support please reach us via our website: https://wysiwyg-editor.froala.help/hc/en-us
