### ISSUE TITLE
Error - Broken @import declaration of "node_modules/froala-editor/css/froala_editor.css" gulp-clean-css: 'C:\<somedirectory>\<somename>.component.css':undefined

### ISSUE THREAD

**Issue by webtechy** [froala/wysiwyg-editor#1823]
#### Expected or Desired Behavior
Expected to be able to import additional CSS into the SCSS into a SharePoint (Yeoman) project (SPFx).

#### Observed Behavior
Receiving the following error:

> Error - Broken @import declaration of "node_modules/froala-editor/css/froala_editor.css"
gulp-clean-css: 'C:\<somedirectory>\<somename>.component.css':undefined

#### Steps to Reproduce
As per the following:

```
//@import "../node_modules/bootstrap/scss/bootstrap"; // SASS version
@import "../../../../node_modules/bootstrap/dist/css/bootstrap.min.css"; // CSS version

/* You can add global styles to this file, and also import other style files */
@import "~@progress/kendo-theme-default/scss/all";

/* Import Froala CSS */
//@import "../../../../font-awesome/css/font-awesome.min.css"; <-- ERROR (workaround below)
@import "~font-awesome/scss/font-awesome.scss";
//@import "~froala-editor/css/froala_editor.pkgd.min.css"; <-- ERROR
@import "~froala-editor/css/froala_editor.pkgd.css"; <!-- ERROR
```

Any ideas much appreciated. My feeling is this is caused by some minification. However, I am unclear how to disable this in a SharePoint Yeoman project (gulp/webpack). For example, to disable the CSS minification I have tried:

```
config.module.loaders.push([
      { test: /\.(woff|woff2)$/, loader: "url-loader?limit=10000&mimetype=application/font-woff" },
      { test: /\.css$/, loader: "css-loader?-minimize!css-loader" },
]);
```

Or perhaps something along the lines of the following is needed?

```
gulp.task('gulp-clean-css', function() {
  return gulp.src('styles/*.css')
    .pipe(cleanCSS({compatibility: <somethinghere>}))
    .pipe(gulp.dest('dist'));
});
```

**Comment by stefanneculai** [comment]
It looks like this is an error from `gulp-css-import` rather than from Froala Editor. The editor CSS files are regular CSS files, nothing special there.
