### ISSUE TITLE
Delay before getting contentChange event is quite long

### ISSUE THREAD

**Issue by JSteunou** [froala/wysiwyg-editor#1826]
I imagine you did a debounce on key events and maybe on content change, but I found the delay quite long. Is it possible to make it shorter or at least configurable?

**Comment by stefanneculai** [comment]
Sure, please see: https://www.froala.com/wysiwyg-editor/docs/options#typingTimer.

**Comment by JSteunou** [comment]
Actually I was wondering if it was the same, thank you.

Why can we set a value below 500? I would to be able to set it to 150.

**Comment by stefanneculai** [comment]
Under 500 you would kill browser performance.

**Comment by JSteunou** [comment]
I figured out the debounce is for performance reason but as I am not using a lot of formating features I would like to have the liberty to test for myself the minimum delay I could set to improve UX without compromising performance.

**Comment by JSteunou** [comment]
> Under 500 you would kill browser performance.

Can you let me judge of that in my app and make it configurable?

**Comment by JSteunou** [comment]
In fact, even if the doc says it cannot be set under 500, it is possible. I just set it to 150 and it works very well. No performance issue at the moment, but like I said, I do not use a lot of plugins & features, and the editable texts are not that big.

**Comment by hariharasuthan-balaji** [comment]
@stefanneculai Any way to detect if the contentChange task is running ? As in http://ember-concurrency.com/api/Task.html

**Comment by rizalrhmn** [comment]
I'm experiencing issue with this. I'm using froala for chat messages that the user is so fast typing and just enter quickly to send the message. Because of the delay, it's quite often we got the model is still undefined. 

just like what @hariharasuthan-balaji said, Is there any method to detect contentChange task is running before we do some action with the model?

**Comment by yellow1912** [comment]
Not sure why this issue is closed. I think it's nice to detect this change while the user is still typing as well (not only when they pause). It's useful for certain usecases when you have to do live-update of some content for example.

**Comment by ychcg** [comment]
> I'm experiencing issue with this. I'm using froala for chat messages that the user is so fast typing and just enter quickly to send the message. Because of the delay, it's quite often we got the model is still undefined.
> 
> just like what @hariharasuthan-balaji said, Is there any method to detect contentChange task is running before we do some action with the model?
> 
> Or for this case, how's the best practice to accomplish this?

I solved this problem with a fake.

when user stroke enter button, it submit after 300ms.


```js

//froalaOption
<Froala
  config = {{
    typingTimer: 0,
  }},
  events : {
    keydown(event) {
     if (event.key === "Enter") {
      window.setTimeout(handleSubmit, 300);
    }
  },
}
/>
```

**Comment by ha-vo-giang** [comment]
### ### ### _**ádasd**_
