### ISSUE TITLE
Inline Edit - Video Issue After Latest Pull

### ISSUE THREAD

**Issue by Akkadius** [froala/wysiwyg-editor#1829]
##### Expected behavior.
Editor should allow regular editing

##### Actual behavior.
Editor focuses on video and does not let off

##### Steps to reproduce the problem.
Inline Edit initialization using Ctrl + E keypress

##### Browser.
Chrome

Issue that I am having now on one of my pages, is that when I edit a page with a Youtube video, the editor is completely blanked out of options, and it looks like scripts are frozen on the video, I can't click out or anything.

I have a video reproducing this

https://dl.dropboxusercontent.com/u/50023467/dl/wiki/froala_issue.mp4

I don't have any javascript errors or anything, but it won't bring that video out of focus.

The source HTML for this is:

http://wiki.akkadius.com/i?M=Pastebin&Paste=lPmbrb2F

I'm on the latest git code

Does the same thing on a fresh page: https://dl.dropboxusercontent.com/u/50023467/dl/wiki/froala_video_issue_2.mp4

Please advise

**Comment by stefanneculai** [comment]
This doesn't look like an editor problem but rather a CSS conflict inside your app. Please reach us via tech support.

**Comment by Akkadius** [comment]
Standalone reproduction: http://codepen.io/anon/pen/jBwoRv

**Comment by Anexon** [comment]
Same issue here, would you mind tell how you solved it?

**Comment by stefanneculai** [comment]
@Anexon please make sure you are including the `froala_style.min.css` file and that you are using the latest editor version.

**Comment by Anexon** [comment]
I'm using angular-froala-wysiwyg but found this thread. 
Where should I put that file?
