### ISSUE TITLE
Pluralize 'Row' when multiple selected

### ISSUE THREAD

**Issue by jeremylynch** [froala/wysiwyg-editor#1831]
<img width="925" alt="screen shot 2017-03-13 at 5 08 24 pm" src="https://cloud.githubusercontent.com/assets/3665457/23844716/c132ab2e-080f-11e7-9a1b-2b88155b1f9a.png">

When Multiple cells are selected, 'Delete Row' should be pluralized ('Delete Rows')

**Comment by stefanneculai** [comment]
Unfortunately, in the current implementation of the editor dropdowns that is not possible. I marked it as a `feature-request` and it is in our attention for further iterations.
