### ISSUE TITLE
Pressing `delete` with multiple table cells selected fails. 

### ISSUE THREAD

**Issue by jeremylynch** [froala/wysiwyg-editor#1832]
![ezgif com-video-to-gif 7](https://cloud.githubusercontent.com/assets/3665457/23845483/2403ac04-0814-11e7-8d0f-097b5110932e.gif)

Pressing `delete` when multiple cells selected fails. 

Steps to reproduce: 

1. Select at least two cells in a table
2. Select-all Keyboard shortcut: `CMD + A` or `CNTRL + A`
3. Keyboard: `delete`

**Comment by stefanneculai** [comment]
Right, the cells should deselect and delete key should work as usually.
