### ISSUE TITLE
Option to show align buttons in toolbar (not dropdown)

### ISSUE THREAD

**Issue by jeremylynch** [froala/wysiwyg-editor#1834]
##### Expected behavior.
<img width="128" alt="screen shot 2017-03-13 at 7 48 09 pm" src="https://cloud.githubusercontent.com/assets/3665457/23849133/09073f9e-0826-11e7-88fb-345547d2002e.png">

##### Actual behavior.
<img width="74" alt="screen shot 2017-03-13 at 7 48 46 pm" src="https://cloud.githubusercontent.com/assets/3665457/23849142/1737888a-0826-11e7-92b6-2bd261f23825.png">

**Comment by stefanneculai** [comment]
This is not built-in at this moment, however you could create some custom buttons for that. You can find something similar here: https://wysiwyg-editor.froala.help/hc/en-us/articles/115001232345-Add-button-for-H1-and-H2-in-the-editor-toolbar.

**Comment by jeremylynch** [comment]
The only issue with this, is **showing the format of the selected text**. 

I think there is great value in having features that are consistent with Microsoft word for user friendliness reasons. 

Is this feature something that is planned for Froala?
