### ISSUE TITLE
Clear Formatting button doesn't clear blockquotes

### ISSUE THREAD

**Issue by irphilli** [froala/wysiwyg-editor#1835]
##### Expected behavior.
"Clear Formatting" button clears blockquotes

##### Actual behavior.
Blockquotes remain after pushing "Clear Formatting"

##### Steps to reproduce the problem.
1. Use the "Quote" button to create a block quote
2. Enter some text (optional)
3. Highlight text or place cursor in blockquote
4. Push "Clear Formatting" Button

##### OS.
MacOS Sierra

##### Browser.
Chrome Latest

**Comment by stefanneculai** [comment]
This is the designed behavior. Quotes are considered block tags and like headings they are not removed using the Clear Formatting button.

**Comment by irphilli** [comment]
Ahh, ok.  That makes sense.  Thanks!
