### ISSUE TITLE
Firefox: Extra blockquote when pressing enter

### ISSUE THREAD

**Issue by irphilli** [froala/wysiwyg-editor#1836]
##### Expected behavior.
While creating a quote, pressing enter should not result in an extra blockquote.

##### Actual behavior.
Pushing enter creates an additional blockquote below the cursor.

##### Steps to reproduce the problem.
1. In Firefox, push the quote button
2. Hit Enter

##### OS.
MacOS Sierra

##### Browser.
Firefox Latest

**Comment by dswitzer** [comment]
This happens in Windows 10 too:

![firefox_block_quote_issue](https://cloud.githubusercontent.com/assets/900497/23872909/7b9a2258-0806-11e7-8579-232886ac2f17.gif)
