### ISSUE TITLE
ESC key not exiting fullscreen

### ISSUE THREAD

**Issue by jeremylynch** [froala/wysiwyg-editor#1839]
##### Expected behavior.
`ESC` should exit fullscreen

##### Actual behavior.
`ESC` does nothing when in fullscreen

##### Browser.
Chrome

**Comment by stefanneculai** [comment]
Allowing to exit from fullscreen using `ESC` is not a good thing speaking for accessibility and UX. ESC is designed to close modals and popups inside the editor so it would create confusion to have it do that for fullscreen.
