### ISSUE TITLE
Testing Inserting Image from Mobile editor.froala.com

### ISSUE THREAD

**Issue by cmaxnow** [froala/wysiwyg-editor#184]
I like your product and would like to use it for my website. I have a lot of users that use their phones to post. I have a Andriod (4.1.2) Motorola Bionic that is a couple years old, but up to date :)

I can't upload an image from my phone using the Inline or Dark Theme on this page http://editor.froala.com/#inline-demo 

I am able to do this using my Laptop... 

Should I be able to do this with your Test version?

Thanks,
Cmaxnow

**Comment by anant1992** [comment]
On mobile mode, as soon as you type, the cursor moves inside the toolbar and the typed text on the 1st line isnt visible
