### ISSUE TITLE
2.5.1 not published to npm

### ISSUE THREAD

**Issue by Panman8201** [froala/wysiwyg-editor#1840]
I see that [2.5.1 was released yesterday](https://github.com/froala/wysiwyg-editor/releases/tag/v2.5.1) (with [changelog](https://www.froala.com/wysiwyg-editor/changelog#2.5.1)) but it appears that it [wasn't published to npm](https://www.npmjs.com/package/froala-editor) (still reporting 2.5.0).

**Comment by stefanneculai** [comment]
It is published now. We usually publish it 2-3 days after the official release is made on our website.

**Comment by Panman8201** [comment]
Interesting, I didn't realize that. With the ember addon switch from bower to npm for the editor dep, it became more apparent to me now. Thanks for the info!
