### ISSUE TITLE
Further paste from Word issues for tables and font family.

### ISSUE THREAD

**Issue by markedmondson** [froala/wysiwyg-editor#1841]
##### Expected behavior.
The attached document should format pretty closely to its visual output in Word.

[Froala issue.docx](https://github.com/froala/wysiwyg-editor/files/842917/Froala.issue.docx)

##### Actual behavior.
Font family settings and table rowspans are lost.

Word:
<img width="553" alt="screenshot 2017-03-14 15 27 44" src="https://cloud.githubusercontent.com/assets/1653699/23925068/cdf594fa-08ca-11e7-9259-dda5ee06c6ec.png">

Froala:
<img width="1236" alt="screenshot 2017-03-14 15 25 23" src="https://cloud.githubusercontent.com/assets/1653699/23925053/b0931cac-08ca-11e7-9e78-a44f2867eb67.png">

##### Steps to reproduce the problem.
Copy and paste attached document into editor with Paste from Word plugin enabled.

##### OS.
OSX Sierra

##### Browser.
Chrome 56

**Comment by stefanneculai** [comment]
The Calibri font family doesn't show up because Calibri font is not loaded on the browser. The fonts from Word would be rendered exactly only if they are loaded on the page as well.

We're going to make some further checks for the table problem.

**Comment by markedmondson** [comment]
Calibri aside, the source shows that the span isn't correctly capturing the entire text block:

```html
<p><span style="font-size:15px;font-family:Calibri;">This gets incorrectly formatted as Times.</span> This is correctly Calibri</p>
```

Note the position of the span.

**Comment by florinpopescu** [comment]
Hi @markedmondson,

Font family and rowspan problem are fixed.
The information about the bold h1 is missing from the pasted html. But this is only for h1. For h2, h3, etc it works perfectly. I think the problem is because in the browser the unbolded h1 looks bolded.
