### ISSUE TITLE
Increase indent/decrease indent is not working correctly if multiple text lines are marked as Ordered List

### ISSUE THREAD

**Issue by binod12** [froala/wysiwyg-editor#1842]
##### Expected behavior.
Increase indent/decrease indent is not working correctly if multiple text lines are marked as Ordered List

##### Actual behavior.
All the selected Ordered list should be indented together

##### Steps to reproduce the problem.
1) Add multiple lines in the correspondence text
2) Select all and click on 'Ordered' option. The lines should be marked as ordered
3) Now select all lines and click on "Increase Indent". All lines should be moved to right

![1842](https://cloud.githubusercontent.com/assets/6301387/23961849/340fa098-09d2-11e7-886e-3b10e57260be.gif)

##### OS.
Windows 10

##### Browser.
All browsers

**Comment by stefanneculai** [comment]
This is the intended behavior. The nested lists should be inside another list item tag in order to be valid HTML.

**Comment by thonglee** [comment]
Hi @stefanneculai,
I think, the intended behavior that you explain is wrong logic. You can check with one note, Microsoft Word (office), Google doc, Apple Note ...
The right logic should be the @binod12 expectation.

**Comment by stefanneculai** [comment]
@thonglee MS Word, Google Docs, etc. are not generating HTML valid out of it and that's why the list indentation works differently at them. We consider the behavior we currently have in the editor as the best one for generating a valid HTML output.
