### ISSUE TITLE
Enhancement: Ordered list customization

### ISSUE THREAD

**Issue by irphilli** [froala/wysiwyg-editor#1843]
It would be nice if numbered lists allowed us to customize the style (i.e. numbers vs. roman numerals vs. letters). For an example, see attached word doc (even better if Froala can handle copy/paste from that document)

[bullets.docx](https://github.com/froala/wysiwyg-editor/files/845308/bullets.docx)

**Comment by stefanneculai** [comment]
For this moment we consider this a `feature-request` and might be implemented in the following period.

**Comment by IndrajaPunna** [comment]
Just want to know by when this enhancement request is going to be implemented.

**Comment by stefanneculai** [comment]
@IndrajaPunna I don't have an estimate to provide for this at this moment.

**Comment by nodefiend** [comment]
bump !

we would love to have this too!

**Comment by trevordevore** [comment]
My company would like to see this as well.

**Comment by daveywc** [comment]
Plus one from us as well - this is a requirement from our customers.

**Comment by stefanneculai** [comment]
We've just put together a public roadmap with the most popular features. 😍 There you can vote your favorite one, provide feedback or make new suggestions: https://wysiwyg-editor-roadmap.froala.com/public.
