### ISSUE TITLE
Increase Indent on image causes images to be resized and disappear at the end

### ISSUE THREAD

**Issue by binod12** [froala/wysiwyg-editor#1844]
##### Expected behavior.
Image should not be resized when reaching the right margin when we use increase indent on any image.

##### Actual behavior.
The image size is being reduced and at last it disappears

##### Steps to reproduce the problem.
See the attached recording
![1844](https://cloud.githubusercontent.com/assets/6301387/23961311/8c7d30ee-09d0-11e7-9102-ef503fb3220e.gif)
##### OS.
Windows 10

##### Browser.
All browsers

**Comment by stefanneculai** [comment]
We consider this a correct behavior. The images are designed to take the maximum width of the parent.
