### ISSUE TITLE
Script tag is executing when switching between code view and the normal view

### ISSUE THREAD

**Issue by drdaemos** [froala/wysiwyg-editor#1846]
##### Expected behavior.
Switching between the code view and the normal view should not cause script tags to execute, otherwise this editor can't be used to write JavaScript.

The problem lies in editor.html.set() function, which internally uses jQuery .html() function, and that leads to script execution.

The problem can be solved by replacing html() call with the assignment via innerHTML property and I don't see any drawbacks to that solution right now.

##### Actual behavior.
Switching between modes executes Javascript code inside <script> tags.

##### Steps to reproduce the problem.
1. Set froala options to allow script tags (htmlRemoveTags: []).
2. Open the page with the editor
3. Switch to the code view
4. Write in the editor

```
<script>alert(1);</script>
```
5. Switch back to the normal view
6. Alert happens.

##### OS.
MacOS Sierra 10.12.3 (16D32) (it is irrelevant though)

##### Browser.
Google Chrome 56.0.2924.87 (64-bit)

P.S. I'm an OEM license owner, can provide you with the key to prove it.

**Comment by stefanneculai** [comment]
This is the intended behavior. All the html code which is put inside the code view should be rendered on editing view.

Please read more about it here: https://wysiwyg-editor.froala.help/hc/en-us/articles/115000428829-Why-is-the-script-tag-being-removed-.

**Comment by drdaemos** [comment]
@stefanneculai, well, why not render it via innerHTML? What is the reason to execute the scripts from the code view? innerHTML does exactly the same thing except it doesn't execute any underlying scripts.

What is the reason for allowing to modify **htmlRemoveTags** option when you can't really use for containing the script tags?

I don't mind that <script> should be removed by default, no problems. But I can't really configure it in my software. I don't really care about XSS attacks in my particular case because I implement other ways of protection.

**Comment by drdaemos** [comment]
Ok, I get your point about rendering the code to achieve the real WYSIWYG effect. But I really wish it to be configurable in the next releases because there are other use cases for that feature. I think it would really improve the great software you've already made.

**Comment by stefanneculai** [comment]
@drdaemos makes sense. I marked this as an `enhancement` and we'll put an option for it.

**Comment by drdaemos** [comment]
Thank you, Stefan, this is the best news of the day for me.

**Comment by drdaemos** [comment]
I guess it should be reopened because in 2.7.6 we're again experiencing this behavior.

**Comment by stefanneculai** [comment]
@drdaemos this should be fixed in version 2.8.1.

**Comment by drdaemos** [comment]
Well, I can repro it on https://jsfiddle.net/vt9j2fcb/1/.

**Comment by drdaemos** [comment]
Oh, sorry about that, i've discovered the **htmlExecuteScripts** option which is enabled by default.
