### ISSUE TITLE
Copy-pasting should not filter certain tags

### ISSUE THREAD

**Issue by jeremylynch** [froala/wysiwyg-editor#1850]
Occasionally, some websites have abnormal html tags (eg. `<article></article>`)
```html
<p>First Sentence</p>
<article>
    <p>Second sentence</p>
</article>
```
**The problem**
When copy-pasting from these sites, these tags are added into Froala. When backspacing at the start of `Second sentence`, nothing happens. 

Should tags such as `article` be blacklisted?

**Comment by stefanneculai** [comment]
You could use the `htmlDeniedTags` for that.

**Comment by jeremylynch** [comment]
@stefanneculai, I am aware of this. 

Shouldn't this be included in the global list of denied tags?

**Comment by jeremylynch** [comment]
@stefanneculai have you had the chance to review above? Thank you

**Comment by stefanneculai** [comment]
@jeremylynch no, it shouldn't because there might be cases when someone wants to use the ARTICLE tag.
