### ISSUE TITLE
Chrome: Aligning images scrolling to top when iframe:true

### ISSUE THREAD

**Issue by firstladymb** [froala/wysiwyg-editor#1852]
##### Expected behavior.
Editor does not scroll to top when aligning images.

##### Actual behavior.
Editor scrolls to top when aligning images.

##### Steps to reproduce the problem.
Replicated in [JSFiddle](https://jsfiddle.net/firstladymb/vokpqbwu/) loading 2.5.2

1. Add enough text to scroll the editor.
2. Add an image.
3. Align image. Editor scrolls to top.

![Align Image Scroll](http://g.recordit.co/VGZutt07TR.gif)

##### OS.
macOS Sierra Version 10.12.3

##### Browser.
Chrome Version 56.0.2924.87 (64-bit)

**Comment by irphilli** [comment]
I was able to confirm this in Chrome and Firefox, but it looks like it still happens in IE.

**OS**
Windows 7

**Browser**
IE 11.0.38

**Comment by irphilli** [comment]
@stefanneculai Would you like a new issue for the IE-only bug?

**Comment by stefanneculai** [comment]
@irphilli please make sure you are using the master version. It is fixed on the master version.
