### ISSUE TITLE
contentChanged event provides no info

### ISSUE THREAD

**Issue by nikita-korovin** [froala/wysiwyg-editor#1853]
##### Expected behavior.
I want to be able to retrieve what was changed by user, to finally obtain something like this:
`{
   element: span#bla,
   textBefore: 'Hello world',
   textAfter: 'Hello worl' // 1 char erased
}`

##### Actual behavior.
This is the console.log(e) output, I see no useful info for what I want

`r.Event
{
altKey:undefined
bubbles:undefined
button:undefined
buttons:undefined
cancelable:undefined
changedTouches:undefined
char:undefined
charCode:undefined
clientX:undefined
clientY:undefined
ctrlKey:undefined

// this is the entire wysiwig html content
currentTarget:div.text-editor.fr-box.fr-basic.fr-top 
data:undefined
delegateTarget:div.text-editor.fr-box.fr-basic.fr-top
detail:undefined
eventPhase:undefined
handleObj:Object
// and so on, I don't see any useful info
}`

##### Steps to reproduce the problem.
`$('.text-editor')
.on('froalaEditor.contentChanged', function(e, editor){
                console.log(e);
            })`

##### OS.
Windows 10

##### Browser.
Chrome

**Comment by stefanneculai** [comment]
@nikita-korovin thank you for the `feature-request` on this. We use this repo for bug tracking only, therefore I am going to close this for now.
