### ISSUE TITLE
FroalaEditor_Image::delete($filename) is not limited to a specific directory

### ISSUE THREAD

**Issue by AMC** [froala/wysiwyg-editor#1854]
##### Expected behavior.
File to be deleted from a specific directory or subdirectory

##### Actual behavior.
Any file can be deleted

##### Steps to reproduce the problem.
using curl and the expected endpoint, I can delete any file on the webserver
`curl -X POST "http://example.com/delete_image.php" -F "src=index.php"` 

##### OS.
All OSes

##### Browser.
All Browsers

#### Suggested Fix.
Include a directory parameter similar to `FroalaEditor_Image::upload($fileRoute, $options)` or `FroalaEditor_Image::getList($fileRoute, $thumbpath)`

Make sure you check for relative paths to prevent malicious path traversal. PHPs realpath() isn't always supported so you might just throw an exception if relative path strings are found since they should not occur in typical usage.

You could also document this and recommend the user add in some level of validation to prevent malicious usage.

**Comment by stefanneculai** [comment]
@AMC would you mind opening this issue on the PHP SDK: https://github.com/froala/wysiwyg-editor-php-sdk? Thank you.
