### ISSUE TITLE
Cursor jumps to start of editor after deleting link

### ISSUE THREAD

**Issue by jeremylynch** [froala/wysiwyg-editor#1855]
![ezgif com-video-to-gif 9](https://cloud.githubusercontent.com/assets/3665457/24086802/dac0bf5c-0d61-11e7-9b10-1b279e652243.gif)

**Comment by stefanneculai** [comment]
@jeremylynch are you able to reproduce this on our website?

**Comment by jeremylynch** [comment]
This video was recorded on your website

**Comment by stefanneculai** [comment]
What browser and OS are you using?

**Comment by jeremylynch** [comment]
Mac OS
Chrome Version 56.0.2924.87 (64-bit)

Make sure your content is as follows:
```
<p>Sample content [<a href="https://www.google.com">5</a>]</p>
```
