### ISSUE TITLE
When link HREF is same as anchor content, behaviour abnormal

### ISSUE THREAD

**Issue by jeremylynch** [froala/wysiwyg-editor#1856]
This issue only occurs when the a HREF is the same as the content. eg. `<a href="www.google.com">www.google.com</a>`
![ezgif com-video-to-gif 10](https://cloud.githubusercontent.com/assets/3665457/24098830/3436747c-0db8-11e7-9f7e-8b4d8eaafff5.gif)

Here is the HTML from the above example: 
```html
<p>Sample <a href="www.google.com">www.google.com</a> content</p>
```

**Comment by stefanneculai** [comment]
It is not an issue. When using the URLs plugin, the editor is designed to convert texts which are links to `<a>` tags.

**Comment by jeremylynch** [comment]
There are still bugs with this behaviour: look what happens to the cursor in the following: 
![ezgif com-video-to-gif 11](https://cloud.githubusercontent.com/assets/3665457/24133297/99c120be-0e47-11e7-931e-31e269383f81.gif)

**Comment by jeremylynch** [comment]
@stefanneculai have you had opportunity to review above? 

Thanks
