### ISSUE TITLE
Sticky toolbar in chrome (57) not working

### ISSUE THREAD

**Issue by eitan-i** [froala/wysiwyg-editor#1857]
On chrome 57, froala 2.5.1 - sticky toolbar not working for me. 

OS: Windows 10, Chrome Version 57.0.2987.110

**Comment by eitan-i** [comment]
by the way... in froala v2.4.1 the sticky toolbar works fine on the same chrome version.

**Comment by stefanneculai** [comment]
It is working fine on our checks. Could you please clear your cache? Thank you.

**Comment by stefanneculai** [comment]
Closing this as we discussed the problem further on email and it's editor related.
