### ISSUE TITLE
Problem when page contains multiple body tags (SVG)

### ISSUE THREAD

**Issue by warpdesign** [froala/wysiwyg-editor#1863]
I am using Froala in an app that contains some SVG tags. The problem is that SVG can contain html, and particualrly <body> tags. For example this is a valid document:

    <!doctype html>
    <html>
    <body>
    <svg width="400px" height="300px" xmlns="http://www.w3.org/2000/svg"xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1">
    <switch>
    <foreignObject requiredFeatures="http://www.w3.org/TR/SVG11/feature#Extensibility" width="100" height="50" class="fobj">
    <body xmlns="http://www.w3.org/1999/xhtml">
    <div>
    <p>Here is some html embeded into the SVG</p>
    </div>
    </body>
    </foreignObject>
    <text>sdsdg</text>
    </switch>
    </svg>
    </body>
    </html>

When using Froala in such a page, some Froala elements (like the color popup) gets injected into the main document's page, but also into every SVG's <body> tags.

Looking at the source code, it seems Froala assumes $('body') always returns the single document's root body element. But in my case it returns the document's body element and all body elements found inside svg/foreignObject elements.

**Comment by stefanneculai** [comment]
It doesn't look like a problem from the editor. According to the W3C specs, only a body tag is allowed inside a HTML page. By default, the browser should remove the BODY tag from SVG tag. How are you initializing the editor in order to keep it?

**Comment by warpdesign** [comment]
The browser doesn't always remove the multiple body tags, see this demo page for example: [http://resources.jointjs.com/demos/bpmn](http://resources.jointjs.com/demos/bpmn)

Typing `$('body')` in the console returns multiple body tags:

    $('body')
    > [body, body, body, body, body, body, body, body, body, body, body, prevObject: jQuery.fn.init(1)]

I don't know how these body tags were created, but that's how I end up. And this makes froala append elements everywhere on my page.

**Comment by stefanneculai** [comment]
@warpdesign could you make a jsFiddle?

**Comment by warpdesign** [comment]
@stefanneculai I wans't able to isolate the problem with a simple jsFiddle: the library seems to append elements in the SVG by JavaScript and this is were the body seems to be added.

But looking at this demo page, the problem seems to be obvious.

**Comment by stefanneculai** [comment]
@warpdesign We have tried to insert somehow that SVG on the page, but nothing seems to work. The fix to be applied inside the editor code seems pretty basic, however we cannot just make it without having the possibility to test this. If you can find a way to have such a SVG structure inserted, we would be happy to reopen this and look into it.

**Comment by warpdesign** [comment]
@stefanneculai Here is a simple example how to have two body tags inside a page. Hope this is what you expected and it is enough to reopen the issue: [https://jsbin.com/xelaqodife/edit?html,js,console,output](jsbin)

Notice how the console.log printss 2.

**Comment by stefanneculai** [comment]
Last commit fixes it.
