### ISSUE TITLE
Copy/Paste feature from word and html page

### ISSUE THREAD

**Issue by tomalex0** [froala/wysiwyg-editor#1867]
Demo :  https://jsfiddle.net/tomalex0/q7cc3h3u/3/

##### Expected behavior.
Have similar experience for paste to froala  even if copied from word or html page

##### Actual behavior.
Copying from word and pasting to froala still hold font-family

##### Steps to reproduce the problem.
(Describe the steps to reproduce the problem here)

![ezgif-1-f7c0bd8972](https://cloud.githubusercontent.com/assets/208168/24225225/930e5f2c-0f1c-11e7-8bec-103f5e3446c8.gif)

MP4 : https://github.com/tomalex0/files/blob/master/froala.mp4

##### OS.
Windows 7

##### Browser.
Google Chrome
Version 56.0.2924.87

**Comment by stefanneculai** [comment]
There are special options for Word paste:
```js
   wordDeniedTags: [],
   wordDeniedAttrs: [],
   wordAllowedStyleProps: ['font-family', 'font-size', 'background', 'color', 'width', 'text-align', 'vertical-align', 'background-color']
```

**Comment by tomalex0** [comment]
Thanks @stefanneculai , really missed to look into all options :)
