### ISSUE TITLE
Deleting certain emoji characters leaves data behind causing invalid UTF-8 characters/strings

### ISSUE THREAD

**Issue by theknet** [froala/wysiwyg-editor#1868]
##### Expected behavior.
Adding an emoji then deleting it should remove all character data for the emoji

##### Actual behavior.
When using certain emoji's (for instance the pumpkin emoji) some data is left behind. This appears invisible in Safari or a question mark character in Chrome. In Safari you'll notice the placeholder text does not appear until you press backspace again.

##### Steps to reproduce the problem.
Open an instance of Froala (tested in the demos page of Froala website)
Add the pumpkin emoji (other's may cause the issue but this is 100% reproducible)
Delete the pumpkin emoji

##### OS.
macOS Sierra 10.12.3

##### Browser.
Safari 10.0.3
Chrome 57.0.2987.98 (64-bit)

**Comment by stefanneculai** [comment]
@theknet could you please make a recording for this?

**Comment by theknet** [comment]
Sure thing. Please see attached.

[Froala Issue (Drive)](https://drive.google.com/open?id=0BxBCI3wwOKYibGljYUdGU2JvY0U)
