### ISSUE TITLE
Can't delete table with keyboard

### ISSUE THREAD

**Issue by GMiLL5** [froala/wysiwyg-editor#1869]
##### Expected behavior.
Selecting text through a table should delete the table

##### Actual behavior.
Selecting text through a table deletes the text in the table, but the table remains

##### Steps to reproduce the problem.
![tablebug](https://cloud.githubusercontent.com/assets/1800407/24263741/d1fa084c-0fdc-11e7-9137-494a690691eb.gif)

##### OS.
OSX 10.10.5

##### Browser.
Firefox 52.0.1

##### Notes:
This does work properly in Chrome

**Comment by GMiLL5** [comment]
Another issue I noticed that might be related, let me know if I should make a separate ticket for this one:

What I'm trying to do is programmatically put the selection around a table so if the user does any keyboard input, the table will be removed. I have that working properly, but when the user enters keyboard input, every row except the first and last are being removed (in all browsers).

Am I doing something wrong or is there a bug in `editor.selection.remove( )`?

Here's some code example
```
// Assume we were given table
editor.selection.clear( );

var id = Date.now( );
var start = $( $.FE.START_MARKER );
var end = $( $.FE.END_MARKER );

// Make sure ids match for selection.restore
start.data( 'id', timestamp );
end.data( 'id', timestamp );
start[ 0 ].setAttribute( 'data-id', timestamp );
end[ 0 ].setAttribute( 'data-id', timestamp );

table.before( start );
table.after( end );

editor.selection.restore( );
```

Then pressing delete/etc

**Comment by florinpopescu** [comment]
Unfortunately this is how Mozilla handles table selection on contenteditable. Here is an example https://jsfiddle.net/wL8md0fr/ . You must write in the table first to reproduce this.

**Comment by GMiLL5** [comment]
@florinpopescu Thanks for the info! Any thoughts on why my second snippet wouldn't be working? It seems to delete the majority of the table but leaves the first & last rows in the editor box

**Comment by stefanneculai** [comment]
It is happening because of the Mozilla limitation on table selection.

**Comment by GMiLL5** [comment]
@stefanneculai That specific issue seems to happen in both Chrome & Safari as well

**Comment by stefanneculai** [comment]
@GMiLL5 could you please make a jsFiddle for it? Thank you.

**Comment by GMiLL5** [comment]
Sure thing! https://jsfiddle.net/y7t1174d/1/ 

Click the icon in the toolbar which runs the code I had above - then when you use keyboard input it seems to delete every row in the table except the header/footer and then puts your cursor in the first cell

**Comment by GMiLL5** [comment]
@stefanneculai Was there anything you could see in the jsFiddle I shared?

**Comment by GMiLL5** [comment]
@stefanneculai Swinging back around to this, I was able track it down finally to the `selection._processNodeDelete` method

In my case, it was the initial if that was getting tripped up for td/th cells: `editor.node.hasClass(contents[0], 'fr-marker')` was returning false because there's nested nodes.

I modifed this check: 
```
// Node is TD or TH.
if (['TD', 'TH'].indexOf($node.get(0).tagName) >= 0 && $node.find('.fr-marker').length == 1 && editor.node.hasClass(contents[0], 'fr-marker')) {
   $node.attr('data-del-cell', true);
}
```

to instead read:
```
if (['TD', 'TH'].indexOf($node.get(0).tagName) >= 0 && $node.find('.fr-marker').length == 1 ) {
	var marker = $node.find( '.fr-marker' ).get( 0 );

	if ( $node.is( ':first-child' ) === true ) {
		while ( marker !== null && $node.is( marker ) === false ) {
			marker = marker.parentNode;

			if ( marker.previousSibling !== null ) {
				marker = null;
			}
		}
	}
	else if ( $node.is( ':last-child' ) === true ) {
		while ( marker !== null && $node.is( marker ) === false ) {
			marker = marker.parentNode;

			if ( marker.nextSibling !== null ) {
				marker = null;
			}
		}
	}
	else {
		marker = null;
	}

	if ( $node.is( marker ) === true ) {
		$node.attr( 'data-del-cell', true );
	}
}
```

Which seems to fix it by accounting for nested nodes in the th/td & catches the last cell marker

**Comment by stefanneculai** [comment]
@GMiLL5 thanks for sharing that. Are you still seeing this problem in the latest editor version?

**Comment by GMiLL5** [comment]
@stefanneculai No problem! I am, just updated my fiddle to pull the latest version: https://jsfiddle.net/y7t1174d/2/
