### ISSUE TITLE
Editor on textarea within form tag doesn't allow form tag within editor.

### ISSUE THREAD

**Issue by pijulius** [froala/wysiwyg-editor#1870]
##### Expected behavior.
Keep form tag even if Froala is run on textarea and textarea being within a form tag itself.

##### Actual behavior.
Removes the form tag and replaces it with p tag.

##### Steps to reproduce the problem.
1. Please go here:
https://www.froala.com/wysiwyg-editor/examples/textarea

2. In console run:
$('.fr-box.fr-basic.fr-top').wrap('&lt;form>&lt;/form>');

3. Click Code View in Froala

4. Paste this html code
&lt;form action="https://www.paypal.com/cgi-bin/webscr" method="post">
&lt;input name="cmd" type="text" value="command" />
&lt;/form>

5. Click Code View in Froala again
6. Click Code VIew in Froala again and see form tag being replaced by p tag

##### OS.
Linux Debian

##### Browser.
Firefox 49

**Comment by stefanneculai** [comment]
If you want to use `FORM` tag inside the editor, then it is best to enable the `iframe: true` option.
