### ISSUE TITLE
Bullets & Numbering are added at Left side of editor.

### ISSUE THREAD

**Issue by binod12** [froala/wysiwyg-editor#1872]
##### Expected behavior.
Bullets and numbering should work with the text allignment

##### Actual behavior.
When any list is right aligned, it shows different behavior in different browsers. IE and Chrome behave same, whereas Firefox shows the correct behaviour. 

##### Steps to reproduce the problem.
1. Add some text in 'Correspondence Text'.
2. Click on Align Right.
3. Click on Bullets/Numbering.

##### OS.
Windows 10

##### Browser.
IE 10/11, Firefox 50/51/52, Chrome 57/58
![chrome-1872](https://cloud.githubusercontent.com/assets/6301387/24286391/024d5062-109b-11e7-83e3-27759d72a3ad.gif)
![firefox-1872](https://cloud.githubusercontent.com/assets/6301387/24286392/02a04b1e-109b-11e7-9a5e-7aa3a3d29975.gif)

**Comment by stefanneculai** [comment]
This is the intended behavior. The alignment should be applied to the inner contents of the element.
