### ISSUE TITLE
Image src is escaping blob URLs with multiple colons

### ISSUE THREAD

**Issue by KielAtIgloo** [froala/wysiwyg-editor#1876]
##### Steps to reproduce the problem.

- Have a blob image url with multiple colons in an img tag's src. Ex: blob:https://totallyrealdomain.co/adfad 
- Use html.set to set the editor's content

##### Expected behavior.
The src is not encoded.

##### Actual behavior.
The second colon in the src gets encoded to: blob:https%3A//totallyrealdomain.co/adfad and the image breaks.

##### Related to
https://github.com/froala/wysiwyg-editor/issues/1360

**Comment by stefanneculai** [comment]
See: https://github.com/froala/wysiwyg-editor/issues/1235#issuecomment-251943999.
