### ISSUE TITLE
How can I add new custom button with same predefined method

### ISSUE THREAD

**Issue by BDhara** [froala/wysiwyg-editor#1878]
I want to add new insert image custom button in which popup will open like in inserImage. is there any method which I can directly call to do this?..

**Comment by stefanneculai** [comment]
Sure, there is an example for it on our website: https://www.froala.com/wysiwyg-editor/examples/custom-popup.

**Comment by BDhara** [comment]
I read that but I didn't want like that.. what I need is.. image button with same method call when `insertImage` used..on click same method call of insert image on custom button
