### ISSUE TITLE
Can't capture Backspace or Delete key event

### ISSUE THREAD

**Issue by peca11** [froala/wysiwyg-editor#1879]
##### Expected behavior.
I wanted to add some behaviour when the user presses the "Backspace" or "Delete" key.

##### Actual behavior.
Can't capture the Backspace or Delete key press event

##### Steps to reproduce the problem.
1- On any of the exemples html add this code:
`$('#edit').on('keydown', function(aEvent) {
        if (aEvent.keyCode == 8) {
          console.log('backspace key')
        } else if (aEvent.keyCode == 46) {
          console.log('delete key')
        } else {
          console.log('any other key')
        }
    });
`
2 - Open the html in the browser and click the "Backspace" and "Delete" key.
##### OS.
Win10
##### Browser.
Chrome 56.0.2924.87

**Comment by peca11** [comment]
This also happens with "Enter" key (number 13)

**Comment by stefanneculai** [comment]
That is because there is another event which is triggered before and prevents the keydown to propagate. If you would like to subscribe and be the first who catches the key, you should do it like this:

```js
$(selector).on('froalaEditor.initialized', function (e, editor) {
  editor.events.on('keydown', function () { ... }, true);
}).froalaEditor();
```

**Comment by peca11** [comment]
Perfect, just what I needed! Thanks Stefan!
