### ISSUE TITLE
Video upload does not work in Firefox

### ISSUE THREAD

**Issue by scribblerp9** [froala/wysiwyg-editor#1880]
##### Expected behavior.
Click to upload a video, video should upload and display in editor.

##### Actual behavior.
Video seems to upload, but then get error message "Something went wrong". Works fine in Chrome.

##### Steps to reproduce the problem.
Upload a video file in the Firefox browser

##### OS.
Both WIndows 10 and Mac OSX Sierra

##### Browser.
Firefox 52.0.2

**Comment by stefanneculai** [comment]
This should be fixed on master.
