### ISSUE TITLE
linkAutoPrefix not applied to typed text detected as links

### ISSUE THREAD

**Issue by bboyle** [froala/wysiwyg-editor#1881]
##### Expected behavior.
Typing "www.froala.com" in the editor should create `<a href="http://www.froala.com">www.froala.com</a>` (the linkAutoPrefix config may override the "http://" default)

##### Actual behavior.
`<a href="www.froala.com">www.froala.com</a>` is created. This is not what end users intend.

##### Steps to reproduce the problem.
Type a URL without the protocol (as described above).
Can be reproduced on the live demo here: https://www.froala.com/wysiwyg-editor

Note that using the "Insert Link" dialog works as expected.

##### OS.
Windows 10

##### Browser.
Chrome 56

**Comment by stefanneculai** [comment]
On master, it is designed to follow the protocol of the page, by using `//:`.

**Comment by bboyle** [comment]
is there an ETA on the next release?
(I'm assuming that the fix being in master implies it is not in 2.5.1)

**Comment by jhubert** [comment]
This issue with local network links seems pertinent: https://github.com/froala/wysiwyg-editor/issues/1989

**Comment by LukeHartcher** [comment]
> On master, it is designed to follow the protocol of the page, by using `//:`.

Is it possible to override this behavior somehow? A generated URL of href="//froala.com" is not really usable!?
