### ISSUE TITLE
Editor keeps uploading files to i.froala.com/upload when fileUploadURL is provided

### ISSUE THREAD

**Issue by mcoeur** [froala/wysiwyg-editor#1882]
##### Expected behavior.
As described in the documentation, the editor should send images to the url specified in the configuration object.

##### Actual behavior.
Editor keeps uploading files to i.froala.com/upload

![screen shot 2017-04-03 at 09 43 57](https://cloud.githubusercontent.com/assets/7251472/24599800/2bb09c52-1852-11e7-9d53-66da8a7438c3.png)

##### Steps to reproduce the problem.
I'm loading froala from the CDN (packaged, minified) :

```javascript
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/froala-editor/2.5.1/js/froala_editor.pkgd.min.js"></script>
```

Here is my configuration object:

```javascript
$(function() { $('textarea').froalaEditor({
    fileUploadURL: '/news/upload',
    heightMin:400,
    iframe:true,
  })
});
```

Am I doing something wrong ?

##### OS.
OSX 10.11.6

##### Browser.
Chrome 57.0.2987.133

**Comment by stefanneculai** [comment]
There are different options for fileUploadURL and imageUploadURL.

**Comment by mcoeur** [comment]
Dude, you're the fastest human beeing on the planet when it comes to answering stupid questions =|.
Thanks !
