### ISSUE TITLE
Caret positioned to beginning of input content when focusing via tabbing

### ISSUE THREAD

**Issue by will-newmarch** [froala/wysiwyg-editor#1884]
##### Expected behavior.
When tabbing into a Froala editor which has content, the caret should be positioned at the end of the content as per default browser input behaviour.

##### Actual behavior.
When tabbing into a Froala editor which has content, the caret is positioned at the beginning of the content in the editor.

##### Steps to reproduce the problem.
Tab into a Froala editor which has content, and the caret will be positioned at the beginning of the editor.

##### OS.
Mac

##### Browser.
Chrome

**Comment by stefanneculai** [comment]
Thank you for the suggestion.

**Comment by stefanneculai** [comment]
Browser default behavior is to focus at the end: https://jsfiddle.net/tgnaduwz/. We're going to keep it the way it is now.
