### ISSUE TITLE
Inline editor toolbar doesn't show up in modals

### ISSUE THREAD

**Issue by natcohen** [froala/wysiwyg-editor#1885]
##### Expected behavior.
The inline editor tolbar in a modal should show up when text is selected

##### Actual behavior.
The toolbar appears in the back and the popup (such as color, etc...) have the same problem

##### Steps to reproduce the problem.
https://jsfiddle.net/z8uv8jtj/

##### OS.
OSX 10.12.3

##### Browser.
Chrome 56

**Comment by stefanneculai** [comment]
That is because the modal has a higher zIndex than the editor. Changing it would fix the problem right away. https://jsfiddle.net/z8uv8jtj/1/

**Comment by natcohen** [comment]
@stefanneculai can't you get the z-index of the modal and adapt the one of the toolbar? The quickinsert appears properly!
