### ISSUE TITLE
Unable to resize image correctly inside modals

### ISSUE THREAD

**Issue by natcohen** [froala/wysiwyg-editor#1886]
##### Expected behavior.
When you add the editor inside a modal, you can add an image. But when you try to resize the image, the pointer become sticky and it's impossible to set the size.

##### Actual behavior.
Should behave like editor not in the modal.

##### Steps to reproduce the problem.
- Create bootsrap modal with editor inside
- Add image
- Try to resize it

##### OS.
OSX 10.12

##### Browser.
Chrome 56

**Comment by stefanneculai** [comment]
There is actually one in our examples: https://github.com/froala/wysiwyg-editor/blob/master/html/3rd-party/bootstrap/modal.html. It appears to work just fine. Are you having the problem with this example or could you provide a jsFiddle?

**Comment by natcohen** [comment]
@stefanneculai well... Look at my other suggestion: https://github.com/froala/wysiwyg-editor/issues/1888 I can't reproduce it in jsfiddle!

**Comment by natcohen** [comment]
I've tried with bootstrap v4
