### ISSUE TITLE
Pasting image from clipboard adds base64 encoded image into editor

### ISSUE THREAD

**Issue by will-newmarch** [froala/wysiwyg-editor#1889]
Not so much a bug but a difficult scenario to handle currently. If it was optional to add the base64 version to editor this would help a lot.

##### Ideal behavior.
Froala allows for option to show some sort of placeholder while uploading an image that has been pasted from clipboard instead of inserting an <img> element with base64 as the content.  

##### Actual behavior.
When pasting an image from the clipboard (that has been copied in another program, say Preview on Mac), the upload file functionality kicks in and uploads the file, though the editor also has an <img> tag inserted with the base64 data in as the src, which in cases with large image files is really taking a toll on the browser etc.

##### Steps to reproduce the problem.
Copy an image from a program, say Preview on Mac or Paint on Windows, and paste into a Froala editor while having the upload file functionality set up. The image will upload but also be appended to the editor as an <img> with base64.

**Comment by stefanneculai** [comment]
Unfortunately, that is not possible, the image has to be loaded somewhere in order to be uploaded.

**Comment by Hiaslafson** [comment]
Is this still the case? No workaround?
