### ISSUE TITLE
TypeError Updating from v2.4.2 to v2.5.1

### ISSUE THREAD

**Issue by joeworkman** [froala/wysiwyg-editor#1890]
##### Expected behavior.
No errors

##### Actual behavior.
TypeError: undefined is not an object (evaluating 'a.FE')

![screen shot 2017-04-05 at 11 17 03 pm](https://cloud.githubusercontent.com/assets/225628/24740691/5bffc3e0-1a57-11e7-95bc-79f33692ce6e.jpg)

##### Steps to reproduce the problem.
I am in a similar situation with jQuery as this previous issue... https://github.com/froala/wysiwyg-editor/issues/139

##### OS.
MacOS 10.12

##### Browser.
Safari 10.1

**Comment by joeworkman** [comment]
Same thing happens if I use the 2.5.0 release

**Comment by stefanneculai** [comment]
It is not related to the other issue. Please make sure you are including the editor JS main file before the plugins.

**Comment by joeworkman** [comment]
Thanks for the vote in confidence but I am pretty sure that is a no-brainer. 

Here are the files that I am using the version with v2.4.2 works and the version with the latest version from v2.5.2 HEAD does not. 

v2.4.2 working: https://gist.github.com/joeworkman/26f59e743417e2a214940bfa37965415
v2.5.2 not working: https://gist.github.com/joeworkman/35c0e55c41ec676e1f2d85409915a482

**Comment by joeworkman** [comment]
Can this be reopened please?

**Comment by stefanneculai** [comment]
There doesn't appear to be any problem: https://jsfiddle.net/3tcm0kqh/.
