### ISSUE TITLE
Shift+tab shortcut should decrease indent

### ISSUE THREAD

**Issue by jeremylynch** [froala/wysiwyg-editor#1891]
##### Expected behavior.
`Shift+Tab` decreases indent on tabbed content (test [here](https://www.froala.com/wysiwyg-editor/examples/tabs))

##### Actual behavior.
`Shift+Tab` increases indent on tabbed content

**Comment by stefanneculai** [comment]
Tab is designed to add spaces, not to decrease it. Anyway, thank you very much for the suggestion.
