### ISSUE TITLE
Border incomplete in master

### ISSUE THREAD

**Issue by jeremylynch** [froala/wysiwyg-editor#1892]
Border is not showing correctly in master version as depicted in below image: (border right and border bottom missing)
<img width="691" alt="screen shot 2017-04-06 at 8 53 21 pm" src="https://cloud.githubusercontent.com/assets/3665457/24750966/331f0346-1b0b-11e7-9f5d-7c1eceb4e124.png">

**Comment by stefanneculai** [comment]
What browser and OS are you using? Could you send us a link to a place where we can reproduce this? Thank you.

**Comment by jeremylynch** [comment]
Mac OS, Chrome. I will try to recreate this on a jsfiddle using master.

**Comment by stefanneculai** [comment]
@jeremylynch we couldn't reproduce it. Please use the following files for creating the jsFiddle:
https://cdn.rawgit.com/froala/wysiwyg-editor/44fc7c52/js/froala_editor.pkgd.min.js
https://cdn.rawgit.com/froala/wysiwyg-editor/44fc7c52/css/froala_editor.pkgd.min.css

**Comment by stefanneculai** [comment]
@jeremylynch we cannot reproduce it. I believe it is mainly related to a CSS conflict with something else you have there on the page. If you could put together and example it would be great.
