### ISSUE TITLE
Abnormal table behaviour in master

### ISSUE THREAD

**Issue by jeremylynch** [froala/wysiwyg-editor#1893]
1. Cursur jumps after `enter`
2. Enter adds two lines below

These can both be observed in below video: 
![ezgif com-video-to-gif 13](https://cloud.githubusercontent.com/assets/3665457/24754516/1ea922e8-1b1a-11e7-907b-6f474db54f01.gif)

**Comment by stefanneculai** [comment]
Could you please let us know the exact steps to reproduce it? Also, please follow the layout for reporting an issue, that helps to get it fixed faster.

**Comment by jeremylynch** [comment]
No worries @stefanneculai I will follow normal layout in future. 

I have simplified steps: 

1. Create a Table
2. Press `enter` key a few times
3. Note the addition of unnecessary lines

![ezgif com-video-to-gif 14](https://cloud.githubusercontent.com/assets/3665457/24824179/472c1afa-1c4a-11e7-8619-86f05a3c05e5.gif)

**Comment by jeremylynch** [comment]
Hi @stefanneculai were you able to reproduce this or do you need a jsfiddle/codepen created?

**Comment by jeremylynch** [comment]
If needed the following can be reproduced in this codepen: http://codepen.io/jeremylynch/pen/EmazVW?editors=0110
