### ISSUE TITLE
'FroalaEditor.ENTER_BR' option is causing text alignment issues when pasting rich text from clipboard

### ISSUE THREAD

**Issue by PDiddyStyleShrimpingVessel** [froala/wysiwyg-editor#1895]
##### Expected behavior.
When pasting rich text that has been formatted to contain indents, the formatting is maintained in the target paste element.

Here is a gif of the text alignment working on version 1.2.8 using `<br>` spacing:
https://gyazo.com/f1d2339f2c29818bc8ba9a9af2c9c5a9

##### Actual behavior.
When pasting rich text that has been formatted to contain indents, this formatting is removed.

Here is a gif of the text alignment not working on version 2 using `<br>` spacing:
https://gyazo.com/e1dc9a38db3200c9dd4ace0c514103d6

And here is a gif of the text alignment working on version 2 using `<p>` spacing:
https://gyazo.com/54798e1c9f962882c4f8e30dbf96c374

Notice that the text indent is not working using either.

##### Steps to reproduce the problem.
1. Setup Froala and change the default enter setting to be as follows:
`enter: $.FroalaEditor.ENTER_BR`

2. Create an empty MS Word document and enter some text ensuring to set different alignments
e.g. 
![image](https://cloud.githubusercontent.com/assets/26972045/24764740/40c0bba2-1aed-11e7-93b9-c1dc96ef849f.png)

3. Copy and paste the text in the document to the Froala editor.

##### OS.
Windows 10

##### Browser.
Chrome 56.0.2924.87
IE11

**Comment by stefanneculai** [comment]
@PDiddyStyleShrimpingVessel would it be possible to send us the document you're copying from? Also, are you experiencing that on our website as well?

**Comment by PDiddyStyleShrimpingVessel** [comment]
@stefanneculai Here is the original document I was using to test the formatting. For the gifs I was only showing the issues with the alignment and indenting as the other formatting appears to work (e.g. bulleting, numbering, bolding etc).
[Text Formatting.docx](https://github.com/froala/wysiwyg-editor/files/904903/Text.Formatting.docx)

I tried on the demos on your site and was only getting the issue with the text indent, the exact same behaviour as here: https://gyazo.com/54798e1c9f962882c4f8e30dbf96c374
Here it is on the 'Full Feature' demo on your site: https://gyazo.com/7cb95140a8bc18716b728469b46bbb14

**Comment by PDiddyStyleShrimpingVessel** [comment]
@stefanneculai Hi there. Were you able to recreate this issue?
