### ISSUE TITLE
Feature request: pick and choose VIDEO_PROVIDERS

### ISSUE THREAD

**Issue by george-norris-salesforce** [froala/wysiwyg-editor#1896]
For those that need to limit the video providers (and/or add some) it would be nice to have each `$.FE.VIDEO_PROVIDERS` be exported individually (or some other means) so someone could pick and choose which to use.

**Comment by stefanneculai** [comment]
Great suggestion!

**Comment by stefanneculai** [comment]
Last commit adds the option `videoAllowedProviders` where you can specify which ones to choose. More details will be added on our website as soon as we make the official release.

**Comment by robnelson** [comment]
Hey, this is great, do you know when you will issue a new release as this is exactly what I am looking for?

**Comment by stefanneculai** [comment]
@robnelson There will be a release in the following days.
