### ISSUE TITLE
Word Paste of bullets not working in Microsoft Edge

### ISSUE THREAD

**Issue by jeremylynch** [froala/wysiwyg-editor#1897]
##### Expected behavior.
Bulleted content should persist when copied from word to Froala

##### Actual behavior.
Bulleted content is not bulleted correctly when copied from Word to Froala in Microsoft Edge
The content appears as follows after being pasted in the editor: 
```html
<p>&middot; &nbsp; &nbsp; &nbsp; &nbsp;Indented content</p>
```
In Chrome (on the same operating system) the content is (correctly) pasted as follows:
```html
<ul>
    <li> Indented content </li>
</ul>
```

##### Steps to reproduce the problem.

1. Open the following [MSword document.docx](https://github.com/froala/wysiwyg-editor/files/904348/Sample.MSword.document.docx) on Windows and copy everything in the document
2. Open [Froala](https://www.froala.com/wysiwyg-editor) in Microsoft Edge
3. Paste the content into the editor

##### OS.
Windows 10 Education. Version `1607`

##### Browser.
Microsoft edge `38.14393.0.0`
Microsoft EdgeHTML `14.14393` (Current Stable Version)

**Comment by Pyro979** [comment]
I'm seeing the same behavior. 

OS Name	Microsoft Windows 10 Pro Version	10.0.14393 Build 14393

Microsoft Edge 38.14393.1066.0
Microsoft EdgeHTML 14.14393

Please let me know if you need any repro help, or in-the-wild testing.

**Comment by Pyro979** [comment]
I think adding some more functionality to isWord function might solve this issue.

```
    /*
     * Detect if html is pasted from Word.
     */
    function isWord (clipboard_html) {
	  var detectWord = clipboard_html.match(/(class=\"?Mso|class=\'?Mso|style=\"[^\"]*\bmso\-|style=\'[^\']*\bmso\-|w:WordDocument)/gi);
	  
	  //when pasting only bulleted list from word, there might not be any MSO classes
	  //might need to explore more samples to make this more comprehensive
	  var detectWordBullets = clipboard_html.indexOf('face="Symbol"')>0 && clipboard_html.indexOf('\u00B7')>0;
	  
      return detectWord || detectWordBullets;
    }
```

**Comment by stefanneculai** [comment]
@Pyro979 @jeremylynch unfortunately, at this moment Microsoft Edge doesn't get the HTML correctly from Word. We're going to report this over to Microsoft to see if we can get them fix it somehow.

**Comment by Pyro979** [comment]
@stefanneculai please let us know if there is an issue on their tracker we need to vote up or comment on.
