### ISSUE TITLE
Can't prevent users from dragging and dropping elements into the editor

### ISSUE THREAD

**Issue by tindiep** [froala/wysiwyg-editor#1900]
##### Expected behavior.
When i drag html elements from another place of the page or local storage, I would like to prevent the copy html source into the editor when I drop them to it.

##### Actual behavior.
Users can be able to drop elements into the editor such as images, the editor will show the images which I only need it to store text only.

##### OS.
Windows 10

##### Browser.
Google chrome

**Comment by stefanneculai** [comment]
You can use the drop event and prevent propagating it: https://www.froala.com/wysiwyg-editor/docs/events#drop.

**Comment by tindiep** [comment]
I have tried but seems it can't be fixed. Could you please give me an example?Many thanks!

**Comment by zephyr-soft** [comment]
```
$('.wisiwyg-textarea').on('froalaEditor.initialized', function (e, editor) {
    editor.events.on('drop', function (e) {
        e.preventDefault();
        return false;
    }, true);
});

$('.wisiwyg-textarea').froalaEditor({
    // options
});
```
