### ISSUE TITLE
Toolbar buttons for inline editor XS still shows all toolbar buttons on mobile

### ISSUE THREAD

**Issue by lf237** [froala/wysiwyg-editor#1901]
##### Expected behavior.
The inline editor should show only the buttons specified at initiation for toolbarButtonsXS for mobile devices.

##### Actual behavior.
The inline editor shows the buttons specified at initiation for toolbarButtonsXS as well as the buttons specified for toolbarButtons. The editor should only be showing the buttons specified for toolbarButtonsXS on mobile devices.

##### Steps to reproduce the problem.
Initialize a new editor with toolbarInline set to true. Select a few buttons to go into the toolbarButtonsXS and a set of different buttons for toolbarButtons. Click on the editor to show the toolbar and you will see buttons from both toolbarButtonsXS and toolbarButtons.

##### OS.
macOS Sierra Version 10.12.3

##### Browser.
Chrome

**Comment by stefanneculai** [comment]
Most likely you are doing something incorrectly. For tech support please use our website: https://wysiwyg-editor.froala.help/hc/en-us
