### ISSUE TITLE
Any option to embed pdf 

### ISSUE THREAD

**Issue by tomalex0** [froala/wysiwyg-editor#1902]
This is more like a feature request

##### Expected behavior.
Option to embed pdf to froala

##### Actual behavior.
Not allowing pdf url to be embeded

##### Steps to reproduce the problem.
Try embeding 
http://www.adobe.com/content/dam/Adobe/en/devnet/acrobat/pdfs/pdf_open_parameters.pdf

##### OS.
Windows 7

##### Browser.
Chrome 57.0.2987.133

**Comment by stefanneculai** [comment]
At this moment we don't have such a feature.

**Comment by stefanneculai** [comment]
We've just put together a public roadmap with the most popular features. 😍 There you can vote your favorite one, provide feedback or make new suggestions: https://wysiwyg-editor-roadmap.froala.com/public.
