### ISSUE TITLE
Iframe doesn't resize on content img load so scroll isn't right.

### ISSUE THREAD

**Issue by pijulius** [froala/wysiwyg-editor#1904]
##### Expected behavior.
When Froala is in iframe mode and the predefined content contains image elements Froala should resize the iframe to the correct height after the image itself loads too.

##### Actual behavior.
Froala resizes iframe with "editor.size.syncIframe" on keyup, down, html.set and so on but the problem is that if I have an image that hasn't been loaded yet (textarea mode) Froala will set the wrong iframe height and it won't refresh to the correct height once the image itself loads.

I fixed this for now by adding:
> editor.events.on('html.set', function() {
> &nbsp;&nbsp;editor.$el.find('img').load(function() {
> &nbsp;&nbsp;&nbsp;&nbsp;setTimeout(editor.size.syncIframe, 0);
> &nbsp;&nbsp;});
> });`

##### Steps to reproduce the problem.
1. Create an iframe instance of Froala
2. Set maxHeight so you will have scrollbars
3. Define for e.g. this default content for the editor (using textarea):
&lt;p>&lt;img src="http://wallpapershome.com/images/pages/pic_hs/13335.jpg?1 ">&lt;/p>
&lt;p>Some text&lt;/p>
4. Initiate the editor on the textarea
5. Do the same by changing the number at the end of the image url or press refresh so the image is forced to reload and it should happen over and over again.

##### OS.
Debian 8

##### Browser.
Firefox 52

**Comment by stefanneculai** [comment]
Please make sure you're using the latest version of the editor as it is already doing that.

**Comment by pijulius** [comment]
Unfortunately I'm using the latest release 2.5.1 and this was reported with 2.5.1

I can't switch to github master as sometimes it has strange bugs and anyway if I login with the account we paid for (OEM license) 2.5.1 is the latest.
