### ISSUE TITLE
Selecting table cells can render editor uneditable

### ISSUE THREAD

**Issue by GMiLL5** [froala/wysiwyg-editor#1906]
##### Expected behavior.
Editing (clicking into) text after selecting table cells should always be possible

##### Actual behavior.
Editor can become uneditable (`.fr-no-selection`) after selecting table cells

##### Steps to reproduce the problem.
1. Create two tables with some empty lines in between
2. Select several cells in table 2
3. Select a single cell in table 1
4. Try to place your cursor anywhere in the editor

![froala-table-selection-bug](https://cloud.githubusercontent.com/assets/1800407/25003250/dadc7e42-2024-11e7-8e8b-143e476be4c6.gif)

##### OS.
OSX 10.10.5

##### Browser.
Firefox 52.0.2

**Comment by stefanneculai** [comment]
This is not reproducible on the current master version.
