### ISSUE TITLE
Feature Idea: Always add a space at the end of editor for cursor focus...

### ISSUE THREAD

**Issue by george-norris-salesforce** [froala/wysiwyg-editor#1907]
Currently I'm doing something like this ⬇︎⬇︎⬇︎ and it works well. Could make this a part of Froala core..

addSpacerAtEnd is run on..
`froalaEditor.contentChanged`

```
addSpacerAtEnd(editor) {
    /*
    add an empty <p><br></p> tag to end of editor
    if there is none, to make sure there is always room
    to focus cursor after a custom element..
    So user does not get into situation where they cannot 'get a line' to type into after a video
    or a custom block element. The alternative would be to use the 'line breaker' plugin. 
    */

    const lastElInEditor = $(editor.el).children().last();
    const lastElemIsSpacer =
          lastElInEditor.prop('tagName') === 'P' &&
          lastElInEditor.text() === '' &&
          !!lastElInEditor.find('> br').length;

    if (!lastElemIsSpacer) {
      const spacerEl = `<p><br></p>`;
      return $(editor.el).append(spacerEl);
    }

    return $(editor.el);
  }
```

**Comment by stefanneculai** [comment]
Probably it makes sense to do that after those elements which are not editable, such as table, images or videos. Great suggestion!

**Comment by stefanneculai** [comment]
@george-norris-salesforce we've just put an update for it. It is designed slightly different, when you click at the bottom / top of the space that's left there between the editor edges and last element a new line would get inserted. It is not necessary to include the line breaker tool.
