### ISSUE TITLE
Paste/replace (when text selected first) doesn't fire contentChanged

### ISSUE THREAD

**Issue by pijulius** [froala/wysiwyg-editor#1908]
##### Expected behavior.
When pasting text but having a part of the content already selected (lets call it paste/replace) the "contentChanged" event should be fired (just like on a normal paste) and so update the textarea Froala is attached to so when one hits submit the new content will be really submitted.

##### Actual behavior.
When pasting text but having a part of the content already selected (lets call it paste/replace) the "contentChanged" event isn't fired and so the textarea itself never gets updated and so when one hits submit button the new content won't be submitted.

##### Steps to reproduce the problem.
1. Attach Froala to a textarea
2. Have it prepolutated with some content
3. Double click on a word (for e.g. "example" word)
4. Click CTRL+V to paste the text from your clipboard and replace the selected text (for e.g. "example" word)
5. Click submit for the form and the old content will still be submitted

FYI: also tried by adding:
> editor.events.on('contentChanged', function() {
> &nbsp;&nbsp;console.log(editor.html.get());
> }

and you will see this even never gets fired if you follow the above steps to reproduce.

##### OS.
Debian 8

##### Browser.
Firefox 52

##### Temporary Fix
For now what I did is the following and that fixes for us but would welcome a global fix:
> editor.events.on('paste.after', function() {
> &nbsp;&nbsp;editor.events.trigger('contentChanged');
>});

**Comment by stefanneculai** [comment]
@pijulius  It is not reproducible in the current master version of the editor. Could you please make a jsFiddle? Thank you.

**Comment by stefanneculai** [comment]
There doesn't appear to be a problem in the current master. Please make sure that you are binding to the contentChanged event correctly. It should be something like this:

```js
$('selector').on('froalaEditor.contentChanged', function (e, editor) {
}).froalaEditor();
```

**Comment by pijulius** [comment]
This is happening on 2.5.1 as that's the latest release, haven't tested with the master but once there is a newer release will check again.
