### ISSUE TITLE
Caret disappears after dropping text into the editor (Firefox)

### ISSUE THREAD

**Issue by nermand** [froala/wysiwyg-editor#1912]
##### Expected behavior.
After dropping content into the editor, content should be pasted where the cursor is set and caret should be positioned and visible after new content.
##### Actual behavior.
A content is added as expected, but caret is not visible. It is positioned well, as I can continue typing text there. It will reappear only after editor loses and again gains focus

##### Steps to reproduce the problem.
Go to: [Drop content demo](https://www.froala.com/wysiwyg-editor/examples/drop-content)
Drag text into the editor
##### OS.
Windows 8.1
##### Browser.
Firefox 52.0.2

**Comment by stefanneculai** [comment]
Unfortunately, there is no too much we can do about it as it is a Firefox problem: https://bugzilla.mozilla.org/show_bug.cgi?id=226301. There appears to be a workaround, but it doesn't work: http://stackoverflow.com/a/10903605/1806855
