### ISSUE TITLE
Emojis are inserted 4 stacked within a single line

### ISSUE THREAD

**Issue by jacobzweig** [froala/wysiwyg-editor#1914]
##### Actual behavior.
Emojis are inserted as multiple stacked within a single line with `emoticonsUseImage: true`:
![image](https://cloud.githubusercontent.com/assets/2703695/25091088/cdb748f2-234c-11e7-88b3-d59f8f2fc9f6.png)

##### Steps to reproduce the problem.
Adding from emoticons button in main froala bar

##### OS.
Sierra

##### Browser.
Chrome 57.0.2987.133

**Comment by stefanneculai** [comment]
Please make sure you are including the froala_style CSS file.

**Comment by an0nh4x0r** [comment]
Included froala_style CSS file still the same problem 😕

**Comment by stefanneculai** [comment]
@an0nh4x0r could you please make a jsFiddle or something similar?

**Comment by vaibhavsah** [comment]
@stefanneculai I am also getting same issue. Did you get the solution to it ?

**Comment by vaibhavsah** [comment]
@jacobzweig  Did you get any solution for this? I am also getting same error.

**Comment by kyds3k** [comment]
@jacobzweig getting the same error too . . . did you find a resolution?

**Comment by vaibhavsah** [comment]
It seemed there was some issue with CSS not loading properly. Once that fixed, issue resolved.

**Comment by stratosk21** [comment]
I encountered this issue also, it was fixed by applying the class "fr-view" to the element. But beforehand just make sure to include the froala_style CSS files too.

`<div class="fr-view">
  content inside div
</div>`
