### ISSUE TITLE
Can not get S3 upload callback url & key value.

### ISSUE THREAD

**Issue by hsuanshao** [froala/wysiwyg-editor#1915]
##### Expected behavior.
According to document descript, I can get URL & Key when videouploadtos3 finish.

##### Actual behavior.
However, It does not work when upload finished (video file already uploaded on my bucket)

##### Steps to reproduce the problem.
I try to do dump anything in callback function (e.g., console.log('ABC')), it still not show this message when video upload finish (even the video player already embedded into froala editor)

##### OS.
Mac OS X

##### Browser.
Chrome

####My Code as shown as follows :

videoAllowedTypes: ['mp4','asf','asx','avi','divx','dv','dvx','m4v','mov','mpeg','mpg','qt','wmv','3g2','3gp','3ivx','3vx'],
      videoUploadToS3: {
          bucket: 'pressplay-bucket',
          region: 's3-ap-northeast-1',
          keyStart: 'creator_video/',
          params: {
            acl: 'public-read', // ACL according to Amazon Documentation.
            AWSAccessKeyId: $('#keyfieldofpost').attr('data-keyid'), // Access Key from Amazon.
            policy: $('#keyfieldofpost').attr('data-policy'), // Policy string computed in the backend.
            signature: $('#keyfieldofpost').attr('data-signature'), // Signature computed in the backend.
          },
          callback: function (url, key) {
            // The URL and Key returned from Amazon.
            alert('test');
            console.log (url);
            console.log (key);
          }
        }

**Comment by stefanneculai** [comment]
The documentation had a small problem there. The [video.uploadedToS3](https://www.froala.com/wysiwyg-editor/docs/events#video.uploadedToS3) event shall be used as an alternative.
