### ISSUE TITLE
Pasting from Google Docs wraps all text in bold/strong

### ISSUE THREAD

**Issue by constancecchen** [froala/wysiwyg-editor#1918]
Note: I saw a similar (or identical?) issue was already opened/addressed in https://github.com/froala/wysiwyg-editor/issues/1014, but I'm wondering if this was regressed at some point during the Word pasting enhancements, since I can reproduce it reliably using the current Froala homepage demo (and have confirmed with someone else that they can also reproduce it).

##### Expected behavior.
When coping and pasting from Google Docs, I expect all pasted text not to be wrapped in a `<strong>` tag.

##### Actual behavior.
All text being copied from Google Docs is being wrapped in a `<strong>` tag.

##### Steps to reproduce the problem.
1. Open [a Google Doc](https://docs.google.com/document/d/18L3TOdNRyw0ggrkC0EFhTw3MFdaogBg9K3xsE4Z2JZA/edit), select all, and copy the contents
2. Navigate to the [Froala homepage demo WYSIWYG](https://www.froala.com/wysiwyg-editor), and either select all or start a new line
3. Paste content

##### OS.
Mac OSX El Capitan - 10.11.6

##### Browser.
Chrome 57 and Firefox 52

**Comment by constancecchen** [comment]
Ahh, after doing some logging, it looks like the issue might well be on Google's side. They're using the `<b>` tag for their own wrapping/ID markers rather than something more innocuous like `<div>` or `<span>`. Froala ends up converting that to `<strong>` using its HTML5Map object.

Here's an example `clipboard_html` output from the paste.beforeClean event:

```html
<meta charset='utf-8'><meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-d9643e9b-8289-d035-00fe-cb24f80e07fb"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre-wrap;">Lorem ipsum</span></b>
```

I was able to release a hotfix/workaround for this on my end for now using the following code:

```js
editor.events.on('paste.beforeCleanup', function (clipboard_html) {
  var googleDocRegex = /<b.* id="docs-internal-guid-\S*">/i;

  if (clipboard_html.match(googleDocRegex)) {
    clipboard_html = clipboard_html.replace(googleDocRegex, '');
    clipboard_html = clipboard_html.replace('</b>', '');
  }

  return clipboard_html;
});
```
It's not super thoroughly tested - my regex may not be catching every edge case and my .replaces could probably be combined. Hopefully it helps a bit, however.

**Comment by node-gs** [comment]
thank you @constancecchen
