### ISSUE TITLE
Language plugin is missing. Can't change language.

### ISSUE THREAD

**Issue by maximemoring** [froala/wysiwyg-editor#1919]
##### Expected behavior.
https://www.froala.com/wysiwyg-editor/docs/options#language
"Type:	String
Default:	null
Plugin:	language.min.js"
Seems to say the necessary plugin is language.min.js, which isn't present.

##### Actual behavior.
Can't seem to change the language. I suspect it is because of it being missing entirely.

##### Steps to reproduce the problem.
Done with RequireJS and KnockoutJS (everything else works)
Done with the option language: 'fr' (and fr.js included in required.config.js)

##### OS.
Mac OSX

##### Browser.
Chrome 56.0

**Comment by stefanneculai** [comment]
There was an error in our docs. There is no such plugin `language.min.js`. If the language doesn't work for you , then most likely you are not including the language file correctly.

**Comment by mm580486** [comment]
hi @stefanneculai 
i have some problem in angular 
but i cant find language.min.js in node_modules directry but i can see language directory (fa.js.en.js....)

**Comment by mm580486** [comment]
i got it i most only import language js file like fa.js or ....
thanks
