### ISSUE TITLE
(Links) Not respecting contenteditable=false with newline & spacing

### ISSUE THREAD

**Issue by danniehansen** [froala/wysiwyg-editor#1920]
##### Expected behavior.
When having a editor with contenteditable=false & a link with contenteditable=true. Spaced & newlines should respect the parent contenteditable=false & leave spaced appended & newlines appended within our contenteditable=true link.

##### Actual behavior.
Line breaks & spacing is appended to the parentNode of our currently focused & active link having contenteditable=true. Even though our parentNode exists in a contenteditable=false context.

##### Steps to reproduce the problem.
1. Make main froala wrapper contenteditable=false after init.
2. Create a link as being the only element having contenteditable true.
3. Move cursor to the end of the link & press either space or enter.
4. Watch how it's appended to the parentNode instead of respecting the contenteditable properties.

##### OS.
Mac OS X Yosemite version 10.10.5

##### Browser.
Chrome 57

##### Why?
We're using contenteditable to seperate content that is editable to the customer. In this case we have a single editor instance containing a <a /> tag that is displayed as a button with CSS. When user moves cursor to the end of the link & press either space or enter - it will act strangely.

**Comment by stefanneculai** [comment]
@danniehansen could you please make a jsFiddle?

**Comment by stefanneculai** [comment]
We are closing this due to lack of response.
