### ISSUE TITLE
Background color not set correctly on sub bullets

### ISSUE THREAD

**Issue by Pyro979** [froala/wysiwyg-editor#1921]
##### Expected behavior.
set background color of all the list items including the sub items

##### Actual behavior.
set background color of the list items EXCLUDING the sub items

##### Steps to reproduce the problem.
- create list with sub bullets
- select the whole list
- set background

![froala_bullet_background](https://cloud.githubusercontent.com/assets/552431/25189908/a47d3ffc-24f8-11e7-8b3d-d0a5e336cfd9.gif)

##### OS.
Win10

##### Browser.
All tested.

**Comment by stefanneculai** [comment]
It is fixed on the current master.

**Comment by Pyro979** [comment]
@stefanneculai how long till it's available fro download to paid customers? I'm not sure what your release schedule is on the main site.
