### ISSUE TITLE
Word Copy Paste: JS Error when pasting from doc with multiple images

### ISSUE THREAD

**Issue by irphilli** [froala/wysiwyg-editor#1923]
##### Expected behavior.
Able to copy/paste from Word doc with no errors

##### Actual behavior.
Copy/paste results in JS error and some images not loading in.

Error is: Uncaught TypeError: Cannot read property 'offset' of null

##### Steps to reproduce the problem.
Use this doc: 
[Doc with Smart Art Cycle.docx](https://github.com/froala/wysiwyg-editor/files/938658/Doc.with.Smart.Art.Cycle.docx)
Copy/paste into editor

##### OS.
Windows 7 with Word 2013

##### Browser.
Chrome Latest

**Comment by irphilli** [comment]
After testing a little further, it only seems to happen since there's "smart art" in the doc

**Comment by irphilli** [comment]
Scratch that... here's another example of a doc without smart art that's causing the error: 
[images.docx](https://github.com/froala/wysiwyg-editor/files/938712/images.docx)

**Comment by firstladymb** [comment]
Replicated on Windows 10 Chrome 58 and maxOS Sierra 10.12.4 Chrome 58. Works in Firefox. 

Our customers were reporting disappearing images as they appear to have pasted properly until you preview or save. 

Here's an example doc that shows the error in Chrome.
[DisappearingImage.docx](https://github.com/froala/wysiwyg-editor/files/963099/DisappearingImage.docx)

**Comment by clechner77** [comment]
Seems to happen in Chrome any time there are multiple images.   I wonder if there's a workaround until an official fix gets posted.
