### ISSUE TITLE
lineBreaker position is wrong when the editor is in bootstrap modal

### ISSUE THREAD

**Issue by 21k** [froala/wysiwyg-editor#1925]
![_20170421162131](https://cloud.githubusercontent.com/assets/13778916/25269338/bcbf01c4-26ae-11e7-9db5-13399d31bc74.png)

**Comment by stefanneculai** [comment]
Most probably you are not setting it correctly. See: https://github.com/froala/wysiwyg-editor/blob/master/html/3rd-party/bootstrap/modal.html.

**Comment by 21k** [comment]
the problem is that i am using bootstrap V4?

**Comment by 21k** [comment]
the key point is 
`      .modal-dialog {
        transform : none !important;
        -webkit-transform : none !important;
        -moz-transform : none !important;
      }`

thank you very much @stefanneculai
