### ISSUE TITLE
excel paste is broken format on merge rows or cells

### ISSUE THREAD

**Issue by jungyoungtai** [froala/wysiwyg-editor#1927]
i used to word_paste.min.js

##### Expected behavior.
not broken excel-format.

(Describe expected behaviour here)

##### Actual behavior.
(Describe actual behaviour here)
broken

##### Steps to reproduce the problem.
(Describe the steps to reproduce the problem here)

##### OS.
(OS name and version here)
windows10

##### Browser.
(Browser name an version here)
chrome

**Comment by stefanneculai** [comment]
@jungyoungtai could you send us an Excel file for that?

**Comment by jungyoungtai** [comment]
[image: 본문 이미지 1]

----------- paste result -----------------------

[image: 본문 이미지 2]



2017-04-24 18:04 GMT+09:00 Stefan Neculai <notifications@github.com>:

**Comment by stefanneculai** [comment]
@jungyoungtai could you send an excel file? Thank you.

**Comment by jungyoungtai** [comment]
i send an email. address - froala/wysiwyg-editor <wysiwyg-editor@noreply.github.com>

**Comment by stefanneculai** [comment]
We haven't got it. Could you please upload the Excel file somewhere and put the link here?

Thanks.

**Comment by jungyoungtai** [comment]
[test.xlsx](https://github.com/froala/wysiwyg-editor/files/963849/test.xlsx)

**Comment by stefanneculai** [comment]
It is already fixed on the master version.

**Comment by jungyoungtai** [comment]
i'm test on this website(https://www.froala.com/wysiwyg-editor)

i trying to excel paste is still format  broken.

![image](https://cloud.githubusercontent.com/assets/2044712/25521639/6629ddec-2c3b-11e7-870b-56859b50d065.png)

**Comment by stefanneculai** [comment]
Yes, but it is fixed on the master version of the Github repo. We do here the development and put updates on our website only after a new release is made.

**Comment by jungyoungtai** [comment]
ok. i see. thank you. :)
