### ISSUE TITLE
Pasting images doesn't always upload

### ISSUE THREAD

**Issue by GMiLL5** [froala/wysiwyg-editor#1929]
##### Expected behavior.
Pasting any image should perform upload action

##### Actual behavior.
Only images with `data:` in their source are uploaded

##### Steps to reproduce the problem.
Paste an image

##### OS.
Mac OSX 10.0.5

##### Browser.
Firefox 52.0.2

##### Notes.
Looking at old options from v1.2 this used to be supported. In the migration from 1-2 it suggests it should still be, see [`pastedImagesUploadURL`](https://www.froala.com/wysiwyg-editor/docs/migrate-from-v1)

**Comment by stefanneculai** [comment]
Pasted images which have the SRC set to a URL shouldn't be uploaded. In V2, pasted images are uploaded automatically to the `imageUploadURL` option.
