### ISSUE TITLE
Froala jquery support

### ISSUE THREAD

**Issue by raghuramv1988** [froala/wysiwyg-editor#1930]
This is a query on the latest version of jQuery which froala supports. The documentation says 1.11.0 or above and we are using the 1.11.0, but we would like to upgrade to a later version of jQuery. Can there be a confirmation on the last version of jQuery with which froala has been tested and found stable.

**Comment by stefanneculai** [comment]
@raghuramv1988 it works with any version higher than 1.11.0.
