### ISSUE TITLE
Fixed Toolbar doesn't work on Firefox or Safari

### ISSUE THREAD

**Issue by fernandoacosta** [froala/wysiwyg-editor#1932]
I'm using the fixed toolbar on scroll and it's working fine on Chrome. But it's not working on Firefox or Safari.

Even the example doesn't work: https://www.froala.com/wysiwyg-editor/examples/full-featured

I'm using Ubuntu 16.x, but I've tested on Windows 10 as well.

**Comment by stefanneculai** [comment]
@fernandoacosta please make sure you don't have parent elements which have CSS property `overflow: hidden`.

**Comment by fernandoacosta** [comment]
@stefanneculai, please make sure you've read my issue: your example doesn't work. do you have a overflow: hidden?

Chrome::
![anim](https://cloud.githubusercontent.com/assets/7092808/25529846/3fe576aa-2bfa-11e7-8fd2-70200b6d24d6.gif)

Firefox::
![anim](https://cloud.githubusercontent.com/assets/7092808/25529942/a70b075a-2bfa-11e7-855a-7c91183fe5a8.gif)

**Comment by stefanneculai** [comment]
Yes, that is because we have there an `overflow: hidden` on the page in a parent element - we're going to update it shortly. That is not happening on the homepage, where that CSS property is not used.
