### ISSUE TITLE
Edit Image Popup - Doesn't do any collision detection (properly?)

### ISSUE THREAD

**Issue by jpgilchrist** [froala/wysiwyg-editor#1933]
We are using froala in a static location at the bottom of a message stream with `toolbarBottom: true`. The editor is using the `heightMax` and `heightMin` options. When an image is added to the editor there is a situation where the image edit popup is not visible, which is truly frustrating. 

After spending a lot of time looking into the code I came across the `at` function and subsequently the `_topNormalized` function. Within this code I see the variable `new_top` is calculated based on the popup's height (`obj_height`), but no where else in this function is `obj_height` used. I strongly believe that it was intended to be used in the `if` statement to determine whether the class `fr-above` should be added or removed. 

Original code: 

```javascript
        if (p_offset + top + height > editor.$sc.offset().top + s_height && $el.parent().offset().top + new_top > 0) {
          top = new_top;
          $el.addClass('fr-above');
        }
        else {
          $el.removeClass('fr-above');
        }
```

suggested code:

```javascript
        if (p_offset + top + obj_height > editor.$sc.offset().top + s_height && $el.parent().offset().top + new_top > 0) {
          top = new_top;
          $el.addClass('fr-above');
        }
        else {
          $el.removeClass('fr-above');
        }
```

**Comment by stefanneculai** [comment]
@jpgilchrist could you please put together a jsFiddle for it?

**Comment by jpgilchrist** [comment]
@stefanneculai this hard to setup a jsfiddle for since I can't use unminified code in order to tell if I'm hitting the block of code correctly. Regardless it's more of a conceptual thing. I think the math should be `p_offset + top + obj_height` not `p_offset + top + height`.

**Comment by jpgilchrist** [comment]
@stefanneculai any further thoughts on this?

**Comment by stefanneculai** [comment]
We reviewed this and the math looks correct. The top where the element should be displayed (`p_offset + top`) added with the height of the element (`height`) shall be higher than the height of the offset of the scrollableContainer (`editor.$sc.offset().top`) added with the height of the container (`s_height`). 

I might be wrong, therefore if you could put together a CodePen or jsFiddle to show what is wrong, we could definitely look more into it.
