### ISSUE TITLE
Scroll inside the editor is not working when editor is locate inside iframe

### ISSUE THREAD

**Issue by jobnoam** [froala/wysiwyg-editor#1938]
##### Expected behavior.
When we open a modal with iframe inside and inside the iframe we have more then 1 editor instance that scroll of the editors is not working with the mouse.

##### Actual behavior.
The scroll on the editors need to work. Only when we show the page outside the iframe as a stand a long page it's working

##### Steps to reproduce the problem.
1. Open modal.
2. Build iframe inside the modal.
3. Inside the iframe add a page with more then 1 editor.
4. Add text to the editors.
5. Try to scroll inside this editors with your mouse.

##### OS.
macOS 10.12.4

##### Browser.
57.0.2987.133 (64-bit)

**Comment by stefanneculai** [comment]
@jobnoam could you please put together a jsFiddle? Thank you.

**Comment by stefanneculai** [comment]
We're closing this due to lack of response.
