### ISSUE TITLE
Does not work imageManagerPreloader

### ISSUE THREAD

**Issue by celalnuriakgun** [froala/wysiwyg-editor#1939]
"Image uploading" does not appear when the image is uploaded at my web site. but worked my localhost How to solve?

**Comment by stefanneculai** [comment]
@celalnuriakgun Please make sure you have the correct path set up. If that is going on your development environment, that is unlikely to be a problem from the editor. For tech support please reach us via our website.

Thank you,

**Comment by celalnuriakgun** [comment]
Now I realize that my local server is not working either

**Comment by stefanneculai** [comment]
Most probably you're setting it incorrectly. Please reach us via our website for tech support about configuring the editor. Thank you.

**Comment by celalnuriakgun** [comment]
Okey, Thanks.
