### ISSUE TITLE
Font format is lost after selecting and deleting the whole line

### ISSUE THREAD

**Issue by liunaijia** [froala/wysiwyg-editor#1940]
##### Expected behavior.
Format should be kept with the previous line.

##### Actual behavior.
Format goes for the default.

##### Steps to reproduce the problem.
Even with the `keepformatondelete` option enabled:
1. Select the whole text in the editor, change font family to non-default value.
2. Type two lines of text
3. Select the whole second line
4. Press backspace to delete the text on the second line
5. Press backspace one more time to delete the second line, after doing this the cursor is at the end of the first line
6. Press enter to create a new line
7. Type some texts on the new line. The font style goes back to the default one rather than using the style from the first line.

##### OS.
Any.

##### Browser.
Chrome

**Comment by carolynmills** [comment]
@stefanneculai this still appears to be be an issue when testing it following the above steps

**Comment by stefanneculai** [comment]
@carolynmills please make sure you're using the latest editor version.

**Comment by carolynmills** [comment]
I tested it here: https://www.froala.com/wysiwyg-editor/

**Comment by stefanneculai** [comment]
@carolynmills on our website keepFormatOnDelete option is not enabled and that's why you see this behavior.
