### ISSUE TITLE
Support for local blob src in img tag

### ISSUE THREAD

**Issue by PvanHengel** [froala/wysiwyg-editor#1941]
##### Expected behavior.

When the value of the text-area uses a local image url such as <img src="blob:http://localhost:8080/guid"> the value of the editor should not be encoded.  

##### Actual behavior.
When the value of the textarea uses a local image url such as <img src="blob:http://localhost:8080/guid"> the value of the editor returns the incorrect url: <img src="blob:http%3A//localhost%3A8080/guid"> resulting in a missing image

##### Steps to reproduce the problem.
Setup a standard editor with the image plugin, attach an event to beforeUpload eg:

```
editor.on('froalaEditor.image.beforeUpload', function (e, editor, files) {
            if (files.length) {
                var blob = new Blob([files[0]], {type: files[0].type});
                var localImageUrl = URL.createObjectURL(blob);             
                editor.image.insert(localImageUrl, null, null, editor.image.get());
            }
            return false;
        });
```

It should insert the image with a url like "blob:http://localhost:1234/guid

save this html, clear the page, put the saved html in a new text area, and initialize the editor.  You will see the URL gets encoded incorrectly.

##### OS.
OSX

##### Browser.
Chrome

**Comment by stefanneculai** [comment]
We have an example for that as base64: https://github.com/froala/wysiwyg-editor/blob/master/html/image/insert_base64.html#L89

**Comment by PvanHengel** [comment]
Your example works fine when the image is first inserted, however the issue is not about the first insert, its about loading existing HTML that uses that url format, it is improperly encoding the URL.  It seems that during the load there are some regex replacements that happen with the src that i was able to find in the minified code.

**Comment by stefanneculai** [comment]
@PvanHengel please see: https://github.com/froala/wysiwyg-editor/issues/1235#issuecomment-251943999.

**Comment by PvanHengel** [comment]
Thank you this looks like it will work!

**Comment by Dzunisanu** [comment]
How do i save video to DB with froala base64 like the example you have for image

**Comment by dana8123** [comment]
@stefanneculai Thank you! it works for me!

> We have an example for that as base64: https://github.com/froala/wysiwyg-editor/blob/master/html/image/insert_base64.html#L89
