### ISSUE TITLE
Image plugin <img> tag not </closed>

### ISSUE THREAD

**Issue by PvanHengel** [froala/wysiwyg-editor#1942]
##### Expected behavior.

After inserting an image using the image plugin, the inserted img tag should contain a closing forward slash eg `<img src="..." />`

##### Actual behavior.
After inserting an image using the image plugin, the inserted img tag is missing the closing forward slash eg `<img src="..." >`

##### Steps to reproduce the problem.
Setup a standard editor with the image plugin, insert an image and observe the resulting image tag.  Some html parsers require all tags to be closed properly.

##### OS.
OSX

##### Browser.
Chrome

**Comment by stefanneculai** [comment]
The editor is using HTML 5 underneath and editor's output is HTML5 as well. In HTML5, it is not necessary to have an ending / for self-closing tags.

**Comment by PvanHengel** [comment]
I guess this is a grey area with self closing tags. I'll address the issue with the parser (xml) we are using to validate the html(5). (https://www.w3.org/TR/html/syntax.html#writing-html-documents-elements)

Thank you!
