### ISSUE TITLE
Iframe Editor does not align images right

### ISSUE THREAD

**Issue by rblin081** [froala/wysiwyg-editor#1943]
##### Expected behavior.
Insert image into editor with iframe option turned on. Set image display to inline. Set align to align-right. Blue image border appears right but actually image does not.

##### Actual behavior.
Inline image should align right.

##### OS.
Windows 

##### Browser.
Firefox

**Comment by stefanneculai** [comment]
Please make sure you are loading the froala_style CSS file from the same domain. If you cannot do that, then pass it to the `iframeStyleFiles` option.

**Comment by rblin081** [comment]
froala_style.css is being loaded from the same domain
