### ISSUE TITLE
emoji-unicode multiple character emoji

### ISSUE THREAD

**Issue by m-andrew-albright** [froala/wysiwyg-editor#1944]
# Question:

With the emoticonSet is it possible to use some of the emoji which are comprised of two (or more) unicode characters for one emoji?

For instance, all the skin-tone-X modifiers (see http://unicode.org/emoji/charts/full-emoji-list.html#1f476_1f3fb)

If this is possible, how do we do it?

**Comment by stefanneculai** [comment]
At this moment we don't have an option for that. I marked this as a `feature-request` and it is going to be added if we get more requests for it.

**Comment by m-andrew-albright** [comment]
Thanks for the response

**Comment by thedotedge** [comment]
👍

**Comment by duellsy** [comment]
+1 for this, wondering if there's any update or other PRs / issues that have any updates to using a larger emoji etc
