### ISSUE TITLE
htmlAllowedEmptyTags not working if htmlUntouched: true

### ISSUE THREAD

**Issue by bartezic** [froala/wysiwyg-editor#1945]
##### Steps to reproduce the problem.
htmlUntouched: true
htmlAllowedEmptyTags: ['div']

with this settings, the plugin will remove empty div tags

**Comment by stefanneculai** [comment]
@bartezic could you please let us know what HTML you have there?

**Comment by bartezic** [comment]
```HTML
<script id='elopage-script' src='https://elopage.com/assets/badges.js'></script><div class='elopage-badge-wrap' data-username='frank-heister-coachings' data-btncmps='icon|text|price|duration|progressbar' data-btnfontfamily='Open Sans' data-btncolor='#ffb900' data-btnfontcolor='#fff' data-btntext='null' data-locale='en' data-embedcheckout='off' data-badge='ElopageBadgeBtn'> </div>
```

**Comment by stefanneculai** [comment]
@bartezic we just tried it and appears to work just fine. Could you please make a codePen for it. You can use the following as a starting point: http://codepen.io/Froala/pen/PpgxGL

**Comment by bartezic** [comment]
@stefanneculai Sorry, I can't reproduce too, Thanks for your time.
