### ISSUE TITLE
Flicker when editing

### ISSUE THREAD

**Issue by PvanHengel** [froala/wysiwyg-editor#1947]
##### Expected behavior.
As the user types into the editor when scrolled down using the app on an iphone (cordova wrapper) the view should be smooth and not 'redraw' or 'flicker'.

##### Actual behavior.
As the user types into the editor which has enough text that it scroll's the screen 'flickers' white after every key press.  When inspecting using the remote debugger, it seems this might be related to the sizzle and edits made by jquery?  #871  

##### Steps to reproduce the problem.
Run the editor inside a cordova wrapped application, and enter some text until it scrolls.  Using iframe mode (note when not using iframe's you cant edit the text at all)...  This behavior is NOT seen when using the desktop browser (chrome).

##### OS.
OSX / IOS

##### Browser.
Cordova

**Comment by stefanneculai** [comment]
@PvanHengel could you please send us an app where we can test it?

**Comment by stefanneculai** [comment]
We are closing this due to lack of response.
