### ISSUE TITLE
Translation not taken in account for "Uploading" and "Loading image"

### ISSUE THREAD

**Issue by cyrilepinat** [froala/wysiwyg-editor#1948]
I should be able to replace "Uploading" and "Loading image" in my language translation object. But the values are not taken in account.
In image.min.js file https://github.com/froala/wysiwyg-editor/blob/master/js/plugins/image.min.js
I'm creating an FR translation object : 
``` 
$.FE.LANGUAGE.fr.translation.Uploading = 'Téléchargement';
$.FE.LANGUAGE.fr.translation['Loading image'] = 'Chargement de l\'image';
```
but it has no effect

**Comment by cyrilepinat** [comment]
@stefanneculai is this fixed ?

**Comment by stefanneculai** [comment]
Yes, on Github master it is fixed.

**Comment by cyrilepinat** [comment]
nice ! thank you @stefanneculai
