### ISSUE TITLE
Option to disable paste from Word/Excel modal

### ISSUE THREAD

**Issue by markedmondson** [froala/wysiwyg-editor#1949]
##### Expected behavior.
A configuration option to default the paste behaviour for word to "keep", "clean" or "default" (show modal) which determines whether to show the modal on paste.

Another side effect is the text in the modal does not seem to be translated.

##### Actual behavior.
The modal is forced when the preferred behaviour may already be known.

##### Steps to reproduce the problem.
Paste from Word, modal is shown.

##### OS.
Mac OS Sierra

##### Browser.
Chrome 58

**Comment by stefanneculai** [comment]
Last commit adds the `wordPasteModal` option which is a boolean. By default it is true and can be set to false. In this case the format would be kept. If Word format is not desired, then the Word Paste plugin shouldn't be included at all.

**Comment by markedmondson** [comment]
Awesome @stefanneculai thanks!
