### ISSUE TITLE
I have a question about the getBoundingRect () function.

### ISSUE THREAD

**Issue by largeden** [froala/wysiwyg-editor#1952]
froala editor version: 2.5.1

```javascript
editor.position.getBoundingRect().top
```
On mobile, I can not get the value I want.
This is because editor.helpers.isMobile () returns 0.
```javascript
  $.FE.MODULES.position = function (editor) {
    /**
    * Get bounding rect around selection.
    *
    */
    function getBoundingRect () {
//...
        boundingRect.top = offset.top - (editor.helpers.isMobile() ? 0 : editor.helpers.scrollTop());
```

In the past, there were not mobile conditions.
```javascript
//froala editor version: 2.0.1
boundingRect.top = offset.top - $(editor.original_window).scrollTop();
```

Is this the intended behavior?

**Comment by stefanneculai** [comment]
Hi @largeden. Yes, this is the intended behavior and it was added in order to fix some problems with the inline toolbar not showing correctly on mobile devices.
