### ISSUE TITLE
Forms with a Froala editor + Code View won't submit in Chrome

### ISSUE THREAD

**Issue by Loilo** [froala/wysiwyg-editor#1955]
##### Expected behavior.
A form with a Froala editor should regularly submit.

##### Actual behavior.
Submitting a form fails with an error message when *Code View* was used.

![form-submission](https://cloud.githubusercontent.com/assets/1922624/25764509/703f53e0-31e8-11e7-84b2-2a8095314675.png)

##### Steps to reproduce the problem.
1. Put a Froala editor with the option to use *Code View* inside a form with a submit button.

   You may use [this codepen](http://codepen.io/loilo/pen/jmGZLe?editors=1010).
2. Open it in an up to date Chrome browser.
3. Enable *Code View*.
4. Click the *Submit* button.

Over at mautic/mautic#4000, where I first opened this issue, the problem could not be reproduced by one of the contributors. Also, googling the error message does not bring up too much. In fact, [this](https://chromium.googlesource.com/chromium/src.git/+/master/third_party/WebKit/Source/core/html/HTMLFormElement.cpp#298) seems to be the only result Google brings up by searching for the error message. But it at least kind of proves that this is a thing and it is kind of new (as the referenced WHATWG issue on the referenced page is).

However, they sent me here, [assuming](https://github.com/mautic/mautic/issues/4000#issuecomment-299428844) that you introduced such an unclosed tag, which seems correct to me.

It should be pretty easy to fix though. This code

```javascript
k=a('<textarea class="fr-code" tabIndex="-1">')
```

can just slightly be adjusted to this:

```javascript
k=a('<textarea class="fr-code" tabIndex="-1" />')
```

This would fix the issue.

##### OS.
macOS 10.11.6

##### Browser.
Google Chrome Version 58.0.3029.81 (64-bit)

**Comment by stefanneculai** [comment]
We just tried to reproduce it with that CodePen, but it appears to work just fine, no error is being thrown.

**Comment by Loilo** [comment]
Okay, to clarify: This was a weird issue with my Chrome that could only be resolved by completely purging my Chrome user data and then reinstall it.

Sorry, a bug in a JS library was just the more natural assumption. 😬
