### ISSUE TITLE
 Word Paste Detected

### ISSUE THREAD

**Issue by SergioCrisostomo** [froala/wysiwyg-editor#1957]
As of  `2.6.0` I see a "Word Paste Detected" dialog.

![skarmavbild 2017-05-08 kl 11 56 22](https://cloud.githubusercontent.com/assets/5614559/25799485/6d797060-33e5-11e7-9e89-dcf255ca899d.png)

This raises some questions:

 - Is there a option to disable this? 
 - which of the options was the "default" one before?
 - if I need to i18n this dialog, where do I do this?

I was building integration tests with copy paste and this broke my tests. Would be nice to know how to bypass it when needed. Checked the docs but didn't find info about it there.

Regards,
Sérgio

**Comment by PDiddyStyleShrimpingVessel** [comment]
I second this. This was introduced seemingly as a fix to this bug https://github.com/froala/wysiwyg-editor/issues/1895
Sérgio raises valid points. It is being used in a multi-lingual application and the dialog comes with its own styles. This should not be the default behaviour that cannot be turned off.

**Comment by SergioCrisostomo** [comment]
Just saw the `feature-request`label, in that case would be good if you would have a method for this, with events or a callback. So we can call our own UI dialog and provide the same functionality integrated.

**Comment by stefanneculai** [comment]
See: https://github.com/froala/wysiwyg-editor/issues/1949#issuecomment-302407484 for disabling the option.

**Comment by argeualcantara** [comment]
I'm trying to copy from MS Word online, but I keep getting plain paste, even with plainPaste option set to false, does it only detects MS Word pasting?
