### ISSUE TITLE
Stack Trace - Cannot read property 'offset' of null

### ISSUE THREAD

**Issue by jpgilchrist** [froala/wysiwyg-editor#1958]
##### Expected behavior.
Taking a screenshot into your clipboard (mac `shift + ctrl + cmd + 4`) and pasting it into the editor should work. 

##### Actual behavior.
often generates this error: 

```
image.js:295 Uncaught TypeError: Cannot read property 'offset' of null
    at _repositionResizer (image.js:295)
    at HTMLImageElement._sendRequest (image.js:953)
    at HTMLImageElement.dispatch (jquery.js:4435)
    at HTMLImageElement.$event.dispatch (jquery.event.drag-2.2.js:374)
    at HTMLImageElement.elemData.handle (jquery.js:4121)
```

##### Steps to reproduce the problem.
* screenshot into clipboard
* paste into RTE
* see error

Odd note: if I click the image (i.e. select it very quickly) during upload, before it completes, then it's fine. 

##### OS.
Mac OS Sierra

##### Browser.
Chrome Latest

**Comment by stefanneculai** [comment]
@jpgilchrist are you using V2.6.0? This problem is not happening there.

**Comment by jpgilchrist** [comment]
@stefanneculai nope we were on 2.5.1 at the time. We will upgrade. Thanks!
