### ISSUE TITLE
Image insert missing cursor

### ISSUE THREAD

**Issue by rblin081** [froala/wysiwyg-editor#1959]
##### Expected behavior.
After inserting image, clicking off of image (anywhere in editor) should show blinking cursor

##### Actual behavior.
After inserting image, clicking off of image(anywhere in editor) does not show a blinking cursor

##### Steps to reproduce the problem.
Insert image (will be selected with blue box)
Click off of image
Begin typing to show that editor is active / confirm cursor position
Letters will show but cursor is not visible

##### OS.
Windows 7

##### Browser.
Firefox

**Comment by stefanneculai** [comment]
This appears to work just fine on the current master. Could you please provide a place where we can reproduce this with the master version?
