### ISSUE TITLE
List group font-size should be the same as children

### ISSUE THREAD

**Issue by jeremylynch** [froala/wysiwyg-editor#1962]
##### Expected behavior.
List group (`ul`) font-size should be the same as children (`li`)

##### Actual behavior.
Bullet font-size does not change when font-size of children is changed. 

Word processors such as Microsoft word and Google docs change the bullet/list font size when the font size of children changes.

**Comment by stefanneculai** [comment]
When the font-size is changed for a list item, there is inline style being applied. Unfortunately, that is not possible to be done for list bullets. One possible approach would be to apply the font size directly on the list item, but that means that the content should be wrapped with another tag if there is inline style and it would result in a very messy HTML.

**Comment by jeremylynch** [comment]
@stefanneculai if all children are selected, couldn't we just apply the inline styling directly onto the `ul` element?
