### ISSUE TITLE
Resize image with handles produces poor scaling when browser is resized.

### ISSUE THREAD

**Issue by jkeatingatigloo** [froala/wysiwyg-editor#1963]
##### Expected behavior.
When you resize an image, either with the drag handles or with the input field it should scale the same way.  

##### Actual behavior.
When you resize an image with the drag handles and resize your browser window it will not scale nicely - the height remains the same and squishes the width.  If you resize using the size input (width only) the image scales nicely and does not distort the proportions.  

When resizing the the image with the drag handles a height is applied to the image which is causing the issues scaling. 

##### Steps to reproduce the problem.
Upload an image to the Froala demo page, resize it with the handles. Resize the browser.

![froala_image_resize](https://cloud.githubusercontent.com/assets/24943924/25859495/b58c4fcc-34ac-11e7-8980-f26945efee4e.gif)

**Comment by largeden** [comment]
@stefanneculai 
I thought this problem was solved in #769.
But I think the issue is happening again.
