### ISSUE TITLE
On Android a backspace on an newline causes the screen to scroll down

### ISSUE THREAD

**Issue by tmpg** [froala/wysiwyg-editor#1964]
##### Expected behavior.
Backspace to delete the newline

##### Actual behavior.
The backspace deletes the newline but also forces a scroll down

**For some reason on my site the scroll down happens on a newline also. Very odd. I used to use 2.4 and I did not have this issue.**

##### Steps to reproduce the problem.
Go on the froala site (Android and chrome) and delete everything. Then make a single newline. Delete that newline. The screen should scroll down

Gif of the issue
http://gph.is/2puFpV7

##### OS.
ANDROID 

##### Browser.
Version 57.0.2987.133

**Comment by stefanneculai** [comment]
@tmpg this should be fixed now here on Github and we'll update our website by the end of this week.
