### ISSUE TITLE
Pasting formatted text from word does not maintain indentation

### ISSUE THREAD

**Issue by PDiddyStyleShrimpingVessel** [froala/wysiwyg-editor#1967]
##### Expected behavior.
Text that is indented in a Word document and pasted into an editor should keep its indented formatting

##### Actual behavior.
The text indentation is lost

##### Steps to reproduce the problem.
1. Download the following document  [Text Formatting.docx](https://github.com/froala/wysiwyg-editor/files/990264/Text.Formatting.docx)
2. Paste the contents into an instance of froala wysiwyg

See this occur on this JS fiddle: https://jsfiddle.net/f87vde0c/
And also occuring on the demo on the Froala home page: https://www.froala.com/wysiwyg-editor

##### OS.
Windows 10

##### Browser.
Chrome 57.0.2987.133

**Comment by stefanneculai** [comment]
This should be fixed on the current Github master.
