### ISSUE TITLE
Table, td, th tags do not receive styles when useClasses is set to 'false'

### ISSUE THREAD

**Issue by raerae13** [froala/wysiwyg-editor#1968]
##### Expected behavior.
We are setting the useClasses option to false, so expect that styles for all elements should be inline.
Using Froala version 2.6.0

##### Actual behavior.
For table elements, we are seeing that the td, and th styling doesn't get added. Specifically, we are not seeing styling for borders, border-collapse, or background color (for the th tag)

##### Steps to reproduce the problem.
1. Set useClasses to false
2. Create a table with headers in the editor
3. Try to view the editor html somewhere without the froala stylesheet referenced.
4. The table cells will be borderless and the table header background will not be gray.

Here is a video that demonstrates what we are seeing.
[FroalaTableStylesWithNoClasses.zip](https://github.com/froala/wysiwyg-editor/files/990944/FroalaTableStylesWithNoClasses.zip)

##### OS.
Windows 10 Pro

##### Browser.
Chrome: Version 58.0.3029.110 (64-bit)

**Comment by stefanneculai** [comment]
@raerae13 this works correctly in our tests. Could you please make a jsFiddle or CodePen to reproduce this?

**Comment by raerae13** [comment]
This fiddle shows what we are seeing... the table cell and table header default styles (borders and background color) don't get applied inline on html.get. This happens with static html and when a table is created using the insert table button in the editor.

https://jsfiddle.net/sarae13/aytbdzwj/

**Comment by stefanneculai** [comment]
The problem on jsFiddle is coming from the fact that the `froala_style.css` file is not included from the same URL as the JS. Copying it to the STYLE directly in jsFiddle fixes it: https://jsfiddle.net/6h7xcqdy/2/.
