### ISSUE TITLE
Pasting Links With Ampersands Crashes Browser

### ISSUE THREAD

**Issue by apoktechnology** [froala/wysiwyg-editor#1969]
##### Expected behavior.
Pasting a link should not cause the browser to crash.

##### Actual behavior.
Web page becomes unresponsive. In Chrome, you have to "End Task" and Firefox you have to "Stop Script".

##### Steps to reproduce the problem.
Load the Url plugin and then paste a link such as http://www.domain.com/test/?NAME1=VALUE1&NAME2=VALUE2

##### OS.
I'm using Windows 10.

##### Browser.
I'm using the latest versions of Chrome (58.0.3029.110) and Firefox (53.0.2).

**Comment by stefanneculai** [comment]
@apoktechnology are you experiencing that on our website? Please make sure you are using the latest version 2.6.0.

**Comment by apoktechnology** [comment]
Stefan,

Yes, I am experiencing the issue on your full featured demo:

https://www.froala.com/wysiwyg-editor/examples/full-featured

Try the following link:

https://www.amazon.com/s/ref=nb_sb_noss?url=me%3DA1VBI64L0E2QBN&field-keywords=XPS+8910
