### ISSUE TITLE
url detection requires user to type an additional character

### ISSUE THREAD

**Issue by bboyle** [froala/wysiwyg-editor#1971]
##### Expected behavior.
Typing `www.google.com` should link to `//www.google.com`

##### Actual behavior.
Link to `//www.google`, the .com suffix is not included in the link.
```html
<a href="//www.google">www.google</a>.com
```

##### Steps to reproduce the problem.
1. Type "www.google.com"
2. Do not type anything after .com

We would like the url detection to be a touch smarter about what the URL the user is typing, and not rely on that extra character at the end. It works really well now if they type a URL and period, comma, space or line break—but if they just type a URL and nothing else it's confusing.

##### OS.
Windows 10

##### Browser.
Chrome 58

**Comment by stefanneculai** [comment]
Hi @bboyle! We consider this as being the correct behavior and it's unlikely to make the change you are suggesting. That is the way most of Word processors and Email clients works.
