### ISSUE TITLE
toolbarContainer causes weird scrolling issues when pressing Enter or Backspace

### ISSUE THREAD

**Issue by theknet** [froala/wysiwyg-editor#1973]
I'm using toolbarContainer to move the toolbar into a container which can be dragged around the screen. I've noticed that when the toolbarContainer option is used and you're scrolled down a page, if a user presses enter or backspace the page scrolls so the cursor position is at the bottom of the page.

I haven't been able to reproduce this in the Froala examples and I've tried removing all events from my custom toolbar container but haven't had any success.

Does Froala do any kind of focussing on the toolbar while typing (though this does seem to be limited to Enter and Backspace keys).

##### OS.
macOS Sierra 10.12.4

##### Browser.
Safari 10.1

**Comment by stefanneculai** [comment]
Yes, there is some logic there behind for the cases when you hit enter & backspace in order to scroll the editor contents correctly. If you could provide a jsFiddle we could definitely look into it.

**Comment by theknet** [comment]
Not a problem. I've created a basic version [here](https://jsfiddle.net/mcjyg52c/).

I can't seem to replicate the Enter behaviour but if you press backspace while scrolled down the page it will scroll the cursor out of view (I think it attempts to scroll to the top of the page each time)

**Comment by jturmel** [comment]
I'm having the same problem when hitting "enter", it pushes the scroll of the page down quite a bit.
