### ISSUE TITLE
Possibility to cancel the loading of an image?

### ISSUE THREAD

**Issue by starceaker** [froala/wysiwyg-editor#1975]
##### Expected behavior.
After uploading an image, the text / flow changes to downloading the image you just put on the server so you can display it. Sometimes, for different reasons (network delay is one), the loading of this image can take a long time (> 30 seconds). This can give the user the impression that the site is hanging, etc.

At this moment I can't seem to delete this image to cancel the image load proces. Am I missing something or is there no "abort" option?

##### Actual behavior.
Expected behaviour combines this in one story.

##### Steps to reproduce the problem.
Expected behaviour combines this in one story.

##### OS.
Windows 10

##### Browser.
Google Chrome 57.0.2987.133

**Comment by stefanneculai** [comment]
At this moment that is not possible. I am adding this as a `feature-request`.

**Comment by stefanneculai** [comment]
We've just put together a public roadmap with the most popular features. 😍 There you can vote your favorite one, provide feedback or make new suggestions: https://wysiwyg-editor-roadmap.froala.com/public.
