### ISSUE TITLE
Browser just down after paste the Link

### ISSUE THREAD

**Issue by DingGGu** [froala/wysiwyg-editor#1977]
I just paste a link on froala editor, browser directly not responding inifinitly. 
I use Froala 2.6.0

##### Steps to reproduce the problem.
Paste Link

https://support.google.com/chrome/answer/95617?visit_id=1-636304956992260619-4017060553&p=ui_security_indicator&rd=1&hl=ko

##### OS.
Mac 10.12.4

##### Browser.
Chrome latest

**Comment by thedotedge** [comment]
Reproducible with Chrome 58.0.3029.110 (64-bit) Mac.

**Comment by sandeepsukhija** [comment]
Also reproducible on froala site: https://www.froala.com/wysiwyg-editor
Browser : Chrome 58.0.3029.81 (64- bit) Ubuntu

Another Link:
https://www.owler.com/reports/mithi-s/vaultastic-now-offers-email-archiving-for-zimbra--/1495121521608?utm_campaign=ep&utm_source=snapshot&utm_medium=articlelink&source=snapshot_events_page
