### ISSUE TITLE
Popup shown after selecting datetime in Angular datetimepicker

### ISSUE THREAD

**Issue by starceaker** [froala/wysiwyg-editor#1979]
##### Expected behavior.
After selecting a datetime in the Angular datetimepicker it just does it's date magic and nothing else happens.

##### Actual behavior.
See attachment, there's a "edit link" popup being shown after selecting the datetime.
The fr-active class is added to the popup, for an unknown reason.
I have many guesses as to what is going on but none of them seem to add up so I'm hoping you can shed some light on this, see whether you have any ideas as to what is going on.

![datetimepicker popup issue](https://cloud.githubusercontent.com/assets/7840830/26110358/60792fc2-3a52-11e7-8f23-f502970bb163.gif)

**Update**
We have noticed that the root cause lies more in the fact that this popup is generated (HTML wise). It shouldn't be there in the first place. For example when you add an image, then it also generates a popup tag to go with it.
In my scenario, no popups should be visible in the HTML.

**Question**
What logic generates the HTML of these popups? One of my colleagues does not have this issue (also uses Chrome) and another colleague does have the issue so it's not consistent.

##### Steps to reproduce the problem.
See attachment.
I also attached a code snippet of one of those datetimepickers. If I remove the class on  
`<div class="input-group">` then the popup is not visible anymore (and the fr-active is also not triggered). However, if I add the same styling without using that class name the issue still occurs so it's not class name related probably.

`.input-group {
    position: relative;
    display: table;
    border-collapse: separate;
}`

[datetimepicker code snippet.txt](https://github.com/froala/wysiwyg-editor/files/1004709/datetimepicker.code.snippet.txt)

##### OS.
Windows 10

##### Browser.
Google Chrome 
Version 58.0.3029.110 (64-bit)

**Comment by stefanneculai** [comment]
@starceaker please make sure you are using editor version 2.6.0 which is the latest. Also, please make a plunker where we can reproduce this. Thank you.

**Comment by starceaker** [comment]
Hi @stefanneculai , looks like that fixed it. Sorry for missing this and thanks for the tip!

**Comment by stefanneculai** [comment]
@starceaker no problem. Thanks for confirming it!
