### ISSUE TITLE
Developing plugins for froala editor

### ISSUE THREAD

**Issue by cksachdev** [froala/wysiwyg-editor#1982]
I am trying to develop plugins for froala editor. Could you please point me to the necessary resources to get started.
Also where can I find un minified version of existing plugins?

**Comment by stefanneculai** [comment]
@cksachdev the unminified JS for the editor is available only under the Advanced and OEM licenses.  You can find more details about creating a plugin on our website: https://www.froala.com/wysiwyg-editor/docs/concepts/custom/plugin.

**Comment by cksachdev** [comment]
Thx for the quick response. Are there any more resources for developing plugin apart from that link?

**Comment by stefanneculai** [comment]
Inside the docs from our website, you can find more resources: https://www.froala.com/wysiwyg-editor/docs.

**Comment by NathanCH** [comment]
@stefanneculai, any chance you guys could provide unminified version for any of the plugins inside `froala-editor/plugins` there are about 30 there. That would be immensely useful for developers to study and create there own and would benefit the Froala project in the long run.
