### ISSUE TITLE
Can't get Froala to work in an Electron app

### ISSUE THREAD

**Issue by maxthet604** [froala/wysiwyg-editor#1983]
I'm using Electron to build an app. Other plugins works but not Froala. Froala successfully loads in the browser but not in Electron. I also have Jquery included. 

Here's my code:
In my index.html, i put the <script> tag at the end of the page:
``` 
<script>
        window.$ = window.jQuery = require('./js/jquery.js');
        require('./froala/js/froala_editor.min.js');
        require('./froala/js/align.min.js');
        require('./froala/js/font_size.min.js');
        require('./froala/js/colors.min.js');
        require('./froala/js/table.min.js');
        require('./js/core.js');
</script> 
```
In my core.js file, I initialize Froala like below:
```
$(function () {
    $.FroalaEditor.DefineIconTemplate('md_icon', '<i class="mdi mdi-[NAME]"></i>');
    $.FroalaEditor.ICON_DEFAULT_TEMPLATE = 'md_icon';
    $('#note-content-input').froalaEditor();
});
```

##### Expected behavior.
Froala successfully loads and initializes the editor.

##### Actual behavior.
I run the app using `npm start`. The Console shows: 
`Uncaught TypeError: Cannot read property 'DefineIconTemplate' of undefined`
`Uncaught TypeError: $(...).froalaEditor is not a function`

**Comment by stefanneculai** [comment]
@maxthet604 it looks like somehow the editor is not being loaded on the global jQuery variable. It would be amazing if you could put together a simple Electron app that we can get and help you fix this.

**Comment by maxthet604** [comment]
@stefanneculai Here you go. Sorry, want to make it fast, so I upload a .zip instead :)
[FroalaTest.zip](https://github.com/froala/wysiwyg-editor/files/1014636/FroalaTest.zip)

**Comment by stefanneculai** [comment]
@maxthet604 you should do it like this:
```html
  <!-- Insert this line above script imports  -->
  <script>if (typeof module === 'object') {window.module = module; module = undefined;}</script>

  <script src="js/jquery.js"></script>
  <script src="froala/js/froala_editor.pkgd.min.js"></script>
  <script src="js/core.js"></script>

  <!-- Insert this line after script imports -->
  <script>if (window.module) module = window.module;</script>
```

See more details here: http://stackoverflow.com/a/37480521/1806855.

**Comment by maxthet604** [comment]
Thanks, that solved the problem
