### ISSUE TITLE
IE 11 Font Family / Font Size Selection Issue

### ISSUE THREAD

**Issue by rblin081** [froala/wysiwyg-editor#1988]
##### Expected behavior.
Highlighed / selected text should keep selection when using dropdown menus
##### Actual behavior.
Highlighted / selected texts loses selection

##### Steps to reproduce the problem.
Highlight text in the editor. Click font family or font size toolbar button. Hover over a menu item. Editor selection is lost. There is no way to apply style to selection as it is no longer selected.

##### OS.
Windows 10

##### Browser.
IE 11

**Comment by stefanneculai** [comment]
It appears to work just fine on the current master version.
