### ISSUE TITLE
Local network links are being treated as text urls without a protocol

### ISSUE THREAD

**Issue by jhubert** [froala/wysiwyg-editor#1989]
##### Expected behavior.

If we enter a local network URL when creating a link, the link should be considered valid and send the user to the right place.

##### Actual behavior.

Entering a local network URL causes the URL to be prefixed by `http://`, which breaks the link.

![image](https://cloud.githubusercontent.com/assets/3384/26293147/59cc7374-3e70-11e7-9b60-e11eb508d720.png)

Becomes

![image](https://cloud.githubusercontent.com/assets/3384/26293150/5da397b6-3e70-11e7-948e-5a30bfc7af9d.png)

##### Steps to reproduce the problem.

- Create a link, setting the URL to `G:\\network\file` and the text to whatever you'd like.
- Click script and check the `href` of the link you created.

##### OS.
Tested on OSX 10.11.6 natively and Windows 8.1 via BrowserStack.

##### Browser.
Chrome Version 58.0.3029.110 (64-bit) on OSX 
IE 11 on Windows

**Comment by jhubert** [comment]
I made a small modification to `plugins/link.js` to add support for this.

I replace line 603 with the following:

```javascript
      /*****
      * Make sure network paths are not autoprefixed
      *
      * This regex matches G:\file\path.txt and \\network\file\path
      ******/
      var network_path_regex = /^(\\(\\[^\s\\]+)+|([A-Za-z]:(\\)?|[A-z]:(\\[^\s\\]+)+))(\\)?$/;

      // Add autoprefix.
      if (editor.opts.linkAutoPrefix !== '' && !/^(mailto|tel|sms|notes|data):.*/i.test(href) && !/^data:image.*/i.test(href) && !/^(https?:|ftps?:|file:|)\/\//i.test(href) && !network_path_regex.test(href)) {
```

**Comment by NikolaosWakem** [comment]
UNC paths like that mensioned above 

\\network\file\path 

don't seem to work :-( 

It still produces 

<a href="http://%5C%5Cnetwork%5Cfile%5Cpath">\\network\file\path</a>

in the HTML
@stefanneculai
