### ISSUE TITLE
tableInsert not fired when adding table via Quick Insert

### ISSUE THREAD

**Issue by raerae13** [froala/wysiwyg-editor#1990]
##### Expected behavior.
When table is inserted via Quick Insert, the tableInsert command should get fired.

##### Actual behavior.
The tableInsert command doesn't seem to get fired when a table is inserted via Quick Insert.

##### Steps to reproduce the problem.
Click on a new line to activate the Quick Insert tool. 
Choose Insert Table.
froalaEditor.commands.after doesn't get fired

##### OS.
Windows 10 Pro

##### Browser.
Chrome: Version 58.0.3029.110 (64-bit)

**Comment by stefanneculai** [comment]
Inserting table via Quick Insert tool is designed not to fire the `commands.after` because those are not regular buttons inside the editor. I marked this as a `feature-request` and is going to be implemented together with the possibility of adding custom buttons inside the Quick Insert tool.

**Comment by justcookit** [comment]
Hi, are there any updates on this?

Is there a possibility to make quick insert table button behave similarly to the toolbar table insert button without re-implementing table size selection popup from scratch? Currently quick insert table button just adds default 2 x 2 table, but I need this to be configurable here as well as in the toolbar.

**Comment by justcookit** [comment]
Is it even possible to add a manually implemented table size selection popup for quick insert table button?
