### ISSUE TITLE
Link open in new tab option is broken

### ISSUE THREAD

**Issue by wrporter** [froala/wysiwyg-editor#1991]
##### Expected behavior.
When creating or editing a link, I should be able to toggle the option to open the link in a new tab.

##### Actual behavior.
When clicking on the "Open in new tab" option, the popup disappears, the option does not toggle, and my link is not inserted or modified.

![froala-link](https://cloud.githubusercontent.com/assets/2702937/26359326/621f80e8-3f92-11e7-923c-e90bc69df48c.gif)

##### Steps to reproduce the problem.

1. Click the link button
2. Enter a URL and text
3. Click "Open in new tab"

OR

1. Insert a link
2. Click on the link
3. Click edit
4. Click "Open in new tab"

##### OS.
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36

##### Browser.
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36

##### Froala Version

Froala 2.6.0

**Comment by stefanneculai** [comment]
@wrporter we are not able to reproduce it. Could you make a jsFiddle?

**Comment by wrporter** [comment]
I am running this on lite-server. It looks like there is a conflicting issue with browser sync. Feel free to disregard, as this won't affect any production systems, unless you'd like to solve the problems presented with browser sync. If I am able to reproduce with a production server, I'll note back here.
