### ISSUE TITLE
Popup within a popup

### ISSUE THREAD

**Issue by wrporter** [froala/wysiwyg-editor#1993]
The documentation is not very clear around all of the functionality of Froala, particularly on custom components. What's the most appropriate way to show a popup within a popup so that the containing popup does not vanish? 

This seems like it would be a common use case so that the editor does not have to show all available options on the main toolbar.

##### Expected behavior.
When the inner popup is shown, the containing popup remains visible.

##### Actual behavior.
When the inner popup is shown, the containing popup disappears.

##### Steps to reproduce the problem.
![froala-inner-popup](https://cloud.githubusercontent.com/assets/2702937/26366171/4841a36c-3fa7-11e7-8714-19fbd6559215.gif)

##### OS.
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36

##### Browser.
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36

##### Froala Version
Froala 2.6.0

**Comment by stefanneculai** [comment]
You should pass `popup: true` as an option for the button inside the popup. If you are using the default buttons, then it would be best to do something like this:

```js
$.FroalaEditor.COMMANDS.insertImage.popup = true;
```

**Comment by wrporter** [comment]
@stefanneculai Wouldn't your example apply to all instances of the editor? Is there a way to do this for a single instance?

**Comment by stefanneculai** [comment]
Yes, that applies to all editor instances because this is how button actions are defined in the editor. For a single instance, it would be best to define custom buttons for those actions.

**Comment by wrporter** [comment]
@stefanneculai It's not clear from the docs, is there a way to inherit one of the current buttons and just add the `popup` option to the new command?

**Comment by wrporter** [comment]
@stefanneculai Looks like your recommendation to use `$.FroalaEditor.COMMANDS.insertImage.popup = true;` actually makes things worse. I threw together a [codepen](https://codepen.io/wesleyrporter/pen/zwgRyo) so you can see. Wouldn't this be considered a bug in Froala?
