### ISSUE TITLE
codeViewKeepActiveButtons does not apply to buttons in popups

### ISSUE THREAD

**Issue by wrporter** [froala/wysiwyg-editor#1994]
##### Expected behavior.
`codeViewKeepActiveButtons` applies to all buttons, including buttons in popups, not just the ones in the main toolbar.

##### Actual behavior.
codeViewKeepActiveButtons does not apply to buttons in popups.

##### Steps to reproduce the problem.

1. Create a custom popup with built-in buttons.
2. Include the code view button in the popup.
3. Include the custom popup button in `codeViewKeepActiveButtons`
4. Click on the code view button.
5. Click again on the custom popup button. Note that all buttons are enabled.

![froala-codeview-popup](https://cloud.githubusercontent.com/assets/2702937/26367232/1b6be4ca-3fab-11e7-986d-2848e0405330.gif)

##### OS.
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36

##### Browser.
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36

##### Froala Version
Froala 2.6.0

**Comment by stefanneculai** [comment]
The current behavior is correct. The refresh methods for buttons are called only for buttons which are visible (the ones from your popup are not initially). It is best to make them inactive when you show the popup if codeView is active.

**Comment by wrporter** [comment]
@stefanneculai What's the most appropriate way to disable the buttons when codeView is active? It looks like there is special code that has more complexity than simply adding a disabled class to the buttons.
