### ISSUE TITLE
Provide a way to clean all source code and use plain text

### ISSUE THREAD

**Issue by wrporter** [froala/wysiwyg-editor#1995]
I want to use Froala for both email and SMS message editing. For SMS, I want to make sure the message doesn't have any source code, so what I get via a text message is what I see in the editor. Does Froala support this out of the box?

##### Expected behavior.
Provide an option to strip all HTML and only use plain text.

##### Actual behavior.
The option isn't available as far as I can tell from the documentation.

Froala Version 2.6.0

**Comment by stefanneculai** [comment]
We consider this as being out of the editor's scope. We would recommend to use a sanitizer on server side to remove the HTML entities and keep only the text.

**Comment by ryanholte** [comment]
@stefanneculai I am doing your recommendation, currently. What would you recommend to validate the editor isn't empty or doesn't have just a &nbsp; or space value.

**Comment by stefanneculai** [comment]
@ryanholte When the editor is empty it would return an empty string.
