### ISSUE TITLE
url plugin bug

### ISSUE THREAD

**Issue by largeden** [froala/wysiwyg-editor#1996]
##### Steps to reproduce the problem.

![url_bug](https://cloud.githubusercontent.com/assets/5575931/26413513/36bd9178-40e7-11e7-9c6e-6c31a3ab47ad.gif)

##### OS.
mac sierra

##### Browser.
firefox

---

I found a bug in version 2.6.0.
This bug can be fixed in the following ways:
(Could you solve it in a better way?)

```javascript
//plugins/url.js

    function _init () {
//...
        if (keycode == $.FE.KEYCODE.ENTER || keycode == $.FE.KEYCODE.SPACE || keycode == $.FE.KEYCODE.PERIOD) {
	        var el = editor.selection.element();
	        if((editor.browser.mozilla && el.tagName == editor.html.defaultTag().toUpperCase()) || el.tagName == 'A') e.stopImmediatePropagation();
	        else _inlineType();
        }
      }, true);
//...
    }

```

**Comment by stefanneculai** [comment]
Nice catch. 👍
