### ISSUE TITLE
Large resizing of image on short page causes editor to become unresponsive

### ISSUE THREAD

**Issue by jfrei** [froala/wysiwyg-editor#1997]
##### Expected behavior.
Resizing image should behave as normal, allowing user to resize irregardless of image dimensions.

##### Actual behavior.
While resizing an image in the editor, if the image height + image popup height > screen height the editor seemingly "crashes" (From user point of view). It becomes entirely unresponsive. This can be rectified by removing the ".fr-image-overlay" div, which is what causes the entire window to be blocked.

Note: We have the editor contained in multiple nested divs, one of which has a "max-height: calc(100vh - 61px);", and another that has "overflow: visible". However, even when removing these styles, the editor still has the same issues.

##### Steps to reproduce the problem.

1. Resize image quite large, enough to force it to grow the window size vertically.

![froala-bug](https://cloud.githubusercontent.com/assets/740059/26414030/161f2a7a-406b-11e7-9902-004a49f31622.gif)

##### OS.
Windows 10

##### Browser.
Chrome 58.0.3029.110 (64-bit)

**Comment by stefanneculai** [comment]
@jfrei please make a jsFiddle or CodePen to reproduce this. Thank you.

**Comment by stefanneculai** [comment]
Closing this due to lack of response. Would be happy to look into it if you could provide a jsFiddle so that we can see the problem. Thanks.

**Comment by robclancy** [comment]
We have this issue too. Doesn't happen all the time. I am able to reproduce by editing an old image in a table cell from our legacy articles from when we used redactor.  In a table cell it actually gets quite buggy, will try make something you can reproduce with.

I actually can't reproduce after some editing on the same article, will keep messing with it and try get it reproducible. 

I have had similar issues before where the overlay would essentially "lockup" the editor. I think you should add a click event to the overlay that checks if there is anything selected / any popup. Bit hacky though.

**Comment by robclancy** [comment]
Testing more the `mouseup` event isn't stopping the handle resizing, I then click to make it fire again and it stops the resizing however the overlay stays and the editor is locked.

**Comment by robclancy** [comment]
I can't reproduce on codepen and can't spend more time debugging, will wait for more user reports. If it is only legacy data then might be fine for us anyway.

**Comment by jfrei** [comment]
@robclancy Super excited you are having the same issue that we were. Unfortunately I also don't have the time to reverse engineer what's going on there. Our solution was ugly but simple: The editor used to grow with it's content, and as soon as the window grew large enough to warrant a scrollbar, Froala's image overlay basically won't go away.

So, we made the page tall enough that it always has a bit of a scrollbar to it; Ugly, but it has been saving us numerous headaches when our clients try to resize their content within the editor.

**Comment by phippster** [comment]
I want to chime in as well.  Same problem!  Resizing larger or smaller will freeze the entire browser after only a few pixels of size change.  This is a show stopper bug.

**Comment by phippster** [comment]
I've been working through lines of code to see if some parent element might have an overflow CSS attribute that is causing the issue -- no luck.  However, I found that if you enable the "iframe: true" option the resizing works!  So there is a conflict with something on the page.

**Comment by robclancy** [comment]
Yeah I couldn't reproduce on the demo sites or in the codepen or whatever
service I used which means something on my page is conflicting in some way.
I've had the issue in different situations. If iframe works then that's
good to know will just use it.
