### ISSUE TITLE
Where is quickInsertTags used?

### ISSUE THREAD

**Issue by largeden** [froala/wysiwyg-editor#1999]
Froala Editor v2.6.0

```javascript
quickInsertTags: ['p', 'div', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'pre', 'blockquote']
```

The `quickInsertTags` feature of the quick_insert plugin does not work. I can not see the relevant code.

**Comment by stefanneculai** [comment]
It looks like this option is not used because the editor is making use of the default block tags rather than using a custom list. It should be removed from there.

**Comment by largeden** [comment]
@stefanneculai 

I hope this option is used.
because, clicking on the hr tag causes problems.
And I am using it by adding code.
```javascript
//quick_insert.js

function _checkTag () {

  // If editor has focus.
  if (editor.core.hasFocus()) {
    var tag = editor.selection.element();

        // Add a quickInsertTags check.
	if($(tag.parentNode).hasClass('fr-element') || $.inArray(tag.parentNode.tagName.toLowerCase(), editor.opts.quickInsertTags) < 0) {
		hide();
		return;
	}
```

Please review.
