### ISSUE TITLE
Refresh not called for dropdowns and popups

### ISSUE THREAD

**Issue by wrporter** [froala/wysiwyg-editor#2000]
I have a custom menu button that is closed on refresh. It closes when I click on a button that performs some modification to the text. However, when I click on a dropdown or popup, the refresh function is not called. Interestingly, only the colors popup will trigger a refresh. How can I have my custom menu listen to when other items in the editor are clicked, so I know to close my menu?

Also, is there a way to listen to click events anywhere on the editor so I can close the menu when a user clicks outside of the menu? It appears that the editor is not propagating click events.

```javascript
$.FroalaEditor.RegisterCommand('myMenu', {
    icon: '<div class="menu"></div>',
    refresh: function($btn) {
        $btn.find('.menu')[0].closeMenu();
    }
});
```

##### Expected behavior.
When clicking on dropdowns or popups, buttons are refreshed.

##### Actual behavior.
When clicking on dropdowns or popups, buttons are not refreshed.

##### Steps to reproduce the problem.
![froala-custom-menu](https://cloud.githubusercontent.com/assets/2702937/26502612/a2638428-41fa-11e7-961b-7a62edb42883.gif)

**Comment by stefanneculai** [comment]
@wrporter that behavior is correct, refresh callback should not be called on showing a dropdown or popup because no change is made inside the editor. Creating a dropdown and using the **html** property within it would be a better approach because that would self-close the dropdown when you click on another dropdown or popup. 

https://www.froala.com/wysiwyg-editor/docs/concepts/custom/dropdown

**Comment by wrporter** [comment]
@stefanneculai Thank you for the reply! We'd like to keep our components decoupled from Froala as much as possible so they are reusable. I am using an AngularJS component for my menu. Is there any reason the color picker popup triggers a refresh and the others don't? Preferably, the experience would be the same. The menu in my example contains much more complexity than the Froala dropdowns offer, with nested menus, etc.
