### ISSUE TITLE
Suggestion for clear formatting

### ISSUE THREAD

**Issue by raerae13** [froala/wysiwyg-editor#2002]
##### Expected behavior.
Our users are confused that h1, h2, h3, blockquotes, etc don't get cleared to normal text when they click clear formatting. They don't realize that they aren't just looking at css styles. This is especially confusing for our users when they are copying and pasting from a website and they get mixed tag content without realizing that is what they are doing.

##### Actual behavior.
When clear formatting is clicked, any CSS styling is cleared but the headings, etc. aren't reset to normal text.

Suggestion: Perhaps resetting block level tags to normal text could be an option for the editor when clear formatting is clicked?

##### Steps to reproduce the problem.
Add text in an initialized editor that contains h1, h2, etc tags and also add some text that is styled with CSS (font size , bold, etc).
Select all and click clear formatting.
Only css styling is cleared, no block level clearing.

##### OS.
Windows 10 pro

##### Browser.
Chrome latest

**Comment by stefanneculai** [comment]
@raerae13 the clear formatting feature is designed to remove only the inline styles, not the ones for H1, H2, etc. Those are considered block styles and should not be removed that way. If you would like to implement it that way, I would to use the following approach:
1. Create a custom button
2. Within the custom button use selection.blocks to get the current blocks
3. Remove the styles you don't want on them

**Comment by faisal77** [comment]
@stefanneculai Can you please share an example to do this?
We want some <h1><h2> tags for headings and no such tag or style for normal text.
