### ISSUE TITLE
Aviary does not work with two editors

### ISSUE THREAD

**Issue by VitaliyLogvin** [froala/wysiwyg-editor#2003]
##### Expected behavior.
froala_editor v2.6.1
Aviary should support to work correctly with two froala editors.

##### Actual behavior.
froala_editor v2.6.1
When I'm on a page where there is no second froala editor(only one), Aviary and froala works correctly.
But when on the page where two froala editors are implemented, Aviary gives an error. And I can not write anything else in both editors(except emoji).

##### Steps to reproduce the problem.
1. Create two Froala editors
2. In the second editor open the Aviary(on Image). After the Aviary modal window is opened, it is necessary to close it.
3. Output an error in the console. Aviary no longer appears in both editors. And I can not write anything else in both editors.
4. If this is initially done with the first editor, then everything will work. And if this is initially done with the second gives an error. It's strange.
_Addition:_
When in first editor open Aviary on image, then close it. All is well. Then in the second editor I open Aviary, then close it. No errors but, image popup jumps over the picture of the first editor. 
5. Below i attached screenshots and Froala editors configuration files in zip file.

**Html**
`<textarea autocomplete="off" class="feditor" id="feditor" name="content"></textarea><textarea autocomplete="off" class="feditor" id="multichattext" name="content"></textarea>
`

**Connected styles**
`<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.3.0/codemirror.min.css">
	<link href="/feditor/css/froala_editor.pkgd.min.css" rel="stylesheet" type="text/css" />
	<link href="/feditor/css/themes/gray.min.css" rel="stylesheet" type="text/css" />
	<link href="/feditor/css/froala_style.min.css" rel="stylesheet" type="text/css" />`

**Connected JS**
`<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.3.0/codemirror.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.3.0/mode/xml/xml.min.js"></script>
    <script type="text/javascript" src="/feditor/js/froala_editor.pkgd.min.js"></script>
    <script type="text/javascript" src="/feditor/js/third_party/image_aviary.min.js"></script>
    <script src="/feditor/js/languages/ru.js"></script><script src="/js/main.js"></script><script src="/js/second.js"></script>
`

**Files Zip**
[Info about problem.zip](https://github.com/froala/wysiwyg-editor/files/1033519/Info.about.problem.zip)

Thank you,
Sincerely.

##### OS.
MacOS 

##### Browser.
FireFox, Chrome

**Comment by tnchuntic** [comment]
I am also having the same issue. I have traced the code and it all points to.
The issue was caused by $current_image not set and it will point to $(window)
**image_aviary.js -> plugin**
`
function _initAviary() {
...
..
..
// Select image and upload.
            editor.image.edit($(current_image)); // this is the call where current_image is empty/set to window.

}
`
**image.js -> plugin**
`
/**
     * Place selection around current image.
     */
    function _selectImage () {
      if ($current_image) {
        editor.selection.clear();
        var range = editor.doc.createRange();
        range.selectNode($current_image.get(0));
        var selection = editor.selection.get();
        selection.addRange(range);
      }
    }
`
![image](https://cloud.githubusercontent.com/assets/4864523/26569437/19bebf5a-454e-11e7-97d9-8fd1db69fb80.png)

![image](https://cloud.githubusercontent.com/assets/4864523/26569444/26a41832-454e-11e7-908c-74cf8aa12664.png)

**Somehow fixed it by removing this.**
`function launch () {
      // current_image = editor.image.get()[0];
      current_image = editor.image.get();

      feather_editor.launch({
        image: current_image,
        url: current_image.src
      });
    }
`

**Comment by VitaliyLogvin** [comment]
thank you
