### ISSUE TITLE
Froala strips out <p> inside <td>

### ISSUE THREAD

**Issue by ca-dsgn** [froala/wysiwyg-editor#2006]
##### Expected behavior.
When adding a

```
<table>
  <tr>
    <td><p>test</p></td>
  </tr>
</table>
```

via source code to Froala, it should stay as is when switching to normal view.

I also checked if the markup above is valid to html5's doctype: To check so, I pasted the code down below to https://validator.w3.org/nu/#textarea

```
<!DOCTYPE html>
<html>
<head>
<title>Test</title>
</head>
<body>
<table>
  <tr>
    <td><p>test</p></td>
  </tr>
</table>
</body>
</html>
```

The result:

> Document checking completed. No errors or warnings to show.

##### Actual behavior.
Froala strips out the &lt;p&gt; inside the &lt;td&gt; and adds a &lt;br/&gt; after it

```
<table>
	<tbody>
		<tr>
			<td>test
				<br>
			</td>
		</tr>
	</tbody>
</table>
```

##### Steps to reproduce the problem.
1. Go to https://www.froala.com/wysiwyg-editor
2. Paste the code above (first code) in code view
3. Leave code view and switch to normal view
4. Switch back to code view and check changed html

##### OS.
macOS (latest)

##### Browser.
Chrome (latest)

**Comment by stefanneculai** [comment]
This is the intended behavior for `P` tags inside table cells.
