### ISSUE TITLE
Set a custom filename in Content-Disposition header for paste uploads

### ISSUE THREAD

**Issue by retoheusser** [froala/wysiwyg-editor#2008]
##### Expected behavior.
I want to be able to set a custom `filename` property in the `Content-Disposition` header for the file upload instead of the fixed default `blob`. When i set it to `jpg` for example, the server will save the file as `file.jpg` instead of `file.blob`.
I was thinking of something similar to the option `fileUploadParam` or `imageUploadParam` which lets you set the `name` property likewise.

##### Actual behavior.
When pasting an image into the editor, its `filename` is automatically set to `blob`:
```
------WebKitFormBoundaryFtoyDIHLULLdqqF5
Content-Disposition: form-data; name="file"; filename="blob"
Content-Type: image/jpeg


------WebKitFormBoundaryFtoyDIHLULLdqqF5--
```
The server will save it as `file.blob`

##### Steps to reproduce the problem.
1. Copy an image
2. Paste it into the editor

##### OS.
Tested on OSX 10.10.5

##### Browser.
Tested on 58.0.3029.110 (64-bit)

**Comment by stefanneculai** [comment]
See https://www.froala.com/wysiwyg-editor/docs/options#requestHeaders.

**Comment by retoheusser** [comment]
@stefanneculai Thanks for your link. But this is not a HTTP request header but the header inside the payload of a `multipart/form-data` upload request. The Froala API already allows setting the `name` property via the `fileUploadParam`, but setting `filename` to something other than `blob` is not possible.

**Comment by stefanneculai** [comment]
Oh, you could use use `fileUploadParams` for that.
