### ISSUE TITLE
Local path URL sanitizing doesn't allow for spaces in paths

### ISSUE THREAD

**Issue by markedmondson** [froala/wysiwyg-editor#2009]
##### Expected behavior.
Adding a link such as `C:\Users\Public\Pictures\Sample Pictures\Jellyfish.jpg` should be recognized as a local link.

Changing the regex to the below works but I'm not sure what the intention of not allowing the space in the first place was?

```javascript
      var local_path = /^([A-Za-z]:(\\){1,2}|[A-Za-z]:((\\){1,2}[^\\]+)+)(\\)?$/i;
```

Encoding the URL manually with a %20 works but most people won't know to do that.

##### Actual behavior.
The path should be seen as local and not prefixed with http://

##### Steps to reproduce the problem.
Add a link to a local file path with a space.

##### OS.
Sierra

##### Browser.
Chrome

**Comment by jhubert** [comment]
I believe that was my mistake. I didn't account for spaces in the RegExp accompanied with my issue report.
