### ISSUE TITLE
Video "handle" breaks when not using `froala_style.css`

### ISSUE THREAD

**Issue by robclancy** [froala/wysiwyg-editor#2010]
The `.fr-video` needs to be `position: relative` otherwise `.fr-video::after` covers the entire editor up to the `.fr-element`.

I don't know if `froala_style.css` is meant to be required or not but this makes it so it is for videos, otherwise the handle to select the video is over the entire editor.

**Comment by stefanneculai** [comment]
Yes, froala_styles.css file is required.
