### ISSUE TITLE
Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by ellandebasque** [froala/wysiwyg-editor#2011]
Hello,
When I run ng serve I have the following message :
"Cannot read property 'length' of undefined"

I have this message when I run :
npm install ng2-froala-editor --save (no problem)

and add this in my app.modules.ts
// Editor Forala
import {FroalaEditorModule} from 'ng2-froala-editor/ng2-froala-editor'; // <-- Import it in your NgModule

I'm using Angular ^4.0.0 and "@angular/cli": "^1.0.0",

##### OS.
Ubuntu 16.04 LTS

**Comment by stefanneculai** [comment]
@ellandebasque `ng2-froala-editor` is not officially provided by us. Please use https://github.com/froala/angular2-froala-wysiwyg instead.
