### ISSUE TITLE
'Tab' action I want

### ISSUE THREAD

**Issue by eondcom** [froala/wysiwyg-editor#2013]
Inline mode or Editor mode, 
push 'tab' key, 

cf1. froala editor this action -> Indenting inside the editor

cf2. github issue editor this action -> another tag, escape textarea

I understand this behavior Froala Editor.
But, I want **escape textarea.** for Submit new article.

so, I want to have a shortcut key to escape the textarea.

ex.
Tab key : Indenting 
Shift Tab or Ctrl+Q or Alt+S(accesskey) : escape textarea.

PS. I don't speak English well. Please understand.

**Comment by stefanneculai** [comment]
By default, the editor is switching to the next input on the page when you hit the TAB key. If you want to disable it, then you could use the **tabSpaces** option.
