### ISSUE TITLE
Do u know 'Sir Trevor' Editor Function

### ISSUE THREAD

**Issue by eondcom** [froala/wysiwyg-editor#2014]
http://madebymany.github.io/sir-trevor-js/example.html

Sir Trevor Editor is capable of moving paragraphs.
but, Every time you type Enter, it is inconvenient for paragraphs to be created.

I think that, Enter is [P]. ctrl+enter is [DIV]

[div] is new paragraphs blocks. and then capable of moving paragraphs.

What do you think of this function?

ps. It is not limited to p and div tags for SEO.

**Comment by stefanneculai** [comment]
Thank you for your suggestion. I marked this as a `feature-request` and it is already on our TODO list.
