### ISSUE TITLE
Shift+Enter in blockquote splits into two blockquotes

### ISSUE THREAD

**Issue by firstladymb** [froala/wysiwyg-editor#2016]
##### Expected behavior.
Shift+Enter inside a blockquote inserts `<br>` creating a line break.

##### Actual behavior.
Shift+Enter inside a blockquote inserts `<p><br></p>` and splits blockquote into two blockquotes.

##### Steps to reproduce the problem.
[https://www.froala.com/wysiwyg-editor](url)
1. Highlight text and click Quote > Increase to add a blockquote.
2. Insert cursor between sentences in second paragraph of blockquote.
3. Use Shift+Enter to add a line break.

![Shift+Enter in Blockquote](http://g.recordit.co/RuMj8u9YMt.gif)

##### OS.
Macintosh OS X 10.12.5

##### Browser.
Chrome 58.0.3029.110
Firefox 53.0

**Comment by stefanneculai** [comment]
That is the intended behavior. Quotes are designed not to allow creating a new line inside them.

**Comment by firstladymb** [comment]
Thanks, Stefan. I believe the reason this behavior is the expected is because blockquotes act that way in at least two other major editors (CKEditor and TinyMCE). People used to working with blockquotes in those are reporting this as a bug to us. We do have a workaround (applying the blockquote last applies it to the whole section), but I wanted to put this on the radar in case others run into the same complaints.

**Comment by poohitan** [comment]
@firstladymb can you please elaborate on your workaround for this issue?

**Comment by poohitan** [comment]
hey @firstladymb I would be very thankful if you respond to my question :)

**Comment by poohitan** [comment]
@firstladymb I see. Thank you so much!
