### ISSUE TITLE
Froala textarea editor within a custom popup

### ISSUE THREAD

**Issue by rugarcialopez** [froala/wysiwyg-editor#2018]
##### Expected behavior.
Froala textarea editor should work within a custom popup.

##### Actual behavior.
Froala textarea editor does not work within a custom popup. When I try to update the default content displayed in textarea element is not possible. It is impossible to set the focus within of textarea element.

##### Steps to reproduce the problem.
https://cl.ly/1T3S050J0e0G

##### OS.
(OS Sierra version 10.12.5)

##### Browser.
(Chrome 58.0.3029.110)

**Comment by rugarcialopez** [comment]
@stefanneculai any idea when you will add this enhancement?

**Comment by stefanneculai** [comment]
@rugarcialopez would it be possible to provide more details about the use case you have for this?

Unfortunately, V2 was not designed to allow this and this issue will remain a `wontfix` for now. Additional details you could provide would help us to better understand your needs and design further editor major versions to accommodate such cases as well.
