### ISSUE TITLE
Does not load buttons in array toolbarButtons when toolbarInline is true

### ISSUE THREAD

**Issue by AyrtonHenrique** [froala/wysiwyg-editor#2019]
##### Expected behavior.
Custom  buttons inline toolbar

##### Actual behavior.
ignore buttons in array when toolbarInline is true

##### Steps to reproduce the problem.
Does not load buttons in array toolbarButtons .

```
$('#selector').froalaEditor({
toolbarButtons: ['bold', 'italic', 'underline'],
                        toolbarInline: true,
                        pastePlain: true,
                        enter: $.FroalaEditor.ENTER_BR,
                    });
```
test in  [https://codepen.io/Froala/pen/evobdr ](https://codepen.io/Froala/pen/evobdr ) is not working. 
##### OS.
Windows 10

##### Browser.
Mozila Firefox 53.0.3

**Comment by stefanneculai** [comment]
We just updated the CodePen.
