### ISSUE TITLE
Android: Inline editor won't open after inserting text

### ISSUE THREAD

**Issue by riccardomessineo** [froala/wysiwyg-editor#2020]
##### Expected behavior.
On inline editor mode if I modify a text and then select it, I expect Froala to open up.

##### Actual behavior.
On inline editor mode if I modify a text and then select it, Froala doesn't open.

##### Steps to reproduce the problem.
Visit https://www.froala.com/wysiwyg-editor/inline from an Android Device.
Long press (select) on "Inline" --> Froala opens correctly.
Place your cursor next to "Inline" and add a word, then long press on any words --> Froala doesn't open

![ezgif-3-a6a4afe8b8](https://cloud.githubusercontent.com/assets/10194398/26822163/70d2c42a-4aa9-11e7-9f4c-ab98dea814c9.gif)

##### OS.
Android 6.0.0

##### Browser.
Chrome 58.0.3029.83

**Comment by riccardomessineo** [comment]
Any news?

**Comment by stefanneculai** [comment]
@riccardomessineo we just tried to reproduce this on the latest editor version and the issue appears to be fixed. If you still have the problem, please let us know.
