### ISSUE TITLE
how to disable quick insert bar?

### ISSUE THREAD

**Issue by bonesoul** [froala/wysiwyg-editor#2022]
after 2.6.0 upgrade, although i don't include quick_insert.min.js with my distribution, it started rendering. how can i completely disable it?

setting `quickInsertButtons: []` as empty didn't help.

i guess there may be a bug.

**Comment by stefanneculai** [comment]
You could either not include the Quick Insert plugin or disable it through the `pluginsEnabled` option.

**Comment by bonesoul** [comment]
i actually did not include it. but i'll try pluginsenabled.

**Comment by zakutnya** [comment]
@bonesoul 
Hi! It was complicated for me to disable Quick Insert using `pluginsEnabled` option because i use **pkgd** version of Froala, so i just set `quickInsertTags` options value to `['']` in order it wouldn't show anywhere. Worked for me. Hope it helps)

**Comment by swarupbam** [comment]
@bonesoul Thanks. It worked for me.

**Comment by tobiaszuercher** [comment]
hi, is there still no other way to disable the quick insert?

**Comment by Merenia** [comment]
Have you tried `quickInsertTags: null `? It worked for me.

**Comment by cbielich** [comment]
@Merenia Worked for me, Thanks!

**Comment by Kayui** [comment]
@Merenia This will cause an error which I'd rather not have.
![image](https://user-images.githubusercontent.com/4786413/46141826-964d1980-c244-11e8-99cf-a525a8fddc5c.png)

@vesrah has a solution that works fine for the pkgd version.

**Comment by stefanneculai** [comment]
The best way would be not to include the JS for the Quick Insert plugin. As an alternative, you could use the `pluginsEnabled` option, where you'd pass all the plugins you want enabled, except the Quick Insert one.

**Comment by yeshchaubey** [comment]
@Raghav-khunger 

It's work for me. Thanks for help. It's nice way for solution.

**Comment by Calvin-Coomer** [comment]
I couldn't get any of the above to work, used css instead

.fr-box.fr-basic .fr-insert-helper.fr-visible {
        display: none;
}

Worked for me

**Comment by bholtbholt** [comment]
Undocumented, but adding `quickInsertEnabled: false` to your config disables the quick insert bar without errors or CSS hacks

```javascript
$('.selector').froalaEditor({
  quickInsertEnabled: false
});
```

**Comment by habibulislam6862** [comment]
> Undocumented, but adding `quickInsertEnabled: false` to your config disables the quick insert bar without errors or CSS hacks
> 
> ```js
> $('.selector').froalaEditor({
>   quickInsertEnabled: false
> });
> ```

get some error in console.

**Comment by osahner** [comment]
> > Undocumented, but adding `quickInsertEnabled: false` to your config disables the quick insert bar without errors or CSS hacks
> > ```js
> > $('.selector').froalaEditor({
> >   quickInsertEnabled: false
> > });
> > ```
> 
> get some error in console.

thanks!

**Comment by AFDevMike** [comment]
`pluginsEnabled: [],` worked for me and produced no console errors.
