### ISSUE TITLE
Buttons not showing in Safari 10.1

### ISSUE THREAD

**Issue by acufarah** [froala/wysiwyg-editor#2024]
##### Expected behavior.
The toolbar buttons should show their symbols: i.e. B for bold, etc. 

##### Actual behavior.
The toolbar buttons are not showing their symbols, but they are clickable and functioning. The functions, like "bold" are showing when I hover the mouse over the button. 

##### Steps to reproduce the problem.
(Describe the steps to reproduce the problem here)

##### OS.
Mac OS Sierra 10.12.4

##### Browser.
Safari 10.1

**Comment by stefanneculai** [comment]
Are you seeing that on our website? Could you please clear cache?
