### ISSUE TITLE
ERROR in Cannot read property 'getSourceFile' of undefined

### ISSUE THREAD

**Issue by ellandebasque** [froala/wysiwyg-editor#2025]
Hello,
when I add in app.module.ts this line :
import {FroalaEditorModule} from 'ng2-froala-editor/ng2-froala-editor';

I have the following message error (when ng serve is running) :
ERROR in Cannot read property 'getSourceFile' of undefined
or this one (when i start ng serve):
Cannot read property 'length' of undefined

In my package.json I have "ng2-froala-editor": "^1.0.17"
In node_modules the ng2-froala-editor exists.

It seems that this file doesn't exist :
/node_modules/typings/globals/core-js/index.d.ts

Thank you.

##### OS.
Ubuntu

##### Browser.
Google chrome

**Comment by ellandebasque** [comment]
From node_modules folder :
typings install --save --global dt~core-js

**Comment by stefanneculai** [comment]
@ellandebasque `ng2-froala-editor`plugin is not created and maintained by us. The official angular plugin for the editor is: https://github.com/froala/angular2-froala-wysiwyg.
