### ISSUE TITLE
Inconsistent behaviour when uploading pasted images fails

### ISSUE THREAD

**Issue by markedmondson** [froala/wysiwyg-editor#2026]
##### Expected behavior.
When inserting an image from clipboard, if the upload fails I expect to see an error message which then removes the image after I acknowledge it (the same way as if an image upload fails when I attach through the image plugin)

##### Actual behavior.
If the pasted image fails to upload, no error is thrown, the image element is left inside the editor - the knock-on effect of this is that if the image is pasted from Word, a huge data-uri version of the image may be saved inline with the content.

##### Steps to reproduce the problem.
https://jsfiddle.net/markedmondson/ugtxdcLk/

![froala](https://user-images.githubusercontent.com/1653699/27108377-b3d8a926-5051-11e7-98b8-5d3200df3227.gif)

##### OS.
Sierra

##### Browser.
Chrome

**Comment by stefanneculai** [comment]
@markedmondson could you please send the document you're pasting from?

**Comment by markedmondson** [comment]
@stefanneculai Yep - nothing out of the ordinary.

[Test.docx](https://github.com/froala/wysiwyg-editor/files/1078507/Test.docx)
