### ISSUE TITLE
Pasting bullets using word cleanup loses indentation

### ISSUE THREAD

**Issue by jeremylynch** [froala/wysiwyg-editor#2029]
##### Expected behavior.
Copy paste from word into Froala when using MS word cleanup should still maintain indentation in lists/bullets. 

##### Actual behavior.
Indentation in lists/bullets is lost after cleaning. 

##### OS.
Mac OS

##### Browser.
Chrome

**Comment by stefanneculai** [comment]
@jeremylynch could you please send a document you're pasting from?

**Comment by jeremylynch** [comment]
No worries @stefanneculai 
[Sample Word document.docx](https://github.com/froala/wysiwyg-editor/files/1082837/Sample.Word.document.docx)

**Comment by stefanneculai** [comment]
Duplicate of #1967.
