### ISSUE TITLE
imageUploadParams value too long ?

### ISSUE THREAD

**Issue by watsy0007** [froala/wysiwyg-editor#2030]
##### Expected behavior.
(Describe expected behaviour here)

##### Actual behavior.
(Describe actual behaviour here)

![12256238-5e48-4a7a-8188-52d5fc820cb3](https://user-images.githubusercontent.com/822237/27194890-f7f77998-5236-11e7-84a5-69fb31be5b1d.png)
![e5c7a029-b8b6-4837-a374-9f96e15eec32](https://user-images.githubusercontent.com/822237/27194905-03872542-5237-11e7-9bfb-df2ce9b869db.png)

##### Steps to reproduce the problem.
(Describe the steps to reproduce the problem here)

```
uploadImagePrams: {
  token: 'xxxxxxxxxxxxxxxxxxxxx ... xxxxxxx'
}
```

##### OS.
(OS name and version here)
mac os 10.12.5

##### Browser.
(Browser name an version here)
58.0

**Comment by watsy0007** [comment]
@stefanneculai

**Comment by stefanneculai** [comment]
@watsy0007 could you please provide more details?

**Comment by watsy0007** [comment]
@stefanneculai sorry, it's my fault.
