### ISSUE TITLE
image.beforePasteUpload doesn't eventually trigger image.inserted

### ISSUE THREAD

**Issue by jpgilchrist** [froala/wysiwyg-editor#2033]
Not sure if this is a feature request or a bug fix... but this is pretty important for us.

##### Expected behavior.
We have functionality that's expected to run on every image uploaded, because we need to format the link/image tag a certain way with various attributes. 

I expected the image paste upload event would eventually trigger the `image.inserted` event because there's no equivalent `image.pasteInserted`, but alas it does not. I could try and do something in the `paste.after` event, but I really need to response from the server. 

##### Actual behavior.
`image.beforePasteUpload` does not trigger the `image.inserted` event. 

##### Steps to reproduce the problem.
Paste an image into the editor and have a breakpoint set in the `image.inserted` event and you'll see it's never called.

##### OS.
Mac OS Sierra

##### Browser.
Chrome latest

**Comment by barretts** [comment]
@stefanneculai this is still an issue. The `image.inserted` event is never called when pasting an image.

**Comment by stefanneculai** [comment]
@barretts could you please let us know the steps to reproduce it on a jsFiddle?https://jsfiddle.net/froala/wc5c3jhk/

**Comment by barretts** [comment]
https://jsfiddle.net/xj03w16y/

Paste an image into the editor, see the console log message `'image pasted; cancel the process'`. The image is inserted into the editor even after returning `false`. The image inserted event is never reached. If you remove the `return false;` from `beforePasteUpload` the inserted event appears as expected.

**Comment by stefanneculai** [comment]
That is because when you cancel the `image.beforePasteUpload`, the image is still inserted as base64 in the original HTML.

**Comment by zmysb** [comment]
> That is because when you cancel the `image.beforePasteUpload`, the image is still inserted as base64 in the original HTML.

How can I stop inserting as base64 in the original HTML?

**Comment by Hiaslafson** [comment]
Is there any way to stop inserting it as base 64?? Directly uploading it would be better
