### ISSUE TITLE
Extra lines inserted when changing line to header style

### ISSUE THREAD

**Issue by alassiter** [froala/wysiwyg-editor#2034]
##### Expected behavior.
When I change a line to a header style, I should not get extra lines entered elsewhere

##### Actual behavior.
When I have text in the editor. If I change a line to a Header style, extra lines are inserted wherever blank lines are. The following was recorded using the Enter Demo on the Froala website

![screen recording 2017-06-16 at 12 15 pm](https://user-images.githubusercontent.com/81304/27235241-fb38dd3e-528d-11e7-8e2c-ae30409f710a.gif)

##### Steps to reproduce the problem.
1. Enter this text:

```
Line 1 - one empty line after

Line 2 - two empty lines after


Line 3 - last line

Header - Change this to a heading style
```
2. Change the header line to a Header style

##### OS.
Mac 10.11.6

##### Browser.
Chrome 58.0.3029.110 (64-bit)

**Comment by stefanneculai** [comment]
It is fixed on the latest master.
