### ISSUE TITLE
Popup position moves

### ISSUE THREAD

**Issue by joelabair** [froala/wysiwyg-editor#2035]
##### Expected behavior.
the popup points to the element selected

##### Actual behavior.
the popup jumps approx. 200px to the right

##### Steps to reproduce the problem.
[https://codepen.io/joelabair/pen/eRggOm](https://codepen.io/joelabair/pen/eRggOm)

1. select all "paragraph text" in either editor
2. click the bold icon (or ctrl+b) - text is boldened and the popup remains
3. click the bold icon again (or ctrl+b) - text is unboldened and the popup moves to the right pointing to nothing.

##### OS.
any

##### Browser.
google chrome, firefox, opera, ...

**Comment by stefanneculai** [comment]
This issue has been fixed last week. It should work correctly on Github master.
