### ISSUE TITLE
Editor not showing up in production on Digital Ocean server

### ISSUE THREAD

**Issue by shawnpk** [froala/wysiwyg-editor#2036]
I'm implemented the wysiwyg-rails gem in my app. I followed the installation instructions and I have the editor working in development. When I push my app to my Digital Ocean server, the editor does not show up. I'm getting this error in the console:
`TypeError: $('#wysiwyg').froalaEditor is not a function. (In '$('#wysiwyg').froalaEditor', '$('#wysiwyg').froalaEditor' is undefined)`
I thought maybe I didn't have the jQuery gem installed (I'm using Rails 5.1.1), but it's definitely in my Gemfile. The first image below is my development app. The second is the production app.

<img width="1363" alt="screen shot 2017-06-18 at 10 25 24" src="https://user-images.githubusercontent.com/5712501/27262673-8af6f0a4-5410-11e7-905b-ac123e75776f.png">
<img width="1439" alt="screen shot 2017-06-18 at 10 25 34" src="https://user-images.githubusercontent.com/5712501/27262674-8c807e2c-5410-11e7-997a-0887f9a443de.png">

**Comment by stefanneculai** [comment]
@shawnpk for tech support please reach us via our website. Thank you.
