### ISSUE TITLE
Url parser after paste

### ISSUE THREAD

**Issue by romainjanvier** [froala/wysiwyg-editor#2038]
##### Expected behavior.
Transform url in pasted text into html link tag

##### Actual behavior.
The url doesn't match with the url plugin regexp

##### Steps to reproduce the problem.
Paste not only an url but a text containing an url, for example :
"Here is a site link :
https://developer.mozilla.org
This was the site link"

After that, to transform url into html link go at the end of the url line and type Enter.

**Comment by stefanneculai** [comment]
Please make sure you are using the latest version and that you include the URL plugin.
