### ISSUE TITLE
Access table cell formatting when focussed on link inside table cell

### ISSUE THREAD

**Issue by theknet** [froala/wysiwyg-editor#2039]
##### Expected behavior.
There should be a way to access table cell formatting toolbar when the cursor is within a link that resides in a table cell

##### Actual behavior.
While focused inside a link the only popup available is the link editing popup. Focusing inside non-linked text shows the table cell formatting. If the link is the only content inside the cell, there is no way to format the cell at all

##### Steps to reproduce the problem.
1. Create a table
2. Add text inside cell
3. Add a link to all text in the cell
4. Click inside the link

##### OS.
MacOS 10.12.5

##### Browser.
Safari 10.1.1

**Comment by stefanneculai** [comment]
There is a shortcut for enabling the table popup using keyboard only: `ALT + SPACE`. However, there was an issue and link popup was always showing over. Now if you click on a table cell with a link, the link popup would show, but if you hit `ALT + SPACE`, the popup one would appear.

All shortcuts can be found on [our website](https://www.froala.com/wysiwyg-editor/shortcuts) and they are also listed in the help button from the toolbar.

If you have suggestions for improving the UX for this case, we would definitely be interested in hearing them.
