### ISSUE TITLE
It's hard to get the cursor when I had inserted an video  into the edit.

### ISSUE THREAD

**Issue by yunClouds** [froala/wysiwyg-editor#2040]
##### Expected behavior.
 hardly to get the cursor when I had inserted an video  into the edit.

##### Actual behavior.
![image](https://user-images.githubusercontent.com/26613310/27314864-e2f5e2f8-55a8-11e7-8934-e46bd2df598c.png)

##### Steps to reproduce the problem.
After insert one video ,we always need to edit other parts of text , but  I found its  hard to get the cursor when I had inserted an video  into the edit.
##### OS.
My app is user Angular 4 and angular2-froala-wysiwyg

##### Browser.
chrom 57.0.2987.133

**Comment by stefanneculai** [comment]
Please make sure you have included the `froala_style.css` file. For that we designed the line breaker plugin, however there isn't too much we can do for it at this moment.

**Comment by yunClouds** [comment]
oh yeah , I  missing that file . Thank you @stefanneculai
