### ISSUE TITLE
image.insert() in a loop

### ISSUE THREAD

**Issue by krecebli** [froala/wysiwyg-editor#2041]
##### Expected behavior.
I am want to add checked images to the editor by iterating:

```js
var checkboxes = previews.querySelectorAll('input:checked'),
    len        = checkboxes.length - 1;
                
for ( ; len >= 0; --len) {
    $('.editor').froalaEditor(
        'image.insert',
        checkboxes[len].nextSibling.getElementsByTagName('img')[0].src,
        true
    );

    checkboxes[len].checked = false;
}
```

##### Actual behavior.
But only the first insert works (if let's say 10 checked checkboxes, only checkboxes[9] works), other doesn't work and there is even no error.

##### Steps to reproduce the problem.
I don't know could you reproduce it, but the steps are:
- I add this:
```js
.on('froalaEditor.commands.after', function (e, editor, cmd) {
    switch (cmd) {
        case 'insertImage':
            var imageManager = document.getElementById('imageManager-1');

            if (imageManager) {
                imageManager.dataset['multiple']    = 'true';
                imageManager.dataset['targetModal'] = 'images-modal';

                imageManager.addEventListener('click', openModal);
            }
            break;

        case 'imageManager':
            $(this).froalaEditor('imageManager.hide');
    }
})
```
So it opens custom modal instead of the froala's image manager.

- Then, when "Select" button at the modal is clicked, the code I described at "Expected behavior." runs to insert selected images into the editor.

##### OS.
Ubuntu 16.04.2 LTS

##### Browser.
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.86 Safari/537.36

**Comment by stefanneculai** [comment]
@krecebli after you insert one image, the editor selects that image and when you add the other image, the selected image is probably being replaced. What you should do is to place the selection after the just inserted image or use the `html.insert` method instead which would be a better approach in this case because the image wouldn't get selected.

**Comment by krecebli** [comment]
I can't use `html.insert` because I use `image.inserted` event, so how can I place the selection after the just inserted image (or deselect the just inserted image)? I couldn't find anything about this in the docs.

**Comment by stefanneculai** [comment]
See https://github.com/froala/wysiwyg-editor/issues/803#issuecomment-144942840. For tech support, please reach us via our website.

**Comment by krecebli** [comment]
I couldn't understand how the markers can help me. I am using froala just few days, don't know what ara markers for yet.

**Comment by stefanneculai** [comment]
You could place selection markers and then restore selection to have selection after the image.

**Comment by krecebli** [comment]
I tried this:

```js
var checkboxes = previews.querySelectorAll('input:checked'),
    len        = checkboxes.length - 1;

$('editor').froalaEditor('markers.insert');

for ( ; len >= 0; --len) {
    $('.editor').froalaEditor(
        'image.insert',
        checkboxes[len].nextSibling.getElementsByTagName('img')[0].src,
        true
    );

    $('editor').froalaEditor('selection.restore');

    checkboxes[len].checked = false;
}
```

Probably I misunderstood something.

**Comment by stefanneculai** [comment]
@krecebli we use this repo for bug tracking. Please contact us via our website for technical support. Thank you.

**Comment by krecebli** [comment]
I solved the problem. I used `selection.setAfter` method at `image.insert` event like this:
```js
$(this).froalaEditor('selection.setAfter', $img[0]);
```
And now it is working :) Thanks a lot!
