### ISSUE TITLE
Toolbar visible outside of bootstrap modal panel

### ISSUE THREAD

**Issue by RHinderiks** [froala/wysiwyg-editor#2044]
##### Expected behavior.
Toolbar visible within bootstrap modal panel or hidden.

##### Actual behavior.
When a modal panel contains an froala editor and its scrolled outside of the modal panel frame it sometimes pops up in the space above the modal panel when switching to an different window and back

##### Steps to reproduce the problem.
Place a froala editor inside an bootstrap modal panel and scroll until the froala editor toolbar is not visible anymore. Then tab to another window and back. The toolbar is now showing outside of the modal panel.

##### OS.
MacOS and Windows 10

##### Browser.
Edge
Internet Explorer
Chrome

Firefox and Safari seems to be working fine.

![screen shot 2017-06-21 at 13 33 52](https://user-images.githubusercontent.com/26223525/27382233-5978499c-5686-11e7-9560-5164c28b7ca1.png)

**Comment by stefanneculai** [comment]
Are you able to replicate it here: https://github.com/froala/wysiwyg-editor/blob/master/html/3rd-party/bootstrap/modal.html?

**Comment by RHinderiks** [comment]
Right i forgot to mention we use the angular version so the page you linked doesnt work quiet the same way, however adding multiple editors to that example results in some strange behaviour but this might just be an copy paste mistake at our end. 

![screen shot 2017-06-21 at 14 17 56](https://user-images.githubusercontent.com/26223525/27383805-d7f76996-568c-11e7-91cc-13be4ec6aaf0.png)

**Comment by stefanneculai** [comment]
@RHinderiks have you added https://github.com/froala/wysiwyg-editor/blob/master/html/3rd-party/bootstrap/modal.html#L44?

**Comment by RHinderiks** [comment]
This doesn't seem to have any effect

**Comment by stefanneculai** [comment]
@RHinderiks Could you please make a jsFiddle for it or something similar?

**Comment by RHinderiks** [comment]
That might be a bit difficult and time consuming, so we'll set up an testing env. (which we have done before for you) and i will mail you the info etc. (This might take some time)

**Comment by stefanneculai** [comment]
@RHinderiks Looking forward for that so that we can help with getting it work correctly for you.

**Comment by RHinderiks** [comment]
We solved out issue by setting toolbar sticky to false. Personally i think our combination of an outdated bootstrap was the problem maker here.. We'll keep an eye out for it in the future if it does pop up again we'll let you know.
