### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by JSteunou** [froala/wysiwyg-editor#2045]
Hi,

could you publish a new release please? I see a lot of bugfix since the last one (nearly a month) even some major fixes like this one #2004 which affect chrome 60 which is now out & public.

Thank you for your efforts, keep rocking :rocket:

**Comment by stefanneculai** [comment]
There is going to be a new release in couple of days.

**Comment by JSteunou** [comment]
Thank you @stefanneculai :)
