### ISSUE TITLE
No autofocus on mobile

### ISSUE THREAD

**Issue by mbaudry** [froala/wysiwyg-editor#2046]
Hello !

When the editor is initialized, I would like to autofocus it automatically. It works on my desktop, but nothing happened on mobile.

##### Steps to reproduce the problem.
https://jsfiddle.net/bysp4rxv/7/

##### OS.
iOS 10

##### Browser.
Safari

Thank you !

**Comment by stefanneculai** [comment]
On iOS it is possible to focus inside an input only after the user makes an action (e.g. clicking a button). This is a limitation set by Apple and there is no work around for it.

**Comment by mbaudry** [comment]
Ok, but I have the same thing on Android...
