### ISSUE TITLE
Update ember plugin Webpage

### ISSUE THREAD

**Issue by Panman8201** [froala/wysiwyg-editor#2048]
Another minor update whenever you get a chance, the [ember plugin Webpage](https://www.froala.com/wysiwyg-editor/docs/framework-plugins/ember) needs a couple changes;

1. The compatibility version should be changed to 2.4.**2**+
2. Remove the "Breaking changes..." section

Thanks!

**Comment by dianaprajescu** [comment]
Done. Thanks for the heads-up!
