### ISSUE TITLE
Emoticon popup does not fit on the screen

### ISSUE THREAD

**Issue by VitaliyLogvin** [froala/wysiwyg-editor#2049]
Hi. Can this be somehow corrected?
![screen shot 2017-06-25 at 16 01 01](https://user-images.githubusercontent.com/5080851/27516301-2f8268b0-59c0-11e7-99de-ef0bc63bdbe0.png)

**Comment by stefanneculai** [comment]
Hi @VitaliyLogvin! This is on our ToDo list as a `feature-request`. We don't have ETA for it at this moment.
