### ISSUE TITLE
Aviary Plugin - Uncaught TypeError: Cannot read property 'image' of undefined at HTMLImageElement.img.onload

### ISSUE THREAD

**Issue by tnchuntic** [froala/wysiwyg-editor#2051]
##### Expected behavior.
Aviary Plugin - Uncaught TypeError: Cannot read property 'image' of undefined at HTMLImageElement.img.onload

##### Actual behavior.
It should be saving the image without error.

##### Steps to reproduce the problem.
Step1: Edit image
Step 2: Save Image

Note: This bug/error is not consistently showing, sometimes the saving will be successful and sometimes it will throw this error.

##### OS.
Mac OS

##### Browser.
Chrome latest

##### Error screenshot.
![screen shot 2017-06-26 at 12 13 21 pm](https://user-images.githubusercontent.com/4864523/27523379-27b20504-5a70-11e7-9540-c1bfe4ee2faa.png)
![screen shot 2017-06-26 at 12 13 28 pm](https://user-images.githubusercontent.com/4864523/27523380-27b2ce58-5a70-11e7-85ae-a4ea82d43d85.png)

**Comment by stefanneculai** [comment]
@tnchuntic would it be possible to make a recording when this error happens? Maybe we can somehow find out in what conditions it happens?

**Comment by stefanneculai** [comment]
I'm closing this due to lack of response. We'd be happy to look again over it if you could provide more details.

**Comment by akomkov** [comment]
I have the same issue. @stefanneculai what recording do you need?

**Comment by stefanneculai** [comment]
@akomkov it would be helpful to have a recording of the steps to do to replicate it. A jsFiddle would also be handy: https://jsfiddle.net/froala/wc5c3jhk/.

**Comment by akomkov** [comment]
Maybe it will be helpfull for someone. For me problem was solved by changing the order of imported packages. My previuos (incorrect) variant was:

```javasccript
// ... some imports
import 'froala-editor/js/froala_editor.pkgd.min';
import 'froala-editor/js/third_party/image_aviary.min';
import 'froala-editor/css/froala_style.min.css';
import 'froala-editor/css/froala_editor.pkgd.min.css';
import 'font-awesome/css/font-awesome.css';
import FroalaEditor from 'react-froala-wysiwyg';
// ... some another imports
```

Now my correct variant looks like:
```javasccript
// ... some imports
import 'froala-editor/js/froala_editor.pkgd.min';
import 'froala-editor/css/froala_style.min.css';
import 'froala-editor/css/froala_editor.pkgd.min.css';
import 'font-awesome/css/font-awesome.css';
import FroalaEditor from 'react-froala-wysiwyg';
// ... some another imports
import 'froala-editor/js/third_party/image_aviary.min';
```

When I use `import 'froala-editor/js/third_party/image_aviary.min';` last all works fine

**Comment by demonspear** [comment]
i have the same issue. Here's the video i created to show you: 
https://youtu.be/m1Wd1jkkdKY
