### ISSUE TITLE
When inserting HTML using the API, URLs aren't linked

### ISSUE THREAD

**Issue by robclancy** [froala/wysiwyg-editor#2052]
##### Expected behavior.
I expect, just like when pasting or typing, that a URL will turn into a link.

##### Actual behavior.
Just inserts as text, you need to put cursor at the end of URL and press space to make it autolink.

##### Steps to reproduce the problem.
https://codepen.io/anon/pen/GEMywx

**Comment by stefanneculai** [comment]
`html.insert` method is designed to insert the HTML passed to it without making such changes.

**Comment by robclancy** [comment]
Why? That seems like a very weird design choice. Completely inconsistent and makes using froala feel buggy to users if you use ember or angular. I hope this project isn't an "it's a feature" echo chamber to avoid doing work. 

I don't care about `html.insert` but `html.set` which the ember and angular components use and won't autolink if the models have data already not created by froala.

So now I have to make our own components to hack in this functionalty because I can't even fork this properly.
