### ISSUE TITLE
picture load not working on Lumia 950

### ISSUE THREAD

**Issue by VitaliyLogvin** [froala/wysiwyg-editor#2054]
Users write.
_"On Lumia 950 (Windows 10 Mobile, Microsoft Edge browser). I click the picture icon, a window appears with the message that I need to select a file, click on it and it disappears. It's all. Nothing more happens."_

**Comment by stefanneculai** [comment]
@VitaliyLogvin Unfortunately, we don't have a way to test Windows 10 Mobile for now, however this appears to work just fine on Windows 8, Nokia Lumia 930. 

Windows mobile is not on our [official browser support list](https://www.froala.com/wysiwyg-editor/browsers). Anyway, if you know a way to simulate this, we'd be happy to reopen this and check it. Thanks.
