### ISSUE TITLE
No "contentChanged" event on iOS suggestion keyboard

### ISSUE THREAD

**Issue by JSteunou** [froala/wysiwyg-editor#2055]
##### Expected behavior.

Froala should trigger the `contentChanged` event

##### Actual behavior.

No event

##### Steps to reproduce the problem.

Use iOS, start typing a few letter, accept a word suggestion which will be paste inside the content editor, but hélas without `contentChanged` triggered.
User have to touch at least once the content editor to make froala trigger the event.

##### OS.

iOS 10

##### Browser.

Safari

**Comment by JSteunou** [comment]
@stefanneculai sorry but the bug is still present on last release and on froala website.

**Comment by stefanneculai** [comment]
That is strange, it works in simulator but not on the physical device. Reopening it.

**Comment by largeden** [comment]
@stefanneculai 
The following code will cause problems.
Upon deletion, uploading in IOS works.

```javascript
/js/plugins/image.js
      if (editor.helpers.isIOS()) {
        editor.events.$on($popup, 'touchend', '.fr-image-upload-layer input[type="file"]', function () {
          $(this).trigger('click');
        });
      }
```
