### ISSUE TITLE
Performance very slow on Android

### ISSUE THREAD

**Issue by setuun** [froala/wysiwyg-editor#2056]
##### Actual behavior.
We want to use the froala-editor in a slider(flickity),
but if we insert more than one instance, the slide animation gets very slow.
And it get worse with every additional instance.

First i thought, its the sliders problem, but after i made a testcase with Quill,
and added many many instances there, the slider doesnt get slow.

Please try to fix this, we really want to use your editor, because the editor is very nice apart from that.

##### Steps to reproduce the problem.
Testcase with Froala:
https://codepen.io/anon/pen/mwBgWm

Testcase with Quill
https://codepen.io/anon/pen/zzEXjx

##### OS.
Device: Nexus 5, Nexus 5X
Andoroid 6 and 7

##### Browser.
Latest Chrome Browser

**Comment by Panman8201** [comment]
Is it possible to initialize the froala-editor instances *after* the slider is open? I believe the froala-editor does some of it's own alignment stuff and that probably really takes a toll on the sliding animation.

Note, I'm not with the froala core team, just a suggestion from a fellow user. :)

**Comment by stefanneculai** [comment]
@setuun the problem is coming from the fact that in editor toolbar, the dropdowns are not actually hidden, but they have a height set to `0` and far on the left of the screen. Because of that inside the sliders the browser has to compute a lot of things. The best approach for it would be to force hiding dropdowns while animation like this: https://codepen.io/Froala/pen/yXdpNB.

```css
 .fr-dropdown-menu.force-hide {
   display: none !important;
}
```

```js
$('.main-carousel')
    .flickity()
    .on('select.flickity', function () {
        $('.fr-dropdown-menu').addClass('force-hide')
    })
    .on('settle.flickity', function () {
        $('.force-hide').removeClass('.force-hide')
    })
```
