### ISSUE TITLE
Code view keyup scrolls to top

### ISSUE THREAD

**Issue by b0gd4n** [froala/wysiwyg-editor#2059]
##### Expected behavior.
To be able to edit text in code view.

##### Actual behavior.
This is fine in normal view, but in Code View, if I scroll further down the page and as soon as I start typing, the container scroll all the way up. The carret stays in place, so as soon as you type again, it jumps back to where I want to edit, but when I release the key, it jumps back up. I added a gif showing the problem:

![jun 27 2017 12-25 pm 2](https://user-images.githubusercontent.com/1862528/27586013-63bbc55a-5b36-11e7-98f9-9765998a8692.gif)

##### Steps to reproduce the problem.
In Code View, edit any block of text long enough to have to scroll to the end.

##### OS.
macOS Sierra 10.12.5

##### Browser.
Chrome 59 & editor version 2.6.2

**Comment by stefanneculai** [comment]
@b0gd4n are you able to reproduce this on our website or could you please make a jsFiddle for it? Thank you.

**Comment by guiideandrade** [comment]
I found quite the same problem. Actually, any keystroke changes it to top.

**Comment by stefanneculai** [comment]
@guiideandrade are you able to reproduce that on our website? Could you please make a jsfiddle or codepen?

**Comment by guiideandrade** [comment]
@stefanneculai I can give you access to a demo account on Helpjuice KB if you like. Feel free to email me at guilherme at helpjuice.com

I still trying to reproduce it on your website/jsfiddle

**Comment by stefanneculai** [comment]
@guiideandrade if that is not happening on our website / jsFiddle then most likely it is not a problem from the editor, but rather a conflict with something else inside you app.

**Comment by stefanneculai** [comment]
Code Mirror should not be included in order to reproduce this issue.
