### ISSUE TITLE
There is a problem with blockquote processing in table.

### ISSUE THREAD

**Issue by largeden** [froala/wysiwyg-editor#2061]
![blockquote](https://user-images.githubusercontent.com/5575931/27588611-b74284fa-5b83-11e7-8885-e0e8973396fe.gif)

color plugin and paragraph plugin do not cause problems

froala editor v2.6.2

**Comment by stefanneculai** [comment]
This is the way blockquotes have been designed to work. They should wrap the outer block tag with a `quote` tag.

**Comment by largeden** [comment]
@stefanneculai 
Thank you. I understand.
