### ISSUE TITLE
Non-passive event listener to a scroll-blocking 'touchstart' event

### ISSUE THREAD

**Issue by natcohen** [froala/wysiwyg-editor#2062]
##### Expected behavior.
No warning and fast behavior

##### Actual behavior.
Warning and very slow behavior

##### Steps to reproduce the problem.
Check the console of chrome with verbose level and go to https://www.froala.com/wysiwyg-editor, you will see the following warning: `[Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive.`

The problem becomes extreme when using multiple editors in modals. For some reasons, when hovering over the editors, I'm getting thousands of these warnings and the editors become unusable

##### OS.
OSX

##### Browser.
Latest Chrome

**Comment by natcohen** [comment]
BTW I'm using [ngbootstrap modals](https://ng-bootstrap.github.io/#/components/modal)

**Comment by stefanneculai** [comment]
This is a `wontfix` for now as jQuery which we're using for binding events doesn't support that: https://github.com/jquery/jquery/issues/2871. We're working on a jQuery free version where this will be possible.
