### ISSUE TITLE
Paragraph alignment destroys table "style"

### ISSUE THREAD

**Issue by various89** [froala/wysiwyg-editor#2064]
##### Expected behavior.
When "styling" a table, e.g. insert a few lines of text with line breaks, the "style" of the table should not be touched when changing the alignment of some text outside the table.

##### Actual behavior.
"Styling" a table, e.g. insert a few lines of text with line breaks, the "style" of the table will be discarded when changing the alignment of some text outside the table.

##### Steps to reproduce the problem.
Create a table (e.g. one row, three columns) and insert three or four lines of arbitrary text, including line breaks. 
Change the alignment of a paragraph outside the table.
The line breaks, inside the columns, are gone.

##### OS.
4.11.6-3-ARCH

##### Browser.
Chromium	59.0.3071.109 (Developer Build) (64-bit)

**Comment by stefanneculai** [comment]
@various89 could you please make a recording? Are you able to reproduce this on our website?

**Comment by various89** [comment]
Yes, I'm able to reproduce it on your website. 

![33e21a412bbc4efa891f63f615265413](https://user-images.githubusercontent.com/1713375/27603032-1cea3140-5b75-11e7-9d52-1182a1406138.gif)
