### ISSUE TITLE
Integration question, true initialization hook even with the `initOnClick` option

### ISSUE THREAD

**Issue by Panman8201** [froala/wysiwyg-editor#2065]
I have an integration question/issue, the [ember-froala-editor plugin/addon](https://github.com/froala/ember-froala-editor/) does [additional (eventing) setup](https://github.com/froala/ember-froala-editor/blob/v2.6.2/addon/components/froala-editor.js#L347-L454) after the [initial `$('.selector').froalaEditor()` initialization call](https://github.com/froala/ember-froala-editor/blob/v2.6.2/addon/components/froala-editor.js#L295-L296). Currently this is done on a [`froalaEditor.initialized` event listener](https://github.com/froala/ember-froala-editor/blob/v2.6.2/addon/components/froala-editor.js#L285-L292) to gain access to the `editor` instance and to ensure the editor "is ready" (async). However, with the [`initOnClick` option](https://www.froala.com/wysiwyg-editor/docs/options#initOnClick), that hook is not called until, well, the editor is clicked (which is troublesome in this case). So what I need is a "hook" to run the additional setup code right after the initialization call and with access to the editor instance, no matter if the `initOnClick` option is used or not. Few questions/options;

1. Is there another event that I can use for this setup task? It seems like `froalaEditor.init` works but want to confirm that this is *ok* to depend upon and that the editor "is ready" in this case.

2. Is the `$('.selector').froalaEditor()` initialization call sync or async? In doing some research, [the](https://github.com/froala/react-froala-wysiwyg/blob/2.6.1/lib/FroalaEditorFunctionality.jsx#L76) [other](https://github.com/froala/angular2-froala-wysiwyg/blob/2.6.0/src/editor/editor.directive.ts#L197) [integration](https://github.com/froala/vue-froala-wysiwyg/blob/2.0.0/src/vue-froala.js#L100) [plugins](https://github.com/froala/knockout-froala/blob/2.6.1/src/knockout-froala.js#L69) [use](https://github.com/froala/angular-froala/blob/2.6.1/src/angular-froala.js#L122) a variation of the following for additional setup in sync mode. But is the editor truly ready in this case and is this an acceptable solution? `this.$element.froalaEditor(this.config).data('froala.editor').$el`

3. Is there another option? Looking to brainstorm on solutions for this issue.

** "is ready" = ok to call editor methods and such (interact with the editor instance)

Related Issue: froala/ember-froala-editor#40

**Comment by stefanneculai** [comment]
It is done async. At this point, there is no option for that. I am marking this as an `enhancement` and we'll add a new event specially for this. In the meanwhile, you could do that by using a timeout after calling the `$('.selector').froalaEditor()`.

**Comment by stefanneculai** [comment]
Last commit adds the `initializationDelayed` event which is being called just after the initial setup for `initOnClick` option.

**Comment by Panman8201** [comment]
Will this event also fire if the `initOnClick` option is *not* used?  Just wondering if I have to look for that option to determine what event (`initialized` or `initializationDelayed`) to attach to, or if I can just use `initializationDelayed` all the time. Thanks!

**Comment by stefanneculai** [comment]
@Panman8201 here is how it works:
`initOnClick: true`  ---> basic stuff ---> `initializationDelayed` ---> click ---> `initialized`
`initOnClick: false`  ----------------------------------------------------------> `initialized`

**Comment by kurdin** [comment]
initializationDelayed or initialized are not working.

https://codepen.io/anon/pen/MvEONa

**Comment by Panman8201** [comment]
@kurdin You are attaching the event handler after initializing the editor... Instead;

```js
$(function(){
    $('#edit').on('froalaEditor.initialized', (e, editor) => {
        alert('initialized');
    });
    $('#edit').froalaEditor({
        // toolbarInline: true,
        // initOnClick: true
    });
});
```

**Comment by kurdin** [comment]
@Panman8201 
hmm, that is strange because other events I tried work fine with attachment on init element.

I just tried this and it works as well
````js
$(function(){
  $('#edit').froalaEditor({
    toolbarInline: true,
    initOnClick: true
  }).on('froalaEditor.contentChanged', (e, editor) => {
      alert('changed');
  }).on('froalaEditor.initialized', (e, editor) => {
     alert('initialized');
 });
});
````
https://codepen.io/anon/pen/RZLQmo

**Comment by stefanneculai** [comment]
@kurdin this feature has been added in version 2.6.3, while you're using 2.6.0 in the CodePen: https://www.froala.com/wysiwyg-editor/changelog#2.6.3.
