### ISSUE TITLE
linkAutoPrefix default changed in 2.6.2

### ISSUE THREAD

**Issue by thedotedge** [froala/wysiwyg-editor#2067]
##### Expected behavior.
`bit-laboratory.com` to be linkified to `http://bit-laboratory.com`

##### Actual behavior.
`bit-laboratory.com` is linkified to `//bit-laboratory.com`

##### Steps to reproduce the problem.
Use default config. Adding `linkAutoPrefix: 'http://'` does not fix the problem.

**Comment by stefanneculai** [comment]
I believe you are talking about typing in the editor the link, not inserting it through the link popup. The links typed in the editor are not designed to use the `linkAutoPrefix` option, but they are set to follow the current page protocol, by adding the `//`.
