### ISSUE TITLE
Replacing an image causes jump to top

### ISSUE THREAD

**Issue by scribblerp9** [froala/wysiwyg-editor#2070]
##### Expected behavior.
Replacing an image shouldn't effect scroll position.

##### Actual behavior.
Replacing an image causes content to scroll to top, particularly problematic when editing a long document.

##### Steps to reproduce the problem.
1. Insert an image as normal
2. Click image, then the "Replace" button on the popup toolbar (arrows pointing in opposite directions).
3. Either drag and drop new image or click to replace
4. Once image dropped/selected, content jumps to top.
Demonstrated here: https://www.screencast.com/t/P0r3MEp53

##### OS.
Mac OS 10.12.5

##### Browser.
Chrome 59.0.3071.115

**Comment by stefanneculai** [comment]
@scribblerp9 it looks like you are not using the latest editor version 2.6.2. Could you please check that?

**Comment by stefanneculai** [comment]
Closing this due to lack of response. We'd be happy to look again into it if you could provide more details. Thank you.
