### ISSUE TITLE
Froala editor toolbar problem in asp.net 4.5 

### ISSUE THREAD

**Issue by indradeepc** [froala/wysiwyg-editor#2071]
Hi All,
This is my first issue related post on github, so if i violate any protocol kindly let me know.
I have integrated froala editor in asp.net 4.5.  I have added all the plugins and files as instructed in froala document. Editor is working fine except i couldn't  see char counter, Font family, Color picker and font size. I have done everything from my side but failed to know what i am doing wrong. 
Your kind help is much needed.

**What i have done:**
1. Font Awesome 4.2.0 is included
2. All the froala content, editor, page, style css are included.
3. All the plugins are there.
4. froala editor js is there.
5. I am using jquery1.11.1.

Below is my code: 

**Style and Script:**

    <link href="../Content/font-awesome.css" rel="stylesheet" type="text/css" />
    <link href="../Content/froala_editor.css" rel="stylesheet" />
    <link href="../Content/froala_page.css" rel="stylesheet" />
    <link href="../Content/themes/dark.css" rel="stylesheet" />
    <script src="../Scripts/jquery-1.11.1.min.js"></script>
    <script src="../Scripts/froala_editor.min.js"></script>
    <script src="../Scripts/plugins/block_styles.min.js"></script>
    <script src="../Scripts/plugins/colors.min.js"></script>
    <script src="../Scripts/plugins/file_upload.min.js"></script>
    <script src="../Scripts/plugins/font_family.min.js"></script>
    <script src="../Scripts/plugins/font_size.min.js"></script>
    <script src="../Scripts/plugins/lists.min.js"></script>
    <script src="../Scripts/plugins/media_manager.min.js"></script>
    <script src="../Scripts/plugins/tables.min.js"></script>
    <script src="../Scripts/plugins/video.min.js"></script>
    <script src="../Scripts/plugins/char_counter.min.js"></script>
     <script src="../Scripts/plugins/image.min.js"></script>
    <script src="../Scripts/froala_editor.min.js"></script>

**Body**
<div>
    <asp:TextBox ID="txtEditor" ClientIDMode="Static"
        runat="server" Height="199px" TextMode="MultiLine" Width="447px"></asp:TextBox>
    <br />
    <asp:Button ID="btnSave" runat="server" Text="Submit" />

    <style type="text/css">
        .froala-element {
            font-family: tahoma;
            font-size: 9pt;
        }
    </style>

    <script type="text/javascript">
        $(function () {
            $('#txtEditor').editable({
                buttons: ["bold", "italic", "underline", "strikeThrough", "fontFamily",
                    "fontSize", "color", "formatBlock", "align", "insertOrderedList",
                    "insertUnorderedList", "outdent", "indent", "selectAll", "createLink",
                    "insertImage", "insertVideo", "undo", "redo", "html", "save", "inserthorizontalrule","insertHTML" 
                ],
                maxCharacters: 500,
                inlineMode: false,
                spellcheck: true,
                plainPaste: false,
                preloaderSrc: 'Content/img/preloader.gif',
                allowedImageTypes: ["jpeg", "jpg", "png"],
                height: 300,
                language: "en_gb",
                //direction: "rtl",
                fontList: ["Tahoma, Geneva", "Arial, Helvetica", "Impact, Charcoal"],
                autosave: true,
                autosaveInterval: 2500,
                saveURL: '../FroalaHandler.ashx',
                saveParams: { postId: "123" },
                imageButtons: ["display", "align", "removeImage", "replaceImage", "linkImage"],
                borderColor: '#00008b',
                imageUploadURL: '../FroalaHandler.ashx',
                imageParams: { reqType: "AdminBlog" },
                imageAllowedTypes: ['jpeg', 'jpg', 'png'],
                enableScript: false,
                placeholderText: 'Placeholder',
            });

        });
        $('#btnSave').click(function () {
            var htmldata = $('#txtEditor').val();
            $.ajax({
                type: "POST",
                contentType: "application/json; charset=utf-8",
                url: "Default.aspx/SaveData",
                data: "{'html':'" + htmldata + "'}",
                dataType: "json",
                success: function (data) {
                    alert("Sucess");
                },
                error: function (result) {
                    alert("Error");
                },
                
            });
        });
       

    </script>
    <asp:RequiredFieldValidator ID="RequiredFieldValidator1" runat="server" ControlToValidate="txtEditor" ErrorMessage="RequiredFieldValidator"></asp:RequiredFieldValidator>
    </div>

**CS File**

    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Web;
    using System.Web.UI;
    using System.Web.UI.WebControls;
    using System.Web.Script.Serialization;
    using System.Web.Services;
    using System.Data;
    using System.Data.SqlClient;
    using System.Configuration;
    public partial class _Default : System.Web.UI.Page
    {
        protected void Page_Load(object sender, EventArgs e)
        {

        }
        protected void btnSave_Click(object sender, EventArgs e)
        {
            if (!string.IsNullOrWhiteSpace(txtEditor.Text))
            {

            }
        }
        [WebMethod]
        public static string SaveData(string html)
        {
            try
            {
                return "sucess";
           
            }
            catch (Exception ex)
            {
                throw ex; ;
            }
        }
    }

**Handler (FroalaFileHandler.ashx)**

    <%@ WebHandler Language="C#" Class="FroalaFileHandler" %>

    using System;
    using System.IO;
    using System.Web;
    using System.Web.Script.Serialization;

    public class FroalaFileHandler : IHttpHandler {

        public void ProcessRequest (HttpContext context) {
        string path = "";
        var body = context.Request.Form["body"];
        var reqType = context.Request.Form["reqType"];
        if (!string.IsNullOrWhiteSpace(body) && !string.IsNullOrWhiteSpace(reqType))
        {
            //todo: save changes

            context.Response.ContentType = "text/plain";
            context.Response.Write("");
            context.Response.End();
        }

        var files = context.Request.Files;
        if (files.Keys.Count > 0)
        {
            foreach (string fileKey in files)
            {
                var file = context.Request.Files[fileKey];
                if (file == null || file.ContentLength == 0)
                    continue;
                path= context.Server.MapPath("~/images/Blog/" + DateTime.Now.ToString("ddMMyyyy") + "/");
                if (!Directory.Exists(path))
                {
                    Directory.CreateDirectory(path);
                }
                var fileName = Path.GetFileName(file.FileName);
                var rootPath = path;
                file.SaveAs(Path.Combine(rootPath, fileName));

                var json = new JavaScriptSerializer().Serialize(new { link = "images/Blog/" + DateTime.Now.ToString("ddMMyyyy") + "/" + fileName });
                context.Response.ContentType = "text/plain";
                context.Response.Write(json);
                context.Response.End();
            }
        }

        context.Response.ContentType = "text/plain";
        context.Response.Write("");
        context.Response.End();
    }

    public bool IsReusable {
        get {
            return false;
        }
    }

    }

**Comment by stefanneculai** [comment]
@indradeepc please contact us via our website for tech support: https://www.froala.com/wysiwyg-editor/contact. Also, it would be helpful if you could send us a link where we can check it.
