### ISSUE TITLE
Dragging image into editor attempts to upload

### ISSUE THREAD

**Issue by dave-buzzy** [froala/wysiwyg-editor#2074]
##### Expected behavior.
Using Meteor JS package of Froala. Not allow images to be added to the editor via drag and drop if we don't allow paste or upload. 

##### Actual behavior.
Dragging an image into the editor still attempts to upload it. 

##### OS.
macOS Sierra 10.12.5

##### Browser.
Chrome Version 59.0.3071.115 - tries to upload, then renders broken image icon
Safari Version 10.1.1  - attempts to upload, shows loading bar popover, then popover vanishes and renders nothing (ie it's not trying to render image)

Have gone through https://github.com/froala/wysiwyg-editor/issues/1403 and https://github.com/froala/wysiwyg-editor/issues/561, and have set `imagePaste` to false, `pasteDeniedTags` set to `img`,  and 'allowedImageTypes' set to empty array; `plainPaste` is true as well. Have not yet tried modifying image.beforeUpload or the image plugin itself, but feel that if we don't allow paste of images or files, then drag and drop should be disabled as well, or at least available to disable as a separate option.

**Comment by stefanneculai** [comment]
The following code should to the trick.

```JS
$(selector).on('froalaEditor.initialized', function (e, editor) {
  editor.events.on('drop', function (dropEvent) {
      // Check if we are dropping files.
      var dt = dropEvent.originalEvent.dataTransfer;

      if (dt && dt.files && dt.files.length) {
        var img = dt.files[0];

        if (img && img.type && img.type.indexOf('image') !== -1) {
          dropEvent.preventDefault();
          return false;
        }
     }
  }, true);
}).froalaEditor();
```

**Comment by dave-buzzy** [comment]
Thanks, that was quick! Will try this.
