### ISSUE TITLE
Upload image throw Bad link error

### ISSUE THREAD

**Issue by eloufirhatim** [froala/wysiwyg-editor#2075]
Hello,

I have an issue with the video upload option, it always throw the **Bad link (code: 1)** error, whether it is the default `videoUploadURL` or my own, here is the javascript options that I passed to the froala wysiwyg:

`
videoDefaultAlign: 'left',
videoUploadParams: {_token: "{{ csrf_token() }}"},
videoAllowedTypes: ['webm', 'mp4', 'ogg'],
videoUploadURL: '{{ route("frontend.question.create.post.video") }}'
`

I am using Laravel framework on the server side, the upload is correctly done (server side) and the url returned is correct: `http://localhost:8000/questions/new-question/get-video/test.mp4`, this route allows to download the file from public path.

Do I miss something in the javascript options or what, because I have the same issue for the default `videoUploadURL` that is `http://i.froala.com/upload'`

thanks in advance

**Comment by stefanneculai** [comment]
@eloufirhatim The problem is most likely being caused by having a bad link in the response. For tech support please contact us via our website instead of Github.

**Comment by eloufirhatim** [comment]
Done, thank you for your help

**Comment by eloufirhatim** [comment]
@stefanneculai please can you check the contact mail that I send yesterday in your website, it's kind of major issue that I have to solve in a professional project.

Thanks in advance
