### ISSUE TITLE
Unexpected content cropping up in text

### ISSUE THREAD

**Issue by hay-wire** [froala/wysiwyg-editor#2076]
We are developing a content editing application and running into a wierd issue:

##### Expected behavior.
When clicked inside the content div, only the editor options and text inside the content div should appear.

##### Actual behavior.
When clicked inside the content, sometimes (not always), wierd text appears on the screen at random places

![image](https://user-images.githubusercontent.com/2913409/27826168-be288f5c-60cf-11e7-94b9-2b98b4bf71e0.png)

##### Steps to reproduce the problem.
Add multiple text editors in an html page and click on any one of the boxes, 3 out of 10 times, random `Heading 2 Heading 3` and other options appear on the screen as shown in the image above.

##### OS.
Windows 10, 

##### Browser.
Google Chrome 59.0.3071.115

Hoping for a quick reply.

**Comment by stefanneculai** [comment]
@hay-wire could you please make a jsFiddle or codePen to reproduce this? Thank you.

**Comment by hay-wire** [comment]
Sure. Let me make one.

**Comment by hay-wire** [comment]
@stefanneculai  Tried creating the fiddle here https://jsfiddle.net/e1vqkohd/1/ but its not initiating the editor at all, not sure why. However, the code gives an idea what I am trying to accomplish.

(Sorry for non-working fiddle, but I'm down with fever so could not complete it.)

**Comment by hay-wire** [comment]
Also we are using material design lite (mdl.io) as used in the jsfiddle if it helps.

**Comment by stefanneculai** [comment]
@hay-wire I've updated it and the editor initializes now: https://jsfiddle.net/e1vqkohd/2/. Please update it so that we can see the problem. Thank you.

**Comment by hay-wire** [comment]
@stefanneculai Apologies for the delay. I just recovered. Anyways, I'm unable to see toolbar buttons in any of the editors in the fiddle - https://jsfiddle.net/e1vqkohd/2/. Is this expected?

**Comment by stefanneculai** [comment]
That's because Font Awesome was not included. See: https://jsfiddle.net/e1vqkohd/3/.

**Comment by hay-wire** [comment]
@stefanneculai I'm unable to replicate this issue on jsfiddle. If you want, I can share the link and credentials where this application is hosted so you can take a look, and then you can advise if we can replicate it.

**Comment by stefanneculai** [comment]
@hay-wire if that is not possible to replicate in a jsFiddle then it is most likely related to the way your app is implemented, maybe other scripts interacting with the editor.

**Comment by hay-wire** [comment]
Okay. Any clue on how do I go about debugging it?

**Comment by stefanneculai** [comment]
The best way would be to remove other scripts from the app and see which one is causing the problem.

**Comment by hay-wire** [comment]
Cool. Let me try that. Thanks!
