### ISSUE TITLE
Allow typingTimer option to be 0.

### ISSUE THREAD

**Issue by bklik** [froala/wysiwyg-editor#2077]
##### Expected behavior.
typingTimer option should allow any time from 0+.

##### Actual behavior.
typingTimer option forces a minimum of 500ms.

In ReactiveForms, changes to form fields updates the valueChanges Observable. In all form fields this happens immediately, and are debounced at this point. However, the Froala field has an additional delay of 500 due to it's internal debounce. This should be configurable.

**Comment by stefanneculai** [comment]
Setting typingTimer to 0 would make typing laggy because when the HTML is taken from the editor, there is some processing which should be done.

**Comment by bklik** [comment]
Before arbitrarily closing this ticket, is there some non-stop zero number that is less than 500ms that can be made available?

**Comment by stefanneculai** [comment]
The minimum `typingTimer` value that can be set is 250ms.
