### ISSUE TITLE
url plugin bug(TLD problem)

### ISSUE THREAD

**Issue by largeden** [froala/wysiwyg-editor#2078]
##### Steps to reproduce the problem.
test.jpg
test.exe

##### Froala Version.
2.6.2

The domain link feature does not work correctly because the regular expression in the plugin does not check Domain TLD.

I changed the code by referring to the regular expression below.
https://autohotkey.com/boards/viewtopic.php?t=15269

```javascript
  $.FE.URLRegEx = '(^| |\\u00A0)((https?:\\/\\/(www\\.)?)?((?:[-a-zA-Z0-9@:%_\\+~#=]{2,256}\.)?(?:[-a-zA-Z0-9@:%_\\+~#=]{2,256}\.)(com|net|jp|kr|co|`domainTLD`)|([\\d]{1,3}\\.[\\d]{1,3}\\.[\\d]{1,3}\\.[\\d]{1,3}([-a-zA-Z0-9@:%_\\+~#?&/=]*))))$';
```

Also, it seems better to remove `$.FE.KEYCODE.PERIOD` from the key event.
Please check. :)

**Comment by largeden** [comment]
This regular expression is not perfect. I'll think a bit more.

**Comment by stefanneculai** [comment]
@largeden last commit should fix it. The regular expression for checking URLS is built differently now and it passes most of the validations from https://mathiasbynens.be/demo/url-regex, except the IPs one which IMO should be let as valid input from user in this case. Also, the [RegEx is safe](https://github.com/substack/safe-regex) which is a huge plus. It's built like this:
```js
  // Chars to allow.
  var x = 'a-z\\u0080-\\u009f\\u00a1-\\uffff0-9';

  // Common regex to avoid double chars.
  $.FE.LinkRegExCommon = '(([' + x + '])|([' + x + '](\\.|-|_))){1,}[' + x + ']{1,}';

  // PORT:something_else.php
  $.FE.LinkRegExEnd = '((:[0-9]{1,5})|())((\\/[a-z\\u00a1-\\uffff0-9@?^=%&amp;\/~+#-_{}]*)|())';

  // Common TLD
  $.FE.LinkRegExTLD = '((' + $.FE.LinkRegExCommon + ')(\\.(com|net|org|edu|mil|gov|co|biz|info|me|dev)))';

  // Starts with HTTP.
  $.FE.LinkRegExHTTP = '((ftp|http|https):\\/\\/(www\\.)?' + $.FE.LinkRegExCommon + ')';

  // Authenticate with HTTP.
  $.FE.LinkRegExAuth = '((ftp|http|https):\\/\\/(www\\.)?[\\u0021-\\uffff]{1,}@' + $.FE.LinkRegExCommon + ')';

  // Starts with WWWW.
  $.FE.LinkRegExWWW = '(((ftp|http|https):\\/\\/)?www\\.' + $.FE.LinkRegExCommon + '\\.[a-z0-9-]{2,24})';

  // Join.
  $.FE.LinkRegEx =  '(' + $.FE.LinkRegExTLD + '|' + $.FE.LinkRegExHTTP + '|' + $.FE.LinkRegExAuth + '|' + $.FE.LinkRegExWWW + ')' + $.FE.LinkRegExEnd;
```

PS: More details about that in a blog post shortly.

**Comment by largeden** [comment]
Thank you!
I am looking forward to the blog post. :p

**Comment by largeden** [comment]
hi @stefanneculai 
This regular still needs a modification.

The following text are also auto linked.
`test.comalekjfleafjljf`

**Comment by largeden** [comment]
@stefanneculai  👍
