### ISSUE TITLE
Retain only anchor tag links with plainPaste

### ISSUE THREAD

**Issue by manikmi** [froala/wysiwyg-editor#2080]
##### Expected behavior.
Retain the links with pasted content

##### Actual behavior.
the links are replaced with simple text

##### Steps to reproduce the problem.
1. Create a froala editor object with option plainPaste=true
2. Paste some content from the internet which contains text as well as links.
3. The Content styling is removed. Which is fine. I want to retain only the links. but the links are also remoed from the text, converted to plain text

##### OS.
Windows 10

##### Browser.
Google Chrome

**Comment by stefanneculai** [comment]
That is not possible to achieve via `pastePlain` option. This option is designed to remove all the formatting. A better way for achieving what you want would be not to enable the pastePlain option, but use filter options for pasting such as `pasteDeniedAttrs` or `pasteDeniedTags`.
