### ISSUE TITLE
No cursor displayed next to an image

### ISSUE THREAD

**Issue by jrust** [froala/wysiwyg-editor#2082]
##### Expected behavior.
When an image is in the editor a cursor can be seen either right before or right after it.  For example, in this demo for [TinyMCE](https://www.tinymce.com/docs/demo/image-tools/) you can click at the top of the document and see a cursor next to the header image.  However, in this [Froala demo](https://www.froala.com/wysiwyg-editor/examples/custom-image-button) a cursor does not show up next to the image.

##### Actual behavior.
When the cursor gets next to an image it disappears.

##### Steps to reproduce the problem.
Insert an image into the editor. Add some text. Use the left/right arrows to move cursor back to the image and see it disappear.

##### OS.
OSX Sierra

##### Browser.
Chrome 59

**Comment by stefanneculai** [comment]
@jrust that is happening only when the image display is set to `Break Text`. If you choose `Inline`, it would work just the way you are looking for. Unfortunately, when using the Break Text feature, it is not possible because of the way browser renders the cursor to show it.
