### ISSUE TITLE
styling lost when copy/pasting

### ISSUE THREAD

**Issue by nullest** [froala/wysiwyg-editor#2083]
1.copy some text with style, eg:

`<p style="font-size: 18px; color: rgb(0, 128, 255);">It is blue.</p>`

2.paste it into my editor or even [https://www.froala.com/wysiwyg-editor](https://www.froala.com/wysiwyg-editor)

3.click "Code View", and it becomes:

`<p>It is blue.</p>`

--------------

I've tried: 

- [https://github.com/froala/wysiwyg-editor/issues/1386](https://github.com/froala/wysiwyg-editor/issues/1386) 
- [https://github.com/froala/wysiwyg-editor/issues/1415](https://github.com/froala/wysiwyg-editor/issues/1415) 

but it does not work.

**Comment by stefanneculai** [comment]
@nullest please use https://www.froala.com/wysiwyg-editor/docs/options#pasteAllowedStyleProps. Also, make sure you are using the latest 2.6.2 version.

**Comment by nullest** [comment]
@stefanneculai , after updating to v2.6.2 from 2.6.1, it works. But it should config both 'pasteAllowedStyleProps' and 'pasteDeniedAttrs'. 

I wonder if the default value of 'pasteAllowedStyleProps' is not right in the [document](https://www.froala.com/wysiwyg-editor/docs/options#pasteAllowedStyleProps), because it just works after I copy the default value to config.

**Comment by stefanneculai** [comment]
@nullest it is right, the `pasteAllowedStyleProps` is not correct in docs. We just updated it.
