### ISSUE TITLE
Delete image confirmation dialog

### ISSUE THREAD

**Issue by abologna-r7** [froala/wysiwyg-editor#2084]
##### Expected behavior.
1. Open the image manager from the editor.
2. Click on the "trash icon" from one of the uploaded images.
3. Confirmation dialog shows up.
4. Use "froalaEditor.imageManager.beforeDeleteImage" event instead to capture the event and provide a custom made confirmation dialog.

##### Actual behavior.
Even though "froalaEditor.imageManager.beforeDeleteImage" event was provided, the confirmation dialog still opens up, even before the event itself, which my be misleading in some cases, resulting in the displaying of the default confirmation dialog, and the one made in the event.

This finding proves that the "froalaEditor.imageManager.beforeDeleteImage" actually does not fires before the deletion of an image, but only afterwards, that's why we can experience the firing of the default confirmation dialog, then the endpoint call from the **imageManagerDeleteURL** option parameter, and then and only then, the editor script calls the **froalaEditor.imageManager.beforeDeleteImage** event.

##### OS.
Mac OS 

##### Browser.
Chrome Version 59.0.3071.115 (Official Build) (64-bit)

**Comment by abologna-r7** [comment]
BTW, I'm using the **froalaEditor.imageManager.beforeDeleteImage** event inside the events react component property.

**Comment by stefanneculai** [comment]
The `imageManager.beforeDeleteImage` event is triggered after the confirmation message. At this moment it is not possible to replace the built-in confirmation message with a custom one without making changes directly on the editor JS code. I am marking this as a `feature-request` so that it's in our attention to add it eventually.

**Comment by abologna-r7** [comment]
Thank you Stefan!

**Comment by stefanneculai** [comment]
We've just put together a public roadmap with the most popular features. 😍 There you can vote your favorite one, provide feedback or make new suggestions: https://wysiwyg-editor-roadmap.froala.com/public.
