### ISSUE TITLE
Impossible to make an image float to left or right with text around

### ISSUE THREAD

**Issue by jpdupont** [froala/wysiwyg-editor#2087]
Firefox last, OSX last.
Impossible to make an image float to left or right with text around.

On example on your site, first page it works, but impossible to do the same. What settings please ???

Thanks

**Comment by jpdupont** [comment]
It works if I modify the style like this

`.fr-view img.fr-dib.fr-fil {
  margin-left: 0;
  float: left;
  margin: 5px 5px 5px 0;
  max-width: calc(100% - 5px);
}
.fr-view img.fr-dib.fr-fir {
  margin-right: 0;
  float: right;
  margin: 5px 0 5px 5px;
  max-width: calc(100% - 5px);
}`

**Comment by stefanneculai** [comment]
Please make sure you include the `froala_style.min.css` file.
