### ISSUE TITLE
Paste from Word does not work on IE11 or Edge

### ISSUE THREAD

**Issue by alexmoraru25** [froala/wysiwyg-editor#2089]
The word paste plugin does not work on IE11 or Edge, no error in the console, it's just not working. 

Windows 10 

IE 11 & Edge

**Comment by alexmoraru25** [comment]
Here is a demo on the website: http://recordit.co/bY2KL4qlCY

**Comment by stefanneculai** [comment]
This has been fixed few of days ago on the master repo. We update it on our website only after we make an official release. This update will be included in release 2.6.3.
