### ISSUE TITLE
Changing Special Characters Sets

### ISSUE THREAD

**Issue by SidKH** [froala/wysiwyg-editor#2090]
It seems like you don't have any information in docs on how to update Special Characters sets with your own characters, or remove some section from the set.
  
I ended up editing `$.FE.DEFAULTS.specialCharactersSets` but shouldn't this info been added into the docs?
  
Or maybe you have a better way of dealing with special characters sets?  
  
Thanks.

**Comment by stefanneculai** [comment]
Sure, those should be in docs as well.
