### ISSUE TITLE
Lettered lists

### ISSUE THREAD

**Issue by jeremylynch** [froala/wysiwyg-editor#2092]
##### Expected behavior.
It should be possible to add lettered (alphabetical) lists in addition to numbered and bulleted. Eg. 
```
a. List item 1
b. List item 2
c. List item 3
```

**Comment by stefanneculai** [comment]
Thanks for the `feature-request`, @jeremylynch!

**Comment by stefanneculai** [comment]
We've just put together a public roadmap with the most popular features. 😍 There you can vote your favorite one, provide feedback or make new suggestions: https://wysiwyg-editor-roadmap.froala.com/public.
