### ISSUE TITLE
unwanted link on strings

### ISSUE THREAD

**Issue by IraNostraEst** [froala/wysiwyg-editor#2094]
##### Expected behavior.
only link real links such as www.example.com or mail@example.com

##### Actual behavior.
links everything with "." in it. for example:
something.pdf   to   https://something.pdf/
some.string       to   https://some.string/

##### Steps to reproduce the problem.
type string with dot in editor.

##### Version.
latest 2.6.2

##### Browser.
Firefox 54.0.1

**Comment by stefanneculai** [comment]
Duplicate of #2078.
