### ISSUE TITLE
Cut/copy and paste is broken on Internet Explorer 11

### ISSUE THREAD

**Issue by codeabit** [froala/wysiwyg-editor#2096]
The **expected behavior** is that I can copy and/or cut any image or text in a froala document and then paste it into a different location in the document and it will appear unchanged from the source location. 

The **actual behavior** is that images don't copy or cut and any text that is copied or cut has "~~" prepended to it when it is pasted.

You can reproduce this issue by navigating to froala site (http://tinyurl.com/y9927y3x) and trying to cut/copy the text and/or image in the document and paste it into a different location.

Windows 10
Internet Explorer 11
Version: 11.483.15063.0

**Comment by stefanneculai** [comment]
It's fixed on the current Github master.

**Comment by codeabit** [comment]
I just tested with current Github master (349ffd527d88d421c4e1936088a0386d61db3b01) and copying/pasting images still does NOT work in IE 11.
