### ISSUE TITLE
New line make the parent page scroll to bottom

### ISSUE THREAD

**Issue by JSteunou** [froala/wysiwyg-editor#2097]
##### Expected behavior.

New line should add new line without scrolling the parent container

##### Actual behavior.

With current dev version (froala website) new line make the page scroll to bottom on mobile and small tablet in landscape mode

##### Steps to reproduce the problem.

Go to froala website demo editor with a mobile
Edit the text in the middle
Add new line (hit return)
boum, bottom page

##### OS.

Android 5,6,7

##### Browser.

Chrome 59

Seems like a regression, I remember having this issue months ago and someone from Korea too. If I find back the issue I will link it.

**Comment by stefanneculai** [comment]
@JSteunou Thanks for reporting it. We fixed that just yesterday here on Github. :)

**Comment by JSteunou** [comment]
Wow fast, very nice @stefanneculai :+1:
