### ISSUE TITLE
Event handling breaks when deleting one of multiple froala editors.

### ISSUE THREAD

**Issue by natashad** [froala/wysiwyg-editor#2099]
##### Expected behavior.
When multiple froala editors exist, deleting the first one should not effect the others in any way.

##### Actual behavior.
When multiple froala editors exist, deleting the first one effects the event handlers on the others.

##### Steps to reproduce the problem.
**JSFIDDLE**: https://jsfiddle.net/Panman8201/z5ux2c32/

* Create multiple Froala editors on a page.
* Upload an image to the first one.
* Delete/destroy the first editor. (In the example provided, click on the "Destroy Editor A" button.)
* Try uploading an image to the second editor.
* Notice that clicking on the "Drop Image" area closes the pop up and doesn't bring up the File Browser.

##### OS.
OSX

##### Browser.
Chrome (Version 59.0.3071.115)

##### Notes:
The issue seems to be in froala_editor.js in `FE.prototype.destroy` which is calling `this.events.$off`.

**Comment by AntiFreez** [comment]
I also found this issue.

**Comment by natashad** [comment]
This still seems to be broken (but slightly differently) using v2.6.5 : https://jsfiddle.net/L8m12nLh/1/

## Steps to reproduce the problem.

JSFIDDLE: https://jsfiddle.net/L8m12nLh/1/

Create multiple Froala editors on a page.

- Upload an image to the first one.
- Delete/destroy the first editor. (In the example provided, click on the "Destroy Editor A" button.)
- Try uploading an image to the second editor.
- **Slight variation from before:** clicking on upload an image brings up the file browser, but selecting a file doesn't do anything.

![77m5c3pr3e](https://user-images.githubusercontent.com/1857154/29465642-fff9fd70-8407-11e7-8fba-8517d44ef4e1.gif)
