### ISSUE TITLE
Paste cleanup removes empty HTML elements

### ISSUE THREAD

**Issue by UCIS** [froala/wysiwyg-editor#2100]
##### Expected behavior.
Pasting HTML containing empty <input type="button /> or <iframe src="" /> elements should preserve those elements.

##### Actual behavior.
When pasting HTML content, some empty HTML elements are incorrectly removed. Froala seems to use a white-list of tags which may be empty when pasting ('*:empty:not(br):not(img):not(td):not(th)'), but this does not include void elements like input, button and iframe, which may be valid in the editor. This also does not respect the list in the htmlAllowedEmptyTags option.

##### Steps to reproduce the problem.
Open two instances of https://jsfiddle.net/4jxr3mfx/11/
Copy the text including the button from the first instance and paste into the second instance.

##### OS.
Linux Mint

##### Browser.
Chrome 59.0.3071.115

**Comment by stefanneculai** [comment]
@UCIS please make sure you are using the latest version, in the jsFiddle it is version 2.2.4. Also, it is missing the 2nd editor instance. We've added one and appears to work fine: https://jsfiddle.net/4jxr3mfx/13/. If I missed something, please provide couple more details. Thank you.

**Comment by UCIS** [comment]
@stefanneculai I am not sure why the fiddle suddenly started working. Looking at the sourcecode and debugger, Froala seems to use a shortcut without cleanup when the pasted text (plaintext) matches previously copied content, which may in itself be incorrect since it allows to insert arbitrary HTML into the editor, as long as the resulting plaintext matches the copy buffer in local storage.

Anyway, it still does not work cross-domain. To reproduce:

- Open https://jsfiddle.net/ec0e675e/ and https://codepen.io/anon/pen/xLbwXJ
- Try to copy the text inside the froala editor from jsfiddle to codepen.
- The text will be copied, but the button element will be removed.

For comparison you may try to paste into TinyMCE (eg at https://www.tinymce.com/docs/demo/basic-example/). You will see that the button is pasted (although styling is off).

The problem is in the two lines (in the unminified froala_editor.js) containing: div.querySelectorAll('*:empty:not(br):not(img):not(td):not(th)');

This removes the <input type="button" value="button" /> because it has no DOM content. I think the input and iframe tags should be added to the list of exceptions, as those are all valid in a froala editor (with some plugins):
div.querySelectorAll('*:empty:not(br):not(img):not(td):not(th):not(input):not(iframe)');
