### ISSUE TITLE
Can not upload image, video and file on iOS Safari

### ISSUE THREAD

**Issue by BIGWOO** [froala/wysiwyg-editor#2105]
##### Expected behavior.
Upload image, video and file on iOS Safari.

##### Actual behavior.
No files have been uploaded after selecting a file.

##### Steps to reproduce the problem.
1.Use the iPhone to open the Froala wysiwyg-editor homepage.
2.Click Insert Image button.
3.Select a photo.
4.No files have been uploaded.

##### OS.
iOS 10

##### Browser.
Safari, Chrome

**Comment by largeden** [comment]
@stefanneculai
The following code will cause problems.
Upon deletion, uploading in IOS works.

/js/plugins/image.js
      if (editor.helpers.isIOS()) {
        editor.events.$on($popup, 'touchend', '.fr-image-upload-layer input[type="file"]', function () {
          $(this).trigger('click');
        });
      }

**Comment by BIGWOO** [comment]
Thank you!
