### ISSUE TITLE
Firefox: Spaces get removed when entering bolded text

### ISSUE THREAD

**Issue by adamcooper** [froala/wysiwyg-editor#2106]
##### Expected behavior.
When bold is turned on I expect spaces to behave the same when bold is turned off in Firefox.

##### Actual behavior.
When bold is turned on it looks like the space is registered but when a subsequent letter is typed the space is lost.

##### Steps to reproduce the problem.
Use Firefox
Turn on Bold
Type "first second" . 

And notice that "firstsecond" is what comes out.

##### OS & Browser
Firefox / Mac
Froala version: v2.6.4

**Comment by jtrain** [comment]
We are seeing this issue as well.

Firefox 54.0.1 on windows and mac.

We saw the issue appear in 2.6.2 and it wasn't present in 2.6.1. I downgraded our install to 2.6.1 and it resolved the issue.

I can reproduce the error (when bold is active) here: https://www.froala.com/wysiwyg-editor/examples/custom-buttons and the iframe demo. Perhaps other demos are also affected but I didn't check them - sorry.
