### ISSUE TITLE
Can not always detect paste from Excel in IE11

### ISSUE THREAD

**Issue by opalleq** [froala/wysiwyg-editor#2108]
Hi!

The confirmation popup for keeping formatting won't appear when I paste Excel content in IE.
However, after I change width or height of cells and copy it again, it appears. Though some styles are lost (e.g. text color, border color).

Tested in online demo.
Please find the recording here http://recordit.co/CEqFWpkJ0f

Windows 7
IE11

**Comment by AntiFreez** [comment]
I also found this issue. `Keep format` window has not appeared and cell resizing does not work in my case.

Excel (Microsoft Office 365 Business, Version 1706, Build 8229.2103):
![excel](https://user-images.githubusercontent.com/1442020/28761774-3823ccb6-75db-11e7-87d7-2182e9e6be4b.png)

IE11 (Version 11.713.10586.0, Update Version 11.0.38):
![ie11](https://user-images.githubusercontent.com/1442020/28761775-3824b1a8-75db-11e7-93ba-49458e45cc2f.png)

**Comment by stefanneculai** [comment]
@opalleq @AntiFreez could you please send us the documents you're pasting from? Thanks.

**Comment by opalleq** [comment]
Please find the file attached below

[test.xlsx](https://github.com/froala/wysiwyg-editor/files/1193200/test.xlsx)

**Comment by AntiFreez** [comment]
[Froala test.xlsx](https://github.com/froala/wysiwyg-editor/files/1193239/Froala.test.xlsx)

**Comment by SagarKarwa** [comment]
I'm facing an isue in froala(in IE browser), once you click on table button, table popup will open up, select few rows in it, again open same. Now click on other button which have popup like Insert Image , Insert Link, Insert Video. here popup disappears within fraction of seconds. This occurs frequently. Same is happening on 
https://www.froala.com/wysiwyg-editor?utm_expid=98676916-3.hPnlB_8ZTIKKKXBgYslKZA.0&utm_referrer=https%3A%2F%2Fwww.froala.com%2F

If you repeat same, then it continuosly open & disappears

**Comment by SagarKarwa** [comment]
I'm facing same issue, confirmation popup is not opening. It's pasting data withous rows,column css, Plain data.

**Comment by stefanneculai** [comment]
We just checked it, and unfortunately, there is not too much we can do about it. It looks in some cases Internet Explorer is doing some cleanup on the pasted HTML before we can intercept it in JS. That makes it not possible to detect if data is coming from Microsoft Excel.
