### ISSUE TITLE
can not upload image on IE10

### ISSUE THREAD

**Issue by nullest** [froala/wysiwyg-editor#2109]
##### Actual behavior.

It will returns "Image file type is invalid" when uploading image on IE10.

##### Steps to reproduce the problem.
1.goto [editor](https://www.froala.com/wysiwyg-editor)
2.click "Insert image"

##### OS.
Windows

##### Browser.
IE10

**Comment by stefanneculai** [comment]
@nullest could you please send us the file you're trying to upload?

**Comment by nullest** [comment]
@stefanneculai well, any images don't work on IE10 while woking on Chrome or Firefox.

**Comment by stefanneculai** [comment]
@nullest we couldn't reproduce this. Could you please record a video of it?

**Comment by stefanneculai** [comment]
It appears to work fine. If you could provide exact steps to reproduce it on our website, we would be happy to look into this.
