### ISSUE TITLE
Customize server response after upload

### ISSUE THREAD

**Issue by loicbisiere** [froala/wysiwyg-editor#2112]
Is it possible to get a hook function to customize the server response before Froala try to insert the ressource? With this feature, we could use any image hosting SAAS without creating a proxy server side to customize the server response.
Another solution: let us customize the attribut name (link by default).

Currently, I need to use a dirty trick 👎  by overriding JSON parse:
```
// patching `parseJSON` because Froala doesn't allow customization of response
// To update for 2.6.3+ to use JSON.parse instead of Jquery.parseJSON (https://www.froala.com/wysiwyg-editor/changelog#2.6.3)
var _parseJSON = jQuery.parseJSON; //var _parseJSON = JSON.parse;
jQuery.parseJSON = function(j) { // JSON.parse = function(j) {
  var response = _parseJSON(j);
  if (response.link === undefined && response.url !== undefined)
    response.link = response.url;
  return response;
};
```

**Comment by stefanneculai** [comment]
@loicbisiere sure, you could use the [image.uploaded event](https://www.froala.com/wysiwyg-editor/docs/events#image.uploaded), return false to cancel the upload chain and then insert the image using the `image.insert` method.

**Comment by momadthenomad** [comment]
Can you please provide an example?

**Comment by stefanneculai** [comment]
Sure: 

```js
function parseResponse(resp) {
  // return the url for image here.
}

$('#editor').on('froalaEditor.image.uploaded', function (e, editor, response) {
  var url = parseResponse(response);

  editor.image.insert(url);

  return false;
}).froalaEditor();

**Comment by shuhuaxie** [comment]
should use this
```
editor.image.insert(img_url, false, null, editor.image.get(), response);
```
or you will have two picture

**Comment by joey91133** [comment]
@stefanneculai 
I have a issue.
When I use paste from word or website, It have more than 1 images.
If  I use
`editor.image.insert(img_url, false, null, editor.image.get(), response);`
will cause image insert to wrong way, than cause other image can not insert.
Than console have warning message.
`The given range isn't in document. `

**Comment by lovelyelfpop** [comment]
@joey91133 I think, when insert an image, the `<img>` is cloned, and the cloned one is wrapped inside a `<div>`, and the original one is replaced by the cloned one.
It causes the the original image removed from document, by it still trigger `onload` event, `The given range isn't in document.` is thrown in one of the onload event handlers
