### ISSUE TITLE
Getting webspellchecker customscayt.js:33 Invalid CustomerID. Please contact support@webspellchecker.net

### ISSUE THREAD

**Issue by adamgins** [froala/wysiwyg-editor#2113]
Using Froala 2.6.4 with Meteor

##### Expected behavior.
No error

##### Actual behavior.
Seems to lock component, sometimes not allowing user to edit tables

##### Steps to reproduce the problem.
just running Froala -as per usual. 

##### OS.
OSX 10.12.5

##### Browser.
Chrome  Version 59.0.3071.115 (Official Build) (64-bit)

**Comment by stefanneculai** [comment]
@adamgins would it be possible to make a recording of it? Thanks.

**Comment by stefanneculai** [comment]
@adamgins that error is shown there because you haven't added a license key for SCAYT. Please follow the instructions from https://www.froala.com/wysiwyg-editor/examples/web-spell-checker.

**Comment by dave-buzzy** [comment]
@stefanneculai  - FYI, we're getting this error even though we never inited or called the spellchecker as per your doc at https://www.froala.com/wysiwyg-editor/examples/web-spell-checker. Additionally, we have the normal (non-plugin) spellcheck option set as `spellcheck: false`.

Does `scaytAutoload` default to true? As a hack, am gonna try setting `scaytAutoload: false,` to see if that fixes it.

**Comment by AshMcConnell** [comment]
You need to ensure you aren't loading the spell_checker.min.js otherwise it will still show the error even if you remove the spell checker from the menus
