### ISSUE TITLE
Styles does not match Word/Excel document

### ISSUE THREAD

**Issue by AntiFreez** [froala/wysiwyg-editor#2114]
##### Expected behavior.
Pasting content from Word/Excel should preserve styles.

##### Actual behavior.
Styles differ from original content and between different browsers.

Excel (Microsoft Office 365 Business, Version 1706, Build 8229.2103):
![excel](https://user-images.githubusercontent.com/1442020/28762410-7e0895c2-75e0-11e7-8048-2a10bfe72090.png)

IE11 (Version 11.713.10586.0, Update Version 11.0.38):
![ie11](https://user-images.githubusercontent.com/1442020/28762409-7e0768f0-75e0-11e7-8998-e2af45a5990b.png)

Chrome (Version 60.0.3112.78):
![chrome](https://user-images.githubusercontent.com/1442020/28762408-7e01dad4-75e0-11e7-970a-4f863aaa27fa.png)

##### OS.
Windows 10 Pro

**Comment by stefanneculai** [comment]
@AntiFreez could you please send us the document you're pasting from?

**Comment by AntiFreez** [comment]
[Froala test.xlsx](https://github.com/froala/wysiwyg-editor/files/1193196/Froala.test.xlsx)

**Comment by stefanneculai** [comment]
@AntiFreez last commit should fix it in Chrome. For IE, it is a duplicate of #2108.
