### ISSUE TITLE
Manually Trigger a Registered Command

### ISSUE THREAD

**Issue by andrewskaggs83** [froala/wysiwyg-editor#2117]
I want to manually trigger the imageManager command (i.e. show the Image Manager) under certain conditions.

I have a binding on the "froalaEditor.commands.after" inside which I want to open the image manager.

`if(cmd == 'insertImage') && /* some more conditions */) {
// Open the image manager
}`

I have tried triggering the handlers for click, mouseup, and mousedown on the #imageManager-1 button (as well as all of the elements below it).

I have also tried manually calling the command.

`$.FE.COMMANDS.imageManager.callback();`

Is there a way to do what I'm asking?

**Comment by stefanneculai** [comment]
@andrewskaggs83 see: https://www.froala.com/wysiwyg-editor/docs/methods#imageManager.show.

**Comment by sunjidshibly** [comment]
Is there a way to trigger a custom Register Command?

here is my custom register command
 $.FroalaEditor.RegisterCommand('guardFile', {....
......}

I want to call it's callback function from inside a jQuery function.
Is it possible?
