### ISSUE TITLE
Paste from word - colors

### ISSUE THREAD

**Issue by alexmoraru25** [froala/wysiwyg-editor#2119]
##### Expected behavior.
H1 html from Word paste should look like: 

`<h1 style="margin-top:12.0pt;margin-right:0in;margin-bottom:.0001pt;margin-left:0in;font-size:21px;"><span style="color: rgb(44, 130, 201);">Considered options</span></h1>`

##### Actual behavior.
When pasting from word, the color for an H1 is set inline, ex: 

`<h1 style="margin-top:12.0pt;margin-right:0in;margin-bottom:.0001pt;margin-left:0in;font-size:21px;font-family:&quot;Calibri Light&quot;,sans-serif;color:#2E74B5;">Considered options</h1>`

And if I save the content and restore it into the editor the color of the H1 is lost (stripped). 

##### Steps to reproduce the problem.
Copy & paste from a document which has a colored Heading 1 into the editor, save the html and after that insert it back in the editor.

##### OS.
Windows 10

##### Browser.
Chrome Version 59.0.3071.115

**Comment by stefanneculai** [comment]
@alexmoraru25 could you send us the document you're pasting from?

**Comment by alexmoraru25** [comment]
After further checks we discovered that the issue is from our side, the `&quot;` was interpreted as `"` and broke the styles. 

Sorry and thanks for the assist.
