### ISSUE TITLE
IE 11 clicking on wysiwig editor causes browser to crash.  Works in chrome.

### ISSUE THREAD

**Issue by JBurtonMCFA** [froala/wysiwyg-editor#2120]
##### Expected behavior.
(edit text)

##### Actual behavior.
(browser crash)

##### Steps to reproduce the problem.
xlixk on text area of editor)

##### OS.
(Windows 7)

##### Browser.
(IE11)

**Comment by stefanneculai** [comment]
@JBurtonMCFA are you able to reproduce this on our website?

**Comment by JBurtonMCFA** [comment]
Yes, it occurs on the website as well.

**Comment by stefanneculai** [comment]
Could you please make a recording?

**Comment by stefanneculai** [comment]
We are not able to reproduce it. Please make a recording and let us know additional details about the Windows build and IE specific version. Thanks.

**Comment by JBurtonMCFA** [comment]
IE 11

[cid:image001.png@01D30F7A.FE7CB9D0]

[cid:image002.png@01D30F7A.FE7CB9D0]

**Comment by jason-hobbs** [comment]
I have this same issue and this is the event viewer entry:
Faulting application name: iexplore.exe, version: 11.0.9600.18763, time stamp: 0x59683ec6
Faulting module name: MSCTF.dll, version: 6.1.7601.23572, time stamp: 0x57fd0632
Exception code: 0xc0000005
Fault offset: 0x0000000000007364
Faulting process id: 0x1130
Faulting application start time: 0x01d31216d2e54e27
Faulting application path: C:\Program Files\Internet Explorer\iexplore.exe
Faulting module path: C:\Windows\system32\MSCTF.dll
Report Id: 195676f9-7e0a-11e7-ba8b-005056a44669

**Comment by jason-hobbs** [comment]
[crash.zip](https://github.com/froala/wysiwyg-editor/files/1216838/crash.zip)
Here is a recording of the crash.

**Comment by stefanneculai** [comment]
@JBurtonMCFA @jason-hobbs we couldn't replicate this issue. However, we might have a couple of clues. Are you using a 32-bit installation of Windows? Which graphic card do you have?

**Comment by jason-hobbs** [comment]
On the machine with issues it is 64-bit and it is a virtual machine so the display driver is VMware SVGA 3D

**Comment by stefanneculai** [comment]
@jason-hobbs is it possible to somehow share the VM with us?

**Comment by jason-hobbs** [comment]
We will have to do something chrome remote and share the screen, I am available Saturday the 19th after 5:00 pm central.

**Comment by stefanneculai** [comment]
@jason-hobbs could you please reach us on https://www.froala.com/wysiwyg-editor/contact to see what we can do about this? Thanks.

**Comment by forum-is** [comment]
Any progress on this issue? At least one of our customers is also affected by this problem.

**Comment by stefanneculai** [comment]
@forum-is at this moment we don't have a way to replicate this issue. It looks like a user restriction set on the Windows machine, however, we couldn't point what that is.

**Comment by rturner2** [comment]
Can I re-open this... getting this issue with a corporate customers on multiple computers running windows 7 and IE 11 but where "User agent string" they can't select IE11. Only 10 max.


IE Text:
Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	iexplore.exe
  Application Version:	11.0.9600.19036
  Application Timestamp:	5b077f17
  Fault Module Name:	MSCTF.dll
  Fault Module Version:	6.1.7601.23915
  Fault Module Timestamp:	59b94ec5
  Exception Code:	c0000005
  Exception Offset:	0000000000007310
  OS Version:	6.1.7601.2.1.0.256.4
  Locale ID:	3081
  Additional Information 1:	84cb
  Additional Information 2:	84cb45c7bfe8407df2f08613a0aabb6f
  Additional Information 3:	5845
  Additional Information 4:	584598706c0fa819c89a1b68111f75ed

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409

If the online privacy statement is not available, please read our privacy statement offline:
  C:\WINDOWS\system32\en-US\erofflps.txt


<img width="1177" alt="ie11a" src="https://user-images.githubusercontent.com/3177469/46992580-7bd8d280-d156-11e8-99d4-0ee83d3fb142.png">
<img width="1176" alt="ie11-2a" src="https://user-images.githubusercontent.com/3177469/46992581-7bd8d280-d156-11e8-82e0-cb12c5e04c84.png">

**Comment by rturner2** [comment]
Using froala v2.6.0 - updating tonight.

**Comment by rturner2** [comment]
Upgrading to Version 2.8.5 fixed this issue.
