### ISSUE TITLE
Popup's hide automatically with a fraction of seconds(in IE Browser)

### ISSUE THREAD

**Issue by SagarKarwa** [froala/wysiwyg-editor#2121]
##### Expected behavior.
Popup should be open until mouse click is not done anywhere else

##### Actual behavior.
Popup disappears within fraction of seconds.

##### Steps to reproduce the problem.
I'm facing an isue in froala(in IE browser), once you click on table button, table popup will open up, select few rows in it, again open same. Now click on other button which have popup like Insert Image , Insert Link, Insert Video. here popup disappears within fraction of seconds. This occurs frequently. Same is happening on 
https://www.froala.com/wysiwyg-editor?utm_expid=98676916-3.hPnlB_8ZTIKKKXBgYslKZA.0&utm_referrer=https%3A%2F%2Fwww.froala.com%2F

If you repeat same, then it continuosly open & disappears. Works fine with Chrome

##### OS.
Windows 7

##### Browser.
Internet Explorer

**Comment by AntiFreez** [comment]
Hello @SagarKarwa! What version of IE do you use?
I have tested this issue and want to add some details.

##### Steps to reproduce:

1. фычфычфычфыч

1. "Insert Image" popup was not opened before. 
2. Click "insert table" button. Table popup is opened.
3. Click "insert image" button. "Insert table" popup is closed, then "Insert image" popup is opened and closed immediately.

**Comment by stefanneculai** [comment]
@SagarKarwa @AntiFreez could one of you guys please make a recording? Thank you.

**Comment by AntiFreez** [comment]
[Popup's hide automatically with a fraction of seconds(in IE Browser).zip](https://github.com/froala/wysiwyg-editor/files/1206954/Popup.s.hide.automatically.with.a.fraction.of.seconds.in.IE.Browser.zip)

**Comment by SagarKarwa** [comment]
Thanks Stefan, it's working fine with updated version :+1:
