### ISSUE TITLE
Behaviour based on CSS class / custom attribute

### ISSUE THREAD

**Issue by Smashr** [froala/wysiwyg-editor#2122]
I'm looking for further documentation on BLOCKS_TAGS as identified here but not having any luck.

[Issue 1554](https://github.com/froala/wysiwyg-editor/issues/1554)

We are looking for a way to assign behaviors to some elements, specifically to not let them split when the "return / enter" key is pressed.

If there was an option to assign behaviors to elements based on a specific attribute or css class value, that would be awesome. That way some 'div' tags can be assigned to behave like other different type of tags while other / normal 'div' tags behave normally like block elements.

Maybe consider this as a feature request. Not having some elements (for example: "div buttons" etc ) split when "return / enter" is pressed would be great.

Sometimes there are multiple nested 'div' tags that form a particular layout of an element. Splitting a div within that type of element breaks the layout / design of that element. Assigning a different behavior by attribute or CSS class to these elements and nested tags will solve a wide array of issues.

Have a great day. Thank you.

**Comment by stefanneculai** [comment]
@Smashr the best way would be to bind to the keydown event and stop the event propagation by using return false.

```js
$(selector).on('froalaEditor.initialized', function (e, editor) {
  editor.events.on('keydown', function () { ... }, true);
}).froalaEditor();

**Comment by Smashr** [comment]
I'll definitely try this, seems quite straightforward :) . Thank you Stefan !
