### ISSUE TITLE
htmlUntouched:true with htmlAllowedEmptyTags bug

### ISSUE THREAD

**Issue by boynet** [froala/wysiwyg-editor#2124]
this config:
```
$('textarea').froalaEditor({
wordAllowedStyleProps:['font-size', 'background', 'color', 'width', 'text-align', 'vertical-align', 'background-color'],
htmlUntouched: true,
});
```
I removed font-family from wordAllowedStyleProps.

1. create a table in word with a few empty rows like:
![1](https://user-images.githubusercontent.com/1615629/29024143-4ad7105e-7b79-11e7-835e-e1129acc016e.jpg)

2. copy and paste in into the editor
3. click on the table in the editor
4. you will get error in console like and the table rows will disappear:
```
VM107 froala_editor.pkgd.min.js:20 Uncaught TypeError: Cannot read property 'length' of undefined
    at J (VM107 froala_editor.pkgd.min.js:20)
    at O (VM107 froala_editor.pkgd.min.js:20)
    at Q (VM107 froala_editor.pkgd.min.js:20)
    at d (VM107 froala_editor.pkgd.min.js:19)
    at V (VM107 froala_editor.pkgd.min.js:20)
    at dispatch (VM106 jquery-2.2.4.js:4737)
    at elemData.handle (VM106 jquery-2.2.4.js:4549)
```

here is a link:
[https://jsfiddle.net/f87vde0c/2/](https://jsfiddle.net/f87vde0c/2/)

**Comment by stefanneculai** [comment]
@boynet could you please send the document from which you're pasting?

**Comment by boynet** [comment]
[froala.docx](https://github.com/froala/wysiwyg-editor/files/1204960/froala.docx)

Hi try both options (clean and keep) and try clicking on empty rows after pasting
