### ISSUE TITLE
Insert Link Tooltip with Anchor Text over Multiple Lines

### ISSUE THREAD

**Issue by chrisdeeming** [froala/wysiwyg-editor#2126]
Received a report from one of our users:

>When inserting link over an anchor text that has a few words at the end of the line while remaining words are soft-wrapped into the next line in the RTE, the anchor tooltip (that appears after inserting the link) is aligned in the middle of the editor where there is no part of the anchor text present. I think I understand why it does the way it does, because it perhaps calculates the farthest right and left edges of the anchored text and calculated the midpoint to position the tooltip. It is not really a bug, but visually not very elegant.

>A couple potential approaches would be to position tooltip right under the the cursor position within the anchor text or to actually find the mid pint of the anchor text from the start of the anchor text to the end (but calculating the real mid position this way with line breaks could be tricky, so character count can be another possibility). It is a Froala issue though and I am not sure if the effort is worth.

>I was able to create a funny situation on Froala Editor's home page where the tooltip belongs to the anchor text "framework plugins", but due to the position calculation approach used, it is aligned to another anchor text "tons of examples" (I had to add little extra text "[foo]" there to make the alignment situation worse, but this could happen in real cases very easily).

>OS: Latest version of elementary OS Loki (based on Ubuntu 16.04 LTS)
Browser: Google Chrome version 60.0.3112.78 (Official Build) (64-bit)

![image](https://user-images.githubusercontent.com/2158514/29050927-e51613ba-7bd6-11e7-94f2-203a7f3eaca3.png)

**Comment by ibnesayeed** [comment]
I was able to replicate it on Google Chrome on Android as well (by strategically adding some extra text in the home page's example to make the anchor text break in two lines).

**Comment by stefanneculai** [comment]
@chrisdeeming thanks for the report on this one, unfortunately, there is not too much we could do about it because we cannot find out if the link goes to the other line or not. I am closing this as a `wontfix` for now.

**Comment by ibnesayeed** [comment]
@stefanneculai, what are some practical issues in not **trying to** position it in the middle of the anchor text, but below the cursor position? I can think of one issue, when the user is using LEFT/RIGHT keys to move the cursor, the tooltip will follow, but this can be strategically stopped from happening unless the cursor moves to the next line.

There is another possibility which seems more practical and elegant that the tooltip should be positioned in the middle of the only part of the anchor text that is in the line where the cursor is positioned (this means tooltip wont follow the cursor as it moves left and right). This will be great from usability perspective, even if the anchor text wraps in several lines. With this approach in place, the example in the screenshot above would behave in a way that the tooltip will be positioned in the middle of the text "framework" while the cursor is still somewhere in that word, but it will jump down to the middle of the word "plugins" when the cursor moves to the next line while still within the anchor text.

To calculate the mid point of the part of the anchor text in the current line, we will need X and Y coordinates of the start of the anchor text, end of the anchor text, editable area's far left and right X coordinates, and the current cursor position. I can elaborate on this further, if such information is available and developers are willing to try this approach.

**Comment by stefanneculai** [comment]
@ibnesayeed the implications of making such changes are quite significant. It is the way we designed the popups for links to appear in V1. However, here are lots of cases when users are using `A` tags for buttons, and they have paddings or custom content inside them which might create some spacing around the text. 

We couldn't find a way to satisfy both cases, so when we made V2, we had to go with one of the behaviors. Based on the reports we had about these 2, more users face the padding problem than the ones who run into a link split into two lines.

**Comment by ibnesayeed** [comment]
Thanks @stefanneculai for insights, that makes sense when considering the kind of usage other customers might have. It is not such a big deal, but in future we might be able to come up with a more elegant solution that handles many of the use cases.

**Comment by stefanneculai** [comment]
Thanks for the feedback. We're open to any suggestions.
