### ISSUE TITLE
Inserting &nbsp; when copy pasting from other editor in FF

### ISSUE THREAD

**Issue by webjazz** [froala/wysiwyg-editor#2127]
##### Expected behavior.
1 to 1 copy pasting from other editor should result in identical source code.

##### Actual behavior.
When copy/pasting in latest FF/Windows 7 inserts &nbsp; in each line at various points.

##### Steps to reproduce the problem.
Copy from one froala-editor and paste into another

##### OS.
Windows 7

##### Browser.
FireFox 54.0.1 (32-Bit)

<img width="773" alt="bildschirmfoto 2017-08-08 um 11 23 30" src="https://user-images.githubusercontent.com/6874672/29066011-42b6b900-7c2e-11e7-9a4b-92e9191cfd3f.png">
<img width="772" alt="bildschirmfoto 2017-08-08 um 11 23 35" src="https://user-images.githubusercontent.com/6874672/29066012-42dcfe12-7c2e-11e7-91df-5cb2f0c75afb.png">
<img width="764" alt="bildschirmfoto 2017-08-08 um 11 23 41" src="https://user-images.githubusercontent.com/6874672/29066013-42dd1f5a-7c2e-11e7-8b0b-e41ede190dd1.png">

**Comment by stefanneculai** [comment]
@webjazz are you able to reproduce this on our website? If so, could you please detail a bit more? Thank you.

**Comment by webjazz** [comment]
Hi,

yes I can reproduce the same behaviour when copying and pasteing the example content.
![bildschirmfoto 2017-08-10 um 14 00 36](https://user-images.githubusercontent.com/6874672/29169454-6d20bd4c-7dd4-11e7-9f84-090ad83e0a94.png)

**Comment by webjazz** [comment]
I am using FireFox 54.0.1 on Windows 7
