### ISSUE TITLE
Custom breakpoints for toolbar buttons

### ISSUE THREAD

**Issue by maxthet604** [froala/wysiwyg-editor#2128]
I think there should be an option to declare custom breakpoints beside the `toolbarButtonsMD`, `toolbarButtonsSM` and `toolbarButtonsXS`. This feature will be really helpful if added to Froala.

**Comment by stefanneculai** [comment]
There actually is one already. Just add the following code after including the editor CSS (it is in SCSS):

```sass
@screen-sm: 768px;
@screen-md: 992px;
@screen-lg: 1200px;

.fr-visibility-helper {
  @media (min-width: @screen-sm) {
    margin-left: 1px !important;
  }

  @media (min-width: @screen-md) {
    margin-left: 2px !important;
  }

  @media (min-width: @screen-lg) {
    margin-left: 3px !important;
  }
}
```

**Comment by ataraFrieman** [comment]
> There actually is one already. Just add the following code after including the editor CSS (it is in SCSS):
> 
> ```sass
> @screen-sm: 768px;
> @screen-md: 992px;
> @screen-lg: 1200px;
> 
> .fr-visibility-helper {
>   @media (min-width: @screen-sm) {
>     margin-left: 1px !important;
>   }
> 
>   @media (min-width: @screen-md) {
>     margin-left: 2px !important;
>   }
> 
>   @media (min-width: @screen-lg) {
>     margin-left: 3px !important;
>   }
> }
> ```

But how can I define custom break points to decide which toolbar layout to use?
for example:
toolbarButtonsMD appers for  devices ≥ 700px and not from 992px
