### ISSUE TITLE
Error when deleting (del key) a horizontal line

### ISSUE THREAD

**Issue by GAntoine** [froala/wysiwyg-editor#2134]
##### Expected behavior.
When editing text, placing cursor before a horizontal line and pressing the delete key (DEL) deletes the line.

##### Actual behavior.
Throws an error: `Uncaught TypeError: Cannot read property 'tagName' of undefined`

##### Steps to reproduce the problem.
- Enable to horizontal rule in the toolbar
- Add a horizontal rule to the text
- Place cursor before the horizontal rule and press DELETE
  - Editor will crash with the error above

##### OS.
`macOS Sierra 10.12.6`

##### Browser.
`Opera 46.0.2597.57`
Also seen on `Google Chrome Version 60.0.3112.90`

I've managed to trace what's causing the issue, so let me know if you'd like me to point to the specific piece of code.

**Comment by stefanneculai** [comment]
@GAntoine are you using the latest editor version?

**Comment by GAntoine** [comment]
No, I'm on version `2.5.1`. I've looked through the changelog but couldn't find an entry for a fix to this issue. Should I try upgrading to the latest version anyways?

**Comment by stefanneculai** [comment]
Yes.
