### ISSUE TITLE
The given range isn't in document.

### ISSUE THREAD

**Issue by NiravMungara** [froala/wysiwyg-editor#2135]
##### Expected behavior.
Image upload.

##### Actual behavior.
I am using editor in bootstrap model.

##### Steps to reproduce the problem.
when I upload image using editor (button "insertImage") and upload process is started then after I close bootstrap model I get this error "The given range isn't in document." in console.
I got error in line/function "...... function ta(){if(xa){b.selection.clear();var a=b.doc.createRange();a.selectNode(xa.get(0));b.selection.get()**.addRange(a)}}function ua(){xa?(.......**".
error is highlighted.

##### Browser.
Chrome Version 60.0.3112.90 (64-bit)

**Comment by stefanneculai** [comment]
It is because when the image has to be inserted, the editor is no longer visible. The best solution would be to disable closing the modal while there is an image upload.

**Comment by lovelyelfpop** [comment]
I think, when insert an image, the `<img>` is cloned, and the cloned one is wrapped inside a `<div>`, and the original one is replaced by the cloned one.
It causes the the original image removed from document, by it still trigger `onload` event, `The given range isn't in document.` is thrown in one of the onload event handlers
