### ISSUE TITLE
Drag Image from desktop & drop on froala editor in  (IE - 11 Browser), instead of uploading it opens dropped image in same tab.

### ISSUE THREAD

**Issue by SagarKarwa** [froala/wysiwyg-editor#2136]
##### Expected behavior.
Drag Image from desktop & drop on froala editor, it should start uploading(This works fine with chrome)

##### Actual behavior.
Drag Image from desktop & drop on froala editor, instead of uploading it opens dropped image in same tab.
On https://www.froala.com/wysiwyg-editor?utm_expid=98676916-3.hPnlB_8ZTIKKKXBgYslKZA.0&utm_referrer=https%3A%2F%2Fwww.froala.com%2F
, it dont even do any action on dropping image
##### Steps to reproduce the problem.
1 - Drag Image from desktop.
2 - Drop on froala editor

##### OS.
Windows

##### Browser.
IE - 11

**Comment by stefanneculai** [comment]
@SagarKarwa what windows version are you using?

**Comment by SagarKarwa** [comment]
Windows 7

**Comment by stefanneculai** [comment]
@SagarKarwa could you please make a recording? Thank you.

**Comment by stefanneculai** [comment]
We're closing this due to lack of response. Would be happy to look over it if we'd get more details.
