### ISSUE TITLE
Open image uploader directly

### ISSUE THREAD

**Issue by loicbisiere** [froala/wysiwyg-editor#2138]
Hi, I'm trying to open the image uploader (popup open by the imageUpload button) directly without the step "click on imageReplace button":

![screencast 2017-08-10 11-27-16](https://user-images.githubusercontent.com/1148072/29178636-247408ec-7dc0-11e7-93d8-6da744fdd46e.gif)

And as extra question, I would like the to be centered over the image:

![2ps - contacts 2017-08-10 11-30-06](https://user-images.githubusercontent.com/1148072/29178689-50111922-7dc0-11e7-8305-2a61b4ec1dfe.jpg)

Thank you.

**Comment by stefanneculai** [comment]
@loicbisiere for tech support, please reach us via our website. Thank you.
