### ISSUE TITLE
There is a problem with the paragraph_format plugin operation.

### ISSUE THREAD

**Issue by largeden** [froala/wysiwyg-editor#2139]
##### Steps to reproduce the problem.
![blocks](https://user-images.githubusercontent.com/5575931/29210523-f251f738-7ece-11e7-86ac-534e874380cc.gif)

I have found that this problem only appears in certain locations.
The cause of the problem was in `editor.selection.blocks()`

```javascript
//froala_editor.js

    /**
     * Search for the current selected blocks.
     */
    function blocks () {
//...
      // Remove blocks that we don't need.
      for (i = blks.length - 1; i > 0; i--) {
        // Nodes that contain another node. Don't do it for LI, but remove them if there is a single child and has format.
        console.log(blks[i].children);
        if ($(blks[i]).find(blks).length && (blks[i].tagName != 'LI' || (blks[i].children.length == 1 && blks.indexOf(blks[i].children[0]) >= 0))) {
	        blks.splice(i, 1);
       }
      }
```
If there is `ul` `ol` in the selected element, `blks[i].children.length` becomes 2.

I think I should change it with the code below.
Could you check if there is a problem overall?

```javascript
blks[i].children.length > 0
```

**Comment by stefanneculai** [comment]
👍
