### ISSUE TITLE
Pre tag with code tag will lose blank space

### ISSUE THREAD

**Issue by jkhaoqi110** [froala/wysiwyg-editor#2141]
##### Expected behavior.
![5939d5be-f710-4da1-8261-35d5cc02ab0e](https://user-images.githubusercontent.com/7346148/29242209-6a524c3c-7fbb-11e7-8a6a-c7a89779cd72.png)

##### Actual behavior.
![f4a6a5cb-5d85-45cc-a3a7-908274b3c1a0](https://user-images.githubusercontent.com/7346148/29242213-740c6f46-7fbb-11e7-8430-5b820d9b5be6.png)

##### Steps to reproduce the problem.
Put code tag after pre tag will product this problem

##### OS.
macOS Sierra 10.12.6

##### Browser.
Chrome 60.0.3112.90

**Comment by stefanneculai** [comment]
@jkhaoqi110 it appears this is not happening on the latest version. Are you able to reproduce it on our website?

**Comment by stefanneculai** [comment]
I am closing this as it appears to work fine with the latest editor version. Please let us know if you can reproduce it on our website.

**Comment by jkhaoqi110** [comment]
@stefanneculai 
demo here: https://codepen.io/anon/pen/GvyxJZ
two or more blanks become one blank
