### ISSUE TITLE
"undo" button in toolbar stays disabled after undo.saveStep

### ISSUE THREAD

**Issue by Smashr** [froala/wysiwyg-editor#2142]
When a change is done to the content externally and undo.saveStep is called right after initializing Froala, it saves the state in the stack but does not enable the 'undo' button in the toolbar.

##### Expected behavior.
Automatically enable the 'undo' button on undo.saveStep if the button is disabled.

##### Actual behavior.
Undo button stays disabled until some other action is performed in the editor, like bolding some text, and then undo works as expected. 

This prevents the previous state saved with undo.saveStep to be reached ... until the undo button is enabled by performing another action in the editor.

##### Steps to reproduce the problem.
trigger undo.saveStep after appending a div to the content right after init.

##### OS.
Win 10

##### Browser.
Chrome

**Comment by stefanneculai** [comment]
Could you please make a jsFiddle for it?

**Comment by Smashr** [comment]
In the pen's froala editor, you'll see the undo button is disabled. Then perform an action in the editor like typing a letter. The undo button becomes active, click it once and it removes the letter you just typed, and click it again and it goes to the previous state without the "Hello world" text.

There seems to be no way to undo to the original state without clicking in the editor and performing an action.

**Comment by largeden** [comment]
@Smashr 

https://codepen.io/romanesque/pen/mMBNej

Is this what you working thinking?

**Comment by stefanneculai** [comment]
@Smashr the way @largeden suggested is the right way of doing this. A step should be stored before changing the HTML and another one just after that.

**Comment by Smashr** [comment]
Thanks guys @largeden @stefanneculai  ... Looks good, I can't believe I struggled with that :). Appreciate all the help.
