### ISSUE TITLE
When adding images failed, click the failed img, not the 'ok' button, the last img that be deleted will appear

### ISSUE THREAD

**Issue by huhu213** [froala/wysiwyg-editor#2145]
##### Expected behavior.
(Describe expected behaviour here)
Adding images failed and click the images, the failed images should be removed.
##### Actual behavior.
(Describe actual behaviour here)
Adding images failed and click the images, the images being deleted appears.
##### Steps to reproduce the problem.
(Describe the steps to reproduce the problem here)
1. Adding two images, and delete the second one
2. Adding a image and failed
3. Click the failed image self, not the 'ok' button, the second picture being deleted will appear.
##### OS.
(OS name and version here)
windows7
##### Browser.
(Browser name an version here)
Chrome

**Comment by docikaci** [comment]
![gif3](https://user-images.githubusercontent.com/7788102/29452651-ad0248c0-8439-11e7-85ce-afa41d621cd2.gif)

**Comment by docikaci** [comment]
选第一张图片，然后选第二张图片，删除第二张图，再一次选一张图片（上传失败），点击上传失败的图片，会显示刚删除的图片，bug or 正常？

Choose the first picture, then choose the second picture, delete the second picture, and then select a picture (upload failed), click upload failed picture, will show just deleted pictures, bug or normal?

**Comment by stefanneculai** [comment]
@huhu213 @docikaci which is the error message you get in console when listening to the `image.error` event?

**Comment by stefanneculai** [comment]
Closing this issue due to lack of response. Would be happy to check it if you could provide the requested details. Thank you.
