### ISSUE TITLE
Image / Advanced Edit menu option disappears

### ISSUE THREAD

**Issue by kelfink** [froala/wysiwyg-editor#2147]
##### Expected behavior.
I updated to the latest froala editor in my development environment, to try fixing an image save problem (worked!). But once someone else tried it, the advanced image edit menu actually disappeared.  Is this part of the new third-party folder of plugins?  I can't repeat the behavior except to say it might be because at one point I had merged the code and had the aviary plugin both in the third-party and in the normal plugins folder.   DO we *need* to get the aviary adobe license key to use this advanced edit from now on ?

##### Actual behavior.
Advanced editor content menu on images went away.

##### Steps to reproduce the problem.
update to froala 2.3

##### OS.
OSX

##### Browser.
safari

**Comment by stefanneculai** [comment]
In the latest version, the Aviary plugin is no longer included in the pkgd file and it should be included separately.
