### ISSUE TITLE
Image Resize Behaves Inconsistently Inside FancyBox IFrame

### ISSUE THREAD

**Issue by andrewskaggs83** [froala/wysiwyg-editor#2148]
##### Expected behavior.
Images would resize fluidly.

##### Actual behavior.
When an editor is intialized within a FancyBox modal, dragging the corners of an image acts erratically (when you begin to drag, the image will jump to a smaller or larger size).

##### Steps to reproduce the problem.

1. Create an HTML page with a basic editor instance.
2. Insert an image and resize.
3. Note that the image resizes fluidly as expected.

1. Create another HTML page which opens the first page in a FancyBox modal.
2. Insert an image and resize.
3. Note that the image changes shape erratically when you begin to drag.

##### Example HTML files.
[modalResizeExample.zip](https://github.com/froala/wysiwyg-editor/files/1225645/modalResizeExample.zip)

##### OS.
MacOS 10.12.5
Windows 10

##### Browser.
Chrome 60.0.3112.101
Safari 10.1.1

##### Web Servers.
nginx 1.4.6
IIS 7.5

##### Additional Notes.
I do not have this problem when I open these files via "file://" url (by double-clicking them in the file system).  This only presents itself when the files are served through a web server.

**Comment by andrewskaggs83** [comment]
Thanks for the quick turnaround, @stefanneculai !

When can we expect this fix to be included in a release?

**Comment by stefanneculai** [comment]
It will be included in the next release 2.6.5.
