### ISSUE TITLE
Deleting pasted text in Chrome behaves weird around spaces

### ISSUE THREAD

**Issue by xandervdm** [froala/wysiwyg-editor#2151]
##### Expected behavior.
When enabling style to be pasted into the editor and the HTML being pasted into the editor contains SPAN tags, the cursor behaves weird in that it skips spaces between words when back spacing from the end of say a pasted paragraph. 

That is, when you reach the first letter of the last word after backspacing, the cursor will jump over the preceding space when deleting that first letter. You then have to press the backspace twice to delete the last character of the (previously) second last word and so on.

##### Actual behavior.
- Paste HTML that contains SPAN tags
- Place cursor at end of pasted text
- press backspace and notice that the cursor jumps over the spaces between words when those are embedded inside span tags

If you then add the pasteDeniedTags: ['span'], option it will work correctly, but you lose the ability to paste color background for example.

##### Steps to reproduce the problem.
- Set options as follows:
  -- pasteAllowedStyleProps: ['font-family', 'font-size', 'color', 'background-color',
  --                                           'font-style', 'font-weight', 'text-decoration'],
  -- pasteDeniedAttrs: ['class', 'id'],

##### OS.
- Windows 7 & 10

##### Browser.
- Chrome (works fine on IE11)

**Comment by stefanneculai** [comment]
@xandervdm please send us a link to the text you're pasting into the editor.

**Comment by xandervdm** [comment]
@stefanneculai if you paste the HTML inside the <i> tag box (6th box from top) from the top on this page for example (starting with "Color text and another color..."), you can see the problem: https://www.quackit.com/html/examples/html_text_examples.cfm

Also, a more simple test to reproduce the issue is if you copy and paste the italic text from the <b> tag box (5th box from top) in above link into the Froala demo on your home page then you can also see the problem (cursor jumping over space between words) when using the backspace to delete it again.

**Comment by xandervdm** [comment]
@stefanneculai do you have an ETA for when a fix or perhaps a workaround for this can be expected?

**Comment by stefanneculai** [comment]
@xandervdm we just tried to reproduce it without success. Could you please make a recording?

**Comment by xandervdm** [comment]
@stefanneculai here is video showing the problem in the latest version of Chrome. HTML in the video is copied from https://www.w3schools.com/html/tryit.asp?filename=tryhtml_formatting_b

Note what happens to the cursor as you backspace over the first character of any word and it skips the preceding space. With sound you can hear the click of the backspace key.

**Comment by xandervdm** [comment]
@stefanneculai any update on this issue and a possible ETA for resolution? We have a large customer chasing us for a fix. Thanks

**Comment by stefanneculai** [comment]
@xandervdm we don't have an ETA for it, however we were able to reproduce it now and there should be a fix shortly.
