### ISSUE TITLE
How to display custom error message for image upload / replace with node js (my own API)

### ISSUE THREAD

**Issue by kurdin** [froala/wysiwyg-editor#2152]
I am using my own API for image uploads (nodejs) and I want to users know if there are any errors on uploads. 

How can I send back error code with message to display on image upload/replace popup? 
I use ` return res.status(422).send(JSON.stringify(new Error('JPG, JPEG or PNG only')));` and it's kinda working but only for uploads (not for image replace) I can see message in popup 'Something went wrong. Please try again.'  Can I display my own message in the popup? 

Thanks for great wysiwyg editor!

**Comment by stefanneculai** [comment]
https://github.com/froala/wysiwyg-editor/issues/1358#issuecomment-228046725
