### ISSUE TITLE
How to set image width 1000px when upload and insert image

### ISSUE THREAD

**Issue by dungphanxuan** [froala/wysiwyg-editor#2154]
I try to upload image with size large than 1000px, so editor set image with 300px, so how can i auto set with 1000px when insert image.
![image](https://user-images.githubusercontent.com/10725732/29455287-cf706f12-843a-11e7-9f34-955c4794eeda.png)

**Comment by stefanneculai** [comment]
See: https://www.froala.com/wysiwyg-editor/docs/options#imageDefaultWidth.
