### ISSUE TITLE
Find image data in clipboard of multiple items

### ISSUE THREAD

**Issue by jtrain** [froala/wysiwyg-editor#2155]
I have included a patch at the end..

##### Expected behavior.
Froala to upload the image data after copy and paste

##### Actual behavior.
A HTML version with a src hotlinking to the original image is inserted

##### Steps to reproduce the problem.
1. Visit an image e.g. http://www.britainexpress.com/zen/albums/potd/Cree-Woods-1333.jpg
2. right click and select "copy image" < firefox terminology
3. Visit froala editor https://www.froala.com/wysiwyg-editor
4. Paste (CMD + V)
5. Inspect source, it is a html representation with hotlink to the original

```
<img src="http://www.britainexpress.com/zen/albums/potd/Cree-Woods-1333.jpg" alt="http://www.britainexpress.com/zen/albums/potd/Cree-Woods-1333.jpg" class="fr-fir fr-dib fr-draggable" height="671" width="1073">
```

##### OS.
macOS Sierra 10.12

##### Browser.
Firefox 54

##### Discussion and Patch
The problem is in the plugin `image.js` in the `_clipboardPaste` function. It is currently hardcoded to check `items[0]`. While the PNG data is kept in `items[1]` and a HTML hotlinked version is in `items[0]`. 

So, instead I developed this patch which seems to get the desired result:

```
@@ -2206,9 +2206,10 @@
     }

     function _clipboardPaste (e) {
-      if (e && e.clipboardData) {
-        if (e.clipboardData.items && e.clipboardData.items[0]) {
-          var file = e.clipboardData.items[0].getAsFile();
+      if (e && e.clipboardData && e.clipboardData.items) {
+
+        for (var i=0; i < e.clipboardData.items.length; i++) {
+          var file = e.clipboardData.items[i].getAsFile();

           if (file) {
             var reader = new FileReader();
```

I am using a forloop to iterate and test each of the items to see if they are a file.

**Comment by stefanneculai** [comment]
@jtrain Nice catch. Thanks for the suggestion.
