### ISSUE TITLE
Ability to trigger registered command manually 

### ISSUE THREAD

**Issue by SidKH** [froala/wysiwyg-editor#2158]
Hey guys, is there a way to manually trigger custom command registered with `$.FroalaEditor.RegisterCommand` ?
  
Currently `$('#editor').froalaEditor('commands.myCommand')` doesn't seem to work even after you register `myCommand`, and throws `Method commands.myCommand does not exist in Froala editor`.

[Codepen Example](https://codepen.io/Sid_KH/pen/QMxQLx).

Thanks.

**Comment by stefanneculai** [comment]
Here is what should do for that:
```js
var editor = $('#editor').data('froala.editor');
$.FE.COMMANDS.yourCommand.call(editor);
```

**Comment by SidKH** [comment]
Thanks @stefanneculai !
  
But `$.FE.COMMANDS.yourCommand` would be an object with a set of settings for command including `callback` function.
  
So `$.FE.COMMANDS.yourCommand.callback.call(editor)` will work.
Although `yourCommand` settings like `undo`, `focus`, etc.. would be ignored.
Would be great if you implement ability to trigger commands directly with all set of options as it triggered natively when toolbar button clicked.
  
Anyway, thanks for the solution! Will use it for now.

**Comment by stefanneculai** [comment]
@SidKH That is right, I updated the comment. 

Another way to call a command would be by the following code. This should do the undo/focus things automatically: `editor.commands.exec('yourCommand');`.

**Comment by SidKH** [comment]
@stefanneculai Thanks! That's exactly what I need.

**Comment by nirvparekh** [comment]
> @SidKH That is right, I updated the comment.
> 
> Another way to call a command would be by the following code. This should do the undo/focus things automatically: `editor.commands.exec('yourCommand');`.

But nowhere documented. How can we pass parameter with this command?
