### ISSUE TITLE
Quick Insert plugin file is minified

### ISSUE THREAD

**Issue by Artenes** [froala/wysiwyg-editor#2159]
I'd like to implement a custom quick insert plugin to Froala to use in my project. For this I intend to use as a base the current Quick Insert plugin that comes with Froala. But the plugin file is minified and is really hard to understand anything in this kind of file. 

So is there any possibility that I can have access to the source of at least this plugin? I am planning in buying a Froala license but first I need to understand how can I implement what I need in my project.

**Comment by stefanneculai** [comment]
@Artenes the Professional and OEM licenses come with the source code unminified.
