### ISSUE TITLE
Froala editor strips out p element from li elements

### ISSUE THREAD

**Issue by ca-dsgn** [froala/wysiwyg-editor#2160]
##### Expected behavior.
When entering something like this via html to the editor:

```
<ul>
<li><p>Test</p></li>
</ul>
```

##### Actual behavior.
It becomes this:
```
<ul>
<li>Test</li>
</ul>
```

W3C describes content model of a li item as Flow Content:
https://www.w3.org/TR/html5/grouping-content.html#the-li-element

Flow content contains the p element:
https://www.w3.org/TR/html5/dom.html#flow-content-1

##### OS.
macOS latest Version

##### Browser.
Chrome latest Version

##### Possible solution
It would be great to get control over this via htmlAllowedTags as a 'li p'.

**Comment by george-norris-salesforce** [comment]
I've noticed similar behavior. This is currently breaking alot of our content.
Also a links `href` are being stripped when they are in a list.
