### ISSUE TITLE
URL Detection interfering with editing sentence

### ISSUE THREAD

**Issue by irphilli** [froala/wysiwyg-editor#2161]
##### Expected behavior.
Period added to text in editor

##### Actual behavior.
Link created at end of sentence 

##### Steps to reproduce the problem.

- Paste the following text into editor:
(See important note after this Help text — spoiler alertbatchconverter.exe is wrong — batchconverter.com
- Anywhere along the text, try to add a period

##### OS.
Mac OS

##### Browser.
Chrome Latest

##### Froala Version
Happening on https://www.froala.com/wysiwyg-editor

**Comment by irphilli** [comment]
Thanks for the fix!

One thing that I did notice... if you have part of a sentence that you've unlinked and then try to put a period anywhere within the sentence, it'll jump right back to the end again. Suggestion: only do URL detection when updating the part of the sentence that matches a URL. (Should that have a separate issue?)

**Comment by stefanneculai** [comment]
@irphilli could you please make a recording?
