### ISSUE TITLE
The text doesn't wrap around an inline left-aligned image. 

### ISSUE THREAD

**Issue by skk2142** [froala/wysiwyg-editor#2162]
[bug-video](https://youtu.be/6_ZUBKcwTT8)
##### Expected behavior.
With left alignment and inline-block display of image, the text should wrap around the image. However, it sometimes does not and hence is a bad UX. 

##### Actual behavior.
The text doesn't wrap around. 

##### Steps to reproduce the problem.
Shown it in the video. Just insert an image, align left, change display to inline. Then start typing next to the image. 

##### OS.
Mac 10.12.5

##### Browser.
Chrome 60.0.3112

**Comment by stefanneculai** [comment]
That is happening because the image is below the text. To have text on its right, you should move the picture up by dragging it in front of the text you want to go to the right.
