### ISSUE TITLE
HTML being displayed as a string, not rendered HTML

### ISSUE THREAD

**Issue by OlliePython** [froala/wysiwyg-editor#2163]
I am using Node.js as a backend, and when I submit HTML in the wysiwyg editor, it gets displayed in tags, so typing "Hello" will be displayed as "<.p.>Hello<./p.>" (with the tags)

**Comment by stefanneculai** [comment]
Most likely when you display the content it is not being marked as safe HTML

**Comment by OlliePython** [comment]
How do i render it


________________________________

**Comment by AllyBerry** [comment]
@stefanneculai How do you render this please?
