### ISSUE TITLE
Table Resize cursor not appearing for the froala Editor on a bootstrap Modal

### ISSUE THREAD

**Issue by ShanmugaPriyanV** [froala/wysiwyg-editor#2164]
##### Expected behavior.
Table resize cursor <-||-> should appear on the table border to resize the table

##### Actual behavior.
Cannot see the table resizer

##### Steps to reproduce the problem.
Insert the Editor in an bootstrap Modal.
create a table.
hover the mouse to the table border.

##### OS.
Windows 7

##### Browser.
Chrome Version 60.0.3112.101 (Official Build) (32-bit)

**Comment by stefanneculai** [comment]
Please set a zIndex option in the editor higher than the Bootstrap Modal: https://www.froala.com/wysiwyg-editor/docs/options#zIndex

**Comment by ShanmugaPriyanV** [comment]
I have set the zIndex and popups appear correctly but the table resizer is not working.

**Comment by stefanneculai** [comment]
@ShanmugaPriyanV could you please make a jsFiddle for it?

**Comment by AntiFreez** [comment]
Hello @stefanneculai,
I have faced the same issue. Here is an example for AngularJS Material dialogs: http://jsfiddle.net/xdm4sjpb/8.
Also, insert column/row button does not appear.

Probably it is another question, but table editing popup appears under the modal backdrop. I found solution, but want to be sure that it is ok to override Froala styles.

**Comment by stefanneculai** [comment]
@AntiFreez to show the table popup editing correctly, you should set the zIndex option for the editor: 
```js
angular.module('froala', [])
.value('froalaConfig', {
	zIndex: 3000,
})
```

Also, inside modals, it is best to set the `scrollableContainer` option as well, so that all controls are being placed relative to the modal and not the body of the page.

**Comment by AntiFreez** [comment]
@stefanneculai thank you! I have updated demo http://jsfiddle.net/xdm4sjpb/10. 
Popups now are working fine. 

Resize indicator still does not appear. 
Also you can see that insert column/row button appears in the wrong place.

**Comment by stefanneculai** [comment]
@AntiFreez we did an additional check and it appears that the problem is actually coming from the transform CSS property of the modal. It should be overridden by setting it to none.

<img width="816" alt="screen shot 2017-09-04 at 11 30 57" src="https://user-images.githubusercontent.com/637004/30018208-acb4de04-9164-11e7-8204-88de7691c57f.png">

**Comment by ShanmugaPriyanV** [comment]
@steffanneculai i tried in seperate standalone and the table resizer was working but in a wierd way..Im using Jhipster app generator somehow the table resizer is totally not working in our Jhipster app.. @stefanneculai is there any way i could get non minified version of plugins js.

**Comment by stefanneculai** [comment]
@ShanmugaPriyanV the unminified JS is available under the Professional/OEM licenses for download inside your account.
