### ISSUE TITLE
html.insert does not updates textarea

### ISSUE THREAD

**Issue by LinGG** [froala/wysiwyg-editor#2165]
##### Expected behavior.
When you paste some text via API and then hit save button - new changes are not posted.

##### Actual behavior.
You have to click editor to toggle some "update" call for it.

##### Steps to reproduce the problem.
Using latest version of editor without any settings passed in.

##### OS.
Win10

##### Browser.
Chrome 60

**Comment by stefanneculai** [comment]
If you are inserting text in the editor using the `html.insert` or `html.set`, you should also use the `undo.saveStep` method in order to add the changes to the undo stack.

**Comment by LinGG** [comment]
would be great to have this as default true argument in the list. I guess around 99% of cases want to save the step.
