### ISSUE TITLE
Problem with new At.js

### ISSUE THREAD

**Issue by natcohen** [froala/wysiwyg-editor#2166]
I've tried to reimplement the new At.js into the latest froala and got issues after a selection was made. Try this: https://codepen.io/anon/pen/qXJpMy and add "@", choose one in the list and then try to put the pointer in what has just been added to the editor. Also trying to delete the selection with backspace doesn't work as well as arrows...

##### Steps to reproduce the problem.
https://codepen.io/anon/pen/qXJpMy

##### OS.
OSX

##### Browser.
Chrome

**Comment by stefanneculai** [comment]
That's because the inserted HTML should have the class `fr-deletable`. We'll put an update shortly.

**Comment by natcohen** [comment]
Looking forward to get this working... why did you put the enhancement tag? IMHO it's more a bug than an enhancement. You can't go backward with the arrows of your keyboard and it has unexpected behaviors. Anyway, if you get this working, it's all that matters.
