### ISSUE TITLE
Toolbar goes slightly out of top of window on Firefox

### ISSUE THREAD

**Issue by SeanKendle** [froala/wysiwyg-editor#2168]
##### Expected behavior.
Toolbar should test to see if it needs to be shown above or below content and display where it is fully visible.

##### Actual behavior.
Every other time, on Firefox, when the toolbar opens, it's shown floating out of the top of the window.

##### Steps to reproduce the problem.
Create an inline Froala on a page with several lines of text.  Open toolbar by highlighting text or left clicking if that option is available (I created a quick plugin that allows right-click to show the menu).  Half the time it sticks out of the top of the window, the other half it shows below the cursor and displays properly.

##### OS.
Windows 7

##### Browser.
Firefox (latest version)

![screenshot240](https://user-images.githubusercontent.com/5393604/29791956-dfd06950-8c0c-11e7-98f2-9253f55d4d9e.jpg)

**Comment by stefanneculai** [comment]
@SeanKendle could you please make a jsFiddle for it?

**Comment by SeanKendle** [comment]
Test this in Firefox:  highlight the top text in this example, and the toolbar will go out of the iframe:

https://jsfiddle.net/SeanKendle/88ex1L63/3/
