### ISSUE TITLE
inline mode does not working dropdown menu in IOS.

### ISSUE THREAD

**Issue by largeden** [froala/wysiwyg-editor#2170]
##### Steps to reproduce the problem.
![inlinemodeios](https://user-images.githubusercontent.com/5575931/29881224-faf3f196-8de4-11e7-9eb8-4d53cd136bca.gif)

There is a problem with the dropdown menu.

**Comment by largeden** [comment]
@stefanneculai 
https://github.com/froala/wysiwyg-editor/commit/acfefad571f96dad3f73714542138365e1ed4e71

There seems to be a problem with this commit.

**Comment by stefanneculai** [comment]
@largeden thanks for the additional investigation. We're going to check it shortly.

**Comment by stefanneculai** [comment]
@largeden great catch! We're reverting it for now to the previous behavior.
