### ISSUE TITLE
how to regist html change event?

### ISSUE THREAD

**Issue by icepoint0** [froala/wysiwyg-editor#2172]
i didn't see anything about this.

**Comment by stefanneculai** [comment]
Could you please detail what you mean by `html change event`?

**Comment by icepoint0** [comment]
click the code button,and input some html code. i want to observe the html code change

**Comment by stefanneculai** [comment]
We don't have an option for getting the changes from HTML view. A change in HTML view is considered finished when switching back to the editor. That's because rendering it before that, would involve a lot of computation to clean up the HTML each time and make it valid in case it's not.
