### ISSUE TITLE
Pasting issue with new lines (version diff 2.6.0 vs 2.6.5.)

### ISSUE THREAD

**Issue by benorudolf** [froala/wysiwyg-editor#2173]
##### Expected behavior.
When I paste a list like this:

CreatedBy 
Client 
CreatedDateTime 
FollowupByDate 
ContactName 
Text 

I would expect each line to be wrapped in a paragraph tag so I can easily edit this e.g. make a bullet list, each line its own bullet.

##### Actual behaviour.
No paragraphs are added. Break tags are used which makes creating a bullet list from this tedious.

##### Steps to reproduce the problem.
Paste a list-like text into the editor. 
This jsbin uses an older Froala **2.6.0** which wraps the lines correctly.
https://jsbin.com/yikewituyi/1/edit?html,js,output

If you change the Froala version to **2.6.5** (change the script include) the lines will not be wrapped.

##### OS.
OS X El Capitan 10.11.6

##### Browser.
Chrome Version 59.0.3071.115 (Official Build) (64-bit)

##### Additional
The example editor in the Examples section
https://www.froala.com/wysiwyg-editor/examples/inline

Seems to work correctly and Froala version is **2.6.5** 
(at least from the console by checking  _$.FroalaEditor.VERSION_)

**Comment by stefanneculai** [comment]
@benorudolf could you please send us a link to a page from where we can copy the HTML you're having problems with?

**Comment by benorudolf** [comment]
@stefanneculai I copied the list-like text from a Trello description, but you can use the above text or any other. This for example:

Item1
Item2
Item3

Again, on version 2.6.0 it will paste with each item being wrapped in a p tag enabling selection and creating bullet points in one go.
On version 2.6.5 it doesn't wrap items in p tags and you can't select all and create a bulleted list - it creates 1 bullet point out of the entire list. 

See JS bin; easily replicable, just change the version number in the script src and paste.

**Comment by stefanneculai** [comment]
We just checked this and the way the editor is currently pasting is the correct one. The pasted content is not a new paragraph, but a line inside an existing paragraph. Here is a screenshot of it for the content above.

<img width="618" alt="screen shot 2017-09-07 at 21 02 09" src="https://user-images.githubusercontent.com/637004/30177909-dcf2a418-940f-11e7-9863-2d347f066bf6.png">

**Comment by benorudolf** [comment]
@stefanneculai Thanks for the reply. Seems it's not as easy to reproduce as I first wrote this, but I found a sure way to do it. 

If you paste the _list like_ text on a new line or somewhere inside existing content it parses the list as a single paragraph and uses break tags between the lines.
However, if you clear your editor (select all + delete) and then paste, the lines get parsed as paragraphs each. (see gif)

![froala-2-6-0_list_paste_issue](https://user-images.githubusercontent.com/955836/30244205-9e226a36-95b1-11e7-8fea-7cee60745cbb.gif)

-----

This behaviour only happens on 2.6.0 and seems to be adjusted with 2.6.5 where it is consistent and always does a single paragraph with breaks. (see gif)

![froala-2-6-5_list_paste_issue](https://user-images.githubusercontent.com/955836/30244202-86ac3f12-95b1-11e7-863e-d25926e6fbde.gif)

-----

Since it's been fixed to be consistent in the newer version, I'm guessing that is the correct behaviour. 

So just for confirmation: if you paste a _list like_ text, like the one above, in to Froala and try to convert it in to a bulleted list in one go, it won't work?

**Comment by stefanneculai** [comment]
@benorudolf for such cases we would recommend changing the `enter` option to `$.FE.ENTER_BR`.

**Comment by benorudolf** [comment]
@stefanneculai Thank you for the information. Seems my question doesn't come out clearly. 

So the issue we're having is: 
If you **paste** a plain text like this in to Froala: 

item1
item2
item3 

Then select all items and try to create a bulleted list it will only create one bullet and not separate bullets. 
If you paste this exact text into Word or Google Docs, select all and create a bulleted list, each item becomes a bullet. 

Is this possible in Froala? 

----------

**Behaviour in Google docs**
![froala_editor_paste_list_2](https://user-images.githubusercontent.com/955836/30267753-77fd1826-96db-11e7-941c-e95bbf32b2d3.gif)

**Behaviour in Froala**
![froala_editor_paste_list](https://user-images.githubusercontent.com/955836/30267770-8224f774-96db-11e7-97ba-494f2ef0d14b.gif)

**Comment by stefanneculai** [comment]
Yes, that would be possible when using `enter: $.FroalaEditor.ENTER_BR`. This mode is similar to the way Google Docs handles new lines.

**Comment by benorudolf** [comment]
@stefanneculai I see! Seems to work as desired with the additional config value. 

Thanks for all the help and resolution!
