### ISSUE TITLE
Froala Editor violating Content Security Policy

### ISSUE THREAD

**Issue by caolan2603** [froala/wysiwyg-editor#2174]
##### Expected behavior.
When loading a page which contains a Froala editor no console errors are thrown & CSP is not violated

##### Actual behavior.
My CSP is set such that only internally hosted images are allowed with the exclusion added for base 64 images contained within css files (data:)

When loading a page which contains a Froala editor, console error is thrown stating: 
"Refused to load the image 'https://c0.froala.com/i?xxxxxxxxx' because it violates the following Content Security Policy directive: "img-src 'self' data:"." - **Where xxxxxxxxx is my Froala license key**

The request 'https://c0.froala.com/i?xxxxxxxxx' seems to be initiated by the froala-editor.min.js file.

Is there any way around this request without having to update my CSP?

##### Steps to reproduce the problem.
Set CSP to include `img-src 'self' data:;`
Load any page containg a froala editor

##### OS.
Windows 10

##### Browser.
Chrome Version 60.0.3112.113 (Official Build) (64-bit)

**Comment by stefanneculai** [comment]
Yes, please reach us via https://www.froala.com/wysiwyg-editor/contact and our support team will help you with this.
