### ISSUE TITLE
Wrong font-family format when saving

### ISSUE THREAD

**Issue by WayneUong** [froala/wysiwyg-editor#2175]
##### Expected behavior.
`<span style="font-family: &quot;Times New Roman&quot;, Times, serif; font-size: 18px;">a</span>`

##### Actual behavior.
`<span style="font-family: "Times New Roman", Times, serif; font-size: 18px;">a</span>`

##### Steps to reproduce the problem.
When editing font family and font size for paragraphs, the first `<p>` will save the `&quot;` as `"` along with the font name, causing display error in browser. The following `<p>` tags are however saved correctly.

##### OS.
OSX and Windows 10

##### Browser.
Chrome

**Comment by WayneUong** [comment]
The last `<p>` is affected too.

**Comment by stefanneculai** [comment]
Please make sure you're using the latest editor version.
