### ISSUE TITLE
Suggestion: Content free of fr- control classes.

### ISSUE THREAD

**Issue by ptheofan** [froala/wysiwyg-editor#2176]
Would be nice if the editor itself would provide a means of cleaning up the control classes set by the various plugins and used only for the "internals"

The cleanest possible way would be to create an element outside the forms etc where it keeps the code we actually edit and see and the actual control where we enable it on (example text-area) would only keep a clean copy withought the fr- classes, etc.

Example

<form><textarea id="froala-editor"></textarea></form>

froala should
1. create a hidden text area somewhere outside (say in the end of body tag)
2. Update all elements in there with all fr- classes etc as it needs them to work with
3. Keep the #froala-editor textarea clean with the actual html that should be submitted (no froala control classes).

This would allow to
1. Operate on existing html that was generated with other means (since froala can populate the classes it needs on the elements on load)

2. Submit clean html withought editor control functionality traces

3. make my life easier :D

What do you think?

**Comment by stefanneculai** [comment]
The editor is using `fr-` classes in order to enable rich features such as image alignment or image display. If you don't want these features, the easiest way around it would be not to include these features.

**Comment by ptheofan** [comment]
There appears to be a miss understanding here.

*We do not want to disable the features. We want to serve to live clean html withought utility classes meant for the editor.*

We want to ensure that these classes will never reach our frontend.

We can strip them away ourselves but when we upgrade if a new class is introduced that will leak into the system until it's noticed. The software that generates these classes should have the responsibility of removing them (aka IC).

**Comment by stefanneculai** [comment]
These classes are getting into the content only when they are being used for rich features to display the content. For example, there is `fr-dib` which is used for displaying the image a block with no text next to it. This class would, of course, be present in the output because you want the output to look just like the way the content was edited.

**Comment by ptheofan** [comment]
You have 2 type of classes.
1. Internal controls - example, fr-draggable
2. Styling - example fr-dib

The control related classes should be strippable from final content
The styling should be customisable so they can be adjusted to existing CSS (not sure if this is possible atm, haven't tried to modified that part yet)

**Comment by stefanneculai** [comment]
`fr-draggable` is being added as a way to tell the editor that the specific element is draggable. It can be used not only on images/videos but it can be used to extend the editor with other draggable elements as well. This is the reason why it is not being removed.

**Comment by ptheofan** [comment]
Which makes perfect sense for the editor. But the content is not generated to stay in the editor. We push this content in multiple channels. Example, web pages. On production frontend pages fr-draggable should not exist (it's control class for the editor and not used for styling)

These type of classes must be stripped from web pages (they are not needed, they add bytes, they add nodes to browser nodes indexing, etc)

As I mentioned we can strip them ourselves but since the editor is a component that can be updated, we want to be able to update it withought concerns about "What new control classes might have been introduced". This can only be done from the editor itself since the editor knows which classes are meant for editor usage only and not styling and only the editor can make this future-proof.

**Comment by stefanneculai** [comment]
I believe there is a misunderstanding because you are not taking into consideration editing the content for the 2nd time. If someone would extend the editor and create a special area which can be moved around by using the `fr-draggable`, the 2nd time when the content is being edited, the editor wouldn't know that the particular area should is draggable.

**Comment by ptheofan** [comment]
I have loaded content that had no fr- classes at all (from our older editor) and Froala did a great job at adding all the control classes where needed.

**Comment by stefanneculai** [comment]
Yes, it is doing that for images and videos, however, it couldn't have done that for custom areas which could be dragged. While I appreciate your suggestion, this is not something we're going to change, at least in the current major version because it might impact existing users.

**Comment by ptheofan** [comment]
Fair enough. By any chance you could introduce a function that would return an array with all the control classes? We can then leverage this one and future-proof eliminate them from the content.

**Comment by stefanneculai** [comment]
It doesn't make sense to add such an option just to have these values there. Here is the list of them: 
`fr-draggable`, `fr-dragging`, `fr-uploading`, `fr-selected-cell`, `fr-active`.

**Comment by ptheofan** [comment]
Ok, but this is not future proof solution. Just keep it in mind as it could be very helpful for future proof modular systems.

Regarding the styling classes (example fr-dib) is there some way I can rename them in the Froala instance setup through the options?

**Comment by stefanneculai** [comment]
Thanks for the suggestion, really appreciate it. 

No, we don't have an option for renaming the styling classes.
