### ISSUE TITLE
Suggestion: make link valid protocol configurable

### ISSUE THREAD

**Issue by corneverbruggen** [froala/wysiwyg-editor#2177]
When entering a URL in de link popup, or when using `link.insert`, the default protocol as defined in `linkAutoPrefix` is added when neither `http` nor `https` is detected. But sometimes you might want to use a protocol different then http or https. For instance, I'm working on an application where I want to refer to a global id of a resource having protocol `gid://`. Those href values are transformed by the backend application into a "normal" link on showing the content.

Using `link.insert` it is currently possible to provide a `href` value in the `attrs` parameter which overrides the value provided as the `href` parameter. But when editing such a link through the link popup, the `linkAutoPrefix` is still added. Plus this "workaround" might break, as it is not part of documented API.

Setting the  `linkAutoPrefix` to the custom protocol (in my case `gid://`) would not be convenient, because that breaks the functionality for adding "normal" links in the same editor.

**Suggestion**: add a `linkValidProtocols` configuration option that by default is `['http', 'https'] `and can be changed to e.g. `['http', 'https', 'gid']`. Only add the `linkAutoPrefix` when the URL does not start with any of the `linkValidProtocols + "://"`

**Comment by stefanneculai** [comment]
With the latest commit, you could use the following code to set protocols before initializing the editor.
```js
$.FE.LinkProtocols = ['mailto', 'tel', 'sms', 'notes', 'data', 'gid'];
```
