### ISSUE TITLE
Spellcheck language cannot be set

### ISSUE THREAD

**Issue by ptheofan** [froala/wysiwyg-editor#2178]
After some digging in the minified spell_check js I found and copied the configuration options (the ones on the documentation are not correct) so I ended up with these. 

```js
scaytOptions: {
            enableOnTouchDevices: false,
            localization:"de",
            extraModules:"ui",
            DefaultSelection:"Germany German",
            spellcheckLang:"de_DE",
            contextMenuSections:"suggest|moresuggest",
            serviceProtocol:"https",
            servicePort:"80",
            serviceHost:"svc.webspellchecker.net",
            servicePath:"spellcheck/script/ssrv.cgi",
            contextMenuForMisspelledOnly: true,
            scriptPath:"https://svc.webspellchecker.net/spellcheck31/lf/scayt3/customscayt/customscayt.js",
}
```

I would have expected spell checker to pass on the de_DE to the webspellchecker. Instead in request is formed as follows

`
cmd=check_spelling&customerid=...hidden...&format=json&out_type=words&version=1.0&slang=en_US&text=...the-actual-content...
`

Obviously the slang is set wrong.

Using version: 2.6.2

**Comment by wsc-julia-shaptala** [comment]
Hello Paris,

It looks like that spellcheckLang:"en_US" was saved in your browser local storage. Please try to clean it and let us know if this resolved the problem and now you can see spellcheckLang:"de_DE".

Sincerely,
WebSpellChecker LLC

**Comment by ptheofan** [comment]
Hi, 

Clearing the local-storage worked fine. However we use multiple languages under the same domain and the configuration of the SCAYT settings in Froalla are generated dynamically.

By my understanding, the data should be updated every time a Froala is initialised (preferrably should be instance dependant though I don't really mind as all the editors on a page use always the same language)

Are you planning on fixing that?

**Comment by jalners** [comment]
We have ‘disableOptionsStorage’ option in our application. But by default this option is empty and language (passed during the first initialization) is saved in localStorage. And Froala Editor does not allow to configure this option.

We will discuss with Froala team about disabling the storing data in localStorage or adding the ‘disableOptionsStorage’ option for ‘scaytOptions’.

**Comment by ptheofan** [comment]
Looking forward to an update.
Thank you.

**Comment by stefanneculai** [comment]
We're closing this for now and will continue this discussion on email.
