### ISSUE TITLE
When removing one word in a bolded sentence the space before is also removed

### ISSUE THREAD

**Issue by mukk85** [froala/wysiwyg-editor#2179]
##### Expected behavior.
**foo bar**
When selecting and deleting _bar_ I would expect the output to be **'foo '**

##### Actual behavior.
The space after foo is removed and the output is **foo**

##### OS.
OSX and Windows

##### Browser.
Chrome 60.0.3112.113

**Comment by stefanneculai** [comment]
@mukk85 this is fixed on the Github master.
