### ISSUE TITLE
Ability to add new table rows easily

### ISSUE THREAD

**Issue by WTK** [froala/wysiwyg-editor#218]
Some of our customers work with a large tables of data - it would be great if there would be a way in Froala to add new rows to the table easily - either (ideally) by pressing tab while focused on last cell in last row, or (at very least) by giving user an option to specify how many new rows he'd like to add.
Otherwise adding new row requires clicking 3 times, every time.

**Comment by stefanneculai** [comment]
I am closing this since it will be part of the new table tool we'll release during April.
