### ISSUE TITLE
Can't type text after inserting HR

### ISSUE THREAD

**Issue by Brisstor** [froala/wysiwyg-editor#2180]
Hello! Looks like here is a minor issue with hr.

##### Expected behavior.
I should be able to type text after inserting hr
##### Actual behavior.
I cant type text after inserting hr
##### Steps to reproduce the problem.
1) Type some text
2) Insert hr
3) You cant type more text after hr
##### OS.
macOS Sierra 10.12.6
##### Browser.
Chrome 60.0.3112.113 64 bit

**Comment by stefanneculai** [comment]
@Brisstor are you able to reproduce that on our website? https://www.froala.com/wysiwyg-editor/examples/full-featured

**Comment by Brisstor** [comment]
@stefanneculai yes, same. But sometimes it works, looks like it depends on click position. http://take.ms/AQJLr
