### ISSUE TITLE
Cannot prevent posting image

### ISSUE THREAD

**Issue by slavik990** [froala/wysiwyg-editor#2183]
Now after #2131 when we copy & paste image `beforeUpload` event triggered, but it cannot prevent posting image (image with base64 src added before event triggered). Here jsFiddle https://jsfiddle.net/mLsajwe1/3/

**Comment by stefanneculai** [comment]
That's because you should remove the image. See https://jsfiddle.net/mLsajwe1/4/ and make sure you're using the version 2.6.5.

**Comment by slavik990** [comment]
@stefanneculai Thanks!
