### ISSUE TITLE
imageReplace drag and drop not working

### ISSUE THREAD

**Issue by alexcrawford** [froala/wysiwyg-editor#2184]
##### Expected behavior.
Existing image should be replaced with the uploaded file.

##### Actual behavior.
Shows a greyed-out version of the image with no further input possible.

##### Steps to reproduce the problem.
Using v2.6.5 on your demo - click on the image, select the "Replace" button, drag and drop an image file onto the dropzone.

![screen shot 2017-09-07 at 17 23 29](https://user-images.githubusercontent.com/4070024/30173955-4f6156a8-93f1-11e7-8ef0-3e1a65acbb0f.png)

##### OS.
macOS Sierra

##### Browser.
Chrome 60

```
application-c7e2f6e37bb2d8dc23d7909387d894bc.js:24 Uncaught TypeError: Cannot read property 'offset' of null
    at r (application-c7e2f6e37bb2d8dc23d7909387d894bc.js:24)
    at HTMLImageElement.oe (application-c7e2f6e37bb2d8dc23d7909387d894bc.js:25)
    at _ (application-c7e2f6e37bb2d8dc23d7909387d894bc.js:25)
    at HTMLImageElement.s (application-c7e2f6e37bb2d8dc23d7909387d894bc.js:25)
    at HTMLImageElement.dispatch (application-c7e2f6e37bb2d8dc23d7909387d894bc.js:2)
    at HTMLImageElement.m.handle (application-c7e2f6e37bb2d8dc23d7909387d894bc.js:2)
```

**Comment by stefanneculai** [comment]
@alexcrawford could you please make a recording?

**Comment by alexcrawford** [comment]
![f5e6d3fb-85dc-4aef-add8-45f342361b7b-34187-00003fe395055db4](https://user-images.githubusercontent.com/4070024/30174423-f4c83386-93f2-11e7-8b44-e9b0e92c5ee6.gif)

**Comment by stefanneculai** [comment]
@alexcrawford few more questions 😄 
1. Which Chrome build version are you using?
2. Could you send us the image you're dropping there?
3. Could you make a screenshot of the entire error?

**Comment by alexcrawford** [comment]
Sure, see below.

** Which Chrome build version are you using? **
Chrome Version 60.0.3112.113 (Official Build) (64-bit)
Also happening in Safari 10.1.2
![screen shot 2017-09-08 at 08 58 27](https://user-images.githubusercontent.com/4070024/30201796-e69e7780-9473-11e7-824b-078d4455ae04.png)


** Could you send us the image you're dropping there? **
See below but this happens with any image.
![moon 1](https://user-images.githubusercontent.com/4070024/30201687-94d8e14c-9473-11e7-8473-8ae4394ac91f.jpg)

** Could you make a screenshot of the entire error? **
![screen shot 2017-09-08 at 08 57 34](https://user-images.githubusercontent.com/4070024/30201762-d1d5d032-9473-11e7-9750-e8b79d2f6509.png)

**Comment by alexcrawford** [comment]
@stefanneculai thanks for fixing - when should we expect a new release?

**Comment by stefanneculai** [comment]
@alexcrawford yesterday 😄. https://www.froala.com/wysiwyg-editor/changelog

**Comment by alexcrawford** [comment]
Good man! 👍
