### ISSUE TITLE
toolbarstickyoffset not working in Safari 10.1.1

### ISSUE THREAD

**Issue by jrhess3** [froala/wysiwyg-editor#2185]
I am using the toolbarstickyoffset feature and it is working fine on every browser except for 1

The toolbarStickyOffset is not working in Safari 10.1.1

The tool bar remains sticky and gets hidden as you scroll down the page

IOS 10.1.1
Also iPad 10.3.3

**Comment by stefanneculai** [comment]
@jrhess3 are you seeing this problem on https://github.com/froala/wysiwyg-editor/blob/master/html/toolbar/offset.html?

**Comment by jrhess3** [comment]
Hi Stefan,

The sticky offset feature works in Maverick 10.9.5, but doesn't work in El Capitan 10.11.6.

Here is your code live:

https://sfponline.org/newoffsettest.html


I used a textarea.


John


________________________________

**Comment by stefanneculai** [comment]
@jrhess3 it appears to work just fine on El Capitan 10.11.6. For now, we do not support this feature on mobile devices.

**Comment by jrhess3** [comment]
Hi Stefan,
Thank you for looking into it, it must be something with that particular user's  Mac.
The editor is really an excellent tool for my CMS.
John



Sent from my Sprint Samsung Galaxy S7.


-------- Original message --------
