### ISSUE TITLE
fr- classes not styling content outside of fr-view

### ISSUE THREAD

**Issue by NathanDubord** [froala/wysiwyg-editor#2186]
##### Expected behavior / ##### Steps to reproduce the problem.
When creating content in the Froala editor, saving the content, and displaying the content to the user, fr- styling does not take affect. I've tried toggling the "useClasses" config, but seems to have only fixed image alignment. Classes like fr-green, fr-strong, fr-dashed-borders, etc. only have styling affected to them within fr-view. Is this intended?

##### Browser.
Chrome 60

**Comment by stefanneculai** [comment]
@NathanDubord please see: https://www.froala.com/wysiwyg-editor/docs/overview#frontend.
