### ISSUE TITLE
Froala init on image - unrecognized expression on Safari

### ISSUE THREAD

**Issue by loicbisiere** [froala/wysiwyg-editor#2187]
##### Expected behavior.
The "Upload image popup" should open

##### Actual behavior.
On Safari on IOS or MacOS there is an error in console and the popup doesn't show up:
Error: Syntax error, unrecognized expression: [id*='fr-image-by-url-layer-text'
Safari doesn't support missing "]" (every browser except Safari on Windows and iPhone let this error slip through). See : https://stackoverflow.com/a/32147730/1626477

##### Steps to reproduce the problem.
Add froala editor on an image:

![image](https://user-images.githubusercontent.com/1148072/30236097-a44addd4-94e0-11e7-813f-58ac82f4fd82.png)

##### OS.
iOS or Mac

##### Browser.
Safari all version

**Comment by stefanneculai** [comment]
@loicbisiere we're not using such a selector. Please check if you are not extending the editor somehow and using it.
