### ISSUE TITLE
Add support for the Shift + Del shortcut for cutting text (Windows)

### ISSUE THREAD

**Issue by chrisdeeming** [froala/wysiwyg-editor#2188]
Apparently, an alternative shortcut in Windows for cutting text aside from `Ctrl+X` is `Shift+Del`. This is certainly undocumented but it does work and some other rich text editors do support it (CKEditor and Redactor).

##### Expected behavior.
`Shift+Del` should work the same as `Ctrl+X` on Windows. The highlighted text should be removed and added to the clipboard.

##### Actual behavior.
The text is deleted, but not copied  to the clipboard.

##### Steps to reproduce the problem.
* Highlight some text in the Froala demo while using Windows.
* `Shift+Del` removes the selection but it is not added to the clipboard.

Compare to Notepad:
* Highlight some text
* `Shift+Del` removes the selection and it is added to the clipboard

That shortcut seems to work globally in all apps.

##### OS.
Windows (any)

##### Browser.
Any

**Comment by JordanAtIgloo** [comment]
@chrisdeeming you appear to have a typo in your issue title.

**Comment by chrisdeeming** [comment]
I can't believe it's been like that for over 24 hours and no one else told me 🤣

**Comment by JordanAtIgloo** [comment]
@chrisdeeming it's happened to the best of us 😄
