### ISSUE TITLE
Losing text styling on copy paste from Google Docs

### ISSUE THREAD

**Issue by francisco-oktana** [froala/wysiwyg-editor#2193]
This behavior used to work and it stopped working, I don't know if Google changed things around on Google Docs or if there is any fix in the pipeline for Froala.

##### Expected behavior.
Mantain pasted styling from GDocs

##### Actual behavior.
Losing text styles on paste(bold, italics, underline, etc)

##### Steps to reproduce the problem.
Have a google doc with bolded text, underlined text, italics text. Copy paste into froala and all text styling is missing.

##### OS.
OSX El Capitan 10.11.6

##### Browser.
Chrome Version 60.0.3112.90

**Comment by stefanneculai** [comment]
@florinpopescu please send us the document you're pasting from.

**Comment by francisco-oktana** [comment]
https://docs.google.com/a/salesforce.com/document/d/16mvdmkGhcxCIx_JkzQg3SwXbxR_oZR7HYxdb_dFcsK8/edit?usp=sharing

We're using this document for testing

**Comment by stefanneculai** [comment]
@francisco-oktana I just requested access to the document.

**Comment by francisco-oktana** [comment]
@stefanneculai Just gave you access to the doc, sorry!

**Comment by stefanneculai** [comment]
@francisco-oktana the formats come from Google Docs in the `style` attribute. By default, the editor is designed to remove the `style` attribute, however, you can change that easily using the [pasteDeniedAttrs](https://www.froala.com/wysiwyg-editor/docs/options#pasteDeniedAttrs) option. Further on, you can also filter which style props you want to keep with the [pasteAllowedStyleProps](https://www.froala.com/wysiwyg-editor/docs/options#pasteAllowedStyleProps).

**Comment by stefanneculai** [comment]
It's on our TODO list to make something similar, however, we don't have any ETA for it now.
