### ISSUE TITLE
Mustache tags being moved

### ISSUE THREAD

**Issue by charleseswine** [froala/wysiwyg-editor#2196]
##### Expected behavior.
Mustache tags shouldn't be moved outside of a table tag when wrapping table rows and toggling code view off

##### Actual behavior.
Mustache tags are being moved outside of the table tag when code view is toggled off

##### Steps to reproduce the problem.
In the editor switch to code view and paste this:
```
<table>
	<tbody>
		<tr>
			<td>header</td>
		</tr>
		{{#listOfData}}
		<tr>
			<td>{{data}}</td>
		</tr>
		{{/listOfData}}
	</tbody>
</table>
```
Toggle out of code view and the mustache tags will be moved outside of the table.

##### OS.
macOS 10.12.6

##### Browser.
Chrome 60.0.3112.113

**Comment by stefanneculai** [comment]
@charleseswine the editor is using HTML code for editing. Moustache tags are not recognized by the browser as valid HTML tags and that's why they are being removed.

**Comment by ffjanhoeck** [comment]
@stefanneculai I have the same issue, which function is removing this things ? So I will try to override oder disable this function
