### ISSUE TITLE
"The given range isn't in document" error on image align

### ISSUE THREAD

**Issue by marinoboscolo** [froala/wysiwyg-editor#2197]
I got an error "The given range isn't in document" after a few times I added images and tried to align them left.
This error destroy the active froala instance leaving a confused html code in textarea input (tags not respecting the place order before error).
I tried versions 2.6.4, 2.6.5 and 2.6.6.
Tested in Chrome and Fireforx (both lastest version) on Windows 10.

**Comment by stefanneculai** [comment]
@marinoboscolo would it be possible to make a recording? Thank you.

**Comment by marinoboscolo** [comment]
![pau-froala](https://user-images.githubusercontent.com/5541983/30541657-b7d7a890-9c52-11e7-998c-10cde5db2514.gif)

**Comment by marinoboscolo** [comment]
I found another way to get same issue:
![pau-froala-2](https://user-images.githubusercontent.com/5541983/30541861-6ea3f290-9c53-11e7-9733-35d70cd20f37.gif)

**Comment by stefanneculai** [comment]
@marinoboscolo are you able to reproduce this on our website?

**Comment by stefanneculai** [comment]
I am closing this for now. We would be happy to look over it you could send us a link to a demo page where we can reproduce it. Thank you in advance.
