### ISSUE TITLE
Regex results in "Invalid regular expression" error in Chrome

### ISSUE THREAD

**Issue by SwintDC** [froala/wysiwyg-editor#2199]
##### Expected behavior.
Regex to work without browser exceptions.

##### Actual behavior.
A browser exception is thrown.

##### Steps to reproduce the problem.
1. build an app with webpack (with UglifyJS plugin) and the froala wysiwyg editor as npm package: "froala-editor": "2.6.6" with uglify options:
```
      new UglifyJsPlugin({        
        beautify: false, //prod
        output: {
          comments: false
        }, //prod
        mangle: {
          screw_ie8: true
        }, //prod
        compress: {
          screw_ie8: true,
          warnings: false,
          conditionals: true,
          unused: true,
          comparisons: true,
          sequences: true,
          dead_code: true,
          evaluate: true,
          if_return: true,
          join_vars: true,
          negate_iife: false // we need this for lazy v8
        }
      }),
```
2. Look at the resulting javascript code. The regex `new RegExp('([\uD83C-\uDBFF\uDC00-\uDFFF\u200D]+)' + ((first ? '' : '$')), 'i')` should be in there, but the string `\uD83C-\uDBFF\uDC00-\uDFFF\u200D` should be replaced with faulty unicode characters.

##### OS.
Win10

##### Browser.
Chrome 61

The problem is not so much an error of Froala, but with version 2.6.5 the error does not occur. In this version the unicode characters in the regex are escaped twice, for example: `\\ud83c`.

**Comment by stefanneculai** [comment]
@SwintDC it has already been fixed in the latest commit. We're going to publish this fix officially in couple of hours.

**Comment by SwintDC** [comment]
@stefanneculai Are you sure the regex I am talking about is also fixed ? Because I don't see any changes in your commit to that regex.

**Comment by stefanneculai** [comment]
Yes, that's the one that fixes it: https://github.com/froala/wysiwyg-editor/commit/fed2f09d86f21b9edf47f22c741408aaad5ae900.
