### ISSUE TITLE
Sketchfab embed support similar to youtube/vimeo

### ISSUE THREAD

**Issue by thedotedge** [froala/wysiwyg-editor#2201]
It would be good to have a possibility to paste [Sketchfab](https://help.sketchfab.com/hc/en-us/articles/205642585-Facebook) models in Froala (it's supported on a lot of major services: https://help.sketchfab.com/hc/en-us/articles/203509977-Embed-on-Web-Platforms#networks)

**Comment by stefanneculai** [comment]
Great news for you. We just added Embedlly as a plugin to the editor and starting with release 2.6.7 that is going to be possible. Make sure you follow us here for updates: https://www.froala.com/wysiwyg-editor/download#updates.

**Comment by stefanneculai** [comment]
@thedotedge we just published the new version and you can play with it on our website already.
