### ISSUE TITLE
Documentation: little typo

### ISSUE THREAD

**Issue by warpdesign** [froala/wysiwyg-editor#2202]
I'm not sure this is the right place for it, but I think I found a typo in the documentation:

>Specify the theme name to use in the editor. The theme should be included as CSS. For more details please read the color themes example.

> CODE EXAMPLE
```
$('.selector').froalaEditor({
  theme: dark
});
```

Since the theme parameter is a string, I guess the example code should be:

```
$('.selector').froalaEditor({
  theme: 'dark'
});
```

See [documenation](https://www.froala.com/wysiwyg-editor/docs/options#theme).

**Comment by nico-onmap** [comment]
Thanks!
