### ISSUE TITLE
Inserting multiple images causes editor to turn into text area showing HTML

### ISSUE THREAD

**Issue by danpolites** [froala/wysiwyg-editor#2204]
##### Expected behavior.
Expected to add multiple images, using display inline style, but text editor gets replaced with text area showing HTML.

![image](https://user-images.githubusercontent.com/340402/30601292-969f7e90-9d2f-11e7-8719-bfa9a3fbdcf2.png)

##### Actual behavior.
Adding multiple images and changing image size/display to inline causes froala editor to be replaced with text area populated with the editor's html. There is no way to get the froala editor back without a page refresh.

Here is a sample of what the editor gets replaced with:
![image](https://user-images.githubusercontent.com/340402/30600726-40215fd0-9d2e-11e7-878a-286a86f9b4db.png)

##### Steps to reproduce the problem.
Upload image
Resize Image
Change display to inline
Type some text
Upload another image
Resize image
May need to resize/change display a few times.

Other notes,  I have three froala editors on one page. Using angular froala 2.7.0 plugin. I also tried with 2.6.6. Reverting to 2.5.1 resolved the issue.

Froala Config
`{
    imagePasteProcess: true,
    imageMaxSize: 1024 * 1024 * 10, // 10MB
    pluginsEnabled: ['charCounter', 'image', 'lists', 'link'],
    zIndex: 2501,
    imageEditButtons: ['imageAlign', 'imageCaption', 'imageRemove', '|', 'imageLink', 'linkOpen', 'linkEdit', 'linkRemove', '-', 'imageDisplay', 'imageStyle', 'imageAlt', 'imageSize']
  }`

##### OS.
MacOS Sierra 10.12.6

##### Browser.
Google Chrome Version 61.0.3163.79 (Official Build) (64-bit)

**Comment by stefanneculai** [comment]
@danpolites your issues are related to your integration, not to the editor. If you have a demo page where we can see this problem, please contact us on https://www.froala.com/wysiwyg-editor/contact. Thank you in advance.

**Comment by danpolites** [comment]
My integration works fine simply by reverting both plugins back to 2.5.1.

**Comment by danpolites** [comment]
I get the same behavior when I putting a lot of text in the editor. This issue seems to happen when the editor begins scrolling. The destroy event is also fired.

**Comment by dimaloop** [comment]
Same issue detected with 2.6.6

**Comment by danpolites** [comment]
Something in a.FE.MODULES.data is keeping track of 10 of something and destroying the editor. Is it a licensing check or something else?
![image](https://user-images.githubusercontent.com/340402/30608043-1a7b9c84-9d45-11e7-9026-75a3f3fd4934.png)
