### ISSUE TITLE
Can not working image caption text in IOS.

### ISSUE THREAD

**Issue by largeden** [froala/wysiwyg-editor#2206]
##### Steps to reproduce the problem.
- iOS (iphone7)
- Click the caption feature icon in the image.
- Text can not be edited.

##### OS.
IOS

It's a amazing. 👍 
This is the plugin I was going to make.

I also have questions about this feature.
Why did not you use `figure`, `figcaption`?
I did not have any problems when I modified the `figure`, `figcaption`.

**Comment by largeden** [comment]
The code below is the cause of the problem.

$el.wrap('<figure **contenteditable="false"** class="fr-img-caption ' + $current_image.attr('class') + '" draggable="false"></figure>');

**Comment by FinesseRus** [comment]
The bug also occurs in desktop Safari.

##### Expected behavior.
It is possible to place the cursor to an image caption by clicking it. And it is possible to edit the image caption without going to the source code.

##### Actual behavior.
The cursor is not placed on an image caption (a click on the image caption does nothing).

##### Steps to reproduce the problem.
1. Make an editor instance with enabled images and image captions. You can get a ready instance [here](https://www.froala.com/wysiwyg-editor/examples/full-featured).
2. Insert an image to the editor.
3. Click the image.
4. Add the caption to the image.
5. Click the caption.

##### OS.
macOS 10.12.6 (didn't test in other versions)

##### Browser.
Safari 10.1 and 11.1 (didn't test in other Safaris). The bug doesn't occur in Chrome and Firefox.

**Comment by stefanneculai** [comment]
Indeed, there appears to be a problem in Safari because of that `contenteditable="false"`. 

Now, coming to the `figure` and `figcaption`. We chose not to use them because browsers do not allow using the `figure` tag inside `p` tags. Thus, having images with captions inside `p` tags wouldn't be possible. We are really interested in finding out more details about what you think on this matter as we've had lots of talks about it before doing this change.

**Comment by FinesseRus** [comment]
@stefanneculai 
> Now, coming to the `figure` and `figcaption`. We chose not to use them because browsers do not allow using the `figure` tag inside `p` tags. Thus, having images with captions inside `p` tags wouldn't be possible. We are really interested in finding out more details about what you think on this matter as we've had lots of talks about it before doing this change.

Here is my image caption implementation: https://gist.github.com/FinesseRus/7086abcc731a54a159cdf34cdf3e860b. It is a plugin that automatically adds a caption to all images. It takes a text for the caption from the alternate text. The `figure` and `figcaption` are displayed well on a webpage. The only problem is that the resizing doesn't work properly for inline images with a caption.

**Comment by stefanneculai** [comment]
@largeden @FinesseRus I believe you misunderstood my explanation. There are cases when the users have image inside a `P` tag. Something like this: `<p>foo <img> bar</p>`. If we'd wrap the image with a `figure`, the browsers would move it outside of the paragraph.

**Comment by FinesseRus** [comment]
@stefanneculai I understood you correctly. You are right, `figure` really splits the paragraph.

Perhaps paragraph split is such a rare case that even my users have never complained about it therefore I didn't notice it.

**Comment by largeden** [comment]
@stefanneculai 
I will explain a more detailed example of the use of the caption of the image I think.
![example1](https://user-images.githubusercontent.com/5575931/30794025-d07a2c52-a200-11e7-9a8d-cf9d08bc4702.png)

I think the use of figure tag is correct if I use the caption of the image for only the type A pattern.
But if you need to use the pattern of Type B, I think you need to use span tag.

When using Type A (figure tag), the following operation method is required.
#### Step1
I have the following conditions and I want to use captions for IMG tag.
```html
<p>text text text text <img src="image.jpg">text text text text text </p>
```

#### Step2
Wraps the IMG tag with a figure tag and replace it into a paragraph.
```html
<p>text text text text</p>
<figure><img src="image.jpg"><figcaption>image caption</figcaption></figure>
<p>text text text text text </p>
```

#### Step3
If you remove the image caption, the figure tag is replaced with the p tag.
```html
<p>text text text text</p>
<p><img src="image.jpg"></p>
<p>text text text text text </p>
```

**Comment by FinesseRus** [comment]
@largeden What the problem of using the `figure` tag for multiple pictures in a single line? I think it can be a problem only if you want to add a text to that line (who really needs such case?).

**Comment by largeden** [comment]
@FinesseRus The code of the last pattern of B type I am saying is as follows. I think that in this case the figure tag should not be used and the span tag should be used.
```html
<p>
    <span class="fr-img-caption fr-fic fr-draggable fr-dii" contenteditable="false" draggable="false">
        <span class="fr-img-wrap" style="width: 200px;">
            <img src="image.jpg" alt="Editor photo" style="width: 200px;" class="fr-fil fr-dib">
            <span class="fr-inner" contenteditable="true">Image caption</span>
        </span>
    </span>
    <img src="image.jpg" alt="Editor photo" class="fr-fic fr-dii" style="width: 200px;">
    <img src="image.jpg" alt="Editor photo" class="fr-fic fr-dii" style="width: 200px;">
</p>
<p>
    <img src="image.jpg" alt="Editor photo" style="width: 200px;" class="fr-fic fr-dii">
    <img src="image.jpg" alt="Editor photo" class="fr-fic fr-dii" style="width: 200px;">
    <span class="fr-img-caption fr-fic fr-draggable fr-dii" contenteditable="false" draggable="false">
        <span class="fr-img-wrap" style="width: 200px;">
            <img src="image.jpg" alt="Editor photo" style="width: 200px;" class="fr-fil fr-dib">
            <span class="fr-inner" contenteditable="true">Image caption</span>
        </span>
    </span>
</p>
```
![ws000001](https://user-images.githubusercontent.com/5575931/30795356-27d8559e-a208-11e7-84e6-69b07a8dddc0.PNG)

**Comment by stefanneculai** [comment]
@largeden @FinesseRus thank you guys for the feedback. We're going to analyze the options available there and take a decision based on that.

**Comment by FinesseRus** [comment]
@largeden You can make a bunch of images stay on a single line using `float: left`. Why do you need an image inside a paragraph?

**Comment by stefanneculai** [comment]
The last commit fixes the problem of the image caption not working on iOS. For the moment, we're going to keep the `SPAN` structure for compatibility with previous editor versions. Adding figure is a breaking change and we're going to add it only in a major release.
