### ISSUE TITLE
cut/copy Word with Wingdings font on firefox

### ISSUE THREAD

**Issue by maverick42** [froala/wysiwyg-editor#2207]
Hi,

When I copy text from word (with Wingdings font) with my FireFox Browser, the result is not good.
With Chrome and IE all works fine !

![image](https://user-images.githubusercontent.com/2311642/30625165-f21048d0-9dc1-11e7-8c3b-a746d8c280a3.png)

![image](https://user-images.githubusercontent.com/2311642/30625213-2f20e2ca-9dc2-11e7-80fe-e4e98a1e6808.png)

![image](https://user-images.githubusercontent.com/2311642/30625237-563424bc-9dc2-11e7-8117-ed5afa9646d5.png)

The pasted code : 

`<p style="margin: 0cm 0cm 10pt;"><span style="font-family: Wingdings;">&egrave;</span>Double fl&egrave;che&nbsp;</p><p style="margin: 0cm 0cm 10pt;"><span style="font-family: Wingdings;">J</span> Smiley</p>`

What do you think ?

Best regards 
Frédérik

Windows, Firefox , Ie Chrome

**Comment by stefanneculai** [comment]
@maverick42 we would need the doc file if possible. Thank you.

**Comment by stefanneculai** [comment]
@maverick42 we did a little bit of research on that and it looks like Firefox doesn't support `font-family: Wingdings` and that's why you are seeing it incorrectly.
http://mottie.github.io/Unicode/wingdings.html
