### ISSUE TITLE
Selecting table cells throwing an error.

### ISSUE THREAD

**Issue by ghedwards** [froala/wysiwyg-editor#2208]
When inserting a table using the Quick insert button at the bottom of my document with inline tools the selection of a table cell throws a javascript error ( attached )

<img width="949" alt="screen shot 2017-09-20 at 3 10 11 pm" src="https://user-images.githubusercontent.com/125586/30627831-14e01774-9e16-11e7-8c20-c86d2b08c8d7.png">

**Comment by ghedwards** [comment]
There appears to be multiple places where _tableMap() is called without arguments, which returns undefined, which would be ok if it weren't passed to elsewhere which is checking for it's length, and .length on undefined fails.

_cellOrigin passed an undefined map appears to be the origin of the issue.
`// Create a table map.
        var map = _tableMap();

        // Get first and last cell's i and j map coordinates.
        var firstCellOrigin = _cellOrigin(firstCell, map);
        var lastCellOrigin = _cellOrigin(lastCell, map);`

**Comment by stefanneculai** [comment]
@ghedwards are you able to replicate this on our website? Could you please send us a recording of that if so?

**Comment by ghedwards** [comment]
the function _tableMap(); returns undefined if $table is not truthy

**Comment by stefanneculai** [comment]
@ghedwards I believe the problem is coming from the fact that the table you have there is not HTML valid.

**Comment by ghedwards** [comment]
the function _tableMap(); returns undefined if $table is not truthy ( see for yourself ) ... is this intended ?

/*
     * Create a table map.
     */
    function _tableMap ($table) {
      $table = $table || null;

      var map = [];

      if ($table == null && selectedCells().length > 0) {
        $table = selectedTable();
      }

      if ($table) {
        $table.find('tr').not($table.find('table tr')).each (function (row, tr) {
          var $tr = $(tr);

          var c_index = 0;
          $tr.find('> th, > td').each (function (col, td) {
            var $td = $(td);
            var cspan = parseInt($td.attr('colspan'), 10) || 1;
            var rspan = parseInt($td.attr('rowspan'), 10) || 1;

            for (var i = row; i < row + rspan; i++) {
              for (var j = c_index; j < c_index + cspan; j++) {
                if (!map[i]) map[i] = [];

                if (!map[i][j]) {
                  map[i][j] = td;
                }
                else {
                  c_index++;
                }
              }
            }

            c_index += cspan;
          })
        });

        return map;
      }
    }

**Comment by stefanneculai** [comment]
@ghedwards is there a way we can reproduce this error?

**Comment by dianaprajescu** [comment]
This was not intended. However, it shouldn't have normally happen. The `_tableMap()` function is called without an argument only when there is a table selection in the editor. The source of your error indicates something is wrong, even though this issue is fixed.
