### ISSUE TITLE
Russian translation

### ISSUE THREAD

**Issue by FinesseRus** [froala/wysiwyg-editor#2211]
Here are not translated phrases than I've found. If there are more, please let me know.

* Special Characters — Специальные символы
* Print — Распечатать
* Spell Checker — Проверка правописания
* Help — Помощь
* URL — Адрес («URL» is also OK but less people understand it)
* Loading image — Загрузка изображения
* Advanced Edit — Продвинутое редактирование
* Image Caption — Подпись изображения
* Paste in a video URL — Вставьте адрес видео
* Upload video — Загрузить видео
* Drop video — Переместите сюда видео

Translate corrections:

* Quote — Цитата
* Select All — Выбрать всё
* Drop image — Переместите сюда изображение

**Comment by stefanneculai** [comment]
The last commit adds the corrections. For the rest of the translations, we're going to make a different commit as there are more missing translations in other languages.
