### ISSUE TITLE
Unable to resize table located in a "transformed" element

### ISSUE THREAD

**Issue by FinesseRus** [froala/wysiwyg-editor#2212]
##### Expected behavior.
Tables are resizable in a editor instance which is located in a HTML element with `transform` CSS rule. I can move vertical borders in such tables by dragging them.

##### Actual behavior.
Tables are not resizable. Cells are selected when I try to drag a vertical border.

##### Steps to reproduce the problem.
1. Make a HTML element with a `transform` CSS rule. The rule can have any value, even a zero transform (i.e. `translateX(0)`).
2. Put a Froala Editor instance with the table plugin inside the element.
3. Insert a table to the editor instance.
4. Try to resize a table cell.

[Demo on CodePen](https://codepen.io/TheFinesse/pen/gGrKNB)

##### OS.
macOS 10.12.6 (didn't test in other OSs)

##### Browser.
Safari 11.0, Safari 11.1, Chrome 61.0.3163.91, Firefox 55.0.3 (didn't test in other browsers)

**Comment by ppppaowu** [comment]
fr-table-resizer element have error left, top attribute.
![2017-11-14 11 22 09](https://user-images.githubusercontent.com/32115260/32761447-fa73a1ee-c8b8-11e7-8c0b-b8c6be2a4714.png)

**Comment by mthomasson** [comment]
Hi there!
I am encountering the same issue on every Linux browsers... 
Do you have any idea if it is planned to be tackled? And maybe when?

**Comment by stefanneculai** [comment]
@mthomasson yes, we're going to fix it. Unfortunately, we don't have an ETA for it at this moment.
