### ISSUE TITLE
Image Overlay wrongly positioned on scroll

### ISSUE THREAD

**Issue by pijulius** [froala/wysiwyg-editor#2213]
##### Expected behavior.
Started with 2.7.0 so expected behavior is to show the overlay (resizable blue rectangle) correctly on the image even if you scroll down just like in ver 2.6.0

##### Actual behavior.
The image overlay is getting placed more and more to the top as you scroll down. Meaning the overlay will be misplaced (above the image itself) or even outside of the viewport if long document.

##### Steps to reproduce the problem.
1. Please go here:
https://www.froala.com/wysiwyg-editor/examples/iframe
2. Click "Edit it Codepen"
3. This is important as codepen is still on 2.6.0: 
Edit HTML and replace 2.6.0 with 2.7.0 for Froala css and js files
4. Edit Javascript and add "heightMax: 200"
5. In the editor on the bottom add two new paragraphs
6. After the newly added paragraphs insert an image
7. Click on the image and start scrolling down

##### OS.
Linux

##### Browser.
Firefox 55

**Comment by stefanneculai** [comment]
@pijulius could you please make a record of the screen? Thank you in advance.

**Comment by pijulius** [comment]
Hi Stefan,

Sorry about that, just got some free time now to check this and saw your screen record request but as it seems it's not required anymore :) as I can confirm the fix works just fine and all is good now!

Thanks for the quick fix.

Regards,
Julius
