### ISSUE TITLE
[idea] Using embedly event.

### ISSUE THREAD

**Issue by largeden** [froala/wysiwyg-editor#2216]
Because the embedly plugins does not have height in the div.fr-embedly element, it is difficult to find the cursor position when `commands.undo` `commands.redo` events occur.

I added the code as shown below with reference to embedly docs.
http://docs.embed.ly/docs/cards#listeners

```javascript
//embedly.js
function _init () {
//...

//editor.events.on('contentChanged', _normalize);

  embedly('on', 'card.resize', function(iframe){
    // iframe is the card iframe that we used to render the event.
    $card = $(iframe);
    $card_parent = $card.parents('.fr-embedly');
    $card_parent.attr('contenteditable', false);
    $card_parent.attr('draggable', true);
    $card_parent.css('height', $card.height());
  });

  _initInsertPopup(true);
}
```
And,
what about loading the script internally, like the image_aviary plugin?

**Comment by stefanneculai** [comment]
@largeden I am not sure I understand the problem you're explaining. Could you please detail?

**Comment by largeden** [comment]
@stefanneculai 
Sorry.
My explanation was not good.

I am talking about a very minor problem.
This may be something that others will not care about.
This symptom appears on all OSs and browsers.

When I perform `commands.undo`, `commands.redo` as below, I see the phenomenon that the height is shaken by the _cleanOnGet function of the embedly plugin.
![embedly](https://user-images.githubusercontent.com/5575931/30808748-42a036e4-a23a-11e7-9f08-e30da003d1af.gif)

I chose to specify a height for the .fr-embedly element to solve this.
```javascript
  embedly('on', 'card.resize', function(iframe){
    $card_parent = $(iframe).parents('.fr-embedly');
    $card_parent.css('height', $card.height());
  });
```
![embedly_height](https://user-images.githubusercontent.com/5575931/30809028-4a985be6-a23b-11e7-94e8-0fc16aba01b0.gif)

If there is a willingness to improve, it is safe to apply `overflow: hidden` as well.
