### ISSUE TITLE
Pasting from word with track changes includes deleted words

### ISSUE THREAD

**Issue by mukk85** [froala/wysiwyg-editor#2217]
##### Expected behavior.
The updated document should be pasted

##### Actual behavior.
Deleted words show with a line through and added words show as underlined

##### Steps to reproduce the problem.
Create a word document and enable track changes. Make some changes to the document and copy/paste into editor

##### OS.
Windows

##### Browser.
Chrome latest

**Comment by mukk85** [comment]
Note: This happens with the Word Paste module enabled and when selecting either clean or keep options

**Comment by stefanneculai** [comment]
@mukk85 could you please send us a document sample?

**Comment by mukk85** [comment]
Nevermind, I think this is fine behaviour. Once we mark the changes as accepted they do not appear.
