### ISSUE TITLE
Pasting multi-level lists from word breaks formatting

### ISSUE THREAD

**Issue by mukk85** [froala/wysiwyg-editor#2218]
##### Expected behavior.
List can be viewed the same as it appears in word.

##### Actual behavior.
![image](https://user-images.githubusercontent.com/1731299/30676774-048ffc76-9eb2-11e7-9c5e-8858463800d7.png)

turns into

1. Heading  1
To get started right away,  just tap any placeholder text (such as this) and start typing.
1. Heading 2
i.To easily apply any text formatting you see in  this outline with just a tap, on the Home tab of the ribbon, check out Styles.
For example, this paragraph uses Heading 3 style.

##### Steps to reproduce the problem.
Create a new document in Word (I used the Outline template). Create a multi-level list. Copy/paste into editor.

##### OS.
Mac OS/Windows

##### Browser.
Chrome 60.0.3112.113

**Comment by stefanneculai** [comment]
@mukk85 we've just checked this and unfortunately because of the way the HTML comes from Word, at this moment we don't have the possibility to keep this formatting.
