### ISSUE TITLE
how to allow all tag and style froala editor on html mode

### ISSUE THREAD

**Issue by gofursp** [froala/wysiwyg-editor#2220]
##### Expected behavior.
im try to save some html file to database,
but froala editor always remove some html tag like this 

`	<body style="min-height: 500px;">&lt;html&gt;&lt;head&gt;&lt;meta http-equiv=&quot;content-type&quot; content=&quot;text/html; charset=UTF-8&quot;&gt;&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot;&gt;&lt;meta name=&quot;format-detection&quot; content=&quot;address-no&quot;&gt;&lt;meta name=&quot;format-detection&quot; content=&quot;telephone-no&quot;&gt;&lt;title&gt;Title goes here&lt;/title&gt;&lt;/head&gt;&lt;body align=&quot;center&quot; [removed]=&quot;font-size: 15px; color: #666;&quot;&gt;&lt;table [removed]=&quot;margin: 0 auto;font-size: inherit; line-height: inherit; text-align: center; border-spacing: 0; border-collapse: collapse; -premailer-cellpadding: 0; -premailer-cellspacing: 0; padding: 0; border: 0;&quot;&gt;
		<br>&nbsp;`

this js ```
$('#editor').froalaEditor({
            fullPage: true,
            //toolbarInline: true,
            charCounterCount: true,
            toolbarButtons: ['fontFamily', 'fontSize', 'color', 'paragraphFormat', '|', 'bold', 'italic', 'underline', 'strikeThrough', 'subscript', 'superscript', '|', 'align', 'formatOL', 'formatUL', 'indent', 'outdent', '-', 'insertImage', 'insertLink', 'emoticons', 'insertVideo', 'insertTable', '|', 'undo', 'redo', 'fullscreen', 'html'],
            toolbarVisibleWithoutSelection: true,
            heightMin: 500,

		
        });
```

**Comment by stefanneculai** [comment]
You should enable `fullPage` option for that.
