### ISSUE TITLE
Inconsistent in fonts and alignments of table in mail client

### ISSUE THREAD

**Issue by ShanmugaPriyanV** [froala/wysiwyg-editor#2221]
##### Expected behavior.
The Fonts that are given in Bold appear normal in mail clients. Similarly the table alignment are not appearing as created in Froala.

##### Actual behavior.
Fonts should appear Bold and the table alignment should be consistent created in Froala.

##### Steps to reproduce the problem.
Create a simple template with bold fonts and table containing data.
Set useClasses: false 
Send a mail to a mail client by using the saved template.

##### OS.
Windows 7

##### Browser.
chrome 60.0.3112.113

**Comment by stefanneculai** [comment]
I believe that the problem is not actually coming from the editor. Could you please make a jsFiddle to highlight this problem? Thank you in advance.

**Comment by ShanmugaPriyanV** [comment]
Hi  @stefanneculai i have created a js fiddle https://jsfiddle.net/80b7mvv9/ that contains the froala editor.
We sent the mail using the content from js fiddle and the font alignment and formatting have issues as reported earlier.
The screen shots of the content in the jsfiddle and the content received in mail are attached.

**Template created in Froala (jsFiddle)**
![froala template3](https://user-images.githubusercontent.com/20870994/30808801-1c487c30-a21d-11e7-8996-43174362ca09.JPG)


**Mail Content Received**
![froala mail](https://user-images.githubusercontent.com/20870994/30808807-20f07b34-a21d-11e7-89b3-cc2ba9e6c0de.JPG)

**Comment by stefanneculai** [comment]
@ShanmugaPriyanV we would need the HTML template you had there in the editor. Thank you.

**Comment by ShanmugaPriyanV** [comment]
Hi @stefanneculai . I have updated the fiddle https://jsfiddle.net/80b7mvv9/2/ with the content to be displayed in Editor, Thanks.

**Comment by stefanneculai** [comment]
@ShanmugaPriyanV we just tested the content from the jsFiddle you posted and it looks just fine in the email. Basically, the output of the editor, in this case, would be the one at the bottom. We put it in a test by sending that HTML in an email using https://putsmail.com/tests.

If you are using Outlook 2017-16, there might be a potential problem with the width CSS property on tables as highlighted on https://www.campaignmonitor.com/css/box-model/width/. Unfortunately, there is not too much which can be done about it. 

```html
<p>This is a text. This is a text. This is a text. This is a text. This is a text. This is a text. This is a text. This is a text. This is a text. This is a text. This is a text. This is a text. This is a text. This is a text. This is a text. This is a text. <strong>This is a text.&nbsp;</strong>This is a text. This is a text. This is a text. This is a text. This is a text. This is a text. This is a text. This is a text. This is a text. This is a text. This is a text. This is a text. This is a text.</p><p>This is a text. This is a text. This is a text. This is a text. This is a text. This is a text. This is a text. This is a text. This is a text. This is a text. This is a text. This is a text. This is a text. This is a text. This is a text. This is a text. This is a text.<strong>&nbsp;This is a text.</strong> This is a text. This is a text. This is a text. This is a text. This is a text. This is a text. This is a text. This is a text. This is a text. This is a text. This is a text. This is a text.</p><p>This is a text. This is a text. This is a text. This is a text. This is a text. This is a text. This is a text. This is a text. This is a text. This is a text. This is a text. This is a text. This is a text. This is a text. This is a text. This is a text. This is a text. <strong>This is a text.&nbsp;</strong>This is a text. This is a text. This is a text. This is a text. This is a text. This is a text. This is a text. This is a text. This is a text. This is a text. This is a text. This is a text.</p><table style="width: 100%;"><tbody><tr><td style="width: 20.0000%;">This is a text<br></td><td style="width: 20.0000%;">This is a text<br></td><td style="width: 20.0000%;">This is a text<br></td><td style="width: 20.0000%;">This is a text<br></td><td style="width: 20.0000%;"><strong>This is a text</strong><br></td></tr><tr><td style="width: 20.0000%;">This is a text<br></td><td style="width: 20.0000%;">This is a text<br></td><td style="width: 20.0000%;">This is a text<br></td><td style="width: 20.0000%;">This is a text<br></td><td style="width: 20.0000%;"><em>This is a text</em><br></td></tr></tbody></table><table style="width: 100%;"><tbody><tr><td style="width: 20.0000%;">Second table</td><td style="width: 20.0000%;">Second table<br></td><td style="width: 20.0000%;"><u>Second table</u><br></td><td style="width: 20.0000%;">Second table<br></td><td style="width: 20.0000%;">Second table<br></td></tr><tr><td style="width: 20.0000%;">Second table<br></td><td style="width: 20.0000%;">Second table<br></td><td style="width: 20.0000%;">Second table<br></td><td style="width: 20.0000%;">Second table<br></td><td style="width: 20.0000%;">Second table<br></td></tr></tbody></table>
```
