### ISSUE TITLE
Popups show below bottom of window sometimes

### ISSUE THREAD

**Issue by SeanKendle** [froala/wysiwyg-editor#2222]
##### Expected behavior.
The popups should know whether they'll show off the bottom of the window, and instead show above an element if they fit below the top of the window.  If the popup won't fit below or above, it should show in the center of the element if possible.  If it can't show in the center of the element (with arrow facing up or down to point toward the center of the element) maybe it should show in the center of the screen).

##### Actual behavior.
Popups allow themselves to display beyond the bottom of the window

##### Steps to reproduce the problem.
Insert a very large image.  Scroll so the top of the image is sufficiently far down on the page to allow for the popup to show above it, but the image hangs below the bottom of the window.  Click the image, it will show the popup below the image, off the screen.

##### OS.
Windows 7

##### Browser.
Firefox, Chrome, IE 11 (although IE 11 scrolls down a bit to try to encompass the new popup menu it seems, but falls short a bit and only shows about half of the popup)

**Comment by stefanneculai** [comment]
@SeanKendle please create a jsFiddle for this. Thank you in advance.

**Comment by SeanKendle** [comment]
JSFiddle isn't working.  They're appending an extra quote into the jQuery script tag suddenly.

However, the example on the Froala website is enough to test it.  Just make the image in that example full width in the editor.

https://www.froala.com/wysiwyg-editor

**Comment by stefanneculai** [comment]
@SeanKendle Would it be possible to create a recording for it? Thanks.

**Comment by SeanKendle** [comment]
https://www.youtube.com/watch?v=dZKclK6hVf8

**Comment by stefanneculai** [comment]
The editor is designed to show popups inside the `scrollableContainer` option as long as there is room. I am marking this as an enhancement, however, we're not going to change this behavior in the current major version V2.

**Comment by SeanKendle** [comment]
Is `scrollableContainer` not the window when editing inline?

**Comment by stefanneculai** [comment]
It is the full body, not the viewport.
