### ISSUE TITLE
Captions: No way to go to next line

### ISSUE THREAD

**Issue by irphilli** [froala/wysiwyg-editor#2224]
##### Expected behavior.
After filing out a caption, there should be a way to "break" out and go to the next line.

##### Actual behavior.
Doesn't seem to be a way to break out of the caption text box.

##### Steps to reproduce the problem.

1. Have an image as the last element of the content
2. Add a caption
3. Try to break out (press enter, try to hover for break bar, etc)

Screencap: 
![caption](https://user-images.githubusercontent.com/345511/30755653-5de5f472-9f7c-11e7-872b-738b14ba2679.gif)

##### OS.
Mac OS

##### Browser.
Chrome Latest

**Comment by stefanneculai** [comment]
With the last commit, the Line Breaker can be used for that. For now, it is the best solution we can provide.

<img width="663" alt="screen shot 2017-09-28 at 18 16 30" src="https://user-images.githubusercontent.com/637004/30974805-443d4eba-a479-11e7-8085-df24135b2867.png">

**Comment by irphilli** [comment]
That is perfect - thanks!
