### ISSUE TITLE
free?

### ISSUE THREAD

**Issue by asktalk** [froala/wysiwyg-editor#2226]
##### Expected behavior.
(Describe expected behaviour here)

##### Actual behavior.
(Describe actual behaviour here)

##### Steps to reproduce the problem.
(Describe the steps to reproduce the problem here)

##### OS.
(OS name and version here)

##### Browser.
(Browser name an version here)

**Comment by stefanneculai** [comment]
Hi @asktalk! No, it is not free. Please find our pricing plans here: https://www.froala.com/wysiwyg-editor/pricing.

**Comment by AkgunFatih** [comment]
$239 its just bullshit
