### ISSUE TITLE
placeholder no way to change after initialisation

### ISSUE THREAD

**Issue by Fandangi** [froala/wysiwyg-editor#2227]
##### Expected behavior.
There should be an API method via which the placeholder text can be changed. For various reasons the editor may be re-used, maybe in a popup input process launched in relation to varying input content. The placeholder may therefore need to be changed with the intent of the input.

##### Actual behavior.
No way to change the placeholder text.  API provides placeholder hits / show / refresh / isVisible function but no change.

##### Steps to reproduce the problem.
No real repro - just create a Froala editor instance and ponder how to change the placeholder without tearing it down.

##### OS.
All versions - this is a core issue.

##### Browser.
All browsers - core issue.

**Comment by stefanneculai** [comment]
Actually, there is one. See: https://github.com/froala/wysiwyg-editor/issues/1678#issuecomment-270628939.

**Comment by Fandangi** [comment]
Thanks for pointing that out.  Can you give me a URL to the docs where this is explained ? [Save me having to open another issue pointing out the missing documentation ]

**Comment by stefanneculai** [comment]
We don't have in documentation explained how to change options after initialization because in most of the cases that is not possible and the right way to go is by destroying the editor and initializing it again. We're preparing some articles for that and they will be available shortly.

**Comment by Fandangi** [comment]
ok thanks. I get that. Writing code is easy, writing documentation is a pain and always lags. Your product is excellent btw. I will  try your suggested fix later today and come back to you if there is any issue.
