### ISSUE TITLE
Better Image Browsing within Image Manager

### ISSUE THREAD

**Issue by StefanNeuser** [froala/wysiwyg-editor#2230]
#1510 At the moment the current Froala loads and shows all images if the file manager gets open. In our case for example we get images from pages, news, newsletters which ends in a messed up overview within image browsing. 

Are there any solution that is currently not documented at https://www.froala.com/wysiwyg-editor/docs/concepts/image/manager ?

Possible behaviour might be:

1. if tags are available within the imageManagerLoadURL response than group the tags and just load and show the images of the first (alphabetic order) tag.
2. if you browse to another tag, froala loads and shows the images assigned to this tag

**Comment by stefanneculai** [comment]
Thank you for the suggestion. What we recommend is to use the tags. By default, all the tags are shown, however when clicking them, they are toggled.

**Comment by StefanNeuser** [comment]
Thank for your reply. We use the tags but that did'nt solve the issue. Why did you close it?

**Comment by stefanneculai** [comment]
@StefanNeuser we've designed tags to work just like filters. By default, no tag is selected because that's how app usually work when no filter is selected, take for example the list of issues on Github. If you would like to have this working differently, it would be better to change the Image Manager and adapt it as per your needs.

**Comment by ca-dsgn** [comment]
Maybe this will help somebody in future: everybody who's looking for a mechanism to just load a default tag on imagemanager start:

`
$("#editor").froalaEditor().on('froalaEditor.imageManager.imageLoaded', function (e, editor, data) {

	$(".fr-image-list img").each(function() {

		if ($(this).attr("data-tag") != $(".fr-modal-tags a:first-child").text()) {

			$(this).parent().hide();
		}
	});

	$(".fr-modal-tags a:first-child").addClass("fr-selected-tag");
});`

**Comment by molidort** [comment]
Facing with the same problem.
A search mechanism should be added urgently.
Just add a simple INPUT at the upper line, look for tags. 
Otherwise it is unusable and inefficient at all.
Why is the manager only for images? we need it also for videos.
Thanks.
