### ISSUE TITLE
Change Default behaviour of Image copy Paste & Drag drop

### ISSUE THREAD

**Issue by ShanmugaPriyanV** [froala/wysiwyg-editor#2232]
Currently in Froala Editor if i copy and paste an image, it gets uploaded to Froala server. Same process occurs while dragging and dropping images into the editor. In the editor integrated in my application, we replaced the default image plugin to a plugin that inserts dataURI of that image. Is there any way to do the same thing for Copy/Paste and Drag & Drop?
Thanks in Advance.

**Comment by stefanneculai** [comment]
@ShanmugaPriyanV I believe this is what you're looking for: https://wysiwyg-editor.froala.help/hc/en-us/articles/115000555949-Can-I-insert-images-as-base64-.
