### ISSUE TITLE
Empty value after "html.set"

### ISSUE THREAD

**Issue by alkoval** [froala/wysiwyg-editor#2233]
##### Expected behavior.
After sending the form to the server, you need to get the value from the editor.

##### Actual behavior.
The value in the form is equal to the empty.

##### Steps to reproduce the problem.
The editor is added to the textareatag in the form, for subsequent sending to the server. I pass the value to the editor using jquery:
`$('#PreviewText').froalaEditor('html.set', response.previewText);`
Visual text is displayed. But the counter is zero. When I submit a form, I get an empty value and when I try to get values, I get emptiness.
[Screenshot](https://photos.app.goo.gl/I9x7msQxxMDUTPxy2)

##### OS.
Windows 10. Visual Studio 2017.

##### Browser.
Chrome

**Comment by alkoval** [comment]
If before sending to the form server, call this:
`$('#PreviewText').froalaEditor('events.trigger', 'blur');`
then you can get values from the editor.
[https://photos.app.goo.gl/8PkWAO4YNBReHsUB3](Screenshot)

**Comment by stefanneculai** [comment]
@alkoval you should call the `undo.saveStep` method after setting the HTML.
