### ISSUE TITLE
Add image uploading proxy support to bypass CORS issues

### ISSUE THREAD

**Issue by dswitzer** [froala/wysiwyg-editor#2234]
One of the issues our users have run into, is they often are trying to paste images from other sites and end up running into CORS issues so the images won't paste. To resolve this issue, I've created the following patch which adds proxy support to the image plugin. 

The way this patch works is if the `imageProxy` option is true, then if an image with a source of `http` or `https` is seen, then an XHR request is fired off to the path in the `imageUploadURL` with the value of the string in the `imageProxyParam` parameter. You can then use your favorite server-side technology to try and download the file. The expected return parameters are the same as if a blob was posted to the server for upload.

Here's my patch for v2.7.0:

```
diff -r image.js image.with.proxy.js
4a5,23
>  *
>  *
>  * **** image.js Modifications ****
>  *
>  * Image Upload Proxy support
>  * This is a modification which has added support for image pasting to
>  * a proxy. If an absolute image exists in the output, the URL is sent to the
>  * server for the server to download the file and return an updated link. To
>  * enable the feature, added the following configuration properties:
>  *
>  *   , imageProxy: true         // enables image proxy support
>  *   , imageProxyParam: 'proxy' // field that contains the <img /> "src" attribute
>  *
>  * If an image is pasted with an absolute link (i.e. https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png)
>  * the URL is send via the imageProxyParam to the imageUploadURL. This means
>  * the imageUploadURL script must look for either imageUploadParam or imageProxyParam
>  * field and act accordingly. If the "imageProxyParam" value exists, the request should
>  * just do a HTTP request to grab the image as binary data.
>  *
6d24
< 
35c53
<   
---
> 
50a69,72
>     /* added properties */
>     imageProxy: false,         // enables support for the image proxy
>     imageProxyParam: 'proxy',  // the name of the form field to send containing the image source
>     /*/end */
2248a2271,2346
>           /* MOD */
>           // image proxy handler
>           else if (editor.opts.imageProxy && img.src.indexOf('http') == 0) {
>           	if (editor.events.trigger('image.beforePasteUpload', [img]) === false) {
>           		return false;
>           	}
> 
>           	// Show the progress bar.
>           	$current_image = $(img);
>           	_repositionResizer();
>           	_showEditPopup();
>           	replace();
>           	showProgressBar();
>           	editor.edit.off();
> 
>             // Create form Data.
>             var form_data = new FormData();
> 
>             // Add upload params.
>             for( var key in editor.opts.imageUploadParams) {
>               if (editor.opts.imageUploadParams.hasOwnProperty(key)) {
>                 form_data.append(key, editor.opts.imageUploadParams[key]);
>               }
>             }
> 
>             // Set the image in the request.
>             form_data.append(editor.opts.imageProxyParam, img.src);
> 
>             // Create XHR request.
>             var xhr = editor.core.getXHR(editor.opts.imageUploadURL, editor.opts.imageUploadMethod);
> 
>             /* this was taken from the _startUpload() function, ideally the code would be refactored into something re-usable, for example: function createSendRequest(xhr, form_data){ return function _sendRequest(){ ... exist code.... };}; */
>             function _sendRequest () {
>               var $img = $(this);
> 
>               $img.off('load');
> 
>               $img.addClass('fr-uploading');
> 
>               if ($img.next().is('br')) {
>                 $img.next().remove();
>               }
> 
>               editor.placeholder.refresh();
> 
>               // Select the image.
>               _editImg($img);
>               _repositionResizer();
>               showProgressBar();
>               editor.edit.off();
> 
>               // Set upload events.
>               xhr.onload = function () {
>                 _imageUploaded.call(xhr, $img);
>               };
>               xhr.onerror = _imageUploadError;
>               xhr.upload.onprogress = _imageUploadProgress;
>               xhr.onabort = _imageUploadAborted;
> 
>               // Set abort event.
>               $img.off('abortUpload').on('abortUpload', function () {
>                 if (xhr.readyState != 4) {
>                   xhr.abort();
>                 }
>               });
> 
>               // Send data.
>               xhr.send(form_data);
>             }
> 
>             _sendRequest.apply(img, []);
> 
>           	$(img).removeAttr('data-fr-image-pasted');
>           }
>           /* /MOD */
> 
```

The footprint for this addition could be even smaller, if some of the other code in the image.js library was refactored. For example, the `_sendRequest` function is a duplicate of a function used elsewhere in the code, but it's done as a private function and isn't currently re-usable.

While I could attempt to make this a standalone plugin, it leverages a lot of the existing private functions and methods in the image code. With a little more refactoring of the current image plugin, I think the actual additional footprint of this feature would be almost nothing and I think it adds a lot of value.

**Comment by stefanneculai** [comment]
@dswitzer thanks for the suggestion. I marked this as a `feature-request` and I am closing it for now. While this is very helpful, we would make this update just after we can also update the editor SDKs and server-side examples to accommodate it.

**Comment by stefanneculai** [comment]
The last commit adds a better solution. By default, the editor would use a proxy from cors-anywhere.froala.com and it can be changed to https://github.com/Rob--W/cors-anywhere for more flexibility by clients through the `imageCORSProxy` option. More details will be added in the documentation with the official release.

**Comment by dswitzer** [comment]
That looks intriguing as a way to fix the CORS issue.

**Comment by dswitzer** [comment]
I actually had a chance to finally play around with this, while it addresses the issue it ends up generated a lot of HTTP requests. I'm seeing an HTTP request for each of the following:

1. The original image is requested
2. Then the CORS URL is requested
3. Another HTTP request is sent to then send the Base64 data to upload the image to the server
4. Finally, the final image uploaded URL is requested

So if you paste a request that has dozens of images, this workflow really added up.

However, in my original proposal there's a lot less HTTP requests:

1. The URL is passed to the proxy, which handles the downloading and uploading
2. The final image URL is requested

In my testing, using the proxy is much more efficient.

**Comment by stefanneculai** [comment]
@dswitzer I agree that your approach might make fewer requests, however, it involves additional steps configuring the server-side and we'd prefer not to reinvent the wheel in this case.

**Comment by dswitzer** [comment]
It's not a required step, it's optional for someone who wants to handle it that way. Users who want to have users upload images are going to need an upload script anyway, so I don't see this as being any real problem. The only difference between the upload and proxy endpoints, are the proxy grabs the file from an HTTP request and the upload script gets it from the file upload.
