### ISSUE TITLE
Clear format removing links

### ISSUE THREAD

**Issue by SidKH** [froala/wysiwyg-editor#2236]
Hey guys.
It seems like right now clear format button completely removes links from the text, leaving only raw text.  
Even in the demo on your site.
Is this behavior intentional?  
It doesn't work like that in big word processing apps like google docs . Links always remain untouchable. That's why I'm asking.

**Comment by stefanneculai** [comment]
@SidKH yes, this is how it is designed. I marked this as a feature request, so maybe we're going to add an option for it later on.

**Comment by priscilazetace** [comment]
Hello, are there any updates on this issue?
I would like to know if this feature request was anyhow processed.
Cheers
