### ISSUE TITLE
Allow GitHub Gists Script (But not other script tags)

### ISSUE THREAD

**Issue by tonyspiro** [froala/wysiwyg-editor#2237]
Either something like the video Insert By Url, or an ability to add the GitHub gist <script> embed.  It would need to only allow the GitHub Gist URL to prevent XSS.  Medium does this very intuitively by converting a simple link.
![wg3upvimmw](https://user-images.githubusercontent.com/1950722/30968927-85ebb688-a426-11e7-8ea3-9f70868741f7.gif)

**Comment by stefanneculai** [comment]
@tonyspiro you could do that through the Embedly plugin we offer. https://www.froala.com/wysiwyg-editor/examples/embedly

<img width="402" alt="screen shot 2017-09-28 at 16 38 36" src="https://user-images.githubusercontent.com/637004/30969586-82cb24a8-a46b-11e7-9dc9-ec32c1fe0b3b.png">
