### ISSUE TITLE
TypeError Cannot read property 'tagName' of null  (Stack Trace Included)

### ISSUE THREAD

**Issue by jpgilchrist** [froala/wysiwyg-editor#2238]
Froala 2.6.6

TypeError Cannot read property 'tagName' of null 
    webpack:///soschat-client/src/main/froala/js/froala_editor.pkgd.js:5547:29 Object.insert
    webpack:///soschat-client/src/main/froala/js/froala_editor.pkgd.js:29974:18 Object.insert
    webpack:///soschat-client/src/main/froala/js/froala_editor.pkgd.js:33128:17 t.callback
    webpack:///soschat-client/src/main/froala/js/froala_editor.pkgd.js:10598:19 Object.n
    webpack:///soschat-client/src/main/froala/js/froala_editor.pkgd.js:12373:71 exec
    webpack:///soschat-client/src/main/froala/js/froala_editor.pkgd.js:12380:6 _commandButtonClick
    webpack:///soschat-client/src/main/froala/js/froala_editor.pkgd.js:12410:8 click
    webpack:///soschat-client/src/main/froala/js/froala_editor.pkgd.js:12420:6 t.l
    webpack:///soschat-client/src/main/froala/js/froala_editor.pkgd.js:1082:16 _buttonMouseUp
    webpack:///soschat-client/src/main/froala/js/froala_editor.pkgd.js:1114:39 HTMLSpanElement.<anonymous>

##### Expected behavior.
not to cause an error

##### Actual behavior.
causes an error

##### Steps to reproduce the problem.
I don't know.. but the breadcrumbs in our bugsnag dashboard shows this:
![image](https://user-images.githubusercontent.com/5065660/30976341-8d3b4982-a442-11e7-9605-0ece4833c91b.png)
Something to do with inserting a table.

![image](https://user-images.githubusercontent.com/5065660/30976397-b1dc8058-a442-11e7-953e-ab5ee990a622.png)

**Comment by stefanneculai** [comment]
@jpgilchrist It is fixed in version 2.7.0.

**Comment by jpgilchrist** [comment]
Oh Excellent thank you!
