### ISSUE TITLE
Can't use backspace key while image is selected (iframe option bug)

### ISSUE THREAD

**Issue by cauethenorio** [froala/wysiwyg-editor#2240]
##### Expected behavior.
After selecting an image in the froala editor I want to select a input/textarea element in the page and remove it's content with the backspace key

##### Actual behavior.
After selecting an image in the froala editor any input/textarea element in the page ignore the backspace key press

##### Steps to reproduce the problem.
1. Initialize a froala instance with iframe option
2. Insert or select an image in the editor
3. Focus on an input/textarea element in the page
4. Try to remove the field content with backspace key

##### OS.
OSX  10.11.6

##### Browser.
Chrome 61
Edge 15

Froala try to avoid user leave the page while an image is being uploaded to the editor, default-preventing the backspace key press event globally while a image is selected. But when you create an editor instance with the iframe option, any selected image keep selected even after you select other elements in the page.

**Comment by stefanneculai** [comment]
@cauethenorio please make sure you're using version 2.7.0. This issue is fixed in the latest version.

**Comment by cauethenorio** [comment]
Thanks @stefanneculai, using v2.7.0 the issue is gone.

**Comment by ArnoutHub** [comment]
@stefanneculai I'm on version v3.2.3 and this issue seems to have returned.
