### ISSUE TITLE
(>= 2.6.5) Incorrect placeholder position when ".fr-view p" has set margin-top

### ISSUE THREAD

**Issue by fenivana** [froala/wysiwyg-editor#2241]
##### Expected behavior.
The placeholder should at the same vertical alignment with the cursor.

##### Actual behavior.
![froala-placeholder-issue](https://user-images.githubusercontent.com/11750532/31044832-bc258e8c-a59c-11e7-8d62-8c253ea01c2d.png)

##### Steps to reproduce the problem.
set `froala_style.css`:
```css
.fr-view p {
  margin: 16px 0;
}
```

##### OS.
macOS 10.12.6

##### Browser.
Chrome 61.0.3163.100

**Comment by stefanneculai** [comment]
@fenivana in version 2.7.0 this works as expected.
