### ISSUE TITLE
At JS Issue with iPhone Soft Keyboard

### ISSUE THREAD

**Issue by PvanHengel** [froala/wysiwyg-editor#2243]
##### Expected behavior.
As a user types in the text area when using at js, you would expect to be able to type the At Sign and text, then press "enter" to select the first item in the list. 

##### Actual behavior.
When a user presses enter to select the first item in the atjs list, the editor removes the text.

##### Steps to reproduce the problem.
Open https://www.froala.com/wysiwyg-editor/examples/at-js in an iPhone safari browser, and type "@I" then press enter, you will see the expected popup window, then it will begin to filter, Isabella will appear as the selected (first) item in the list, and then press "enter" the list will close and no text will be inserted.  To see expected behavior, open the exact same example (https://www.froala.com/wysiwyg-editor/examples/at-js) in a browser and do the same test, it will work.   In addition, if you attach an external keyboard to the iPhone (or iPad) and use that enter key it works as expected (another words the "soft on screen" keyboard doesn't work, but a physical keyboard does).  Also if using an iPad Pro, when you press shift to switch from the number 2 to the @ sign, the text ends up as the number 2 after pressing enter.

##### OS.
iOS 10.3

##### Browser.
Safari

**Comment by stefanneculai** [comment]
It's fixed now on master brach.
