### ISSUE TITLE
custom response structure in image manager

### ISSUE THREAD

**Issue by mateuszwitkowski** [froala/wysiwyg-editor#2244]
##### Expected behavior.
API I'm working with returns information about images in different form than expected by Froala's image manager. Is there any way to: 1) customize default object structure?; 2) add domain address in thumb path dynamically? Any workaround?

Expected form:
```
[
  {
    "url": "http://exmaple.com/images/photo1.jpg",
    "thumb": "http://exmaple.com/thumbs/photo1.jpg",
    "tag": "flower"
  }
]
```

In my case:
```
data: [
{
 'path': 'xx/zzz/test/png', // here I need to insert "http://domain.example.com dynamically"
...
}
```
]

##### Actual behavior.
There's no obvious way to customize expected response structure.

**Comment by stefanneculai** [comment]
@mateuszwitkowski at this moment we don't have such an option. I marked this as a `feature-request` for now and we'll add such an option shortly.

**Comment by mateuszwitkowski** [comment]
@stefanneculai Any update on this one?

**Comment by stefanneculai** [comment]
@mateuszwitkowski unfortunately, I don't have an ETA for it at this moment.

**Comment by stefanneculai** [comment]
We've just put together a public roadmap with the most popular features. 😍 There you can vote your favorite one, provide feedback or make new suggestions: https://wysiwyg-editor-roadmap.froala.com/public.
