### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by aeoris** [froala/wysiwyg-editor#2245]
We are considering this editor for a commercial project, but don't really understand whether this project is open source or not. The license provided with the project states that a purchase is needed to use the editor, but does hosting it on GitHub that it's open-source project?

What would we have to purchase for a commercial use of the editor and can we use it free of cost "as provided" when downloading the source, for whatever purpose?

**Comment by stefanneculai** [comment]
In order to use the editor, you would have to purchase a license from https://www.froala.com/wysiwyg-editor/pricing. We host it on Github so that we can easily publish it to `bower` and `npm` and to also have a bug tracker.
