### ISSUE TITLE
Styling text with a contenteditable="false" span inbetween

### ISSUE THREAD

**Issue by MANETEC** [froala/wysiwyg-editor#2247]
Expected behavior.
Marking the text and making it Bold styles the whole text except the contenteditable="false" span

Actual behavior.
Marking the text and making it Bold styles the whole text up to the contenteditable="false" span

Steps to reproduce the problem.
https://jsfiddle.net/gfp4tt1q/1/

OS.
Windows 10

Browser.
Firefox 56.0(32-Bit)

**Comment by stefanneculai** [comment]
@MANETEC we consider this as being the correct behavior as the strong would wrap the zone with `contenteditable="false"`. `contenteditable="false"` means that content within it cannot be edited, but the one from outside can be edited.
