### ISSUE TITLE
Custom protocols

### ISSUE THREAD

**Issue by TomMettam** [froala/wysiwyg-editor#2250]
The implementation for #2177 appears not to be working as intended.

`$['FroalaEditor'].LinkProtocols = ['mailto', 'tel', 'sms', 'notes', 'data', 'secondlife'];`

Still results in this URL being completely removed from links:

`secondlife:///app/agent/828f7198-42e5-41b4-bd60-926a33ea067b/about`

**Comment by stefanneculai** [comment]
@TomMettam please make sure you're setting it before initializing the editor.

**Comment by TomMettam** [comment]
@stefanneculai : I am setting it before initialising the editor, with angular-froala-wysiwyg:

`public initialize(initControls)
    {
        $['FroalaEditor'].LinkProtocols = ['mailto', 'tel', 'sms', 'notes', 'data', 'secondlife'];
        initControls['initialize']();
    }`
