### ISSUE TITLE
pasteDeniedTags ignoring an 'iframe' tag

### ISSUE THREAD

**Issue by Brisstor** [froala/wysiwyg-editor#2252]
Hello, looks like there is a small issue with iframe pasting when it's denied;
I'm not sure, but i did not noticed this case in previous versions of Froala.

P.S. Thank you for great editor and fast and effective responses!

##### Expected behavior.
I've got 'iframe' in pasteDeniedTags array, and anyway, a can paste an iframe
##### Actual behavior.
Iframe is ignoring on paste
##### Steps to reproduce the problem.
Copy some content with iframe, and paste it in editor
##### OS.
macOS Sierra 10.12.6 (16G29)
##### Browser.
61.0.3163.100x64

**Comment by stefanneculai** [comment]
@Brisstor could you please provide a link from where we can copy it?

**Comment by Brisstor** [comment]
Sure, the pasted iframe were from here - https://habrahabr.ru/company/jugru/blog/335276/
