### ISSUE TITLE
Inline toolbar disappear on hovering over submenu dropdown. in IE 11 + Windows 7 

### ISSUE THREAD

**Issue by pkhruasu-ui** [froala/wysiwyg-editor#2254]
##### Expected behavior.
Inline toolbar stay visible when hovering over any submenu (like headings).

##### Actual behavior.
The whole toolbar disappear right when I move my mouse over the submenu (like H1, H2, H3)

##### Steps to reproduce the problem.
1. USe Windows 7 + IE 11 + manually activate a container element with toolbarInline = true; 
2. Double click on a text so toolbar shows up.
3. Click on an option like aligning or headings so the submenu shows up.
4. Mouseover the submenu. At this point the whole toolbar disappear.

##### OS.
Windows 7

##### Browser.
IE 11

**Comment by stefanneculai** [comment]
@pkhruasu-ui could you please make a recording? Thank you.

**Comment by RHinderiks** [comment]
Same, Windows 8.1 and ie 11. Both found by our own customers and reproduced on the froala website

![ezgif com-crop](https://user-images.githubusercontent.com/26223525/32283355-5f0a336e-bf24-11e7-912a-d8a0a699ea38.gif)

**Comment by RHinderiks** [comment]
@stefanneculai Are you able to reproduce it now ?
