### ISSUE TITLE
Manually Trigger a Custom Registered Command

### ISSUE THREAD

**Issue by sunjidshibly** [froala/wysiwyg-editor#2257]
Is there a way to trigger a custom Register Command?

here is my custom register command,

$.FroalaEditor.DefineIconTemplate('material_design', '<i class="fs0 [NAME]"></i>');
        $.FroalaEditor.DefineIcon('guardFile', {NAME: 'fs0 efile-guard_file1', template: 'material_design'});
        $.FroalaEditor.RegisterCommand('guardFile', {
            title: 'Guard File',
            focus: true,
            undo: true,
            showOnMobile: true,
            refreshAfterCallback: true,
            callback: function () {...}
        });

I want to call it's callback function from inside a jQuery function.
Is it possible?

**Comment by stefanneculai** [comment]
Yes, it can be done like this:
```js
var editor = $(selector).data('froala.editor');
editor.commands.guardFile();
```
