### ISSUE TITLE
Ordered list and unordered list when clicked off adds 21 pixels to left margin in the next paragraph

### ISSUE THREAD

**Issue by moddaman** [froala/wysiwyg-editor#2258]
##### Expected behavior.
When I create a list and then turn it off again  by clicking the list tool I expect the next paragraph to have the same margin as the paragaph(s) before the list. 

![image](https://user-images.githubusercontent.com/2629760/31653614-7402baf0-b323-11e7-9240-ba37a28019cd.png)

##### Actual behavior.
The paragraph after a list gets a inline style margin-left of 21px (chrome, 20px in explorer).

##### Steps to reproduce the problem.
click ordered- or unorderedlist in a editor.
create at least one list element.
press return
turn off the ordered list

PS: If you click return twice when you are in the list. The editor has the expected behavior and will not add the left-margin. Only if the user turns it off by clicking the list tool.

##### OS.
Windows 10 Enterprise.
Version: 1703

##### Browser.
Chrome 61.0

**Comment by jjsiman** [comment]
I am also having this issue with an unordered list inserted after a paragraph. We gave the <p> a margin-left in order to give the illusion of centered spacing and when you enter to the next line and insert a list, it enters `<ul style="margin-left: 175px">...</ul>"
