### ISSUE TITLE
imageUpload set to false still uploads image to i.froala.com

### ISSUE THREAD

**Issue by bcanseco** [froala/wysiwyg-editor#2264]
##### Expected behavior.
Using the [imageUpload](https://www.froala.com/wysiwyg-editor/docs/options#imageUpload) option set to `false`, uploading an image by URL will add the image to the editor and use the provided image URL as the source.

##### Actual behavior.
The image is added to the editor, but it is still uploaded to https://i.froala.com and doesn't use the URL you provided as the source.

##### Steps to reproduce the problem.
https://codepen.io/anon/pen/NaeZoQ
1. Click the image button
2. Enter https://i.imgur.com/g3D5jNz.jpg into the field
3. Click Insert
4. Right click the inserted image and hit Inspect
5. The image's `src` attribute is a https://i.froala.com URL, not the original https://i.imgur.com URL.

##### OS.
Windows 10 64bit

##### Browser.
Chrome 61.0.3163.100

**Comment by stefanneculai** [comment]
@bcanseco please make sure you're using editor version 2.7.0.

**Comment by bcanseco** [comment]
@stefanneculai It works in 2.7.0, just wanted to give you a heads up that it's not working with the js from the top of the master branch.

**Comment by stefanneculai** [comment]
We'll check.

**Comment by stefanneculai** [comment]
@bcanseco just tested the master branch and all is good. I believe you did something wrong.

**Comment by jackley** [comment]
@stefanneculai I just tried 2.7.4 with imageUpload false and it is still posting to i.froala and attempting to upload.

![image](https://user-images.githubusercontent.com/2819040/34598311-ee414ae6-f1b9-11e7-9ede-cb4cf404635e.png)

![image](https://user-images.githubusercontent.com/2819040/34598324-039beeaa-f1ba-11e7-8bdd-bdfcbacadcf9.png)

![image](https://user-images.githubusercontent.com/2819040/34598349-36a6174e-f1ba-11e7-8838-467e56d8c722.png)

**Comment by stefanneculai** [comment]
@bcanseco @jackley please turn off https://www.froala.com/wysiwyg-editor/docs/options#imageUploadRemoteUrls.
