### ISSUE TITLE
Copy paste from word shifts the text out of editor

### ISSUE THREAD

**Issue by adamcooper** [froala/wysiwyg-editor#2265]
##### Expected behavior.
The copy paste includes the text aligned in the box

##### Actual behavior.
The text is aligned properly in the editor.

![image](https://user-images.githubusercontent.com/12883/31745331-ea800c50-b427-11e7-81a2-de37ee2abaea.png)

Actual document
![image](https://user-images.githubusercontent.com/12883/31745472-696e7a88-b428-11e7-921c-b89674ce2b8a.png)

##### Steps to reproduce the problem.
Use the attached document and copy and paste the details into froala.

##### OS.
Mac OSX

##### Browser.
Tested in Chrome but I'm guessing other browsers too.

[shifted_copy_paste_bug.docx](https://github.com/froala/wysiwyg-editor/files/1396520/shifted_copy_paste_bug.docx)

**Comment by stefanneculai** [comment]
@adamcooper we just checked it and in this case, the margin comes from Word as being negative margin. If you don't want to take the margin into consideration, I would recommend changing the following option: https://www.froala.com/wysiwyg-editor/docs/options#wordAllowedStyleProps.
