### ISSUE TITLE
Uncaught TypeError: b.opts.codeMirror.fromTextArea is not a function

### ISSUE THREAD

**Issue by btmdave** [froala/wysiwyg-editor#2268]
We're running froala 2.7.0 with codemirror 5.30.0.   Tested in Chrome, we get the above error when trying to switch to code view.  Any idea what could cause this? We're not explicitly calling this anywhere.

**Comment by btmdave** [comment]
It looks like if we set the codeMirror option to reference codeMirror, i.e., `{codeMirror: window.CodeMirror}` this seems to work, as oppose to this being set to `true`.  Is that right?

**Comment by stefanneculai** [comment]
@btmdave that is right. The option was changed and now you should use `codeMirror: window.CodeMirror`.

**Comment by davidrichied** [comment]
The docs should definitely be updated.

Code view would work for me after clicking it twice, but the error that I got from using "codeView: true" broke the code beautifier.

Here is an example page where the JS Fiddle isn't working: https://www.froala.com/wysiwyg-editor/examples/code-mirror

Here is where it is listed incorrectly in the docs: https://www.froala.com/wysiwyg-editor/docs/options#codeMirror

**Comment by stefanneculai** [comment]
@davidrichied we'll update it shortly. Thanks for pointing it out.

**Comment by mephju** [comment]
Removing the `codeMirror` option from the object resolves the issue for me.
