### ISSUE TITLE
Uploading vimeo videos produces unexpected URL

### ISSUE THREAD

**Issue by ncmancuso** [froala/wysiwyg-editor#2269]
##### Expected behavior.
When copying a vimeo url and pasting in the Froala video upload plugin, the video should appear in the editor with a proper URL.

##### Actual behavior.
Extra slashes are being applied which is causing issues with our external sanitizer. 

##### Steps to reproduce the problem.
Note: The 4 slashes "////" in the iframe's src.

![vimeo](https://user-images.githubusercontent.com/6825718/31792986-e5a5c76e-b4eb-11e7-9d16-95bbd235291b.gif)

##### OS.
OS X El Capitan 10.11.6

##### Browser.
Chrome

**Comment by bocasfx** [comment]
Seems to be related to #1709
