### ISSUE TITLE
Adobe is shutting down the Creative SDK (Aviary) Image Editing UI

### ISSUE THREAD

**Issue by aarndt** [froala/wysiwyg-editor#2271]
Adobe has announced that they will be shutting down the Image Editor UI that is utilized by Froala for image editing and manipulation.

https://creativesdk.zendesk.com/hc/en-us/articles/115004788243

Are there any plans to replace this functionality with something else?

**Comment by stefanneculai** [comment]
Yes, we're aware of it and we'll add an alternative.

**Comment by dianaprajescu** [comment]
@aarndt is there a particular alternative that you would prefer to have for advanced image editing?

**Comment by inquam** [comment]
Have you identified any good replacement candidate for the Image Editor UI? I'm in a similar position where I have built a plugin for a system that uses it and now I'm trying to find a good replacement. I was hoping Adobe could open source it and let people host the (probably heavy and for them costly) backend components on their own servers now when they are killing it. But that is unlikely to happen.

**Comment by stefanneculai** [comment]
@aarndt @inquam we'd probably go with https://www.photoeditorsdk.com/.

**Comment by inquam** [comment]
@stefanneculai Yea, I saw them too and was thinking about them. But how will you handle their subscription fee? Will every user have to have their own subscription if they want to enable the feature?

**Comment by stefanneculai** [comment]
@inquam every user would have to handle their own subscription in order to enable this feature.

**Comment by m1is** [comment]
So let me get this straight Adobe is eliminating the image editor and replacing it with anything else?

**Comment by inquam** [comment]
@m1is: Yes, that is correct. For existing production applications support will continue until November 2018. I raised the idea of them making it open source and allow people to host the back end on their own servers (since that is probably what costs a bit for them to keep running). But they seem happy with just letting it die. Perhaps we could get a petition going? :)

**Comment by m1is** [comment]
So they bought Aviary just to kill it, was a great product, how sad.

**Comment by huyph** [comment]
@stefanneculai : any idea when support for photoeditorsdk will be worked on?. Currently I can not register for adobe creative SDK. It looks like it is no close the door for new comers.

**Comment by stefanneculai** [comment]
@huyph we're looking to add it at during January. We're also taking into consideration adding an in-house solution for this as well.

**Comment by inquam** [comment]
@stefanneculai If you make your own solution I'd love if you open sourced it. It would probably help a lot of people in this position due to Adobe's crap move.

**Comment by iukpo** [comment]
I am in a similar predicament. I came across two image editors-one for Android, the other for iOS-that I think will fit the bill and are free (they use the MIT license). HTH.

https://github.com/yackle/CLImageEditor

https://github.com/eventtus/photo-editor-android

**Comment by inquam** [comment]
These won't help me much since my need is for the web. I can understand if Adobe sees no money in this and only have to pay for servers etc. But just shutting it down after the history of Aviary and not provide any solution or releasing the code as open source is quite crappy to be honest. Especially since I contacted Adobe and asked them about their plans for the image editor and it's future before I started implementing my project and was told they had no plans on removing it or even starting to charge for it.

Then, a few months after I released my thing, they kill it :P

**Comment by BjornMelgaard** [comment]
@inquam raise a petition

Have same problem https://adobeio.zendesk.com/hc/en-us/requests/2632

**Comment by inquam** [comment]
@BjornMelgaard: I get "The page you were looking for doesn't exist"... Should I put my tinfoil hat on? :)

**Comment by BjornMelgaard** [comment]
@inquam seems like its private conversation) the problem is that aviary api keys have stopped working and I have this issue https://github.com/trippo/ResponsiveFilemanager/issues/441.

You have said that you want to raise a petition to opensource aviary, I'm in.

**Comment by adrienlamotte** [comment]
Hi Guys,
Any update on this ? What is the Froala plan to replace Aviary ?

**Comment by scottybo** [comment]
would also be interested to hear an update

**Comment by josh3336** [comment]
anyone found a suitable alternative to the web sdk? @scottybo @inquam @srghma

**Comment by srghma** [comment]
@josh3336 no

**Comment by stefanneculai** [comment]
We're planning on replacing Adobe Aviary with http://ui.toast.com/tui-image-editor/. An update will come shortly.

**Comment by stefanneculai** [comment]
There is a method for opening a file from a specific URL (http://nhnent.github.io/tui.image-editor/latest/ImageEditor.html#loadImageFromURL) and for saving the edited image, we're going to use http://nhnent.github.io/tui.image-editor/latest/ImageEditor.html#toDataURL.

**Comment by inquam** [comment]
Yea, but I don't think the documentation is very clear.

toDataURL returns a DOMString containing the requested data URI. Sounds a bit diffuse. I would expect for instance the image data encoded somehow so I can post it to for instance a PHP backend. This might be what they mean, but URI doesn't sound like this is what I would get. But if you have had time to test the function, what does it return?

**Comment by stefanneculai** [comment]
We haven't got yet to that place, however, taken into consideration the internal methods that we have available in the editor for working with images, we can take any URL and further upload it by using the editor logic. Adobe Aviary works just the same way.

**Comment by stefanneculai** [comment]
We've just put together a public roadmap with the most popular features. 😍 There you can vote your favorite one, provide feedback or make new suggestions: https://wysiwyg-editor-roadmap.froala.com/public.

**Comment by ianwantstea** [comment]
It looks like Adobe have changed their mind on retiring Aviary.

There's a migration guide, which says:

"The Web Image Editing component is the first Web component in the Creative SDK and we’ve made great efforts to ensure that migrating from the Aviary SDK to the Adobe Creative SDK is as seamless as possible."

Details:

https://creativesdk.zendesk.com/hc/en-us/articles/202903359-Migrating-from-the-Aviary-SDK-to-the-Adobe-Creative-SDK

The homepage also has a fullscreen splash saying it's now a "key component" of Creative SDK.

https://developers.aviary.com/

**Comment by inquam** [comment]
@ianwantstea But this is the exact implementation I have made in my project. I even used the desired callbacks instead of deprecated ways and I was told this was going to go away. I have received no other mail saying "hey, we changed our minds". This seems very strange. Not just a bad date on that article?

**Comment by ianwantstea** [comment]
@inquam the article date could be wrong, I guess. That seems unlikely for Adobe though. The homepage splash screen does also suggest image editing support is being continued. The migration guide is also linked to from this splash screen (you have to scroll down).

Other resources suggest it's retiring:

Changelog:
https://www.adobe.io/apis/creativecloud/creativesdk/docs/websdk/adobe-creative-sdk-for-web_master/changelog.html

Blog post:
https://blog.creativesdk.com/2017/09/important-update-to-the-creative-sdk-end-of-support-for-the-image-editor-ui-color-ui-market-browser-and-labs-components/

I'm confused by what they're doing.

**Comment by inquam** [comment]
I hit them up on Twitter asking them to explain

**Comment by stefanneculai** [comment]
It is not clear if they will keep it or not. Anyway, we're going to implement Toast UI - it is good to have from where to choose. :)

**Comment by ianwantstea** [comment]
I've tried to contact them, including msg'ing some of the product managers on Twitter, but haven't had a reply yet.

**Comment by kvitozev** [comment]
@ianwantstea, do you have any feedback from Creative SDK's team?

**Comment by kvitozev** [comment]
Unfortunately, that was it :) 

![0eaa9c22c153cec0f7ffe7c9eaa3fa43](https://user-images.githubusercontent.com/1749918/47845570-0f083e00-ddce-11e8-8b29-22523b248a08.png)

**Comment by stefanneculai** [comment]
@kvitozev We're just in time with a replacement: https://github.com/froala/wysiwyg-editor/commit/79120fef0721fe5094184e27ed023906323e10b1. 😄

**Comment by atrauzzi** [comment]
Out of curiosity, was anyone in this thread able to get a clear confirmation that Adobe no longer maintains an embeddable web-based image editor?

**Comment by T-vK** [comment]
I think they made a blog post in December 2018.

**Comment by atrauzzi** [comment]
Do you have a link to it?  Everything I've found so far seems kind of vague.

**Comment by T-vK** [comment]
http://blog.aviary.com/archive/eol

**Comment by atrauzzi** [comment]
If you read carefully, you'll see there's no mention of the web-based SDK.  This only mentions android and ios.  There are still mentions today in live adobe documentation about the web based editor.

That's exactly what I'm talking about.  While I can obviously glean it isn't something I should probably want to use at this rate, it would be nice to have it clear.

**Comment by T-vK** [comment]
"the Photo Editor by Aviary" does in my opinion include the web-based one. I'm pretty sure it's discontinued. Most aviary domains are down and they even canceled the API key I used.  
But I don't know... I just didn't wanna bother trying to keep that thing alive. ToastUI's image editor seems like the better choice anyway because it doesn't rely on third party servers.

**Comment by kaanuki** [comment]
My app mainly needs a photo editor with built in, Instagram-like filters. That's a must for me.  Are there any Filter presets available for ToastUI?

**Comment by T-vK** [comment]
I don't know what Instagram-like filters are, but you can check out a demo of ToastUI's Image Editor on their website: http://ui.toast.com/tui-image-editor/

And you can of course save your edited images or send them where ever you want using ajax.

**Comment by kaanuki** [comment]
Instagram-like filters / 'Preset Filters'  are filter settings that you can apply anytime, without having to manually adjust the filter settings every time (See example).  Preset Filters were made popular by Instagram.  Is it possible to SAVE FILTER SETTINGS themselves  -- I'm  not refering to  'edited images' with the filters applied to them?

![filter-example](https://user-images.githubusercontent.com/5781065/51280578-00cdc500-19ae-11e9-8a1a-82444877e1f1.PNG)
