### ISSUE TITLE
Froala export unneeded inline element when fullapge=true, useClasses= false

### ISSUE THREAD

**Issue by Ohadcy** [froala/wysiwyg-editor#2275]
Hello,

When using mode fullPage=true, useClasses=false
Seems like Froala export unnecessary inline elements.
For example on design mode if you add some basic table for example:
```
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <title></title>
    </head>
    <body>
        <table>
            <tbody>
                <tr>
                    <td>This is a simple Text&nbsp;</td>
                </tr>
            </tbody>
        </table>
    </body>
</html>
```

You will get this inline element in the code mirror as in the screenshot below, and then there is a border in the output html:
![image](https://user-images.githubusercontent.com/18525400/31929869-2efe673c-b8a6-11e7-879a-7f324c9d7c23.png)

And here is the result, border in the cell which is not needed and probably is being added from the design view:
![image](https://user-images.githubusercontent.com/18525400/31930073-0ea0cd30-b8a7-11e7-9311-a137a26d504a.png)

It seems like Froala break also input html with inline elements.

Now, If I understand correctly when useClasses=true, I need to handle the output classes by myself either by write it as inline element in <style> or by using Froala link:
https://cdnjs.cloudflare.com/ajax/libs/froala-editor/2.6.0/css/froala_style.min.css
Which is not common use for emails

Please advise.

**Comment by stefanneculai** [comment]
@Ohadcy `useClasses` exports all the CSS inline so that the output matches the look. If you want to prevent certain style from getting there, then there is an option for that: https://www.froala.com/wysiwyg-editor/docs/options#htmlIgnoreCSSProperties
