### ISSUE TITLE
Partial URL autolinking

### ISSUE THREAD

**Issue by philfreo** [froala/wysiwyg-editor#2276]
This seems to be a change in one of the more recent versions (we just upgraded and noticed it)

It's weird that if you type `https://close.io` that the `https://close` portion is autolinked without the .io portion until you hit space or enter after typing the TLD.

<img width="201" alt="screenshot 2017-10-24 15 12 13" src="https://user-images.githubusercontent.com/97612/31963162-cda1a9d6-b8cd-11e7-93d8-97e6bd0553c5.png">

I would probably expect that none of it is autolinked if you add a period but there isn't a TLD yet?

**Comment by stefanneculai** [comment]
Indeed, it's a recent change we've made and there were lots of discussions about how to implement it. In the end, we decided to go with to the way Apple Mail is handling it and that's because we wanted to have URLs such as `http://localhost` to be converted to links as well.

**Comment by philfreo** [comment]
But Apple Mail does _not_ work this way!

If I type a URL in Apple Mail it doesn't weirdly link a portion of the URL before I'm done typing it.

**Comment by stefanneculai** [comment]
Hm.. here is a GIF from Apple Mail. Maybe we're using a different version of MacOS? They convert text to link when a `.` is typed.

![apple mail](https://user-images.githubusercontent.com/637004/32001047-42b40d58-b9a1-11e7-82dc-9324fbd87e44.gif)

**Comment by philfreo** [comment]
I'm on Apple Mail Version 11.0 (3445.1.7) on macOS 10.13 (High Sierra).

However I found a setting that was disabled for me by default (Edit > Substitutions > Smart Links) that, once turned on, does behave like you say.

So fair enough... I can see the reasoning. Thanks.

**Comment by stefanneculai** [comment]
Maybe it worths adding an option for the URLs plugin which would select what to convert and what not. I am adding this as a `feature-request` and based on the interest from others we'll add it later on or not.

**Comment by brianarpie** [comment]
@stefanneculai We just ran into this issue and would love an option to change the default behavior!

**Comment by rogeru** [comment]
@stefanneculai same here. Did any of you look into adding such an option in the meantime?
