### ISSUE TITLE
froalaEditor.image.removed doesn't trigger when the image was replaced by the same one

### ISSUE THREAD

**Issue by hanbang-wang** [froala/wysiwyg-editor#2277]
##### Expected behavior.
froalaEditor.image.removed should be called when the image was replaced by the same one, or otherwise the froalaEditor.image.inserted should not be called.

##### Actual behavior.
When replaced with the same picture in the imageManager, froalaEditor.image.inserted was called but froalaEditor.image.removed was not called.

##### Steps to reproduce the problem.
> imageManager enabled

Upload a picture.
Click the picture and click the replace button.
Select the same picture that just uploaded.

##### OS.
Windows 10 

##### Browser.
Chrome 61.0.3163.100

**Comment by stefanneculai** [comment]
@hanbang-wang the `image.removed` is not being called because the image has not been removed. When you do this action, `image.replaced` is the only event which is called. We consider this as being the correct behavior.

**Comment by hanbang-wang** [comment]
You should consider this again since if it is not removed, it is not replaced, and vice versa.
