### ISSUE TITLE
Concerning closed issue 2275-> Froala export unneeded inline element when fullapge=true, useClasses= false 

### ISSUE THREAD

**Issue by Ohadcy** [froala/wysiwyg-editor#2278]
Hello,

Concerning the closed issue from yesterday:
https://github.com/froala/wysiwyg-editor/issues/2275
**stefanneculai commented 21 hours ago:
@Ohadcy useClasses exports all the CSS inline so that the output matches the look. If you want to prevent certain style from getting there, then there is an option for that: https://www.froala.com/wysiwyg-editor/docs/options#htmlIgnoreCSSProperties**

It's not solve the problem, in the htmlIgnoreCSSProperties we can define a list of  CSS properties to be ignored **BUT** this is not good CSS property is general, it might affect user's css properties.

See me screenshot if I will ignore BORDER property (this is the property that FROALA add from design), then it will also ignore customer's property and this is not good.
Let's take an example:
This is the code:
```
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <title></title>
    </head>
    <body>
        <span style="border:5px solid red">Important</span>
        <table>
            <tbody>
                <tr>
                    <td>This is a simple Text&nbsp;</td>
                </tr>
            </tbody>
        </table>
    </body>
</html>
```

Now in this situation Froala adding border to the "This is a simple Text", the border is from the design and not needed:![image](https://user-images.githubusercontent.com/18525400/31990354-899773be-b97d-11e7-8fd6-3e55b50d45bd.png)

 if i will define $('.selector').froalaEditor({
  htmlIgnoreCSSProperties: ['border']});

I will loose the all borders in the document.
This border should remain because it's from the original document:
`<span style="border:5px solid red">Important</span>`

Please advise

**Comment by stefanneculai** [comment]
@Ohadcy those rules that you get there inline for the table, are the ones from [froala_style.css file](https://github.com/froala/wysiwyg-editor/blob/master/css/froala_style.css#L29). The `useClasses` option set to false is designed to move all the CSS properties from the stylesheets inline so that the HTML output can be used in emails. 

If you don't want to have those rules in the output then we provide 2 methdos for that:
1) via `htmlIgnoreCSSProperties` 
2) by removing those rules from the CSS file directly

```css
.fr-view table {
  border: none;
  border-collapse: collapse;
  empty-cells: show;
  max-width: 100%;
}

.fr-view table td,
.fr-view table th {
  border: 1px solid #dddddd;
}
```
