### ISSUE TITLE
Ability to manage save

### ISSUE THREAD

**Issue by kenxle** [froala/wysiwyg-editor#228]
Amazing editor. Really a pleasure to work with. 

I need to trigger the content changed event to let the editor know that associated data has changed, and it should update it's state to dirty (and save after the interval). I tried calling the command below, without success. 

$(".selector").editable("triggerEvent", contentChanged, {}, false);

I can call save directly, but I would rather use contentChanged, since this waits for the autosave interval before saving. The associated data I have is typed, so saving on each keyup is excessive. Saving onChange is too intermittent. Tapping into this contentChanged event might be just right, and is cleaner conceptually.

Is this workflow supported?

Thanks,
Ken

**Comment by darkbluesun** [comment]
Is there seriously no way to access the 'dirty' property? Say for preventing the user leaving the page without saving? Forcing a save might not be what they want.
