### ISSUE TITLE
Table resize and table alignment is not working 

### ISSUE THREAD

**Issue by ShanmugaPriyanV** [froala/wysiwyg-editor#2280]
Expected behavior.

We are using the Froala editor in Modal.If we insert  a table  and reducing the size of table,then table size should realter as per the requirement

Actual behavior.

Table size cannot be altered in Modal.

OS.

Windows 7

Browser.

chrome 60.0.3112.113

**Comment by stefanneculai** [comment]
@ShanmugaPriyanV please make sure you are setting a higher `zIndex` option to the editor than the one of the modal. Also, make sure you don't have any translates: https://github.com/froala/wysiwyg-editor/blob/master/html/3rd-party/bootstrap/modal.html#L44
