### ISSUE TITLE
Image caption problems

### ISSUE THREAD

**Issue by igiz0l** [froala/wysiwyg-editor#2281]
##### Expected behavior.
Correctly working image plugin

##### Actual behavior.
A lot of strange stuff is happening, heres some of bugs:
http://www.giphy.com/gifs/l378fnEGebigrhOW4
<img src="https://media.giphy.com/media/l378fnEGebigrhOW4/giphy.gif" /> 
(after deleteing last char from the caption i was still pressing random char keys, with no effect, spacebar scrolls).

var error1 = "Uncaught TypeError: Cannot read property 'left' of undefined"; //string 13723 of froala_editor.js v2.7.0 

##### Steps to reproduce the problem.
a) deletes image while working with caption
1) insert an image
2) click image caption icon
3) press 'backspace' 2 times
after that you can try to type anything - and nothing appears in the editor, pressing 'spacebar' just scrolls the page down, pressing 'enter' can either cause a %error1% - or just adds newline (while cursor in invisible), and you cant type anything. And step 3 actually keeps some of the spans (.fr-img-caption, .fr-img-wrap and .fr-inner), but they cant be deleted w/o going into sourcecode.

b) Cmd+A not working
If you try to click on caption string and press "Cmd+A" - you'll get %error1% again.
Pressing Cmd+A twice selects all content (not only from the textarea - but also outside of it).

also, after 'a3' step it helps if you switch between windows or tabs (out and back to tab with froala instance), textarea gets focus and cursor becomes visible, you can type again - but Cmd+A not working still, image spans still in code without <img /> and cant be deleted.
##### OS.
mac OS Sierra 10.12.3

##### Browser.
61.0.3163.100

**Comment by stefanneculai** [comment]
@igiz0l this is already fixed on the Github master branch and will be included in release 2.7.1.

**Comment by igiz0l** [comment]
@stefanneculai Thanks for the response & release!
