### ISSUE TITLE
First time editor loses focus, blur event is not triggered

### ISSUE THREAD

**Issue by rickghome** [froala/wysiwyg-editor#2283]
##### Expected behavior.
Blur event should be triggered WHENEVER focus leaves the editor.

##### Actual behavior.
I have a webpage that contains multiple editor instances. All get initialized when the page is done loading. No problem editing content.  But the first time I click out of the editor frame, blur event is not triggered.

MacOS - chrome, firefox, safari, using CDN hosted demo version of froala. 

UPDATE: Actually, it seems that although the editor is initialized and activated for editing, it doesn't appear to be getting focus properly the first time.  In javascript console, body is reported at the activeElement the first time the editor has focus. Subsequent times, the editor gets the focus (activeElement == editor view) and blur works correctly.

WORKAROUND: I can force the .fr-element to have focus after the editor is initialized. In doing so, blur/focus events work correctly.

**Comment by stefanneculai** [comment]
@rickghome could you please make a jsFiddle?

**Comment by FWennerdahl** [comment]
@rickghome are you using the [angular-froala](https://github.com/froala/angular-froala) bindings? I was able to reproduce this with the angular bindings and logged it at https://github.com/froala/angular-froala/issues/159
