### ISSUE TITLE
Add an option for $.FE.NO_DELETE_TAGS

### ISSUE THREAD

**Issue by SeanKendle** [froala/wysiwyg-editor#2284]
Can you add a publicly accessible option for $.FE.NO_DELETE_TAGS?  I would like to add "DIV" to that list, because we're working on a more complex CMS using Froala, and that would help me out a ton.  Otherwise, I have to keep on adding that each time I update.

Thanks!

**Comment by stefanneculai** [comment]
@SeanKendle it is unlikely to make an option with it. However, you could easily change that by adding the following line of code just before initializing the editor.

```js
$.FE.NO_DELETE_TAGS.push('div')
```

**Comment by SeanKendle** [comment]
Thanks!
