### ISSUE TITLE
How to disable word-paste detected modal and default to use "Clean" 

### ISSUE THREAD

**Issue by rongo123** [froala/wysiwyg-editor#2285]
Hi guys, how do I disable the "Word Paste Detected" dialog and default to use "Clean"?
[https://i.stack.imgur.com/79EXH.png](url)

Tried setting wordPasteModal to false but still doesn't work.

Dialog is still showing.

**Comment by stefanneculai** [comment]
@rongo123 please make sure you are using the latest version 2.7.1.

**Comment by rongo123** [comment]
@stefanneculai 
Okay now the dialog can be disabled already. 

However the default is "Keep". 

How do I set it to do whatever it does for "Clean" by default?

**Comment by YoeriDeschrijver** [comment]
@stefanneculai  I have the same problem as @rongo123.
How can I set the default to "Clean" when the dialog is disabled?

**Comment by dianaprajescu** [comment]
If the dialog is disabled, the default action is to clean the styles. Please make sure you are using the latest version of the editor and let us know if you still have this problem.
