### ISSUE TITLE
Image will be auto resize after right click while doing image resize.

### ISSUE THREAD

**Issue by hnpkat** [froala/wysiwyg-editor#2286]
This bug related #2279   was fixed but it cause other issue:

Steps to reproduce the problem:

1. Add a image to editor.
2. Resize this image.
3. Still keep mouse down when resize , right click the mouse button .
4. Click to the image again and move mouse, just move do not click anything >> the image auto resize to mouse mover.

**Comment by hnpkat** [comment]
Hi Lucas, you can upgrade to v3 or v4, and https://github.com/froala/wysiwyg-editor/issues/2279 was also fixed. If you still using v2.6, edit the _exitEdit function into image.js for work around:

       function _exitEdit(force_exit) {
         if ($current_image && (_canExit() || force_exit === true)) {
           editor.toolbar.enable();
           $image_resizer.removeClass('fr-active');
           editor.popups.hideAll();
           $current_image = null;

           _unmarkExit();

           $handler = null;

           if ($overlay) {
             $overlay.hide();
           }
       }
    }

**Comment by lucas-contreras** [comment]
Hey @hnpkat , thanks for your answer, I will try the workaround you mentioned, although I have 4.0.9 froala version.
