### ISSUE TITLE
Rethink cookie usage

### ISSUE THREAD

**Issue by dwaxweiler** [froala/wysiwyg-editor#2288]
##### Expected behavior.
I want to integrate Froala in an `iframe sandbox="allow-scripts"` to make a website CSP-compliant.

##### Actual behavior.
Froala fails to load in this sandbox as it wants to set a cookie, which is not allowed. The error on the console: `Uncaught DOMException: Failed to set the 'cookie' property on 'Document': The document is sandboxed and lacks the 'allow-same-origin' flag.` in `froala_editor.pkgd.min.js:11`

Why is a cookie needed? Could you add an option do disable it?

##### Steps to reproduce the problem.

1. Create a page with the Froala editor.
2. Create a page with an `iframe sandbox="allow-scripts"` and include the first page.
3. Add the header `Content-Security-Policy: default-src 'self';` to the second page.
4. Load the second page.

##### Browser.
Google Chrome 62

**Comment by stefanneculai** [comment]
Thanks for reporting this, @dwaxweiler. For now, we're going to keep this the way it is implemented.  I added the label `feature-request` as well so that this is in our attention in new major editor versions.
