### ISSUE TITLE
Whitespaces in span, anchor or custom tags will be stripped when it's wrapped in span

### ISSUE THREAD

**Issue by zushenyan** [froala/wysiwyg-editor#2289]
[code pen example](https://codepen.io/zushenyan/pen/aLexLe)

I have a text like this:

```html
<div><span style="font-size:20px"><foobar>aaa</foobar> <foobar>bbb</foobar> <foobar>ccc</foobar> </span></div>
```

Notice there are several whitespaces which were intentionally placed between or after `<foobar>` tag.

When I set the Froala content with `$('textarea#froala-editor').froalaEditor('html.set', content);` or directly copy-paste it to code view and switch back to normal view, the whitespace between custom tags will be automatically stripped.

```html
<div><span style="font-size:20px"><foobar>aaa</foobar><foobar>bbb</foobar><foobar>ccc</foobar></span></div>
```

This also happens when whitespace are placed between `span` or `anchor` tags which are wrapped in another `span`. 

```html
<div><span style="font-size:20px"><span>aaa</span> <span>bbb</span> <span>ccc</span> </span></div>
```

Is there any way to override the default behavior in order to keep those whitespaces?

##### Expected behavior.
Keep whitespaces.
```html
<div><span style="font-size:20px"><foobar>aaa</foobar> <foobar>bbb</foobar> <foobar>ccc</foobar> </span></div>
```
![screen shot 2017-10-26 at 7 23 07 pm](https://user-images.githubusercontent.com/829686/32050375-364b15b4-ba16-11e7-8d0f-ae8bb12e16c5.png)

##### Actual behavior.
It trimmed the whitespaces.
```html
<div><span style="font-size:20px"><foobar>aaa</foobar><foobar>bbb</foobar><foobar>ccc</foobar></span></div>
```
![image](https://user-images.githubusercontent.com/829686/32050409-50d0ad5e-ba16-11e7-9232-f3a3a5fba022.png)

##### Steps to reproduce the problem.
Go to code pen example and click `get content` button for result.

##### OS.
Mac OS Sierra 10.12.6

##### Browser.
Chrome Version 61.0.3163.100 (64bit)

##### Froala version.
2.7.1

**Comment by stefanneculai** [comment]
@zushenyan the Code Pen is using version 2.6.0, not 2.7.1. It works fine in 2.7.1.
