### ISSUE TITLE
videoUpload option is not being respected when set to false

### ISSUE THREAD

**Issue by jkeatingatigloo** [froala/wysiwyg-editor#2292]
##### Expected behavior.
As per the docs setting `videoUpload` enables or disables video upload in the editor.  The expected behavior when setting the following (see below) is that you should not be able to upload a video via drag and drop OR the popup button.

```
$('.selector').froalaEditor({
  videoUpload: false
});

```
##### Actual behavior.
Setting the `videoUpload: false` still allows uploading of videos both via drag and drop and the popup button.

##### Steps to reproduce the problem.
1. Create a new editor
2. Set the `videoUpload` option to false for your editor
```
$('.selector').froalaEditor({
  videoUpload: false
});
```
3. Upload a video via drag/drop OR the popup button.

You can use this codepen to see the behavior 
https://codepen.io/anon/pen/VrZLJd

##### OS.
Windows

##### Browser.
Chrome

**Comment by stefanneculai** [comment]
@jkeatingatigloo please update to version `2.7.1` which introduced this feature.
