### ISSUE TITLE
Disable url automatic conversion

### ISSUE THREAD

**Issue by elodieirdor** [froala/wysiwyg-editor#2296]
##### Expected behavior.
When I type google.com, I do not want the url to be automatically converted. 

##### Actual behavior.
Type google.com then hit space, the url is converted.

Is there any option to deactivate this behaviour?

**Comment by stefanneculai** [comment]
@elodieirdor for that is best not to include the URLs plugin.

**Comment by ludowicus** [comment]
How do you disable it for the angular version?
