### ISSUE TITLE
Auto-linking doesn't quite work when typing a link manually

### ISSUE THREAD

**Issue by gabaum10** [froala/wysiwyg-editor#2297]
##### Expected behavior.
- Entering a link manually should  link the whole thing as you type, or not link it at all.

##### Actual behavior.
- As you type a URL manually, anything after .com doesn't become linked correctly.
![badlink](https://user-images.githubusercontent.com/1561245/32176255-8b2b8aba-bd5d-11e7-88fb-8d1dd6ea59df.PNG)

##### Steps to reproduce the problem.
- try to type http://google.com into an input.  Unless you hit a space, the .com at the end doesn't become part of the link.  This is particularly a problem if you have the enter key bound to perform an action that's not inserting a new line, such as submit.   In that case, it submits a broken link.
- Additionally, anything else you type after the .com is not linked either.  For example: http://google.com/test will not have the /test linked correctly.  

##### OS.
Windows 10

##### Browser.
Chrome Version 62.0.3202.75 (Official Build) (64-bit)

**Comment by stefanneculai** [comment]
@gabaum10 the text is being linked in case of 3 actions: dot key, space key or enter key. If you want to disable this feature, it is best to not include the URLs plugin.
