### ISSUE TITLE
Label on center align image option in imageAlign plugin shows "None"  

### ISSUE THREAD

**Issue by ayjee** [froala/wysiwyg-editor#2298]
##### Expected behavior.
Label on center align image option in imageAlign plugin should be "Align Center".

##### Actual behavior.
Label on center align image option in imageAlign plugin shows "None".  

##### Steps to reproduce the problem.
1. Navigate to an instance of the froala plugin with the `imageAlign`
 plugin, for example https://www.froala.com/wysiwyg-editor/examples/custom-image-button.
2. Click on the image.
3. Click the image align dropdown.
4. Notice that the center option has a label of "None" instead of "Align Center".

This appears to be attributed to this line in the code:
`a.FroalaEditor.RegisterCommand("imageAlign",{type:"dropdown",title:"Align",options:{left:"Align Left",justify:"None",right:"Align Right"}`

However, I am using the material icon set and to redefine this icon you must use the string "image-align-center" not something like "image-align-justify".  I am curious to see if maybe I am missing something or misunderstanding the use of this option, but to me it seems it would make more sense if it said "Align Center" and had a center aligned icon. 

<img width="350" alt="screen shot 2017-10-30 at 10 56 51 am" src="https://user-images.githubusercontent.com/8784165/32177595-18d134b6-bd61-11e7-9bb2-404444a07934.png"> 

##### OS.
MAC OS Sierra 10.12.6

##### Browser.
Google Chrome Version 61.0.3163.100 (Official Build) (64-bit)

**Comment by stefanneculai** [comment]
@ayjee that one is designed to show `None` because it inherits the alignment of the parent element. If you would like to change it to `Center`, then please add the following before initializing the editor:
```js
$.FroalaEditor.COMMANDS.imageAlign.options.justify = 'Center';
```

**Comment by ayjee** [comment]
@stefanneculai looking in to this deeper I do have a couple more follow up questions:
If you look at the latest code snippet below:

`
a.FE.DefineIcon("image-align",{NAME:"align-left"}),a.FE.DefineIcon("image-align-left",{NAME:"align-left"}),a.FE.DefineIcon("image-align-right",{NAME:"align-right"}),a.FE.DefineIcon("image-align-center",{NAME:"align-justify"}),a.FE.DefineIcon("imageAlign",{NAME:"align-justify"}),a.FE.RegisterCommand("imageAlign",{type:"dropdown",title:"Align",options:{left:"Align Left",center:"None",right:"Align Right"}
`

If `justify` is intended to inherit the alignment of the parent element, shouldn't there be a separate label option for `center` then?

If this is true, I would expect that the structure of the object would be something like this:

```
options : {
  left: "Align Left",
  center: "Align Center",
  right: "Align Right",
  justify: "None"
}
```
