### ISSUE TITLE
Safari Inline Toolbar Too Low when Selecting Entire line

### ISSUE THREAD

**Issue by bryannovoed** [froala/wysiwyg-editor#2300]
##### Expected behavior.
When an entire line is selected by double-clicking the line, the inline toolbar displays immediately below the selected line

##### Actual behavior.
When an entire line is selected by double-clicking the line, the inline toolbar displays too low
![screen shot 2017-10-31 at 1 38 12 pm](https://user-images.githubusercontent.com/8356554/32248020-8d15eb42-be41-11e7-8d7a-83f10515e206.png)

##### Steps to reproduce the problem.
1. Type some content like "line 1"
2. Press enter
3. Select the first line by double-clicking the space immediately to the right of "line 1"

##### OS.
macOS 10.12.6

##### Browser.
Safari 11.0

**Comment by stefanneculai** [comment]
We just checked it and the problem comes from the [getBoundingClientRect](https://developer.mozilla.org/en-US/docs/Web/API/Range/getBoundingClientRect) method. Unfortunately, in Safari there are few glitches like this one when the coordinates are not correct and we don't have a workaround for that.
