### ISSUE TITLE
Lists Plugin UL not adding new bullets on iOS

### ISSUE THREAD

**Issue by PvanHengel** [froala/wysiwyg-editor#2301]
##### Expected behavior.
When I press enter on an unordered list (bullet) i expect it to insert a new bullet, the same way it does with an ordered list.

##### Actual behavior.
When I press enter using iOS, it inserts a blank line.

##### Steps to reproduce the problem.
Run any demo from an iOS device, and insert an unordered list, enter some text, press enter

##### OS.
ios 10+

##### Browser.
n/a

**Comment by stefanneculai** [comment]
@PvanHengel could you please create a recording? I just tried to reproduce it without success.

**Comment by PvanHengel** [comment]
@stefanneculai Sorry I should have been more clear, this issue only occurs when an external keyboard is used, not the soft keyboard.  It is similar (but the opposite) to the issue reported https://github.com/froala/wysiwyg-editor/issues/2243

I think generally we need to make sure to handle both the soft and physical keyboard keystrokes, i'm not sure why they are different on iOS.  Perhaps whatever the solution was to 2243 can be used here as well.
