### ISSUE TITLE
Two conflicting aligns

### ISSUE THREAD

**Issue by igiz0l** [froala/wysiwyg-editor#2302]
If table was pasted from MS word - some tags (like &#60;p&#62;) inside of td's persist, and there is a possibility to align text inside td through both table popover and usual text toolbar. In that case there is a conflict: p is higher prioritized, and cant be overwritten by td settings
<img src="https://media.giphy.com/media/xT4AprgDNPlWKzEH8Q/giphy.gif" />

is it possible to set styles (e.g. text-align) both for td and nested tags?

**Comment by stefanneculai** [comment]
@igiz0l please send us a document you're pasting from. Thanks.

**Comment by igiz0l** [comment]
[paste_test.docx](https://github.com/froala/wysiwyg-editor/files/1434113/paste_test.docx)

**Comment by Snuff** [comment]
@stefanneculai Any updates?

**Comment by stefanneculai** [comment]
Related to #1527. Unfortunately, in the current version, we don't have a workaround for it. This problem would be addressed in V3.

**Comment by pnhughes** [comment]
@stefanneculai, any estimate on a V3 release?

**Comment by stefanneculai** [comment]
We don't think it's right to set expectations that may not be met due to shifting schedules. Therefore, we can't release any information about when it may become available.
