### ISSUE TITLE
draggable table

### ISSUE THREAD

**Issue by igiz0l** [froala/wysiwyg-editor#2303]
Is it possible to make table draggable just like image/video? #feature_request

**Comment by stefanneculai** [comment]
@igiz0l thanks for the `feature-request`.

**Comment by stefanneculai** [comment]
We've just put together a public roadmap with the most popular features. 😍 There you can vote your favorite one, provide feedback or make new suggestions: https://wysiwyg-editor-roadmap.froala.com/public.
