### ISSUE TITLE
Text selection artifacts remains after justify align

### ISSUE THREAD

**Issue by Brisstor** [froala/wysiwyg-editor#2304]
Hello, there is minor problem with text selection, there are visible selection remains after using of text alignment - justify - http://take.ms/3yhpk . I know that this is insignificant, but anyway, just wanted to let you know. 
P.S. btw, looks like the problem appears only on Windows OS, on Mac its ok. 

##### Expected behavior.
No artifacts after justify align

##### Actual behavior.
http://take.ms/3yhpk

##### Steps to reproduce the problem.
Paste text and align it with Align Justify

##### OS.
Windows 10

##### Browser.
Chrome 62

**Comment by stefanneculai** [comment]
Thanks for reporting it @Brisstor. We just checked it and it looks the problem is because of the way Chrome is rendering the selection. Unfortunately, we can't do anything about it.
