### ISSUE TITLE
persistent links

### ISSUE THREAD

**Issue by igiz0l** [froala/wysiwyg-editor#2305]
##### Expected behavior.
if
`pastePlain: true`
or
`pasteDeniedTags: ['a'], 
 pasteDeniedAttrs: ['href']`
expected to clean up all links from the content

##### Actual behavior.
If the name of the link contains protocol (http/https/ftp) - link is pasted as a link anyway

##### Steps to reproduce
<img src="https://media.giphy.com/media/l2ZDLYMOIeNqn2wWk/giphy.gif"/> 

[plain_paste_test.docx](https://github.com/froala/wysiwyg-editor/files/1434267/plain_paste_test.docx)

**Comment by stefanneculai** [comment]
@igiz0l the URLs plugin is designed to convert URLs on paste. If you don't want them, then it is best not to include the URLs plugin.
