### ISSUE TITLE
Pasting Word content into a numbered list in IE & Edge sometimes does nothing

### ISSUE THREAD

**Issue by briantaylorm** [froala/wysiwyg-editor#2306]
##### Expected behavior.
Pasting paragraph of text from Word into a numbered list should paste the text

##### Actual behavior.
If the pasted content from Word includes <p> tags, IE & Edge throw a javascript error. The js error is thrown where Froala tries to unwrap <p> tags from the Word content, saying the ':scope' selector is invalid syntax.

##### Steps to reproduce the problem.
Copy a paragraph from Word and paste it into a numbered list in IE or Edge

##### OS.
Windows 10

##### Browser.
IE 11, Edge

**Comment by stefanneculai** [comment]
@briantaylorm please make sure you are using the latest version 2.7.1.

**Comment by briantaylorm** [comment]
Hi Stefan, I’m almost positive this was on 2.7.1, but I’ll be traveling for the next several days, so will check when I get back.
