### ISSUE TITLE
Edge Browser hangs if you copy text with 2 or more empty paragraphs in the editor

### ISSUE THREAD

**Issue by briantaylorm** [froala/wysiwyg-editor#2307]
##### Expected behavior.
Copy a string of text and then paste it somewhere else in the editor

##### Actual behavior.
If there are 2 or more empty paragraphs in the editor, the browser hangs after you highlight text and then hit ctl-c.

##### Steps to reproduce the problem.
1. Enter the following block of text into an editor (reproducible on froala demo page):

Test

Test

Test

2. Highlight any of the text in the editor and hit ctl-c
3. The browser hangs until you switch windows (alt-tab)

##### OS.
Windows 10

##### Browser.
Edge

**Comment by briantaylorm** [comment]
This may just be a defect in Edge and there is nothing that can be done by Froala.

**Comment by stefanneculai** [comment]
@briantaylorm thanks for letting us know about that. We'll check it shortly.

**Comment by stefanneculai** [comment]
It's fixed on the current master branch.
