### ISSUE TITLE
Sticky toolbar not workings as expected on Chrome when Froala has a parent with transform CSS property 

### ISSUE THREAD

**Issue by nermand** [froala/wysiwyg-editor#2309]
##### Expected behavior.
When toolbar sticky is enabled (default option), it should float on top of the editor when a page is scrolled.

##### Actual behavior.
On Chrome it is misplaced. It's fixed position got screwed due to having a parent with transform CSS property,  so it is not relative to the viewport anymore.
Seems to be working as expected in Firefox.

##### Steps to reproduce the problem.
https://codepen.io/nermand/pen/MOKLLQ
Please, open a forked codepen example of using the sticky toolbar and scroll a bit.
I just extended it with a parent element which has transform property set.

##### OS.
Windows 8, v6.3

##### Browser.
Google Chrome, Version 61.0.3163.100 (Official Build) (64-bit)

**Comment by stefanneculai** [comment]
It is mainly a similar to #2212. I am closing this, for now, please follow the other issue for updates.
