### ISSUE TITLE
editable is not a function

### ISSUE THREAD

**Issue by ylebarch** [froala/wysiwyg-editor#231]
Hello,
 i have a js error "TypeError: $(...).editable is not a function". Editor not appear, it's linked ?

I use Firefox (latest version) and Wamp.

In chrome, i have an other problem, but i think that you don't concerned ^^  
This error "Not allowed to load local resource" for each include file.

Thanks

**Comment by thomas-boll** [comment]
I followed the quickstart (copy paste into header and body) and also get this problem.
I really would like to know the cause for this (js and everything is included like in quickstart as I said).

Does it interfere with other js/css maybe as I use laravel and gumby?

**Comment by echazen** [comment]
Having the same issue.  Is there no support even though I paid for this?

**Comment by stefanneculai** [comment]
@thomas-boll If you get this error, then it is most likely because you're including the editor JS files after initializing the instance. The JS files should be included before initializing the editor.

@echazen If you have a license for the editor that includes support, you can [contact us](https://www.froala.com/contact) at anytime through our website.

**Comment by connect-technologies** [comment]
... or you included v1 and initialized it with the v2 call. Vor vice versa

**Comment by echazen** [comment]
The js files are being included before initializing the instance. Yes, I 
do have a license and I have contacted you guys.  Just haven't heard 
back yet.

Jason Ho-Ching
Creative Director
www.echazen.com
480.355.1434

**Comment by echazen** [comment]
Nope.  I only downloaded v2.

Jason Ho-Ching
Creative Director
www.echazen.com
480.355.1434

**Comment by davidsneal** [comment]
Also having this issue. I copied the example, downloaded the latest version and am getting the error. All files mentioned in the example have been included successfully, in the order specified - https://www.froala.com/wysiwyg-editor/docs

**Comment by connect-technologies** [comment]
You know your posted example file is for v1? Do you really include v1?
If you habe the JS from here, please take a look at my earlier post.

**Comment by connect-technologies** [comment]
Sorry, here is the link https://www.froala.com/wysiwyg-editor/v2.0/docs/migrate-from-v1

**Comment by davidsneal** [comment]
Thanks for this. It wasn't clear that I was looking at v1, nor that v2 was available/different when viewing those docs.

Looks like I went to the v1 docs via links on the homepage - features, innovation and examples all lead you through to v1, then the menu items all stick within v1 too.

**Comment by echazen** [comment]
I found out that the problem was with the documentation.  They had old 
documentation on the website.  Use the documentation that came with the 
download instead.

Jason Ho-Ching
Creative Director
www.echazen.com
480.355.1434

**Comment by stefanneculai** [comment]
The documentation for V2 is available on https://www.froala.com/wysiwyg-editor/v2.0/docs

**Comment by thomas-boll** [comment]
@echazen Thanks but sorry. That took too long. I am already using another editor instead.
