### ISSUE TITLE
Enabling CodeMirror documentation

### ISSUE THREAD

**Issue by Danack** [froala/wysiwyg-editor#2310]
##### Expected behavior.
Documentation says how to enable CodeMirror correctly

##### Actual behavior.
Documentation doesn't give steps to enable code mirror correctly.

##### Steps to reproduce the problem.
Go to https://www.froala.com/wysiwyg-editor/docs/options#codeMirror and read the documentation.

The docs says to set the option codeMirror to true, to enable CodeMirror.

This didn't work for us, as Froala editor didn't pickup CodeMirror automatically.

Setting `codeMirror: window.CodeMirror` i.e. passing in the CodeMirror object as the value seems to make it work.

##### OS.
N/A

##### Browser.
N/A

Apologies if this in the wrong repo - I couldn't see a docs repo.

**Comment by jaimestuardo** [comment]
I tried it and CodeMirror works only by showing line numbers..... HTML code is not actually colored.
