### ISSUE TITLE
htmlAllowedEmptyTags has no effect on nested custom elements

### ISSUE THREAD

**Issue by bcanseco** [froala/wysiwyg-editor#2311]
##### Expected behavior.
Setting `htmlAllowedEmptyTags` to `['content']` will prevent the editor from removing a `<content>` tag inside a `<p>` tag when the `<content>` becomes empty.

##### Actual behavior.
The editor still removes the `<content>` element when it becomes empty.

##### Steps to reproduce the problem.
1. Open this codepen: https://codepen.io/anon/pen/rYxXNN
2. Click after the period of the text inside the editor.
3. Hold backspace until the text is gone.
4. Inspect the editor and notice that the `<content>` element is now gone.

##### OS.
Windows 10 64bit

##### Browser.
Chrome v62.0.3202.75

**Comment by stefanneculai** [comment]
Probably you would want something like this: https://codepen.io/anon/pen/QONLjj. `htmlAllowedEmptyTags` is more for allowing empty blocks in the editor, not for keeping them there when you backspace.
