### ISSUE TITLE
Blur event is fired when selecting table cells

### ISSUE THREAD

**Issue by Adrian-Aiken** [froala/wysiwyg-editor#2312]
##### Expected behavior.
When table cells are selected in the editor it should keep focus within the editor

##### Actual behavior.
When no cells were already selected, a blur event ('froalaEditor.blur') is fired. Any methods watching for the blur event fire.

##### Steps to reproduce the problem.
Create a table within froala. Without any table cells selected, click and drag to select multiple cells. The blur event will fire.

(https://codepen.io/anon/pen/wPGzOb?editors=1111)

##### OS.
Windows 10 (10.0.14393 Build 14393)

##### Browser.
Google Chrome, Version 32.0.3202.75

**Comment by stefanneculai** [comment]
This should be fixed on the current Github master. If you still have the problem just let us know.
