### ISSUE TITLE
Placeholder styling modified when text is deleted by backspace

### ISSUE THREAD

**Issue by bryannovoed** [froala/wysiwyg-editor#2313]
##### Expected behavior.
Placeholder text styling is preserved when removing all content by backspace.

##### Actual behavior.
Placeholder text styling copies the style of text removed by backspace.
![placeholder_backspace](https://user-images.githubusercontent.com/8356554/32473780-12109d20-c31e-11e7-9c6f-83c5246ec3c5.gif)

##### Steps to reproduce the problem.
1. from an empty, type some text e.g."asdf"
2. select a paragraph style or paragraph format
3. select cursor at the end of the text
4. delete all the characters by pressing backspace multiple times

##### OS.
macOS 10.12.6

##### Browser.
Version 61.0.3163.100 (Official Build) (64-bit)

**Comment by bryannovoed** [comment]
still seeing this on 2.7.2
![placeholder](https://user-images.githubusercontent.com/8356554/33298305-5930ee8a-d39a-11e7-9d6c-9ddd0ae3bba4.gif)

**Comment by stefanneculai** [comment]
@bryannovoed the current behavior is the correct one. When you delete the last character, the formatting is kept. If you backspace once more, it is removed.

**Comment by smoockpp** [comment]
Hi.
I'm using angular-froala-wysiwyg 2.7.3 and I can also see it. How I can prevent this from happening?
