### ISSUE TITLE
froala in popup : image overlay in background window

### ISSUE THREAD

**Issue by javeriaanwer** [froala/wysiwyg-editor#2316]
##### Expected behavior.
on clicking on image in froala, image options are open in background window 
![image error](https://user-images.githubusercontent.com/25203829/32480841-7e2662b2-c3b2-11e7-9f0e-163547e7c9a7.png)

##### Actual behavior.
Froala editor is open in popup, on clicking on image, its options should open in froala editor.

##### Steps to reproduce the problem.
click on image in froala editor

##### OS.
windows 10

##### Browser.
any

**Comment by stefanneculai** [comment]
It looks like you're using the editor inside a modal. Please make sure you set a higher zIndex option for the editor than the modal.

**Comment by javeriaanwer** [comment]
z-index is high in editor

**Comment by javeriaanwer** [comment]
how can I increase z-index of overlay through jquery.

**Comment by stefanneculai** [comment]
@javeriaanwer do you think you could make a jsFiddle to highlight this?

**Comment by javeriaanwer** [comment]
here is the jsfiddle. 

http://jsfiddle.net/JaveriaAnwer/ubdmyoep/43/

We are opening froala editor in kendo window. Image edit popup of z-index is set to 5 which is lower than kendo window z-index. We can not disturb any styling in existing UI. the only option is to chnage z-index of Image edit popup. how can we achieve this?    

![image](https://user-images.githubusercontent.com/25203829/36887014-0b351520-1de7-11e8-9517-dd5f56d6cd30.png)

**Comment by stefanneculai** [comment]
There are 2 things you should set:
```js
zIndex: 15000,
scrollableContainer: '#window1'
```
