### ISSUE TITLE
2.7.1 Adds empty p tag to the body

### ISSUE THREAD

**Issue by michaelkoper** [froala/wysiwyg-editor#2318]
2.7.0 works fine but 2.7.1 gives me empty tags when I initialize froalaEditor on an already populated textarea.

The editor adds an empty p tag to all my text fields.

Original textfield:

```
<p>lorem ipsum</p>
```

This is what 2.7.1 gives me (2.7.0 works fine)

```
<p><br/></p><p>lorem ipsum</p>
```
##### Plugins I use:

fullscreen
image
link
lists
paragraph_format
table
video

##### OS.
OSX El Capitan, 10.11.6

##### Browser.
Chrome Version 61.0.3163.100 (Official Build) (64-bit)

**Comment by stefanneculai** [comment]
@michaelkoper could you create a jsFiddle or codePen? Thanks.

**Comment by michaelkoper** [comment]
Sure, Here it is: https://jsfiddle.net/6Lcmxdb0/

You can see <p><br/></p> when you inspect the content in the results.
