### ISSUE TITLE
If an error occurs on image upload, a broken "blob" image is added to the html

### ISSUE THREAD

**Issue by Medo42** [froala/wysiwyg-editor#2321]
##### Expected behavior.
If the upload fails, the html should be left unchanged.

##### Actual behavior.
If the upload fails, an image tag like the following is added to the html (visible in the code view and the output html):

    <img src="blob:https://www.froala.com/761b634c-7e1b-4f20-a3f3-bf752cd21489" style="width: 300px;" class="fr-fic fr-dib">

##### Steps to reproduce the problem.
Attempt to upload a broken image by drag and drop, e.g. in the basic froala demo. You can just rename some random file to an image extension to get a broken image that makes the upload fail. Inspect the html in the code view.

##### OS.
Ubuntu 16.04 (Xenial), 64-bit

##### Browser.
Chromium 61.0.3163.100, Firefox 56.0

**Comment by dswitzer** [comment]
While you'd lose the CORS proxy, I suspect you can avoid this behavior by setting the `imageUploadRemoteUrls` option to false.

**Comment by Medo42** [comment]
I just tried that, it doesn't see to make a difference.

**Comment by stefanneculai** [comment]
@Medo42 please send us the image you're trying to upload so that we can check this. Thank you.

**Comment by Medo42** [comment]
Hi. You can use the following file to test it. Just drag and drop it from your filesystem to the editor on this page: https://www.froala.com/wysiwyg-editor

![blah](https://user-images.githubusercontent.com/339540/32520909-f52cdd0a-c411-11e7-95bf-ae385d5fb78d.jpg)

**Comment by sodacrunch** [comment]
The fix did not work for me, still getting a broken blob image

**Comment by ThunderSpoon** [comment]
I have got Failed to load resource: The operation couldn't be completed.(WebKitBlobResource error 1.) Can you please explain why this happening?

**Comment by Cokser** [comment]
@sodacrunch did you fix this issue?
