### ISSUE TITLE
Align of image caption

### ISSUE THREAD

**Issue by igiz0l** [froala/wysiwyg-editor#2322]
##### Expected behavior.
Expected to be able to align text inside of image caption

##### Actual behavior.
<img src="https://media.giphy.com/media/26u40C5nG5vsY5Ubu/giphy.gif"/>
selection drops on 'align' dropdown option hovered

##### Steps to reproduce the problem.
1) insert image, fill in caption
2) select section of caption or all caption
3) try to align it with a button from toolbar

##### OS.
mac os x 10.12.3

##### Browser.
chrome  62.0.3202.75

**Comment by Snuff** [comment]
Hey @stefanneculai,

Are you going to fix this bug in the upcoming release?

**Comment by SeanKendle** [comment]
I noticed this same problem because I created my own plugins that use divs, and this problem was happening.  I was able to change some code in the froala.js file to fix my particular problem.  @stefanneculai, if you're interested in seeing my fix, it has to do with setting and loading the selection.

Happens on Chrome.

**Comment by largeden** [comment]
Hi,
I have found the cause of this problem. (It may have been solved by @stefanneculai  already.)
This problem will occur on all browsers except mozilla.

```javascript
// image.js
function _syncImages (loaded) {
//...
    if (c_images[i].parentNode && c_images[i].parentNode.parentNode && editor.node.hasClass(c_images[i].parentNode.parentNode, 'fr-img-caption')) {
      var p_node = c_images[i].parentNode.parentNode;

      if (!editor.browser.mozilla) { <- here
        p_node.setAttribute('contenteditable', false);
      }

      p_node.setAttribute('draggable', false);
      p_node.classList.add('fr-draggable');
//...
}
```

**Comment by igiz0l** [comment]
Hello. Yep, but only particularly.
Unnecessary image align was fixed in 2.7.2, but we still can't align image.
More than that, if we play with aligning - at some point image caption falls out of '.fr-img-caption' element, as here <br/><img src="https://media.giphy.com/media/l49JFScIhFl3ITlCg/giphy.gif"/>

**Comment by largeden** [comment]
![fr-img-caption](https://user-images.githubusercontent.com/5575931/34215390-8dc5a7a2-e5e8-11e7-9d84-d44cf8a99147.gif)

I have found a definite cause.

This problem occurs when the parent has `contenteditable = "false"` and the child has `contenteditable = "true"`.
image.js treats the parent as `contenteditable = "false"` in non-Firefox browsers.

**Comment by Snuff** [comment]
@stefanneculai Any news?

**Comment by largeden** [comment]
@igiz0l 
The symptoms of the picture are not the bugs I mentioned. It's another bug.
We have confirmed that this symptom occurs in Windows environment.
Symptoms were not found on the Mac.

**Comment by largeden** [comment]
@igiz0l @stefanneculai 

hello.
I have found the cause of the align problem.
```javascript
//plugins/align.js
  $.FE.PLUGINS.align = function (editor) {
    function apply (val) {
//...
      // Wrap.
      editor.selection.save();
      editor.html.wrap(true, true, true, true); // <- here
      editor.selection.restore();
//...
```
The fourth value is wrap processing of `.fr-inner`
For the caption, the fourth value should be false to avoid the problem.
Exception handling of the `_wrap()` is required.
```javascript
    /**
     * Wrap the direct content inside the default block tag.
     */
    function _wrap (temp, tables, blockquote, inner) {
//...
      if (inner) {
        _wrapElements(editor.el.querySelectorAll('.fr-inner:not(span)'), temp);
      }
//..
    }
```

**Comment by stefanneculai** [comment]
@largeden thanks for the suggestions both here and by email. We're going to review them shortly and make some changes to the alignment of the caption.
