### ISSUE TITLE
URL plugin: link not converted on android chrome

### ISSUE THREAD

**Issue by bryannovoed** [froala/wysiwyg-editor#2325]
##### Expected behavior.
Texts that look like links are automatically converted to links.

##### Actual behavior.
Texts that look like links are not automatically converted to links.
![screenshot_20171107-102456](https://user-images.githubusercontent.com/8356554/32513466-248bb0a2-c3af-11e7-8b3a-8d1f9f67f900.png)

##### Steps to reproduce the problem.
1. from a clean slate type 'www.google.com' and then a space

##### OS.
Android 6.0.1

##### Browser.
Chrome b61.0

**Comment by stefanneculai** [comment]
Unfortunately, because of the way we get the input from the browser on Android browsers this feature is unavailable for now on Android.
