### ISSUE TITLE
Mobile Inline Toolbar present after cursor selection changed

### ISSUE THREAD

**Issue by bryannovoed** [froala/wysiwyg-editor#2327]
##### Expected behavior.
After selection, clicking on another text should close the inline toolbar(like on desktop).

##### Actual behavior.
After selection, clicking on another text, the inline toolbar continues to show at the original position

##### Steps to reproduce the problem.
1. Enable inline toolbar with color selection
2. Select some text
3. Change the color to yellow
4. Move cursor to another portion of the text that is not part of the original selection
![screenshot_20171107-154513](https://user-images.githubusercontent.com/8356554/32528718-6c23a3b8-c3e9-11e7-9c86-a10de710dabd.png)

##### OS.
Android 6.0.1
Similar issue is seen on iOS

##### Browser.
Chrome b61.0

**Comment by largeden** [comment]
@stefanneculai 

This is caused by the following code.
I was able to fix the problem by removing the code below.
However, if you remove the code, the toolbar will not appear on PC mode.

```javascript
// froala_editor.js
function _initInlineBehavior () {
//...
    editor.events.on('window.mouseup', showInline); <- here
//...
}
```

#### Solution
```javascript
// froala_editor.js
function _initInlineBehavior () {
//...
    if (!editor.helpers.isMobile()) {
      editor.events.on('window.mouseup', showInline);
    }
//...
}
```

**Comment by stefanneculai** [comment]
@largeden thanks for the suggestion. We're going to check it in the upcoming days.
