### ISSUE TITLE
The editor gets destroyed after clicking multiple times on the bold, italic and underline buttons

### ISSUE THREAD

**Issue by thexpand** [froala/wysiwyg-editor#2328]
##### Expected behavior.
The Froala editor remains.

##### Actual behavior.
The Froala editor gets destroyed.

##### Steps to reproduce the problem.
1. Initialize a new Froala editor on a textarea.
2. Click the "Bold", "Italic" or "Underline" buttons several times until the editor destroys itself.
3. The editor gets destroyed and the froalaEditor.destroy event is triggered.

##### OS.
Ubuntu 17.04

##### Browser.
Google Chrome, Version 61.0.3163.100 (Official Build)

**Comment by stefanneculai** [comment]
@thexpand this is a problem from your implementation. Please contact tech support via https://www.froala.com/wysiwyg-editor/contact.

**Comment by thexpand** [comment]
@stefanneculai Why the implementation? I'm calling the `froalaEditor()` method on the textarea, without any additional options.
