### ISSUE TITLE
videoAllowedTypes not working

### ISSUE THREAD

**Issue by michaelkoper** [froala/wysiwyg-editor#2329]
##### Expected behavior.
To not return an error when uploading video with an extension that is present in videoAllowedTypes.

##### Actual behavior.
Only default video types `['mp4', 'webm', 'ogg']` are allowed.

##### Steps to reproduce the problem.
Fiddle: https://jsfiddle.net/ef2ngqa3/

Example mov file: http://techslides.com/demos/samples/sample.mov

Try to upload the video, you will see an error in the console (and in the interface). Btw, `froalaEditor.video.error` is not present in the [documentation](https://www.froala.com/wysiwyg-editor/docs/events) Just the codeError event. You want me to make a separate issue? 

##### OS.
OSX El Capitan

##### Browser.
Version 62.0.3202.89 (Official Build) (64-bit)

**Comment by stefanneculai** [comment]
The error is coming from the fact that the editor is using the HTML5 `video` tag. At this moment, `mov` is not a supported video type by the browsers: https://www.w3schools.com/html/html5_video.asp.

**Comment by jackyhuynh0407** [comment]
I found solution to upload video form iphone. Just add videoAllowedTypes: ['quicktime']. And you can upload .mov video form your iphone as html5 video.

**Comment by nareshdasireddi** [comment]
> I found solution to upload video form iphone. Just add videoAllowedTypes: ['quicktime']. And you can upload .mov video form your iphone as html5 video.

Thnaks @jackyhuynh0407 .its helped me alot
