### ISSUE TITLE
UseClasses: false but allow classes from stylesheets

### ISSUE THREAD

**Issue by swiftMessenger** [froala/wysiwyg-editor#2334]
##### Desired Behavior.
I do not want any Froala classes to be saved in the output from the editor, but I DO want users to be able to add classes from their own stylesheets.

There is only 1 style-related configuration option right now which controls both of those concerns. When useClasses = true, images and videos in particular add a number of classes to the output. When useClasses = false, any stylesheet-defined classes are stripped from the output and replaced with the styles from the stylesheet.

It would be nice to have a separate configuration option to allow or prevent removing classnames that are defined in the stylesheet. Maybe something like "preserveStylesheetClasses".

##### Additional Information
I am displaying the Froala editor in a completely separate environment from where the content is displayed. Additionally, and by design, I do not have control over what stylesheets are loaded on the page where the content is displayed - where the Froala stylesheet is typically not loaded.

My users do have control over what stylesheets are loaded on the page that displays the content, as well as the ability to select stylesheets to be used in the Froala preview area (and therefore what classes are available to be applied to HTML elements inside Froala). This is accomplished by way of a script that scans stylesheets for styles that are applicable to elements and dynamically updating the configuration before initializing Froala.

##### Workaround
I am currently working around the issue by setting useClasses: true and "hacking" several plugins to remove their use of classes - which is prone to errors and omissions and is painful every time that I update Froala to take advantage of new features, improvements, and bugfixes.

##### Configuration
...
iframe: true,
iframeStyleFiles: ['/path-to-froala-stylesheet', '/path-to-custom-stylesheets'],
imageStyles: [{image styles configuration}],
inlineStyles: [{inline styles configuration}],
linkStyles: [{link styles configuration}],
paragraphStyles: [{paragraph styles configuration}],
etc...
imageDefaultDisplay: false,
imageDefaultAlign: false,
imageOutputSize: false,
...

**Comment by stefanneculai** [comment]
Thanks for your suggestion @swiftMessenger. I marked this as a `feature-request` and based on the feedback from other users for this, it would be added or not.

**Comment by xfstef** [comment]
Hello.
Has this feature been implemented? I'm having the same issue with the useClasses option. We can't remove it because image styling won't work but we can't keep it because it overrides our classes.

Any other ideas or hints would be helpful!

Multumesc!

**Comment by hchiam** [comment]
> Hello. Has this feature been implemented? I'm having the same issue with the useClasses option. We can't remove it because image styling won't work but we can't keep it because it overrides our classes.
> 
> Any other ideas or hints would be helpful!
> 
> Multumesc!

me too. we can't use `useClasses: false` because then styles that relied on classes don't work anymore, and removing `useClasses: false` doesn't work either because some previews weren't resolving correctly when using classes (in an `<iframe>`)

please advise
vă rog să informați :)
