### ISSUE TITLE
IE11: paste link then undo immediately, cursor in wrong location

### ISSUE THREAD

**Issue by bryannovoed** [froala/wysiwyg-editor#2335]
##### Expected behavior.
After pasting a link, then immediately undo by ctrl-z, the blinking cursor moves to the proper position where the next text should go.

##### Actual behavior.
After pasting a link, then immediately undo by ctrl-z, the cursor remains at the same position.

##### Steps to reproduce the problem.
1. paste "https://www.froala.com/wysiwyg-editor"
2. undo by typing "ctrl-z"
![ie_cp_undo](https://user-images.githubusercontent.com/8356554/32627234-9b0445b2-c546-11e7-8ad1-e6277de5c61e.gif)

##### OS.
Windows 8.1

##### Browser.
IE11

**Comment by stefanneculai** [comment]
@bryannovoed this looks like a browser rendering issue of the cursor. Unfortunately, there is not too much we can do from our side.
