### ISSUE TITLE
Clear Formatting button does not clear formatting on ul element

### ISSUE THREAD

**Issue by mukk85** [froala/wysiwyg-editor#2336]
##### Expected behavior.
Clear formatting will remove the style tag from the root ul element

##### Actual behavior.
style element remains after clear formatting is pressed

##### Steps to reproduce the problem.
Example HTML:
```<p><strong style="box-sizing: border-box; font-weight: 700; line-height: inherit;"><u style="box-sizing: border-box;">Waterproofing:</u></strong></p><ul style='box-sizing: border-box; margin: 0px 0px 1.125rem 1.1rem; padding: 0px; font-family: Arial, "Helvetica Neue", Helvetica, sans-serif; font-size: 12px; line-height: 1.4; list-style-position: outside; color: rgb(0, 0, 0); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; background-color: rgb(255, 255, 255);'><li style="box-sizing: border-box; margin: 0px; padding: 0px;">GL 5-9 waterproofing started Monday Nov 6th and will be ready for spray Thursday Nov 9th, 2017</li><li style="box-sizing: border-box; margin: 0px; padding: 0px;">Boom lifts to be removed from site Friday Nov 10th, 2017</li></ul>```

Clear formatting will result in:
```<p>Waterproofing:</p><ul style='box-sizing: border-box; margin: 0px 0px 1.125rem 1.1rem; padding: 0px; font-family: Arial, "Helvetica Neue", Helvetica, sans-serif; font-size: 12px; line-height: 1.4; list-style-position: outside; color: rgb(0, 0, 0); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; background-color: rgb(255, 255, 255);'><li>GL 5-9 waterproofing started Monday Nov 6th and will be ready for spray Thursday Nov 9th, 2017</li><li>Boom lifts to be removed from site Friday Nov 10th, 2017</li></ul>```

##### OS.
OSX/Windows

##### Browser.
Chrome Version 61.0.3163.100 (Official Build) (64-bit)

**Comment by stefanneculai** [comment]
@mukk85 clear formatting is designed to remove the inline style, but not from the block tags, such as `P`, `H1`, `H2`, 'LI', 'Ol', 'UL', etc.

**Comment by mukk85** [comment]
That seems odd... so it only clears formatting on span? Is there another button to remove all font and colour inline styles?

**Comment by stefanneculai** [comment]
At this moment, there is no built-in feature for that. Yes, it removes the inline formattings such as span, strong, a, etc.

**Comment by mukk85** [comment]
So unless you know how to code you cannot remove the styles placed on a block level element?
