### ISSUE TITLE
Froala table resize on bootstrap modal

### ISSUE THREAD

**Issue by nainashukla3300** [froala/wysiwyg-editor#2337]
Expected behavior.

Resizing table with in Bootstrap Modal.

Actual behaviour
when click on insert table not able to resize table. While doing it on normal page its working but not on bootstrap modal

##### Steps to reproduce the problem.
Open a bootstrap modal and add a  froala editor then resize table.

##### OS.
Windows 7 

##### Browser.
Google Chrome

![image](https://user-images.githubusercontent.com/18672959/32645198-0f0b0430-c60c-11e7-8830-d336f915a0be.png)

**Comment by stefanneculai** [comment]
@nainashukla3300 please make sure you implement it as described in our examples: https://github.com/froala/wysiwyg-editor/blob/master/html/3rd-party/bootstrap/modal.html#L44.
