### ISSUE TITLE
Copy & paste converts all visual styling into inline styling

### ISSUE THREAD

**Issue by bryannovoed** [froala/wysiwyg-editor#2338]
##### Expected behavior.
When copy and pasting simple text, if copying pasting in the same browser, no additional inline styles are added. This seems to work in the non-minified version.

##### Actual behavior.
When copy and pasting simple text, all visual styles are converted into inline styling.

##### Steps to reproduce the problem.
1. Go to https://www.froala.com/wysiwyg-editor
2. Select "capabilities"
3. Copy by pressing ctrl-c
4. Go to next line by going to the end of the line and pressing enter
5. Paste by pressing ctrl-v
![chrome_cp_paste](https://user-images.githubusercontent.com/8356554/32646413-4f74abc2-c5a1-11e7-8d52-750084f5a3bd.gif)

##### OS.
macOS 10.12

##### Browser.
Chrome 62

**Comment by jamesmoss** [comment]
@stefanneculai This is a blocker for us right now. Any idea how long before this lands in a release?

**Comment by stefanneculai** [comment]
@jamesmoss it will be released in a couple of days.
