### ISSUE TITLE
"html.set" file protocol - file://

### ISSUE THREAD

**Issue by beljand** [froala/wysiwyg-editor#2340]
##### Expected behaviour.
When trying to set html content, img tags should not get stripped out if they start with "file://" (file protocol)

##### Actual behavior.
Img tags are stripped if they include (start) with "file://"

##### Steps to reproduce the problem.
Try to set html with an image that points to a local image on your machine

##### OS.
macOS/Win/all

##### Browser.
Chrome / Electron

**Comment by stefanneculai** [comment]
Image loaded by `file://` protocol are controlled by the following option which by default is `false`: https://www.froala.com/wysiwyg-editor/docs/options#pasteAllowLocalImages
