### ISSUE TITLE
Pasting text from Word

### ISSUE THREAD

**Issue by jamesatplebble** [froala/wysiwyg-editor#2341]
##### Expected behavior.
You can copy/paste text from a Word document into the rich text editor.

##### Actual behavior.
Pasting creates an image which is then uploaded to the rich text editor.

##### Steps to reproduce the problem.
Screen recording: https://vimeo.com/242312257 (and attached)
[Screen Recording 2.mov.zip](https://github.com/froala/wysiwyg-editor/files/1462853/Screen.Recording.2.mov.zip)

##### OS.
Mac OS X 10.7.5

##### Browser.
Chrome v 49.0.2623.112 (64-bit)

**Comment by stefanneculai** [comment]
@jamesatplebble please send us the document you're pasting from. Thanks in advance.

**Comment by dswitzer** [comment]
While this might not be the same issue, 

I've seen this happen w/IE11 when the Word is using an object for the layout. It renders the Word object as an image.

Here's an example of that behavior.

[Text Pasted as Image in IE11.docx](https://github.com/froala/wysiwyg-editor/files/1475354/Text.Pasted.as.Image.in.IE11.docx)

**Comment by jamesatplebble** [comment]
Hi Dan

Yeah, this is just straight text, no object. I'm also using Chrome, not
IE11.

Thanks

James

**Comment by stefanneculai** [comment]
@jamesatplebble what Microsoft Word version are you using?

**Comment by stefanneculai** [comment]
@dswitzer unfortunately, this is the way we're getting the data in the clipboard. 

@jamesatplebble I'm closing this due to lack of response. Would be happy to check it if you could send us the doc you're pasting from. Thanks.
