### ISSUE TITLE
Video embeds (ex. Youtube) strip https:// protocol

### ISSUE THREAD

**Issue by drampelt** [froala/wysiwyg-editor#2344]
##### Expected behavior.
`<iframe>`s for embedded videos should have a protocol for the URL in the `src` attribute. 

##### Actual behavior.
When pasting in a Youtube link to embed for example, the `https` in the URL is removed so the `src` attribute starts with `//`

##### Steps to reproduce the problem.
Embed a Youtube video by provided the link to the video (ex. https://www.youtube.com/watch?v=OvVKnC6gGtg), the generated `<iframe>` will have no URL protocol

##### OS.
All

##### Browser.
All

---

HTML generated from Froala editors on our website is displayed in a WebView on our mobile apps. On both iOS and Android these are served from `file://` URLs, so any image or video that just uses `//` for the protocol defaults to `file://` and as such Youtube videos do not load in our apps.

Is there a particular reason for stripping the protocol from embedded videos? Youtube actually uses HSTS to enforce the HTTPS protocol, so as far as I can tell there wouldn't be any downside to using `https://` instead.

We have tried replacing the `//` in `src` attributes with `https://` to work around the problem, but that can break some images hosted on external webservers that do not support HTTPS. Additionally we could replace it with just `http://` and let the webserver redirect to HTTPS if necessary, but as our website is served over HTTPS most browsers will not downgrade protocols to display insecure `<iframe>`s and then video embeds would not work on our website.

**Comment by stefanneculai** [comment]
Last commit adds the `https://` protocol by default.
