### ISSUE TITLE
Color Picker Behavior

### ISSUE THREAD

**Issue by SeanKendle** [froala/wysiwyg-editor#2346]
##### Expected behavior.
Clicking OK on the color picker should use the hex value in the textbox.

##### Actual behavior.
When you select a color, the dialog goes away. But, if you open it again, the Hex code is filled into the textbox.  Now that there is an OK button, the user expects to click that in order to "set" the color, despite the fact that the color is already set.  If you click OK, the textbox clears out.  Then if you click OK again, it removes the background color.

##### Steps to reproduce the problem.
Set a background color of a table cell.  Open the color dialog again, click OK, click OK.

##### OS.
Windows 7 Pro

##### Browser.
Firefox (latest), Chrome (latest)

**Comment by dianaprajescu** [comment]
The OK button uses the hex value in the input, and no longer clears it out. When the HEX Color input is empty, hitting the OK button will remove the background color.

The OK button is only meant to be used together with the HEX Color input, and not with the colors in the list. I understand your concern about this, and I just aded on our TODO list. Thanks.
