### ISSUE TITLE
Froala Image click event

### ISSUE THREAD

**Issue by javeriaanwer** [froala/wysiwyg-editor#2347]
hi,

I want to create an event on image click under froala editor, I couldn't find froala image click event in [Docs](https://www.froala.com/wysiwyg-editor/docs/events.).

**Comment by stefanneculai** [comment]
You could do something like this:
```js
$(selector)
  .on('froalaEditor.initialized', function (e, editor) {
    editor.$el.on('click', 'img', function () { ... });
  })
  .froalaEditor()
```
