### ISSUE TITLE
Dynamically load Froala Editor image editor buttons

### ISSUE THREAD

**Issue by javeriaanwer** [froala/wysiwyg-editor#2348]
Hi,

I want to dynamically load froala editor image button, I am using wiris library that dumps its data in image format, I am also using advance image options, so I want image editor button to show advance options when normal image is selected otherwise wiris option when wiris image is selected.

**Comment by stefanneculai** [comment]
@javeriaanwer it is best to reach Wiris because they are handling the Wiris integration for the editor.
