### ISSUE TITLE
Disable all image styles and classes

### ISSUE THREAD

**Issue by SeanKendle** [froala/wysiwyg-editor#2351]
I would like to use my own custom classes for images. I've already created my own dialog for setting image alignment with an option to apply responsive styles (float left but center on tablets and smaller, etc).

I would like to disable classes on images, but I don't want styles to end up in the styles attribute of the image.  Obviously size is fine, but float should not end up in the styles attribute.

Is there a way to prevent "fr-dib", etc, from being added to images?

Thanks

**Comment by stefanneculai** [comment]
The best way to disable the editor classes for images would be to remove the `imageAlign` and `imageDisplay` buttons from the `imageEditButtons` option.

**Comment by SeanKendle** [comment]
I did that, but when you add a new image it comes with classes already predefined.

**Comment by stefanneculai** [comment]
@SeanKendle you are right. We'll update the editor to accommodate this case.

**Comment by SeanKendle** [comment]
Thanks for you attention to this matter, @stefanneculai!  As always, your customer service/tech support is fantastic!
