### ISSUE TITLE
Indentation is not working properly

### ISSUE THREAD

**Issue by SagarKharche** [froala/wysiwyg-editor#2352]
##### Steps to reproduce the problem.
1. Create an ordered list with at least four rows
2. Select 3 rows of the ordered list together
3.  Hit indent 3 time
<img width="109" alt="order list" src="https://user-images.githubusercontent.com/7273026/32888387-1d86e476-caed-11e7-88ce-03f00d381241.png">

<img width="102" alt="select list" src="https://user-images.githubusercontent.com/7273026/32888414-2e651484-caed-11e7-85cc-c77833945233.png">

<img width="206" alt="output" src="https://user-images.githubusercontent.com/7273026/32888419-34ce241e-caed-11e7-97e0-dc700aa75daf.png">

CURRENT RESULTS: It stops indenting all the rows together and staggers them

DESIRED RESULTS: All selected rows are indented together.

**Comment by stefanneculai** [comment]
@SagarKharche thanks for reporting this, however, we consider this as being the correct behavior.  A list item is indented in the previous list item from the same level. If no previous list item is present at the same level, then the list item remains unchanged.
