### ISSUE TITLE
Duplicates of link while copying/pasting from Word

### ISSUE THREAD

**Issue by AntiFreez** [froala/wysiwyg-editor#2353]
##### Expected behavior.
Only one link is inserted in the editor.

##### Actual behavior.
One empty link and one link with original text are inserted in the editor.

![image](https://user-images.githubusercontent.com/1442020/32890489-8f123262-cb01-11e7-86e8-382d9be66c52.png)

##### Steps to reproduce the problem.
Copy link from original document and paste to the editor.

##### OS.
Windows 10

##### Browser.
Chrome 61.0.3163.100, 64 bit

**Comment by AntiFreez** [comment]
This is [Original document.docx](https://github.com/froala/wysiwyg-editor/files/1478470/Original.document.docx)

**Comment by AntiFreez** [comment]
Also, for version 2.7.1 in IE 11.0.9600.18816 on Windows 7, we get:
 
```html
<p><span style='font-family: "Calibri",sans-serif; font-size: 15px;'><a href="https://www.froala.com/wysiwyg-editor"><a href="https://www.froala.com/wysiwyg-editor" rel="noopener noreferrer" target="_blank">https://www.froala.com/wysiwyg-editor</a></span></p>
```

You can see that empty link is not closed. We cannot reproduce this issue on the official site. For the same document we get:

```html
<p><span style='font-family: "Calibri",sans-serif; font-size: 15px;'><a href="https://www.froala.com/wysiwyg-editor"></a><u><a href="https://www.froala.com/wysiwyg-editor">https://www.froala.com/wysiwyg-editor</a></u></span></p>
```

**Comment by stefanneculai** [comment]
It's fixed on the current master branch.
