### ISSUE TITLE
Is there an officially supported/recommended way to use ems for font size?

### ISSUE THREAD

**Issue by d3chapma** [froala/wysiwyg-editor#2354]
Our company uses Froala, but has the requirement of needing to use ems for scaling. We started using Froala before there was any support for ems, so we modified `froala_editor.js` and `font_size.js` to be able to do what we need. 

When we updated most recently, we started seeing an issue with font sizes where we could keep setting the font size on a piece of text to the same value and the text would continue to grow. Every time you set the font size, it would nest a new span rather than changing the span that already had `font-size` set on it.

We narrowed it down to this code in `froala_editor.js`:

```
// When em are being used keep them as the most inner props.
if ((val || '').match(/\dem$/)) {
  editor.$el.find('span.fr-unprocessed').removeClass('fr-unprocessed');
}
```

The comment makes it seem like you are supporting ems somehow, but I don't see any information about how to use them.

If you are not officially supporting ems, what is the above code for?

**Comment by stefanneculai** [comment]
@d3chapma would it be possible to create a jsFiddle for it? Thank you.

**Comment by d3chapma** [comment]
I'm not quite sure what you mean. You want me to make a js fiddle using our customized froala code to demonstrate the issue? I don't really see how that is helpful unless the froala code is unminified, but I am assuming you would not want me to post that.

I can send you a git diff with our changes to `froala_editor.js` and `font_size.js`. Would that be helpful?

To be clear, I'm not looking for you to fix anything right now. If I comment out the code snippet I posted above everything works for us. I was just surprised to see code specifically dealing with ems when my understanding was that ems are not supported (hence us having to modify the froala code to make it work).

**Comment by dianaprajescu** [comment]
@d3chapma your problem is related to issues #2104 and #2081. The current version of the editor was not designed to work with `em`. The code you highlighted in the issue's description was added as a workaround to address issue #2801, but it causes multiple spans to be created for the same css property if you are using `em`.

We'll make sure the next major version of the editor supports `em`. Until then, removing that code snipped will fix your problem.

**Comment by d3chapma** [comment]
@dianaprajescu I see there is now a `fontSizeUnit` option introduced  in 2.8.0. Does that provide official `em` support or is that waiting for version 3.0?

**Comment by stefanneculai** [comment]
The fontSizeUnit allows to specify the font-size unit by default, however, it does not address the issue explained by Diana.
