### ISSUE TITLE
imageDefaultAlign and imageDefaultDisplay not work with paste image

### ISSUE THREAD

**Issue by etarel** [froala/wysiwyg-editor#2355]
##### Expected behavior.
Image paste should be with display block and align center

##### Actual behavior.
- I paste content with images from other site to my developed editor, the image don't get centerd.
- I paste the same content to `www.froala.com`'s demo editor, the images can get centered.
- I tried to set `{ imageDefaultAlign: 'center', imageDefaultDisplay: 'block' }`, but it had no effect. Also I tried `left`, `right`, `block`, `inline`, they all seems to have no effect. 
- I tried to upload image from disk, this time `imageDefaultAlign` and `imageDefaultAlign` work very well.

##### OS.
Latest windows 10 and MacOS.

##### Browser.
latest chrome and Safari with froala 2.7.1 and jquery 3.2.1.

**Comment by stefanneculai** [comment]
@etarel most likely the pasted images have some inline style which overrides all the editor alignment options for images.
