### ISSUE TITLE
Froala's "Open Link" button ignores <a> tag security attributes

### ISSUE THREAD

**Issue by drampelt** [froala/wysiwyg-editor#2357]
##### Expected behavior.
After clicking the "Open Link" button, the link should open the exact same way as if they had actually clicked on the link. If `rel="noopener noreferrer"` was present on the `<a>` tag, the opened window should not have access to the opener or referrer. Since these attributes are added by default after fixing #1576, all windows that opened should not have access to the opener or referrer.

##### Actual behavior.
After clicking the "Open Link" button, the link opens in a new tab/window that has access to the opener window and referrer. This can than be used for phishing attacks by modifying the opener window.

##### Steps to reproduce the problem.
1. Create a link pointing to a malicious webpage (ex. https://testergirl.000webhostapp.com/redirect.php)
2. Click the link
3. Click the "Open Link" button
4. After the new window loads it will close and the original page has been redirected elsewhere

##### OS.
macOS 10.12.6 (likely others affected)

##### Browser.
Chrome 62.0.3202.94 (likely others affected)

**Comment by stefanneculai** [comment]
Nice catch! 👍
