### ISSUE TITLE
When imageOutputSize is enabled, editing width/height isn't updating properly

### ISSUE THREAD

**Issue by bpautsch** [froala/wysiwyg-editor#2358]
When imageOutputSize is enabled and an image is dropped in, we see this HTML:
&lt;img src="someimage.jpg" style="width: 300px;" width="300" height="200"&gt;

When you click into "Change Size" and clear the width or height, the "style" value updates but the attribute isn't removed. For example, in the example above, clear the width and set the height...below is the result. width="300" should have been removed too.
&lt;img src="someimage.jpg" style="height: 255px;" width="300" height="255"&gt;

We are seeing this on Windows Chrome Version 61.0.3163.100 (Official Build) (64-bit).

Note: This is not an issue when imageOutputSize  isn't enabled.

Thanks for your help.

**Comment by bpautsch** [comment]
Thanks for addressing this, but there are a few small issues you might want to address.

1. When an image is added to the page, this is the HTML:
<img src="someimage.jpg" style="width: 300px;" width="300" height="187">
Issue: The height is missing from the "style". It's an issue because when you click "Change Size", the width is 300px, but the height is blank. It probably wouldn't cause display issues, but I'm guessing you'd want the HTML to be consistent.
Note: It does resize nicely and update both the style height/width and the height/width attributes.
For example, I grabbed the corner and resized it to 400px wide. This is the HTML:
<img src="someimage.jpg" style="width: 400px; height: 249.333px;" width="400" height="249.333">
Great!

But another problem: If I click "Change Size", clear the height and click Update, this is the HTML:
<img src="someimage.jpg" style="width: 400px;" width="400" height="250">
Issue: Notice the height attribute remains. Fortunately the height is a valid value right now and resizing the image (either drag or Change Size) update the value. Again, just a small consistency issue.

For both issues...I don't think anyone would notice them in the UI, so they're not urgent.

Thanks,
Brian

**Comment by JaxonWright** [comment]
This still seems to be broken in v3.2.6-1. When you resize with this option, it simply does not change the `width=` nor `height=` attributes.

The fix for this appears to have been made to the Mautic project, which uses Froala, here:
https://github.com/mautic/mautic/pull/7569/files#diff-b4e8abf64b5f04f4eb5b853b7ee08795ac8649b9e4d1e84f399eca5bf3d55e03R1873

Unfortunately, the unminified code is not stored in this repository, so it is impossible to submit pull requests or fix it ourselves
