### ISSUE TITLE
Text selection disappears when the Color Picker w/ Hex Editor is open

### ISSUE THREAD

**Issue by bsatorius** [froala/wysiwyg-editor#2359]
##### Expected behavior.
When opening the color picker, any selected text should stay active.

##### Actual behavior.
Text selection disappears when the Color Picker w/ Hex Editor is open. It appears that the focus of the text field removes the selection from the editor.

##### Steps to reproduce the problem.
Select text in the editor, then open the color picker

##### OS.
Windows 10

##### Browser.
Chrome 62.0.3202.94 (Official Build) (64-bit)

**Comment by stefanneculai** [comment]
It is disappearing because the focus moves to another input (the one from the popup). However, the editor knows to store that and apply the color correctly.
