### ISSUE TITLE
Paragraph Alignment Issue.

### ISSUE THREAD

**Issue by ShanmugaPriyanV** [froala/wysiwyg-editor#2361]
##### Expected behavior.
Copied Some Content having three to six paragraphs to the Editor. Selected the first paragraph and gave center align it worked,  but when selecting next paragraph the entire paragraph below the selected one got aligned. 

##### Actual behavior.
Only selected paragraphs should be aligned?

##### OS.
Windows 7

##### Browser.
Chrome 62.0.3202.94 (Official Build) (64-bit)

**Comment by stefanneculai** [comment]
@ShanmugaPriyanV could you please send us a document/place to paste from in the editor? Thank you.

**Comment by ShanmugaPriyanV** [comment]
@stefanneculai Attached the sample document with test data for your assistance.
[Paragraph_Alignment_Issue.docx](https://github.com/froala/wysiwyg-editor/files/1498511/Paragraph_Alignment_Issue.docx)

**Comment by stefanneculai** [comment]
@ShanmugaPriyanV are you experiencing this on our website? Could you please make a recording?

**Comment by ShanmugaPriyanV** [comment]
@stefanneculai Attached the document which contains the screen recording captured from Froala Website. Download the attachment, unzip and open the document using Internet Explorer.
[Problem_20171212_1024.zip](https://github.com/froala/wysiwyg-editor/files/1570142/Problem_20171212_1024.zip)

**Comment by stefanneculai** [comment]
@ShanmugaPriyanV we just tested it. In the HTML which comes from Word, the last 4 paragraphs are actually a single one although they look like different ones. The HTML is similar to the following one, where there are only 2 main paragraphs because on the other ones there are SOFT new lines.

```html
<p>paragraph 1</p>
<p>paragraph2 <br><br> line 3<br><br> line 4</p>
```
