### ISSUE TITLE
Youtube reload with EnterKey 

### ISSUE THREAD

**Issue by seraOh** [froala/wysiwyg-editor#2362]
##### Expected behavior.
- video must not reload by enter key. 

##### Actual behavior.
 - when Enter key down near the iframe,  every time reload. 

##### Steps to reproduce the problem.
 1.  insert a video by URL  (like youtube)
 2. Enter key down on the iframe next paragraph

##### Browser.
- chrome, safari

**Comment by stefanneculai** [comment]
@seraOh we're aware of this, unfortunately, there is no workaround for it at this moment. At the time a paragraph is split on ENTER key, it recreates the existing one and that makes the iframe from YouTube to reload.
