### ISSUE TITLE
iOS undo with getBoundingRect on keyup removes 1 character at a time

### ISSUE THREAD

**Issue by bryannovoed** [froala/wysiwyg-editor#2363]
##### Expected behavior.
LIke on Mac chrome, removal of characters on pressing undo should remove chunks at a time.

##### Actual behavior.
Individual character is removed each time.

##### Steps to reproduce the problem.
1. Go to jsfiddle.net/5g17kpn6
2. type "abcdef"
3. press undo
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/8356554/33048592-8314e2ea-ce10-11e7-94ec-08b5972723a8.gif)

##### OS.
iOS 11

##### Browser.
Safari 11

**Comment by stefanneculai** [comment]
@bryannovoed the editor is handling the undo steps by using the `typingTimer` option. Based on how quick you press backspace that change would go to the undo stack.

**Comment by bryannovoed** [comment]
@stefanneculai i tested with and without getBoundingRect (called like in the jsfiddle) and the two perform differently even though the rough input speed was the same
1) without getBoundingRect, undo would remove all the text [http://jsfiddle.net/5g17kpn6/1](http://jsfiddle.net/5g17kpn6/1)
2) with getBoundingRect, undo would only remove one character at a time [http://jsfiddle.net/5g17kpn6/](http://jsfiddle.net/5g17kpn6/)
