### ISSUE TITLE
iOS toolbar unbold cannot unbold iOS bold

### ISSUE THREAD

**Issue by bryannovoed** [froala/wysiwyg-editor#2364]
##### Expected behavior.
After bolding text with the iOS bold option, one can unbold using Froala toolbar.

##### Actual behavior.
After bolding text with the iOS bold option, one cannot unbold using Froala toolbar.
same issue for italic, underline seems to work

##### Steps to reproduce the problem.
https://jsfiddle.net/5g17kpn6/2/
1. type "abcdefg"
2. highlight the text
3. select "BIU" from the iOS toolbar
4. select "Bold" from the iOS toolbar
5. select "B" for bold from the Froala toolbar
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/8356554/33049312-4b767c3c-ce14-11e7-983f-2e8cf69007e2.gif)

##### OS.
iOS 11

##### Browser.
Safari 11

**Comment by stefanneculai** [comment]
Unfortunately, the iOS toolbar is applying the formats different than the editor and that's why they are not being removed. I am marking this as a `feature-request` and `wontfix` for now.
