### ISSUE TITLE
mobile(iOS&Android) on scroll secondary menu closes

### ISSUE THREAD

**Issue by bryannovoed** [froala/wysiwyg-editor#2365]
##### Expected behavior.
Onscroll, menus stay put.

##### Actual behavior.
Onscroll, secondary menu closes. e.g. paragraph format for inline toolbar

##### Steps to reproduce the problem.
1. highlight a string on https://www.froala.com/wysiwyg-editor/examples/inline
2. scroll on the page
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/8356554/33050661-e16c3c1c-ce1a-11e7-8889-d96ee869d594.gif)

##### OS.
iOS 11 & Android 6.0.1

##### Browser.
Safari 11 & Chrome 62

**Comment by stefanneculai** [comment]
@bryannovoed thanks for reporting this. However, there is not too much we can do about it because the editor toolbar is designed to close on scroll in order to improve performance. On scroll it might be required to recompute position and that would create an overload.
