### ISSUE TITLE
iOS Link dropdown disappears when autofilling in Chrome/Safari

### ISSUE THREAD

**Issue by ayjee** [froala/wysiwyg-editor#2368]
##### Expected behavior.
As a user, I would expect to open the link dropdown and be able to select an autofilled url from a previously visited website (via autofill) without losing focus in the link dropdown (without closing the link dropdown).

##### Actual behavior.
When opening the link dropdown and attempting to autofill a previously visited url, the link dropdown loses focus and closes.

##### Steps to reproduce the problem.
- On an iOS device with Chrome or Safari, in settings turn on Autofilling of forms.
- Navigate to a site with froala that supports inserted links, ie https://www.froala.com/wysiwyg-editor/examples/link-styles
- Start typing the URL field with the link dropdown open, and then select a previously visited url from the autofill options that show above the iOS keyboard.
- Notice that once you select the autofilled url, the dropdown closes.

##### OS.
iOS v 11.1.1

##### Browser.
Google Chrome Version 62.0.3202.70
Safari Version Version 11

**Comment by dianaprajescu** [comment]
@ayjee we are not able to reproduce this. It seems the AutoFill (Settings > Safari > AutoFill) is for contact info, previous names and passwords, or credit card info. It does not autofill URLs. Are we missing something?

Could you please make a recording to highlight this issue?

**Comment by dianaprajescu** [comment]
@ayjee Do you have any updates that could help us reproduce this issue?

I'm going to close this issue for now, due to lack of response. Once we have more details and we are able to reproduce it, we will reopen the issue.
