### ISSUE TITLE
.com.ua domain are not properly linkified

### ISSUE THREAD

**Issue by thedotedge** [froala/wysiwyg-editor#2371]
##### Expected behavior.
When typing .com.ua domains (i.e. free.com.ua) full domain should be linkified.

##### Actual behavior.
Only .com part is linkified, i.e. **free.com**.ua

##### Steps to reproduce the problem.
![nov-23-2017 16-53-24](https://user-images.githubusercontent.com/227241/33181069-305f35c6-d06f-11e7-858f-6765b86cc11d.gif)

Reproducible in Froala 2.7.0

**Comment by Brisstor** [comment]
Hello, looks like there is a minor problem still appearing. The domain becomes linkified only after spacebar is placed after him. Or that's a feature?


http://take.ms/1nWmK

Reproducible in Froala 2.7.5

**Comment by stefanneculai** [comment]
@Brisstor that is how it is designed to work. The link is made on space, dot or enter.
