### ISSUE TITLE
Disable Specific Toolbar Buttons

### ISSUE THREAD

**Issue by vusisindane** [froala/wysiwyg-editor#2373]
I've creates several custom toolbar buttons.  I want to disable specific buttons, similar to what happens with the undo buttons.  

I've gone through the documentation but can't seem to be able to see how this is done.  There's an option to disable the whole toolbar, but this is not what I am looking for.  I want to disable specific toolbar buttons.  

How do we do this?

**Comment by stefanneculai** [comment]
The best way is to do it like here, but use the `fr-disabled` class: https://wysiwyg-editor.froala.help/hc/en-us/articles/115000592265-How-can-I-make-a-custom-button-active-.
