### ISSUE TITLE
Default font family and font size changes on focus

### ISSUE THREAD

**Issue by FWennerdahl** [froala/wysiwyg-editor#2375]
##### Expected behavior.
The default font family and font size should be selected when the editor is initially focused.

##### Actual behavior.
The font family and font size are changed when the editor is initially focused.

##### Steps to reproduce the problem.
1. Open JSFiddle at https://jsfiddle.net/rmooksaL/
2. Notice that default font family is "Arial" and default font size is "18".
3. Click the editor to focus it.

##### OS.
macOS 10.12.6

##### Browser.
Chrome 62.0.3202.94

**Comment by stefanneculai** [comment]
`defaultFontFamily` option is designed to be used when the selection is outside of the editor. If you would like to change the default font-family to Arial the best way is to do it via CSS: https://jsfiddle.net/rmooksaL/1/.

**Comment by FWennerdahl** [comment]
@stefanneculai I'm not entirely sure what you mean with "when the selection is outside of the editor", but applying the default font size and family in CSS in combination with the defaultSelection properties seems to result in the behaviour we were after. Thanks for the help!

**Comment by nickvoegeli** [comment]
This seems very counterintuitive.  The options are called `fontFamilyDefaultSelection` and `fontSizeDefaultSelection`, which seems to imply that these options represent the default selections for font size and family.  What's the point of having user-configurable options to display a given font size/family as through they're selected when the editor is out of focus, then change those values when the editor is focused?

**Comment by stefanneculai** [comment]
@nickvoegeli it is designed to be as a placeholder when there is no selection in the editor. It helps end-users to get familiar with what options they have there.

**Comment by craigjennings11** [comment]
I agree with @nickvoegeli. The `fontFamilyDefaultSelection` and `fontSizeDefaultSelection` options are not intuitive at all.  I'd expect to be able to set `fontFamilyDefaultSelection` to a certain value (like "Impact" for example) and that be the font that the user is set to when they start typing in the editor. Instead, "Impact" is highlighted as though the editor is set to it, but when you type the resulting text is some other font, not "Impact". Widely unexpected behavior, and makes the option useless.
