### ISSUE TITLE
Missing Content type

### ISSUE THREAD

**Issue by sureshy02** [froala/wysiwyg-editor#2376]
Hi,
     I am trying to upload image into my local storage. But its calling twice the server . In first request, it's throwing Missing Content-type and in second request its storing the image into the folder . In front end its showing "something went wrong". I am using node.js and angular 4

**Comment by stefanneculai** [comment]
@sureshy02 for tech support regarding image upload please contact us via our website https://www.froala.com/wysiwyg-editor/contact
