### ISSUE TITLE
How can we get the length of the text entered (without the HTML tags) ???

### ISSUE THREAD

**Issue by saihanuman73** [froala/wysiwyg-editor#2377]
Is there any method to get the length of the text edited without those HTML tags. 
I need to write a condition where the length of the text entered is important.

I will be glad if anyone helps me out !!! Thank you.

**Comment by FWennerdahl** [comment]
The `$.FE.INSTANCES[0].el.textContent` property seems to contain all textual data (without markup), so the length of that might be what you're looking for.

**Comment by saihanuman73** [comment]
@FWennerdahl Hey, thanks for the reply. But I'm getting an error like 

**FE does not exist on type JQueryStatic**

Actually, I'm trying to place this in typescript file. and I'm getting the above error. Any idea regarding this?

**Comment by stefanneculai** [comment]
```js
$('selector').data('froala.editor').el.textContent;
```
