### ISSUE TITLE
Styling link text with color results to  incorrect tags wrapping structure

### ISSUE THREAD

**Issue by celeneisip** [froala/wysiwyg-editor#2378]
##### Expected behavior.
Applying color style to a link text should  have the inline style inside the <a> tag 

markup:
<p><a><span style="color: rgb(226, 80, 65);"> sample text</span></a></p>

##### Actual behavior.
Applying color style to a link text wraps the <a> tag with span tag
markup:
<p><span style="color: rgb(226, 80, 65);"><a>sample text</a></span></p>

##### Steps to reproduce the problem.

1. Type in any text
2. Higlight that text and click the link icon in the toolbar
3. Add a link address to the link popup
4. Hightlight the created link text and apply any color style from the toolbar
5. Then check dom markup

![linkstyle](https://user-images.githubusercontent.com/20301406/33278538-3c78b9a8-d372-11e7-9235-131886e8a7c6.gif)

##### OS.
windows and mac

##### Browser.
Chrome/firefox/safari

**Comment by stefanneculai** [comment]
We consider the current behavior as being the correct one. There is a rule inside CSS which is set for such cases:
```css
.fr-view span[style~="color:"] a {
    color: inherit;
}
```
