### ISSUE TITLE
Integrate wiris editor in quick insert

### ISSUE THREAD

**Issue by javeriaanwer** [froala/wysiwyg-editor#2379]
hi, I want to show wiris Editor button in quick insert buttons , I tried this code: `quickInsertButtons: ['image', 'table', 'ol', 'ul', `'wirisEditor'],` but its not working, can you suggest any thing else?

**Comment by stefanneculai** [comment]
@javeriaanwer for any help regarding the Wiris Editor please reach the Wiris team instead.
