### ISSUE TITLE
Image replace throwing error "cannot read property 'offset' of null"

### ISSUE THREAD

**Issue by Tolsee** [froala/wysiwyg-editor#2380]
##### Expected behavior.
Image upload, as usual, show loading or uploading progress bar.

##### Actual behavior.
Throws error "cannot read property 'offset' of null". Shows faded image

##### Steps to reproduce the problem.
1. Go to image and replace it as below:

<img width="892" alt="screen shot 2017-11-28 at 3 40 59 pm" src="https://user-images.githubusercontent.com/16590492/33313418-b28c49e4-d452-11e7-8f02-89c9bdda83e3.png">

2. You will see faded image with error msg like below:(the editor is customized as per requirement)
![szoter_image](https://user-images.githubusercontent.com/16590492/33313945-4457ed3c-d454-11e7-83ba-9f9e9b73744c.png)

##### OS.
Ubuntu 16.04 LTS

##### Browser.
Chrome Version 62.0.3202.75

##### OS.
Windows 10 

##### Browser.
Version 62.0.3202.94

*Works fine in mac
*editor version 2.7.2

**Comment by dianaprajescu** [comment]
@Tolsee we are not able to reproduce the issue you described. Could you please make a jsFiddle or Codepen with your configuration to highlight the problem? Thanks.

**Comment by Tolsee** [comment]
@dianaprajescu Thanks for your reply, btw, It seems that I had not upgraded the `image` plugin. Now, it works perfect.
