### ISSUE TITLE
Cut doesnt remove text

### ISSUE THREAD

**Issue by jamesmoss** [froala/wysiwyg-editor#2382]
##### Expected behavior.
Using cut behaviour will copy highlighted text to the clipboard and remove text from the editor field.

##### Actual behavior.
Text is copied to clipboard but text is not removed from editor

##### Steps to reproduce the problem.

- Highlight some text.
- Cut the text (using either the keyboard shortcut or with the menu)
- Text is not removed
- If all text in the field is highlighted then cut works correctly.

##### Browser.
All browsers.

**Comment by bryannovoed** [comment]
@stefanneculai we had to revert to 2.7.1 since this was a bigger issue than the issues 2.7.2 fixed. any idea when this will land into a release?

**Comment by bryannovoed** [comment]
@stefanneculai on iOS now we're seeing that cutting removes the text, but you still can't paste it. same with copy. for copy, it will remove what you have previously copied as well

**Comment by mostafaznv** [comment]
I had this problem in 2.7.2 and when I upgraded problem solved
