### ISSUE TITLE
Correctly encoded href losing encoding

### ISSUE THREAD

**Issue by topherdavis** [froala/wysiwyg-editor#2384]
##### Expected behavior.
(Describe expected behaviour here)

Editor initialized with an anchor containing a url with the correct encoding should not modify the url.

Specifically a url containing `&amp;` in the parameters should maintain `&amp;`.

Initialized with:
```
<textarea><a href=""https://en.wikipedia.org/w/index.php?title=2017_eruption_of_Mount_Agung&amp;action=edit&amp;section=2"" target=""_blank"">edit</a></textarea>
```

Should result in the following saved:

```
<a href=""https://en.wikipedia.org/w/index.php?title=2017_eruption_of_Mount_Agung&amp;action=edit&amp;section=2"" target=""_blank"">edit</a>
```

##### Actual behavior.
(Describe actual behaviour here)

Editor initialized with an anchor containing a url with the correct encoding will decode `&amp;` to `&`.

Initialized with:
```
<textarea><a href=""https://en.wikipedia.org/w/index.php?title=2017_eruption_of_Mount_Agung&amp;action=edit&amp;section=2"" target=""_blank"">edit</a></textarea>
```

Results in the following saved:

```
<a href=""https://en.wikipedia.org/w/index.php?title=2017_eruption_of_Mount_Agung&action=edit&section=2"" target=""_blank"">edit</a>
```

##### Steps to reproduce the problem.
(Describe the steps to reproduce the problem here)

The editor has the links plugin.

Initialize the editor with the following html:

```
<textarea><a href=""https://en.wikipedia.org/w/index.php?title=2017_eruption_of_Mount_Agung&amp;action=edit&amp;section=2"" target=""_blank"">edit</a></textarea>
```

Give focus to the editor.

Trigger a save event.

##### OS.
Win 10

##### Browser.
Chrome

**Comment by stefanneculai** [comment]
@topherdavis inside HREFs, `&amp;` is always converted to `&`. Is there any specific reason why would you need there `&amp` inside a link?

**Comment by topherdavis** [comment]
@stefanneculai My understanding is that in the html itself `&amp;` is correct while the rendering of the html is `&`.

I have server side html sanitation and the editor is changing the url which leads to a dirty state in the model.

I was trying to determine if I should make the behavior match by changing the server or the client and it appeared from my research the the sanitizer on the server was correct.

**Comment by topherdavis** [comment]
That said.. I just need the value of the field not to change. The conversion in the rendered component is fine.

If there really isn't going to be a fix I can just write some additional code to ensure the user has performed the modification and not the editor.
