### ISSUE TITLE
fr-above class being incorrectly applied to the toolbar.

### ISSUE THREAD

**Issue by natashad** [froala/wysiwyg-editor#2385]
##### Expected behavior.
The toolbar should be displayed above the clicked area only if there isn't enough space below.

##### Actual behavior.
The toolbar gets rendered above even though there is plenty of space under the toolbar in certain situations

##### Steps to reproduce the problem.
- On a browser with viewport size around 1280 x 670
- Open up the following HTML file in browser (after renaming .txt to .html since i couldn't upload an html): 
[froala.txt](https://github.com/froala/wysiwyg-editor/files/1519571/froala.txt)
- scroll down and click inside any of the editors  titled "CLICK IN ME AND I BREAK"
- Notice that despite there being enough space under the editor, the toolbar still renders on top.
![image](https://user-images.githubusercontent.com/1857154/33456428-6992b51a-d5ed-11e7-8473-fda622f76d3b.png)

##### Notes:
Note: This appears to be due to the change in function `_topNormalized()` to use `clientHeight` instead of `scrollHeight` despite the rest of the variables (specifically `top`) used to calculate whether to use `.fr-above` taking into account the scroll container.

##### OS.
mac OS ( on a retina laptop screen (1280 x 671 viewport size) not on a larger monitor )

##### Browser.
(Browser name an version here)
Chrome

**Comment by stefanneculai** [comment]
@natashad the problem is coming from the fact that you have no DOCTYPE set to the page:
```html
<!DOCTYPE html>
```
