### ISSUE TITLE
2.7.2 : wrong encoding when copying text from Safari

### ISSUE THREAD

**Issue by YannLeBihan** [froala/wysiwyg-editor#2391]
##### Expected behavior :
Copying text from Safari should result in text encoding consistency

##### Actual behavior :
Encoding is wrong when copying text from a Froala instance running on Safari for Mac

##### Steps to reproduce the problem.
- Go to [Froala site](https://www.froala.com/wysiwyg-editor) with Safari for Mac
- Paste this small piece of text into the demo editor : "Caractères accentués"
- Select and copy the pasted text
- Paste it into any text editing app like TextEdit or Pages
- The result will be "CaractÃ¨res accentuÃ©s"

##### OS :
macOS 10.13.1, tested on 3 different machines

##### Browser :
Safari 11.01. Doesn't happen on Chrome.

**Comment by stefanneculai** [comment]
@YannLeBihan fixed on the current master here on Github.

**Comment by YannLeBihan** [comment]
This is great news, thanks a lot.
