### ISSUE TITLE
2.7.1 Code view in full size mode if set heightMax

### ISSUE THREAD

**Issue by wdc-admin** [froala/wysiwyg-editor#2392]
##### Expected behavior.
Code view block in full size mode need will be in full screen if set heightMax param.

##### Actual behavior.
(Describe actual behaviour here)
Code view mode works correctly only if doesn't set max-height for redactor.
![2066fe1984](https://user-images.githubusercontent.com/32925265/33545346-ee3dacd0-d8ee-11e7-8c59-55fd90272f06.jpg)

##### Steps to reproduce the problem.
(Describe the steps to reproduce the problem here)

1. Set heightMax param for redactor
2. Paste big text in text editor
3. Click "fullscreen" mode
4. Click "code view"

##### OS.
(OS name and version here)
LInux Mint 17.3

##### Browser.
(Browser name an version here)
Chromium 58.0.3029.110

**Comment by dianaprajescu** [comment]
@wdc-admin could this issue be reproduced on other OS than Linux?

I would recommend you to update your Froala Editor to the latest version 2.7.2, although this will most likely not solve this issue.

**Comment by dianaprajescu** [comment]
@wdc-admin Is this issue still happening for you with the latest version of the Froala Editor? Do you have any additional information to help us reproduce it at our end?

I'm closing this issue for the moment due to lack of response. We'll reopen it once we have enough details to reproduce it.

**Comment by wdc-admin** [comment]
I checked on last version 2.7.3.

Steps to reproduce:
text - view by default(without tags), html - code view(with tags)

1) Small screen, text. Write a text about 6000 characters.
2) Small screen, html.
3) Full screen, html. => Html-text is located on a half of screen in horizontal line, with scroll.
OR
1) Small screen, text. Write a text about 6000 characters.
2) Full screen, text.
3) Full screen, html.
4) Small screen, html. => Html-text is located in full textarea, with scroll. But we see a half of text.
5) Small screen, text.
6) Full screen, html. => Html-text is located on a half of screen in horizontal line (bottom of text), without scroll.
