### ISSUE TITLE
Some spacing lost in paste from Powerpoint

### ISSUE THREAD

**Issue by cmkind** [froala/wysiwyg-editor#2395]
I'm sorry if there is another existing report that covers this; I checked a few that seemed somewhat related and didn't see anything that quite matched. It's a minor problem but has been a little irritating for several of our users.

##### Expected behavior.
Consistent spacing is preserved through paste

##### Actual behavior.
Some spaces are removed when content is pasted (regardless of keep\clean selection)

##### Steps to reproduce the problem.
1. Open attached example file in Powerpoint
2. Copy the chunk of text starting with "1980..."
3. Paste into froala

Example powerpoint file is attached. Some content was removed for privacy, but the particular section that shows the issue is the middle box:
1980-‘94 Brauerausbildung, Studium Brautechnik, Schicht-Braumeister, 2011 Supply Controlling - Bremen, Deutschland, West-Europa, 2013 Zone Brew.Support – Better World, 2015 Brewery Manager Gilde Hannover, 2016 Brewing Manager Bremen

It's subtle, but when pasted, there are a handful of missing spaces
1980-‘94Brauerausbildung
2015Brewery 

Similar behavior has been reported by our users with other documents, from other MS Office applications, but unfortunately this is the only actual example I've been able to get thus far.

I'm a bit suspicious that it is related to the prompt for "Keep" or "Clean", just because the prompt doesn't show up in situations where the issue doesn't replicate - namely, when using Mac, or when explicitly pasting as plain text (Ctrl+Shift+V).

##### OS.
Windows
I have not been able to repro in Mac OS (using Safari and Chrome)

##### Browser.
Chrome\IE 11\Edge\Firefox

I compared the paste result in a couple other applications. So far have not seen anything else strip the spacing.
![image](https://user-images.githubusercontent.com/28112300/33569419-821c62d6-d8de-11e7-96ec-3ec5dc9b72a2.png)

[paste_ex.pptx](https://github.com/froala/wysiwyg-editor/files/1528332/paste_ex.pptx)

**Comment by stefanneculai** [comment]
@cmkind this should be fixed on the current Github master. Could you please check?

**Comment by cmkind** [comment]
@stefanneculai we're working on getting updated, I'll double-check when it's live and confirm. Thank you!!

**Comment by dianaprajescu** [comment]
@cmkind do you have any updates regarding this?

**Comment by stefanneculai** [comment]
Closing this due to lack of response.

**Comment by cmkind** [comment]
I'm so sorry, I thought I dropped a note here before. To belatedly confirm, it does appear to be preserving the spacing now. Thank you for your help!
