### ISSUE TITLE
Remove toolbar and inline editor 

### ISSUE THREAD

**Issue by joshoconnor89** [froala/wysiwyg-editor#2396]
I would like to create my own custom toolbar instead of being forced to use the default toolbar or inline toolbar.  Is this possible?

I've tried the following:

const EDITOR_OPTIONS = {
placeholderText: 'Enter task description...',
charCounterCount: false,
htmlRemoveTags: ['script'],
heightMin: 300,
toolbarInline: true,
saveInterval: 10000,
saveMethod: 'PUT',
toolbarButtons: null
}

$(function () {
  let $editor = $('#editor-container').froalaEditor(EDITOR_OPTIONS);
});

This seems to solve the issue, but then I can't remove the arrow pointing up when text is highlighted (where the inline toolbar was).

**Comment by joshoconnor89** [comment]
<img width="372" alt="screen shot 2017-12-04 at 11 41 52 am" src="https://user-images.githubusercontent.com/9359439/33572620-4e9554c2-d8e8-11e7-908a-26caa6c045f4.png">

**Comment by joshoconnor89** [comment]
Also, setting the toolbarButtons to null is causing alignment to not work:

function alignText(alignment){
    $("#editor-container").froalaEditor('align.apply', alignment);
}

**Comment by stefanneculai** [comment]
Sure, just make use of the toolbar.show event: https://www.froala.com/wysiwyg-editor/docs/events#toolbar.show
