### ISSUE TITLE
Image resize event(s) don't fire when changing size via modal

### ISSUE THREAD

**Issue by aarndt** [froala/wysiwyg-editor#2397]
##### Expected behavior.
The resizeEnd (and perhaps resize) event(s) fire after an image has been resized via the "Change Size" button modal

##### Actual behavior.
When resizing an image via the "Change size" button/modal, the resize/resizeEnd events do not fire.

##### Steps to reproduce the problem.
1. Add console log statements to the resize and resizeEnd events in order to observe events firing
2. Insert an image into the editor
3. Click on the "Change size" button on the image menu
![changesize](https://user-images.githubusercontent.com/13895114/33582049-2a124504-d908-11e7-92bc-cc888baf8b1f.PNG)

4. Change the image size and click 'Update'
![changesize2](https://user-images.githubusercontent.com/13895114/33582057-30e95ec6-d908-11e7-8583-3a3b7c7421e0.PNG)

5. Observe that the resize events do not fire

Note - I am trying to ensure that the user does not resize images above a certain limit.

##### Froala Version
froala-editor 2.7.2 via angular-froala-wysiwyg 2.7.2

##### OS.
Windows 10 Version 1703 Build 15063.726

##### Browser.
Firefox Developer Edition 58.0b8 (64-bit)

**Comment by stefanneculai** [comment]
@aarndt it shouldn't trigger that event. For this case, it is best to use the `commands.after` event and catch it.
