### ISSUE TITLE
View bug by empty toolbarButtons in toolbarInline mode 

### ISSUE THREAD

**Issue by cokuna-pavelkosolapov** [froala/wysiwyg-editor#2400]
##### Expected behavior.
toolbarInline = true and toolbarButtons = [ ] ( don't want any buttons ). It shouldn't show a popup with any buttons.

##### Actual behavior.
an arrow will be shown => empty popup

##### Steps to reproduce the problem.
1. Init froala like this:
```
$('#froala-editor').froalaEditor({
  toolbarButtons: [ ],
  toolbarButtonsMD: [ ],
  toolbarButtonsSM: [ ],
  toolbarButtonsXS: [ ],
  toolbarInline : true,
  toolbarVisibleWithoutSelection : true // or false
});
```
2. ( if you set toolbarVisibleWithoutSelection to false, need select a word. ) you will see an empty popup (an arrow under the text area). 
Like this: 
![bildschirmfoto 2017-12-05 um 17 23 23](https://user-images.githubusercontent.com/13797256/33618124-f942d152-d9e1-11e7-80be-cf3c6c8c1a18.png)

##### OS.
macOS 10.12.6

##### Browser.
Google Chrome 62.0.3202.9
Firefox 57.0.1
Opera 49.0

**Comment by stefanneculai** [comment]
@cokuna-pavelkosolapov we don't consider this behavior as being incorrect. If you don't want to show the toolbar, then the correct way is to use the `toolbar.show` event and return false in the callback.

**Comment by cokuna-pavelkosolapov** [comment]
Sorry, but it's foolishly... imo, it should be checked, that dropdown-menu is not empty.
