### ISSUE TITLE
When select multi cells, an event FroalaEditor.blur has sent

### ISSUE THREAD

**Issue by masseuro** [froala/wysiwyg-editor#2402]
##### Expected behavior.
When I select cells on a table in editor, I don't want a blur event

##### Actual behavior.
FroalaEditor.blur event is created when select cells

##### Steps to reproduce the problem.

See what happens 
![screen recording 2017-12-06 at 10 13 am](https://user-images.githubusercontent.com/131135/33653816-7df2b412-da6e-11e7-8a28-02273358af9b.gif)

And here [the codepen to reproduce](https://codepen.io/masseuro/pen/vWMqbz)

##### OS.
Macos 10.31.1

##### Browser.
Chrome 62

**Comment by dianaprajescu** [comment]
@masseuro this is no longer happening in the latest version of the Froala Editor 2.7.2.
