### ISSUE TITLE
Problem integration At.js

### ISSUE THREAD

**Issue by mmmf84** [froala/wysiwyg-editor#2403]
I have a problem with the integration with froala editor.
I follow the document and use this code:

```javascript
var config = {
      at: "@",
      callbacks: {
		remoteFilter: function(query, callback) {
		var thisVal = query,
	        self = $(this);
	        if( !self.data('active') && thisVal.length >= 1 ){
			$.post("/users/list", {q: query}, function(data) {
				callback(data)
			},'json');
		}
		}
	},
      selector: "#new_comment",
      displayTpl: '<li>${name}</li>',
      insertTpl: '<a class="big" href="/${id}/${slug}" target="_blank">${name}</a> &nbsp;',
      limit: 200
    };

    $('#new_comment')
		.on('froalaEditor.initialized', function (e, editor) {
			// Add At.JS
			editor.$el
			.atwho(config)
			.on('inserted.atwho', function () {
				editor.$el.find('.atwho-inserted').removeAttr('contenteditable');
			})

			editor.events.on('keydown', function (e) {
				if (e.which == $.FroalaEditor.KEYCODE.ENTER && editor.$el.atwho('isSelecting')) {
				return false;
			}
			}, true);
		})
      .froalaEditor()
```

The data is loaded and entered correctly. The problem arises when I send the data to the database because if after inserting an element with at.js and any key is pressed, instead of sending the template i
instead of sending the template it simply sends the query entered up to that moment while if I press some key afterwards upon insertion by at.js then the tamplate is sent correctly.

**Comment by stefanneculai** [comment]
It looks like `undo.saveStep` should be called in the `inserted.atwho` event from At.js.

**Comment by mmmf84** [comment]
Thanks Stefan. Now it works perfectly.
