### ISSUE TITLE
inline Image and align are broken

### ISSUE THREAD

**Issue by electroheadfx** [froala/wysiwyg-editor#2404]
##### Expected behavior.
Inline mode and align for image

##### Actual behavior.
The image doesn't align (stay at left) and only one text line float a right image. 
Change inline to break or different align doesn't work
I have no console JS debug message.
On the froala site it works fine, something was broken or a setup was changed before 2.7 ?

##### Steps to reproduce the problem.
Use froala_editor v2.7.2 on Safari 11.0.1 and chrome 61.0.3

##### OS.
macOS 10.12.6 / Windows 7

##### Browser.
Safari 11.0.1 / Chrome tested on  macOS and PC

**Comment by dianaprajescu** [comment]
@electroheadfx we are not able to reproduce this issue. Since it works fine on the Froala website, could you please make a JSFiddle where we could see the problem?

**Comment by electroheadfx** [comment]
Thanks, I fixed it through JSFiddle, With froala_editor.pkgd.css I missed froala_style.css
