### ISSUE TITLE
"cmd + x" seems to be broken

### ISSUE THREAD

**Issue by achambers** [froala/wysiwyg-editor#2405]
##### Expected behavior.
When highlighting selected text in the editor, `cmd + x` cuts the text.

##### Actual behavior.
The text is not cut.

(When highlighting ALL the text, it seems to work ok).

This can be reproduced on the Froala demo page - https://www.froala.com/wysiwyg-editor

##### Steps to reproduce the problem.
- Highlight some text
- `cmd + x`
- Observe the text remains

##### OS.
macOS Sierra, 10.12.2

##### Browser.
Chrome, 62.0.3202.94
Firefox, 57.0.1

**Comment by stefanneculai** [comment]
It's fixed on the current master.

**Comment by achambers** [comment]
@stefanneculai Ok. Is it published to npm? We're on v2.7.1 and I don't see it in the [release notes](https://github.com/froala/wysiwyg-editor/releases) for v2.7.2.

If it's not, when is it likely to be?

**Comment by stefanneculai** [comment]
By the end of the week.
