### ISSUE TITLE
EXTERNAL CSS(LINK TAG) HAS BEEN EXECUTED IN EDITOR WHEN PAGE IS LOAD

### ISSUE THREAD

**Issue by fatihtan** [froala/wysiwyg-editor#2407]
I add external css link tag into editor, and save it to the database. I expect external css link tag does not affect the current page. But it does.
Added link tag is below:
`<link rel="stylesheet" href="http://netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" />`

How can I prevent effect of the classes in the css file?

**Comment by stefanneculai** [comment]
For that you should enable the iframe or fullPage option.

**Comment by fatihtan** [comment]
Thank you for your response.

**Comment by fatihtan** [comment]
When I try to `  fullPage: true`, I cannot write on the editor and insert anything.

**Comment by Devyn-poignancy759** [comment]
> When I try to ` fullPage: true`, I cannot write on the editor and insert anything.





https://grislyprecision7.github.io/benign5/
