### ISSUE TITLE
text selection not working properly on dark background color firefox

### ISSUE THREAD

**Issue by javeriaanwer** [froala/wysiwyg-editor#2411]
Hi,

Text with Dark Background color on selection showing white Background and blue text color in FireFox.

Before:

![before froala](https://user-images.githubusercontent.com/25203829/33816774-3cd31e84-de5d-11e7-8bca-f3628be0622e.png)

After selecting:

![after froala](https://user-images.githubusercontent.com/25203829/33816771-3896c334-de5d-11e7-91fe-367e988b360c.png)

It's difficult to identify selected text. It functions fine in Chrome and IE. 

Regards,

**Comment by dianaprajescu** [comment]
@javeriaanwer does this happen on our [website](https://www.froala.com/wysiwyg-editor/) too?

By default Firefox makes the background of the selected text always blue, no matter what background color (dark or light) the text has. It is possible that you have some CSS rules that are causing this.

**Comment by javeriaanwer** [comment]
No, it does not happen in our website, I created an example on code pen . please see 
https://codepen.io/Javeria_Anwer/pen/goObqd

PS: Open this in firefox and Select all in froala editor. 

![image](https://user-images.githubusercontent.com/25203829/33867316-b16b5f34-df1d-11e7-828d-1014cac9703a.png)
