### ISSUE TITLE
 Heading formatting is not applied on text 

### ISSUE THREAD

**Issue by javeriaanwer** [froala/wysiwyg-editor#2412]
Hi,

Steps to Produce Error:

1. Select Text and set Font size to 8 (just for example)
2. Select Text again and Set Heading 1

You can see font size is not increased after formatting.

Regards,

**Comment by dianaprajescu** [comment]
Font size is applied inline to the selected text. Selecting an option from Paragraph Format (i.e. Heading 1) will change the paragraph type form a P tag to a H1 tag, but will not remove the existing inline style. This is the intended behavior, and it is the way text editors usually work. If you want to remove the inline style you have to use clear formatting.
