### ISSUE TITLE
Clear Formatting does not clear Paragraph Format

### ISSUE THREAD

**Issue by javeriaanwer** [froala/wysiwyg-editor#2414]
Hi,

Clear formatting should clear paragraph format or set its format to Normal, but its not working like this. How can I achieve this?

**Comment by dianaprajescu** [comment]
Text formatting refers to CSS properties set on the selected text. It is not meant to change the paragraph format. To achieve this, you could either change the current implementation for the Clear Formatting button or create a [custom button](https://www.froala.com/wysiwyg-editor/docs/concepts/custom/button).
