### ISSUE TITLE
Polmer Framework Plugin

### ISSUE THREAD

**Issue by Zynde** [froala/wysiwyg-editor#2416]
This is not really an issue but a request really.

I would love to see a Polymer 2 Framework Plugin. I would love to use Froala in my project but have had a few issues trying to get it going in Polymer.

Thanks

**Comment by stefanneculai** [comment]
Thanks for the `feature-request`, @Zynde. We have this on our TODO list already.

**Comment by Zynde** [comment]
@stefanneculai Thanks. Any timeline?

**Comment by beyondcreed** [comment]
Hi Stefan, any updates on this? We are about to either write Polymer binding or look into alternative editor.

**Comment by stefanneculai** [comment]
Unfortunately, we cannot provide an ETA for it yet.
