### ISSUE TITLE
About text-indent for <P>

### ISSUE THREAD

**Issue by yunClouds** [froala/wysiwyg-editor#2417]
##### Expected behavior.
Sometimes , There are some scenes that we just want the first line of the <p> to indent。（like the style text-indent: 2em;)

##### Actual behavior.
Now the button " indent" is made the whole <p> margin-left ,

##### Steps to reproduce the problem.

![image](https://user-images.githubusercontent.com/26613310/33868482-3c4f4d3e-df3e-11e7-98b6-4104241e0480.png)

##### OS.
angular-froala-wysiwyg": "^2.7.2-1",

##### Browser.
chrome & ie

suggest to add this function  OR if there any another way to solve this。 THANKS

**Comment by stefanneculai** [comment]
@yunClouds the current behavior for indent action is the correct one. I marked this as a `feature-request` and we might add it in the future.

**Comment by kauanmocelin** [comment]
I didn't found this feature on froala v4. Please, help me to find how to add that to my toolbar.
