### ISSUE TITLE
On iOS if an image is embedded in the editor, backspace will reload the image

### ISSUE THREAD

**Issue by chrisdeeming** [froala/wysiwyg-editor#2418]
##### Expected behavior.
Other browsers do not reload the image when the editor content changes.

##### Actual behavior.
Backspaces and I think new lines cause the image to briefly disappear, before being reloaded.

##### Steps to reproduce the problem.
Insert an image into the editor from a URL. Add some text and then remove some of the text. There's a noticeable flash. If you inspect the "Network" tab via the dev inspector of macOS Safari while the iOS device is connected, you will see a network request for the image.

##### Browser.
Any iOS browser.

**Comment by chrisdeeming** [comment]
I can't say I agree with the "enhancement" classification, unfortunately.

Not being able to see what you're typing or deleting should be considered a reasonably high priority bug.

**Comment by belazor** [comment]
This is quite clearly a bug, it makes it impossible to see what you're doing when deleting content on mobile. 

Please resolve this, as it significantly impacts usability on mobile.

**Comment by JakeBooher** [comment]
Here's another video of this happening to show how broken this really is:

https://www.youtube.com/watch?v=fZFC47t2LYQ

**Comment by ellisonpatterson** [comment]
I almost went blind, I wouldn't consider that an enhancement.

**Comment by chrisdeeming** [comment]
Thank you @stefanneculai 👍

**Comment by chrisdeeming** [comment]
@stefanneculai this still appears to be happening, but not on backspace. This time it seems to happen on return.

A user of ours created this video to demonstrate:

https://www.dropbox.com/s/1csv907tudfpczn/ScreenRecording_02-01-2018%2017%3A34%20%281%29.m4v?dl=0

I can reproduce the issue too, but perhaps only (or at least more reliably) on this demo:

https://www.froala.com/wysiwyg-editor/examples/adjustable-height

(We do use the `heightMax` option so it could be related).

Could this be re-opened please?

**Comment by chrisdeeming** [comment]
@stefanneculai unfortunately we're still having reports of slightly abnormal behaviour with this one (after upgrading to 2.7.6):

https://www.dropbox.com/s/4b9tm6xbktul4do/freola-bug1.mp4?dl=0

**Comment by stefanneculai** [comment]
@chrisdeeming at this moment we're not doing any special things on enter/backspace. What is happening now is coming from how the browser handles it.

**Comment by chrisdeeming** [comment]
Thanks @stefanneculai. It does seem similar to what was reported before, in that it does appear as though the image is redrawn which seems odd.

That said, I haven't tried to reproduce it in other editors. That might be telling... I'll report back.
