### ISSUE TITLE
line_breaker plugin throw errors in IE when iframe option is enabled

### ISSUE THREAD

**Issue by cauethenorio** [froala/wysiwyg-editor#2419]
##### Expected behavior.
When I hover at the table bottom I expect to see the "line break" floating icon, which when clicked would insert a new line after the table.

##### Actual behavior.
With iframe option enabled, when I hover the mouse cursor over the table bottom, I got a lot of "Object doesn't support property or method 'closest'" JS errors on browser console.

##### Steps to reproduce the problem.
Create a editor instance with iframe option enabled, insert two tables and try to insert a line between them using the line-breaker plugin.

##### OS.
Windows 7

##### Browser.
IE 10

**Comment by stefanneculai** [comment]
@cauethenorio are you using the latest 2.7.3 version?

**Comment by cauethenorio** [comment]
Yes @stefanneculai it happened with the last version.
