### ISSUE TITLE
Console error when pasting in edge

### ISSUE THREAD

**Issue by topherdavis** [froala/wysiwyg-editor#2420]
##### Expected behavior.
(Describe expected behaviour here)
Paste in edge should not result in a console error.
##### Actual behavior.
(Describe actual behaviour here)
Pasting in edge results in a console error.
##### Steps to reproduce the problem.
(Describe the steps to reproduce the problem here)
1. Go to: https://www.froala.com/wysiwyg-editor
2. Paste in the editor

##### OS.
(OS name and version here)
win10

##### Browser.
(Browser name an version here)
edge

![image](https://user-images.githubusercontent.com/1301399/33912103-2ab01f10-df5a-11e7-8c50-7fb008915044.png)

**Comment by jemunk** [comment]
I also see automatic reportings from our site, regarding this code line from the minified froala_editor.min.js:
....
(s=u.get(0).innerHTML,b.selection.restore(),b.events.enableBlur());var a=**s**.match(/(class=\"?Mso|clas
...
It says that **s** is undefined

We are using the latest version 2.7.3

**Comment by jemunk** [comment]
How come aren't we getting any respond to this error?

**Comment by stefanneculai** [comment]
@topherdavis @jemunk could you please let us know where you're pasting from? Thank you.

**Comment by jemunk** [comment]
@stefanneculai  I was really hoping that by pointing out the code line that fails, you would be able to locate that in your source. 
So far we haven't got any reports from users having problem pasting, so I am unaware if the error affects the user. But our automatic error reporting from the clients has so far recorded 46 occurrences over the last 7 days.

**Comment by stefanneculai** [comment]
@topherdavis @jemunk it's fixed on the current master branch from Github and will be included in release 2.7.4.
