### ISSUE TITLE
Bullets doesn't show up

### ISSUE THREAD

**Issue by mikolajkosmal** [froala/wysiwyg-editor#2424]
##### Expected behavior.
Editor should show bullets.
##### Actual behavior.
Editor doesn't show bullets

##### Steps to reproduce the problem.

![froala](https://user-images.githubusercontent.com/25504119/33995556-a1373db4-e0de-11e7-8993-ed4b482c7dec.gif)

##### OS.
OSX Sierra

##### Browser.
Chrome 63.0.3239.84

**Comment by stefanneculai** [comment]
@mikolajkosmal most likely you have some CSS on the page which removes the bullets for lists inside the editor.
