### ISSUE TITLE
HTML Entities within attributes are converting to special characters

### ISSUE THREAD

**Issue by sirtastic** [froala/wysiwyg-editor#2431]
##### Expected behavior.
Entities within html attributes should never result in a special character.

##### Actual behavior.
Entities added to element attributes are converted to respective special characters. 

##### Steps to reproduce the problem.

- Visit the [Froala Full Feature Editor Demo](https://codepen.io/bleutzinn/pen/xRGVGE) 
- Include an html element using the code view.
(_only tested `<img>` + `alt=""`, and `<a>` + `title=""`._) 
- Add a relevant attribute to your element and include an entity such as `&rarr;`. 
(_In my testing the amerpsand entity `&amp;` and space `&nbsp;` were the only ones that would remain unchanged._)
- Toggle code view off/on and check your included entity in code view. You should see it has been changed. 

**Snippet you can use to test:**
```html
<img src="https://www.festisite.com/static/partylogo/img/logos/google.png" alt="google&nbsp;&rarr;">
```

**Comment by stefanneculai** [comment]
@sirtastic it's fixed on the current master branch (v2.7.4).
