### ISSUE TITLE
Unable to configure special character sets

### ISSUE THREAD

**Issue by bboyle** [froala/wysiwyg-editor#2432]
##### Expected behavior.
Able to specify a custom set of special characters as documented: https://www.froala.com/wysiwyg-editor/docs/options#specialCharactersSets

##### Actual behavior.
The default special character set is always shown.

##### Steps to reproduce the problem.
Minimal test on codepen: https://codepen.io/bboyle/pen/rpxxjd?editors=0010

##### OS.
Win 10

##### Browser.
Opera

**Comment by bboyle** [comment]
thanks!

**Comment by wkurtz** [comment]
the latest version of froala Editor is 2.7.3 (12-11-2017), seems this doesn't work in this version as becribed
is there a way to have this fix in a new production version? Is there a scheduled release date?

**Comment by stefanneculai** [comment]
@wkurtz this is fixed in version 2.7.4 already released.
