### ISSUE TITLE
Unable to make edits in code editor view "codeMirror" (from jQuery UI Modal window)

### ISSUE THREAD

**Issue by angusgrant** [froala/wysiwyg-editor#2434]
##### Expected behavior.
Hi when switching to code editor mode I expect to be able to add, cut , paste and edit the HTML source contents in this window.

##### Actual behavior.
The actual behaviour I'm experiencing is that I am unable to add or update contents from this window... I can remove contents but that is the only function I appear to have access too. 

##### Steps to reproduce the problem.
Click on the text I want to edit and it brings up a jquery UI modal with the Froala editor embeded (that allows me to edit the contents) Now Click on the code editor icon it switches to the code editor view however when I try and edit the html say adding a anchor link `<a href="/my test">My test</a>` my changes are not reflected on the front end and swiching back to the Froala WYSIWYG editor view my changes are not retained... see  https://jsfiddle.net/23c5gnz4/19/
I see no errors in the developer console.... Pls Advise?

##### OS.
OS Windows

##### Browser.
Browser Chrome 63 and FF 58b11

**Comment by stefanneculai** [comment]
@angusgrant we just checked this and it appears that somehow the `modal: true` option (http://api.jqueryui.com/dialog/#option-modal) from jQuery UI is preventing making those changes. And [here](https://github.com/jquery/jquery-ui/blob/master/ui/widgets/dialog.js#L868) is the code from jQuery UI which does that.
