### ISSUE TITLE
contentteditable=false element stripped when cut/copy and pasting

### ISSUE THREAD

**Issue by achambers** [froala/wysiwyg-editor#2435]
##### Expected behavior.
1. Highlight line of text that contains a `contenteditable="false"` element at the beginning.
2. Cut line of text (`cmd + x`)
3. Paste line of text (`cmd + v`)
4. Line of text is as it was and includes the `contenteditable="false"` element

##### Actual behavior.
1. Highlight line of text that contains a `contenteditable="false"` element at the beginning.
2. Cut line of text (`cmd + x`)
3. Paste line of text (`cmd + v`)
4. `contenteditable="false"` is missing and only plain text is pasted.

##### Steps to reproduce the problem.
See above

#### Extra context

This only _seems_ to happen when the `contenteditable="false"` element is the first element in the text line. Even if there is a space as the first character everything works as expected.

When `contenteditable="true"`, this is not an issue.

Interestingly, when pasting the content in via pastebot (a clipboard manager) the `contenteditable="false"` is correctly pasted. Maybe this doesn't trigger some sort of event that the normal paste does.

I have also knocked up a demo of a vanilla content editable div that contains the `contenteditable="false"` element and subscribes to the `paste` event and you can see that the pasted context does still include the `contenteditable="false"` element. You can see it [HERE](https://bird-flight.glitch.me/). Just open the debugger and follow the reproduction steps above.

When subscribing to the `froalaEditor.paste.before` event, however, the `contenteditable="false"` element is already removed.

##### OS.
macOS Sierra - v10.12.6

##### Browser.
Chrome Version 63.0.3239.84
Safari Version 11.0.2
Firefox Version 57.0.1

**Comment by achambers** [comment]
I'm still trying to nail down exactly where this is occurring and I'm 99% sure it is somewhere in the froala code but I can't confirm. Hoping someone here can help me steer this issue in the right direction.

**Comment by achambers** [comment]
Pretty sure this comes from the `_handleCopy()` function.

**Comment by achambers** [comment]
Ok, have finally nailed this down to froala css.

```css
.fr-element [contenteditable=false] {
  user-select: none;
  -o-user-select: none;
  -moz-user-select: none;
  -khtml-user-select: none;
  -webkit-user-select: none;
  -ms-user-select: none;
}
```

**Comment by stefanneculai** [comment]
@achambers that CSS is being used to prevent selecting the text inside contenteditable="false". Adding that CSS would allow indeed selecting the text, however, it is not the best approach. We're working on something different which would allow adding non-editable zones without making use of the `contenteditable="false"`.

**Comment by stefanneculai** [comment]
We run few more tests and it appears that those CSS lines are no longer necessary. Last commit fixes it.
