### ISSUE TITLE
Wrong iframe height on Firefox

### ISSUE THREAD

**Issue by thejahweh** [froala/wysiwyg-editor#2437]
##### Expected behavior.
Correct height.

##### Actual behavior.
The iframe has not enough height on initial load, so the last paragraph is missing. It gets fixed if you add another break.

##### Steps to reproduce the problem.
Insert multiple initial paragraphs.
Add the Iframe Style: `iframeStyle: 'body>p:last-child{margin:0}'`.

##### OS.
Windows 10

##### Browser.
Firefox 57.0

**Comment by thejahweh** [comment]
I can't really reproduce it, it has something to do with the time of the initialization.

My current workaround:
```ts
froala.on('froalaEditor.initialized', function (e, editor) {
    setTimeout(function() {
        froala.froalaEditor('size.syncIframe');
    }, 250);
});
```
Its quite ugly, because of the 250ms delay. If I set it to 100ms it doesn't work sometimes.

**Comment by stefanneculai** [comment]
That's happening because some of the default styles are being removed. We would suggest doing it like this instead:
```js
iframeStyle: $.FroalaEditor.DEFAULTS.iframeStyle + 'body>p:last-child{margin:0}'
```
