### ISSUE TITLE
Callback after autolinking URLs

### ISSUE THREAD

**Issue by markedmondson** [froala/wysiwyg-editor#2443]
##### Expected behavior.
Prior to the change to using the `keydown` action in 2.7.1, the URL plugin used to use `paste.afterCleanup`, meaning I could chain onto the event and perform additional actions on any URLs. For example looking for internal application links and changing the link title to something else or adding attributes.

Now there's no simple way to do that, unless I'm missing it...?

I'm wondering if we can get a callback method on autolink instead? It'd be a way cleaner place to interface.

##### Steps to reproduce the problem.
No way to chain or perform callback events after auto linking has happened.

##### OS.
All

##### Browser.
All

**Comment by stefanneculai** [comment]
Now there is the `url.linked` event which gets the auto-linked link as a parameter.

**Comment by markedmondson** [comment]
Ah that's amazing, thank you!

**Comment by laharshah** [comment]
I don't see a way to change the link using url.linked event.

'froalaEditor.image.inserted' this event has $img parameter that is jQuery object for the image. Need something similar for url.linked so attributes can be added to the link element. 

Is there any way to do so?

**Comment by stefanneculai** [comment]
@laharshah the event is for auto-linked urls, not for links. For links is best to use the `link.beforeInsert` event and change the attributes there.

**Comment by laharshah** [comment]
@stefanneculai 
Thank you for the quick response. I meant to use that with auto URL. I got that working later. I see that link parameter is actually an object and you can add attribute like this: `link.attrName = 'someValue';` and it worked great!

**Comment by GuilhermeMaziero** [comment]
#teste
