### ISSUE TITLE
Enter Configuration

### ISSUE THREAD

**Issue by inssein** [froala/wysiwyg-editor#2444]
I am using the development version of Froala and just experimenting to see if it is a good fit for our needs. So far, its going pretty well, but little confused by the `enter` configuration.

When I load the editor with content that has `<br />` tags, they get auto converted to `<p></p>`. This struck me as odd, so I googled around, and all I found was documentation for an [enter](https://www.froala.com/wysiwyg-editor/docs/options#enter) option. I then set it to `$.FroalaEditor.ENTER_BR` just as a test, and to my surprise, it all works.

That said, this means the documentation is incorrect, or something unexpected is happening. Pressing enter on the keyboard is still inserting `<p></p>` tags, and shift enter is entering `<br>`.

The documentation for enter states:

> Set the default tag to be used when ENTER key is hit.

However, what is happening instead is `<br/>` in the html is not getting converted, which is what we wanted.

##### OS.
OSx

##### Browser.
Chrome

**Comment by stefanneculai** [comment]
@inssein thank you for your feedback on this. Maybe the docs are not clear enough. The ENTER_P option is indeed converting new lines into paragraphs by default.

**Comment by inssein** [comment]
@stefanneculai what you said directly contradicts what I wrote.

> The ENTER_P option is indeed converting new lines into paragraphs by default.

It is not converting new lines, it seems to only convert old lines.

**Comment by stefanneculai** [comment]
@inssein it does both actually. converts the old lines and the new lines as well.
