### ISSUE TITLE
Is there any options to not filter some styles, tags, or attrs?

### ISSUE THREAD

**Issue by anjorn** [froala/wysiwyg-editor#2446]
##### Expected behavior.
(Describe expected behaviour here)
keep some contents  from third-party editors the same.
##### Actual behavior.
(Describe actual behaviour here)
Contents synced from third-party editors sometimes are filtered. For examples, some inline styles of images will be filtered.
##### Steps to reproduce the problem.
(Describe the steps to reproduce the problem here)

##### OS.
(OS name and version here)

##### Browser.
(Browser name an version here)

**Comment by stefanneculai** [comment]
https://www.froala.com/wysiwyg-editor/docs/options#htmlAllowedAttrs
https://www.froala.com/wysiwyg-editor/docs/options#htmlAllowedStyleProps
https://www.froala.com/wysiwyg-editor/docs/options#htmlAllowedTags
https://www.froala.com/wysiwyg-editor/docs/options#pasteAllowedStyleProps
https://www.froala.com/wysiwyg-editor/docs/options#pasteDeniedAttrs
https://www.froala.com/wysiwyg-editor/docs/options#pasteDeniedTags
