### ISSUE TITLE
atJS arrows selection

### ISSUE THREAD

**Issue by PvanHengel** [froala/wysiwyg-editor#2447]
##### Expected behavior.
When using the atJS plugin via mobile device, with a keyboard attached, the user should be able to use the up and down arrows to change the selected element.

##### Actual behavior.
When using the atJS plugin via mobile device, with a keyboard attached, the arrow keys move the cursor up and down in the editor, the selected element does not change.

##### Steps to reproduce the problem.
Using an ipad with a physical keyboard attached, browse to https://www.froala.com/wysiwyg-editor/examples/at-js in the editor window type the @ and then use the arrows on the keyboard to try to change the selected element, the cursor moves, not the selected element.

##### OS.
iOS 11.x 

##### Browser.
Safari

**Comment by stefanneculai** [comment]
@PvanHengel I marked this as a `wontfix` for now. It looks At.JS made lots of changes recently which are no longer compatible with the way the editor is designed and we're looking forward to adding a built-in solution for the editor.

**Comment by PvanHengel** [comment]
What is the eta for the new solution?  We use this a lot

**Comment by stefanneculai** [comment]
@PvanHengel unfortunately, at this moment we don't have an ETA for it.

**Comment by jturmel** [comment]
@stefanneculai is there anymore movement or plans for built in mentioning functionality? Now that At.js is no longer maintained we're trying to find a solution/replacement for our current setup which is Froala + At.js... https://github.com/zurb/tribute looks nice but doesn't seem to have any editor compatibility yet either.

**Comment by stefanneculai** [comment]
We're going to add a built-in mention plugin -https://wysiwyg-editor-roadmap.froala.com/public/ideas/5047. I would encourage you to upvote it on our roadmap so that it gets more priority.
