### ISSUE TITLE
using data-attribute selectors in 'htmlAllowedEmptyTags' causes syntax error in Edge

### ISSUE THREAD

**Issue by Smashr** [froala/wysiwyg-editor#2448]
Hey guys,

The following will cause an unexpected "Syntax Error" in Edge on init. Works as expected in Chrome.

Edge Console:   SCRIPT5022: SyntaxError

Tested with options:
htmlAllowedEmptyTags: ['textarea', 'a', 'iframe', 'object', 'video', 'style', 'script', '.fa', '*[data-delay]'', 'path', 'span', 'i', 'canvas', 'div' ]

The error is caused only when using attribute selectors in the list. Class selectors work fine, so do tag selectors.

Works perfectly in Chrome.

Thanks.

**Comment by stefanneculai** [comment]
@Smashr are you getting the same error if you use only `[data-delay]` instead of `*[data-delay]`?

**Comment by Smashr** [comment]
Yes, only in Edge though.

We are probably going to circumvent this by adding a class to the containerbefore initing Froala and then specifying that class in the htmlAllowedEmptyTags, in case this issue is not resolved.

Cheers and happy holidays ! :)

**Comment by stefanneculai** [comment]
@Smashr sorry for the delayed response. We've just tested this and the error is not there anymore when using only `[data-delay]` instead of `*[data-delay]`.
