### ISSUE TITLE
Electron integration, images

### ISSUE THREAD

**Issue by pdehne** [froala/wysiwyg-editor#2450]
I try to integrate froala into an electron app. It works fine except for images with relative urls, which are (naturally) not requested from the correct server. The froala editor is hosted in a html page that is loaded from the filesystem after all.

Is it possible to tell froala where to download images from?

E.g. the currently edited source contains:
`<img src="/images/image.png">`

and froala should load the image from
http://www.some-server.com/images/image.png

**Comment by stefanneculai** [comment]
@pdehne it is best to use absolute paths in this case.
