### ISSUE TITLE
Pasting text with superscript/subscript from Google Docs removes formatting

### ISSUE THREAD

**Issue by ashwini0529** [froala/wysiwyg-editor#2451]
##### Expected behavior.
- Go to Google Docs
- Copy text that contains superscript/subscript
- Paste in editor
- Should look as it is

##### Actual behavior.
Loses formatting 

##### Steps to reproduce the problem.
- Go to Google Docs
- Copy text that contains superscript/subscript
- Paste in editor
- Loses formatting 

##### OS.
Mac OSX

##### Browser.
Chrome Version 63.0.3239.84 (Official Build) (64-bit)

**Comment by dianaprajescu** [comment]
@ashwini0529 Google Docs uses inline style for superscript/subscript formatted text. By default, the editor does not keep the `style` attribute on paste. You can change this behavior using the `pasteDeniedAttrs` option: https://www.froala.com/wysiwyg-editor/docs/options#pasteDeniedAttrs.

**Comment by dianaprajescu** [comment]
@ashwini0529 Please make sure that you are using the latest editor version from GitHub, when trying `pasteDeniedAttrs` option.
