### ISSUE TITLE
fontSizeDefaultSelection not working

### ISSUE THREAD

**Issue by suryaiiit** [froala/wysiwyg-editor#2452]
I'm trying to set the default Font Size to 30 as given here - https://www.froala.com/wysiwyg-editor/docs/options#fontSizeDefaultSelection

It shows fine, but when I place my cursor and start typing it is going back to 16 font Size, please check.

Here is the codepen - https://codepen.io/suryaiiit/pen/aEpzyN

Thanks

**Comment by stefanneculai** [comment]
@suryaiiit that option is referring to what is displayed by default when there is no selection in the editor. For what you're trying to achieve, please see: https://wysiwyg-editor.froala.help/hc/en-us/articles/115000817105-How-can-I-set-a-default-font-style-.

**Comment by suryaiiit** [comment]
But that would set all the previously written Froala documents also to this Font Size. I want to do this only for the newly created documents. Also what is the purpose of fontSizeDefaultSelection if it doesn't set the text/document font size?

**Comment by stefanneculai** [comment]
> that option is referring to what is displayed by default when there is no selection in the editor. It reflects only in the toolbar, not on the editor text.

I marked this as a `feature-request` so that we can add an option later on for specifiyng the default style.

**Comment by JaxonWright** [comment]
What is the point of this option? Why would you want to display a certain size/font only for it to change when actually using the editor?

Has any progress been made to make this do what users would expect it to?

**Comment by jhays89** [comment]
Bump ^

**Comment by jhays89** [comment]
@JaxonWright This might be late but for anyone looking for a work around:
_example below is in Vue2_

```
// Capture context
var self = this;

// Hook into focus event:
froalaConfig: {
   ...,
   events: {
      'froalaEditor.focus': function (event, froalaObject) {
         self.setDefaultFontStyles(froalaObject);
      }
   },
   ...
}

...
// Set defaults
setDefaultFontStyles(froalaObject) { 
   var editor = this.$refs.froalaEditor; // Vue specific
   
   if(editor.oldModel === '' && editor) { // Check if there is any content
      froalaObject.format.apply('p');
      froalaObject.inlineStyle.apply('color: #ffffff; font-size: '18px'; font-family: 'Roboto');
   }
}
```
