### ISSUE TITLE
Formatting should apply to a word when selection is collapsed inside a word

### ISSUE THREAD

**Issue by theknet** [froala/wysiwyg-editor#2454]
##### Expected behavior.
Moving the caret anywhere within a word (without actually highlighting), and applying formatting (bold, underline), should expand the selection and apply the formatting to the whole word. (Similar behavior is part of Pages/Word etc).

##### Actual behavior.
Currently the button for bold highlights but nothing is actually changed visually, I suspect an empty <b> element is added into the text

##### Steps to reproduce the problem.
* Type a sentence
* Move the caret into the center of a word (make sure the selection is collapsed)
* Click Bold

##### OS.
MacOS 10.13.2

##### Browser.
Safari 11.0.2 (tested with FF too)

**Comment by stefanneculai** [comment]
@theknet thanks for the `feature-request`.
