### ISSUE TITLE
Word paste plugin inserts unnecessary characters in Editor while copying from MS Word in Production package

### ISSUE THREAD

**Issue by ShanmugaPriyanV** [froala/wysiwyg-editor#2455]
Tried to copy paste some paragraphs from MS Word to Editor (2.7.2). The copy paste worked  in development package in application server and also in local deployment . 

However, when generated a production package (Pprod), deployed in application server and copy pasted the same content from the MS Word to Editor, the editor in-turn introduced some unsupported characters in place of spaces after each line.

Additionally, please make note that while generating the production package (Pprod), the Editor didn't work as expected. As a work around, we copied all the JS files(in bower component folder of froala editor)  to a app folder where all the html and js files resides.

Please refer the attached Sample text.docx which is used to copy paste the data to editor to replicate the issue.

Kindly refer the screenshot Editor_Screenshot.jpg captured while replicating the issue.

[Sample text.docx](https://github.com/froala/wysiwyg-editor/files/1600379/Sample.text.docx)
![editor_screenshot](https://user-images.githubusercontent.com/20870994/34521539-27620758-f0c9-11e7-98bf-f0eb8bb64fdb.JPG)

Please let us know if any other details is required. Thanks!

**Comment by stefanneculai** [comment]
@ShanmugaPriyanV are you able to reproduce this on our website, or at least send us a link to a page where we can reproduce it?

**Comment by ShanmugaPriyanV** [comment]
@stefanneculai ...It works correctly in your website but in my production package it's not working.

 On further debugging im able to find the difference was that in development environment the charset was "**UTF-8**" but in production it is "**windows-1252**".

 I couldn't override that object. I have attached the screenshots.

**Screenshot in Development Environment**
![shaancp](https://user-images.githubusercontent.com/20870994/34765590-eef60e92-f617-11e7-91b6-2233917ac69f.jpeg)

**Screenshot in Production**
![shaanserv](https://user-images.githubusercontent.com/20870994/34765601-f567f13c-f617-11e7-80b5-136610e88383.jpeg)

**Comment by stefanneculai** [comment]
@ShanmugaPriyanV we've tried to reproduce this in multiple environments without success. If you would like to override the HTML which gets in there, I would recommend to use the `paste.before` event and replace those characters with empty space.
