### ISSUE TITLE
linkEditButtons results in empty edit link toolbar

### ISSUE THREAD

**Issue by theknet** [froala/wysiwyg-editor#2456]
##### Expected behavior.
Customizing the `linkEditButtons` property should update the toolbar that appears when focusing on a link. If an empty array is set the toolbar should remain invisible.

##### Actual behavior.
Setting anything in `linkEditButton` results in an empty toolbar with an array above.

##### Steps to reproduce the problem.
Create a Froala instance with a linkEditButtons property

CodePen (Full Featured Example): https://codepen.io/Froala/pen/PpgxGL

##### OS.
MacOS 10.13.3

##### Browser.
Safari 11.0.2

**Comment by theknet** [comment]
I would propose that this is a bug. The feature is supported but even if I only want to show the remove link button, if I update the linkEditButtons as supported, I see no toolbar, only the arrow pointing to the content.

**Comment by stefanneculai** [comment]
@theknet we just checked this. The link edit popup is designed to be able to contain other things, not only buttons. Therefore, we introduced a better approach. To disable the link edit popup, use the following code instead before initializing the editor:

```js
$.FroalaEditor.POPUP_TEMPLATES.link.edit = null;
```

**Comment by theknet** [comment]
I'm afraid this does not resolve the issue. As per the documentation, users should be able to configure an array of Froala buttons to appear in the link edit popup:

https://www.froala.com/wysiwyg-editor/docs/options#linkEditButtons

However, as demoed in the following link, this does not work. In my particular use case I do not wish to remove the popup entirely, I'd like to show a subset of the controls Froala provides. This is still an unresolved bug.

https://codepen.io/Froala/pen/PpgxGL

**Comment by stefanneculai** [comment]
@theknet thanks for bringing this to our attention. Should be fixed now on master.

**Comment by theknet** [comment]
Awesome. Thank you!
