### ISSUE TITLE
Pasting images/text from word inserts incorrect images when performing a subsequent paste task

### ISSUE THREAD

**Issue by marissahart** [froala/wysiwyg-editor#2457]
##### Expected behavior.
I see the second set of images I pasted and not a copy of the first set of images. We believe that this bug was introduced in version 2.7.2 as it seemed ok in 2.7.1 when we swapped versions locally.

##### Actual behavior.
I see a duplicate copy of the first images I pasted when I paste the second time with the new images.

##### Steps to reproduce the problem.
- Create/open a word document that contains multiple images and text
- Select 2-5 images containing some text and copy to clipboard using cmd-c or right click & copy
- Navigate to froala - https://www.froala.com/wysiwyg-editor
- Right click into froala and paste contents of clipboard
- Select “Keep” when prompted to keep or discard MS formatting (believe bug exists in both scenarios)
- Navigate back to the word document
- Select different images/text
- Right click and copy the newly selected images / text
- Navigate back to froala and the originally pasted images
- Hit enter a few times to create a space
- Paste the second set of images that were copied into the wysiwyg below the first images
- Select “Keep” when prompted to keep or discard MS formatting

##### OS.
S X Yosemite - Version 10.10.5

##### Browser.
Google Chrome - Version 63.0.3239.84

**Comment by stefanneculai** [comment]
@marissahart would it be possible to send us a doc you're pasting from?

**Comment by marissahart** [comment]
[Brochure Title.docx](https://github.com/froala/wysiwyg-editor/files/1612589/Brochure.Title.docx)

**Comment by stefanneculai** [comment]
Nice catch!
