### ISSUE TITLE
Image change alignment on clicking Image Caption Option. 

### ISSUE THREAD

**Issue by javeriaanwer** [froala/wysiwyg-editor#2458]
Hi,

I am facing this issue, image changes its alignment automatically when I select Caption option on it. below is froala code:

```
$('#editor').froalaEditor({
            fullPage: true,
            useClasses: false            
        });

```
Issue is shown in attached video.
[ImageWCaption.zip](https://github.com/froala/wysiwyg-editor/files/1602937/ImageWCaption.zip)

**Comment by javeriaanwer** [comment]
It is only occurring when i am using option useClasses : false.

**Comment by stefanneculai** [comment]
@javeriaanwer could you please check you're using the latest version 2.7.3?

**Comment by javeriaanwer** [comment]
no, its 2.7.2

**Comment by stefanneculai** [comment]
@javeriaanwer please use the latest 2.7.3 where this shouldn't happen. If you still have the problem with the latest version just let us know.
