### ISSUE TITLE
Cant Edit Caption after deleting text Completely 

### ISSUE THREAD

**Issue by javeriaanwer** [froala/wysiwyg-editor#2459]
hi, 

I am not able to edit caption after removing text completely. please see attached video.

here is the forala code:

```
$('#editor').froalaEditor({});
```

[CantEditCaptionAfterDelete.zip](https://github.com/froala/wysiwyg-editor/files/1602947/CantEditCaptionAfterDelete.zip)

**Comment by stefanneculai** [comment]
@javeriaanwer are you able to reproduce this on our website as well? What browser and OS are you using?

**Comment by javeriaanwer** [comment]
I am not able to reproduce it on your website. 

Google Chrome: Version 63.0.3239.84 (Official Build) (64-bit) 
OS: Windows 10 Enterprise.

**Comment by stefanneculai** [comment]
@javeriaanwer could you please send us a link to a page where we can reproduce it? Thank you.

**Comment by javeriaanwer** [comment]
hi, please check here: https://codepen.io/Javeria_Anwer/pen/XVZWMQ.

remove image caption text through back space.

**Comment by javeriaanwer** [comment]
I upgraded to 2.8.4, caption is editable now after complete removal of text, but in IE cursor is lost after you delete text from caption, you can see here.

![ezgif com-video-to-gif 6](https://user-images.githubusercontent.com/25203829/47478789-35653100-d844-11e8-9a7c-04a852e0b502.gif)
