### ISSUE TITLE
Is there a recommendation for which font to use for special characters?

### ISSUE THREAD

**Issue by tschoppi** [froala/wysiwyg-editor#2461]
##### Expected behavior.
There exists a recommendation of one font which covers all of the special characters offered through Froala WYSIWYG.

##### Actual behavior.
A combination of Noto Sans, Droid Sans, DejaVu Sans, and Liberation Sans is used to get all special characters to render.

##### Steps to reproduce the problem.
Open the special characters dialog window and check the fonts with the browser dev tools.

##### OS.
Cross-platform

##### Browser.
Chromium 63, Firefox 57

Thanks for getting back to me about this issue. Would be very nice if I could keep the font requirements as low as possible.

**Comment by stefanneculai** [comment]
@tschoppi the fonts used there are the default fonts available on MacOS system.

**Comment by tschoppi** [comment]
![If you want something done right, do it yourself.](http://s2.quickmeme.com/img/4c/4c92aea5a041156e7480456cbd8911f4935a7132f1308bbe2adcd0a93a0fb592.jpg)

I arrived at the conclusion that [DejaVu Sans](https://dejavu-fonts.github.io/) offers the highest coverage, barring two glyphs only; The currency symbols "LIVRE TOURNOIS" and "SPESMILO". 

I will remove those via the [specialCharactersSets](https://www.froala.com/wysiwyg-editor/docs/options#specialCharactersSets) option.

**Comment by stefanneculai** [comment]
@tschoppi on our website we're using `Arial, Helvetica, sans-serif;` and it shows all the characters. When it comes to custom fonts you might be a little limited on what characters can be used. Thanks for sharing your tests which show `DejaVu Sans` as a winner for those who don't want to use the default `Arial, Helvetica` font.
