### ISSUE TITLE
Image pasting error in FireFox

### ISSUE THREAD

**Issue by Urchinstripe** [froala/wysiwyg-editor#2462]
Hey guys! when you paste image in firefox, icon is being pasted instead of the image.

##### Expected behavior.
In Chrome - http://recordit.co/Cjic83afgC

##### Actual behavior.
http://recordit.co/qReFBedoCa

##### OS.
macOS high Sierra

##### Browser.
Firefox 57.0.3

**Comment by stefanneculai** [comment]
Unfortunately, because of the way we get data in the clipboard, pasting images when copied from the Finder is not possible in Firefox.
