### ISSUE TITLE
Quick Insert is on by default and i can't turn it off

### ISSUE THREAD

**Issue by RickyRoller** [froala/wysiwyg-editor#2463]
##### Expected behavior.
In the docs it says quick insert has to be enabled by using `pluginsEnabled: ['quickInsert']`

##### Actual behavior.
Quick insert is enabled by default and even when I use `pluginsEnabled: null` it still shows up

##### Steps to reproduce the problem.
npm installed `froala-editor` and `angular-froala-wysiwyg` and when using the froala element, quick insert is enabled with no apparent way to disable it

##### OS.
Mac OS X Yosemite

##### Browser.
Version 63.0.3239.84 (Official Build) (64-bit)

**Comment by dianaprajescu** [comment]
The value for the `pluginsEnabled` option has to be an array with the plugins you want to include, where `[]` means no plugins and `['image', 'link']` means only the image and link plugins.

The default value for the `pluginsEnabled` option is `null`. This means that there is no value specified for the option and when a plugin's JS file is included (e.g. `quick_insert.min.js`), the plugin is automatically turned on.

If you don't want the Quick Insert plugin you can either not include the plugin's file, or exclude it from the array pasted to the `pluginsEnabled` option.
