### ISSUE TITLE
Editor instance gets destroyed with no matter

### ISSUE THREAD

**Issue by poohitan** [froala/wysiwyg-editor#2465]
##### Expected behavior.
The editor remains working.

##### Actual behavior.
Editor destroys itself with no matter.

##### Steps to reproduce the problem.
It's hard to provide you specific steps-to-reproduce, seems like it happens at random moments while editing the content.
This issue happens even with default editor settings.
Another point is that I was not able to reproduce this on localhost, only on staging.

It's quite similar to this issue, but it was immediately closed and locked for some reason, so I can't comment there https://github.com/froala/wysiwyg-editor/issues/2330

**Please don't close this issue without any explanation.** If this behaviour is intended as kind of "protection" from unlicensed use, please note that. You assert that unlicensed version don't have any limitations except the red banner. 

I'm not the first person who face with this issue, so please help.
If it's an intended limitation, please say that. I want to be sure that it won't reproduce after I purchase the license as it makes the use of editor very annoying and almost impossible.
If it's not an expected behaviour but a bug, please help me to get around of it.

##### OS.
OS X High Sierra

##### Browser.
Firefox Nightly 59

**Comment by mostafaznv** [comment]
I faced with this error too

**Comment by dianaprajescu** [comment]
This happens because you are using the editor incorrectly. Please reach us through our <a href="https://www.froala.com/wysiwyg-editor/contact">contact page</a>, specifying the options you pass during initialization, to help you out with this.

**Comment by poohitan** [comment]
Sorry, but I've mentioned, that I use the default settings... Few people already faced this issue, it means that more people can face it in the future, so why don't you want to solve this issue publicly, to make it possible for others to find this thread and solve the issue too...
And why did you edit my post and delete a comment from another person?..
