### ISSUE TITLE
Converting selected text to h1 tag converts whole paragraph to h1 

### ISSUE THREAD

**Issue by Chandrika-Desai** [froala/wysiwyg-editor#2468]
##### Expected behavior.
Only selected text should move to separate line and add h1 tag

##### Actual behavior.
In a paragraph, if i select a sentence to convert to h1 or h2, whole paragraph is converting to h1.

##### Steps to reproduce the problem.
1.Add a paragraph with 4 to 5 sentences.
2. Select any one sentence and try to convert it to h1 tag.
3. Instead of converting the selected sentence, it converts whole paragraph to h1 tag

##### OS.
Ubuntu 16.4

##### Browser.
Chrome 60.0

**Comment by stefanneculai** [comment]
@Chandrika-Desai the paragraph dropdown is designed to change the entire paragraph to h1/h2, not only the selected text. If you would like to change it as per your request, we would recommend using the format.apply method.
