### ISSUE TITLE
Change font family / size of selected row   

### ISSUE THREAD

**Issue by javeriaanwer** [froala/wysiwyg-editor#2469]
Hi ,

I want to change font family and size of selected row but there is no option available in table options and main toolbar is also disabled. how can I achieve this?

Regards,

**Comment by stefanneculai** [comment]
@javeriaanwer at this moment we don't have a feature for doing this. It is already on our TODO list and it should land in the editor in the following months.

**Comment by javeriaanwer** [comment]
Is this feature released?

**Comment by MursaleenFayyaz** [comment]
Is this feature supported in latest version?
