### ISSUE TITLE
Input fields do not work in modals

### ISSUE THREAD

**Issue by zgorbe** [froala/wysiwyg-editor#2470]
##### Expected behavior.
Modals should allow using text input fields

##### Actual behavior.
Keydown events in input fields and textarea fields are not properly handled inside a modal dialog. Please review the keydown event handler in the $.FE.MODULES.modals module. In that keydown event handler the "event.target" should be checked in the "elseif" condition. Please check the difference between e.currentTarget and e.target. (https://developer.mozilla.org/en-US/docs/Web/API/Event/currentTarget)

##### Steps to reproduce the problem.
The issue can be reproduced by creating a modal dialog with text input or textarea elements.

##### OS.
OS independent

##### Browser.
Browser independent

**Comment by stefanneculai** [comment]
@zgorbe the modals weren't designed initially to be extended. We have more and more requests for doing this and we're working on allowing to use any content inside the modal. An update should come for this shortly.

**Comment by suryaiiit** [comment]
Has this been done? which version??

**Comment by stefanneculai** [comment]
It hasn't been added yet.

**Comment by suryaiiit** [comment]
oh, it was working fine in 2.5 or previous ... do you have any suggestions for me to fix the same!!
If not, when do you think it will fixed? Thanks.

**Comment by stefanneculai** [comment]
Unfortunately, I do not have an ETA for it at this moment.
