### ISSUE TITLE
set default font size and family 

### ISSUE THREAD

**Issue by javeriaanwer** [froala/wysiwyg-editor#2475]
hi,

I am trying to set default font size and family on froala editor, I set default selection but when I click on smart editor it changes its font size to 16 and font family to Times new Roman, how can I change it to selected style. 

please see below: https://codepen.io/Javeria_Anwer/pen/ypvNVM?editors=0010

click on smart editor, you can see its size and family changed to other.

**Comment by stefanneculai** [comment]
See https://wysiwyg-editor.froala.help/hc/en-us/articles/115000817105-How-can-I-set-a-default-font-style-.

**Comment by dcporter44** [comment]
Using .fr-view seems like a poor way to do this. The styles are not saved to the actual content. So if you want different default settings for separate editors in your app, it gets complicated quickly.

**Comment by stefanneculai** [comment]
@dcporter44 another way that you could use is to wrap the editor content into a different class and set the styles for that. It is not recommended to use inline styles, but rather use stylesheets .

**Comment by craigjennings11** [comment]
Yes, @dcporter44 is right. That blog post is not a valid solution. Instead, Froala should respect the `fontFamilyDefaultSelection` and `fontSizeDefaultSelection` and actually apply those to the default paragraph inside the editor.

**Comment by philipstratford** [comment]
I agree that using the .fr-view class doesn't really address this issue. I want to have User A create a document and save it, and then have User B open it (using a different instance of Froala editor) and, by default, for any text that User B adds to appear in a different colour (a crude form of change tracking), but I can't find any way to set the default font colour for User B.

**Comment by jmiserez** [comment]
Using .fr-view seems to work at first, but then leads to this other closed issue (https://github.com/froala/wysiwyg-editor/issues/3320) where the line-height on <p> tags is always at least as high as the default font-size.
I think the way the formatting/font size button works this is not so easy to fix.

**Comment by shah20** [comment]
using .fr-view sets default font family in application, but when the content is send in mail those font family is used in outlook. It would be good it we can have that same way when we are selecting it form font family dropdown which preserves the font style.

**Comment by omarsumadi** [comment]
This should be fixed - but in the meantime, you can set a default style on all p tags using CSS, then have a set of keypress events:
``` javascript
            initialized: () => {
                  console.log('initialized')
                  const editorInstance = this.$refs.title.getEditor()
                  // Default HTML on Initialization since Inline Styles can't be set on Initialization
                  // Turn into Arrow Function if you need to use this in Vue Context
                  // On Editor Load
                  editorInstance.html.set('<p style="font-size: 40px; font-family: "Times New Roman", Georgia, Serif; color: #444444"><span>​</span><br></p>')
                  editorInstance.events.on('keydown', function (keypressEvent) {
                  if ((keypressEvent.which == 8 && (editorInstance.html.get() === ""))) {
                    keypressEvent.preventDefault();
                    keypressEvent.stopPropagation();
                    // We Set the Default Style for Froala in CSS, then apply that default style for us here so that there isn't cross-transfer problems.
                    editorInstance.html.set('<p style="font-size: 40px; font-family: "Times New Roman", Georgia, Serif; color: #444444"><span>​</span><br></p>')
                    return false;
                  }
                  }, true);
            },
            click: () => {
              const editorInstance = this.$refs.title.getEditor()
              if(editorInstance.html.get() === '') { // Check if there is any content
                    // We Set the Default Style for Froala in CSS, then apply that default style for us here so that there isn't cross-transfer problems.
                    editorInstance.html.set('<p style="font-size: 40px; font-family: "Times New Roman", Georgia, Serif; color: #444444"><span>​</span><br></p>')
                }
            },
```

That way, your CSS is copied over as Default Text.

**Comment by KhurramEdev** [comment]
Any solution? Still couldn't find anyway to solve this issue.

**Comment by ilyaskarim** [comment]
The fontFamilyDefaultSelection can only take effect if we enable the fontFamilySelection option and it only represents the title of the dropdown.
You can set the default font by calling the fontFamily.apply and fontSize.apply methods inside the initialized event.
Please see https://jsfiddle.net/ilyasfroaal/1d4pv28s/.

**Comment by omarsumadi** [comment]
@ilyaskarim I know but everyone wants the same thing: to enable a default style inside the editor rather than having to find backwards ways of doing it. In addition, the placeholder is now off.

**Comment by idengager** [comment]
Seems like the official suggestion is to use `.fr-view` after all 🤨 https://wysiwyg-editor.froala.help/hc/en-us/articles/115000817105-How-can-I-set-a-default-font-style-

**Comment by davedesantis** [comment]
> The fontFamilyDefaultSelection can only take effect if we enable the fontFamilySelection option and it only represents the title of the dropdown. You can set the default font by calling the fontFamily.apply and fontSize.apply methods inside the initialized event. Please see https://jsfiddle.net/ilyasfroaal/1d4pv28s/.

I tried this and it works for me. However, it requires focus, so whatever page the editor is on, will scroll to the editor and mess with the user's flow.
Is there any way to do so without focus? I tried removing the first line, but then nothing happens, font family and size are not applied.
According to https://froala.com/wysiwyg-editor/docs/methods/, only the apply command is required, no focus there. But that doesn't work :-(

**Comment by mhassanedev** [comment]
Any Solution? @stefanneculai

**Comment by abhinav-sriraj** [comment]
Add this to the froala editor options.

This was suggested by official froala tech support.

events: {
        initialized: function(editor){
          // console.log("editor", editor._editor)
          //here we are setting the default values
          editor._editor.events.focus();
          editor._editor.fontSize.apply('16px');
          editor._editor.fontFamily.apply('Open Sans Condensed, sans-serif');
          editor._editor.lineHeight.apply('1.5');
          editor._editor.colors.text('#4a4a4a');
        }
}

**Comment by satas99** [comment]
I solved it this way with jQuery and it worked.

events: {
	'paste.afterCleanup': function (html) {
		var $html =  $(html);
		$html.find("*").css("font-family","Times New Roman");
		return $(document.createElement("div")).append($html).html();
	}
}

**Comment by satas99** [comment]
I solved it this way with jQuery and it worked.

`events: {
'paste.afterCleanup': function (html) {
var 
(html);
$html.find("*").css("font-family","Times New Roman");
return $(document.createElement("div")).append($html).html();
}
}`

**Comment by imransilvake** [comment]
Should have a proper way to update editor font-family....

**Comment by Baspa** [comment]
It's already the year 2024 and still it isn't possible to set the editor font-family and font-size properly..
