### ISSUE TITLE
After copying more than one space

### ISSUE THREAD

**Issue by docikaci** [froala/wysiwyg-editor#2476]
##### Expected behavior.
(Describe expected behaviour here)
Can not automatically add spaces
##### Actual behavior.
(Describe actual behaviour here)
automatically add spaces
##### Steps to reproduce the problem.
(Describe the steps to reproduce the problem here)
copy  something  to  editor
##### OS.
(OS name and version here)
windows10
##### Browser.
(Browser name an version here)
chrome  63.0.3239.84（正式版本） （64 位）
![image](https://user-images.githubusercontent.com/7788102/34709394-06e945da-f552-11e7-8a79-0511275bb5c2.png)

copying from  other editor ！

See the comments below

**Comment by stefanneculai** [comment]
@docikaci could you please let us know where you're copying from?

**Comment by docikaci** [comment]
@stefanneculai     other editor 

example：
https://xiumi.us/studio/v5#/paper/for/new

**Comment by docikaci** [comment]
![image](https://user-images.githubusercontent.com/7788102/34711238-a1e67448-f559-11e7-828a-e4b922c2aa33.png)

**Comment by docikaci** [comment]
![image](https://user-images.githubusercontent.com/7788102/34711306-e1866f86-f559-11e7-97b2-d0bf77eb8f9a.png)
**These spaces lead to my style mess**

**Comment by docikaci** [comment]
@stefanneculai    Can you help me?
