### ISSUE TITLE
on changing alignment of any item in list, it should change all list alignment

### ISSUE THREAD

**Issue by javeriaanwer** [froala/wysiwyg-editor#2477]
hi,

I change alignment on single item of list, it does not change alignment of whole list, as considering list items should work uniformly but they aren't. 

please see reference image.

![listalignmentbehavior](https://user-images.githubusercontent.com/25203829/34757713-f496b658-f5f4-11e7-8669-aedf8841c339.gif)

**Comment by stefanneculai** [comment]
We consider the current behavior as being correct. Select alignment should align each item, not the whole list.
