### ISSUE TITLE
XSS vulnerability in froalaView

### ISSUE THREAD

**Issue by nsamsonov** [froala/wysiwyg-editor#2479]
##### Expected behavior.
froalaView not displaying "javascript:" URLs

##### Actual behavior.
froalaView does not stripe "javascript:" URLs. Seems like the protection against XSS relies on the editor, however, in case of using a RESTful API, the attacker can forge the request and insert a `<a href="javascript: ...">` tag, and then, when displaying the URL in the froalaView, the link is still present.

There is no way for the server to distinguish the malignant code without parsing the content (and it shouldn't be doing that), so I believe, the security checks should be done on the view component

##### Steps to reproduce the problem.
Using the following code on a preview:
`<div id="preview" class="fr-view"></div>`
...
`$('#preview').html('<a href=\'javascript:alert(1)\'>test</a>');`

Also, tested this in Angular 4 using the `[froalaView]="'<a href=\'javascript:alert(1)\'>test</a>'"` directive.

##### OS.
Win 10

##### Browser.
Google Chrome v63

**Comment by stefanneculai** [comment]
@nsamsonov for any problems related to Angular implementation please open an issue on the Angular repo (https://github.com/froala/angular-froala-wysiwyg). The `froalaView` directive is designed only to wrap the output of the editor in the layout required (a DIV with the fr-view class). To sanitize the HTML displayed by the froalaView, we would recommend using the Angular Sanitizer: https://angular.io/api/core/Sanitizer.
