### ISSUE TITLE
fr-original-style=""-Attributes appear in the editor HTML / code view

### ISSUE THREAD

**Issue by Medo42** [froala/wysiwyg-editor#2480]
##### Expected behavior.
When using useClasses=false, froala will bake styles into the "style" attribute for the output HTML, while using the "fr-original-style" attribute to be able to undo this process when loading the HTML back into the editor. Therefore, fr-original-style attributes should only appear in the output HTML, not in the editor.

##### Actual behavior.
Empty fr-original-style attributes can be seen in froala's code view. This may be related to the fix for the earlier issue where empty style attributes were not preserved (issue #2317).

##### Steps to reproduce the problem.
Set up an editor with useClasses=false and create a table. Save the HTML and load it back into the editor, then look at the code view (or simply look at the DOM of the table in the editor).

##### OS.
Ubuntu 16.04 (Xenial), 64-bit

##### Browser.
Chromium 63.0.3239.84

**Comment by pankajmauryaverma123-cloud** [comment]
Hm
