### ISSUE TITLE
Reports that copy and paste stop working in Firefox

### ISSUE THREAD

**Issue by chrisdeeming** [froala/wysiwyg-editor#2484]
##### Expected behavior.
Each copy action to the clipboard should replace the previously copied text in the clipboard buffer.

##### Actual behavior.
Intermittently, copying won't take effect, and the previous contents of the clipboard are pasted instead.

##### Steps to reproduce the problem.
https://drive.google.com/file/d/1bNjuBwDan_vRwFgDPcXrsNBqUD7_Wds1/view&t=65

##### OS.
Windows/macOS

##### Browser.
Firefox

**Comment by Nirjonadda** [comment]
Please check this video: https://giant.gfycat.com/PoorNippyIchthyostega.webm

I think formatting text will have this issue but not plain text? If this video help understanding about this issue.

**Comment by chrisdeeming** [comment]
Here's another demonstration:

https://xenforo.com/community/data/xfmg/video/166/166532-ed792cbb75ea68decec8b919e28cd9a4.mp4

**Comment by stefanneculai** [comment]
@chrisdeeming @Nirjonadda it should be fixed on the Github master. Could you please check that? Thank you.

**Comment by chrisdeeming** [comment]
Thanks @stefanneculai 

@Nirjonadda I've never been able to reproduce the issue myself but I think this Fiddle I created ages ago serves a couple of the files directly from the GitHub master so hopefully it should appear to be fixed in this version?

https://jsfiddle.net/xgg23h82/

**Comment by stefanneculai** [comment]
@chrisdeeming we haven't been able to reproduce it in the jsFiddle. Could you please make a recording? Thanks.

**Comment by chrisdeeming** [comment]
I only provided the Fiddle as an easy way for those who could reproduce the issue before to test it is now fixed. As far as I know that should be the case now.

**Comment by stefanneculai** [comment]
Oh, thanks for confirming that it is fixed now.
