### ISSUE TITLE
Scroll down is not working properly when selected an image

### ISSUE THREAD

**Issue by javeriaanwer** [froala/wysiwyg-editor#2485]
hi, 

I am facing this problem, when I select an image an scroll down, scrolling is not working smoothly. please see attach gif for reference. 

![image](https://user-images.githubusercontent.com/25203829/34927846-2a2ec17c-f9db-11e7-9b06-64d57010957a.gif)
   
and you can also see at here: https://codepen.io/Javeria_Anwer/pen/eyOWdR?editors=0010

here is my code:

 $(function() {
    $('div#froala-editor').froalaEditor({
      height: 300,
      iframe: true
    })
  });

Browser: Chrome

**Comment by stefanneculai** [comment]
@javeriaanwer what OS are you using? Thank you.

**Comment by javeriaanwer** [comment]
OS: Windows 10 Enterprise

**Comment by stefanneculai** [comment]
We just checked this and it looks like there is a problem in Chrome in some cases when position fixed is used. We'll try to find a workaround for this situation, however, for now, it will remain a `wontfix`.

**Comment by liorafar** [comment]
Can we please open this issue again? It really bothers our customer's user experience
They really don't like to work with our editor this way
