### ISSUE TITLE
Impossible to select toolbar options: hyperlink/color picker/image with enter on IE

### ISSUE THREAD

**Issue by mlysak** [froala/wysiwyg-editor#2487]
**Expected behavior:**
user should be able to navigate through toolbar with keyboard and press enter to open hyperlink popup

 **Actual behavior.**
on Internet Explorer pressing enter, sometimes causes popup to flicker for split second but most of time nothing happens and focus is lost. This happens for all buttons that should open popup: color picker, hyperlink, image

**Steps to reproduce the problem.**
Bug reproducible on official demo: https://www.froala.com/wysiwyg-editor
use alt+f10 and try to select hyperlink with keyboard 

**OS.**
Windows 7

**Browser.**
Internet Explorer 11

**Comment by dianaprajescu** [comment]
Usually the `alt` key is used to access menus and navigate through them. Unfortunately, IE makes it impossible to use the `alt` key in javascript. 

You are saying that, when having the Insert Link toolbar button focused, pressing enter will cause the popup to flicker. But how are getting the focus on the Insert Link toolbar button?

**Comment by mlysak** [comment]
I am not sure what you are saying. there is nothing wrong with alt. alt+f10 shortcut works in IE. it moves focus to first button in froala toolbar. then you can navigate with arrow keys. With simple buttons, like bold/underline you can choose them by pressing enter.

However you cannot do that with hyperlink/color picker or any popup based button

![navigation_ie](https://user-images.githubusercontent.com/6990198/35649467-781a0c9c-06d9-11e8-9be9-93ab09a5ac10.gif)

**Comment by mlysak** [comment]
Thank you for fixing this! Now it works like a charm.

**Comment by mlysak** [comment]
This is happening again. This time also when user tries to click button with mouse. 
Bug was fixed with version 2.7.5 with 2.8.1 is back.
