### ISSUE TITLE
Translation Tables and Image 

### ISSUE THREAD

**Issue by Trapdafifou** [froala/wysiwyg-editor#2488]
##### Expected behavior.
I want everything translated to french on my editor.

##### Actual behavior.
I miss some translations on Tables dropdown and Images dropdown.

##### Steps to reproduce the problem.
Add an image into an editor translated to french then click the image and check the "style" selector. The options are still in english. Aswell insert a table and click it to see the dropdown check the cell style and the table style.

##### OS.
Mac Os Sierra 10.12.6

##### Browser.
Chrome Version 63.0.3239.84

**Comment by Trapdafifou** [comment]
I made the translation, i just want to be able to ask for a PR

**Comment by stefanneculai** [comment]
@Trapdafifou a PR would be highly welcome. Thank you. Please update https://github.com/froala/wysiwyg-editor/blob/master/js/languages/fr.js.

**Comment by shahbazmansha25** [comment]
ITS [NICE ](https://jobzalerts.pk/)dear

**Comment by shahbazmansha25** [comment]
here is the time of [jobzalerts](https://jobzalerts.pk/) for the latest jobs in pakistan and may provide jobs careers opportunities all over the world and thanks for apreciate
