### ISSUE TITLE
Some spaces get eaten when pasting text from some pages

### ISSUE THREAD

**Issue by chrisdeeming** [froala/wysiwyg-editor#2491]
##### Actual behavior.
When you copy some text from some web pages, occasionally the leading space after a HTML tag (often links) is lost.

##### Steps to reproduce the problem.
Copy the first paragraph from this page:
https://www.securitylab.ru/news/490786.php?ref=123

Paste it into Froala.

It will look something like this:

![image](https://user-images.githubusercontent.com/2158514/35003006-5ea8d4ac-fae3-11e7-8df0-8c490a8c7961.png)

It's not just links, I've seen it happen with `<em>` tags too. Try the first paragraphs from this page:
http://www.digitalspy.com/tv/black-mirror/news/a847169/black-mirror-jimmi-simpson-uss-callister-spinoff-heard-buzzes/

Star Trek homage comes out as <em>Star Trek</em>homage

I'm not seeing an obvious pattern...

##### OS.
Any

##### Browser.
Seems to be Chrome and Safari in my testing.

**Comment by dianaprajescu** [comment]
@chrisdeeming this is actually not an issue with the editor, but with the website you are copying from. The content that is copied from the website to clipboard does not have spaces. Wherever you would paste that content to it will behave exactly the same as it does in the Froala Editor. You could also try pasting into an email client, Google docs or Notes.
