### ISSUE TITLE
If you drag and drop an unapproved file extension, it will be drag and drop with the img tag.

### ISSUE THREAD

**Issue by largeden** [froala/wysiwyg-editor#2492]
![upload](https://user-images.githubusercontent.com/5575931/35041184-31294e64-fbc7-11e7-9e0d-74725d1d1d36.gif)

##### Expected behavior.
If you drag and drop unauthorized file extensions, an upload warning appears.

##### Actual behavior.
If you drop an unauthorized extension, it will be dropped into the image tag.

##### Steps to reproduce the problem.
Set the file type.
```fileAllowedTypes: ['application/pdf']```
Drag and drop the .txt file.

##### Cause of the problem.
File type checking is not required for drag and drop.
This is because `upload()` checks the file type.

```javascript
//plugins/file.js

    function _drop (e) {

      // Check if we are dropping files.
      var dt = e.originalEvent.dataTransfer;

      if (dt && dt.files && dt.files.length) {
        var file = dt.files[0];

        if (file && typeof file.type != 'undefined') {

          // Dropped file is an file that we allow.
          if (file.type.indexOf('image') < 0 && (editor.opts.fileAllowedTypes.indexOf(file.type) >= 0 || editor.opts.fileAllowedTypes.indexOf('*') >= 0)) { // <- here
//...

          if (file.type.indexOf('image') < 0) { // <- ok

```

**Comment by stefanneculai** [comment]
@largeden what browser and OS are you using? Are all plugins enabled?

**Comment by largeden** [comment]
This is different on windows and mac.

windows 10 chrome:
Drag and drop the file into the editor and the will move to the file download or file view.

mac high sierra chrome:
It looks like the attached screen.

This is because file.js performs image type checking and unnecessary extension checking at the same time.

full.html tested.

**Comment by stefanneculai** [comment]
It is OK to do the filecheck in drop. It does 2 things:
1. If an image is dropped, the file is not inserted so that the image plugin can do the job (`file.type.indexOf('image') < 0`)
2. Checks that the file is allowed (`(editor.opts.fileAllowedTypes.indexOf(file.type) >= 0 || editor.opts.fileAllowedTypes.indexOf('*') >= 0)`). It doesn't make sense to do any processing and get to the upload step.

The last commit should fix by doing a check on the image type instead.

**Comment by largeden** [comment]
![drop](https://user-images.githubusercontent.com/5575931/35390692-9ed6163c-021f-11e8-8932-1a9eea69717e.gif)

max high sierra / firefox

@stefanneculai 
Please check again.

I just created a video with the version you just committed.
I made the following settings.

```html

  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.3.0/codemirror.min.js"></script>
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.3.0/mode/xml/xml.min.js"></script>

  <script type="text/javascript" src="../../js/froala_editor.min.js" ></script>
  <script type="text/javascript" src="../../js/plugins/code_beautifier.min.js"></script>
  <script type="text/javascript" src="../../js/plugins/code_view.min.js"></script>
  <script type="text/javascript" src="../../js/plugins/file.min.js"></script>

  <script>
    $(function(){
      $('#edit').froalaEditor({
        fileAllowedTypes: ['application/pdf']
      })
    });
  </script>
```

This symptom has nothing to do with image.js.
This is a problem because file.js does not do anything if it is not mime type allowed.

If the type is not image or video, you must perform upload () and the error should be indicated by the filter.

**Comment by largeden** [comment]
8c7146d Commit did not resolve the symptom...

```
<p><img src="data:text/plain;base64,66Gc66eI64Sk7Iqk7YGsIOu4lOuhnOq3uCDsiqTtgqgg7JWI64K0DQ3snbQg7YyM7J287J2AIOuhnOuniOuEpOyKpO2BrCDruJTroZzqt7gg7Iqk7YKoIO2MqO2CpOyngOyXkCDtj6ztlajrkJjripQg7JWI64K066y4IOyeheuLiOuLpC4NDeyKpO2CqCDsgqzsmqnsnYQg7JyE7ZW07ISc64qUIOuPhOuplOyduOyXkCDtlbTri7ntlZjripQg65287J207ISg7IqkIO2CpOqwgCDtlYTsmpTtlanri4jri6QuDeyVhOyngSDsiqTtgqjsnYQg6rWs66ek7ZWY7KeAIOyViuycvOyFqOuLpOuptCDslYTrnpjrpbwg7Ya17ZW0IOq1rOunpCDqsIDriqXtlanri4jri6QuDWh0dHBzOi8vcm9tYW5lc3F1ZS5tZS82MjY3DQ3siqTtgqjsnYQg6rWs66ek7ZWY7IugIOq1rOunpOyekOuKlCDslYTrnpjsnZgg7KO87IaM66GcIOygkeyGje2VmOyLnOqzoCDqtazrp6Qg7IOB7ZKIIOuplOuJtOyXkOyEnCDrnbzsnbTshKDsiqQg7YKk66W8IOuwnOq4iSDrsJvsnLzshLjsmpQuDWh0dHBzOi8vcm9tYW5lc3F1ZS5tZS9hY2NvdW50DQ3shKTsuZjrgpgg7IKs7Jqp67Cp67KV7JeQIOuMgO2VtOyEnOuKlCDslYTrnpjsnZgg7J207JqpIOqwgOydtOuTnOulvCDsnb3slrTrs7TshLjsmpQuDWh0dHBzOi8vcm9tYW5lc3F1ZS5tZS82MjIyDQ3qtoHquIjtlZjsi6Ag7IKs7ZWt7J2AIOyVhOuemOydmCDsg4Hri7Qg6rKM7Iuc7YyQ7Jy866GcIOuCqOqyqOyjvOyEuOyalC4NaHR0cHM6Ly9yb21hbmVzcXVlLm1lL2NvbnRhY3QNDS0NUm9tYW5lc3F1ZS5pbw==" alt=""></p>
```

**Comment by largeden** [comment]
![drop3](https://user-images.githubusercontent.com/5575931/35436720-e86382e0-02d2-11e8-8979-b3ac6cb9ae3b.gif)

```javascript
// file.js
    function _drop (e) {

      // Check if we are dropping files.
      var dt = e.originalEvent.dataTransfer;

      if (dt && dt.files && dt.files.length) {
        var file = dt.files[0];

        if (file && typeof file.type != 'undefined') {

          // Dropped file is an file that we allow.
          if (file.type.indexOf('image') < 0) {
            if (!editor.opts.fileUpload) {
              e.preventDefault();
              e.stopPropagation();

              return false;
            }
        //...
    }
```

Simply do not do a file check from drop (), we can get the result we assumed.
