### ISSUE TITLE
Extensions(7z) without a file type can not be uploaded.

### ISSUE THREAD

**Issue by largeden** [froala/wysiwyg-editor#2493]
##### Expected behavior.
Even if there is no mime type, the test must pass.

##### Actual behavior.
Files without mime type can not be uploaded.

##### Steps to reproduce the problem.
Set the file type.
fileAllowedTypes: ['application/x-7z-compressed']
File Upload

##### OS.
Windows 10

##### Browser.
Chrome

##### Cause of the problem.
As far as I know, there are differences between OS and browser, but all files have mime type.
However, there are files that do not actually have a mime type. 7z does not have a mime type.
For Windows 10, the 7z file does not have mime type.

[Mac Firefox]
![ec32fe10a8f4268ac20051ad5d755231](https://user-images.githubusercontent.com/5575931/35042399-d9e5489c-fbcb-11e7-8729-671fcc523932.jpg)

[Win10 Chrome]
![f90f8fd9d73b7a5ea3dee4364269b6da](https://user-images.githubusercontent.com/5575931/35042416-e79a2ef8-fbcb-11e7-86a6-2fd6d631f865.jpg)

I think we should pass the file check if there is no file type.
What do you think?

**Comment by stefanneculai** [comment]
Just checked it. If the mime type is not there, then the file shouldn't pass the upload filter.

**Comment by largeden** [comment]
I'll ask one question.
If there is no file type in the future, is it a policy that will not pass the filter?

**Comment by stefanneculai** [comment]
@largeden that is an interesting debate, however, I think it is unlikely to have no file type in the future. 😄
