### ISSUE TITLE
Text field is not get focused

### ISSUE THREAD

**Issue by dragokas** [froala/wysiwyg-editor#2494]
After clicking in the message field, focus is often not activated. Pressing on some button in BB-code panel helps in this case.

##### Browser.
Used last update: Opera Presto 12.18.

**Comment by dragokas** [comment]
Yes, please, open any topic: https://xenforo.com/community/forums/bug-reports-2-x.91/

**Comment by stefanneculai** [comment]
@dragokas we don't support Opera Presto browser as an official browser because Opera removed the support for it.
