### ISSUE TITLE
Change in font size/font family is not applied on text - IE

### ISSUE THREAD

**Issue by javeriaanwer** [froala/wysiwyg-editor#2495]
in IE i am not able to select font size and format of selected text.

![wordgif](https://user-images.githubusercontent.com/25203829/35084468-ed5ab8d8-fc45-11e7-90d1-d43e0998ae20.gif)

you can also check it from here.
https://codepen.io/Javeria_Anwer/pen/rpQyzw

Browser: IE/ Edge

**Comment by stefanneculai** [comment]
@javeriaanwer when pasting from Word, please make sure you have the Word Paste plugin enabled in order to keep text formatting.

**Comment by javeriaanwer** [comment]
I tried it , its pasting text from word with CSS but not showing pop message of  **_"The pasted content is coming from a Microsoft Word document. Do you want to keep the format or clean it up?"_**

Browser: "Edge"

its working fine in IE. 

here is the code: https://codepen.io/Javeria_Anwer/pen/XVLXmP

and output: 

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/25203829/35371407-a7918014-01b5-11e8-9d7a-aa77963d454d.gif)

**Comment by stefanneculai** [comment]
@javeriaanwer could you send us the document you're pasting from? What Window version and Edge version are you using?

**Comment by javeriaanwer** [comment]
Browser Version: 
Microsoft Edge 38.14393.0.0
Microsoft EdgeHTML 14.14393
 2016 Microsoft

Windows Version:
Windows 10 Enterprise

[Text from Word.docx](https://github.com/froala/wysiwyg-editor/files/1705689/Text.from.Word.docx)

**Comment by stefanneculai** [comment]
Unfortunately, in Edge, we get the content from Microsoft already cleaned-up and we cannot make any additional processing and detect that it's coming from Word.

**Comment by javeriaanwer** [comment]
it is still not working in IE
