### ISSUE TITLE
Background images set by inline styles break when froala_editor.css on same domain as editor

### ISSUE THREAD

**Issue by scottblinch** [froala/wysiwyg-editor#2497]
##### Expected behavior.
Setting a background image on an element via inline styles should not mangle the URL on editor get.

##### Actual behavior.
When froala_editor.css is hosted on the same domain as the edtior, all background image urls that contain a specific protocol (e.g. `https://` or `http://`) get transformed to just `http` or `https`.

##### Steps to reproduce the problem.
https://codepen.io/scottblinch/pen/EoOjZr
The initialize event doesn't seem to be getting triggered so you'll need to make an update in the editor for the preview to update. Notice that when inspecting the preview, the background image is reduced to `background-image: url('https');`. The issue is fixed when deleting the froala_editor css from the CSS pane and instead loading it from the cloudflare CDN.

##### OS.
macOS Sierra 10.12.6

##### Browser.
Google Chrome 63.0.3239.132 (64-bit)

**Comment by stefanneculai** [comment]
@scottblinch this should be fixed on the current Github master.
