### ISSUE TITLE
'html.insert' not inserting elements inline

### ISSUE THREAD

**Issue by mrahhal** [froala/wysiwyg-editor#2502]
Using the following always wraps the element I'm inserting in a paragraph:

```
el.froalaEditor('html.insert', `<span>...</span>`);
```

What I'm trying to do is insert this element inline. Am I doing something wrong, or is there a way to do this?

**Comment by stefanneculai** [comment]
@mrahhal we would be happy to assist if you could provide a jsFiddle.
