### ISSUE TITLE
Add new plugin

### ISSUE THREAD

**Issue by ankitjain28may** [froala/wysiwyg-editor#2504]
Hey, I have created a new plugin for froala editor which will add embedded video on pasting/writing a video url of facebook/youtube and add a link for other links.

I want to add this new plugin to froala editor, can you please guide me how will i add this plugin on your website

**Comment by stefanneculai** [comment]
@ankitjain28may we do not merge outside contributions for new plugins. What we could do instead is to set up a demo on our website for it: https://www.froala.com/wysiwyg-editor/examples. Could you please send us the code here?

**Comment by ankitjain28may** [comment]
@stefanneculai It would be great if you can add the demo on your website which links to this repo. I am sharing the link of the Github repo which contains its code [froala-video-embed-plugin](https://github.com/ankitjain28may/froala-video-embed-plugin).

Thanks a lot

**Comment by stefanneculai** [comment]
@ankitjain28may thanks for sharing the code. We'll have to make some cleanup on it before adding to our website.
