### ISSUE TITLE
Uncaught TypeError: Cannot read property 'pageX' of undefined

### ISSUE THREAD

**Issue by anlumo** [froala/wysiwyg-editor#2505]
##### Expected behavior.

No error messages in console while using the editor.

##### Actual behavior.

Whenever I move the mouse over the editor, I get the following messages for every single mouse event:

`Uncaught TypeError: Cannot read property 'pageX' of undefined`

  | ia | @ | table.min.js:7
-- | -- | -- | --
  | setTimeout (async) |   |  
  | o.(anonymous function) | @ | VM2190:1
  | na | @ | table.min.js:7
  | dispatch | @ | jquery.js:5206
  | elemData.handle | @ | jquery.js:5014

`Uncaught TypeError: Cannot read property 'pageX' of undefined`

  | j | @ | line_breaker.min.js:6
-- | -- | -- | --
  | setTimeout (async) |   |  
  | o.(anonymous function) | @ | VM2190:1
  | k | @ | line_breaker.min.js:6
  | dispatch | @ | jquery.js:5206
  | elemData.handle | @ | jquery.js:5014

##### Steps to reproduce the problem.

I'm using [ember-froala-editor](https://github.com/froala/ember-froala-editor) for this, but it looks like the issue is with jquery, not that package.

* `ember new froala-isolationtest`
* `cd froala-isolationtest/`
* `ember install ember-froala-editor`
* `echo "{{froala-editor}}" > app/templates/application.hbs`
* `ember serve`

Then open http://localhost:3000 in Chrome and move the mouse over the editor while the web inspector is open.

I'm using jquery 3.3.1 with ember 2.15.3.

##### OS.
Windows 10 Creators Update

##### Browser.

Chrome 63

Does *not* occur on Firefox 57

**Comment by dianaprajescu** [comment]
@anlumo we were not able to reproduce this issue. Neither on this repo nor on the ember one. We tried both Windows and MacOS. Could you please test and let us know if the error is present here: http://www.emberwysiwygeditor.com/?

**Comment by anlumo** [comment]
Sorry, this is actually a bug in the Chrome extension Spector, not froala.
