### ISSUE TITLE
IE 11 - Unable to backspace/delete/enter when editing in  Froala

### ISSUE THREAD

**Issue by kishore12** [froala/wysiwyg-editor#2509]
##### Expected behavior.
Users should be able to backspace/delete/enter when editing in Froala

##### Actual behavior.
Users are unable to backspace/delete/enter when editing in Froala

##### Steps to reproduce the problem.
JSFiddle Link - https://jsfiddle.net/gygj3myz/2/

When editing in IE 11, I'm unable to delete any text by using backspace or delete. I'm also unable to hit Enter to start a new line. It doesn't throw any errors in the console so not sure what could be causing the problem.

##### OS.
Windows 10 Pro
10.0.16299 Build 16299

##### Browser.
IE 11
Version - 11.192.16299.0

**Comment by dianaprajescu** [comment]
@kishore12 you are using an older version of the editor. Please update to the latest, which is 2.7.3. Also, the Froala editor requires jQuery 1.11.0 or higher and you are using 1.7.1.
