### ISSUE TITLE
Upload file Icon Missing from Default toolbar

### ISSUE THREAD

**Issue by MarcPinnell** [froala/wysiwyg-editor#251]
Pretty much that's it. All the other buttons appear to be there, but the uploadFile is missing. It can be added by recreating the entire button bar, but seems silly.

**Comment by numbers1311407** [comment]
I disagree that this should not be clarified in the docs.

Overriding the button layout (as a default or an argument) is a fine solution, but it's anti-intuitive and anti-principle-of-least-surprise that both 1) the **default** layout includes **optional plugins** and 2) *some but not all* **plugin** buttons are included as part of the plugin load.

I understand the need, as I assume there will be users who load the full suite of plugins as a package without needing all of them, but if you're going to make the loading of *some but not all* plugins a two-step process, that most certainly should be documented.
