### ISSUE TITLE
Link href value is being emptied 

### ISSUE THREAD

**Issue by BodhiMax** [froala/wysiwyg-editor#2510]
##### Expected behavior.
Pasting html content into the html window should leave the value in href alone.

##### Actual behavior.
HREF value is being emptied out. I think there's some error correction that is overwriting special value formatting. Here is the link format that is being emptied out. These links work in the context of emails and require this format to function: [http://[link]?nps=0]

##### Steps to reproduce the problem.
Paste content with links formatted as above into the html window. Click html off to go to text wysiwyg and then click html on again. Links formatted above are emptied out.

##### OS.
macOS Sierra, Version 10.12.6

Froala version: 4.7.3
Options are linked as below
{
	height: 300,
	key: OMITTED,
	placeholderText: 'Click to add note',
	saveMethod: 'POST',
	saveParam: 'editor_content',
	htmlUntouched: true,
	toolbarButtons : ['fullscreen', 'html', 'paragraphFormat', 'paragraphStyle', 'bold', 'italic', 'underline', 'strikeThrough', '|', 'subscript', 'superscript', '|', 'formatOL', 'formatUL', 'outdent', 'indent', 'align', '|', 'insertTable', 'insertLink', 'insertHR', '|', 'color', 'fontFamily', 'fontSize', '-', 'emoticons', 'specialCharacters', 'selectAll', 'clearFormatting', '|', 'spellChecker', 'help',  '|', 'undo', 'redo']
};

##### Browser.
Chrome Version 61.0.3163.100 (Official Build) (64-bit)

**Comment by dianaprajescu** [comment]
@BodhiMax could you please give us the exact content you are pasting?

In Code View, we tried pasting HTML code with an `A` tag having the `href` value formatted like you said, but it isn't emptied out when switching back to text and then again to Code View.

**Comment by jcreason** [comment]
@dianaprajescu, thanks for replying.  I work with @BodhiMax and below is an example:

`<p style="font-size:13px;"><a href="http://[placeholder_link]">[placeholder_link]</a></p>`

**Comment by dianaprajescu** [comment]
Thanks for your example. This issue is no longer happening with the latest updates from the master branch of this repo.
