### ISSUE TITLE
Browser becomes unresponsive after typing lots of dashes

### ISSUE THREAD

**Issue by RonnyTh** [froala/wysiwyg-editor#2512]
##### Actual behavior.
After typing a line of dashes and an enter the entire browser becomes unresponsive. Tested in Chrome, Firefox and IE/Edge

##### Steps to reproduce the problem.
Open a froala editor for instance on https://www.froala.com/wysiwyg-editor
Type ---------------------------------------------- followed by enter.
=> Browser becomes unresponsive

##### OS.
Ubuntu and Windows

##### Browser.
Chrome, Firefox, IE, Edge.

**Comment by dianaprajescu** [comment]
@RonnyTh this issue is already fixed on the master branch of this repo. The fix will be included in the next release, and then we will also update the editor version on our website.
