### ISSUE TITLE
Uncaught TypeError: Cannot read property 'attributes' of undefined at Image.g.onload

### ISSUE THREAD

**Issue by cahyowhy** [froala/wysiwyg-editor#2513]
hii..
iam try to upload image to my custom server and its work.

btw, because the response is doesnt contain link prop, it raise an error and invoke this function

```
onImageError(ed, err, response) {
      response = JSON.parse(response);
      if (!_.isEmpty(response['data'])) {
        const editor = ed.get('editor');
        // change image err, from response url
        console.log(editor);
        editor.image.insert(ENV.IMG_CDN + response['data'][0].name, true, {name: 'image'},
          Ember.$('img.fr-uploading.fr-error'));
      }
    }
```

my goal is to replace $img object while froala uploading the image with the response from my webserver, with these syntax
```
editor.image.insert(ENV.IMG_CDN + response['data'][0].name, true, {name: 'image'},
          Ember.$('img.fr-uploading.fr-error'));
```

its work on a first try but then it raise an error
`Uncaught TypeError: Cannot read property 'attributes' of undefined at Image.g.onload`

can anyone solve this.. sorry for my bad english. btw i use ember-froala-editor

**Comment by stefanneculai** [comment]
@cahyowhy It is best to use the `image.uploaded` event, return false inside it and then insert the image using the `image.insert` method.
