### ISSUE TITLE
Docs: search field design problem

### ISSUE THREAD

**Issue by connect-technologies** [froala/wysiwyg-editor#2514]
##### Expected behavior.
search result drop down fully visible

##### Actual behavior.
the drop down is hidden partially

##### Steps to reproduce the problem.
goto https://www.froala.com/wysiwyg-editor/docs and try to search for smth

![grafik](https://user-images.githubusercontent.com/13328421/35320381-e497e160-00e3-11e8-96a9-a62dc5f6ed10.png)

##### OS.
win7

##### Browser.
ff58

**Comment by dianaprajescu** [comment]
@connect-technologies thanks for pointing this out.
