### ISSUE TITLE
If you press the Enter key or the Space key after typing the hyphen (-) key continuously, the browser will not respond.

### ISSUE THREAD

**Issue by largeden** [froala/wysiwyg-editor#2515]
##### Symptom
If you press the Enter key or the Space key after typing the hyphen (-) key continuously, the browser will not respond.

------------------------------------------------------------ space key or enter key

##### Browser.
Firefox, Chrome

##### The cause of the problem
I think there is a problem with the regular expression.
```javascript
// url.js
    function _inlineType () {
      var range = editor.selection.ranges(0);
      var node = range.startContainer;

      if (!node || node.nodeType !== Node.TEXT_NODE) return false;

      if (_isA(node)) return false;

      if (_getRegEx().test(_lastPart(node.textContent))) { // <- here
        $(node).before(_convertToLink(node.textContent));

        node.parentNode.removeChild(node);
      }
      else if (node.previousSibling && node.previousSibling.tagName === 'A') {
        var text = node.previousSibling.innerText + node.textContent;

        if (_getRegEx().test(_lastPart(text))) {
          $(node.previousSibling).replaceWith(_convertToLink(text));

          node.parentNode.removeChild(node);
        }
      }
    }
```

**Comment by dianaprajescu** [comment]
This should be fixed on the master branch of this repo. @largeden, could you please test and let us know if everything is okay?

**Comment by largeden** [comment]
@dianaprajescu 
I downloaded the latest brunch but my symptoms are not getting better.
You will have to consider four situations.

1. ---------------------------------------------- space key
2. ---------------------------------------------- enter key
3. --------------------------space key--------------------
4. space key----------------------------------------------

**Comment by largeden** [comment]
@stefanneculai 
Good! 👍
