### ISSUE TITLE
Paste content after copy HTML content doesn't paste in Firefox

### ISSUE THREAD

**Issue by ThePokyWizard** [froala/wysiwyg-editor#2517]
##### Expected behavior.
Paste any content copied after copy a HTML content.

##### Actual behavior.
In Firefox when a HTML content is pasted and after this a link copied is pasted, the link not appear in editor.

##### Steps to reproduce the problem.
1 - Copy HTML content;
2 - Paste the content in editor;
3 - Copy a link and paste in editor;
4 - The HTML content is pasted

##### OS.
Elementary OS Loki
Windows 10 Fall Creators Update

##### Browser.
 Firefox 58

##### Demonstration.
[Screencast from 2018-01-24 15.32.10.webm.tar.gz](https://github.com/froala/wysiwyg-editor/files/1660940/Screencast.from.2018-01-24.15.32.10.webm.tar.gz)

**Comment by stefanneculai** [comment]
@ThePokyWizard this should already be fixed on the current master from Github.

**Comment by ppppaowu** [comment]
![untitled](https://user-images.githubusercontent.com/32115260/35500973-5c0a4a0c-0513-11e8-8eda-040be302daac.gif)
