### ISSUE TITLE
#2515 URL conversion problem after patching.

### ISSUE THREAD

**Issue by largeden** [froala/wysiwyg-editor#2519]
#2515 URL conversion problem after patching.

It was a bug that happened before.
The following values are converted to hyperlinks:

abc.jpg
abc.exe

**Comment by stefanneculai** [comment]
@largeden this is not happening when typing. Could you please double check? :)

**Comment by largeden** [comment]
@stefanneculai
ok, I'll go home and check it again.

**Comment by largeden** [comment]
@stefanneculai 
sorry, this is my mistake.
I tested the url.min.js in the past by applying it incorrectly.
Please close the issue.

**Comment by stefanneculai** [comment]
Thanks for testing!
