### ISSUE TITLE
Editor disappears

### ISSUE THREAD

**Issue by divdax** [froala/wysiwyg-editor#2521]
##### Actual behavior.
Sometimes the editor disappears and the textarea with current content is shown.
The console is empty - no errors.

##### Steps to reproduce the problem.
video: https://vimeo.com/252747410
klick 10 times on a button in the toolbar. the 11th click will destroy the editor and the textarea appears.

##### OS.
macOS Sierra

##### Browser.
Chrome Version 63.0.3239.132

**Comment by dianaprajescu** [comment]
@divdax can this issue be reproduced on our website?

**Comment by divdax** [comment]
Everything fine in you website. I was using some css to hide the license warning on my local dev machine. If i don't hide it everything is fine. What can i do to work locally without license warning?

**Comment by dianaprajescu** [comment]
The warning doesn't change in any way how the editor works and behaves. It makes it possible to test all the editor's features before actually purchasing a license and it can only be removed after the purchase.

**Comment by github-monday** [comment]
I have tested the suggestions and also faced the same editor disappearing problem and finally found the solution.

here is the css trick that will hide the licence warning and also the editor will not disappear on 11th click on any button.

try the following:
<style>
a[href="https://froala.com/wysiwyg-editor"], a[href="https://www.froala.com/wysiwyg-editor?k=u"], a[href="https://www.froala.com/wysiwyg-editor?k=u"] { opacity:0; margin-top:-30px !important }
</style>

I am also using some more css for some added beautification.

<style>
#fr-modal-more-1 { display:none !important }
.fr-qi-helper a.fr-btn.fr-floating-btn { padding-top:10px }
</style>
