### ISSUE TITLE
Poor performance on older Apple devices

### ISSUE THREAD

**Issue by chrisdeeming** [froala/wysiwyg-editor#2523]
##### Expected behavior.
Although older devices are expected to have slower performance, there's something not quite right about Froala performance on the older devices which cannot be replicated in a standard textarea element or even on some other commercial rich text editors. Typing should be as lag free as possible, and backspace behaviour should be fairly smooth.

##### Actual behavior.
Generally typing text is experiencing a very noticeable lag and backspacing to delete text is not performing great.

Here's a video made by one of our customer's users demonstrating the issue:
https://youtu.be/o3fD6Da3OMI

##### Steps to reproduce the problem.
You'll seemingly need an actual live device to test this rather than the Simulator. Just open up the Froala WYSIWYG home page and try typing and/or backspacing through text.

##### OS.
iOS certainly 9 and 10 though it may depend exactly on the hardware; for example the issue can't be reproduced on the iPhone X. May also affect older Android devices.

##### Browser.
Probably any iOS based browser.

**Comment by stefanneculai** [comment]
@chrisdeeming are you able to reproduce this on our website as well?

**Comment by chrisdeeming** [comment]
@stefanneculai  yes, this video should demonstrate that. Worth noting that I've tried to demonstrate poor typing performance in general, but as this is a screen recording, that doesn't quite come across very well (obviously). All I can say about that is that the majority of the taps on the keyboard you see in the video actually occurred well after I actually tapped the screen.

The deleting issue is apparent, though. You'll notice that the editor is very unresponsive, especially after the backspace key is held down for a while.

https://youtu.be/b4td2463l94

**Comment by dianaprajescu** [comment]
@chrisdeeming How old the Apple devices should actually be? We tested on iPhone 6S with iOS 11 and on iPad Air 2 with iOS 11 (initially launched with iOS8) and it seems to be working just perfect on our website.

We also made some changes to the backspace, so we might have some improvements for this in 2.7.4.

**Comment by chrisdeeming** [comment]
Might be a combination of hardware and software - the video I took was on the iPad Mini with iOS 9. I'll happily test - are those backspace changes committed to master yet?

**Comment by dianaprajescu** [comment]
Yes, they are, please test the master version if you can.

You could also try some tips from the Apple forum that might help you speed up the device: https://discussions.apple.com/message/30293501#30293501

**Comment by chrisdeeming** [comment]
The backspace issue seems a lot better and perhaps even typing in general. We'll call that fixed 👍
