### ISSUE TITLE
How do I insert HTML where I want to insert it?

### ISSUE THREAD

**Issue by LieRabbit** [froala/wysiwyg-editor#2525]
##### Expected behavior.
I want to insert `HTML` to '444' when i lose focus
##### Actual behavior.
froala insert `HTML` to '111'
##### Steps to reproduce the problem.
![froala-insert-html-demo](https://github.com/LieRabbit/images/raw/master/froala-insert-html.gif)
##### OS.
mac 10.13.3
##### Browser.
chrome 64.0.3282.119

**Comment by fuqihan** [comment]
Sorry, no such parameter...

**Comment by stefanneculai** [comment]
Please see https://codepen.io/anon/pen/aqoQqp.

**Comment by LieRabbit** [comment]
How can i do it in angular2?
