### ISSUE TITLE
Option to disable custom Froala styles

### ISSUE THREAD

**Issue by wrporter** [froala/wysiwyg-editor#2527]
##### Expected behavior.
I should have an option to disable custom Froala styles that get placed inside the iframe.

##### Actual behavior.
When using `fullPage: true` or not, a lot of custom Froala styles are added to the content and I don't have an option to remove them.

There are some styles that are ruining the layout of tables and other elements that get rendered properly everywhere else, except in the Froala editor. For example, a table with padding and border radius does not render with padding and a border radius in Froala, making it not WYSIWYG.

##### Steps to reproduce the problem.
1. Use the `fullPage: true` option or without.
2. Notice that there are extra styles in the iframe or content
3. There's no way to disable the custom Froala styles

##### OS.
macOS Sierra 10.12.6

##### Browser.
Chrome 63.0.3239.132

**Comment by stefanneculai** [comment]
@wrporter could you please make a jsFiddle? Thanks in advance.

**Comment by wrporter** [comment]
@stefanneculai I think I finally got to the root of the bug! (After many hours of debugging and banging my head against the desk.) Unfortunately, it doesn't manifest in jsFiddle. I was able to get it up on a site though: http://sample.orionhub.org:8000/index.html

Now the explanation:

In the `_initStyle` function in `froala_editor.pkgd.js`, there is code that extracts `cssRules` from `styleSheets` on the document. 

Here's the rub. Those `cssRules` are only populated for each styleSheet when hosted on the same domain. Hence the reason why I can't reproduce in jsFiddle, you can't host the styles on the same domain and must reference a CDN.

Those cssRules, however, do get applied when the styleSheets are hosted on the same domain. 

If you look at the source within the editor iframe, you will see the following styles applied, which come from `froala_editor.pkgd.min.js` and `froala_style.min.css`

```html
<style data-fr-style="true">
html{margin:0px;height:auto;}body{height:auto;padding:10px;background:transparent;color:#000000;position:relative;z-index: 2;-webkit-user-select:auto;margin:0px;overflow:hidden;min-height:20px;}body:after{content:"";display:block;clear:both;}body, body:focus{outline: transparent solid 0px;}body{background: 0px 0px; position: relative; z-index: 2; user-select: auto;}body a{user-select: auto;}body.fr-disabled{user-select: none;}body [contenteditable="false"]{user-select: none;}body [contenteditable="true"]{outline: transparent solid 0px; user-select: text;}body img{cursor: pointer;}body table td.fr-selected-cell, body table th.fr-selected-cell{border: 1px double rgb(30, 136, 229);}body table tr{user-select: none;}body table td, body table th{user-select: text;}body .fr-no-selection table td, body .fr-no-selection table th{user-select: none;}body .fr-video{user-select: none;}body .fr-video::after{position: absolute; content: ""; z-index: 1; top: 0px; left: 0px; right: 0px; bottom: 0px; cursor: pointer; display: block; background: rgba(0, 0, 0, 0);}body .fr-video.fr-active > *{z-index: 2; position: relative;}body .fr-video > *{box-sizing: content-box; max-width: 100%; border: 0px;}body span[style~="color:"] a{color: inherit;}body strong{font-weight: 700;}body table{border: 0px; border-collapse: collapse; empty-cells: show; max-width: 100%;}body table.fr-dashed-borders td, body table.fr-dashed-borders th{border-style: dashed;}body table.fr-alternate-rows tbody tr:nth-child(2n){background: rgb(245, 245, 245);}body table td, body table th{border: 1px solid rgb(221, 221, 221);}body table td:empty, body table th:empty{height: 20px;}body table td.fr-highlighted, body table th.fr-highlighted{border: 1px double red;}body table td.fr-thick, body table th.fr-thick{border-width: 2px;}body table th{background: rgb(230, 230, 230);}body hr{clear: both; user-select: none; break-after: page;}body .fr-file{position: relative;}body .fr-file::after{position: relative; content: "📎"; font-weight: 400;}body pre{white-space: pre-wrap; word-wrap: break-word;}body[dir="rtl"] blockquote{border-left: 0px; border-right: 2px solid rgb(94, 53, 177); margin-right: 0px; padding-right: 5px; padding-left: 0px;}body[dir="rtl"] blockquote blockquote{border-color: rgb(0, 188, 212);}body[dir="rtl"] blockquote blockquote blockquote{border-color: rgb(67, 160, 71);}body blockquote{border-left: 2px solid rgb(94, 53, 177); margin-left: 0px; padding-left: 5px; color: rgb(94, 53, 177);}body blockquote blockquote{border-color: rgb(0, 188, 212); color: rgb(0, 188, 212);}body blockquote blockquote blockquote{border-color: rgb(67, 160, 71); color: rgb(67, 160, 71);}body span.fr-emoticon{font-weight: 400; font-family: "Apple Color Emoji", "Segoe UI Emoji", NotoColorEmoji, "Segoe UI Symbol", "Android Emoji", EmojiSymbols; display: inline; line-height: 0;}body span.fr-emoticon.fr-emoticon-img{font-size: inherit; height: 1em; width: 1em; min-height: 20px; min-width: 20px; display: inline-block; margin: -0.1em 0.1em 0.1em; line-height: 1; vertical-align: middle; background-repeat: no-repeat !important;}body .fr-text-gray{color: rgb(170, 170, 170) !important;}body .fr-text-bordered{border-top: 1px solid rgb(34, 34, 34); border-bottom: 1px solid rgb(34, 34, 34); padding: 10px 0px;}body .fr-text-spaced{letter-spacing: 1px;}body .fr-text-uppercase{text-transform: uppercase;}body img{position: relative; max-width: 100%;}body img.fr-dib{margin: 5px auto; display: block; float: none; vertical-align: top;}body img.fr-dib.fr-fil{margin-left: 0px; text-align: left;}body img.fr-dib.fr-fir{margin-right: 0px; text-align: right;}body img.fr-dii{display: inline-block; float: none; vertical-align: bottom; margin-left: 5px; margin-right: 5px; max-width: calc(100% - 10px);}body img.fr-dii.fr-fil{float: left; margin: 5px 5px 5px 0px; max-width: calc(100% - 5px);}body img.fr-dii.fr-fir{float: right; margin: 5px 0px 5px 5px; max-width: calc(100% - 5px);}body span.fr-img-caption{position: relative; max-width: 100%;}body span.fr-img-caption.fr-dib{margin: 5px auto; display: block; float: none; vertical-align: top;}body span.fr-img-caption.fr-dib.fr-fil{margin-left: 0px; text-align: left;}body span.fr-img-caption.fr-dib.fr-fir{margin-right: 0px; text-align: right;}body span.fr-img-caption.fr-dii{display: inline-block; float: none; vertical-align: bottom; margin-left: 5px; margin-right: 5px; max-width: calc(100% - 10px);}body span.fr-img-caption.fr-dii.fr-fil{float: left; margin: 5px 5px 5px 0px; max-width: calc(100% - 5px);}body span.fr-img-caption.fr-dii.fr-fir{float: right; margin: 5px 0px 5px 5px; max-width: calc(100% - 5px);}body .fr-video{text-align: center; position: relative;}body .fr-video > *{box-sizing: content-box; max-width: 100%; border: 0px;}body .fr-video.fr-dvb{display: block; clear: both;}body .fr-video.fr-dvb.fr-fvl{text-align: left;}body .fr-video.fr-dvb.fr-fvr{text-align: right;}body .fr-video.fr-dvi{display: inline-block;}body .fr-video.fr-dvi.fr-fvl{float: left;}body .fr-video.fr-dvi.fr-fvr{float: right;}body a.fr-strong{font-weight: 700;}body a.fr-green{color: green;}body .fr-img-caption{text-align: center;}body .fr-img-caption .fr-img-wrap{padding: 0px; display: inline-block; margin: auto; text-align: center;}body .fr-img-caption .fr-img-wrap img{display: block; margin: auto;}body .fr-img-caption .fr-img-wrap > span{margin: auto; display: inline-block; padding: 5px 5px 10px; font-size: 14px; font-weight: initial; max-width: 100%; box-sizing: border-box; opacity: 0.9;}body button.fr-rounded, body input.fr-rounded, body textarea.fr-rounded{border-radius: 10px; -webkit-background-clip: padding-box; background-clip: padding-box;}body button.fr-large, body input.fr-large, body textarea.fr-large{font-size: 24px;}
</style>
```

**Comment by wrporter** [comment]
It appears that this is a problem with or without using the iframe option.

**Comment by pablovieiras** [comment]
It would be very useful if there was an option to disable the default style when the '_iframe_' option is _true_!

**Comment by wrporter** [comment]
@stefanneculai Any chance this can get looked at sooner? This is breaking some of our customer workflows.

**Comment by wrporter** [comment]
@stefanneculai I noticed that the "waiting-details" label is still on this issue. Is there anything else I can provide that could help here?

**Comment by stefanneculai** [comment]
@wrporter those styles are needed in order to display the editor elements properly inside the iframe. If you don't want to have them added, as a workaround, you could do the following 2 things:
  1. Don't include the froala_style CSS file on the page you're initializing the editor on.
  2. Use the [iframeStyleFiles](https://www.froala.com/wysiwyg-editor/docs/options#iframeStyleFiles) option so that you can still have the elements inside the editor displayed correctly.

**Comment by wrporter** [comment]
@stefanneculai That's not quite the issue. Whether I'm hosting my froala code on the same domain or not, the styles should behave the same within the editor. This is definitely a bug in Froala.

**Comment by wrporter** [comment]
I submitted a new issue for this at https://github.com/froala/wysiwyg-editor/issues/2614

**Comment by brandonreid** [comment]
My biggest issue was borders around table markup (using froala to edit email templates). To fix this I was able to use the `iframeStyle` option:
`iframeStyle: 'body table tr td, body table tr th { border: 0; }'`

**Comment by atomcorp** [comment]
This was causing us problems. we wanted to use Froala as an HTML email editor, so it couldn't have any external styles. The best way I found to remove these styles was by using the initialised event and jquery

i'm using React and I think it's an old version, but hopefully it gets the idea across.

```jsx
<FroalaEditor
  config={{
    fullPage: true,
    // froala will inline applied styles
    useClasses: false,
    events: {
      'froalaEditor.initialized': (e, editor) => {
        // remove added styles from iframe head
        editor.$html.find('[data-fr-style="true"]').remove();
      },
    },
  }}
/>
```
 This thread confused me so helpfully someone finds the answer they need with this.
