### ISSUE TITLE
Add SAS token to end of file/image url when downloading content into editor.

### ISSUE THREAD

**Issue by rokobasilisk** [froala/wysiwyg-editor#2529]
##### Expected behavior.
Ability to update image/file link before download perhaps with event.
Currently using Azure Blob storage for image storage. Upload works, however a SAS token is required  to be appended to each request to an image URL to authenticate access for a specific amount of time. This needs to be renewed each time the SAS Token expires.

I have searched through events and options, and while you can supply authentication headers, you can't seem to append anything to the image link before calling out to the service to fetch the image.

**Comment by stefanneculai** [comment]
@rokobasilisk the images are fetched by the browser through the `IMG` tag in HTML. As far as we know it is not possible to pass an authentication header to them.

**Comment by waynebloss** [comment]
How do you even upload to Azure with froala? Do you intercept the `beforeUpload` event and change the `editor.imageUploadParams` there or something similar?

**Comment by rokobasilisk** [comment]
I would recommend creating a web service that receives the file using fileUploadURL parameter on the froala editor. 

That web service then uploads to Azure. You have greater control over authentication with this method.
