### ISSUE TITLE
Add an identifier/class to distinguish between multiple ".fr-popup"

### ISSUE THREAD

**Issue by BrianLaughlan** [froala/wysiwyg-editor#2532]
![1](https://user-images.githubusercontent.com/8556999/35563117-f98b5daa-05b5-11e8-9a9a-0b531d6bc71a.PNG)

To allow more granular CSS tweaking you should add an identifier/class to distinguish between multiple `.fr-popup` - based on what has activated the popup. 

e.g. The "insertLink" button would have a popup with this class `.fr-popup-link-insert`

In the example image above, there is no way for me to style the "insert link" popup vs the "change color" popup.

**Comment by dianaprajescu** [comment]
@BrianLaughlan we want all the editor popups to have a unitary feel that is consistent with the editor. For this reason we consider that all `.fr-popup` elements should have the same style: border, shadow, margins, colors and text formatting.

For more granular styling, each popup has a specific template that includes classes for each element inside it. We recommend styling either all `.fr-popup` elements or the content inside each of the `.fr-popup` elements, like for example `fr-link-insert-layer`.

**Comment by BrianLaughlan** [comment]
@dianaprajescu You misunderstand me. I am not talking about cosmetic styling. I am talking about the ability to override the positioning. I understand I can change `.fr-link-insert-layer` however this does not help because Froala is calculating the top and left values and adding them to the parent (`.fr-popup`)

See here for example:

![1](https://user-images.githubusercontent.com/8556999/35620169-9cbeb7ae-0680-11e8-8363-cff11e5e1bf0.PNG)

Lets say I wanted to override the left and top position that has been calculated by the plugin and added to `.fr-popup`. So that the "Insert Link" popup would be on the far left and go full width. I currently could not do that because it would also effect other `.fr-popup`

As a plugin, the aim here should to make it as flexible as possible for the end user. Simply adding a class would not break anything for anybody, but it would allow us **paying customers** to modify the editor as required, based on our own application and needs.

Look forward to hearing back from you.

**Comment by dianaprajescu** [comment]
A better approach for what you need is to use the `popups.show` event. I just notice that it is currently not documented on our website, but it is similar with the hide event (https://www.froala.com/wysiwyg-editor/docs/events#popups.hide.[id]).

Indeed, adding a class will not break anything, but we are doing our best to keep the plugin's size as small as possible. I'm going to mark this as a `feature-request` and if there are more users asking for such classes we will consider adding them in the future.

Even if  we add classes for popups, we wouldn't recommend setting the popup's position using CSS, because the position has to change along with the scroll. Therefore it is better to do this in Javascript.

**Comment by BrianLaughlan** [comment]
Thank you for marking this as a feature request.

In the event you mentioned. Where would I get the [id] of the popup? As far as I can see there are no unique identifiers, otherwise I would be able to target it in the first place.

**Comment by stefanneculai** [comment]
@BrianLaughlan you could do it like this:

```js
$('selector').froalaEditor().on('froalaEditor.popups.show.link.insert', function (e, editor) {
  var $popup = editor.popups.get('link.insert');
  $popup.addClass('your_custom_class');
});
```

**Comment by cannyedge34** [comment]
+1
