### ISSUE TITLE
Image resize not working

### ISSUE THREAD

**Issue by rajchetan** [froala/wysiwyg-editor#2534]
##### Expected behavior.
Image resize to work

##### Actual behavior.
Image resize is not working when `image.insert` is used

##### Steps to reproduce the problem.
Upload image using `image.insert`

##### OS.
macOS

##### Browser.
Chrome - Version 63.0.3239.132 (Official Build) (64-bit)

**Comment by dianaprajescu** [comment]
We made some changes to the image plugin lately that will be included in the next release 2.7.4. We tested this issue on the latest editor version and it doesn't happen. Please update your editor version once we make the release and give it another try.

I'm closing this issue for now, but if your problem still persists, please make a jsfiddle where we can reproduce it.
