### ISSUE TITLE
Exception in empty editor for 2.7.4

### ISSUE THREAD

**Issue by markedmondson** [froala/wysiwyg-editor#2535]
##### Expected behavior.
Editor should initialize and show

##### Actual behavior.
Editor doesn't initialize or show

##### Steps to reproduce the problem.
Initialize new editor, exception is thrown as below.

![screenshot 2018-01-31 10 18 55](https://user-images.githubusercontent.com/1653699/35639786-33b247e0-0670-11e8-9884-833d2e242fc9.png)

##### OS.
MacOS High Sierra

##### Browser.
Chrome 64

**Comment by stefanneculai** [comment]
@markedmondson could you please let us know what options are you using for the editor?

**Comment by markedmondson** [comment]
```javascript
var froalaColors = [
  '#61BD6D', '#1ABC9C', '#54ACD2', '#2C82C9', '#9365B8', '#475577', '#CCCCCC',
  '#41A85F', '#00A885', '#3D8EB9', '#2969B0', '#553982', '#28324E', '#000000',
  '#F7DA64', '#FBA026', '#EB6B56', '#E25041', '#A38F84', '#EFEFEF', '#FFFFFF',
  '#FAC51C', '#F37934', '#D14841', '#B8312F', '#7C706B', '#D1D5D8', '#C0C0C0',
  '#FF0000', '#FFFF00', '#008000', '#0000FF', '#00FFFF', '#800080', 'REMOVE'
];

var froalaConfig = {
  key: '[redacted]',
  charCounterCount: false,
  colorsBackground: froalaColors,
  colorsText: froalaColors,
  fontSize: ['8', '9', '10', '11', '12', '14', '16', '18', '24', '30', '36', '48', '60', '72', '96'],
  fontSizeSelection: true,
  height: 400,
  imageDefaultDisplay: 'inline',
  imageDefaultWidth: 0,
  imageUploadMethod: 'POST',
  imageUploadParams: {
    'authenticity_token': $('meta[name="csrf-token"]').attr('content')
  },
  imageUploadURL: '/some/path',
  imageManagerDeleteMethod: 'DELETE',
  imageManagerDeleteParams: {
    'authenticity_token': $('meta[name="csrf-token"]').attr('content')
  },
  imageManagerDeleteURL: '/some/path',
  imageManagerLoadURL: '/some/path',
  imageManagerPageSize: 5,
  language: 'en',
  linkInsertButtons: [],
  linkifySurveys: true,
  linkEditButtons: ['linkOpen', 'linkEdit', 'linkRemove'],
  linkList: [],
  toolbarButtons: ["bold", "italic", "underline", "strikeThrough", "fontSize", "color",  "clearFormatting", "|", "paragraphFormat", "align", "formatOL", "formatUL", "outdent", "indent", "|", "insertLink", "insertImage", "insertVideo", "insertTable", "html", "|", "fullscreen"],
  toolbarButtonsXS: ['bold', 'italic', 'fontFamily', 'fontSize', 'color', 'undo', 'fullscreen'],
  toolbarSticky: false,
  useClasses: false,
  videoInsertButtons: ['videoBack', '|', 'videoByURL', 'videoEmbed'],
  wordPasteModal: false
};
```

**Comment by stefanneculai** [comment]
We couldn't replicate it on our side. Do you think you could put together a jsFiddle?

**Comment by markedmondson** [comment]
For sure,  it seems to be `useClasses: false`. I'll try and make a fiddle.

**Comment by stefanneculai** [comment]
@markedmondson Looking for the jsFiddle. While it appears to come from the `useClasses: false`, we couldn't replicate it. Thanks in advance!

**Comment by lucassimibueno** [comment]
I have the same problem here. After update to version 2.7.4 the same error appeared. My configuration use the `useClasses: false` as well.

**Comment by stefanneculai** [comment]
@lucassimibueno could you provide a jsFiddle? We can't replicate it at our end for now.

**Comment by markedmondson** [comment]
I'm struggling to replicate it in a fiddle too, I'm guessing it's something in our setup but could be common if @lucassimibueno is experiencing the same. I'll keep trying.

**Comment by markedmondson** [comment]
FWIW we're initializing the troublesome editor in React.

**Comment by stefanneculai** [comment]
@markedmondson @lucassimibueno we managed to replicate it. We'll post a workaround shortly.

**Comment by markedmondson** [comment]
Thanks @stefanneculai, should we expected to see 2.7.5 soon or should we just pull those changes into 2.7.4 to get it working?

**Comment by stefanneculai** [comment]
We'll most likely put a 2.7.4-1 version. Still discussing that.
