### ISSUE TITLE
IE11 - froala content outside fr-view

### ISSUE THREAD

**Issue by smoockpp** [froala/wysiwyg-editor#2538]
##### Expected behavior.
I'm not sure how your plugin is set to work, but It shouldn't place fr-view content outside of it

##### Actual behavior.
On IE11  - for example ( you can see the screenshots ) I have a text which is wrapped by a span element with some styling as a content which is within fr-view element, but also is outside of it as a normal text.

##### Steps to reproduce the problem.
We are using angular-froala-wysiwyg, so I'm not sure if this is not an issue with the angular wrapper ot froala itself.

##### OS.
Windows 10

##### Browser.
Internet Explorer 11
![froala-bug](https://user-images.githubusercontent.com/15022761/35735166-a064c08c-081b-11e8-839c-c751a8030bd8.png)

**Comment by stefanneculai** [comment]
@smoockpp it looks like you are doing something wrong. Could you create a Plunker for it?
