### ISSUE TITLE
Striped HTML tags

### ISSUE THREAD

**Issue by homoky** [froala/wysiwyg-editor#254]
I am new to Froala. We would like to use it on our commercial project for newsletters, but when we paste HTML newsletter it strips all head tags and it shows only the body content.

Can I change this behavior in JS? 

THX.

**Comment by stefanneculai** [comment]
Last commit introduced a new option `fullPage` that allows tags such as `HTML`, `HEAD`, `BODY` when the option is enabled.

**Comment by devmondo** [comment]
awesome :)
