### ISSUE TITLE
Updated packagist

### ISSUE THREAD

**Issue by N1cE-tm** [froala/wysiwyg-editor#2542]
Upated pls [packagist repo](https://packagist.org/packages/froala/wysiwyg-editor) to latest version.
I tried install [froala/yii2-froala-editor](https://packagist.org/packages/froala/yii2-froala-editor#dev-master) `dev-master` version but got following 
```
Problem 1
    - Installation request for froala/yii2-froala-editor dev-master -> satisfiable by froala/yii2-froala-editor[dev-master].
    - froala/yii2-froala-editor dev-master requires froala/wysiwyg-editor ^2.7.5 -> no matching package found.
```
Because packagist repo last ver 2.7.3.

And mb u'll follow [this guide](https://packagist.org/about#how-to-update-packages) for autoupdate in future

**Comment by stefanneculai** [comment]
@N1cE-tm it should be updated now. The Packagist is doing a fetch from time to time and it looks they haven't updated the package automatically.
