### ISSUE TITLE
New image caption in 2.7.5 is always bold generated outside text editor

### ISSUE THREAD

**Issue by NordicLight** [froala/wysiwyg-editor#2543]
The new image caption 2.7.5 is rendered normal in the editor (See picture below). However rendering the html content outside the editor according to (https://www.froala.com/wysiwyg-editor/docs/overview) the same caption is always bold. So there is bug in the froala_style.min.css for 2.7.5 around this.

Showing a picture caption as displayed in the editor
<img width="200" alt="screen shot 2018-02-03 at 13 59 09" src="https://user-images.githubusercontent.com/9700899/35767327-b11f7f28-08ea-11e8-8d99-def9edfc403e.png">

Showing the same picture caption as displayed outside the editor
<img width="200" alt="screen shot 2018-02-03 at 14 04 44" src="https://user-images.githubusercontent.com/9700899/35767356-4afbff54-08eb-11e8-9637-db97af855701.png">

**Comment by stefanneculai** [comment]
@NordicLight I believe you have some style there on the page which conflicts with it. We don't have any specific CSS for that. If you could make a jsFiddle or send us a link to the page where you have this problem, I would be happy to check.

**Comment by NordicLight** [comment]
You are right Stefan. This is not a bug in Froala!

The problem occurred when trying to render a html to pdf report outside the browser. The problem was the opacity:0.9 in your css. Adding below did fix the issue in my environment however the bug is that the html to pdf solution seems to have problem with opacity and not in Froala... 

.fr-view .fr-img-caption .fr-img-wrap>span {
    opacity: 1.0 !important;  (in your css the opacity was 0.9 which caused the problem)
}

**Comment by stefanneculai** [comment]
Thanks for the follow-up, @NordicLight.
