### ISSUE TITLE
IE: Unable to get property 'trim' of undefined or null reference

### ISSUE THREAD

**Issue by LaurenceKaye** [froala/wysiwyg-editor#2544]
##### Expected behavior.
No errors

##### Actual behavior.
Javascript Error received: Unable to get property 'trim' of undefined or null reference

##### Steps to reproduce the problem.
1. Open https://jsfiddle.net/kyfotvfb/4/ in Internet Explorer 11
2. Try and type a new word into the box whilst there is a spelling mistake awaiting correction

##### OS.
Windows 10

##### Browser.
Internet Explorer 11

##### Misc.
I know this is the same error as #2498 but I wasn't sure if it was the same cause as that one had been marked as fixed in 2.7.5. It doesn't seem to error when using a div as the Froala element. In my example I am using a textarea.

**Comment by stefanneculai** [comment]
@LaurenceKaye it should be fixed on the current Github master. Could you please give it a try?

**Comment by LaurenceKaye** [comment]
@stefanneculai My jsFiddle is using 2.7.5, but give me a few minutes and I can check the latest github version.

**Comment by stefanneculai** [comment]
see https://jsfiddle.net/kyfotvfb/6/

**Comment by LaurenceKaye** [comment]
@stefanneculai Look's like it is fixed on the master. Thanks
