### ISSUE TITLE
Bold formatting is not preserved when copied from google docs.

### ISSUE THREAD

**Issue by ibtisamniche-vteams** [froala/wysiwyg-editor#2545]
##### Expected behavior.
Hi when I copy rich text from google docs that contains bold formatting and paste into froala editor i want to show the text as in bold as copied from the docs.

##### Actual behavior.
Instead of showing the bold text froala editor is showing the text as plain.

Kindly tell my why is that happening , I saw the same issue #1506 but no guidance was there. On another issue it was mentioned that version the problem of formatting will be covered in versions greater than 2.0. I am using 2.3.2 but still facing the issue.

**Comment by stefanneculai** [comment]
@ibtisamniche-vteams unfortunately, when pasting from Google Docs, all the styling comes inline which is not ideal. If you would like to keep all that formatting, all you should do is to change the pasteDeniedAttrs to `pasteDeniedAttrs: ['class', 'id']`.

**Comment by gmallick90** [comment]
when copy paste the online formatted line then its work and if select multiple combination then it remove the style tags
