### ISSUE TITLE
Add Fontawesome icon to Editor

### ISSUE THREAD

**Issue by divdax** [froala/wysiwyg-editor#2547]
##### Expected behavior.
not writing "inside" of added html `<i>` element.

##### Actual behavior.
insert html, writes text "inside" of added html element. Also it's not possible to format the Font Awesome icon e.g. Headline, Color. Adding new lines repeats icon.

##### Steps to reproduce the problem.
1. go to editors homepage
2. open console and type:
`$('#froala-editor').froalaEditor('html.insert', '<i class="fa fa-check"></i>');`
3. write before icon (font), hit enter, write...

##### OS.
macOS

##### Browser.
Newest Chrome

**Comment by stefanneculai** [comment]
Duplicate of #1307.

**Comment by divdax** [comment]
@stefanneculai why both are closed?

**Comment by stefanneculai** [comment]
@divdax we use this repo for bug-tracking. Feature requests are not left open, however, we add a `feature-request` label to them and they are to our attention.

**Comment by stefanneculai** [comment]
We've just put together a public roadmap with the most popular features. 😍 There you can vote your favorite one, provide feedback or make new suggestions: https://wysiwyg-editor-roadmap.froala.com/public.
