### ISSUE TITLE
Line breaker wrong position when using animate.css and the like.

### ISSUE THREAD

**Issue by mikeshow** [froala/wysiwyg-editor#2548]
##### Expected behavior.
The line breaker should position itself for instance after a table.

##### Actual behavior.
The line breaker position itself depending on the position of the froala editor.

##### Steps to reproduce the problem.
- Take for example 'custom_button.html' as starting point.
- add 'animate.css' (before or after the froala css doesn't matter)
- add some text before and after the div="editor"
- enclose all that in a div like:
`<div id="thetest" class="animated fadeInRightBig" style="display: none;">`
- enclose the froala script code in something like:
`$('#thetest').show(5000, function () {[froala code here]});`
- Execute in a browser other than IE11
- add a table at the end (after '... option.')
- Hover over the bottom of the table with the cursor. Depending on the vertical position of the editor you'll see the line breaker at different position or not at all.
- To use the file attached you have to have animate.css somewhere and change the path accordingly:
[custom_button.zip](https://github.com/froala/wysiwyg-editor/files/1698015/custom_button.zip)

Notice that the problem is not specific to animate.css. I used other lib like anime.js or velocity.js and the result is the same.

##### OS.
Windows 10

##### Browser.
Opera 50.0.xxx, Firefox 58.0.1, Chrome 64.0.xxx, Edge 41.xxx : it doesn't work.
IE11.192.xxx : it works.

**Comment by stefanneculai** [comment]
@mikeshow do you think you could make a jsFiddle?

**Comment by mikeshow** [comment]
You just get the custom_button.html file in the zip file attached, add canvas.css from somewhere, update the link accordingly and you're good to go.

**Comment by stefanneculai** [comment]
@mikeshow it should be fixed in version 2.7.6.
