### ISSUE TITLE
Video can not be longer selected on edit mode

### ISSUE THREAD

**Issue by timoelsila** [froala/wysiwyg-editor#2549]
##### Expected behavior.
All videos should be selectable in editing mode.

##### Actual Behavior.
If the videos are added one below the other, you cant select bottom video anymore.

##### Steps to reproduce the problem.
1) Add video from a cloud service
2) Add another video
3) Select video #1
4) Select video #2
5) Select video #1
6) Select video #2
-> Problem: You can no select video number #2 anymore?
Look video attachment
https://drive.google.com/file/d/1tfByeQeFJr8dXLkW47MuAsRLEAfyqMMK/view

##### OS.
Windows 10 Pro

##### Browser.
Google Chrome Version 
64.0.3282.140 (Official Build) (64-bit)

**Comment by dgroh** [comment]
In which version this fix was pushed to?
