### ISSUE TITLE
Selection anchor node has unpredicted behavior with inline-block elements

### ISSUE THREAD

**Issue by petester42** [froala/wysiwyg-editor#2554]
When backspacing text and the cursor is then next to an inline-block, the current selection is set to the paragraph node instead of the text node.

##### Expected behavior.
I expect the selection to be in the text node with offset of 0.

##### Actual behavior.
Selection is in the current paragraph.

##### Steps to reproduce the problem.
Here is reproducible plunker https://plnkr.co/edit/dAqAux1dmis2jZhzC5yH. Open the plunker and place the cursor after the T in "Try to change" then press backspace. Look at the log below the editor to see that the anchor node is a p tag.

##### OS.
macOS High Sierra

##### Browser.
Chrome 64.0.3282.140

**Comment by stefanneculai** [comment]
@petester42 the current behavior is the correct desired one. When removing the element between text nodes with backspace, and there are 2 text nodes one to another, the editor is designed to join them together. This is called node normalization: https://developer.mozilla.org/en-US/docs/Web/API/Node/normalize.

**Comment by petester42** [comment]
I understand what you are saying but I don't see how these two things are related. My problem is that selection ends up being in an unexpected place. I am not deleting the inline-block between 2 text nodes I am deleting the first character of the text node after the inline-block. 

My expectation is that my selection would stay in the text node and be at position 0. What actually happens is the selection ends up in the parent of the text node. I don't see why node normalization would cause this. Maybe I am missing something.

**Comment by stefanneculai** [comment]
I apologize, I misunderstood your initial message. We are working directly with the selection API offered by the browser. This problem is coming from how the selection API works and there is not too much we can do to overcome it. The same situation happens sometimes when you just put the cursor at the beginning of the P tag an get the selection.

Unfortunately, the selection info across browsers is not consistent and sometimes you would have to write some custom code to detect such situations. What I would recommend in this situation would be to do a check for this particular case. Something like this:

```js
var range = editor.ranges(0);
if (node.childNodes.length > 0 && node.childNodes[range.startOffset]) {
  child = node.childNodes[range.startOffset];
}
```

**Comment by petester42** [comment]
Ok thanks. I’ll try that out.

**Comment by petester42** [comment]
For anyone interested in my fix for this here is the final result which is executed on keydown. Thanks @stefanneculai for pointing me in the right direction.

``` javascript
var selection = editor.selection.get();
var node;
var offset;

switch (event.which) {
  case $.FE.KEYCODE.DELETE:
    node = selection.focusNode;
    offset = selection.focusOffset;
    break;

  case $.FE.KEYCODE.BACKSPACE:
    node = selection.anchorNode;
    offset = selection.anchorOffset;
    break;

  default:
    // only handle backspace and delete
    return;
}

if (
  node.childNodes.length > 0 &&
  node.childNodes[offset] &&
  node.childNodes[offset].nodeType === Node.TEXT_NODE
) {
  node = node.childNodes[offset];
}
```
