### ISSUE TITLE
Removing zero width space

### ISSUE THREAD

**Issue by rajchetan** [froala/wysiwyg-editor#2555]
##### Expected behavior.
Not to remove INVISIBLE_SPACE[`&#8203;`]

##### Actual behavior.
It's removing  INVISIBLE_SPACE[`&#8203;`] when it resides at end of an element

##### Steps to reproduce the problem.
It's happening in this function

```
function q(a) {
    for (var c = b.doc.createTreeWalker(a, NodeFilter.SHOW_TEXT, b.node.filter(function(a) {
        return /\u200B/gi.test(a.textContent)
    }), !1); c.nextNode(); ) {
        var d = c.currentNode;
        d.textContent = d.textContent.replace(/\u200B/gi, "")
    }
}
```

Is there any way we can avoid it, Can you let me know please..

##### OS.
MacOS

##### Browser.
Chrome latest

**Comment by stefanneculai** [comment]
@rajchetan the current editor version is designed to create output without zero-width spaces. Is there any reason why you would need to have those in the text?

**Comment by rajchetan** [comment]
Hi @stefanneculai, we're currently migrating from an old editor to Froala, the old editor has inserted a lot of `&#8203;` in the db, So we cannot replace that, that's the reason. Please let me know if there's any alternative.

**Comment by stefanneculai** [comment]
@rajchetan I would recommend removing the `&8203;` character with an empty string before adding it to the editor. Probably, the old editor was using it in order to make editing possible in some edge situations, however, it should not be present in the output.
