### ISSUE TITLE
font-family does not use external fonts in iframe-mode

### ISSUE THREAD

**Issue by dularion** [froala/wysiwyg-editor#2556]
##### Expected behavior.
When using external fonts like google fonts, and following the instructions posted here https://www.froala.com/wysiwyg-editor/examples/font-family, the expected behaviour is that changing a font will apply it to the text within the editor. Even in iframe-mode. 

##### Actual behavior.
When using iframe:true, only the fonts in the dropdown are displayed correctly, ie the content outside of the iframe that gets affected by the css of the surrounding page, but the text within the iframe does not get the correct fonts applied, probably because those external fonts are not loaded within the iframe. 

##### Steps to reproduce the problem.
Here is a plunkr: https://codepen.io/anon/pen/EQNzrY

##### OS.
Mac OSX 10.13.2 (17C88)

##### Browser.
Chrome Version 64.0.3282.140 (Official Build) (64-bit)

**Comment by stefanneculai** [comment]
They should be loaded via `iframeStyleFiles` option: https://codepen.io/anon/pen/oEBWGN.

**Comment by dularion** [comment]
thanks mate!
