### ISSUE TITLE
quick-insert element stranded in DOM in single-page apps

### ISSUE THREAD

**Issue by FWennerdahl** [froala/wysiwyg-editor#2564]
##### Expected behavior.
In single-page apps using (for example using AngularJS with ng-view), the quick-insert element is removed from the DOM when navigating to a page without the Froala editor.

##### Actual behavior.
The quick-insert element can be left stranded in the DOM when navigating to another page in a single-page app. It's never removed unless the page is fully reloaded, and loading Froala again can cause additional elements to end up in the body.

##### Steps to reproduce the problem.
1. Open the JSFiddle at: https://jsfiddle.net/zn8L0xku/
2. Focus editor 2.
3. Press Enter to make the quick insert helper show.
4. Click "Replace editor".
5. Notice the quick-insert plus added to the bottom of the page (made visible through CSS).
6. Click "Other page". Notice the plus is still present.
7. Click "Editor page" and repeat. Multiple quick-insert elements can be added to the DOM.

**Notes:**
- Replacing the model/editor is a real use-case when using ng-repeat and updating the model outside the Froala editor.
- While the reproduction case uses angular-froala, the problem is actually in Froala editor where the quick-insert element is appended to the body on destroy. As such, it should manifest in AngularJS even if the angular-froala bindings aren't used.
- This also seems to apply to the tooltip and line-breaker elements.

##### OS.
macOS 10.12.6

##### Browser.
Chrome 63.0.3239.132

**Comment by stefanneculai** [comment]
That is happening because of the CSS added in the jsFiddle, not because of how the editor is handling it.

```css
body > .fr-quick-insert {
  position: static;
  width: 40px;
  float: left;
}
```

**Comment by FWennerdahl** [comment]
The CSS is only present to visualize the issue. Without it it wouldn't be as apparent.

The element is still left in the DOM as a child to body when navigating to another view. Please consider re-opening this as it is an issue with the DOM being cluttered for single-page apps.

**Comment by stefanneculai** [comment]
We keep it in DOM in order to be used by other editors. When the last editor instance is destroyed, the Quick Insert helper would be removed as well. This is happening in order to improve the editor performance.

**Comment by FWennerdahl** [comment]
Yes, however the issue is that the quick-insert helper isn't removed when changing route, since it's a single-page app. It remains in the body even though another view has been loading that doesn't contain any Froala editor instances. I'm guessing it's treated as a page load which isn't triggering the destroy events.

Any advice on how to handle this for single-page apps would be welcome.

**Comment by stefanneculai** [comment]
What we'd recommend is to destroy all the editor instances from a page before changing the route and navigating to another page using manual controls: https://github.com/froala/angular-froala#manual-instantiation.

**Comment by FWennerdahl** [comment]
Righto, we'll look into that. Thanks!

**Comment by FWennerdahl** [comment]
@stefanneculai We've attempted the recommended approach to destroy all editor instances before navigating to another page, however this does seem to make any difference. We also noticed that other elements such as the color picker end behave in the same way.

An example on how the DOM looks after navigating to another page without any Froala editors:
<img width="625" alt="screen shot 2018-03-13 at 22 35 31" src="https://user-images.githubusercontent.com/3178426/37371305-32fced4a-270f-11e8-946c-549406b21229.png">

Navigating back to a page with editors adds duplicate elements, which causes this to be very problematic for single page apps:
<img width="626" alt="screen shot 2018-03-13 at 22 41 56" src="https://user-images.githubusercontent.com/3178426/37371482-c74ead44-270f-11e8-8660-6367d08b6e57.png">

**Comment by stefanneculai** [comment]
@FWennerdahl do you think you could make a Plunker / jsFiddle?

**Comment by FWennerdahl** [comment]
@stefanneculai sorry, I'm not quite following. I made a JSFiddle in my initial post in this issue with reproduction steps for this issue. Do you need me to update it in any way?

**Comment by FWennerdahl** [comment]
@stefanneculai I've updated the JSFiddle from the first post: https://jsfiddle.net/zn8L0xku/15/

Notice that even when explicitly destroying editors both before the model updates but also when changing route, the steps to reproduce still causes the quick-insert elements to be stranded in the DOM.
