### ISSUE TITLE
Replace Image Scrolling Bug

### ISSUE THREAD

**Issue by btmdave** [froala/wysiwyg-editor#2569]
##### Expected behavior.

_When Froala is loaded inside of a scrollable window_
1. Select an existing image and click on the replace icon
2. Select the by URL option

The expectation is that the input for the link would show in place.

##### Actual behavior.

The window is scrolled to the top and you have to scroll down to find the image again.

##### OS.
Mac

##### Browser.
Chrome 64

**Comment by stefanneculai** [comment]
@btmdave could you please confirm you are seeing this problem on our website too?

**Comment by stefanneculai** [comment]
@btmdave any input here? Thank you.

**Comment by btmdave** [comment]
@stefanneculai I apologize, I wasn't clear in my description.  This is actually when in a scrollable div, not window so `overflow: scroll`.  I don't believe there's an example of that usage on your site.

**Comment by stefanneculai** [comment]
Are you setting the scrollableContainer option? Here is [a basic jsFiddle](https://jsfiddle.net/froala/wc5c3jhk/) which you could use to show us the problem. Thanks in advance.

**Comment by btmdave** [comment]
@stefanneculai Here's a quick pen - https://codepen.io/anon/pen/jZXrNg

If you scroll down and try to edit that Google logo with Replace and By URL, when you click on the URL icon, it'll scroll to the top.

**Comment by stefanneculai** [comment]
Thanks for the details.

**Comment by stefanneculai** [comment]
@btmdave we've just checked this again in order to fix it. It looks the CodePen was outdated (version 2.6.0). Please find here an updated code pen: https://codepen.io/anon/pen/mXoYWe.
