### ISSUE TITLE
HTTP_X_REQUESTED_WITH not sent with AJAX requests

### ISSUE THREAD

**Issue by twistedpixel** [froala/wysiwyg-editor#257]
Just noticed, some AJAX calls (uploading an image for example) don’t appear to be sent with the HTTP_X_REQUESTED_WITH header. I only noticed because Codeigniter fails to detect the request as AJAX. Looks like the request to retrieve the image directory is sent with the header though.

Not a crucial issue but might worth investigating. Didn't see this in the issues list so thought I'd mention.

**Comment by craigbennett1981** [comment]
I am still seeing this issue with image uploads in v1.2.7, do you plan to put a fix in for this issue?

**Comment by stefanneculai** [comment]
How are you setting the headers?

**Comment by craigbennett1981** [comment]
No I am not, if I delete and image the header is set, but if I delete it is not on the same element.

**Comment by lpalomo** [comment]
I did this to resolve: , 'headers': {'X-Requested-With': 'XMLHttpRequest',}

I don't know if this is still required or not, when I asked I supposed that this was the default for ajax requests.
