### ISSUE TITLE
Internal "copy and paste" copies the css propertied also

### ISSUE THREAD

**Issue by rajchetan** [froala/wysiwyg-editor#2570]
##### Expected behavior.
(Describe expected behaviour here)

##### Actual behavior.
When i'm writing something inside the editor, and copy the text inside the editor and paste, the copied text is also having CSS properties.

copied text is like -

`<meta charset='utf-8'><span style="color: rgb(0, 0, 0); font-family: Roboto, &quot;Open Sans&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">adipisicing voluptate</span>`

##### Steps to reproduce the problem.
write some text, then copy and paste the same text.

**Comment by stefanneculai** [comment]
@rajchetan please make sure you're using the latest 2.7.5 version.

**Comment by stefanneculai** [comment]
@pawansingh-snapwiz the CodePen you sent is using the 2.6.0 version instead of 2.7.5.

**Comment by pawansingh-snapwiz** [comment]
@stefanneculai
Below I have given a link which is using 2.7.5 version still happening with it also please check.
[https://codepen.io/pawansingh/pen/ddWqZZ?editors=1010](url)

**Comment by stefanneculai** [comment]
@pawansingh-snapwiz in the code pen you sent, you are overriding the entire pasting action and skipping all the pasting internals. In the `paste.beforeCleanup`, you get the raw HTML which is there on the clipboard. Then, inside the pasting action, we're doing some processing which cleans the unnecessary HTML.

**Comment by pawansingh-snapwiz** [comment]
@stefanneculai 
In that case can u please tell how should I be doing it.

**Comment by stefanneculai** [comment]
To get the HTML correctly, you should not override the HTML which is cleaned. As I said in the comment above, the `paste.beforeCleanup` is designed to return exactly the HTML from the clipboard handled by the browser.
