### ISSUE TITLE
br tags removed after visit to HTML view.

### ISSUE THREAD

**Issue by Fandangi** [froala/wysiwyg-editor#2571]
##### Expected behavior.
 When I type shift-enter Froala should insert a br. When I go to the HTML view I should see that br. When I return to richtext view the br should still be present. 

##### Actual behavior.
The br is removed after leaving the HTML view.

##### Steps to reproduce the problem.
Take a Froala editor instance on the Froala website. The live content preview example is useful for this - https://www.froala.com/wysiwyg-editor/examples/live-content-preview.
 Make a short sentence in a para. Duplicate the sentence - you should now have 2 paras like this. 

<p class="dzPlainText">A short sentence.</p>
<p class="dzPlainText">A short sentence.</p>

In normal editor view, put the cursor at the end of the first para and type shift-enter. Go to HTML view and you can see the structure is as we expect:

<p class="dzPlainText">A short sentence.
    <br></p>
<p class="dzPlainText">A short sentence.</p>

Now return to editing view and note that the line break is not effective - there is no blank line between the paras. So no go to HTML view to see the structure and it has reverted to:

<p class="dzPlainText">A short sentence.</p>
<p class="dzPlainText">A short sentence.</p>

Froala is removing the br between HTML and editing view. 

This is bad behavior - the idea of a WYSIWYG editor is .... well you get it ;-)

NOTE: One suggested workaround might be to place the cursor at the beginning of the second para because the br thus introduced remains in place. However, the benefit of the shift-enter is to have a blank line with the same line-height characteristics as the para to which it belongs, and the users desire could be to use the characteristics of the first para in preference to the second.

##### OS.
Windows 10

##### Browser.
Google Chrome Version 64.0.3282.140 (Official Build) (64-bit

**Comment by Fandangi** [comment]
Hi Stefan - I am new to this process. Thanks for the rapid fix, can you advise me how I can get hold of the corrected version to confirm the fix is good ?

**Comment by stefanneculai** [comment]
Currently the fix is available only here on Github and will be included in the release 2.7.6.
