### ISSUE TITLE
Adding an audio tag in code view auto plays in edit view

### ISSUE THREAD

**Issue by davehearne** [froala/wysiwyg-editor#2574]
##### Expected behavior.
Copy audio tag in code view , audio does not play when switching back to editor view

##### Actual behavior.
Every time I switch between code view and edit view the audio clip plays

##### Steps to reproduce the problem.
drop an audio tag in code view with autoplay = 'autoplay'
I need the autoplay feature for the pages I am creating with this.

`<audio id="demo" src="whatever.mp3" autoplay="autoplay">
</audio>`

##### OS.
Mac OSX

##### Browser.
All

**Comment by stefanneculai** [comment]
@davehearne when switching from Code View back to the editor, the HTML is written again back to the editor. If you want to have the `autoplay` only in the output, I would recommend not adding it to the original HTML, but process it just before displaying it and adding the attribute there.

**Comment by nidhin038** [comment]
Is it possible to autoplay inside the editor soon after uploading ?

**Comment by echobool** [comment]
How did you do it? Is there any code that can be shared? Thank you 

> ##### 预期行为。
> 在代码视图中复制音频标签，切换回编辑器视图时音频不播放
> 
> ##### 实际行为。
> 每次我在代码视图和编辑视图之间切换时，都会播放音频剪辑
> 
> ##### 重现问题的步骤。
> 在代码视图中放置一个带有 autoplay = 'autoplay' 的音频标签 我需要为我正在创建的页面提供自动播放功能。
> 
> `<audio id="demo" src="whatever.mp3" autoplay="autoplay"> </audio>`
> 
> ##### 操作系统。
> Mac OSX
> 
> ##### 浏览器。
> 全部
