### ISSUE TITLE
Pasting Mixed Content from MS Word document not working in Microsoft Edge

### ISSUE THREAD

**Issue by hassannaseem** [froala/wysiwyg-editor#2575]
##### Expected behavior.
(Mixed Content) Text and image should be pasted.

##### Actual behavior.
Only the text is pasted

##### Steps to reproduce the problem.
Visit  https://www.froala.com/wysiwyg-editor in Microsoft Edge. Now open a word document with text and images. Select all and try pasting it in to the editor only the text is pasted. There is error in console "SEC7111: HTTPS security is compromised by" followed by a link to the local image temp directory.

Same thing is working fine in IE 11 on the same machine.

##### OS.
Window 10 Pro, 64 Bit
Version: 1703 
OS Build: 15063.632

##### Browser.
Microsoft Edge 40.15063.0.0
Microsoft EdgeHTML 15.15063

**Comment by stefanneculai** [comment]
@hassannaseem Microsoft is doing by itself a cleanup when pasting from Word and we cannot get the HTML as it comes from Word. Unfortunately, we cannot do nothing for that at this moment.
