### ISSUE TITLE
How to show spinner

### ISSUE THREAD

**Issue by StanislavMayorov** [froala/wysiwyg-editor#2576]
Hi.
I use custom method for api request to upload images. Is it possible to show froala spinner or progress bar while image is uploading? 

Option object for react-froala-wysiwyg:
```
option = {
    events: {
        'froalaEditor.image.beforeUpload': function (e, editor, images) {
            uploadApi.uploadFileForHtmlEditor(images).then(function (response) {
                editor.image.insert(response.url);
            });
            return false;
        }
    }
}
```

**Comment by stefanneculai** [comment]
@StanislavMayorov there are couple of things which should be done for that. Please reach us [via our website](https://www.froala.com/wysiwyg-editor/contact) for the tech support in the Professional/Business license.

**Comment by CodeXtinction** [comment]
need this too :D
