### ISSUE TITLE
Uploaded image is taking width of the editor box instead of full width of the container

### ISSUE THREAD

**Issue by Chandrika-Desai** [froala/wysiwyg-editor#2577]
##### Expected behavior.
After saving the content,, hiding editor and showing the edited content which has images, images should take width of my wrapper container

##### Actual behavior.
Images are taking the width of the editor box, I have container, which has the width of 600px, editor width is also 600px with 10px padding , when I upload image, its width is 570 inside the editor box, when I save content and view the page, width of image remain 570 instead of 600px

##### Steps to reproduce the problem.
1. Open editor box
2. Add content and images
3. Save content, close editor view
4. View the saved content.
If there is text content ,  content flows and occupies 600px of my container width, but image width remains 570px.
imageOutputSize is set to true
imageUploadParams, we are passing width aswell

It was working when we were using 2.3.4, we upgraded to 2.7.2, is it because of upgrade?
**This is how it looks when I m editing inside editor**

![save-story](https://user-images.githubusercontent.com/10757819/36200837-eae96aea-11a3-11e8-81c5-94d64b248648.png)

**This is how it looks when I close editor**

![saved-story](https://user-images.githubusercontent.com/10757819/36200852-f8481060-11a3-11e8-81ae-69e3614623e3.png)

##### OS.
Ubuntu 16.04

##### Browser.
Chrome

**Comment by stefanneculai** [comment]
@Chandrika-Desai when using the `imageOutputSize` option, the width of the image would be exactly the width you're seeing while editing inside the editor. We consider this as being the correct behaviour.
