### ISSUE TITLE
"froalaEditor.paste.beforeCleanup" Method Issue

### ISSUE THREAD

**Issue by pawansingh-snapwiz** [froala/wysiwyg-editor#2578]
Expected behavior.

(Describe expected behaviour here)

Actual behavior.

When i'm writing something inside the editor, and copy the text inside the editor and paste, the copied text is also having some unwanted HTML and CSS properties. In case we are using "froalaEditor.paste.beforeCleanup" event to manipulate the copied text.

```
$('div#froala-editor').on('froalaEditor.paste.beforeCleanup', function (e, editor, clipboard_html) { 
                 console.log(clipboard_html); 
                 var buffer = clipboard_html.replace(/\n/g, "<br />");
                 buffer = buffer.replace(/ /g, " "); 
                 this.buffer = buffer; 
}).on('froalaEditor.paste.afterCleanup', function (e, editor, clipboard_html) { 
                return this.buffer; 
});
```

write some text(say adipisicing voluptate), then copy and paste the same text. copied text is like -

`<meta charset='utf-8'><span style="color: rgb(0, 0, 0); font-family: Roboto, &quot;Open Sans&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">adipisicing voluptate</span>`

Codepen Link to reproduce --- [https://github.com/froala/wysiwyg-editor/issues/url](url)

@stefanneculai

**Comment by stefanneculai** [comment]
@pawansingh-snapwiz please make sure you're using the latest 2.7.5 version. There this shouldn't happen.
