### ISSUE TITLE
Can't prevent backspace button from erasing text

### ISSUE THREAD

**Issue by brandon-runbiz** [froala/wysiwyg-editor#2579]
##### Expected behavior.
I wanted to add behavior so that when the user is entering text in the editor and press the backspace button, it does not delete any text.

##### Actual behavior.
I can tap into the 'keydown' event of the editor when the user hits the backspace and I am calling preventDefault() but the backspace still fires and removes text.

##### Steps to reproduce the problem.
Here is the code I have that runs on initialization:

```js
$('div#froala-editor')
	.on('froalaEditor.initialized', function (e, editor) {

		editor.events.on('keydown', function (keypressEvent) {
			if (keypressEvent.which == 8) {
				e.preventDefault();
				e.stopPropagation();
			}
		}, true)
		
	}).froalaEditor()
```

The 'keydown' event hits and can determine when the backspace button is pressed in the editor, but calling e.preventDefault() and e.stopPropagation() does not cause the backspace to stop from firing and deleting text.

##### OS.
Windows 10

##### Browser.
Google Chrome Version 63.0.3239.132

**Comment by stefanneculai** [comment]
@brandon-runbiz you should `return false` to prevent the default action.

**Comment by brandon-runbiz** [comment]
@stefanneculai I put `return false` underneath my `e.stopPropagation();` and that didn't make a difference. The backspace button is still working to delete text.

**Comment by stefanneculai** [comment]
That's because you are using the wrong event: https://jsfiddle.net/wc5c3jhk/45/.

**Comment by brandon-runbiz** [comment]
That solved my problem! Thank you!
