### ISSUE TITLE
toolbar is not showing all buttons 

### ISSUE THREAD

**Issue by javeriaanwer** [froala/wysiwyg-editor#2580]
I am not getting all buttons in toolbar.

this is my code.

`var button = ['bold', 'italic', 'underline', 'strikeThrough', 'subscript', 'superscript', '|', 'fontFamily', 'fontSize', 'color', 'paragraphStyle', '|', 'align', 'formatOL', 'formatUL', 'outdent', 'indent', '|', 'paragraphFormat', 'specialCharacters', 'insertHR', '|', 'clearFormatting', 'insertLink', 'insertImage', 'embedly', 'insertFile', 'insertTable', '|', 'undo', 'redo', 'spellChecker', '|', 'help'];`

     $('#paste').froalaEditor({
            pluginsEnabled: ['aviary'],
            toolbarButtons: button,
            toolbarButtonsMD: button,
            toolbarButtonsXS: button,
            toolbarButtonsSM: button
        });

and this is the output I get.
![image](https://user-images.githubusercontent.com/25203829/36241549-dc8f541a-1238-11e8-8710-ed62561aeca9.png)

it works fine when I remove  pluginsEnabled: ['aviary'].

**Comment by dianaprajescu** [comment]
The [pluginsEnabled option](https://www.froala.com/wysiwyg-editor/docs/options#pluginsEnabled) specifies which plugins should be enabled in the editor instance. By passing `pluginsEnabled: ['aviary']`, you basically tell the editor to enable only the aviary plugin. Buttons from plugins that are disabled will not be displayed in the editor's toolbar.

**Comment by javeriaanwer** [comment]
okay, thank you, I ended up adding every button in PluginEnabled option ,
`['aviary', 'image', 'fontFamily', 'fontSize', 'help', 'colors', 'paragraphStyle', 'align', 'lists', 'outdent', 'indent', 'paragraphFormat', 'specialCharacters', 'hr', 'clearFormatting', 'link', 'embedly', 'file', 'table', 'undo', 'redo', 'spellchecker']`
now its showing all buttons.  💯 👍

**Comment by dianaprajescu** [comment]
By default all plugins are enabled. Therefore, if you are using all of them you could simply not use the `pluginsEnabled` option.

**Comment by javeriaanwer** [comment]
yes I got it, just checking how it works.
