### ISSUE TITLE
Feature request: AllowMultipleParagraphStyle option

### ISSUE THREAD

**Issue by mthomasson** [froala/wysiwyg-editor#2582]
Would it be possible to have a AllowMultipleParagraphStyle like for tablesMultipleStyles, linkMultipleStyles?

**Comment by stefanneculai** [comment]
https://www.froala.com/wysiwyg-editor/docs/options#paragraphMultipleStyles :)

**Comment by mthomasson** [comment]
Wooops! Sorry!
