### ISSUE TITLE
Is there any method or event or any way to mark red underline the words. 

### ISSUE THREAD

**Issue by sunjidshibly** [froala/wysiwyg-editor#2583]
I am making a custom spell-checker that works for Bangla language. I have own algorithm to detect the misspelled  word. Is there any method or event or any way to mark red underline the misspelled Bangla words so that on right button click I can create my own context menu. 

PS: I am a Business License holder. Is it ok to ask for support like this?

**Comment by stefanneculai** [comment]
What we'd recommend for that would be to create a custom class in CSS for this and apply the class using the `format.apply` method.
