### ISSUE TITLE
`html.insert` method wraps iframe tag with p tag

### ISSUE THREAD

**Issue by simsim0709** [froala/wysiwyg-editor#2584]
##### Expected behavior.
(Describe expected behaviour here)
When iframe tag is inserted by `html.insert` method, froala editor should not wrap iframe tag with `p`.

##### Actual behavior.
(Describe actual behaviour here)
When `html.insert` method is triggered with `iframe` tag, froala editor wraps iframe tag with `p` tag.

##### Steps to reproduce the problem.
(Describe the steps to reproduce the problem here)
Here is the fiddle:
https://jsfiddle.net/wc5c3jhk/8/

##### OS.
(OS name and version here)
Mac OS

##### Browser.
(Browser name an version here)

Chrome latest

**Comment by stefanneculai** [comment]
The editor is designed to wrap by default all the content inside the editor in P tags. If you want to disable this behaviour, then please use the enter option: https://jsfiddle.net/wc5c3jhk/9/.
