### ISSUE TITLE
Editor doesn't display or work properly in iOS 7.

### ISSUE THREAD

**Issue by chrisdeeming** [froala/wysiwyg-editor#2585]
##### Expected behavior.
iOS 7 is reported to be officially supported.

##### Actual behavior.
Apparently the editor doesn't load properly, and doesn't accept focus - tapping on whatever loads in place of the editor doesn't bring up the keyboard.

##### Steps to reproduce the problem.
Unfortunately this is a customer report and details are thin other than:

>Won't even put down a typing cursor or show the whole test box on my iPad.

This has been tested within our software and on the Froala WYSIWYG home page.

##### OS.
iOS 7

##### Browser.
Safari/Chrome

**Comment by stefanneculai** [comment]
@chrisdeeming it will take a little bit more to test this as on XCode 8, iOS 7 is no longer supported.

**Comment by chrisdeeming** [comment]
@stefanneculai not a total priority for us as we don't officially support iOS versions beyond iOS 10, though we do tend to have some graceful degradation for older versions. For now, we've just stopped the editor loading for iOS 7 and below (was previously 6 and below).

Given the difficulty of testing and supporting such an old version (nearly 5 years!) I'm not sure you'd be blamed for dropping support for it inline with what you can reasonably still test based on what Apple supports.

**Comment by stefanneculai** [comment]
According to the Browser Usage stats (https://caniuse.com/usage-table), there are very few users currently using iOS 7, therefore we decided to remove the support for it.

**Comment by chrisdeeming** [comment]
Perfectly reasonable and fine by us. Good move.

**Comment by chrisdeeming** [comment]
@stefanneculai when the browser support page was updated, I **think** you increased the Android minimum requirements to Android 6.

We've recently had issues reported with Android 4.x but Android 5.x seems to work fine. Worth noting that Android 5, I believe, was the first Android version to (mostly) ship with Chrome as its default browser. Which, if kept up to date, should obviously work fine regardless of Android version. It's also the version that ships with Amazon Fire tablet (or at least did) and the default browser on that is Silk (which is based on Chrome).

**Comment by stefanneculai** [comment]
Thanks for the info, Chris. We haven't changed the Android version now, it was changed last year.

**Comment by chrisdeeming** [comment]
Fair enough.

We've gone for blocking Froala on Android if the version is less than 5, but also only if they're not using a modern browser like Chrome or Firefox.
