### ISSUE TITLE
Backspace delets two alphabet instead of one in RTL...

### ISSUE THREAD

**Issue by FethiLamaici** [froala/wysiwyg-editor#2588]
##### Expected behavior.
The backspace in RTL should only delets one alphabet when is clicked once.
+++
As a user of XenForo script, this bug appears when the company updated their script to use the latest Version (2.7.5) of Froala Editor, the previous verion (2.7.4) didn’t have this issue. I tested the editor in your site as well and the same issue is there.

##### Actual behavior.
The backspace in RTL delets two or more alphabet instead of one when is clicked just once.

##### Steps to reproduce the problem.
1. Use RTL direction to write
2. For example, use Arabic language
3. Write something like (مرحبا فريولا) => (Hello Froala)
4. Now use backspace to delete an alphabet.

The results: The backspace will delete two alphabet instead of one!!

##### OS.
IOS 11.2.5 & IOS 11.3 Beta 1

##### Browser.
Safari and Chrome

**Comment by FethiLamaici** [comment]
Attached video:

[backspace-bug.zip](https://github.com/froala/wysiwyg-editor/files/1738179/backspace-bug.zip)

**Comment by FethiLamaici** [comment]
Hello @stefanneculai 

I tested the latest version 2.7.6 and unfortunately the backspace bug still exists.

In RTL “Arabic language”, clicking once on the backspace deletes two alphabets.

I appreciate if you can take a look again on this bug because it’s totally annoying when I write in Arabic with Froala editor.

Tested using IOS 11.3 beta 4 / Safari & Chrome

Thanks.

**Comment by stefanneculai** [comment]
@FethiLamaici could you please make a recording?

**Comment by ALMUSA** [comment]
Please see here 

https://www.dropbox.com/s/8mns9x0eztzmtiu/ScreenRecording_03-14-2018%2023-44-25.MP4?dl=0

**Comment by FethiLamaici** [comment]
Hello @stefanneculai 

In the following editor (https://www.froala.com/wysiwyg-editor/examples/editor-direction) the backspace bug doesn’t exist using RTL language “Arabic” but notice that now the bug is exiting when writing in LTR “English”.

Also if I choose the RTL editor from Froala demos site the bug exist with RTL writing and it’s fine with  LTR writing!

**Comment by ALMUSA** [comment]
Im wondering how long this is going to take to be fixed?

**Comment by stefanneculai** [comment]
@ALMUSA this should be fixed in version 2.8.1. Could you please check?

**Comment by ALMUSA** [comment]
This is now fixed Thanks @stefanneculai
