### ISSUE TITLE
Extra "fr-tag" class added to block elements

### ISSUE THREAD

**Issue by rwaters71** [froala/wysiwyg-editor#259]
Seems that the newest build adds an extra class to block elements ?

```
<p class="fr-tag">....</p>
```

**Comment by michaelGregoire** [comment]
I've upgraded to v1.2.5 and I'm still getting the fr-tag added to resulting html, even though I have not set the useFrTag option to true. Is there another option that I might be setting that is likely to set useFrTag to true?

**Comment by stefanneculai** [comment]
If you use getHTML and pass the param `add_fr_tag` it would override the `useFrTag` option.

**Comment by michaelGregoire** [comment]
Ok, thanks for the response. I'm not using getHTML. For now, since I'm already using htmlpurifier on that field, I'm using it to remove the class. However, it would be nice to not have it in the first place.

**Comment by stefanneculai** [comment]
@michaelGregoire could you try with the last commit and let me know if you still have the problem?

**Comment by michaelGregoire** [comment]
@stefanneculai that did the trick. Thank you.

**Comment by sunra** [comment]
v.2.2.4
how to disable adding extra classes "fr-dib fr-draggable" to images?

**Comment by piayo** [comment]
default,
```
    $editorTarget.froalaEditor({
        useClasses: false, //disable fr-classes
    }
```
when i get html
```
    var editor = $("#editor_target").data("froala.editor");
    editor.opts.useClasses = true;
    var html = editor.html.get();
    editor.opts.useClasses = false;
```
and destroy
```
    editor.opts.useClasses = true;
    editor.destroy();
```
