### ISSUE TITLE
Entering and deleting hiragana content on mobile loses the input position

### ISSUE THREAD

**Issue by markedmondson** [froala/wysiwyg-editor#2590]
##### Expected behavior.
I can type on mobile using the hiragana keyboard and then replace the characters with kanji.

##### Actual behavior.
Hitting backspace at any time to remove a hiragana character causes the editor to stop responding to further keyboard input.

##### Steps to reproduce the problem.
I type hiragana, the mark grows.
Then I type a backspace. The mark immediately disappears and the insertion point vanishes. All typing falls into a black hole.
Even if I manually set the insertion point again by tapping where it left off, there's no way to reset the mark. So there's no way to replace already typed hiragana with kanji.

Video showing issue: https://www.dropbox.com/s/29frp45z1ul5vcn/ScreenRecording_02-19-2018%2013-15-44.mp4?dl=0

##### Version
2.7.3

##### OS.
iOS 11

##### Browser.
Safari

**Comment by markedmondson** [comment]
It looks like this might have been fixed in 2.7.4. Still testing, will come back and close if so.

**Comment by stefanneculai** [comment]
@markedmondson indeed, it should be fixed in 2.7.4.
