### ISSUE TITLE
Pasting Empty Tags

### ISSUE THREAD

**Issue by mattbolt** [froala/wysiwyg-editor#2591]
##### Expected behavior.
When pasting HTML into the editor that contains empty tags, it should respect the "htmlAllowedEmptyTags" option.

##### Actual behavior.
Only tags in the $.FE.VOID_ELEMENTS list are not cleaned during the paste process.

##### Steps to reproduce the problem.

- Setup an editor with option `htmlAllowedEmptyTags: ['customtag']`
- Paste in some HTML content that contains `<customtag />`

##### OS.
Windows

##### Browser.
Chrome

##### Context.
PHP: 7.1.9
Froala: 2.7.5

**Comment by stefanneculai** [comment]
The `htmlAllowedEmptyTags` is for tags which are empty, not for void tags. By default, we allow as VOID tags the ones from HTML5. I marked this as an enhancement in order to add an option to extend the list.

**Comment by stefanneculai** [comment]
@mattbolt I believe your problem actually comes from the fact that you are not adding the custom tag to the `htmlAllowedTags` option.

**Comment by mattbolt** [comment]
I definitely have the custom tag added to htmlAllowedTags option.

**Comment by stefanneculai** [comment]
@mattbolt please find here a working example: https://jsfiddle.net/wc5c3jhk/88/.

**Comment by mattbolt** [comment]
Thanks @stefanneculai i will look over my code again and see if I can either reproduce the error or fix the problem ;)

**Comment by stefanneculai** [comment]
Thanks for the jsFiddle. It looks the problem was there only when pasting from one editor to another.

**Comment by mattbolt** [comment]
I thought so too - however it works when you don’t have my plugin enabled and a reduced set of options ... just htmlAllowedTags and htmlAllowedEmptyTags - I can send a fiddle tomorrow if you need

**Comment by stefanneculai** [comment]
The last commit should fix it anyway :)
