### ISSUE TITLE
Selecting a whole tag of formatted text and start writing removes the formatting

### ISSUE THREAD

**Issue by mthomasson** [froala/wysiwyg-editor#2593]
##### Expected behavior.
If I format some text (color, bold, italic, ...), select the whole text and start typing (just to replace the text), the formatting should still be as I set it up.
##### Actual behavior.
The whole tag is removed, and so is the formatting. The new text is added in a new tag

##### Steps to reproduce the problem.
- Write some text
- format it
- Start typing again (with the text still selected)
##### OS / Browser.
Any OS  or browser (froala demo too)

**Comment by stefanneculai** [comment]
@mthomasson please use the `keepFormatOnDelete` for that.

**Comment by mthomasson** [comment]
@stefanneculai 
Awesome! Thxs!!!
