### ISSUE TITLE
contenteditable option does not work as expected

### ISSUE THREAD

**Issue by mthomasson** [froala/wysiwyg-editor#2594]
##### Expected behavior.
With the contenteditable="false" attribute on a link, I would expect the link edition menu to open when I click on the link instead of being redirected. 

##### Actual behavior.
Having the link edition menu opening is really hard. You need to select smoothly all the text of the link before the menu shows up (users never find it).  And if you click on the link you get redirected (or a new tab open and you get redirected). This makes no sense because users can see the URL when editing the link, so he can open it whenever he wants

##### Steps to reproduce the problem.
- Create a link.
- Add the attribute contenteditable="false"
- Play around with the link

##### OS / Browser.
Any OS or browser.

**Comment by stefanneculai** [comment]
Having `contenteditable="false"` attribute on a link should prevent showing the link-edit popup.

**Comment by mthomasson** [comment]
@stefanneculai 
Do you have an idea how I could disable the text editing inside the editor, but leave the option of opening the link edit panel on click on the link?
