### ISSUE TITLE
Can't type in editor after adding caption to image

### ISSUE THREAD

**Issue by FWennerdahl** [froala/wysiwyg-editor#2597]
##### Expected behavior.
If an image with a caption is added to an empty editor, you should be able to add new paragraphs and type.

##### Actual behavior.
If an image with a caption is added to an empty editor, you can't add any new paragraphs or type text. No line insert helper is shown either, making impossible to add more textual content.

##### Steps to reproduce the problem.
1. Open the demo editor on https://www.froala.com/wysiwyg-editor.
2. Remove everything in the editor.
3. Insert an image.
4. Add a caption to the image.
5. Click outside the image and try to type.
![image-caption-cant-type](https://user-images.githubusercontent.com/3178426/36534356-9ea060de-17c6-11e8-8619-8bd75229edfc.gif)

##### OS.
macOS 10.12.6

##### Browser.
Chrome 64.0.3282.167

**Comment by zstrad44** [comment]
This issue has not been resolved. See demo of exact same issue as the one shown above here: http://ronz.io/sof8Gh

If you upload an image with no other text or content, it does not allow you to type or add more content.

Please let me know if you would like me to create this as a separate issue.

**Comment by sai-velamuri** [comment]
@zstrad44 Any luck on this? I'm fighting this bug for a long time.

**Comment by zstrad44** [comment]
@sai-velamuri This appears to have been resolved on my end. Have you updated to the latest version?
