### ISSUE TITLE
Froala editor is removing the tab character when pasting content to it

### ISSUE THREAD

**Issue by guipilon** [froala/wysiwyg-editor#2599]
##### Expected behavior.
When copy/pasting a text to froala's editor containing a tab in it, the tab character should be preserved in the editor

##### Actual behavior.
When copy/pasting a text to froala'a editor containing a tab in it, the tab character is being removed by editor in the Cleanup process

##### Steps to reproduce the problem.
Copy this text to froala's editor:

This is a paragraph.
	This is another paragraph.
This is the last paragraph.

Verify that the second paragraph is pasted without the tab.

Additional info:
 - String returned in the beforeCleanup.paste event:
`This is a paragraph.<br>	This is another paragraph.<br>This is the last paragraph.`

 - String returned in the afterCleanup.paste event:
`This is a paragraph.<br>This is another paragraph.<br>This is the last paragraph.`

##### OS.
Ubuntu 17.10

##### Browser.
Google Chrome 64

**Comment by stefanneculai** [comment]
In HTML the tab character has no use and that's why it is being removed on purpose.

**Comment by guipilon** [comment]
But if I want to persist the formatting style of a pasted text?

**Comment by stefanneculai** [comment]
The editor is designed to always remove the TAB character all the time. It is not possible to keep it. What I would recommend instead would be in the beforeCleanup.paste to convert tabs to multiple spaces.
