### ISSUE TITLE
Froala throws a SyntaxError in IE11

### ISSUE THREAD

**Issue by jemunk** [froala/wysiwyg-editor#2604]
Our automatic error reporting which gathers error from the clients, reports several "SyntaxError" exceptions
in froala.min.js in this function:
`function B(a){return a&&"BR"==a.tagName?!1:0===(a.textContent||"").length&&a.querySelector&&!a.querySelector(":scope > br")}`

So far reported from IE11 clients only.
Our froala version is latest 2.7.5.

**Comment by stefanneculai** [comment]
Fixed on the current master.
