### ISSUE TITLE
Prevent or override replace image

### ISSUE THREAD

**Issue by mcblum** [froala/wysiwyg-editor#2605]
##### Expected behavior.
We'd like to either remove the replace image functionality within the Image Manager or hijack it to use our custom image management.

##### Actual behavior.
Reading through the docs I can't see a way to modify which things are available in the image manager. Ideally, we could add our own replace button that does our own stuff.

##### OS.
Mac Latest

##### Browser.
Chrome

**Comment by stefanneculai** [comment]
@mcblum I would recommend creating a custom button inside the image popup which would open your custom image management: https://www.froala.com/wysiwyg-editor/examples/custom-image-button.
