### ISSUE TITLE
table resize functionality "lost" after scrolling the page

### ISSUE THREAD

**Issue by sanna-woo** [froala/wysiwyg-editor#2606]
##### Expected behavior.
create a new table, scroll down a bit, resizing the table still possible.

##### Actual behavior.
the table resizing functionality only works as long as I do not scroll down the page. It seems like the ' .fr-table-resizer' is absolute positioned to some other parent element than the table.

##### Steps to reproduce the problem.
just visit this page https://www.froala.com/wysiwyg-editor/examples/table-styles
scroll down a bit, try to resize the table

##### OS.
Win 10

##### Browser.
Chrome v63.0.3239.132 (Offizieller Build) (64-Bit)

**Comment by stefanneculai** [comment]
@sanna-woo this should be fixed on the current master. Could you please check?

**Comment by ncmancuso** [comment]
@stefanneculai is there an isolated commit for this fix that I can use for the meantime until we do a version upgrade?

**Comment by stefanneculai** [comment]
@ncmancuso unfortunately, we cannot provide that.
