### ISSUE TITLE
2 Issues with Aviary in Chrome when multiple Froala editors on the same page

### ISSUE THREAD

**Issue by SeanKendle** [froala/wysiwyg-editor#2607]
On pages with more than one editor, there are 2 errors that arise depending on the order of events. I will try to lay these out as well as I can.

1. **Loading a single editor**, adding a new editor, then attempting to crop and save an image in the first editor in Aviary results in the following error:

> image.js:2816 
Uncaught DOMException: Failed to execute 'selectNode' on 'Range': the given Node has no parent.
    at _selectImage (https://manage.joyceinc.com/resources/froala/js/plugins/image.js:2816:15)
    at HTMLImageElement._edit (https://manage.joyceinc.com/resources/froala/js/plugins/image.js:2445:33)
    at Object._editImg [as edit] (https://manage.joyceinc.com/resources/froala/js/plugins/image.js:746:13)
    at Image.img.onload (https://manage.joyceinc.com/resources/froala/js/third_party/image_aviary.js:109:57)
_selectImage @ image.js:2816
_edit @ image.js:2445
_editImg @ image.js:746
img.onload @ image_aviary.js:109

![aviary-error-01](https://user-images.githubusercontent.com/5393604/36692016-eda1d28a-1b04-11e8-8673-f44492a81226.gif)

2. **Loading a page with two editors**, then attempting to crop and save an image in the first editor in Aviary results in the following error:

> image_aviary.js:123 
Uncaught TypeError: Cannot read property 'image' of undefined
      at Object.onClose (image_aviary.js:123)
      at Object.n.paintWidgetShutdown (VM859 editor.js:2)
      at HTMLDivElement.<anonymous> (VM859 editor.js:2)
      at HTMLDivElement.a.complete (VM907 feathercontrols_en.js:6)
      at fx.step (VM907 feathercontrols_en.js:6)
      at i (VM907 feathercontrols_en.js:6)
      at tick (VM907 feathercontrols_en.js:6)

![aviary-error-02](https://user-images.githubusercontent.com/5393604/36692026-f1d5b1fa-1b04-11e8-9754-5d1bf00fac71.gif)

##### OS.
Windows 7 Pro

##### Browser.
Chrome - v64.0.3282.186 (Official Build) (64-bit)

**Comment by stefanneculai** [comment]
@SeanKendle could you please check you're using the latest 2.7.5 version? Thanks.

**Comment by SeanKendle** [comment]
No, v2.7.5 broke our implementation as described in another of my posts.

**Comment by SeanKendle** [comment]
However, I did a diff with the aviary plugin and it's the same exact file.

**Comment by stefanneculai** [comment]
We can't reproduce on our side in version 2.7.5. Do you think you could create a jsFiddle where we can reproduce it? Here is one you could use as a starting point: https://jsfiddle.net/froala/wc5c3jhk/.

**Comment by SeanKendle** [comment]
We cannot update to v2.7.5 because it breaks our editor per: https://github.com/froala/wysiwyg-editor/issues/2562

**Comment by stefanneculai** [comment]
@SeanKendle I understand that the other issue is in our attention. It would be good if you could test this issue with the latest version 2.7.5 and let us know how to replicate it, as we can't do it on a clean editor instance. If the issue is not present in version 2.7.5, then it's left only the other issue which will be addressed shortly.

**Comment by SeanKendle** [comment]
How can I include the aviary plugin on that fiddle?

**Comment by stefanneculai** [comment]
https://jsfiddle.net/wc5c3jhk/35/

**Comment by SeanKendle** [comment]
Thanks, I've updated it. Looks like I can't recreate it in this version. I'll definitely test once we upgrade to the next version once that's out. For now I think this is resolved, but I will comment with my findings after the next Froala update. Thanks again!

**Comment by SeanKendle** [comment]
Test fiddle:

https://jsfiddle.net/46ahu03g/

**Comment by SeanKendle** [comment]
This had to do with how I was instantiating my own custom plugins, not an issue with Froala. I've fixed it on my end.
