### ISSUE TITLE
Image Editor Menu Popups are not working

### ISSUE THREAD

**Issue by javeriaanwer** [froala/wysiwyg-editor#2608]
Hi,

I am having this issue, sometimes image editor menu popups does not appear in froala editor. Please see following gif for reference. 

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/25203829/36719191-27b9efc2-1bc6-11e8-97b1-5191bfb71222.gif)

**Comment by stefanneculai** [comment]
@javeriaanwer could you please let us know if you can reproduce this on our website or create a jsFiddle where we can reproduce it? Thank you.

**Comment by stefanneculai** [comment]
@javeriaanwer are you seeing this on our website demo as well? https://www.froala.com/wysiwyg-editor
