### ISSUE TITLE
Style tag is removed after toggling code view

### ISSUE THREAD

**Issue by ibmalo95** [froala/wysiwyg-editor#2609]
Expected behavior.
When using code view to add a style tag at the top of the editor, it should apply the styles and should be visible when you enter code view again.

Actual behavior.
It doesn't apply the CSS and when you toggle back to code view the tag is no longer there.

Steps to reproduce the problem.
1. In code view, add a style tag to the top of the editor (above all other elements)
2. Toggle away from code view and then toggle back
3. The style tag will no longer be there
Note: If the style tag is not at the top it will do the expected behavior.

Example:
Before toggling away from code view:
`<style>.style-test {color: red;}</style><div class="style-test">test</div>`

After:
`<div class="style-test">test</div>`

OS.
Mac OS 10.12 Sierra

Browser.
Chrome Version 64

**Comment by Trapdafifou** [comment]
What is the ETA of this ticket ?

**Comment by altjx** [comment]
Any updates on this?

**Comment by stefanneculai** [comment]
@altjx this is fixed and should work correctly in the latest 2.8.4 version.
