### ISSUE TITLE
Backspace with RTL text deletes two characters

### ISSUE THREAD

**Issue by chrisdeeming** [froala/wysiwyg-editor#2611]
##### Steps to reproduce the problem.
https://xenforo.com/community/data/xfmg/video/168/168320-7843a2a14280e46852d10272a76333c0.mp4

##### Browser.
iOS 11.3 Beta (may affect others)

**Comment by FethiLamaici** [comment]
Hello Chris,

Sorry for not updating the bug thread on Xenforo.

I already posted the same bug here:
https://github.com/froala/wysiwyg-editor/issues/2588

Hopefully get sorted out in the next release.
