### ISSUE TITLE
Paragraph Style events do not differentiate between adding and removing

### ISSUE THREAD

**Issue by cdepuydt** [froala/wysiwyg-editor#2612]
##### Expected behavior.
The paragraphStyle after event (froalaEditor.commands.after) should either have a second parameter that states if the class was added or removed, or else there should be two different events.  This probably also affects the before event.

##### Actual behavior.
The paragraphStyle after event just fires a single event stating that something was done with the returned class name.

##### Steps to reproduce the problem.
Add a paragraphStyle button to a menu.  Add the following event handler and then select a style.
```
    $editorElement.on('froalaEditor.commands.after', function (e, editor, cmd, param1, param2) {
        console.log(e);
        console.log(editor);
        console.log(cmd);
        console.log(param1);
        console.log(param2);
        }
    });
```
Nothing in the returned parameters states what happened with the class other than directly interrogating the returned value in the event.

##### OS.
Windows 10

##### Browser.
Chrome

**Comment by stefanneculai** [comment]
The `commands.after` method is designed to pass the parameters the command gets when it is being called in the editor, no additional info about what happened during that action. If you need to get the styles for the current paragraph, I would recommend using the `selection.blocks` method to get the current active paragraph and then the styles from it.

**Comment by cdepuydt** [comment]
It's not about knowing what the styles were, it's about knowing what the event actually was, an add or a remove, since this will drive the logic of anything that would be called in this sort of event.  In my case, I was trying to modify the text that the class was being added to, and what I needed to do varied dramatically between an add or a delete.

**Comment by stefanneculai** [comment]
I understand your use-case and that could be achieved by using a combination of `commands.before` with `commands.after`. Adding to all editor actions such a custom action would result in a lot of additional code being added to the editor core which is used by very few. Thus, the size of the editor bundle would grow a lot unnecessary.
