### ISSUE TITLE
Pasting Image into Editor forces image classes to be applied when they shouldn't

### ISSUE THREAD

**Issue by SeanKendle** [froala/wysiwyg-editor#2620]
##### Expected behavior.
Copy/pasting an image into the editor should not apply default image classes when `imageAlign` and `imageDisplay` buttons are removed from the `imageEditButtons` option per: https://github.com/froala/wysiwyg-editor/issues/2351

##### Steps to reproduce the problem.
Remove `imageAlign` and `imageDisplay` from the `imageEditButtons` option, then copy/paste an image into the editor.

(testing on v2.7.3, and also on v2.7.5 here:  https://jsfiddle.net/gj8Lsnyg/6/ )

##### OS.
Windows 7 Pro

##### Browser.
Firefox (latest)
Chrome (latest)

**Comment by stefanneculai** [comment]
Starting with version 2.7.4, it is possible to pass `null` to the `imageDefaultAlign` and `imageDefaultDisplay` options. Please use this as a replacement for the old way of doing it.
