### ISSUE TITLE
Critical BUG - Froala editor suddenly becomes "read only" after random paste/typing

### ISSUE THREAD

**Issue by idoromm** [froala/wysiwyg-editor#2625]
(Using in React JS / Node app)

##### Expected behavior.
Typing/pasting content (text) normally

##### Actual behavior.
Editor randomly becomes "disabled" or "read only" and only works after refresh or render() is called on the editor. 
Reproducing it for us does not depend on character count or line count (it can happen with 1 character each line for 5 lines, or 19 lines etc...)

##### Steps to reproduce the problem.
Video:

![t](https://user-images.githubusercontent.com/14105492/37049698-90354578-2126-11e8-94e4-9be05d623c62.gif)

As you can see the editor suddenly becomes stuck
(behavior is random is "steps" cannot be described really)

##### OS.
Windows 10 / 7

##### Browser.
Chrome/Firefox    / others not tested

**Comment by wakirin** [comment]
@idoromm why did you close it ? do you found solution ?

**Comment by poohitan** [comment]
That's an intended behaviour if you use the editor without a license. Kind of a protection from unlicensed use. The editor will work properly if you purchase a license.

But I wonder why the dev team tries to hide this fact in all the possible ways. Lots of people think it's a bug, while it's not.

**Comment by ganeshselva95** [comment]
@poohitan Isn't it Obvious poohitan?! Why would some one buy just an editor for $300. The license cost of this editor is obscene. There are versions of froala already pirated and you guys can do nothing about that.

Best of Luck!🤣

**Comment by poohitan** [comment]
@ganeshselva95 not sure what do you mean under "isn't it obvious".

**Comment by EugeCos** [comment]
@idoromm did you manage to resolve this issue? 
One of our customers is currently experiencing the same and we don't know from what angle to approach this.
