### ISSUE TITLE
There is a problem when deleting a tag.

### ISSUE THREAD

**Issue by largeden** [froala/wysiwyg-editor#2626]
##### Expected behavior.
Type 'test.com' (a `a` tag is automatically insert).
Then use the backspace key to delete 'test.com'.
`a` tags and characters will be deleted.

##### Actual behavior.
An empty `a` tag remains.

##### Steps to reproduce the problem.
- Type 'test.com' (a `a` tag is automatically generated).
- Then use the backspace key to delete 'test.com'.
- Check the source code in Code view.
- An empty `a` tag remains.
```html
<p><a href="//test.com"></a></p>
```

##### OS.
Windows 10 pro

##### Browser.
Chrome

##### froala editor
Last commit version

---
This issue was not seen in v2.7.3

**Comment by GMiLL5** [comment]
The fix for this seems to have some unintended consequences, it's deleting block-level nodes as you backspace inside them:
![froala-weird-backspace](https://user-images.githubusercontent.com/1800407/38883498-7659b36c-4243-11e8-8297-71d704c78309.gif)

@stefanneculai
