### ISSUE TITLE
Froala Editor Image Uploading Issue in NGINX Server

### ISSUE THREAD

**Issue by pkundariya** [froala/wysiwyg-editor#2628]
Hi Guys,

I have issue with uploading image to editor from long time. i am not finding any solution could anyone please help me out to this?

My Server is NGINX so please give solution according it. Thanks

I am using Froala Editor. When trying to drag and drop image to upload in editor i see below error message.

In Console Error Message is:

> **Refused to load the image 'blob:https://www.example.com/831a7599-7b0c-416c-ab79-7678f2409e7d' because it violates the following Content Security Policy directive: "default-src https: data: 'unsafe-inline' 'unsafe-eval'". Note that 'img-src' was not explicitly set, so 'default-src' is used as a fallback.**

![image](https://user-images.githubusercontent.com/37189926/37167713-bb3d2886-2328-11e8-82b6-d10e707073b2.png)

Could you please help me to resolve this?

Thank you in advanced
Parth

**Comment by stefanneculai** [comment]
@pkundariya it looks you have a CSP set on the page. Please see https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP and allow loading images from the same website.

**Comment by pkundariya** [comment]
it is not for perticular browser it is for all browsers so we need to set header at server configuration file. Let me know how can i do it?

**Comment by pkundariya** [comment]
Can you guide me what is configuration setting for that issue?

**Comment by stefanneculai** [comment]
@pkundariya for now you'd have not to set the the CSP on the page and allow img-src.

**Comment by pkundariya** [comment]
Ok, but server settings are not possible my side to edit so can you guide me what to do so i can tell to owner and hosting company

**Comment by pkundariya** [comment]
it is kind of secure dedicated server so we have limited it

**Comment by stefanneculai** [comment]
The CSP is a tag that you add on the page. You would have to whitelist there image-src: https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP.

**Comment by pkundariya** [comment]
<meta http-equiv="Content-Security-Policy" content="default-src 'self'; img-src *">

**Comment by pkundariya** [comment]
`<meta http-equiv="Content-Security-Policy" content="default-src 'self' *.m5idoingit.com; img-src *">`

**Comment by pkundariya** [comment]
(index):1 Refused to load the image 'blob:https://www.m5idoingit.com/3d65efe9-4507-4c10-acbf-62ea44958a59' because it violates the following Content Security Policy directive: "default-src https: data: 'unsafe-inline' 'unsafe-eval'". Note that 'img-src' was not explicitly set, so 'default-src' is used as a fallback.

**Comment by pkundariya** [comment]
**Still i have issue can you please help me out?**

**Comment by pkundariya** [comment]
at nginx server meta will not work might be
