### ISSUE TITLE
2.7.6 bundle only includes minified JS

### ISSUE THREAD

**Issue by markedmondson** [froala/wysiwyg-editor#2629]
##### Expected behavior.
Previously the full source files were in the zip but now I only see the .min files for the javascript (the CSS is still available raw). Is this a conscious decision?

##### Actual behavior.
No raw JS source files.

**Comment by stefanneculai** [comment]
If you have a Business or Professional license, the unminifies JS is available for download from our website. Just make sure you are logged in and download from oue website.

**Comment by markedmondson** [comment]
Ah, I wasn't logged in. Thanks :)
