### ISSUE TITLE
Attempting to destroy editor fails when using `editInPopup` option

### ISSUE THREAD

**Issue by jacobq** [froala/wysiwyg-editor#2630]
##### Expected behavior.
Calling [`.froalaEditor('destroy');`](https://www.froala.com/wysiwyg-editor/docs/methods#destroy) after initializing with the [`editInPopup` options](https://www.froala.com/wysiwyg-editor/docs/options#editInPopup) should not result in any errors.

##### Actual behavior.
As you can see [in this jsbin](https://jsbin.com/qenucug/9/edit?html,js,output), this results in `TypeError: Cannot read property 'removeAttr' of undefined`.
![image](https://user-images.githubusercontent.com/1633459/37181514-f1c1e184-22f2-11e8-81f0-22c849438e64.png)

This did not happen in v2.7.5, so I suspect it to be a regression between [v2.7.5 and v2.7.6](https://github.com/froala/wysiwyg-editor/compare/v2.7.5...v2.7.6).

##### Steps to reproduce the problem.
(see jsbin link above)

##### OS.
OS independent but tested on Debian Linux 9 64-bit

##### Browser.
Chrome 64.0.3282.167 (Official Build) (64-bit)

cc @panman8201

**Comment by Panman8201** [comment]
Yep, that's the error [ember-froala-editor](https://github.com/froala/ember-froala-editor) is seeing on the [failing build](https://travis-ci.org/froala/ember-froala-editor/jobs/350988053#L2852) for this new version.

Thanks for tracking this down and reporting it @jacobq !
