### ISSUE TITLE
pastePlain option is not working

### ISSUE THREAD

**Issue by seb303** [froala/wysiwyg-editor#2631]
##### Expected behavior.
When pastePlain is set true I would expect any pasted content to appear as plain text only

##### Actual behavior.
Rich content is pasted

##### Steps to reproduce the problem.
https://www.froala.com/wysiwyg-editor/examples/plain-paste
Copy the existing text in the editor, and paste it back in.
The link "pastePlain" is not removed.
Same happens with any external content pasted it.

##### OS.
Windows 8.1

##### Browser.
Firefox 58
Chrome 65
In Internet Explorer 11, some rich content is removed (e.g. links and bold), but some is not (e.g. tables)

**Comment by stefanneculai** [comment]
@seb303 thanks for reporting this. The editor is designed to keep tables on plainPaste.

**Comment by jwhitmarsh** [comment]
@stefanneculai sorry to comment on an old issue, but i'm fighting this exact issue currently - is there a way to disable keeping tables on plainPaste? My users are pasting lines and lines from Excel, and having to manually remove the inserted table html each time.

**Comment by phil-bell** [comment]
In case anyone comes across this, you can block paste styles and tables like so:
``` 
pastePlain: true,
pasteDeniedTags: ["table"],
```
