### ISSUE TITLE
Extra spaces inserted when pasting 

### ISSUE THREAD

**Issue by seb303** [froala/wysiwyg-editor#2632]
##### Expected behavior.
Multiple white-space in pasted HTML should collapse to single spaces.

##### Actual behavior.
Every white-space in pasted HTML is rendered as an individual space.

##### Steps to reproduce the problem.
Go here, and copy & paste some content which has multiple white-space in the source.
https://www.froala.com/wysiwyg-editor/examples/enter

##### OS.
Windows 8.1

##### Browser.
Firefox 58
Chrome 65
Internet Explorer 11

Here's an example....

Copy text from Thunderbird email:
![image](https://user-images.githubusercontent.com/467942/37204853-5e07ef90-238a-11e8-9476-4b96b748051f.png)

Source looks like this:
![image](https://user-images.githubusercontent.com/467942/37204881-7be5b25e-238a-11e8-981e-be17dd9c4963.png)

Result looks like this:
![image](https://user-images.githubusercontent.com/467942/37204913-9fc8767a-238a-11e8-99db-3cd65d7a1dca.png)

**Comment by stefanneculai** [comment]
@seb303 could you please send us the HTML so that we can play with it?

**Comment by seb303** [comment]
Hi,

Here is a sample (rename the file to .html):
[sample.html.txt](https://github.com/froala/wysiwyg-editor/files/1800850/sample.html.txt)

I've tried copy and pasting from Thunderbird and Firefox and in both cases it results in visible spaces wherever there are spaces in the HTML.  Pasting with Shift-Ctrl-V results in correct pasting (plain text with spaces collapsed).

Seb

**Comment by stefanneculai** [comment]
@seb303 do you have the tabSpaces option enabled?

**Comment by seb303** [comment]
No.

The same thing happens on your example editors here, so I don't think it's to do with the options I'm using.
https://www.froala.com/wysiwyg-editor/examples/enter

**Comment by stefanneculai** [comment]
@seb303 could you please send us the HTML that you get in the `paste.beforeCleanup` event?

**Comment by seb303** [comment]
Some example HTML from paste.beforeCleanup attached.  The HTML is fine here - it has the whitespace as does the source, but it hasn't been converted to &nbsp; or anything.  This is how it looks in the editor:

![image](https://user-images.githubusercontent.com/467942/37930183-ee5084e2-3139-11e8-8a7e-705671b5fa56.png)

[html_from_paste.beforeCleanup.txt](https://github.com/froala/wysiwyg-editor/files/1849368/html_from_paste.beforeCleanup.txt)

**Comment by seb303** [comment]
Even the html from paste.afterCleanup is ok.  Please see attached.  Again, it has the extra whitespace from the source, but this should collapse.
[html_from_paste.afterCleanup.txt](https://github.com/froala/wysiwyg-editor/files/1849377/html_from_paste.afterCleanup.txt)

**Comment by seb303** [comment]
Should this bug be fixed in v2.8.0 ?
I'm still seeing exactly the same behaviour...

**Comment by devoficial** [comment]
@stefanneculai  is this bug fixed on higher versions, I am facing this issue with 4.0.4 version
