### ISSUE TITLE
Add Option for Line Breaker to Move to Mouse X position on show

### ISSUE THREAD

**Issue by SeanKendle** [froala/wysiwyg-editor#2633]
Line Breaker shows up in the center of the parent element, so things like floated-left photos make it impossible to insert a line break.

##### Steps to reproduce the problem.
You'll have to add the line breaker plugin to the live example at https://www.froala.com/wysiwyg-editor

Then, paste in this code:

`<p><img src="https://s3-eu-west-1.amazonaws.com/froala-eu/temp_files%2F1520607126390-Hydrangeas.jpg" style="width: 300px;" class="fr-fic fr-dib fr-fil"><img src="https://s3-eu-west-1.amazonaws.com/froala-eu/temp_files%2F1520607126390-Hydrangeas.jpg" style="width: 300px;" class="fr-fic fr-dib fr-fil"></p>`

Hover your mouse between the two images, the line breaker should show up. Because the button is so far to the right, you can't get your mouse to the button quickly enough to click it.

Instead, the button should show up at the same X position as the mouse, or at least centered on the target element, in this case the image.

##### OS.
Windows 7 Pro

##### Browser.
All

**Comment by stefanneculai** [comment]
Because of the way the images are displayed, sometimes we cannot get this info accurate. Because of that, we decided not to add image to the `lineBreakerTags` option and implement a different approach. If you click above/below the image, you can get a new line there directly.
