### ISSUE TITLE
Can't Backspace or Delete P tag if before or after contenteditable="false"

### ISSUE THREAD

**Issue by SeanKendle** [froala/wysiwyg-editor#2634]
##### Expected behavior.

- If the cursor is after a contenteditable=false element, hitting backspace should delete the P tag, leave cursor where it is
- If the cursor is before a contenteditable=false element, hitting the delete key should delete the P tag, leave cursor where it is

##### Actual behavior.
Can't delete P tags that are before contenteditable=false elements using delete key
Can't delete P tags that are after contenteditable=false elements using backspace key

##### Steps to reproduce the problem.
Insert this code into editor at https://www.froala.com/wysiwyg-editor:

```
<div contenteditable="false"><img src="https://s3-eu-west-1.amazonaws.com/froala-eu/temp_files%2F1520607126390-Hydrangeas.jpg" style="width: 300px;" class="fr-fic fr-dib fr-fil"></div>

<p>
	<br>
</p>

<div contenteditable="false"><img src="https://s3-eu-west-1.amazonaws.com/froala-eu/temp_files%2F1520607126390-Hydrangeas.jpg" style="width: 300px;" class="fr-fic fr-dib fr-fil"></div>
```

Place cursor in P tag between images, hit backspace, hit delete. Nothing happens.

##### OS.
Windows 7

##### Browser.
All

**Comment by stefanneculai** [comment]
That's because, by default, the editor is designed not to delete block tag elements. If you'd like to make it deletable, it is necessary to add the `fr-deletable` class to it.

```html
<p contenteditable="false" class="fr-deletable">...</p>
```

**Comment by SeanKendle** [comment]
You misunderstand, it's not the P tag that I want to delete which has contenteditable false, but the P tag (which does not) before it (or after), please review my example code.

**Comment by SeanKendle** [comment]
I've changed them to `DIV`s with `contenteditable="false"` to make my example more clear. I want to be able to backspace within the P tag, and delete the P tag itself.

**Comment by stefanneculai** [comment]
Thanks for the clarification, Sean. I see what you mean now.

**Comment by stefanneculai** [comment]
We've checked this again and decided to leave the current implementation as it is. Removing that line would result in not being possible to add a line between those 2 non-editable lines easily.

**Comment by SeanKendle** [comment]
To be able to add back in that line, I just add those tags to the Line Breaker tags array. It seems to work fine.
