### ISSUE TITLE
Triple Click in a Div, selection bleeds into next Div (Chrome)

### ISSUE THREAD

**Issue by SeanKendle** [froala/wysiwyg-editor#2635]
##### Expected behavior.
Triple-click to select text within a Div should only select the text within that div. It appears to also select partially into the next Div

##### Actual behavior.
It appears to also select partially into the next Div

##### Steps to reproduce the problem.
Add this code into the editor at https://www.froala.com/wysiwyg-editor:

```
<div class="grid" contenteditable="false" style="display: flex; flex-wrap: wrap; clear: both;">
	<div class="fr-inner" contenteditable="true" style="flex: 0 0 20%; border: 1px solid black;">
		test1 test1
	</div>
	<div class="fr-inner" contenteditable="true" style="flex: 0 0 20%; border: solid 1px black;">
		test2
	</div>
	<div class="fr-inner" contenteditable="true" style="flex: 0 0 20%; border: solid 1px black;">
		test3
	</div>
	<div class="fr-inner" contenteditable="true" style="flex: 0 0 20%; border: solid 1px black;">
		test4
	</div>
	<div class="fr-inner" contenteditable="true" style="flex: 0 0 20%; border: solid 1px black;">
		test5
	</div>
</div>
```

Triple-click "test1 test1", center the text. "test2" will also center.

Here's what the selection looks like in the source view:
![image](https://user-images.githubusercontent.com/5393604/37223758-7d2ae7be-239f-11e8-94cb-e6a4cf3df330.png)

##### OS.
Windows 7 Pro

##### Browser.
Chrome Version 65.0.3325.146 (Official Build) (64-bit) - ONLY

**Comment by stefanneculai** [comment]
This is how the browser selection works and we're not changing it in any way.
