### ISSUE TITLE
Image Popup closing when using external file manager

### ISSUE THREAD

**Issue by SeanKendle** [froala/wysiwyg-editor#2636]
I have created a new tab and Browse button to open an iframe with our file manager in it, for selecting images. 

In the _inputFocus function in froala_editor.js, there is a bit of code that causes the image insert popup to hide when I click inside the file manager iframe:
```
//IE workaround.
setTimeout(function () {
	inst.events.enableBlur();
}, 100);
```

I have to comment that out to prevent the popup from closing while selecting an image.

Is there any way to work around that, without having to edit froala_editor.js for each release?

##### OS.
Windows 7 Pro

##### Browser.
Firefox, Chrome, IE

**Comment by stefanneculai** [comment]
The editor is designed to trigger the blur event when another elements from the page are being focused. For this situation, I would recommend to use the events.disableBlur if you'd like to keep the popup active. A better approach would be to open the popup again instead of keeping it open when your modal is visible.

**Comment by SeanKendle** [comment]
I tried using events.disableBlur before, but the 100ms timeout creates a race condition. I could set a timeout for 101ms, or something like that, but that feels hacky. I'll see if I can get the popup to open again. Thanks.

**Comment by stefanneculai** [comment]
I know it might look a little bit hacky, however, IE forces us to do it for now.

**Comment by SeanKendle** [comment]
I know the "joys" of working with IE, and I didn't mean to suggest your workaround is hacky. Just that my own workaround for your workaround would be hackey... two timers.

Do you think you could raise an event on "enableBlurForIE", or something, at that time that I could add a listener for?

Thanks

**Comment by stefanneculai** [comment]
@SeanKendle it is highly unlikely to add separate events for specific browsers.
