### ISSUE TITLE
Set Iframe height to parent container

### ISSUE THREAD

**Issue by javeriaanwer** [froala/wysiwyg-editor#2637]
Hi,

I want to set iframe height as parent container height. currently iframe height is higher than parent container and showing data outside froala editor box. 

like this:

![image](https://user-images.githubusercontent.com/25203829/37273011-3a5ae0ee-25fa-11e8-97f0-5a00e571bc56.png)

I want it to be 340px, as set in fr-wrapper.
 
![image](https://user-images.githubusercontent.com/25203829/37273081-768b7cfe-25fa-11e8-996b-8d133955ad10.png)

Regards,

**Comment by stefanneculai** [comment]
@javeriaanwer could you please make a jsFiddle? Here is a basic example to start from: https://jsfiddle.net/froala/wc5c3jhk/.

**Comment by javeriaanwer** [comment]
here is the jsFiddle; http://jsfiddle.net/javeria_anwer/ubdmyoep/132/

![image](https://user-images.githubusercontent.com/25203829/37383356-1bd89adc-276a-11e8-824b-d21201ba944b.png)

**Comment by glenpierce** [comment]
This is an issue with iframes themselves. I set a max height to my parent containers and usually put them inside of flexboxes so they'll resize nicely.
