### ISSUE TITLE
Parsing response failed. .NET

### ISSUE THREAD

**Issue by mapretel** [froala/wysiwyg-editor#2639]
Hello,

I'm having a problem when doing the response parser, in question FROALA gives me the error: "Parsing response failed.", although the object obtained is the following "{"link":"Upload/1695423b.png"} "

The image is correctly uploaded to the server, the path to which the test is referenced in the browser and the image looks correct, but still gives the error What is happening?

I have the latest version of Froala deployed and the browser used is IE11 version 11.0.9600.18893 and ChromeVersion 64.0.3282.186.

Attached screenshots and Word file with the source of both the upload and the file containing FROALA

Best regards !!

[CODE.docx](https://github.com/froala/wysiwyg-editor/files/1802409/CODE.docx)

![browser](https://user-images.githubusercontent.com/27733084/37279922-2d053496-25e4-11e8-8950-a66363f5af48.JPG)

![image](https://user-images.githubusercontent.com/27733084/37281048-96d0eaca-25e7-11e8-955a-a539de90e7ae.JPG)

##### OS.
Windows 7  + IIS7

##### Browser.
IE11 version 11.0.9600.18893 and ChromeVersion 64.0.3282.186.

**Comment by stefanneculai** [comment]
The response is a relative path, while you're accessing it as absolute. Could you please try returning an absolute path instead? `{"link":"/Upload/1695423b.png"}`
