### ISSUE TITLE
Critical video editing bug: cannot edit the rest of the document after inserting video with Froala editor v2.7.5 or v2.7.6

### ISSUE THREAD

**Issue by gkilwein** [froala/wysiwyg-editor#2640]
##### Expected behavior.

After inserting a video into the editor (I am using this video URL: https://www.youtube.com/watch?v=6yheQCOPxQM&feature=youtu.be ) I should be able to edit the rest of the content in the editor. The toolbar should continue to work and I should be able to click anywhere else and continue to edit the rest of the document. 

##### Actual behavior.

After inserting a video into the editor (I am using this video URL: https://www.youtube.com/watch?v=6yheQCOPxQM&feature=youtu.be ) I am unable to edit the rest of the content. The toolbar becomes grayed out and the video remains selected no matter where I click. I cannot press escape.  

Reverting to v2.6.4 (the only older version I was lucky to have around) fixes the problem and the rest of the document is fully editable after inserting a video

##### Steps to reproduce the problem.

This is how I am initializing the editor. I left out my license key here but am including that in the real version. This problem exhibits in 2.7.5 and 2.7.6 but not in 2.6.4.

       $('#body').froalaEditor({
        fontFamily: {
            'Lato,sans-serif': 'Lato',
            'Raleway,sans-serif': 'Raleway'
        },
        imageManagerDeleteURL: '/app/image-gallery/delete',
        imageManagerLoadURL: '/app/image-gallery/list',
        imageUploadURL: '/app/image-gallery/upload',

        fileUploadURL: '/app/file-manager/upload',

        heightMin: 300,
             heightMax: 400,

        enter: $.FroalaEditor.ENTER_DIV,
        paragraphFormat: {
            N: 'Normal',
            BLOCKQUOTE: 'Block quote',
            H1: 'Heading 1',
            H2: 'Heading 2',
            H3: 'Heading 3',
            H4: 'Heading 4'
        },

                     
        toolbarButtons: ['bold', 'italic', 'underline', 'align', 'color', '|',
                         'fontSize', 'paragraphFormat', '|',
                         'insertLink', 'insertImage', 'insertVideo', 'insertFile', 'filesListButton',  'insertTable', '|',
                         'formatOL', 'formatUL', 'outdent', 'indent', 'quote', 'embedly', 'html'
                        ],

        toolbarButtonsMD: ['bold', 'italic', 'underline', 'align', 'color', '|',
                         'fontSize', 'paragraphFormat', '|',
                         'insertLink', 'insertImage', 'insertVideo', 'insertFile', 'filesListButton',  'insertTable', '|',
                         'formatOL', 'formatUL', 'outdent', 'indent', 'embedly', 'html' /*, 'quote',*/
                        ],

        toolbarButtonsSM: ['bold', 'italic', 'underline', 'align', 'color', '|',
                         'fontSize', 'paragraphFormat', '|',
                         'insertLink', 'insertImage', 'insertVideo', 'insertFile', 'filesListButton',  'insertTable', '|',
                         'formatOL', 'formatUL', 'outdent', 'indent', 'quote', 'embedly', 'html'
                        ],

        toolbarButtonsXS: ['bold', 'italic', 'underline', 'align', 'color', '|',
                         'fontSize', 'paragraphFormat', '|',
                         'insertLink', 'insertImage', 'insertVideo', 'insertFile', 'filesListButton',  'insertTable', '|',
                         'formatOL', 'formatUL', 'outdent', 'indent', 'quote', 'embedly', 'html'
                        ],
        videoInsertButtons:['videoBack','|','videoByURL','videoEmbed'], //,'videoUpload']
        htmlRemoveTags: ['base'],key: '(removed)'

    });

##### OS.
(OS name and version here)
Mac OS X High Sierra
##### Browser.
(Browser name an version here)
Happens in multiple browsers:
Google Chrome Version 64.0.3282.186 (Official Build) (64-bit)
Firefox 58.0.2 (64-bit)
Safari Version 11.0.3 (13604.5.6)

**Comment by stefanneculai** [comment]
@gkilwein are you able to reproduce it on our website?

**Comment by gkilwein** [comment]
It works fine on https://www.froala.com/wysiwyg-editor.  Can you explain to me how the code above is initializing it incorrectly?

**Comment by stefanneculai** [comment]
Please make sure that you're including the `froala_style` CSS file, not only the `froala_editor` one.

**Comment by gkilwein** [comment]
Thank you - build script was including froala_editor a second time instead of froala_style for the 2nd. Sorry about the false alarm.
