### ISSUE TITLE
Image popup menu positioned incorrectly when reinitializing editors and using scrollableContainer

### ISSUE THREAD

**Issue by FWennerdahl** [froala/wysiwyg-editor#2642]
##### Expected behavior.
The image popup menu should always be positioned in proximity to the selected image.

##### Actual behavior.
When using a scrollable container and reinitializing editors on blur, the image popup menu is positioned incorrectly when selecting images. Instead of being positioned near the image, it ends up a long way below the content, seemingly outside the scrollable container.

![image-menu-position-bug](https://user-images.githubusercontent.com/3178426/37314747-17a6393e-2656-11e8-95c3-9528dbb32dcf.gif)

##### Steps to reproduce the problem.
1. Open the JSFiddle at https://jsfiddle.net/vd44bqmq/
2. Add content to the first editor, including images. In the example above we copied a Word document used for testing.
3. Add the same amount of content to the second editor, including images.
4. Select an image in the second editor.
5. Scroll down a lot to find the image popup menu.

##### OS.
macOS 10.12.6

##### Browser.
Chrome 65.0.3325.146

**Notes:** The JSFiddle is modeled after our own use-case, where we have a static top bar above a scrollable content area where the editors are located.

**Comment by stefanneculai** [comment]
It looks the problem comes from the shared elements. Please use a unique id for each editor instance as a workaround: https://jsfiddle.net/vd44bqmq/11/.
