### ISSUE TITLE
rich text format not work in window chrome 

### ISSUE THREAD

**Issue by Vnthf** [froala/wysiwyg-editor#2643]
##### Expected behavior.
When I paste excel data, It is appended image in window chrome new version.
Because, clipboardData.getData('text/rtf') is null. Yes. it is chrome bug. 
But editor still need to change logic. This is because if data do not have rtf, it looks as an image file. At a minimum, it should check to text/plain and text/html format

##### Actual behavior.
(Describe actual behaviour here)

##### Steps to reproduce the problem.
copy excel.
paste in editor.
Then, image is shown

##### OS.
Window

##### Browser.
Chrome 65.0.3325.146

**Comment by stefanneculai** [comment]
The editor is using the `text/rtf` only for getting some rich info, not for the HTML pasted in the editor. If the content comes as an image, most likely this is how we're getting it from MSWord. 

@Vnthf could you send us the document you're pasting from? What Windows version and Word version are you using?

**Comment by Vnthf** [comment]
@stefanneculai 
I tested all window OS version, and any document(.xls) 
In Currently chrome version, MSExcel paste and copy does not work in Froala. Froala just add image not table.
I don't understand what you mean. T.T.
This bug is chrome bug(clipboardData.getData('text/rtf') is null) but also, you have to change paste logic. You have to add code to consider not only text/rtf but also text/html or text plain. Other editor consider that.
It is serious bug. Many customers using our service request to fix this bug.

**Comment by vanayun** [comment]
I don't understand why this bug is closed.
ckeditor and summernote are works well in same chrome version 65.0.3325.146
I think it should be solved.

MSWord is same bug too.

OS.
macOS

Browser.
Chrome 65.0.3325.146
