### ISSUE TITLE
Feature Request: Responsive Video sizing

### ISSUE THREAD

**Issue by SeanKendle** [froala/wysiwyg-editor#2644]
I developed some CSS for responsive YouTube videos that you can find here:
https://jsfiddle.net/crtqar0y/9/

With a checkbox to display the video in a responsive way, you could append the class `responsive` to the fr-video span, and insert an additional child span for styling, with the iframe inside.

Thoughts?

**Comment by stefanneculai** [comment]
Thanks for the suggestion, Sean. Most likely we'll add an option instead of using a checkbox in the video popup.

**Comment by SeanKendle** [comment]
One last thing, and you may already know this, but in order to get that to work, the iframe's height and width have to be attributes rather than inline styles. Cheers!

**Comment by stefanneculai** [comment]
This is more like a `feature-request`, therefore I marked it accordingly and will close it for now.

**Comment by stefanneculai** [comment]
We've just put together a public roadmap with the most popular features. 😍 There you can vote your favorite one, provide feedback or make new suggestions: https://wysiwyg-editor-roadmap.froala.com/public.
