### ISSUE TITLE
Does pasting image data from the clipboard work in Windows 8.1?

### ISSUE THREAD

**Issue by chrisdeeming** [froala/wysiwyg-editor#2645]
##### Expected behavior.
Pasting from the clipboard should upload the image.

##### Actual behavior.
The pasted image is inserted with a data URI.

##### Steps to reproduce the problem.
Pretty much just try to paste an image from the clipboard and look inside "Code View".  Obviously you should notice whether it uploads or not because of the "Uploading" overlay and progress bar, but code view will confirm it's inserted as a data URI.

##### OS.
Windows 8.1

##### Browser.
Firefox Quantum 59

Note: I haven't actually been able to test this myself, yet, as I only have Windows 10 available right now. Though if you need me to I'll have another go.

**Comment by stefanneculai** [comment]
@chrisdeeming could you please let us know where is it copied from?

**Comment by stefanneculai** [comment]
We've just checked it with Windows 8.1 and Firefox Quantum on version 2.7.6 and appears to work fine -  I am attaching a screen recording for reference.  Would be happy to look into it if you are able to reproduce it with the latest version 2.7.6.

[Win 8.1 - FF Quantum.mov.zip](https://github.com/froala/wysiwyg-editor/files/1889643/Win.8.1.-.FF.Quantum.mov.zip)
