### ISSUE TITLE
Initializing a froala editor on a div that has embedly content doesn't render the embedly card

### ISSUE THREAD

**Issue by ncmancuso** [froala/wysiwyg-editor#2654]
We use Froala to publish content onto a page, allowing our users to edit the content after they publish it. We recently adopted your embedly plugin and ran into issues around the EDIT use case.

##### Steps to reproduce the problem.
- Create a container (div) that contains an embedly card.
- Initialize Froala on that div.

##### Expected behavior.
- Froala should wrap the contents of that div into the editor and the embedly card should appear as it did before the initialization.

##### Actual behavior.
- The editor appears blank and the embedly card doesn't render.

I've created a codepen scenario to help demonstrate this issue. In the example below:
- A div is pre populated with the exact html we get when executing "froalaEditor('html.get')" on a froala editor that contains an embedly card (This is what we store when our users publish content, thus it is what is in the div before they click the edit button). 
- There is a 3sec delay before the Froala editor is initialized on that div, this is mimicking our edit use case pretending a user clicked an "edit" button.
- As you can see, the editor initializes but we lose the embedly card.

https://codepen.io/nickmancuso/pen/OvXNZV?editors=1111

Note: We had to work around this by explicitly calling "html.set" with the original content after initializing the editor and then the card renders properly.

##### OS.
OS X El Capitan version 10.11.6

##### Browser.
Chrome Version 64.0.3282.186 (Official Build) (64-bit)

**Comment by ncmancuso** [comment]
I haven't tested this much but I think this also includes invoking froalaEditor('destroy') on an editor that contains an embed.ly card.

**Comment by stefanneculai** [comment]
@ncmancuso it looks the problem comes from including the Embedly JS file. In the latest version 2.7.6, it is no longer necessary to include it: 
```html
<script src="https://cdn.embedly.com/widgets/platform.js" charset="UTF-8"></script>
```

**Comment by ncmancuso** [comment]
@stefanneculai the problem with removing the embedly JS file is that unless we initialize Froala somewhere on the page, the cards won't render. Is there a method we can call to trigger cards to render? 

In our case, we post the content to a separate page from where Froala is initialized. The source for Froala is still included on both pages, but rendering the embedly cards doesn't happen unless we call .froalaEditor()?

**Comment by axd** [comment]
@ncmancuso Including the "platform.js" in "frontend" view is working for me in latest version. No need to initialize .froalaEditor().

**Comment by Kikerrobles** [comment]
Hi @ncmancuso, Adding this script works for me:

```
<script>
    (function(w, d){
        var id='embedly-platform', n = 'script';
        if (!d.getElementById(id)){
            w.embedly = w.embedly || function() {(w.embedly.q = w.embedly.q || []).push(arguments);};
            var e = d.createElement(n); e.id = id; e.async=1;
            e.src = ('https:' === document.location.protocol ? 'https' : 'http') + '://cdn.embedly.com/widgets/platform.js';
            var s = d.getElementsByTagName(n)[0];
            s.parentNode.insertBefore(e, s);
        }
    })(window, document);
</script>
```

**Comment by zainlateef** [comment]
This still does not work me. If I include platform.js but not embedly.js, the embedly icon doesn't show up on the toolbar. If I include both, I get the same rendering issue described above. Any thoughts?

**Comment by zainlateef** [comment]
Also in [this thread](https://github.com/froala/wysiwyg-editor/issues/3040) you mention that we need the js file in order for embedly to work correctly. To be clear, I'm having the same issue mentioned above in regards to initializing embedly content. Now I'm a little confused as to the setup instructions for embedly

**Comment by wmacdonald919** [comment]
This still seems to be an issue. I haven't been able to reproduce in Fiddle. After an html.get and set, sometimes the the cards are not fully rendered, sometimes they are. After they have been published, the user moves away from the edit page and expects the card to be rendered. Again, sometimes they are, sometimes it is just an empty space like embedly did not queue the events properly and the initialization never happened.
