### ISSUE TITLE
Firefox caches editor content after page reload (using textarea init)

### ISSUE THREAD

**Issue by chrisdeeming** [froala/wysiwyg-editor#2655]
##### Expected behavior.
Reloading the page should clear the editor contents.

##### Actual behavior.
Reloading the page keeps the previous editor contents. A hard reload will clear it.

##### Steps to reproduce the problem.
1. Open the [Froala textarea demo](https://www.froala.com/wysiwyg-editor/examples/textarea)
2. Type some junk in the editor
3. Reload the page
4. Contents are still there
5. Hard reload the page
6. Contents are gone (well, default contents come back)

##### OS.
Tested with macOS

##### Browser.
Firefox only.

Side note: I have often found Firefox has some very undesirable behaviour in terms of caching the value of certain input types on back/reload. This could be a Firefox quirk/feature, but it's worth noting I can't reproduce the same in a standard, basic, textarea element. Interesting it only applies to textarea initialisation though.

**Comment by stefanneculai** [comment]
I've just checked and this is happening on a simple textarea as well. It is indeed an FF problem for a long time: https://bugzilla.mozilla.org/show_bug.cgi?id=46845. Unfortunately, there isn't too much we could do on our side for it as on page reload we're displaying the HTML we get from the underlying textarea.

**Comment by ionutvasiliu** [comment]
We're experiencing the same issue for Froala v3 on Firefox 70.0.1.

Even if the textarea has the initial content, after reloading the page, Froala displays the text we entered. Please take a look at the screenshot below

![image](https://user-images.githubusercontent.com/4112662/69848386-a9151100-1282-11ea-9c07-195b95e0bf9f.png)

**Comment by tobias-kuendig** [comment]
This problem still exists to this day with current Firefox versions. We are experiencing the exact same problem as described by @ionutvasiliu.

The textarea is populated correctly, but the editor still shows data from the previous page load.
