### ISSUE TITLE
Selection doesn't work in table cells

### ISSUE THREAD

**Issue by FWennerdahl** [froala/wysiwyg-editor#2657]
##### Expected behavior.
It should be possible to select content and copy it in table cells by using Shift + arrow keys and using copy shortkeys (Cmd + C on macOS).

##### Actual behavior.
Selecting text using Shift + arrow keys only select one character before moving to the next cell.
Attempting to copy selected content by pressing Cmd + C deselects the content.

##### Steps to reproduce the problem.
1. Go to https://www.froala.com/wysiwyg-editor
2. Add a table with some columns and rows to the editor.
3. Type some text in a cell.
4. Hold Shift and use the arrow keys to select text.
5. Double click a word to select it.
6. Press Cmd + C to try to copy the content

##### OS.
macOS 10.12.6
Windows 10

##### Browser.
Tested in the following browsers:
- Chrome 65.0.3325.146
- Internet Explorer 11.0.9600.18920
  - Marking text by double clicking and copying using Ctrl + C works in IE.
- Edge v41.16299
- Firefox v57.0.4
- Safari 11.0.1 (13604.3.5)
  - As described above. In addition, selecting content causes rows below to flash and re-render.

**Comment by fedesc** [comment]
I'm also Experiencing wierd behaviour when trying to select text from a table cell and type another char instead it throws it to the start of line in the table cell.. 
Could reproduce it also on froala demo on site

**Comment by fedesc** [comment]
Thank you. Fix works great
