### ISSUE TITLE
Images in table cells does not scale on column resize

### ISSUE THREAD

**Issue by FWennerdahl** [froala/wysiwyg-editor#2659]
##### Expected behavior.
Images should scale down when making columns more narrow.

##### Actual behavior.
Images do not scale, instead other columns are resized.

##### Steps to reproduce the problem.
1. Go to https://www.froala.com/wysiwyg-editor
2. Add a table to the editor with a couple of columns.
3. Select a cell in the middle and upload an image in it.
4. Drag the column separators to resize the column with the image and make it smaller.

##### OS.
Windows 10

##### Browser.
Internet Explorer 11.309.16299.0

**Comment by dianaprajescu** [comment]
The fix for issue #2765 reverts the change that addresses this issue. 

Unfortunately the fix we initially found for this causes real problems in other places. Since this issue is more the way IE renders the code than an actual issue it will remain a wontfix.
