### ISSUE TITLE
Custom dropdown stops working with latest version of Froala (2.7.6) [urgent]

### ISSUE THREAD

**Issue by banana-in-a-box** [froala/wysiwyg-editor#2664]
##### Expected behavior.
Custom dropdown callback should fire as per "callback" passed to `RegisterCommand`

##### Actual behavior.
Callback does not fire

##### Steps to reproduce the problem.
Follow custom dropdown instructions as per [docs](https://www.froala.com/wysiwyg-editor/examples/custom-dropdown). 
Or visit [supplied jsFiddle](https://jsfiddle.net/froala/3t238543/)

##### OS.
Windows 10 Pro

##### Browser.
Chrome, FF

**Comment by stefanneculai** [comment]
We've just tried that in Browser Stack and there doesn't seem to be any problem. 

<img width="1534" alt="screen shot 2018-03-19 at 12 25 51" src="https://user-images.githubusercontent.com/637004/37590376-be980cd0-2b70-11e8-818a-e603d00b2cef.png">
