### ISSUE TITLE
Korean word composition broken in some cell 

### ISSUE THREAD

**Issue by Vnthf** [froala/wysiwyg-editor#2666]
##### Expected behavior.
not broken composition

##### Actual behavior.
broken composition some cell 

##### Steps to reproduce the problem.
![image](https://user-images.githubusercontent.com/6292309/37637352-9537f14a-2c4a-11e8-8d23-00a567955bed.png)

##### OS.
mac. window

##### Browser.
chrome.

**Comment by stefanneculai** [comment]
Duplicate of #2648.
