### ISSUE TITLE
msOffice copy and paste has critical problem.

### ISSUE THREAD

**Issue by vanayun** [froala/wysiwyg-editor#2667]
##### Expected behavior.

Copy and paste from msOffice should work normally. There is a bug that can be converted and uploaded when copying and pasting to the editor.

##### OS.
MacOS, Window

##### Browser.
Chrome 65.0.3325.146

![2018-03-20 10 48 20](https://user-images.githubusercontent.com/22494109/37647870-b84dbf36-2c70-11e8-8d20-d77a495de744.png)

What you should be aware of is that I am using a business license and have the right to receive technical support.

You should have to solve.

**Comment by stefanneculai** [comment]
@vanayun could you please provide a document you're pasting from? Thank you.

**Comment by vanayun** [comment]
[testExcel.xlsx](https://github.com/froala/wysiwyg-editor/files/1828914/testExcel.xlsx)

This is a sample file provided by MSExcel.

**Comment by stefanneculai** [comment]
Could you please make a recording as well? We're not able to reproduce this on Chrome on MacOS. 
Also, what Excel version are you using?

**Comment by vanayun** [comment]
[froala-excel-test.zip](https://github.com/froala/wysiwyg-editor/files/1829086/froala-excel-test.zip)

macOS High Sierra
version 10.13.3

**Comment by stefanneculai** [comment]
That is very strange as we cannot reproduce it with the exact same versions. Are you copying using CMD + C / CMD + V?

**Comment by vanayun** [comment]
Sure. I did use CMD + C / CMD + V and copy & paste by mouse click.
Not only me but other users have the same bug. 

OS 
window, macOS 

browser
Chrome 65.0.3325.146 

froala version is 2.7.6
If you have not problem Could you please make a recording as well?

**Comment by vanayun** [comment]
I found the difference.
The MacOS I am using has recognized that the language setting is in Korean, but I changed the language setting in English to show it to you and it works normally.

Previously, it worked normally even though the language setting was in Korean.

It should work fine regardless of OS' language setting. I hope you solve this problem. As soon as possible.

**Comment by largeden** [comment]
@stefanneculai 
This case occurs in the msoffice environment of Windows 10.
msOffice is MS Office 365 Business.

The cause of the problem is shown in the following code.
Chrome browser does not have `e.clipboardData.getData('text/rtf')` value when pasting.
Then it loads the value of `e.clipboardData.items[3].getAsFile()`
```javascript
// image.js
    function _clipboardPaste (e) {
      if (e && e.clipboardData && e.clipboardData.items) {

        var file = null;

        if (!e.clipboardData.getData('text/rtf')) {
          for (var i = 0; i < e.clipboardData.items.length; i++) {
            file = e.clipboardData.items[i].getAsFile();

            if (file) {
              break;
            }
          }
        }
```
###### chrome
![chrome](https://user-images.githubusercontent.com/5575931/37750460-846f39cc-2dd0-11e8-9583-7ef63a98f331.png)
###### firefox
![firefox](https://user-images.githubusercontent.com/5575931/37750462-8672c4d2-2dd0-11e8-8fcd-b41ed28f316b.png)

I have not tested it in a MacOS.

**Comment by Vnthf** [comment]
https://github.com/froala/wysiwyg-editor/issues/2643
I had already mentioned the same bug. However, the work was closed without proper action.

**Comment by largeden** [comment]
As a result of my testing, replacing `text/rtf` with`text/html` solves the problem.
(Word format with image file worked well.)

**Comment by vanayun** [comment]
@largeden If this is the solution, why not apply it to the library?

**Comment by stefanneculai** [comment]
@Vnthf @largeden @vanayun it would be great if you could check with the latest Github master.
