### ISSUE TITLE
Word documents with Images are unable to copy

### ISSUE THREAD

**Issue by vartikatomaradl** [froala/wysiwyg-editor#2669]
##### Expected behavior.
(Complete document(With all images and hyperlinked images) should copy exact the same)

##### Actual behavior.
(Images and hyperlinked images are unable to copy from Word document to Froala editor)
![froala issue](https://user-images.githubusercontent.com/21773148/37696105-2adb066a-2cfa-11e8-84d5-affcc7502799.png)

##### Steps to reproduce the problem.
(Copy all the content of attached document and paste into froala editor. Images and hyperlinked images will not be copied.)
[Adam Signature.docx](https://github.com/froala/wysiwyg-editor/files/1832169/Adam.Signature.docx)

##### OS.
(Windows 10)

##### Browser.
(Chrome Version 64.0.3282.186 (Official Build) (64-bit))

**Comment by stefanneculai** [comment]
Thanks for the details, @vartikatomaradl. It looks like the image is inserted in the Word document by an URL and that's why it doesn't appear in the editor. We'll fix it shortly.

**Comment by vartikatomaradl** [comment]
Have you fixed this?

**Comment by vartikatomaradl** [comment]
We are getting many other issues after fixing this issue. Can you please let us know about the new stable version since we can't pick updated js and css from github.
