### ISSUE TITLE
Paste text with spaces and tabs in text editor(Notes app).

### ISSUE THREAD

**Issue by largeden** [froala/wysiwyg-editor#2671]
##### Expected behavior.
It should be pasted, including tabs and spaces.

##### Actual behavior.
chrome and safari do not include tabs and spaces.
(no problem in firefox)

##### Steps to reproduce the problem.
- Run Notes.app
- Decorate your text with tabs and spaces.
![image](https://user-images.githubusercontent.com/5575931/37700971-b24a74a6-2d30-11e8-8834-40da81346f7f.png)
- Copy and paste it into the fr editor.
  - firefox
![firefox](https://user-images.githubusercontent.com/5575931/37700998-c80087e0-2d30-11e8-8c15-f236a122d5b3.png)
  - chrome
![chrome](https://user-images.githubusercontent.com/5575931/37701011-d1845bfc-2d30-11e8-89c0-052717ca94bd.png)
  - safari
![safari](https://user-images.githubusercontent.com/5575931/37701020-d9b65a78-2d30-11e8-98a4-f82605ee4ccf.png)

##### OS.
mac high sierra, windows 10

##### Browser.
chrome, safari

As a result of debugging, only firefox was replacing tabs and spaces with `&nbsp;`
ckeditor, tinymce, summernote also show different results in all environments.
(The summernote was the most compatible.)

I was able to improve the symptoms through the code below.
But I do not think this is a fundamental problem solving. Applications such as msoffice have the potential to cause other problems.

```javascript
$('.selector').on('froalaEditor.paste.beforeCleanup', function (e, editor, clipboard_html) {
	if(editor.browser.chrome || editor.browser.safari) {
		return clipboard_html = String(clipboard_html)
		.replace(/\s/g, '&nbsp;')
		.replace(/\t/g, '&nbsp;&nbsp;&nbsp;&nbsp;');
	}
})
```

**Comment by largeden** [comment]
I added it to this code and it seems to be fixed.
Please check this code.

```javascript
froala_editor.js
function _handlePaste (e) {
//...
  else if (/text\/plain/.test(types) && !editor.browser.mozilla) {
    clipboard_html = editor.html.escapeEntities(e.clipboardData.getData('text/plain'))
    .replace(/\n/g, '<br>')
    .replace(/\t/g, '&nbsp;&nbsp;&nbsp;&nbsp;')
    .replace(/\s/g, '&nbsp;');
  }
//...
}
```

**Comment by stefanneculai** [comment]
Thanks, @largeden, your input is appreciated as always! We've decided on using a different more generic approach. Could you please check with the Github master and let us know your feedback?

**Comment by largeden** [comment]
@stefanneculai 
Thank you all the time.
Everything is satisfactory. :)
