### ISSUE TITLE
$.FroalaEditor.ICON_DEFAULT_TEMPLATE does nothing since 2.7.6

### ISSUE THREAD

**Issue by philippeBchn** [froala/wysiwyg-editor#2672]
##### Expected behavior.
When I use `$.FroalaEditor.ICON_DEFAULT_TEMPLATE = 'material_design'` I expect to see icons with my `material_design` template.

##### Actual behavior.
The value of `$.FroalaEditor.DEFAULT.IconsTemplate` is not updated, it still `font_awesome

##### Steps to reproduce the problem.
(Describe the steps to reproduce the problem here. A [jsFiddle](https://jsfiddle.net/froala/wc5c3jhk/) is awesome when possible.)
All was OK with v2.7.5 but KO with 2.7.6

I define my template : 
`$.FroalaEditor.DefineIconTemplate('material_design', '<i class="mdi mdi-[NAME]"></i>');`
And I set my icon template
`$.FroalaEditor.ICON_DEFAULT_TEMPLATE = 'material_design';`

But if I inspect the toolbar, I see: `<i class="fa fa-fullscreen" aria-hidden="true"></i>` instead of `<i class="mdi mdi-fullscreen" aria-hidden="true"></i>`

##### OS.
Mac OS Sierra 10.12.3

##### Browser.
Chrome, Version 65.0.3325.162

**Comment by mthomasson** [comment]
In the DEFAULT setup variable, you can add `iconsTemplate: 'material_design'` to have it working again.
