### ISSUE TITLE
TypeError: e[d].getAttribute is not a function

### ISSUE THREAD

**Issue by mjniday** [froala/wysiwyg-editor#2676]
##### Actual behavior.
Intermittent crashes in our app occur due to a TypeError happening in froala_editor. 

##### Steps to reproduce the problem.
Unfortunately this has been really difficult to reproduce, but it's occurring for somewhat regularly for us right now. It seems that prolonged use of the editor is more likely to cause this. The editor initializes without issue, but periodically this error message is thrown when making changes to the editor. 

##### OS.
Mac OS 10.13.3

##### Browser.
Chrome 64.0.3282

![image](https://user-images.githubusercontent.com/7980741/37794102-e0a751fa-2de6-11e8-9255-a841d920d285.png)

**Comment by Xtinct** [comment]
Having same issue there. It happens, when one of my `<p>` tags contain both text and another tag, for instance: `<p> some text here <strong> some bold text </strong> </p>` and i'm trying to get html with selection markers.

**Comment by stefanneculai** [comment]
@mjniday @Xtinct do you think you could replicate it in a jsFiddle: https://jsfiddle.net/froala/wc5c3jhk/?
