### ISSUE TITLE
Text selection inside a table (copy, ...) using the keyboard

### ISSUE THREAD

**Issue by mthomasson** [froala/wysiwyg-editor#2678]
##### Expected behavior.
Selecting text using keyboard inside a table would select the text. Copying a selection would copy the selection to the clipboard.

##### Actual behavior.
When selecting text inside the cell of a table using the keyboard (shift + arrow), the second key pressed unselects the text and the cursor jumps. When tables are nested it gets worst, the cursor jumps in another cell (usually one of the parent table). Any combination of keys generates the same issue: copy, paste, etc....

##### Steps to reproduce the problem.
See https://jsfiddle.net/calmarRobot/n3gcrcho/
Create a table, add some text in a cell, try to select and copy using the keyboard

##### OS.
MacOs, Linux (Ubuntu 16.04LTS)

##### Browser.
Last Chrome, last Firefox

**Comment by stefanneculai** [comment]
It's fixed on the current master.

**Comment by mthomasson** [comment]
@stefanneculai 
I am currently on the 2.7.6 version, it feels a little less jumpy, but I still can't manage to select all the text of a cell using the keyboard.
Moreover, I guess [this page](https://www.froala.com/wysiwyg-editor/examples/table-styles) is also pointing towards the last version?
