### ISSUE TITLE
allowfullscreen transforms to allowfullscreen=""

### ISSUE THREAD

**Issue by simoroshka** [froala/wysiwyg-editor#2680]
##### Expected behavior.
allowfullscreen should be interpreted as true and either be left as is or transformed to the full form allowfullscreen="true" 

##### Actual behavior.
allowfullscreen transforms to allowfullscreen="", and the fullscreen on video does not work.

##### Steps to reproduce the problem.
insert a video from youtube, switch to code editing.

**Comment by stefanneculai** [comment]
@simoroshka we're not doing any changes on that and leave the browser to handle this case. This is how the browsers transform the property when nothing is specified as value.
