### ISSUE TITLE
Spell check not running after new line inserted

### ISSUE THREAD

**Issue by twolfe2** [froala/wysiwyg-editor#2683]
##### Expected behavior.
After I type in a misspelled word and press enter, I would like to be shown that the word is misspelled by indication of a red dotted underline 

##### Actual behavior.
If I type in a misspelled word and press enter (note: do not press space and then enter), it appears the spell check does not run.

##### Steps to reproduce the problem.
1. Goto the [Froala editor here](https://www.froala.com/wysiwyg-editor)
2. Type in a word that is misspelled ('limitss' in my example)
3. Press enter
![froalaspellissue](https://user-images.githubusercontent.com/13949747/37941200-dc5c5fb2-3121-11e8-8306-c7c6d0024521.gif)

Note: It appears the spell check runs if I go back to the line with the misspelled words but that sort of defeats the purpose of having a spell check 😉 

##### OS.
macOS Sierra

##### Browser.
Google Chrome Version 65.0.3325.162

**Comment by stefanneculai** [comment]
Unfortunately we're facing a browser problem here and for now, this is a `wontfix` as when going to a new line we have to split the current one in half and this makes the browser autocomplete to break. There are some workarounds by unfocusing the editable area and focusing it again, however, we're not happy with any of them.
