### ISSUE TITLE
Feature Request: File Manager like Image Manager

### ISSUE THREAD

**Issue by StefanNeuser** [froala/wysiwyg-editor#2684]
##### Expected behavior.
A popup to browse uploaded files like the image manager module does would be AWESOME!

##### Actual behavior.
Just a upload without a File-Browsing

##### Steps to reproduce the problem.
Upload a file and try to browse for uploaded files.

I can develop it based on the image manger module. But unfortunetly you only publish the minified version of your modules. Can you server a not minified version of the module?

**Comment by stefanneculai** [comment]
Thanks for the feature request, @StefanNeuser. We do not keep feature requests opened here, therefore I am closing it. The unminified JS is available under the Professional / Business license inside your account.

**Comment by dgroh** [comment]
No feedback about this?

**Comment by treetop1500** [comment]
+1 for a file manager similar to the image manager.

**Comment by stefanneculai** [comment]
We've just put together a public roadmap with the most popular features. 😍 There you can vote your favorite one, provide feedback or make new suggestions: https://wysiwyg-editor-roadmap.froala.com/public.
