### ISSUE TITLE
Disallow to use H1-H3, P, UL, OL inside BLOCKQUOTE

### ISSUE THREAD

**Issue by glebmachine** [froala/wysiwyg-editor#2685]
##### Expected behavior.
Unable to put H1-H3, P, UL, OL into BLOCKQUOTE tag

##### Actual behavior.
I'm able to put H1-H3, P, UL, OL into BLOCKQUOTE tag

##### Steps to reproduce the problem.
1. Create Blockqute
2. Select text
3. Transform it as to any other tag.

**Comment by stefanneculai** [comment]
It is unlikely to implement this behavior by default in the editor. Is there any reason why you think this behavior is better than the existing one?

**Comment by glebmachine** [comment]
For example: we work on "Add comment" form, which riched with ul, ol, h1-h3 and blockqoute.
And we would like to disallow users to fold one semantic elements into another (like tables into blockqoutes or blockquotes into unordered list items)

I think it's common goal
