### ISSUE TITLE
"Clear Formatting" should preserve selection

### ISSUE THREAD

**Issue by kantuni** [froala/wysiwyg-editor#2686]
##### Expected behavior.
`Clear Formatting` should preserve selection.

##### Actual behavior.
When `Clear Formatting` is clicked, only part of the selection remains selected.

##### Steps to reproduce the problem.
- Type `hello world`
- Make `hello` bold
- Make `world` italic
- Select the whole line
- Click on `Clear Formatting`
- Only `hello` is now selected

##### OS.
macOS
10.13.3

##### Browser.
Firefox Quantum
59.0.2

**Comment by stefanneculai** [comment]
@kantuni thanks for reporting it. Should be fixed on the current Github master. Could you please check it?

**Comment by kantuni** [comment]
@stefanneculai it works. Thank you for a quick fix!
