### ISSUE TITLE
Add option to overflow toolbar buttons instead of wrapping

### ISSUE THREAD

**Issue by StickNitro** [froala/wysiwyg-editor#2687]
##### Expected behavior.
I am using the editor inside a table (using bootstrap grid system) and when a column is small the toolbar is wrapping quite significantly.

Adding an option, something like `toolbarOverflow: true|false` (default to false) and if set to true would add an overflow menu and all buttons that do not fit will be added to this menu

##### Actual behavior.
The actual behaviour at the moment is that all toolbar buttons wrap and when the editor is displayed in a narrow column this can be quite significant

**Comment by stefanneculai** [comment]
Thanks for the feature-request, @StickNitro .

**Comment by pdr** [comment]
+1. This would be really great.

**Comment by StickNitro** [comment]
Any update on this please?

**Comment by b3tsych3n** [comment]
+1

**Comment by figurelegend** [comment]
+1
