### ISSUE TITLE
Table alignment mismatch with toolbar alignment 

### ISSUE THREAD

**Issue by javeriaanwer** [froala/wysiwyg-editor#2688]
Hi,

I noticed that on changing alignment from table options toolbar alignment changed as well but it is not working vice versa. I want it to work in both ways.

please see this reference. 

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/25203829/38019091-218ed104-3290-11e8-96eb-66f33543eceb.gif)
 
you can also verify this on your website.

**Comment by stefanneculai** [comment]
I think that there is currently a confusion. The align button from the toolbar popup set the default alignment for the entire cell, while the one from the editor toolbar, sets the alignment for the current block tag inside the table cell. Therefore, if you have 2 lines in the toolbar cell, you could use the main toolbar button to align individually the lines.

**Comment by javeriaanwer** [comment]
can you please explain it with example.

**Comment by lostan** [comment]
Table alignment at toolbar doesn't work. I select the table and the toolbar disable ... how my clients are expected to align the whole table using Froala?

**Comment by stefanneculai** [comment]
@lostan it's on our roadmap: https://wysiwyg-editor-roadmap.froala.com/public/ideas/3546.
