### ISSUE TITLE
Crop image

### ISSUE THREAD

**Issue by danielarturo** [froala/wysiwyg-editor#269]
Should be nice that the editor could edit uploaded images for cropping and rotating in the way this editor does

http://fengyuanchen.github.io/cropper/

**Comment by iisfaq** [comment]
Any update on this Stefan?

Chris

**Comment by stefanneculai** [comment]
Yes, we're adding Aviary just in the next release and update is already on Github: https://github.com/froala/wysiwyg-editor/blob/master/html/3rd-party/aviary/index.html.
