### ISSUE TITLE
Copy pasting from word to froala editor results in removing white spaces.

### ISSUE THREAD

**Issue by bilalahmad4554** [froala/wysiwyg-editor#2690]
##### Expected behavior.
Copy pasting from word should paste the content as it is after i click the "Keep" option on the modal shown on pasting something. 

##### Actual behavior.
Instead of exact pasting as in word, editor is removing white spaces. 

##### Steps to reproduce the problem.

Open this file

Pro Forma Balance Sheet 
[file for testing.docx](https://github.com/froala/wysiwyg-editor/files/1855749/file.for.testing.docx)

paste it in froala editor. Boom! you see the spaces are eaten by the editor. 
I am using the latest froala version.

##### OS.
Windows 7

##### Browser.
Chrome

**Comment by stefanneculai** [comment]
@bilalahmad4554 do you think you could send us a video highlighting the problem? Thank you in advance.
