### ISSUE TITLE
Double/multiple spaces have non-breaking space in wrong order

### ISSUE THREAD

**Issue by seb303** [froala/wysiwyg-editor#2691]
##### Expected behavior.
Double spaces should become: "& nbsp; "
(ignore the space within & nbsp; - this is a github limitation)

##### Actual behavior.
Instead the following html is generated: " & nbsp;"
i.e. The non breaking space is after the space.  This causes gaps at the start of the line when the text wraps at this point.

##### Steps to reproduce the problem.
https://www.froala.com/wysiwyg-editor/examples/quick-insert
Type a sentence long enough to push the next sentence to the line end.  After the full stop, type 2 spaces.  When the sentence starts at the line start, it is inset by 1 space.

![image](https://user-images.githubusercontent.com/467942/38041610-1e147668-32aa-11e8-9e0c-e83a15422a85.png)

##### OS.
Windows 8.1

##### Browser.
Firefox 59

**Comment by stefanneculai** [comment]
@seb303, unfortunately, this is a browser rendering problem and there is not too much we could do about it. The current way of inserting the non-breaking spaces is the one which works in most of the cases.

**Comment by seb303** [comment]
@stefanneculai 
Thanks for your reply, but I would not call it a browser rendering problem that a non-breaking space attached to the start of a word creates an inset when the word falls at the start of a line.  This is correct behaviour according to the HTML specification.

If you simply reverse the order of the space and non-breaking space sequence then this does not occur.

I can't think of a case where it works better to represent double spaces the way round that the Froala editor does it (i.e. with a space followed by a non-breaking space).  Every other editor, WYSIWYG html software, email software, etc. that I know does it the other way.

By the way, I noticed that github collapsed the double space between sentences in my example text so perhaps it wasn't clear what I meant?  Let me know if a file upload of some example HTML would be useful.
