### ISSUE TITLE
Refresh froala toolbar

### ISSUE THREAD

**Issue by javeriaanwer** [froala/wysiwyg-editor#2692]
I want to set toolbar buttons to its original state, I only find undo.reset method on froala editor documents. how can I reset other buttons as well.

**Comment by stefanneculai** [comment]
The toolbar buttons are designed to display the state of the content. To change the toolbar buttons state, the way the content is formatted should be changed. To clear the formatting, you could use the following method: https://www.froala.com/wysiwyg-editor/docs/methods#commands.clearFormatting.
