### ISSUE TITLE
how to check hide event?

### ISSUE THREAD

**Issue by windbug** [froala/wysiwyg-editor#2694]
so sorry. my english is so poor.

i made a own popup plugin.
and i need check hide event.

1. open and hide by button, i can check callback and hide event.
but click container outside editor, popup closed. but can not check hide event.

how can i check hide event with click editor outside?

2. i must disable scroll window when popup open.
how can i do?

**Comment by stefanneculai** [comment]
@windbug for tech support please contact us via our website. Thank you.
