### ISSUE TITLE
format.toggle method doesn't work as intended 

### ISSUE THREAD

**Issue by Trapdafifou** [froala/wysiwyg-editor#2697]
##### Expected behavior.
I wouldlike this method to add the tag around my selection if the selection doesn't have it and to remove it if it has the tag.

##### Actual behavior.
Actually, it adds the tag when the selection doesn't have it but it will not remove it

##### Steps to reproduce the problem.
https://jsfiddle.net/byyo8mnd/113/
try to quote and the remove the quote on a selection

##### OS.
mac Os 10.12.6 

##### Browser.
Chrome 65.0.3325.181

**Comment by stefanneculai** [comment]
@Trapdafifou the format.toggle method is designed to work for inline tags, not for block tags such as blockquote, p, div, h1, etc.
