### ISSUE TITLE
Reinitialize froala editor with new editor config

### ISSUE THREAD

**Issue by loutocky** [froala/wysiwyg-editor#2698]
I am not able to reinitialize froala editor with new config. I am using Angular 4 froala editor (version 2.7.6) directive from the examples of froala editor. This directive I wrapped into my own component:

```
  selector: 'froala-editor',
  template: `<textarea [froalaEditor]="editorConfig" (froalaModelChange)="onChange($event)" [(froalaModel)]="HTMLData"></textarea>`,
  providers: [FROALA_EDITOR_VALUE_ACCESSOR],
  styleUrls: ['./froala-editor.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush
```
This Component has ngOnInit() method, where I am creating config with one event (froalaEditor.image.beforeUpload, converting image into base64). In the end, there is:

`Object.assign(this.editorConfig, defaultConfig);`

Now, it is working correctly, froala editor is created with my configuration. Now I want to implement autocomplete with At.js 3rd party plugin (it is already working if I have static data from the example of using At.js), but my data for autocomplete are Observable. So I need to call my backend, subscribe to it and when data arrive reinitialize editor with other new event 'froalaEditor.initialized' and set there data for autocomplete. So I need to update editorConfig and createEditor again with new other event. But froala editor is not able to respect and add initialized event. So autocomplete is not working.

**Comment by stefanneculai** [comment]
@loutocky the editor config cannot be changed after the editor was initialized. If you would like to change it, the way to do it would be by destroying the editor instance and initializing it again. 

For angular issues, please use the Angular repo instead. Thank you.

**Comment by loutocky** [comment]
Thank you, can you just provide me, how to destroy and create froala editor again from my component with the new config?

**Comment by stefanneculai** [comment]
see https://github.com/froala/angular-froala-wysiwyg#manual-initialization

**Comment by loutocky** [comment]
Thanks
