### ISSUE TITLE
Media Manager group options

### ISSUE THREAD

**Issue by sudeste** [froala/wysiwyg-editor#270]
Option to sort "group" images by categories.
examples:
cars, christmas, holidays, abstract

I think this option would return the json file.
I think this would be a nice complement.

Currently it seems that everything is mixed.

**Comment by stefanneculai** [comment]
Added in v2.0.0-rc.1

**Comment by connect-technologies** [comment]
is there a example with the media manager? I just found the image library in https://www.froala.com/wysiwyg-editor/v2.0
Is there a way to browser other files than images (pdf...)?

**Comment by stefanneculai** [comment]
Only images can be browsed for the moment. You can find an example about how to use tags on https://www.froala.com/wysiwyg-editor/v2.0/docs/concepts/image-manager.
