### ISSUE TITLE
Text selection isn't shown when color popup is open

### ISSUE THREAD

**Issue by petester42** [froala/wysiwyg-editor#2702]
##### Expected behavior.
The text in the editor will still retain its look of selected even when the color popup is open

##### Actual behavior.
The selection appear to have disappeared when the color popup is open. It is reselected when closed.

##### Steps to reproduce the problem.
- Select a range of text in the editor
- Click the color button to open up the text/background color popup
- Selection of text seems to have disappeared
- Close popup
- Selection reappears

##### OS.
macOS High Sierra

##### Browser.
Chrome 65.0.3325.181

**Comment by stefanneculai** [comment]
That is because it is not possible to have 2 inputs on the same page with selection in it. When the colors popup is showm the cursor goes to the HEX input and we remove it from the editor.

**Comment by petester42** [comment]
Thanks for the quick response!
