### ISSUE TITLE
Safari 11.1 : can't paste any styled text

### ISSUE THREAD

**Issue by YannLeBihan** [froala/wysiwyg-editor#2703]
##### Expected behavior.
Styled text should be kept after a paste operation, unless specified in options

##### Actual behavior.
Pasted text is systematically converted to plain. Adding `pastePlain : false` to the options doesn't work either. Only workaround I found was to downgrade Froala Editor from version **2.7.6**. to **2.7.2**

##### Steps to reproduce the problem.
Go to Froala Editor's home page and paste some styled text into the demo editor

##### OS.
macOS 10.13.4

##### Browser.
Safari 11.1  (13605.1.33.1.2)

**Comment by stefanneculai** [comment]
If you'd like to keep the inline style on paste, you should change the [pasteAllowedAttrs option](https://www.froala.com/wysiwyg-editor/docs/options#pasteDeniedAttrs) and remove the `style` from the array.

**Comment by YannLeBihan** [comment]
Hi @stefanneculai,

Thank you for answering quickly. Unfortunately, it doesn't work : only plain text can be pasted. furthermore, I also noticed that html tags like `<img>` are also filtered, whatever the init settings. The only solution I have been able to figure is to downgrade to 2.7.2.

You can check it by copying some content with styles and images on any web page, and pasting it into Froala's homepage test editor : everything is correctly pasted if you're using Chrome, for example, but not Safari 11.1. I have verified it on 3 different Mac computers running the latest macOS version.

**Comment by nivapo95** [comment]
I'm having the same issue and can't find any solution online.
Once I upgraded to react 18.0 the paste is no longer working for non-plain text.

Also, reaching any support from Froala is impossible even for paying customers.

**Comment by nivapo95** [comment]
Every few months I get back to this issue with no hope.
My previous answer was ditching the **onModelChanged** and getting the content manually from the ref.

But now I need the **onModelChanged** again, so my new approach is to ditch the **Model** property and manually update the content on initialization by doing this:

`events: {
                                        "initialized": function () {
                                            // Do something here.
                                            // this is the editor instance.

                                            editorRef.current = this;
                                            this.html.set(editorContent); // Set the content manually on initialize
                                        }
                                    }`

So for some reason, using the **Model** and the **onModelChanged** together causes issues when pasting.
