### ISSUE TITLE
How to use custom tags?

### ISSUE THREAD

**Issue by yhJayChen** [froala/wysiwyg-editor#2705]
### insert my custom tag:
![image](https://user-images.githubusercontent.com/17180289/38193281-de1847bc-36a3-11e8-8dda-91c24a2c2de4.png)

### close code view:
![image](https://user-images.githubusercontent.com/17180289/38193323-24746880-36a4-11e8-8a25-0706cf94d17e.png)

### press ENTER and write some text:
![image](https://user-images.githubusercontent.com/17180289/38193389-693db44e-36a4-11e8-815c-486b7ef6f9c7.png)

### open the code view:
![image](https://user-images.githubusercontent.com/17180289/38193402-80eb36e8-36a4-11e8-984e-77adcdd81223.png)

now I have two same `cus-tag` element

**Comment by stefanneculai** [comment]
All tags which have HTML inside them are treated as inline tags and they are being split on the ENTER action. If you'd like to implement a custom behavior for this case, you'd have to intercept the keydown event and change the way enter is handled in this case.
