### ISSUE TITLE
Cursor disappears after dropping image on editor in firefox

### ISSUE THREAD

**Issue by neeasade** [froala/wysiwyg-editor#2706]
##### Expected behavior.
The text cursor is visible after dropping image on froala

##### Actual behavior.
The text cursor disappears (you can still type)

##### Steps to reproduce the problem.
go to https://www.froala.com/wysiwyg-editor/examples/drop-content in firefox (I'm on 59.0.2)
drag the smiley to the editor
observe that the text cursor is no longer present

##### OS.
Windows 10

##### Browser.
Firefox 59.0.2

**Comment by stefanneculai** [comment]
We just put an update for it on the website.

**Comment by karanjariwala** [comment]
where is the update on the website?
