### ISSUE TITLE
Buttons with labels

### ISSUE THREAD

**Issue by valivvvv** [froala/wysiwyg-editor#2707]
Is there a way to add a label to a custom button? 

Thanks!

**Comment by stefanneculai** [comment]
Sure, you could make a custom icon template for that: https://www.froala.com/wysiwyg-editor/docs/concepts/custom/icon.

**Comment by valivvvv** [comment]
Thanks for the quick answer Stefan! 
I have one more question though. I'm using froala inside an Angular app. Froala's html is not inside an <iframe>, however I can't target the toolbar buttons with CSS. Any idea why?
