### ISSUE TITLE
Image Upload Fail(chrome)

### ISSUE THREAD

**Issue by largeden** [froala/wysiwyg-editor#2708]
##### Expected behavior.
![image_upload_error](https://user-images.githubusercontent.com/5575931/38241064-3c696e36-376c-11e8-82cb-dad81f4098e8.png)

##### Steps to reproduce the problem.
- Upload an image file from the Chrome.

![os_x_yosemite_2-wallpaper-1366x768](https://user-images.githubusercontent.com/5575931/38241550-7dff0cf6-376d-11e8-8f62-504601d5815b.jpg)
os_x_yosemite_2-wallpaper-1366x768.jpg

##### OS.
Windows 10 pro
froala editor:Latest commit version.

##### Browser.
Chrome
(FF, IE10 has no problem)

**Comment by stefanneculai** [comment]
Could you make a screenshot of the request in the developer tools console?

**Comment by largeden** [comment]
@stefanneculai 

![ws000012](https://user-images.githubusercontent.com/5575931/38244753-9ade99fa-3776-11e8-9b36-a9765ee5c8a2.PNG)

#### message
Failed to load https://i.froala.com/upload: Response to preflight request doesn't pass access control check: The 'Access-Control-Allow-Origin' header has a value 'null' that is not equal to the supplied origin. Origin 'null' is therefore not allowed access.

**Comment by stefanneculai** [comment]
It looks there was a bad config on i.froala.com where the images were uploaded. All should be good now.

**Comment by largeden** [comment]
@stefanneculai 
I was relieved :)
