### ISSUE TITLE
Pasting from MS Word to Froala Editor - Clear Format Not working properly

### ISSUE THREAD

**Issue by jithinrajpr** [froala/wysiwyg-editor#2709]
##### Expected behavior.
When pasting the content from **MS Word** to Froala Editor if I clicked the _Clean_ button all the style should be gone and I should get a clean text.

##### Actual behavior.
if I clicked the _Clean_ button all the other style that I know of changes except **bold** style of the font.

##### Steps to reproduce the problem.
Just paste the content from the **MS Word** with bold and colour and other styles to Froala Editor and when the popup for **Word Detected** comes just click the _Clean_ button. You will get this bug.

##### Methods I tried to resolve this Bug.
When I inspected the content I noticed that a `<strong>` tag is wrapping the text I pasted from **MS Word** so I check the doc and found the `pasteDeniedTags:` option from Froala Editor.

I tried it when I init the Plugin like the below sample:

`pasteDeniedTags: ["colgroup", "col", "meta","strong"]`

##### OS.
This can be reproduced in all OS only you have to get MS Office.

##### Browser.
Chrome Version 65.0.3325.181

**Comment by stefanneculai** [comment]
See https://www.froala.com/wysiwyg-editor/docs/options#wordDeniedTags.

**Comment by asmundwego** [comment]
Adding denied tags is not god enough. Then it will remove this formatting if the user selects "Keep" when pasting, which is not good!

**Comment by chakritgui** [comment]
fdgsgdgdfg
