### ISSUE TITLE
Cannot delete highlighted text in a table

### ISSUE THREAD

**Issue by firstladymb** [froala/wysiwyg-editor#2710]
##### Expected behavior.
When highlighting text inside a table cell, clicking delete should delete the text.

##### Actual behavior.
Text does not delete but the highlight disappears.

##### Steps to reproduce the problem.
https://jsfiddle.net/firstladymb/wc5c3jhk/242/
1. Go to the fiddle.
2. Highlight any text in the table.
3. Click delete.
This also happens in the demo on the website with a simple table.
https://www.froala.com/wysiwyg-editor

##### OS.
MacOS 10.12.6 Chrome Version 65.0.3325.181 (Official Build) (64-bit)

##### Browser.
(Browser name an version here)

**Comment by stefanneculai** [comment]
It's fixed on the current master and will be included in the next minor release.
