### ISSUE TITLE
Paste not working when text to paste is longer than charCounterMax

### ISSUE THREAD

**Issue by dloreto** [froala/wysiwyg-editor#2711]
##### Expected behavior.
If a text longer than charCounterMax is pasted, it should be truncated to charCounterMax characters.
eg:
charCounterMax = 5
I paste 123456789, my text should be truncated to 12345

##### Actual behavior.
The text is not getting paste

##### Steps to reproduce the problem.
[jsFiddle](https://jsfiddle.net/2gc31s5s/1/)

##### OS.
Tested on Windows and OSX.

##### Browser.
Tested on Chrome and Safari.

**Comment by dloreto** [comment]
This request has been closed. Does it mean that it's not going to be implemented? @stefanneculai

**Comment by stefanneculai** [comment]
@dloreto we marked it as a `feature-request` and closed it. We keep this repo only for bug tracking, not for feature requests. We might add it, however, I cannot provide an ETA.

**Comment by ConnorsFan** [comment]
I hope that this feature will be implemented. The current behavior is somewhat confusing for our users.

**Comment by RLeDEV** [comment]
Is there any update about this one? We're experiencing the same thing.

**Comment by mansuu** [comment]
I am also experiencing the same issue, is it available now?

**Comment by ashish-singh06** [comment]
I am also experiencing the same issue, is this fixed?
