### ISSUE TITLE
Extra line spaces

### ISSUE THREAD

**Issue by cff2880** [froala/wysiwyg-editor#2713]
##### Expected behavior.
When i copy & paste from Word into Froala editor ver. 2.7.6 (Microsoft 2010, Windows 7, Chrome Browser)  there is always extra line spaces that are not in the word document... and header should be centered.

##### Actual behavior.
The Froala editor will ask to clean or keep formatting, both render the same output with extra spaces on each new line.  It might not be an actual extra line space, but an increased line size.  Not sure how to fix this. Also, the alignment of the header text should be centered, and it renders left aligned.  See attached screenshot of output in Froala. 

##### Steps to reproduce the problem.
I have attached a simple document, with no tables or anything complicated.  

##### OS.
Windows 7

##### Browser.
Chrome
[Borrower Acknowledgment for Private Loans.docx](https://github.com/froala/wysiwyg-editor/files/1879853/Borrower.Acknowledgment.for.Private.Loans.docx)
[Froala_Output_boyd.pdf](https://github.com/froala/wysiwyg-editor/files/1879855/Froala_Output_boyd.pdf)

**Comment by stefanneculai** [comment]
The editor is wrapping each new line in P tags. By default, it has a margin-bottom of 10px. You could override it with the following CSS:

```css
.fr-view p {
    margin-bottom: 0px !important;
}
```
