### ISSUE TITLE
Support Angular2+ components as icon templates

### ISSUE THREAD

**Issue by fynnfeldpausch** [froala/wysiwyg-editor#2718]
##### Expected behavior.
Angular 2+ components should be supported as icon templates. Given a component `my-component`, it should be possible to specify `$.FroalaEditor.DefineIconTemplate('angular', '<my-component [bind]="data"></my-component>');`.

##### Actual behavior.
Adding a component as an icon template does not work:
- Components are not compiled
- Bindings (e.g. `[bind]="data"`) are interpreted as template parts

##### OS.
macOS 10.13.3

##### Browser.
Chrome 65.0.3325.181

**Comment by stefanneculai** [comment]
@fynnfeldpausch the icon templates are treated as HTML, they are not compiled in anyway.

**Comment by fynnfeldpausch** [comment]
I do understand that. This was not supposed to be a bug report, but a feature request. Is there any way to have this added in the future?

**Comment by stefanneculai** [comment]
Unfortunately, it's unlikely for us to add it as the editor is designed not to be framework-dependent.
