### ISSUE TITLE
IE11: Editor window jump up when hovering over Paragraph Format items

### ISSUE THREAD

**Issue by andymason** [froala/wysiwyg-editor#2719]
##### Expected behavior.
Hovering over paragraph format items has no effect on editor position.

##### Actual behavior.
Hovering over paragraph format items cause editor window to jump up to the top of editor content.

##### Steps to reproduce the problem.
1. Add content causing the editor to extend further than viewport
2. Scroll to the bottom of the content
2. Select Paragraph Format from the sticky nav and hover the cursor over an item
3. Editor window jump to the top

https://codepen.io/anon/pen/yKZjMR

##### OS.
Win 7

##### Browser.
IE 11

**Comment by stefanneculai** [comment]
@andymason could you please check if you still have this problem in version 2.8.0?

**Comment by TimSielemann** [comment]
@stefanneculai 

Yes still existing in 2.8.0. 
This error also occurs when changing the text size of a item (see video). 

[scroll top bug.zip](https://github.com/froala/wysiwyg-editor/files/1941823/scroll.top.bug.zip)

**Comment by andymason** [comment]
2.8.0 doesn't load in Win 7 IE 11. Outputs an `Object doesn't support property or method 'endsWith'` error.

https://codepen.io/anon/pen/ZoWObb

**Comment by stefanneculai** [comment]
@andymason we've put a fix and the editor should work fine with version 2.8.1. It would be great if you could confirm that the problem is still there. Thanks in advance.

**Comment by TimSielemann** [comment]
@stefanneculai unfortunatly this is still there (video attached)

[scroll top bug.zip](https://github.com/froala/wysiwyg-editor/files/1983587/scroll.top.bug.zip)

**Comment by TimSielemann** [comment]
any update on this?
