### ISSUE TITLE
IE11: Cursor moves to top of editor when selecting inline image

### ISSUE THREAD

**Issue by andymason** [froala/wysiwyg-editor#2720]
##### Expected behavior.
When inserting or clicking on an inline image the cursor's position should  remain in it's last location.

##### Actual behavior.
Clicking on or inserting an inline image the cursor jumps to the top of the editor.

##### Steps to reproduce the problem.
1. Insert and image to the bottom of the editor
2. Notice the cursor is now in the top left of the editor

https://codepen.io/anon/pen/rdPERr

##### OS.
Win7

##### Browser.
IE 11

**Comment by stefanneculai** [comment]
It's fixed on the current master.
