### ISSUE TITLE
Tab doesn't work in table mode

### ISSUE THREAD

**Issue by Karrlllis** [froala/wysiwyg-editor#2721]
##### Expected behavior.
Tab works switching from cell to cell

##### Actual behavior.
Tab pressing doesn't move to next cell

##### Steps to reproduce the problem.
Please see html sample https://www.dropbox.com/s/ifwsjxjt4occu8h/froala_table_cell_tabbing_bug_2.7.6.html?dl=0

##### OS.
OSX and Windows

##### Browser.
IE, FF, Chrome

**Comment by stefanneculai** [comment]
It's fixed on the current master.
