### ISSUE TITLE
Cant delete word in table if using list items

### ISSUE THREAD

**Issue by Karrlllis** [froala/wysiwyg-editor#2722]
##### Expected behavior.
Should be able to delete any word in any cell

##### Actual behavior.
Cant delete some words in some cells

##### Steps to reproduce the problem.
Please see sample https://www.dropbox.com/s/ifwsjxjt4occu8h/froala_table_cell_tabbing_bug_2.7.6.html?dl=0

Please see 1st and 3rd cell with lines - Select word and press Delete

##### OS.
Win, OSX

##### Browser.
IE, FF, Chrome

**Comment by stefanneculai** [comment]
It's fixed on the current master already.
