### ISSUE TITLE
Class styles excludes while sending editor data as mail.

### ISSUE THREAD

**Issue by vartikatomaradl** [froala/wysiwyg-editor#2723]
##### Expected behavior.
(styling should be same as showing in editor)

##### Actual behavior.
(classes style excludes while send as mail content)

##### Steps to reproduce the problem.
(copy document 
[Adam Signature.docx](https://github.com/froala/wysiwyg-editor/files/1897916/Adam.Signature.docx) paste in editor 
![test spaces](https://user-images.githubusercontent.com/21773148/38605440-f309b0cc-3d90-11e8-92c2-d7460f95f457.png) in editor we can see the spaces while after sending as mail content these spaces got removed 
![test spaces 1](https://user-images.githubusercontent.com/21773148/38605514-2452644e-3d91-11e8-87f9-8f3cc0cb6704.png)

)

##### OS.
(Windows 10)

##### Browser.
(Google Chrome)

**Comment by stefanneculai** [comment]
Make sure you enable the following option when using the editor for sending emails: https://www.froala.com/blog/wysiwyg-editor/styling-emails-with-wysiwyg-html-editors.
