### ISSUE TITLE
Getting issues after fixing #2669 

### ISSUE THREAD

**Issue by vartikatomaradl** [froala/wysiwyg-editor#2724]
We are getting many other issues after fixing the issue #2669. Can you please let us know about the new stable version since we can't pick updated js and css from github.

**Comment by stefanneculai** [comment]
@vartikatomaradl it would be great if you could let us know what problems you get. The Github master version is the one which is used for dev between version releases and it indeed might contain few issues.

**Comment by stefanneculai** [comment]
We cannot provide a release date at this moment. Could you send us the options you're initializing the editor with?

**Comment by stefanneculai** [comment]
@vartikatomaradl we've checked this and doesn't appear to be a problem that we could reproduce with the basic editor config. It would be great if you could put these changes on a staging app and send us a link to it via our contact form: https://www.froala.com/wysiwyg-editor/contact. Thanks in advance.
