### ISSUE TITLE
Cursor jumps back to the previous line when Return is clicked during creation of UL or OL

### ISSUE THREAD

**Issue by ajredovan** [froala/wysiwyg-editor#2725]
##### Expected behavior.
When creating an ordered list or unordered list on mobile, it should create a new bulleted/numbered line when "return" is tapped.

##### Actual behavior.
When creating a list and "return" is tapped, it jumps back to previous list and will not allow continuation of list.

##### Steps to reproduce the problem.
Open any Froala WYSIWYG on mobile, make sure the textarea is clear and try to create a list from toolbar list button (reproducible on website)

##### OS.
iOS

##### Browser.
Safari
Firefox

**Comment by haithngn** [comment]
@stefanneculai,
This bug is quite important do we have any update ?

**Comment by fizshoemaker** [comment]
I can confirm that I have encountered this issue as well. Even when you use Chrome in responsive view set to iPhone.
