### ISSUE TITLE
Font sizes question

### ISSUE THREAD

**Issue by BrendonFerreira** [froala/wysiwyg-editor#2727]
The editor has some config to perform font-size units like pt?

I have the premium edition and i did not found any trace of this on the source code.

It is very useful for printing pages with the correct font scale.

**Comment by stefanneculai** [comment]
The latest commit adds the `fontSizeUnit` option which could be set as `'pt'` to use points instead of pixels.

**Comment by DenniLa2** [comment]
Can I use 'vw' as fontSizeUnit? If no, add plz this ability

**Comment by lostan** [comment]
Setting font-size in pt is working fine and set the style correctly. However, the tool bar displays another size instead of correct. I found this bug 10 days ago, hope you have fixed it. 

Thanks,
Leonardo
