### ISSUE TITLE
Bug: IE11 throws "NoModificationAllowedError" exception

### ISSUE THREAD

**Issue by jemunk** [froala/wysiwyg-editor#2728]
Our automatic reporting system, has frequently reported this from the clients.

IE 11 throws "NoModificationAllowedError" exception.

froala_editor.min.js  v2.7.6
Line 11 Coloumn 20872
in this code: 
`h.outerHTML=i`
... within this context:
`... ;c++){var h=e[c],i=h.innerHTML.replace(/\u0009/gi,"").trim();h.outerHTML=i}e=o(Array.prototype.slice.call(d.querySelectorAll("div:not([style]) ...`

I have no idea regarding what action the users have been doing.

Thanks for a great product! In all a very solid editor.

**Comment by stefanneculai** [comment]
Got further details via email.

![image](https://user-images.githubusercontent.com/637004/38889106-4fb35662-4286-11e8-914d-5067341623fd.png)
