### ISSUE TITLE
IE 11 can not type after image

### ISSUE THREAD

**Issue by dhha** [froala/wysiwyg-editor#2729]
##### Expected behavior.
After uploading image into editor then should have new line after that to allow click on and type text

##### Actual behavior.
After uploading image try to enter some text but nothing happen

##### OS.
OS: window 10

##### Browser.
IE 11

**Comment by stefanneculai** [comment]
Adding a new line after the image would create some HTML which wasn't introduced by the end user. For such case we have implemented 2 things: (1) the line breaker tool and (2) when you click closer to the image above/below a new line would be introduced.
