### ISSUE TITLE
Image should be deselect when click outside editor 

### ISSUE THREAD

**Issue by javeriaanwer** [froala/wysiwyg-editor#2730]
Hi, 

I uploaded the image on editor then click outside editor, image remain selected. I want a method from which I can deselect an image. I am using iframe.

you can see this issue here: 

>https://codepen.io/Javeria_Anwer/pen/wpWQPX

![ezgif com-video-to-gif 1](https://user-images.githubusercontent.com/25203829/38722854-c74654a2-3f18-11e8-82cd-bcea887f121f.gif)

how can I deselect an image with method.

**Comment by javeriaanwer** [comment]
Chrome, windows 10

**Comment by GraemeFulton** [comment]
I had this problem too, but when using multiple Froala editors. The editor focus was not being lost, so I triggered blur, which deselects the image:

`events.trigger('blur')`

https://www.froala.com/wysiwyg-editor/docs/events#blur
