### ISSUE TITLE
Escaped spaces in link href

### ISSUE THREAD

**Issue by rafalolszewski94** [froala/wysiwyg-editor#2732]
##### Expected behavior.
Froala shouldn't touch it so I can put it in database, then render via backend engine (escaping breaks the Django tag).

##### Actual behavior.
Froala escapes text in `href` attribute of a link:
![image](https://user-images.githubusercontent.com/37925892/38733833-c026ede8-3f23-11e8-81db-2fbf2209f0f5.png)
As seen on a screenshot, space is replaced by `%20`

##### Steps to reproduce the problem.
1. https://jsfiddle.net/froala/wc5c3jhk/
2. Put a link into the editor
3. Set URL to `{% kb_article_url 2 %}`

##### OS.
mac OS High Sierra 10.13.3

##### Browser.
Chrome Version 65.0.3325.181 (Official Build) (64-bit)

**Comment by stefanneculai** [comment]
It can be done like this: https://github.com/froala/wysiwyg-editor/issues/1235#issuecomment-251943999. However, we do not recommend to disable sanitization because you might introduce XSS problems.
