### ISSUE TITLE
question about toolbar

### ISSUE THREAD

**Issue by DenniLa2** [froala/wysiwyg-editor#2734]
Hello!
What can I do, what would the toolbar look like this http://joxi.ru/Dr8WgxGs4XEPnA ?
Toolbar must be full-size, but if hi is wider editor, his edge extended beyond the edge of editor.

**Comment by stefanneculai** [comment]
For that we'd recommend to use the inline toolbar with minor customizations: https://www.froala.com/wysiwyg-editor/inline.
