### ISSUE TITLE
Want to highlight syntax code snippet insert into WYSIWYG editor area

### ISSUE THREAD

**Issue by TechMaster** [froala/wysiwyg-editor#2739]
##### Expected behavior.
I want to insert code snippet of different programming languages into Froala Editor ( in text editor not code view). Then I use [highlight.js](https://highlightjs.org/) to high light syntax.

The flow will be:

1. Add a customized toolbar into Froala editor
2. Write event handler to open modal dialog that allows user types or pastes code into. User selects type of programming language of inserted code.
3. On modal dialog closes, code will be inserted into WYSIWYG editor area
4. Highlight.js parse inserted code then highlight its syntax 
![image](https://user-images.githubusercontent.com/1491686/38791196-8b256260-4170-11e8-88a4-8d831a20baf0.png)

##### My question:
Does any one have done this feature before?
Is there any plugin for this feature?

**Comment by Meikandanathan** [comment]
@stefanneculai, It's not done, currently we don't have this plugin support in Froala Editor

**Comment by Meikandanathan** [comment]
@stefanneculai, It's not done, currently you don't have this plugin support in Froala Editor
