### ISSUE TITLE
Regression in Froala 2.8.0: Shift + Arrow Left doesn't work as expected

### ISSUE THREAD

**Issue by steffenweber** [froala/wysiwyg-editor#2740]
##### Expected behavior.
For each "arrow left" keypress, one more of the previously typed characters should be selected.

##### Actual behavior.
The cursor moves to the left and selection alternates between 0 or 1 character but never more.

##### Steps to reproduce the problem.
Type a few characters. Then hold shift while pressing the "arrow left" key a few times. This seems to be a regression in Froala 2.8.0 and is currently reproducibly here: https://www.froala.com/wysiwyg-editor

##### OS.
Linux

##### Browser.
Chrome 65.0.3325.181

**Comment by steffenweber** [comment]
This issue does not affect Chrome on macOS but it affects Chrome on Linux and Windows.

**Comment by chrisdeeming** [comment]
I think there are issues in macOS too, actually. I suspect they must be related:

https://youtu.be/IM38rfRalkk

Notice that my intention here is to highlight the word "current" but I also highlight the preceding space.  I'm using Shift + Left Arrow to highlight the word. In normal usage (and in the previous version), Shift + Right would unhighlight the character you just typed, but in this case it starts adding highlighted characters on the opposite side.

@stefanneculai unfortunately this regression is quite significant and it may prevent us rolling out Froala 2.8.0 in its current form. A fairly quick solution would be appreciated...

**Comment by SeanKendle** [comment]
I can confirm this on Firefox on Windows 7 as well.

**Comment by biallo** [comment]
I also encountered this problem.

macOS High Sierra
Chrome 65.0.3325.181

**Comment by steffenweber** [comment]
Thanks! :slightly_smiling_face:

**Comment by steffenweber** [comment]
At least the version of Froala shipped with XenForo 2.0.10 (Froala 2.8.4) doesn't have this bug. And https://www.froala.com/wysiwyg-editor doesn't have this bug either, so I guess it's still fixed in Froala 2.8.5.
