### ISSUE TITLE
Empty list items don't get removed when pressing backspace

### ISSUE THREAD

**Issue by petester42** [froala/wysiwyg-editor#2741]
##### Expected behavior.
When pressing backspace on an empty line the li should be remove.

##### Actual behavior.
The li stays in the document but is empty when pressing backspace. 

##### Steps to reproduce the problem.
Here is a plunkr reproducing the issue. (https://embed.plnkr.co/XyKETv4eM5P8XJZGIai3/).
Steps: 
1 - click ordered list to insert a like
2 - type 1, enter, 2, enter, 3, enter, 4
3 - press backspace until cursor is after 1

There will now be empty li nodes the were not removed by the backspace. 

##### OS.
macOS High Sierra

##### Browser.
Chrome 65.0.3325.181

**Comment by GMiLL5** [comment]
👍 Noticed this with the latest release as well!

**Comment by largeden** [comment]
@stefanneculai 
This issue is related to the issues below.
The important point is that the `_middleBackspace()` in v2.7.3 is fine.

https://github.com/froala/wysiwyg-editor/issues/2626

**Comment by stefanneculai** [comment]
It's fixed on the current master.
