### ISSUE TITLE
wish for improvement

### ISSUE THREAD

**Issue by DenniLa2** [froala/wysiwyg-editor#2743]
Hello!
Thanks for froala - beautiful editor!
Plz, add support for 'vw'. In our project we are going to use your editor. And the lack of 'vw' is the only thing that we lack.
With respect
Denni Adam

**Comment by stefanneculai** [comment]
Thanks for the feature-request, @DenniLa2. We keep this repo mainly for bug tracking, therefore I am closing this for now.
