### ISSUE TITLE
froala parsing mathml incorrect?

### ISSUE THREAD

**Issue by lfeistner** [froala/wysiwyg-editor#2745]
##### Expected behavior.
Expected behaviour would be to show the image for the complete formula:  
[formula2.txt](https://github.com/froala/wysiwyg-editor/files/1920348/formula2.txt)

##### Actual behavior.
I have the following problem: I have the following text:
[formula.txt](https://github.com/froala/wysiwyg-editor/files/1920344/formula.txt)

When I load this into froala with the wiris plugin on I get a call to pluginwiris_engine (these are the query parameters: lang=de&metrics=true&centerbaseline=false&formula=24966ee559643361605d635c372bfad1&version=7.1.0.1388) and get the following response:
{"status":"ok","result":{"height":"29","width":"35","content":"<svg xmlns=\"http://www.w3.org/2000/svg\" xmlns:wrs=\"http://www.wiris.com/xml/cvs-extension\" height=\"29\" width=\"35\" wrs:baseline=\"18\"><defs><style type=\"text/css\"/></defs><text font-family=\"Arial\" font-size=\"16\" text-anchor=\"middle\" x=\"10.5\" y=\"18\">Pp</text><text font-family=\"Arial\" font-size=\"12\" text-anchor=\"middle\" x=\"23.5\" y=\"25\">4</text><text font-family=\"Arial\" font-size=\"12\" text-anchor=\"middle\" x=\"26.5\" y=\"11\">12</text></svg>","baseline":"18","format":"svg","alt":"Pp unterer Index 4 oberer Index 12"}}
As you can see the mprescripts tag is missing which leads to an incorrect image.

##### Steps to reproduce the problem.
(Describe the steps to reproduce the problem here. A [jsFiddle](https://jsfiddle.net/froala/wc5c3jhk/) is awesome when possible.)

##### OS.
any

##### Browser.
definitely chrome and firefox

Further question: I don't understand how and when the digest for the formula is created and also I would have thought the formula transcodes to a digest but not the digest to a formula which in my understanding one call to the pluginwiris_engine is missing?

**Comment by stefanneculai** [comment]
@lfeistner please reach the Wiris team for more details. They have done the Wiris integration.
