### ISSUE TITLE
Content extends beyond the editor

### ISSUE THREAD

**Issue by angelvazquezmenendez87** [froala/wysiwyg-editor#2746]
##### Expected behavior.
The text should always be inside the editor.

##### Actual behavior.
You can see how the text exceeds the bottom of the editor.

##### Steps to reproduce the problem.
1 - Place the Froala editor on a page and configure it to have a maximum height (example: 500px).
2 - Enter a text that exceeds the height of the editor and you can see the vertical scroll.
3 - Gently scroll down.

I have attached an image in which the error can be observed. I can also send you the test page that I used.
![editor 2 8 0](https://user-images.githubusercontent.com/16782281/38882500-46578eec-4238-11e8-90e5-eb54773b6c14.jpg)

##### OS.
Windows Server 2012 R2 Standard 64-bit (6.3, Build 9600) (9600.winblue_ltsb.170914-0600)
(I did the same test in Windows 10 and I could NOT see the error)

##### Browser.
Google Chrome Version 65.0.3325.181 (Official Build) (64-bit)

**Comment by stefanneculai** [comment]
Do you think it would be possible to make a jsFiddle to highlight the problem? That would speed-up things a lot. Here is a basic jsFiddle you could use as a starting point: https://jsfiddle.net/froala/wc5c3jhk/.

**Comment by angelvazquezmenendez87** [comment]
sure thing, please try with this:
https://jsfiddle.net/wc5c3jhk/322/

I hope this can help you, anyway please, if I can help in something else
let me know. Remember, I was only able to reproduce the error in windows
server.

2018-04-17 14:12 GMT-04:00 Stefan Neculai <notifications@github.com>:

**Comment by angelvazquezmenendez87** [comment]
A note for when you are able to reproduce the bug. Note that the problem is
solved by setting the "iframe" property to "false".

best regards

2018-04-17 15:04 GMT-04:00 Angel Vazquez Menendez <
angelvazquezmenendez87@gmail.com>:

**Comment by angelvazquezmenendez87** [comment]
Hi Stefan,
A member of my team was able to reproduce it on Windows 10, I attached a
gif.

2018-04-17 15:25 GMT-04:00 Angel Vazquez Menendez <
angelvazquezmenendez87@gmail.com>:

**Comment by stefanneculai** [comment]
@angelvazquezmenendez87 would it be possible to send the GIF again, it's not visible. Also, do you have any details about where you're pasting the HTML from?

**Comment by angelvazquezmenendez87** [comment]
Hi Stefan,
You do not have to paste an html from another place, you just need to write
"sample test_" and paste it several times until the vertical scroll
appears. Then you can see how the text on the bottom of the editor comes
out.

2018-05-02 15:25 GMT-04:00 Stefan Neculai <notifications@github.com>:

**Comment by angelvazquezmenendez87** [comment]
Hi Stefan,

When I reported this bug I was using this version of chrome:
Version 65.0.3325.181 (Official Build) (64-bit)

Now I noticed that it was updated to the:
Version 66.0.3359.139 (Official Build) (64-bit)

Currently neither I nor my team can see more the error. Thank you very much
for your time.
best regards.

2018-05-02 15:49 GMT-04:00 Angel Vazquez Menendez <
angelvazquezmenendez87@gmail.com>:

**Comment by dbakshi** [comment]
Hi, i used froala editor in my project. It wokred fine on my local. Now when i saw it on my live site server, it is throwing this error. "**Unlicenced copy of froala editor. Use it legally by purchasing a licence.** " How to fix it, as then it should have thrown same error in my local machine. Now that i used it ,invested time in it. Now after few days checking on server, it is creating issue. Kindly help. Reply asap.
Regards
Dharna

**Comment by angelvazquezmenendez87** [comment]
Hi dbakshi,
I suggest you write directly to Froala technical support, or create a ticket specifically for your issue.
This comment may not see it, because the related ticket has already been resolved.
Greetings, I hope you're lucky

**Comment by stefanneculai** [comment]
@dbakshi in order to use the editor, you would have to purchase a license: https://www.froala.com/wysiwyg-editor/pricing.

**Comment by dbakshi** [comment]
Ok thank you both of you!!
