### ISSUE TITLE
Firefox doesn't show the image preview while it's being uploaded

### ISSUE THREAD

**Issue by cauethenorio** [froala/wysiwyg-editor#2747]
##### Expected behavior.
After drag n dropping  an image to the editor using Firefox it should show a preview of the image while it's being uploaded

Like this:
![froala-bug-chrome](https://user-images.githubusercontent.com/496987/38884216-4ccf6d78-4245-11e8-9c27-c2d17cf7207a.gif)

##### Actual behavior.
No image preview is shown and the "Uploading" popover box is shown misaligned, outside the editor area.

Like this:
![froala-bug-firefox](https://user-images.githubusercontent.com/496987/38884223-54d97428-4245-11e8-8072-3616fdf3bb12.gif)

##### Steps to reproduce the problem.
1. Open Froala editor website main page https://www.froala.com/wysiwyg-editor using Firefox
2. Clear the editor content
3. Drop an image to the editor
4. No image preview is shown

##### OS.
OSX 10.11.6

##### Browser.
Firefox 59.0.2

**Comment by stefanneculai** [comment]
I've just checked it and looks like the image is being inserted correctly in Firefox on my side. It looks like your browser is reading the file a little bit slow. The upload works like this: the file is read from disk and rendered in the editor to display the placeholder, in the same time the upload already uploads the image. My guess is that in your case the image is not read from disk to be displayed in the editor fast enough or you might have some configurations in FF which prevent that from happening.

**Comment by cauethenorio** [comment]
Hey @stefanneculai I found the problem on my Firefox: the uBlock and uBlock Origin extensions add a `style` tag which hides all `img[src*="blob:"]` images. Just adding it here case someone face the same problem in the future.

**Comment by stefanneculai** [comment]
Thanks for sharing the solution, @cauethenorio .
