### ISSUE TITLE
META tags with http-equiv = 'refresh'

### ISSUE THREAD

**Issue by abologna-r7** [froala/wysiwyg-editor#2748]
##### Expected behavior.
When I put a Meta tag in source mode, when going back to graphical mode (not source) I should keep editing the HTML contents without META tags actually executing.

##### Actual behavior.
I have a specific META tag that has an http-equiv attribute and where its content has an external URL. Whenever I add this meta tag and change my view into graphical mode, the META tag gets triggered and it causes a redirection/refresh and into the new page specified content. 

This is the META tag I'm actually putting:

```
<meta http-equiv="refresh" content="0; url=https://www.google.com">
```

##### Browser.
Chrome Version 65.0.3325.181 (Official Build) (64-bit)

**Comment by stefanneculai** [comment]
@abologna-r7 Could you make a jsFiddle for it? Thank you in advance.

**Comment by abologna-r7** [comment]
Here it is: https://jsfiddle.net/antoniobologna/m6gz37r9/3/

try adding ```<meta http-equiv="refresh" content="0; url=https://www.google.com">```
It will try to execute the meta tag as soon as you switch back to the non-html mode:

![image](https://user-images.githubusercontent.com/8812471/38889917-a414c29a-4245-11e8-8e61-1eefa26cd372.png)

**Comment by abologna-r7** [comment]
Any updates on this? Thanks.
