### ISSUE TITLE
Question about inline toolbars

### ISSUE THREAD

**Issue by BrendonFerreira** [froala/wysiwyg-editor#2749]
I'm trying to show an inline toolbar in addition to the editor toolbar. I would like to know if it is possible to create in a simplified way, through the settings or I would have to create a plugin to listen some kind of text selection, and show this. If I need to create this plugin, has some function to call this inline editor in a simple way?

Thank's

**Comment by BrendonFerreira** [comment]
Obs. The additional toolbar is not going to show the same elements of toolbar

**Comment by lostan** [comment]
https://www.froala.com/wysiwyg-editor/examples/always-visible
(like that)?

Cheers

**Comment by BrendonFerreira** [comment]
No. This is editor inline, i'm looking for two toolbars with different elements inside

**Comment by stefanneculai** [comment]
Unfortunately, we don't have such an option at this moment. It's already on our list, however, I cannot provide an ETA for it now.
