### ISSUE TITLE
Unable to paste plaintext to iFrame Froala

### ISSUE THREAD

**Issue by kaniansky** [froala/wysiwyg-editor#2750]
##### Expected behavior.
User should be able to paste plaintext to Froala editor with iframe setting on

##### Actual behavior.
User is unable to paste plaintext to Froala editor within iFrame

##### Steps to reproduce the problem.
Copy plaintext to clipboard and try to paste it to Froala editor with iframe setting on
[demo](https://www.froala.com/wysiwyg-editor/examples/iframe)

##### OS.
Win10 x64

##### Browser.
Version 65.0.3325.181 (Official Build) (64-bit)

**Comment by firstladymb** [comment]
@kaniansky @stefanneculai 
We were able to fix it by adding Chrome to line 11131:
```
if (editor.browser.chrome || editor.browser.safari) {
```
Hope that helps!

**Comment by dbattistelli** [comment]
Please add the fix in froala_editor.min.js

**Comment by mthomasson** [comment]
Hi there!
This bug is also for Chrome on other distributions (Linux and Mac).
It is really critical for our users, and I couldn't get @firstladymb fix working. 

@firstladymb, could you maybe fork the repo and add your fix?
@stefanneculai, do you have an idea about when it'll be tackled on the official repo?

Cheers!

**Comment by stefanneculai** [comment]
Thanks for the suggestion guys. We're going to put an update here in the following days.

**Comment by mthomasson** [comment]
Hi @stefanneculai !
Would you have any idea about when this will be tackled? 
This is a very annoying and critical bug, and it was raised almost a month ago.

Cheers!

**Comment by mthomasson** [comment]
Hi there!
Would you have any update on this bug?

Cheers!!
