### ISSUE TITLE
Feature request: Event table.row_inserted table.column_inserted

### ISSUE THREAD

**Issue by mthomasson** [froala/wysiwyg-editor#2751]
##### Expected behavior.
I would like to apply styles on the table when a row or column gets added. 

##### Actual behavior.
For now, the only event available is table.inserted

##### Steps to reproduce the problem.
No way to reproduce (yet)

##### OS.
(OS name and version here)

##### Browser.
(Browser name an version here)

**Comment by stefanneculai** [comment]
@mthomasson, until we add such a feature, we'd recommend using the `commands.after` event to find out when a new column / row was added.
