### ISSUE TITLE
Indenting Lists has wrong default behavior

### ISSUE THREAD

**Issue by Apee** [froala/wysiwyg-editor#2752]
##### Expected behavior.
When I indent a selected list, I expect the whole list to indent. Like it does in every editing software.

##### Actual behavior.
Every element of the list get indented expect the first one.

##### Steps to reproduce the problem.
https://jsfiddle.net/wc5c3jhk/350/

1. Create a list with 4 items in it.
2. Select the whole list
3. Indent it.

**Comment by stefanneculai** [comment]
Although, this is the way Google Docs or MSWord work, indenting the whole list would result in an invalid HTML because in HTML5, for UL and OL tags, valid children are only LI tags.
