### ISSUE TITLE
Dropdown navigation IE - stuck when do not choose any option

### ISSUE THREAD

**Issue by MaciekKuna** [froala/wysiwyg-editor#2755]
##### Expected behavior.
User should navigate through each element of dropdowns (default as well as custom dropdowns) and then move to next toolbar element without being stuck.

##### Actual behavior.
User is stuck when you enter the dropdown and navigate through options. When you do not choose any option and move to next toolbar element, you are stuck.

##### Steps to reproduce the problem.
1. Open editor with toolbar including dropdowns
2. Navigate to dropdown using shortcuts (Alt+F10)
3. Move to dropdown element like font size
4. Unfold dropdown and go down and up without selecting anything
5. Move to next dropdown element
6. Now you are stuck.

##### OS.
Windows 7

##### Browser.
Internet Explorer 11
![navigationbug](https://user-images.githubusercontent.com/16246708/39116161-ffc05648-46e3-11e8-9142-ab37220e525b.gif)

**Comment by kunaMaciej** [comment]
2.8.1 version works fine. Please close this issue.

**Comment by MaciekKuna** [comment]
Works fine in 2.8.1. Please close this issue.
