### ISSUE TITLE
Broken editor on main website on IE

### ISSUE THREAD

**Issue by MaciekKuna** [froala/wysiwyg-editor#2756]
##### Expected behavior.
Should show correct froala editor.

##### Actual behavior.
Editor is broken, toolbar isn't visible as well as editor's frames.

##### Steps to reproduce the problem.
1. Go to https://www.froala.com/wysiwyg-editor

##### OS.
Windows 7

##### Browser.
Internet Explorer 11
![froalaexampleie](https://user-images.githubusercontent.com/16246708/39116800-9f4351c4-46e5-11e8-8171-9f060bd96fcc.PNG)

#

**Comment by JMSD-B** [comment]
We are also having similar issues with both the WYSIWYG editor and with the inline editor. This can be seen on the main website as stated above, but also does not work in our Froala editor which we have already integrated into a project.

Works on other browsers except for IE, no errors can be found in the console.

Inline editors works, however, we cannot highlight text, seems as IE sees it as an element and doesn't allow interaction.

**OS:**
Windows 7 & Browserstack

**Browsers:**
IE11 (windows 7)
IE11/IE10 browser stack
