### ISSUE TITLE
After upload video, thumbnail didn't be shown

### ISSUE THREAD

**Issue by Wolf21** [froala/wysiwyg-editor#2757]
##### Expected behavior.
Upload video by file. Preview video on the editor

##### Actual behavior.
can upload for script, but thumbnail didn't be shown

**Comment by stefanneculai** [comment]
@Wolf21 are you getting this problem on our website? Could you please send us the video file that you''re using?

**Comment by stefanneculai** [comment]
Closing this due to lack of response.

**Comment by nidhin038** [comment]
Yes, it is there in your website. If image is uploaded via file upload, the name of the file is displayed rater than thumbnail. It will work fine if the image is uploaded via image upload. The same problem is for videos as well. 

![image](https://user-images.githubusercontent.com/1975529/51015262-94a82700-1591-11e9-9f67-28636acaf3a0.png)
