### ISSUE TITLE
Froala 2.8.0 lost all selected format after hit return key

### ISSUE THREAD

**Issue by haithngn** [froala/wysiwyg-editor#2760]
##### Expected behavior.
Keep current selected format (eg. color, font, strike, etc...)

##### Actual behavior.
Return original format

##### Steps to reproduce the problem.
Try to format a text line on Froala Editor Demo on an iPad device
Hit enter key then type sometext.

##### OS.
iOS 11

##### Browser.
Safari

**Comment by amerrnath-murugan-E0711** [comment]
+1

**Comment by stefanneculai** [comment]
It's fixed in 2.8.4.
