### ISSUE TITLE
Can't paste tables

### ISSUE THREAD

**Issue by coolrecep** [froala/wysiwyg-editor#2761]
Expected behavior.
Tables should be in tables.

Actual behavior.
Pasted as plain text.

Steps to reproduce the problem.
Copy and paste a table from a website.

OS.
Windows 10 1803

Browser.
Chrome 66 / Edge

https://www.youtube.com/watch?v=JelMBiImJNI

**Comment by Lyubomyr** [comment]
Having the same issue. If copy table from web site and paste - will show not table but html code.

**Comment by coolrecep** [comment]
This is really annoying. Can't even paste from Excel.

**Comment by coolrecep** [comment]
Any update on that?

**Comment by stefanneculai** [comment]
Could any of you guys send us a link / file from which we can paste to see this problem?

**Comment by Lyubomyr** [comment]
From my side, I found the issue and it was not in this library but in my sanitizer. Happened when copy and paster table from any website (so it includes <table> HTML).

**Comment by stefanneculai** [comment]
Thanks for the clarification @Lyubomyr. @coolrecep looking forward to getting details from your side as well.

**Comment by coolrecep** [comment]
Well on my side, I'm using XenForo. XenForo does not have native table support but I've enabled it via an add-on and tables do work. But I can not paste them...

**Comment by coolrecep** [comment]
Any update on that?

**Comment by coolrecep** [comment]
Still. Can't. Paste. Tables.

**Comment by coolrecep** [comment]
Ola!

**Comment by dianaprajescu** [comment]
@coolrecep can you also reproduce this on our website? Or could you please create a jsFiddle where we can see this happening?

**Comment by coolrecep** [comment]
On your website, it works perfect.

**Comment by dianaprajescu** [comment]
Thanks for your confirmation. If it works okay on our website then it means that the issue is not from the editor, but from the way it is integrated. For technical support, please contact us thorough out website: https://www.froala.com/wysiwyg-editor/contact
