### ISSUE TITLE
text deselected (removed highlight) when color picker is selected

### ISSUE THREAD

**Issue by jettcalleja** [froala/wysiwyg-editor#2766]
##### Expected behavior.
Text should be selected (highlighted) when color picker is selected.
##### Actual behavior.
Text is not selected nor highlighted.
##### Steps to reproduce the problem.
https://jsfiddle.net/wc5c3jhk/358/
1. Type anything
2. Select that text
3. Click the color picker
4. Notice the highlight is removed
##### OS.
(OS name and version here)
Windows 10, Version 2.8
##### Browser.
(Browser name an version here)
Chrome 66

**Comment by stefanneculai** [comment]
When the colors popup is opened, the cursor focuses on the input inside the popup. The browsers do not allow to have focus on multiple regions on the same page and that is why the focus / highlight is being removed from the editor.
