### ISSUE TITLE
Editor scrolls to top after adding an image

### ISSUE THREAD

**Issue by TimSielemann** [froala/wysiwyg-editor#2768]
##### Expected behavior.
Scroll position stays the same as before

##### Actual behavior.
Scroll position is resetted to the top of the content

##### Steps to reproduce the problem.

1. use this fiddle (https://jsfiddle.net/xnsac70u/1/) with an editor with fixed max height
2. create content that forces the editor to be scrollable
3. add a stock image (by the "browse" section, no uploading) at the bottom of the content

##### OS.
MacOS 10.12.6

##### Browser.
Chrome 66

**Comment by stefanneculai** [comment]
@TimSielemann we're not able to reproduce it. Do you think you could provide a video?

**Comment by TimSielemann** [comment]
Hey @stefanneculai turns out that i can't reproduce this too in default froala but in our customised version. Sorry for the time taken.
