### ISSUE TITLE
Unable to insert links with port but without protocol

### ISSUE THREAD

**Issue by remofritzsche** [froala/wysiwyg-editor#2769]
##### Expected behavior.

1. Insert link: `foo.com:3000` (any description)
2. Link gets prefixed and results in `https://foo.com:3000`

##### Actual behavior.

1. Insert link: `foo.com:3000` (any description)
2. Link gets prefixed and results in `https://foo.com%3A3000` (`:` gets replaced by `%3A`)

**=> The `:` should stay and not be replaced by `%3A`**

##### OS.
Any.

##### Browser.
Mozilla Firefox, possibly others.

**Comment by stefanneculai** [comment]
See https://www.froala.com/wysiwyg-editor/docs/options#linkAutoPrefix.

**Comment by remofritzsche** [comment]
Thank you for your answer. We know about `linkAutoPrefix`, but the problem is that `:` gets replaced by `%3A`.

**Comment by sitroxrmeier** [comment]
Hi, I would like to know if this is work-in-progress and if we can expect a fix for this issue soon.

Thank you for your efforts

Kind Regards
Robin Meier
