### ISSUE TITLE
Backspacing over the first character of a new line, entirely removes the new line.

### ISSUE THREAD

**Issue by chrisdeeming** [froala/wysiwyg-editor#2771]
##### Expected behavior.
If you backspace the first character of a new line, you shouldn't jump back to the previous line.

##### Actual behavior.
Backspacing over the first character of a new line, entirely removes the new line.

##### Steps to reproduce the problem.
1. [Froala front page](https://www.froala.com/wysiwyg-editor/)
2. Type the following:

```
This is a line.

T
```
3. Backspace the new line's `T` character.
4. Entire new line is removed and the caret jumps to the end of `line.` on the first line.

##### OS.
Any

##### Browser.
Any

**Comment by SeanKendle** [comment]
Experiencing this with DIV elements as well, even when they have the "fr-inner" class.

**Comment by timfeid** [comment]
https://codepen.io/anon/pen/jKOLwV

This happens here as well. The 1 letter block + backspace seems to be ignoring NO_DELETE_TAGS or htmlAllowedEmptyTags.

Perhaps #2849 is another example of this.

**Comment by Vnthf** [comment]
plz fix this

**Comment by stefanneculai** [comment]
This should be fixed on the current master repo from here.
