### ISSUE TITLE
On pasting big text need to convert into multple div's not in single div

### ISSUE THREAD

**Issue by dharmadurai** [froala/wysiwyg-editor#2773]
##### Expected behavior.
If i paste a big content like this, with multiple lines

Hello line 1
Hello line 2
Hello line 3

I want this output should come, Note: no need wrapping div
```
<div>Hello line 1</div>
<div>Hello line 2</div>
<div>Hello line 3</div>
```
##### Actual behavior.
After pasting i get this as output
```
<div>
Hello line 1<br>
Hello line 2 <br>
Hello line 3 <br>
</div>
```

**Comment by stefanneculai** [comment]
@dharmadurai could you please provide more details about where you're pasting from?

**Comment by dharmadurai** [comment]
I dont understand what more details you want, and why you closed the issue
without getting information and fixing..

Thanks for your support, forget this issue.

**Comment by stefanneculai** [comment]
@dharmadurai my mistake. Sorry. Waiting for more details. Thanks.

**Comment by dharmadurai** [comment]
No problem... I just before found an alternate solution.. It is working for
me... We can close the issue, i will get back to you if any help...

Thanks... Very Sorry, Forget my replies..

You can close the issue.. I will comment on the issue also

**Comment by dharmadurai** [comment]
We can close this issue, i found a simple solution, it might be more time consuming for you to fix, lets forget this issue..
Thanks
