### ISSUE TITLE
Caret jumps to the beginning of the text

### ISSUE THREAD

**Issue by kantuni** [froala/wysiwyg-editor#2774]
##### Expected behavior.
Caret should stay where it is unless instructed to do so.

##### Actual behavior.
Caret jumps to the beginning of the text

##### Steps to reproduce the problem.
- Type `hello`
- Hit space

##### OS.
macOS
10.13.4

##### Browser.
Firefox Quantum
59.0.2 (64-bit)

**Comment by stefanneculai** [comment]
@kantuni are you experiencing this on our website as well?

**Comment by kantuni** [comment]
That's strange. I did. But now it's fine.

**Comment by stefanneculai** [comment]
That is good to hear, @kantuni :)

**Comment by kantuni** [comment]
Yeah! Thanks, @stefanneculai
