### ISSUE TITLE
'fr-sticky-dummy' element not rendering in FF/Edge

### ISSUE THREAD

**Issue by joshuaaron** [froala/wysiwyg-editor#2775]
##### Expected behavior.
element 'fr-sticky-dummy' to be rendered in the dom

##### Actual behavior.
element 'fr-sticky-dummy' not rendering in the dom

##### OS.
Windows 10

##### Browser.
Firefox 59.0.2,
Microsoft Edge 16

Using Froala Editor for a project where it is rendered to post a comment. We have set styles to this element to get some vertical spacing between the toolbar / profile icon we have added to the left and the actual textarea.
In Chrome + IE this works without issue. In Firefox and Edge (oddly not IE?) this element doesn't seem to render in the DOM tree:

Chrome:
![image](https://user-images.githubusercontent.com/13953685/39457830-c229ea46-4d33-11e8-9e31-0dfa606ecb07.png)

Firefox:
![image](https://user-images.githubusercontent.com/13953685/39457811-a4734a10-4d33-11e8-85aa-1bfe26efc2ab.png)

**Comment by joshuaaron** [comment]
We were utilising that element as a spacing element but this can definitely be refactored to use something else - was just wondering why that was happening

**Comment by stefanneculai** [comment]
This should be fixed in version 2.8.4.

**Comment by riv-riv** [comment]
I have a similar problem
somtimes element 'fr-wrapper' not rendering

I use version 3.1.1-1

OS.
Windows 10

Browser.
Chrome
![image](https://user-images.githubusercontent.com/83582757/116867302-8aecd680-ac15-11eb-9ea8-d0fde1be6a61.png)

![image](https://user-images.githubusercontent.com/83582757/116867306-8cb69a00-ac15-11eb-810a-ddded814265a.png)
