### ISSUE TITLE
Batch remove links button

### ISSUE THREAD

**Issue by coolrecep** [froala/wysiwyg-editor#2777]
##### Expected behavior.
Ability to remove all hyperlinks in texts

##### Actual behavior.
No button to do that

##### Steps to reproduce the problem.
Remove one by one...

##### OS.
10 x64 1803

##### Browser.
Chrome 66

**Comment by stefanneculai** [comment]
Thanks for the feature-request, @coolrecep .

**Comment by mpssoft** [comment]
create a custom button to remove all links href attribute:
$.FroalaEditor.DefineIcon('unlink', {NAME: 'unlink'});
		$.FroalaEditor.RegisterCommand('unlink', {
		  title: 'unlink all links',
		  focus: true,
		  undo: true,
		  refreshAfterCallback: true,
		  callback: function (e) { 
			$('.fr-view').find("a").each(function(){
				$(this).removeAttr("href"); // remove href
                                //$(this).remove(); // remove [a] tag
			});
		  }
    });
