### ISSUE TITLE
Local file upload does not work

### ISSUE THREAD

**Issue by Hillcow** [froala/wysiwyg-editor#2778]
I successfully upload the image to a local folder on my PC and return JSON as expected:

{"link":"file:///Documents/test.jpg"}

So I am using the absolute path which works perfectly fine in any browser.

However, I get the error message: "Something went wrong. Please try again"

Even though the upload was successful, the link works fine and the JSON is formatted correctly.

I guess your code struggles to load local image data anyway?

**Comment by stefanneculai** [comment]
@Hillcow could you please let us know what output you get in the console when you add the following events:

```js
.on('froalaEditor.image.error', function (e, editor, error, response) {
  console.log(error);
  console.log(response);
});
```

**Comment by stefanneculai** [comment]
Closing this due to lack of response.
