### ISSUE TITLE
Cannot focus to the editor by invoked the JavaScript function (iOS)

### ISSUE THREAD

**Issue by haithngn** [froala/wysiwyg-editor#2779]
##### Expected behavior.
Open iOS keyboard, focus cursor to the Froala Editor

##### Actual behavior.
scrollup to show toolbar only

##### Steps to reproduce the problem.
Load Froala into UIWebview, listen "initialized" event.
call editor.events.focus();

##### OS.
iOS 9 10 11

##### Browser.
UIWebview/Safari

**Comment by stefanneculai** [comment]
Unfortunately, on iOS it is not possible to focus to an element by using JS code. It requires user interaction. This is a restriction set in by Apple.

**Comment by haithngn** [comment]
I did fixed it.

**Comment by vermashivam** [comment]
> I did fixed it.

Can you please give an insight on how you fixed it?
