### ISSUE TITLE
TypeError: Failed to execute 'setStartAfter' on 'Range': parameter 1 is not of type 'Node'.

### ISSUE THREAD

**Issue by wojcikstefan** [froala/wysiwyg-editor#2783]
We (Close.io) have noticed that some of our users regularly get a `TypeError` when using Froala v2.7.5. I don't yet have a way to reproduce the problem, but I figured the stack trace alone might be helpful:

```
TypeError: Failed to execute 'setStartAfter' on 'Range': parameter 1 is not of type 'Node'.

1 File "webpack:///./node_modules/froala-editor/js/froala_editor.min.js" line 7 col 30209 in Object.u [as save]
!function(a){"function"==typeof define&&define.amd?define(["jquery"],a):"object"==typeof module&&...
2 File "webpack:///./node_modules/froala-editor/js/froala_editor.min.js" line 8 col 14804 in Object.p [as toHTML5]
a(u.previousSibling).remove();if(t&&(b.node.isVoid(t)||b.node.isBlock(t))&&(t=null),u&&(b.node.is...
3 File "webpack:///./node_modules/froala-editor/js/froala_editor.min.js" line 8 col 29778 in y
a(u.previousSibling).remove();if(t&&(b.node.isVoid(t)||b.node.isBlock(t))&&(t=null),u&&(b.node.is...
4 File "webpack:///./node_modules/froala-editor/js/froala_editor.min.js" line 9 col 1 in Object.S [as set]
u(),b.opts.useClasses||(b.$el.find("[fr-original-class]").each(function(){this.setAttribute("clas...
5 File "webpack:///./node_modules/froala-editor/js/froala_editor.min.js" line 9 col 16757 in Object.d [as _init]
u(),b.opts.useClasses||(b.$el.find("[fr-original-class]").each(function(){this.setAttribute("clas...
6 File "webpack:///./node_modules/froala-editor/js/froala_editor.min.js" line 7 col 4761 in t.load
!function(a){"function"==typeof define&&define.amd?define(["jquery"],a):"object"==typeof module&&...
7 File "webpack:///./node_modules/froala-editor/js/froala_editor.min.js" line 7 col 2031 in t.<anonymous>
!function(a){"function"==typeof define&&define.amd?define(["jquery"],a):"object"==typeof module&&...
8 File "webpack:///./node_modules/jquery/dist/jquery.js" line 10268 col 1 in HTMLTextAreaElement.r
return fn.apply( context || this, args.concat( slice.call( arguments ) ) );
9 File "webpack:///./node_modules/jquery/dist/jquery.js" line 5183 col 1 in HTMLTextAreaElement.dispatch
handleObj.handler ).apply( matched.elem, args );
10 File "webpack:///./node_modules/jquery/dist/jquery.js" line 4991 col 1 in HTMLTextAreaElement.m.handle
jQuery.event.dispatch.apply( elem, arguments ) : undefined;
```

##### OS.
Happens on all recent versions of Windows and macOS.

##### Browser.
All of the errors I'm seeing come from our Chromium-based native application (https://www.chromium.org/)

**Comment by stefanneculai** [comment]
Thanks for the details @wojcikstefan. Any way we could get the HTML which is there in the editor when this error happens?

**Comment by wojcikstefan** [comment]
Hi @stefanneculai! Unfortunately I haven't been able to capture the HTML that causes this error yet. Will let you know once I do.

**Comment by philfreo** [comment]
@stefanneculai Any chance you could try solving this without the actual HTML based on the stack trace? We've had similar errors in the past (#369).

**Comment by stefanneculai** [comment]
@philfreo it is pretty clear where the email comes from, however, it is strange that you're seeing it in Chrome because that part of the code is only for Safari.

**Comment by philfreo** [comment]
What makes you think we're seeing it in Chrome?

Most (maybe all - but I'm not sure, we'd need to check) of the errors are coming from our desktop app which is based on Chromium (an older version at the moment - we will be updating it soon) but has a custom user agent set like: 
"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) CloseIO/2.3.3 Safari/537.36"

**Comment by stefanneculai** [comment]
@philfreo have you had the chance to take a look over the changes I put recently?

**Comment by stefanneculai** [comment]
I would assume this is fixed as per our tests the problem is not there anymore.
