### ISSUE TITLE
Feature Request: displayText option for fontSize

### ISSUE THREAD

**Issue by iseem** [froala/wysiwyg-editor#2784]
Many sites use relative units for font size, such as `em`, `rem`, or ` %`. When displayed to the user these values may not make sense. For example, a site that uses `rem` units might have a `fontSize` array like:

`fontSize: ['0.75', '0.85', '1', '1.25', '1.5']`

I would like to be able to control the text my users see in the font size dropdown menu by creating a `fontSize` array like:

`fontSize: [
    { 
        displayText: 'Tiny',
        fontSize: '0.75'
    }, 
    {
        displayText: 'Small',
        fontSize: '0.85'
    },
    {
        displayText: 'Medium',
        fontSize: '1'
    },
    {
        displayText: 'Large',
        fontSize: '1.25'
    },
    {
        displayText: 'Huge',
        fontSize: '1.5'
    }
]`

Thanks!

**Comment by stefanneculai** [comment]
Closing this for now, as we keep here only the issues, not `feature-requests`. Thanks for sending it, @iseem!
