### ISSUE TITLE
Define icon per instance

### ISSUE THREAD

**Issue by dgroh** [froala/wysiwyg-editor#2786]
##### Expected behavior.
I have multiple froala instances on the same page and I want to have for each instance different icons

##### Actual behavior.
Currently is only possible to define global icons with **$.FroalaEditor**

##### Steps to reproduce the problem.
Add multiple froala editors to the page:

`$('#instance1').froalaEditor(...)`
`$('#instance2').froalaEditor(...)`

Try to add for each instance a different icon for `insertLink`

##### OS.
(OS name and version here)

##### Browser.
(Browser name an version here)

**Comment by stefanneculai** [comment]
Thanks for the feature-request, @dgroh .

**Comment by stefanneculai** [comment]
We've just put together a public roadmap with the most popular features. 😍 There you can vote your favorite one, provide feedback or make new suggestions: https://wysiwyg-editor-roadmap.froala.com/public.
