### ISSUE TITLE
Style tags being stripped out of editor.

### ISSUE THREAD

**Issue by abologna-r7** [froala/wysiwyg-editor#2787]
Whenever I put some ```<style>``` tags in the HTML editor, when I come back to edit more HTML I see that the style tags are being removed.

I'm in the latest version of Froala: **2.8.1**

Please see attached screencast:
http://recordit.co/BC5gmQWZ40

**Comment by stefanneculai** [comment]
Please make sure that you've removed style from the following option: https://www.froala.com/wysiwyg-editor/docs/options#htmlRemoveTags.
