### ISSUE TITLE
Chinese image filename received by server is messy code

### ISSUE THREAD

**Issue by RookieLittleFatty** [froala/wysiwyg-editor#2788]
I insert a image with Chinese filename and config the imageUploadURL in my server ,but the filename received by my server is messy code . I find the possible reason in the network, it is about the content-disposition encode mode.  Is there any way to solve this problem?

**Comment by stefanneculai** [comment]
As far as we're aware, it is not possible to avoid that. We'd recommend to set a custom random filename on the server side.
