### ISSUE TITLE
Editor malfunctions after clicking on google map

### ISSUE THREAD

**Issue by ceetee** [froala/wysiwyg-editor#2790]
##### Expected behavior.
The User should be able to enter all characters into the WYSI editors content area
##### Actual behavior.
When on the same page with a google map, clicking on the map causes certain characters(`k m c !#$%'`) to stop functioning within the WYSI editor 
##### Steps to reproduce the problem.
* Add a google map and a Froala WYSI editor to the same page.
* click on the google map.
* try to type characters into the WYSI editor

jsFiddle: https://jsfiddle.net/ceetee/5wckfzn5/2/

When `disableDefaultUI` is set to `true` for the google maps config Froala works as expected.

##### OS.
MacOS Sierra `v10.12.6`

##### Browser.
Google Chrome `Version 66.0.3359.139 (Official Build) (64-bit)`

**Comment by stefanneculai** [comment]
We'd recommend enabling the iframe mode in this case: https://jsfiddle.net/5wckfzn5/3/.
