### ISSUE TITLE
Video not draggable in IE

### ISSUE THREAD

**Issue by TimSielemann** [froala/wysiwyg-editor#2794]
##### Expected behavior.
Video is draggable like in chrome/firefox

##### Actual behavior.
Video is not draggable (see video: [video not draggable.zip](https://github.com/froala/wysiwyg-editor/files/1983702/video.not.draggable.zip))

##### Steps to reproduce the problem.

1. insert video from url (e.g. https://www.youtube.com/watch?v=n75amYUmilQ)
2. try to drag it

##### OS.
Windows 10

##### Browser.
IE 11

**Comment by stefanneculai** [comment]
Should be fixed on the current Github master.
