### ISSUE TITLE
After insert embedly item, if something changes in a paragraph embedly does not render

### ISSUE THREAD

**Issue by Kikerrobles** [froala/wysiwyg-editor#2795]
##### Expected behavior.
Adding or changing paragraph style or  format have not to hide embedly items

##### Actual behavior.
If you change any paragraph style or format, embedly items become invisible.

##### Steps to reproduce the problem.
Just add som text, add an embedly item and them add or change some paragraph style or format

##### OS.
Windows 10

##### Browser.
Using Firefox and Chrome

**Comment by stefanneculai** [comment]
@Kikerrobles do you think you could make a jsFiddle? We've checked it and couldn't replicate on our side.

**Comment by stefanneculai** [comment]
All looks good on the demo from the [Froala Website](https://www.froala.com/wysiwyg-editor). Closing this for now, but we'd be happy to look again into it if we get more details.
