### ISSUE TITLE
Sticky toolbar is not working in Chrome and IE

### ISSUE THREAD

**Issue by rw-tchowdhury** [froala/wysiwyg-editor#2797]
##### Expected behavior.
Sticky toolbar should stick on top while scrolling.
The option "scrollableContainer" should set the container for the toolbar.

##### Actual behavior.
Toolbar disappears from view while scrolling down. 

"scrollableContainer" is not working.

##### Steps to reproduce the problem.
Using the following JSFiddle,
https://jsfiddle.net/toufiq/ppyLhnqt/6/

     1. Scroll the output window
     2. The toolbar disappears

The toolbar is back when you resize the window,

     1. Resize the window making it smaller by width and height to get the toolbar on top
     2. Change the width
     3. Notice the toolbar is still on top
     4. Change the height
     5. Notice the toolbar is not again disappears

Please also check the example below 
https://jsfiddle.net/toufiq/ppyLhnqt/9/

     1. Scroll the output window
     2. The toolbar disappears

It seems, "scrollableContainer" option does not work properly also.

##### Exception:  
Firefox browser does not produce the issue.

Please try the same JSFiddle in Firefox

##### OS.
Windows 10

##### Browser.
Google Chrome
Version 66.0.3359.139 (Official Build) (32-bit)

Internet Explorer
Version: 11.2189.14393.0

**Comment by stefanneculai** [comment]
@rw-tchowdhury that is because you set the CSS property `overflow: hidden` for the `HTML` element.

**Comment by rw-tchowdhury** [comment]
@stefanneculai I have removed the CSS property for HTML element in following JSFiddle but the issue still there.

https://jsfiddle.net/toufiq/ppyLhnqt/11/

     1. Scroll the output window
     2. The toolbar disappears
