### ISSUE TITLE
Paste from docx to froala has style issues

### ISSUE THREAD

**Issue by codeandcloud** [froala/wysiwyg-editor#2798]
##### Expected behavior.
Want to paste a Microsoft Word document and see it in the WYSIWYG editor as it is
##### Actual behavior.
The content is all being pasted. None of the text is missing. But we are having text-align issues. 

If you follow the steps to reproduce below, you can see that the first section looks OK. Its center-aligned as per the doc file. 
But all the sections below the first one should be left aligned. And they all are center aligned.

##### Steps to reproduce the problem.

1. Download and open the document  [Master Example-Star Wars.docx](https://github.com/froala/wysiwyg-editor/files/1985641/Master.Example-Star.Wars.docx)
2.  Now paste it to the [Froala Online WYSIWYG editor](https://www.froala.com/wysiwyg-editor). 
3.  The online editor exactly replicates the behavior we have in our website. Same alignment issues which is quite noticeable.

##### Additional Information 

This is how we use the editor.

      $('div#froala-editor').froalaEditor({
        lineBreakerOffset: 20,
        imageUploadURL: 'https://restservices.oursite.org/api/File/UploadImage',
        tableCellStyles: {
          red: 'Red',
          blue: 'Blue',
          black: 'Black',
          boldblack: 'Black and Bold',
          extraboldblack: 'Extra bold and black',
          'center-bold': 'Centered and Bold'
        },
        wordAllowedStyleProps: ['font-family', 'font-size', 'background', 'color', 'width', 'text-align', 'vertical-align', 'background-color', 'padding', 'margin', 'height', 'margin-top', 'margin-left', 'margin-right', 'margin-bottom', 'text-decoration', 'font-weight', 'font-style'],
        toolbarButtons: ['bold', 'italic', 'underline', 'strikeThrough', 'subscript', 'superscript', 'fontFamily', 'fontSize', '|', 'specialCharacters', 'color', 'emoticons', 'inlineStyle', 'paragraphStyle', '|', 'paragraphFormat', 'align', 'formatOL', 'formatUL', 'outdent', 'indent', '-', 'quote', 'insertHR', 'insertLink', 'insertImage', 'insertVideo', 'insertFile', 'insertTable', '|', 'undo', 'redo', 'clearFormatting', 'selectAll', 'html', 'applyFormat', 'removeFormat', 'fullscreen', 'print', 'help']
      });

Are we missing any properties? Why the align doesn't work?
Any pointers would have been very helpful.

P.S: We have another image with border not appearing issue, which I think we could get around to, later. Letting you know this now to understand whether they are related.

##### Browser.
Chrome Latest Stable in Windows

**Comment by stefanneculai** [comment]
The table might come with align attributes instead of the alignment in the CSS style. We'll have to make some more checks.
