### ISSUE TITLE
Pyramid with Froala wysiwyg editor + SDK. Error when try upload file (code 2 - no link in upload response)

### ISSUE THREAD

**Issue by emptyinc** [froala/wysiwyg-editor#2799]
I'm new to coding, and for several days I have been struggling with this problem.
I got a problem when i upload file on my local server (file don`t save on directory "public")

1. It`s my template (with jinja2):

        <form action="{{request.route_url('article_action',action=action)}}" method="post" class="form">
            {% if action =='edit' %}
                {{ form.id() }}
            {% endif %}
    
            <div class="form-group">
                <label for="title">{{ form.title.label }}</label>
                {{ form.title(class_='form-control') }}
            </div>
    
          {{ form.content(id='edit') }}
            <button type="submit" class="btn btn-default">Submit</button>
        </form>
    
        <script>
        $(function() {
        $('#edit').froalaEditor({
            // Set the file upload parameter.
            fileUploadParam: 'file_param',
    
            // Set the file upload URL.
            fileUploadURL: '/upload_file',
    
            // Additional upload params.
            fileUploadParams: {id: 'my_editor'},
    
            // Set request type.
            fileUploadMethod: 'POST',
    
            // Set max file size to 20MB.
            fileMaxSize: 20 * 1024 * 1024,
    
            // Allow to upload any file.
            fileAllowedTypes: ['*']
          })
          .on('froalaEditor.file.beforeUpload', function (e, editor, files) {
            // Return false if you want to stop the file upload.
          })
          .on('froalaEditor.file.uploaded', function (e, editor, response) {
            // File was uploaded to the server.
          })
          .on('froalaEditor.file.inserted', function (e, editor, $file, response) {
            // File was inserted in the editor.
          })
          .on('froalaEditor.file.error', function (e, editor, error, response) {
            // Bad link.
            if (error.code == 1) { alert('1') }
    
            // No link in upload response.
            **else if (error.code == 2) { alert('2') } // i got this error**
    
            // Error during file upload.
            else if (error.code == 3) { alert('3') }
    
            // Parsing response failed.
            else if (error.code == 4) { alert('4') }
    
            // File too text-large.
            else if (error.code == 5) { alert('5') }
    
            // Invalid file type.
            else if (error.code == 6) { alert('6') }
    
            // File can be uploaded only to same domain in IE 8 and IE 9.
            else if (error.code == 7) { alert('7') }
    
            // Response contains the original server response to the request if available.
          })
        });
    </script>

2. This is my routes.py:

        config.add_route('upload_file', '/upload_file')
        config.add_view(upload_file, route_name='upload_file')

        config.add_route('upload_file_validation', '/upload_file_validation')
        config.add_view(upload_file_validation, route_name='upload_file_validation')

3. This is upload_file.py:

        def upload_file(request):
        options = {
            'validation': None
        }
        try:
            response = File.upload(PyramidAdapter(request), '/public/', options)
        except Exception:
            response = {'error': str(sys.exc_info()[1])}
        return Response(json.dumps(response))
    
        def upload_file_validation(request):
    
        def validation(filePath, mimetype):
            size = os.path.getsize(filePath)
            if size > 10 * 1024 * 1024:
                return False
            return True
    
        options = {
            'fieldname': 'myFile',
            'validation': validation
        }
        try:
            response = File.upload(PyramidAdapter(request), '/public/', options)
        except Exception:
            response = {'error': str(sys.exc_info()[1])}
        return Response(json.dumps(response))

4. This is file.py (from SDK):

        class File(object):
    
        defaultUploadOptions = {
        'fieldname': 'file',
        'validation': {
            'allowedExts': ['txt', 'pdf', 'doc', 'docx', 'xls', 'xlsx'],
            'allowedMimeTypes': ['text/plain', 'application/msword', 
        'application/x-pdf', 'application/pdf']
        }
        }
    
        @staticmethod
        def upload(req, fileRoute, options = None):
        """
        File upload to disk.
        Parameters:
            req: framework adapter to http request. See BaseAdapter.
            fileRoute: string
            options: dict optional, see defaultUploadOptions attribute
        Return:
            dict: {link: 'linkPath'}
        """
    
        if options is None:
            options = File.defaultUploadOptions
        else:
            options = Utils.merge_dicts(File.defaultUploadOptions, options)
    
        # Get extension.
        filename = req.getFilename(options['fieldname'])
        extension = Utils.getExtension(filename)
        extension = '.' + extension if extension else ''
    
        # Generate new random name.
    
        # python 2-3 compatible:
        try:
            sha1 = hashlib.sha1.hexdigest()  # v3
        except Exception:
            sha1 = hashlib.sha1.hexdigest()  # v2
        routeFilename = fileRoute + sha1 + extension
    
        fullNamePath = Utils.getServerPath() + routeFilename
    
        req.saveFile(options['fieldname'], fullNamePath)
    
        # Check validation.
        if 'validation' in options:
            if not Utils.isValid(options['validation'], fullNamePath, req.getMimetype(options['fieldname'])):
                File.delete(routeFilename)
                raise Exception('File does not meet the validation.')
    
        # Check image resize.
        if 'resize' in options and options['resize'] is not None:
            with Image(filename=fullNamePath) as img:
                img.transform(resize=options['resize'])
                img.save(filename=fullNamePath)
    
        # build and send response.
        response = {}
        response['link'] = routeFilename
        return response

5. This is adapters.py (from sdk):    

        class BaseAdapter(object):
        """
        Interface. Inherit this class to use the lib in your framework.
        """
    
        def __init__(self, request):
            """
            Constructor.
            Parameters:
                request: http request object from some framework.
            """
            self.request = request
    
        def riseError(self):
            """
            Use this when you want to make an abstract method.
            """
            raise NotImplementedError( "Should have implemented this method." )
    
        def getFilename(self, fieldname):
            """
            Get upload filename based on the fieldname.
            Parameters:
                fieldname: string
            Return:
                string: filename
            """
            self.riseError()
    
        def getMimetype(self, fieldname):
            """
            Get upload file mime type based on the fieldname.
            Parameters:
                fieldname: string
            Return:
                string: mimetype
            """
            self.riseError()
    
        def saveFile(self, fieldname, fullNamePath):
            """
            Save the upload file based on the fieldname on the fullNamePath location.
            Parameters:
                fieldname: string
                fullNamePath: string
            """
            self.riseError()
        class PyramidAdapter(BaseAdapter):
        """
        Pyramid Adapter: Check BaseAdapter to see what methods description.
        """
    
        def checkFile(self, fieldname):
            if fieldname not in self.request.POST:
                raise Exception("File does not exist.")
    
        def getFilename(self, fieldname):
            self.checkFile(fieldname)
            return self.request.POST[fieldname].filename
    
        def getMimetype(self, fieldname):
            self.checkFile(fieldname)
            return self.request.POST[fieldname].type
    
        def saveFile(self, fieldname, fullNamePath):
            self.checkFile(fieldname)
            file = self.request.POST[fieldname].file
    
        file.seek(0)
        with open(fullNamePath, 'wb') as output_file:
                shutil.copyfileobj(file, output_file)

What am I doing wrong? Please, help.

**Comment by stefanneculai** [comment]
Closing this as it is related to tech support. We use this repo mainly for bug tracking.
