### ISSUE TITLE
extra <p> tags added inside <li> elements

### ISSUE THREAD

**Issue by rwaters71** [froala/wysiwyg-editor#280]
The current version seems to add extra `<p>..</p>` tags inside each `<li> .. </li>` element, which also causes extra vertical spacing.

When I open html that has a bulleted list, after editing there are paragraph wrappers inside each list element.

**Comment by ca-dsgn** [comment]
@stefanneculai Is it possible to prevent this behaviour? I would like to use p tags inside li.
