### ISSUE TITLE
Firefox: Tab crashes when dragging large images

### ISSUE THREAD

**Issue by fynnfeldpausch** [froala/wysiwyg-editor#2800]
##### Expected behavior.
I can drag & drop large images in the RTE to move the image to another part of the text.

##### Actual behavior.
The Firefox tab crashes when I drop the image at another part of the text.

##### Steps to reproduce the problem.
1. Open https://jsfiddle.net/cfzks2jy/1/
2. Insert text in the RTE
3. Insert a large image (>10mb)
4. Drag & Drop the image to another place in the text

##### OS.
macOS High Sierra v10.13.4

##### Browser.
Firefox Quantum v59.0.1 (64-Bit)

**Comment by stefanneculai** [comment]
@fynnfeldpausch we've just checked this and there doesn't appear to be any problem in Firefox 59.0.2. Would it be possible to check in it as well?

**Comment by fynnfeldpausch** [comment]
Seems to be fixed in newer Firefox versions...
