### ISSUE TITLE
When image plugin is disabled you can still "paste" images in Firefox

### ISSUE THREAD

**Issue by jkeatingatigloo** [froala/wysiwyg-editor#2802]
##### Expected behavior.
When you have **disabled** the image plugin, the user should not be able to copy & paste images into the editor.

##### Actual behavior.
If the image plugin is disabled and the users copies and pastes an image into the editor in **Firefox**, the image is inserted.

##### Steps to reproduce the problem.
1. Navigate to this fiddle in Firefox- the image plugin is disabled https://jsfiddle.net/sufx48wx/1/ 
2. right click on an image and "copy" it
3. right click inside the editor and see paste is enabled
4. "paste" image, image in inserts

If you test these steps in Chrome you cannot "paste", it's disabled.

##### OS.
WIndows 10 

##### Browser.
Firefox 59.0.3 (64 bit)

**Comment by stefanneculai** [comment]
@jkeatingatigloo the image plugin is designed for interacting with the images, not for allowing/preventing pasting images. To disable adding images in the editor, it would be best to use the [pasteDeniedTags option](https://www.froala.com/wysiwyg-editor/docs/options#pasteDeniedTags).
