### ISSUE TITLE
Prevent a span's formatting from being inherited by text in the same paragraph

### ISSUE THREAD

**Issue by JWaldenback** [froala/wysiwyg-editor#2808]
When removing all text including the last space between text that is formatted (bold, italic, font-color and such) and normal text the formatting will be inherited. Is it possible to make it work more like Microsoft Word does? Link tags in Froala work that way atm.

This is how it works in Froala:
![froala span and link behaviour](https://user-images.githubusercontent.com/19432538/39998187-a024b37a-5785-11e8-9af5-c7db64858ac5.gif)

This is how it works in Microsoft Word:
https://user-images.githubusercontent.com/19432538/39998194-a36b2b0e-5785-11e8-8be2-5719ddfc751b.gif

**Comment by stefanneculai** [comment]
We don't have a built-in option for such a behavior and it is unlikely to add one because of the way the selection in the browser works.
