### ISSUE TITLE
Script error for ctrl+p shortcut

### ISSUE THREAD

**Issue by tokarkry** [froala/wysiwyg-editor#2809]
##### Expected behavior.
CTRL+P shortcut open printer modal view - default browser shortcut.

##### Actual behavior.
When use shortcut as **CTRL+P** to open printer view modal (default Froala behaviour for this shortcut is to insert image) web browser console shows the error that "isVisible" variable is not defined lub empty/null.
This behaviour exists when Froala editor button for insert image is removed.

##### Steps to reproduce the problem.
Remove insert image button with standard Froala shortcut.
Select CTRL+P which should open printer modal view.

##### OS.
Windows 7.

##### Browser.
Internet Explorer 11, Version: 10.0.9600.18860
Google Chrome, Version: 66.0.3359.139

**Comment by stefanneculai** [comment]
@tokarkry you could easily disable it via https://www.froala.com/wysiwyg-editor/docs/options#shortcutsEnabled.
