### ISSUE TITLE
Sticky toolbar and "scrollableContainer" option is not working in Chrome and IE

### ISSUE THREAD

**Issue by rw-tchowdhury** [froala/wysiwyg-editor#2810]
##### Expected behavior.
Sticky toolbar should stick on top while scrolling.
The option "scrollableContainer" should set the container for the toolbar.

##### Actual behavior.
Toolbar disappears from view while scrolling down.
"scrollableContainer" is not working.

##### Steps to reproduce the problem.
Using the following JSFiddle,
https://jsfiddle.net/toufiq/ppyLhnqt/11/

     1. Scroll the output window
     2. The toolbar disappears

Please notice, "scrollableContainer" option is not working. Toolbar is not sticking on top of the scrollable container.

##### Implementation scenario.
     1. In our implementation, we have views where the html tag is not scrollable container.
     2. For those views, we are expecting the tool bar to become sticky relative to the scrollable container instead of the html element.
     3. To achieve that, we are setting "scrollableContainer" option to the parent scrollable container.
     4. The option scrollableContainer is supposed to set the container of the toolbar, in our case, that is the parent div.

##### OS.
Windows 10

##### Browser.
Google Chrome
Version 66.0.3359.139 (Official Build) (32-bit)

Internet Explorer
Version: 11.2189.14393.0

**Comment by stefanneculai** [comment]
You cannot have the editor itself set as the `scrolalbleContainer`. You could put there a parent which is scrollable: https://jsfiddle.net/ppyLhnqt/12/.
