### ISSUE TITLE
Chrome: Dragging and dropping large images from insecure site to secure site fails

### ISSUE THREAD

**Issue by psoloninka** [froala/wysiwyg-editor#2811]
##### Expected behavior.
Dragging and dropping a large image from an insecure site either attempts to retrieve the image over HTTPS or shows a descriptive error message.

##### Actual behavior.
Dragging and dropping a large image from an insecure site to a secure site fails to upload the image and shows the "Something went wrong. Please try again." message.

##### Steps to reproduce the problem.
1. Go to https://www.froala.com/wysiwyg-editor.
2. Open http://www.dumpaday.com/funny-animals/funny-animal-pictures-27-pics in a new window.
3. Drag the first image on the dumpaday page into the editor.
4. Observe that the image fails to load and a non-specific error message is displayed. The network tab of the Chrome dev tools show a `blocked:mixed-content` message.

Note that dragging smaller images seems to work fine.

##### OS.
Mac OS 10.12.6

##### Browser.
Chrome 66.0.3359.170

**Comment by stefanneculai** [comment]
Thanks for the `feature-request`, @psoloninka.
