### ISSUE TITLE
Back button for custom modal docs

### ISSUE THREAD

**Issue by dgroh** [froala/wysiwyg-editor#2812]
##### Expected behavior.
When I click on a button in the toolbar, I open a custom modal based on this doc (https://www.froala.com/wysiwyg-editor/docs/concepts/custom/popup). I want a button to navigate back to the toolbar - the same as the insertLink modal:

![image](https://user-images.githubusercontent.com/16785357/40043529-f77eab40-5824-11e8-9a37-66d45a2547aa.png)

##### Actual behavior.
I don't find any documentation about how to insert a back button.

##### Steps to reproduce the problem.
(Describe the steps to reproduce the problem here. A [jsFiddle](https://jsfiddle.net/froala/wc5c3jhk/) is awesome when possible.)

##### OS.
(OS name and version here)

##### Browser.
(Browser name an version here)

**Comment by stefanneculai** [comment]
The back button is a regular button that we have in place for each of the popup. You could add one at anytime, by using a custom button: https://www.froala.com/wysiwyg-editor/examples/custom-buttons.

**Comment by dgroh** [comment]
I know how to create a custom button, I wanted to know how to go back? `this.editor.goBack()` ?
