### ISSUE TITLE
placeholderText does not appear with htmlAllowedEmptyTags option

### ISSUE THREAD

**Issue by wkurtz** [froala/wysiwyg-editor#2813]
##### Expected behavior.
placeholder text should still be visible, 

##### Actual behavior.
having 'p' tag in htmlAllowedEmptyTags makes the editor to not show the placeholder text any more

##### Steps to reproduce the problem.
$('#edit').froalaEditor({
  placeholderText: 'pPlaceholder',
  htmlAllowedEmptyTags: [ 'span', 'p' ]
});

##### OS.
linux mint

##### Browser.
chronomium 65.0.3325

**Comment by stefanneculai** [comment]
The `htmlAllowedEmptyTags` option is designed to be set only for non-block tag elements. Therefore, if you add the `p` tag there it won't work correctly anymore. I am sure that there is another better way of achieving the things you're looking for. Could you please explain your use-case?
