### ISSUE TITLE
Content extends to the left of the editor -- content cannot be seen

### ISSUE THREAD

**Issue by apiram** [froala/wysiwyg-editor#2814]
##### Expected behavior.
Content should be displayed within the editor window.

##### Actual behavior.
Content extends past left side of the editor.

##### Steps to reproduce the problem.
![screenshot 2018-05-15 19 26 04](https://user-images.githubusercontent.com/8700389/40053990-d97fe2e8-5875-11e8-810b-8fbf22eb28b2.png)

##### OS.
Windows, MAC

##### Browser.
Chrome

**Comment by apiram** [comment]
![4ec2255b-7330-4d4a-8a13-b200fe3b5a90](https://user-images.githubusercontent.com/8700389/40054031-01f487c4-5876-11e8-8cbe-46d68872cefc.jpg)

Froala is generating auto-indent

**Comment by stefanneculai** [comment]
@apiram most likely you've changed the `wordAllowedStyleProps` (https://www.froala.com/wysiwyg-editor/docs/options#wordAllowedStyleProps) and allowed `text-indent`. Although it might be present, we'd recommend not using this option.
