### ISSUE TITLE
Toolbar button focus/hover

### ISSUE THREAD

**Issue by tokarkry** [froala/wysiwyg-editor#2815]
##### Expected behavior.
Should not remove focus from toolbar buttons when mouse is hover to toolbar buttons after select shortcut navigation as **ALT+F10**.

##### Actual behavior.
Remove focus from toolbar buttons when mouse is hover to toolbar buttons after select shortcut navigation as **ALT+F10**..

##### Steps to reproduce the problem.
Select **ALT+F10** froala navigation shortcut. Navigate between toolbar button by keyboard arrows. Hover mouse pointer to frola toolbar button. The focus of selected button disappears.

##### OS.
Windows 7.

##### Browser.
Internet Explorer 11, Version: 10.0.9600.18860
Google Chrome, Version: 66.0.3359.139

**Comment by stefanneculai** [comment]
This is the way the accesibility was designed to work and unfortunately because of some browser limitations for editing we have to keep it like this.
