### ISSUE TITLE
extra space after pressing fullscreen

### ISSUE THREAD

**Issue by templatetuners** [froala/wysiwyg-editor#2818]
This is a video http://take.ms/iZQvJ

`div.fr-sticky-dummy` is duplicating. So when I focus the editor, there is extra space between toolbar and my text.

It happens on mobiles after pressing fullscreen.

**Comment by stefanneculai** [comment]
@templatetuners could you please check that you're using the latest 2.8.1 version?

**Comment by templatetuners** [comment]
used latest.min from cdn

**Comment by stefanneculai** [comment]
@templatetuners we were not able to reproduce it. Could you please let us know more details on what mobile device are you able to reproduce this?

**Comment by templatetuners** [comment]
web browser chrome and android cordova

**Comment by stefanneculai** [comment]
What is the specific device that you're testing on?

**Comment by templatetuners** [comment]
samsung s8

**Comment by stefanneculai** [comment]
@templatetuners we've tried to reproduce this without success. Do you think it would be possible to make a jsFiddle to highlight the problem? That would speed-up things a lot. Here is a basic jsFiddle you could use as a starting point: https://jsfiddle.net/froala/wc5c3jhk/.

**Comment by Mboulianne** [comment]
I've had the same issue on my iphone.

-Focus the editor
-Open up fullscreen
-Focus the editor again
anndd an extra space appears.

However I was able to fix the issue using the following css

.fr-sticky-dummy + .fr-sticky-dummy {
            height: 0 !important;
}
