### ISSUE TITLE
Jaws INSERT+F5 and select toolbar button

### ISSUE THREAD

**Issue by tokarkry** [froala/wysiwyg-editor#2819]
##### Expected behavior.
After selected in **INSERT+F5** (JAWS shortcuts) and select toolbar button the focus is change and user should can navigate between toolbar button using arrow keys

##### Actual behavior.
After selected in  **INSERT+F5** (JAWS shortcuts) and select toolbar button the focus is change but nothing else happend + arrow keys don't work to move left or right

##### Steps to reproduce the problem.
If selected in  **INSERT+F5**  window, the button is in focus an can be executed with SPACE/ENTER, also the focus then can be moved with arrow keys like if toolbar was accessed via ALT+F10 -no wit has the gray frame as if it is in focus, but nothing happens, also arrow keys don't work to move focus left or right

##### OS.
Windows 7.

##### Browser.
Internet Explorer 11, Version: 10.0.9600.18860

**Comment by stefanneculai** [comment]
The focus can be moved over to the toolbar only by using the `ALT+F10` combination.
