### ISSUE TITLE
contenteditable="true" inside contenteditable="false" quirks

### ISSUE THREAD

**Issue by ghost** [froala/wysiwyg-editor#282]
Hi, 

First of all, I'm a very satisfied customer of Froala editor. Nice work!

Now, I have what might be a strange use case, but was wondering what your thought was on this.

I love the way you have to backspace an empty element for it to be removed in Froala, this makes a lot of sense. But if you have a `contenteditable="true"` element inside a `contenteditable="false"` element, the element gets removed when the last text character is removed, instead of having to backspace away the empty element.

```
<h2>Test</h2>
<div style="background-color: #faa; border: 1px solid #000;" contenteditable="false">
    <h2 contenteditable="true">Test</h2>
</div>
```

The first heading works as expected, while the second heading is removed right away.

Also, if you hit enter while inside the second `h2`, the editor tries to add the paragraph as a child to the `h2` element as so:

```
<h2>Test</h2>
<div style="background-color: #faa; border: 1px solid #000;" contenteditable="false">
    <h2 contenteditable="true">Test        
        <p>Testing again</p>
    </h2>
</div>
```

Any solutions to this?

Thanks!

**Comment by jimmyon** [comment]
Hi Stefan,

The editor has a bug whenever clicking quickly on a inline editor. This
pops up with a textfield. Is this a known bug on your editor plugin?

Jimmy

**Comment by stefanneculai** [comment]
Hi @jimmyon! Is that happening on the master version? If so, could you please make a jsfiddle?

**Comment by Smashr** [comment]
Froala 2.1.0 does not appear to be working in a scenario where contenteditable="true" is inside contenteditable="false". It would work just fine on versions before 2.0.

The editing and the shortcuts work just fine, the Froala toolbar when in inline mode does not appear at all.  ("toolbarInline: true")

The toolbar appears and works just fine when 'toolbarInline' is set to false though.

**Comment by stefanneculai** [comment]
@Smashr last commit should fix it.

**Comment by Smashr** [comment]
Thanks Stefan !
