### ISSUE TITLE
Selection does not restore after transforming text

### ISSUE THREAD

**Issue by latortuga** [froala/wysiwyg-editor#2822]
I'm writing a custom button as outlined in the documentation that converts some selected text to a different format. Now I could do this solely with CSS the way that bold/italic/etc are done, but this needs to persist on to a separate system. So, it's not merely a display concern, the actual text needs to be cleaned / transformed.

As a result, I wrote my button to use `html.insert` and it works great! However, after executing the insert, the selection goes away, and I can't figure out a way to resurrect it.

##### Expected behavior.
```js
const selected = this.selection.text() // e.g. "The thing about it"
this.selection.save()
this.html.insert(selected.replace(/thing/,"THING")) // convert "thing" to uppercase "THING"
this.selection.restore()
```
At this point I expect `selection.text` to return `"The THING about it"`.

Some things I've tried:
- As above, `selection.save` + `selection.restore`
- Calling `markers.place` post-insert with the range returned by `selection.ranges` from pre-insert
- `selection.setBefore` / `selection.setAfter`
- Using `selection.restore` after setting marks with `markers` API, though it's not clear to me if that's an intended usage combo

##### Actual behavior.
No selection at all. Cursor at the end of the changed text.

##### OS.
MacOS High Sierra and Ubuntu 16.04

##### Browser.
Google Chrome 65 and 66

ETA: concrete example text

Thanks for any help / guidance you can provide!

**Comment by stefanneculai** [comment]
When you insert HTML, the stored selection is removed because selection is set in the `html.insert` method. If you'd like to keep the selection, we'd recommend searching for markers after storing the selection and change their class name (`this.el.querySelectorAll('.fr-marker')`) and then change the class back after the insert and restore the selection.

**Comment by latortuga** [comment]
Thanks for the help, I'll give it a go.
