### ISSUE TITLE
Add fab support for Font Awesome 5

### ISSUE THREAD

**Issue by SeanKendle** [froala/wysiwyg-editor#2825]
Add `fab` support for Font Awesome 5, simply add:

Line 12265:
`    font_awesome_5b: '<i class="fab fa-[FA5NAME]" aria-hidden="true"></i>',`

(for use with icons like these: https://fontawesome.com/icons?d=gallery&q=css)

**Comment by chrisdeeming** [comment]
Just throwing this out there, on the off-chance you're not aware, but you can define and use your own icon template.

```javascript
$.FE.DefineIconTemplate('font_awesome_5b', '<i class="fab fa-[FA5NAME]" aria-hidden="true"></i>');

$.FE.DefineIcon('css', { FA5NAME: 'css3-alt', template: 'font_awesome_5b' });
```

**Comment by SeanKendle** [comment]
I know, but he added support for Font Awesome 5 in a recent update, and to fully flesh it out, support for `fab` should be added.

**Comment by chrisdeeming** [comment]
Absolutely agree.

Hopefully people can use the workaround in the meantime.

**Comment by SeanKendle** [comment]
Before FA5 implementation, I created my own plugin that added support for it in the same way, so it's definitely helpful.
