### ISSUE TITLE
Increase identation is disabled after emptied textbox

### ISSUE THREAD

**Issue by opan** [froala/wysiwyg-editor#2827]
##### Expected behavior.

The `increase indent` toolbar should be enabled to click after we emptied the editor.

##### Actual behavior.

The `increase indent` toolbar is disabled after we insert bullets and then emptied the editor. 

I found that `increase indent` toolbar is disabled if we use `enter` options with `$.FroalaEditor.ENTER_BR` but not with the default one which is `$.FroalaEditor.ENTER_P`.

You can try it [here](https://jsfiddle.net/wc5c3jhk/438/).

##### Steps to reproduce the problem.

1. Open [froala editor here](https://jsfiddle.net/wc5c3jhk/438/) and notice that by default `increase indent` or all toolbar is enabled.
2. Insert bullets into editor by clicking `bullets` toolbar.
3. Now click it again so now the bullets are removed from the editor.
4. Notice that `increase indent` toolbar is still disabled, which is should be enabled.

##### OS.

macOS sierra 

##### Browser.

Version 66.0.3359.181 (Official Build) (64-bit)

**Comment by stefanneculai** [comment]
When using list items, the indentation is not possible for the first list item, in order to keep it HTML 5 valid.

**Comment by opan** [comment]
If so why if we used `ENTER_P` as a value for `enter` options is enabled? Could please explain this? Thanks
