### ISSUE TITLE
Save content to localStorage

### ISSUE THREAD

**Issue by Kapranov98** [froala/wysiwyg-editor#2829]
I would like to see in Froala support for saving text in localStorage. Such a function exists in TinyMCE and it is very convenient:
https://www.tinymce.com/docs/plugins/autosave/
https://github.com/tinymce/tinymce-dist/tree/master/plugins/autosave

**Comment by stefanneculai** [comment]
Thanks for the suggestion, @Kapranov98. As a workaround until we add this, I would recommend to use the contentChanged event and store the editor content in the localstorage.
