### ISSUE TITLE
IE 11 Strikethrough line displaying in red colour for misspelled words

### ISSUE THREAD

**Issue by SagarKharche** [froala/wysiwyg-editor#2831]
Hi,

Strikethrough functionality is not working as expected in IE 11 and MS edge when spellcheck is on. Notice an issue with strikethrough line color for misspelled words.
Here are the steps to reproduce:-
1.	Open froala editor in IE 11 or MS edge(https://www.froala.com/wysiwyg-editor)
2.	Insert line with one word misspelled.
3.	Select misspelled word and click on 'Strikethrough'.
4.	Notice text with spelling error are strike in red line.
 
Expected: Strikethrough line should be of same color as text.
Thanks,
Sagar K
<img width="1440" alt="screen shot 2018-05-21 at 3 44 31 pm" src="https://user-images.githubusercontent.com/7273026/40302785-eb1292c0-5d0d-11e8-8318-bb8947a24599.png">

**Comment by stefanneculai** [comment]
This is the way MS Edge displays the misspelled words which are strike-through. Unfortunately, there is nothing we could do to change this.
