### ISSUE TITLE
RTL and Source View

### ISSUE THREAD

**Issue by salasfoor** [froala/wysiwyg-editor#2832]
##### Expected behavior.
Source view should be RTLed where the line numbers are to the right and the alignment of the code is also to the right. 

##### Actual behavior.
Now, when accessing source view in a RTL mode, the alignment is still LTR.

##### Steps to reproduce the problem.
- Change the editor mode to RTL.
- Click on "View Source".

##### OS.
All Operating Systems.

##### Browser.
All Browsers.

**Comment by stefanneculai** [comment]
Thanks for the `feature-request` @salasfoor
