### ISSUE TITLE
[Feature] Shortcut to paste plain text

### ISSUE THREAD

**Issue by talha-asad** [froala/wysiwyg-editor#2833]
##### Expected behavior.
A special shortcut like ctrl+shift+v and a similar alternative for Mac for pasting plain text, regardless of pastePlain setting.

##### Actual behavior.
Text is pasted as rich text

##### Steps to reproduce the problem.
No steps to reproduce as a feature.

##### OS.
Mac OS X 10.12

##### Browser.
Chrome 60+

**Comment by stefanneculai** [comment]
Thanks for the `feature-request` @talha-asad. `CMD + OPT + SHIFT + V` already works on MacOS.

**Comment by talha-asad** [comment]
On second note, it doesn't work.

**Comment by earshinov** [comment]
@stefanneculai , Can you maybe reopen the ticket? The issue isn't solved according to @talha-asad . Also, even if there is a shortcut on MacOS, what about Windows and Linux? My opinion is that this shortcut should be provided by the editor, just like Google Docs implement Ctrl-Shift-V.

**Comment by earshinov** [comment]
I resubmitted the request here: https://wysiwyg-editor-roadmap.froala.com/

> A shortcut to paste without formatting (e.g., Ctrl-Shift-V as in Google Docs).
>
> https://github.com/froala/wysiwyg-editor/issues/2833
