### ISSUE TITLE
Calling "html.get" returns sometimes encoded, sometimes unencoded HTML characters

### ISSUE THREAD

**Issue by rgbweb** [froala/wysiwyg-editor#2835]
##### Expected behavior.
Invoking the API method `html.get` should return identical HTML with either encoded or unencoded special characters like _quotes_ and German umlauts (i.e. _Ä_, _Ö_, _Ü_).

##### Actual behavior.
When the editor is assigned to an element and the configuration setting `initOnClick` is set to `true`, the API method `html.get` returns unencoded HTML. Even previously encoded umlauts become unencoded (i.e. `&Auml;` becomes `Ä`). When the editor is than clicked and becomes initialized, the same method call returns endoded HTML characters like `&Auml;` and `&quot;`.
This is a annoying, when the HTML content needs to be compared to the original HTML after it was edited. The problem can be worked around by initializing all editor instances on the page when they become assigned to their elements (setting `initOnClick` is set to `false`). But this could result in performance problems.

##### Steps to reproduce the problem.
I've created an example on codepen to show the problem. Note, that the printed HTML output is first converted to a JSON string, to better show the behaviour: https://codepen.io/anon/pen/xjBaOO

##### OS.
Windows 10

##### Browser.
Chrome 66, Firefox 60, IE 11

**Comment by stefanneculai** [comment]
see https://www.froala.com/wysiwyg-editor/docs/options#entities

**Comment by rgbweb** [comment]
Hi Stefan,

thank you for the link. I can confirm, that setting the `entities` option to an empty string, can change the behaviour on the second call to that methode.

Bu how does this explain, the first result, where Froala returns always unencoded HTML, even when the entities where encoded in the original input?
