### ISSUE TITLE
Very big z-index value is set to toolbar element in fullscreen mode

### ISSUE THREAD

**Issue by liunaijia** [froala/wysiwyg-editor#2836]
##### Expected behavior.
No z-index attribute applied to the toolbar element.

##### Actual behavior.
`style="z-index: 2147483642;"` is applied to the toolbar element.

##### Steps to reproduce the problem.
1. Go to fullscreen edit mode.
2. Click any toolbar item which has a dropdown menu (i.e. Insert Image).
3. The toolbar element has `z-index: 2147483642` as the value of style attribute.

##### OS.
MacOS 10.13.4

##### Browser.
- Chrome Version 68.0.3437.2 (Official Build) canary (64-bit)
- Safari Version 11.1 (13605.1.33.1.4)

**Comment by stefanneculai** [comment]
The zIndex is being applied in order to make sure that it stays on top of everything else on the page. Also, the toolbar is designed to work highly in connection with the rest of the editor UX.

**Comment by liunaijia** [comment]
@stefanneculai Thanks for your prompt reply. I mean after leaving from fullscreen mode the z-index on the toolbar is still there, which makes toolbar covers other elements (i.e. a popup dialog).

**Comment by InciteGmbH** [comment]
We have the same issue:

"I mean after leaving from fullscreen mode the z-index on the toolbar is still there, which makes toolbar covers other elements (i.e. a popup dialog)." (from liunaijia on 24 May)

 Is there a solution for this? Our version is 2.8.4.
