### ISSUE TITLE
Missing Language Translations for Image Styles

### ISSUE THREAD

**Issue by jkeatingatigloo** [froala/wysiwyg-editor#2838]
##### Expected behavior.
The "style" dropdown options from the image edit menu should be translated from English.

##### Actual behavior.
The values are not translated and remain in English. 

##### Steps to reproduce the problem.
1. Navigate to a Froala editor with a language  other than English  enabled. (https://www.froala.com/wysiwyg-editor/examples/language)
2. Upload an image
3. Ope the image edit "style" drop down
4. Notice Rounded, Bordered, Shadow remain in English

##### OS.
Windows 10

##### Browser.
Chrome Version 66.0.3359.139 (Official Build) (64-bit)

**Comment by stefanneculai** [comment]
@jkeatingatigloo thanks for the suggestion. Unfortunately, at this moment adding translations for those options is not on our list because they can be customized and usually are customized by users.
