### ISSUE TITLE
Cursor goes over the emoji

### ISSUE THREAD

**Issue by antmoreau** [froala/wysiwyg-editor#2841]
When emoticonsUseImage is set to True, the cursor goes over the emoji when trying to select it.
This issue does not appear when emoticonsUseImage is set to False.

Is there a trick to avoid this?

Thank you

**Comment by stefanneculai** [comment]
@antmoreau not sure I understand the issue. Do you think you could send us a recording? Thanks in advance.

**Comment by antmoreau** [comment]
Hi @stefanneculai,
You can find a gif below.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/25058262/40835529-fcfed14a-6593-11e8-8f86-a625a0b4f8f4.gif)

I am using Chrome on Ubuntu 16.04

**Comment by stefanneculai** [comment]
Unfortunately, in some Chrome versions we're facing this problem and for now we don't have a possible workaround.
