### ISSUE TITLE
Shortcuts don't display for dropdown-enabled buttons

### ISSUE THREAD

**Issue by latortuga** [froala/wysiwyg-editor#2842]
##### Expected behavior.
Dropdown options for buttons with multiple options (e.g. Quote plugin) should show shortcut info when `shortcutsEnabled` is true.

##### Actual behavior.
Dropdown options don't have shortcuts shown.

##### Steps to reproduce the problem.
1. Enable quote plugin
2. Add quote to the toolbar
3. Add `shorcutsEnabled: true` to your config.
3. Observe the dropdown options for quote - the plugin includes keyboard shortcuts for both increase and decrease quote level, that both work out of the box. Neither option has a tooltip with shortcut information.

#### Details
I have a Business license and access to the full source so I can actually see the bug. The shortcut string is calculated on lines 12824 - 12831 and then it's never used. It should be included in line 12833. If this is too much private detail to have posted in an issue, please feel free to redact it.

**Comment by SuyogKLP** [comment]
Hi Stefan, I am able to apply shortcuts for "Quote->Increase and Decrease", Can you tell for which all 
drop-downs do we need to put shortcuts as we do not have specific shortcut keys for them.
