### ISSUE TITLE
Link Enhancements

### ISSUE THREAD

**Issue by SeanKendle** [froala/wysiwyg-editor#2843]
`linkAutoPrefix` - this is great, but could we have a boolean option to use the `linkAutoPrefix` value only when clicking the "Preview" button on the link? I would like to leave my links starting with "/", but this breaks the preview button because this editor is in a Control Panel with a different domain from our clients' sites. Or maybe a string `linkPreviewPrefix` option?

`linkList`: 
`displayText` vs `text` 
- `text` replaces the text in the text field, which has its uses.
- `displayText` never replaces the text in the text field. This is great when there is already predefined text. Could you change it to fill the text field only if the text field is blank? Or create an option for that behavior?

Finally, correct me if I'm wrong, but in the documentation, it says that `linkText` is `false` by default, but it seems to be `true` by default.

**Comment by stefanneculai** [comment]
@SeanKendle it is quite a particular case. What I would recommend is to use the link.beforeInsert method and make changes to the options there in case certain conditions are met. Inside the link.beforeInsert method, you could update the linkAutoPrefix option like this:

```js
editor.opts.linkAutoPrefix = false;
```
