### ISSUE TITLE
imageAttributes option

### ISSUE THREAD

**Issue by SeanKendle** [froala/wysiwyg-editor#2844]
Is it possible to add an `imageAttributes` option like the `linkAttributes` option?  Obviously this would need its own popup or tab to also be created.

**Comment by stefanneculai** [comment]
I am marking it as a `feature-request` for now. The image insertion flow is different than the link one, so we'll have to discuss a little bit about that.

**Comment by adammiribyan** [comment]
Has this been implemented by any chance? I need to add a `crossorigin="anonymous"` attribute to all `img` tags inside the editor, any other ways I can do that?
