### ISSUE TITLE
Add the ability to disable lineBreak in table mode

### ISSUE THREAD

**Issue by dgroh** [froala/wysiwyg-editor#2847]
##### Expected behavior.
I don#t want my users to add a line break to the editor with contains only a table

##### Actual behavior.
There is no way to avoid line breaking

![image](https://user-images.githubusercontent.com/16785357/40544092-59a37e4a-6027-11e8-8aac-8115b8532e45.png)

##### Steps to reproduce the problem.
(Describe the steps to reproduce the problem here. A [jsFiddle](https://jsfiddle.net/froala/wc5c3jhk/) is awesome when possible.)

##### OS.
(OS name and version here)

##### Browser.
(Browser name an version here)

**Comment by dgroh** [comment]
Ok, I could manage this by setting `lineBreakerTags: null`

**Comment by yubaoquan** [comment]
> Ok, I could manage this by setting `lineBreakerTags: null`

in froala 4.0.10, setting a null will trigger an exception: 
```
Uncaught TypeError: Cannot read properties of null (reading 'join')
```

this config works:
`lineBreakerTags: ['noExistsSelector']`
