### ISSUE TITLE
When emptying a cell the last cell in the same row is removed

### ISSUE THREAD

**Issue by Tedamo** [froala/wysiwyg-editor#2849]
##### Expected behavior.
When emptying a cell nothing should happen to the cells in the table.

##### Actual behavior.
When emptying a cell the last cell in the same row is removed.

##### Steps to reproduce the problem.
![the last cell in the row is removed when emptying a cell](https://user-images.githubusercontent.com/19432538/40617718-7e6ac16a-628f-11e8-8725-17a152e64e60.gif)

##### Browser.
Chrome.

**Comment by Christian-Seematter** [comment]
We are experiencing this too, lots of users are very confused about this. Emptying the cell should not automatically delete it.

As a workaround you can highlight the text inside the cell and only delete that. This way the cell itself will not be highlighted like it is when just editing the text inside of it.

**Comment by timfeid** [comment]
Try setting `keepFormatOnDelete` to true

**Comment by stefanneculai** [comment]
This should be fixed on the current master branch.
