### ISSUE TITLE
Clear formatting remove element node

### ISSUE THREAD

**Issue by celeneisip** [froala/wysiwyg-editor#2851]
##### Expected behavior.
On clear formatting it should not remove the element node

##### Actual behavior.
On clear formatting it removes the element node, which breaks the format of a HTML markup

##### Steps to reproduce the problem.

- Create list
- style list (optional)
- double click on a list item until the entire list item is selected
- click formatting
- check html markup in your browser inspector

check this for sample:
https://www.dropbox.com/s/jvpf8nk8xli2mj8/list%20-%20clear%20formatting.mov?dl=0

##### OS.
MacOS high seirra

##### Browser.
Firefox/chrome

**Comment by stefanneculai** [comment]
Shoud be fixed on the current master repo.
