### ISSUE TITLE
Ability to set padding on cells in Tables

### ISSUE THREAD

**Issue by ncmancuso** [froala/wysiwyg-editor#2852]
*Feature request*

##### Expected behavior.
Add the ability to set the padding inside of cells when creating and filling out a table. 

##### Actual behavior.
There is no option to increase/decrease the padding.

##### Steps to reproduce the problem.
N/A

##### OS.
N/A

##### Browser.
N/A

**Comment by stefanneculai** [comment]
We don't keep feature requests opened here, therefore, I am marking it accordingly and closing this for now. Thanks for the suggestion!

**Comment by ncmancuso** [comment]
@stefanneculai is there a preferred way to report feature requests?

**Comment by stefanneculai** [comment]
We've just put together a public roadmap with the most popular features. 😍 There you can vote your favorite one, provide feedback or make new suggestions: https://wysiwyg-editor-roadmap.froala.com/public.
