### ISSUE TITLE
Ability to set the border colour of a cell when creating a Table

### ISSUE THREAD

**Issue by ncmancuso** [froala/wysiwyg-editor#2853]
*Feature request*

##### Expected behavior.
When selecting a cell in a table, there should be an option to include the ability to modify that cell(s) border colour.

##### Actual behavior.
There currently is no feature like this

##### Steps to reproduce the problem.
N/A

##### OS.
N/A

##### Browser.
N/A

**Comment by stefanneculai** [comment]
Thanks for the feature-request @ncmancuso

**Comment by LukeHartcher** [comment]
Was this ever implemented? It appears to be been flagged as a feature-request but then closed 1 minute later!?
Have recently purchased a licence (through work) and this is a feature that we would like to be added.
