### ISSUE TITLE
Hiding the container, then switching from Code View to Text while hidden doesn't update iframe height

### ISSUE THREAD

**Issue by r0bb077** [froala/wysiwyg-editor#2854]
##### Expected behavior.
Type some data into code view.
The editor is then hidden.
Toggle to Text View.
Show editor with correct data.

##### Actual behavior.
Type some data into code view.
The editor is then hidden.
Toggle to Text View.
Iframe height isn't updated correctly so you can't see the content

##### Steps to reproduce the problem.
https://jsfiddle.net/robebsta/wc5c3jhk/459/
Start with code view, type something into the body, then click the "hide, switch view, then show" button

##### OS.
Windows 10

##### Browser.
Chrome 66.0.3359.181

##### Workaround
#2437 Used the users workaround here to update iframe when I show the editor again

**Comment by stefanneculai** [comment]
Because of the way browsers work, it is not possible to compute the height of an element while it is hidden. Therefore, for the height of the iframe to be updated correctly, the editor should be visible.
