### ISSUE TITLE
Allow shortcuts without the ctrl key

### ISSUE THREAD

**Issue by petester42** [froala/wysiwyg-editor#2856]
##### Expected behavior.
I would like to register a shortcut that does not require the use of the ctrl key. For example I want to create a quick insert that uses "alt + d" to add content to the editor. 

##### Actual behavior.
Right now I can't register this shortcut "alt + d". The registered shortcut will always be "ctrl + (other keys"

##### Steps to reproduce the problem.
- Register a shortcut

##### OS.
macOS High Sierra

##### Browser.
Chrome  66.0.3359.181

**Comment by stefanneculai** [comment]
Thanks for the `feature-request`.
