### ISSUE TITLE
htmlAllowedEmptyTags -> implement for all tags

### ISSUE THREAD

**Issue by zvermike** [froala/wysiwyg-editor#2858]
hi guys, how to implement htmlAllowedEmptyTags option for all tags at once, i'm tried htmlAllowedEmptyTags: ['.*'] but it's not working?

**Comment by stefanneculai** [comment]
The `htmlAllowedEmptyTags` is designed to be used for tags which are not blockTags, e.g. p, h1, h2, etc.. Also, it doesn't allow a wildcard, and tags should be specified individually.

**Comment by zvermike** [comment]
Maybe there are other options to avoid removing tag if content is empty. Because sometimes i need tag just for implementing font awesome icons without any content.
<i class="fas fa-clock"></i> But when i'm switching mode in froala, tag removed.

**Comment by stefanneculai** [comment]
@zvermike Do you think it would be possible to make a jsFiddle to highlight the problem? That would speed-up things a lot. Here is a basic jsFiddle you could use as a starting point: https://jsfiddle.net/froala/wc5c3jhk/.

**Comment by zvermike** [comment]
1. open this link: https://jsfiddle.net/wc5c3jhk/478/
2. click on editor html view: 
![image](https://user-images.githubusercontent.com/22680852/40986648-6ad16f62-68ef-11e8-953c-5a45004577b1.png);
3. paste this code: `<i class="fas fa-clock"></i>`
4. then on editor click again change mode;
5. result: tag will be removed! (because it's empty tag)

**Comment by elfalem** [comment]
This may be a hack but as of version 3.1.0, I was able to get `htmlAllowedEmptyTags: ['*']` (with no dot) to work as a wildcard.
