### ISSUE TITLE
Split up table plugin for better plugin support

### ISSUE THREAD

**Issue by petester42** [froala/wysiwyg-editor#2859]
I am trying to create something that more or less works like an excel worksheet and using the current table plugin is a real pain. There are a lot of UI features that I really don't need and have no good way of disabling (like the tableEditButtons). I would really like to have a refactor of the table plugin that would split up responsibilities like resizing cells, selecting cells, general table action (add row/column, etc), and UI (popups, toolbar buttons). This would make it much easier to build new plugins that use table.

**Comment by stefanneculai** [comment]
Thanks for the suggestion, @petester42. It is already in our plans to do that for larger plugins such as table and image. We're not keeping feature-requests here, therefore, I am marking it accordingly and closing it for now.
