### ISSUE TITLE
Froala _blank Link always opens in a new window rather than the expected "tab"

### ISSUE THREAD

**Issue by daniellevautier** [froala/wysiwyg-editor#2860]
##### Expected behavior.
When clicking on a link with target="_blank" within Froala content I expect the link to open in a new tab.

##### Actual behavior.
Link opens in a new window.

##### Steps to reproduce the problem.
https://www.froala.com/wysiwyg-editor/examples/predefined-link-list
Click on the Froala link.

##### OS.
Windows 10

##### Browser.
Chrome Latest

**Comment by stefanneculai** [comment]
Unfortunately, for the preview, we cannot open it in a new tab as Javascript doesn't allow such a behavior.
