### ISSUE TITLE
Windows: Trim whitespace from a selection before applying button action

### ISSUE THREAD

**Issue by steffenweber** [froala/wysiwyg-editor#2863]
##### Expected behavior.
Applying an action (bold, link, ...) to a word selected via double-click should ignore (trim) the automatically-selected following whitespace.

##### Actual behavior.
Applying an action (bold, link, ...) to a word selected via double-click applies it to the following whitespace, too. This is especially obvious if you apply "text-decoration: underline" to links.

##### Steps to reproduce the problem.
In a browser on a Windows computer, double-click a word in the middle of a sentence to select it. Notice that on Windows, this auto-selects the following whitespace character, too (which is by design [[1](https://superuser.com/questions/282568/is-there-a-way-to-not-select-whitespace-after-a-word-when-double-clicking)] [[2](https://answers.microsoft.com/en-us/msoffice/forum/msoffice_word-mso_other/removing-extra-space-when-selecting-words/5748b263-d2c5-4672-a343-74ad0e22fa7f?auth=1)]). So Microsoft does this to make cut/copy/paste easier. But spontaneously I cannot think of a situation where it would make sense to include this whitespace character when applying an action like bold or link. I think it should be trimmed automatically.

##### OS.
Windows

##### Browser.
For example Chrome and Firefox.

**Comment by stefanneculai** [comment]
@steffenweber Unfortunately this is a `wontfix`. The editor is designed to apply the format over to the selected text. If the OS selects the whitespace, then applying the format to that is the right way of doing it.

**Comment by steffenweber** [comment]
Please reconsider: Even Microsoft Word automatically trims whitespace when inserting a link (after using doubleclick-to-select). So the native behaviour is to select the whitespace but the native behaviour is also to trim whitespace when inserting a link etc.

**Comment by steffenweber** [comment]
@stefanneculai Please reconsider: Even Microsoft Word automatically trims whitespace when inserting a link (after using doubleclick-to-select). So the native behaviour is to select the whitespace but the native behaviour is also to trim whitespace when inserting a link etc.

**Comment by steffenweber** [comment]
@stefanneculai The dominant office app on Windows trims the selection before applying an action ([source](https://answers.microsoft.com/en-us/msoffice/forum/msoffice_word-mso_other/removing-extra-space-when-selecting-words/5748b263-d2c5-4672-a343-74ad0e22fa7f)). Its unexpected behavior if Froala behaves differently. Could you please make Froala trim whitespace, too?
