### ISSUE TITLE
can't Replace Image in Foala Editor In Firfox.

### ISSUE THREAD

**Issue by ZIqbalconsultech** [froala/wysiwyg-editor#2866]
##### Expected behavior.
(When I replace Image in Firefox instead of replacing image. It create New Image on the top of Page.)

##### Browser.
(FireFox)
 @stefanneculai

**Comment by stefanneculai** [comment]
@ZIqbalconsultech it is not happening in the latest 2.8.1 version. Please make sure that you're using this version.
