### ISSUE TITLE
Empty lines having Zero Width Space character

### ISSUE THREAD

**Issue by jemunk** [froala/wysiwyg-editor#2867]
##### Expected behavior.
Hitting enter must insert a new blank line having: `<div><br /></div>`
##### Actual behavior.
Instead inserts: `<div>&#8203;</div>` (The Zero Width Space character)
##### Steps to reproduce the problem.
Bug is observed when using this setting: keepFormatOnDelete: true
If not set, it is behaving as expected.
Is observed in Froala version 2.7.6 and 2.8.1
##### Browser.
Latest Chrome

**Comment by stefanneculai** [comment]
@jemunk while zero-width white-spaces might appear while in editing when getting the HTML from the editor by using the `html.get` method. They are being used in order to do exactly what the name of the option keepFormatOnDelete says - keeping the current format on delete. :)

**Comment by unnecessara** [comment]
New ticket related to this incident https://github.com/froala/wysiwyg-editor/issues/3822
