### ISSUE TITLE
Crashes - Cannot read property 'KEYCODE' of null

### ISSUE THREAD

**Issue by Zaltek** [froala/wysiwyg-editor#2869]
##### Expected behavior.
Froala does not crash.

##### Actual behavior.
Froala crashes. Errors:
froala_editor.2.8.1.pkgd.min.js:formatted:5322 Uncaught TypeError: Cannot read property 'COMMANDS' of null
    at froala_editor.2.8.1.pkgd.min.js:formatted:5322
Uncaught TypeError: Cannot read property 'KEYCODE' of null
froala_editor.2.8.1.pkgd.min.js:formatted:3415 
Uncaught TypeError: Cannot read property 'KEYCODE' of null
    at Object.m [as isCharacter] (froala_editor.2.8.1.pkgd.min.js:formatted:3415)
    at k (froala_editor.2.8.1.pkgd.min.js:formatted:5371)
    at dispatch (VM42 jquery-3.2.1.min.js:2)
    at q.handle (VM42 jquery-3.2.1.min.js:2)

##### Steps to reproduce the problem.
It's fairly random, but if you add an ordered list and keep adding bullets, it'll eventually break.

##### OS.
Windows 10

##### Browser.
All

**Comment by stefanneculai** [comment]
@Zaltek it appears to be a configuration problem on your side. Please reach us via https://www.froala.com/wysiwyg-editor/contact and our support team can assist you.
