### ISSUE TITLE
User-settable HTTP headers for image/document upload requests to the API

### ISSUE THREAD

**Issue by IdahoEv** [froala/wysiwyg-editor#287]
OEM license holder - license #FWE00185

Is there a way to add HTTP headers to the HTTP requests sent when uploading images and/or documents?  

We need this to ensure that uploads can only be performed by authenticated users, but the documented API only seems to support setting the URL and the query params. This is actually fairly urgent for us.

Thanks!

**Comment by boypanjaitan16** [comment]
> There is already an option for that https://editor.froala.com/options#headers
> 
> Please contact us using the contact form from our website in the future. We use this repo as a bug tracker and not for support.

hey, I follow the link you mention but there is now options about header in there
