### ISSUE TITLE
Translated correctly (pt_br)

### ISSUE THREAD

**Issue by giovanigenerali** [froala/wysiwyg-editor#2871]
https://github.com/froala/wysiwyg-editor/blob/e615e2fa407f76cca6482426cbce3567914c2912/js/languages/pt_br.js#L292-L294

```js
 "Keep": "Manter", 
 "Clean": "Limpar", 
 "Word Paste Detected": "Colar do Word detectado" 
```

**Comment by stefanneculai** [comment]
Thanks for the suggestion @giovanigenerali .
