### ISSUE TITLE
Inserting image (image.insert) causes function to go into loop

### ISSUE THREAD

**Issue by azmatzuberi** [froala/wysiwyg-editor#2872]
##### Expected behavior.
Only 1 image should be inserted when using the image.insert method

##### Actual behavior.
Endless loop of the same image being inserted using the image.insert method. I don't see why that function would be executed over and over again?

##### Steps to reproduce the problem.
The main function that gets looped over and over again: https://codepen.io/azmatzuberi/pen/vryObp
##### OS.
MacOS

##### Browser.
Chrome

##### Image
<img width="732" alt="screen shot 2018-06-07 at 4 33 35 pm" src="https://user-images.githubusercontent.com/6570598/41125505-aa88e4b2-6a72-11e8-97d4-0da9115ce5cc.png">

**Comment by stefanneculai** [comment]
@azmatzuberi it looks like you have some custom code in there. We offer tech support via https://www.froala.com/wysiwyg-editor/contact.
