### ISSUE TITLE
Pasted image data is not uploaded.

### ISSUE THREAD

**Issue by chrispadfield** [froala/wysiwyg-editor#2873]
##### Expected behavior.
Pasted image should be uploaded, not hotlinked.

##### Actual behavior.
Image is hotlinked

##### Steps to reproduce the problem.
* Copy image from a website where you need permissions to view the image (e.g. an image stored in Amazon s3 uploaded via www.notion.so).
* Paste image into froala.
* Froala will hotlink the image instead of uploading it.

##### OS.
All

##### Browser.
All

Froala seems to handle pasted images by doing a round trip via froala's servers to the URL of the image that is pasted. As well as being a potential privacy issue; this means that any image that can only be viewed by a logged in user can not be reached and froala therefore hotlinks the image instead of uploading it.

It's not clear why Froala does this. The paste event includes the data for the actual image itself as well as the URL. Froala handles pasted image data just fine (e.g. if you get an image into the clipboard using a product like Greenshot). Froala can easily take the image data pasted and use that to generate the image.

We've not found an API to change the behavior and it's caused a bit of a crisis for us. We either need to resolve this or revert to another editor we upgraded from where this "just worked". Can you advise on whether you can fix this or point us to where in the code we could fix ourselves.

**Comment by stefanneculai** [comment]
This should be fixed on the current master.
