### ISSUE TITLE
Set Code View as Default in Froala Editor

### ISSUE THREAD

**Issue by vivekssharma07** [froala/wysiwyg-editor#2877]
I want to make codeview as default view when i select froala editor.
My problem is how can i call the callback function:-
My code is below:-

$.FE.RegisterCommand('html', {
    title: 'Html View',
    undo: false,
    focus: false,
    forcedRefresh: true,
    toggle: true,
    callback: function () {
      this.codeView.toggle();
    },
    plugin: 'codeView'
  });
Now i am trying to call this callback function but i am facing trouble:-

    var editor = $('#editor').data('froala.editor');
        $.FE.RegisterCommand.callback.call(editor);

and i dont know ho in $('#editor') what should i pass ??

**Comment by vivekssharma07** [comment]
var editor = $('div').data('froala.editor');
        editor.commands.exec('html');

**Comment by YingDreamyoung** [comment]
now , do you solve it ?
