### ISSUE TITLE
<span class="rangySelectionBoundary"... in HTML

### ISSUE THREAD

**Issue by bpautsch** [froala/wysiwyg-editor#2878]
##### Expected behavior.
These weird spans are now all over the HTML after editing it. They used to never exist and now are causing small issues (e.g. CSS has span classes and the spans are breaking up words).

##### Actual behavior.
The spans are staying in the HTML.

##### Steps to reproduce the problem.
I did a Google search for rangySelectionBoundary and found it's from github "textAngular". They have an open issue where the spans aren't being removed. Sounds like the same issue.
https://github.com/textAngular/textAngular/issues/1458

I'm opening an issue here as I don't believe I'm using textAngular and assume Froala is using it in some way. I'm sure you'd like to know of any issues and resolve them. Looks like it might be an easy RegEx fix. Note: There is a special (hidden) character between the span tags.

Example HTML:
<span style="font-family: Raleway; font-size: 18px;">At age of 5, I was diagnosed with... I wanted more out of life and kept searching for happiness.<br><br>#Truth, if it wasn't for <span class="rangySelectionBoundary" id="selectionBoundary_1528472162949_41918674364777875" style="line-height: 0; display: none;">﻿</span>doTERRA<span class="rangySelectionBoundary" id="selectionBoundary_1528472162949_8727841591288004" style="line-height: 0; display: none;">﻿</span>, I’d still be bogged down by my own “problems” instead of helping people like YOU.</span>

##### OS.
Windows 8

##### Browser.
Chrome

**Comment by stefanneculai** [comment]
@bpautsch the HTML markup you're seeing there is from the [rangy lib](https://github.com/timdown/rangy). Froala Editor is not using it.
