### ISSUE TITLE
Ctrl+shift+arrow range deselection issue

### ISSUE THREAD

**Issue by celeneisip** [froala/wysiwyg-editor#2879]
##### Expected behavior.
On crtl+shift+arrow toward the opposite direction the selected words/text should be deselected before it selects the words/text(should behave similar to shift+arrow)

##### Actual behavior.
On crtl+shift+arrow toward the selected words/text arent deselected and it just select the words/text on the new directions

sample:
https://www.dropbox.com/s/fsfo7v1kfal5ims/crtl-shift-arrow-issue.mov?dl=0

##### Steps to reproduce the problem.
- In a paragraph, first do ctrl+shift+ right arrow (or ctrl+shift+ left arrow)once the the words/texts from the right side of the cursor do ctrl+shift+ left arrow

##### OS.
mac high sierra

##### Browser.
Chrome/Firefox/Safari

**Comment by stefanneculai** [comment]
This is the way the selection works by default on MacOS. Same thing happens if you try to do that in the browser URL for instance.

**Comment by RenaldasK** [comment]
> This is the way the selection works by default on MacOS. Same thing happens if you try to do that in the browser URL for instance.

That's incorrect, but you might be talking about something else. Anyway I am having the same issue as shown in the video above, but this seems to have been fixed in the latest version, so I will try upgrading.
