### ISSUE TITLE
Link Colors not working when sent to mail

### ISSUE THREAD

**Issue by ShanmugaPriyanV** [froala/wysiwyg-editor#2880]
##### Expected behavior.
I created a template that has links and applied colors (eg.red) to the link using colors tab and sent the mail to gmail using the content. The Mail content should have red colored link.

##### Actual behavior.
The Mail content appears with the standard blue color.

##### OS.
Windows 7

##### Browser.
Chrome Version 66+

**Comment by stefanneculai** [comment]
@ShanmugaPriyanV please see: https://www.froala.com/blog/wysiwyg-editor/styling-emails-with-wysiwyg-html-editors.

**Comment by ShanmugaPriyanV** [comment]
I have already specified the useClass in the js. My concern is when I apply color to link it appends a span tag and gives style to it , but in mail the color should be applied directly to the anchor tag.

**Comment by MikeMugu** [comment]
We are seeing the same problem - the link styling gets inlined in the <span> instead of within the anchor tag. This is causing Gmail/Outlook to apply their default link styling instead of the color selected by the user in the editor.

**Comment by stefanneculai** [comment]
@MikeMugu Do you think it would be possible to make a jsFiddle to highlight the problem? That would speed-up things a lot. Here is a basic jsFiddle you could use as a starting point: https://jsfiddle.net/froala/wc5c3jhk/.
