### ISSUE TITLE
Deleting 1-character table cell content deletes the whole cell

### ISSUE THREAD

**Issue by oeleo1** [froala/wysiwyg-editor#2881]
##### Expected behavior.
Deleting 1-character cell content with Backspace should delete the character

##### Actual behavior.
Deleting 1-character cell content with Backspace deletes the table cell

##### Steps to reproduce the problem.
Create a table and insert one character in a cell. Then delete the character with Backspace. 

##### OS.
Windows 64

##### Browser.
Chrome 67

**Comment by stefanneculai** [comment]
It's already fixed on the current master repo.

**Comment by oeleo1** [comment]
Thanks.  The same bug occurs for list items.  Is it fixed there too?
