### ISSUE TITLE
Spell checker crashes if .fr-box gets hidden

### ISSUE THREAD

**Issue by danielx** [froala/wysiwyg-editor#2882]
##### Expected behavior.
Spell checking should work regardless of the display property.

##### Actual behavior.
Spell checker crashes if the editor (div.fr-box) has been hidden using the display property and the editor must be destroyed and re-created for it to work again.

##### Steps to reproduce the problem.
A valid `scaytCustomerId` is required to reproduce.

[jsfiddle](https://jsfiddle.net/daniel_onlinepartner/Lptv5z1h/)
[gist](https://gist.github.com/danielx/2e6b7d81d7536cda5bf3aadc68510dcc)

##### Error.
Uncaught TypeError: o.isDisabled is not a function
    at Object.e [as refresh] (spell_checker.min.js:7)
    at s.refresh (spell_checker.min.js:7)
    at Object.refresh (froala_editor.pkgd.min.js:7)
    at froala_editor.pkgd.min.js:7

##### OS.
Ubuntu 16.04.4 LTS

##### Browser.
Google Chrome 65.0.3325.181 (Official Build) (64-bit)
Firefox 60.0.1 (64-bit)

**Comment by stefanneculai** [comment]
Unfortunately, it is a bug from SpellChecker side. We already discussed with them and a fix will be provided by them in the upcoming weeks.

**Comment by wsc-julia-shaptala** [comment]
We have just launched a new version of WebSpellChecker 5.0.1. It includes the fix for the reported issue. Try to check if everything works now (don't forget to clean your browser's cache).
