### ISSUE TITLE
Issues with sticky toolbar on iOS when scrollableContainer isn't body

### ISSUE THREAD

**Issue by felskov** [froala/wysiwyg-editor#2887]
##### Expected behavior.
If I embed the editor inside a scrollableContainer, then the sticky toolbar doesn't work as expected. The toolbar is always positioned at the top of the viewport, regardless of the position of the scrollableContainer, so if the scrollableContainer is positioned 100px further down, then the toolbar will become invisible because it's positioned too high.

##### Actual behavior.
The toolbar should be positioned at the top of the viewport OR the top of the scrollableContainer, depending on which is lowest (assuming that the toolbar is positioned on top of the editor).

##### Steps to reproduce the problem.
The issue can be reproduced with the following sample code: https://jsfiddle.net/wc5c3jhk/510/

When you put focus to the editor on iOS, the software keyboard pops up, allowing you to scroll up / down the screen. Once you've entered more text than the wrapper can contain you'll begin scrolling down within the scrollableContainer. But the toolbar will not be visible no matter how far down you scroll, unless you also scroll the body layer down, so the viewport starts at an offset lower than the scrollableContainer.

##### OS.
iOS v11.4

##### Browser.
Mobile Safari

**Comment by ilyaskarim** [comment]
Issue not reproducible on latest V4.1.
