### ISSUE TITLE
Error 4 after 'image.remove' not consistent across Editors

### ISSUE THREAD

**Issue by daviviano** [froala/wysiwyg-editor#2889]
##### Expected behavior.
My image will be removed without an error, as it is done in my other editor with the same code.

##### Actual behavior.
Upon calling the remove method, a 'Error 4 : Parsing response failed' error occurs.

##### OS.
Windows 10

##### Browser.
Chrome Version 67.0.3396.87

I have 2 editors.  My intended functionality is upon uploading a new image to the Image Manager, the image uploads to the manager, but does not load into the editor.  To get this functionality, I use the following code:
 `'froalaEditor.image.uploaded': function (e, editor, response) {
                    $('#froala-editor').froalaEditor('image.remove', editor.image.get()).delay(1000); 
                }`
Once the upload event is triggered, the image is removed.  The delay was added to make sure the image editor popup had rendered before removing the image (without it, the image loaded, was deleted, and then the image editor popup would appear after.  With the delay, both image and editor delete simultaneously.)

I have the same code on another editor, but it throws an Error 4 after a call to the remove method.  Due to the error description, I compared the responses from both editors, and both are exactly the same (as they upload to the same url location).
I also have all of the same options for both editors, so I do not think I am missing one that could be causing this issue.

**Comment by stefanneculai** [comment]
@daviviano Do you think it would be possible to make a jsFiddle to highlight the problem? That would speed-up things a lot. Here is a basic jsFiddle you could use as a starting point: https://jsfiddle.net/froala/wc5c3jhk/

**Comment by stefanneculai** [comment]
The `image.uploaded` event is triggered when the request got back from the server. The `image.error` event might still be triggered after this event in case the image fails to load.
