### ISSUE TITLE
Duplicating my <span> tags when adding links to text.

### ISSUE THREAD

**Issue by kmckinless** [froala/wysiwyg-editor#2892]
##### Expected behavior.
I use MAUTIC, a marketing automation platform.  It uses your editor which is 99% Awesome.

When adding a link to text, I expect that piece of text to be wrapped in an anchor tag.

##### Actual behavior.
When adding a link to text it is duplicating my previous SPAN tag and wrapping my linked text in BOTH SPAN AND ANCHOR tags.

##### Steps to reproduce the problem.
1. Select Text in Mautic Builder.
2. Add link.
3. Look at source file.  Span has been wrapped around the Anchor tag.

##### OS.
Any OS.

##### Browser.
Any browser.

IMPORTANT NOTE: I have to use Span tags in HTML Emails in order to maintain styling across the vast number of email clients.  I can't use standard tags (h1, p, etc) because they are sometimes controlled by the email client themselves and have been difficult to override.

Images:
<img width="1918" alt="screen shot 2018-06-18 at 16 37 53" src="https://user-images.githubusercontent.com/36159832/41546775-6b78f922-7316-11e8-99fd-6884bb15b9ba.png">
<img width="1918" alt="screen shot 2018-06-18 at 16 38 07" src="https://user-images.githubusercontent.com/36159832/41546774-6b48c7de-7316-11e8-850d-cf540f885123.png">
<img width="1912" alt="screen shot 2018-06-18 at 16 38 37" src="https://user-images.githubusercontent.com/36159832/41546772-6b147ed4-7316-11e8-8a54-4a07dc8e8b7d.png">

**Comment by stefanneculai** [comment]
Do you think it would be possible to make a jsFiddle to highlight the problem? That would speed-up things a lot. Here is a basic jsFiddle you could use as a starting point: https://jsfiddle.net/froala/wc5c3jhk/.

**Comment by kmckinless** [comment]
Cool.  Thanks for getting back.  I put the span (including text) in there.

Please add a "link" to any of the text.  See that it duplicated the span around the test you've selected followed by an <a> tag.

If you allow the "CODE VIEW" feature on your WYSIWYG editor in the fiddle you'll see what I mean.  The Mautic iteration of your editor has a "CODE VIEW" option.  That's how I know it's duplicating my Span.

https://jsfiddle.net/wc5c3jhk/713/

**Comment by kmckinless** [comment]
Hi folks,

Did you receive my details ok?

Thanks
Kevin.

**Comment by stefanneculai** [comment]
Thanks for the details @kmckinless. We checked it further and the editor is designed to split SPAN tags and place links outside of them. This helps in properly maintaining the way colors and other font styles are set.

**Comment by kmckinless** [comment]
Cool Stefan.  That's up to you guys.  It doesn't do this with any other tag AND if when you do add it to another tag such a <p> it just wraps the text in an anchor tag.  REALLY, the function should be exactly the same because the parent tag would contain the main CSS and the anchor tag could be styled afterwards.  It seems odd to me. 

Apart from that, GREAT editor btw.  Best one I've used in years.

**Comment by stefanneculai** [comment]
We're doing it like this because in case we'd wrap the A tag with a span, you might end up selecting like red color and that wouldn't apply for links because you might have a CSS rule on the page which says that links should be blue.
