### ISSUE TITLE
(Enhancement request) Need to specify a URL to pull web content to display/edit

### ISSUE THREAD

**Issue by jinq102030** [froala/wysiwyg-editor#2893]
##### Expected behavior.
Be able to configure Froala editor to take URL instead of web content.  The idea is for Froala editor to pull content/HTML directly from a URL, this makes is much easier to specify links for resources (images/css)

##### Actual behavior.
We can only configure Froala with html content.

##### Steps to reproduce the problem.
N/A because it's enhancement request

##### OS.
all

##### Browser.
all

**Comment by stefanneculai** [comment]
Thanks for the `feature-request`, @jinq102030 .
