### ISSUE TITLE
Validation in image resize modal

### ISSUE THREAD

**Issue by cygwin255** [froala/wysiwyg-editor#2894]
Q: Is there a way to add a validation to resize modal?

##### Expected behavior.
User should not be able to set invalid width or height values.

##### Actual behavior.
There is no validation in image resize modal.

##### Steps to reproduce the problem.
1. Insert an image
2. Open resize modal
3. Enter some invalid values
4. Observe

**Comment by stefanneculai** [comment]
@cygwin255 thanks for the `feature-request`. We don't have at this moment such a feature.
