### ISSUE TITLE
Table jsFiddle not opening on Internet Explorer

### ISSUE THREAD

**Issue by dgroh** [froala/wysiwyg-editor#2895]
##### Expected behavior.
I want to be able to check the jsFiddle provided by Froala team on Internet Explorer:

https://jsfiddle.net/froala/r38jwxbn/

##### Actual behavior.
The link works on Chrome tho.

##### Steps to reproduce the problem.
(Describe the steps to reproduce the problem here. A [jsFiddle](https://jsfiddle.net/froala/wc5c3jhk/) is awesome when possible.)

##### OS.
(OS name and version here)

##### Browser.
(Browser name an version here)

**Comment by stefanneculai** [comment]
Looks like a problem from jsFiddle, not from us. 

<img width="1360" alt="screen shot 2018-07-12 at 14 19 16" src="https://user-images.githubusercontent.com/637004/42630205-9ebcfbfa-85de-11e8-9b4f-596f721430ca.png">
