### ISSUE TITLE
Froala editor jumps down by pressing backspace

### ISSUE THREAD

**Issue by angelvazquezmenendez87** [froala/wysiwyg-editor#2896]
##### Expected behavior.
By pressing "Enter" or "Backspace" the user should be able to continue to see the position of the cursor.

##### Actual behavior.
By pressing "Enter" or "Backspace" the editor scrolls down.

##### Steps to reproduce the problem.
Just use this fiddle:
https://jsfiddle.net/wc5c3jhk/735/

Also see the attached gif.
![froala editor jumps down by pressing backspace](https://user-images.githubusercontent.com/16782281/41666183-e310c778-7477-11e8-8d16-cd687c4547c8.gif)

##### OS.
Windows 10 and Server

##### Browser.
Chrome (last version)

**Comment by Trapdafifou** [comment]
Got the same issue any ETA for the 2.8.6 ?

**Comment by stefanneculai** [comment]
We don't set specific dates for a release, but we do them based on the features ready to be done and bugs which should be fixed. Most likely, it would be around the end of September.

**Comment by angelvazquezmenendez87** [comment]
I did some tests and it looks good, thanks.
