### ISSUE TITLE
Table cells selection not working on IE 11 when toolbarInline is true

### ISSUE THREAD

**Issue by dgroh** [froala/wysiwyg-editor#2898]
##### Expected behavior.
I want to be able to select cells on **IE 11** when `toolbarInline` is true

##### Actual behavior.
When you select multiple cells and rows and leave the mouse pointer and select multiple cells and rows  again, it seems like Froala breaks and no action can be made

##### Steps to reproduce the problem.
1. Open IE 11 with Froala editor
2. Add a table with several cells and rows to it
3. Set `toolbarInline` to **true**
3. Select cells and rows and release the mouse pointer
4. Try selecting cells and rows again, Froala should break

##### OS.
(OS name and version here)

##### Browser.
(Browser name an version here)

**Comment by stefanneculai** [comment]
@dgroh could you please check with the latest 2.8.4 version?

**Comment by dgroh** [comment]
Yes, we are facing other issues here and as soon they are fixed we will test with `2.8.4`. I give a feedback in the next days.

**Comment by dgroh** [comment]
This is fixed with 2.8.4
