### ISSUE TITLE
v2.8.2 breaks when fullPage: true

### ISSUE THREAD

**Issue by bpautsch** [froala/wysiwyg-editor#2899]
Today's release of v2.8.2 doesn't work when "fullPage: true".
I confirmed rolling the code back to v2.8.1 works.
I narrowed the issue down to setting "fullPage: true".
The editor will not render at all and any clicking in the area generates more and more errors.

Javascript error:
Uncaught TypeError: Cannot read property 'refresh' of undefined
    at Object.get (froala_editor.min.js?v=2.8.2:7)
    at Object._init (froala_editor.min.js?v=2.8.2:7)
    at r.Bootstrap.load (froala_editor.min.js?v=2.8.2:7)
    at r.Bootstrap.a (froala_editor.min.js?v=2.8.2:7)

I also receive error:
GET https://svc.webspellchecker.net/spellcheck31/lf/scayt3/customscayt/css/scayt.css 404 ()

**Comment by stefanneculai** [comment]
@bpautsch Do you think it would be possible to make a jsFiddle to highlight the problem? That would speed-up things a lot. Here is a basic jsFiddle you could use as a starting point: https://jsfiddle.net/froala/wc5c3jhk/.

**Comment by bpautsch** [comment]
Absolutely. Give me an hour.

**Comment by bpautsch** [comment]
OK...it's even more specific than I originally mentioned. To replicate, the froala field must be something other than a div (I use textareas) + content must be loaded + full page = true.

<textarea id="froala-editor">
    Sample content...
</textarea>

$('#froala-editor').froalaEditor({
	fullPage: true,
});

![jsfiddle-example](https://user-images.githubusercontent.com/2838210/41729895-1325beaa-7540-11e8-83f9-80a085d97739.JPG)

**Comment by stefanneculai** [comment]
Thanks for the details @bpautsch it is fixed on the current master.
