### ISSUE TITLE
webpack build error with 2.8.2

### ISSUE THREAD

**Issue by bboyle** [froala/wysiwyg-editor#2900]
##### Expected behavior.
Our webpack build compiles without issue using froala-editor v2.8.1

##### Actual behavior.
npm automatically installed v2.8.2 and we started seeing this build errors:

```
ERROR in ./node_modules/froala-editor/js/plugins/code_beautifier.min.js
Module not found: Error: Can't resolve 'FroalaEditor' in './node_modules/froala-editor/js/plugins'
 @ ./node_modules/froala-editor/js/plugins/code_beautifier.min.js 7:70-93
```
This is repeated for each plugin we use.

##### Steps to reproduce the problem.
Try to compile froala-editor plugins on v2.8.2.
(Did something change in the way plugins reference the main editor?)

##### OS.
Issue has occurred on windows and linux.
node 8.9.1
npm 6.1.0
webpack 3.12.0

##### Browser.
Not applicable.

**Comment by stefanneculai** [comment]
Yes, there were some changes in the way we made the build. Let us check what is happening there.
