### ISSUE TITLE
froalaEditor.save.after event broken in v2.8.2 and v2.8.3

### ISSUE THREAD

**Issue by seb303** [froala/wysiwyg-editor#2901]
##### Expected behavior.
.on('froalaEditor.save.after', function (e, editor, data) {
data should contain an object from the JSON response
This is the behaviour in v2.8.1 and earlier

##### Actual behavior.
data contains JSON string instead of object
This is despite AJAX file returning correct application/json content type

##### Steps to reproduce the problem.
(Describe the steps to reproduce the problem here. A [jsFiddle](https://jsfiddle.net/froala/wc5c3jhk/) is awesome when possible.)
.on('froalaEditor.save.after', function (e, editor, data) {
	console.log(typeof data);
	console.log(data);
}

##### OS.
Windows 8.1 64bit

##### Browser.
Firefox 60.0.2

**Comment by dgroh** [comment]
Is it possible to see list of Breaking Changes somewhere? breaking changes in minor is critical IMO.

We also had problems trying to update to 2.8.2 and had to rollback to 2.8.1, this was the error we were having:

> Uncaught TypeError: Cannot read property 'areVisible' of undefined
>     at i (froala_editor.pkgd.min.js?cdv=180:7)
>     at r.Bootstrap.<anonymous> (froala_editor.pkgd.min.js?cdv=180:7)
>     at u (froala_editor.pkgd.min.js?cdv=180:7)
>     at HTMLDivElement.<anonymous> (froala_editor.pkgd.min.js?cdv=180:7)
>     at HTMLDivElement.dispatch (jquery.js?cdv=180:3074)
>     at HTMLDivElement.elemData.handle (jquery.js?cdv=180:2750)

**Comment by seb303** [comment]
Another related issue is that objects in editor.opts.saveParams are not correctly converted to JSON representation in the save POST request.  Objects just come out as a string "object" rather than the JSON.

In summary: v2.8.2 (and v2.8.3) completely breaks our application.  Seems to be more a beta release than well tested production code.

**Comment by seb303** [comment]
Sure...
{
	key: 'xxxx',
	
	charCounterCount: false,
	theme: 'custom',
	
	enter: $.FroalaEditor.ENTER_DIV,
	useClasses: false,
	pasteDeniedAttrs: ['class', 'id', 'style', 'tabindex', 'lang'],
	pasteDeniedTags: ['mark'],
	
	pluginsEnabled: ['customPlugin', 'align', 'codeBeautifier', 'codeView', 'colors', 'draggable', 'entities', 'file', 'fontFamily', 'fontSize', 'help', 'image', 'inlineStyle', 'lineBreaker', 'link', 'lists', 'paragraphFormat', 'paragraphStyle', 'quote', 'save', 'table', 'url', 'video', 'wordPaste'],
	
	toolbarButtons: toolbarButtonsExtras,
	toolbarButtonsMD: toolbarButtonsExtras,
	toolbarButtonsSM: toolbarButtons,
	toolbarButtonsXS: toolbarButtons,
	quickInsertTags: [],
	
	paragraphFormat: {
		N: 'Normal',
		H1: 'Heading 1',
		H2: 'Heading 2',
		H3: 'Heading 3',
		PRE: 'Code'
	},
	
	linkList: [],
	linkInsertButtons: ['linkBack'],
	linkEditButtons: ['linkOpen', 'linkEdit', 'linkRemove'],
	
	imageInsertButtons: ['imageBack', '|', 'imageUpload', 'imageByURL'],
	imageDefaultAlign: 'left',
	imageDefaultWidth: 0,
	
	imageUploadURL: '/ajax/upload_file.php',
	imageUploadParams: {disposition: 'inline'},
	imageMaxSize: 1024*1024*10,
	
	fileUploadURL: '/ajax/upload_file.php',
	fileUploadParams: {disposition: 'attachment'},
	imageMaxSize: 1024*1024*10,
	
	saveURL: '/ajax/send_message.php',
	saveParams: {threadid:threadid, messageid:messageid, rel:rel, s:localStorage.getItem('indexStatus')},
	saveInterval: 0,
	
}

**Comment by stefanneculai** [comment]
@seb303 we just tested it and the saveParams appears to be sent correctly  - see the picture below. 

Regarding the response, we've started a more extending process of getting rid of jQuery and now all requests are made without jQuery, therefore, indeed the response is not converted to a hash, but it is the raw response. To convert it to a JSON, you could use `JSON.parse(response)`.

<img width="433" alt="screen shot 2018-06-21 at 15 03 49" src="https://user-images.githubusercontent.com/637004/41718025-5630dd3c-7564-11e8-9952-48fb579d388b.png">

**Comment by stefanneculai** [comment]
@dgroh Do you think it would be possible to make a jsFiddle to highlight the problem? That would speed-up things a lot. Here is a basic jsFiddle you could use as a starting point: https://jsfiddle.net/froala/wc5c3jhk/.

**Comment by seb303** [comment]
@stefanneculai 
It should not be up to the user of your library to do additional conversions.  It makes no sense for the library user to work with JSON strings rather than actual objects.

If an object is set in editor.opts.saveParams  it should be sent to the browser as JSON, and when a JSON response is received it should be returned in the callback as an object.

This is how it has always worked up to v2.8.1
Why would you introduce a change that breaks backwards compatibility in a minor version release?

**Comment by seb303** [comment]
@stefanneculai 
Regarding saveParams being sent correctly - this works with string values, but not if there is an object.

We are setting additional saveParams before the data is submitted.
e.g.
```
.on('froalaEditor.save.before', function (e, editor, html) {
editor.opts.saveParams.test = {param1: 'x', param2: 'y'}
}
```

**Comment by stefanneculai** [comment]
I agree with you that maybe this should have been done in a release such as 2.9.0, however, at this moment it is too late to make such change because the release was already published on NPM and other places. It was a mistake on our side, we're learning from it, and next time will be better. 🙏 

The data set to `saveParams` is sent in the body of the request. This is how the requests work for image, file and video from the very first version (and the same thing applies for the response). This last release just makes the saveParams consistent with the other params. I understand that this might break the behavior in your app, however, for now, the best approach would be to either keep using the version 2.8.1 or update to 2.8.3 and make some changes in your app.

**Comment by seb303** [comment]
@stefanneculai 
If you are pushing changes that will require workarounds/fixes in the apps using the library, I would strongly request that you publish details of such changes in a prominent place so that the necessary steps can be taken when upgrading.  You would save your paying users a lot of headaches by doing this.

Once you have published a full list of such changes, could you please respond with a link so that we can look at what we need to do to update our app.

Thanks,
Seb

**Comment by stefanneculai** [comment]
Every time we do a release, we send an email with the changes to everyone who is subscribed to editor updates: https://www.froala.com/wysiwyg-editor/download#updates. Please make sure you are on the list so that you get such updates. 

Also, we try to keep a full list of changes on the Changelog: https://www.froala.com/wysiwyg-editor/changelog. While it is not always possible to list there all the changes, the most important ones should be highlighted. 

Thanks for all your feedback once again. It will for sure help us do better!

**Comment by seb303** [comment]
@stefanneculai 
Yes, I receive these email updates. and I also read the changelog before installing the new version of the library.  But nowhere did it state that there were changes which would break backwards compatibility.

I saw that one of the changes is "Use XHR requests instead of jQuery AJAX" but this doesn't suggest to me that the library will behave differently.  After all, jQuery AJAX also uses XHR requests.

So I ask again: where can we check if a new version of your library will require workarounds/fixes in the apps using it?  Surely this is important information to include in your changelog?

**Comment by seb303** [comment]
@stefanneculai 
I hear you that you didn't foresee that these latest changes would break backwards compatibility.  But now that I have reported the issue, could you please assess exactly which functions and callbacks have been affected.  These breaks in backwards compatibility could then be described in your changelog, so that we and others can know what changes are needed throughout our applications if we want to update past v2.8.1
That's all I'm asking.  I don't think it's an unreasonable request :)

**Comment by stefanneculai** [comment]
As far as we know, there shouldn’t be any other events affected. I apologize again for the troubles it created.
