### ISSUE TITLE
After undo.saveStep, undo.canDo returns false

### ISSUE THREAD

**Issue by ConnorsFan** [froala/wysiwyg-editor#2905]
##### Expected behavior.
After starting the editor and executing undo.saveStep, the undo list should contain one item, and undo.canDo should return true.

##### Actual behavior.
After executing undo.saveStep, checking the undo list with undo.canDo returns false.

##### Steps to reproduce the problem.
1. Start the Froala editor 
2. Before making any change to the existing text, call undo.saveStep
3. Call undo.canDo, and see that it returns false
4. Call undo.saveStep again
5. Call undo.canDo, and see that now it returns true

##### OS.
Windows 7

##### Browser.
Chrome 67, Firefox 60

**Comment by stefanneculai** [comment]
@ConnorsFan that is the correct behavior. The `undo.saveStep` method is designed to store a new snapshot in the undo stack only when the last snapshot is different.

**Comment by ConnorsFan** [comment]
I don't understand. I want to do some custom formatting that is not provided by Froala (e.g. change the line height in a paragraph), and allow the user to undo that change. How should I proceed? I thought that I could save a snapshot in the undo stack before doing the change, but the snapshot is not saved.

You say that the snapshot is saved only when different. Different from what? If I try to save a snapshot, it is not saved on the first try, but it is on the second try. That second snapshot is not different from the first one.

**Comment by stefanneculai** [comment]
As per my understanding, you are calling `undo.saveStep` before making any change in the editor after it is being loaded. Therefore, when you call the method in the editor there is already a first step which is exactly the first state of the loaded HTML.

**Comment by ConnorsFan** [comment]
It works. Thanks!
