### ISSUE TITLE
angular froala occur error

### ISSUE THREAD

**Issue by Vnthf** [froala/wysiwyg-editor#2906]
##### Expected behavior.
In froala version 8.3,

angular-froala occur error.

angular.js:14199 Error: Method node.isEmpty does not exist in Froala Editor.
```
   ngModel.$isEmpty = function (value) {
                    if (!value) {
                        return true;
                    }

                    var isEmpty = element.froalaEditor('node.isEmpty', jQuery('<div>' + value + '</div>').get(0));
                    return isEmpty;
                };
```
##### Actual behavior.
(Describe actual behaviour here)

##### Steps to reproduce the problem.
(Describe the steps to reproduce the problem here. A [jsFiddle](https://jsfiddle.net/froala/wc5c3jhk/) is awesome when possible.)

##### OS.
mac

##### Browser.
chrome

**Comment by stefanneculai** [comment]
Could you please open this issue on the Angular repo instead? Thanks.

**Comment by Vnthf** [comment]
@stefanneculai 
I think the responsibility of this bug is in froala. In the change initialization process of this 8.2 version, the editor instance is replaced with the editor bootstrap instance, and most editor methods are disabled like `element.froalaEditor('html.get'), element.froalaEditor('node.isEmpty')`

**Comment by Vnthf** [comment]
@stefanneculai Please tell me how to solve it. It is a very urgent issue because of https://github.com/froala/wysiwyg-editor/issues/2771
