### ISSUE TITLE
Cannot specify S3 domain in order to point to DigitalOcean Spaces instead of AWS.

### ISSUE THREAD

**Issue by shinzenkoru** [froala/wysiwyg-editor#2908]
##### Expected behavior.
Directly upload to DigitalOcean Spaces (interoperable with Amazon's AWS S3 API).

##### Actual behavior.
Still upload to Amazon domain.

##### Steps to reproduce the problem.
1. Set imageUploadToS3 with DigitalOcean Spaces options (bucket, region, keyStart, acl, accessKey, and secretKey)
2. Upload the image with Froala Editor

##### OS.
macOS High Sierra Version 10.13.5

##### Browser.
Google Chrome Version 67.0.3396.87

**Comment by stefanneculai** [comment]
@shinzenkoru at this moment we have only AWS S3 built-in integration. I marked this as a feature request for now.

In the meanwhile, I would recommend to upload images to your server and from there to the Digital Ocean Spaces.

**Comment by shinzenkoru** [comment]
@stefanneculai Thank you very much!

**Comment by stefanneculai** [comment]
We've just put together a public roadmap with the most popular features. 😍 There you can vote your favorite one, provide feedback or make new suggestions: https://wysiwyg-editor-roadmap.froala.com/public.
