### ISSUE TITLE
Table Style Popup is being shown at wrong place

### ISSUE THREAD

**Issue by szaib1986** [froala/wysiwyg-editor#2911]
If you create a table and press some 'Enter Keys' so that scroll bar appears in the Editor, after that If you click on a cell, the popup that appears is not being positioned correctly. Also, popup always appear on the bottom of TD, so if we have last cell and popup will appear at the bottom, user can't see it.

**Comment by stefanneculai** [comment]
@szaib1986  Do you think it would be possible to make a jsFiddle to highlight the problem? That would speed-up things a lot. Here is a basic jsFiddle you could use as a starting point: https://jsfiddle.net/froala/wc5c3jhk/.

**Comment by stefanneculai** [comment]
Closing this due to lack of response.
