### ISSUE TITLE
Adding an image using ENTER_BR remove the next line break tag

### ISSUE THREAD

**Issue by cauethenorio** [froala/wysiwyg-editor#2912]
##### Expected behavior.
After uploading images, the document line breaks will be kept

##### Actual behavior.
when using `ENTER_BR` as `enter` option, when you upload an image (dropping it, adding by url or picking a file from your local system), once the image is loaded the next `BR` is removed

##### Steps to reproduce the problem.
1. Open the `ENTER key` demos page:
https://www.froala.com/wysiwyg-editor/examples/enter

2. Add a text with several lines to the third demo (the `ENTER_BR` one), like this:
```
line 1

line 2
line 3
line 4
```
3. Put the cursor to the empty line and upload some image
4. After image load the final content will be:
```
line 1
[image]
line 2line 3
line 4
```

##### OS.
OSX 10.11 and Windows 10

##### Browser.
Chrome 65

**Comment by stefanneculai** [comment]
It's fixed on the current master.

**Comment by joostbaptist** [comment]
It's still happening in Froala 2.9.1.
