### ISSUE TITLE
Table dropping empty cells and causing inconsistent views.

### ISSUE THREAD

**Issue by sfescape** [froala/wysiwyg-editor#2914]
##### Expected behavior.
The displayed html should always match the codeview.
Table cells should never be removed unless deleted.

##### Actual behavior.
If you empty a table cell in the editor, it ends up getting removed from the html. Additionally the editor doesn't reflect that behavior until another event (like a switch to codeview and back).

##### Steps to reproduce the problem.
1) Create a 2 column single row table
2) update the cell values to some text (such as "test")
3) highlight and remove the entered text from the first cell
4) Observe you see 2 columns, the first empty and the second with "test"
5) Switch to codeview
6) Observe you see 1 column populated with "test"
7) Switch to editor
8) Observe you see 1 column populated with "test"

It appears that tables are created by default populated with <br>. If you enter text and then remove it, the <br> is also removed rendering the cell empty. Empty cells are automatically cleaned out of the html at some point later.

##### OS.
MAC Sierra
##### Browser.
Chrome Version 67.0.3396.87 (Official Build) (64-bit)

**Comment by dgroh** [comment]
I can confirm this bug. What is your Froala version? Ours is 2.8.1

**Comment by sfescape** [comment]
2.8.4

**Comment by sfescape** [comment]
Looks like I was actually using 2.8.3. I upgraded to 2.8.4 and it's working correctly now.
