### ISSUE TITLE
Popups with overflow: auto/scroll and a max-height are not scrollable on mobile devices

### ISSUE THREAD

**Issue by chrisdeeming** [froala/wysiwyg-editor#2917]
##### Expected behavior.
Popup contents should be scrollable.

##### Actual behavior.
Popup contents are not scrollable.

##### Steps to reproduce the problem.
Here's a fork of the custom popup example, where the popup content spans over 100px which is the max-height and overflow: auto is applied.

https://jsfiddle.net/chrisxf/msu91950/168/

Seems to be on touch devices only.

My suspicion is the code responsible is whatever prevents scrolling on touch devices when the touch start begins on the toolbar.

##### OS.
Any mobile.

##### Browser.
Any mobile.

**Comment by chrisdeeming** [comment]
If there's any known workarounds for this, that can be applied to the scrollable element, that'd be appreciated.

**Comment by stefanneculai** [comment]
@chrisdeeming at this moment, the popups were not designed to have scrollable content inside them. They are designed to be helpers for the UX and we don't expect to have scroll inside there. Unfortunately, we won't add such a feature.
