### ISSUE TITLE
Incorrect focus change after select operation from table popup (IE browser)

### ISSUE THREAD

**Issue by tokarkry** [froala/wysiwyg-editor#2918]
##### Expected behavior.
Always after select opration from table popup this operation should be done and focus should stay in this table (table row)

##### Actual behavior.
Sometimes after select operation from table popup the focus is changes to bottom of email (and scrolls to it). This behaviour is when editor has scrollbar and is open in Internet Explorer browser

##### Steps to reproduce the problem.
1.Open Froala wysiwyg editor in IE browser
2. Add quite long email content to editor which have max height properties (this content should add scrollbar to Froala editor)
3. Add table with some rows.
4. Try to change this table by table popups (like insert columns or rows)

##### OS.
Windows 7.

##### Browser.
Internet Explorer 11, Version: 10.0.9600.19002

**Comment by stefanneculai** [comment]
@tokarkry Do you think it would be possible to make a jsFiddle to highlight the problem? That would speed-up things a lot. Here is a basic jsFiddle you could use as a starting point: https://jsfiddle.net/froala/wc5c3jhk/.

**Comment by stefanneculai** [comment]
Closing this due to lack of response from user.
