### ISSUE TITLE
Not visible which rows is selected after selected them by keyboard (IE browser)

### ISSUE THREAD

**Issue by tokarkry** [froala/wysiwyg-editor#2919]
##### Expected behavior.
After selecting a row in added table and try to select more than one of them (by keyboard) user should see which of them are selected or focused.

##### Actual behavior.
After selecting a row in added table and try to select more than one of them (by keyboard) user cannot see which of them are selected or focused.

##### Steps to reproduce the problem.
1. Add new table to Froala editor in Internet Explorer browser.
2.Select first (or another) row in this table by keyboard (not by mouse clicking)
3.Try to select few row (using Shift + arrowkey)

##### OS.
Windows 7.

##### Browser.
Internet Explorer 11, Version: 10.0.9600.19002

**Comment by stefanneculai** [comment]
Closing this due to lack of response from user.
