### ISSUE TITLE
It is not possible to remove or add row before added table (IE browser)

### ISSUE THREAD

**Issue by tokarkry** [froala/wysiwyg-editor#2922]
##### Expected behavior.
If in editor exist row before added table then is possible to removed it using "Delete" key. Additionally it is possible to add new line before table if table is first in email content. This behavior is when table row is selected and it has focus.

##### Actual behavior.
If in editor exist row before added table then is impossible possible to removed them using "Delete" or any keys in keyboard. Additionally it is impossible to add new line before table if table is first in email content. This behavior is when table row is selected and it has focus.

##### Steps to reproduce the problem.
1. Add new empty line in Froala Editor in Internet Explorer browser
2. Add new table with rows. (the focus is in this table row)
3. Try to remove empty line before table
--------------------------------
1. Add new table to empty email content.
2. Try to create new line before added table

##### OS.
Windows 7.

##### Browser.
Internet Explorer 11, Version: 10.0.9600.19002

**Comment by stefanneculai** [comment]
Unfortunately, the browsers do not allow the best editing support for empty lines next to tables. At this moment, the behavior that is there in place is the best we can provide.
