### ISSUE TITLE
It is not possible to add row after added table (IE browser)

### ISSUE THREAD

**Issue by tokarkry** [froala/wysiwyg-editor#2923]
##### Expected behavior.
If in editor not exist any rows after added table then is possible to add new line after table if table is the last "thing" in email content. This behavior is when table row is selected and it has focus.

##### Actual behavior.
If in editor not exist any rows after added table then is impossible to add new line after table if table is the last "thing" in email content. This behavior is when table row is selected and it has focus.

##### Steps to reproduce the problem.
1. Add new table with rows in empty Froala editor or in the bottom of email content. (the focus is in this table row) in Internet Explorer browser
2. Try to add new line after table
--------------------------------

##### OS.
Windows 7.

##### Browser.
Internet Explorer 11, Version: 10.0.9600.19002

**Comment by stefanneculai** [comment]
@tokarkry for this we have the line breaker tool which we'd suggest to use.

<img width="1279" alt="screen shot 2018-07-05 at 14 48 35" src="https://user-images.githubusercontent.com/637004/42321696-89179296-8062-11e8-8c01-4c2effc417f8.png">
