### ISSUE TITLE
Use froala editor with images doesn't work in angular 5 projects

### ISSUE THREAD

**Issue by bindea-mihai** [froala/wysiwyg-editor#2927]
##### Expected behavior.
Use Froala Editor on images, after updating to version 2.8.4 should work in angular 5 projects.

##### Actual behavior.
When using the editor on an image element in an angular 5 project the image doesn't load. It used to work when using the editor in version 2.7.3

##### Steps to reproduce the problem.

1. Follow the tutorial for using the editor with webpack like presented in the link below:
https://www.froala.com/wysiwyg-editor/docs/framework-plugins/angularjs-2-4#use-with-webpack
2. Use Froala editor on an image element like presented in the same link under the special tags section
<img [froalaEditor] [(froalaModel)]="imgObj"/>
and declare a public object with the src property like below (of course use a valid link to an image):
public imgObj: Object = {
  src: 'path/to/image.jpg'
};
3. When the page loads the image doesn't load.

##### OS.
Windows 10 Enterprise v 1803

##### Browser.
Chrome 67.0.3396.99
Firefox 60.0.2

**Comment by stefanneculai** [comment]
@bindea-mihai could you please open this issue in the angular repo (https://github.com/froala/angular-froala-wysiwyg)?
