### ISSUE TITLE
Font not changing 

### ISSUE THREAD

**Issue by me12722** [froala/wysiwyg-editor#2928]
When I change the font or the font size I should see the font or font size change; 
in the html i should see something like this go from:
 `<div style="font-family: sans-serif; font-size: 13px;"> Text Inside the div </div>`

To: 
 `<div style="font-family: sans-serif; font-size: 13px;"> <span style="font-family: Comic-sans; font-size: 12px;" >Text Inside the div </span></div>`

##### Actual behavior.
What I'm actually getting is:
`<span style="font-family: Comic-sans; font-size: 12px;" ><div style="font-family: sans-serif; font-size: 13px;"> Text Inside the div </div></span>`

Because the span is wrapping around the div the styles don't change. 
##### Steps to reproduce the problem.
This problem is intermittent so it's hard to say. I am sure of the expected behavior because I have seen it on other non-buggy instances of my editor. 

##### OS.
Mac OSX

##### Browser.
Chrome

**Comment by stefanneculai** [comment]
@me12722 it looks like you have some specific options changed in the default editor configuration. If you could create a jsFiddle where we can reproduce this, we would be happy to look into it. Without having a way to reproduce it, we cannot really do too much. 

Do you think it would be possible to make a jsFiddle to highlight the problem? That would speed-up things a lot. Here is a basic jsFiddle you could use as a starting point: https://jsfiddle.net/froala/wc5c3jhk/.

**Comment by stefanneculai** [comment]
@me12722 we checked this again. I believe that you either changed the default editor options in a specific way or you are using an older version than 2.8.4.
