### ISSUE TITLE
Trigger event on new paragraph

### ISSUE THREAD

**Issue by Khrystyna** [froala/wysiwyg-editor#293]
Could you please tell me if it's possible to trigger event when new paragraph is added (by pressing Enter key)? Maybe I am missing this in spec.

**Comment by mtuan94** [comment]
could u tell me how to get the content of paragraph before hit enter

**Comment by stefanneculai** [comment]
@mtuan94 you could listen to the keydown event like this and take the editor content before enter.
```js
$(selector).on('froalaEditor.initialized', function (e, editor) {
  editor.events.on('keydown', function (e, editor) {
    // editor.$el.html()
  }, true);
});
