### ISSUE TITLE
Pasting an image copied from the froala editor doesn't trigger the image.beforeUpload event

### ISSUE THREAD

**Issue by fflfi** [froala/wysiwyg-editor#2930]
**Expected behavior**
Copying an image from one froala editor to another one should trigger the beforeUpload event.

**Actual behavior**
Copying an image from one froala editor to another doesn't trigger the beforeUpload event.
Issue occures in version 2.8.4

**Steps to reproduce the problem**

If I paste an image from one froala editor to another froala editor the event is not triggered. If I paste it from another source everything is working as expected.

It looks like it happens because if you copy an image from the editor its stored as HTML, so the editor doesnt recognize it as an image if you paste it again.

OS.
W10

Browser.
Chrome/Chromium

**Comment by stefanneculai** [comment]
@fflfi could you please make sure that you're using the latest 2.8.4 version. We cannot reproduce it here: https://jsfiddle.net/froala/wc5c3jhk/884/.

**Comment by fflfi** [comment]
@stefanneculai It happens when you use the method with 3 parameters.
I updated your jsfiddle:
https://jsfiddle.net/wc5c3jhk/887/
