### ISSUE TITLE
Image upload to Amazon S3 broken since Froala 2.8.2

### ISSUE THREAD

**Issue by kreintjes** [froala/wysiwyg-editor#2931]
##### Expected behavior.
When I configure Froala to upload images to Amazon S3, by initializing the editor with the `imageUploadToS3` option (with data provided by the Ruby FroalaEditorSDK::S3.data_hash method), then I expect the images to be uploaded to Amazon S3 and include a URL to S3. Just as it did before Froala 2.8.2.

##### Actual behavior.
The image gets uploaded to local storage and the URL is something like "blob:http://localhost:3000/0d562d4e-e14d-6f42-86d5-60c6feb2baa4".

##### Steps to reproduce the problem.
Install Froala 2.8.2 or higher (tested in 2.8.4 which is the newest version at time of writing) and initialize an editor with valid `imageUploadToS3` option. Then try to uplaod and image and view the S3 bucket as well as the URL in the img src.

##### OS.
MacOs 10.13.4

##### Browser.
Mozilla Firefox 60.0.2. Problem occurs in Chrome 67.0.3396.99 as well.

**Comment by kreintjes** [comment]
The problem can be fixed by explicitly disabling the imageUploadUrl when initializing the editor (i.e. passing `imageUploadURL: false`), but this feels a bit double when already stating we want images uploaded to S3 and wasn't necessary before.

Problem is probably caused by the "Images are uploaded to a local blob instead of i.froala.com by default." change since version 2.8.2.

**Comment by ilamarang** [comment]
im able to replicate the same issue as well.

**Comment by stefanneculai** [comment]
As a temporary workaround, please pass `imageUploadURL: 'https://i.froala.com/upload?i=1` when uploading to S3.
