### ISSUE TITLE
Pressing Enter inside a Div creates a new Div instead of a P tag

### ISSUE THREAD

**Issue by SeanKendle** [froala/wysiwyg-editor#2933]
##### Expected behavior.
Pressing enter in a Div should create a new P tag.

##### Actual behavior.
Pressing enter in a Div creates another div

##### Steps to reproduce the problem.

copy/paste this into the editor at https://www.froala.com/wysiwyg-editor:

```
<div class="col-l-2 col-m-2 col-s-2 gutter-10 grid flex" contenteditable="false" id="communityPricing">
	<div class="communityPricing" contenteditable="true" style="text-align: center;">Lot #130
		<br>Longleaf Drive
		<br><strong>$119,900&nbsp;</strong>
		<br><a href="#">Inquire</a></div>
	<div class="communityPricing highlight" contenteditable="true" style="text-align: center;">Lot #201
		<br>Chadwick Drive
		<br><strong>SOLD</strong></div>
</div>
```

Click inside a Div, press Enter, click "Code View", now there are 3 divs instead of 2.

This is a big problem for us because we use nested divs for our grid system, and this will create a new div within the grid.

##### OS.
Windows 7 Pro

##### Browser.
Firefox (latest), Chrome (latest)

**Comment by SeanKendle** [comment]
Looks like adding fr-inner class fixes this issue.

**Comment by stefanneculai** [comment]
@SeanKendle as an alternative approach you could also change the enter option: https://www.froala.com/wysiwyg-editor/examples/enter.
