### ISSUE TITLE
Any Way to search font family in inline editor. If you have many fonts its very difficult to find the desired one. Maybe input box at the top of font family drop down ??

### ISSUE THREAD

**Issue by DaniyalZiaAwan** [froala/wysiwyg-editor#2934]
##### Expected behavior.
(Describe expected behaviour here)

##### Actual behavior.
(Describe actual behaviour here)

##### Steps to reproduce the problem.
(Describe the steps to reproduce the problem here. A [jsFiddle](https://jsfiddle.net/froala/wc5c3jhk/) is awesome when possible.)

##### OS.
(OS name and version here)

##### Browser.
(Browser name an version here)

**Comment by stefanneculai** [comment]
Thanks for the `feature-request`, @DaniyalZiaAwan .
