### ISSUE TITLE
Selection is lost while insert link popup visible 

### ISSUE THREAD

**Issue by SagarKharche** [froala/wysiwyg-editor#2935]
##### Expected behavior.
While inserting link, selected text should remain selected.

##### Actual behavior.
Selection is lost on insert link toolbar button press.

##### Steps to reproduce the problem.
Steps:
1. Select text in editor.
2. Click on insert link button on toolbar.
3. Notice selection is lost for the selected text.

##### OS.
All OS.

##### Browser.
All browser's
<img width="878" alt="selection lost" src="https://user-images.githubusercontent.com/7273026/42155328-bd955800-7e05-11e8-8b62-10ef3b555f81.png">
<img width="767" alt="with selection" src="https://user-images.githubusercontent.com/7273026/42155329-be100c9e-7e05-11e8-979e-dfab7018c7ba.png">

**Comment by stefanneculai** [comment]
When the popup is open, we have to move focus to the input from the popup. Unfortunately, the browsers do not allow 2 different selection on the same page and we have to remove one of them.
