### ISSUE TITLE
Edge - image with text is not pasted from word document

### ISSUE THREAD

**Issue by HammadKhalil90** [froala/wysiwyg-editor#2940]
hi,

I am facing this issue, I copy image with text from word 2013 to Edge, images are not pasted and text formatting is lost.

![edge-textwwords](https://user-images.githubusercontent.com/40855170/42315233-5c316f74-8060-11e8-9354-2ba9d0d8337c.gif)

Edge Version:
Microsoft Edge 42.17134.1.0
Microsoft EdgeHTML 17.17134

Regards,
Hammad Khalil.

**Comment by stefanneculai** [comment]
@HammadKhalil90 could you please send us the document you're pasting from?

**Comment by stefanneculai** [comment]
@HammadKhalil90 are you experiencing this on our website as well?

**Comment by HammadKhalil90** [comment]
[test.docx](https://github.com/froala/wysiwyg-editor/files/2175584/test.docx)

it is also reproducible on your website
https://www.froala.com/wysiwyg-editor
https://jsfiddle.net/froala/wc5c3jhk/

**Comment by stefanneculai** [comment]
Unfortunately, MS is doing some cleanup by its own and we don't have enough data in the clipboard in order to paste the image and formatting.
