### ISSUE TITLE
IE/Edge text format is lost when copy/paste from Word

### ISSUE THREAD

**Issue by HammadKhalil90** [froala/wysiwyg-editor#2941]
Hi,

I copy formatted text from word to Froala editor, following issues occur.

- after paste enter does not work.
- does not show pop up message.
- even when it shows pop up message formatting get lost.

 
![textpasteinie](https://user-images.githubusercontent.com/40855170/42315651-6c11401c-8061-11e8-8897-7b595e0bd300.gif)

**Comment by stefanneculai** [comment]
@HammadKhalil90 could you please send us the document you're pasting from?

**Comment by HammadKhalil90** [comment]
[Smart Editor in Read Only Mode.docx](https://github.com/froala/wysiwyg-editor/files/2166795/Smart.Editor.in.Read.Only.Mode.docx)

here it is

**Comment by stefanneculai** [comment]
@HammadKhalil90 Do you think it would be possible to make a jsFiddle to highlight the problem? That would speed-up things a lot. Here is a basic jsFiddle you could use as a starting point: https://jsfiddle.net/froala/wc5c3jhk/.

**Comment by HammadKhalil90** [comment]
it is also reproducible on your website 
https://www.froala.com/wysiwyg-editor 
https://jsfiddle.net/froala/wc5c3jhk/

**Comment by stefanneculai** [comment]
Thanks for all the details, @HammadKhalil90. We've investigated this problem and unfortunately, the HTML comes from MS Word already cleaned in this case and there is no way we could retrieve the formatting.
