### ISSUE TITLE
select all in cell should only be within the cell and not the entire editor

### ISSUE THREAD

**Issue by celeneisip** [froala/wysiwyg-editor#2942]
##### Expected behavior.
When user do select all via cmd+a/ctrl+a and the users cursor is within a table cell the range selection should only be within the cell and not the entire editor

##### Actual behavior.
When user do select all via cmd+a/ctrl+a and the users cursor is within a table cell the entire editor is selected

##### Steps to reproduce the problem.
- create a table
- type anything in a cell
- place your cursor in the cell where you add your content
- do cmd+a/ctr+a

refer to this video for sample:
https://www.dropbox.com/s/63dt9ig90wxsfky/cmd%2Ba%20cell.mov?dl=0

##### OS.
Mac

##### Browser.
Chrome/Firefox/Safari

**Comment by stefanneculai** [comment]
We are trying to keep the editor behavior similar to what other email clients / web apps do. This is the way email clients and Google Docs work, therefore at this moment we won't change this behavior.
