### ISSUE TITLE
imageDefaultWidth with percentage

### ISSUE THREAD

**Issue by rafal-olszewski** [froala/wysiwyg-editor#2943]
##### Expected behaviour.
To be able to set `imageDefaultWidth` with percentage, like `100%`

##### Actual behaviour.
When you set `100%` it prints out `100%px`

##### Steps to reproduce the problem.
Try uploading image via URL

##### OS.
OS X Mojave 10.4

##### Browser.
Chrome 67.0.3396.99 (Official Build) (64-bit)

**Comment by stefanneculai** [comment]
In order to have the images use percent instead of pixels, you should use the following option: https://www.froala.com/wysiwyg-editor/docs/options#imageResizeWithPercent.
