### ISSUE TITLE
Shift+Pos1 / Shift+End don't work correctly with a multi-line selection

### ISSUE THREAD

**Issue by steffenweber** [froala/wysiwyg-editor#2944]
##### Expected behavior.
Shift+Pos1 / Shift+End should work as expected with a multi-line selection.

##### Actual behavior.
They don't (see below).

##### Steps to reproduce the problem.
1. Go to https://www.froala.com/wysiwyg-editor
2. Select a word in the last line of the editor
![screenshot from 2018-07-06 13-33-06-fs8](https://user-images.githubusercontent.com/1138129/42376941-5fc2704a-8121-11e8-86b9-b3ec6dc3a089.png)
3. Press Shift + Arrow Up
![screenshot from 2018-07-06 13-33-36-fs8](https://user-images.githubusercontent.com/1138129/42376950-65ddab8e-8121-11e8-9e93-54b26a4bd931.png)
4. Press Shift + Pos1
![screenshot from 2018-07-06 13-34-14-fs8](https://user-images.githubusercontent.com/1138129/42376954-69091eb0-8121-11e8-9a04-6f905f6f46aa.png)
This should have added the first half of the second line ("Its complete documentation, specially designed framework") to the selection. But it actually removed the last line from the selection.

##### OS.
Linux

##### Browser.
Chrome 67

**Comment by stefanneculai** [comment]
@steffenweber we're not really doing any special changes to the selection, but we let the browser behave the way it would normally do, therefore we cannot do too much on our side. Could you please open this issue on Chromebug instead?

**Comment by steffenweber** [comment]
@stefanneculai This issue doesn't exist in a normal textarea (try it here on GitHub for example). It only happens in Froala. Please reopen.

**Comment by stefanneculai** [comment]
We're using a contenteditable field underneath. Here is a jsFiddle which uses a simple contenteditable: https://jsfiddle.net/froala/wc5c3jhk/890/. Is the problem present only in the editor?

**Comment by steffenweber** [comment]
I'm using Gentoo Linux but this issue isn't Linux-only. It was originally reported by one of our users running Windows. You should be able to reproduce it (at least) in Chrome on Windows.

**Comment by steffenweber** [comment]
I can reliably reproduce it using Chrome 67 on Windows 10 (via BrowserStack).

**Comment by mhartmann0** [comment]
I'm the user who reported it at computerbase.de.

@stefanneculai 

OS is Windows 10 17134.112

My test is on a 1080p monitor with the browsers 50/50 split (960x1080px big browser window). The fiddle's output pane is about 370x810px big, so you can comprehend what I'm talking about. Im directly copy'n'pasting the selection into the results table.

Test: Double clicking on `features` and selecting it, Shift + Up arrow, pressing Pos1/Home key

Expected result: `easy to integrate. We're continuously working to add in new ` like in the image below

![image](https://user-images.githubusercontent.com/15929417/42379796-35d0da6e-812c-11e8-81e7-58497c1a6f0b.png)

| Browser | Selection in Froala | Selection in Contenteditable |
|-|-|-|
| Firefox 59.0b12 | `e're continuously working to ` | `easy to integrate. We're continuously working to add in new ` |
| Edge 42.17134.1.0 | `e're continuously working to ` | `easy to integrate. We're continuously working to add in new ` |
| Chrome 68.0.3440.42 | `e're continuously working to ` | `easy to integrate. We're continuously working to add in new ` |

Seems like you're not setting the correct cursor position but leaving it at the end of the selection.

**Comment by steffenweber** [comment]
This issue was fixed in Froala 2.8.6 but is back again in Froala 3 (3.2.3). You can reproduce it by following the steps above.

Can you please re-open this issue?
