### ISSUE TITLE
Code view plugin doesn't trigger keypress event

### ISSUE THREAD

**Issue by sfescape** [froala/wysiwyg-editor#2945]
##### Expected behavior.
Keypress (as well as other key events) should trigger when they occur when in code view.

##### Actual behavior.
key events are not triggered

##### Steps to reproduce the problem.
Select code view while listening for key events.

##### OS.
MAC Sierra

##### Browser.
Chrome

**Comment by stefanneculai** [comment]
The code view is designed to be separate from all editor events. All changes made there are treated as an external change by the editor because it would be necessary to do some cleanup on them. I marked this as a `feature-request` for now.

**Comment by sfescape** [comment]
The notion is that it is needed to known when the panel is "dirty" in order to enable application level management of the content. Currently the only way I can see to do that is to monitor "keypress" and mark the panel "dirty" when that event occurs (and clear it after managing the content on a "contentChanged" event). I would be happy with a proper "dirty" event/state or even a specific code view "keypress" event.

As is, if the panel is in code view mode I have no way of knowing if the content has actually been modified until code view is left and "contentChanged" is triggered (thank goodness that event is at least getting triggered). In the meanwhile I'll look at simply marking the content as "dirty" if the user simply enters "code view" (if I can figure that out).

**Comment by stefanneculai** [comment]
Please see more details about why we don't trigger the contentChanged and other key events in the code view in the comment form here: https://github.com/froala/wysiwyg-editor/issues/1465#issuecomment-248594297.

**Comment by sfescape** [comment]
Yes, I read that while I was evaluating the product. I'm fine with contentChanged not triggering while in code view, it does however get triggered once you leave code view so still gives me a hook to know that I should now handle any changes made.

What I don't have is a way to know that editing of the content has actually started and so the content should be considered "dirty". A code view event would be fine, and as I said I'll see if there is a way for me know that at least code view has been entered and assume from that point the content is "dirty" and I suppose clear the "dirty" state when "contentChanged" is triggered at the end or some time after they leave code view mode if I don't get the "contentChanged" event (which feels hacky).

**Comment by stefanneculai** [comment]
We've just put together a public roadmap with the most popular features. 😍 There you can vote your favorite one, provide feedback or make new suggestions: https://wysiwyg-editor-roadmap.froala.com/public.
