### ISSUE TITLE
mailto links open a blank window

### ISSUE THREAD

**Issue by gabra20** [froala/wysiwyg-editor#2947]
##### Expected behavior.
a mailto link opens the user's mail application.

##### Actual behavior.
a mailto link opens a blank window before opening the mail application.

##### Steps to reproduce the problem.
- go to https://www.froala.com/wysiwyg-editor
- click the insert link button
- write a mail address in the URL input
- click on the open link button of the created link editButtons

##### OS.
Windows 10

##### Browser.
Google chrome an Firefox.

**Comment by CrazyClicker** [comment]
Is there a possibility to get target="blank" attribute for mailto links?
Seems that editor cuts it event if "Open in new window" checkbox is ticked and thats a problem if the link is in an iframe it causes it to not work.
