### ISSUE TITLE
android chrome hit the Enter/Delete key will scroll to top of page.

### ISSUE THREAD

**Issue by HereSinceres** [froala/wysiwyg-editor#2949]
##### Expected behavior.
android chrome click delete of the keyboard,the page no scroll to top

##### Actual behavior.
android chrome click delete of the keyboard,the page will scroll to top

##### Steps to reproduce the problem.
1.type long article
2.then delete
3.back to top 
froala version 2.8.4
##### OS.
android chrome

##### Browser.
chrome simulator

**Comment by stefanneculai** [comment]
@HereSinceres are you seeing this on a real device or only Chrome Simulator? Based on our experience, the Chrome Simulator doesn't replicate correctly the real device.

**Comment by HereSinceres** [comment]
https://www.froala.com/wysiwyg-editor
android chrome
Steps to reproduce the problem.
1.type long article
2.then delete
3.back to top
froala version 2.8.4

**Comment by stefanneculai** [comment]
@HereSinceres could you please let us know what mobile device are you using?

**Comment by shurlik9999** [comment]
@stefanneculai Some problem, xiaomi mi5s https://www.youtube.com/watch?v=YB84-Pxcmc8

**Comment by pridumkuvatyj** [comment]
Got the same behavior with version 2.8.5:
`if (e && !l.helpers.isIOS() && (e.which == M.FE.KEYCODE.ENTER || e.which == M.FE.KEYCODE.BACKSPACE || 37 <= e.which && e.which <= 40 && !l.browser.msie))
    try {
        s()// $(window).scrollTo(...) inside
    } catch (n) {}`

**Comment by largeden** [comment]
hi @stefanneculai 

I suspect that this issue is due to improvements in the issues below.

https://github.com/froala/wysiwyg-editor/issues/2573

```javascript
function positionCaret () {
//...
  if (info < editor.$tb.height() + 20 && info >= 0) {
    $(editor.o_win).scrollTop(info + editor.helpers.scrollTop() - editor.$tb.height() - 20);
  }
//...
}
```
I think the issue is happening because the `info> = 0` code has been removed.
