### ISSUE TITLE
Aviary Plugin - Uncaught TypeError: Cannot read property 'image' of undefined at Image.i.onload

### ISSUE THREAD

**Issue by demonspear** [froala/wysiwyg-editor#2951]
I have same issue like issue 2051. Here's the video i created to show you:
https://youtu.be/m1Wd1jkkdKY
OS: Windows
Browser: Chrome

**Comment by stefanneculai** [comment]
@demonspear please make sure you are using the latest 2.8.4 version.

**Comment by demonspear** [comment]
yes, i used 2.8.4 version 
![image](https://user-images.githubusercontent.com/35674559/42809677-5a8d849e-89e0-11e8-91d1-7b77e44849c1.png)

**Comment by stefanneculai** [comment]
@demonspear are you able to reproduce this on our website?
