### ISSUE TITLE
 Can not scroll by applying style to text

### ISSUE THREAD

**Issue by Eringi5** [froala/wysiwyg-editor#2952]
### bug behavior.
https://youtu.be/KaWH0dsTzvE
The focus does not come off from the area to which the style is applied

### Steps to reproduce the problem.
1.Apply styles to multiple words
2.Scroll
3.The focused area can not be removed from the screen

### OS.
iOS
I verified iOS 11.4
(Android has no problem)

### Browser.
・Safari
・Chrome

**Comment by largeden** [comment]
I think this is a bug in iOS 11.4. The same issue appears in ckeditor that I use.

iOS:11.4.1

**Comment by stefanneculai** [comment]
We've just checked this and it is more like a contenteditable problem and a restriction imposed by iOS, same happens in a blank contenteditable element: http://jsfiddle.net/froala/s0dkoyj4/. We're going to report it to Apple.
