### ISSUE TITLE
How can I adjust the height of a table cell?

### ISSUE THREAD

**Issue by mirazero** [froala/wysiwyg-editor#2957]
##### Expected behavior.
I want to adjust the height of the table cells with the mouse.

##### Actual behavior.
Currently, only table column widths can be adjusted with the mouse.

##### Steps to reproduce the problem.
1. Add a table from the toolbar
2. Attempt to adjust the height by selecting the table row with the mouse

##### OS.
Windows7

##### Browser.
IE 11.0.4 or Chrome 67.0.3396.99

**Comment by stefanneculai** [comment]
At this moment we don't have this feature, however, please make sure you subscribe to our newsletter to receive news as soon as it becomes available: https://www.froala.com/wysiwyg-editor/download#updates.

**Comment by Gabvo94** [comment]
@stefanneculai can you give any update on this please?

**Comment by Hiaslafson** [comment]
any news on this feature?

**Comment by AshMcConnell** [comment]
@stefanneculai has this been implemented anywhere, failing that, any tips to implement it manually?
