### ISSUE TITLE
Is it possible to edit the line width/style/color of the cell edge direction (up/down/left/right)?

### ISSUE THREAD

**Issue by mirazero** [froala/wysiwyg-editor#2959]
##### Expected behavior.
I want to specify the thickness, color, and style of table cell like ms office table cell.

##### Actual behavior.
Only Highlighted, Thick in table cell style is supported.

##### Steps to reproduce the problem.
1. Select the table cell.
2. Specify the cell style through the Cell pop-up menu.
2. I want to specify various cell styles. (like an ms office)

##### OS.
Windows 7

##### Browser.
IE11 or chrome 67.0.3396.99

**Comment by stefanneculai** [comment]
You can always add new table style: https://www.froala.com/wysiwyg-editor/examples/table-cell-styles.
