### ISSUE TITLE
Image with a caption

### ISSUE THREAD

**Issue by Khrystyna** [froala/wysiwyg-editor#296]
Hello! 

That's a common feature in newspapers to show caption below the image. I couldn't find a way to change html output for image upload feature. Image upload popup has input field for title. This title can be used for caption (even from semantic point of view, title should cover image purpose, so perhaps to omit new field you can use this data). Can be this handy? Or there is a way to handle this right now?..

Thanks for supporting and quick feedbacks! :)

**Comment by FinesseRus** [comment]
Two years passed already and the feature is still not implemented. This is sad :(

**Comment by leelinde92** [comment]
Will this be implemented?

**Comment by stefanneculai** [comment]
Yes, it will be in the following months. Sorry to keep all you guys waiting.

**Comment by Faey2222** [comment]
> Yes, it will be in the following months. Sorry to keep all you guys waiting.

Any update on this yet?

**Comment by Coedcoe** [comment]
Here's some hacky JS/CSS to use the images alt text and display that as an image caption

```
// Loops through all the images in the fr-view
$(".fr-view img").each(function() {
     // Checks if it is floating and wraps the image in a container with specific classes for the float position
     if($(this).hasClass('fr-fil')) {
        $(this).wrap("<div class='froala-img-container fl-left'></div>");
     } else if($(this).hasClass('fr-fir')) {
        $(this).wrap("<div class='froala-img-container fl-right'></div>");
     } else {
        $(this).wrap("<div class='froala-img-container'></div>");
     }
    
     // Sets the caption from the value of the images alt text, then appends that after the image
     var caption = $(this).attr("alt");
     $(this).after("<div class='froala-img-caption'><p>" + caption + "</p></div>");
});
```


  SASS styles to make it look nice:
```
.froala-img-container {
   position: relative;

   &.fl-left {
     float: left;
   }

   &.fl-right {
     float: right;
   }
 }

 .froala-img-caption p {
   color: #777777;
   font-size: 12px;
   width: 250px;
   float: left;
   white-space: nowrap;
   text-overflow: ellipsis;
   display: block;
   overflow: hidden;
 }
```

Preview in action:
<img width="946" alt="screen shot 2017-08-25 at 4 55 18 pm" src="https://user-images.githubusercontent.com/6466412/29736453-43bbb4f0-89b6-11e7-81be-abe1e415cbe9.png">

**Comment by stefanneculai** [comment]
Just a quick update here. The last commit is adding image caption feature.
