### ISSUE TITLE
*Update* Pasting an image copied from the froala editor doesn't trigger the image.beforeUpload event.

### ISSUE THREAD

**Issue by fflfi** [froala/wysiwyg-editor#2960]
Referencing closed issue: https://github.com/froala/wysiwyg-editor/issues/2930

Update:
It happens when you use the method with 3 parameters.
I updated your jsfiddle:
https://jsfiddle.net/wc5c3jhk/887/

Expected behavior:
Copying an image from one froala editor to another one should trigger the beforeUpload event.

Actual behavior:
Copying an image from one froala editor to another doesn't trigger the beforeUpload event.
Issue occures in version 2.8.4

Steps to reproduce the problem:

If I paste an image from one froala editor to another froala editor the event is not triggered. If I paste it from another source everything is working as expected.

It looks like it happens because if you copy an image from the editor its stored as HTML, so the editor doesnt recognize it as an image if you paste it again.

OS:
W10

Browser:
Chrome/Chromium

**Comment by stefanneculai** [comment]
@fflfi it looks like you haven't updated the jsFiddle. Could you please check it?

**Comment by fflfi** [comment]
@stefanneculai I managed to reproduce the problem last week in this updated jsfiddle. You should be able to see the following line in the fiddle "on('froalaEditor.image.beforeUpload', function (e, editor, files)" the problem only occured in the version with 3 parameters. But I just checked and I cant reproduce the problem anymore. Sorry for bothering you.

**Comment by stefanneculai** [comment]
It's good to hear that all is good now.
