### ISSUE TITLE
froala at.Js integration issue

### ISSUE THREAD

**Issue by rmmodi2** [froala/wysiwyg-editor#2961]
##### Expected behavior.
(Describe expected behaviour here)

Expected that display is:
@newname
@James

##### Actual behavior.
(Describe actual behaviour here)

In this bug, if someone tries to use @newname (where newname is not currently in the data), and then creates a new line and uses @Ja (where James IS currently in the data), when you click on the autocomplete for James, both the new line AND the ‘@newname’ text are replaced with @James.

Actual display is:
@James
@James

##### Steps to reproduce the problem.
(Describe the steps to reproduce the problem here. A [jsFiddle](https://jsfiddle.net/froala/wc5c3jhk/) is awesome when possible.)

first type @newname (where newname is any text which is not included in the at.Js "data" field)
then start typing @existingname on a new line (where existingname is included in the at.Js "data" field, but it will autocomplete existingname while you type it. once you click on the autocomplete it will replace both lines with @existingname (look at expected / actual display sections)

##### OS.
(OS name and version here)
Mac OS High Sierra version 10.13.5

##### Browser.
(Browser name an version here)
Google Chrome version 66.0.3359.117

**Comment by stefanneculai** [comment]
@rmmodi2 are you able to reproduce that on our website demo https://www.froala.com/wysiwyg-editor/examples/at-js? Could you also make a recording of the issue?

**Comment by rmmodi2** [comment]
I will attach the recordings here as a zip folder. It doesn't let me post them directly

**Comment by rmmodi2** [comment]
[bug_wrong_text_replaced.zip](https://github.com/froala/wysiwyg-editor/files/2198317/bug_wrong_text_replaced.zip)

**Comment by rmmodi2** [comment]
there is also one more bug that seems to be related which I will also attach a recording for here. 
[bug_text_appears_incorrectly.zip](https://github.com/froala/wysiwyg-editor/files/2198319/bug_text_appears_incorrectly.zip)

**Comment by stefanneculai** [comment]
@rmmodi2 thanks for the details. It looks like this is a problem from At.JS, not from the editor.
