### ISSUE TITLE
imagePaste option prevents images in pasted HTML content from displaying

### ISSUE THREAD

**Issue by chrisdeeming** [froala/wysiwyg-editor#2962]
##### Expected behavior.

If `imagePaste` is set to `false` it should still be possible to paste content into the editor that contains HTML with hot linked images inside it.

##### Actual behavior.

If `imagePaste` is set to `false` and you copy and paste some HTML from a web page that contains an image, the image HTML is stripped.

##### Steps to reproduce the problem.

1. Set up an editor instance with `imagePaste` set to false.
2. Copy and paste a paragraph of text including an image from [this page](https://news.xbox.com/en-us/2018/06/06/e3-2018-outer-wilds-coming-soon-xbox-one/) into the editor.
3. The `<img />` tags are stripped out.

I understand that this may be expected, but there's potentially another problem.

If `imagePaste` is set to `true` and you have no other image upload options enabled, then the above works fine. However, if you then attempt to paste image data (as in raw image data, not HTML) into the editor, the image is pasted into the editor as a data URI. For large images, this is not only incredibly slow but the "Uploading" progress meter is displayed and never closes. It feels wrong to display this as clearly it's not uploading anything.

My key point, however, is that there may well be a use case for allowing embedded images to come in via a paste of HTML, but not allowing raw image data to be uploaded/embedded as a data URI.

This may require a new option. `imagePasteHtml` so that we can have the HTML paste behaviour without any of the other behaviours associated to image pasting in the context of uploading/embedding.

##### OS.
Any.

##### Browser.
Any.

**Comment by stefanneculai** [comment]
The image paste feature was designed to prevent all images from being added over to the editor. I think you'd rather using for this https://www.froala.com/wysiwyg-editor/docs/options#imageUpload.
