### ISSUE TITLE
wordPasteModal set to false should clean word styles

### ISSUE THREAD

**Issue by Mboulianne** [froala/wysiwyg-editor#2964]
##### Expected behavior.
When wordPasteModal is set to false I expect to not see the modal and have word styles cleaned up.

##### Actual behavior.
The modal doesn't show up, howerer, the styles aren't cleaned.

##### Steps to reproduce the problem.
Set wordPasteModal to false and paste something from word to the editor.

##### OS.
Windows 10

##### Browser.
Chrome (didn't check on other browsers since it didn't seem relevant)

**Comment by Mboulianne** [comment]
@gabra20

**Comment by stefanneculai** [comment]
@Mboulianne if you'd like not to keep the word styles, then it is best to turn off the Word Paste plugin by not including it.

**Comment by Mboulianne** [comment]
@stefanneculai 
From the documentation => 
Show modal to choose if to keep or not styles pasted from Word. **If set to false, the default action is to clean the styles.**

You should at least update the documentation then ;).  Plus, I wanna keep word paste for image / list / etc... I just want to always clean the pasted text (so the modal is not needed)

**Comment by stefanneculai** [comment]
Indeed it appears to be an inconsistency there. We'll update the docs.

**Comment by Mboulianne** [comment]
I've done some test and removing the plugin doesn't work as indented.

I'm pasting from a word document with some text (bold, italig, etc) and some image.

when the plugin is removed I get something like
```
<p>sdfsdf</p><p>sdfsdf</p><p>sdf</p><p>sdfsdfsdfsdfsdf</p><p><!--[if !vml]--><br></p><p>Sdfsdfsdfsdf</p>
```
The image is gone.  No italic or bold tags are present.  I don't want that

when the plugin is active and I click clean
```
<p>sdfsdfsdfsdfsdf</p><p><img width="182" src="blob:http://localhost:8082/4c620cf7-5be7-41b5-84ae-ffaa843abc1c" class="fr-fic fr-dii"></p><p>Sdfsdfsdfsdf</p><p>sdfsdfsdfsdf</p><p><br></p><p>sdfsdf dsfsd<strong>f sdf sdf s<em>df sdf sd<u>f sdf sdf sdf sdf ds<s>sd fsdf sdf sdfsd f<sub>sdf sdf sdf</sub><sup>&nbsp;sdf sdf sdf&nbsp;</sup></s></u></em></strong></p>
```
The image is still there.  Bold / italic / underline is still there.  Everything looks fine.  I want this... but by default (I want to get rid of the modal that gives the user a choice).

when the plugin is active and I click keep
```
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:15px;font-family:"Calibri",sans-serif;'>sdfsdfsdfsdfsdf</p><p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:15px;font-family:"Calibri",sans-serif;'><img width="182" src="blob:http://localhost:8082/a4da0573-01ba-4953-91e7-97d51c4532d8" class="fr-fic fr-dii"></p><p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:15px;font-family:"Calibri",sans-serif;'>Sdfsdfsdfsdf</p><p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:15px;font-family:"Calibri",sans-serif;'>sdfsdfsdfsdf</p><p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:15px;font-family:"Calibri",sans-serif;'><br></p><p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:15px;font-family:"Calibri",sans-serif;'>sdfsdf dsfsd<strong>f sdf sdf s<em>df sdf sd<u>f sdf sdf sdf sdf ds<s>sd fsdf sdf sdfsd f<sub>sdf sdf sdf</sub><sup>&nbsp;sdf sdf sdf&nbsp;</sup></s></u></em></strong></p>
```
I get this... a big mess of word styles.  I don't want that.

**Comment by stefanneculai** [comment]
Thanks for the additional feedback, @Mboulianne. We're going to review it shortly.

**Comment by stefanneculai** [comment]
The last commit is adding the `wordPasteKeepFormatting` where you can choose if to keep or not the formatting when pasting from Word and not displaying the model.
