### ISSUE TITLE
Focus and paste functions use wrong element to scroll back to correct position

### ISSUE THREAD

**Issue by petester42** [froala/wysiwyg-editor#2966]
##### Expected behavior.
When focusing and pasting I expect the view to scroll to the correct position. Right now it always scrolls to top since the functions use $win to detect the scroll. This doesn't work since my window doesn't scroll I have a container that wraps the editor which scrolls.

##### Actual behavior.
The actual behaviour should use $sc (aka scroll container) to reset the position of the editor.

##### Steps to reproduce the problem.
- Focus in editor
- Enter text so that the editor has a scroll bar
- Scroll to end of editor content
- Click somewhere else in the page that is not part of the editor
- Focus back into the editor. 
- Editor will have scrolled to the top.

<img width="480" alt="screen shot 2018-07-16 at 3 08 09 pm" src="https://user-images.githubusercontent.com/296718/42778298-a17a38a6-890a-11e8-9b4f-9817caf44d6d.png">
<img width="443" alt="screen shot 2018-07-16 at 3 08 25 pm" src="https://user-images.githubusercontent.com/296718/42778302-a3323fc2-890a-11e8-9dd6-3c7b6da421fa.png">

##### OS.
macOS High Sierra

##### Browser.
Chrome 67.0.3396.99

**Comment by stefanneculai** [comment]
@petester42 we're not able to reproduce this. Do you think you could make a recording of this issue on our website demos?

**Comment by petester42** [comment]
Ya sure no problem but even without the demo it should be clear that scroll top will always be wrong. If the editor scroll is not the window scroll then it will for sure be wrong. Our problem is that our window doesn’t scroll only the editor scroll.

**Comment by petester42** [comment]
Here you go. I modified the styles of fr-wrapper to get it to work on the demo site. The editor scrolls to top when focus is called. This happens if I click on a toolbar button or tab into the editor.

![screen shot 2018-07-24 at 1 15 43 pm](https://user-images.githubusercontent.com/296718/43154917-e46eebc2-8f43-11e8-995f-4ef35aaf29d5.png)

![jul-24-2018 13-14-23](https://user-images.githubusercontent.com/296718/43154904-df1e51c6-8f43-11e8-8527-1fda616cd56d.gif)

**Comment by stefanneculai** [comment]
@petester42 it looks like you're setting some style there on the editor elements which shouldn't be done. To set a max-height, the height options should be used: https://www.froala.com/wysiwyg-editor/examples/adjustable-height.

**Comment by petester42** [comment]
I still see the issue in that example but I just realized we are talking about 2 different things. I want the content to stay scrolled to where it is right now but I believe the current code is to scroll to the editor itself. Maybe we are just misunderstanding each other.

**Comment by stefanneculai** [comment]
Yes, the editor is designed to scroll to the end of the pasted content.

**Comment by petester42** [comment]
Ok but it doesn’t scroll to the content that is getting changed by a toolbar button. That is the issue I want fixed.

**Comment by petester42** [comment]
Yes. Will do when I get to work

**Comment by petester42** [comment]
Here you go.
![jul-26-2018 14-28-48](https://user-images.githubusercontent.com/296718/43280960-5508a1aa-90e0-11e8-8591-e836364ca679.gif)

**Comment by stefanneculai** [comment]
Thanks, Peter. However, I don't understand exactly what you're doing. Are you scrolling the editor to the top and then pasting some text?

**Comment by petester42** [comment]
I’m just clicking. 

- has a scroll offset in the editor
- click outside the editor
- click bold

**Comment by petester42** [comment]
any updates?
