### ISSUE TITLE
Saving and restoring selection on focus and blue

### ISSUE THREAD

**Issue by petester42** [froala/wysiwyg-editor#2967]
##### Expected behavior.
I would expect that the selection from the editor be kept when I blur out of it and restore it when the editor is focused.

##### Actual behavior.
When editor is blured the selection is not saved and the selection is not restored when the editor is focused.

##### Steps to reproduce the problem.
Using the demo on [the website](https://www.froala.com/wysiwyg-editor)

- Focus in on editor
- Enter some text
- Place cursor in middle of text
- Click somewhere outside the editor that is not the toolbar
- Change paragraph format to Heading 1
- Cursor will jump to the beginning of the editor content

##### OS.
mac OS High Sierra 

##### Browser.
Chrome 67.0.3396.99

**Comment by stefanneculai** [comment]
The editor is not designed to store the cursor position when you're leaving the editing area. I am marking this as a `feature-request` for now.

**Comment by r-k-b** [comment]
there's a potential solution mentioned here: https://github.com/froala/wysiwyg-editor/issues/3881#issuecomment-626177266
(call `.selection.save()` from the `Froala.events.blur` callback)
