### ISSUE TITLE
Image toolbar - resize

### ISSUE THREAD

**Issue by MaciekKuna** [froala/wysiwyg-editor#2968]
It's connected with 
https://github.com/froala/wysiwyg-editor/issues/2397

##### Expected behavior.
(Describe expected behaviour here)
I would like to catch command `imageSize` from modal and then do own operations.
All parameters should be available like $img or something else.

![1](https://user-images.githubusercontent.com/16246708/42808026-98050f0a-89b2-11e8-9ec0-ece10cedc331.PNG)
![2](https://user-images.githubusercontent.com/16246708/42808028-982d05f0-89b2-11e8-99d7-0a73b75e642e.PNG)

##### Actual behavior.
Parameters passed to method are undefined. Only event name is present.

##### Steps to reproduce the problem.
1. Add image
2. Change size.

##### OS.
Windows

##### Browser.
(Browser name an version here)
Chrome, IE 11

**Comment by MaciekKuna** [comment]
Also the problem is that Froala add width and height to tag style but for example Outlook doesn't support this, only attributes height and width in img tag so I need to do it manually. That's why I need to intercept the event.

**Comment by stefanneculai** [comment]
@MaciekKuna we actually have an option for that: https://www.froala.com/wysiwyg-editor/docs/options#imageOutputSize.
