### ISSUE TITLE
Multiple editors flickering on chrome when scrolling

### ISSUE THREAD

**Issue by sharmaprashant232** [froala/wysiwyg-editor#2969]
In my website, multiple editors flickering on chrome when scrolling although it is running smoothly in firefox. 

Version I am using for froala is 2.7.1. 

When I tried using version 2.8.4, it flickers even on firefox.

Link for website is:

https://www.nexttrophy.com/create/academy

Please help me with this.

**Comment by stefanneculai** [comment]
Are you guys able to reproduce this on froala.com demo? What browser and OS are you using?

**Comment by Mboulianne** [comment]
I'll try to reproduce on jsFiddle.

**Comment by Mboulianne** [comment]
Well jsFiddle won't cooperate with me but here is what I did
First my froala config =>

`events: {
    'froalaEditor.initialized': (_e, editor) => {
        editor.toolbar.hide();
    }
}`

I found out that an element with class .fr-sticky-dummy is being inserted with the same height as the toolbar.  This is what created the flicker for me.  I fixed it with CSS.  I'm not sure this should be fixed by froala.

So I just wanted to share what fixed it for me.. might help you guys

**Comment by sharmaprashant232** [comment]
@Mboulianne After adding of this event, it hides the toolbar permanently for me. Any other ideas?

**Comment by stefanneculai** [comment]
Is any of you experiencing this on https://www.froala.com/wysiwyg-editor? If not, maybe you could create a jsFiddle where it happens? Here is a basic jsFiddle you could use as a starting point: https://jsfiddle.net/froala/wc5c3jhk/.

**Comment by sharmaprashant232** [comment]
Did you find the solution? @stefanneculai

**Comment by stefanneculai** [comment]
@sharmaprashant232 are you able to reproduce it on https://www.froala.com/wysiwyg-editor? Also, is this happening on a jsFiddle? https://jsfiddle.net/froala/wc5c3jhk/

**Comment by sharmaprashant232** [comment]
This is not happening on jsFiddle. Everything works fine on JsFiddle.

**Comment by stefanneculai** [comment]
Most likely this is an issue from your app - might be a CSS conflict or something similar. Please try checking the CSS rules in the browser developer console. Also, it might worth checking if there are other JS libs which might conflict with the editor.

**Comment by ziaongit** [comment]
```
.fr-toolbar {
  min-width: 300PX;
    max-width: 100%;
    /* overflow-y: hidden; */
    /* overflow-x: scroll; */
    OVERFLOW: VISIBLE;
    display: flex;
    border: 1px solid black;
    FLEX-WRAP: wrap;
 }
```

**Comment by ziaongit** [comment]
```
.fr-toolbar {
        position: fixed;
        display: flex;
        overflow: scroll;
        width: 100%;
        -webkit-overflow-scrolling: touch;
 }
```
