### ISSUE TITLE
Update imageUploadToS3 doc

### ISSUE THREAD

**Issue by jsnick** [froala/wysiwyg-editor#2973]
https://www.froala.com/wysiwyg-editor/docs/options#imageUploadToS3

v2.8.4

- not working case by doc
```
params: {
  AWSAccessKeyId: 'ACCESS_KEY', // Access Key from Amazon.
  policy: 'POLICY_STRING', // Policy string computed in the backend.
  signature: '', // Signature computed in the backend.
}
```

- my working case
```
params: {
  "X-Amz-Credential": "...",
  "X-Amz-Algorithm": "AWS4-HMAC-SHA256", 
  "X-Amz-Date": "...",
  Policy: "...", //
  "X-Amz-Signature": "", // computed in backend
}
```

- my minimum policy conditions for this
```
{ bucket: bucket },
[ "starts-with", "$key", upload_path ],
[ "starts-with", "$x-requested-with", "xhr" ],
[ "starts-with", "$content-type", "" ],
{ "x-amz-algorithm": "AWS4-HMAC-SHA256" },
{ "x-amz-credential": credential },
{ "x-amz-date": time_iso8601 },
{ success_action_status: "201" }
```
- https://github.com/froala/wysiwyg-editor/issues/2931

References
- https://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-UsingHTTPPOST.html#sigv4-post-signature-calc
- https://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-HTTPPOSTConstructPolicy.html
- https://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-post-example.html

**Comment by stefanneculai** [comment]
@jsnick it looks like you have a newer region where the signature should be computed differently. We'll put some updates there in the docs for it.
