### ISSUE TITLE
Toolbar => Mouse events (click, mousedown, mouseup, etc) don't bubble up

### ISSUE THREAD

**Issue by Mboulianne** [froala/wysiwyg-editor#2974]
##### Expected behavior.
Events should bubble up correctly or a custom froala event (ex: buttons.click) should be provided

##### Actual behavior.
Right now if you click on a button in the toolbar, there is no way to intercept the corresponding event.

##### Steps to reproduce the problem.
Make a page
Add an onclick listener to a container
Put an editor in that container.
Click in the container => event is catched by the handler.
Click in the text zone of the editor => event is catched by the handler
Click on a button in the toolbar => event is not catched by the handler.

##### OS.
Windows 10

##### Browser.
All of them

**Comment by Mboulianne** [comment]
@gabra20

**Comment by stefanneculai** [comment]
The editor is designed to stop these events because if we wouldn't do so, then we'd end up losing focus from the editable area in many cases.

**Comment by Mboulianne** [comment]
@stefanneculai I understand that you may have some limitations and that's why I'm proposing a custom event if native events aren't faisible.  I mean, we have events for pretty much everything (even buttons update!) but nothing for a simple click... which is waayyyyy more useful IMO.

If you can't provide a custom event either, would you be so kind as point a possible solution for me?  As I said, I need to do something when the user interacted with the rich text AFTER the focus.

Sorry to pester you again, have a nice day

**Comment by stefanneculai** [comment]
I added the `feature-request` flag on this for now and we'll consider adding it in a further release an event for toolbar click.

**Comment by Mboulianne** [comment]
@stefanneculai thank you.  The issue is still closed though ;)

**Comment by stefanneculai** [comment]
We do not keep `feature-requests` opened here. We use this repo only for bug tracking and enhancements.

**Comment by Mboulianne** [comment]
Ok thank you!
