### ISSUE TITLE
Can't  focus plugin in Bootstrap Modal

### ISSUE THREAD

**Issue by ckheder** [froala/wysiwyg-editor#2975]
##### Expected behavior.
(Describe expected behaviour here)
![capture du 2018-07-20 11-08-29](https://user-images.githubusercontent.com/29141668/42994013-44546718-8c0d-11e8-8665-d9481188ef5e.png)

##### Actual behavior.
(Describe actual behaviour here)
![capture du 2018-07-20 11-07-45](https://user-images.githubusercontent.com/29141668/42994034-4e8c06e6-8c0d-11e8-92dd-1b583221bd5e.png)

##### Steps to reproduce the problem.
Using the Froala editor v 2.8.4 with CDN inside a Bootstrap Modal 3.3.7

##### OS.
Linux Mint

##### Browser.
Firefox

**Comment by stefanneculai** [comment]
@ckheder do you think you could create a jsFiddle?

**Comment by ckheder** [comment]
Can't reproduce this issue

Using a link like this :
`<button data-toggle="modal" data-target="#ModalTweet" class="btn btn-info navbar-btn" type="button"><span class="glyphicon glyphicon-pencil"></span></button>`

And my modal look like this

```
<div class="modal fade" tabindex="-1" role="dialog" id="ModalTweet" aria-labelledby="ModalTweetLabel">
<div class="modal-dialog" role="document">
<div class="modal-content"><div class="modal-header">
<h4 class="modal-title" id="ModalTweetLabel">Nouveau Tweet</h4></div>
<form method="post" accept-charset="utf-8" class="form-inline" role="form" 
action="/instatux/tweet/add"><div style="display:none;"><input type="hidden" name="_method" class="form-control"  value="POST" /></div>                
<textarea id="editor1" name="contenu_tweet"></textarea>
               <script> $(function() 
               { 
               $('#editor1').froalaEditor({

                language: 'fr',
                toolbarButtons: ['embedly', 'insertLink', 'insertImage'],
                placeholderText: 'Placeholder'
        })
      });
    </script>   
                <br />
<div class="text-center">
                <button class="btn btn-success" type="submit">Tweeter</button>             
</div>
                <br />
                </form><div class="modal-footer"><button data-dismiss="modal" class="btn btn-danger" type="submit">Fermer</button></div></div></div></div>
```
Nothing more

**Comment by stefanneculai** [comment]
Are you experiencing it in https://github.com/froala/wysiwyg-editor/blob/master/html/3rd-party/bootstrap/modal.html if you just download the archive from master?

**Comment by ckheder** [comment]
No i'm not experiencing it if i download the archive from master

**Comment by stefanneculai** [comment]
It looks more like a conflict on setting up the editor in your app, rather than an issue with the editor itself. I would have to close this here and ask you to reach us for tech support via https://www.froala.com/wysiwyg-editor/contact.
