### ISSUE TITLE
Double click in buttons inside Insert image, blocks image section

### ISSUE THREAD

**Issue by ezebc182** [froala/wysiwyg-editor#2976]
##### Expected behavior.
The "target" (area to click or drag and drop the image, or input field to fill it with url image) is not blocked when double click is triggered on each tabs, respectively

##### Actual behavior.
The "target"(area to drag an drop image or click, input field to fill with url) is blocked and there is no way to upload an image.

##### Steps to reproduce the problem.
1) In Froala Editor Open **Insert image**
2) Double click on **upload image** or **By Url**

##### OS.
Ubuntu 18.04

##### Browser.
Google Chrome Version 67.0.3396.62 (Official Build) (64-bit)

**Comment by stefanneculai** [comment]
Thanks for logging this, @ezebc182. We'll provide updates for it shortly.
