### ISSUE TITLE
Unable to enter URL in Insert link Cordova App

### ISSUE THREAD

**Issue by sachinkumaram-veoci** [froala/wysiwyg-editor#2977]
##### Expected behavior.
Can be able to enter URL text in Insert link input field

##### Actual behavior.
Insert link input field gets disable , can't enter any text.

##### Steps to reproduce the problem.
1. In Froala Editor Open Insert link
2. Enter any text in URL text field

##### OS.
iOS 11.4(iPhone 5S)

##### Browser.
Cordova App

**Comment by stefanneculai** [comment]
@sachinkumaram-veoci do you still have this problem if you're using the iframe option?

**Comment by sachinkumaram-veoci** [comment]
@stefanneculai Could you please elaborate more about iframe option?

**Comment by stefanneculai** [comment]
https://www.froala.com/wysiwyg-editor/docs/options#iframe

**Comment by sachinkumaram-veoci** [comment]
Is any alternate solutions?

**Comment by sachinkumaram-veoci** [comment]
Set iframe = true, It doesn't working in my implementation.If any other solutions, Please suggest.

**Comment by sachinkumaram-veoci** [comment]
One interesting thing i found, if i remove tabindex from input type, it start working. Please let me know,How can i remove through froala library?

**Comment by stefanneculai** [comment]
Does it work if you're changing the editor `zIndex` option to a high value? https://www.froala.com/wysiwyg-editor/docs/options#zIndex

**Comment by sachinkumaram-veoci** [comment]
No,It doesn't working after changing the zIndex option to high value.

**Comment by stefanneculai** [comment]
@sachinkumaram-veoci do you think could put together a repo with a simple Cordova app in which we can replicate this? Thanks in advance.

**Comment by sachinkumaram-veoci** [comment]
Repository created : https://github.com/sachinkumaram-veoci/froala-insertLinkIssue

**Comment by sachinkumaram-veoci** [comment]
@stefanneculai Please suggest the possible solution.

**Comment by stefanneculai** [comment]
@sachinkumaram-veoci I just tried it and appears to work correctly for me. Any chance you could make a recording?

**Comment by stefanneculai** [comment]
@sachinkumaram-veoci we are not able to reproduce it. Please find attached a recording.

[cordovaapp (1).zip](https://github.com/froala/wysiwyg-editor/files/2686365/cordovaapp.1.zip)

**Comment by sachinkumaram-veoci** [comment]
Hi Stefan,
These errors would come if you try to enter the link in URL field around
3-4 times.
On first instance, it will work perfectly.

Regards,
Sachin Kumaram

**Comment by stefanneculai** [comment]
@sachinkumaram-veoci can you make a recording?

**Comment by sachinkumaram-veoci** [comment]
Hi Stefan,

Please find the attached video for froala issue.

Regards,
Sachin Kumaram

**Comment by stefanneculai** [comment]
It doesn't appear to be any video attached. Could you please check?

**Comment by sachinkumaram-veoci** [comment]
Please find the attached video.

**Comment by stefanneculai** [comment]
@sachinkumaram-veoci I think you're sending it via email. You should upload it directly to Github in order to work correctly.

**Comment by sachinkumaram-veoci** [comment]
[froala-issue-l.mov.zip](https://github.com/froala/wysiwyg-editor/files/2690996/froala-issue-l.mov.zip)

**Comment by sachinkumaram-veoci** [comment]
@stefanneculai I hope the attached video should work and clarify my issue.

**Comment by stefanneculai** [comment]
As per our investigation, it looks there is a problem with `tabIndex` CSS property on inputs in Cordova apps. As a workaround, we would suggest, the following approach: https://jsfiddle.net/froala/rds2p3f4/.
