### ISSUE TITLE
Insert after image captions

### ISSUE THREAD

**Issue by kristian-puccio** [froala/wysiwyg-editor#2978]
##### Expected behavior.
When I add an image as the last element in a document and give it a caption I should be able to insert other things underneath it.

Not sure if this is a duplication of #2731 but if it is it is also affecting Chrome + FireFox

##### Actual behavior.
I can only add to the image caption

##### Steps to reproduce the problem.
Add some text or anything really.
Add an image and add a caption.
Try to create a new element underneath the image/caption.

##### OS.
Osx 10.13.6

##### Browser.
Chrome + Firefox

**Comment by stefanneculai** [comment]
@kristian-puccio browser control inside contenteditable is quite limited in this case. We don't have too many options and what we did, is adding the possibility of clicking underneath the caption to create a new line after the image.

**Comment by kristian-puccio** [comment]
@stefanneculai do you have an example of this working?
Or is it something I would have to code manually?

Thanks
