### ISSUE TITLE
Webpack (Encore) & KMS FroalaEditorBundle

### ISSUE THREAD

**Issue by jmsche** [froala/wysiwyg-editor#2980]
##### Expected behavior.
Pack everything using Webpack Encore to reduce HTTP calls & data transfer.

##### Actual behavior.
Does not work; jQuery & `froalaEditor` are not accessible from outside the webpack config/app.js file.

##### Steps to reproduce the problem.
Hi,

I currently use the KMSFroalaEditorBundle. I put the issue here as I think it is more a Froala issue than a KMS one.
By default, for each editor created by the bundle, everything is loaded several times (jQuery, Froala JS, each plugin...). That means the page may take several seconds to load due to this default configuration.
Loading the editor is done "externally" in the template (see https://github.com/froala/KMSFroalaEditorBundle/blob/master/Resources/views/Form/froala_widget.html.twig#L62-L94).
To avoid this, I try to reduce HTTP calls/load by packing everything using Webpack Encore (a wrapper for Webpack), using this configuration:

```js
// webpack.config.js
let Encore = require('@symfony/webpack-encore');
let HardSourceWebpackPlugin = require('hard-source-webpack-plugin');

Encore
    .setOutputPath('public/build/')
    .setPublicPath('/build')
    .cleanupOutputBeforeBuild()
    .enableSourceMaps(!Encore.isProduction())
    .enableVersioning(Encore.isProduction())
    .enableBuildNotifications()

    .addEntry('app', './assets/js/app.js')
    .enableSassLoader()
    .autoProvidejQuery()
    .autoProvideVariables({
        '_': 'underscore',
        Backbone: 'backbone',
    })

    .addPlugin(new HardSourceWebpackPlugin())
;

module.exports = Encore.getWebpackConfig();
```

```js
// assets/js/app.js
require('jquery');

// Froala
import 'froala-editor/js/froala_editor.pkgd.min.js';
import 'froala-editor/js/languages/fr.js';
```

Do you have any idea how I could fix that?

Thanks

##### OS.
N/A

##### Browser.
N/A

**Comment by stefanneculai** [comment]
At this moment jQuery should be defined globally in order to work correctly.

**Comment by jmsche** [comment]
Is there any plan in the future to either remove jQuery as a dependency, or fix this?

**Comment by stefanneculai** [comment]
Yes, it is on our roadmap to remove jQuery as a dependency. In the meanwhile, jQuery should be defined globally. In Webpack, you could do it like this

```js
import $ from 'jquery';
window.jQuery = $;
window.$ = $;
```

or add to the webpack config file

```js
new webpack.ProvidePlugin({
  $: 'jquery',
  jQuery: 'jquery'
})
```
