### ISSUE TITLE
Uploading image sidebar works fine, but from toolbar does not popup dialog to choose image

### ISSUE THREAD

**Issue by cbielich** [froala/wysiwyg-editor#2983]
I am using a Froala textarea for users to comment as well be able to upload images. I have the image upload button on the toolbar as well as the + sign on the side when you enter the cursor. I use this editor all over my site and works great, but for some reason on this particular page it is partially working

When a user clicks the + sign and clicks the image upload button the behavior works fine. The image can be selected and image uploaded. For some reason when you click the toolbar button I get the file upload popup but when I click on it to choose a image nothing pops up. It only works on the side toolbar.

**This works**

![image](https://user-images.githubusercontent.com/63542/43166983-114c4398-8f4d-11e8-8e64-190f1f2baf1e.png)

**This does not work**

![image](https://user-images.githubusercontent.com/63542/43167015-30881d0e-8f4d-11e8-857a-39022765066d.png)

When I click on the Drop Image nothing pops up

Does not work in any browser. Any idea why the side bar works but the main toolbar does not?

**Comment by stefanneculai** [comment]
@cbielich it looks like you might have some code there on the page which prevents the default editor behavior. Are you able to reproduce this on our website? If not, please reach us via https://www.froala.com/wysiwyg-editor/contact so that we can help you with tech support.
