### ISSUE TITLE
Table pasted as image in Froala editor

### ISSUE THREAD

**Issue by sandeepsukhija** [froala/wysiwyg-editor#2985]
##### Expected behavior.
When we copy content from OpenOffice Calc - 4.1 and paste in the editor, the content should be copied and should be editable.

##### Actual behavior.
The content is pasted as an image.

##### Steps to reproduce the problem.
- Create a table in Calc with multiple rows and columns
- Copy the table
- Paste in editor

##### OS.
Centos 7

##### Browser.
Chrome - Version 64.0.3282.24 (Official Build) dev (64-bit)

** The issue can be simulated on the froala's site as well.

**Comment by stefanneculai** [comment]
Thanks for bringing this to our attention. At this moment, we do not support fully pasting from OpenOffice. This is the way the browser is handling the pasting and it is on our list to add more support for pasting from OpenOffice.
