### ISSUE TITLE
Allow `tableResizer` only for certain tables

### ISSUE THREAD

**Issue by petester42** [froala/wysiwyg-editor#2986]
##### Expected behavior.
I would like to have 2 kinds of table in the content of my editor one which can resize cells and one that can't.

##### Actual behavior.
Right now the option is always on or always off since it is an option that the editor takes as a parameter. 

##### Steps to reproduce the problem.
There are no real steps, this is more of feature request.

##### OS.
macOS High Sierra

##### Browser.
Chrome 68.0.3440.75

**Comment by stefanneculai** [comment]
Thanks for the feature request. I marked it accordingly and will close it for now as we don't keep feature requests here.

**Comment by stefanneculai** [comment]
We have an internal system for tracking them. As soon as they are released, they will be included in the changelog.

**Comment by petester42** [comment]
Are these items prioritized by tier of lisence?

**Comment by stefanneculai** [comment]
No, features are prioritized by the number of requests. Only bugs are prioritized by license tier.

**Comment by petester42** [comment]
Ok. Thanks for the information.
