### ISSUE TITLE
In a restricted height editor, Grammarly causes horizontal scrollbars to appear sporadically.

### ISSUE THREAD

**Issue by chrisdeeming** [froala/wysiwyg-editor#2991]
##### Expected behavior.
Grammarly and Froala should work nicely with each other especially when the editor height is constrained and scrollbars may appear. It may require changes on Froala's end or Grammarly's end or a collaboration to ensure the two products work well together.

##### Actual behavior.
See attached screen recording:

[Screen Recording 2018-07-26 at 18.49.48.zip](https://github.com/froala/wysiwyg-editor/files/2233025/Screen.Recording.2018-07-26.at.18.49.48.zip)

When the editor has a max height, there appear to be problems when Grammarly is enabled.

##### Steps to reproduce the problem.
See above.

##### OS.
Windows. I believe it affects macOS too, but it is less obvious due to the invisible scrollbars.

##### Browser.
Any.

**Comment by stefanneculai** [comment]
We're aware of some Grammarly problems and reported them over to Grammarly. Unfortunately, there is not too much we could do on our side, but push these further to Grammarly.
