### ISSUE TITLE
Clear formatting button converts table cells into divs

### ISSUE THREAD

**Issue by psoloninka** [froala/wysiwyg-editor#2992]
##### Expected behavior.
Selecting formatted text within a table cell and hitting the clear formatting button removes the formatting from the text and the text remains inside the table cell.

##### Actual behavior.
The text within the cell is moved to a div outside of the table.

##### Steps to reproduce the problem.
1. Create a table
2. Type "test" into a cell
3. Select "test" and click align-center
4. Select "test" and click clear-formatting
5. Observe that the text appears to remain within the table, but borders are missing and the alignment is different from the default
6. Switch to the code view and observe that `<div>test</div>` appears before the table and "test" is not present in the table.

##### OS.
OSX 10.12.6

##### Browser.
Chrome 67.0.3396.99

**Comment by stefanneculai** [comment]
This should be fixed on the current master.
