### ISSUE TITLE
There is no progress bar when uploading images?

### ISSUE THREAD

**Issue by rex19001** [froala/wysiwyg-editor#2993]
There is no progress bar when uploading images?

I am using angular 6

This options code:

`
  ngOnInit() {
    this.options = {
      language: "zh_cn",
      placeholderText: "",
      charCounterCount: true,
      charCounterMax: 1000,
      imageUploadURL: "http://localhost:21021/api/services/app/UploadFiles/EditorImageAsync",
      imageUploadParam: "file",
      imageMaxSize: 1024 * 1024 * 10,
      imageAllowedTypes: ['jpeg', 'jpg', 'png', 'gif'],
      quickInsertButtons: ['image', 'table', 'ul', 'ol', 'hr'],
      toolbarButtons: ['fullscreen', 'bold', 'italic', 'underline', 'strikeThrough', 'subscript', 'superscript', '|', 'fontFamily', 'fontSize', 'color', 'inlineStyle', 'paragraphStyle', '|', 'paragraphFormat', 'align', 'formatOL', 'formatUL', 'outdent', 'indent', 'quote', '-', 'insertLink', 'insertImage', 'embedly', 'insertFile', 'insertTable', '|', 'specialCharacters', 'insertHR', 'selectAll', 'clearFormatting', '|', 'print', 'spellChecker', 'help', 'html', '|', 'undo', 'redo'],
      codeMirror: false,
      codeMirrorOptions: { tabSize: 4 },
      events: (e, editor) => {
        this.froala.emit(this.froalaText);
        console.log(editor.selector.get());
      }
    }
  }

`

**Comment by stefanneculai** [comment]
This looks more like a configuration problem, rather than an issue from the editor. By default, the editor has a loader while upload the images, which in this case doesn't show. Please reach us via https://www.froala.com/wysiwyg-editor/contact with more details on how we can reproduce it.
