### ISSUE TITLE
Commands must select word if selection isCollapsed

### ISSUE THREAD

**Issue by kachurun** [froala/wysiwyg-editor#2995]
##### Expected behavior.
Then you set cursor to any word without selection and then select any command (e.g BOLD) - need select word under cursor.

I create simple method `extend` in `selection` class:

```
function expand(granularity = 'word') {
    const sel = get();

    sel.modify('move', 'backward', granularity);
    sel.modify('extend', 'forward', granularity);
}
```
and run it in `commands -> mapping` in beginning of each method:

```
if (editor.selection.isCollapsed()) {
  editor.selection.expand();
}
```

It correct works for me.

**Comment by stefanneculai** [comment]
Probably this would go better as an option, rather than something by default. I marked it as a `feature-request` for now.
