### ISSUE TITLE
Clear formatting button is not consistent on last item copy-pasted from Froala

### ISSUE THREAD

**Issue by psoloninka** [froala/wysiwyg-editor#2996]
##### Expected behavior.
I clear formatting on an item that I just copy-pasted from somewhere in Froala and all formatting is removed.

##### Actual behavior.
Some formatting like color is removed from the text, but the item remains in its own p tag or list item.

##### Steps to reproduce the problem.

1. Type "test" into the editor
2. Copy "test" from the editor
3. Hit return/enter to create a new line 
4. Paste into the new line
6. Repeat 3 and 4
7. Select all the text in the editor and click the clear formatting button
8. Observe that the first two lines have been merged together, but the last "test" remains on its own line

*Alternate flow with lists*
Before step 7: Select all text in the editor and click either one of the list buttons

##### OS.
OSX 10.12.6

##### Browser.
Safari 11.1.2

**Comment by stefanneculai** [comment]
@psoloninka do you think you could provide a recording as well? Thanks in advance.

**Comment by psoloninka** [comment]
@stefanneculai, sure, here is a recording: [froala-wysiwyg-editor-2996.zip](https://github.com/froala/wysiwyg-editor/files/2271397/froala-wysiwyg-editor-2996.zip).

**Comment by stefanneculai** [comment]
Thanks for the details. I can confirm that it is an issue and the cause for it is the same with #2992.
