### ISSUE TITLE
Content changed stops emitting after selection.save()

### ISSUE THREAD

**Issue by ankitjainOfficial** [froala/wysiwyg-editor#2997]
##### Expected behavior.
The below function should always emit when user changes content.
```
froalaEditor.on('froalaEditor.contentChanged', () => {
	console.log('content changed');
});
```

##### Actual behavior.
Content Changed event is not emitted after `selection.save()` is called.

##### Steps to reproduce the problem.
See console.logs.
https://jsfiddle.net/ankitjain11/wc5c3jhk/1025/

##### OS & Browser.
I dont think this is an OS or Browser issue. However, I've tried this on OS X, Chrome and Firefox.

**Comment by stefanneculai** [comment]
The `selection.save` is adding some markers in the editor. It should never be used to add markers and leave the option of typing.

**Comment by ankitjainOfficial** [comment]
@stefanneculai I am sorry, but I don't get you. Can you guide me, how do we get or restore the caret positions of the editor. My use case being, I need to add a special html, from outside the Froala editor to the model.

**Comment by stefanneculai** [comment]
The cursor position can be changed using the `selection.save` method and restored with `selection.restore`. However, these actions should be done with no typing in between. It looks like you're looking for a special case and I would recommend reach our tech support via https://www.froala.com/wysiwyg-editor/contact for further guidance.
