### ISSUE TITLE
Incorrect encoding when email address is wrapped in <> characters

### ISSUE THREAD

**Issue by arnaudvalle** [froala/wysiwyg-editor#2998]
##### Expected behavior.
< and > characters should not be encoded when added as part of a mailto link

##### Actual behavior.
< and > characters are encoded when added as part of a mailto link

##### Steps to reproduce the problem.
1. Add the following text to an editor: `Email <email@domain.com>`
2. Press [enter]
3. This transforms the text in a mailto link but also encodes the `<` and `>` characters and put them inside the link. The resulting source is: `Email <a href="mailto:<email@domain.com>">&amp;lt;email@domain.com&amp;gt;</a>`
Note: this is possibly related to https://github.com/froala/wysiwyg-editor/issues/2182

The mailto link itself is correct but the text of the <a> tag isn't.

Example:

![image](https://user-images.githubusercontent.com/1215056/43444473-14acc876-94a4-11e8-878d-39714d2b7b3e.png)

##### OS.
macOS 10.13.6

##### Browser.
Chrome 67.0.3396.99

**Comment by Vnthf** [comment]
plz fix this bug
