### ISSUE TITLE
button's popup doesn't show under the button, inside a custom popup containing a built-in button that's already on the toolbar

### ISSUE THREAD

**Issue by gabra20** [froala/wysiwyg-editor#2999]
##### Expected behavior.
the insert link or insert image popup should always pop under the right button.

##### Actual behavior.
When you have a popup containing a button with a popup ('insertLink', 'insertImage', ...) that's already on the toolbar, the button's popup pops under the toolbar button.

##### Steps to reproduce the problem.
https://jsfiddle.net/pzt4adxb/42/

- add a button with a popup to the toolbar ('insertLink', 'insertImage', ...)
- create a custom popup with this button inside
- add the custom popup to the toolbarButtons and toolbarButtonsXS options
- click on the custom popup's button => the popup shows under the toolbar button
- resize page to switch to toolbarButtonsXS => the popup show out of the editor (under the hidden toolbar button, i think)

I think it's because of this line :
"var $btn = editor.$tb.find('.fr-command[data-cmd="myButton"]');"
since both buttons have the same command, the popup shows under the first button it finds.

##### OS.
Windows 10 (I think it'll happen on any OS)

##### Browser.
Chrome and Firefox (I think it'll happen on any browser)

**Comment by gabra20** [comment]
@Mboulianne

**Comment by stefanneculai** [comment]
Please see https://jsfiddle.net/froala/pzt4adxb/46/ for a fix.

**Comment by gabra20** [comment]
@stefanneculai, I'm sorry but i don't think this fixes my bug...

 - When I click on the custom popup's "insert link" button, the popup's still shows under the toolbar's button
![2018-08-02 15_34_03-sticky toolbar in froala editor - jsfiddle](https://user-images.githubusercontent.com/38441217/43606579-c0508e44-9669-11e8-9baa-a6a3830a07d5.png)


 - When I'm in "toolbarButtonsXS mode", the popup show's above the editor...
![2018-08-02 15_34_20-sticky toolbar in froala editor - jsfiddle](https://user-images.githubusercontent.com/38441217/43606635-ebb356ac-9669-11e8-9787-14dc3fc8f3dd.png)


It's the same for the "insert picture" button

**Comment by stefanneculai** [comment]
@gabra20 the `insertLink`, `specialCharacters` and `insertImage` buttons were designed to be used in the main toolbar and not in a popup. To use them in a popup, you should be changing the code used by the editor for those buttons.
