### ISSUE TITLE
IE 11 - Cursor at the top of the image after image insert

### ISSUE THREAD

**Issue by kishore12** [froala/wysiwyg-editor#3000]
##### Expected behavior.
After inserting an image in IE 11, the cursor is at the bottom of the image

##### Actual behavior.
After inserting an image in IE 11, the cursor is at the top of the image

![image](https://user-images.githubusercontent.com/5471291/43478251-6538a4fa-94cb-11e8-9aa4-cc9533747379.png)

##### Steps to reproduce the problem.
- Go to https://www.froala.com/wysiwyg-editor
- Select Insert Image
- Add an image
- Wait for the image upload to finish
- Cursor is at the top of the image

##### OS.
Windows 10 Pro
Build - 17134.167

##### Browser.
IE 11
Version - 11.165.17134.0

**Comment by stefanneculai** [comment]
Unfortunately, in IE 11, there are some problems with the way the browser renders the cursor. We've tried all kind of approaches for this and there is nothing we could find so far.
