### ISSUE TITLE
Generating XHTML output

### ISSUE THREAD

**Issue by jaimestuardo** [froala/wysiwyg-editor#3001]
##### Expected behavior.
Tags that does not have ending tag should finish with "/>". For example, IMG tag.

##### Actual behavior.
Tags finish with ">". For example IMG tag.

##### Steps to reproduce the problem.
Just add an image. For example, this HTML was generated for mine:

`<img src="/User/Images/Editor/logo.gif" style="width: 189px;" class="fr-fic fr-dib fr-fil">`

It should be:

`<img src="/User/Images/Editor/logo.gif" style="width: 189px;" class="fr-fic fr-dib fr-fil" />`

##### OS.
Any

##### Browser.
Any

It is very important output to be XHTML compatible. In my case, I am generating a PDF file from the HTML, however, since HTML is bad formed (non XHTML), PDF component notifies that and does nothing.

I need urgently this to be solved. Is this plugin available as non minimized version somewhere?

**Comment by stefanneculai** [comment]
The editor is designed to output HTML5. What we'd suggest is to post-process the editor output and add the self-closing tags. 

The unminified JS is available under the Professional / SaaS / Enterprise license.

**Comment by jaimestuardo** [comment]
Thanks Stefan.. I have did it that way. After I retrieved the content from Froala I ran a method to convert HTML to XHTML.

I thought there was a way to avoid that, but thanks anyway.
