### ISSUE TITLE
Undo command does not reupload the deleted image

### ISSUE THREAD

**Issue by 17100194** [froala/wysiwyg-editor#3002]
Hi, I am facing a slight issue with image upload in Froala. When I add a new image I store it on the server using the editor options and then when the image is removed from the editor I at the same time also delete it from the server where it is stored but the issue is that after removing the image if the user clicks the undo button the image reappears in the editor but it does not call the upload function again to store it on the server so is it suppose to be like this or am I missing something?

**Comment by stefanneculai** [comment]
The best way for removing the images would be just to send a request to the server telling that the image was removed from the editor but don't delete it. When the content of the editor is saved, together with that, the images which have been marked to be removed should be deleted as well.

**Comment by hanyska** [comment]
> The best way for removing the images would be just to send a request to the server telling that the image was removed from the editor but don't delete it. When the content of the editor is saved, together with that, the images which have been marked to be removed should be deleted as well.

This is not a solution. Please fix this issue

**Comment by fadymicroquest** [comment]
This is still an issue
