### ISSUE TITLE
Paragraph Styles on selected text

### ISSUE THREAD

**Issue by btmdave** [froala/wysiwyg-editor#3004]
When using Paragraph Styles, it doesn't seem to factor in selected text? For example.  With the following copy:

`<p>This is some <strong>major</strong> text</p>`

If you highlight in the editor over `major` and add a paragraph style, it adds it to the parent `p` tag.  Is there an option available to have this apply to the closest element, in this case strong or to the text specifically highlighted, not the containing p tag?

**Comment by stefanneculai** [comment]
The paragraph styles feature is designed to apply the style to the current paragraph, not the currently selected text. If you'd like to change it this way, it is best to create a custom plugin and use the `format.apply`, `format.remove`, and  `format.toggle` options.
