### ISSUE TITLE
Unlink file menu does not work on mac

### ISSUE THREAD

**Issue by cbielich** [froala/wysiwyg-editor#3007]
I discovered today that the menu that comes up when clicking on a file after uploading shows up fine on my windows machine but when I am on my mac that menu does not show up when I click it.

Its the menu that lets you edit or unlink the file

I tried it with Safari, Chrome and Firefox and all didn't work on my mac but works fine on my windows machines.

Any help?

**Comment by stefanneculai** [comment]
@cbielich are you able to reproduce this on our website as well? If so, could you please send a recording?
