### ISSUE TITLE
Image setting not working on responsive images.

### ISSUE THREAD

**Issue by Spoowy** [froala/wysiwyg-editor#3009]
##### Expected behavior.
Froala should change the image, even when the previous image is of responsive type (via srcset or figure).

##### Actual behavior.
Something happens but the changes Froala makes are kept overwritten by other properties.
Possible solution? Remove the other properties if they exist - or - add options supporting responsive images :)

##### Steps to reproduce the problem.
Here is a jsfiddle with both examples: https://jsfiddle.net/amek8znp/9/

##### OS.
Mac OS X Sierra 

##### Browser.
Chrome Version 68.0.3440.106 (Official Build) (64-Bit)

Cheers!

**Comment by stefanneculai** [comment]
At this moment, we do not support such a feature in the editor. I am marking this as a `feature-request` so that it is in our attention to be implemented in further versions.

**Comment by martinschenk** [comment]
Any news belonging scrset in froala editor?
I always would like to use it.
Cheers

**Comment by pomartel** [comment]
I would also like to be able to define a `srcset` or a `picture` tag when using the `image.insert` method.

**Comment by TutanRamon** [comment]
Yes, me too. Very few editors support responsive images.
