### ISSUE TITLE
Issues with disabling/enabling editors

### ISSUE THREAD

**Issue by monsterlane** [froala/wysiwyg-editor#3011]
##### Expected behavior.
Disabling one editor should not disable other instances toolbars.

##### Actual behavior.
Disabling one editor makes all other editors toolbars think they're disabled. The toolbar will appear but clicking any button (bold for ex) will not apply the action.

##### Steps to reproduce the problem.
https://jsfiddle.net/mj8q0un4/11/

##### OS.
Any

##### Browser.
Any

Reported this about 2 years ago. A workaround was provided: "When you initialize the editor pass an unique ID to each instance". While this does fix the bug it also makes each and every instance have their own toolbar DOM. This creates a lot of extra markup especially if you have many Froala instances on one page. Our application can have 500+ instances on a page at once and having 500+ toolbars impacts performance.

**Comment by stefanneculai** [comment]
Thanks for bringing this to our attention, @monsterlane. We consider this more like a feature-request, therefore I am marking it accordingly.  What I would recommend in case you have multiple instances in the meanwhile is to use the init on click configuration: https://www.froala.com/wysiwyg-editor/examples/init-on-click.

**Comment by monsterlane** [comment]
It's not really a feature request. If you put console.logs into the core editor file you'll see the CSS tags are being applied correctly but the disabled variable isn't being managed properly.

I wasn't aware of that option thanks!

**Comment by monsterlane** [comment]
@stefanneculai we fixed this internally do you want us to send you our fix?

**Comment by stefanneculai** [comment]
@monsterlane please send the code you might have on https://www.froala.com/wysiwyg-editor/contact. Thus we can redirect it to the right team. Thank you.
