### ISSUE TITLE
Video/File uploading via S3 defaults to Blob upload

### ISSUE THREAD

**Issue by markedmondson** [froala/wysiwyg-editor#3012]
##### Expected behavior.
When the options `videoUpload` and `videoUploadToS3` or `fileUpload` and `fileUploadToS3` are set, drag and drop attachments still uploads to a blob only.

This is due to the video (and similar file) plugin check:

```
        // Upload as blob for testing purposes.
        if (editor.opts.videoUploadURL === null || editor.opts.videoUploadURL == DEFAULT_VIDEO_UPLOAD_URL) {
          _browserUpload(video)

          return false;
        }
```

Which should probably check for a value in `videoUploadToS3` and `fileUploadToS3` too.

Note, the docs are out of date here too, they still suggest that the default videoUpload is 'http://i.froala.com/upload'.

##### Actual behavior.
Video uploads to blob even when S3 video upload is set.

##### Steps to reproduce the problem.
https://jsfiddle.net/markedmondson/Lewpnd1j/

Upload a video - note that it doesn't even try and hit cloudfront.

##### OS.
MacOS High Sierra

##### Browser.
Chrome 67

**Comment by stefanneculai** [comment]
It's fixed on the current master branch from Github and will be included in the release 2.8.5.
