### ISSUE TITLE
Copy and paste not work (upload new image)

### ISSUE THREAD

**Issue by InciteGmbH** [froala/wysiwyg-editor#3014]
##### Expected behavior.
I would like to copy an image from froala editor and paste it as a second image to froala editor. The pasted image should upload the image as a new image. 

##### Actual behavior.
The pasted image is not uploaded as a new image

##### Steps to reproduce the problem.

1. Copy an image from outside into the editor -> everything works fine -> the MVC action UploadFroalaImage (imageUploadURL) on server is called and the image will be get from server (Read/GetMedia?...) -> everything great so far
 ![image](https://user-images.githubusercontent.com/27292796/44136307-a02b6924-a06c-11e8-8e59-1684590195e3.png)
 
![image](https://user-images.githubusercontent.com/27292796/44136315-a840ca1e-a06c-11e8-9f76-63a243930bf0.png)
 
![image](https://user-images.githubusercontent.com/27292796/44136329-af4a3af2-a06c-11e8-900a-698d35c8e7d4.png)

2. Now I copy the pasted google image from the editor with ctrl&c and paste it again -> now the Request  URL for get the image on server looks not correct (https://cors-anywhere.froala.com/https://....) -> the second GetMedia will be cancled and the headers are not present -> the error is
Access to Image at 'https://s30/p1/Read/GetMedia?parameterString=%7b%22accountId%22%3a%22default%22%2c%22baseMediaId%22%3a%22c0663f61-34fc-4ab4-b63b-fa76c4d3055f%22%7d' from origin 'null' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'null' is therefore not allowed access.
  
![image](https://user-images.githubusercontent.com/27292796/44136335-b6d3ec46-a06c-11e8-9aa5-43311b1d271a.png)

![image](https://user-images.githubusercontent.com/27292796/44136346-c2439e5a-a06c-11e8-9575-e3fb2302d1b9.png)
 
![image](https://user-images.githubusercontent.com/27292796/44136353-c83b1356-a06c-11e8-9833-18da4c5a4d88.png)

3. Now I found the option imageCORSProxy and set it to empty string -> This works but the image html is copied only and not uploaded as a new image. The UploadFroalaImage Action on server won't be called anymore.
 
![image](https://user-images.githubusercontent.com/27292796/44136360-cf138cd0-a06c-11e8-8039-15318d159b1d.png)

What can I do or what do I need to configure for my use case?

##### OS.
Windows Server 2012

##### Browser.
Chrome  68.0.3440.106 (Official Build) (64-bit)

**Comment by stefanneculai** [comment]
When pasting images from other websites, we are making them available for upload via a CORS proxy. Unfortunately, this doesn't work in all the cases because of the way websites are configured and there is not too much we could as far as we know.

**Comment by InciteGmbH** [comment]
The problem is not copying from other websites. The problem is when copy an image from froala editor to froala editor. Please see the steps below and the printscreens.

**Comment by stefanneculai** [comment]
@InciteGmbH are you able to reproduce this on our website as well?

**Comment by InciteGmbH** [comment]
No I can't because I don't know how to remove the "https://cors-anywhere.froala.com" in front of my url "https://s30/p1/Read/GetMedia?parameterString....." in the request. See this printscreen:

![image](https://user-images.githubusercontent.com/27292796/44321947-2b414380-a44b-11e8-97db-61aff47083ae.png)

It seems to work on your website with https://cors-anywhere.froala.com. As soon as the server url (imageUploadURL) is the own one it doesn't work anymore because of your url in front of the correct own url.

**Comment by InciteGmbH** [comment]
I don't want to disable the UploadRemoteUrl. Everything works well with upload the image. Only the upload will not be startet as a new image when I copy the image from froala editor to froala editor. If I do this, the following happens which I think this must be a bug. The requestURL looks like this:

**https://cors-anywhere.froala.com/https://s30/p1/Read/GetMedia?parameter...**

Why is the froala url in front of my url???

![image](https://user-images.githubusercontent.com/27292796/44382080-c140a100-a513-11e8-9a5e-e70b57dca273.png)

Please see this printscreen...there must be something strange at this RequestUrl:

![image](https://user-images.githubusercontent.com/27292796/44381971-2778f400-a513-11e8-8e00-b2f5c0728b94.png)
