### ISSUE TITLE
Shortcut with custom popup button not working

### ISSUE THREAD

**Issue by InciteGmbH** [froala/wysiwyg-editor#3015]
##### Expected behavior.
CTRL-d should insert acutal date.

##### Actual behavior.
CTRL-d does not working.

##### Steps to reproduce the problem.
Run this [jsfiddle ](https://jsfiddle.net/InciteGmbH/cav6mu41/) and press CTRL-d, this doesn't work. 
Run the jsfiddle again and press first the custom popup and then press CTRL-d, now it works.

##### OS.
Windwos 10

##### Browser.
Chrome actual version

**Comment by stefanneculai** [comment]
The shortcut is not working because the button is not included in the toolbar. The shortcuts are designed to work only for the buttons included in the editor toolbar: https://jsfiddle.net/froala/cav6mu41/8/.
