### ISSUE TITLE
Shortcut CTRL + . not working

### ISSUE THREAD

**Issue by InciteGmbH** [froala/wysiwyg-editor#3016]
##### Expected behavior.
Shortcut CTRL + . should activate ordered list.

##### Actual behavior.
Nothing happens when pressing CTRL + .

##### Steps to reproduce the problem.
Press CTRL+. in this [jsfiddle](https://jsfiddle.net/InciteGmbH/xyemc714/).

##### OS.
Win10

##### Browser.
Newest Chrome

**Comment by stefanneculai** [comment]
See: https://jsfiddle.net/froala/xyemc714/4/.
