### ISSUE TITLE
html.insert not at selected place

### ISSUE THREAD

**Issue by InciteGmbH** [froala/wysiwyg-editor#3018]
##### Expected behavior.
I would like to insert html text at a selected place 

##### Actual behavior.
The html text will be pasted always at the end of the document and not at the current selection.

##### Steps to reproduce the problem.
Here the video to see the behavior:
[InsertHtmlAtSelection.zip](https://github.com/froala/wysiwyg-editor/files/2292601/InsertHtmlAtSelection.zip)

Here the fiddle for reproducing:
https://jsfiddle.net/InciteGmbH/anv1Lpkb/

##### OS.
WindowsServer 2012

##### Browser.
Version 68.0.3440.106 (Offizieller Build) (64-Bit)

**Comment by stefanneculai** [comment]
See https://jsfiddle.net/froala/anv1Lpkb/43/.
