### ISSUE TITLE
ContentChanged event not fired when insertHtml

### ISSUE THREAD

**Issue by InciteGmbH** [froala/wysiwyg-editor#3020]
##### Expected behavior.
ContentChanged event should be fired when execute html.insert.

##### Actual behavior.
Event not fired

##### Steps to reproduce the problem.
See video here:
[ContentChangedNotFired.zip](https://github.com/froala/wysiwyg-editor/files/2292761/ContentChangedNotFired.zip)

See the fiddle for reproducing here:
https://jsfiddle.net/InciteGmbH/gw0xfzsb/

##### OS.
WindowsServer2012

##### Browser.
Version 68.0.3440.106 (Offizieller Build) (64-Bit)

**Comment by stefanneculai** [comment]
The `undo.saveStep` method should also be called: https://jsfiddle.net/froala/gw0xfzsb/42/.
