### ISSUE TITLE
Froala Editor getting crash  while editing.

### ISSUE THREAD

**Issue by pranayplash** [froala/wysiwyg-editor#3021]
##### Expected behavior.
Working file while editing

##### Actual behavior.
While editing text editing getting a crash.

##### Steps to reproduce the problem.
Add HTML from code view
View in normal view
try to edit, getting crash,

To check flow see video [https://cl.ly/3G2q0C270W1n](url)
editor version: froala_editor v2.8.1

It happens when deployed in NGINX in centos 7.
In locally WampServer with window 10, It's working fine

##### OS.
Any OS

##### Browser.
Chrome

**Comment by stefanneculai** [comment]
It is a known problem in version 2.8.1. Please upgrade to 2.8.4. Thank you.

**Comment by hsntareq** [comment]
it is happening in version 3.2.1
