### ISSUE TITLE
html mode does not save changes

### ISSUE THREAD

**Issue by zvermike** [froala/wysiwyg-editor#3024]
##### Expected behavior.
Changing should be saved from html mode

##### Actual behavior.
When i try to save changing from html mode, it dosen't save anything

##### Steps to reproduce the problem.
check screencast: https://drive.google.com/file/d/1BqhZyBjvyhveY4Rq7_8yWx5MvZNXTd9F/view

##### OS.
Linux

##### Browser.
Version 65.0.3325.181 (Official Build) (64-bit)

**Comment by stefanneculai** [comment]
Do you think it would be possible to make a jsFiddle to highlight the problem? That would speed-up things a lot. Here is a basic jsFiddle you could use as a starting point: https://jsfiddle.net/froala/wc5c3jhk/.

**Comment by zvermike** [comment]
@stefanneculai, it will be bit difficult because problem present just on React side, on part where we using html+jQuery it works fine;
should i reproduce my React component?

**Comment by stefanneculai** [comment]
@EmanuelGenially see https://github.com/froala/wysiwyg-editor/issues/1465#issuecomment-248594297.
