### ISSUE TITLE
can't insert embed code Froala edior

### ISSUE THREAD

**Issue by ivanyshak** [froala/wysiwyg-editor#3028]
##### Expected behavior.
when i embed code for example:
`<iframe width="420" height="315" src="https://www.youtube.com/embed/tgbNymZ7vqY"></iframe>`
![image](https://user-images.githubusercontent.com/22680852/44407554-1954c300-a567-11e8-8239-6c0406875942.png)
then click insert, video should be inserted;

##### Actual behavior.
when i click insert button, nothing happens

##### Steps to reproduce the problem.
i embed code then click insert and nothing happans;
if try to insert without src, it will work;
check video: https://drive.google.com/file/d/1JNpX8v_7MOOhTXRbx2AqJmqKz-WR2bH-/view

##### OS.
All

##### Browser.
All

**Comment by zvermike** [comment]
@stefanneculai, i've created an example: https://jsfiddle.net/x6cuve4j/21/
try to insert this iframe:
<iframe width="420" height="315"
src="https://www.youtube.com/embed/tgbNymZ7vqY">
</iframe>

**Comment by apuchkov** [comment]
This issue needs to be reopened. JSFiddle in the previous comment shows that it doesn't work.
