### ISSUE TITLE
styling not continued on empty line between paragraphs that have been double-spaced

### ISSUE THREAD

**Issue by raerae13** [froala/wysiwyg-editor#3030]
##### Expected behavior.
When styling is applied to a paragraph or line and the user hits return twice to create a double space, the styling is carried over to the next paragraph the user starts typing. If they return to the line between two paragraphs, the styling should be the same as the paragraph before and after.

##### Actual behavior.
When styling is applied to a paragraph or line and the user hits return twice to create a double space, the styling is carried over to the next paragraph the user starts typing, but if they return to the line between two paragraphs, the styling is missing.

##### Steps to reproduce the problem.
See attached video.

Select a large font size.
Type a line of text.
Hit return twice to double-space.
Type another line.
Click back into the empty line between the two lines you just typed.

##### OS.
PC using Windows 10

##### Browser.
Chrome Version 68.0.3440.106 (Official Build) (64-bit)
I've repro'd on Firefox and Edge, too.

[double spacing styling issue.zip](https://github.com/froala/wysiwyg-editor/files/2308286/double.spacing.styling.issue.zip)

**Comment by stefanneculai** [comment]
If you're like to keep the formatting, please use the `keepFormatOnDelete` option.

**Comment by raerae13** [comment]
Thanks! That worked for our use case.
