### ISSUE TITLE
Text converted to link after image insert.

### ISSUE THREAD

**Issue by YaroslavMolchan** [froala/wysiwyg-editor#3032]
##### Expected behavior.
When typing text and insert image from buffer and than continue typing text and press Space - I continue typing on the same line.
text
##### Actual behavior.
When typing text and insert image from buffer and than continue typing text it will convert to link under inserted image when I press Space button.

##### Steps to reproduce the problem.
I upload gif with the problem.

![froala](https://user-images.githubusercontent.com/9335727/44471870-7e76ea00-a635-11e8-9060-6c0bbc8afe5d.gif)

##### OS.
Any

##### Browser.
Any

**Comment by stefanneculai** [comment]
@YaroslavMolchan are you able to replicate this on our website?

**Comment by stefanneculai** [comment]
@YaroslavMolchan unfortunately, without having a way to reproduce it we cannot do too much. We've tried replicating it on our side without success.

**Comment by stefanneculai** [comment]
I am closing this as we don't have enough details to reproduce it. Would be happy to check it again once we get more details.
