### ISSUE TITLE
formatUL/formatOL toolbar buttons creating blank li's on nested lists

### ISSUE THREAD

**Issue by JordanMacHattie** [froala/wysiwyg-editor#3033]
##### Expected behavior.
Clicking _Ordered List_ or _Unordered List_ buttons on nested list item brings list item down one level.

##### Actual behavior.
Clicking _Ordered List_ or _Unordered List_ buttons on nested list item brings list item down one level and creates a blank list item below the selected line.

##### Steps to reproduce the problem.
[https://jsfiddle.net/wc5c3jhk/1235/](https://jsfiddle.net/wc5c3jhk/1235/)

##### OS.
Any.

##### Browser.
Any.

**Comment by mpomet** [comment]
Same problem with another conditions.

**Steps to reproduce the problem.**
Switch to "code view"
Paste the following example : 
```
<ul class="ul1">
    <li class="li1">Level 1</li>
    <li class="li1">last item of level 1</li>
	<ul class="ul1">
		<li class="li1">Level 2</li>
		<li class="li1">last item of level 2</li>
		<ul class="ul1">
			<li class="li1">Level 3</li>
			<li class="li1">last item of level 3</li>
		</ul>
	</ul>
</ul>
```
Switch to close code view.
The result is now a list that include new empty `<li><br>` elements.

**Comment by frankarensmeier** [comment]
I am struggling with a similar issue. Splitting the list element results in one extra (empty) list element. See here for an example: https://jsfiddle.net/rak4gsd9/
