### ISSUE TITLE
Inline style on image applied to class not element in iframe

### ISSUE THREAD

**Issue by btmdave** [froala/wysiwyg-editor#3037]
When using froala in iframe mode, if you select an image and choose `Inline` style.  It seems to apply this to `img.fr-dii` class, however when not using an iframe, this is applied directly to the img element.  Is there a way to have this applied to the element itself and not a class when using iframe?

**Comment by stefanneculai** [comment]
To use styles instead of classes, please disable the `useClasses` option.
