### ISSUE TITLE
way to prevent XSS link attacks?

### ISSUE THREAD

**Issue by george-norris-salesforce** [froala/wysiwyg-editor#3039]
Is there a way to prevent XSS attacks in links? 
For example you can paste `Payload: "><object data='data:text/html;base64,PHN2Zy9vbmxvYWQ9YWxlcnQoMSk+'>`
into a link URL popup.

**Comment by george-norris-salesforce** [comment]
Sorry, I mean I see the `beforeInsert` event. Which gives you.. `e, editor, link, text, attrs`
My question is, how to take those argument to the link, check them and modify the link. For instance, I'm trying to use this library [sanitize-url](https://www.npmjs.com/package/@braintree/sanitize-url) to test the link url and change it if it is not legal.

**Comment by stefanneculai** [comment]
@george-norris-salesforce see https://jsfiddle.net/froala/wc5c3jhk/1446/.
