### ISSUE TITLE
Cann't enable embedly button

### ISSUE THREAD

**Issue by ModernArtisan** [froala/wysiwyg-editor#3040]
##### Expected behavior.
Embed button appears after import embed.ly script following [this instruction](https://www.froala.com/wysiwyg-editor/examples/embedly)

##### Actual behavior.
Nothing happens, no errors, no messeges, nothing.

##### Steps to reproduce the problem.
Trying to enable ability to paste embed content by including embedly script
![Embedly button](https://image.prntscr.com/image/pjaC5YpBSEaysF37t5o-yA.png)
Have tried include embedly script before froala script, after, also in vue.js application with [this](https://github.com/froala/vue-froala-wysiwyg) wrapper in any variations, nothing happens.

##### OS.
MacOS High Sierra 10.13.6

##### Browser.
Any

**Comment by stefanneculai** [comment]
@ModernArtisan for the Embedly plugin to load correctly, please make sure that you include it from the third_party folder: 

```js
// Require Froala Editor Embedly js file.
require('froala-editor/js/third_party/embedly.min.js');
```
