### ISSUE TITLE
Feature request: adjustable width

### ISSUE THREAD

**Issue by mikicz** [froala/wysiwyg-editor#3041]
Currently Froala only has one attribute controlling the width, simply `width`, however height has `height`, `heightMin` and `heightMax`. Could the min and max options also be implemented for width?

**Comment by stefanneculai** [comment]
In a web app, the content usually grows vertically. It is unlikely to add the same options for width.

**Comment by stefanneculai** [comment]
We've just put together a public roadmap with the most popular features. 😍 There you can vote your favorite one, provide feedback or make new suggestions: https://wysiwyg-editor-roadmap.froala.com/public.
