### ISSUE TITLE
mobile safari prev/next input button don't close fullscreen

### ISSUE THREAD

**Issue by Mboulianne** [froala/wysiwyg-editor#3042]
##### Expected behavior.
The fullscreen should exit when focusing the next or previous input

##### Actual behavior.
The fullscreen remains when using the virtual keyboard previous / next input

##### Steps to reproduce the problem.
https://jsfiddle.net/byyo8mnd/688/
https://jsfiddle.net/byyo8mnd/688/show (more practical link for mobile use :D)

![image](https://user-images.githubusercontent.com/18729439/44852072-4d4b7a80-ac30-11e8-86a5-8c07b62b040b.png)

1. Open the fiddle on mobile ios
2. Focus the editor.
3. Go in fullscreen mode.
4. Focus again (since IOS will remove the focus when going full screen)
5. On the keyboard, push the up / down caret, this should focus the previous / next input.
6. The fullscreen remain on... the next input is focused annnddd the display is broken.  The user can't see what he's editing.

##### OS.
iphone 7
ios 11.4.1

iphone 8
ios 11.4

##### Browser.
mobile safari 11

**Comment by stefanneculai** [comment]
Unfortunately, we cannot detect when the next / previous buttons are hit on iOS. This would remain a `wontfix` for now.
