### ISSUE TITLE
Drag&Drop looses formatting

### ISSUE THREAD

**Issue by Christian-Seematter** [froala/wysiwyg-editor#3044]
##### Expected behavior.
The formatting is kept between drag&drop within the same Froala instance.

##### Actual behaviour.
Some formatting options are removed. 
![froala_native_drag drop](https://user-images.githubusercontent.com/1957259/44857679-97545080-ac70-11e8-8571-0e7de159df96.gif)

I found that at minimum the following are affected:
- Font Size
- Font Face
- Text Colour
- Background Colour

##### Steps to reproduce the problem.
- Format some text in a Froala instance.
- Drag&Drop it to a different line.
- Notice how some formatting is removed.

##### OS.
Mac OS X High Sierra 10.13.6 (17G65)

##### Browser.
Chrome 68.0.3440.106 (Official Build) (64-bit)

**Comment by stefanneculai** [comment]
Do you think it would be possible to make a jsFiddle to highlight the problem? That would speed-up things a lot. Here is a basic jsFiddle you could use as a starting point: https://jsfiddle.net/froala/wc5c3jhk/.

**Comment by Christian-Seematter** [comment]
@stefanneculai It works even in that jsfiddle with no changes. No options need to be set in Froala for this to occur. Just add text and a few empty lines, highlight the text, set the font size to 30 and drag&drop the resized text to another position in the editor. The dropped text will have discarded the formatting.

**Comment by Christian-Seematter** [comment]
@stefanneculai Hey there!

Were you table to reproduce the issue as described? I see you have added this to a milestone, just want to be sure the repro worked.

**Comment by stefanneculai** [comment]
Yes, it worked. That is why it is marked as `enhancement`.
