### ISSUE TITLE
Heavy Content timeout

### ISSUE THREAD

**Issue by jakeplaras** [froala/wysiwyg-editor#3045]
I've been trying to find a workaround with an issue in our system regarding pasting heavy content on to the editor.  We are integrating this on an angular/nodejs project. 

The problem is, when we try to paste content on it (maybe 5 paragraphs or more of text, and a little bit of small images) it makes the browser freeze. Sometimes it goes through, but it really does take some time to actually paste the content. 

This document is a great example of content that has a lot of text, with some images:
https://www.sec.gov/Archives/edgar/data/1623613/000162361316000046/myl10k_20151231xdoc.htm

We experience this on IE11, because most of our users use this.

Any ideas?

**Comment by stefanneculai** [comment]
Thanks for sending all the details @jakeplaras. Unfortunately, the lag comes from the browser pasting the content from the clipboard to the editor. There is not too much we could do from our side since this is the way the browser handles the large amount in the clipboard.
