### ISSUE TITLE
Font size varies between the template created in the application and in the message content in mailbox

### ISSUE THREAD

**Issue by ShanmugaPriyanV** [froala/wysiwyg-editor#3046]
##### Expected behavior.
Font size applied by using the Froala editor should be consistent in the message content received in mailbox

##### Actual behavior.
1.Font size varies between the template created in the application and in the message content received in mailbox
2. Font applied across the entire template is not consisten. Few paragraphs having 18 px and few are having 14 px

##### Steps to reproduce the problem.
1. Create a template with font size 18 px. 
2. Select all the content and apply font size 18 px
2. Trigger an email with the new template having font size as 18 px 

##### OS.
NA

##### Browser.
NA

**Comment by stefanneculai** [comment]
@ShanmugaPriyanV is there any way you could send us the HTML which was received in the email?

**Comment by ShanmugaPriyanV** [comment]
Pls refer the attached document. It is having the raw HTML data

**Comment by stefanneculai** [comment]
@ShanmugaPriyanV this is the HTML that is sent on the email?

**Comment by ShanmugaPriyanV** [comment]
Hi tefanneculai ,
Yes.  The content in the attached document is the same content sent on the email

**Comment by stefanneculai** [comment]
I am closing this here as we have a conversation over the support channel regarding it.
