### ISSUE TITLE
On Windows, BIU formatting shortcuts are reset to on after switching them off and hitting space

### ISSUE THREAD

**Issue by chrisdeeming** [froala/wysiwyg-editor#3047]
Following on from #2621 which was closed and not re-opened as I requested.

I can reproduce what is mentioned in the last couple of comments. I can't quite reproduce what @belazor is reporting, though I'll keep trying, but I suspect the behaviour that I can reproduce should be similar.

I've made a video:
https://youtu.be/XOwH4xZ-Zkw

I've slowed the video down to 2x speed. You do have to be very fast to repro it, hence slowing it down so you can more clearly see the exact steps.

I recorded it in BrowserStack, and I've enabled KeyCastr so you can see the exact keys being pressed.

You'll see me type some normal text, then I hit Cmd + B, I, U type a word and then I hit Cmd + B, I, U again. You can see the toolbar buttons deactivate. I then hit space, the space key doesn't register either, which is weird. But when I start typing again, B I U are highlighted again.

**Comment by stefanneculai** [comment]
@chrisdeeming which is the browser / OS that you're using?

**Comment by chrisdeeming** [comment]
Windows 10, Chrome 68.

Remember to reproduce it as in the video above you have to be quick. The video is slowed down to half speed.

Thing is, although I'm deliberately being almost too quick in the video, this does seem to be cropping up in normal usage so there may be other factors involved but there are at least now three different examples in the original issue #2621.

**Comment by stefanneculai** [comment]
We've tried this several times and we managed just a single time to reproduce it. Unfortunately, as it is so hard to have this happening, I am moving this for now to the `wontfix` category as the impact it has is not very high.
