### ISSUE TITLE
Table context menu behavior in IE is strange.

### ISSUE THREAD

**Issue by mirazero** [froala/wysiwyg-editor#3049]
##### Expected behavior.
In Chrome, work well.
If i pop up a table context menu in IE, i should be able to select the context menu item immediately, just as you would in Chrome.

##### Actual behavior.
In IE, when i pop up a table context menu, suddenly jump to the top of the editor.
(Only Cell color selection menu works normally)
In Chrome, works well.

##### Steps to reproduce the problem.
1. Enter the content in the editor so that the page is passed.
2. Add a table component.
3. Select a table cell and pop up the table context menu.
4. Attempts to select one of the context menus.

##### OS.
Windows

##### Browser.
IE11

[froala-error-IE.zip](https://github.com/froala/wysiwyg-editor/files/2343252/froala-error-IE.zip)

**Comment by stefanneculai** [comment]
Same with https://github.com/froala/wysiwyg-editor/issues/2719
