### ISSUE TITLE
Preventing Froala from modifying pasted HTML

### ISSUE THREAD

**Issue by altjx** [froala/wysiwyg-editor#3050]
##### Expected behavior.
I expect to be able to paste HTML, and have that HTML stay just the way I pasted it. 

##### Actual behavior.
Froala takes my HTML and starts modifying classes, adding/removing styles, etc. Quite annoying

##### Steps to reproduce the problem.
Just simply take any HTML code and paste it in there.

##### OS.
Mac OS X High Sierra (v 10.13.6)

##### Browser.
Google Chrome

##### Additional Information.
So I read over https://github.com/froala/wysiwyg-editor/issues/1386 as a reference and noticed that this guy added the following options when initiating Froala:

```
    htmlAllowedTags: ['.*'],
    htmlRemoveTags: [''],
    lineBreakerTags: [''],
    lineBreakerOffset: 0,
    linkAlwaysBlank: true,
    linkText: true,
    fullPage: true,
```

When I do this, just about everything works flawlessly. The only problem that I have, however, is that the textbox shrinks and there's no space to type. If I click in the area that I think I'm supposed to type, and type anything such as just a random letter, then everything resizes back to normal. Also, the font size of the tag that holds the placeholder defaults to 16 instead of 13 like it is before I enable this option.

Quite frankly, this only happens when I enable the ```fullPage``` option.

Is there a way to just simply allow me to paste my HTML contents, and Froala not do ANYTHING to it? Is this possible????

**Comment by altjx** [comment]
Ok so it looks like `fullPage` does not break anything. However, `iframe` does. This is one way I've been able to fix the weird sizing issue:

```
  // Fix Froala
  document.getElementsByClassName("fr-iframe")[0].style["height"] = "70px";
```

AFTER initializing Froala.

Now the textbox resizes itself after clicking on it. Just need to figure this out and I should be good to go.

**Comment by altjx** [comment]
Just simply changed the height to 90px and all is well now.

**Comment by stefanneculai** [comment]
@altjx Do you think it would be possible to make a jsFiddle to highlight the problem? That would speed-up things a lot. Here is a basic jsFiddle you could use as a starting point: https://jsfiddle.net/froala/wc5c3jhk/.

**Comment by altjx** [comment]
@stefanneculai hey man thanks so much for replying. I think I'm finally OK now with the way it pastes, since it seems like the email view still looks great after pasting my HTML.

The only question I do have now is that, when I enable `fullPage`, it seems that the text from the non-source-view is in Times New Roman font. Any suggestions on how I can fix that? It seems that `fontFamily` (from https://www.froala.com/wysiwyg-editor/docs/options#fontFamily) breaks Froala.

**Comment by altjx** [comment]
Just ran across an article where someone asked the same question and was able to resolve it using the following CSS:

`
 .fr-view {
  font-family: "Verdana", Georgia, Serif;
  font-size: 13px;
  color: #444444;
}
`

I'm gonna close this since I think I'm all good now. Thanks again.
