### ISSUE TITLE
Set Focus on cursor froala Editor Table

### ISSUE THREAD

**Issue by udaykirangoshika** [froala/wysiwyg-editor#3051]
When ever I'm adding the symbols on froala editor table, table losses the cursor position.

After checking the froala documentation I used :- $('selector').froalaEditor('events.focus', true);
after inserting the above line still table losses the cursor.

Please anyone help us.
Provide me steps.

**Comment by stefanneculai** [comment]
@udaykirangoshika could you please provide details about how we can reproduce this issue?

**Comment by stefanneculai** [comment]
I am closing this for now due to lack of response and would be happy to check it further if we get more details.

**Comment by alexgurrola** [comment]
This snapshot workaround fixes this issue:  https://github.com/froala/react-froala-wysiwyg/issues/105#issuecomment-661819495
