### ISSUE TITLE
Editor isn't auto sizing on load, but only after moving cursor

### ISSUE THREAD

**Issue by altjx** [froala/wysiwyg-editor#3052]
##### Expected behavior.
When I open up my editor (and let's say it has a LOT of content in it), it's automatically a small size of 20px. However, the minute I move the cursor, then it automatically expands to show the full contents.

##### Actual behavior.
It's actually defaulting to a size 20px. Doesn't auto expand until I move the cursor

##### Steps to reproduce the problem.
Simply paste the following code into the editor:
`<p>HELLO WORLD</p>

<p>HELLO WORLD</p>

<p>HELLO WORLD</p>

<p>HELLO WORLD</p>

<p>HELLO WORLD</p>

<p>HELLO WORLD</p>

<p>HELLO WORLD</p>

<p>HELLO WORLD</p>
`

And then save it (in my case I'm using it for a Rails application). Once I re-open it, it's default to 20px and you can't see anything until you click in there and move the cursor.

If, perhaps, I could just trigger the keydown event every time I load the Froala Editor, that should do the trick.

**Comment by altjx** [comment]
This fixed it for me.

```
  $(function() { $('textarea').froalaEditor({
    placeholderText: 'Place the body of your email in this section.',
    htmlAllowedTags: ['.*'],
    htmlRemoveTags: [''],
    lineBreakerTags: [''],
    lineBreakerOffset: 0,
    linkAlwaysBlank: true,
    linkText: true,
    iframe: true,
  }) }); 

  // Fix Froala
  document.getElementsByClassName("fr-iframe")[0].style["height"] = "90px";

  function resizeFroala() {
    var iframe = document.getElementsByClassName("fr-iframe")[0]
    var innerDoc = (iframe.contentDocument) ? iframe.contentDocument : iframe.contentWindow.document;

    // get the element in question
    const input = innerDoc.getElementsByTagName("body")[0];

    // dispatch keyboard events
    input.dispatchEvent(new KeyboardEvent('keyup', {'key':'y'}));
  }

  setTimeout(resizeFroala, 500);
```

**Comment by jemunk** [comment]
@altjx, I don't think your solution is perfect. You should not rely on a delay using setTimeout, as it sets some performance requirements to the client, that it must have initialized a certain state within the given 500 ms.
We currently have this issue and we found a pattern to when the issue happens. The thing is, that we've placed the Froala editor on a tab page. A tab page that is hidden on load. The content of the Froala editor is loaded by an Ajax call. So, if we open the tab page before the response of the Ajax call, the iframe height is perfectly adjusted to the content. But if not, the height is just 20px.
I assume Froala is not able to calculate the height of the iframe, when not visible in the DOM.

**Comment by jemunk** [comment]
.. continuing my last comment:
I found this Froala method that could be called just after making the Froala editor visible:
[https://www.froala.com/wysiwyg-editor/docs/methods#size.syncIframe](https://www.froala.com/wysiwyg-editor/docs/methods#size.syncIframe)
