### ISSUE TITLE
Style tag is being removed IF nothing exists before it

### ISSUE THREAD

**Issue by altjx** [froala/wysiwyg-editor#3053]
Ok, so I've seen a number of issues here regarding this. In my case, the style tag is being KEPT if I add a simple character in the source code view BEFORE the stye.

FOR EXAMPLE:

If I paste this:

```
a
<style whatever>

</style>
```

then the style tag is NOT removed when toggling away and back to the source code view.

However, if you simply go to the text editor and do something like:

```
<style>

random stuff here
</style>

```
and toggle away and back to the source code review, the style tag is removed. This is DESPITE the following options when initializing Froala Editor:

```
    htmlAllowedTags: ['.*'],
    htmlRemoveTags: [''],
```

Thoughts?

**Comment by altjx** [comment]
So apparently this must have been associated with an older version of Froala.

Is there any way that I can just simply tell Froala to stop screwing with my HTML? I've been battling issues all day just because of this one single problem: it won't stop screwing with my HTML. I thought those options would do the trick.

**Comment by stefanneculai** [comment]
Do you think it would be possible to make a jsFiddle to highlight the problem? That would speed-up things a lot. Here is a basic jsFiddle you could use as a starting point: https://jsfiddle.net/froala/wc5c3jhk/.

**Comment by altjx** [comment]
My apologies. Just been dealing with alot of back and forth minor issues. After updating Froala, I've been able to get a lot of things working. The only issue I'm having now is that my Froala Editor is displayed in a Bootstrap modal, and a fullscreen doesn't "full screen" it, it just full screens it in that model, but not the web page. I'll open a new issue for that one with jsfiddle example.
