### ISSUE TITLE
Stickers support 

### ISSUE THREAD

**Issue by thedotedge** [froala/wysiwyg-editor#3054]
Do you plan to support custom stickers in addition to emoticons/custom emoticons?
For example, `stickerSet` configuration option:

```
emoticonsSet: [
        { url: '/images/stickers/cat.png', desc: 'Imaginary cat' },
        { url: '/images/stickers/dog.png', desc: 'Inflated dog' }
      ]
```

Gallery is the closest it seems, but it's not really suitable for this purpose.

Sticker pack usages:
* https://tlgrm.eu/stickers
* https://www.facebook.com/stickers/

**Comment by stefanneculai** [comment]
Thanks for the feature request, @thedotedge. We don't keep `feature-requests` here, therefore I am closing it for now.

**Comment by stefanneculai** [comment]
We've just put together a public roadmap with the most popular features. 😍 There you can vote your favorite one, provide feedback or make new suggestions: https://wysiwyg-editor-roadmap.froala.com/public.
