### ISSUE TITLE
Image Upload dialog doesn't openning

### ISSUE THREAD

**Issue by AnibalDuarte** [froala/wysiwyg-editor#3055]
##### Expected behavior.
Image selection dialog when click on "Drop here" square of image plugin.

##### Actual behavior.
No dialog opens.

##### OS.
Windows 10

##### Browser.
Google Chrome

I need help to track the problem. My Froala configs are:

```
$('.froala').froalaEditor({
		height: 500,
		imageUpload: true,
		imageUploadURL: '/email_templates/upload_file',
		htmlAllowedTags: ['.*'], 
		htmlRemoveTags: [''],
		fullPage: true,
		lineBreakerTags: [''],
		linkAlwaysBlank: true 
	  });
```

PS.: if I use the "Quick Insert" button the dialog opens.

**Comment by stefanneculai** [comment]
As it works on a jsFiddle (https://jsfiddle.net/froala/wc5c3jhk/1538/), your problem most likely comes from a conflict with some JS or CSS from your app.

**Comment by franlab** [comment]
Hi @stefanneculai It doesn't work for me, neither on the fiddle or in the demo at https://www.froala.com/wysiwyg-editor/examples/init-on-image.

I am using chrome and froala 2.8.5

Thanks!
