### ISSUE TITLE
Full screen isn't going outside of modal

### ISSUE THREAD

**Issue by altjx** [froala/wysiwyg-editor#3056]
Here's an example: http://jsfiddle.net/1aeur58f/5550/

Is there any way to make full screen extend beyond the size of the modal, so that it takes up the entire page?

In the example, try to trigger the fullscreen mode from within the small modal. In my live example, I'm actually using a normal size modal, but being able to go beyond the size of that would be perfect.

Thanks for an amazing tool!

**Comment by zhaoyouliang** [comment]
I have the same requirement .
Thanks very much
