### ISSUE TITLE
Using Local Font Awesome 4.4.0 CSS

### ISSUE THREAD

**Issue by ThePokyWizard** [froala/wysiwyg-editor#3058]
##### Expected behavior.
Load local file of font-awesome

##### Actual behavior.
Loading font-awesome.min.css file via CDN

Is possible config Froala to use local font-awesome.min.css instead load from a CDN?

**Comment by stefanneculai** [comment]
Sure, you can load Font Awesome they way you need. It doesn't matter as long as it is loaded.
