### ISSUE TITLE
Toolbar overlaps text area when using predefined or min/max height using iPhone

### ISSUE THREAD

**Issue by bitplex-brad** [froala/wysiwyg-editor#3059]
##### Expected behavior.
The cursor appears at the top of the text edit area and the toolbar does not overlap.

##### Actual behavior.
The toolbar overlaps the text edit area causing the cursor to appear in the toolbar area.

![froala](https://user-images.githubusercontent.com/40725487/45127328-25718f00-b1bb-11e8-9e65-c232424069e9.PNG)

##### Steps to reproduce the problem.
Navigate to either of the Froala demo pages below using an iPhone and safari:

https://www.froala.com/wysiwyg-editor/examples/adjustable-height
https://www.froala.com/wysiwyg-editor/examples/predefined-height

##### OS.
iOS 11

##### Browser.
Safari (tested on iPhone 6 - iPhone 8)

**Comment by jamesdixon** [comment]
This is still an issue on the examples @bitplex-brad posted above. Specifically seeing this on my iPhone 12 Pro, iOS 14.4.2.

![IMG_1E53F90EFAA1-1](https://user-images.githubusercontent.com/110114/127201211-bf50f947-4735-4918-bce5-f783f824b16b.jpeg)
