### ISSUE TITLE
edit.off() makes content unselectable

### ISSUE THREAD

**Issue by twgraham** [froala/wysiwyg-editor#3060]
I came across this as I have a use case where I need to disable editing, but content should still be selectable.

### Expected behavior.
When using `edit.off()`, `contenteditable` is removed from the editor input, content is no longer editable, but I can still select it.

According to the documentation:
> Disable editor by removing the `contenteditable` attribute.

It doesn't mention anything about content not being selectable 

### Actual behavior.
`contenteditable` is removed from the editor input, content is no longer editable, but I **cannot** select content.

### Steps to reproduce the problem.
```JavaScript
$('.selector').froalaEditor('edit.off');
```

### OS.
macOS 10.13.6

### Browser.
Google Chrome 69.0.3497.81

**Comment by twgraham** [comment]
FYI - this is because the class `fr-disabled` is added to the editor input, the only thing it does is disable content selection.

**Comment by stefanneculai** [comment]
Thanks for reporting it, @twgraham. The `edit.off` was designed to disable editing and it also removes the selection because there is some internal methods which require that. As it was not designed by default to work as this, I am marking this ticket as a `feature-request` to be considered.

**Comment by ansh-les** [comment]
Any update on this?

**Comment by burtonrhodes** [comment]
I would also second this feature.  I currently have a js line to remove `fr-disabled` from the DOM after the editor is initialized. Definitely a hack, but seems to do the trick for now.  Ideally having edit.off(allowSelection) take a boolean parameter or options {} parameter?

**Comment by Benshakalaka** [comment]
Any update on this?

**Comment by ryandonnelly161** [comment]
Is this feature coming?
