### ISSUE TITLE
Adjusting font-family or color resets font size

### ISSUE THREAD

**Issue by riafoxdev** [froala/wysiwyg-editor#3063]
This issue is occurring in Angular: 5.1.2

##### Expected behavior.
Adjusting font-family and color changes only font-family and only color.

##### Actual behavior.
When changing the font-family or color of text that has previously been saved in a different font size than default, the font size gets set to default.

##### Steps to reproduce the problem.
Enter text into froala editor.
Modify font size of some of the text.
Save text content to database.
Reload page.
Modify font-family or color of the text that was adjusted in previous steps.

##### OS.
Microsoft Windows 10 Pro
Version 10.0.17134 Build 17134

##### Browser.
Google Chrome
Version 68.0.3440.106 (Official Build) (64-bit)

**Comment by stefanneculai** [comment]
@riafoxdev Could you please open this issue on the [Angular repo](https://github.com/froala/angular-froala-wysiwyg) instead? Also, it would be helpful if you could create a reproducible demo for it.
