### ISSUE TITLE
Files restrictions on fileAllowedTypes are not taken in consideration on file selection

### ISSUE THREAD

**Issue by iursevla** [froala/wysiwyg-editor#3065]
##### Actual behavior.
There's no filter for the MIMEs given in fileAllowedTypes when selecting from the file system.

##### Expected behavior.
Since we can provide allowed types for [files](https://www.froala.com/wysiwyg-editor/docs/options#fileAllowedTypes), then we can filter upon file selection from the file system, using [accept attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file#Limiting_accepted_file_types). Currently images, and videos are using the filter so i guess this could be easily implemented.

**Comment by stefanneculai** [comment]
Thanks for sending this.
