### ISSUE TITLE
Undo does not trigger image.inserted/image.removed/image.replaced events

### ISSUE THREAD

**Issue by joeholdcroft** [froala/wysiwyg-editor#3067]
##### Expected behavior.

When undoing, events should be triggered if the act of undoing results in any images being added/removed/replaced.

For context, I need this because we need to maintain an array of the inline images in the editor for our backend. This works well until the user starts using the undo functionality, and we can't see any way around this currently.

##### Actual behavior.

No image events are fired when using undo.

##### Steps to reproduce the problem.

Add an image, delete it, undo. You'll get events for adding the image and deleting it, but not when undoing the delete (which adds it back).

##### OS.

Mac OS X 10.13.6

##### Browser.

Chrome Version 68.0.3440.106 (Official Build) (64-bit)

**Comment by stefanneculai** [comment]
On undo, the `image.loaded` is being triggered.
