### ISSUE TITLE
Need a single imageManager.deleteImage event

### ISSUE THREAD

**Issue by Sayan751** [froala/wysiwyg-editor#3068]
##### Expected behavior.
Injecting an event handler for deleting an image from image manager should be possible. 

At present, the Froala editor handles the deletion of images from image manager by itself. It provides 2 events for this, namely: `imageManager.beforeDeleteImage, imageManager.imageDeleted`. Such approach can be limiting so to say. 

For example, let's say my REST endpoint to delete the images is `my.base.url/images/{id}`, where `id` is the identifier of the image to be deleted. Then, I can configure the editor with `imageManagerDeleteURL: "my.base.url/images/"`. And thereafter, manipulate `imageManagerDeleteURL` in `imageManager.beforeDeleteImage` (add the id), and `imageManager.imageDeleted` (remove the id) events. Moreover, if there is a failure from server, on which I need to act and show some sort of message to the user, then I need to use `imageManager.error`, with `error.code` 21. Note that in case of server error, I need to remove the `id` from  `imageManagerDeleteURL`, as I did in `imageManager.imageDeleted`.

Though, the above said scenario is just an example, I think such use cases are not uncommon. This unnecessarily complicates the logic for image upload. Instead, it would be lot simpler, if there would have been a single event, such as `imageManager.deleteImage`, where an event handler can be injected that does whatever needs to be done. If such event handler is present, Froala should call that instead of the default one. When a simple `true` is returned from this handler, Froala can remove the image from image manager (DOM).

Of course a better and sensible name can be used instead of `imageManager.deleteImage`. I am leaving that decision for the core contributors.

##### Actual behavior.
There is no such events.

##### Steps to reproduce the problem.
Not applicable.

##### OS.
Not applicable.

##### Browser.
Not applicable.

**Comment by stefanneculai** [comment]
It's already on our list to do that: https://wysiwyg-editor-roadmap.froala.com/public/ideas/3547. Please make sure you upvote it.
