### ISSUE TITLE
froala editor not working on firefox

### ISSUE THREAD

**Issue by leoincedo** [froala/wysiwyg-editor#3069]
##### Expected behavior.
i was try using editor from froala demo, but not working

toolbar and menu not response

##### Actual behavior.

i think just working.

##### Steps to reproduce the problem.
just demo site

##### OS.
OSX high sierra 1.36.

##### Browser.
firefox 62+

**Comment by stefanneculai** [comment]
We don't have any such problem. Could you please check if you have any plugins installed which might not allow it to work correctly?
