### ISSUE TITLE
When I delete the last line, delete the format

### ISSUE THREAD

**Issue by EmanuelGenially** [froala/wysiwyg-editor#3073]
##### Expected behavior.
When you erase the last line keep the format

##### Actual behavior.
When I delete the last line, delete the format
![bug-froala](https://user-images.githubusercontent.com/34505409/45613629-39dd4380-ba67-11e8-966e-2b356c437f7b.gif)

##### Steps to reproduce the problem.

1. Write a text with two paragraphs.
2. Remove last line.

##### OS.
macOs Sierra v.10.12.6

##### Browser.
The problem in all browsers.
Google Chrome Version 68.0.3440.106 (Official build) (64 bits)

**Comment by stefanneculai** [comment]
@EmanuelGenially please use the keepFormatOnDelete in order to keep the format.
