### ISSUE TITLE
Cursor disappears when deleting new line after a contenteditable="false" element

### ISSUE THREAD

**Issue by sChupin** [froala/wysiwyg-editor#3074]
##### Expected behavior.
The cursor should be displayed at the end of the _contenteditable="false"_ element and it should be possible to delete it by pressing backspace.

##### Actual behavior.
On chrome: The cursor disappears and it is impossible to delete the _contenteditable="false"_ element by pressing backspace.

On Firefox: The cursor is correctly displayed but it is impossible to delete the _contenteditable="false"_ element.

##### Steps to reproduce the problem.
- Insert some HTML in the editor (via a button) with attribute _contenteditable=false_ and class _fr-deletable_.
- Add a new line by pressing Enter.
- Press backspace to delete the new line.
- Press backspace again should delete the inserted HTML.

Here is a fiddle to reproduce the issue: https://jsfiddle.net/x9ja58wo/8/

##### OS.
macOS High Sierra 10.13.6

##### Browser.
Opera 55.0
Google Chrome 69.0
FireFox 61.0.2

**Comment by stefanneculai** [comment]
We're aware of this problem and we're looking into alternatives way of disabling editing rather than using `contenteditable="false"`. Unfortunately, this is a browser rendering problem and until we come with the new way there is not too much we could do about it.
