### ISSUE TITLE
Embedded posts in Chrome 69

### ISSUE THREAD

**Issue by DmitryVolkovTulaco** [froala/wysiwyg-editor#3075]
##### Expected behavior.
Example: 
![fe-test-1](https://user-images.githubusercontent.com/18539677/45630530-8f364680-baa1-11e8-8706-77e54654760a.png)

##### Actual behavior.
(Describe actual behaviour here)
When I use Editor in view-mod( FroalaEditorView) with embedded social media posts, they overlap the below sections/content.
 Example: 
![fe-test-2](https://user-images.githubusercontent.com/18539677/45630598-abd27e80-baa1-11e8-9d3c-2d1176e77ef1.png)
By the red line, I marked the place where he cuts off the post.

##### Steps to reproduce the problem.
1. Add some instagram, twitter posts. Save it.
2. Open the page with FroalaEditorView, from Chrome(IOS/Android)

##### OS.
(IOS/Android)

##### Browser.
(Chrome 69)

**Comment by DmitryVolkovTulaco** [comment]
Upd.
I also reproduce this bug on [Demo Page](https://www.froala.com/wysiwyg-editor/examples/embedly)
@stefanneculai can you look at this issue.

**Comment by stefanneculai** [comment]
@DmitryVolkovTulaco could you please let us know the steps to reproduce it on https://www.froala.com/wysiwyg-editor/examples/embedly? Thanks.

**Comment by DmitryVolkovTulaco** [comment]
@stefanneculai 
1) Open Chrome 69v on your ios, adndroid device.
2) Add some twitter, instagram posts.
Even in Editor's input it will look incorrect.
3) Open the FroalaEditorView Component with pre-saved model.

**Comment by stefanneculai** [comment]
Thanks for the details, Dmitry. We've checked it and unfortunately with the events that we get from Embedly that is the best we could do for syncing the editor height. I am marking this as `wontfix` for now and we would try to discuss with the Embedly team about it.
