### ISSUE TITLE
Pressing the tab key causes the cursor to be misaligned（iPhone bug ）

### ISSUE THREAD

**Issue by zhaoyouliang** [froala/wysiwyg-editor#3076]
##### Expected behavior.
(Describe expected behaviour here)

##### Actual behavior.
(Describe actual behaviour here)
The cursor gets confused when you click TAB （Use the external keyboard on the iPhone App）
##### Steps to reproduce the problem.
(Describe the steps to reproduce the problem here. A [jsFiddle](https://jsfiddle.net/froala/wc5c3jhk/) is awesome when possible.)
Create a bulletedList /numberdList
Then tab to create a secondary set of bullets
Pressing enter to create a new bulletedList brings the user back to the other position.
##### OS.
(OS name and version here)
iPhone 11.3 . 
##### Browser.
(Browser name an version here)
 Platform  NativeScript.

[Froala_iPhone,bug.zip](https://github.com/froala/wysiwyg-editor/files/2391488/Froala_iPhone.bug.zip)

**Comment by stefanneculai** [comment]
Thanks for reporting this. Unfortunately, on iOS we don't get the TAB key correctly from the keyboard and because of that, we cannot indent the list. As a workaround, we would suggest indenting list by using the toolbar indentation buttons.
