### ISSUE TITLE
pasting from an email

### ISSUE THREAD

**Issue by willhoyle** [froala/wysiwyg-editor#3079]
##### Expected behavior.
Images pasted with an external URL (http://somethingelse.com/blahblah) are uploaded to my server (at imageUploadURL param) and then I can save the image to my server and return the URL link to my stored image URL.

##### Actual behavior.
When pasting from an email client (gmail, outlook, etc), images are not uploaded to my server by means of imageUploadURL. When looking at the src="" attribute for the <img /> that is pasted, the original src url is the same as what the src was in the email client. (http://somethingelse.com/blahblah)

##### Steps to reproduce the problem.
Just paste any email that has a picture in the editor and check the source. It will be the same as the email client url.

##### OS.
Linux 16.04

##### Browser.
Chrome 64

**Comment by stefanneculai** [comment]
@willhoyle we don't have such a feature at this moment. It would be great if you could put a request for it here: https://wysiwyg-editor-roadmap.froala.com.
