### ISSUE TITLE
Toolbar button colors and custom icon text.

### ISSUE THREAD

**Issue by ibtisamniche-vteams** [froala/wysiwyg-editor#3080]
Hi!
1) I am using froala 2.8.5 in my angular project. I want to change toolbar buttons color as the default color is #222 and I want to change it to #263238. I have checked the options in froala documentation but there is no option to change color for toolbar buttons. Is there any option to do that?
2) By default the file upload icon is simple outline file icon in froala editor. I want to change the icon. How can I do that?
Thanks.

**Comment by stefanneculai** [comment]
See: https://www.froala.com/wysiwyg-editor/customize and https://www.froala.com/wysiwyg-editor/docs/concepts/custom/icon. 

PS: We're using this channel mainly for bug tracking. For support, please reach us via https://www.froala.com/wysiwyg-editor/contact.
