### ISSUE TITLE
can't embed iframe because of excessive space between attributes

### ISSUE THREAD

**Issue by zvermike** [froala/wysiwyg-editor#3081]
##### Expected behavior.
**Can't embed iframe code because of excessive space!!!**
![image](https://user-images.githubusercontent.com/22680852/44407554-1954c300-a567-11e8-8239-6c0406875942.png)
then click insert, video should be inserted;

##### Actual behavior.
when i click insert button, nothing happens

##### Steps to reproduce the problem.
sometimes when user is trying to embed iframe code he can just copy some code and paste it in right place but there can be excessive space between attributes or open and close tags;
if there is some excessive space user will not be able to embed this code;
check screencast: https://drive.google.com/file/d/1PGHD4IkrJ4KusgMzKaRhvgV8nPvBFaOm/view 

**maybe there is some option in Froala what can remove excessive space**?

##### OS.
All

##### Browser.
All

**Comment by stefanneculai** [comment]
Do you think it would be possible to make a jsFiddle to highlight the problem? That would speed-up things a lot. Here is a basic jsFiddle you could use as a starting point: https://jsfiddle.net/froala/wc5c3jhk/.
