### ISSUE TITLE
Cursor jumps at the bottom of the editor container

### ISSUE THREAD

**Issue by naegahyung** [froala/wysiwyg-editor#3082]
##### Expected behavior.
When an user presses 'enter' for a new line and starts typing, the cursor stays on same line.

##### Actual behavior.
When an user presses 'enter' for a new line, a padding on the bottom of the editor container appears. When user starts to type, the padding disappears, creating a jumpy behavior.

![Video to explain the behavior](https://user-images.githubusercontent.com/37382742/45760906-2530b500-bbf9-11e8-8b7d-cc2e77c33662.gif)

##### Steps to reproduce the problem.
```
const html = `
<!DOCTYPE html>
    <html>
        <head>
          <meta charset="utf-8" />
          <meta  name='viewport' content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' />
              <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css">
              <link href="https://cdnjs.cloudflare.com/ajax/libs/froala-editor/2.5.1/css/froala_editor.pkgd.min.css" rel="stylesheet" type="text/css" />
              <link href="https://cdnjs.cloudflare.com/ajax/libs/froala-editor/2.5.1/css/froala_style.min.css" rel="stylesheet" type="text/css" />
              <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
              <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/froala-editor/2.5.1/js/froala_editor.pkgd.min.js"></script>
        </head>
        <body>
          <textarea></textarea>
          <script>
            $(function() {
              $('textarea').froalaEditor({
                height: 300,
              })
            });
          </script>
        </body>
      </html>`
```

```
<WebView
   key="froala"
   source={{
      html:  this.html(this.props.value),
      baseUrl: `file://${localPath}/`,
   }}
/>
```

You can duplicate this issue by going to Safari through iPad simulator and browse https://jsfiddle.net/wc5c3jhk/1640/.

##### OS.
iOS

##### Browser.
iPad simulator (10.5 inch)

**Comment by stefanneculai** [comment]
Thanks for reporting this. We just checked it and unfortunately, there is not too much we could do about it. When you start typing, the browser is automatically doing a reposition for the cursor thus the scroll..

**Comment by PvanHengel** [comment]
Hi it must be a recent change that causes it because a few releases back we do not see the issue with the same version of browser

**Comment by naegahyung** [comment]
@stefanneculai Hi, I was able to isolate the version that introduced this bouncing cursor. Is it possible to know what changed between the version 2.7.5 to 2.7.6?
