### ISSUE TITLE
Upload of image to own server doesn't work

### ISSUE THREAD

**Issue by appyours** [froala/wysiwyg-editor#3083]
Hi there,

I can't get it to work that an inserted image is uploaded to a directory at my webserver.
(upload to the froala server works fine).

I added to the arguments of the editor:  imageUploadURL: '/mailing-imgs',	
and have added the lib image.min.js

Getting following info in console.
{code: 3, message: "Error during file upload."}
add.php:239 <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>403 Forbidden</title>
</head><body>
<h1>Forbidden</h1>
<p>You don't have permission to access /mailing-imgs/
on this server.<br />
</p>
</body></html>

Let me say that the directory is there and it has a 755 permission.

Any suggestions?
Thx Tim

**Comment by stefanneculai** [comment]
It looks like there is a problem with configuring the server. For tech support, please reach us via https://www.froala.com/wysiwyg-editor/contact.
