### ISSUE TITLE
Inline Editing: IE not removing extra <br> when there is content

### ISSUE THREAD

**Issue by BrianLaughlan** [froala/wysiwyg-editor#3086]
I have seen in other issues that the extra `<br>` that is added is to allow the div to be editable. This is fine, however, it should be gone when there is content. 

##### Expected behavior.
IE should do the same as **every other browser** and remove the `<br>` when there is content.

##### Actual behavior.
IE is not removing the  `<br>` when there is content like it does in every other browser.

See here for IE: https://doc.enuvo.ch/88b30315b5.gif
See here for Chrome: https://doc.enuvo.ch/2eec109fc6.gif

##### Steps to reproduce the problem.
Empty out an inline editor, there is a  `<br>` shown, type something, the  `<br>` disspears. This should also be the case in IE.

##### OS.
Windows 10

##### Browser.
IE11

**Comment by stefanneculai** [comment]
Unfortunately, we cannot remove it in IE as it would break the way the editable area would work.

**Comment by BrianLaughlan** [comment]
In what way?

I am not talking about removing it completely. I am talking about removing it when there is content. If there is content in the editable element, why is the `<br>` still needed in IE? when it is not needed in any other browser.

**Comment by stefanneculai** [comment]
Unfortunately, in IE enter is not working correctly in certain cases if we don't have that ending BR. IE is behaving completely different and sometimes we have to use such dirty tricks.
