### ISSUE TITLE
ClearFormattion is not working with ordered list and bullet list

### ISSUE THREAD

**Issue by raaj0505** [froala/wysiwyg-editor#3087]
##### Expected behavior.
Clicking on Clear formatting button should clear ordered and ordered list

##### Actual behavior.
(Describe actual behaviour here)
Clicking on Clear formatting button is not clearing ordered and ordered list

##### Steps to reproduce the problem.
Open https://www.froala.com/wysiwyg-editor
add some lines
click on ordered list
now select all content 
click Clear formatting button

##### OS.
Window 10

##### Browser.
Chrome
 Version 69.0.3497.100 (Official Build) (64-bit)

**Comment by stefanneculai** [comment]
The editor is designed to clear the inline formatting, such as bold, italic, etc.. It is not clearing the paragraph styles such as lists.
