### ISSUE TITLE
<br> display nothing

### ISSUE THREAD

**Issue by javeriaanwer** [froala/wysiwyg-editor#3089]
hi,
I am setting "< p></ br></ p>" html string in editor and it shows empty state of editor wherelse it show a line break.

$('#editor').froalaEditor('html.set', "< p></ br></ p>");

you can verify it from [here]( https://codepen.io/anon/pen/XPLJxm?editors=1010)

please look into this. 

Regards,
Javeria Anwer

**Comment by stefanneculai** [comment]
That is considered by the editor to be an empty state when you are using the ENTER_P mode. This is how it was actually designed in the first place.

**Comment by javeriaanwer** [comment]
I set editor to all three modes mentioned [here](https://www.froala.com/wysiwyg-editor/docs/options#enter), It did not produce line break.
you can see it over [here](https://codepen.io/anon/pen/YOmqzx?editors=0010)
