### ISSUE TITLE
fr-view class is screwing up the look and feel of my site

### ISSUE THREAD

**Issue by angusgrant** [froala/wysiwyg-editor#3090]
Hi I am building a CMS platform in which many bits of content are editable in the Froala editor but not all. As many bits of the page are editable and I don't necessarily have any containing html tags (or want to add a css class to each every element in the page that contains Froala editable text)  
I'm adding the fr-view class to the BODY element.

##### Expected behavior.
I only expect froala's CSS/JS to affect styles of elements added via the froala editor. Not existing HTMLs added outside the editor.  

##### Actual behavior.
One issue is that Froala is applying styling to all TABLE TD elements  that are inside the fr-view class. However Froala should only be applying it to table elements directly added by the froala editor itsself.  

My expectation is that all html elements added via the froala editor should have there own fr-* class which should also be present in the froala_style.css stylesheet therefore shielding them from any existing styles applied to these elements. 

##### Steps to reproduce the problem.
Cut and paste TABLE HTML outside of the froala editor.  

https://jsfiddle.net/wc5c3jhk/1731/

Expectation in this example would be that the table should only have a border on the bottom of each TD element (as applied by my existing css)

**The following lines of the CSS are problematic for me:**

 .fr-view span[style~="color:"] a {
  color: inherit;
}
.fr-view strong {
  font-weight: 700;
}
.fr-view table {
  border: none;
  border-collapse: collapse;
  empty-cells: show;
  max-width: 100%;
}
...
.fr-view table td,
.fr-view table th {
  border: 1px solid #dddddd;
}
.fr-view table td:empty,
.fr-view table th:empty {
  height: 20px;
}
.fr-view table td.fr-highlighted,
.fr-view table th.fr-highlighted {
  border: 1px double red;
}
.fr-view table td.fr-thick,
.fr-view table th.fr-thick {
  border-width: 2px;
}
.fr-view table th {
  background: #e6e6e6;
}
.fr-view hr {
  clear: both;
  user-select: none;
  -o-user-select: none;
  -moz-user-select: none;
  -khtml-user-select: none;
  -webkit-user-select: none;
  -ms-user-select: none;
  page-break-after: always;
}
....

.fr-view pre {
  white-space: pre-wrap;
  word-wrap: break-word;
}
.fr-view[dir="rtl"] blockquote {
  border-left: none;
  border-right: solid 2px #5e35b1;
  margin-right: 0;
  padding-right: 5px;
  padding-left: 0px;
}
.fr-view[dir="rtl"] blockquote blockquote {
  border-color: #00bcd4;
}
.fr-view[dir="rtl"] blockquote blockquote blockquote {
  border-color: #43a047;
}
.fr-view blockquote {
  border-left: solid 2px #5e35b1;
  margin-left: 0;
  padding-left: 5px;
  color: #5e35b1;
}
.fr-view blockquote blockquote {
  border-color: #00bcd4;
  color: #00bcd4;
}
.fr-view blockquote blockquote blockquote {
  border-color: #43a047;
  color: #43a047;
}
....
.fr-view img {
  position: relative;
  max-width: 100%;
}
##### OS.
Windows

##### Browser.
Chrome / FF etc...

**Comment by stefanneculai** [comment]
That is because on paste, the editor is removing by default the styles and classes. However, you can control that through the `pasteDeniedTags` option: https://jsfiddle.net/froala/wc5c3jhk/1740/.

**Comment by angusgrant** [comment]
Hi @stefanneculai  I don't think you are understanding the problem. I'm talking about html elements existing OUTSIDE of the froala editor

**Comment by shnigi** [comment]
I have this exact same problem. I have added fr-view on my content div and Froala styles are affecting previously added tables.
