### ISSUE TITLE
Froala style sheet is screwing up my website pls advise??

### ISSUE THREAD

**Issue by angusgrant** [froala/wysiwyg-editor#3092]
Hi @stefanneculai  I'm creating this ticket again as your previous response did not answer my question or help. Am i doing something wrong in implementation and how am i to resolve this??? 

Previous ticket was https://github.com/froala/wysiwyg-editor/issues/3090

Hi I am building a CMS platform in which many bits of content are editable in the Froala editor but not all. As many bits of the page are editable and I don't necessarily have any containing html tags (or want to add a css class to each every element in the page that contains Froala editable text)
I'm adding the fr-view class to the BODY element.

Expected behavior.
I only expect froala's CSS/JS to affect styles of elements added via the froala editor. Not existing HTMLs added outside the editor.

Actual behavior.
One issue is that Froala is applying styling to all TABLE TD elements that are inside the fr-view class. However Froala should only be applying it to table elements directly added by the froala editor itsself.

My expectation is that all html elements added via the froala editor should have there own fr-* class which should also be present in the froala_style.css stylesheet therefore shielding them from any existing styles applied to these elements.

Steps to reproduce the problem.
Cut and paste TABLE HTML outside of the froala editor.

https://jsfiddle.net/wc5c3jhk/1731/

Expectation in this example would be that the table should only have a border on the top of each TD element (as applied by my existing css)

The following lines of the CSS are problematic for me:

.fr-view span[style~="color:"] a {
color: inherit;
}
.fr-view strong {
font-weight: 700;
}
.fr-view table {
border: none;
border-collapse: collapse;
empty-cells: show;
max-width: 100%;
}
...
.fr-view table td,
.fr-view table th {
border: 1px solid #dddddd;
}
.fr-view table td:empty,
.fr-view table th:empty {
height: 20px;
}
...
.fr-view table th {
background: #e6e6e6;
}
.fr-view hr {
clear: both;
user-select: none;
-o-user-select: none;
-moz-user-select: none;
-khtml-user-select: none;
-webkit-user-select: none;
-ms-user-select: none;
page-break-after: always;
}
....

.fr-view pre {
white-space: pre-wrap;
word-wrap: break-word;
}
.fr-view[dir="rtl"] blockquote {
border-left: none;
border-right: solid 2px #5e35b1;
margin-right: 0;
padding-right: 5px;
padding-left: 0px;
}
.fr-view[dir="rtl"] blockquote blockquote {
border-color: #00bcd4;
}
.fr-view[dir="rtl"] blockquote blockquote blockquote {
border-color: #43a047;
}
.fr-view blockquote {
border-left: solid 2px #5e35b1;
margin-left: 0;
padding-left: 5px;
color: #5e35b1;
}
.fr-view blockquote blockquote {
border-color: #00bcd4;
color: #00bcd4;
}
.fr-view blockquote blockquote blockquote {
border-color: #43a047;
color: #43a047;
}
....
.fr-view img {
position: relative;
max-width: 100%;
}

OS.
Windows

Browser.
Chrome / FF etc...

**Comment by stefanneculai** [comment]
@angusgrant you're wrapping everything in a .fr-view class and that is why you get the editor style applied. Updated jsFiddle here: https://jsfiddle.net/froala/wc5c3jhk/1743/.

Screenshot with the problem:
<img width="421" alt="screen shot 2018-09-26 at 16 50 46" src="https://user-images.githubusercontent.com/637004/46084486-7538ea00-c1ac-11e8-87b4-e541386385d5.png">

**Comment by angusgrant** [comment]
Yes @stefanneculai  as i tried to explain to you i'm doing this for a reason and that is that most content can be editable in the Froala editor and therefore i need all changes to be contained within the fr-view container class to get the froala styling... However. not all editable content will be contained with its own html element in which case how do i hook this class without it affecting all other content on the page?

**Comment by stefanneculai** [comment]
Unfortunately, we do not have an alternative for displaying the content. What I would recommend in this case is to use an empty DIV which has just that class and wrap the editor output with it.

**Comment by angusgrant** [comment]
OK thanks the problem comes when it is html that is inline html not block html. I need to somehow differentiate between the two and contain one within a span and the other within a div. I do still feel that if froala was applying a fr-* class to every element that it adds it would be easy to apply the froala styling to just the froala content... However for some reason this is not the case is there a reason for this?

**Comment by stefanneculai** [comment]
All the editor content should be wrapped within an element with the `fr-view` class when it is being displayed: https://www.froala.com/wysiwyg-editor/docs/overview#frontend. Version 1 was working more as you need and that was creating a lot of troubles and this is how we end to have it set up like this.

**Comment by angusgrant** [comment]
Is there somewhere I can go to read / understand why  froala ended up making these design decisions? thanks @stefanneculai

**Comment by stefanneculai** [comment]
Sure, there is a full discussion here: https://github.com/froala/wysiwyg-editor/issues/259. All comments are for V1, so please note that they might not apply on V2.
