### ISSUE TITLE
Copying and pasting nested lists from Pages is not working.

### ISSUE THREAD

**Issue by thiagopradi** [froala/wysiwyg-editor#3093]
##### Expected behavior.
- First item
  - Second nested item

##### Actual behavior.
- First item
- (blank line)
  - Second nested item

##### Steps to reproduce the problem.
- Create a document with nested lists using Pages (I've created and attached a sample document [here](https://www.dropbox.com/s/ignkdsmr1vroys0/sample-bug-froala.pages?dl=0))
- Access https://www.froala.com/wysiwyg-editor and copy / paste the content of the document.

##### OS.
OSX 10.13.6

##### Browser.
Chrome 69.0.3497.100

#### Details
I've tried to play with the `froalaEditor.paste.beforeCleanup` callback to cleanup the copied content and render the text correctly (with no luck). Here is the content that is copied from Pages:

``` html
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta http-equiv="Content-Style-Type" content="text/css">
<title></title>
<meta name="Generator" content="Cocoa HTML Writer">
<meta name="CocoaVersion" content="1561.6">
<style type="text/css">
li.li1 {margin: 0.0px 0.0px 0.0px 0.0px; font: 11.0px Helvetica; color: #000000; -webkit-text-stroke: #000000}
span.s1 {font: 12.0px Helvetica; color: #000000; -webkit-text-stroke: 0px #000000}
span.s2 {font-kerning: none}
span.s3 {font: 12.0px Helvetica; color: #000000}
</style>
</head>
<body>
<ul>
<li class="li1"><span class="s1"></span><span class="s2">First item</span></li>
<ul>
<li class="li1"><span class="s3"></span><span class="s2">Second nested item</span></li>
</ul>
</ul>
</body>
</html>
```

**Comment by stefanneculai** [comment]
Thanks for opening this ticket @thiagopradi. At this moment, we don't have support for pasting from Apple Pages. I would recommend to open a feature request for that here: https://wysiwyg-editor-roadmap.froala.com/public.
