### ISSUE TITLE
Caret is visible when selecting images and media

### ISSUE THREAD

**Issue by felskov** [froala/wysiwyg-editor#3094]
##### Expected behavior.
When I select an image, the caret should disappear and the border highlighting the image should be the only visible indication of my focus.

##### Actual behavior.
The caret is still being displayed, offsetting the border around the image slightly.

![udklip](https://user-images.githubusercontent.com/1436954/46140339-1f6a4d80-c251-11e8-82e3-95b64742540e.png)

##### Steps to reproduce the problem.
1. Insert an image
2. Click the image

##### OS.
Windows 10

##### Browser.
IE11

**Comment by felskov** [comment]
I think that this thread on StackOverflow has a solution to the issue:

https://stackoverflow.com/questions/20168381/clear-textbox-selection-in-ie11-using-javascript

**Comment by stefanneculai** [comment]
@felskov are you able to reproduce it with the latest version 2.9.1?

**Comment by felskov** [comment]
@stefanneculai My client has since dropped support for IE11, so they're not interested in spending time upgrading the editor until https://github.com/froala/wysiwyg-editor/issues/2887 is fixed. That means I wont be able to help verify your fix, sorry for the inconvenience.

**Comment by stefanneculai** [comment]
Thanks for the details. We are working on addressing #2887 in the next minor release. I am going to mark this as closed for now as we can no longer reproduce it and will be happy to reopen it if someone can confirm the problem is still there.
