### ISSUE TITLE
In IE11, after adding an image, not able to add anymore text after the image in the Editor.

### ISSUE THREAD

**Issue by surajgn** [froala/wysiwyg-editor#3096]
Expected behaviour:
In IE 11, after adding an image, not able to add anymore text after the image.

Actual behaviour:
In IE 11, When a user adds an image, he should be able to add text after the image by clicking after the image.

Steps to reproduce the problem.

1. In IE 11, Add an image to the editor using the menu
2. After the image is added, try to add some text after the Image

Note:
We are able to replicate this issue in the below Froala site also in IE11
https://www.froala.com/wysiwyg-editor/

Please see below video of the issue
https://share.vidyard.com/watch/MhdKivJX9ru7wqPHWiJU1D

OS.
Windows 10 Pro
Version 1803

Browser.
Internet Explorer 11
Version 11.285.17134.0

**Comment by stefanneculai** [comment]
For such cases, when you click just below the image at the bottom of the editor it would add a new line after the image.

**Comment by surajgn** [comment]
In IE11, I am not able to add a new line by clicking below the image. It works in other browsers.

**Comment by stefanneculai** [comment]
@surajgn do you think you could send us a recording?

**Comment by surajgn** [comment]
I have already send a video. 
https://share.vidyard.com/watch/MhdKivJX9ru7wqPHWiJU1D

Please let me know whether this is enough or not.

**Comment by stefanneculai** [comment]
Thanks for sending more details, @surajgn. In IE, it would be necessary to click in the space below the image, not to the right of it. I know this might be a little bit unintuitive, but it is the best we could do for now as of some IE limitations when working with images.

**Comment by surajgn** [comment]
The issue is only with inline editor in IE11.
Please see the attached video. Even if I click just under the image, I cannot add text below the image
Please reopen this issue


[Issue-3096-InlineEditor-IE11.zip](https://github.com/froala/wysiwyg-editor/files/2638400/Issue-3096-InlineEditor-IE11.zip)

**Comment by stefanneculai** [comment]
@surajgn we were able to reproduce it sometimes. Unfortunately, we're facing some limitations for it in IE and I have to mark it as a `wontfix`. We're looking into alternatives with the hope to come with a better resolution shortly.
