### ISSUE TITLE
imageEditButtons popup position not correct

### ISSUE THREAD

**Issue by monkey-pawan** [froala/wysiwyg-editor#3097]
Hi,

I'm using jQuery version 1.8.0 as my whole project was written few years back and now I need to integrate Froala for some features but I'm getting following error in the console when I click on image and the popup is all the way to the bottom, could you please suggest how can I fix it?

```
Uncaught TypeError: Failed to execute 'compareDocumentPosition' on 'Node': parameter 1 is not of type 'Node'.
    at Function.Z.contains (jquery.min.js:2)
    at init.<anonymous> (jquery.min.js:2)
    at jquery.min.js:2
    at Function.grep (jquery.min.js:2)
    at bj (jquery.min.js:2)
    at init.filter (jquery.min.js:2)
    at init.find (jquery.min.js:2)
    at Object.show (froala_editor.min.js:7)
    at n (image.min.js:7)
    at HTMLImageElement.se (image.min.js:7)
```

FYI: I am using Windows 7, Chrome.

**Comment by stefanneculai** [comment]
The Froala Editor requires at least version 1.11.0 for jQuery.

**Comment by BoilerTom90** [comment]
I am in the process of upgrading my application to the latest release of Froala (2.9.1). I just noticed that when I click on the "Insert Image" icon the top 1/3rd of the field where you enter the URL to the image is cut off.   Here's a clip of what this looks like. 
<img width="316" alt="froalaeditorimagepopupcutoff" src="https://user-images.githubusercontent.com/17208255/51554305-99df5e80-1e3a-11e9-912a-abe793179dde.PNG">

**Comment by stefanneculai** [comment]
@BoilerTom90 it looks like there might be a conflict with some CSS from your page. Could you please check on that?
