### ISSUE TITLE
weird contentChanged callback

### ISSUE THREAD

**Issue by outluch** [froala/wysiwyg-editor#31]
I decided to show user when his content is not saved and show when saved. So, i want to draw some checkmark when i receive OK from server. I do this with `afterSaveCallback` Everithing ok here.
But i want show some red cross or red border maybe when content is edited, but still not saved. I thought that `contentChangedCallback` will solve my problem. But it doesnt, it works only just before save. I dont know how to detect changes in editable...

**Comment by JoshMcCullough** [comment]
So, if a user types something and clicks "save" immediately, and we are using the `contentChanged` event to get the content, it's possible that the text we're saving is not the latest text in the Froala control.

This is what we're seeing, perhaps we shouldn't be relying on `contentChanged` to supply our updated text, but instead get the HTML content directly from the editor before we save?

**Comment by stefanneculai** [comment]
@JoshMcCullough the `contentChanged` event is triggered after the `typingTimer` option when you type inside the editor. If you want to get the latest changes there in your external save button, then you could use the `html.get` method.

**Comment by JoshMcCullough** [comment]
@stefanneculai We ended up using the `blur` event in combination with the `contentChanged` event to ensure we always had the latest content.
