### ISSUE TITLE
Weird contextual menu issue when opening inside jQuery UI dialogue

### ISSUE THREAD

**Issue by angusgrant** [froala/wysiwyg-editor#3100]
##### Expected behavior.
I expect to see the contextual inline edit menu when i make an edit inside the Froala interface. For example selecting a table cell should bring its inline contextual menu up.

##### Actual behavior.
Apparently randomly there is a 50% chance that the inline contextual menu will initially appear. However if I then attempt to publish changes to page and then reopen the froala editor this drops to a 0% I believe. However if i open in fullscreen mode I appear to get the contextual menu each  time.   

##### Steps to reproduce the problem.
1) Pls visit this fiddle: https://jsfiddle.net/angusgrant/23c5gnz4/75/ 
2) Click on the Lorem Ipsum text in the browser view (A jQuery UI dialogue should spawn with the froala editor emended inside it)
3) Now add a table layout (you might have to expand the window / dialogue to bring up the main menu)
4) Now try and click inside a cell of the new table there is around a 50% chance a contextual dialogue will be displayed.
5) If it does display try clicking on publish button from inside the dialogue (you should see the contents of the froala editor being published to the page and the dialogue closing).  If it doesn't display skip to step 8, 
6) Now click again on the newly created table again a jquery UI dialogue should (again) spawn with the table contents  embedded in the Froala editor.
7) Now try again to click inside the table cell. The chances of seeing the contextual dialogue in my experience have reduced to 0%.
8) However now  select the Full-screen mode note that the behaviour at least for me is now correct and you see the table contextual menu when you put the cursor in it. 

##### OS.
Windows 10.

##### Browser.
Chrome 69.

**Comment by stefanneculai** [comment]
@angusgrant do you think you could send a recording for it? Thanks in advance.

**Comment by stefanneculai** [comment]
Please use a higher zIndex: https://jsfiddle.net/froala/23c5gnz4/80/.

**Comment by angusgrant** [comment]
Thanks @stefanneculai  that looks like it solves my problem.
