### ISSUE TITLE
Embed ly invisible input

### ISSUE THREAD

**Issue by ckheder** [froala/wysiwyg-editor#3103]
##### Expected behavior.
Using the Embed ly plugin inside my froala editor.

##### Actual behavior.
![capture du 2018-10-03 11-22-56](https://user-images.githubusercontent.com/29141668/46401949-b8d8aa00-c6fe-11e8-8dd6-d9627ec27b69.png)

##### Steps to reproduce the problem.
I simply install the editor on a page thanks to the CDN, I changed the language and some buttons.

My Congigs

`<script> $(function() 
	{ 
		$('#editor1').froalaEditor({ 

toolbarButtons: ['undo', 'redo' , 'bold', '|', 'embedly'],
language: 'fr',
zIndex: 2501
}); 
});
</script>`

##### OS.
Linux Mint 18

##### Browser.
Firefox 62 and Chromium 69.0.3497.81

**Comment by stefanneculai** [comment]
It looks like a conflict with some CSS that you have there inside your app. I would suggest to check on that with the developer tools.
