### ISSUE TITLE
List of issues faced when using Froala Editor

### ISSUE THREAD

**Issue by ShanmugaPriyanV** [froala/wysiwyg-editor#3104]
##### Expected behavior.
Refer Attached document

##### Actual behavior.
Refer Attached document

##### Steps to reproduce the problem.
Refer Attached document

##### OS.
NA

##### Browser.
Any browser
[Froala Editor Issues.docx](https://github.com/froala/wysiwyg-editor/files/2441886/Froala.Editor.Issues.docx)

**Comment by stefanneculai** [comment]
@ShanmugaPriyanV we keep track of issues separately. Please instead open a separate ticket for each issue you might face. For fast turnarounds, please make sure that you provide the Steps to reproduce the problem.
