### ISSUE TITLE
config.toolbarBottom does not work if user agent = iPhone

### ISSUE THREAD

**Issue by Hillcow** [froala/wysiwyg-editor#3106]
The toolbar stays on top if you are using an iPhone. Bug can be easily reproduced with Google Chrome simulating an iPhone (see screenshot).
<img width="304" alt="screen shot 2018-10-04 at 11 32 50" src="https://user-images.githubusercontent.com/20979750/46465614-5dbfb980-c7c9-11e8-90ba-d4788258dca9.png">

**Comment by stefanneculai** [comment]
At this moment, we're facing some limitations on mobile devices, thus the option is available only on desktop platforms.

**Comment by platypusrex** [comment]
This configuration seems to work as expected on android devices. Can we get some detail as to why this doesn't work on iOS?

**Comment by stefanneculai** [comment]
Sure, on iOS there is the keyboard and because of it we cannot take the screen size correctly in JS.
