### ISSUE TITLE
Check please. not fixed in version 2.8.5

### ISSUE THREAD

**Issue by mirazero** [froala/wysiwyg-editor#3107]
##### Expected behavior.
(Describe expected behaviour here)

We have applied version 2.8.5.
However, the below hot fixes are not working properly. Please check.
- Editor was scrolling up when hovering a dropdown in IE browser.
- Typing in Korean was not working correctly for image captions in IE.

##### Actual behavior.
(Describe actual behaviour here)

##### Steps to reproduce the problem.
(Describe the steps to reproduce the problem here. A [jsFiddle](https://jsfiddle.net/froala/wc5c3jhk/) is awesome when possible.)

##### OS.
(OS name and version here)
Windows 7

##### Browser.
(Browser name an version here)
IE 11

**Comment by dima888** [comment]
### Comment:
I have the same problem! 
- In the version 2.8.4 the editor was scrolled up
- In the version 2.8.5 the browser was scrolled up (Need Fix)

### Description: 
1. Create a new Rich Editor
2. Create some content, so that the Rich Editor is scrollable
3. Scoll down and select text.
4. Add paragraph style. (for example)

### Result: 
Browser scrolling up! 

### Environment: 
IE: 11
angular-froala-wysiwyg: 2.8.5

**Comment by stefanneculai** [comment]
@mirazero @TimMeissner @dima888 could you please make a recording?

**Comment by dima888** [comment]
[froalaBug.mp4.zip](https://github.com/froala/wysiwyg-editor/files/2469140/froalaBug.mp4.zip)

I'm sorry the bad quality.
Videoformat is in mp4.

**Comment by stefanneculai** [comment]
@dima888 are you able to reproduce this on our website too?

**Comment by dima888** [comment]
Unfortunately I could not reproduce the bug on their homepage

**Comment by stefanneculai** [comment]
@herumtreiber are you able to reproduce on our website?

**Comment by TimSielemann** [comment]
@stefanneculai 
i have reproduced it in a fiddle: [fiddle](https://jsfiddle.net/af3h7bt5/) 

Please have a look at this ASAP because we on our side have some SLA's regarding this bug. 

The code section responsible for the malfunction seem to be the focus function.

**Comment by stefanneculai** [comment]
@TimMeissner thanks for the jsFiddle. We'll check it shortly.

**Comment by stefanneculai** [comment]
Thanks @TimMeissner. We were able to reproduce on Windows 8 with IE 11 by creating scroll on the page and then focusing in the editor and selecting a new font family.

**Comment by brycehill** [comment]
I'm seeing a similar issue in Chrome when the `.fr-wrapper` has a set height. Could it be related? 

**Fiddle:** https://jsfiddle.net/8u1oms74/

Here is a gif where I scroll to the bottom of `.fr-wrapper`, click outside of the textarea to lose focus, and then click the "bold" option in the toolbar. Note how the scroll bar scrolls to the top of the textarea. 

![2019-01-08 16 39 50](https://user-images.githubusercontent.com/2396642/50865711-1dda1680-1364-11e9-9b46-9950aa8f0efd.gif)
