### ISSUE TITLE
Unable to cancel paste event

### ISSUE THREAD

**Issue by frankarensmeier** [froala/wysiwyg-editor#3108]
Not sure if this qualifies as a bug or not (I think it's a bug). I need to be able to cancel the paste event under certain circumstances. Apparently, this doesn't seem possible. This code for example should cancel the paste event:

```
$editor.on('froalaEditor.beforeCleanup.paste', function(event){
    event.preventDefault();
    return false;
});
```

Returning an empty string (as stated in the documentation) has no effect either.

##### Expected behavior.
As with all bubbling events, cancellation for the paste event should be possible.

##### Actual behavior.
Event is not cancelled.

##### Steps to reproduce the problem.
See example

**Comment by stefanneculai** [comment]
See: https://www.froala.com/wysiwyg-editor/docs/events#paste.before
