### ISSUE TITLE
After apply out dent on any indent extra bullet point is shown

### ISSUE THREAD

**Issue by javeriaanwer** [froala/wysiwyg-editor#3109]
1. Insert some text and apply numbering till 5.
2. Indent any 2 words from the middle.
3. Apply out dent on the first one(sub list).

Result:
After apply out dent after indent extra bullet point is shown

![ezgif com-video-to-gif 5](https://user-images.githubusercontent.com/25203829/46653352-3d27a300-cbbf-11e8-9182-224d667200a4.gif)

**Comment by stefanneculai** [comment]
It's fixed in 2.9.2.
