### ISSUE TITLE
Toolbar dropdowns not positioned properly when at the right hand edge

### ISSUE THREAD

**Issue by Pratibha-M** [froala/wysiwyg-editor#3110]
#### Expected behavior.
Toolbar dropdowns like color, insert link should be positioned properly.

#### Actual behavior.
When the toolbar buttons are at the end of a container, the dropdowns are positioned incorrectly.

#### **Insert link (cutoff)**
![image](https://user-images.githubusercontent.com/43984880/46655638-c5697080-cbde-11e8-8ac5-ff166e4d829c.png)

#### **Colors (displayed weirdly)**
![image](https://user-images.githubusercontent.com/43984880/46655712-ee8a0100-cbde-11e8-83f6-30fd30270150.png)

#### Steps to reproduce the problem.
Click on insert link or color buttons in toolbar - https://jsfiddle.net/vrw6bp3j/3/

#### OS.
Windows 10

#### Browser.
Chrome, IE and Edge

**Comment by stefanneculai** [comment]
It's fixed on the current master.
