### ISSUE TITLE
Background color breaking span elements in IE11

### ISSUE THREAD

**Issue by Pratibha-M** [froala/wysiwyg-editor#3112]
#### Expected behavior.
When I select the background color it should not remove the span elements and its attributes.

##### Actual behavior.
Selecting background color removes the span elements from the editor.

##### Steps to reproduce the problem.
1. Open froala demo page in IE and from code view add the following
    `<p>Test <span data-name="my-span-el">My Span EL</span> this</p>`
2. Now switch back to editor view and select all text and add a background color.
3. Switch to code view and see that span data-name is lost.

![background color destroying span_ie](https://user-images.githubusercontent.com/43984880/46659088-d0c09a00-cbe6-11e8-8d07-89ce20b8829a.gif)

Try the same with other styles like bold, text color. span data-name is retained - expected

Try this in chrome/edge and it works as expected even for background color.

##### OS.
Windows 10

##### Browser.
IE11

**Comment by stefanneculai** [comment]
This is fixed on the current 2.9.2 version.
