### ISSUE TITLE
Esc on edit link popup in froala editor is giving an error

### ISSUE THREAD

**Issue by Pratibha-M** [froala/wysiwyg-editor#3113]
##### Expected behavior.
Hitting Escape on edit link popup should not throw error.

##### Actual behavior.
Its throwing error.

##### Steps to reproduce the problem.
Add a link in the froala editor and hit escape when it is displaying edit link popup.

I could not get a jsfiddle for this but I am getting error from the below code. It is trying to use t.accessibility.**FocusPopupButton**(i) (notice the capital F) instead of t.accessibility.focusPopupButton(i).
```
_windowKeydown: function(e) {
                    if (!c.core.sameInstance(i))
                        return !0;
                    var t = i.data("instance") || c
                      , n = e.which;
                    if (be.FE.KEYCODE.ESC == n) {
                        if (t.popups.isVisible(r) && t.opts.toolbarInline)
                            return e.stopPropagation(),
                            t.popups.isVisible(r) && (i.find(".fr-back:visible").length ? (t.button.exec(i.find(".fr-back:visible:first")),
                            t.accessibility.focusPopupButton(i)) : i.find(".fr-dismiss:visible").length ? t.button.exec(i.find(".fr-dismiss:visible:first")) : (t.popups.hide(r),
                            t.toolbar.showInline(null, !0),
                            t.accessibility.FocusPopupButton(i))),
                            !1;
                        if (t.popups.isVisible(r))
                            return i.find(".fr-back:visible").length ? (t.button.exec(i.find(".fr-back:visible:first")),
                            t.accessibility.focusPopupButton(i)) : i.find(".fr-dismiss:visible").length ? t.button.exec(i.find(".fr-dismiss:visible:first")) : (t.popups.hide(r),
                            t.accessibility.focusPopupButton(i)),
                            !1
                    }
                },
```

I am using froala editor in angular 5 component.

##### OS.
Windows 10

##### Browser.
Chrome, IE and Edge

**Comment by fmay** [comment]
Same happening to me (Mac, Chrome)

- Select a piece of text with link. 
- Popup appears
- Press ESC and the main toolbar, balloon/inline in my case, appears rather than returning to plain text edit
- Dev tools shows error below

`froala_editor.pkgd.min.js:7 Uncaught TypeError: t.accessibility.FocusPopupButton is not a function
    at s._windowKeydown (froala_editor.pkgd.min.js:7)
    at u (froala_editor.pkgd.min.js:7)
    at froala_editor.pkgd.min.js:7
    at dispatch (jquery.js:5183)
    at elemData.handle (jquery.js:4991)`
