### ISSUE TITLE
isMac helper breaks on iphone

### ISSUE THREAD

**Issue by greggreenhaw** [froala/wysiwyg-editor#3118]
On iphone 
navigator.platform = 'iPhone'

Current function: 
function isMac() {
            if (is_mac == null) {
                is_mac = navigator.platform.toUpperCase().indexOf("MAC") >= 0;
            }
            return is_mac;
        }

Suggested Change use userAgent instead:

function isMac() {
            if (is_mac == null) {
                is_mac = navigator.userAgent.toUpperCase().indexOf("MAC") >= 0;
            }
            return is_mac;
        }

**Comment by stefanneculai** [comment]
`isMac` is actually looking for the OS. For iphone, we recommend using the `isIOS` method instead.
