### ISSUE TITLE
Cannot insert text after an image with caption in inline editor

### ISSUE THREAD

**Issue by surajgn** [froala/wysiwyg-editor#3119]
Expected behaviour.
In Inline Editor, User should be able to enter text after giving caption for an inserted Image

Actual behaviour.
User cannot enter text after giving caption for an inserted Image

Please see below video of the issue
https://share.vidyard.com/watch/njgkC3B3DtBZsQVgRyDvvs

Also Here's a jsfiddle with the Issue
https://jsfiddle.net/SurajNair/9vd83dgj/130/

OS.
Windows 10 Pro
Version 1803

Browser.
Chrome
Version 69.0.3497.100

**Comment by stefanneculai** [comment]
The last commit introduces the option `imageAddNewLine` which when enabled would add a new line after image when it is the last element inside the editor.
