### ISSUE TITLE
iFrame height calculation

### ISSUE THREAD

**Issue by btmdave** [froala/wysiwyg-editor#3121]
We're using iframe and custom css, part of this css is for fonts what appears to be happening is the iframe height calculation is being made prior to the font being fully rendered.  This causes the iframe to be shorter, than it should be.  Is there an API or a way that we can force re-calculate the height of the iframe?

**Comment by stefanneculai** [comment]
https://www.froala.com/wysiwyg-editor/docs/methods#size.syncIframe
