### ISSUE TITLE
apostrophe character gets shown as html code instead of '

### ISSUE THREAD

**Issue by shaivi-mob-incedo** [froala/wysiwyg-editor#3123]
##### Expected behavior.
(Describe expected behaviour here)

##### Actual behavior.
(Describe actual behaviour here)

##### Steps to reproduce the problem.
(Describe the steps to reproduce the problem here. A [jsFiddle](https://jsfiddle.net/froala/wc5c3jhk/) is awesome when possible.)

##### OS.
(OS name and version here)

##### Browser.
(Browser name an version here)

**Comment by stefanneculai** [comment]
@shaivi-mob-incedo please provide details to reproduce this issue.
