### ISSUE TITLE
Activate image href edit option,  when pasted to  froala editor

### ISSUE THREAD

**Issue by tomalex0** [froala/wysiwyg-editor#3124]
### _If you have a feature suggestion, please add it on the [Feature List](https://wysiwyg-editor-roadmap.froala.com/public) instead._
Not sure if this is already raised or even as part of the road map,

##### Expected behavior.

Copy content which has image with href from word and paste it in froala editor, focusing on image should give an option to edit the url.

##### Actual behavior.

Copy content which has image with href from word and paste it in froala editor, focusing on image does not give an option to edit but to add and eventually there will be two anchor tag parent element for the image

##### Steps to reproduce the problem.
(Describe the steps to reproduce the problem here. A [jsFiddle](https://jsfiddle.net/froala/wc5c3jhk/) is awesome when possible.)
1. Copy Content from [froala_image_href.docx](https://github.com/froala/wysiwyg-editor/files/2474815/froala_image_href.docx)
2. Paste to https://www.froala.com/wysiwyg-editor

## Demo
https://github.com/tomalex0/froala_issue_video/blob/master/3124.md

##### OS.
(OS name and version here)
Windows 10
##### Browser.
(Browser name an version here)
Chrome Version 69.0.3497.100

**Comment by stefanneculai** [comment]
Unfortunately, when we get the HTML from Word in clipboard, it doesn't include the link to image and that is why it is not retained. I am putting below for reference what we received from Word:

```html

<p align=center style='margin-top:0cm;text-align:center;background:white'><span
lang=EN-US style='font-family:Helvetica;mso-bidi-font-family:Helvetica;
color:black;mso-no-proof:yes'><!--[if gte vml 1]><v:shapetype id="_x0000_t75"
 coordsize="21600,21600" o:spt="75" o:preferrelative="t" path="m@4@5l@4@11@9@11@9@5xe"
 filled="f" stroked="f">
 <v:stroke joinstyle="miter"/>
 <v:formulas>
  <v:f eqn="if lineDrawn pixelLineWidth 0"/>
  <v:f eqn="sum @0 1 0"/>
  <v:f eqn="sum 0 0 @1"/>
  <v:f eqn="prod @2 1 2"/>
  <v:f eqn="prod @3 21600 pixelWidth"/>
  <v:f eqn="prod @3 21600 pixelHeight"/>
  <v:f eqn="sum @0 0 1"/>
  <v:f eqn="prod @6 1 2"/>
  <v:f eqn="prod @7 21600 pixelWidth"/>
  <v:f eqn="sum @8 21600 0"/>
  <v:f eqn="prod @7 21600 pixelHeight"/>
  <v:f eqn="sum @10 21600 0"/>
 </v:formulas>
 <v:path o:extrusionok="f" gradientshapeok="t" o:connecttype="rect"/>
 <o:lock v:ext="edit" aspectratio="t"/>
</v:shapetype><v:shape id="Picture_x0020_1" o:spid="_x0000_i1025" type="#_x0000_t75"
 alt="Editor photo" style='width:150pt;height:100pt;visibility:visible;
 mso-wrap-style:square'>
 <v:imagedata src="file:////Users/me/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_image001.jpg"
  o:title="Editor photo"/>
</v:shape><![endif]--><![if !vml]><img data-fr-image-pasted="true" width=150 height=100
src="file:////Users/me/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_image001.jpg"
alt="Editor photo" v:shapes="Picture_x0020_1"><![endif]></span><span
lang=EN-US style='font-family:Helvetica;mso-bidi-font-family:Helvetica;
color:black'><o:p></o:p></span></p>
```

**Comment by tomalex0** [comment]
[froala_image_href.docx](https://github.com/froala/wysiwyg-editor/files/2857257/froala_image_href.docx)

Looks like the previous word document didn't had the href applied. Can you try this file.
