### ISSUE TITLE
Unsafe Use Of Target blank

### ISSUE THREAD

**Issue by binod12** [froala/wysiwyg-editor#3125]
##### Expected behavior.
In order to fix a security vulnerability **Unsafe Use Of Target blank** when using the "target" attribute,  "rel" attribute should also be set as “noopener noreferrer”. Following two instances does not follow above security guidelines. 
froala_editor.pkgd.min.js
"<a class="fr-link" tabIndex="-1" href="http://emojione.com/" target="_blank" rel="nofollow" role="link" aria-label="Open Emoji One website.">Emoji One</a>"

emoticons.min.js
"<a class="fr-link" tabIndex="-1" href="http://emojione.com/" target="_blank" rel="nofollow" role="link" aria-label="Open Emoji One website.">Emoji One</a>"

##### Actual behavior.
We have found that it has not been set in the following two files:
- froala_editor.pkgd.min.js
- emoticons.min.js

##### Steps to reproduce the problem.
Refer the above mentioned files.

##### OS.
NA

##### Browser.
NA

**Comment by stefanneculai** [comment]
See https://www.froala.com/wysiwyg-editor/docs/options#linkNoOpener and https://www.froala.com/wysiwyg-editor/docs/options#linkNoReferrer

**Comment by binod12** [comment]
Thanks for the quick reply. 

We understand that the provided solution will work for any link in the editor.

But this issue was logged for the source code security scan, where a link was mentioned in the above mentioned source code files. 

Can we modify following scripts files to include the suggested solution “noopener noreferrer” in order to close the security issue?

- froala_editor.pkgd.min.js
- emoticons.min.js

**Comment by binod12** [comment]
Thanks for the fix. 

We are still using the version v2.5.0. 

Plan to upgrade it to newest version is in pipeline and will take almost 6-8 months. 

By that time can we modify the the existing JavaScript file to close this issue at our end? Is it allowed under the license agreement? We are using Professional license.

**Comment by stefanneculai** [comment]
Sure, you can do that, @binod12

**Comment by uppy18** [comment]
We have updated with the latest froala editor v3.2.2, but still security vulnerability Unsafe Use Of Target blank persist. At some places it been fixed with "rel" attribute set as “noopener noreferrer” but some instances it is not.

Following two instances does not follow above security guidelines.

froala_editor.pkgd.min.js
"Froala WYSIWYG HTML Editor"

froala_editor.min.js
"Froala WYSIWYG HTML Editor"
