### ISSUE TITLE
Word paste is broken in Edge

### ISSUE THREAD

**Issue by Pratibha-M** [froala/wysiwyg-editor#3128]
##### Expected behavior.
When copy pasting from word document to froala demo page there should be a 'Word paste detected' popup.

##### Actual behavior.
It does not give any popup when pasted in Edge and the formatting is not proper when pasting the list items.
Pasting the list items from word to Chrome or IE adds them as UL/LI's but in Edge they are added as P tags.

##### Steps to reproduce the problem.
Open froala demo page in MS Edge and copy paste the list items from word document.
The list items are added directly without a popup.
In the code view can see the items are actually added as P tags instead of UL/LI elements.

Word doc:
[List items.docx](https://github.com/froala/wysiwyg-editor/files/2481480/List.items.docx)

Pasted list items into froala editor in Edge (**Bug**):
![word paste_edge](https://user-images.githubusercontent.com/43984880/46993734-702fe080-d143-11e8-885a-ffd68b4a2a5e.gif)

Pasted in Chrome (**Expected**):
![word paste_chrome](https://user-images.githubusercontent.com/43984880/46993743-7cb43900-d143-11e8-8c86-80fcfcae0720.gif)

##### OS.
Windows 10

##### Browser.
Microsoft Edge 42.17134.1.0

**Comment by stefanneculai** [comment]
Unfortunately, in MS Edge we're getting the HTML like this from the browser clipboard and there is not too much we could do to convert it to lists.
