### ISSUE TITLE
format.removeStyle doesn't work properly with collapsed selection

### ISSUE THREAD

**Issue by GMiLL5** [froala/wysiwyg-editor#3129]
##### Expected behavior.
Using `editor.format.removeStyle( )` when selection is collapsed or expanded should work the same

##### Actual behavior.
With an expanded text selection `editor.format.removeStyle( )` works properly

With a collapsed text selection, a span is created with a null style attribute value `<span style="font-weight: null"></span>`

##### Steps to reproduce the problem.
Trigger editor.format.removeStyle with a collapsed cursor selection.

Fiddle here: https://jsfiddle.net/wjbqa84g/

1. Put your cursor in the editor
2. Select the removeStyle button (only button at the top)
3. Inspect markup

##### OS.
Mac OS 10.13.6

##### Browser.
Firefox 62.0
Chrome 69.0.3497.100

**Comment by stefanneculai** [comment]
It's fixed in version 2.9.2 and on the master branch.
