### ISSUE TITLE
The editor is very slow and lagging with 25k+ lines of HTML

### ISSUE THREAD

**Issue by farahat80** [froala/wysiwyg-editor#3131]
When having over 25K + lines of HTML the performance is very bad and the editor is very laggy, is there anything that can be disabled to improve this ?

**Comment by stefanneculai** [comment]
@farahat80 Do you think it would be possible to make a jsFiddle to highlight the problem? That would speed-up things a lot. Here is a basic jsFiddle you could use as a starting point: https://jsfiddle.net/froala/wc5c3jhk/.

**Comment by farahat80** [comment]
@stefanneculai after making a test on jsFiddle i see that its working more smooth than the one we have on our app, so i will keep tracking of this untill i am able to catch a working example that show the lagging problem, thanks for your response, i am closing the issue now.
