### ISSUE TITLE
How to adjust filename text in editor based on server response?

### ISSUE THREAD

**Issue by adueck** [froala/wysiwyg-editor#3132]
Looking at the documentation [here](https://www.froala.com/wysiwyg-editor/docs/methods#file.upload), and [here](https://www.froala.com/wysiwyg-editor/docs/concepts/file/upload), I am unable to see how I can adjust the filename that gets inserted into the editor once uploaded into the server.

Ideally I would love to be able to do this when dragging a file into the editor, but the fourth step missing:

1. Upload the file 
2. Listen for the event `froalaEditor.file.uploaded (e, editor, response)`
3. Get the filename that was saved on the server, based on `{ "link": "http://example.com/saved-file.txt" }`
4. **Insert the file into the editor with the `text` based on the response in step 3**

The normal process works fine for the link. It sets the `href` attribute according to `{ link: http://example.com/file-save-on-server.txt}` but the text in the editor shows up as the original file name.

I would like to get the server-saved file name from the link and insert it into the editor, so when the user downloads the file the download name is the same as what they click on.

I have tried to insert the file with the appropriate text using the [file.insert() method](https://www.froala.com/wysiwyg-editor/docs/methods#file.insert), in response to the `froalaEditor.file.uploaded (e, editor, response)` event. However, this does not seem to work.

When a file gets dragged in, how can we suppress the regular `file.insert()` function and do one with our own custom text.

Otherwise, **I would suggest that the text that shows up in the editor is automatically based on the filename in the server response.**

**Comment by stefanneculai** [comment]
You can use https://www.froala.com/wysiwyg-editor/docs/events#file.inserted.
