### ISSUE TITLE
bug?: `video.removed` event fires twice for one remove

### ISSUE THREAD

**Issue by adueck** [froala/wysiwyg-editor#3133]
##### Expected behavior.
When one video is removed from the editor, the `video.removed` event should fire once, and return one video element.

##### Actual behavior.
**Removing one video fires 2 events right after each other**, with each returning a different jQuery object
- `jQuery.fn.init [span.fr-video.fr-dvb.fr-draggable]` (for the outer `<span>` element)
- `jQuery.fn.init [video.fr-draggable]` (for the inner `<video>` element)

This makes sense and can be dealt with, but the code gets a bit ugly and it would be nice to warn people about this [in the documentation here](https://www.froala.com/wysiwyg-editor/docs/events#video.removed).

##### Steps to reproduce the problem.
- Set event listener for `editor.video.remove`
- Add in a video and delete it
- The event fires twice and returns two different objects

##### OS.
Widows

##### Browser.
Chrome, Firefox, Edge

**Comment by adueck** [comment]
I don't have a jsFiddle account to save a fiddle on, but all you have to do is add this block of code to that sample you gave.

```
$('#froala-editor').on('froalaEditor.video.removed', function (e, editor, $video) {
    console.log('fired event');
    console.log($video);
});
``` 

If you add a video and then remove it, you will see that the event fires twice with the two different elements, as I described.

**Comment by stefanneculai** [comment]
It is not necessary to have an account to save the Fiddle. Just fork the one I sent and then make the updates and send us the result URL.

**Comment by adueck** [comment]
https://jsfiddle.net/ao1qj4s2/
