### ISSUE TITLE
Using insertTable or insertVideo button within popup on body container throws error

### ISSUE THREAD

**Issue by FloPrey** [froala/wysiwyg-editor#3135]
##### Expected behavior.
When using a popup on the body container and adding the insertTable and insertVideo button, the behavior is the same as within the default toolbar.

##### Actual behavior.
When clicking on the insertTable or insertVideo an error is thrown.

##### Steps to reproduce the problem.
Click on the 'arrow' to show the popup and then click on the insertTable or insertVideo button in this codepen.
https://codepen.io/anon/pen/OBzXRP

##### OS.
Windows 10

##### Browser.
Chrome, 70.0.3538.67

**Comment by stefanneculai** [comment]
The built-in popups have been designed for the main editor toolbar, not for being used nested and that is the reason why they don't appear correctly. To get them work as you're looking for, the best way would be to make changes directly on the editor source code on the following methods: `video.showInsertPopup`, `image.showInsertPopup`, `table.showInsertPopup`.
