### ISSUE TITLE
Shortcuts to indent and outdent text doesn't work

### ISSUE THREAD

**Issue by felskov** [froala/wysiwyg-editor#3136]
##### Expected behavior.
Tooltips for indent and outdent suggest that keyboard shortcuts ⌘[ and ⌘] should work.

##### Actual behavior.
When using those shortcuts, nothing happens.

##### Steps to reproduce the problem.
Try using the shortcuts in the editor.

##### OS.
macOS Mojave 10.14 (18A391)

##### Browser.
Chrome Version 70.0.3538.67 (Official Build) (64-bit)

**Comment by stefanneculai** [comment]
@felskov could you please check if you have any plugins enabled in Chrome that might prevent such a behavior? It works fine on my side.

**Comment by felskov** [comment]
@stefanneculai Thank you for the quick reply :-)

I've tested https://www.froala.com/wysiwyg-editor in Chrome incognito (where all my extensions are disabled). It also doesn't work there :-)

I suppose that the short cut is supposed to be ⌘+⌥+8/9 (as ⌥+8/9 will render [/]).

When I use those short cuts, it'll navigate back / forwards in the browser history instead of adjusting indentation.

Let me know if there's anything else I can do to help :-)

**Comment by stefanneculai** [comment]
Maybe it is the keyboard layout. Are you using an US one?

**Comment by felskov** [comment]
I'm using danish keyboard layout. My colleague just pointed out that the same issue exists in gmail.com, so it's most likely an issue with our keyboard layouts. Feel free to close the issue if you can't figure out an easy fix :-)

<img width="630" alt="screenshot 2018-10-24 at 13 59 15" src="https://user-images.githubusercontent.com/1436954/47429007-3be89f80-d795-11e8-864b-a65b8b08509c.png">

**Comment by stefanneculai** [comment]
Thanks for the quick response, @felskov.
