### ISSUE TITLE
Selection (caret position) in text-view is not restored after toggle code-view

### ISSUE THREAD

**Issue by tidus2102** [froala/wysiwyg-editor#3137]
##### Expected behavior.
Selection (or caret position) must be restored after toggle (open then hide) code-view

##### Actual behavior.
Selection (or caret position) is NOT restored after toggle (open then hide) code-view

##### Steps to reproduce the problem.
Test with editor in Froala [homepage](https://www.froala.com/wysiwyg-editor) 
1. Select any text or move caret to any position
2. Open code-view. In code-view, selection is the same (caret at same position) => CORRECT
3. Hide code-view. Selection is NOT restore (caret is NOT restored) => ERROR

##### OS.
macOS High Serria 10.13.6

##### Browser.
Google Chrome 70.0.3538.67

**Comment by stefanneculai** [comment]
Please upvote this on https://wysiwyg-editor-roadmap.froala.com/public/ideas/3558.
