### ISSUE TITLE
Front Family Issue - New paragraph inserted between existing paragraph.

### ISSUE THREAD

**Issue by VenkateshJhipster** [froala/wysiwyg-editor#3138]
##### Expected behavior.
When a new paragraph is inserted between the existing paragraphs, the font family must be inherited from the previous paragraph.

##### Actual behavior.
When a new paragraph is inserted between the existing paragraphs, the font family is not getting inherited from the previous paragraph.

##### Steps to reproduce the problem.
Please refer the attached document for reproducing the steps.

##### OS.
Window 7. 
[Font Family Issue - Froala Editor.docx](https://github.com/froala/wysiwyg-editor/files/2504558/Font.Family.Issue.-.Froala.Editor.docx)

##### Browser.
Microsoft Chrome Version 60.0.3112.101

##### Email Client
Outlook 2016.

**Comment by stefanneculai** [comment]
@VenkateshJhipster are you experiencing this if you enable the `keepFormatOnDelete` option?

**Comment by ShanmugaPriyanV** [comment]
Hi stefanneculai,

We will try and let you know.

**Comment by ShanmugaPriyanV** [comment]
Hi stefanneculai,

We experience the same even if we enable the keepFormatOnDelete  option. Please refer the attached document.

![image](https://user-images.githubusercontent.com/20870994/47655103-3e992980-dbc7-11e8-839c-31eef9660b7f.png)

**Comment by stefanneculai** [comment]
Are you able to replicate it on https://jsfiddle.net/froala/wc5c3jhk/2057/? Could you provide a recording?

**Comment by ShanmugaPriyanV** [comment]
@stefanneculai . Hi I have added the recording made in Froala site regarding the Font Family Issue.
[Froala Font Family Issue.zip](https://github.com/froala/wysiwyg-editor/files/2596410/Froala.Font.Family.Issue.zip)

**Comment by ShanmugaPriyanV** [comment]
@stefanneculai .. Hope this helps. Thanks in Advance

**Comment by stefanneculai** [comment]
@ShanmugaPriyanV are you able to replicate on this page: https://jsfiddle.net/froala/wc5c3jhk/2057/? The recording appears to be done on our homepage.

**Comment by ShanmugaPriyanV** [comment]
@stefanneculai . I have recorded in jsfiddle you provided replicating our scenario hope it helps thanks in advance.
[Font issue issue.zip](https://github.com/froala/wysiwyg-editor/files/2630226/Font.issue.issue.zip)

**Comment by stefanneculai** [comment]
Could you please update the jsFiddle with the HTML that you're having there after paste? Also, what browser and OS are you using? Thanks.

**Comment by stefanneculai** [comment]
@ShanmugaPriyanV pinging on it.

**Comment by stefanneculai** [comment]
Closing this as we haven't got enough details.
