### ISSUE TITLE
Word Copy Paste not keeps the format while editing further

### ISSUE THREAD

**Issue by ShanmugaPriyanV** [froala/wysiwyg-editor#3140]
##### Expected behavior.
Opened MSWord and typed the following
Test line 1
(Enter) line 2 in italic
(Shift+enter) line 3 in bold and font size 16

Copied the content to editor which invoked the word paste plugin popup to show up and used 'keep'
The formats got copied but when pressed enter and typed new line in editor the previous line styling should be applied to the newer lines.

##### Actual behavior.
Opened MSWord and typed the following
Test line 1
(Enter) line 2 in italic
(Shift+enter) line 3 in bold and font size 16

Copied the content to editor which invoked the word paste plugin popup to show up and used 'keep'
The formats got copied but when pressed enter and typed new line in editor the previous line styling didn't get reflected in the new line.

##### Steps to reproduce the problem.
Steps provided in Attached Word Document

##### OS.
Windows 8.1

##### Browser.
Chrome Version 68.0.3440.75 (Official Build) (32-bit)

**Comment by ShanmugaPriyanV** [comment]
[Froala Editor Word Paste issue.docx](https://github.com/froala/wysiwyg-editor/files/2513520/Froala.Editor.Word.Paste.issue.docx)

**Comment by ShanmugaPriyanV** [comment]
@stefanneculai Hi, any updates on this and is there any change we need to do from our end?

Thanks!

**Comment by ShanmugaPriyanV** [comment]
@stefanneculai , Hi is there any workaround for this issue? Thanks!

**Comment by stefanneculai** [comment]
@ShanmugaPriyanV it is scheduled to be added in version 2.9.3 and it is marked as an enhancement.
