### ISSUE TITLE
Webpack errors and set up

### ISSUE THREAD

**Issue by george-norris-salesforce** [froala/wysiwyg-editor#3145]
Recently switching from Browserify/Gulp to Webpack and running into issues with Froala.

Would be nice if you provided some kind of guidance on setting up Froala with Webpack? Seems there are quite questions on here about that — a comprehensive would be really great.

error happens on this line in our code:
`
import froala from 'froala-editor/js/froala_editor.pkgd.min.js';
froala(jQuery);
`

In Chrome DevTools this error is shown.
`RichEditor.jsx:18 Uncaught TypeError: (0 , v.default) is not a function`

Using 
froala-editor 2.5.1

**Comment by george-norris-salesforce** [comment]
Hello. Any update on this?

**Comment by stefanneculai** [comment]
See https://gist.github.com/stefanneculai/9c734689bc88c8931d18f187d6b5a94b

**Comment by george-norris-salesforce** [comment]
ty!

**Comment by george-norris-salesforce** [comment]
stil throwing errors
```
align.min.js:7 Uncaught TypeError: Cannot read property 'PLUGINS' of undefined
    at Object.r (align.min.js:7)
```
