### ISSUE TITLE
copy and paste image cause chrome Browser crash

### ISSUE THREAD

**Issue by anjorn** [froala/wysiwyg-editor#3146]
##### Expected behavior.
(Describe expected behaviour here)
copy 70+ images from others, then paste to the edito . every image is about 100kbs
##### Actual behavior.
(Describe actual behaviour here)
copy 70+ images from others  then paste to the editor  then the chrome browser crash  
![image](https://user-images.githubusercontent.com/17606214/47702968-954f4380-dc59-11e8-84bf-e0522c6745f9.png)

##### Steps to reproduce the problem.
(Describe the steps to reproduce the problem here. A [jsFiddle](https://jsfiddle.net/froala/wc5c3jhk/) is awesome when possible.)

##### OS.
(OS name and version here)
windows 8G内存
##### Browser.
(Browser name an version here)
chrome 70.0.3538.77

**Comment by stefanneculai** [comment]
Closing this due to lack of response. The problem might be related to some fixes in version 2.9.2.
