### ISSUE TITLE
Toolbar button problems with 2.9.0

### ISSUE THREAD

**Issue by bpautsch** [froala/wysiwyg-editor#3151]
1. Save icon for FA5 now needs to be 'save'. 'disk' no longer supported.

2. Line Height icon for FA5 now need to be 'arrows-alt-v'. 'arrows-v' no longer supported.

3. OL and UL buttons render weird. Fix is to float left.
.fr-toolbar.fr-inline .fr-command.fr-btn:not(.fr-hidden) {
    float: left;
}

**Comment by stefanneculai** [comment]
@bertoost are you seeing these problems here https://www.froala.com/wysiwyg-editor/examples/font-awesome-5-js?

**Comment by bertoost** [comment]
don't know what you mean @stefanneculai .. I am not yet using the newest version

**Comment by stefanneculai** [comment]
@bertoost sorry I tagged you wrong. :)

@bpautsch are you seeing these problems here https://www.froala.com/wysiwyg-editor/examples/font-awesome-5-js?

**Comment by bpautsch** [comment]
The Save and Line Height buttons aren't there, so I can answer that.
The OL and UL buttons look good there.
Note: I use the inline editor so maybe that's the difference.

**Comment by bpautsch** [comment]
Yep...it's an inline editor issue. See code below and screenshot:

 $('div#froala-editor').froalaEditor({
  iconsTemplate: 'font_awesome_5',
  toolbarInline: true,
  toolbarButtons: ['save', 'insertContent', 'insertImage', 'insertLink', 'insertFile', 'insertVideo', , 'embedly', 'undo', 'redo', 'html', '-', 
           'bold', 'italic', 'underline', 'strikeThrough', 'paragraphStyle', 'indent', 'outdent', 'formatOL', 'formatUL', 'insertTable', '-', 
           'fontFamily', 'fontSize', 'lineHeight', 'color', 'align', 'emoticons', 'specialCharacters', 'quote', 'spellChecker', 
           'Draggable', 'quickInsert', 'wordPaste'], 
})

![froala](https://user-images.githubusercontent.com/2838210/47921919-c743ee00-de83-11e8-9911-fbb8cbb9e633.JPG)

**Comment by giovanigenerali** [comment]
@stefanneculai I'm getting the same problem:

**Froala v2.9.0 + Font Awesome 4.7.0**

Example:
https://jsfiddle.net/giovanigenerali/bu7k3pec/ 
** here I got the problem only with the second instance ```froala-editor-2```

Buttons with problem:
- formatOL
- formatUL

---

**Froala v2.9.0 + Font Awesome 5.5.5**

Example:
https://jsfiddle.net/giovanigenerali/5r7fvw3a/

Buttons with problem:
- undo
- redo
- formatOL
- formatUL

---

**Using themes**

Example:
https://www.froala.com/wysiwyg-editor/examples/color-themes

Buttons with problem:
- formatOL
- formatUL

---

**DocumentReady with theme**

Example using theme gray and document ready:
https://jsfiddle.net/giovanigenerali/2t3unxw7/

Problem:
Background change and others css issues.

**Comment by Spoowy** [comment]
I am seeing this as well in the inline editor.

**Comment by massarogi** [comment]
> @stefanneculai I'm getting the same problem:
> 
> **Froala v2.9.0 + Font Awesome 4.7.0**
> 
> Example:
> https://jsfiddle.net/giovanigenerali/bu7k3pec/
> ** here I got the problem only with the second instance `froala-editor-2`
> 
> Buttons with problem:
> 
> * formatOL
> * formatUL
> 
> **Froala v2.9.0 + Font Awesome 5.5.5**
> 
> Example:
> https://jsfiddle.net/giovanigenerali/5r7fvw3a/
> 
> Buttons with problem:
> 
> * undo
> * redo
> * formatOL
> * formatUL
> 
> **Using themes**
> 
> Example:
> https://www.froala.com/wysiwyg-editor/examples/color-themes
> 
> Buttons with problem:
> 
> * formatOL
> * formatUL
> 
> **DocumentReady with theme**
> 
> Example using theme gray and document ready:
> https://jsfiddle.net/giovanigenerali/2t3unxw7/
> 
> Problem:
> Background change and others css issues.

Same issues for us as well.
