### ISSUE TITLE
Pasting embed code from Vimeo doesn't seem to work

### ISSUE THREAD

**Issue by apuchkov** [froala/wysiwyg-editor#3152]
##### Expected behavior.
Inserting this Vimeo Embed code would insert video
```
<iframe src="https://player.vimeo.com/video/172009499" width="640" height="360" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
<p><a href="https://vimeo.com/172009499">ASP.NET Core Kestrel: Adventures in building a fast web server - Damian Edwards, David Fowler</a> from <a href="https://vimeo.com/ndcconferences">NDC Conferences</a> on <a href="https://vimeo.com">Vimeo</a>.</p>
```
The code is generated on this page: https://vimeo.com/172009499

##### Actual behavior.
Click Insert button in Embedded Code doesn't do anything. No errors in console.

##### Steps to reproduce the problem.
- Go to https://www.froala.com/wysiwyg-editor
- Click the Insert Video button in the toolbar.
- Switch to Embedded Code
- Input this Embedded Code:
```
<iframe src="https://player.vimeo.com/video/172009499" width="640" height="360" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
<p><a href="https://vimeo.com/172009499">ASP.NET Core Kestrel: Adventures in building a fast web server - Damian Edwards, David Fowler</a> from <a href="https://vimeo.com/ndcconferences">NDC Conferences</a> on <a href="https://vimeo.com">Vimeo</a>.</p>
```
- Click Insert

##### OS.
Windows 10

##### Browser.
Version 70.0.3538.77 (Official Build) (64-bit)

**Comment by stefanneculai** [comment]
The editor is designed to filter the embeded code. By default, it validates it by using a regular expression. If you'd like to change that, then add the following line and update the regex just before initializing the editor:

```js
$.FE.VIDEO_EMBED_REGEX = /^\W*((<iframe.*><\/iframe>)|(<embed.*>))\W*$/i;
```

**Comment by apuchkov** [comment]
Permitting to paste any content to the embed window helped, thanks.

```
$.FE.VIDEO_EMBED_REGEX = /.*/mi;
```
