### ISSUE TITLE
Video in iframe- bad positioning toolbar

### ISSUE THREAD

**Issue by KarolMilewski** [froala/wysiwyg-editor#3156]
Demo
https://streamable.com/k3mzn

##### Expected behavior.
The box border follows into the video.

##### Actual behavior.
The box border doesn't follow

##### Steps to reproduce the problem.
Set config to:
iframe: true,
toolbarInline: true,

toolbarSticky: true,

**Comment by stefanneculai** [comment]
I am closing this due to lack of response. Would be happy to open it again if you can send us steps to reproduce it in a demo.
