### ISSUE TITLE
Image upload documentation

### ISSUE THREAD

**Issue by fmay** [froala/wysiwyg-editor#3159]
If you want to save yourself support requests on this issue (and I can see there are a lot of them), you might add this ...

`$(selector).data('froala.editor').opts.imageUploadParam = 'originalImageName';
$(selector).data('froala.editor').opts.imageUploadParams = { abc: 'DEF' };`

to [this docs page](https://www.froala.com/wysiwyg-editor/docs/concepts/image/upload)

It will save a **lot** of time for those of us who want to set the parms after instantiating the editor.

**Comment by stefanneculai** [comment]
Thanks for the suggestion, @fmay. There is also: https://wysiwyg-editor.froala.help/hc/en-us/articles/360001329125-Can-I-change-an-option-after-initializing-the-editor-
