### ISSUE TITLE
Image TUI editor not working

### ISSUE THREAD

**Issue by sChupin** [froala/wysiwyg-editor#3161]
The TUI editor doesn't seem to work. I included `image_tui.min.css` and `image_tui.min.js`, and I added **imageTUI** in the list of plugin enabled in the Froala instance. I can see the new button _Advanced edit_ in the image pop up menu but nothing happens when I click it.

##### Expected behavior.
Display the TUI editor on _Advanced edit_ click in the image pop up menu.

##### Actual behavior.
Nothing happens when clicking the _Advanced edit_ button.

##### Steps to reproduce the problem.
Here is a fiddle with the last version of Froala (2.9.0) and the tui files (css & js) imported.
https://jsfiddle.net/hu15smgf/

Insert an image via the _Insert image_ button.
In the pop up image menu, click on _Advanced edit_.

##### OS.
MacOS High Sierra

##### Browser.
Opera 56

**Comment by stefanneculai** [comment]
See https://www.froala.com/wysiwyg-editor/examples/tui-advanced-image-editor. You should also include the TUI lib.

**Comment by pegasus1982** [comment]
Hi @stefanneculai 
I used react and I faced same problem.
So I tried with your way.

I added follows code section to index.html
```
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/tui-image-editor@3.2.2/dist/tui-image-editor.css">
  <link rel="stylesheet" href="https://uicdn.toast.com/tui-color-picker/latest/tui-color-picker.css">

  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/fabric.js/1.6.7/fabric.min.js"></script>
  <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/tui-code-snippet@1.4.0/dist/tui-code-snippet.min.js"></script>
  <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/tui-image-editor@3.2.2/dist/tui-image-editor.min.js"></script>
```

And **Toast UI Image Editor** worked perfectly.
You saved my life.
Thank you so much.

**Comment by alimoonmh** [comment]
thanks
