### ISSUE TITLE
froalaEditor.contentChanged event fired on clicking on CodeView button

### ISSUE THREAD

**Issue by javeriaanwer** [froala/wysiwyg-editor#3162]
content changed event is fired even though no content is changes in froala editor.
open froala editor and click on code view.

you can look this [example](https://jsfiddle.net/6Lrgwxbn/)

please provide any work around as it is continuously effecting my project's core functionality.

**Comment by stefanneculai** [comment]
See https://github.com/froala/wysiwyg-editor/issues/1465#issuecomment-248594297.

**Comment by javeriaanwer** [comment]
this comment does not answer my question, what I am saying is that without editing any thing in wysiwyg I clicked on code View button and content changed event is fired, that should not be the case, content change event should only fired when content is change in wysiwyg. 

my issue is related to [this] (https://github.com/froala/wysiwyg-editor/issues/3022)

please see this output.
![ezgif com-video-to-gif 7](https://user-images.githubusercontent.com/25203829/48395204-52e93480-e738-11e8-8050-708d511ddeb4.gif)

**Comment by stefanneculai** [comment]
That is because you should call `undo.reset` after you set the HTML: https://jsfiddle.net/froala/ab2qfj0r/.
