### ISSUE TITLE
Content creation- Major issue

### ISSUE THREAD

**Issue by AshishTiwariMEAN** [froala/wysiwyg-editor#3164]
I have tested this on multiple accounts, on multiple computers, and clients have also flagged same issue with me.
In content creation mode, text editor drops content outside of text editor, and does not allow publish.
I tested this in articles and benefits, but may be issue with all content creation i.e. groups, events etc.
![contentcreation-editor-issue_ew](https://user-images.githubusercontent.com/18064298/48336953-9b94e500-e687-11e8-9ca4-42ad72dd7d8f.png)

**Comment by stefanneculai** [comment]
@AshishTiwariMEAN it appears to be a problem from your config. Please contact us via our website: https://www.froala.com/wysiwyg-editor/contact.
