### ISSUE TITLE
CMD-K shortcut adds a new text with a link (instead of adding a link to selected text)

### ISSUE THREAD

**Issue by YannLeBihan** [froala/wysiwyg-editor#3165]
##### Expected behavior.
`CMD-K` shortcut should add a link to the selected text

##### Actual behavior.
On a Mac (couldn't test it on other systems) this shortcut creates a new text with the link at the end of the text, whereas the "create link" button works as expected.

##### Steps to reproduce the problem.
- Go to [Froala's test page](https://www.froala.com/wysiwyg-editor) on a Mac browser
- Select a portion of text
- Hit `CMD-K`
- Enter a url and validate
- A copy of the selected text, with the link applied, is added at the end of the text.
##### OS.
macOS 10.4.1

##### Browser.
Safari and Chrome

**Comment by tavosansal** [comment]
I am also experiencing this issue

**Comment by chrisdeeming** [comment]
Worth noting that Cmd/Ctrl+K also doesn't focus the URL input like it does if you trigger the popup with a click.

**Comment by seb303** [comment]
I can also confirm this bug on the PC, tested in latest Firefox and latest Chrome.
When Ctrl-K shortcut is used, the actual link is inserted right at the end of the document, not in the place of the selected text.  And additionally, focus is not set to the URL field of the pop-up form.
These are relatively recent bugs - Ctrl-K used to work fine.
When clicking the link button, everything works as it should.

**Comment by chrisdeeming** [comment]
Indeed. The issues you mention along with some other significant ones for us were introduced in v2.9.0. Unfortunately that version only brought us more problems than it solved and fixes haven't been as quick as they were in the past so we reverted back to using v2.8.5 in case that's any help. We'll stick with that until we see an improvement.

**Comment by seb303** [comment]
@chrisdeeming Thanks for the reply - we are in fact looking to roll back to an earlier version, so you have saved us testing to find a working release.  We too have noticed other new bugs, and slower response to fix them.

**Comment by chrisdeeming** [comment]
2.8.5 isn't perfect by any means and it depends on your exact use case (some new features were added in 2.9 so you will have to check you're not using them).

But for our use case, 2.9.0 actually only fixed one outstanding issue we had and we had to re-open that as there ended up being more to it. It introduced a few more issues though.

From our point of view, the following bugs still exist in 2.8.5 but they don't pose a major problem for us:

https://github.com/froala/wysiwyg-editor/issues/3242
https://github.com/froala/wysiwyg-editor/issues/3228
https://github.com/froala/wysiwyg-editor/issues/3197

**Comment by seb303** [comment]
Thanks, very useful.

**Comment by seb303** [comment]
Please re-open this issue as it is not fully fixed.
The other bug raised in this issue is when using Ctrl-K the focus is not set to the URL field of the pop-up form.  This was working fine in v2.8.5 and is not fixed in v2.9.2.

**Comment by stefanneculai** [comment]
It's fixed on the Github master, and will be included in release 2.9.3.

**Comment by seb303** [comment]
Just tried v2.9.3 now and can confirm fixed.  Thank you :)

**Comment by pandaa880** [comment]
I am having similar issue and we are using direct source code because we have done our own modifications. Because of some limitations as of now we can't upgrade. Where I can see the PR for this issue so I can make changes ?
 @stefanneculai
