### ISSUE TITLE
table border are not visible in iframe mode

### ISSUE THREAD

**Issue by javeriaanwer** [froala/wysiwyg-editor#3166]
insert table in froala editor, you will see empty editor as not borders are applied on that table

here is code:
```
$('div#froala-editor').froalaEditor({
  iframe: true
});

```
you can reproduce it in following link 

https://www.froala.com/wysiwyg-editor/examples/iframe
https://jsfiddle.net/froala/ojwhvppr/

![ezgif com-video-to-gif 8](https://user-images.githubusercontent.com/25203829/48466631-3b797c80-e808-11e8-8b38-99d5c6f11bcd.gif)

**Comment by stefanneculai** [comment]
Updated working example: https://jsfiddle.net/froala/ojwhvppr/323/.

**Comment by dawesi** [comment]
+1 we have the same issue css on iframe for table seems to be out

**Comment by deving2710** [comment]
@stefanneculai Thanks so much, this resolve the issue!!
