### ISSUE TITLE
table style and cell style are not working in iframe mode when table is set from html.set

### ISSUE THREAD

**Issue by javeriaanwer** [froala/wysiwyg-editor#3167]
1.  initialize froala editor in iframe mode  
       ` $('#editor').froalaEditor({ height: 300,iframe:true});`
2.  insert table in froala editor through [html.set](https://www.froala.com/wysiwyg-editor/docs/methods#html.set) command
`   $('#editor').froalaEditor('html.set'," <table style=\"width: 100%; empty-cells: show; max-width: 100%;\"><tbody><tr  style=\"user-select: none;\"><td style=\"width: 100%; background-color: rgb(97, 189, 109); min-width: 5px; user-select: text; border:black solid 2px;\"><br></td></tr></tbody></table>");`
3.  apply table style \ cell style

no styling is applied.

you can reproduce this bug [here](https://codepen.io/anon/pen/XyppvQ?editors=0010).

please look into this.

**Comment by stefanneculai** [comment]
The editor API is designed on an atomic design pattern. Thus, calling one method is not automatically doing all the job and you have to also call other methods, such as: https://www.froala.com/wysiwyg-editor/docs/methods#size.refresh.

**Comment by javeriaanwer** [comment]
What method should I use to clean table borders. As you can see, I set table with borders and I am not able to apply cell styling on it. 

here is the [code](https://codepen.io/anon/pen/dQdqoO?editors=0010)

`$('#editor').froalaEditor('html.set'," <table style=\"width: 100%; empty-cells: show; max-width: 100%;\"><tbody><tr style=\"user-select: none;\"><td style=\"width: 100%; background-color: rgb(97, 189, 109); min-width: 5px; user-select: text; border:black solid 2px;\"><br></td></tr></tbody></table>");`

![ezgif com-video-to-gif 11](https://user-images.githubusercontent.com/25203829/48882456-39cd3b80-ee3c-11e8-9eed-7c401205b530.gif)

it should allow me to apply cell styling whether table/cell already has border on it.

**Comment by stefanneculai** [comment]
We don't have an option at this moment for clearing the style and reverting it to a clear state.
