### ISSUE TITLE
cell style "Thick" is not applied on table cell

### ISSUE THREAD

**Issue by javeriaanwer** [froala/wysiwyg-editor#3168]
1. add table in froala editor
2. apply cell style thick on table cell

no styling is applied on cell

you can reproduce it [here](https://www.froala.com/wysiwyg-editor).

**Comment by javeriaanwer** [comment]
please see this.

![ezgif com-video-to-gif 9](https://user-images.githubusercontent.com/25203829/48530447-96b77780-e8b9-11e8-8097-efaae28399ad.gif)

Chrome: Version 70.0.3538.102 (Official Build) (64-bit)
Windows 10.

**Comment by stefanneculai** [comment]
Thick style is designed to set the cell borders to 2px. That appears to work correctly to me and you can see it in the attached screenshot.

<img width="1094" alt="screenshot 2018-11-16 at 17 40 21" src="https://user-images.githubusercontent.com/637004/48631217-be483600-e9c6-11e8-91a4-487617971ded.png">

**Comment by javeriaanwer** [comment]
I am trying this on chrome Version 70.0.3538.102 (Official Build) (64-bit) and it is not working.

**Comment by stefanneculai** [comment]
What OS are you using? Are you able to reproduce this in other browser as well?

**Comment by javeriaanwer** [comment]
It is only reproducing on Chrome, Windows 10 Enterprise.
