### ISSUE TITLE
Emojis are added in URL

### ISSUE THREAD

**Issue by rob-jed** [froala/wysiwyg-editor#3170]
Hey,

I've got a problem with emojis being added in URLs. For example typing or pasting  http://testdomain.com/page:Param/ will result in ":P" being replaced with emoji. Is there any way to disable emoji in that case?

**Comment by mimoskal** [comment]
I've got the same problem. I'm using `emoticons.min.js` plugin

**Comment by 86driver** [comment]
how can i use my personal emoji, 
in another words,  can i change the default url of emoji?
