### ISSUE TITLE
OL UL default option not working

### ISSUE THREAD

**Issue by sChupin** [froala/wysiwyg-editor#3171]
##### Expected behavior.
Clicking on *Default* option in OL or UL dropdown menu should reset the list style to default (i.e. number for OL and disc for UL).

This is not a big deal for UL as *disk* option is available in the dropdown menu but for OL there is no way to reset style to numbers except by removing the list and creating a new one.

##### Actual behavior.
Clicking on *Default* does not change the current OL or UL style.

##### Steps to reproduce the problem.
Here is a jsfiddle: https://jsfiddle.net/4jxr3mfx/415/
1. Create a OL or UL
2. Change type of list
3. Click on *Default* in the OL or UL menu

_Note:_ This fiddle includes the version 2.9.0 but I tried locally with 2.9.1 and got the the issue.

##### OS.
MacOS High Sierra

##### Browser.
Opera 56

**Comment by pirate-matt** [comment]
Did a little digging, doesn't look like that complex of a fix.

You could do something as simple as changing this: 
```javascript
$(blocks[i].parentNode).css('list-style-type', list_type);
```
to this:
```javascript
$(blocks[i].parentNode).css('list-style-type', list_type === 'default' ? '' : list_type);
```
