### ISSUE TITLE
html.get is giving different output every time for same data

### ISSUE THREAD

**Issue by javeriaanwer** [froala/wysiwyg-editor#3172]
1. initialize froala editor in iframe mode, [fullPage ](https://www.froala.com/wysiwyg-editor/docs/options#fullPage) enables iframe
` $('#froala-editor').froalaEditor({ height: 300, fullPage: true, useClasses: false });`
2. set html in froala editor through [html.set](https://www.froala.com/wysiwyg-editor/docs/methods#html.set) command.
`$("#froala-editor").froalaEditor('html.set', "<img alt=\"Embedded Image\" id=\"saveAsImg\" width=\"150\" height = \"50\" src=\"https://www.google.com.pk/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png\" >");
	`
3. now get html through [html.get](https://www.froala.com/wysiwyg-editor/docs/methods#html.get) command.
`var get1 = $("#froala-editor").froalaEditor('html.get');`
4. again get html through [same](https://www.froala.com/wysiwyg-editor/docs/methods#html.get) command 
`var get2 = $("#froala-editor").froalaEditor('html.get');`
5. now click inside editor then click outside editor and get html through [same](https://www.froala.com/wysiwyg-editor/docs/methods#html.get) command 
`var get3 = $("#froala-editor").froalaEditor('html.get');`

you will see `get1, get2` and `get3` results are different.

## In my case `get1` return this
`<!DOCTYPE html><html><head><title></title></head><body style="min-height: 280px;"><p><img alt="Embedded Image" id="saveAsImg" width="150" height="50" src="https://www.google.com.pk/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png" style="cursor: pointer; position: relative; max-width: 100%;" fr-original-style=""></p></body></html>`

**please note position of attributes 'style' and 'fr-original-style'**

## `get2` returns following result
`<!DOCTYPE html><html><head><title></title></head><body style="min-height: 280px;"><p><img alt="Embedded Image" id="saveAsImg" width="150" height="50" src="https://www.google.com.pk/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png" fr-original-style="" style="cursor: pointer; position: relative; max-width: 100%;"></p></body></html>`

**here you can see position of attributes 'style' and 'fr-original-style' are switched.**

## now in `get3` output is this
`<!DOCTYPE html><html><head><title></title></head><body style="min-height: 280px;"><p><img alt="Embedded Image" id="saveAsImg" width="150" height="50" src="https://www.google.com.pk/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png" fr-original-style="" fr-original-class="fr-draggable" style="cursor: pointer; position: relative; max-width: 100%;"></p></body></html>
`

**here you can see `"fr-draggable"` class is added to this image although I have not clicked on image.**

please give us some work around to avoid this issue. 

here is my html code

````
<script src="~/Scripts/jquery-1.10.2.min.js" type="text/javascript"></script>

<link href="~/Content/froala/css/froala_editor.pkgd.min.css" rel="stylesheet" type="text/css" />
<link href="~/Content/froala/css/froala_style.min.css" rel="stylesheet"/>

<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />

<script src="~/Scripts/froala/js/froala_editor.pkgd.min.js" type="text/javascript"></script>

<div id="main">
    <div id="froala-editor" style="left: 45px; width: calc(100% - 55px)">
    </div>
</div><br />
````

and jQuery code:

```
$(function() {
	$('#froala-editor').froalaEditor({
		height: 300,
		fullPage: true,
		useClasses: false
	});
	$("#froala-editor").froalaEditor('html.set', "<img alt=\"Embedded Image\" id=\"saveAsImg\" width=\"150\" height = \"50\" src=\"https://www.google.com.pk/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png\" >");
	var get1 = $("#froala-editor").froalaEditor('html.get');
	var get2 = $("#froala-editor").froalaEditor('html.get');
});
//Click inside editor then click outside editor and run following command in browser console window
var get3 = $("#froala-editor").froalaEditor('html.get');
```

**Comment by stefanneculai** [comment]
@javeriaanwer could you please make a jsFiddle?

**Comment by stefanneculai** [comment]
@javeriaanwer I actually made a jsFiddle for it: https://jsfiddle.net/froala/wc5c3jhk/2149/ and indeed I was able to reproduce your problem. Unfortunately, controlling the order of the attributes is not something that we'd be looking to do - the order of the attributes is set by the browser and if we'd try to change it that would be a huge performance drop.

Regarding draggable, I was not able to reproduce it. If you could update the jsFiddle to reflect that, I would be happy to open this again.

**Comment by javeriaanwer** [comment]
thank you @stefanneculai, for draggable, if image contains any class then "fr-draggable" is added after clicking inside froala editor.  i have modified your [jsFiddle](https://jsfiddle.net/3amht7gn/1/) for it.

steps to reproduce this bug is given below:

1. initialize froala editor in iframe mode, fullPage enables iframe
        `   $('#froala-editor').froalaEditor({ height: 300, fullPage: true, useClasses: false });`
2. set html in froala editor through html.set command.
`$("#froala-editor").froalaEditor('html.set', "<img alt=\"Embedded Image\" id=\"saveAsImg\" width=\"150\" height = \"50\" class = \"abc\" src=\"https://www.google.com.pk/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png\" >");`
3. now click inside editor then click outside editor and get html through following command
```
$("#froala-editor").on('froalaEditor.contentChanged',function(e, editor) {

	console.log($("#froala-editor").froalaEditor('html.get'));
});
```

you will notice fr-draggable class is added to content.
