### ISSUE TITLE
TextArea reload broken with Firefox

### ISSUE THREAD

**Issue by n-rodriguez** [froala/wysiwyg-editor#3174]
Hi there!

I'm using Froala Editor 2.9.1 in a Rails app.

I use Froala in Textarea Editor mode with `iframe: true` and `fullPage: true`.

On the first page load, the editor is correctly initialized and everything works well.

![screenshot_2018-11-15 clients](https://user-images.githubusercontent.com/3433835/48558026-81a60d00-e8e8-11e8-83ee-4db6166fc760.png)

When the form is submitted in Ajax (with Rails `remote: true`), the JS view re-renders the form and call Froala to initialize the editor. 

The editor is initialized but the content is empty :/

![screenshot_2018-11-15 clients2](https://user-images.githubusercontent.com/3433835/48557891-2f64ec00-e8e8-11e8-8a0d-7ab1d7d6e713.png)

Note: on the screenshot, the toolbar is displayed on top but it's a bug in the screenshot feature.

The original `textarea` is correctly filled and the bug only happens with Firefox. It works well with Google Chrome.

##### Expected behavior.
The editor content should be filled.

##### Actual behavior.
The editor content is not filled.

##### Steps to reproduce the problem.
See above

##### OS.
ArchLinux

##### Browser.
Firefox 63.0.1

**Comment by stefanneculai** [comment]
@n-rodriguez it looks like the page is being reloaded via AJAX without destroying the previous editor instance. Please make sure that before the page is being reloaded you destroy the editor instance by using the `destroy` method.

**Comment by n-rodriguez** [comment]
@stefanneculai I did try to destroy the editor but it doesn't work neither.
The editor is loaded, editor's content is loaded too, but the content blinks then become blank... :/

**Comment by n-rodriguez** [comment]
The editor's content seems to be reloaded because after the blink the iframe is empty (the text area input is filled)

**Comment by stefanneculai** [comment]
Can you replicate it here https://www.froala.com/wysiwyg-editor/examples/iframe?
