### ISSUE TITLE
TextArea broken with Safari

### ISSUE THREAD

**Issue by n-rodriguez** [froala/wysiwyg-editor#3175]
Hi there!

I'm using Froala Editor 2.9.1 in a Rails app.

I use Froala in Textarea Editor mode with `iframe: true` and `fullPage: true`.

On the first page load, the editor is not correctly initialized.

![mailing](https://user-images.githubusercontent.com/3433835/48558568-e0b85180-e8e9-11e8-8d34-ab02cbf044de.png)

The first load works well with Firefox and Google Chrome. (there is a bug on reload with Firefox, see: #3174)

(Sorry for the small screenshot, but we can see that the content is not correcly set)

##### Expected behavior.
The editor content should be correctly initialized.

##### Actual behavior.
The editor content is not correctly initialized.

##### Steps to reproduce the problem.
See above

##### OS.
Mac OS High Sierra 10.13.6

##### Browser.
Safari 12.0.1

**Comment by stefanneculai** [comment]
Please see: https://github.com/froala/wysiwyg-editor/issues/3174#issuecomment-439435283.

**Comment by n-rodriguez** [comment]
Can you please reopen this issue. This issue has nothing to do with https://github.com/froala/wysiwyg-editor/issues/3174.

**Comment by n-rodriguez** [comment]
This issue happens on the **first page load**.

**Comment by stefanneculai** [comment]
@n-rodriguez are you able to reproduce it on https://www.froala.com/wysiwyg-editor/examples/iframe?
