### ISSUE TITLE
The command emoticons.insert(...) always inserts as Unicode text

### ISSUE THREAD

**Issue by ConnorsFan** [froala/wysiwyg-editor#3176]
##### Expected behavior.
When the option `emoticonsUseImage` is set to `true`, the command `emoticons.insert(...)` should insert the emoticon as an SVG image.

##### Actual behavior.
Even when the option `emoticonsUseImage` is set to `true`, the command `emoticons.insert(...)` always inserts the emoticon as Unicode text.

##### Steps to reproduce the problem.
See [this jsfiddle](https://jsfiddle.net/ConnorsFan/a8s462ym/).

##### OS.
Windows 7

##### Browser.
Chrome 70
Firefox 63

**Comment by stefanneculai** [comment]
Actually, the `emoticons.insert` method has 2 params. The first is the unicode, while the 2nd one is the image to be inserted. We'll update the docs for it.

**Comment by ConnorsFan** [comment]
Can you give me an example so that I can try it?

**Comment by stefanneculai** [comment]
Sure: https://jsfiddle.net/froala/4vt96kga/

**Comment by ConnorsFan** [comment]
Thanks! It works well also in my Angular application.
