### ISSUE TITLE
 TextArea broken with Safari

### ISSUE THREAD

**Issue by n-rodriguez** [froala/wysiwyg-editor#3179]
Hi there!

I'm using Froala Editor 2.9.1 in a Rails app.

I use Froala in Textarea Editor mode with `iframe: true` and `fullPage: true`.

**On the first page load** (meaning: "when you arrive on the page with the editor after a click on 'Edit content'"), the editor is not correctly initialized.
 
![mailing](https://user-images.githubusercontent.com/3433835/48558568-e0b85180-e8e9-11e8-8d34-ab02cbf044de.png)

WTF?

##### Expected behavior.
The editor content should be correctly initialized.

##### Actual behavior.
The editor content is not correctly initialized.

It's a full HTML page and the editor displays the HTML source code and not the HTML rendered content.

##### Steps to reproduce the problem.
See above

##### OS.
Mac OS High Sierra 10.13.6

##### Browser.
Safari 12.0.1

**Comment by n-rodriguez** [comment]
Can you please help me solving this issue? I pay my subscription (Froala is not free) and I need some help.

**Comment by n-rodriguez** [comment]
Here the JS I use : 

```coffee
$(element).froalaEditor
  key: $(element).data('key')
  language: $(element).data('language')
  iconsTemplate: 'font_awesome_5'
  heightMin: 600
  fullPage: true
  iframe: true
  htmlUntouched: true
  htmlAllowComments: true
  iframeDefaultStyle: ''
  codeBeautifierOptions:
    indent_size: 2
  toolbarButtons: [
    'undo', 'redo', 'bold', 'italic', 'underline', '|',
    'fontFamily', 'fontSize', 'color', '|',
    'paragraphFormat', 'paragraphStyle', '|',
    'align', 'insertTable', 'insertLink', '|',
    'fullscreen', 'html'
  ]
```

**Comment by n-rodriguez** [comment]
The same code works with Froala 2.8.5. (I rollbacked Froala to this version, so my customer can have a working version of their tool)

**Comment by stefanneculai** [comment]
Closing this here and moving discussion to the support channel for access to the staging env.
