### ISSUE TITLE
TextArea reload broken with Firefox

### ISSUE THREAD

**Issue by n-rodriguez** [froala/wysiwyg-editor#3180]
Hi there!

I'm using Froala Editor 2.9.1 in a Rails app.

I use Froala in Textarea Editor mode with `iframe: true` and `fullPage: true`.

On the first page load, the editor is correctly initialized and everything works well.

![screenshot_2018-11-15 clients](https://user-images.githubusercontent.com/3433835/48558026-81a60d00-e8e8-11e8-83ee-4db6166fc760.png)

When the form is submitted in Ajax (with Rails `remote: true`), the JS view re-renders the form and call Froala to initialize the editor. 

The editor is initialized but the content is empty :/

![screenshot_2018-11-15 clients2](https://user-images.githubusercontent.com/3433835/48557891-2f64ec00-e8e8-11e8-8a0d-7ab1d7d6e713.png)

Note: on the screenshot, the toolbar is displayed on top but it's a bug in the screenshot feature.

The original `textarea` is correctly filled and the bug only happens with Firefox. 

**It works with Google Chrome**.

##### Expected behavior.
The editor content should be filled.

##### Actual behavior.
The editor content is not filled.

##### Steps to reproduce the problem.
See above

##### OS.
ArchLinux

##### Browser.
Firefox 63.0.1

**Comment by n-rodriguez** [comment]
Here the JS I use : 

```coffee
$(element).froalaEditor
  key: $(element).data('key')
  language: $(element).data('language')
  iconsTemplate: 'font_awesome_5'
  heightMin: 600
  fullPage: true
  iframe: true
  htmlUntouched: true
  htmlAllowComments: true
  iframeDefaultStyle: ''
  codeBeautifierOptions:
    indent_size: 2
  toolbarButtons: [
    'undo', 'redo', 'bold', 'italic', 'underline', '|',
    'fontFamily', 'fontSize', 'color', '|',
    'paragraphFormat', 'paragraphStyle', '|',
    'align', 'insertTable', 'insertLink', '|',
    'fullscreen', 'html'
  ]
```

**Comment by n-rodriguez** [comment]
In `create.js.erb` :

```js
Mailing.destroy_text_editor('#custom_mailing_body'); // destroy editor before re-render the form
<%= js_render_partial('#new_custom_mailing', "mailings/custom_mailings/form", method: :replace) %> // re-render invalid form (it replaces the #new_custom_mailing form with a new one)
Mailing.create_text_editor('#custom_mailing_body'); // create text editor
```

**Comment by n-rodriguez** [comment]
I repeat : **it works with Google Chrome with or without the code above**

**Comment by stefanneculai** [comment]
@n-rodriguez do you think you could create a demo app on Github and send it to us to test?

**Comment by n-rodriguez** [comment]
> @n-rodriguez do you think you could create a demo app on Github and send it to us to test?

I can give you access to the staging environment if you want.

**Comment by stefanneculai** [comment]
Please reach us on the support channel with more details on that: https://www.froala.com/wysiwyg-editor/contact.

**Comment by stefanneculai** [comment]
I am going to close this in the meanwhile here.
