### ISSUE TITLE
Initializing a froala editor on a div that has embedly content doesn't always render the embedly card

### ISSUE THREAD

**Issue by wmacdonald919** [froala/wysiwyg-editor#3181]
Opening a new ticket as this is still an issues even after latest release
#2654

##### Expected behavior.
On initialization of froala on a div containing Embedly content, Embedly card should be rendered

##### Actual behavior.
Sometimes card is rendered, sometimes it is not

##### Steps to reproduce the problem.
Create a div with embedly content. Initialize Froala on that div
https://jsfiddle.net/7k0txegw/
You can see it renders properly sometimes, but not all the time. This may seem like a small issue, but when you factor in a large number of users, this issue becomes more prevalent.

##### OS.
High Sierra 10.13.6

##### Browser.
All browsers

**Comment by stefanneculai** [comment]
@wmacdonald919 I am not able to reproduce it. Do you think you could make a recording?

**Comment by wmacdonald919** [comment]
![kapture 2018-11-22 at 11 15 55](https://user-images.githubusercontent.com/19154574/48913969-0a243080-ee48-11e8-97e8-601fab1a3096.gif)

Luckily was able to get it to happen. It's difficult because this doesn't happen all the time. In my fiddle I have a delay to mimic how it currently functions for our clients when clicking edit on the page. If you can see in the GIF, the card simply isn't fully rendered. On refresh it appears but may also not appear. Not sure if it is a race condition or Embedly not queueing things correctly

**Comment by stefanneculai** [comment]
To me it looks more like embedly plugin not working correctly, as they should be able to detect when the document is ready to apply the script. I think it might be good to reach them and ask for an opinion on that.

**Comment by stefanneculai** [comment]
@wmacdonald919 actually it is a problem from the editor and we're going to fix in the next release. Fix is already ready, we just have to do a bit of more review. In the meanwhile, please use this fix: https://jsfiddle.net/froala/f6wc4khn/.

**Comment by stefanneculai** [comment]
It is going to be a minor release - `2.9.2`
