### ISSUE TITLE
br tag add by default in empty p/div tag

### ISSUE THREAD

**Issue by GnanaAjana** [froala/wysiwyg-editor#3182]
Using ember froala editor.
##### Expected behavior.
When empty div/p tag should be like as empty div/p tag.

##### Actual behavior.
In froala editor, empty tag add <br> tag default. 

I seen suggested option for this issue, like

fillEmptyBlocks method(there is no option in froala editor), $.FE.BLOCK_TAGS(tried this, but gives unexpected behavior)

It doesn't work for me. Is this issue is fixed, or is there any other solution for it?

**Comment by GnanaAjana** [comment]
Any update on this?

**Comment by stefanneculai** [comment]
@GnanaAjana Do you think it would be possible to make a jsFiddle to highlight the problem? That would speed-up things a lot. Here is a basic jsFiddle you could use as a starting point: https://jsfiddle.net/froala/wc5c3jhk/.

**Comment by stefanneculai** [comment]
I am closing this as we don't have a way to reproduce it. I would be happy to look into it again, if you could provide a jsFiddle to reproduce it.

**Comment by w20k** [comment]
Can't provide a jsFieddle right now, but here is a gif, it might be because of our configs...will look at those.

Gif:
![Apr-03-2019 12-35-27](https://user-images.githubusercontent.com/1053320/55468928-1b0e5b00-560d-11e9-94e7-85f403900bbb.gif)

**Comment by hunter2009** [comment]
I met the same problem
