### ISSUE TITLE
code <pre> reformat creating Â character when pasting from word/notepad/anywhere

### ISSUE THREAD

**Issue by frogga67** [froala/wysiwyg-editor#3185]
##### Expected behavior.
Format the code with spaces

##### Actual behavior.
Â where spaces should be

##### Steps to reproduce the problem.

```
//Write some code
if(this)
{
    if(that)
    {
        if(this)
        {
            //do this
        }
    }
}
```

Paste code in editor
Select text
Click format and change it to "Code"
Press Save button
Reload page

Result

//Write some code
if(this)
{
Â  Â  if(that)
Â  Â  {
Â  Â  Â  Â  if(this)
Â  Â  Â  Â  {
Â  Â  Â  Â  Â  Â  //do this
Â  Â  Â  Â  }
Â  Â  }
}

![2018-11-22_17-58-31](https://user-images.githubusercontent.com/7875645/48886703-0d87de00-ee81-11e8-9d02-5813360455ca.gif)

Note if you manually space out the code then click save it looks correct.

##### OS.
Windows 10 version 1803

##### Browser.
Chrome 70.0.3538.102 and Chrome Beta 71.0.3578.62

##### Browser.
Froala version 2.9.1

**Comment by stefanneculai** [comment]
@frogga67 it looks you're having a bad encoding there on the page. Could you please check if the encoding on the page is set to utf-8?

**Comment by frogga67** [comment]
@stefanneculai just checked, the encoding is set to urf-8 in the database.

If the pasted code goes into froala like this:

<p>if(this)<br>    dothis</p>

and converted to "code"<pre>, it works but if the pasted code goes into froala like this

<p>if(this)</p><p>    dothis</p>

and converted to "code"<pre>, it breaks

**Comment by frogga67** [comment]
Code that is written in froala and copied to notepad and copied back looks correct, but code that is written in notepad breaks.

![2018-11-23_11-47-56](https://user-images.githubusercontent.com/7875645/48925276-15459200-ef16-11e8-86f2-5287ddd41ade.gif)
