### ISSUE TITLE
image styles not applied in iframe mode

### ISSUE THREAD

**Issue by javeriaanwer** [froala/wysiwyg-editor#3187]
when I applied image style such as bordered, Rounded or shadow, it is not applied on image.
```
$('div#froala-editor').froalaEditor({
  iframe: true
});
```

froala version: 2.9.0
browser: Chrome
OS: windows 10 Enterprise

you can verify it [here](https://jsfiddle.net/4j79zs0h/)

![ezgif com-video-to-gif 12](https://user-images.githubusercontent.com/25203829/48929068-ee339400-ef06-11e8-8567-070a07fbd02e.gif)

**Comment by stefanneculai** [comment]
You can include it only in the iframe.
