### ISSUE TITLE
Image size is not set when a caption is present

### ISSUE THREAD

**Issue by TimMeissner** [froala/wysiwyg-editor#3189]
##### Steps to reproduce the problem.
Insert an image to the froala editor. 
Set a caption
Set size to 100%

##### Expected behavior.
The image takes the full width.

##### Actual behavior.
The image size does not change. It does change when no caption is set.

##### OS.
Mac OS Mojave

##### Browser.
Chrome 72

**Comment by TimSielemann** [comment]
I created a video of the problem:

[Video](https://github.com/froala/wysiwyg-editor/files/2619061/Bildschirmaufnahme.zip)
