### ISSUE TITLE
Custom Color Picker can fail for table cells: Cannot read property 'min_i' of null

### ISSUE THREAD

**Issue by srosenthal** [froala/wysiwyg-editor#3190]
##### Expected behavior.
It should be possible to change the color of a cell in a table to a hex code such as #fa8072.

##### Actual behavior.
After a certain sequence of events, the color picker will ignore inputs and instead print errors to the browser console.

##### Steps to reproduce the problem.
1. Use the online demo for the custom color picker at https://www.froala.com/wysiwyg-editor/examples/colors
2. This particular demo doesn't have tables enabled, so we'll need to paste one in. Copy any HTML table to the clipboard, and paste it into the editor. I used the table from https://www.w3schools.com/html/html_tables.asp
3. Click to select a table cell, then select the paint drop icon to select a color.
4. Use the mouse to _drag_ and select any text in the "HEX Color" input text box. Release the mouse button while it is over a different cell in the table.
5. Now, type in a hex code and press OK. Or choose one of the pre-selected colors. Neither will work. Observe errors in the browser console "Uncaught TypeError: Cannot read property 'min_i' of null"

_Screenshot_:
![screen shot 2018-11-26 at 10 40 32 am](https://user-images.githubusercontent.com/1145646/49034942-33a2cc00-f168-11e8-9dc1-7167989e4862.png)

_Technical details_: We read through the code, and the problem seems to be that when you click on a table cell it gains a class ".fr-selected-cell". But when you drag and release a mouse to select the hex code, that class is removed. The color picker is then unable to make the color change, since it doesn't know where to apply it.

_Workaround_: don't drag your mouse to select the hex code. Instead, use only the keyboard (backspace/delete/select-all) to edit the hex code.

##### OS.
macOS Mojave 10.14.1, but also reproduced on Windows

##### Browser.
Google Chrome Version 70.0.3538.102 (Official Build) (64-bit)

**Comment by stefanneculai** [comment]
@srosenthal do you think you could also send a recording?

**Comment by srosenthal** [comment]
@stefanneculai sure! I took a recording and posted it on Youtube: https://youtu.be/5nbSQ49wF60

**Comment by keshav121992** [comment]
Uncaught TypeError: Cannot read property 'colorPicker'

**Comment by keshav121992** [comment]
Uncaught TypeError: Cannot read property 'colorPicker' Can you please help me on this before loading the spreadsheet its throwing error but spreadsheet loading successfully
