### ISSUE TITLE
Cannot insert text after an inline-block with contenteditable=false

### ISSUE THREAD

**Issue by LoicLopes** [froala/wysiwyg-editor#3191]
##### Expected behavior.
When you have an element with `display: inline-block` and `contenteditable="false"` at the end of a paragraph, click after it. Type on your keyboard and text is added in the editor.

##### Actual behavior.
When you have an element with `display: inline-block` and `contenteditable="false"` at the end of a paragraph, click after it. If you type on your keyboard, the text is not added in the editor.

##### Steps to reproduce the problem.
You can see an example with predefined content here : [https://jsfiddle.net/do9xtavj/](https://jsfiddle.net/do9xtavj/)

##### OS.
Windows 10

##### Browser.
Chrome 70 and Firefox 63

Thanks !

**Comment by stefanneculai** [comment]
@LoicLopes unfortunately, this is a browser problem and there is not too much we could do about it. We have on our plan to do something different for non-editable text and we're planning on how to roll that out.

**Comment by junzero741** [comment]
any update? @stefanneculai
