### ISSUE TITLE
embeded view of document in froala

### ISSUE THREAD

**Issue by javeriaanwer** [froala/wysiwyg-editor#3194]
I want to embed a document in froala editor. like this 

![image](https://user-images.githubusercontent.com/25203829/49287597-f15af100-f4bf-11e8-84ac-ab3d7f6db757.png)

how can I achieve this?

**Comment by stefanneculai** [comment]
At this moment we don't have this feature, however, please make sure you subscribe to our newsletter to receive news as soon as it becomes available: https://www.froala.com/wysiwyg-editor/download#updates. You can also upvote it here: https://wysiwyg-editor-roadmap.froala.com/public.
