### ISSUE TITLE
Resizing a video changes width/height attribute to style tag

### ISSUE THREAD

**Issue by adamcooper** [froala/wysiwyg-editor#3198]
##### Expected behavior.
The width and height attribute in the iframe video tag are left alone after resizing a video

E.g. `<iframe src="https://www.youtube.com/embed/vJMLJVha5sw?wmode=opaque" frameborder="0" allowfullscreen="" class="fr-draggable" width="800" height="500"></iframe>`

##### Actual behavior.
The width and height attributes are converted to a style after resizing.

eg. `<iframe src="https://www.youtube.com/embed/vJMLJVha5sw?wmode=opaque" frameborder="0" allowfullscreen="" class="fr-draggable" style="width: 800px; height: 500px;"></iframe>`

##### Steps to reproduce the problem.
1. Click the insert video button and copy and paste a video tag in: `https://www.youtube.com/embed/vJMLJVha5sw`
2. Switch to HTML mode and observe the `height` and `width` attributes being used.
3. Switch to WYSIWYG mode
4. Resize video - Click video, select resize icon, enter new amounts, or drag and resize.
5. Switch to HTML mode and observe the height and width are in the style tag.

##### OS.
Mac OSX 10.14.1

##### Browser.
Chrome Version 70.0.3538.110 

##### Recording.
![froala](https://user-images.githubusercontent.com/12883/49477386-a5ff5600-f7d1-11e8-8b84-4a2a390b68c5.gif)

**Comment by stefanneculai** [comment]
We just reviewed it and we're going to keep it this way as we're using the same behavior for images.
