### ISSUE TITLE
Toolbar at the bottom of the editor, popup to open above, not below

### ISSUE THREAD

**Issue by erdillon** [froala/wysiwyg-editor#320]
I would like to have the toolbar at the bottom of the editor.
I've managed to put it there using CSS tricks with display: table as shown below, but then the popups open below, and are out of scope of the editor (outside of the window/modal).

So... is there a proper way of setting the toolbar to the bottom? And/Or forcing the popups to pop above the toolbar.

Thanks.

.froala-box {
  display: table;
  width: 100%;
}
.froala-editor {
  display: table-footer-group;
}
.froala-wrapper {
  display: table-header-group;
}

**Comment by timavaza** [comment]
We now have the opposite issue.
Froala now allows setting the toolbar to the bottom, but it doesn't allow you to set the direction of the popups. So we are forced to have popups opening upwards, which then go off the screen (as the control is near the top of the screen)
Froala needs to be designed to have flexibility, so the control can be placed anywhere on the screen elegantly.

**Comment by sampadabhatnagar** [comment]
Any updates on this error being resolved in version 3.0.5 ?

**Comment by chanwooro** [comment]
Any update on this?
All of my popups sit under elements and I would like it to put it at the top..

**Comment by coding-bird** [comment]
> I created #326 and marked it as `feature-request`. If there will be interest for such a feature, we'll add it.

This feature work well for popups which position itself based on the position of the button. but there are few selection based popups(like insertLink), which goes out of the editor if your is at the end or adds horizonal scroll if its on the right. Ideally the popup should place itself based on the available space around, like tooltips.
