### ISSUE TITLE
The TUI Colorpicker display is incorrect.

### ISSUE THREAD

**Issue by largeden** [froala/wysiwyg-editor#3200]
##### Expected behavior.
![2018-12-05 20 16 18](https://user-images.githubusercontent.com/5575931/49510259-fdcdb800-f8ca-11e8-93d7-b9fea41dcd55.png)

##### Actual behavior.
![2018-12-05 20 14 44](https://user-images.githubusercontent.com/5575931/49510250-f8706d80-f8ca-11e8-965d-9871f4fb581d.png)

##### OS.
OSX Mojave, Windows 10 pro

##### Browser.
Chrome, Firefox

--

To use the TUI Colorpicker properly, you need to use the plugin below.
https://github.com/nhnent/tui.color-picker
https://www.jsdelivr.com/package/npm/tui-color-picker

**Comment by dianaprajescu** [comment]
Thanks for pointing this out @largeden. It's fixed now.
