### ISSUE TITLE
Custom attributes for linkList are removed

### ISSUE THREAD

**Issue by guilabonte** [froala/wysiwyg-editor#3206]
##### Expected behavior.
When I add custom attributes to the links in my link list, they are added to the created <a> tag.

##### Actual behavior.
All custom attributes are removed when the list is tranformed in <a> tag.

##### Steps to reproduce the problem.
Send this JSON list into linkList property : 

[
       {
		"text": "Test Hyperlien1",
		"href": "http://google.ca",
		"target": "_blank",
		"data-mediaid": "H:3",
		"data-mediatype": "H"
	},
	{
		"text": "Test Hyperlien2",
		"href": "http://google.ca",
		"target": "_blank",
		"data-mediaid": "H:4",
		"data-mediatype": "H"
	}
]

##### OS.
Windows

##### Browser.
All

**Comment by stefanneculai** [comment]
@guilabonte Do you think it would be possible to make a jsFiddle to highlight the problem? That would speed-up things a lot. Here is a basic jsFiddle you could use as a starting point: https://jsfiddle.net/froala/wc5c3jhk/.

**Comment by guilabonte** [comment]
https://jsfiddle.net/gui_labonte/hgdx06sj/1/

**Comment by stefanneculai** [comment]
Thanks for further details, @guilabonte. At this moment, the link predefined list is designed to be using only the options available in the UI. We consider this more of a feature-request. Do you mind adding a request for it on https://wysiwyg-editor-roadmap.froala.com/public?
