### ISSUE TITLE
Pasting ordered and unordered list from Word doesn't retain proper formatting for nested items

### ISSUE THREAD

**Issue by bs-project-android** [froala/wysiwyg-editor#3208]
##### Expected behavior.
Copying and pasting an ordered and unordered list from Word should retain the formatting for indented (child) list items.

##### Actual behavior.
The ordered list is pasted in as "number, number, bullet (not an ordered list type), number." The unordered list is correct until the fourth nested item when everything then becomes the default bullet.

It seems that word uses a loop for formats. Ordered lists are "Number, lowercase alpha, roman numeral" then repeat. Unordered lists are "Closed circle, open circle, square" then repeat. It would be nice to have that same functionality here as opposed to making everything the default list type after three indentations.

##### Steps to reproduce the problem.
Create an ordered and unordered list in Word with at least 4-5 indented list items. Paste into Froala editor and choose the Word "clean" option.

<img width="825" alt="screen shot 2018-12-14 at 11 42 03 am" src="https://user-images.githubusercontent.com/41091970/50024076-165a6400-ff96-11e8-9357-ec3326317bc1.png">

<img width="1090" alt="screen shot 2018-12-14 at 11 42 37 am" src="https://user-images.githubusercontent.com/41091970/50024085-1bb7ae80-ff96-11e8-8fa2-f7e928abf16a.png">

##### OS.
macOS Mojave 10.14.1

##### Browser.
Chrome 70.0.3538.110

**Comment by stefanneculai** [comment]
We just reviewed it and at this moment, the Word implementation is not designed to keep that formatting. I would suggest opening a feature request on https://wysiwyg-editor-roadmap.froala.com/public. Thanks in advance. 🙏
