### ISSUE TITLE
Can't drag images when they have focus (Froala v2.9.1)

### ISSUE THREAD

**Issue by SeanKendle** [froala/wysiwyg-editor#3209]
##### Expected behavior.
Should be able to drag image when it has focus (resize handles shown/menu open)

##### Actual behavior.
Can't drag image when it has focus.

##### Steps to reproduce the problem.
https://www.froala.com/wysiwyg-editor
Click image to give it focus
Try to drag it to a new location
Image won't drag

Click away so the image loses focus
Click and drag immediately so it doesn't get focus
Image will drag

##### OS.
Windows 7 Pro

##### Browser.
FF and Chrome, both latest versions

**Comment by stefanneculai** [comment]
Thanks for reporting it @SeanKendle. It looks it was introduced in https://github.com/froala-labs/froala-editor-js-2/commit/86a5af90ba05b3c2f4298786f262fed19e7f5dc5#diff-533f18d9df1023739c9f58853f604cdc.

**Comment by SeanKendle** [comment]
This is still a bug in v2.9.2
