### ISSUE TITLE
Code view does not disable OL and UL toolbar buttons

### ISSUE THREAD

**Issue by WayneUong** [froala/wysiwyg-editor#3211]
When switching to code view, the expected behaviour is that all other buttons become disabled.

![screen shot 2018-12-21 at 10 24 31 am](https://user-images.githubusercontent.com/8436742/50357446-e289bc00-050a-11e9-9b39-2156e84ec022.png)

**Comment by Doddi-jd-h** [comment]
Similar problem when clicking on the picture

![2019-01-14_15-12_beautiful wysiwyg html editor](https://user-images.githubusercontent.com/6823585/51112102-5f107180-180f-11e9-93e7-1c3446b2bfd0.jpg)

**Comment by stefanneculai** [comment]
Should be fixed on the current master.
