### ISSUE TITLE
[Edge] image moves in next line when click on image 

### ISSUE THREAD

**Issue by javeriaanwer** [froala/wysiwyg-editor#3214]
add image and set Display as "Break Text", click inside editor next to image.

Expected Output:
nothing should happen.

Actual Output: 
image moves in next line.

![ezgif com-video-to-gif 16](https://user-images.githubusercontent.com/25203829/50436694-f9645000-0908-11e9-99ac-69b24880c1fd.gif)

it is occurring in Edge only.  https://codepen.io/anon/pen/LMLJOb?editors=0010

please provide us some solution we are using froala version 2.8.4.  

OS:
Windows 10

Browser:
Microsoft Edge 42.17134.1.0

**Comment by stefanneculai** [comment]
@javeriaanwer are you able to reproduce it with the latest 2.9.1 version?

**Comment by stefanneculai** [comment]
I just tried to reproduce it on the website demo https://www.froala.com/wysiwyg-editor which is using the version 2.9.2 and works fine to me. I used the latest Edge and Windows 10 on BrowserStack.
