### ISSUE TITLE
vue-froala-wysiwyg is crashing in chrome mobile

### ISSUE THREAD

**Issue by waqaar145** [froala/wysiwyg-editor#3215]
Editor is working fine in desktop browser such as chrome, firefox and IE.

When I am using on chrome mobile it is unexpectedly crashing  while typing. I thought it would have been fixed in newer updated version but facing same issue. Currently I have version 2.8.4

(Browser name an version here)
Chrome mobile 71.0.3578.99

**Comment by lovelyelfpop** [comment]
You need a licence when you put the editor online on your site, but not for localhost development.
It will turn to a textarea if no license

**Comment by waqaar145** [comment]
I don't think that is the issue, if so then why it's running on desktop browser but not on mobile browser and yes i am opening website on the same IP but crashing only in mobile browser.
