### ISSUE TITLE
Pasting from Excel gets an image instead of a table

### ISSUE THREAD

**Issue by miyazakijunichi** [froala/wysiwyg-editor#3217]
##### Expected behavior.
Pasting table from excel into the editor should create a html table

##### Actual behavior.
The table creates image in the editor

##### Steps to reproduce the problem.
Paste some table in the editor.

##### OS.
Windows 10
Excel 2016

##### Browser.
Chrome, Edge

##### Recording.

![xt50o-n2nnx](https://user-images.githubusercontent.com/10162699/50500607-e337ca80-0a95-11e9-8a0a-7961a41390a5.gif)
[example.xlsx](https://github.com/froala/wysiwyg-editor/files/2713839/example.xlsx)

**Comment by Santhosini** [comment]
I'm facing a similar issue when I paste content from OneNote 2016. The content gets copy-pasted into an image from a Windows machine.

**Comment by stefanneculai** [comment]
Same with froala-labs/froala-editor-js-2#677.

**Comment by stefanneculai** [comment]
Should be fixed on the current master.

**Comment by miyazakijunichi** [comment]
Thanak you for fixing!

**Comment by kp-thibaut** [comment]
I got the same issue today.
Tested with 2.9.2 / 2.9.3 / master on Edge / Windows 10.

Is there anything to do for this to work ?

**Comment by Gabvo94** [comment]
Hello, 
We have the same issue with pasting from Excel to the editor in Safari. Can you help us out?

**Comment by natanaelsimoes** [comment]
> Hello,
> We have the same issue with pasting from Excel to the editor in Safari. Can you help us out?

+1
