### ISSUE TITLE
When adding formatting to a link sometimes the span is placed inside the <a> tag.

### ISSUE THREAD

**Issue by swarzech** [froala/wysiwyg-editor#3220]
Hi,
I am having an issue where formatting the text of a link will break the click functionality.

When changing the color or other formatting options of a link sometime the <span> and <strong> tags are placed inside the <a> tag.  This behavior is inconsistent as some times the link will be formatted correctly with the <span> outside the link even in the same session.

This is causing the following behavior:
- Single click on the link opens a blank webpage
- Right click on the link, open in new tab, opens the link correctly

OS: Mac OS High Sierra
Browser Chrome 70.0.3538.110 (Official Build) (64-bit)
Froala Version: 2.8.5

**Comment by stefanneculai** [comment]
@swarzech could you please provide details about how we can reproduce this problem on our website: https://www.froala.com/wysiwyg-editor?

**Comment by stefanneculai** [comment]
I am closing this to lack of details. I would be happy to reopen it if we get more details.
