### ISSUE TITLE
Font Size and Font Family Bug

### ISSUE THREAD

**Issue by angeliuz** [froala/wysiwyg-editor#3221]
When I use a Font Family name with two words like "Arial Black" and change the Font Size the Style is compose with same quotes

Ej: 
`<span open="" style="font-family: "Open Sans Condensed", sans-serif; font-size: 23px;">Breve descripción</span>`

or

`<span open='' style='font-family:'Open Sans Condensed', sans-serif; font-size: 23px;'>Breve descripción</span>`

That is a problem for save the html string.

Have you any solution for thats?

**Comment by stefanneculai** [comment]
@angeliuz Do you think it would be possible to make a jsFiddle to highlight the problem? That would speed-up things a lot. Here is a basic jsFiddle you could use as a starting point: https://jsfiddle.net/froala/wc5c3jhk/.

**Comment by stefanneculai** [comment]
Closing this due to lack of response. Would be happy to look into it if we get more details.
