### ISSUE TITLE
Inconsistent tooltips in lists

### ISSUE THREAD

**Issue by awegmueller** [froala/wysiwyg-editor#3226]
##### Expected behavior.
All commands/lists should have the same tooltip type.

##### Actual behavior.
Some commands/lists like 'quote' and 'horizontal alignment' have pretty tooltips with a dark background, but most commands/lists like 'ordered list' show a plain browser tooltip. This makes the command-bar look inconsistent. 

**(1)** A list with plain browser tooltips

![froala-translate-bug-2](https://user-images.githubusercontent.com/1409867/50904349-54756700-1420-11e9-8094-6d51e404f7d4.png)

**(2)** A list with pretty tooltips

![froala-translate-bug-3](https://user-images.githubusercontent.com/1409867/50904372-62c38300-1420-11e9-8403-9907469ad613.png)

##### OS.
Windows 10

##### Browser.
Chrome 71.0.3578.98

**Comment by stefanneculai** [comment]
Thanks for the feedback @awegmueller. Last commit is changing the way shortcuts are being shown. The tooltip was designed there mainly for shortcuts and it doesn't make sense to show it for the rest of the elements where no shortcuts are available and just show the same text.
