### ISSUE TITLE
Toolbar should not show hover/focus state when disabled

### ISSUE THREAD

**Issue by awegmueller** [froala/wysiwyg-editor#3227]
##### Expected behavior.
When the editor is disabled the buttons in the toolbar should not react to hover or focus state.

##### Actual behavior.
When the editor is disabled with froalaEditor('edit.off') the icons in the toolbar are grayed out. However, when the user hovers over an icon, the icon still becomes black. When a disabled icon is clicked  (=focused) the icon stays black even when the mouse does not hover over the icon. When the  editor/toolbar is disabled all icons should stay gray, otherwise the user has the impression the icon is still active.

![froala-disabled-bug](https://user-images.githubusercontent.com/1409867/50904784-83400d00-1421-11e9-9dfa-389062292c18.png)

##### Steps to reproduce the problem.
Disable the editor with froalaEditor('edit.off'), hover over an icon (for example "I", italic) --> the icon becomes black, click on that icon --> the icon stays black until the user clicks somewhere else.

##### OS.
Windows 10

##### Browser.
Chrome 71.0.3578.98

**Comment by stefanneculai** [comment]
Please also call https://www.froala.com/wysiwyg-editor/docs/methods#toolbar.disable. Although these methods might seem to do the same thing, they are disabling different parts.
