### ISSUE TITLE
Manually pasted image URLs are converted to https://i.froala.com/download/..." by the editor.

### ISSUE THREAD

**Issue by drlube** [froala/wysiwyg-editor#3229]
##### Expected behavior.
Image URLs (PNGs at https:// URLs) that are manually input into the editor should maintain their integrity.

##### Actual behavior.
The source URL for images that our client is pasting directly into Froala switches eventually to a variation of a "https://i.froala.com/download/...".

##### Steps to reproduce the problem.
Not sure exactly how this is happening (a client reported it), but I can see that their editor is indeed replaced with the https://i.froala.com/download/ links. Can you describe the cases where this would happen?

![image](https://user-images.githubusercontent.com/46380/50934830-b9c85880-141e-11e9-84f2-faa35c3badb8.png)

##### OS.
OS X 10.13.6

##### Browser.
Chrome 71.0.3578.98

**Comment by stefanneculai** [comment]
See https://www.froala.com/wysiwyg-editor/docs/options#imageUploadRemoteUrls
