### ISSUE TITLE
Thumbnail not displayed when image uploaded using file upload

### ISSUE THREAD

**Issue by nidhin038** [froala/wysiwyg-editor#3232]
##### Expected behavior.
When trying to upload image/video using file upload, thumbnail should be displayed if it is an image and video preview should be shown if its a video.

##### Actual behavior.
Thumbnail is not displayed when uploading image using file upload. Instead the image name is displayed.

##### Steps to reproduce the problem.
Upload an Image using file upload rather than image upload.

##### OS.
macOs 10.13.6

##### Browser.
Firefox 60.0.2

##### ScreenShot.

![image](https://user-images.githubusercontent.com/1975529/51015972-75f75f80-1594-11e9-9dcb-298df53f0264.png)

**Comment by stefanneculai** [comment]
When image/videos are uploaded using the file dialog, the editor is designed to insert them as file instead of rich media.
