### ISSUE TITLE
Unable to resize first/last column of table

### ISSUE THREAD

**Issue by javeriaanwer** [froala/wysiwyg-editor#3233]
hi,

I want to resize first or last column of table, when I drag last/first column it resizes the whole table.

Expected behavior:
It should resize just last/first column width like it is doing for any other column.

you can reproduce it on [froala website](https://www.froala.com/wysiwyg-editor).

![ezgif com-video-to-gif 18](https://user-images.githubusercontent.com/25203829/51025975-47d34900-15af-11e9-98b0-d2267a1ff602.gif)

**Comment by stefanneculai** [comment]
When you resize the editor using the first / last column right, the editor is designed to resize all the cells to scale accordingly.

**Comment by stefanneculai** [comment]
@javeriaanwer I would recommend putting a feature request on https://wysiwyg-editor-roadmap.froala.com/public.
