### ISSUE TITLE
2mb PDF triggers "Parsing response failed" before hitting endpoint - 100kb PDF works fine.

### ISSUE THREAD

**Issue by joelwmale** [froala/wysiwyg-editor#3235]
##### Expected behavior.
PDF should be successfully uploaded.

##### Actual behavior.
When choosing a 2mb pdf, I get a `parsing response failed`. When choosing a 100kb file, it uploads fine.

##### OS.
Ubuntu 16.04

##### Browser.
Chrome 71.0.3578.98

##### Additional information.
Our froala editor key has not changed at all. This issue is not replaceable locally in docker. Production uses docker. Both environments are same in terms of env variables and versions.

![screen shot 2019-01-14 at 10 18 39 am](https://user-images.githubusercontent.com/3906839/51092703-f8c32900-17e5-11e9-9538-9696a12963a5.png)

```
.on('froalaEditor.file.error', (e, editor, response) => {
  console.log(window.froalaConfig.fileUploadURL, window.froalaConfig.imageUploadURL);
  console.log(e);
  console.log(editor);
  console.log(response);
  alert(response.message);
});
```

**Comment by stefanneculai** [comment]
@joelwmale this looks more like a problem from the reported URL not being correct. Could you please send a request to our support team on https://www.froala.com/wysiwyg-editor/contact instead?

**Comment by joelwmale** [comment]
For anyone else that may experience this issue - it was caused due to the proxy nginx config on the Elastic Beanstalk container instance having a `client_max_body_size` of 1mb. So the proxy was terminating the request due to it being greater than that.
