### ISSUE TITLE
Toolbar popups in scrollable container

### ISSUE THREAD

**Issue by MadMatt25** [froala/wysiwyg-editor#3239]
##### Expected behavior.
When you open a popup, created by the toolbar, it should be appended to the scrollableContainer of choice. Currently, it overflows the container which hides the popup partially behind another div. This issue was raised before, and then it was stated that not making the parent scrollable is the solution. We can not do this.

##### Actual behavior.
The popup is always added to the toolbar div, which causes strange behaviour when using Froala editor(s) inside a scrollable container.
We use Froala editors to let customers design pages with content. This content consists of different "blocks" which contain text, images, etc which is created through Froala editors. If the customer creates several columns, the toolbar gets smaller, and the editor as well. It often happens that the popup (e.g. the insert image popup) appears on the display and then overflows the parent container, making it scrollable. However, if the user tries to scroll the container, the popup disappears. 
Ideally, the popup would be added to a custom scrollable container, or it would detect the current size of the container and never overflow it (e.g. by positioning the popup more to the left/right automatically).

The parent MUST be scrollable, because the user can add as much content as they like, which obviously can overflow the available space...

##### Steps to reproduce the problem.
Create a Froala editor in a scrollable container. Open a popup at the left/right side of the container, then the container will become wider (and thus scrollable). When trying to scroll, the popup disappears.

##### OS.
Windows 10

##### Browser.
Chrome, latest version

**Comment by stefanneculai** [comment]
That is because for `.item` you set `overflow: auto;`. The best thing would be to use just `overflow: hidden` for it.

**Comment by jmanos** [comment]
We ran into a similar issue, but we created a workaround by repositioning the popup during the popup's show event:

```
new FroalaEditor(document.querySelector("textarea"), {
    events: {
        "popups.show.table.insert"() {
            let instance_id = this.id;
            let popup_element = document.querySelector(".fr-popup[data-inst" + instance_id + "=true]");

            //reposition element here using whatever logic you need
        }
    }
}
```

We are using Froala v4.1.1.
