### ISSUE TITLE
opened <details> blocks do not add overflow in iframe editor

### ISSUE THREAD

**Issue by aderpio** [froala/wysiwyg-editor#3244]
##### Expected behavior.
In wysiwyg view, opening a `<details>` block (by clicking on the `<summary>`) should increase editor scrolling to accommodate the newly visible content. This does happen as expected in normal (not iframe) mode. 

##### Actual behavior.
When editor is in iframe mode, opening the details block does not increase the initial state overflow. As a result, the editor scrolls as much as it was scrolling initially with all the `<details>` blocks closed so any new content (or the content that is being pushed down by the newly visible content) is not reachable. I am using iframe mode so that the general page styles do not apply to the editor content

##### Steps to reproduce the problem.
Check the fiddle http://jsfiddle.net/okxpnLqr/

##### OS.
Checked on latest Firefox & Chrome on Windows 7.

**Comment by stefanneculai** [comment]
Thanks for reporting this. What I would suggest in this case would be to use the https://www.froala.com/wysiwyg-editor/docs/methods#size.syncIframe method when you expand the summary block.

**Comment by aderpio** [comment]
I was wondering if there is such a method, should have looked for it. It's OK as a dirty workaround (click somewhere every-time you need to update the iframe height) but I would call this more of a bug than an "enhancement" :) Hopefully it's not too difficult to fix.
