### ISSUE TITLE
Colors: REMOVE does not work

### ISSUE THREAD

**Issue by awegmueller** [froala/wysiwyg-editor#3245]
##### Expected behavior.
When a color is applied to a text via the color-popup and later the 'clear formatting' (REMOVE) option is selected in the popup, the color applied to the text should be removed.

##### Actual behavior.
Clicking on 'clear formatting' does nothing.

##### Steps to reproduce the problem.
Go to https://www.froala.com/wysiwyg-editor, type 'Hello', select Hello, open color-popup, select the first background-color (green), click somewhere in the editor to close the popup, then select Hello again, and click on 'clear formatting' --> nothing happens

![froala-bug](https://user-images.githubusercontent.com/1409867/51467661-64b90a80-1d6d-11e9-9759-d2849f81f5d9.png)

##### OS.
Windows 10

##### Browser.
Current Chome and Firefox versions

**Comment by stefanneculai** [comment]
It's fixed on the current master.
