### ISSUE TITLE
Drop and upload image on first click

### ISSUE THREAD

**Issue by Webinsane** [froala/wysiwyg-editor#3246]
Hello. As title says I would like to upload image without clicking on image and choosing replace icon. When clicked on image it should immediately open dialog as shown bellow:

![image](https://user-images.githubusercontent.com/8006939/51474916-1ca3e300-1d81-11e9-8f94-568423058369.png)

Would this be possible?

**Comment by stefanneculai** [comment]
Sure, you could be using the https://www.froala.com/wysiwyg-editor/docs/events#popups.show.[id] event, where you replace id with `image.edit` and there you show the replace popup: https://www.froala.com/wysiwyg-editor/docs/methods#popups.show.

**Comment by promobulls** [comment]
> Sure, you could be using the [https://www.froala.com/wysiwyg-editor/docs/events#popups.show.[id]](https://www.froala.com/wysiwyg-editor/docs/events#popups.show.%5Bid%5D) event, where you replace id with `image.edit` and there you show the replace popup: https://www.froala.com/wysiwyg-editor/docs/methods#popups.show.

Can you give us a code example, please?

Thank you very much.

**Comment by promobulls** [comment]
> Hello. As title says I would like to upload image without clicking on image and choosing replace icon. When clicked on image it should immediately open dialog as shown bellow:
> 
> ![image](https://user-images.githubusercontent.com/8006939/51474916-1ca3e300-1d81-11e9-8f94-568423058369.png)
> 
> Would this be possible?

Hi Webinsane, 

didi you find the solution? Can you share the code, please?

Thank you very much.

**Comment by Webinsane** [comment]
I will be working on this in a month or so and will let you know once I have completed code.

**Comment by promobulls** [comment]
Ok Thank you.

Could someone tell me how to show the replace popup?

https://www.froala.com/wysiwyg-editor/docs/methods#popups.show
Here I see that the method `popups.show (id, left, top, obj_height)` requires an ID.

What is the ID for image replace popup?

Thank you
