### ISSUE TITLE
Quick Insert Popup memu partially cut off 

### ISSUE THREAD

**Issue by BoilerTom90** [froala/wysiwyg-editor#3249]
I've upgraded to the latest version of Froala and while doing some regression testing, I noticed the top 1/3rd of the Quick Insert Image popup is cut off.  Here's a picture of the problem
<img width="316" alt="froalaeditorimagepopupcutoff" src="https://user-images.githubusercontent.com/17208255/51554889-f000d180-1e3b-11e9-8722-a46e790c2f50.PNG">

**Comment by stefanneculai** [comment]
It is for sure a conflict with some CSS from your page. Could you please check on that?
