### ISSUE TITLE
option for disable multi-line editing mode

### ISSUE THREAD

**Issue by eness** [froala/wysiwyg-editor#325]
Hey there,

I've been using Froala for a couple of days so far everything goes ok, thank you for this work!

I wonder how can I make editor not to allow multi line editing in editor. I mean imagine that I will use this editor both for editing a whole html content and inline elements such as Headings tags like `<h1>`. So in theory you shouldn't use line-breaks or `<br>` in a heading element. I would like to prevent the editor from using Enter key. (html source mode will also be disabled for sure)

**Comment by lmiller1990** [comment]
Just had this problem - might be nice to make this clear in the docs.

I'd be interested in making a PR with a small few updates, been using Froala heavily at my org and hit some gotchas. Do you accept docs PRs?
