### ISSUE TITLE
Adding image caption resets alignment and sizing if useClasses is set to false

### ISSUE THREAD

**Issue by avewells** [froala/wysiwyg-editor#3250]
##### Expected behavior.
Adding a caption to an image should maintain the image's size and position.

##### Actual behavior.
Adding a caption causes the image to align center and grow to 100% width. Manually resetting the alignment after adding the caption seems to fix the issue. Similar to https://github.com/froala/wysiwyg-editor/issues/2458 that was supposed to be fixed.
##### Steps to reproduce the problem.
* Initialize editor with `useClasses: false`.
* Insert an image.
* Change alignment to `left`.
* Add caption.

**Here is a [jsFiddle](https://jsfiddle.net/s5o9hLru/1/)**

##### OS.
macOS High Sierra 10.13.6

##### Browser.
Latest Chrome (71)

##### Froala Version
2.9.1

##### Recording.
![2019-01-22 14 53 13](https://user-images.githubusercontent.com/5642174/51564701-9f966d80-1e55-11e9-944c-91b6c7a3c5dc.gif)

**Comment by stefanneculai** [comment]
It's fixed on the master branch from here.
