### ISSUE TITLE
The image is automatically selected after uploading the image.

### ISSUE THREAD

**Issue by highca** [froala/wysiwyg-editor#3253]
##### Expected behavior.
1. Upload an image.
2. Focus on the editor and insert the text immediately. 

##### Actual behavior.
1. Upload an image.
2. When an image is attached, it is automatically selected.
3. To insert the text, it need to click on the editor.

I need option to focus on the editor when image is attached.

**Comment by stefanneculai** [comment]
After uploading an image, we designed the editor to select the image so that it is possible to easily change image properties. This is a built-in behavior and it highly unlikely for us to change it. The easiest way to unselect the image would be to use the ESC key.

**Comment by GraemeFulton** [comment]
I triggered the `image.hideResizer` event, and it had the same effect as unselecting the image:

`editor.events.trigger('image.hideResizer', [],true);`
