### ISSUE TITLE
problem with translate and default values

### ISSUE THREAD

**Issue by AnguelSC** [froala/wysiwyg-editor#3254]
##### Expected behavior.
- Translate all items to Spanish
- Set "Arial" font default.
- Size default 14.
##### Actual behavior.
(Describe actual behaviour here)
![image](https://user-images.githubusercontent.com/3229121/51844365-12369b80-22e3-11e9-963c-d06f7cd5a178.png)
![image](https://user-images.githubusercontent.com/3229121/51844428-4316d080-22e3-11e9-8909-9b3e63bbee0d.png)

##### Steps to reproduce the problem.
Link: https://jsfiddle.net/e2h65zxo/
![image](https://user-images.githubusercontent.com/3229121/51844397-2c707980-22e3-11e9-8bfc-5a032946e0f6.png)

##### OS.
Windows

##### Browser.
Chrome & Edge

Angular 6

**Comment by stefanneculai** [comment]
This doesn't seem to be a bug. If you want to set a default font in the editor, please use CSS as here: https://jsfiddle.net/froala/9pgbr1qa/.

**Comment by AnguelSC** [comment]
Hi,
 i'am use:
Angular 6 and not work translate spanish.
