### ISSUE TITLE
Indent Cursor Issue ... same to closed issue #1223 

### ISSUE THREAD

**Issue by mirazero** [froala/wysiwyg-editor#3255]
Expected behavior.
Pressing enter on a line should bring cursor to beginning of next line

Actual behavior.
Pressing enter, the cursor stays on current line

Steps to reproduce the problem.

Enter text on first line
Press "Increase Indent" button
Press enter to go to next line, cursor will still be on first line

OS.
Windows

Browser.
IE 11

**Comment by stefanneculai** [comment]
@mirazero could you please make a recording to highlight this problem on our website?

**Comment by stefanneculai** [comment]
I am closing this due to lack of response. Would be happy to open it back if we get further details.
