### ISSUE TITLE
RTL source view overflow / display issues

### ISSUE THREAD

**Issue by angusgrant** [froala/wysiwyg-editor#3256]
##### Expected behavior.
Code View / Source view (Code Mirror) should never overflow text area window. 

##### Actual behavior.
when you switch to Code view the markup should appear within the code source window should not overflow the window also tags should be displayed correctly.

##### Steps to reproduce the problem.
1) Visit https://jsfiddle.net/angusgrant/uxmztbpg/6/ 
2) Click on the text to bring up a jQueryUI dialog box with the Froala editor embeded.
3) Click on the code editor icon that looks like this: </>
4) Observe that html source appears to overflow the text area on the right also appears incorrectly!  

##### OS.
Windows 10.

##### Browser.
Tested in Chrome 71

##### Recording.
https://youtu.be/bOjnFYKuuTQ

**Comment by angusgrant** [comment]
HI I also noticed that it does not work on your own official documentation page (select arabic and then go to code view) https://www.froala.com/wysiwyg-editor/languages please fix!

**Comment by stefanneculai** [comment]
We just checked it and looks like the problem is coming from Code Mirror and not from the editor. To display the code source highlighted, we are using Code Mirror which breaks in `rtl` - please find an isolated jsFiddle here: https://jsfiddle.net/froala/ng4stkz6/.
