### ISSUE TITLE
froalaEditor.image.uploaded event not firing

### ISSUE THREAD

**Issue by HammerTron** [froala/wysiwyg-editor#3257]
The froala documentation states that froalaEditor.image.uploaded event is triggered after a successfully image upload request, but before inserting the image in the editor. https://www.froala.com/wysiwyg-editor/docs/events#image.uploaded

however as you can see from my jsfiddle, that event is not being triggered.

https://jsfiddle.net/kzr67tdw/2/

html
<div id="froala-editor">
    <p>Click on the image below to see the custom image button.</p>
    <img src="https://froala.com/assets/editor/docs/photo14.jpg" class="fr-fil" alt="book" width="150"/>
</div>

JS
$('div#froala-editor').froalaEditor({
  // Set image buttons, including the name
  // of the buttons defined in customImageButtons.
  imageEditButtons: ['imageDisplay', 'imageAlign', 'imageInfo', 'imageRemove'],
  
}).on('froalaEditor.image.uploaded', function (e, editor, response) {
  alert('after', response);
}).on('froalaEditor.image.beforeUpload', function (e, editor, response) {
  alert('before', response);
});

is there a different way to trigger this event?

**Comment by stefanneculai** [comment]
By default, the editor uploads to the browser memory and that is why the `image.uploaded` event is not fired. You can see it firing when uploading to a server here: https://jsfiddle.net/froala/jyd91up5/
