### ISSUE TITLE
Youtube embeds ignore start time parameter

### ISSUE THREAD

**Issue by jamesmoss** [froala/wysiwyg-editor#3258]
##### Expected behavior.
Pasting a youtube link such as https://youtu.be/U9DyHthJ6LA?t=60 will create a video embed which when played starts 60 seconds into the video.

##### Actual behavior.
Video is embedded but starts from the beginning

##### Steps to reproduce the problem.

Youtube supports three different parameters in the URL e.g:

https://youtu.be/U9DyHthJ6LA?t=60
https://www.youtube.com/watch?v=U9DyHthJ6LA&time_continue=60
https://www.youtube.com/watch?v=U9DyHthJ6LA&start=60

However, when generating the iframe embed URL _only_ `start=` is is supported, so the other two parameters must be renamed.

Additionally, Youtube often tries to continue playing from where it left off using a cookie, even if a start time is defined. I suggest testing this in incognito mode to prevent this from complicating testing.

##### OS.
n/a

##### Browser.
n/a

**Comment by stefanneculai** [comment]
See https://www.froala.com/wysiwyg-editor/docs/options#htmlAllowedAttrs

**Comment by jamesmoss** [comment]
This isn't a HTML attribute, it's part of the URL that passed to the `iframe` embed. Right now the regex for Youtube in `VIDEO_PROVIDERS` only grabs the video ID, nothing else.
