### ISSUE TITLE
charCounterMax does not work on view change

### ISSUE THREAD

**Issue by rajput-saqib** [froala/wysiwyg-editor#3259]
**Expected behavior.**
character count should be less then or equal to charCounterMax

**Actual behavior.**
character count exceed from charCounterMax

**Steps to reproduce the problem.**
set charCounterMax (in my case 250).
click on Code View button (</>)
paste you html here as you required. that character count should be greater then charCounterMax
click again on Code View button (</>)
check charCounterMax state.

![froala](https://user-images.githubusercontent.com/10720551/52035055-807d9700-254b-11e9-9a7b-70246e9bed79.png)

**OS.**
Windows 10
Ubuntu 18.04.1

**Browser.**
Chrome
Firefox

**Comment by stefanneculai** [comment]
The charCounter is designed only for text mode. At this moment, it does not support Code View and we would recommend disabling code view when using the char counter. Please consider suggesting this feature on https://wysiwyg-editor-roadmap.froala.com/public.
