### ISSUE TITLE
Incorrect paste of ordered/unordered lists from Libre Office Writer

### ISSUE THREAD

**Issue by AndreyPopovChel** [froala/wysiwyg-editor#3260]
##### Expected behavior.
In Froala pasted list items should look like items in Libre Office Writer

##### Actual behavior.
Additional markers appear after inserting the list into Froala. Item's text is inserted outside the "< li >" tags.

##### Steps to reproduce the problem.
Just copy ordered/unordered list from Libre Office 6.0.7.3 (x64)

##### OS.
Windows 7

##### Browser.
Chrome 71

##### Recording.
![pastefromlibre](https://user-images.githubusercontent.com/12490300/52040965-e1f93200-255a-11e9-9be8-603bc2381495.gif)

**Comment by stefanneculai** [comment]
At this moment, we support power paste only from MSWord. It would be great if you could open a request for adding Libre Office here: https://wysiwyg-editor-roadmap.froala.com/public.
