### ISSUE TITLE
All ordered/unordered list items deleted after double “Enter” followed by “Ctrl + Z”

### ISSUE THREAD

**Issue by AndreyPopovChel** [froala/wysiwyg-editor#3261]
##### Expected behavior.
"Ctrl + Z" should undo only inserting new line after list

##### Actual behavior.
"Ctrl + Z" removes new line after list and all ordered/unordered list items

##### Steps to reproduce the problem.
1 Create ordered/unordered list with 2-3 items in Froala
2 Press "Enter" two times
3 Press "Ctrl + Z" 

In second video additional case with click above list. In this scenario we can see new tag < br >

##### OS.
Windows 7

##### Browser.
Chrome 71

##### Recording.
![listsctrlz](https://user-images.githubusercontent.com/12490300/52040985-f3423e80-255a-11e9-8628-afe75d2c87d6.gif)
![clickoverlist](https://user-images.githubusercontent.com/12490300/52041001-f9381f80-255a-11e9-8241-cb8f2845ef8e.gif)

**Comment by stefanneculai** [comment]
See https://www.froala.com/wysiwyg-editor/docs/options#typingTimer. The editor is using an option which tells the editor how fast to put changes in undo stack when doing an action.
