### ISSUE TITLE
Loosing line break formatting in format block <pre> again

### ISSUE THREAD

**Issue by AndreyPopovChel** [froala/wysiwyg-editor#3263]
##### Expected behavior.
Line breaks and tabs present in pasted text

##### Actual behavior.
Having lost the line breaks and showing one line only after patsing multiline text within < pre > tags.

##### Steps to reproduce the problem.
Seems like issue https://github.com/froala/wysiwyg-editor/issues/409 is actual

##### OS.
Windows only (can't reproduce in Ubuntu)

##### Browser.
Chrome 71

##### Recording.
![linebreakspre](https://user-images.githubusercontent.com/12490300/52042372-d7d93280-255e-11e9-967b-d6610ed23bcf.gif)

**Comment by stefanneculai** [comment]
This should be fixed in version 2.9.3. Do you think you could try again with the latest master?

**Comment by AndreyPopovChel** [comment]
Yes, it fixed since 2.9.2
