### ISSUE TITLE
Preview not showing after video upload in Safari

### ISSUE THREAD

**Issue by nidhin038** [froala/wysiwyg-editor#3264]
##### Expected behavior.
After video upload, the preview with play button should be shown

##### Actual behavior.
After video upload, the preview with play button is not shown in safari

##### Steps to reproduce the problem.
Open safari
try uploading a video

##### OS.
Mac 10.13.6

##### Browser.
Safari 11.1.1

![screen shot 2019-01-31 at 4 25 15 pm](https://user-images.githubusercontent.com/1975529/52049872-e6cadf80-2574-11e9-810f-976f1ab49e65.png)

**Comment by stefanneculai** [comment]
@nidhin038 could you please send us the video you are using?

**Comment by stefanneculai** [comment]
If no preview is being shown, the problem might come from the format of the file which is uploaded. We are using the [VIDEO tag ](https://www.w3schools.com/html/html5_video.asp) which in Safari supports only `mp4` at this moment,.
