### ISSUE TITLE
Continue editing after image.loaded

### ISSUE THREAD

**Issue by 7i4** [froala/wysiwyg-editor#3269]
The main goal is to create a Telegra.ph or Medium.com looks like app using Froala
Everything went cool except one detail:
after adding an image using Quick Insert Button it is becoming absolutely insane quest to get to the new line... 
##### Expected behavior.
On image.loaded (if there are no other lines beneath) new line or line breaker button should appear.  It is extremely necessary for mobile devices. 

Details:

![ezgif-3-08610d031ca5](https://user-images.githubusercontent.com/8938682/52155742-4e784c00-2695-11e9-89f8-34bbe064f825.gif)

##### Actual behavior.
After loading image on page its menu become focused. We do something and then going to proceed with further editing but we can't! 
![ezgif-3-bec54ac28d39](https://user-images.githubusercontent.com/8938682/52155959-6bf9e580-2696-11e9-8010-f3ae494cea34.gif)

I have added line breaker button to avoid this confuse but:
1) **lineBreakerOffset: 20** doesn't work as expected;
2) lineBreaker is disabled on mobile devices because of _hover_ event listener.

##### Steps to reproduce the problem.

- Initialize editor.
- Insert an image.

(Describe the steps to reproduce the problem here. A [jsFiddle](https://jsfiddle.net/froala/wc5c3jhk/) is awesome when possible.)

##### OS.
macOS High Sierra 10.13.6

##### Browser.
Safari 12.0.3 (13606.4.5.3.1)
Chrome (71)

##### Recording.
(A recording showing how to reproduce the problem)

**Comment by stefanneculai** [comment]
See https://jsfiddle.net/froala/wc5c3jhk/2205/.

**Comment by 7i4** [comment]
Thank you so much!!!
