### ISSUE TITLE
XSS Issue In Link Insertion

### ISSUE THREAD

**Issue by shivangtrip** [froala/wysiwyg-editor#3270]
##### Expected behavior.
No popup should be shown when an embed tag is added while inserting link.

##### Actual behavior.
The script executes and popup is shown.

##### Steps to reproduce the problem.
1. Go to:
2. Click on insert link icon
3. Enter anything in the url section
4. Enter:
`<EMBED SRC="data:image/svg+xml;base64,PHN2ZyB4bWxuczpzdmc9Imh0dH A6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcv MjAwMC9zdmciIHhtbG5zOnhsaW5rPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5L3hs aW5rIiB2ZXJzaW9uPSIxLjAiIHg9IjAiIHk9IjAiIHdpZHRoPSIxOTQiIGhlaWdodD0iMjAw IiBpZD0ieHNzIj48c2NyaXB0IHR5cGU9InRleHQvZWNtYXNjcmlwdCI+YWxlcnQoIlh TUyIpOzwvc2NyaXB0Pjwvc3ZnPg==" type="image/svg+xml" AllowScriptAccess="always"></EMBED>` in the Text Section
5. Clikc insert.

##### OS.
Mac

##### Browser.
Chrome

##### Recording.
https://vimeo.com/user94698215/review/315195332/0f3212788d

**Comment by 7i4** [comment]
Sorry, we couldn’t find that page
Make sure you’ve typed the URL correctly, or try searching Vimeo. You could also watch one of the videos below instead.
