### ISSUE TITLE
Emoticons regression

### ISSUE THREAD

**Issue by thedotedge** [froala/wysiwyg-editor#3271]
##### Froala version
2.9.2

##### Expected behavior.
Emoticons popover is triggered when clicking the toolbar icon. 

##### Steps to reproduce the problem.
1. Go to https://www.froala.com/wysiwyg-editor/examples/full-featured
2. Click ![image](https://user-images.githubusercontent.com/227241/52209147-4a118600-2883-11e9-8c00-2e3666fe5981.png)

##### OS.
Mac OS 10.14.2 

##### Browser.
71.0.3578.98 (Official Build) (64-bit)

##### Recording.
https://d.pr/i/Cz1y14

**Comment by thedotedge** [comment]
@stefanneculai closed because it's fixed or..? :)

**Comment by stefanneculai** [comment]
Yes, it is fixed.
