### ISSUE TITLE
No Unminified version?

### ISSUE THREAD

**Issue by SeanKendle** [froala/wysiwyg-editor#3273]
I am not seeing an unminified version of Froala's files. I'm a developer and need to be able to see the full source code for when something goes wrong so I can submit the appropriate bug reports, and also, I have to change a bit of code in the froala.js main file in order to fix a bug that was marked as "will not fix".

**Comment by SeanKendle** [comment]
Nevermind I found it in my account, sorry!

**Comment by T-vK** [comment]
@SeanDKendle I don't really understand why the unminified version should be in your account, but I checked your repositories and didn't see anything the like. Please reopen or clarify.

**Comment by SeanDKendle** [comment]
Different account. This was at my old job. I've since changed jobs.

**Comment by T-vK** [comment]
Okay, and where did it come from? I'm currently in a very similar situation where I need to apply a fix to the source code.

**Comment by SeanDKendle** [comment]
If you bought Froala, it should be in your account on their website. Log in, and go to your account. I can't provide any more details, because I no longer have access to the account my former boss purchased the license under. Sorry!

**Comment by T-vK** [comment]
Oh, I see. I guess I'll use Quill then... :neutral_face:

**Comment by SeanDKendle** [comment]
Sorry, full code is only available to paid accounts. I would just keep posting your specific problems and hope they'll be fixed. They're very responsive with that kind of thing. Froala's a great editor!

**Comment by em77** [comment]
For anyone who finds this, they [now want you](https://wysiwyg-editor.froala.help/hc/en-us/articles/360001875177-How-do-I-log-in-to-my-account-) to contact support to access the code.

> As of June 2019, we have disabled the client portal in favor of using our customer success team. Our team can assist in generating new keys, looking up existing keys, sharing an invoice, sharing unminified builds, and much more.
> Send them a note for anything you may need and they'll get back to you as quick as they can: support@froala.com.
