### ISSUE TITLE
Default font style to text when copy pasted

### ISSUE THREAD

**Issue by ShanmugaPriyanV** [froala/wysiwyg-editor#3278]
When copy and pasting a content inside the editor it is possible to maintain a default font family and size irrespective of existing font?
Thanks in Advance.

**Comment by stefanneculai** [comment]
You can control that through: 
https://www.froala.com/wysiwyg-editor/docs/options#pasteAllowedStyleProps
https://www.froala.com/wysiwyg-editor/docs/options#pasteDeniedAttrs

**Comment by mxlle** [comment]
Why is there no `pasteDeniedStyleProps` ? 
We just want to deny some ... it would be a pain to list all that we allow.
