### ISSUE TITLE
 Can't drag images when they have focus (Froala v2.9.2) - Bug Remains in Firefox

### ISSUE THREAD

**Issue by SeanDKendle** [froala/wysiwyg-editor#3282]
##### Expected behavior.
Should be able to drag image when it has focus (resize handles shown/menu open)

##### Actual behavior.
Can't drag image when it has focus.

##### Steps to reproduce the problem.
https://www.froala.com/wysiwyg-editor in Firefox

Click image to give it focus
Try to drag it to a new location
Image won't drag

Click away so the image loses focus
Click and drag immediately so it doesn't get focus
Image will drag

##### OS.
Windows 7 Pro

##### Browser.
FF latest version

**Comment by stefanneculai** [comment]
Should be fixed on the current master.
