### ISSUE TITLE
Insert video button not working

### ISSUE THREAD

**Issue by emeryowa** [froala/wysiwyg-editor#3283]
##### Expected behavior.
When clicking insert video button, popup should show up with insert video options

##### Actual behavior.
No video options pop up shows up when clicking the insert video button

##### Steps to reproduce the problem.
Initialize Froala editor with `videoInsertButtons` setting set to  `['videoByURL']`
Then click Insert Video button
See https://jsfiddle.net/cLwrtpnk/

When you set `videoInsertButtons` setting to default as mentioned [here](https://www.froala.com/wysiwyg-editor/docs/options#videoInsertButtons) it works

##### OS.
MacOS Mojave 10.14.2
##### Browser.
Chrome 71.0.3578.98

##### Recording.
See jsfiddle https://jsfiddle.net/cLwrtpnk/

**Comment by stefanneculai** [comment]
It's fixed on the master branch.

**Comment by emeryowa** [comment]
@stefanneculai Does that mean the fix has been released?

**Comment by dgroh** [comment]
@stefanneculai in which version this was fixed?
