### ISSUE TITLE
Clear Formatting doesn't clear paragraph styles

### ISSUE THREAD

**Issue by bholtbholt** [froala/wysiwyg-editor#3285]
## Expected behavior.
When using the clear formatting tool, all inline styles are removed.

```
// Pasted Content from Microsoft Word
<p style="color: rgb(0, 0, 0);font-family: Helvetica;font-size: 14px;margin-bottom: 3.2pt;">
  <strong>
    <span style='font-size:14px;font-family: "Comic Sans MS";'>
      January
    </span>
  </strong>
  <span style='font-size:14px;font-family: "Comic Sans MS";'>
   &nbsp;is the first month of the year&nbsp;
  </span>
</p>
```

```
// Content after using Clear Formatting Tool
<p>
  January&nbsp;is the first month of the year&nbsp;
</p>
```

## Actual behavior.
When inline styles are applied to a paragraph, using clear formatting doesn't remove the inline styles from the paragraph.

This commonly happens when pasting in content from Microsoft Word.

```
// Pasted Content
<p style="color: rgb(0, 0, 0);font-family: Helvetica;font-size: 14px;margin-bottom: 3.2pt;">
  <strong>
    <span style='font-size:14px;font-family: "Comic Sans MS";'>
      January
    </span>
  </strong>
  <span style='font-size:14px;font-family: "Comic Sans MS";'>
   &nbsp;is the first month of the year&nbsp;
  </span>
</p>
```

```
// Content after using Clear Formatting Tool
<p style="color: rgb(0, 0, 0);font-family: Helvetica;font-size: 14px;margin-bottom: 3.2pt;">
  January&nbsp;is the first month of the year&nbsp;
</p>
```

## Steps to reproduce the problem.
- Open Word Doc [inline-styles.docx](https://github.com/froala/wysiwyg-editor/files/2847241/inline-styles.docx)
- Copy and paste text into [Froala Editor](https://www.froala.com/wysiwyg-editor)
- Select all text in Froala editor
- Click Clear Formatting button
- Inspect code to see HTML results with inline styles still applied to paragraph tag

## OS.
Reproducible on Mac and Windows (reported from our customers). I've specifically tested on Mac OSX 10.14.3

## Browser.
Chrome, Safari, Firefox, IE11, Edge

## Recording.
![inline-styles-in-word](https://user-images.githubusercontent.com/4933622/52511743-426d1c80-2bb6-11e9-96b6-c65d7c0c2f93.gif)

**Comment by gothate** [comment]
No?

**Comment by Foozor** [comment]
This bug is still present. I don't understand why it was closed.

**Comment by lukaszahorec** [comment]
> This seems to be working on the latest version (4.0.5). Can anyone confirm if this has been fixed?

not for me :(

**Comment by X-Tream** [comment]
This issue has reappeared when upgrading from 4.0.5 to 4.0.15

You can try it [here](https://froala.com/online-html-editor/)
With the following paragraph: `<p style="background: rgba(178, 222, 39, 1);">background green</p>`

![froalaParagraphStyleClearIssue](https://user-images.githubusercontent.com/16964299/196879845-94778b8f-86a0-4846-bace-525c94b5ff56.gif)
