### ISSUE TITLE
IE 11 can't edit content of some elements in the editor

### ISSUE THREAD

**Issue by miroslavgeorgiev-rg** [froala/wysiwyg-editor#3289]
##### Expected behavior.
Can make changes on elements content in the editor.

##### Actual behavior.
Can't make any changes on some elements content in the editor - blockquotes, links.

##### Steps to reproduce the problem.
A [CodePen example](https://codepen.io/miroslavgeorgiev-rg/full/NoMdRZ) you can use:

1. Try to change the content of the blockquote element.
2. Try to change the content of the link, styled as button.

##### OS.
Windows 7

##### Browser.
Internet Explorer 11

##### Recording.
![ie](https://user-images.githubusercontent.com/47526982/52581066-69378700-2e32-11e9-8960-f8e00d9f79c0.gif)

**Comment by stefanneculai** [comment]
This is a known IE problem which is happening when using some CSS attributes. In your case, they are: `min-height` and `overflow` - removing them would fix the problem right away. Unfortunately, we don't have a fix for this problem.

**Comment by miroslavgeorgiev-rg** [comment]
Hi, @stefanneculai,

Thank you for the information - my research also revealed that these kind of issues affects this behaviour in IE.
But this resolves the issue with the **blockquote** element that has "overflow: hidden; min-height: 30px;" attributes and NOT the **button** element problem that doesn't have those kind of attributes.
So I don't think the ticket should be closed.

Additional - in your documentation there is not a single word about these issues and how to resolve them. If you pretend to support IE 10 and IE 11 you should consider extend the docu with examples like this ones.
