### ISSUE TITLE
Content pasting in reverse on Edge

### ISSUE THREAD

**Issue by bholtbholt** [froala/wysiwyg-editor#3290]
## Expected behavior.
Pasting content from another Froala window or from Microsoft Products should be in the correct order.

## Actual behavior.
When using Edge, sometimes pasting content will reverse the order. For example,
```
<li>Item 1</li>
<li>Item 2</li>
```
Will paste as
```
<li>Item 2</li>
<li>Item 1</li>
```

This was most frequently seen in lists, but also occurred in paragraphs. It did not occur in tables.

## Steps to reproduce the problem.
I'm having a really tough time reproducing this, as it was reported by our customer. As far as I can tell it's something like:

- Have some sort of Word format.
- Paste the content in using Edge
- Copy the content you've just pasted
- In a new tab, paste the content in again
- The content is sometimes reversed

When capturing this, the user showed us it happening, then immediately did it again, but it didn't happen.

#### Hints
- It only occurs on Edge
- It might have something to do with Outlook. The user is copying Word content out of Outlook and into Froala using Edge

## OS.
Windows

## Browser.
Edge, latest

## Recording.
This clip shows already pasted content being pasted into another Froala instance (in another tab)

![reverse-pasting](https://user-images.githubusercontent.com/4933622/52593803-bc8fe200-2dfe-11e9-850e-a378aabde293.gif)

**Comment by stefanneculai** [comment]
@bholtbholt Do you think it would be possible to make a jsFiddle to highlight the problem? That would speed-up things a lot. Here is a basic jsFiddle you could use as a starting point: https://jsfiddle.net/froala/wc5c3jhk/.

**Comment by bholtbholt** [comment]
@stefanneculai I haven't been able to reproduce the problem, I think it's because I'm on a Mac whereas our client is on a Windows machine. I've been trying to get it working through BrowserStack, but it seems copying and pasting isn't quite the same.

The clip I've included was recorded from the client where they have content in Froala then paste it into a new Froala editor where it's reversed.

I think it has something to do with a combination of Office products interacting with Froala on Edge.

Would it help if we added our Froala configuration to the jsFiddle? Or is there another way I can help speed this along?

**Comment by stefanneculai** [comment]
What would help is a jsFiddle from where to paste content to another jsFiddle.

**Comment by bholtbholt** [comment]
I've updated the jsFiddle with our settings: https://jsfiddle.net/03hkbtc8/

Our client has reported this issue while having one Froala instance enabled per page, but the page opened in two tabs. They have pasted from one tab into another tab.

**Comment by stefanneculai** [comment]
@bholtbholt it's not clear how we can reproduce it on this jsFiddle. Can you maybe put the HTML which gets pasted incorrectly in on jsFiddle? Unfortunately, without having that specific HTML it's a shot in the dark.

**Comment by bholtbholt** [comment]
Sorry about the unclear reproduction steps. As I mentioned, I haven't been able to reproduce it either. It doesn't appear to be from specific HTML, but rather some sort of combination of Microsoft products.

We checked in with the client again today and they've since switched over to using Internet Explorer where it doesn't occur. If they report that it occurs again we'll try to get better steps.

**Comment by bholtbholt** [comment]
Hi @stefanneculai this appears to be the HTML our client was using, but it's gone through Gmail so I'm not sure what transformations have been applied.

```
<ul style="margin-top:0in" type="disc">
<li class="m_9091689620044473053m_6458905975569501009m_500173768271867832MsoNormalCxSpMiddle" style="margin-bottom:8.0pt;line-height:105%">
<span style="font-family:&quot;Comic Sans MS&quot;">Lifetime Residential and 10 year Commercial Warranty<u></u><u></u></span></li><li class="m_9091689620044473053m_6458905975569501009m_500173768271867832MsoNormalCxSpMiddle" style="margin-bottom:8.0pt;line-height:105%">
<span style="font-family:&quot;Comic Sans MS&quot;">24hr protection from everyday spills<u></u><u></u></span></li><li class="m_9091689620044473053m_6458905975569501009m_500173768271867832MsoNormalCxSpMiddle" style="margin-bottom:8.0pt;line-height:105%">
<span style="font-family:&quot;Comic Sans MS&quot;">T-molding expansion breaks only needed if connected span is greater than 40ft in any direction or when flooring direction changes.<u></u><u></u></span></li><li class="m_9091689620044473053m_6458905975569501009m_500173768271867832MsoNormalCxSpMiddle" style="margin-bottom:8.0pt;line-height:105%">
<span style="font-family:&quot;Comic Sans MS&quot;">½” expansion space around all fixed objects<u></u><u></u></span></li><li class="m_9091689620044473053m_6458905975569501009m_500173768271867832MsoNormalCxSpMiddle" style="margin-bottom:8.0pt;line-height:105%">
<span style="font-family:&quot;Comic Sans MS&quot;">Minimum 48 hour acclimation<u></u><u></u></span></li><li class="m_9091689620044473053m_6458905975569501009m_500173768271867832MsoNormalCxSpMiddle" style="margin-bottom:8.0pt;line-height:105%">
<span style="font-family:&quot;Comic Sans MS&quot;">Foam Backer rod and 100% silicone needed <u>in wet areas only</u> (bathroom, laundry room, kitchens, etc)<u></u><u></u></span></li><ul style="margin-top:0in" type="circle">
<li class="m_9091689620044473053m_6458905975569501009m_500173768271867832MsoNormalCxSpMiddle" style="margin-bottom:8.0pt;line-height:105%">
<span style="font-family:&quot;Comic Sans MS&quot;">1/2” foam backer rod and silicone in expansion spaces of wet areas<u></u><u></u></span></li><li class="m_9091689620044473053m_6458905975569501009m_500173768271867832MsoNormalCxSpMiddle" style="margin-bottom:8.0pt;line-height:105%">
<span style="font-family:&quot;Comic Sans MS&quot;">3/8” foam backer rod and silicone under transitions attached to wet areas<u></u><u></u></span></li><li class="m_9091689620044473053m_6458905975569501009m_500173768271867832MsoNormalCxSpMiddle" style="margin-bottom:8.0pt;line-height:105%">
<span style="font-family:&quot;Comic Sans MS&quot;">Silicone applied around door jambs in wet areas. <u></u><u></u></span></li></ul>
<li class="m_9091689620044473053m_6458905975569501009m_500173768271867832MsoNormalCxSpMiddle" style="margin-bottom:8.0pt;line-height:105%">
<span style="font-family:&quot;Comic Sans MS&quot;">6 mil poly over concrete substrates<u></u><u></u></span></li><li class="m_9091689620044473053m_6458905975569501009m_500173768271867832MsoNormalCxSpMiddle" style="margin-bottom:8.0pt;line-height:105%">
<span style="font-family:&quot;Comic Sans MS&quot;">Installation guidelines (<a href="https://www.lumberliquidators.com/assets/images/installation/AS24_LAM.pdf" target="_blank" data-saferedirecturl="https://www.google.com/url?q=https://www.lumberliquidators.com/assets/images/installation/AS24_LAM.pdf&amp;source=gmail&amp;ust=1550251128747000&amp;usg=AFQjCNFkPsv--Fc-vdnRF-ERB6CvrbzGeA">click here</a>)<u></u><u></u></span></li><li class="m_9091689620044473053m_6458905975569501009m_500173768271867832MsoNormalCxSpMiddle" style="margin-bottom:8.0pt;line-height:105%">
<span style="font-family:&quot;Comic Sans MS&quot;">Warranty details and Care instructions (<a href="https://www.lumberliquidators.com/assets/images/product_page/pdf_warranty/aquaseal24_war.pdf" target="_blank" data-saferedirecturl="https://www.google.com/url?q=https://www.lumberliquidators.com/assets/images/product_page/pdf_warranty/aquaseal24_war.pdf&amp;source=gmail&amp;ust=1550251128747000&amp;usg=AFQjCNEzwfmwpbQfM2a3B_xvj1Wxroyk9Q">click here</a>)<u></u><u></u></span></li></ul>
```

**Comment by stefanneculai** [comment]
Thanks for further details, @bholtbholt. I've tried to reproduce it without any success. I am closing it for now and would be happy to look into it if we get more details.
