### ISSUE TITLE
Copy paste from Word to Froala converts unordered list to ordered list

### ISSUE THREAD

**Issue by waynechaw** [froala/wysiwyg-editor#3291]
##### Expected behavior.
In a word doc with a unordered list, if I copy and paste it into froala editor, the list should still be unordered

##### Actual behavior.
It converts to ordered list

screenshot of word doc:

<img width="795" alt="screen shot 2019-02-11 at 2 16 32 pm" src="https://user-images.githubusercontent.com/7528925/52597598-3bd5e380-2e08-11e9-9459-61dfe746e938.png">

screenshot of Froala:

![screen shot 2019-02-11 at 2 17 08 pm](https://user-images.githubusercontent.com/7528925/52597635-5445fe00-2e08-11e9-82f7-0707b6ad92ec.png)

this happens when you "select all", then copy and paste into froala

this is happening in froala 2.9.2

word doc:
[bulletpointissue.docx](https://github.com/froala/wysiwyg-editor/files/2853302/bulletpointissue.docx)

**Comment by stefanneculai** [comment]
@waynechaw what browser and OS are you using?

**Comment by waynechaw** [comment]
> @waynechaw what browser and OS are you using?

Macbook pro, chrome.

I just tried it in IE on Waindows and it is working fine, so it seems to be just issue with mac

**Comment by waynechaw** [comment]
video showing the issue:
[froala_3291.webm.zip](https://github.com/froala/wysiwyg-editor/files/2857188/froala_3291.webm.zip)

**Comment by waynechaw** [comment]
thanks for fixing this issue!
