### ISSUE TITLE
Copy paste from Word to Froala does not retain line height

### ISSUE THREAD

**Issue by waynechaw** [froala/wysiwyg-editor#3292]
##### Expected behavior.
Line height should be retained from Word to Froala

##### Actual behavior.
Line height is not set in froala regardless of the line heigh set in Word

##### Steps to reproduce the problem.
Copy a word doc with line height set to 2.0, paste content into froala, line height is not set in froala

**Comment by stefanneculai** [comment]
See https://www.froala.com/wysiwyg-editor/docs/options#wordAllowedStyleProps.
