### ISSUE TITLE
Custom button with commands.indent * commands.outdent method, doesn't apply to the select text

### ISSUE THREAD

**Issue by mdeprezzo** [froala/wysiwyg-editor#3293]
##### Expected behavior.
With custom toolbar and with indendt and outdent button, when call commands.indent() / commands.outdent(), that style need to be applied to the selected element.

##### Actual behavior.
Nothing happen.

##### Steps to reproduce the problem.
Here the buttons:

```
  	<q-btn class="op-icon font-14" icon="fa fa-outdent" @click="frAction('outdent')">
  	</q-btn>		
  	<q-btn class="op-icon font-14" icon="fa fa-indent" @click="frAction('indent')">
  	</q-btn>	  
```
and here the methods:

```
	  	  case 'indent':
	  	    console.log('command', action)
	  	    this.editor.commands.indent()
	  	    break
	  	  case 'outdent':
	  	    console.log('command', action)
	  	    this.editor.commands.outdent()
	  	    break	  
```
##### OS.
Ubuntu 18.10

##### Browser.
Chrome latest

**Comment by stefanneculai** [comment]
For binding an external button, please see: https://www.froala.com/wysiwyg-editor/examples/external-button. The problem in your case is that the editor focus is being lost when clicking on an external butotn.

**Comment by mdeprezzo** [comment]
@stefanneculai oh ok, but its a bit strange. Why for the other actions works fine ? Actions like, bold, italic, underline, alignment ecc ecc
