### ISSUE TITLE
Background image in table

### ISSUE THREAD

**Issue by ShanmugaPriyanV** [froala/wysiwyg-editor#3294]
Currently in froala there is option to add color in cell background of a table, is it possible to add background image for the cell ?

Thanks

**Comment by stefanneculai** [comment]
For that, I would recommend to create a custom button in the table toolbar and set it there: https://www.froala.com/wysiwyg-editor/examples/custom-buttons.

**Comment by shah20** [comment]
@ShanmugaPriyanV  were you able to add backgorung color or backgrounf image to cell in froala?
