### ISSUE TITLE
[Word copy paste] space is missing

### ISSUE THREAD

**Issue by waynechaw** [froala/wysiwyg-editor#3298]
##### Expected behavior.
Spaces between words shouldn't go missing

##### Actual behavior.
Space between words is missing

##### Steps to reproduce the problem.
Copy the word doc I have attached to this issue. Paste it into Froala.

![image](https://user-images.githubusercontent.com/7528925/52736919-e290c000-2f7f-11e9-9fec-9dbaa572fb8a.png)

![image](https://user-images.githubusercontent.com/7528925/52736924-e6244700-2f7f-11e9-849e-0664a32da5de.png)

word doc:
[space missin.docx](https://github.com/froala/wysiwyg-editor/files/2861772/space.missin.docx)
[onthursday.docx](https://github.com/froala/wysiwyg-editor/files/2921281/onthursday.docx)

first word doc contains a link
second word doc contains bolded text

I was able to produce the issue in both Chrome on Mac and IE in Windows

**Comment by ilyaskarim** [comment]
I put label and someone will look over it shortly. I will get back to you as soon as we have news.
