### ISSUE TITLE
Paste from Excel does not preserve a color in part of the cell text

### ISSUE THREAD

**Issue by miyazakijunichi** [froala/wysiwyg-editor#3299]
##### Expected behavior.
Keep text color a part of the cell.

##### Actual behavior.
Text color is not preserved from Excel. 

##### Steps to reproduce the problem.
Copy some colored cell. Paste it into Froala.
![7g3r0-jurlu](https://user-images.githubusercontent.com/10162699/52770891-b35d7a00-3077-11e9-8b7a-e5196a603caa.gif)

##### OS.
Windows 10

##### Browser.
Chrome

**Comment by ilyaskarim** [comment]
I tested with Ms Excel 2013 and pasted into https://www.froala.com/wysiwyg-editor/ and works fine. Can you share your word file?

**Comment by miyazakijunichi** [comment]
This word file occurs same problem.
It seems that the color of the text is overwritten with the color of the cell.
[colored_cell_text.xlsx](https://github.com/froala/wysiwyg-editor/files/2867236/colored_cell_text.xlsx)

**Comment by miyazakijunichi** [comment]
Thank you for fixing!

**Comment by miyazakijunichi** [comment]
This issue is fixed in v2.9.3. But it reproduce in v3.0.0-alpha.
https://www.froala.com/wysiwyg-editor
