### ISSUE TITLE
XSS in FROALA WYSIWYG

### ISSUE THREAD

**Issue by soaj1664** [froala/wysiwyg-editor#33]
Hi,

The editor is vulnerable to an XSS. The editor allows users to insert link and if instead of normal link, I input JavaScript URI

`javascript:alert%28location%29`

then it works. The attacker can execute arbitrary code of his choice. Please fix this issue. Thanks!

**Comment by kimutaiRop** [comment]
`<iframe src="javascript:alert('hi')"></iframe>` does not  get escaped

**Comment by stefanneculai** [comment]
@kimutaiRop do you think you could make a jsFiddle? https://jsfiddle.net/froala/wc5c3jhk/

**Comment by oleksandr-dakal** [comment]
I found out that simple <img src=".." onload=alert(document.cookie) /> will work as XSS attack.

**Comment by stefanneculai** [comment]
@oleksandr-dakal are you able to reproduce this on [our homepage](http://froala.com/wysiwyg-editor)? How?

**Comment by oleksandr-dakal** [comment]
It's possible to reproduce when from Server we received `<img src=".." onload=alert(document.cookie) />`.

**Comment by stefanneculai** [comment]
@oleksandr-dakal could you please make sure that you're using version 2.9.3?

**Comment by oleksandr-dakal** [comment]
@stefanneculai I found issue but it's not related to froala but to angular wrapper:
https://github.com/froala/angular-froala/issues/172

Thx for help
