### ISSUE TITLE
WYSIWYG principle is broken with images

### ISSUE THREAD

**Issue by bruno-santiago** [froala/wysiwyg-editor#3301]
When you insert some text and add a image froala should show exactly how it would be rendered in a html page.

Actually when you insert some text and add a image froala is showing the image one line below the text and the image is centered. When you render the html generated, the text and the image are on the same line and the image is not centered.

Steps:
1. Add some text. e.g: "Some Text"
2. Do not type enter.
3. Add a image
4. Render the generated html in another browser tab.

Ubuntu. 18.04
Chrome. Version 71.0.3578.98 (Official Build) (64-bit)

**Comment by stefanneculai** [comment]
Make sure you follow the details from here for displaying the content: https://www.froala.com/wysiwyg-editor/docs/overview#frontend

**Comment by bruno-santiago** [comment]
Is there anyway to auto save the div that contains fr-view class with froala editor content?

**Comment by stefanneculai** [comment]
You could be using the `html.get` event and wrap it with that div, though this is hackish workaround.
