### ISSUE TITLE
Image captions very difficult to remove in some cases

### ISSUE THREAD

**Issue by brianlenz** [froala/wysiwyg-editor#3303]
##### Expected behavior.
Image captions should always be easy to remove after the image has been removed. The cursor should always appear in the caption.

##### Actual behavior.
Image captions are very challenging to remove sometimes after the image has been deleted. The cursor doesn't appear in the caption in these cases.

##### Steps to reproduce the problem.
1. Put the following source into the body of a Froala editor using the [inline toolbar](https://www.froala.com/wysiwyg-editor/examples/always-visible):

```
<p><br></p><p><span class="fr-img-caption fr-fic fr-dib fr-draggable" contenteditable="false" draggable="false" style="width: 748.328px;"><span class="fr-img-wrap">&gt;<br><br><br><br><br><br></span></span>This is a test.</p>
```

2. You can't easily remove the caption and extra whitespace.
3. When you click in the caption where the `>` character is, the cursor is not visible.
4. You have to use `delete` (forward-delete) to delete the characters/lines one at a time. In between each `delete`, you have to click in the caption again to give it focus.

It should be a lot easier to delete the caption.

##### OS.
macOS 10.14.3.

##### Browser.
Google Chrome 72.0.3626.96.

**Comment by stefanneculai** [comment]
@brianlenz how did you got to that specific HTML?

**Comment by brianlenz** [comment]
@stefanneculai I didn't do it myself; a user did. They had embedded an image and put a caption on it. Then, the image was removed from the server, so it was a broken image. They tried to remove it, but ran into this issue.

**Comment by stefanneculai** [comment]
It is strange that even if the image was removed from the server, there is no `IMG` tag in the HTML.. Do you have some code which is handling image removal and maybe not removing the caption?

**Comment by brianlenz** [comment]
Nope, we don't have anything that manually modifies the HTML. The user removed the broken image from within the editor, which then resulted in this state.

**Comment by stefanneculai** [comment]
@brianlenz do you have any idea on how he removed it? Did he clicked on it and removed by using the image tool?

**Comment by brianlenz** [comment]
The user doesn't exactly remember, so I'm not sure. It could have been the trash can on the image tool? Or perhaps a backspace to delete the image.

FWIW, we have a very minimal set of tools enabled in the editor. For images, we only support caption and remove. We are primarily using the inline toolbar only (not the fixed top/bottom toolbar).

**Comment by stefanneculai** [comment]
@brianlenz unfortunately, we are not able to get to this HTML just by using the editor tools. Thus, I am closing this for now and would be happy to look further into it if you could provide specific steps to get to this.

**Comment by brianlenz** [comment]
Well that's disappointing.
