### ISSUE TITLE
Inserting nested span element in froala using an external button adds extra spaces.

### ISSUE THREAD

**Issue by karanjariwala** [froala/wysiwyg-editor#3309]
Inserting nested span element in froala using an external button adds extra spaces.

##### Expected behavior.
(Describe expected behaviour here)
Inserting a nested span below should insert nested span without spaces added
```
<span class="fr-deletable variable-item-wrapper"  contenteditable="false">
    <span class="variable-item" contenteditable="false" name="variableName">
    variableName
    </span>
  </span>
```

##### Actual behavior.
(Describe actual behaviour here)
inserting 
```
<span class="fr-deletable variable-item-wrapper"  contenteditable="false">
    <span class="variable-item" contenteditable="false" name="variableName">
    variableName
    </span>
  </span>
```
<img width="850" alt="screenshot 2019-02-19 at 7 58 21 pm" src="https://user-images.githubusercontent.com/9664177/53022255-cd84c700-3480-11e9-8b02-f77c7fc5d033.png">

##### Steps to reproduce the problem.
https://jsfiddle.net/karanRippling/gtx0uqzp/11/#&togetherjs=L3E5HqPNLv

##### OS.
(OS name and version here)
Mac OS

##### Browser.
(Browser name an version here)
Chrome 72

##### Recording.
(A recording showing how to reproduce the problem)

**Comment by stefanneculai** [comment]
See https://jsfiddle.net/froala/b4o6dsLe/. Those spaces were added because of the new lines and spaces which are added from the template. Please make sure that you don't have such new spaces.
