### ISSUE TITLE
When i try to click to place cursor next to a nested html span which is the last element in the p tag cursor appears at incorrect position. 

### ISSUE THREAD

**Issue by karanjariwala** [froala/wysiwyg-editor#3311]
When i try to click to place cursor next to a nested html span which is the last element in the p tag cursor appears at incorrect position. 

##### Expected behavior.
(Describe expected behaviour here)
cursor should appear at the correct position.

##### Actual behavior.
(Describe actual behaviour here)
cursor appears at incorrect position.

##### Steps to reproduce the problem.
https://jsfiddle.net/karanRippling/gtx0uqzp/11/#&togetherjs=L3E5HqPNLv

##### OS.
(OS name and version here)
Mac OS

##### Browser.
(Browser name an version here)
Chrome 72

##### Recording.
(A recording showing how to reproduce the problem)
https://www.useloom.com/share/cef19339889743e0be8516ef61fcb886

**Comment by stefanneculai** [comment]
Thanks for reporting this @karanjariwala. Unfortunately, this is a browser rendering problem when using `contenteditable="false"` inside a content editable field and we cannot do too much about it.
