### ISSUE TITLE
At some scroll positions, the drop-down buttons stop working in Firefox

### ISSUE THREAD

**Issue by den11100** [froala/wysiwyg-editor#3312]
At some scroll positions, the drop-down buttons stop working in Firefox
This problem only Firefox  in other browsers work correctly.

froala version 2.9.3

##### OS.
win 10

##### Browser.
Firefox 65.0.1

##### Recording.
![error2](https://user-images.githubusercontent.com/22362946/53174556-abc04700-361c-11e9-8c11-1ba9e1b389ba.gif)

**Comment by den11100** [comment]
The problem were the options  height: 600, and iframe: true, 

```
$(function() {
		$('div#froala-editor').froalaEditor({
			iframe: true,
			height: 600,
		})
	})
```

I change to


```
  $(function() {
    $('div#froala-editor').froalaEditor({
      iframe: true,
      heightMin: 300,
      heightMax: 600
    })
  });
```
or

```
$(function() {
		$('div#froala-editor').froalaEditor({
			iframe: false,
			height: 600,
		})
	})
```

**Comment by stefanneculai** [comment]
@den11100 is this happening only on specific browser sizes or on all sizes?

**Comment by stefanneculai** [comment]
Closing this due to lack of response. Would be happy to reopen it once we get more details.
