### ISSUE TITLE
Error when inserting base64 image

### ISSUE THREAD

**Issue by meiordac** [froala/wysiwyg-editor#3315]
##### Expected behavior.

I am having trouble with the image plugin when inserting base64 photos, if I drag and drop an image before focusing the editor I get the described error:

##### Actual behavior.

```
zone.js:665 Unhandled Promise rejection: Cannot read property 'push' of null ; Zone: <root> ; Task: Promise.then ; Value: TypeError: Cannot read property 'push' of null
    at f (froala_editor.pkgd.min.js:7)
    at Object.bindClick (froala_editor.pkgd.min.js:7)
    at Object.bindCommands (froala_editor.pkgd.min.js:7)
    at i (froala_editor.pkgd.min.js:7)
    at Object.create (froala_editor.pkgd.min.js:7)
    at W (image.min.js:7)
    at I (image.min.js:7)
    at Object.B [as insert] (image.min.js:7)
```

##### Steps to reproduce the problem.
Drag and drop image without focusing and then use base64 to insert the image

https://jsfiddle.net/matiasiordache/5jba4wpm/2/

##### OS.
MacOS Mojave

##### Browser.
Chrome & FF latest versions

**Comment by stefanneculai** [comment]
@meiordac Do you think it would be possible to make a jsFiddle to highlight the problem? That would speed-up things a lot. Here is a basic jsFiddle you could use as a starting point: https://jsfiddle.net/froala/wc5c3jhk/.

**Comment by meiordac** [comment]
yes, here I have reproduced the scenario that I have https://jsfiddle.net/matiasiordache/5jba4wpm/2/

I identified the source of the issue, which is the reset to the editor (we have a special "admin" editor version, which has different options than the regular editor, so we need to set the admin options, and the only way of doing this that I found is by resetting Froala.

Because of a timing issue in the app we do the initialization of the admin feature on focus, this works when activating editor by clicking on it but when dragging and dropping a file into the editor, the init happens after the file has been dropped which creates the issue.

**Comment by stefanneculai** [comment]
@meiordac destroying the editor makes the `editor` object unavailable because the instance is not used anymore. This, it is normal to have this error happening.
