### ISSUE TITLE
Color picker with hidden tabs breaks active color indicator

### ISSUE THREAD

**Issue by bholtbholt** [froala/wysiwyg-editor#3316]
##### Expected behavior.
Hiding the tabs from the colour picker still indicates when a colour is picked

##### Actual behavior.
When tabs are hidden the active colour is never highlighted.

##### Steps to reproduce the problem.
I've done a bit of CSS restyling of the colour editor. Mainly:
- Remove the selection tabs so both text and background colours appear together
- Make the text colour swatches circular (though I'd like coloured letters without background colours)
- Add letters onto the background colour swatches to indicate they're background colours

This all works fine, but it seems like my selection isn't being indicated anymore.

Here's a [Fiddle](https://jsfiddle.net/cyrk0qdn/), but I couldn't get the colours plugin working

I've changed this:
<img width="244" alt="screen shot 2019-02-22 at 9 21 24 pm" src="https://user-images.githubusercontent.com/4933622/53282467-e42f5600-36ec-11e9-98be-7d28bf4c5671.png">

to:
<img width="405" alt="screen shot 2019-02-22 at 8 21 14 pm" src="https://user-images.githubusercontent.com/4933622/53282474-f3ae9f00-36ec-11e9-82e7-cfd4a7e9c480.png">

I believe the problem is because `.fr-selected-set` isn't applied so `.fr-active-item` is never applied.

Ideally, there would be a Froala config option to disable tabs.

##### OS.
Mac

##### Browser.
Any (I'm using Safari)

**Comment by stefanneculai** [comment]
@bholtbholt the current colors popup is made specifically to work with tabs. If you want to change it, then I would recommend creating a separate plugin based on it instead and update the behavior as well.
