### ISSUE TITLE
Pasting on iOS since Froala 2.9.3

### ISSUE THREAD

**Issue by chrisdeeming** [froala/wysiwyg-editor#3317]
This is a direct continuation of #3195 but now more serious as it has the potential to remove editor content (albeit, just what you're trying to paste - makes using the editor very difficult at least).

##### Expected behavior.
Pasting on iOS should fire the relevant paste clean up events.

##### Actual behavior.
The events do fire but the paste isn't processed due to undefined function error. The pasted content appears, but hitting Return deletes the content you just pasted.

##### Steps to reproduce the problem.
1. Copy any text to the clipboard in iOS (Safari or Chrome)
2. Paste the text into the editor on its own line.
3. If any clean up should have happened, it hasn't.
4. An error is logged in the console if debugging with Safari.
5. Hitting return deletes the content just pasted.

Exact console error:

```
TypeError: editor.$sc.overflow is not a function. (In 'editor.$sc.overflow('hidden')', 'editor.$sc.overflow' is undefined)
```

Which happens around here (the first prevent iOS scroll comment):

```javascript
      // Prevent iOS scroll.
      if (editor.helpers.isIOS() && editor.$sc) {
        editor.$sc.overflow('hidden');
      }
```

##### OS.
iOS

##### Browser.
Any iOS.

##### Recording.

https://youtu.be/6BjiSKAK0h4

**Comment by stefanneculai** [comment]
Should be fixed now on the latest master. It would be amazing if you could give it a try and let us know if you still face any problem. Thanks in advance!
