### ISSUE TITLE
Error messages in file-/image upload should show the actual error

### ISSUE THREAD

**Issue by awegmueller** [froala/wysiwyg-editor#3318]
##### Expected behavior.
The file-/image upload should show the actual error, otherwise the user has no clue what he must do in order to solve the problem (for instance the uploaded file has the wrong file-type or is too large). These type of errors are already identified by the code of the file/image plugins. So it should be easy to show a meaningful error message.

I've also checked similar reported issues (#2190, #1358) and I do think the suggested workarounds are kind of a hack and not a proper solution. Also this seems to be a requirement for many developers and users working with Froala (including this developer here), so it would make sense to implement this feature in the Froala editor.

I also understand that some errors might occur on the server, but I don't think this is an excuse not to show any error-details at all. Especially when some type of errors are already identified by the JavaScript code.

I'd suggest to add a new configuration option 'file-/imageUploadShowErrorDetails'. If it's set to false (default) message-boxes show the same (generic) error-message as today. If set to true it shows more details like:
- File is too large. Allowed max. file size: 1024 KB.
- Upload of file type .exe is not allowed. \n Allowed file types: jpg, png, gif.

The error-messages should contain a placeholder for easier localization like:
- File is too large. Allowed max. file size: ${maxFileSize} KB.
- Upload of file type ${invalidFileType} is not allowed. \n Allowed file types: ${allowedFileTypes}.

When something on the server goes wrong, the server response could provide an optional JSON object with an 'errorMessage' property, that will be shown in the message-box, e.g. 'File upload failed, insufficient storage available'.

##### Actual behavior.
User doesn't know what to do when an error occurs in file-/image upload. Workaround is possible, but is more like a hack.

##### Steps to reproduce the problem.
Try to upload a 100MB video file, when option 'fileMaxSize' is set to 5 MB.
Try to upload a .tiff image, when option 'fileAllowedTypes' is set to gif,png,jpg.

**Comment by stefanneculai** [comment]
Thanks for the suggestion, @awegmueller. I moved this to https://wysiwyg-editor-roadmap.froala.com/public/ideas/6561 and looking forward to getting others feedback on it in order to implement it.
