### ISSUE TITLE
Scrolling breaks inline editor toolbar if in div with overflow: scroll

### ISSUE THREAD

**Issue by philfreo** [froala/wysiwyg-editor#332]
If an inline editor toolbar is in a container div that has `overflow: scroll` (rather than the `<body>`) being what scrolls, then the position of the toolbar becomes incorrect as soon as the user scrolls.

Let me know if you need a screencast or jsfiddle example (would be helpful if you had a jsfiddle template somewhere already).

Proposed solution is to add a `container` option that defaults to `<body>` but that can be set to whatever your main scrolling div is.

**Comment by jsilve** [comment]
@stefanneculai I am trying to look at the link above with your fix and looks like im getting a 404

**Comment by stefanneculai** [comment]
@jsilve that's because we moved some things around. See here: https://github.com/froala/wysiwyg-editor/blob/master/html/misc/scrollable_container.html.
