### ISSUE TITLE
Small fonts don't use correct line-height

### ISSUE THREAD

**Issue by bch36** [froala/wysiwyg-editor#3320]
##### Expected behavior.
When a font size smaller than the default font size is selected, and text is written until it wraps, it is expected that the wrapping uses the line-height of the small font, rather than the default font.

##### Actual behavior.
Instead, the wrapping maintains the line-height from the default font, resulting in potentially-wide gaps between lines of text.  The larger the default font (the font size on the page containing the Froala editor), the wider the gap between lines.

##### Steps to reproduce the problem.
1. In the standard editor, type enough text that it will still wrap even after being shrunk.
2. Select all the text and selected the smallest font size.
3. The resulting lines of text are spaced according to the default font size instead of the small font size.

##### OS.
Windows, Froala 2.9.3

##### Browser.
Chrome 72

##### Recording.
[Full Featured _ WYSIWYG HTML Editor Examples _ Froala - Google Chrome 2_26_2019 12_02_26 AM.zip](https://github.com/froala/wysiwyg-editor/files/2904342/Full.Featured._.WYSIWYG.HTML.Editor.Examples._.Froala.-.Google.Chrome.2_26_2019.12_02_26.AM.zip)

**Comment by stefanneculai** [comment]
The font size is applied as an inline `SPAN` and not on the paragraph level. Thus, it is not possible to change the line-height only on it because the browser won't render.

**Comment by bch36** [comment]
Stefanneculai, thanks for the response!  You're correct about how the font-size is applied, but there is a fix, which I've implemented it in my own Froala source code.  The bug isn't a technical CSS bug, but rather an "expectations" bug.  The user's expectation is that the line-wrapping of the paragraph uses the line-height of the font-size they're using, similar to how standard text editors like Microsoft Word implement it.

The fix I implemented, which is a bit of a hack, and which I was hoping could be improved, was to set the font-size of each wrapping div to a minimal value of 1px, then force each text node to have a wrapping inline span with the explicit, currently-used font-size.

Setting the wrapping div's font-size to 1px removes the strut as a factor when the line-height is being calculated.  Forcing all text to have an explicit size ensures that the text looks correct and doesn't inherit the 1px font-size.  The result is that the line-height of the paragraph uses the largest font-size from the text inside the block, rather than the inherited font-size, to determine the line-height.  The text-editor now behaves more like the standard desktop editors that users are familiar with.

I'm happy to share more details if Froala is interested in pursuing this fix or feature.  I'd also welcome input on why my approach might be a bad idea, and unforeseen consequences I might encounter.

**Comment by stefanneculai** [comment]
While this might work in your case, it would not be working correctly when you just select parts of the text and have there different sizes.

**Comment by bch36** [comment]
Stefanneculai, thanks for thinking through a potential issue!  As it turns out, it works just fine in that scenario.  Setting the wrapping div's font-size to 1px effectively removes the minimum line-height that the strut would otherwise impose, leaving the line-height to be set by the inline spans' various font-sizes.  Having a mixture of font-sizes, large and small, seems to work as a user of a standard text-editor would expect. 

I welcome any other thoughts or potential issues you may come up with!

**Comment by stefanneculai** [comment]
Thanks for further checks, @bch36.

**Comment by bch36** [comment]
Acknowledged.  Thank you for taking the time to consider it!
