### ISSUE TITLE
videoDefaultWidth not working

### ISSUE THREAD

**Issue by emeryowa** [froala/wysiwyg-editor#3321]
##### Expected behavior.
The width property of the video is the same as the width given in `videoDefaultWidth` setting

##### Actual behavior.
The width property of the video is always 640, regardless of what value is given is in `videoDefaultWidth`

##### Steps to reproduce the problem.
Initialize Froala editor with `videoDefaultWidth` setting set to `0` or `100`
Insert a video. (I inserted video from YouTube)
Go to code view
Width set on video is 640
https://jsfiddle.net/34zwder1/
https://cl.ly/788fde2be863

##### OS.
MacOS Mojave 10.14.2

##### Browser.
Chrome 71.0.3578.98

##### Recording.
See jsfiddle https://jsfiddle.net/34zwder1/

On a side note:
Is it possible to set the width to `100%` and the height to `auto`?

**Comment by stefanneculai** [comment]
The videoDefaultWidth option is available only for the uploaded videos, not for the ones inserted via Youtube / Vimeo.

**Comment by emeryowa** [comment]
@stefanneculai When the `videoResponsive` option is set to true, the video iframe also gets a hardcoded with and height. This option was already added in the jsfiddle but also persists when I remove the `videoDefaultWidth` https://jsfiddle.net/d5fyvm3z/

**Comment by stefanneculai** [comment]
@emeryowa that is right, though they are being overridden by CSS and the video is responsive - taking the entire width.
