### ISSUE TITLE
Copy paste image on froala editor with image on MAC   

### ISSUE THREAD

**Issue by SJDrwsh** [froala/wysiwyg-editor#3322]
If I try to paste with image on mac OS it doesn't copy the image.

**Comment by stefanneculai** [comment]
@SJDrwsh could you please send a recording for this problem happening on our website demo (https://www.froala.com/wysiwyg-editor)? Thanks in advance.

**Comment by stefanneculai** [comment]
Closing it due to lack of response. If we get the requested details would be happy to reopen it.
