### ISSUE TITLE
IE11: Can't edit content of elements in the editor

### ISSUE THREAD

**Issue by miroslavgeorgiev-rg** [froala/wysiwyg-editor#3323]
Hi, Froala Team,
You closed my [previous ticket](https://github.com/froala/wysiwyg-editor/issues/3289) for this without resloving all the points there:
1) Can't edit content of blockquote element -after removing "overflow: hidden" and "min-height: 30px" properties from the css it is **fixed**.

2) Can't edit content of button element (styled link) - no css properties like the another, nothnig to be changed and can't be edited in IE11, so **not fixed**.

##### Expected behavior.
Can make content changes on button element (styled link) in the editor.

##### Actual behavior.
Can't make content changes on button element (styled link) in the editor.

##### Steps to reproduce the problem.
A [CodePen example](https://codepen.io/miroslavgeorgiev-rg/full/NoMdRZ) you can use:

1. Try to change the content of the button element (styled link).

##### OS.
Windows 7

##### Browser.
Internet Explorer 11

**Comment by stefanneculai** [comment]
Sorry, it looks I missed your reply on the other ticket. For the button, the `display: inline-block;` is causing that problem.
