### ISSUE TITLE
[Word copy paste] Font family for list not copied

### ISSUE THREAD

**Issue by waynechaw** [froala/wysiwyg-editor#3326]
##### Expected behavior.
Font family for list should be retained when pasting from Word to Froala

##### Actual behavior.
When we use a "theme font" on a list, and paste the list into froala, the list is missing the font family style.

<img width="872" alt="screen shot 2019-02-28 at 12 08 47 pm" src="https://user-images.githubusercontent.com/7528925/53595393-fd535f00-3b51-11e9-8953-3af5f48e8282.png">
 

##### Steps to reproduce the problem.

Copy the word doc I have attached to this issue. Paste it into Froala. In this word doc, Arial is set as the theme font. Font family will not work for Arial but other fonts will still work

[list.docx](https://github.com/froala/wysiwyg-editor/files/2916723/list.docx)

##### OS.
Mac

##### Browser.
Chrome

**Comment by stefanneculai** [comment]
Should be fixed in current master.
