### ISSUE TITLE
[Word copy paste]  extra line break is inserted

### ISSUE THREAD

**Issue by waynechaw** [froala/wysiwyg-editor#3330]
##### Expected behavior.
Line breaks should be the same from Word to Froala

##### Actual behavior.
After pasting into Froala, I see extra line breaks

##### Steps to reproduce the problem.
Copy the word doc I have attached to this issue. Paste it into Froala. In the Word Doc, there is 1 line break between the two lines of text. In Froala, there are two line breaks between the two lines of text

<img width="297" alt="screen shot 2019-02-28 at 5 32 53 pm" src="https://user-images.githubusercontent.com/7528925/53610427-aebcb980-3b7f-11e9-8047-c4d056ef168d.png">

<img width="470" alt="screen shot 2019-02-28 at 5 32 48 pm" src="https://user-images.githubusercontent.com/7528925/53610426-aebcb980-3b7f-11e9-89aa-d9cc3d6ee0dc.png">

[linebreak.docx](https://github.com/froala/wysiwyg-editor/files/2917571/linebreak.docx)

##### OS.
Mac

##### Browser.
Chrome

**Comment by srukali** [comment]
This is still an issue I'm seeing
