### ISSUE TITLE
Drag and drop image to upload does not work in IE11 / Edge

### ISSUE THREAD

**Issue by ffaubert** [froala/wysiwyg-editor#3331]
##### Expected behavior.
Go to the Froala demo on the homepage with either IE11 or Edge.  Click insert image.  Drag and drop an image using either IE11 or Edge.  I would expect to upload the image.

##### Actual behavior.
Edge: Shows an invalid drop zone
IE11: Opens the image in a new tab

##### Steps to reproduce the problem.
See above

##### OS.
Windows 10

##### Browser.
IE 11
Edge 18

##### Recording.
You can easily replicate this on your own homepage.

**Comment by navneetnagpal** [comment]
Hi @ffaubert,
This is working in master branch. So closing issue.
Thanks,
Navneet
