### ISSUE TITLE
Embedly output correct?

### ISSUE THREAD

**Issue by george-norris-salesforce** [froala/wysiwyg-editor#3332]
Testing out the Embedly plugin so we can embed videos from arbitrary sources..

https://snugsfbay.github.io/Online-Projects/resource/TrapFlag.mp4

Is this the expected output/behavior? It doesn't show the video..
![image](https://user-images.githubusercontent.com/17860864/53665252-c0ee3480-3c1f-11e9-8ccc-acbf4354090c.png)

**Comment by stefanneculai** [comment]
We are just using the Embed.ly API: https://embed.ly/. It looks this is the way they are embedding MP4.
