### ISSUE TITLE
Deleting the last character of a paragraph deletes that paragraph.

### ISSUE THREAD

**Issue by largeden** [froala/wysiwyg-editor#3333]
##### Expected behavior.
![2019-03-05 01 37 55](https://user-images.githubusercontent.com/5575931/53748036-ddbc8d80-3ee7-11e9-807a-1ff88e7d80a4.gif)

##### Actual behavior.
![2019-03-05 01 34 49](https://user-images.githubusercontent.com/5575931/53748042-e0b77e00-3ee7-11e9-817b-6d7563bf314c.gif)

Froala V2.9.3

This is an problem related to the issue below.
This symptom occurs when you apply the options below.

```javascript
keepFormatOnDelete: false
```

https://github.com/froala/wysiwyg-editor/issues/1379

I modified the code below.

```javascript
/**
 * Do backspace at the middle of a block tag.
*/
function _middleBackspace(marker) {
//...

    // https://github.com/froala/wysiwyg-editor/issues/2626.
    while (!editor.node.isElement(prev_node.parentNode) && editor.node.isEmpty(prev_node.parentNode) && $.FE.NO_DELETE_TAGS.indexOf(prev_node.parentNode.tagName) < 0) {
      var t_node = prev_node;
      prev_node = prev_node.parentNode;
    //  t_node.parentNode.removeChild(t_node); // <- here (remove)
    }

    $(marker).after($.FE.INVISIBLE_SPACE + $.FE.MARKERS); // <- here

    // https://github.com/froala/wysiwyg-editor/issues/1379.
    if (editor.node.isElement(prev_node.parentNode) && !marker.nextSibling && prev_node.previousSibling && prev_node.previousSibling.tagName == 'BR') {
      $(marker).after('<br>');
    }

    if(!editor.node.isElement(prev_node.parentNode) && ['P', 'DIV', 'BLOCKQUOTE', 'OL', 'UL', 'LI'].indexOf(prev_node.tagName) < 0) { // <- here
      prev_node.parentNode.removeChild(prev_node);
    }

//...

```

**Comment by largeden** [comment]
Sorry,

It can be solved with the following functions.
```javascript
$.FE.NO_DELETE_TAGS.push('P','DIV');
```
I think this option should be included in the defaults.
Many people will be confused.

**Comment by stefanneculai** [comment]
@navneetnagpal do you think you could look into this?

**Comment by navneetnagpal** [comment]
Sure.

**Comment by navneetnagpal** [comment]
@largeden, I have tested on master branch and seems to be working fine. I have used `keepFormatOnDelete: false` this option
Please see below
![Uploading Issue-3333.gif…]()
If possible can you make js fiddle if you are using other options as well.

**Comment by largeden** [comment]
@navneetnagpal 
Would you test it with the html code below?

There is a problem when the `a` tag exists in the paragraph to be deleted.

```html
<p>Hello World</p>

<p>Hello <a href="//froala.com">froala.com</a> Hello</p>

<p>Hello Hello</p>
```

**Comment by navneetnagpal** [comment]
got it! issue is coming with this HTML.

thanks @largeden will look into this ASAP.
