### ISSUE TITLE
Unable to apply multiple styles when no text is typed

### ISSUE THREAD

**Issue by sblattj** [froala/wysiwyg-editor#3334]
##### Expected behavior.
The expected behavior is that multiple styles can be added before beginning to type in a new Froala Editor Instance.

##### Actual behavior.
The actual behavior is that only one style can be added at a time when the text editor is empty.

##### Steps to reproduce the problem.
1. If there is text in a Froala Editor, erase all of it, even spaces.
2. Try applying multiple styles

##### OS.
Mac and PC

##### Browser.
All

**Comment by stefanneculai** [comment]
@sblattj what do you mean by multiple styles?

**Comment by sblattj** [comment]
@stefanneculai I mean trying to add more than one style before any text is typed / while the text editor is empty.

Our users would naturally expect to be able to make a text 14px, bold, and underlined, then begin to type with all of those styles applied. The workaround they have to go through to is type the text first, then select it and add the styles.

We have over five bugs now raised by QA that are caused by this one issue, so it is extremely important to us to have it fixed, or at least to give us a nice workaround.

Thanks so much for looking into it.

**Comment by stefanneculai** [comment]
Should be fixed on the current master. Would be great if you can give it a try.
