### ISSUE TITLE
Styles don't nest properly and unnecessary tags are created when text editor is empty - related to 3334

### ISSUE THREAD

**Issue by sblattj** [froala/wysiwyg-editor#3335]
This issue is related to #3334 .

##### Expected behavior.
Nested styles - this behavior happens if there is text in the editor before applying styles

##### Actual behavior.
Styles keep adding next to each other like siblings

##### Steps to reproduce the problem.
1. If there is text in the editor, delete it, even the spaces
2. Add multiple styles while observing the elements

##### Recording
<img width="1607" alt="issueempty" src="https://user-images.githubusercontent.com/5125883/53775285-d2953d80-3ea6-11e9-8a15-9c920772d49f.png">

**Comment by stefanneculai** [comment]
@sblattj could you please let us know the steps to follow for that? Thanks in advance.

**Comment by sblattj** [comment]
@stefanneculai Simply erase all text including whitespaces, then click bold, italic, underline, strikethrough, change the color, change the text size, and tags will just continue to be added as siblings. If you aren't looking at the code, it simply looks like the styles are overriding each other. Looking more into it, they are not nesting correctly. I found that simply adding a space before typing fixes the problem, but this shouldn't be necessary. This is causing quite a few bugs in our application, and it would be extremely helpful to be fixed. Thanks for looking at it.
