### ISSUE TITLE
Spaces break image captions in Firefox

### ISSUE THREAD

**Issue by brianlenz** [froala/wysiwyg-editor#3339]
##### Expected behavior.
I should be able to type a space into an image caption in all browsers

##### Actual behavior.
When using Firefox, if I type a space into the image caption, it breaks to a newline.

##### Steps to reproduce the problem.
* Open Firefox.
* Go here: https://www.froala.com/wysiwyg-editor
* Click to add a caption to the image.
* Type "a a".
* The second "a" will appear in the left column at the top of the post.

##### Browser.
Firefox

**Comment by ilyaskarim** [comment]
It might be a bug on our side and we'll investigate it further and someone will look over it shortly. I will get back to you as soon as we have news.

**Comment by sblattj** [comment]
My company is also experiencing a similar issue.
1. Create a text box
2. Resize the text box to be smaller
3. Type until there is a line break
4. Add a numbered list
5. Press enter

Expected behavior:
1. This is a long string
    of text.
2. This is more text

Actual behavior:
1. This is a long string
    of text.
2. 
    This is more text

**Comment by brianlenz** [comment]
Is this fixed now that it's closed, @navneetnagpal?

**Comment by navneetnagpal** [comment]
Yes. pls checkout the v2 branch.

**Comment by brianlenz** [comment]
Just to be clear, we are running v2 right now. Is it fixed in v2, the recently-released v3, or both? Thank you!

**Comment by casualuser** [comment]
@brianlenz this was fixed in v2 and will be released in upcoming 2.9.6
right now you can checkout actual `v2` branch and verify it with files sourced directly from repo at your side before 2.9.6 released
