### ISSUE TITLE
Popup bug when text is very large

### ISSUE THREAD

**Issue by sblattj** [froala/wysiwyg-editor#3340]
##### Expected behavior.
Popup shows either above or below text

##### Actual behavior.
Popup shows inside text

##### Steps to reproduce the problem.
1. Set text to max size
2. Create link from text
3. Hover over and observe

![image](https://user-images.githubusercontent.com/5125883/53990345-f0e47e80-40dc-11e9-8975-13ca45123bbe.png)

**Comment by ilyaskarim** [comment]
Hey Stephen, I am afraid that I'm unable to reproduce this bug. It could be great if you could make a recording to highlight the problem.

**Comment by sblattj** [comment]
I think the issue may have been fixed. I tried to reproduce it again and
could not.

I'm looking forward to 2.9.4 as is my company!

Do you have an idea of when it will be released?

Thanks,
Stephen

**Comment by stefanneculai** [comment]
We are looking to release it in the upcoming 2 weeks.
