### ISSUE TITLE
Problem after selecting multiple cells in table

### ISSUE THREAD

**Issue by theun0524** [froala/wysiwyg-editor#3343]
##### Expected behavior.
(Describe expected behaviour here)
No Error

##### Actual behavior.
![image](https://user-images.githubusercontent.com/43725818/54188360-d94d3180-44f2-11e9-857d-7e18d9d20c5f.png)

![image](https://user-images.githubusercontent.com/43725818/54188423-000b6800-44f3-11e9-99de-51d1c3bf3bdf.png)

##### Browser.
Chrome

**Comment by ilyaskarim** [comment]
Hi theun0524, Can you make a jsFiddle with this content?

**Comment by theun0524** [comment]
I added the content. Same error will be occurred.

**Comment by theun0524** [comment]
@ilyaskarim Is there any update?
