### ISSUE TITLE
Nested list item trailing content converted to new list item

### ISSUE THREAD

**Issue by mikesul** [froala/wysiwyg-editor#3344]
It appears to be impossible to have any trailing content after a nested list without it being pushed/converted to a separate list item.

In the code view, enter the following HTML:

```
<ul>
	<li>
		Before
		<ul><li>Inner</li></ul>
		After
	</li>
</ul>
```

Toggle the code view off and back on, and you'll see that the output is now semantically different:

```
<ul>
	<li>Before

		<ul>
			<li>Inner</li>
		</ul>
	</li>
	<li>After</li>
</ul>
```

Specifically, the "After" line is now a separate bullet, rather than being part of the 1st outer list item.

Technically, it does look like there's a workaround, though I'm not sure if we could easily apply it in our case. If I wrap the inner `<ul>` in a `<div>`, that appears to change the behavior.

**Comment by ilyaskarim** [comment]
It might be a bug on our side and we'll investigate it further and someone will look over it shortly. I will get back to you as soon as we have news.

**Comment by ilyaskarim** [comment]
Issue NR on V3 & V4
