### ISSUE TITLE
Cannot enter more text into the editor after setting an image caption

### ISSUE THREAD

**Issue by ffaubert** [froala/wysiwyg-editor#3346]
##### Expected behavior.
You should be able to continue adding text after setting an image caption

##### Actual behavior.
The editor is locked down and you can't add more texst

##### Steps to reproduce the problem.
Go to the froala editor on your home page
Clear out the contents
Upload an image
Set a caption
Try to add new text and observe that you cannot

##### OS.
Mac

##### Browser.
Latest chrome

**Comment by stefanneculai** [comment]
Please enable https://www.froala.com/wysiwyg-editor/docs/options#imageAddNewLine

**Comment by ffaubert** [comment]
@stefanneculai That does not fix the problem.  Here is a code pen to demonstrate it:

https://codepen.io/ffaubert/pen/LaamyW

1. Start with the empty editor
2. Upload an image
3. Set a caption
4. Try to add more text to the editor -- it fails

As you can see, this is with imageAddNewLine turned on.

Would you please reopen this issue?

**Comment by stefanneculai** [comment]
The CodePen is using version 2.9.1. Please make sure you use 2.9.3.

**Comment by rogerfar** [comment]
@stefanneculai the codepen is using 2.9.3, please re-open this issue.
