### ISSUE TITLE
Font Family Issue - New paragraph inserted between existing paragraph doesn't inherit font

### ISSUE THREAD

**Issue by VenkateshJhipster** [froala/wysiwyg-editor#3348]
##### Expected behavior.
When a new paragraph is inserted between the existing paragraphs, the font family must be inherited from the previous paragraph.

##### Actual behavior.
When a new paragraph is inserted between the existing paragraphs, the font family is not getting inherited from the previous paragraph.

##### Steps to reproduce the problem.
Please refer the attached document and video for reproducing the steps.

[Font.Family.Issue.-.Froala.Editor (1).docx](https://github.com/froala/wysiwyg-editor/files/2964884/Font.Family.Issue.-.Froala.Editor.1.docx)

##### OS.
Windows 10 

##### Browser.
Version 72.0.3626.121 (Official Build) (64-bit)
[screen-capture.zip](https://github.com/froala/wysiwyg-editor/files/2964883/screen-capture.zip)

##### Recording.
(A recording showing how to reproduce the problem)

**Comment by stefanneculai** [comment]
Please enable `keepFormatOnDelete` option.
