### ISSUE TITLE
Plain paste does not work when copying from Froala instance

### ISSUE THREAD

**Issue by georgegrafos** [froala/wysiwyg-editor#3349]
##### Expected behavior.
Formatted text copy and pasted from a Froala instance should be cleared of formatting when pasting.

##### Actual behavior.
Formatted text from a Froala instance is not cleared upon pasting, even with plainPaste option enabled.

##### Steps to reproduce the problem.
1. Navigate to https://jsfiddle.net/froala/scmf4y26/
2. Format the text in the Froala editor
3. Highlight the text and copy it
4. Try to paste using ctrl+v (command+v on Mac) or ctrl+shift+v (command+shift+v on Mac) to past without formatting
5. Notice in both cases the text is pasted with formatting 

##### OS.
macOS 10.14.3

##### Browser.
Chrome v72

**Comment by venky0195** [comment]
Hi @georgegrafos, did you get this issue resolved?
If yes, please share the solution.
