### ISSUE TITLE
Text Flickers on IE11

### ISSUE THREAD

**Issue by craig-jennings** [froala/wysiwyg-editor#3353]
##### Expected behavior.
I can type in the textbox and the text doesn't flash.

##### Actual behavior.
The text flashes periodically as I type. It appears to happen when a `height` option is specified and the scrollbar appears.

As a note, setting the `heightMax` option seems to mitigate this behavior. That should not be required though.

##### Steps to reproduce the problem.
1. Open https://jsfiddle.net/7zbd45sx/embedded/result,css,html,js in IE11
1. Type text until the vertical scrollbar appears
1. Continue typing, but notice that every once in a while the text will flash or flicker as you type

##### OS.
Windows 10

##### Browser.
IE11

**Comment by stefanneculai** [comment]
@craigjennings11 could you please send us a recording? Thanks in advance.

**Comment by craigjennings11** [comment]
![example](https://user-images.githubusercontent.com/1683368/55191904-56260f80-5171-11e9-800b-35a7efba2797.gif)

**Comment by sfhaney** [comment]
I have also noticed some flickering behavior starting in build 2.9.4 on IE11.  It doesn't appear to happen on any other browsers that I've noticed.  I haven't tested out the heightMax option.

**Comment by sfhaney** [comment]
Setting heightMax did work for me as well.  Thank you for noting that @craigjennings11 , saved me a ton of time!

**Comment by SwarnikaG** [comment]
I am facing the same problem for IE 11. Is there any other way?

**Comment by pahujapuneet** [comment]
In Fullscreen mode the heightMax option even doesn't mitigate the problem.
