### ISSUE TITLE
Bug: quick insert doesn't work right with toolbarInline: true

### ISSUE THREAD

**Issue by rpearce** [froala/wysiwyg-editor#3356]
##### Expected behavior.
Expected quick insert to work no matter the `font-size` nor `line-height` when `toolbarInline: true` is enabled.

##### Actual behavior.
The actual behavior is that quick insert does _not_ work when you are on the last line of an editor with `toolbarInline: true` with a `font-size` greater than `16px` combined with a `line-height` greater than `32px`. (See the fiddle below for how simple to reproduce this it is).

##### Steps to reproduce the problem.
1. navigate to this fiddle: https://jsfiddle.net/1c946w5q/
1. insert a new line at the end of the example by hitting ENTER
1. observe the quick insert functionality not working
1. hit return _again_ and then go to the _next to last line_
1. observe that it works on the next to last line but _not_ the last line

##### OS.
macOS Mojave 10.14.3

##### Browser.
Firefox 65.0.1

##### Recording.
https://360.articulate.com/review/content/78315deb-8348-499c-87d4-a480ff90cdd5/review

**Comment by rpearce** [comment]
Uh, hi @froala-bot. Why did you close this?

**Comment by stefanneculai** [comment]
@rpearce it was closed because we put a fix for it. Could you please try with the latest Github master?

**Comment by rpearce** [comment]
@stefanneculai That's wild you did this this fast, and not seeing a reference to the bug threw me off there. I apologize!

Will try it out ASAP

**Comment by rpearce** [comment]
@stefanneculai It works! Test case HTML file:

```html
<!DOCTYPE html>
<html>
  <head>
    <!-- Include CSS for icons. -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />

    <!-- Include Editor style. -->
    <link href="https://cdn.jsdelivr.net/npm/froala-editor@2.9.0/css/froala_editor.pkgd.min.css" rel="stylesheet" type="text/css" />
    <link href="https://cdn.jsdelivr.net/npm/froala-editor@2.9.0/css/froala_style.min.css" rel="stylesheet" type="text/css" />

    <!-- Include jQuery lib. -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>

    <!-- Include Editor JS files. -->
    <script type="text/javascript" src="https://cdn.rawgit.com/froala/wysiwyg-editor/master/js/froala_editor.pkgd.min.js"></script>
    <!--<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/froala-editor@2.9.3/js/froala_editor.pkgd.min.js"></script>-->

    <style>
      #froala-editor {
        margin-left: 60px;
        font-size: 17px;
        line-height: 33px;
      }
    </style>
  </head>
  <body>
    <!-- Create a tag that we will use as the editable area. -->
    <!-- You can use a div tag as well. -->
    <div id="froala-editor">
      <h3>Quick Insert which makes WYSIWYG HTML editing awesome.</h3>
      <p>The quick insert button will appear when you have focus on an empty line. To see it in action hit enter at the end of this line.
    </div>


    <!-- Initialize the editor. -->
    <script>
      $(function() {
        $('div#froala-editor').froalaEditor({
          toolbarButtons: ['bold', 'italic', 'underline', 'insertImage', 'insertLink', 'insertTable', 'undo', 'redo'],
          toolbarInline: true
        });
      });
    </script>
  </body>
</html>
```
