### ISSUE TITLE
Exiting fullscreen doesn't revert styles completely

### ISSUE THREAD

**Issue by thejahweh** [froala/wysiwyg-editor#3358]
##### Expected behavior.
Revert styles set for fullscreen

##### Actual behavior.
Some styles are not reverted like margin and width on some elements.

##### Steps to reproduce the problem.
https://www.froala.com/wysiwyg-editor
1. check the styles in the debug bar.
2. go fullscreen and see which are changed.
3. exit fullscreen and notice some styles are not reverted.

##### OS.
Windows

##### Browser.
Chrome

##### Recording.
![image](https://user-images.githubusercontent.com/10514993/54682814-3a3ac200-4b10-11e9-9d44-2c96ea553b98.png)

**Comment by stefanneculai** [comment]
Should be fixed on the current master.
