### ISSUE TITLE
br tag

### ISSUE THREAD

**Issue by VenkateshJhipster** [froala/wysiwyg-editor#3359]
##### Expected behavior.
Onlick of **Enter** twice, /br tag should be appended

##### Actual behavior.
Onlick of **Enter** twice, /br tag
[br tag not getting appended on click of Enter.docx](https://github.com/froala/wysiwyg-editor/files/2988483/br.tag.not.getting.appended.on.click.of.Enter.docx)
 is not getting appended

##### Steps to reproduce the problem.
Please refer the attached document

##### OS.
Windows 10

##### Browser.
Version 72.0.3626.121 (Official Build) (64-bit)

**Comment by VenkateshJhipster** [comment]
Adding to this case, &#8203 is getting appended instead of BR tag.

**Comment by stefanneculai** [comment]
@VenkateshJhipster Do you think it would be possible to make a jsFiddle to highlight the problem? That would speed-up things a lot. Here is a basic jsFiddle you could use as a starting point: https://jsfiddle.net/froala/wc5c3jhk/.

**Comment by stefanneculai** [comment]
Closing this due to lack of details.
