### ISSUE TITLE
Link not created & displayed correctly when entered into editor

### ISSUE THREAD

**Issue by xandervdm** [froala/wysiwyg-editor#3360]
##### Expected behavior.
The entered link should be linkified correctly

##### Actual behavior.
(Describe actual behaviour here)

##### Steps to reproduce the problem.
1. Goto https://www.froala.com/wysiwyg-editor
2. Type the following example link into the editor: https://www.google.com
3. Do not press space bar or enter after typing the above

Note that only the [https://www.google] part is linkified and not the whole [https://www.google.com]

##### OS.
Windows 7 & Windoww 10

##### Browser.
Chrome Version 72.0.3626.121 (Official Build) (64-bit)
Firefox Version 65.0.2 (64-bit)

##### Recording.
Follow above steps to reproduce incorrect link in below image:

![Froala-incorrect-link](https://user-images.githubusercontent.com/13308801/54730540-69276580-4bee-11e9-80f5-03a13b9abcc8.png)

**Comment by stefanneculai** [comment]
In order to improve performance, it is being changed to a link only after you hit some characters: dot, space or enter.

**Comment by xandervdm** [comment]
I can understand "space" or "enter", but "dot" doesn't make sense as all domains have a dot in the middle of the domain.

**Comment by stefanneculai** [comment]
"dot" is for cases like: _I searched on google.com. Another phrase starts here._
