### ISSUE TITLE
Editor scrolls to bottom on enter/backspace

### ISSUE THREAD

**Issue by thejahweh** [froala/wysiwyg-editor#3361]
##### Expected behavior.
Don't scoll at all or scroll accordingly.

##### Actual behavior.
Scrolls down to the bottom.

##### Steps to reproduce the problem.
The Problem occurs if the editor uses an Iframe and is not at the top of the page. On the example there is a div with a 1000px height above the editor.
https://jsfiddle.net/7y1d5opv/

##### OS.
Any

##### Browser.
Chrome/Firefox

**Comment by thejahweh** [comment]
This bug was introduced with the **release 2.6.3** `Automatically scroll editor after calling html.insert.`

**Comment by wmacdonald919** [comment]
+1 for this. We have been experiencing this issue for a while and I feel like in version 2.9.0 it was listed as fixed. I understand it based on the fact that it is an iframe, positioned down from the window and Froala is having and issue understand where to scroll the iframe for the cursor. 

I feel this is a very common issue with anyone using Modals to contain the editor. Any communication around this that I can pass on is greatly appreciated

**Comment by SquareBeard** [comment]
We have the same problem with version 3.0.5 but I can't reproduce it in jsfiddle.
So I believe there must be a conflict somewhere with our code.
Any advice on how to fix this problem ?
Could it be CSS related, even with the editor using an iframe ?

**Comment by wmacdonald919** [comment]
Since updating to 2.9.6 (not on 3 yet) this issue has been resolved for us. Strong possibility it is an issue with some conflicting CSS and the use of an iframe. We are also using an iframe and found Froala was having an issue calculating the position of the iframe in the window. If you fine a way to reproduce in jsFiddle, the Froala folks are good at digging in

**Comment by SquareBeard** [comment]
Indeed, it has to do with the vertical position of the iframe, if I move it at the top of the page there is no more scrolling.
Now to find the cause...

**Comment by SquareBeard** [comment]
We found a workaround by removing the fixed height on the editor and setting it on the iframe body.

So from this:
`{
    height: 300,
    heightMax: 300,
    heightMin: 300,
    iframe: true
}`
to this:
`{
    iframeStyle: 'body{height:300px;overflow:auto;}',
    iframe: true
}`

I don't think it is a proper fix, but it will do for now.

**Comment by danchaseCTS** [comment]
I'm having this issue right now, I don't have any height defined at all, wanting the editor to just keep growing.. Once it grew past the edge of the page, it does it.

**Comment by CathalG** [comment]
Any ideas on this, still seems to be an open issue?

**Comment by nirvparekh** [comment]
This issue still persist in 3.2.4 / 3.2.5.
No matter we give configurations or not. it scrolls to bottom on hitting _Enter_ or `this.cursor.enter()`

**Comment by DioNNiS** [comment]
+1
