### ISSUE TITLE
Froala does not include custom requestHeaders when downloading images

### ISSUE THREAD

**Issue by stalar** [froala/wysiwyg-editor#3362]
Our images are protected by authorisation. We set a custom header using [requestHeaders](https://www.froala.com/wysiwyg-editor/docs/options#requestHeaders) which has our authentication token. This works correctly when Froala uploads an image, but does not work when it downloads images included in a document.

##### Expected behavior.
Headers specified in requestHeaders to be present when downloading images.

##### Actual behavior.
Headers specified in requestHeaders are not present when downloading images.

##### Steps to reproduce the problem.
Create a Froala editor, set the requestHeaders options to something. Check if outgoing http requests for images include the headers.

##### OS.
macOS 10.14.3

##### Browser.
Chrome 73.0.3683.75

**Comment by stefanneculai** [comment]
Images are being loaded by using the `src` attribute of the `img` tag. Unfortunately, browsers do not support adding custom headers there. What I would be suggesting is to use a bearer token.
