### ISSUE TITLE
Table Line Breaker / Insert Helper does not correct its position properly on zoom out.

### ISSUE THREAD

**Issue by sblattj** [froala/wysiwyg-editor#3365]
##### Comments.
I'm not sure if this floating line and button is called the Line Breaker, Insert Helper, or both. We really need this fixed as it is causing problems in an app we integrate Froala text editor into. We don't always want the editor to be in a zoomed-in position. I tried turning "tableInsertHelper" to false and the helper still shows up. Please advise.

##### Expected behavior.
Table Insert Helper stays where it should be.

##### Actual behavior.
Table Insert Helper does not stay in place.

##### Steps to reproduce the problem.
1. Create a table.
2. Click outside of table.
3. Hover over bottom or top of table.
4. While helper is being displayed, zoom out with browser.

##### OS.
Mac

##### Browser.
Chrome

##### Recording.
<img width="1213" alt="tableInsert2" src="https://user-images.githubusercontent.com/5125883/55033864-55567780-4fd1-11e9-8ae6-6adee18eca6d.png">

**Comment by stefanneculai** [comment]
@sblattj could you please make a recording? It works fine for me on the same environment.

**Comment by stefanneculai** [comment]
Closing this due to lack of details.
