### ISSUE TITLE
Bulleted/Numbered Lists are losing their formatting 

### ISSUE THREAD

**Issue by ragnerrok** [froala/wysiwyg-editor#3367]
##### Expected behavior.
I expect bulleted and numbered lists to keep the formatting I assigned in the previous bullets/numbers.

##### Actual behavior.
After the first bullet/number it loses the formatting. Sadface

##### Steps to reproduce the problem.
Create a bullet or numbered list. Select at least one formatting option. Add things to the list. Watch the second bullet and so on not have the formatting selected.

##### OS.
Mac OS version 10.13.6

##### Browser.
Chrome

##### Recording.
Recordings were taken on the [Full Feature Demo](https://www.froala.com/wysiwyg-editor/examples/full-featured).
I first found it when I updated to the latest version of Froala 2.9.3. But I am not sure if the earlier versions were broken. 
![broken-bullets](https://user-images.githubusercontent.com/2609762/55105806-708db980-509b-11e9-856c-aafa2cdafbe4.gif)
![broken-numbers](https://user-images.githubusercontent.com/2609762/55105810-72f01380-509b-11e9-86a5-6866706def89.gif)

**Comment by stefanneculai** [comment]
@ragnerrok do you think you could give this a try on the Github master branch? It should be fixed here. Thanks in advance.

**Comment by ragnerrok** [comment]
Pulled the latest master and tested on the full feature page (full.html) and I get the same results. 
![bullets-master](https://user-images.githubusercontent.com/2609762/55249570-5d552800-521a-11e9-908b-c4cfea96b4f9.gif)
