### ISSUE TITLE
Cannot re-edit/update Uploaded File

### ISSUE THREAD

**Issue by ahmadsyamim** [froala/wysiwyg-editor#3369]
##### Expected behavior.
Can click on the link

##### Actual behavior.
When hovering, the cursor changed to "Move" cursor and no edit window appear.

##### Steps to reproduce the problem.
N/A

##### OS.
Windows 10

##### Browser.
IE11

##### Recording.
N/A

**Comment by ahmadsyamim** [comment]
And also, when i'm updating the link, it will duplicate the link to new line.

**Comment by ilyaskarim** [comment]
Without reproducing the issue on my side it is hard to help you. Do you think it would be possible to make a jsFiddle to highlight the problem? That would speed-up things a lot. Here is a basic jsFiddle you could use as a starting point: https://jsfiddle.net/froala/wc5c3jhk/.

**Comment by stefanneculai** [comment]
@ahmadsyamim once a file is being uploaded, it is being inserted as a link. If you want to remove it, you can listen to the https://www.froala.com/wysiwyg-editor/docs/events#file.unlink event and make a request over to your server to remove it.
