### ISSUE TITLE
Embedly not rendering properly

### ISSUE THREAD

**Issue by wmacdonald919** [froala/wysiwyg-editor#3372]
When initializing Froala with `div` included in `htmlAllowedEmptyTags` embedly will not render the card. At some point in time we added `div` because Froala was removing empty `div` tags and this was causing an issue with embedly cards rendering. Since the latest release I feel one of the bugfixes around empty editors has caused this issue. We have fixed this by removing the `div` and leaving it as the default values, I just wanted to bubble this up so it is understood and if anyone runs into this it is a simple fix.

##### Expected behaviour.
Embedly card renders on insert

##### Actual behaviour.
DOM element gets inserted into the editor, but embedly does not pick it up and does not render the card

##### Steps to reproduce the problem.
Fiddle showing a simple editor with a change to the htmlAllowedEmptyTags
https://jsfiddle.net/3rqj7tzp/

##### Browser.
All

**Comment by stefanneculai** [comment]
`DIV` tag is a special block inside the editor and it is designed so that including it in `htmlAllowedEmptyTags` is not an option.

**Comment by wmacdonald919** [comment]
Can this be written in the docs possibly? It took some time to track this issue down, so if `div` is not allowed to be passed in the array for `htmlAllowedEmptyTags`, can that be noted?

Thanks for the info @stefanneculai
