### ISSUE TITLE
Link: "Open in new window" inserts text tag instead of target tag

### ISSUE THREAD

**Issue by GumpDK** [froala/wysiwyg-editor#3374]
Hi there.

I have a problem when inserting links.

##### Expected behavior.
When ticking the box "Open in new window", target="_blank" should be added.

##### Actual behavior.
When ticking the box "Open in new window", text="_blank" is be added.

**Comment by whoisdis** [comment]
We have this issue as well...

**Comment by stefanneculai** [comment]
@GumpDK @whoisdis could you please let us know the steps to reproduce this? Thanks in advance.

**Comment by GumpDK** [comment]
@stefanneculai It has been working for us when we where on an older version, but after vi upgraded to version 2.9.3 it started. The options we use are as follows, i dont know if those are helpful:
`key: '',
        toolbarSticky: false,
        charCounterCount: false,
        enter: $.FroalaEditor.ENTER_DIV,
        theme: 'custom',
        toolbarButtons: ['fontFamily', 'fontSize', 'bold', 'italic', 'underline', 'strikeThrough', 'color', '|', 'formatUL', 'formatOL', 'align', 'outdent', 'indent', '|', 'undo', 'redo', '|', 'emoticons', 'insertHR', 'clearFormatting', 'html'],
        toolbarButtonsSM: null, // Dont allow the standard behavior of reducing the set of tools in the toolbar
        toolbarButtonsXS: null,
        language: Object.keys($.FE.LANGUAGE)[0],
        linkEditButtons: ['linkOpen', 'linkEdit', 'linkRemove'],
        imageEditButtons: ['imageRemove', 'imageSize', '|', 'imageLink', 'linkOpen', 'linkEdit', 'linkRemove'],
        htmlAllowedStyleProps: ['float', 'font-size', 'font-family', 'color', 'width', 'background-color', 'text-align'], // On load of text, froala cleans the html. Add styles here, that are not to be removed.                    
        fontFamily: {  // Those without comments are just copied from the Froala defaults
            'Arial,Helvetica,sans-serif': 'Arial',
            'calibri,sans-serif': 'Calibri', // Required by Uddevalla
            'courier new, monospace': 'Courier New',  // Added as it was available in former editor
            'Georgia,serif': 'Georgia',
            'Impact,Charcoal,sans-serif': 'Impact',
            'Tahoma,Geneva,sans-serif': 'Tahoma',
            'Times New Roman,Times,serif,-webkit-standard': 'Times New Roman',
            'Verdana,Geneva,sans-serif': 'Verdana',
            'arial black,sans-serif': 'Wide'  // Added as it was available in former editor
        },
        colorsBackground: getColorPalette(),
        colorsText: getColorPalette(),
        colorsStep: 8,
        tableStyles: {
            'table table-bordered': 'Bordered'
        }`

**Comment by whoisdis** [comment]
On V2.8.4 here, even with a default editor (no options set) text="_blank" is output.

**Comment by whoisdis** [comment]
Have found the cause of the issue in this instance.

We are using MS MVC, the Froala scripts were linked in as a bundle:
`bundles.Add(new ScriptBundle("~/bundles/froalaEditor/js").Include("..."));`
and in the view:
`@Scripts.Render("~/bundles/froalaEditor/js")`

Linking it in as a bundle (not a ScriptBundle) outputs target="_blank" as expected:
`bundles.Add(new Bundle("~/bundles/froalaEditor/js").Include("..."));`

The MVC minificiation was obviously upsetting the link insert...

**Comment by GumpDK** [comment]
I testet out the solution of @whoisdis. We are also using ScriptBundle, not Bundle, but our include was for the minified file, like this:
`.Include("~/node_modules/froala-editor/js/froala_editor.min.js")`
Changing it to the non-minified file, like this, did the trick:
`.Include("~/node_modules/froala-editor/js/froala_editor.js")`

So i'm thinking it is not a bug in the Froala editor. I'm closing the case.

@whoisdis Thank you for leading in the right direction 😄  👍

**Comment by philiphendry** [comment]
I had this same problem and if I set linkAlwaysBlank to true the target and rel attributes would be added fine but set to false the rel and target attributes would be missing and instead text="_blank" was added. I pulled out froala_editor.pkgd.min.js from the bundling config (I'm using Mad Kirstensen's bundler in a ASP.NET project) and it was fine. It would appear that trying to minify the javascript a second time breaks something! I've lost the benefit of bundling but at least it's working now :)

**Comment by CrazyKodo** [comment]
hmm... got the same issue on v2.9.6.
After so many years, I guess I found the line causing this. 
seems it was caused by one line in link.min.js

`(e=m(r[t])).is(":checked")?s[e.attr("name")]=e.data("checked"):s[e.attr("name")]=e.data("unchecked")||null;`
will be convert to this line in the bundle
`o[i.attr("name")] = (i = t(s[r])).is(":checked") ? i.data("checked") : i.data("unchecked") || null;`

in the original line
```
---- r = n.find('input.fr-link-attr[type="checkbox"]')
(e = m(r[t])).is(":checked") ? s[e.attr("name")] = e.data("checked") : s[e.attr("name")] = e.data("unchecked") || null;
---- e should be a checkbox
e.attr("name") ---> 'target'
```

in the bundle:
```
o[i.attr("name")] = (i = t(s[r])).is(":checked") ? i.data("checked") : i.data("unchecked") || null;
---- i is a input.fr-link-attr[type="text"]
i.attr("name") ---> 'text' 
```

I updated it to this to keep the original logic:
```
{var e = m(r[t]); e.is(":checked") ? s[e.attr("name")] = e.data("checked") : s[e.attr("name")] = e.data("unchecked") || null;}
```

**Comment by CrazyKodoG** [comment]
hmm... got the same issue on v2.9.6.
After so many years, I guess I found the line causing this.
seems it was caused by one line in link.min.js

`(e=m(r[t])).is(":checked")?s[e.attr("name")]=e.data("checked"):s[e.attr("name")]=e.data("unchecked")||null;`
will be convert to this line in the bundle
`o[i.attr("name")] = (i = t(s[r])).is(":checked") ? i.data("checked") : i.data("unchecked") || null;`

in the original line
```
---- r = n.find('input.fr-link-attr[type="checkbox"]')
(e = m(r[t])).is(":checked") ? s[e.attr("name")] = e.data("checked") : s[e.attr("name")] = e.data("unchecked") || null;
---- e should be a checkbox
e.attr("name") ---> 'target'
```

in the bundle, there is already an i which has an input element before assigning the checkbox to it:
```
i = t(f[r]), ---- i in previous for loop, could be an input
   ["href", "text"].indexOf(i.attr("name")) < 0 && (o[i.attr("name")] = i.val());
   for (r = 0; r < s.length; r++)
       o[i.attr("name")] = (i = t(s[r])).is(":checked") ? i.data("checked") : i.data("unchecked") || null;
---- i is a input.fr-link-attr[type="text"] at this stage until i = t(s[r])
i.attr("name") ---> 'text'   AFTER  _i = t(s[r])_  i.data("checked")  --->'_blank'
```
![image](https://github.com/froala/wysiwyg-editor/assets/142093127/51d3f44c-34c5-4115-92fc-acefe9ea217d)


I updated it to this to keep the original logic:
```
{var e = m(r[t]); e.is(":checked") ? s[e.attr("name")] = e.data("checked") : s[e.attr("name")] = e.data("unchecked") || null;}
```
