### ISSUE TITLE
Default font not applied while typing 

### ISSUE THREAD

**Issue by ShanmugaPriyanV** [froala/wysiwyg-editor#3375]
Froala editor is set to default font of Arial 14. But when a word is typed and code view is clicked, the font is not being applied.To fix this, I have tried keyup event, getting the value from editor for every key press,applying style and giving back to editor as editor.html.insert().But for every keyup event,value of the key pressed is getting inserted in new line . Also when I type, certain keys like Backspace,Shift,Ctrl etc the respective values are being inserted into editor like “Backspace “, “Enter” etc.
Is there any other way to get the default font “Arial 14” when the content is typed? or
Can you suggest something to fix the above issues I’m facing?

**Comment by stefanneculai** [comment]
@ShanmugaPriyanV please use the approach described on https://wysiwyg-editor.froala.help/hc/en-us/articles/115000817105-How-can-I-set-a-default-font-style-.
