### ISSUE TITLE
fullscreen mode breaks layout in Firefox

### ISSUE THREAD

**Issue by sumancholleti** [froala/wysiwyg-editor#3377]
As soon as we exit  fullscreen the screen layout breaks as it still keeps margin 0 

##### Expected behavior.
Layout should revert when exiting fullscreen

##### Actual behavior.
It keeps margin 0 

##### Steps to reproduce the problem.
Click on fullscreen and exit from it

##### OS.
(OS name and version here)

##### Browser.
Firefox

##### Recording.
(A recording showing how to reproduce the problem)

**Comment by ilyaskarim** [comment]
Hi Suman, What version of firefox are you using?

**Comment by sumancholleti** [comment]
FF 66

**Comment by sumancholleti** [comment]
I tried latest version 2.9.4 and it didn't work.

**Comment by stefanneculai** [comment]
@sumancholleti could you please provide more details on that? Are you able to reproduce this on our website?

**Comment by sumancholleti** [comment]
Looks like its fixed in latest version , Thanks
