### ISSUE TITLE
option to disable sanitizing

### ISSUE THREAD

**Issue by dolphinsd** [froala/wysiwyg-editor#3378]
with html ever evolving, you tags are out of date.

i want to disable html sanitizing when user uses code view!

**Comment by ilyaskarim** [comment]
We use this channel to receive bugs updates. Please check our roadmap: https://wysiwyg-editor-roadmap.froala.com/public.

**Comment by BugKiller-tech** [comment]
@dolphinsd  did you resolve this issue?
I'm using froala in vue.js. when I add html string to the editor, editor cause the error (in console), and html is not saved in editor.

**Comment by shweta18** [comment]
Has anyone found a solution to this? I am facing the same issue
