### ISSUE TITLE
Froala does not support UTF-8?

### ISSUE THREAD

**Issue by viniciuskoerich** [froala/wysiwyg-editor#3379]
When typing "Vinícius êmé ação" in the Froala editor panel, when I see the code view in html, everything is not in UTF-8.

This has caused a problem sending information to the server. Is it possible to turn the Froala editor into UTF-8 so that I can correctly send the information to the PHP server ($_POST)?

##### Expected behavior.
`<p>Vinícius ême ação</p>`

##### Actual behavior.
`<p>Vin&iacute;cius &ecirc;me a&ccedil;&atilde;o</p>`

##### OS.
Windows 10

##### Browser.
Chrome 73.0.3683.86 (64 bits)

**Comment by viniciuskoerich** [comment]
I already figured out what the problem was.

The `pkgd.js` of the Froala editor comes with an Entities plugin. The solution is to disregard `pkgd.js` and append the plugins only the required via "pluginsEnabled" option. Example:

```
$('.selector').froalaEditor({
  pluginsEnabled: ['image', 'link', etc]
});
```

Link about `pluginsEnabled`: https://www.froala.com/wysiwyg-editor/docs/options#pluginsEnabled

**Comment by kjmtrue** [comment]
I have same problem, this is my solution:

```
$('.selector').froalaEditor({
  entities: ''
});
```
