### ISSUE TITLE
Add Image Caption Dynamically

### ISSUE THREAD

**Issue by rolfo85** [froala/wysiwyg-editor#3380]
Hi,

I would like to pass the image caption in the return response object after having uploaded an image with the Froala editor. Something like:

    return response()->json([
        "link" => "/storage/rte-images/" . $cleanedFilenameWithExtension,
        "image_caption" => $caption
    ]);

or hook to some events such as image.uploaded and pass the caption to the image that I have just uploaded.

Do you know if one of these things is possible or if there is a better way to achieve that?

Thanks in advance!

**Comment by stefanneculai** [comment]
We don't have such a method built-in, though, you could be using the image.inserted event: https://www.froala.com/wysiwyg-editor/docs/events#image.inserted.

**Comment by rolfo85** [comment]
Thanks,

But then how can I add the actual caption?
Cause if I just manipulate the DOM adding a <div> beneath the image, that wouldn’t be like clicking on the caption icon on the image.

**Comment by stefanneculai** [comment]
For that, you could be using the `image.toggleCaption` method which adds caption to the image.

**Comment by rolfo85** [comment]
thanks but I don't see `image.toggleCaption` in your documentation. So I don't know what arguments accept it. Can you write an example?
I'm using Vue Froala.

**Comment by stefanneculai** [comment]
It doesn't get any params. It just adds the required structure.

**Comment by rolfo85** [comment]
Sorry I'm a dumb in programming. Can you write a simple example on how I could use it?
Thanks

**Comment by Spoowy** [comment]
@rolfo85 this works:
```
editor
            .on('froalaEditor.image.inserted', function(e, editor, image) {
                if ($(image).next().hasClass('fr-inner')) {
                    $(image).next().html("This is the new caption");
                } else {
                    setTimeout(function() {
                        editor.image.toggleCaption();
                        $(image).next().html("This is the new caption");
                    }, 300);
                }
            })
            .froalaEditor();
```

You can get the text to be replaced from the $(image).attr('data-caption') if you set a caption attribute on insert.

```
$('.selector').froalaEditor('image.insert', '/uploads/13451.jpg', true, {'name': 'image_name', 'id': 'image_1', caption: 'New caption'}, $('#my_image'), {link: 'http://example.com/file.pdf'});
```

Cheers,
Erwin
