### ISSUE TITLE
"Powered by Froala Editor"

### ISSUE THREAD

**Issue by rtarnaud** [froala/wysiwyg-editor#3381]
Why do I have this message displayed exactly???

**Comment by stefanneculai** [comment]
Please make sure that you use a licensed version of the Froala Editor.

**Comment by rtarnaud** [comment]
I am using a licensed version, that's the problem!

**Comment by stefanneculai** [comment]
Please reach us on https://www.froala.com/wysiwyg-editor/contact. Thanks.

**Comment by meiordac** [comment]
Have the same issue while using IE, is it somehow an IE specific issue?

**Comment by dejanmartinovic** [comment]
You can remove the "Powered by Froala" message by turning off following option as shown here: https://www.froala.com/wysiwyg-editor/docs/options#attribution. Thanks

**Comment by maiaraborges** [comment]
I have the same problem.

**Comment by BrianHHough** [comment]
Confirming I have the same issue as well on the `FroalaEditorView` component. It seems like there isn't a way to pass in a key into the config of this?
