### ISSUE TITLE
Button tag on click opens edit toldbar

### ISSUE THREAD

**Issue by jgomesmv** [froala/wysiwyg-editor#3383]
##### Expected behavior.
When clicking on a button tag the popup toldbar should not appear.
I tried to find a proper API option to configure this, but none have worked

##### Actual behavior.
When clicking on a button tag the popup toldbar is shown

##### Steps to reproduce the problem.
On code view mode, insert a button tag like:
<button style="height:25px;background-color:#00BA7C;padding: 20px;border-radius: 15px;" type="button">Button</button>
Click on the button and the edit button popup toldbar is shown

##### OS.
Windows 10

##### Browser.
Chrome  73.0.3683.103

##### Recording.
![image](https://user-images.githubusercontent.com/8100887/55961834-9c966680-5c67-11e9-8c4b-60c3e7676cdc.png)

**Comment by stefanneculai** [comment]
Please do not include the forms plugin JS file or remove it from `pluginsEnabled` option.
