### ISSUE TITLE
Default Font style not applied for code view.

### ISSUE THREAD

**Issue by ShanmugaPriyanV** [froala/wysiwyg-editor#3385]
Thanks for you reply regarding the issue #3375.
We have been already using fr-view for default font style and size.Its only working for look and feel.My requirement is the default font style should actually be applied to the paragraph tag when I type something.
When I type something and click on code view button, a plain paragraph tag with the typed text is appearing. It should actually have the default style because we need to send emails with this content.
Please help in this regard.

**Comment by stefanneculai** [comment]
@ShanmugaPriyanV the approach described on #3375 is designed to apply CSS at the level the editor is being used. When you send an email, you should be adding the rules added for styling in a `STYLE` tag in the `HEAD` section of the html.
