### ISSUE TITLE
Selected text overflows the editor container on iOS

### ISSUE THREAD

**Issue by sergiolorente** [froala/wysiwyg-editor#3388]
##### Expected behavior.
Selected text should only be visible inside the editor container.

##### Actual behavior.
Selected text overflows the editor container on iOS. 

##### Steps to reproduce the problem.
Open this url from IOS device and try to write  text until the scrollbar appears. 
After that select all text and you could see how the selection overflows the container.

https://www.froala.com/wysiwyg-editor/examples/predefined-height

![imagen](https://user-images.githubusercontent.com/41376483/56133733-776a6680-5f8d-11e9-9237-bfffe97528e0.png)
![imagen](https://user-images.githubusercontent.com/41376483/56134508-0461ef80-5f8f-11e9-8abc-5cbb7b988955.png)

**Comment by stefanneculai** [comment]
Unfortunately, it's an iOS issue. We've reported it to Apple around 3 years ago, though there is no fix yet. :(
