### ISSUE TITLE
Colors: Switching tabs does not work with option colorsDefaultTab: 'background'

### ISSUE THREAD

**Issue by rogersteblerbsi** [froala/wysiwyg-editor#3389]
Assumption: Option `colorsDefaultTab` is set to `background`

##### Expected behavior.
When clicking on the 'Colors' button the tab 'Background' is selected. You can switch between the tabs 'Text' and 'Background'.

##### Actual behavior.
After switching to the 'Text' tab you cannot switch back to the 'Background' tab. Clicking on the tab does nothing.

##### Steps to reproduce the problem.
Go to https://jsfiddle.net/0f6tmpLy/
Click the 'Colors' button. Select the 'Text' tab. Switching back to the 'Background' tab does not work.

##### OS.
Windows 7

##### Browser.
Chrome 73.0.3683.103

**Comment by bostondevin** [comment]
Clicking on anything in the colors panel doesn't work for me any longer
