### ISSUE TITLE
Firefox bug in formatting selection

### ISSUE THREAD

**Issue by jhon100** [froala/wysiwyg-editor#3390]
In firefox when having a line (hr) between two paragraphs, selecting them to apply a style (bold, italic, color), the style is applied only to the first paragraph.

The behaviour can be checked in this fiddle, select the two first paragraphs and try to apply a style:
https://jsfiddle.net/6tskuoxp/1/

It also occurs if you select manually all the text but not occur if you select all the text with the toolbar button 'Select All'

##### OS.
Windows 10

##### Browser.
Firefox 65.0.1

**Comment by navneetnagpal** [comment]
Fixed and pushed in v2 branch
