### ISSUE TITLE
Copy multiple pictures from a Word document and upload them

### ISSUE THREAD

**Issue by xiaoshuzai** [froala/wysiwyg-editor#3391]
I recently learned about clipboardData related API content and found that when copying a single picture in a Word document, I was able to get the file type in files format through the getAsFile method in DataTransfer.itmes, but if you copied multiple copies from Word Picture, it all turns into a text/plain or text/html format. My friend told me that the Froala editor has this feature, so I'd like to ask you how you got the file format from the Clipboard content copied from the Word document so that I could upload the image through the Ajax method.

Can you tell me the mysteries?

**Comment by xiaoshuzai** [comment]
I found it today,thanks

**Comment by ilyaskarim** [comment]
Hi Shuzai. I am glad that you fixed the problem.
