### ISSUE TITLE
Creating Empty div with inline style and inserting one br tag

### ISSUE THREAD

**Issue by paras-deshbhratar** [froala/wysiwyg-editor#3392]
##### Expected behavior.
Should not create empty div

##### Actual behavior.
when the cursor is before or after image, when you press enter, froala editor creating empty div with inline styles and inserting one 'br' tag
It is creating as many div as many time you press enter.

##### Steps to reproduce the problem.
(Describe the steps to reproduce the problem here. A [jsFiddle]
https://jsfiddle.net/paras_d13/4s96owep/
##### OS.
Ubuntu 14.04.6

##### Browser.
google chrome

**Comment by ilyaskarim** [comment]
Bug also produced in this jsFiddle https://jsfiddle.net/L1wqyo6v/1/.

**Comment by paras-deshbhratar** [comment]
Its resolved. Thanks!
