### ISSUE TITLE
How to disable reset in Froala for Angular

### ISSUE THREAD

**Issue by nidhin038** [froala/wysiwyg-editor#3394]
I just need to disable resizing after image upload. Saw the below line of code 

**$('div#froala-editor').off('froalaEditor.image.resize');**

But how can this be given in an angular code ?

The below code is getting triggered on resizing
**'froalaEditor.image.resize':function (e, editor, link) { }**

But how can this be unset ?

**Comment by ilyaskarim** [comment]
Please find the documentation here at https://www.froala.com/wysiwyg-editor/docs/framework-plugins/angularjs-2-4. Please see section Extend functionality.
