### ISSUE TITLE
Cursor is not shown on Froala editor

### ISSUE THREAD

**Issue by javeriaanwer** [froala/wysiwyg-editor#3397]
1. Initialize Froala Editor with height option.
2. Insert image.
3. Click inside the editor.

you will notice that cursor is not appear until you click at the bottom-left of froala editor. 

here it's [jsFiddle](https://jsfiddle.net/froala/ojwhvppr/323/)

![ezgif com-video-to-gif (21)](https://user-images.githubusercontent.com/25203829/56658551-53f19b00-66b4-11e9-8750-cc5efca4a5e1.gif)

**Comment by ilyaskarim** [comment]
Hi Javeria,

I need more details about your issue. Can you please explain more about your issue in detail?

Best,
Ilyas Karim

**Comment by javeriaanwer** [comment]
Hi Ilyas,

the problem is that when I click on froala editor after inserting an image, cursor is not appearing. 

**Expected scenario:** cursor should get visible when clicking on froala editor.

I have already attached gif in previous comment. 

here is the code:

`$('div#froala-editor').froalaEditor({
 height: 400,
  iframeStyleFiles: ['https://cdn.jsdelivr.net/npm/froala-editor@2.9.5/css/froala_style.min.css']
});`

you can reproduce it [here](https://jsfiddle.net/rymaezjx/1/)

What details do you want? I am using Chrome Version 74.0.3729.108 (Official Build) (64-bit) and Windows 10.
