### ISSUE TITLE
Meta, title, comments, and everything else being removed from head tag

### ISSUE THREAD

**Issue by drewkiimon** [froala/wysiwyg-editor#3398]
##### Expected behavior.
I expected all the tags to stay in the head and not be removed/stripped away.

##### Actual behavior.
Right now, when I edit the text it goes from 

```
<head>
    <title>Potatoes R' Us</title>
    <!-- A sneaky little comment -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
</head>
```

to this after I edit text at all

```<head><title></title></head>```.

This is my current config using `"froala-editor": "2.7.5"`:

```
$('#froala-editor').froalaEditor({
    htmlUntouched: true,
    htmlAllowedTags: ['.*'],
    htmlAllowedAttrs: ['.*'],
    htmlAllowedStyleProps: ['.*'],
    htmlRemoveTags: [],
    htmlAllowComments: true,
    iframe: true,
    fullPage: true
});
```

Any help here? Using Chrome and Mac OS

**Comment by ilyaskarim** [comment]
Hi Andrew,

Without reproducing the issue on my side it is hard to help you. Do you think it would be possible to make a jsFiddle to highlight the problem? That would speed-up things a lot. Here is a basic jsFiddle you could use as a starting point: https://jsfiddle.net/froala/wc5c3jhk/.

Please let me know if there is anything else I can assist you with or if you have any questions.

Best,
Ilyas Karim

**Comment by stefanneculai** [comment]
It is working just fine on https://jsfiddle.net/froala/wc5c3jhk/2219/.
