### ISSUE TITLE
Line breaks in <pre> are not retained when saving

### ISSUE THREAD

**Issue by rwaters71** [froala/wysiwyg-editor#340]
If you use the Format Block --> [code] menu, there is no way to have it retain multiple lines. There are two problems I see:

1) hitting ENTER (carriage return)  breaks the `<pre>` in two separate blocks. It seems wrong to create another block.

2)using CTRL+Enter (line feed)  seems to work for multiple lines, however, after saving line breaks are ignored and everything appears as a single line.

There should be a way to retain line feeds inside `<pre>` blocks (and other block elements, like lists?)because they matter to presentation imho.

**Comment by rwaters71** [comment]
Line breaks in <pre> blocks are not retained after saving in 1.2.7 for me either.

**Comment by stefanneculai** [comment]
I can't reproduce this. Could you please make a jsFiddle for it?

**Comment by rwaters71** [comment]
Actually, in newer versions the CRLF line breaks are saved correctly. They are also shown correctly while editing (if you insert <pre> element with breaks in the current editor). 

However, the issue occurs if you open saved content. if you open saved code with line breaks wrapped in a ```<pre>```, all line breaks are collapsed into (and displayed as) single lines by Froala. The html source shows the line breaks, but not the editor. This only occurs if you open code saved previously, so I don't think a jsfiddle can display it.

**Comment by magisters-org** [comment]
Have the same problem to.

**Comment by marriedgeek** [comment]
Same problem as well.

**Comment by stefanneculai** [comment]
@rwaters71 @magisters-org @marriedgeek could any of you create a JSFiddle where to replicate it? Thanks in advance.

**Comment by KenStipek** [comment]
I am also having this issue
