### ISSUE TITLE
Layout disturb when change the size of image and open the image resize option again

### ISSUE THREAD

**Issue by javeriaanwer** [froala/wysiwyg-editor#3400]
1. Initialize froala editor.
2. Insert image.
3. Change size of Image.

You will notice a scroll bar is appeared.

here is [jsFiddle](https://jsfiddle.net/eyvspd54/)

![ezgif com-video-to-gif (23)](https://user-images.githubusercontent.com/25203829/56714034-02491f00-674d-11e9-9229-3ae913955bf7.gif)

**Comment by javeriaanwer** [comment]
or if I add image in the end of froala editor then scroll bar appears and popup is vanished.

![ezgif com-video-to-gif (24)](https://user-images.githubusercontent.com/25203829/56715971-91a50100-6752-11e9-8c30-0bfcb418ab2b.gif)

**Comment by stefanneculai** [comment]
That scrollbar appears because the popup for the image doesn't have enough space on the container for the editor.
