### ISSUE TITLE
Infinite upload when pasting larger image

### ISSUE THREAD

**Issue by jaza089** [froala/wysiwyg-editor#3407]
##### Expected behavior.
Direct copy and paste of an image is possible (even when it is 5MB). As an alternative, a user friendly message if the image is too big to upload for any reason. 

##### Actual behavior.
Infinite "Uploading" box is displayed

##### Steps to reproduce the problem.
Thankfully this can be easily reproduced even on the Froala demo system.
1. Go to this URL with an example pic: https://upload.wikimedia.org/wikipedia/commons/6/66/Mercedes-Benz_GLK_220_CDI_4MATIC_Sport-Paket_AMG_%28X_204%2C_Facelift%29_%E2%80%93_Frontansicht%2C_24._August_2014%2C_D%C3%BCsseldorf.jpg

2. Right-click and copy the picture to the clipboard
3. Go to https://www.froala.com/wysiwyg-editor and paste the pic (CTRL-V) into the editor
4. You will get an infinite loading bar

Smaller pics (around 1MB) work without any problem

##### OS.
Mac OS 10.14.3.

##### Browser.
Reproduced on both Chrome (73.0.3683.103) and Firefox (66.0.3)

##### Recording.
Not necessary I think, I can provide it on request

**Comment by jtconsol** [comment]
IE11 is also affected in the same way
