### ISSUE TITLE
Cursor jumping between contenteditable elements

### ISSUE THREAD

**Issue by flodlc** [froala/wysiwyg-editor#3408]
##### Expected behavior.
The same behaviour than in an element with contenteditable=true without Fraoala activated:
When Froala is not activated, I can't delete an editable element, I can't jump with the arrow keys from this element to the next one neither. An option to disable the Froala deleting / jumping logic for the elements with contenteditable = "true" would help a lot to keep the structure of the document. Obviously, the elements nested in these elements should still be deletable.

##### Actual behavior.
I'm using Froala in a contenteditable = false context and I make some elements of the page editable by setting contenteditable = true. When I delete all the characters from an element, I am currently able to delete this element and the arrow keys allow me to jump between elements which make the behaviour on the page not user friendly.
##### Steps to reproduce the problem.
1. Insert this two elements in a Froala view:
````
<div contenteditable="false">
  <div contenteditable="true"></div> 
  <div contenteditable="true"></div>
</div>
````
2. Delete the content of the second one till the element is deleted itself.

##### OS.
MacOs
##### Browser.
Chrome

**Comment by stefanneculai** [comment]
We have some known problems when working with such a nested structure and we're planning on working towards providing an alternative. I am closing this for now, but please know that this is in our attention with quite high priority.
