### ISSUE TITLE
insert image can set any width .

### ISSUE THREAD

**Issue by zhaoyouliang** [froala/wysiwyg-editor#3409]
##### Expected behavior.
(Describe expected behaviour here)
My froala editor is in the dialog box.Now I want to be able to zoom in to any size for the  insert  image.The text editor then comes up with a horizontal scroll bar to fit the width.Is there a way to do that ?
##### Actual behavior.
(Describe actual behaviour here)
the image only support window size.
##### Steps to reproduce the problem.
(Describe the steps to reproduce the problem here. A [jsFiddle](https://jsfiddle.net/froala/wc5c3jhk/) is awesome when possible.)
1.insert a image
2.set width = 2000px 
##### OS.
(OS name and version here)
"angular-froala-wysiwyg": "^2.9.1",
##### Browser.
(Browser name an version here)
chrome
##### Recording.
(A recording showing how to reproduce the problem)

**Comment by stefanneculai** [comment]
By default, the editor has some CSS rules that prevent images to go beyond the width of the editable area. If you would like to override that, you can add the following CSS rule:

```CSS
.fr-view img {
  max-width: initial !important;
}
```
