### ISSUE TITLE
Froala 2.9.1 is inserting "nbsp;" spaces inside my html

### ISSUE THREAD

**Issue by zhaoyouliang** [froala/wysiwyg-editor#3410]
##### Expected behavior.
(Describe expected behaviour here)
a html from email and  display in forala body . it work fine in web browser .but  it has some specific tag like ("&nbsp <br>")
##### Actual behavior.
(Describe actual behaviour here)

##### Steps to reproduce the problem.
(Describe the steps to reproduce the problem here. A [jsFiddle](https://jsfiddle.net/froala/wc5c3jhk/) is awesome when possible.)

##### OS.
(OS name and version here)
 "angular-froala-wysiwyg": "^2.9.1",
##### Browser.
(Browser name an version here)
ipad safari
##### Recording.
(A recording showing how to reproduce the problem)

**Comment by ilyaskarim** [comment]
Do you think it would be possible to make a jsFiddle to highlight the problem? That would speed-up things a lot. Here is a basic jsFiddle you could use as a starting point: https://jsfiddle.net/froala/wc5c3jhk/.

**Comment by stefanneculai** [comment]
@zhaoyouliang could you please provide more details? Maybe a jsFiddle?

**Comment by navneetnagpal** [comment]
@zhaoyouliang or you can try the latest version 2.9.5 or v3.0.0.

**Comment by casualuser** [comment]
@zhaoyouliang please check latest 2.9.6 or 3.0.1 versions
if the issue still persists then provide clear info about how to reproduce it
for Angular sample project, you can use https://stackblitz.com
