### ISSUE TITLE
Selection.save should not overwrite existing selection markers with selection at end of text if selection range is outside Froala

### ISSUE THREAD

**Issue by jmiserez** [froala/wysiwyg-editor#3418]
When there are selection markers (selection.save was called) and selection.save is called while the cursor is outside of Froala, the existing selection markers are erased and a new selection is saved at the very end of the text.

See the jsFiddle for a demonstration of the issue, and an example of why this is an issue when called selection.save multiple times and onBlur/onFocusout in IE 11.

The onBlur/onFocusout example is similar to [issue #1533](https://github.com/froala/wysiwyg-editor/issues/1533), and the solution there (checking selection.inEditor) works here too. However, this issue is more specific and applies to all browsers: Froala should not replace existing valid markers if there is no new valid selection range inside the editor.

#####  Expected behavior.
- When selection.inEditor is false, existing saved selections should not be overwritten with an incorrect selection at the end of the text.

##### Actual behavior.
- When selection.inEditor is false, existing saved selections are overwritten with an incorrect selection at the end of the text.

##### Steps to reproduce the problem.
1. Open [jsFiddle](https://jsfiddle.net/y3zwkefp/7/)
2. Save a selection using the toolbar button.
3. Put cursor outside Froala
4. Call selection.save via the API.
5. The saved selection is overwritten and replaced with a selection at the end.
6. Also try the real-world example below in IE11.

##### Froala Version.
Froala v2.9.5

##### OS.
Windows 7 64bit 

##### Browser.
Chrome 74.0.3729.131 and IE 11.0.9600.19326

##### Recording.
![froala-selection-save-outside-editor-bug3](https://user-images.githubusercontent.com/5045692/57297469-f3108c80-70cf-11e9-9694-cd6378d047a5.gif)

**Comment by stefanneculai** [comment]
I would recommend using the `core.hasFocus` method to see if selection is inside the editor. The selection.save works this away because we have some internal methods that use this even when the editor doesn't have focus.

**Comment by jmiserez** [comment]
> I would recommend using the `core.hasFocus` method to see if selection is inside the editor.

Thanks for the tip, and good to know it's not a bug!

FYI: `hasFocus` seems to always be false onBlur on IE/Chrome, while selection.inEditor is only false in IE11, and only in the case of clicking into another input field. As I want to save the selection on blur, I think I'll stick to `selection.inEditor` rather than `core.hasFocus`.
