### ISSUE TITLE
Slow performance when amount of text is large

### ISSUE THREAD

**Issue by jrust** [froala/wysiwyg-editor#3420]
##### Expected behavior.
That it be snappy to write text, even if there are several thousand lines of text.  This was described several years ago in #582 and was recorded as fixed in 2.x, but I'm still seeing the problem.

##### Actual behavior.
After a few thousand lines it starts to become sluggish and a noticeable delay is detected when typing text.  I looked at the performance profile in Chrome and the keypress event handler is taking 280ms for each character.

##### Steps to reproduce the problem.
Paste a large amount of text into the latest Froala editor and then start typing and notice the lag. For my test I'm using the [Bee movie script](http://www.script-o-rama.com/movie_scripts/a1/bee-movie-script-transcript-seinfeld.html) which isn't that big (only 4k lines). 

##### OS.
Windows 10

##### Browser.
Chrome 73

**Comment by navneetnagpal** [comment]
@jrust Are you using editor with CodeMirror plugin? If yes can you give a try without CodeMirror plugin.

**Comment by jrust** [comment]
No, not using CodeMirror.  Here's a fiddle with CodeMirror explicitly off and you can see the issue by pasting in a large amount of text: https://jsfiddle.net/s95q62ad/1/

**Comment by stefanneculai** [comment]
@jrust could you please send us a recording and the text that you're pasting?

**Comment by jrust** [comment]
I've recorded it using the fiddle and the bee movie linked in the description: https://www.dropbox.com/s/zdb3o5f2u4hxwv7/typing-froala-slow.flv?dl=0

**Comment by jrust** [comment]
I just tested in the new Froala 3 and the performance problem when there's a large amount of text is fixed.  Nice work!
