### ISSUE TITLE
Font awesome 5 plugin support

### ISSUE THREAD

**Issue by kwasnicki** [froala/wysiwyg-editor#3421]
##### Expected behavior.
Using the Font awesome Flag icon in the toolbar have Font awesome 5 icons supported in the editor content.

(Note: this is not about supporting font awesome 5 icons in the toolbar which works. This is for the 3rd party plugin to support FA5 icons in the content)

##### Actual behavior.
Currently only Font awesome 4 icons appear to be supported. 

##### Steps to reproduce the problem.
Using the plugin with the font-awesome 5 css library yields many of the icons broken:'
https://jsfiddle.net/atw9yxqh/1/

##### OS.
All

##### Browser.
All

**Comment by stefanneculai** [comment]
We're using this repo mainly for bug tracking. Could you please open a ticket on https://wysiwyg-editor-roadmap.froala.com/public instead?
