### ISSUE TITLE
Documentation for custom plugin event handling is incorrect

### ISSUE THREAD

**Issue by grantcox** [froala/wysiwyg-editor#3422]
##### Expected behavior.
As per the documentation at https://www.froala.com/wysiwyg-editor/docs/concepts/custom/plugin, I expect this custom plugin to catch the "contentChanged" event:
```javascript
    $.FroalaEditor.PLUGINS.testEventHandlingPlugin = function (editor) {
        function _init () {
            editor.events.add('contentChanged', function (params) {
```

##### Actual behavior.
`Uncaught TypeError: editor.events.add is not a function`

Changing the code this does work:
```javascript
    $.FroalaEditor.PLUGINS.testEventHandlingPlugin = function (editor) {
        function _init () {
            editor.$oel.on('froalaEditor.contentChanged', function (e, editor) {
```

##### Steps to reproduce the problem.
JSFiddle here: https://jsfiddle.net/x3mwqeay/
Code:
```javascript
(function ($) {
    $.FroalaEditor.PLUGINS.testEventHandlingPlugin = function (editor) {
        function _init () {
            // as documented, this does not work
            editor.events.add('contentChanged', function (params) {
                console.log('testEventHandlingPlugin events.add(contentChanged)');
            });
            
            // however, this does work:
            editor.$oel.on('froalaEditor.contentChanged', function (e, editor) {
                console.log('testEventHandlingPlugin $oel.on(froalaEditor.contentChanged)');
            });
        }
        return {
            _init: _init
        }
    }
})(jQuery);

$('#froala-editor').froalaEditor({});
```

##### OS.
MacOS 10.14.4

##### Browser.
Chrome 74.0.3729.131

**Comment by christophedebatz** [comment]
Same problem, difficult to subscribe to froala hooks from a plugin configuration. Can you advise for a good solution?

**Comment by tovitch** [comment]
Hi,

You can simply replace the `add` method by `on` like the following :

```javascript
editor.events.on('contentChanged', function (/* no params here */) {
    console.log('testEventHandlingPlugin events.on(contentChanged)');
});
```

**Comment by AdityaPawar2** [comment]
ckeditorEvent.events.trigger("media-attached",mediaModel); I am triggering the event here

this.editor.events.on('media-attached', function (mediaModel) {
            console.log('Media attached:', mediaModel);
          });

When I receive it here, mediaModel is null. Am I doing something wrong ?

**Comment by AdityaPawar2** [comment]
ckeditorEvent is fraola editor only, I haven't renamed it yet

**Comment by AdityaPawar2** [comment]
medial model is printed just above where I am triggering the event
