### ISSUE TITLE
IE - When drag-drop file, download file popup showed

### ISSUE THREAD

**Issue by ahmadsyamim** [froala/wysiwyg-editor#3423]
##### Expected behavior.
When drag-drop file, file uploaded (Chrome No Problem)

##### Actual behavior.
When drag-drop file, download file popup showed
[https://pasteboard.co/Ie0RN15.png](url)

##### Steps to reproduce the problem.
-

##### OS.
Windows 7

##### Browser.
IE11

**Comment by stefanneculai** [comment]
@ahmadsyamim could you please send us the file that you're trying to drag&drop and not working?

**Comment by ahmadsyamim** [comment]
@stefanneculai any file. It will popup as Save As Dialog.

**Comment by navneetnagpal** [comment]
@ahmadsyamim can you send us recording or jsFiddle?
