### ISSUE TITLE
Allow configuration of popup direction.

### ISSUE THREAD

**Issue by timavaza** [froala/wysiwyg-editor#3424]
Froala allows setting the toolbar to the bottom of the editor, but it doesn't allow you to set the direction of the popups. 
So we are forced to have popups opening upwards, which then go off the screen (as the control is by necessity near the top of the screen).

Please allow configuring the popup direction. 

Note: There's a trend for Editor toolbars to only become visible on focus to keep UIs clean.. and to have toolbars at the bottom so the mouse position doesn't jump. This is common behaviour now even if the control is near the top of the page.
Froala needs to be designed to have flexibility, so the control can be placed anywhere on the screen elegantly.

**Comment by stefanneculai** [comment]
@timavaza could you please open a feature request on our roadmap: https://wysiwyg-editor-roadmap.froala.com/public?
