### ISSUE TITLE
Froala sync

### ISSUE THREAD

**Issue by karellodewijk** [froala/wysiwyg-editor#3427]
In my setup users add images to a froala editor and submit. But quite often, they press submit before the image is all the way uploaded. 

The result is that the content contains sometng like <img src="blob:https://host/8069bc84-c958-47a1-9c99-3b3aa6195a1a" style="width: 300px;" class="fr-fic fr-dib fr-uploading">. And the image is not recoverable later.

I can probably fix this by setting a state on image.beforeUpload and waiting for image.beforeUpload or image.contentChanged to trigger, but this seems awfully specific to images.

So my question is, is there anyway to check if the froala content is fully synced ?

**Comment by stefanneculai** [comment]
@karellodewijk the approach you're suggesting is a correct one. Do you mind opening this as a feature request on https://wysiwyg-editor-roadmap.froala.com/public?
