### ISSUE TITLE
Want your team to support insert a video by iframe.

### ISSUE THREAD

**Issue by Yilia-Wish** [froala/wysiwyg-editor#3428]
we want to insert a video to this rich editor, but it is not able  to edit iframe's size. could you help to support it?

**Comment by Yilia-Wish** [comment]
we want to buy your product, is you can support it ,we will buy it .

**Comment by stefanneculai** [comment]
Could you please request it on our roadmap: https://wysiwyg-editor-roadmap.froala.com/public? Thanks in advance.
