### ISSUE TITLE
insert text in the editor in iframe

### ISSUE THREAD

**Issue by K-a-tech** [froala/wysiwyg-editor#3430]
hallo     
i used fr-view class to insert a text , i even used the fr-element class  but it not working 

 $('iframe').contents().find('.fr-view ').html("hhhhh");

is there any solution ?(thanks)

**Comment by navneetnagpal** [comment]
@K-a-tech Are you trying to set initial html? If yes you can use editorInstance.html.insert('hhhh') method to do the same thing rather than setting into dom directly.
