### ISSUE TITLE
FroalaEditor methods not available after instantiating

### ISSUE THREAD

**Issue by onhate** [froala/wysiwyg-editor#3433]
##### Expected behavior.
after instantiating FroalaEditor I would expect to access the methods of the editor in the instance just created.
```js
this.froala = new FroalaEditor(this.editor.nativeElement, this.options);
this.froala.html.set(this.value);
```

##### Actual behavior.
methods are not available in the instance.
```
ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'set' of undefined
TypeError: Cannot read property 'set' of undefined
```

When printing `Object.keys(this.editor)` those are the only keys I see
```
["id", "$", "opts", "sid", "shared", "$oel", "o_doc", "o_win", "c_scroll", "_original_html", "$box", "$el", "el", "$wp"]
```

##### Steps to reproduce the problem.
```
npm install --save froala-editor;
--
import FroalaEditor from 'froala-editor';

var editor = new FroalaEditor(...);
editor.html.set('value');
```

##### Editor version.
froala-editor: ^3.0.0-beta.1

**Comment by stefanneculai** [comment]
That is because the editor is not initialized yet at that moment. You should change it to:

```js
var editor = new FroalaEditor(this.editor.nativeElement, this.options, function () {
   editor.html.set(this.value);
});

**Comment by onhate** [comment]
Cool, I'll try it, but one point would be good to mention this in the docs for the methods section, they are all like this
```js
var editor = new FroalaEditor('.selector');
editor.align.apply('left');
```

https://www.froala.com/wysiwyg-editor/docs/events

**Comment by kevinhq** [comment]
> That is because the editor is not initialized yet at that moment. You should change it to:
> 
> ```js
> var editor = new FroalaEditor(this.editor.nativeElement, this.options, function () {
>    editor.html.set(this.value);
> });
> ```

Then, how to update HTML on ajax success function? Should we initialize the editor again? I think it's a common use-case to update the content of editor on ajax success

**Comment by kevinhq** [comment]
Updates:

Here is what works for us:

- Re-instantiation inside AJAX success: `var something = new FroalaEditor(...)`
- Call it using this syntax: `something.html.set(data);`

Though it's a bit weird because we need to do re-instantiation of the editor. Wondering if this is the correct way or maybe it's kind of hack?
