### ISSUE TITLE
Drop event not invoked

### ISSUE THREAD

**Issue by ekalchev** [froala/wysiwyg-editor#3435]
##### Expected behavior.
drop event to be invoked when you drop data object (html format) from outside the browser. draggable.js plugin is loaded

##### Actual behavior.
drop event is not invoked

##### Steps to reproduce the problem.
Just drag some html and drop inside the editor

##### Editor version.
3.0.0-beta1

##### OS.
Windows

##### Browser.
Chrome

If I subscribe for the drop event this way. It is never get invoked.

  ```
new FroalaEditor('.selector', {
   events: {
      'drop': function (dropEvent) {
       // Do something here.
       // this is the editor instance.
       console.log(this);
     })
   }
  });
```

This however works (it needs first:true argument):

           this.events.on('drop', function (e) {
                    return instance._drop(e);
           }, true);

This doesn't work.

          this.events.on('drop', function (e) {
                    return instance._drop(e);
           });

Note that I am dragging html from outside the browser and dropping it inside the Froala editor. When I debug draggable.js i can see that _drag function is invoked and e.originalEvent.dataTransfer has text/html format with the data I want but something is preventing my custom drop handler from invoking.

**Comment by stefanneculai** [comment]
For the drop event, it would be required to subscribe by passing the `true` event - that was happening in v2 too.

**Comment by gauravbnsl** [comment]
@stefanneculai / @ekalchev  can you please provide a working code snippet for using 'drop' event in Froala with Angular 2+?
This just doesn't seem to work for me.

**Comment by goodpilotfish** [comment]
@gauravbnsl: The subscription parameter being mentioned is the true seen bellow.
```
editor.events.on(
  "drop",
  () => {console.log("drop event");},
  true
);
```

Debugging:
- Try adding this event inside the froala initialized event
- Try triggering it by pulling in a document from outside the browser
