### ISSUE TITLE
javascript error in 3.0 beta

### ISSUE THREAD

**Issue by dolphinsd** [froala/wysiwyg-editor#3436]
Running the master demo of https://github.com/froala/angular-froala-wysiwyg produces javascript error:
froala_editor.pkgd.js:16156 Error: <path> attribute d: Expected moveto path command ('M' or 'm'), "undefined"
on this line:
after.insertAdjacentHTML('afterend', content);
in after: function after(content) {
...
}

**Comment by stefanneculai** [comment]
@dolphinsd is there a specific way to reproduce this?

**Comment by cauethenorio** [comment]
I had the same error, I had a custom icon with an `SVG_KEY` value which wasn't defined in `FroalaEditor.SVG` map.

**Comment by stefanneculai** [comment]
@dolphinsd @cauethenorio should be fixed now. Could you please check and confirm?

**Comment by casualuser** [comment]
fixed in 3.0.3
