### ISSUE TITLE
Image caption bug

### ISSUE THREAD

**Issue by largeden** [froala/wysiwyg-editor#3438]
##### Recording.
![caption](https://user-images.githubusercontent.com/5575931/58153605-6efefd00-7caa-11e9-9f95-e8505abdf1c2.gif)

##### Editor version.
Latest commit.

---

Congratulations!! :tada:
Everything is awesome!
Several bugs have been identified.
I will submit the issue separately.

**Comment by akki744** [comment]
@stefanneculai This issue is not reproducible on latest, might have gotten fixed in the last few commits.

**Comment by stefanneculai** [comment]
Fixed on master.
