### ISSUE TITLE
wysiwyg-editor bate 3

### ISSUE THREAD

**Issue by YingDreamyoung** [froala/wysiwyg-editor#3444]
![image](https://user-images.githubusercontent.com/20599819/58231688-29096e00-7d6a-11e9-9be7-084d8291c9ca.png)

**Comment by navneetnagpal** [comment]
Hi, Can you help us with more details like
1) Steps to reproduce the problem
2) Or may be jsFiddle to demonstrate the problem.

Thanks,
Navneet

**Comment by YingDreamyoung** [comment]
thanks ,maybe i got !
