### ISSUE TITLE
editor.html.get()

### ISSUE THREAD

**Issue by YingDreamyoung** [froala/wysiwyg-editor#3446]
### _If you have a feature suggestion, please add it on the [Feature List](https://wysiwyg-editor-roadmap.froala.com/public) instead._
![image](https://user-images.githubusercontent.com/20599819/58237758-74c31400-7d78-11e9-80ec-506557565006.png)
![image](https://user-images.githubusercontent.com/20599819/58237779-87d5e400-7d78-11e9-8de4-367ee17be79b.png)

##### Expected behavior.
(Describe expected behaviour here)
I want to get the html after  initializing the editor 

##### Actual behavior.
(Describe actual behaviour here)
when i get the html but error

##### Steps to reproduce the problem.
(Describe the steps to reproduce the problem here. A [jsFiddle](https://jsfiddle.net/froala/wc5c3jhk/) is awesome when possible.)

##### Editor version.
Release 3.0.0-beta.1

##### OS.
(OS name and version here)
windows10

##### Browser.
(Browser name an version here)
Google Chrome version 74.0.3729.157（正式版本） （32 bit）
##### Recording.
(A recording showing how to reproduce the problem)

**Comment by stefanneculai** [comment]
Demo here: https://jsfiddle.net/froala/a1bs6w9j/.

**Comment by YingDreamyoung** [comment]
> Demo here: https://jsfiddle.net/froala/a1bs6w9j/.
Thanks for your help, the first method i see, but i want use the way in other place,egg：
![image](https://user-images.githubusercontent.com/20599819/58299052-5b6da680-7e10-11e9-9de8-115663cba9a6.png)
 if so, i can get the html anywhere。I'm looking forward to your help。
