### ISSUE TITLE
editor.html.get()2222

### ISSUE THREAD

**Issue by YingDreamyoung** [froala/wysiwyg-editor#3448]
Thanks for your help, the first method i see, but i want use the way in other place,egg：
![image](https://user-images.githubusercontent.com/20599819/58303083-130ab480-7e21-11e9-9348-dacc36af5d1b.png)

if so, i can get the html anywhere。I'm looking forward to your help。
Expected behavior.
(Describe expected behaviour here)
I want to get the html after initializing the editor

Actual behavior.
(Describe actual behaviour here)
when i get the html but error

Steps to reproduce the problem.
(Describe the steps to reproduce the problem here. A jsFiddle is awesome when possible.)

Editor version.
Release 3.0.0-beta.1

OS.
(OS name and version here)
windows10

Browser.
(Browser name an version here)
Google Chrome version 74.0.3729.157（正式版本） （32 bit）

Recording.
(A recording showing how to reproduce the problem)

**Comment by stefanneculai** [comment]
Please see https://www.froala.com/wysiwyg-editor/examples/getHTML.
