### ISSUE TITLE
Difference between *.min.js & *.pkgd.min.js

### ISSUE THREAD

**Issue by pleunv** [froala/wysiwyg-editor#3450]
Hey guys!

Just a quick question, as I can't seem to find it anywhere:

I was going through the npm package and noticed there are 2 minified `froala-editor` files there with a substantial size difference:
* `froala_editor.min.js`
* `froala_editor.pkgd.min.js`

I was just wondering if you could clarify the difference between these? The docs only seem to mention usage of the `pkgd.min.js` file.

**Comment by stefanneculai** [comment]
`froala_editor.min.js` includes the editor core only, while `froala_editor.pkgd.min.js` includes core + all plugins.
