### ISSUE TITLE
Decided to Check out V3

### ISSUE THREAD

**Issue by Akkadius** [froala/wysiwyg-editor#3455]
Went to website, literally first thing I did was put my cursor at the end of the content and this happened

![2019-05-28 02 33 44](https://user-images.githubusercontent.com/3319450/58459536-3cf9fa80-80f1-11e9-83ce-68d1ec2e7e00.gif)

All that was used was arrow keys, backspace and enter

**Comment by stefanneculai** [comment]
It's fixed on master branch from Github.
