### ISSUE TITLE
Links should not be disabled when editor is disabled

### ISSUE THREAD

**Issue by phpfui** [froala/wysiwyg-editor#3457]
##### Expected behavior.
You should be able to click on links (<a href=) when editor is disabled when using the link plug in.

Fix is to remove lines 478-483 in froala\js\plugins\link.js

Not sure why this was added, as I don't have git history of un-minified version. Seems to work great with these lines removed.  Advanced editing still works.  Link is clickable when editing is turned off. My use case is I display the editable content with a nearby edit button. Area is editable only after hitting the edit button.  Otherwise it should work as normal, meaning you have to follow links.

##### Actual behavior.
Links are disabled if editor is disabled and the link plugin is used.

##### Steps to reproduce the problem.
Include link plugin.
$(function(){$("#editable").froalaEditor({whatever}).froalaEditor("edit.off")});
Links in editable area will not work

##### Editor version.
2.9.4

##### OS.
Windows 10

##### Browser.
Firefox and Chrome latest versions

##### Recording.
none

**Comment by Akitektuo** [comment]
This is still an issue, @phpfui do you remember what those lines did so I can remove them?
Our version is 3.2.6

**Comment by phpfui** [comment]
Your fix looks about right.  This is over 2 years old, and I have since trashed the repo that may have had my fix, and also switched over to TinyMCE, so not really involved with this project anymore.
