### ISSUE TITLE
Is it posible code view open on the modal/pup? Like as tinymce code view.

### ISSUE THREAD

**Issue by mdmasumbillah** [froala/wysiwyg-editor#3461]
Please see this and open code view mode.

https://codepen.io/masum-regfire/pen/earMEW

help me any idea

**Comment by navneetnagpal** [comment]
@mdmasumbillah sorry currently we don't have this feature as of now. Checkout our roadmap  here 
https://wysiwyg-editor-roadmap.froala.com/public see upcoming features and you can request features too.

**Comment by mdmasumbillah** [comment]
@navneetnagpal thank. I solved another system.
