### ISSUE TITLE
data attribute striped event i put to htmlAllowedAttrs

### ISSUE THREAD

**Issue by shadowvzs** [froala/wysiwyg-editor#3463]
##### Expected behavior.
i expected if i allow my data attributes then it stay there even after i use **.html.insert('....')**

##### Actual behavior.
data attributes removed from div even i added into **htmlAllowedAttrs list**

##### Steps to reproduce the problem.
(Describe the steps to reproduce the problem here. A [jsFiddle](https://jsfiddle.net/froala/wc5c3jhk/) is awesome when possible.)

##### Editor version.
tried both
2.6.0
2.9.1

##### OS.
any os

##### Browser.
Any browser

##### Recording.
```javascript
const mystr = `<div class="mceNonEditable video youtube" title="MARCHING ON- Rend Collective ft. Hillsong Young & Free (lyric video)" style="height: 270px; background-image: url('https://i.ytimg.com/vi/BCPhnSOHMS0/hqdefault.jpg');" data-url="https://www.youtube.com/watch?v=BCPhnSOHMS0" data-html="%3Cdiv%3E%3Cdiv%20style%3D%22left%3A%200%3B%20width%3A%20100%25%3B%20height%3A%200%3B%20position%3A%20relative%3B%20padding-bottom%3A%2074.9457%25%3B%22%3E%3Ciframe%20class%3D%22video%22%20src%3D%22https%3A%2F%2Fwww.youtube.com%2Fembed%2FBCPhnSOHMS0?feature%3Doembed%22%20style%3D%22border%3A%200%3B%20top%3A%200%3B%20left%3A%200%3B%20width%3A%20100%25%3B%20height%3A%20100%25%3B%20position%3A%20absolute%3B%22%20allowfullscreen%20scrolling%3D%22no%22%3E%3C%2Fiframe%3E%3C%2Fdiv%3E%3C%2Fdiv%3E" data-mce-contenteditable="false"><span class="blocker"></span></div>`;

this.html.insert(mystr);
```

and output is something like this:
(missing *data-url, data-html, data-mce-contenteditable*)

```html
<div class="mceNonEditable video youtube" style='height: 270px; background-image: url("https://i.ytimg.com/vi/BCPhnSOHMS0/hqdefault.jpg");' title="MARCHING ON- Rend Collective ft. Hillsong Young & Free (lyric video)"><span class="blocker"></span></div>
```

**Comment by navneetnagpal** [comment]
@shadowvzs I tried to reproduce but not able to here is jsFiddle https://jsfiddle.net/froala/59dutwmq/
or create new fiddle to demonstrate the problem.

**Comment by shadowvzs** [comment]
> 
> 
> @shadowvzs I tried to reproduce but not able to here is jsFiddle https://jsfiddle.net/froala/59dutwmq/
> or create new fiddle to demonstrate the problem.

it was in **2.x** version not on 3 and i added with _**.html.insert**_ (or when i switched the content view mode) and not directly...

### video: https://monosnap.com/file/M6tjEcseMeP3OqRUDrQ5izsGbHJ6sv
