### ISSUE TITLE
Blockquotes overlapping

### ISSUE THREAD

**Issue by manu-sparheld** [froala/wysiwyg-editor#3469]
Hi, I am trying to add a blockquote, and while adding, my text getting overlapping. 

![image](https://user-images.githubusercontent.com/48676771/58805836-271a9700-8615-11e9-92c7-0c8fd42efe84.png)

How can I fix it?

Thanks

**Comment by navneetnagpal** [comment]
@manu-sparheld Do you think it would be possible to make a jsFiddle to highlight the problem? That would speed-up things a lot. Here is a basic jsFiddle you could use as a starting point: https://jsfiddle.net/froala/wc5c3jhk/.

**Comment by manu-sparheld** [comment]
HI, it was a CSS issue, got fixed. Thanks
