### ISSUE TITLE
Browsing images in IE11 gives error in 3.1.0

### ISSUE THREAD

**Issue by mterhorst** [froala/wysiwyg-editor#3473]
For each image that gets displayed in the images view, the following error gets logged in the console on IE11.
![image](https://user-images.githubusercontent.com/24865628/58963961-5fa1a880-87ae-11e9-85f7-c004361cca92.png)

The button too add/delete images also does not show.

**Comment by navneetnagpal** [comment]
@mterhorst image is as a separate plugin here it looks like you are using froala_editor.min.js.
2 ways you can try to fix it
1. use froala_editor.pkgd.min.js
2. you can include specific plugins like plugins/align.min.js
plugins/image.min.js

Thanks,
Navneet

**Comment by navneetnagpal** [comment]
@mterhorst if you still getting error may be a jsFiddle to reproduce the issue would be great.
Thanks in advance.

**Comment by mterhorst** [comment]
Sorry for the delay. We are still not been able to update our Froala from v2 to v3, due to the Image Manager bug in IE we are experiencing. 
Please visit [this](https://jsfiddle.net/froala/nsj2w4xf/embedded/result,css,html,js) jsFiddle in IE to see it in action. I cannot add or remove images from the Image Manager to the editor.

**Comment by mterhorst** [comment]
Seems like i'm alone in this. Can nobody conform this issue? I tried version 3.1.0 with the previous jsFiddle, and I get the same error.

**Comment by SKPFCW** [comment]
Same here. 
I've found out, that "tui-image-editor.min.js"-script is needed (https://cdn.jsdelivr.net/npm/tui-image-editor@3.2.2/dist/tui-image-editor.min.js) to run Image Manager on IE11.
