### ISSUE TITLE
How to prevent specific tag remove on backspace when all text erase

### ISSUE THREAD

**Issue by MunkhdelgerMorhous** [froala/wysiwyg-editor#3475]
Hello how to keep empty tag deleting on backspace when i remove all text inside after backspace it delete its tag i need to prevent delete specific tag

**Comment by navneetnagpal** [comment]
@MunkhdelgerMorhous you can use this option
https://www.froala.com/wysiwyg-editor/docs/options#keepFormatOnDelete
