### ISSUE TITLE
Froala turns back to a normal textarea in web server.

### ISSUE THREAD

**Issue by skks1212** [froala/wysiwyg-editor#3477]
##### Expected behavior.
Froala must run cool and smooth when uploaded to a server.

##### Actual behavior.
Froala works fine while using in a localhost environment.
On uploading to a web server it works fine while editing for some time, and then on typing/inserting image it suddenly removes all its data and changes back to a default text area.

##### Steps to reproduce the problem.
1. Load Froala through CDN.
2. Put a textarea with the class as ".froala".
3. Load the following script from an external javascript file at the end of page-
new FroalaEditor('textarea.froala', {
    iconsTemplate: 'font_awesome_5',
    imageUploadURL: '/froala_upload.php',

    imageUploadParams: {
        id: 'my_editor'
    },
    
}) 

##### Editor version.
Froala is 3.0.0

##### OS.
Windows

##### Browser.
Chrome and literally every other browser

**Comment by ilyaskarim** [comment]
@skks1212 Is it possible for you to share the URL of the page?

**Comment by ilyaskarim** [comment]
@skks1212 Is it possible for you to share the URL of the page?

**Comment by skks1212** [comment]
@ilyaskarim I had added a bit of external css styling in froala to suit my page design. That was the reason it was destroying itself (still dont know why). So I removed the styling, works fine now!

Thanks.
