### ISSUE TITLE
[Froala v3] Domain licence key no longer working

### ISSUE THREAD

**Issue by karellodewijk** [froala/wysiwyg-editor#3479]
Click this link: 

https://teo.training/assets/license.html

Key there should be valid for http://teo.training domain

**Comment by PowerPalle** [comment]
I have same problem. Froala company never replies to my inquery. 

Palle

Sendt fra min iPhone

**Comment by karellodewijk** [comment]
Apparently the licence keys are different for v3, they sent me a new one.

**Comment by PowerPalle** [comment]
I used v3 and new method. Still does not work. And no reply from Froala. 

Sendt fra min iPhone
