### ISSUE TITLE
v3 Key

### ISSUE THREAD

**Issue by tonyspiro** [froala/wysiwyg-editor#3484]
##### Expected behavior.
Checking out v3. I used to initialize the license with this:
```
<script>
    $.FroalaEditor.DEFAULTS.key = 'mykey';
</script>
```
What's the way to do this for v3?

**Comment by navneetnagpal** [comment]
You can use like this
import FroalaEditor from 'froala-editor';
FroalaEditor.DEFAULTS.key = 'mykey';
