### ISSUE TITLE
ToolbarButtons are not show on angular8.0 

### ISSUE THREAD

**Issue by VolcanoOves** [froala/wysiwyg-editor#3486]
##### Expected behavior.
(Describe expected behaviour here)
show the insertImage button

##### Actual behavior.
(Describe actual behaviour here)
There is no show

##### Steps to reproduce the problem.
(Describe the steps to reproduce the problem here. A [jsFiddle](https://jsfiddle.net/froala/wc5c3jhk/) is awesome when possible.)

##### Editor version.
If you don't know it, please see https://wysiwyg-editor.froala.help/hc/en-us/articles/360000717049-How-can-I-find-my-editor-version-.

##### OS.
(OS name and version here)

##### Browser.
(Browser name an version here)

##### Recording.
(A recording showing how to reproduce the problem)
![微信截图_20190613172446](https://user-images.githubusercontent.com/18513530/59420919-504eda80-8e00-11e9-82ae-c68941b1db24.png)
![微信截图_20190613172458](https://user-images.githubusercontent.com/18513530/59420927-52189e00-8e00-11e9-8749-dba0533de9c0.png)
![微信截图_20190613172517](https://user-images.githubusercontent.com/18513530/59420932-53e26180-8e00-11e9-9e5b-1a931abbfe4a.png)

Excuse my broken English

**Comment by gondar00** [comment]
You need to import ```import 'froala-editor/css/froala_editor.pkgd.min.css';``` file inside your component for all the plugins to be available if you want a particular set please refer the below link 
https://www.froala.com/wysiwyg-editor/docs/options#toolbarButtons

**Comment by ilyaskarim** [comment]
Please see comment https://github.com/froala/wysiwyg-editor/issues/3486#issuecomment-501659286.
