### ISSUE TITLE
Switch "enter" and "shift+enter" behaviour

### ISSUE THREAD

**Issue by caxopog** [froala/wysiwyg-editor#349]
Hello

Now editor works:
Shift+Enter  - new line
Enter - new paragraph

I need to switch it:
Shift+Enter - new paragraph
Enter - new line

Is it possible in editor?

Thanks.

**Comment by performatric** [comment]
not yet?

**Comment by stefanneculai** [comment]
It's not built-in the editor, but you can now change it easily:
```js
$(selector).on('froalaEditor.initialized', function (e, editor) {
    var old_enter = editor.cursor.enter;
    editor.cursor.enter = function (shift) {
        return old_enter(!shift);
    }
}).froalaEditor();
```

**Comment by ziedmahdi** [comment]
@stefanneculai thank you very much for this workaround.

**Comment by imparvez** [comment]
@stefanneculai How to set this config in React Froala Editor component?

**Comment by stefanneculai** [comment]
@imparvez see https://github.com/froala/react-froala-wysiwyg#events-and-methods.

**Comment by prasadk24** [comment]
Hi
Above solution working only div, p, li tags
still duplication happen on remaining tags (span, a, em, strong etc.. )
