### ISSUE TITLE
custom popup & custom item

### ISSUE THREAD

**Issue by marcus130198** [froala/wysiwyg-editor#3492]
Hello. I created my own button on the panel (custom dropdown button), which adds a div container to the editor.
The question is, is it possible to add a pop-up window to it (.fr-popup class in html), an analogue of the window when adding a picture?

An example of this pop-up window in the screenshot. There he is near the picture, and I need the same near my container div.
If this is possible, then how to do it? (function names)
Thanks in advance for your reply.

p.s. Sorry for my english, used google translator.

![2019-06-17_21-36-04](https://user-images.githubusercontent.com/44944440/59627978-2c64ff00-9148-11e9-9531-a9cf2f883f5d.jpg)

**Comment by navneetnagpal** [comment]
@Vasiliy1301 as I can see you are already in editor having top toolbar. Inside editor it won't be possible as of now in this editor however if you apply two separate editor on image and other one as {toolbarInline:true} on div.
