### ISSUE TITLE
Deleting with backspace with htmlUntouched: true is moving cursor to the beginning 

### ISSUE THREAD

**Issue by Adam-Stomski** [froala/wysiwyg-editor#3494]
##### Expected behavior.
Deleting content with backspace works correctly

##### Actual behavior.
Deleting content with backspace sometimes causes cursor to jump to the beginning of the text

##### Steps to reproduce the problem.
https://codesandbox.io/s/damp-dream-ckix0

Everyone sometimes make errors while typing so just do that... type and delete with backspace. 

Pretty sure that it happens when you reach the space between the words

##### Editor version.
3.0.0

##### OS.
macOS Mojave 10.14.3

##### Browser.
Google Chrome
Version 74.0.3729.169 (Official Build) (64-bit)

**Comment by Adam-Stomski** [comment]
@navneetnagpal hey sir, can I have information why is this closed?

**Comment by navneetnagpal** [comment]
@Adam-Stomski this is fixed and pushed in master branch.

**Comment by thenitai** [comment]
This issue resurfaced in the latest versions of v3 :(
