### ISSUE TITLE
Nest list not working as expected on Ie

### ISSUE THREAD

**Issue by MunkhdelgerMorhous** [froala/wysiwyg-editor#3495]
![ie problem](https://user-images.githubusercontent.com/32539018/59757134-a965b500-92bd-11e9-8289-658fd627bb32.gif)
There is bug on nested list when i try to nest a list this is on IE11
Other Major Browser fine thou
anyone i tried to fix my own by digging src code but its no so good also i try custom indent but its bit overkill when its already done it in

**Comment by navneetnagpal** [comment]
@MunkhdelgerMorhous we are planning to release fixes around nested list kindly wait for the next version.

**Comment by MunkhdelgerMorhous** [comment]
Bug still occurs after 4,5 version

**Comment by MunkhdelgerMorhous** [comment]
I think its fixed know
