### ISSUE TITLE
Emoticon code for United Kingdom flag is incorrect

### ISSUE THREAD

**Issue by ConnorsFan** [froala/wysiwyg-editor#3496]
##### Expected behavior.
To see the United Kingdom flag in the emoticon list, and to insert it in the text when selected

##### Actual behavior.
We see the Italian flag instead, and that flag is inserted when we click on the emoticon.

##### Steps to reproduce the problem.
1. On the Froala Web page, use the demo editor
2. Open the emoticon dropdown
3. Select the Flags category
4. Go near the end of the list
5. You can see two Italian flags side by side
6. The first "Italian" flag has the tooltip "United Kingdom Flag"

##### Editor version.
The editor on the Froala Web page

##### OS.
Windows 7

##### Browser.
Chrome 75

**Comment by ConnorsFan** [comment]
Also: the "Soccer Ball" and "Balloon" tooltips have been switched.

**Comment by casualuser** [comment]
fixed in 3.0.4
