### ISSUE TITLE
theme file 'css/themes/royal.min.css' missing in npm v3 package

### ISSUE THREAD

**Issue by abdullahtariq1171** [froala/wysiwyg-editor#3497]
##### Expected behavior.
As per https://www.froala.com/wysiwyg-editor/examples/color-themes there should file `../css/themes/royal.min.css` for royal theme

##### Actual behavior.
`royal.min.css` is missing from published build https://unpkg.com/froala-editor@3.0.0/css/themes/

##### Steps to reproduce the problem.
N/A

##### Editor version.
3.0.0

##### OS.
macOS Mojave 10.14.5 (18F132)

##### Browser.
N/A

##### Recording.
N/A

**Comment by casualuser** [comment]
fixed in 3.0.4
