### ISSUE TITLE
character count is not updated when we call froala.html.set()

### ISSUE THREAD

**Issue by acemtp** [froala/wysiwyg-editor#3501]
##### Expected behavior.
character count is should be updated when we call froala.html.set()

##### Actual behavior.
character count stay to 0

##### Editor version.
3.0.0-alpha

##### OS.
mac os

##### Browser.
chrome latest

**Comment by slavik-chapelskyi** [comment]
You can try as workaround.
```
new FroalaEditor('.selector', {
  events: {
    'html.set': function () {
     	this.events.trigger('charCounter.update');
    })
  }
});
```

**Comment by vsatsw** [comment]
Char counter footer also is not updated, when editor is in the disabled state. This cause issues, when data set in the editor, when it is in the disabled state.
