### ISSUE TITLE
word_paste.min.js does not support strict mode

### ISSUE THREAD

**Issue by andrewgluh** [froala/wysiwyg-editor#3502]
##### Expected behavior.
word_paste.min.js does not support strict mode:

##### Steps to reproduce the problem.
When attempting to include this file in our minified bundle, we get the following errors:
"Strict-mode does not allow assignment to undefined variables"
"Strict-mode does not allow ++ or -- on certain objects:"	

Our bundler automatically includes a "use strict"; in each js file.
This is the only froala .js file that does not support strict mode.

##### Editor version.
Version 3.0.0

##### OS.
N/A

##### Browser.
N/A

##### Recording.
N/A

**Comment by casualuser** [comment]
fixed in 3.0.4
