### ISSUE TITLE
Crash in Jest's jsdom environment: Error: Uncaught [TypeError: Cannot read property '$off' of undefined]

### ISSUE THREAD

**Issue by elliottsj** [froala/wysiwyg-editor#3504]
##### Expected behavior.
froala-editor can be created and destroyed in Jest's jsdom environment.

##### Actual behavior.
When `editor.destroy()` is called, this error is raised:

```
Error: Uncaught [TypeError: Cannot read property '$off' of undefined]
```

##### Steps to reproduce the problem.
Full repro here: https://github.com/elliottsj/froala-editor-jest-issue

##### Editor version.
3.0.0

##### OS.
macOS 10.14.5

##### Browser.
Jest / jsdom

**Comment by casualuser** [comment]
fixed in 3.0.4
