### ISSUE TITLE
translate wrong that Characters is char count no pepole in zh_ch.js

### ISSUE THREAD

**Issue by cifaz** [froala/wysiwyg-editor#3506]
### _If you have a feature suggestion, please add it on the [Feature List](https://wysiwyg-editor-roadmap.froala.com/public) instead._
translate wrong that Characters is char count no pepole in zh_ch.js

##### Expected behavior.
nothing

##### Actual behavior.
nothing

##### Steps to reproduce the problem.
nothing

##### Editor version.
froala-editor@3.0.0

##### OS.
window10

##### Browser.
chrom 63

##### Recording.
replace translate 'Characters': '人物'  to 'Characters': '字数统计' in the zh_ch.js

**Comment by casualuser** [comment]
fixed in 3.0.2
