### ISSUE TITLE
Possible typo on the quote dropdown button

### ISSUE THREAD

**Issue by alecbass** [froala/wysiwyg-editor#3508]
##### Expected behavior.
This is how it looks on the mac editor, with icons:
![Possible quote button typo mac cropped](https://user-images.githubusercontent.com/27332369/60221881-aae73c80-98be-11e9-869a-7f5cabf28fa6.PNG)

##### Actual behavior.
On the Windows editor, this is how it looks:
![Possible quote button typo cropped](https://user-images.githubusercontent.com/27332369/60221917-d9fdae00-98be-11e9-8257-ea64cd3fdf55.PNG)

Is there supposed to be a space between "Increase"/"Decrease" and "Ctrl+Shift"? It seemed a bit odd.

##### Steps to reproduce the problem.
Click on the quote button dropdown and the results should appear.

##### Editor version.
React Editor 3.0.0

##### OS.
Windows 10 1803

##### Browser.
Google Chrome Version 74.0.3729.169 (64-bit)

**Comment by casualuser** [comment]
fixed in 3.0.3

**Comment by alecbass** [comment]
Thank you! It looks great.
