### ISSUE TITLE
Forcing color output as hex

### ISSUE THREAD

**Issue by RobbieArmz** [froala/wysiwyg-editor#3511]
Hi, currently im simply trying to work with the colorpicker, but I need the output color in hex not in rgb, is that possible to do?

For example: I type any text on it, lets say its "Foo test bar", and lets assume I want the word "test" in a specific hex color, lets say its #15E67F. When I highlight the word "test" select the color and hit enter the output i get is this:
`<p>Foo <span style="color: rgb(21, 230, 127);">test</span> bar</p>`

But what I actually need is this:
`<p>Foo <span style="color: #15E67F;">test</span> bar</p>`

How is that possible?

**Comment by casualuser** [comment]
Hi Robbie

At the moment color styles applied as `rgb` in code but you still have an option to specify the color as `hex` in the color selector. 

![hex_color](https://user-images.githubusercontent.com/1243074/60455785-183cf980-9c40-11e9-918d-c64705e66ffc.png)

Yes, that's true that it will be converted to `rgb` but that is how it was designed initially. 

You can find currently available options related to color management in Froala Editor here - https://www.froala.com/wysiwyg-editor/docs/options#colorsBackground

And also you can create a feature request for an option to encode color in `rgb`/`hex` here - https://froala.cnflx.io/public

If it will receive a lot of votes then it will be implemented in one of upcoming build.

**Comment by RobbieArmz** [comment]
I see, Is there any way to override the function that converts the color to RGB or create a custom command that output it on hex format, it is absolutely necessary that the color is output in the hex format because im using Froala editor to manage my Android App News Section, however Android's HTML.fromHtml() function can't parse the rgb colors, but it works just fine using hex.
