### ISSUE TITLE
Image cannot be loaded from the passed link

### ISSUE THREAD

**Issue by luoxionghui** [froala/wysiwyg-editor#3512]
Hi~ Today when using JS + NodeJS to create a project , I meet this question:
The froala/wysiwyg-editor response an error
{code: 1, message: "Image cannot be loaded from the passed link."}

The part of my NodeJS server code (I had clone from [https://www.froala.com/wysiwyg-editor/docs/sdks/nodejs/image-server-upload](https://www.froala.com/wysiwyg-editor/docs/sdks/nodejs/image-server-upload) :
app.post('/upload_image', function(req, res) {

  FroalaEditor.Image.upload(req, '/uploads/', `function(err,` data) {
    console.log(111)
    if (err) {
      return res.send(JSON.stringify(err))
    }
    res.send(data)
  })
})

However , the image which I want to upload is uploaded in my server side folder 'uploads'. And why the froala respone image error code is :{code: 1, message: "Image cannot be loaded from the passed link."}.

**Comment by casualuser** [comment]
Hello, 

It looks like there is something with paths/folders in your code. Please check this working example code https://glitch.com/edit/#!/lofty-chips for details about how to use Node.JS Image Server Upload feature.

**Comment by SublimeSM** [comment]
same issue here, I'm using the laravel nova plugin
- the file is well uploaded in my storage/app/public folder but not displayed in the wysiwyg

**Comment by santoshD93** [comment]
Same issue here. I am building an app using Elixir (phoenix framework) and created froala.js

Froala version: 3.1.1

**Comment by santoshD93** [comment]
@casualuser 
Some help here would be highly appreciated.

**Comment by amitmoondra** [comment]
Is there any resolution for this yet?
I do not see any comments for solution?

**Comment by pmjtb** [comment]
i had the same problem, so i tried to edit the upload_image.php file - i set `$response->link` to absolute path to the image and it started working

`$response->link` = "/public_html/interni/upload/" . $name; /* working */
$response->link = "upload/" . $name;  /* not working */`

hope this helps
