### ISSUE TITLE
Add focusable=false to SVG icons

### ISSUE THREAD

**Issue by kylehalleman** [froala/wysiwyg-editor#3514]
##### Expected behavior.
Tabbing does not focus on toolbar buttons.

##### Actual behavior.
Tabbing in IE11 focuses on toolbar buttons because SVGs are focusable by default in IE11.

##### Steps to reproduce the problem.
[Use the main demo at the homepage](https://www.froala.com/wysiwyg-editor) in IE11. Use <kbd>Tab</kbd>.

##### Editor version.
3.x (whatever the homepage uses)

##### OS.
Windows 10

##### Browser.
Internet Explorer 11

Adding `focusable="false"` to the SVG elements that make up the toolbar button icons will fix this issue.

**Comment by casualuser** [comment]
fixed in 3.0.3
