### ISSUE TITLE
How to upload multiple pictures

### ISSUE THREAD

**Issue by LIMr1209** [froala/wysiwyg-editor#3515]

**Comment by casualuser** [comment]
Hello,

At the moment it is possible to upload images one by one. There is exists possibilities to extend and tweak images upload process. 

Check these links in docs area:
https://www.froala.com/wysiwyg-editor/docs/server/nodejs/image-upload
https://www.froala.com/wysiwyg-editor/docs/concepts/image/upload
https://www.froala.com/wysiwyg-editor/docs/sdks

Also, you can create a feature request here - https://froala.cnflx.io

**Comment by heymexa** [comment]
Hi!

Exists the plugin for multi upload - [Images Multi Upload](https://github.com/heymexa/froala-images-multi-upload), but this plugin only works for version 2.x. so far.
