### ISSUE TITLE
Uncaught TypeError: Cannot read property 'KEYCODE' of undefined

### ISSUE THREAD

**Issue by tommy-nf** [froala/wysiwyg-editor#3516]
I use the Version 3.0.1
I create a new Editor with **toolbarInline: true, toolbarVisibleWithoutSelection: true**.

##### Expected behavior.
When i mark a part of the text (before typing anything), the toolbar should popup up.

##### Actual behavior.
When i mark a part of the text (before typing anything), the toolbar is not shown and in the developer console pops the following error up: **Uncaught TypeError: Cannot read property 'KEYCODE' of undefined**
After typing some characters, the toolbar shows up. When i mark a part again, the toolbar is not updating.

The following snippet of the minified .js causes the error:
**e.which!=b.FE.KEYCODE.ESC** 
When i replace **b.FE.KEYCODE.ESC** with the keycode **27** (for ESC), everything runs fine.

##### Steps to reproduce the problem.
In the JSFiddle occurs the error. 
https://jsfiddle.net/wpyujbvg/2/

**Comment by Spoowy** [comment]
I have the same issue

**Comment by tommy-nf** [comment]
@Spoowy the problem is solved now.
Download the new zip-File and everything works fine. :)

**Comment by Spoowy** [comment]
@tommy-nf I'm installing via npm but will download th zip

**Comment by mzorzella** [comment]
We have the same problem. We also noticed that if you click multiple times on the same editor, the occurrences of this error keep growing and the CPU used by my browser goes over 100%. But that may be related to my configuration.

**Comment by ShaMSofT** [comment]
I have same issue. I downloaded latest zip file with no luck (both from your website and GitHub).
