### ISSUE TITLE
Unlicensed Froala Editor

### ISSUE THREAD

**Issue by SBillion** [froala/wysiwyg-editor#352]
I am not able to use the last master version from github. I thought it was due to the fact I didn't pay a license but after bought a license "Signel website" I didn't get a license key or something special to fix it.
Here is what I see on Google Chrome, Chromium and Firefox after changing all files from 1.2.4 to the dev version. I removed the cache:
![unlicensed_froala_editor](https://cloud.githubusercontent.com/assets/1070649/5506559/acbed812-879b-11e4-8eb3-0969c001a666.png)

**Comment by ahmadalibaloch** [comment]
$("a:contains('Unlicensed Froala Editor')").parent().remove();;

**Comment by imidsac** [comment]
how to get license?

**Comment by stefanneculai** [comment]
From our website https://www.froala.com/wysiwyg-editor/pricing

**Comment by csbug** [comment]
how to implement activation key
i have used `$.FroalaEditor.DEFAULTS.key = 'My activation key'; ` but still i am getting. Unlicensed Froala Editor .

**Comment by gogogous88** [comment]
@stefanneculai your froala is like a virus, i uninstalled it but wherever i have a textarea, there shows unlicensing problem.....any idea whats going on?

**Comment by SBillion** [comment]
@gogogous88 If you removed everything related to froala, I guess it's the cache of your navigator.

**Comment by Prince-254** [comment]
place this css code on your page

`a[href="https://froala.com/wysiwyg-editor"], a[href="https://www.froala.com/wysiwyg-editor?k=u"] {
                                                display: none !important;
                                                position: absolute;
                                                top: -99999999px;
                                              }`
