### ISSUE TITLE
When attribution: false in Froala v3 editor appearance looks odd

### ISSUE THREAD

**Issue by chrisdeeming** [froala/wysiwyg-editor#3521]
If you disable attribution and have nothing else in the footer of the editor, the appeance looks odd:

![image](https://user-images.githubusercontent.com/2158514/60608114-958a7a80-9db6-11e9-9925-948fecbc0c1b.png)

Note there is what appears to be a double border at the bottom, and the symmetry of the rounded corners is lost.

The best solution I found was to:

* Give `div.second-toolbar` a height of 10px.
* Add `border-bottom: 0` to `.fr-box.fr-basic .fr-wrapper`

![image](https://user-images.githubusercontent.com/2158514/60608354-2e20fa80-9db7-11e9-84e2-7b0bd3900cee.png)

**Comment by acwr** [comment]
Looks like this was finally fixed in 3.2.7 (https://jsfiddle.net/trqLodza/)

**Comment by chrisdeeming** [comment]
Yes it is. Thanks!
