### ISSUE TITLE
[3.0 breaking change] Saving now carried out as multipart/form-data

### ISSUE THREAD

**Issue by slavarazum** [froala/wysiwyg-editor#3526]
Looks like 3.0 version has breaking change with **saving feature**. Now all saving requests sending as `multipart/form-data` and encode a parameters.

For example I have editor body and some additional param "title":

![screenshot1](https://image.prntscr.com/image/M8417DWnT9KVuOd_j4CvmA.png)

save config:

```javascript
{
     saveParam: 'content',
     saveURL: `/article/3`,
     saveMethod: 'PUT',
     saveParams: {
          title: this.component.title,
     },
     saveInterval: 10000,
}
```

after saving, we will get following result:

![screentshot2](https://image.prntscr.com/image/0VzVjtMGRTSEJ1zfzEy0wQ.png)

Looks like it encoding all params and sending as `multipart/form-data` (which may cause some problems). Previously in 2.9 version it was sanding as `application/x-www-form-urlencoded; charset=UTF-8`

##### Expected behavior.
Rollback sending request content type, or give ability to customize it. Fix params  default encoding.

##### Actual behavior.
Default content type has changed, what entails breaking changes.

##### Steps to reproduce the problem.
1. Try to setup `save` button
2. Try to save something
3. Look into request body and `Content-Type` 

##### Editor version.
3.0.1

##### OS.
Mac OS Mojave

##### Browser.
Any

**Comment by casualuser** [comment]
fixed in 3.0.4
