### ISSUE TITLE
I am using customize chunk image up-loader in the froala editor. The problem arises is that the uploaded image always appends in the editor at the end and not at the cursor position. How can I insert an image using our chunk up-loader at the cursor position?

### ISSUE THREAD

**Issue by DharmeshMertwal** [froala/wysiwyg-editor#3528]
chunk uploader is integrated with the froala editor to move large files to Amazon s3 without interruption, now I am facing a problem with the position of the Image after the upload any image.

**Comment by casualuser** [comment]
Hello,
We have tried to reproduce the issue but it looks like special conditions required for that.
Please create `jsfiddle` or `stackblitz` sample illustrating the issue.

**Comment by DharmeshMertwal** [comment]
Thank you we have solved this issue through froala support

**Comment by elonbase** [comment]
@DharmeshMertwal hi, I have encountered similar problems recently. Can you share your solution? Thank in advance.

**Comment by elonbase** [comment]
I found the solution on stackoverflow! Thanks! [link](https://stackoverflow.com/questions/32617361/retain-caret-position-in-froala-editor-after-html-set-or-snapshot-restore)
