### ISSUE TITLE
Console Error while adding Video with html.set

### ISSUE THREAD

**Issue by kishorethecoder** [froala/wysiwyg-editor#3530]
##### Expected behavior.
Adding Video to the Editor with html.set should working fine

##### Actual behavior.
Adding Video with Html.set causes the console error **Uncaught TypeError: Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'.**  in the Video Plugin on creating wrapper for video options

##### Steps to reproduce the problem.
https://jsfiddle.net/0qphgtds/1/

##### Editor version.
3.0

**Comment by casualuser** [comment]
fixed in 3.0.4
