### ISSUE TITLE
Applying multiple styles when no text is selected causes infinite sibling tag creation

### ISSUE THREAD

**Issue by sblattj** [froala/wysiwyg-editor#3536]
##### Please fix this fast
This issue has been ongoing when no text is selected and styles are applied. There were tons of issues that came up on our backlog because of this simple case of non-deletion of the HTML when styles are deselected and nothing is selected.

##### Expected behavior.
When styles are selected and deselected, the HTML gets added and removed.

##### Actual behavior.
HTML is continuously added into a gigantic mess, and we are having trouble gaging what buttons should be depressed in our editor because of it.

##### Steps to reproduce the problem.
1. Go to the editor: https://www.froala.com/wysiwyg-editor
2. Erase everything or click somewhere in the text without selecting any text
3. Add and remove bold/underline/italic/strikethrough in various ways
4. Observe HTML generation where the styles were added and removed

##### Editor version.
On the website

##### OS.
All

##### Browser.
All

##### Recording.
![froalaBug](https://user-images.githubusercontent.com/5125883/60835903-22e41b00-a179-11e9-9c82-130314f96d10.png)

**Comment by casualuser** [comment]
fixed in 3.0.4
