### ISSUE TITLE
Pressing "Decrease indent" on a list that has had "Increase indent" applied loses all styling

### ISSUE THREAD

**Issue by LloydBidhive** [froala/wysiwyg-editor#3546]
##### Expected behavior.
Pressing decrease indent on an already indented list should decrease each indent. 

##### Actual behavior.
Pressing decrease indent on an already indented list completely removes all styling.

##### Steps to reproduce the problem.
- Open the attached Word example
- Copy all text
- Paste into our [jsFiddle](https://jsfiddle.net/xk4903gr/1/)
- Press "Keep" when the Word Paste Detected modal appears.
- Highlight all text
- Press increase indent multiple times
- Notice the list has indented as expected
- Press decrease indent
- Notice all list styling is now lost

##### Editor version.
3.0.2

##### OS.
MacOS Mojave 10.14.4 (18E226)

##### Browser.
Google Chrome Version 75.0.3770.100 (Official Build) (64-bit)

##### Attachments.
[List Item Indenting.docx](https://github.com/froala/wysiwyg-editor/files/3375611/List.Item.Indenting.docx)

**Comment by casualuser** [comment]
fixed in 3.0.3

**Comment by LloydBidhive** [comment]
now working great, thanks guys.
