### ISSUE TITLE
Vertical separators between toolbar icons do not work

### ISSUE THREAD

**Issue by LloydBidhive** [froala/wysiwyg-editor#3548]
##### Expected behavior.
Vertical separators display between Froala toolbar icons

##### Actual behavior.
Vertical separators do not display after using the  "|" separator.

Froala documentation [here](https://www.froala.com/wysiwyg-editor/docs/options#toolbarButtons).

"Note: | will insert a vertical separator line in the toolbar, and - a horizontal one."

##### Steps to reproduce the problem.
- Access our [jsFiddle](https://jsfiddle.net/xk4903gr/1/) to see implementation of the "|" separator.

##### Editor version.
3.0.2

##### OS.
MacOS Mojave 10.14.4 (18E226)

##### Browser.
Google Chrome Version 75.0.3770.100 (Official Build) (64-bit)

##### Attachment.
<img width="1532" alt="|  separator" src="https://user-images.githubusercontent.com/41405678/60939860-abe78780-a31c-11e9-9a6f-f7b219abe8ea.png">

**Comment by casualuser** [comment]
fixed in 3.0.4

**Comment by hariharasuthan-balaji** [comment]
Does not seem to work with v3.1.0 Unless it the options is an object.
