### ISSUE TITLE
Various toolbar icons fail to ghost after uploading and selecting an image

### ISSUE THREAD

**Issue by LloydBidhive** [froala/wysiwyg-editor#3549]
##### Expected behavior.
All icons on the toolbar ghost out (or appear inactive) whilst an image is selected.

##### Actual behavior.
"Ordered List" and "Unordered List" icons remain unghosted whilst an image is selected. 

##### Steps to reproduce the problem.
- Open our [jsFiddle](https://jsfiddle.net/xk4903gr/1/)
- Open the image manager
- Drop an image into the page
- Notice that the "Ordered List" and "Unordered List" icons have not ghosted like the rest of the toolbar icons. Undo and Redo will occasionally look active also (see attached)

##### Editor version.
3.0.2

##### OS.
MacOS Mojave 10.14.4 (18E226)

##### Browser.
Google Chrome Version 75.0.3770.100 (Official Build) (64-bit)

##### Attachment.
<img width="1525" alt="Screen Shot 2019-07-10 at 2 21 01 pm" src="https://user-images.githubusercontent.com/41405678/60940219-0b926280-a31e-11e9-969d-8e563008a975.png">

**Comment by casualuser** [comment]
Hi 
Rechecked your issue description and should say that in this case it works as it should.
With "undo" you can cancel image insertion and both lists buttons may be used for converting inserted image into first element of list. So here is nothing to do regard this buttons.

**Comment by LloydBidhive** [comment]
Thanks @casualuser - I did originally miss that you could turn the images into lists.

Appreciate the reply.
