### ISSUE TITLE
Cursor in wrong place in iframe mode

### ISSUE THREAD

**Issue by cjh79** [froala/wysiwyg-editor#3553]
##### Expected behavior.
After clicking in the editor, cursor should appear where the "Type something" placeholder text is.

##### Actual behavior.
In iframe mode, cursor shows up beneath the "Type something" placeholder text. Additionally, the placeholder text is not properly aligned.

##### Steps to reproduce the problem.
Run [this jsfiddle](https://jsfiddle.net/cjh79/wzvn120u/2/)

##### Editor version.
3.0.0

##### OS.
OSX 10.13.6

##### Browser.
Occurs in all browsers I have tried, which are:
* Firefox 68.0
* Chrome 75.0
* Safari 12.1.1

**Comment by casualuser** [comment]
fixed in 3.0.4
