### ISSUE TITLE
[Urgent] Jquery UI Tabs is not working with froala editor

### ISSUE THREAD

**Issue by thehung2224** [froala/wysiwyg-editor#3554]
##### Expected behavior.
I am using froala 2.9.3 inline editor for editing my page, I applied editor in my site and I also wanted to use Tabs (Jquery UI Tabs) for my sliders

##### Actual behavior.
But it seems editor is not working with Froala Editor, here is what I see on Console Logs http://prntscr.com/oglyhh

This is urgent case, please help me fix it soon.

Regards,
[Hung PD](https://hungpd.name)

**Comment by casualuser** [comment]
Hello,

You can easily use Froala Editor in inline mode together with Jquery UI Tabs.
Please keep in mind that to avoid editing names of tabs Froala Editor should be initialized for ids of tab's div elements only.
Also, there is no any needs in additional jQ script inclusion for Jquery UI Tabs. Two versions of jQ at the same page cause errors. 

Take a look at this example - https://jsfiddle.net/womjoy/pd48s1v5/1/

**Comment by thehung2224** [comment]
Hi,

Thank you for your assistance. I added that code but it still doesn't work. 

How can I provide admin credentials in private message then you can take a look?

Regards,
[Hung PD](https://hungpd.name)
