### ISSUE TITLE
CSS class "fr-selected" is not properly removed when leaving a button while keeping mouse button pressed

### ISSUE THREAD

**Issue by rogersteblerbsi** [froala/wysiwyg-editor#3558]
##### Expected behavior.
CSS class "fr-selected" should be removed when you click and then drag the cursor out of a button.

##### Actual behavior.
CSS class "fr-selected" is not removed when you click and then drag the cursor out of a button.

##### Steps to reproduce the problem.

- Go to https://jsfiddle.net/gdosbwz9/
- Click on the "bold" button and keep the mouse button pressed
- Move the mouse to the right
- Release the mouse button when you reached the "italic" button
- "Bold" button is still gray

##### Editor version.
3.0.3

##### OS.
Windows 10

##### Browser.
Chrome 75.0.3770.142

##### Recording.
![1](https://user-images.githubusercontent.com/48489803/61460220-94d51500-a96e-11e9-8d57-e2990594c962.gif)

**Comment by casualuser** [comment]
fixed in 3.0.4
