### ISSUE TITLE
Ability to press Enter to submit popups

### ISSUE THREAD

**Issue by philfreo** [froala/wysiwyg-editor#356]
Should be able to:

- highlight text
- press `cmd-k`
- type or paste a link in URL field
- press enter to create/save the link.

Right now the last step doesn't work -- you have to use a mouse to click "OK".

Similarly if you press Enter in the "Enter URL" part of "Insert Image" it should also submit, but doesn't.

(minor UX improvement)

**Comment by stefanneculai** [comment]
161da35e4450cf28e8b9ec2928e87c35b6aa1e21
