### ISSUE TITLE
IE11: Text is not selectable in iframe mode when using the table plugin

### ISSUE THREAD

**Issue by bjornri** [froala/wysiwyg-editor#3562]
##### Expected behavior.
Text should be selectable by using the mouse.

##### Actual behavior.
Text is not selectable by using the mouse (but works if you hold shift and press arrow buttons on the keyboard).
(Guessing that Froalas Element polyfills aren't applied on objects in the iframe on IE11.)

##### Steps to reproduce the problem.
Initialize Froala with iframe: true and the table plugin. Here's a fiddle:
https://jsfiddle.net/mqpt0efL/

##### Editor version.
3.0.3

##### OS.
Windows 10

##### Browser.
IE11

##### Recording.
[recording.zip](https://github.com/froala/wysiwyg-editor/files/3416086/recording.zip)

**Comment by casualuser** [comment]
fixed in 3.0.4
