### ISSUE TITLE
Destroying editor with quickInsert plugin changes the position of body element

### ISSUE THREAD

**Issue by SergeyKhval** [froala/wysiwyg-editor#3565]
##### Expected behavior.
Destroying editor instance does not affect position of body

##### Actual behavior.
Body's position becomes `left: -9999px; top: -9999px;`

![image](https://user-images.githubusercontent.com/16866432/61714604-efea7b80-ad63-11e9-977c-6dad5f42aecf.png)

##### Steps to reproduce the problem.
[jsFiddle](https://jsfiddle.net/u9h4y3k5/) Place cursor inside editor and hit enter, quick insert button appears. Click 'destroy' button.

##### Editor version.
3.0.3

##### OS.
Ubuntu 19.04

##### Browser.
Latest chrome

**Comment by casualuser** [comment]
fixed in 3.0.4
