### ISSUE TITLE
Manipulating the image upload before/after

### ISSUE THREAD

**Issue by Bardigan** [froala/wysiwyg-editor#3567]
Hi guys, I have a question, we have purchased your licence but last few days i can't make certain functionality to work, our API accepts certain formatting for image upload, I thought that I can manipulate the payload in "image.beforeUpload" but it doesn't seem to be the solution. Is it possible to change the formatting? and make the payload something like { key: base64 } ? also the response should be { link : linkUrl } as far as i see in the doc, but is it possible to manipulate the response data? I would appreciate any help.

React, Froala v 3.0.3

**Comment by casualuser** [comment]
Hello,

Sure thing there is different ways to process images during upload exists.
The main flow described here - https://www.froala.com/wysiwyg-editor/docs/concepts/image/upload
If you already tried something but stuck at some kind of moment then please create jsfiddle/stackblitz/codesandbox sample illustrating your question and we will try to help you with it. 

Not sure about your exact requirements and user story but here is some samples of custom image flow for inserting images as base64
https://wysiwyg-editor.froala.help/hc/en-us/articles/115000555949-Can-I-insert-images-as-base64-

Also, such requests better send privately with the maximum amount of details and code samples via https://www.froala.com/wysiwyg-editor/contact
