### ISSUE TITLE
Script error occurs in word_paste plugin when pasting certain html in Firefox

### ISSUE THREAD

**Issue by bjornri** [froala/wysiwyg-editor#3573]
### Expected behavior.
No script errors should occur and the text should be pasted.

##### Actual behavior.
Clicking either 'Keep' or 'Clean' button causes script error with no feedback to the user. The dialog can be dismissed by using the 'close' button though.

##### Steps to reproduce the problem.
Copy certain rich text to the clipboard then paste it with the word_paste plugin enabled. I'm unsure what exactly that fails as I only have obfuscated sources of the plugin that crashes. 

However, I was able to create a reproducable case here: https://jsfiddle.net/7fo9ad5y/

To provoke the error, run the fiddle and click the 'Copy to clipboard' button. Then click in the Froala editor and press Ctrl+V. Froala will ask if you want to keep or clear formatting. Clicking either will display a script error in the console: 
ReferenceError: assignment to undeclared variable i

##### Editor version.
3.0.3

##### OS.
Windows 10

##### Browser.
Firefox 68.0.1
(Works in Chrome and Safari - can't get the plugin to work at all in IE so unable to test it.. but that's another issue)

##### Recording.
I can add a recording if its required.

**Comment by casualuser** [comment]
fixed in 3.0.4
