### ISSUE TITLE
Upload files/images to Google cloud Storage

### ISSUE THREAD

**Issue by anks333** [froala/wysiwyg-editor#3574]
My requirement is to upload the images/files to google cloud storage with private access.

after image/file upload, when we will render the image at that time signed url will be required.
so does froala editor provides any `pre-fetch` image or embed  hook, so that we can manipulate the `src` attribute and replace the existing src value with signed url.

**Comment by casualuser** [comment]
Hello,

There is exists different possibilities to manage images while uploading.
For example, you can intercept uploaded image, process it in a specific way and then inject a new image into uploading function.

Here is a starting point for doing this:
https://www.froala.com/wysiwyg-editor/docs/events#image.beforeUpload

Also if you do not want to manage image at client-side and expose your Google keys in javascript code then it may be wiser to use additional backend code for handling images.

Server-side processing available in all kind of languages like node.js, python, php, etc
https://www.froala.com/wysiwyg-editor/docs/sdks/nodejs/file-server-upload
https://www.froala.com/wysiwyg-editor/docs/sdks/python/image-manager
