### ISSUE TITLE
TypeError: Object doesn't support property or method 'get’ with editor.image.remove( images[0]) for MS Edge Browser 

### ISSUE THREAD

**Issue by sg-satya** [froala/wysiwyg-editor#3575]
**Customer's description of the issue:**
We are facing issue with image.remove function on Edge browser. We are using below code to upload images.

.on('froalaEditor.image.beforeUpload', function (e, editor, images) {
let image = images[0]
getSignedUrls().then(({ uploadUrl, downloadUrl }) =>
uploadImageToS3(uploadUrl, image ).then(() => {
editor.image.remove( images[0]);
editor.image.insert(downloadUrl, true, null,null);
})
)
return false;
})
Above code is working fine on all browsers and we are able to upload images. But somehow it is not working on Edge browser (Windows 10, Edge version 44.17763.10)
We are getting below error on browser console.
JQuery.Deferred exception: Object doesn't support property or method 'get' TypeError: Object doesn't support property or method 'get'
This error is coming due to line editor.image.remove( images[0]);

**Froala version**
froala_editor v2.9.6

**Customer's fiddle reproducing issue:**
https://jsfiddle.net/0q5jaxyL/2/

**Comment by casualuser** [comment]
this was reported properly in private repo and solved here - https://github.com/froala-labs/froala-editor-js-2/issues/1925
