### ISSUE TITLE
Source code no longer available on froala.com

### ISSUE THREAD

**Issue by petester42** [froala/wysiwyg-editor#3580]
In the past we used to download the source code of froala to integrate it into our product since we needed to make some significant changes to some of the modules and plugins. After the release of v3 the login and source code download options seem to have been removed. We need the source code where do we get it now?

**Comment by casualuser** [comment]
Hello,
If you have some kind of special redistribution permissions then it will be better to contact Accounting team via https://www.froala.com/wysiwyg-editor/contact
Github issues in general useful for tech-related questions with code samples, etc

**Comment by casualuser** [comment]
https://wysiwyg-editor.froala.help/hc/en-us/articles/360001886218-Where-do-I-sign-in-to-my-account-

**Comment by petester42** [comment]
It says "You're not authorized to access this page" after logging in
