### ISSUE TITLE
Plugins not loading on Froala v3.0.4 with React editor v3.0.3

### ISSUE THREAD

**Issue by thomaslenzi** [froala/wysiwyg-editor#3585]
### Expected behavior
The plugins should load and corresponding buttons should be displayed in the toolbar.

##### Actual behavior
The buttons are not being displayed in the toolbar which might indicate the plugins are not loaded.

##### Steps to reproduce the problem
The sole difference between a working and non-working state is that I upgraded from `froala-editor` v3.0.3 to v3.0.4. Note that `react-froala-wysiwyg` is on v3.0.3 (no v3.0.4 available as of the time of writing).

##### Editor version
non-working : v3.0.4
working : v3.0.3

##### OS
Ubuntu 19.04

##### Browser
Firefox Quantum 68.0.1 (64-bit)

##### Small example

```js
import React from 'react';
import FroalaEditorComponent from 'react-froala-wysiwyg';
import 'froala-editor/css/froala_style.min.css';
import 'froala-editor/css/froala_editor.pkgd.min.css';
import 'froala-editor/js/plugins/paragraph_format.min';

<FroalaEditorComponent
  config={{
    toolbarButtons:  [
      'paragraphFormat',
      'bold',
      'italic',
    ],
  }}
  tag="textarea"
/>
```
In v3.0.3 the `paragraphFormat` button is displayed while not being the case in v3.0.4.

**Comment by casualuser** [comment]
Hello,

That is correct - with different versions of `froala-editor` and `react-froala-wysiwyg` packages some kind of issues possible. 
Version 3.0.4 for `react-froala-wysiwyg` had been released same day as version 3.0.4 for `froala-editor`.

Please check package.json and update version values there to fixed version notation if required.
