### ISSUE TITLE
Popup ids list

### ISSUE THREAD

**Issue by slavik-chapelskyi** [froala/wysiwyg-editor#3586]
I'm trying to add event listener for each popup and change position to not overflow container (if needed).
I'm using [popup.show](https://www.froala.com/wysiwyg-editor/docs/events#popups.show.[id]) event and wondering if there is anywhere a list of all possible `popup ids`.

Can anyone provide some info on this?

**Comment by casualuser** [comment]
Hello,
There is no any special methods allow to get list of popups ids in Froala Editor.
But you can use smth like this `Array.prototype.map.call(document.querySelectorAll('[id^="fr-text-edit"]'), el => el.id)`

**Comment by lunfel** [comment]
I cannot find a list of pre-defined popup ids in the documentation. I don't think calling an arbitrary javascript snippet to list the ids is a good way to go.

I wished it was instead added to the official documentation

**Comment by cnacode** [comment]
I'm also having this issue

**Comment by advancedvdragutinovic** [comment]
I was struggling with finding out the popup IDs as well. I didn't find the official list either, but  I was able to find out the IDs by subscribing to popups.onShow event. See below: 

new FroalaEditor('.selector', {
  events: {
    'initialized': function () {
      // Do something here.
      // this is the editor instance.
      console.log(this);
      this.popups.onShow = (popupId) => { 
         // this callback will be called for any popup 
         console.log ('Popup shown: ', popupId);
      }
    }
  }
});

Hope this helps someone
