### ISSUE TITLE
[3.0] Save icon missing

### ISSUE THREAD

**Issue by slavarazum** [froala/wysiwyg-editor#3587]
Duplicate to https://github.com/froala/wysiwyg-editor/issues/3525
Due to lack of response.

**Comment by casualuser** [comment]
we have this question with high prio targeted to release in first days of Sept
there should icons for all standard buttons added

**Comment by slavarazum** [comment]
Great! Will wait.

**Comment by casualuser** [comment]
closing this and reopening initial bug with reference to internal issue
