### ISSUE TITLE
zIndex option also sets z-index to the whole editor

### ISSUE THREAD

**Issue by petrinecp** [froala/wysiwyg-editor#3588]
##### Expected behavior.
z-index is only applied to toolbars and popups, just like the [documentation](https://www.froala.com/wysiwyg-editor/docs/options#zIndex) states.

##### Actual behavior.
z-index is also applied to the main editor element, therefore elements which are positioned above the editor get covered when using _zIndex_ option.
![image](https://user-images.githubusercontent.com/5637849/62370633-f8487080-b532-11e9-8b8f-cd6dca02b49c.png)

##### Steps to reproduce the problem.
https://jsfiddle.net/9q1mr8at/2/

Click inside the second table row.
![image](https://user-images.githubusercontent.com/5637849/62370723-35146780-b533-11e9-8041-d3dc9e6702dc.png)
Then uncomment the zIndex option to increase the z-index of the popup, however then the button gets cover with the editor.

##### Editor version.
3.0.4

##### OS.
Windows 10

##### Browser.
Chrome 75

**Comment by casualuser** [comment]
Hello,

So it looks like in this case zindex option works correctly so bottom editor info toolbar also receives proper zindex.

It looks like in this case you need to increase zindex for the button 
https://jsfiddle.net/womjoy/ugpvjLma/9/ or move it to the next string with `<br>` to let it became visible and not covered by editor window with higher zindex - https://jsfiddle.net/womjoy/ugpvjLma/11/

You also can potentially disable content of bottom panel like this - https://jsfiddle.net/womjoy/ugpvjLma/17/ but still extra `<br>` or higher zindex required there to make the button visible.
