### ISSUE TITLE
Froala 2.9.6 Enter/Return key wrong behavior 

### ISSUE THREAD

**Issue by huan9494** [froala/wysiwyg-editor#3593]
##### Expected behavior.
Enter/Return key behaves correctly.

##### Actual behavior.
No new line was inserted before the line that contains cursor

##### Steps to reproduce the problem.
[jsFiddle](https://jsfiddle.net/0bwr4snL/1/)
Steps:
- Put cursor before Mr. Edwin (last line) and hit Enter

##### Editor version.
2.9.6

##### OS.
MAC and Windows

##### Browser.
Google Chrome

**Comment by ilyaskarim** [comment]
https://github.com/froala/wysiwyg-editor/issues/3592
