### ISSUE TITLE
Language import does not seem to work

### ISSUE THREAD

**Issue by jmsche** [froala/wysiwyg-editor#3599]
Using Froala Editor v3.0.4 (imported via yarn & bundled using Webpack) in combination with Symfony kms/froala-editor-bundle v3.0.1.

To improve performances, I'd like to import Froala's CSS/JS in my webpack config.

Everything seems to work correctly, but languages wouldn't :/  
I think I'm missing something for the language import but I don't see what.  
Plugins seem to work as expected.

Here is my JS file:

```js
import FroalaEditor from 'froala-editor/js/froala_editor.pkgd.min.js';
import 'froala-editor/js/languages/fr.js';
import 'froala-editor/js/plugins.pkgd.min.js';
import "froala-editor/css/froala_editor.pkgd.min.css";
import "froala-editor/css/plugins.pkgd.min.css";
import "froala-editor/css/froala_style.min.css";
window.FroalaEditor = FroalaEditor;

function froalaDisplayError(p_editor, error ) {
    alert(`Error ${error.code}: ${error.message}`);
}
```

Note that when I disable this & import the files using the bundle the correct language is displayed (french in my case).

##### Expected behavior.
French language should be used

##### Actual behavior.
English language is actually used

**Comment by casualuser** [comment]
Hello,
It is not so easy to determine if this related to bundling options or something else.
Please create codesandbox.io sample or share a repo with simple code to reproduce this issue.

**Comment by jmsche** [comment]
Hi, thanks for the feedback.

Here is a reproducer: https://github.com/jmsche/froala-language-reproducer

I don't think it has anything to do with the bundle, I think it's related to how things are loaded using webpack :/ The reproducer I linked above has no dependencies on Symfony or the KMS bundle.

**Comment by jmsche** [comment]
Fixed it by fixing this line: `import FroalaEditor from 'froala-editor/js/froala_editor.pkgd.min.js';`

Replaced by this: `import FroalaEditor from 'froala-editor';`

Apparently this is due to how the original Editor is loaded on this line: https://github.com/froala/wysiwyg-editor/blob/91aba2a9313abb48659737da8076678a952b7364/js/languages/fr.js#L8
