### ISSUE TITLE
Disable multiple editors

### ISSUE THREAD

**Issue by zbiller** [froala/wysiwyg-editor#3601]
Hi there,

I've been struggling with an issue for some time now and can't seem to find a solution.
The issue I'm experiencing is with disabling multiple editors.

I have a page with 3 editors (all initialised on `textarea.editor-input`) and I'm using the following code to disable them:

```
var editor = new FroalaEditor('textarea.editor-input');

editor.edit.off();
editor.edit.disableDesign();
```

When I try to load the page with the editors disabled, I receive the following error:

```
Uncaught TypeError: Cannot read property 'off' of undefined
```

**Very important to mention here, is that the exact code works fine if I only have one editor inside the page**

##### Expected behavior.
Disable all existing editors in page.

##### Actual behavior.
Throws error:
https://monosnap.com/file/Jqbqnpo4FG5x7C5HNRqD1vfEFg40EB
https://monosnap.com/file/ZVZuLUtQXxLTUFNYZs6wIL4r49v6sj

##### Steps to reproduce the problem.
- have 2 or more `textarea.editor-input` inside your html   
- initialize FroalaEditor on the textareas   
- apply the above code to disable the editors

##### Editor version.
 v3.0.0

##### OS.
macOS Mojave   
version: 10.14.6

##### Browser.
Google Chrome    
Version 75.0.3770.142 (Official Build) (64-bit)

##### Recording.

https://monosnap.com/file/wJgWUdsEHLgqD5pvViMX0M7IJ9w2NU

Thanks in advance and hopefully somebody can help with this :)

**Comment by casualuser** [comment]
Hello,

It looks like this happens in case you calling editor functions before it completes initialization.
So you can use delays, wrap into function with callback or promise or even simply call this editor functions after initialization event fired like this:

```
var editor = new FroalaEditor('textarea.editor-input', {
  events: {
    'initialized': function () {
      this.edit.off();
      this.edit.disableDesign();
    }
  }
})
```

It works well for me here - https://jsfiddle.net/womjoy/y6chwjb2/48/

**Comment by MohamedMusthafaA** [comment]
when i am using scrollablecontainer, for popup overflow..in that particular pages it working fine..not able to find rich editor in other pages where i used before...only in  the page container class given for scrollable container  in config only i can see in the UI
