### ISSUE TITLE
Website for v2 broken (https://www.froala.com/wysiwyg-editor/v2.0)

### ISSUE THREAD

**Issue by jmiserez** [froala/wysiwyg-editor#3623]
##### Expected behavior.
https://www.froala.com/wysiwyg-editor/v2.0 should load the v2 editor.

##### Actual behavior.
No editor is loaded.

![image](https://user-images.githubusercontent.com/5045692/63590503-4a1d6d00-c5ac-11e9-9f25-027fda414b9d.png)

**Comment by jmiserez** [comment]
Sorry if this isn't the place to report this, but the v2 website has been broken for a while now. Would be nice to have it back again.

**Comment by chrisdeeming** [comment]
It would be nice if @stefanneculai and Froala acknowledged that - as good as Froala v3 is - they still have a significant commitment to support v2 users. Months without a bug fix release (though that problem pre-dates v3) and seemingly little interest in maintaining even their v2 version of the site is significantly disappointing.

**Comment by casualuser** [comment]
fixed
