### ISSUE TITLE
Froala editor code view Bug

### ISSUE THREAD

**Issue by jithinrajpr** [froala/wysiwyg-editor#3624]
##### Expected behavior.
After pasting `style` tag inside code or generating with some other HTML and when we click on code view it should show the code.

##### Actual behavior.
After pasting `style` tag inside code or generating with some other HTML and when we click on code view it breakes the editor and shows error - 
**Uncaught ReferenceError: isAfterSpace is not defined**

##### Steps to reproduce the problem.
**Here is a [fiddle](https://jsfiddle.net/jithinrajpr7/usd7pvra/) to check the bug.
Just click on the code view in the editor.**

##### Editor version.
Froala editor v3.0.5

##### OS.
ALL  OS

##### Browser.
ALL  Browser

**Comment by jithinrajpr** [comment]
@stefanneculai will you help me with this.?

**Comment by tetnobic** [comment]
I have exactly the same bug :(

**Comment by greggreenhaw** [comment]
I do as well its referenced and never defined

 preserveSingleSpace: function() {
                        isAfterSpace && _.singleSpace()
                    },

**Comment by kapil2704** [comment]
This bug has been resolved and will be available within one or two weeks in the newer version.
