### ISSUE TITLE
'destroy' doesn't properly cleanup all events

### ISSUE THREAD

**Issue by philfreo** [froala/wysiwyg-editor#363]
I haven't done a thorough check to see how many events still need to be cleaned up, but I did notice that the form `submit` event listener isn't cleaned upon destroy

http://jsfiddle.net/zm703hwf/

click init & destroy multiple times

**Comment by mbardelmeijer** [comment]
+1

**Comment by stefanneculai** [comment]
Fixed cf0cfe2b0ff19edb5fdf2ed559a2df9fb8fa6b81
