### ISSUE TITLE
Wrong FR translation

### ISSUE THREAD

**Issue by usb248** [froala/wysiwyg-editor#3630]
Hi,

Please fix wrong translation at https://github.com/froala/wysiwyg-editor/blob/master/js/languages/fr.js#L267.

Replace By: 
`'Characters': 'Caractères',`

Thanks

**Comment by kapil2704** [comment]
Hii @usb248 

Please check the google translation for this 

https://translate.google.com/?sl=fr#view=home&op=translate&sl=en&tl=fr&text=Characters

I think it is already what it should be.

**Comment by usb248** [comment]
@kapil2704 , i'm french and i can confirm you that is not the good translation. You are free to trust a machine rather than a Frenchman....

**Comment by kapil2704** [comment]
@usb248 I believe you (Verified via reversing https://translate.google.com/?sl=fr#view=home&op=translate&sl=fr&tl=en&text=Caract%C3%A8res) I just updated our base code with your character. Soon it will be available in v3.0.6
