### ISSUE TITLE
Additional hooks for custom save actions

### ISSUE THREAD

**Issue by philfreo** [froala/wysiwyg-editor#364]
I'm plugging in Froala into an existing app with more complex saving & autosaving, etc. and a few hooks are needed rather than just using Froala's built in autosave/save. 
- Ability to provide my own `save` function that would get called instead of the Froala built-in function that makes an AJAX request.

or
- An event that would get triggered anytime autosave wants to save, _instead_ of using the built-in save method

or
- Trigger an `input` or `change` event on the textarea anytime it is synced, or trigger some custom event like `editable.afterSync` (should only get called if the value of the textarea was actually changed)

Right now `getHTML` is sort kinda like this, but it's not really a good workaround since `getHTML` can get called at times _other_ than when a save is needed.

**Comment by Spankyed** [comment]
Need hook for custom save function. Or better documentation on how to cancel a save in the 'beforeSave' event so I can just use that as hacked solution.
