### ISSUE TITLE
Dragging an image inline removes <hr> tags

### ISSUE THREAD

**Issue by boviexiong** [froala/wysiwyg-editor#3642]
##### Expected behavior.
Drag an image from one position to another within the editor without affecting the <hr> tags

##### Actual behavior.
After dragging, all <hr> tags are removed

##### Steps to reproduce the problem.
1. go to https://www.froala.com/wysiwyg-editor/examples/drag-inline
2. insert a few horizontal lines
3. drag and drop the image to a different position within the text

##### Editor version.
Froala v2.8, v3

##### OS.
Windows 10

##### Browser.
Chrome

##### Recording.

![M7oYsVvmNj](https://user-images.githubusercontent.com/48688153/64107808-44c1de80-cd73-11e9-8a99-2d3db8c8d5e4.gif)

**Comment by casualuser** [comment]
fixed in 3.0.6

**Comment by codemzy** [comment]
I'm still getting this issue in v3.0.6 and v.3.1.0 😞

**Comment by codemzy** [comment]
> I'm still getting this issue in v3.0.6 and v.3.1.0 😞

Ok... so if you have custom `htmlAllowedEmptyTags` in your options, make sure you include 'hr' in the array, and that fixes it 👍
