### ISSUE TITLE
powered by froala not gone

### ISSUE THREAD

**Issue by littlehome-eugene** [froala/wysiwyg-editor#3652]
##### Expected behavior.
(Describe expected behaviour here)
I have license setup properly 
and attribution=false set,

`powered by froala` should be gone, but not

##### Actual behavior.
(Describe actual behaviour here)

##### Steps to reproduce the problem.
(Describe the steps to reproduce the problem here. A [jsFiddle](https://jsfiddle.net/froala/wc5c3jhk/) is awesome when possible.)
```
     config: {
       key: LICENSE_KEY.v2_8_upper,
       placeholderText: 'Edit Your Content Here',
+      attribution: false,
```

##### Editor version.
If you don't know it, please see https://wysiwyg-editor.froala.help/hc/en-us/articles/360000717049-How-can-I-find-my-editor-version-.
     "froala-editor": "^2.9.5",
     "react-froala-wysiwyg": "^2.9.5-1",
##### OS.
(OS name and version here)
mac high sierra

##### Browser.
(Browser name an version here)
chrome
##### Recording.
(A recording showing how to reproduce the problem)

**Comment by casualuser** [comment]
Hello,

We have checked here some moments and it looks like there is things mixed at your side.
In version 2.x there is no `attribution` option and `powered by froala` label in bottom panel.
So it looks like you're trying to use version 3.x with key from 2.x

Please contact our support team via https://wysiwyg-editor.froala.help and provide your key and version obtained via this commands in browser console:
for v2
```
$.FE.VERSION
$.FE.INSTANCES[0].opts.key
```
for v3
```
FroalaEditor.VERSION
FroalaEditor.INSTANCES[0].opts.key
```
