### ISSUE TITLE
additional classes with fr-* creates render problems

### ISSUE THREAD

**Issue by sujith66** [froala/wysiwyg-editor#3653]
##### Expected behavior.
. Froala should output html contents without adding any additional classes(fr-*) when saving to database
. Froala should output html contents without removing the <style> section when pasting html contents to the editor

##### Actual behavior.
. Froala adds additional style classes with fr-* which causes render problems while displaying the content.
. Froala removes the style section from html which includes media queries which creates problems while rendering in mobile devices

##### Steps to reproduce the problem.
Please insert the html code inside the fiddle to the editor and check for the behavior.
https://jsfiddle.net/yoh2t4s6/

##### Editor version.
Version 3.0

##### OS.
Windows 10

##### Browser.
Google chrome Version 76.0.3809.132 (Official Build) (32-bit)

**Comment by casualuser** [comment]
Hello,

To preserve `<style>` tags it should be removed from the default value of cleanup option `htmlRemoveTags` https://www.froala.com/wysiwyg-editor/docs/options#htmlRemoveTags

And to avoid using extra classes you need set this option to `false`
https://www.froala.com/wysiwyg-editor/docs/options#useClasses

Also if you want to keep pasted html maximum untouched then these options may help you with a such a task.

```
      fullPage: true,
      htmlAllowedTags: ['.*'],
      htmlAllowedAttrs: ['.*'],
      htmlAllowedStyleProps: ['.*'],
      htmlRemoveTags: ['script'],
      pasteAllowedStyleProps: ['.*'],
      pasteDeniedAttrs: [],    
      lineBreakerOffset: 0,
      lineBreakerTags: [''],
      htmlAllowComments: true
```

**Comment by sujith66** [comment]
Hi casualuser,

I have tried out all the options mentioned above in our code and  none of them have worked. I have used htmlUntouched to see if it preseves the code with in style tag but the editor still trims off the code when pasted.

Please let me know if there are any other solutions that can be tried out.
