### ISSUE TITLE
Blockquote doesn't apply to selection when paragraphy is turned off

### ISSUE THREAD

**Issue by MrAlexLau** [froala/wysiwyg-editor#366]
Blockquotes don't apply to selected text when the `paragraphy` option is turned off.

Steps to reproduce:
- Create an editor instance with the `paragraphy` option turned off
- Write a line of text, select it, and apply the Quote style
- Add a second line of text
- Write a third line of text, select it, and apply the Quote style

Expected result:
- The third line of text is in its own, isolated blockquote

Actual result:
- Both the second and third lines of text are applied to the blockquote
- Example (ignore my custom blockquote css styles):
![screen shot 2014-12-31 at 4 54 54 pm](https://cloud.githubusercontent.com/assets/75554/5591091/51e13882-910e-11e4-998f-11f3e481c643.png)

**Comment by stefanneculai** [comment]
Fixed cf0cfe2b0ff19edb5fdf2ed559a2df9fb8fa6b81
