### ISSUE TITLE
Image is resized to zero when pasted from MSWord

### ISSUE THREAD

**Issue by syedharishassan** [froala/wysiwyg-editor#3663]
We have noticed that the "imageDefaultWidth" property is causing few issues. The default value of this property as per your documents is 300. We have changed it to zero so that when user upload an image it wont get resized.

##### Expected behavior.
It should be working fine in all scenarios

##### Actual behavior.
It is working correctly in case of using upload image API from the editor. But now we are facing a problem that if we paste an image from MS Word after setting this property to zero, it is literally showing the pasted image of zero size.

##### Editor version.
froala_editor v2.8.4

##### Browser.
chrome, Firefox, IE

**Comment by casualuser** [comment]
Hello,

You're reporting this against version 2.8.4 but there is already 2.9.6 released and even 3.0.6
There is for sure few more fixes will be applied for 2.9.x till the end of this year but main supported version right now is 3.x
So please check how 2.9.6 and 3.0.6 works for you with "imageDefaultWidth" set and pasting images from MS Word.

**Comment by mhassanedev** [comment]
Hi @casualuser, this issue is still reproducible in Froala editor version 3.1.1

**Comment by ilyaskarim** [comment]
Hi there, The issue is not reproducible on our latest version V4.0.11.
You could test the behaviour on this demo: https://jsfiddle.net/froala/nsj2w4xf/.
