### ISSUE TITLE
Languages sourceMappingUrl

### ISSUE THREAD

**Issue by tommy-nf** [froala/wysiwyg-editor#3665]
Hello,
in all languages JS-Files is an including for the .map-Files
e.g. //# sourceMappingURL=ar.js.map

In Safari occurs a loading error.
Can you remove the sourceMappingUrl?

I think it is not necessary.

Thx
Thomas

**Comment by jrjohnson** [comment]
Same issues throws ugly warnings in an Ember build. Every language file seems to [have a reference to a sourcemap](https://github.com/froala/wysiwyg-editor/blob/master/js/languages/es.js#L269) that does not exist.

**Comment by Panman8201** [comment]
Confirmed, ember-cli seems to pickup on this and tries to import the map file (which doesn't exist). My guess is that other (smart?) build systems will run into this same issue.
