### ISSUE TITLE
simpleAmpersand is always true

### ISSUE THREAD

**Issue by philfreo** [froala/wysiwyg-editor#367]
According to https://editor.froala.com/options#simpleAmpersand the `simpleAmpersand` is false by default. However there appears to be a bug which _always_ causes ampersands to be non-HTML-encoded.

http://jsfiddle.net/xLs9mbyd/

**Comment by stefanneculai** [comment]
Fixed cf0cfe2b0ff19edb5fdf2ed559a2df9fb8fa6b81
