### ISSUE TITLE
How to dynamically modify the parameters of uploaded pictures

### ISSUE THREAD

**Issue by LIMr1209** [froala/wysiwyg-editor#3674]
froala_eidtor  version 2.8.3

.on('froalaEditor.image.inserted', function (e, editor, $img, response) {
            var obj = JSON.parse(response);
            phenix.record_asset_id('asset_ids', obj.data._id)
            editor_img += 1
            $('#edit').froalaEditor()
            editor.imageUploadParams["x:ord"] = editor_img
editor.imageUploadParams   is  undefined

**Comment by casualuser** [comment]
Hello,

In case imageUploadParams is editor option and not method so it should be used at the moment of editor initialization as it described here:
https://www.froala.com/wysiwyg-editor/docs/options#imageUploadParams

for 2.8.3 it will look like this:

$('#edit').froalaEditor({
  imageUploadParams: {
    'x:ord': editor_img
  }
})
