### ISSUE TITLE
UX: 'Text' should be default in color selection dropdown

### ISSUE THREAD

**Issue by Olliepop** [froala/wysiwyg-editor#368]
When selecting a colour from the dropdown, the default behaviour is to change the background/highlight colour. This is not very intuitive, and is a less common case than changing the color of text. 

![Background is the default selection](http://i.imgur.com/VcJ5Jho.png)

Therefore from a user experience perspective I propose that the default selection for the color dropdown be text.

I would submit a PR but unfortunately I don't have a source license (yet).

**Comment by stefanneculai** [comment]
On the master version from this repo it's already like this.
