### ISSUE TITLE
Frola

### ISSUE THREAD

**Issue by GULED251** [froala/wysiwyg-editor#3689]
##### Expected behavior.
(Describe expected behaviour here)

##### Actual behavior.
(Describe actual behaviour here)

##### Steps to reproduce the problem.
(Describe the steps to reproduce the problem here. A [jsFiddle](https://jsfiddle.net/froala/wc5c3jhk/) is awesome when possible.)

##### Editor version.
If you don't know it, please see https://wysiwyg-editor.froala.help/hc/en-us/articles/360000717049-How-can-I-find-my-editor-version-.

##### OS.
(OS name and version here)

##### Browser.
(Browser name an version here)

##### Recording.
(A recording showing how to reproduce the problem)

**Comment by GULED251** [comment]
[wysiwyg-editor-2.6.6.zip](https://github.com/froala/wysiwyg-editor/files/3682003/wysiwyg-editor-2.6.6.zip)
[wysiwyg-editor-2.6.6.tar.gz](https://github.com/froala/wysiwyg-editor/files/3682005/wysiwyg-editor-2.6.6.tar.gz)

**Comment by casualuser** [comment]
Hello

This doesn't look like an issue or feature request.
Please try to organize your new message request according to our issues template to receive some kind of feedback.
