### ISSUE TITLE
Version 2.9.6 released twice, or just lagging information?

### ISSUE THREAD

**Issue by Krisell** [froala/wysiwyg-editor#3697]
I just got a notice that v2.9.6 was released, and looking at the release-tab here, it was just released and has not been released before.

However, v.2.9.6 was released in june. Is this the same version or a new release? If it is a new release, please use version 2.9.7 for the release to play nicely with CDNs and dependency managers.

![image](https://user-images.githubusercontent.com/25909128/66401101-e24ba600-e9e2-11e9-9fa2-ed9674f0c639.png)

**Comment by casualuser** [comment]
Hello,

Last week version 3.0.6 has been released and 2.9.6 still the latest version for v2
Also some works on website in progress now so potentially repeated release notice was triggered by 3.0.6 release or/and website updates.
