### ISSUE TITLE
Only one initialized event handler called

### ISSUE THREAD

**Issue by Panman8201** [froala/wysiwyg-editor#3698]
There seem to be two (documented) ways to create an `initialized` callback/handler.
1. `FroalaEditor('.selector', {events:{'initialized': function(){}}})` [events option](https://www.froala.com/wysiwyg-editor/docs/events#initialized)
2. `FroalaEditor('.selector', {}, function(){})` [third argument](https://www.froala.com/wysiwyg-editor/docs/methods#events.on)

However, only option 2 will be called if both ways are added (see jsFiddle below).

##### Expected behavior.
Both callbacks to be called (probably with option 2 being "first").

##### Actual behavior.
Only option 2 will be called, option 1 is never called.

##### Steps to reproduce the problem.
https://jsfiddle.net/Panman8201/mwnbs9r6/2/
Remove the third argument (function) and notice that the event from the options block now runs.

##### Editor version.
3.x

##### OS.
Both Mac OS X & Windows 10

##### Browser.
Only tested on Chrome (latest)

##### Recording.
NA

**Comment by Panman8201** [comment]
This causes difficulty when trying to make integrations (at least for ember). I'd like to reserve the `options.events = {}` block for all incoming event callbacks and use the third argument callback specifically for the addon/plugin/integration setup needs. For example, usage with the ember integration would look something like:

```hbs
<FroalaEditor
    @content={{this.contentString}}
    @options={{this.optionsObject}}
    @on-initialized={{this.initCallback}}
    @on-contentChanged={{this.updateContentCallback}} />
```

So what I'd like to do is throw those event callbacks (`initialized` and `contentChanged`) into the `events` block, something like:

```js
let options = Object.assign(
    {}, // so we don't reference an original obj
    this.args.options, // this is @options from above
    { events: {
        'initialized': this.args['on-initialized'], // @on-initialized from above
        'contentChanged': this.args['on-contentChanged'] // @on-contentChanged from above
    }}
);
```

Finally I'd use the third argument / callback for other addon/plugin/integration needs:

```js
FroalaEditor('.selector', options, function() {
    // do stuff here
});
```

Why not add the addon initialization setup to the `options.events` block you ask? Because I don't want to trample on a passed in callback shown in the second code example above.

**Comment by casualuser** [comment]
@kapil2704 please check this - we need it for Ember

**Comment by Panman8201** [comment]
So interestingly if you look to `options.events.initialized` from within the third argument callback, it seems to reference itself. So, if there was an `options.events.initialized` to begin with, where did it go? Ex: https://jsfiddle.net/Panman8201/mwnbs9r6/8/

```js
var options = {
    events: {
        'initialized': function optionsInit() {
            window.alert('here I am!');
        }
    }
};

var editor = FroalaEditor('.e', options, function callbackInit() {
    options.events.initialized;
    debugger;
    // options.events.initialized is callbackInit(), THIS function..., where did optionsInit() go?
});
```

It seems like the editor is overriding whatever was passed in for options, even changing it to a reference. Instead, what I'd expect is the editor to look to the options on initialization and use the `events.on()` method to push callbacks onto the stack. Something like;

```js
FroalaEditor = function(selector, options, callback) {
    // whatever to get the `editor` variable with access to the methods
    for (let eventName in (options.events || {})) {
        editor.events.on(eventName, options.events[eventName]);
    }
    if (callback) {
        editor.events.on('initialized', callback, true); // true to run first
    }
};
```

**Comment by kapil2704** [comment]
Right now code is like below:

if (initCallback) {
    if (!options.events) options.events = {}
    options.events.initialized = initCallback
  }

**Comment by kapil2704** [comment]
@Panman8201  will it work for you if we make option.event take precedence than the third argument for initialized event? 

If you want both 'initialized' events to be called i think it can be handled within ember integration as well.

**Comment by Panman8201** [comment]
> will it work for you if we make option.event take precedence than the third argument for initialized event?

Naw, that's actually the opposite direction I go with it. Just seems funny if both are defined that only the callback is used (and referenced from the options).

> If you want both 'initialized' events to be called i think it can be handled within ember integration as well.

Yeah, I certainly can work around the two issues from within the ember integration (and am doing so at this point), it's just not as clean if these two issues were fixed in the editor itself (it causes some extra wrapping and such).

**Comment by kapil2704** [comment]
@Panman8201 Same for this too.
