### ISSUE TITLE
Custom uri without slashes is escaped

### ISSUE THREAD

**Issue by xmedeko** [froala/wysiwyg-editor#3702]
##### Actual behavior.
I have added a file: schema to allowed URIs (and a few more schemas) to `FroalaEditor.LinkProtocols`. When I enter URI with slashes, e.g. `file:///c:/file.txt`, then it's not encoded/escaped, when I enter URI without slashes `file:c:/file.txt` then it's escaped.

##### Expected behavior.
Do not escape URIs without slashes.

BTW. why not to use `encodeURI` instead of `encodeURIElements` ?

##### Editor version.
v3.0.5

##### Browser.
Electron, Chrome

**Comment by jmiserez** [comment]
I just debugged this in-depth recently. The main goal of sanitizeURL seems to be to escape "javascript:" and "data:text/html;..." URIs, which could contain JS.

**Comment by xmedeko** [comment]
Yeah, these should be escaped, but not the `FroalaEditor.LinkProtocols`.

**Comment by xmedeko** [comment]
@casualuser IMO this is not enhancement, this is bug. FroalaEditor is unusable for custom URIs without slashes. E.g. `onenote:` URIs.

**Comment by kapil2704** [comment]
Hi @xmedeko ,

I am curious to know what are use cases to allow custom URI's with these use cases,.

Thanks,
Kapil Garg
Froala Architect

**Comment by xmedeko** [comment]
@kapil2704 the reason is app integration, e.g. see [Hyperlinking Beyond the Web](https://css-tricks.com/hyperlinking-beyond-the-web/). Our particular use case is link documents (a kind of DMS) in Electron.js. A user may create a custom app link in Froala editor and then click it to open the document. OS opens a proper app for that. Usually, our users use `file:` scheme, but would like to use a few other schemes, too, like `onenote:`.

**Comment by kapil2704** [comment]
Hello @xmedeko ,

Thank you for your response. I see how it can be useful for you. will it work for you if we use encodeURI instead of encodeURIComponent ? or if it gives an output of "onenote:c:%5Cmy_files%5Cfroala.txt" for this type of URLs "onenote:c:\my_files\froala.txt"?

Thanks,
Kapil Garg
Froala Architect

**Comment by xmedeko** [comment]
@kapil2704 yes, `encodeURI` works well. I do not know what all types of security attacks do you address in your code, so cannot help you is you can use `encodeURI` of just remove slashes after the colon in the regex you have mentioned.

**Comment by kapil2704** [comment]
Hi @xmedeko ,

Is it possible for you to use method decodeURIComponent for the URL's before redirecting them to other Apps ?

**Comment by xmedeko** [comment]
@kapil2704 the problem is not only in the redirect, but he problem is for the user to edit the link, the problem is in the inconsistent Froala behaviour. Do the following:
1. Create link to `file:///c:/file 1.txt`, edit that, you see the link `file:///c:/file 1.txt` ✔️ 
2. Create link to `file:c:/file 1.txt`, edit that, you see the link `file:c%3A/file%201.txt` ❌ 

Apparently, it's not a behaviour you expect form a (paid!) SW component.

**Comment by kapil2704** [comment]
Dear @xmedeko,

Its not inconsistent behaviour its just encoding of things when it detects it is not URL just to avoid several security attacks because we have regex which will enforce to have  // after :  if it falls under url category.

**Comment by kapil2704** [comment]
@xmedeko We have decided to not encode URL's which are not just ending with //. So it is fixed for you. You will get this updated in v 3.0.8. meanwhile you can use js file from github. and here is link related to commit https://github.com/froala/wysiwyg-editor/commit/49fdbe2862db27a92beda0be6c022e88fe72751d

**Comment by xmedeko** [comment]
@kapil2704 OK, thanks, I will wait for the 3.0.8 release.
FYI: you have to distinguish URL and URI. It's a common mistake to treat both same. **They aren't!** URIs do not need to have slashes, e.g. see https://en.wikipedia.or/wiki/Uniform_Resource_Identifier#Definition - the **authority is optional** and it's often missing in application URIs (e.g. mailto:, tel:, ...)

**Comment by kapil2704** [comment]
I got it @xmedeko , Thanks for sharing this.

**Comment by xmedeko** [comment]
@kapil2704 I've downloaded v3.1.0 and it's fixed, thanks.
