### ISSUE TITLE
Initialize callback (third argument) follows 'initOnClick' option

### ISSUE THREAD

**Issue by Panman8201** [froala/wysiwyg-editor#3704]
Regarding the timing of the third argument / callback in `FroalaEditor('.e', {}, function(){ /*this*/ })`. Currently it's set to the timing of the `initialized` event but I think that is incorrect semantics because it is not called right away when the `initOnClick` option is used. Instead, that third argument/callback should _always_ be called right away and users can use the options `events` for the original timing between `initialized` and `initializationDelayed`.

##### Expected behavior.
The third argument as a callback to fire right away, no matter what the options are.

##### Actual behavior.
When `initOnClick` is true, the callback is not called until the editor area is clicked.

##### Steps to reproduce the problem.
https://jsfiddle.net/Panman8201/dc83fpkq/2/

##### Editor version.
3.x

**Comment by Panman8201** [comment]
This causes difficulty when trying to make integrations (at least for ember). I'd like to reserve the `options.events = {}` block for all incoming event callbacks and use the third argument callback specifically for the addon/plugin/integration setup needs. I can try to provide some example code if it'll help clarify my point.

**Comment by casualuser** [comment]
@kapil2704 please check this - we need it for Ember

**Comment by Panman8201** [comment]
Actually, this might be Ok. Because `editor.html.set()` doesn't seem to be available until initialization. I need to do some more testing tomorrow and will report back here.

**Comment by Panman8201** [comment]
Nope, it would be better tuned to `(options.initOnClick ? 'initializationDelayed' : 'initialized')`. I did some testing and `editor.html.set()` is available from either of those events, and since `initializationDelayed` would come before `initialized` it would be better to get the `editor` at that time.

https://jsfiddle.net/Panman8201/dc83fpkq/13/

**Comment by kapil2704** [comment]
> Nope, it would be better tuned to `(options.initOnClick ? 'initializationDelayed' : 'initialized')`. I did some testing and `editor.html.set()` is available from either of those events, and since `initializationDelayed` would come before `initialized` it would be better to get the `editor` at that time.
> 
> https://jsfiddle.net/Panman8201/dc83fpkq/13/

So @Panman8201 I guess you can work around for a way to get it working without any need to change anything editor itself. So i will be closing this request for now.
