### ISSUE TITLE
How to get a editor example outside

### ISSUE THREAD

**Issue by LIMr1209** [froala/wysiwyg-editor#3705]
![2019-10-14](https://user-images.githubusercontent.com/37957822/66737370-5cc26d00-ee9e-11e9-9ff9-1a4444959367.png)

v 2.8.1
editor is a example  but  froala is not

**Comment by casualuser** [comment]
Hello,

You can use global scope via window.* for referencing, check here - https://jsfiddle.net/oy0423ud/
And also it's better to use shorter chains of code for events.
