### ISSUE TITLE
Full screen button is disabled when an image is selected

### ISSUE THREAD

**Issue by jipigi** [froala/wysiwyg-editor#3708]
##### Expected behavior.
Full screen button should always be available to let user open or leave the full screen mode at anytime.

##### Actual behavior.
When a image is selected, full screen button is disabled : 
https://i.imgur.com/hAray1o.png
When a video is selected, full screen button is disabled : 
https://i.imgur.com/zA44An3.png

##### Steps to reproduce the problem.
- Add an image or a video in the editor
- Open the sub-menu containing the full screen button (optional)
- Select the image or the video 

##### Editor version.
3.0.6

##### OS.
All but i'm on windos 10.

##### Browser.
All but i was on Chrome.

##### Recording.
https://i.imgur.com/4PvG2h7.gifv

**Comment by casualuser** [comment]
Hello,

Actually this is not a bug but completely expected tollbars behavior by design. When image or videos popup toolbars activated then the main toolbar with the fullscreen button will be disabled until this popup toolbars became hidden.

**Comment by jipigi** [comment]
Hello,

I understand and approve this behaviour for all other toolbar buttons. You don’t want user to push the bold button while an image is selected for example.

But the full screen button is anti je r story as you could need to exit full screen at any time, even while an image is selected.

Does it make sense to you ?
