### ISSUE TITLE
URLs with @ in them incorrectly get parsed as mailto links

### ISSUE THREAD

**Issue by philfreo** [froala/wysiwyg-editor#371]
Medium uses the `@` character in their URLs.

1. In Froala editor highlight some text to make it a link
2. Paste the URL `https://medium.com/@handstandapp.com` into the spot for the URL
3. Notice that Froala incorrect made this a `mailto:` link.

**Comment by stefanneculai** [comment]
Fixed cf0cfe2b0ff19edb5fdf2ed559a2df9fb8fa6b81

**Comment by mzane42** [comment]
Hi @stefanneculai, do you know if this problem is solved in froala 3, because i have the same problem in 2020 :)  hope you can help me ! thanks
