### ISSUE TITLE
Unexpected auto-formatting of BR tags

### ISSUE THREAD

**Issue by RodionM** [froala/wysiwyg-editor#3714]
##### Expected behavior.
Put any HTML as data source for Froala and switch to code view - self closing BR tags stay self closing.

##### Actual behavior.
Put any HTML as data source for Froala and switch to code view - self closing BR tags become usual BR tags.
So `<br />` tags becomes `<br>` tags

It looks like a standard behavior.
Is it possible to disable it?
If not, how does Froala do it?

**Comment by casualuser** [comment]
Hello,

So actually there is nothing special Froala Editor does with `<br>` tag but that's how html specification declare it.
Take a look here - https://www.w3schools.com/tags/tag_br.asp

> The <br> tag is an empty tag which means that it has no end tag.

> In HTML, the <br> tag has no end tag.
> In XHTML, the <br> tag must be properly closed, like this: <br />.

So Froala Editor follows html specification and at the moment doesn't support xhtml/xml compatible mode. In this case somewhere in code rendering functions `<br />` became converted into `<br>`.

Potentially this may be changed in future and xhtml/xml compatibility mode option will be introduced. 
Feel free to create a feature request in features list here https://wysiwyg-editor-roadmap.froala.com/public and promote it for voting.
