### ISSUE TITLE
Please continue supporting Froala v2 and release the update you originally scheduled for September

### ISSUE THREAD

**Issue by chrisdeeming** [froala/wysiwyg-editor#3725]
@stefanneculai the level of support for v2 has significantly dropped off (even before v3).

Updates are being released for it at an unacceptable rate with the last update being in June.

You have customers relying on continued support and fixes for v2 and we have many thousands of customers similarly relying on a stable rich text editing experience which they are not currently getting.

2.9.7 was originally going to be released in September. It didn't happen. I asked nearly 3 weeks ago when in October it would be released. It didn't happen.

I hope you can take this opportunity now to advise your customers when you will be releasing 2.9.7 and fixing other related issues such as #3623.

**Comment by pleunv** [comment]
Both v2 & v3 seem to be getting very little support. v3 issues aren't getting any feedback, there's no roadmap or communication whatsoever, we're stuck on v2 because of various bugs and it's getting increasingly frustrating. It honestly feels like they've slowly been giving up on this project. If this is the case it'd be at least nice to get an official statement.

**Comment by casualuser** [comment]
@pleunv we're hardly working on making v3 works stable after the transition from jQuery
there will be 3.1 with all CMS/Frameworks integrations and SDKs updated in the middle of January
at the moment it's in code freeze and testing flow

we also going to release 2.9.7 soon (works already started) and include there as many fixes as will be allowed by timeframe

**Comment by casualuser** [comment]
so https://github.com/froala/wysiwyg-editor/issues/3623 fixed and 2.9.7 in process
please keep watching our blog for new v2 release in the nearest time

**Comment by gagagast** [comment]
@casualuser Is there a release date planned for 2.9.7 ?
