### ISSUE TITLE
Copy paste from a word include some picture into Froala .A duplicate and not the original image appears

### ISSUE THREAD

**Issue by zhaoyouliang** [froala/wysiwyg-editor#3729]
![froala_paste_issue](https://user-images.githubusercontent.com/8610227/68648486-6f8e9700-055b-11ea-8768-5e39f193d7d9.png)
### _If you have a feature suggestion, please add it on the [Feature List](https://wysiwyg-editor-roadmap.froala.com/public) instead._
[Test copy this document and paste to Froala editor.docx](https://github.com/froala/wysiwyg-editor/files/3834716/Test.copy.this.document.and.paste.to.Froala.editor.docx)

copy the attachment doc and paste to froala
##### Expected behavior.
(Describe expected behaviour here)
will display original image
##### Actual behavior.
(Describe actual behaviour here)
display another duplicate picture.
##### Steps to reproduce the problem.
(Describe the steps to reproduce the problem here. A [jsFiddle]
you can paste this document to Website demo

[](url)

**Comment by casualuser** [comment]
Hello,

We checked your MSWord example document with images inside and discovered that there are really two images. And more of that one image has offset settings.
Take a look at this animation - http://recordit.co/vxa4BPvZxH
So here the Editor doing exactly what you're asking to do - pasting two images and in case that custom offset is not supported for <img> tags styling then you're receiving it without offset.

Potentially there are some ways to achieve a similar offset effect for <img> elements but it's requiring additional container elements wrappers and some custom CSS to make the trick.

If you have any good user story with tech details regarding how to support this without breaking simple things then we will be glad to implement this enhancement.
