### ISSUE TITLE
Tabbing into an editor should put cursor at top

### ISSUE THREAD

**Issue by philfreo** [froala/wysiwyg-editor#373]
Tabbing into an editor should put the cursor at the very beginning of the content.

http://jsfiddle.net/t9cg5yL9/

1. put cursor in first input box
2. hit tab

expected: cursor at the very top 

actual: cursor on the first line of text

Related to #335

**Comment by stefanneculai** [comment]
See c8e65b1fa2ce61303862d55813a32d2adca24986
