### ISSUE TITLE
HTML set via setHTML isn't cleaned up nicely as initial textarea html value

### ISSUE THREAD

**Issue by philfreo** [froala/wysiwyg-editor#374]
http://jsfiddle.net/zzoLnkv8/

The top textbox shows some (ugly/invalid) HTML that ideally Froala will do the best job it can with displaying.

The first Froala editor takes this HTML via the `<textarea>`'s starting value, and it nicely shows the content. This is the desired behavior!

The 2nd Froala editor takes the same HTML via `setHTML` but it seems to choke on the HTML rather than displaying it nicely.

Shouldn't both methods have the same result? (Ideally the one where "This text should appear on top" appears on top)

**Comment by stefanneculai** [comment]
See c8e65b1fa2ce61303862d55813a32d2adca24986
