### ISSUE TITLE
Prevent newline on enter, send instead

### ISSUE THREAD

**Issue by ARMATAV** [froala/wysiwyg-editor#3745]
##### Expected behavior.
When we type out a sentence `hello hello hello|` and we navigate our cursor to the center of the sentence `hello h|ello hello` and hit enter - we should send the text.

```
hello hello hello
```

##### Actual behavior.
The line breaks in the center of the text, and then the send event is triggered.

```
hello h
ello hello
```

##### Steps to reproduce the problem.
1. Type out `hello hello hello`
2. Move the cursor to the center of the sentence
3. Hit enter
4. It line breaks by default

##### Editor version.
v3.0.5

##### OS.
macOS 10.14.2

##### Browser.
Google Chrome

##### Recording.
![inputgif](https://user-images.githubusercontent.com/2433203/69470579-674d0d80-0d4c-11ea-81f7-5680cc8ccc0d.gif)

Here's the editor config

```js
  tabSpaces: false,
  events: args.events,
  placeholderText: '',
  htmlRemoveTags: ['img', 'script', 'style'],
  immediateReactModelUpdate: false,
  typingTimer: 1000,stack
  heightMin: 50,
  heightMax: 150,
  linkAlwaysBlank: true,
  attribution: false,
  htmlAllowedTags: [
    'b',
    'a',
    'i',
    'em',
    'u',
    'mark',
    'ul',
    'ol',
    'li',
    'strong',
  ],
  shortcutsEnabled: ['alert', 'bold', 'italic', 'underline', 'undo', 'redo'],
  pluginsEnabled: ['link', 'emoticons', 'url', 'spell_checker'],
  toolbarButtons: ['emoticons', 'bold', 'italic', 'underline', 'insertLink'],
  toolbarBottom: true,
  linkInsertButtons: ['linkBack'],
  emoticonsStep: 4,
  emoticonsUseImage: false,
  linkConvertEmailAddress: false,
```

**Comment by ARMATAV** [comment]
@willbryk720

**Comment by dejanmartinovic** [comment]
@ARMATAV Maybe you could try to disable multiLine: `multiLine: false`
https://www.froala.com/wysiwyg-editor/docs/options#multiLine

**Comment by vibhor1997a** [comment]
We're evaluating Froala and trying to create send functionality on cmd+enter/ctrl+enter. We have added keydown in events like below:

                     keydown: (e) => {
                    if ((e.ctrlKey || e.metaKey) && e.keyCode == 13) {
                        e.preventDefault();
                        e.stopPropagation();
                        // our send logic here
                        return false;
                    }
                }

Send works but it creates a new line before send. Is there any workaround?

**Comment by rizalrhmn** [comment]
hi, i'm facing the same issue. adding multiline false still don't make it. 

Sending is success, but it always create a new line. Is there any workaround?

**Comment by rizalrhmn** [comment]
I find the solution. Don't return false after adding multiline false, then now the enter key is working as expected!

```
if (e.keyCode === 13) {
     handleAction;
    //dont return false here if adding multiline false
} 
```

**Comment by muralimallow** [comment]
@dejanmartinovic We support multiple lines then how to prevent adding BR tag for the cursor position

**Comment by milos-rad** [comment]
I am presenting one of the solutions.

```
  const [model, setModel] = useState('');

  // Inside froala config file
   ...
   events: {
      keydown: onKeyDownHandler
    },
   ...
  
  // Handler definition. When there is only "enter" event, it will set windows variable.
  const onKeyDownHandler = (evt) => {
    window.isEnterPressed = evt.keyCode === 13 && !evt.altKey && !evt.shiftKey && !evt.ctrlKey ? true : false;
  };

  // If enter key is pressed, it will call submit function, else keep setting model value
  const onModelChange = (v) => {
    window.isEnterPressed ? onSubmit(model) : setModel(v);
  };
```

This code will submit the text when "enter" key is pressed, but with "shift" + "enter" will insert new line.
Hope this will help you.

**Comment by imransilvake** [comment]
None of the solution is working with multiline: true. It create a new line on Enter.

**Comment by dennis-f** [comment]
The way it worked WITHOUT a newline for me was this:

```ts
export class MyComponent implements OnInit {
  /* reference to the actual froala editor, this enables us to use the */
  private froalaEditor: any;

  protected config: any;
	
  protected disabled = false;

  ngOnInit() {
    const that = this;

    this.config = {
      // ...
      events: {
        initialized: function (e: any) {
          that.froalaEditor = this;
          if (that.disabled) {
            this.edit.off();
          }
          // `keydown` is the only event that is triggered if special characters are
          // pressed (Shift, Ctrl, Backspace, Del ...)
          //
          // Also handle keydown event here, because this will prevent adding a new line before actually sending.
          this.events.on(
            'keydown',
            (event: KeyboardEvent) => {
              const { key, shiftKey } = event;

              if (!shiftKey && key === 'Enter') {
                event.preventDefault();
                event.stopPropagation();

                // custom logic here

                return false;
              }
              return true;
            },
            true, // 👈 this is important
          );
        },
      },

      // ...
    };
  }
}
```

I used an anonymous function instead of an anonymous big arrow function, because I also needed a reference in my component to the froalaEditor to control it from the outside using `@Input()` fields. I should also work using a big arrow function if that is not needed.
