### ISSUE TITLE
Enter before or after a table cannot be deleted.

### ISSUE THREAD

**Issue by amitmoondra** [froala/wysiwyg-editor#3746]
I entered only a table in the editor.
and then added a empty space line on top of the table (pressed enter).
Its impossible to delete that enter specified on top of the table, cannot delete it with backspace or delete button.
Please suggest a solution

**Comment by ilyaskarim** [comment]
Not reproducible on latest V4.0.14 https://jsfiddle.net/froala/nsj2w4xf/
