### ISSUE TITLE
Don't break OS X control- keyboard shortcuts

### ISSUE THREAD

**Issue by philfreo** [froala/wysiwyg-editor#376]
http://support.apple.com/en-us/HT201236

OS X supports some control- readline/emacs-like shortcut keys everywhere. It works in `<textarea>`s. But Froala breaks them, probably b/c it's wanting to bind those shortcuts (e.g. Control-B) on Windows for something else like Bold.

You shouldn't break any of the OS X text editing keyboard shortcuts. You should only bind Control- shortcuts for Froala formatting on Windows. On Mac, it should only bind Command- for Froala formatting shortcuts.

Test env: http://jsfiddle.net/9412nx1x/

**Comment by stefanneculai** [comment]
Fixed 78cfc87d2dd4e81f805d675f350351ac6ae79562. Nice catch :+1:

**Comment by philfreo** [comment]
Thanks!!

Looks like Control-k is still masked though.

**Comment by stefanneculai** [comment]
278df4978ed8059b1a30d77a80f4c38baff418d2 fixes that.
