### ISSUE TITLE
Froala init on image - Failed to execute 'send' on 'XMLHttpRequest' 

### ISSUE THREAD

**Issue by armin1853** [froala/wysiwyg-editor#3760]
after uploading a new image using init on image, image is not inserted and this error is thrown in the console :

> Uncaught DOMException: Failed to execute 'send' on 'XMLHttpRequest': The object's state must be OPENED.

the error also exists on the example link . 
https://www.froala.com/wysiwyg-editor/examples/init-on-image.

so, what's the solution?

**Comment by casualuser** [comment]
hello,
it seems that's the problem of demo installation
please check this jsfiddle - https://jsfiddle.net/froala/vLbdrsje/
it works well

**Comment by armin1853** [comment]
hello again. thanks @casualuser .
but in jsfiddle - https://jsfiddle.net/froala/vLbdrsje/, it doesnt upload the image. try a big size image. without uploading, instantly the image will be inserted to the view. 
the error is gone because nothing gets uploaded. if you use froala demo version without upload options (without backend manipulations ) you see something like jsfiddle. 

on this page
https://www.froala.com/wysiwyg-editor/examples/init-on-image
the upload progress gets completed but the image wont be inserted.

**Comment by armin1853** [comment]
thanks to froala. 
in version 3.0.1 the error is gone. 
well done.
