### ISSUE TITLE
After for Submit Editor fails to trigger change events

### ISSUE THREAD

**Issue by NoSoup4you2** [froala/wysiwyg-editor#3764]
##### Expected behavior.
Any Edit / change in the HTML editor should fire a change event.

##### Actual behavior.
On initial load the events will fire just fine. But when you hit submit bttn this is no longer the case. If you have a 2 word text and add an s to end it will not fire. If you go and press enter in the Editor and type on new line it does same goes if you insert image or so.

##### Steps to reproduce the problem.
Enclosed is a stackblitz sample. On initial load you can go and one or 2 char to editor and you will see in console the prestine status printed. Now click on save which does nothing else then set prestine to true and add 1 or 2 char at end of text. Nothing fires. If you hit enter it will fire again.

[StackBlitz Sample](https://stackblitz.com/edit/angular-froala-v3-custombutton-dynamic-macatm)

##### Editor version.
3.0.X

##### OS.
Windows 10

##### Browser.
Chrome

##### Recording.
(A recording showing how to reproduce the problem)

**Comment by casualuser** [comment]
Hello Alex, 
It looks like this question was resolved via zendesk ticket so I'm closing issue here.

**Comment by thenitai** [comment]
And what was the solution?
