### ISSUE TITLE
Unexpected result when creating a list

### ISSUE THREAD

**Issue by philfreo** [froala/wysiwyg-editor#377]
I'm not positive if you consider this a bug based on the markup, but my coworker somehow ended up (starting from a blank Froala editor) with the markup similar to what you see here and then was unable to make a list.

http://jsfiddle.net/ttrkobmr/

1. Highlight lines One Two Three
2. Click Numbered List

Excepted: 3-item list from those 3 selected lines

Actual: entire content becomes a 1-item list

Chrome

**Comment by stefanneculai** [comment]
Selecting list for the HTML from jsFiddle works fine. However, it shouldn't be allowed to get to that HTML. We're working on improving the way tags are cleaned so that list would work fine even in this case. Probably there will be few days until we get an update for that.

**Comment by philfreo** [comment]
![screenshot 2015-01-10 11 22 19](https://cloud.githubusercontent.com/assets/97612/5692856/f3fd8ff4-98ba-11e4-9c08-bf166cb5e65c.png)

Here's what I get in Safari

**Comment by stefanneculai** [comment]
How have you got to it in Safari? We tried (Firefox, Chrome and Safari), but couldn't get to that.

**Comment by philfreo** [comment]
https://www.dropbox.com/s/i9vm6v5bvr1ewsf/list%20bug.mov?dl=0

Safari 8.0.2 on Yosemite

**Comment by stefanneculai** [comment]
Sorry, I believe I was not clear enough. How have you got to that HTML starting from a blank editor?

**Comment by philfreo** [comment]
Oh, not positive exactly how. Might have involved pasting from website content. Regardless, would be nice if the list bit was fixed.

**Comment by philfreo** [comment]
Hmm, I'm not seeing the fc931e9 commit that closes this anywhere?

**Comment by stefanneculai** [comment]
Sorry, it is not closed.

**Comment by stefanneculai** [comment]
Fixed 2d022a08f678ac658136e720d64e263e30206c83.
