### ISSUE TITLE
Focusing `focus()` a element in custom button callback doesnt work on mobile

### ISSUE THREAD

**Issue by Lee1984** [froala/wysiwyg-editor#3779]
##### Expected behavior.
On mobile (not native app) we should be able to `focus()` a element of choice in a custom button callback. On desktop it works fine. I was able to focus other elements, not froala related, so it seems to be froala related. Possibly because we need to press and hold on mobile?

##### Actual behavior.
In the callback we target the element and `focus()` `this.$tb.find("input.giphy_search_field").focus()` but the focus (caret) still remains in the editor

##### Steps to reproduce the problem.
    FroalaEditor.RegisterCommand('giphyIcon', {
      title: 'Giphy',
      icon: 'giphyIcon',
      undo: true,
      popup: true,
      plugin: 'giphyPlugin',
      showOnMobile: true,
      refreshAfterCallback: true,
      callback: function () {
        /* Toggle the giphy button */
        if (!this.popups.isVisible('giphyPlugin.popup')) {
          this.giphyPlugin.showPopup();
          this.$tb.find("input.giphy_search_field").focus()
        } else {
          if (this.$el.find('.fr-marker')) {
            this.events.disableBlur();
            this.selection.restore();
          }
          this.popups.hide('giphyPlugin.popup');
        }
      },
    });
##### Editor version.
3.0.6

##### OS.
Android 8.0

##### Browser.
Chrome 79.0.3945.93

**Comment by casualuser** [comment]
hello,
Can you please create a repro with this sample in basement - https://stackblitz.com/edit/angular-froala-wysiwyg

**Comment by Lee1984** [comment]
@casualuser I created the fiddle [froala angular](https://stackblitz.com/edit/angular-froala-wysiwyg-pep6ce?file=demo%2Fsrc%2Fapp%2Fapp.component.ts)
I added the line 
`if (this.$tb.find("input.giphy_search_field").is(":focus")) { alert("hello")};`
And we get the alert. And I get it on my my app as well, so before I must have made a mistake maybe back to my original question, if i can
Is there some sort of touch mechanism froala employs that overrides the focus I am giving to the input?

**Comment by Lee1984** [comment]
Im going to close this as its more of a support question. Feel free to answer though
