### ISSUE TITLE
Creating a new list collapses blank lines

### ISSUE THREAD

**Issue by philfreo** [froala/wysiwyg-editor#380]
http://jsfiddle.net/uextyrue/

Before creating list:
![screenshot 2015-01-09 08 40 56](https://cloud.githubusercontent.com/assets/97612/5683266/4241a104-97db-11e4-9578-901c54975644.png)

After creating list:
![screenshot 2015-01-09 08 41 05](https://cloud.githubusercontent.com/assets/97612/5683267/43c440b8-97db-11e4-90de-8db27cd41be2.png)

**Comment by stefanneculai** [comment]
Fixed 2d022a08f678ac658136e720d64e263e30206c83
