### ISSUE TITLE
Toolbar buttons broken in 3.1

### ISSUE THREAD

**Issue by brpsmith** [froala/wysiwyg-editor#3801]
##### Expected behavior.
Prior config of toolbarButtons works. 

##### Actual behavior.
The following config of toolbarButtons worked prior to 3.1.  The following config no longer works:

`                toolbarButtons:     [['fontFamily', 'fontSize', 'paragraphFormat'],
                                     ['bold', 'italic', 'underline', 'strikeThrough', 'subscript', 'superscript'], [ 
                                     'align', 'outdent', 'indent', 'quote'], ['insertHR', 'insertLink', 'insertImage', 'insertVideo'], 
                                    ['fullscreen', 'selectAll', 'clearFormatting','print', 'help', 'html'], ['undo', 'redo'] 
                 ],`

##### Steps to reproduce the problem.
Attempt to use the above config with the editor.  My specific case is using the editor via react

##### Editor version.
3.1

##### OS.
Mac

##### Browser.
Chrome

##### Recording.
(A recording showing how to reproduce the problem)

**Comment by Dakkers** [comment]
@brpsmith did you fix this? I found similar behaviour.
