### ISSUE TITLE
Option to prevent links without schemes (e.g. autoprefix http://)?

### ISSUE THREAD

**Issue by philfreo** [froala/wysiwyg-editor#381]
If a user creates a link and types or pastes "google.com" as the URL then it results in a broken link since there's no `http://` prefix.

I understand that you can't always detect+autoprefix schemeless URLs with `http://` because people might be using Froala as a CMS tool where they want to link to relative paths/pages on their site (e.g. pasting `mypage.html` as the URL.

However for using Froala for cases like composing html email, it would be nice if there was an option to autoprefix schemeless urls with `http://` to prevent this user error.

Thoughts?

http://jsfiddle.net/d7e2vhcy/

**Comment by stefanneculai** [comment]
Makes sense. We'll add an option for it.

**Comment by stefanneculai** [comment]
025c959d60803c8db44e358c6f7a284d9260250a

**Comment by philfreo** [comment]
I'm assuming the usage is like:

`linkAutoPrefix: 'http://'`

Adding this option breaks mailto: links.

**Comment by stefanneculai** [comment]
Sorry, forgot about it. Please use 09136fd079d37a15609eda7d8e66e29370d811e7

**Comment by philfreo** [comment]
:+1:
