### ISSUE TITLE
Can't type text after adding image

### ISSUE THREAD

**Issue by MahaloBay** [froala/wysiwyg-editor#3812]
##### Expected behavior.
Adding text after adding image.

##### Actual behavior.
I not possible to type text after adding image.

##### Steps to reproduce the problem.
1 . Type text 
2. Insert Image
3. Try to retype text (not working)
4. If you click outside editor and try to retype, it's working

![1](https://user-images.githubusercontent.com/10001667/72879409-167e7480-3cfd-11ea-9398-ffdcc1ea5efa.gif)

I try to solve the problem with enable imageAddNewLine but it doesn't work.
(like issue #3346 )

##### Editor version.
froala-editor 3.1.0
angular-froala-wysiwyg 3.1.0

##### OS.
Windows 10 Enterprise

##### Browser.
Chrome v.79.0.3945.130

**Comment by shawnphoffman** [comment]
This is a **huge** issue for us and is preventing us from moving forward with a paid license. Click on an image, click off and try typing. The only thing you can do is press backspace and it deletes the image.

This is also visible in your demos on the Froala website.

**Comment by rogerfar** [comment]
I thought of fixing this with imageAddNewLine, but that doesn't seem to do anything.

**Comment by ekalchev** [comment]
Froala team, please suggest a fix, fast!

**Comment by ekalchev** [comment]
We reverted image.js to version 3.0.6 as workaround.

**Comment by brendon** [comment]
Looks like it's fixed in their unreleased version since this now works on their website examples. Hopefully we'll see a new release soon.

**Comment by sai-velamuri** [comment]
> We reverted image.js to version 3.0.6 as workaround.

Hi, Can you tell us how to revert the version of image.js?

**Comment by deanmikan** [comment]
Still not fixed, is there an ETA on this?

**Comment by curioustolearn** [comment]
Can someone on Froala team please respond to the issue about what your plans are about fixing this? I am evaluating Froala for use in my app, but this basic bug will be very annoying to my users, and makes such an otherwise great product unusable. I am, especially, surprised by complete lack of a response from a team member about the issue. I tried the latest version from CDN, and I have the same problem. As @ekalchev said, the version 3.0.6 of image.min.js fixes the issue. 
@sai-velamuri you can revert to this version by simply adding:
https://cdnjs.cloudflare.com/ajax/libs/froala-editor/3.0.6/js/plugins/image.min.js
after you load whichever version of Froala you are loading.

**Comment by sai-velamuri** [comment]
> Can someone on Froala team please respond to the issue about what your plans are about fixing this? I am evaluating Froala for use in my app, but this basic bug will be very annoying to my users, and makes such an otherwise great product unusable. I am, especially, surprised by complete lack of a response from a team member about the issue. I tried the latest version from CDN, and I have the same problem. As @ekalchev said, the version 3.0.6 of image.min.js fixes the issue.
> @sai-velamuri you can revert to this version by simply adding:
> https://cdnjs.cloudflare.com/ajax/libs/froala-editor/3.0.6/js/plugins/image.min.js
> after you load whichever version of Froala you are loading.
> 
> I also wanted to add that one **cannot** enter text by clicking away from the image. But one is able to enter text if one uses right-arrow key to get away from the image after it is inserted. I tried simulating the right arrow key press in the image inserted event, but for some reason, that completely fails.

@curioustolearn  Will try that way. Thanks for the information!

**Comment by brendon** [comment]
I’ve spoken with the devs and we can expect 3.2 in the near future.

**Comment by curioustolearn** [comment]
> I’ve spoken with the devs and we can expect 3.2 in the near future.

Thanks @brendon. That is good to know.

**Comment by ilyaskarim** [comment]
Fixed in V3.2.1
