### ISSUE TITLE
Multiple Centered Images On The Same Line

### ISSUE THREAD

**Issue by shawn-northrop** [froala/wysiwyg-editor#382]
Is it possible to insert multiple images on the same line, without floating them left or right? 
Currently If they are centered each image appears on a new line.

**Comment by stefanneculai** [comment]
It's not possible at this point to add more than one image on a single line. There will be an option in the future for that.

**Comment by mbardelmeijer** [comment]
+1

Do you have an ETA for that feature?

**Comment by stefanneculai** [comment]
We implement minor features based on more things:
  - how many request are there for them
  - if there are users who have purchased a license and request the feature than it has higher priority
  - how important we consider it is

**Comment by stefanneculai** [comment]
3495f3b4edda5b0f72340b4ac4496053f486a224 has a new dropdown in the image popup for choosing how to display the images. Now multiple images can be added on the same line if they have `Text Wrap` set to `Inline`.

**Comment by shawn-northrop** [comment]
Thanks for the quick update on this!
