### ISSUE TITLE
"TypeError: Converting circular structure to JSON" when using property iframe_document

### ISSUE THREAD

**Issue by awegmueller** [froala/wysiwyg-editor#3820]
### Expected behavior.
FE.bootstrap should not pass the property "iframe_document" to JSON.stringify and should not throw errors when the passed Document has circular dependencies.

##### Actual behavior.
In an application with multiple browser windows, you need to pass the "iframe_document" property, otherwise Froala fails to find editor instances via ID-selector because it would search in the wrong document (of the main-window). However, when you pass the "iframe_document" property to the options object FE.Bootstrap calls JSON.stringify() on that object. Since Document is a complex object it may contain circular dependencies easily and this the call to stringify will cause an Error at runtime.

A possible solution is to set the property to null (or delete it) in the constructor of FroalaEditor:
```
if (options && options.iframe_document) {
    els = options.iframe_document.querySelectorAll(selector);
    options.iframe_document = null; /* Avoid circular structure Error in FE.Bootstrap */
}
```
Probably there should be a list of property-names that will be removed before the options object is serialized.

##### Steps to reproduce the problem.
Pass a document via property "iframe_document" that contains circular dependencies (e.g. set data via jQuery on a DOM node that points to the same DOM node).

##### Editor version.
v3.0.6

##### OS.
Windows 10

##### Browser.
All browsers

**Comment by PaulKahl** [comment]
I'm getting this same error on a page with an embedded Froala editor. My page shows and hides the editor when a user selects a radio button in the page (based on whether they want to use it or not), and in Chrome and IE11 (our client browser reqs) the moment I tell the Froala edit to hide, it's "gone forever", and that error is displayed in the console.

I've upgraded in dev/test recently to Bootstrap 4.4.1, and jQuery 3.4.1, and my Froala version is 3.1, however in prod my versions are Bootstrap 4.3.1, jQuery 3.2.1, and Froala 3.0.6... And the same issue is there, so I can verify that this is not related to upgrading jQuery, Bootstrap, or Froala.
