### ISSUE TITLE
dont show image in editor

### ISSUE THREAD

**Issue by amir3164** [froala/wysiwyg-editor#383]
hi 
i add image to editor but i have a problem. when add image and save in folder  but show image in editor
I emphasize that the image is stored but dont show in editro
iam use v wysiwyg-editor-1.2.4

**Comment by stefanneculai** [comment]
You're probably returning a bad JSON. See https://editor.froala.com/concepts/image-upload for how you should implement it.

**Please notice that we use this repo mainly for bug reporting and not for support.**
