### ISSUE TITLE
controlList attribute not allowed in editor.

### ISSUE THREAD

**Issue by shashankraj0202** [froala/wysiwyg-editor#3837]
#### Expected behavior.
Attribute controlsList should be allowed for audio and video tags.

##### Actual behavior.
controlsList attribute is removed on code cleanup by froala editor.

##### Steps to reproduce the problem.
1. Add a video/audio.
2. Open code view in the editor and add controlsList="nodownload" to the video/audio tag.
3. Return to the editor.
4. Go back to the code view and check the video/audio tag.

**Comment by lehti29** [comment]
It appears that the disablePictureInPicture attribute is also removed.

**Comment by MartinWa** [comment]
We also have the same issue. Is there any ETA on solving this?

**Comment by dejanmartinovic** [comment]
@shashankraj0202 Have you tried to modify the `htmlAllowedAttrs` option?
Check this example: https://jsfiddle.net/dejan_m/og0hxf2t/3778/

**Comment by shashankraj0202** [comment]
@dejanmartinovic Thanks. It is working as expected.
