### ISSUE TITLE
Lists plug-in makes Firefox hang and causes other issues in Safari

### ISSUE THREAD

**Issue by torstenb** [froala/wysiwyg-editor#385]
I am trying to use `Froala EDITOR` via the `wysiwyg-rails` gem. So far so good, except when I try to include `plugins/lists.min.js`, which causes some unwanted behavior when pressing enter in the editor:
* In Firefox 34, hitting the <kbd>return</kbd> key makes Firefox hang.
* In Safari it causes some weird formatting issues, such as removing padding/margin around the editor:
  Initial, correct formatting:
![initial_formatting](https://cloud.githubusercontent.com/assets/128974/5724111/1b83f140-9afe-11e4-84aa-6b5ac3479705.png)
  Formatting once I hit enter:
![messed_up_formatting](https://cloud.githubusercontent.com/assets/128974/5724112/1fcd4efe-9afe-11e4-82c7-2d998beb6ac7.png)

I am using [Twitter Bootstrap 3](http://getbootstrap.com) and I also use the [Startup Framework](http://designmodo.com/startup/) as well.

**Comment by stefanneculai** [comment]
Are you using the editor inside a `<li>` tag?

**Comment by torstenb** [comment]
Yes.

**Comment by stefanneculai** [comment]
It is already fixed on the master from this repo. We update the Rails gem only when the official release is made. In the meanwhile you could include the files manually instead of using the gem.
