### ISSUE TITLE
Insert Link's URL and Text fields not easily focusable / editable on mobile

### ISSUE THREAD

**Issue by JaxonWright** [froala/wysiwyg-editor#3861]
##### Expected behavior.
Either URL field would auto-focus like it does on desktop, or the user would simply click on the field and it would become focused and editable.

##### Actual behavior.
the fields are not focusable or editable unless long-pressing and then typing.

##### Steps to reproduce the problem.
This is replicable when opening the [demo site](https://froala.com/wysiwyg-editor/) for Froala on a mobile device or emulating one in Chrome.
Simply click the Insert Link option and observe how difficult it is to actually do anything with it.

##### Editor version.
3.1

##### OS.
Android 10 (Also happens when emulating mobile device in desktop Chrome)

##### Browser.
Chrome 80

**Comment by MarceloCajueiro** [comment]
Same here guys.

**Comment by dejanmartinovic** [comment]
@JaxonWright @MarceloCajueiro Input fields on popups do not work as expected on mobile devices.
The fix will be available in version 3.2.2.

**Comment by JaxonWright** [comment]
This actually seems to be fixed in version 3.2.0
