### ISSUE TITLE
very slow performance when typing with certain html

### ISSUE THREAD

**Issue by philfreo** [froala/wysiwyg-editor#387]
Go here and start typing a whole sentence at the top of this email. You'll notice performance is terrible / letters lag.

http://jsfiddle.net/ug4w9v33/

The content here isn't THAT long - only 500 lines of unminified HTML. Perhaps Froala is just poorly handling the level of nested blockquotes?

**Comment by stefanneculai** [comment]
Fixed 2d022a08f678ac658136e720d64e263e30206c83
