### ISSUE TITLE
Placeholder text in insert video popup does not show in (at least) IE 9

### ISSUE THREAD

**Issue by schart01** [froala/wysiwyg-editor#388]
When requesting to insert a video in Froala editor in IE 9, no placeholder text is visible.  The placeholder text is visible in other browsers.  Hence user does not know where to enter video embedded code or video link.  I have updated to current version  1.2.4

**Comment by stefanneculai** [comment]
We're using the `placeholder` attribute which is not available in IE 9. Taking into consideration that the number of users using IE 9 is reducing we'll not implement something specially for that.
