### ISSUE TITLE
"ERROR: Cannot read property 'classList' of null" when using Backspace in some circumestances

### ISSUE THREAD

**Issue by earshinov** [froala/wysiwyg-editor#3885]
##### Expected behavior

Pressing Backspace should not cause runtime exceptions (visible in browser's' developer tools console).

##### Actual behavior

Under some circumstances pressing Backspace causes "ERROR: Cannot read property 'classList' of null".

##### Steps to reproduce the problem

1 Visit https://stackblitz.com/edit/froala-backspace
2 Click "Open in New Window (Live)" in the top right corner
3 Follow the instructions on the page:

3.1 Select a part of the text
![froala](https://user-images.githubusercontent.com/52021/79856208-b6b76880-83d4-11ea-8fa4-7b456132b02b.png)

3.2 Press Backspace
![error](https://user-images.githubusercontent.com/52021/79856271-ce8eec80-83d4-11ea-8e37-150ba0b6e7d9.png)

That's how StackBlitz displays unhandled exceptions.

##### Editor version

3.1.1

##### OS

Irrelevant

##### Browser

Google Chrome 80.0.3987.163 (Official Build) (64-bit)

##### Recording

Please see repro steps above.

**Comment by earshinov** [comment]
It took me a while to prepare a repro, and while I was preparing it, I investigated a problem a bit.

I only have minified sources, so I will post fragments of froala_editor.min.js "unminified" with https://unminify.com/.

The error occurs here:

```js
function m(e, t) {
    if ((-1 < e.innerHTML.indexOf("<span") || -1 < e.parentElement.innerHTML.indexOf("<span") || -1 < e.parentElement.parentElement.innerHTML.indexOf("<span")) && (e.classList.contains("fr-img-space-wrap") || e.parentElement.classList.contains("fr-img-space-wrap") || e.parentElement.parentElement.classList.contains("fr-img-space-wrap"))) {
        if (o(e.parentElement).is("p")) {
            var n = e.parentElement.innerHTML;
            return (n = n.replace(/<br>/g, "")).length < 1 ? e.parentElement.insertAdjacentHTML("afterbegin", "&nbsp;") : "&nbsp;" != n && " " != n && "Backspace" == t.key ? u(t) : "&nbsp;" != n && " " != n && "Delete" == t.key && h(t), !0
        }
        if (o(e).is("p")) {
            var r = e.innerHTML.replace(/<br>/g, "");
            return r.length < 1 ? e.insertAdjacentHTML("afterbegin", "&nbsp;") : "&nbsp;" != r && " " != r && "Backspace" == t.key ? u(t) : "&nbsp;" != r && " " != r && "Delete" == t.key && h(t), !0
        }
    }
    return !1
}
```

The problem is that `e.parentElement.parentElement` is `null` because `e` happens to reside in a detached DOM tree. This function is called from

```js
function s(e) {
    var t = d.selection.element();
    if (t && 0 <= ["INPUT", "TEXTAREA"].indexOf(t.tagName)) return !0;
    if (e && b(e.which)) return !0;
    d.events.disableBlur();
    var n = e.which;
    if (16 === n) return !0;
    if ((f = n) === V.KEYCODE.IME) return p = !0;
    p = !1;
    var r = E(n) && !v(e) && !e.altKey,
        o = n === V.KEYCODE.BACKSPACE || n === V.KEYCODE.DELETE;
    if ((d.selection.isFull() && !d.opts.keepFormatOnDelete && !d.placeholder.isVisible() || o && d.placeholder.isVisible() && d.opts.keepFormatOnDelete) && (r || o) && (g(), !E(n))) return e.preventDefault(), !0;
    if (n === V.KEYCODE.ENTER) {
        /* ...irrelevant branches skipped for brevity... */
    } else {
        if (m(t, e) /* !!! */) return e.preventDefault(), void e.stopPropagation();
        d.placeholder.isVisible() ? (d.opts.keepFormatOnDelete || g(), e.preventDefault(), e.stopPropagation()) : u(e)
    }
    d.events.enableBlur()
}
```

(the call in question is marked with `/* !!! */`). Here, the selected node `t` is initially taken from `window.getSelection()` and seems to be always attached in DOM. However, between it is passed to `m(t, e)` there is a call to `d.selection.isFull() which, contrary to this function's name, is potentially destructive:

```js
isFull:function u() {
    if (O()) return !1;
    T.selection.save();
    var e, t = T.el.querySelectorAll("td, th, img, br");
    for (e = 0; e < t.length; e++) t[e].nextSibling && (t[e].innerHTML = '<span class="fr-mk">'.concat(V.INVISIBLE_SPACE, "</span>").concat(t[e].innerHTML));
    var n = !1,
        r = o(T.el);
    for (r.atStart && r.atEnd && (n = !0), t = T.el.querySelectorAll(".fr-mk"), e = 0; e < t.length; e++) t[e].parentNode.removeChild(t[e]);
    return T.selection.restore(), n
}
```

If things go as far as to `innerHTML` assignments, chances are that they overwrite the part of DOM containing the current selected element.

So, back in `function s`, after `d.selection.isFull` returns, `t` might refer to an element which is no longer attached to DOM.

The bug was probably introduced in 3.1.0 or 3.1.1 because I don't recall seeing "fr-img-space-wrap" in sources of earlier versions.

**Comment by IslamElKassas** [comment]
Is there any solutions ?

**Comment by earshinov** [comment]
I don't know of any. Since we have a commercial license, I contacted Froala support. They told me that they added this issue to their internal development task list, but there is no ETA for the fix.

**Comment by AleksandarM94** [comment]
Any news on this issue?

**Comment by earshinov** [comment]
Not reproducible in 4.0.9.

**Comment by burtonrhodes** [comment]
We are also receiving this error. I am able to reproduce it with v4.0.10 with the following [jfFiddle](https://jsfiddle.net/burtonrhodes/ug5wy3ar/4/)
