### ISSUE TITLE
Preview video during edit

### ISSUE THREAD

**Issue by schart01** [froala/wysiwyg-editor#389]
In IE (at least 9), after inserting a video, I am able to actually run that video in edit mode.  However, in Chrome and Safara, I am unable to run the video while I'm in edit mode.  Is there a way to do this?

**Comment by mbardelmeijer** [comment]
+1

**Comment by devmondo** [comment]
+1

**Comment by stefanneculai** [comment]
We see a high interest for the possibility to preview video while editing, but we don't find any reason to do that. E.g. The user copies the video URL from Youtube, Vimeo, etc. and then he inserts it in the editor. Why would he be interested to see the video again (he already saw it)?

**Comment by devmondo** [comment]
one scenario is when  we create a blog with live edit ability so user can use froala inline mode and he would like to see a full preview of his writing including the ability to preview the video

**Comment by schart01** [comment]
Our system that is using Froala shows a wysiwyg environment where they see and edit their content.  There is no official “preview” mode or “read” mode.  We wanted it as one and the same (edit and view at the same time).   The video element is the only one that a user cannot directly test and see.  

I had a user actually paste in the wrong URL for a video and couldn’t validate that it works.  

Warm Regards,

Suzanne Chartier
Director of Engineering Services





http://eyewyre.com <http://eyewyre.com/> 
65 Market Street, Suite 100
Mount Clemens, MI 48043
586-932-1002 ext. 200

**Comment by stefanneculai** [comment]
Last commit introduces the possibility to preview video while editing. First click on the video will show the edit popup. 2nd click on the video will do the default video actions.
