### ISSUE TITLE
Froala editor breaks other file upload inputs?

### ISSUE THREAD

**Issue by philfreo** [froala/wysiwyg-editor#390]
### Without Froala

http://jsfiddle.net/hjv11p4u/

Drag a file onto the upload field and it works as expected.

![screenshot 2015-01-14 15 26 13](https://cloud.githubusercontent.com/assets/97612/5749846/e133e86a-9c01-11e4-8b55-049f99ff4c6a.png)

### With Froala

http://jsfiddle.net/rufvu3tL/

Stays blue and doesn't show file name. Not sure how this is happening but I'm guessing some event is getting intercepted.

![screenshot 2015-01-14 15 26 22](https://cloud.githubusercontent.com/assets/97612/5749854/f30c59b4-9c01-11e4-9842-4c2a22662ecf.png)

**Comment by stefanneculai** [comment]
Fixed 2d022a08f678ac658136e720d64e263e30206c83
