### ISSUE TITLE
Clicking page scrollbar (to scroll) shouldn't hide dropdown

### ISSUE THREAD

**Issue by philfreo** [froala/wysiwyg-editor#391]
1. go to https://editor.froala.com/examples/custom-dropdown
2. open the block style dropdown or custom dropdown
3. click and drag your browser window's scrollbar to scroll down the page a bit
4. when you release your mouse button, the dropdowns hide (but shouldn't)

this becomes a bigger deal when the dropdown is long and the user must scroll to see the bottom of the dropdown, but then it hides when they are done scrolling.

chrome on os x

(Minor, but slightly related UX improvement: I think that clicking the dropdown icon that you clicked to _open_ the dropdown should also _close_ the dropdown if you click it a 2nd time. This is how it works in OS X menu bar, for example)

**Comment by sudeste** [comment]
I have this problem too, see example: http://i.imgur.com/SUiH9Nf.jpg
How can I fix this.
For example, when the text has much in the left corner, the Dropdown should go to the right.

**Comment by stefanneculai** [comment]
@philfreo please update to 2d022a08f678ac658136e720d64e263e30206c83. You should use `trackScroll` option if you want not to hide the dropdowns when you scroll.

@sudeste That is already on our TODO list, but there are still few items that have higher priority for the moment.

**Comment by philfreo** [comment]
> You should use trackScroll option if you want not to hide the dropdowns when you scroll.

Thanks for the update, I'll try it out. An option is certainly doable, but I have to wonder why you'd introduce new options versus just having the default experience be what seems to have the best UX

**Comment by stefanneculai** [comment]
The option is already in the editor for a while now (https://editor.froala.com/options#trackScroll). Using that option reduces the performance of the editor a bit (specially on mobile devices) when there are more instances on the same page and that is why it is not enabled by default. If we'll find a way that doesn't affect too much the performance, then we'll add it by default for sure.

**Comment by philfreo** [comment]
Okay, got it, thanks

**Comment by philfreo** [comment]
`trackScroll: true` did not fix the problem I described.

**Comment by stefanneculai** [comment]
Are you using a different scroll than the page scroll? It doesn't hide the dropdown when I scroll.

**Comment by philfreo** [comment]
Ah, yes... indeed most of the content is in a <div> with overflow: scroll

**Comment by stefanneculai** [comment]
OK. We'll try to find another way to handle this.

**Comment by stefanneculai** [comment]
We're all out of ideas for this, so I will describe why the dropdown hides when you scroll, maybe someone who follows this can provide some help.

We're listening to `mouseup` on `window` in order to hide the dropdown when you click outside of it. Unfortunately, hitting any scrollbar triggers the same event on the window and there doesn't seem to be any way to stop it. For the `window` we are setting a timer on `scroll` and if the timer is set when `mouseup` is triggered then it means that we did scroll and we don't have to hide the dropdown. Unfortunately, we can't do that for all the elements on the page because would result in a big overload.

**Comment by philfreo** [comment]
>  For the window we are setting a timer on scroll and if the timer is set

Rather than setting this on `window` always, what about just setting it on `scrollableContainer` ?

**Comment by stefanneculai** [comment]
That wouldn't work because when `scrollableContainer` is set to `body`, the scroll is on `window` and not `body`.

**Comment by philfreo** [comment]
Sure but that's a very easy case to handle. Point is you always know which element to bind to and then it should work.
