### ISSUE TITLE
Froala does not clean "table-layout: fixed; width: 0;" attributes from table pasted from Google Spreadsheets

### ISSUE THREAD

**Issue by earshinov** [froala/wysiwyg-editor#3912]
### Expected behavior.

Tables pasted from Google Spreadsheets should look normal.

##### Actual behavior.

Tables look like a vertical line because of the "width: 0" attribute.
This is similar to what was reported in https://github.com/froala/wysiwyg-editor/issues/3882

##### Steps to reproduce the problem.

1. Open the test Google Spreadsheet: [Froala test](https://docs.google.com/spreadsheets/d/1MDOsjptBex1IgCXomsQXHsasC52ybx2dZRKlmNvdu5E/edit?usp=sharing)
2. Copy range A1:B2 (all cells with content)
3. Open the test StackBlitz demo: https://stackblitz.com/edit/froala-test
4, On the StackBlitz page, press "Open in New Window" in the top right corner to open the test Froala page in a separate window.
5. On the test Froala page, paste the content you copied from the test Google Spreadsheet into the editor

The result looks like this:
![image](https://user-images.githubusercontent.com/52021/81409660-2bfe9980-9148-11ea-8506-cfc7351ddab3.png)

HTML content in the Clipboard looks like the following (viewed using [FreeClipViewer](https://www.freeclipboardviewer.com/). Note the `table-layout: fixed` and `width: 0` attributes.

```
Version:0.9
StartHTML:0000000105
EndHTML:0000001244
StartFragment:0000000141
EndFragment:0000001208
<html>
<body>
<!--StartFragment--><google-sheets-html-origin><style type="text/css"><!--td {border: 1px solid #ccc;}br {mso-data-placement:same-cell;}--></style><table xmlns="http://www.w3.org/1999/xhtml" cellspacing="0" cellpadding="0" dir="ltr" border="1" style="table-layout:fixed;font-size:10pt;font-family:Arial;width:0px;border-collapse:collapse;border:none"><colgroup><col width="100"/><col width="100"/></colgroup><tbody><tr style="height:21px;"><td style="overflow:hidden;padding:2px 3px 2px 3px;vertical-align:bottom;" data-sheets-value="{&quot;1&quot;:2,&quot;2&quot;:&quot;A1&quot;}">A1</td><td style="overflow:hidden;padding:2px 3px 2px 3px;vertical-align:bottom;" data-sheets-value="{&quot;1&quot;:2,&quot;2&quot;:&quot;B1&quot;}">B1</td></tr><tr style="height:21px;"><td style="overflow:hidden;padding:2px 3px 2px 3px;vertical-align:bottom;" data-sheets-value="{&quot;1&quot;:2,&quot;2&quot;:&quot;A2&quot;}">A2</td><td style="overflow:hidden;padding:2px 3px 2px 3px;vertical-align:bottom;" data-sheets-value="{&quot;1&quot;:2,&quot;2&quot;:&quot;B2&quot;}">B2</td></tr></tbody></table><!--EndFragment-->
</body>
</html> 
```

6. In the Froala editor, use the Code View to remove the "table-layout: fixed" attribute. After that the table looks normal:

![image](https://user-images.githubusercontent.com/52021/81409965-afb88600-9148-11ea-9b1a-30b8f8ccd0e4.png)

##### Editor version.

3.1.1

##### OS.

Windows 10 x64

##### Browser.

Google Chrome 81.0.4044.138 (Official Build) (64-bit)
Firefox 75.0

HTML content in the clipboard is the same in Chrome and Firefox. I think that this HTML is generated programmatically by Google Spreadsheets, so the browser should not really matter.

**Comment by earshinov** [comment]
Not reproducible in 4.0.9 (https://jsfiddle.net/f56q2pdh/)

**Comment by Vignesh-Manogar-E3433** [comment]
This issue still seems to exist in Safari browser. Tested with the same link but in Safari browser.
