### ISSUE TITLE
Popup Positioning 

### ISSUE THREAD

**Issue by fru** [froala/wysiwyg-editor#393]
When I have options.scrollableContainer === 'body' the file upload dialog is not positioned correctly once the body scrolls.

I fixed this using !c.is('body')) in the following function:
```javascript
a.Editable.prototype.showByCoordinates = function (a, b) {
        a -= 22, b += 8;
        var c = this.$document.find(this.options.scrollableContainer);
        if (!c.is('body')) {
             "static" != c.css("position") && (a -= c.offset().left, b -= c.offset().top), b += c.scrollTop(), a += c.scrollLeft();
        }

...
}
```

**Comment by stefanneculai** [comment]
I could not replicate this. Please make a jsFiddle or provide more details.

**Comment by stefanneculai** [comment]
Indeed this was an issue. We found it only in Webkit browsers. f554f64aece88c6ea0f9c2ee2f8afd6ae04bfa39 fixes it.

Thank you for letting us know about it!
