### ISSUE TITLE
Editor gives errors when I import it to react app

### ISSUE THREAD

**Issue by Luvolunov** [froala/wysiwyg-editor#3933]
### Framework: React

I import froala editor to app, set it to code:

`<Froala config={config} model={content} />`

And it gives me following errors:

`React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: null.`

What is it?

**Comment by ilyaskarim** [comment]
@Luvolunov can you please confirm that you are importing editor in this way https://codesandbox.io/s/pensive-perlman-u0nnw?file=/src/index.js?

**Comment by Luvolunov** [comment]
It was just cache. I was trying to solve warnings in console with UNSAFE_ lifecycle hooks. After it, smth went wrong. Issue is closed
