### ISSUE TITLE
pastePlain fails for some content

### ISSUE THREAD

**Issue by franciscohanna92** [froala/wysiwyg-editor#3955]
##### Expected behavior.
Format should be removed when pasting with `pastePlain` set to `true`

##### Actual behavior.
Format sometime persists after pasting 

##### Steps to reproduce the problem.
1. Go to https://loremipsum.io/
2. Select and copy (CTRL+C) all titles and paragraphs
3. Paste it in the Froala editor (the one in https://froala.com/wysiwyg-editor/examples/plain-paste/) 
4. The format persists

##### Editor version.
3.1.0

##### OS.
Ubuntu 19.04

##### Browser.
Google Chrome 81.0.4044.138

##### Recording.
![Peek 11-06-2020 11-06](https://user-images.githubusercontent.com/12707758/84394923-efeda700-abd3-11ea-8975-39771afeb2f0.gif)

**Comment by franciscohanna92** [comment]
It seems to be solved after adding the option `pasteDeniedAttrs: ['class', 'style']`

**Comment by earshinov** [comment]
@franciscohanna92 , don't you think that `pastePlain` should only paste plain text even with default settings? The whole thing that some HTML is can slip through seems to me like an oversight from froala's developers.

**Comment by franciscohanna92** [comment]
@earshinov Yes, I think so. And yes, it seems like an oversight from their part. Maybe another issue should be opened?

**Comment by earshinov** [comment]
> Maybe another issue should be opened?

I agree. It will make this ticket more visible both to Froala developers and people who search for `pastePlain` in GitHub. Some people might ignore closed tickets although the issue with Froala is still there.

**Comment by franciscohanna92** [comment]
@earshinov here it's https://github.com/froala/wysiwyg-editor/issues/3979

**Comment by earshinov** [comment]
Thanks, I subscribed to that one as well :)
