### ISSUE TITLE
Layout disturb when resize the image and open the image resize option again.

### ISSUE THREAD

**Issue by mhassanedev** [froala/wysiwyg-editor#3971]
##### Expected behavior.
If the scrollbar appears, it should be within a child container, it would not be shown up on the parent container. (**NOTE: Scrollbar should appears once**).
![Expected result](https://user-images.githubusercontent.com/67260588/85387263-085bab00-b55e-11ea-897c-de66935f090a.png)

##### Actual behavior.
When image resized scroll bar appears on the parent container, and cursor down(press enter until scrollbar appears) and then insert image notice two scrollbar appears.

##### Steps to reproduce the problem.
**Scenario # 1**
1. Initialize the Froloa editor.
2. insert image and resize it until the scrollbar appears(notice scrollbar appears on parent container).

**Scenario # 2**
1. Initialize the Froloa editor.
2. Cursor down(press enter until scrollbar appears).
3. Insert image at the end of the page(notice scrollbar appears twice).

##### Editor version.
Froala editor version "3.1.1"

##### OS.
Windows 10

##### Browser.
Google Chrome

##### Recording.
![Actual-Behavior-2](https://user-images.githubusercontent.com/67260588/85387239-0265ca00-b55e-11ea-903c-228f86c540a9.gif)

**Comment by ilyaskarim** [comment]
Hi There, I just tested the issue and it seems like the issue is not reproducible on the latest version, Can you please confirm if you are still able to replicate it on our demo: https://froala.com/wysiwyg-editor/.
