### ISSUE TITLE
WARNING: Replace fill-available to stretch, because spec had been changed

### ISSUE THREAD

**Issue by JaxonWright** [froala/wysiwyg-editor#3989]
##### Expected behavior.
Not have warnings like this when building node dependency with a project.

##### Actual behavior.
![image](https://user-images.githubusercontent.com/14099593/88087522-0c77ea00-cb57-11ea-9b19-a06f738aa9ae.png)

##### Steps to reproduce the problem.
Build a project that has this project as one of its npm dependencies

##### Editor version.
3.1.1

##### OS.
Windows 10 1909

##### Browser.
Irrelevant

**Comment by flonussi** [comment]
This exact issue appeared today for me also.
But I'm stil on 3.1 and didn't touch or update froala or any other dependency of my project in weeks, but today this warning startet to appear...

**Comment by jvmills** [comment]
Same for me

`WARNING in ./node_modules/froala-editor/css/froala_editor.pkgd.min.css (./node_modules/css-loader??ref--5-2!./node_modules/postcss-loader/src??postcss0!./node_modules/froala-editor/css/froala_editor.pkgd.min.css)
Module Warning (from ./node_modules/postcss-loader/src/index.js):
Warning

(7:52021) Replace fill-available to stretch, because spec had been changed
 @ ./resources/sass/app.scss (./node_modules/css-loader??ref--5-2!./node_modules/postcss-loader/src??postcss0!./node_modules/sass-loader/dist/cjs.js??ref--5-4!./resources/sass/app.scss) 9:10-173
 @ ./resources/sass/app.scss`

**Comment by marctaule** [comment]
Same for me...

**Comment by wes337** [comment]
Same, can this please get fixed?

**Comment by qingmang** [comment]
Same for me...

**Comment by arwinvdv** [comment]
I had contact with Froala today and they will fix the issue in v3.2.4 what will be released in a few months.

**Comment by devstack-be** [comment]
@arwinvdv Thanks for the information ;)

**Comment by micheleh** [comment]
Is there a way to work around this until a fix is provided?

**Comment by devstack-be** [comment]
normally npm is not blocking the script. it's just a warning. If you want to fix it, you can explore the package, do a search and replace and replace "fill-available" to "stretch". But it's only temporary and it's better waiting a real fix.

**Comment by paras-deshbhratar** [comment]
Even I am also getting the same warning in console.
Thanks @arwinvdv. Will wait till they release v3.2.4

**Comment by marcodeluca** [comment]
Thanks for the update, having the same issue.

**Comment by marting169** [comment]
gracias!

**Comment by manshu** [comment]
I've the same issue. Any update on this?

**Comment by ffjanhoeck** [comment]
Same issue :)

**Comment by rockingthecode** [comment]
having same problem here. i have been searching for an hour and its frustrating. i hope it fixed very soon.

**Comment by kylepeeler** [comment]
+1, seeing same issue here as well

**Comment by robjac** [comment]
![](https://media3.giphy.com/media/I1nwVpCaB4k36/giphy.gif)

**Comment by taylormaguire** [comment]
Hi Everyone, as noted earlier, it looks like they will fix this in v3.2.4, however if you want to get rid of the error you can open the froala_editor.pkgd.min.css file in your node_modules and do a search and replace 

Search: fill-available
Replace: stretch

Save the file and now your builds wont fail. 

Warning: as you are editing a vendor node library file, any  npm update or re-install of the package will require these changes gain until they fix in the future update.

**Comment by kylepeeler** [comment]
Is there a fix that does not require modifying node_modules?... This is not a fix that could be done in any situation but locally, considering node_modules aren't committed (at least for my project...)

**Comment by herbertharriola** [comment]
> Is there a fix that does not require modifying node_modules?... This is not a fix that could be done in any situation but locally, considering node_modules aren't committed (at least for my project...)

I have the same problem!! It would be nice for them to release the fix soon!!

**Comment by shroomlife** [comment]
Same problem here. Is there a fix to surpress thiss message in the meantime?

**Comment by iicdii** [comment]
I suppressed the message by add [string-replace-loader](https://github.com/Va1/string-replace-loader) in webpack config rules.

```js
// webpack.config.js
module.exports = {
  // ...
  module: {
    rules: [
      {
        test: /froala_editor\.pkgd\.min\.css$/,
        loader: 'string-replace-loader',
        options: {
          search: /fill-available/g,
          replace: 'stretch'
        }
      }
    ]
  }
}
```

**Comment by shroomlife** [comment]
> I suppressed the message by add [string-replace-loader](https://github.com/Va1/string-replace-loader) in webpack config rules.
> 
> ```js
> // webpack.config.js
> module.exports = {
>   // ...
>   module: {
>     rules: [
>       {
>         test: /froala_editor\.pkgd\.min\.css$/,
>         loader: 'string-replace-loader',
>         options: {
>           search: /fill-available/g,
>           replace: 'stretch'
>         }
>       }
>     ]
>   }
> }
> ```

works for me! thank you a lot @iicdii 👏👏👏

**Comment by Taskle** [comment]
Hi folks! I saw 3.2.4 came out yesterday, and admittedly I've been tracking it closely for the fix to this issue per the comment below:

> I had contact with Froala today and they will fix the issue in v3.2.4 what will be released in a few months.

I didn't see it in the release notes:
https://github.com/froala/wysiwyg-editor/releases/tag/v3.2.4

and updating, I see the issue persists.

Can someone from Froala kindly advise? For those of us who don't want to manually edit our third party packages, it would be great to get an update!

**Comment by EthanRBrown** [comment]
Agreed, @Taskle !  This has been a HUGE thorn in our sides...I know it may seem like a small thing, but we have a clean console policy, and the time it takes to sort past those warnings every time we see something real that needs to be addressed adds up.  Plus it's just a giant eyesore in something we take pride in.  This needs to be fixed!  If Froala doesn't respond to this issue soon, we'll certainly be looking towards another rich text editor and not renewing our subscription.

I was so happy to see that 3.2.4 dropped, and you can imagine my disappointment when I upgraded, hoping to finally see a clean console and....

![image](https://user-images.githubusercontent.com/7088733/102000743-5d6fb280-3c9f-11eb-8ee6-4a9c6ef83c4f.png)

**Comment by yuriy-vasilyev** [comment]
@EthanRBrown, how many options do we have out there? :)

**Comment by arwinvdv** [comment]
I just checked the new version and as said above, warnings still exists. So I looked to the mail they send me and I see that I wrote it wrong here. 
They wrote version version 3.4 not 3.2.4... So we have to wait a few months more. Until then I think the fix of @iicdii will work.

**Comment by kylepeeler** [comment]
So since this still seems to be an issue (🙄)... here is how we handled it in our app... I just brought in [webpack-filter-warnings-plugin](https://www.npmjs.com/package/webpack-filter-warnings-plugin), and applied it to my webpack config like so:

```js
const baseConfig = {
  name: pkg.name,
  entry: [paths.appIndexJs, 'whatwg-fetch'],
  output: {
    path: path.resolve(__dirname, '../dist'),
    publicPath: '/',
  },
  module: {
    rules: [
      configureFontLoader(),
      configureImageLoader(),
      configureIconLoader(),
    ],
  },
  resolve: resolveConfig,
  plugins: [
    new WebpackNotifierPlugin({
      title: 'Webpack',
      excludeWarnings: true,
      alwaysNotify: true,
    }),
    new webpack.ProvidePlugin({
      FroalaEditor: 'froala_editor.min.js/froala_editor.pkgd.min.js',
    }),
    /*
    @HACK: Froala currently has a warning that postcss throws, and the only solution from the author is basically to edit node_modules ~until 3.2.4 is released~...
    Well since that won't work for us (node_modules is not committed), I have decided to filter the warnings so it doesn't make our logs ginormous between now
    and when it is released.

    Relevant Issue: https://github.com/froala/wysiwyg-editor/issues/3989

    @FUTURE: remove me + corresponding plugin ~when froala-editor is upgraded >=3.2.4~ (also remember to update storybook/main.js)!
    */
    new FilterWarningsPlugin({
      exclude: /Replace fill-available to stretch/,
    }),
  ],
};
```
💨 Poof, no more warnings 😄

**Comment by Taskle** [comment]
For those of us that are using React's CRA and not ejected to use custom webpack configs, sounds like this is only an option if we either eject or use CRACO. Sounds like we're stuck waiting until 3.4... if folks who are also using CRA have thoughts on a workaround without a ton of work/changes/additions, feel free to share! Indeed this has been the only warning lingering in our app for months, so unfortunate that it will continue to linger.

**Comment by kgish** [comment]
Please fix!

**Comment by nirvparekh** [comment]
I updated to **v3.2.5**
Not fixed yet.

**Comment by EthanRBrown** [comment]
@ansh-les I will.  At this point, I'm tempted to go with CKEditor 5, though I haven't investigated the options yet.  Quill is also very interesting, more of a new kid on th block.

**Comment by a-bit-too-literal** [comment]
This is also causing us to reassess our choice of froala. Does anyone know why it is taking so long to resolve?

**Comment by kgish** [comment]
This is VERY annoying indeed.

For the time being I have added the following script in my `package.json` file:

```
 "froala:css:fix": "sed -i 's/fill-available/stretch/g' ./node_modules/froala-editor/css/froala_editor.pkgd.min.css",
```

**Comment by dzetah** [comment]
@kgish Nice one-liner, worth placing it inside a `postinstall` script so it runs automatically :)

**Comment by JCanlett** [comment]
Glad I'm not alone here. Just upgraded to 3.2.6 after dealing with the crazy licensing issues.. Now console is full of warnings. Is this still slated for 3.4? that seems like a long way out. Will be on Angular 12 by then.

**Comment by ac-andyta** [comment]
You can also have a node solution to support all systems (Windows):

Create a file called `patch.js` in the same folder as your `package.json`:
```javascript
const fs = require('fs');

const froalaMinCss = 'node_modules/froala-editor/css/froala_editor.pkgd.min.css';
fs.readFile(froalaMinCss, 'utf8', function (err, data) {
  if (err) {
    throw err;
  }
  const result = data.replace(/fill-available/g, 'stretch');
  fs.writeFile(froalaMinCss, result, 'utf8', function (e) {
    if (e) throw e;
  });
});
```
Essentially, it does the same thing as the `sed` command.

Then, add it to your `postinstall` in `package.json` like `"postinstall": "node patch.js"` or `"postinstall": "... && node patch.js"` if you have other commands.

Finally, run `npm install`.

**Comment by dejanmartinovic** [comment]
The issue has already been solved. The fix will be available in version 3.3.3 (mid-March at the latest). Thanks

**Comment by msalmankarim** [comment]
Experiencing the same issue :)

**Comment by nirvparekh** [comment]
> The issue has already been solved. The fix will be available in version 3.3.3 (mid-March at the latest). Thanks

March has ended. not fixed yet.

**Comment by adrianksiezarczyk** [comment]
> March has ended. not fixed yet.

It's 30.03, UTC 10AM. They still have time.

**Comment by QaisMakani** [comment]
I see a PR open since Aug, 2020 that fixes this issue:
https://github.com/froala/wysiwyg-editor/pull/4006

The issue and the PR are not linked though. Can we please get it merged?

**Comment by gekikara404** [comment]
> The issue has already been solved. The fix will be available in version 3.3.3 (mid-March at the latest). Thanks

March has ended. not fixed yet ( 2 )

**Comment by HernanGH** [comment]
Same issue here! @dejanmartinovic do you know when the version 3.3.3 will be available?

**Comment by zdm** [comment]
I think, nobody from support reads this threads.
Don't waste your time, guys. ))

**Comment by ilyaskarim** [comment]
The fix for this issue will be released in the next editor release which is expected to be released by the first week of May.

**Comment by nirvparekh** [comment]
> The fix for this issue will be released in the next editor release which is expected to be released by the first week of May.

which year???

**Comment by horsemanV** [comment]
Snark aside, thanks for the update

**Comment by ValentinSolod** [comment]
any updates ?

**Comment by HernanGH** [comment]
> The fix for this issue will be released in the next editor release which is expected to be released by the first week of May.

This week?

**Comment by MaksimEpifanau** [comment]
This day?

**Comment by HernanGH** [comment]
This month?

**Comment by jaymathew** [comment]
This year?

**Comment by zdm** [comment]
At this life or after reincarnation?

**Comment by arwinvdv** [comment]
I don't know where @ilyaskarim got his information, but I just mailed Froala support and they say: 

> The next release is v3.3 (renamed as v4.0) and is scheduled to be released by the mid of June.

**Comment by erikramalho** [comment]
> I don't know where @ilyaskarim got his information, but I just mailed Froala support and they say:
> 
> > The next release is v3.3 (renamed as v4.0) and is scheduled to be released by the mid of June.
> 
> Edit: Apparently if you ask when the next release is, they are assuming a major release.

Awesome! Now Froala will charge us to solve this issue, since we all have V3 licensing… great way to force us tu buy a new license.🤮

**Comment by sssppp6** [comment]
Finally fixed in https://froala.com/wysiwyg-editor/changelog/#3.2.7

**Comment by nirvparekh** [comment]
I updated to 3.2.7, still showing the same.

**Comment by harsh-100** [comment]
/{YOUR_PROJECT PATH}/node_modules/react-pure-modal/dist/react-pure-modal.min.css
 
-- first search for the word 'fill-available '
-- then just replace it with 'stretch'
-- Your problem will be solved and there will be no more warning for this ✌️

**Comment by Icodezhan** [comment]
is ok?

**Comment by Vimal-79** [comment]
i think i have different one 

[vite:css][postcss] Replace fill to stretch, because spec had been changed
1  |  @tailwind base;
2  |  @tailwind components;
3  |  @tailwind utilities;
   |  ^^^^^^^^^^^^^^^^^^^^
