### ISSUE TITLE
beforeImageUpload return empty FileList

### ISSUE THREAD

**Issue by ahmadajmi** [froala/wysiwyg-editor#399]
I'm trying to catch the upload image before uploading, so I use the `beforeImageUpload` event as.

``` javascript
$("#edit").on('editable.beforeImageUpload', function (e, editor, images) {
    console.log(images); //=>  FileList []
});
```

**Comment by stefanneculai** [comment]
It works as it should: http://jsfiddle.net/4ushg74q/. If you don't return false in the callback and just display the object, then it might be cleared from memory and that's why you see it empty.

**Comment by ahmadajmi** [comment]
It appears that Firefox print it as `FileList []`, while Chrome print it as `FileList {0: File, length: 1, item: function}`.

Thanks
