### ISSUE TITLE
bug in latest 3.2 release with losing ability to edit

### ISSUE THREAD

**Issue by dolphinsd** [froala/wysiwyg-editor#3990]
latest release, go to your demo at https://froala.com/wysiwyg-editor/

1. Insert image from your computer.
2. Place cursor anywhere try to edit text

Anything you type, no response!

**Comment by ilyaskarim** [comment]
@kapil2704 Can you please check this bug?

**Comment by asp3** [comment]
+1

**Comment by dejanmartinovic** [comment]
@dolphinsd Can you try to reproduce following these steps?
1. Insert image from your computer.
2. Click the Esc button on the keyboard
3. Place cursor anywhere try to edit text
Thanks

**Comment by dolphinsd** [comment]
@dejanmartinovic , pressing esc button fixes the issue, but how do you expect user to know. the bug reported still exist on your own demo: https://froala.com/wysiwyg-editor/

Insert image from your computer.
Place cursor anywhere try to edit text

**Comment by dolphinsd** [comment]
Just checked in 3.2.5 and issue seems to be resolved!
