### ISSUE TITLE
IE space issues.

### ISSUE THREAD

**Issue by shidhu40** [froala/wysiwyg-editor#402]
In IE 9 when we set the html by setHTML() function it will take extra space.
Also when we delete the element then cursor moves downward. A wide space is remaining.

**Comment by dianaprajescu** [comment]
First of all are you using the latest version from this repository?

Secondly, we don't have enough information to reproduce the issues. What HTML do you pass over to the `setHTML()` method? We tried with some random text and it works fine. What do you mean by "delete **the element**"? Deleting characters works okay.

**Comment by shidhu40** [comment]
I am using <ul><li>Hello</li><li>Sudhir</li></ul> when deleting this bullet it will disappear

**Comment by dianaprajescu** [comment]
We have updated this repository with some fixes for lists in IE9. Please test and let us know if you encounter any issues.

**Comment by stefanneculai** [comment]
The issue appears fixed in our tests. Closing this issue.
