### ISSUE TITLE
Editor splits in two when Enter key pressed

### ISSUE THREAD

**Issue by danielarturo** [froala/wysiwyg-editor#403]
When i typped some words and then press enter the editor splits using IE11 in some conditions.

Sample page: https://www.dropbox.com/s/ys1p2gncgrbudtg/TEST.rar?dl=0

![test](https://cloud.githubusercontent.com/assets/9198962/5842553/5c660f4a-a16b-11e4-98ea-f919fa14457e.jpg)

**Comment by stefanneculai** [comment]
You're using an older version. It is already fixed on the master one.
