### ISSUE TITLE
Cursor moves to the begging of the line while pressing backspace instead of removing one character. 

### ISSUE THREAD

**Issue by B45i** [froala/wysiwyg-editor#4038]
if I navigate to the froala editor by pressing <kbd>Tab</kbd> and try to remove the last character that I type by pressing the <kbd>Back Space</kbd>, instead of removing the character, the cursor is jumping to the beginning of the line.

[This](https://github.com/froala/react-froala-wysiwyg/issues/105) is a similar issue but I `html.get()` method is not being called.

![frola bug](https://i.imgur.com/vYSMJWP.gif "")

* Only happening when the content is empty
* Framework: angular
* Video Link: https://vimeo.com/458090291

**Comment by ilyaskarim** [comment]
Fixed in V4.0.15 https://froala.com/wysiwyg-editor/changelog/#4.0.15
