### ISSUE TITLE
imageuploadtos3

### ISSUE THREAD

**Issue by sabanaqvi** [froala/wysiwyg-editor#404]
I'm trying to use the imageUploadToS3 option but I keep getting:

<Error><Code>AccessDenied</Code><Message>Invalid according to Policy: Extra input fields: x-requested-with</Message><RequestId>8FFF313E47C10DEF</RequestId><HostId>l2q8cn/28UNkQPyj6S6trHiImmGW3YDFshkJiChJ1UOnQE6OEjYQjTNNczk3oY2LdUHp8Ut8pP8=</HostId></Error>

Please let me know if you have any ideas. I'm including my code below:

Here is my initalization of the editor: (I've put ### where private stuff exists)
$('#fs_editor').editable({
      inlineMode: false,
      customButtons: doubleUnderline,
      buttons: ['undo', 'redo', 'bold', 'italic', 'underline', 'doubleUnderline', 'fontSize', 'fontFamily', 'align', 'table', 'createLink', 'insertImage'],
      imageUploadToS3: {
        bucket: '#####',
        region: 's3',
        keyStart: 'uploads/',
        callback: function (url, key) {
          console.log (url);
          console.log (key);
        },
        params: {
          acl: 'public-read', // ACL according to Amazon Documentation.
          AWSAccessKeyId: "#####", // Access Key from Amazon.
          policy: "#####", // Policy string computed in the backend.
          signature: "#####" // Signature computed in the backend.
        }
      }
  });

My policy looks like this:
str_policy = {"expiration": "2016-01-01T00:00:00Z",
                                "conditions": [
                                  {"bucket": "#####"},
                                  ["starts-with", "$key", "uploads/"],
                                  {"acl": "public-read"},
                                  {"success_action_redirect": ""},
                                  ["starts-with", "$Content-Type", ""]
                                ]
                              }

I'm getting my signature and policy values like this:
signature = Base64.encode64(
          OpenSSL::HMAC.digest(
              OpenSSL::Digest::new('sha1'),
              '<inserted_aws_secret_key>', '')).gsub("\n",'').gsub("\r",'')

policy = Base64.encode64(str_policy).gsub("\n",'').gsub("\r",'')

**Comment by stefanneculai** [comment]
Please use the below example in PHP as reference. We'll write an article about that during this week.

```php
<?php
// Set date timezone.
date_default_timezone_set('Europe/Bucharest');

// important variables that will be used throughout this example
$bucket = 'froala';
$region = 's3';
$keyStart = 'test/';
$acl = 'public-read';

// these can be found on your Account page, under Security Credentials > Access Keys
$accessKeyId = '';
$secret = '';

$policy = base64_encode(json_encode(array(
    // ISO 8601 - date('c'); generates uncompatible date, so better do it manually
    'expiration' => date('Y-m-d\TH:i:s.000\Z', strtotime('+1 day')),
    'conditions' => array(
        array('bucket' => $bucket),
        array('acl' => $acl),
        array('success_action_status' => '201'),
        array('x-requested-with' => 'xhr'),
        array('starts-with', '$key', $keyStart),
        array('starts-with', '$Content-Type', '') // accept all files
    )
)));

$signature = base64_encode(hash_hmac('sha1', $policy, $secret, true));

?>

<!DOCTYPE html>
<html>
<head>
	<link href="css/font-awesome.min.css" rel="stylesheet" type="text/css">
	<link href="css/froala_editor.min.css" rel="stylesheet" type="text/css">

    <style>
        body {
            text-align: center;
        }

        section {
            width: 80%;
            margin: auto;
            text-align: left;
        }
    </style>
</head>

<body>
  <section id="editor">
      <div id='edit' style="margin-top: 30px;">
          <img src="img/cute_cat.jpg" alt="Cute cat" width="300" style="float: left; margin-right: 10px; margin-bottom: 10px; margin-top: 10px;"/>

          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec facilisis diam in odio iaculis blandit. Nunc eu mauris sit amet purus viverra gravida ut a dui. Vivamus nec rutrum augue, pharetra faucibus purus. Maecenas non orci sagittis, vehicula lorem et, dignissim nunc. Suspendisse suscipit, diam non varius facilisis, enim libero tincidunt magna, sit amet iaculis eros libero sit amet eros. Vestibulum a rhoncus felis. Nam lacus nulla, consequat ac lacus sit amet, accumsan pellentesque risus. Aenean viverra mi at urna mattis fermentum. Curabitur porta metus in tortor elementum, in semper nulla ullamcorper. Vestibulum mattis tempor tortor quis gravida. In rhoncus risus nibh. Nullam condimentum dapibus massa vel fringilla. Sed hendrerit sed est quis facilisis. Ut sit amet nibh sem. Pellentesque imperdiet mollis libero.</p>

          <p><a href="http://google.com" title="Aenean sed hendrerit">Aenean sed hendrerit</a> velit. Nullam eu mi dolor. Maecenas et erat risus. Nulla ac auctor diam, non aliquet ante. Fusce ullamcorper, ipsum id tempor lacinia, sem tellus malesuada libero, quis ornare sem massa in orci. Sed dictum dictum tristique. Proin eros turpis, ultricies eu sapien eget, ornare rutrum ipsum. Pellentesque eros nisl, ornare nec ipsum sed, aliquet sollicitudin erat. Nulla tincidunt porta vehicula.</p>

          <p>Nullam laoreet imperdiet orci ac euismod. Curabitur vel lectus nisi. Phasellus accumsan aliquet augue, eu rutrum tellus iaculis in. Nunc viverra ultrices mollis. Curabitur malesuada nunc massa, ut imperdiet arcu lobortis sed. Cras ac arcu mauris. Maecenas id lectus nisl. Donec consectetur scelerisque quam at ultricies. Nam quis magna iaculis, condimentum metus ut, elementum metus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vivamus id tempus nisi.</p>
      </div>
  </section>

  <script src="http://code.jquery.com/jquery-1.10.2.js"></script>
  <script src="js/froala_editor.min.js"></script>

  <script>
      $(function(){
          $('#edit').editable({
            inlineMode: false,
            imageUploadToS3: {
              bucket: '<?php echo $bucket; ?>',
              region: '<?php echo $region; ?>',
              keyStart: '<?php echo $keyStart; ?>',
              callback: function (url, key) {
                // The URL and Key returned from Amazon.
                console.log (url);
                console.log (key);
              },
              params: {
                acl: '<?php echo $acl; ?>',
                AWSAccessKeyId: '<?php echo $accessKeyId; ?>',
                policy: '<?php echo $policy; ?>',
                signature: '<?php echo $signature; ?>',
              }
            }
          })
      });
  </script>
</body>
</html>

```

**Comment by igas** [comment]
Hey, @stefanneculai 
> We'll write an article about that during this week.

Any update on this? I try to do S3 uploading with editor, but I think I missed something, probably on AWS side. More detailed post would be awesome. Thank you.

**Comment by stefanneculai** [comment]
Sorry, we had to delay a bit the posting of the article. You should also set the CORS on AWS like this: https://gist.github.com/stefanneculai/deed108fad534d0db3ff#file-cors-file

**Comment by igas** [comment]
@stefanneculai works like a charm, thank you!

**Comment by ahmadajmi** [comment]
Thanks @stefanneculai for posting the code for Ruby, I managed it to work as

`application_helper.rb`

``` ruby
  AWS_CONFIG = {
    'access_key_id' => '',
    'secret_access_key' => '',
    'bucket' => 'bucket-name',
    'acl' => 'public-read',
    'key_start' => 'uploads/'
  }

  def signature
    Base64.encode64(
        OpenSSL::HMAC.digest(
          OpenSSL::Digest.new('sha1'),
          AWS_CONFIG['secret_access_key'], policy
        )
      ).gsub("\n", "")
  end

  def policy
    Base64.encode64(self.policy_data.to_json).gsub("\n", "")
  end

  def policy_data
    {
      expiration: 10.hours.from_now.utc.iso8601,
      conditions: [
        ["starts-with", "$key", AWS_CONFIG['key_start']],
        ["starts-with", "$x-requested-with", "xhr"],
        ["content-length-range", 0, 20.megabytes],
        ["starts-with", "$content-type", ""],
        {bucket: AWS_CONFIG['bucket']},
        {acl: AWS_CONFIG['acl']},
        {success_action_status: "201"}
      ]
    }
  end

  def data_hash
    {:signature => self.signature, :policy => self.policy, :bucket => AWS_CONFIG['bucket'], :acl => AWS_CONFIG['acl'], :key_start => AWS_CONFIG['key_start'], :access_key => AWS_CONFIG['access_key_id']}
  end
```
Then we can use theses helpers `policy` as `#{policy}` and `signature` as `#{signature}` in our views like this example

``` javascript
  $(function() {
    var $editor = $('#editor-body');
    $editor.editable({
      inlineMode: false,
      imageUploadToS3: {
        bucket: 'bucket-name',
        region: 's3',
        keyStart: 'uploads/',
        callback: function (url, key) {
          // The URL and Key returned from Amazon.
          console.log (url);
          console.log (key);
        },
        params: {
          acl: 'public-read',
          AWSAccessKeyId: '',
          policy: "#{policy}",
          signature: "#{signature}",
        }
      }
    });
```

Thanks

**Comment by ravz** [comment]
hi, any chance of getting that article? would be nice to see an example done in Javascript

**Comment by MACscr** [comment]
You have $key and $Content-Type in your https://github.com/froala/wysiwyg-editor/blob/master/html/image_s3_upload.php, but those are never defined. Also, why are we putting sensitive values in javascript?

Its a bit frustrating that you state you support s3 for image/file storage, but the documentation for it is severely lacking. Im not sure how much I even trust the implementation should it work. =/

**Comment by stefanneculai** [comment]
$key and $Content-Type are strings not PHP variables. The example from master is fully working. You should make sure you set the `date_default_timezone_set`, `$accessKeyId` and `$secret`. Also, you should set the CORS correctly on AWS: https://gist.githubusercontent.com/stefanneculai/deed108fad534d0db3ff/raw/a8829d697dcd7f90b934be61862c94cb97e69d50/CORS%2520file

**Comment by p1Machado** [comment]
@sabanaqvi the reason why s3 is warning "Extra input fields: x-requested-with" is that Froala sets this field in every upload to s3 form. So you need to build your policy based on every field that has on the request form.

You can add a statement in the policy like: { "x-requested-with": "xhr" }, ou like @ahmadajmi already did: ["starts-with", "$x-requested-with", "xhr"], which means that s3 will check if the value of the field "x-requested-with" starts with "xhr".
