### ISSUE TITLE
Copy paste image does not work

### ISSUE THREAD

**Issue by hamusi** [froala/wysiwyg-editor#4065]
##### Expected behavior.
Pasted image from clipboard is uploaded to server, and then shown.

##### Actual behavior.
Uncaught ReferenceError: replace is not defined is thrown and image is pasted as base64

##### Steps to reproduce the problem.
Open Froala Editor demo on your pages and try to paste image from clipboard

##### Editor version.
3.2.2

##### OS.
macOS Catalina 10.15.7
##### Browser.
(Browser name an version here)
Google Chrome 85.0.4183.121
##### Recording.
(A recording showing how to reproduce the problem)

**Comment by dkharlan** [comment]
I'm also seeing this error, both on Chromium 83.0.4103.116 and Firefox 81.0.2.

**Comment by Nice2Work** [comment]
Yes seeing this as well, not sure how to fix this. And yes I do have the paid version.
This happens when you copy/paste an image into the editor. 

plugins.pkgd.min.js?2458:7 Uncaught ReferenceError: replace is not defined
    at Ze (plugins.pkgd.min.js?2458:7)
    at HTMLImageElement.eval (plugins.pkgd.min.js?2458:7)
    at v.each (froala_editor.min.js?3a37:7)
    at b.Bootstrap.et (plugins.pkgd.min.js?2458:7)
    at Object.C [as trigger] (froala_editor.min.js?3a37:7)
    at FileReader.tt (plugins.pkgd.min.js?2458:7)

**Comment by chille1987** [comment]
Anyone manage to solve this? I'm experiencing the same issue on latest version of froala.

**Comment by krissce** [comment]
This bug is since version 3.1.1 and it's still not fixed! Froala wake up.

**Comment by ostrui** [comment]
Does anyone have a solution?

**Comment by ilyaskarim** [comment]
Fixed in V3.2.5 https://froala.com/wysiwyg-editor/changelog/#3.2.5
