### ISSUE TITLE
The "Open Link" button in the link editing popup should open the link in a new tab rather than the current tab

### ISSUE THREAD

**Issue by earshinov** [froala/wysiwyg-editor#4088]
### Repro steps

1. Open any page with a Froala editor, e.g. https://froala.com/wysiwyg-editor/examples/link-styles/
2. Type in or copy-paste this link: https://yandex.ru/
3. Click the link to make the link editing popup appear
4. Click the "Open Link" button in the popup

![froala open link](https://user-images.githubusercontent.com/52021/98396026-2a1d8080-206e-11eb-8ae8-f7aaeec5108e.png)

Expected behavior:
- The link is opened in the new tab

Actual behavior: 
- The link is opened in the current tab

Why I consider the actual behavior wrong:
1. The user might accidentally lose his/her changes by navigating away from the page with the editor
2. Even if the user makes his/her intention to open the link in a new tab clear by ctrl-clicking or middle-clicking the "Open Link" button, the link is still opened in the current tab.

Personally, I like the UI approach taken by CKEditor (https://ckeditor.com/ckeditor-5/demo/):
![ckeditor open link](https://user-images.githubusercontent.com/52021/98396614-0ad32300-206f-11eb-8d4d-402d6f7da67b.png)
(but of course I don't expect you to regard CKEditor's implementation as a reference or an absolute truth you should blindly follow).

### Version information

Froala editor: v3.2.3
Browser: Google Chrome 86.0.4240.75 (Official Build) (32-bit)

**Comment by dejanmartinovic** [comment]
Hi. In order to achieve that, you can try to enable the `linkAlwaysBlank `option or to select the "Open in new tab" checkbox from the Edit Link popup.

**Comment by earshinov** [comment]
This option solves the problem with the button in edit mode, but it unconditionally adds `target="_blank"` to all links in the resulting HTML, leaving our users without an opportunity to make some links open in the current window. We can't do that.

I think that the way the button works in edit mode shouldn't depend on whether the link is configured to open in a new tab or in the current one. What is appropriate in the edit mode isn't always desired in the resulting HTML.

Ideally, the `linkAlwaysBlank` option would only control the resulting HTML. but the button should work as I described in the description, either always opening in a new tab or properly handling ctrl- or middle-click.

Again, just for reference, CKEditor always opens links in a new tab in edit mode:
https://stackblitz.com/edit/angular-ckeditor5-classsic

![image](https://user-images.githubusercontent.com/52021/98406135-7c669d80-207e-11eb-8b17-cc7c92cd9532.png)

Have I convinced you?

**Comment by dejanmartinovic** [comment]
You can easily create a custom button and replace the original one. 
Let me know if this example fits your needs: https://jsfiddle.net/dejan_m/og0hxf2t/4520/.

**Comment by earshinov** [comment]
Thanks, that works. Here is our code:

```ts
/**
 * Contents:
 *   - 'grtLinkOpen' command
 *
 * # 'grtLinkOpen' command
 *
 * The command to replace the standard 'linkOpen' in `linkEditButtons`.
 *
 * Usage example:
 *
 *   ```
 *   new FroalaEditor(el, {
 *     linkEditButtons: ['grtLinkOpen', 'linkStyle', 'linkEdit', 'linkRemove'],
 *   });
 *   ```
 *
 * The problem with the standard 'linkOpen' is that it opens the link either in the current tab or in a new tab
 * depending on what target is configured for the link by the user.  Also, it doesn't open the link in a new tab
 * even when Ctrl-clicked or middle-clicked.  The 'grtLinkOpen' command instead always opens the link in a new tab.
 *
 * References:
 *   - https://github.com/froala/wysiwyg-editor/issues/4088
 */

import * as Froala from 'froala-editor';

Froala.DefineIcon('grtLinkOpen', {
  NAME: 'external-link',
  FA5NAME: 'external-link-alt',
  SVG_KEY: 'openLink'
});

Froala.RegisterCommand('grtLinkOpen', {
  title: 'Open Link',
  undo: false,
  refresh: function refresh($btn) {
    const link = this.link.get();

    if (link) {
      $btn.removeClass('fr-hidden');
    } else {
      $btn.addClass('fr-hidden');
    }
  },
  callback: function callback() {
    const link = this.link.get();

    if (link) {
      if (link.href.indexOf('mailto:') !== -1) {
        window.open(link.href).close();
      } else {
        window.open(link.href, '_blank');
      }

      this.popups.hide('link.edit');
    }
  }
});
```
