### ISSUE TITLE
Adding liquid syntax with single quote changes content

### ISSUE THREAD

**Issue by giannik** [froala/wysiwyg-editor#4093]
When saving content with the following liquid syntax

{{ Content'guid' }}

it changes the content from froala.

If i remove the single quotes in the curly brackets it works as expected.

How can I tell froala to allow this syntax to be submitted as shown above.
Thanks 
Im using version 3 of froala version 3.2.1

**Comment by ilyaskarim** [comment]
https://youtu.be/KEI4qSrkPAs?si=1O6tPqE15zwC92F4
