### ISSUE TITLE
[Bug] Editor scrolling down on pressing enter in inline editor

### ISSUE THREAD

**Issue by Reforced** [froala/wysiwyg-editor#4096]
##### Expected behavior.
Enter a new line or paragraph and do not scroll when not needed

##### Actual behavior.
When pressing enter the editor always scrolls down

##### Steps to reproduce the problem.
- Open the inline [demo page](https://froala.com/wysiwyg-editor/examples/inline/) on Froala
- Enter a bunch of new lines (have a scrollbar)
- Go to some of the top lines and press enter; if it works normally, wait a bit and press at some different lines at the top and press enter
- Sooner or later the editor keeps jumping down on enter

##### Editor version.
3.2.3

##### OS.
Windows 10 Professional, version 1909, build 18363.1198

##### Browser.
Chrome 64bits, 86.0.4240.198

##### Recording.
![See here](https://i.imgur.com/oBj16FF.gif)

**Comment by arwinvdv** [comment]
They said that it will be fixed in 3.2.4 but the issue still exists... I have send them an mail.

**Comment by Reforced** [comment]
Seems indeed it has been fixed in v3.2.5. Nice work, team Froala!
