### ISSUE TITLE
blockStyles defaults show when editor does not have focus

### ISSUE THREAD

**Issue by twistedpixel** [froala/wysiwyg-editor#411]
When setting blockStyles at initialization, I find that until the editor has focus, the custom list shows the 4 defaults (Italic, typewriter, spaced and uppercase). When the editor is given focus, the custom menu items are there but then are replaced by defaults again after blur.

Is this a bug or is there a toggle I've missed?

On v1.2.5, OSX Mavericks, Safari 7.1

**Comment by stefanneculai** [comment]
This is the way it should have worked. There is an option for that default list `https://editor.froala.com/options#defaultBlockStyle`.
