### ISSUE TITLE
Can't move images

### ISSUE THREAD

**Issue by rachmann** [froala/wysiwyg-editor#412]
Latest version, as of this writing (v1.2.5), in Visual Studio MVC 5.2.2 razor site with bootstrap 3.3.1

Add image via URL, then 

When you try to move an image in the editor:

Exception was thrown at line 8, column 30778 in http://localhost:51234/Scripts/froala/froala_editor.min.js

0x80004005 - JavaScript runtime error: Unspecified error.

That part of the doc is the moveToPoint(b,c) call in the line:
if("undefined"!=typeof this.document.body.createTextRange)try{e=this.document.body.createTextRange(),e.moveToPoint(b,c);

**Comment by stefanneculai** [comment]
What browser and OS are you using?

**Comment by rachmann** [comment]
OS Windows 8.1 
Browsers: IE 11 - latest updates / Latest Chrome / Opera 27.0 / FireFox Dev Ed 37.0a2 (2015-01-27) / FireFox 35.0 / Safari 5.1.7  for Windows

oh - I figured it out... In the example page you use:

  imageButtons: ['floatImageLeft', 'floatImageNone', 'floatImageRight',
        'linkImage', 'info', 'removeImage'],

With that, all you get are the three default buttons as the others are invalid.

but the docs page have : 
imageButtons: ["display", "align", "linkImage", "replaceImage", "removeImage"].

With this list, the movement of images is possible in all browsers except Safari.

So just apply this bug to Safari 5.1.7  for Windows

**Comment by stefanneculai** [comment]
What do you mean by "example page"?

**Comment by rachmann** [comment]
https://editor.froala.com/examples/custom-image-button

**Comment by stefanneculai** [comment]
Image move is not available for Safari under Windows because of some browser limitations.

We updated the example error.

**Comment by rachmann** [comment]
That's understandable!
