### ISSUE TITLE
CORS proxy certificate has expired

### ISSUE THREAD

**Issue by seahorsepip** [froala/wysiwyg-editor#4123]
https://cors-anywhere.froala.com/

The SSL certificate on the above domain has expired.

**Comment by Lootvoet** [comment]
Same for https://i.froala.com/

**Comment by mikedaly** [comment]
Come on, Froala. This shouldn't be that hard.

**Comment by mikedaly** [comment]
I believe this issues has now been resolved.

**Comment by seahorsepip** [comment]
@mikedaly certificate seems renewed indeed.
