### ISSUE TITLE
Can't drop image

### ISSUE THREAD

**Issue by rachmann** [froala/wysiwyg-editor#413]
Latest version, as of this writing (v1.2.5), in Visual Studio MVC 5.2.2 razor site with bootstrap 3.3.1

When you try to add an image by dropping it on the image tool window, the file actually makes it to the upload directory, but the image doesn't show up

**Comment by stefanneculai** [comment]
Happens only when the cursor is not in the editor.

**Comment by rachmann** [comment]
I'm sorry, I don't understand what you mean. To drop an image, you need to place your cursor in the editor where you expect to see the image. You then need to click the image tool... Then you use your mouse to go to another folder window from your PC and drag an image over the 'Drop Image' area of the tool. The Cursor is wherever it is.

**Comment by kotmatpockuh** [comment]
@rachmann you tried this commit (f2eb7e1)?
because if i click on drop area, and from fileBrowser drop image into area - nothing happened in ie 10 & 11, but in other browsers all is ok
