### ISSUE TITLE
Option "fontAwesomeSets" not working since 3.2.5

### ISSUE THREAD

**Issue by jmsche** [froala/wysiwyg-editor#4153]
##### Expected behavior.
Option `fontAwesomeSets` to be working

##### Actual behavior.
Option `fontAwesomeSets` not working anymore

##### Steps to reproduce the problem.
I set the `fontAwesomeSets` option with a simple set, with one category and 4 icons.

The set is correctly displayed when using < 3.2.5 version; after this one, the option does not seem to be handled by the editor, and all categories/icons are shown.

The only thing I changed is the version in my package.json file & upgraded using yarn.

##### Editor version.
It was working well to 3.2.4. After upgrading to 3.2.5 or 3.2.6 it does not.

##### OS.
Linux Mint, but does not seem to be an OS issue.

##### Browser.
Chrome & Firefox latest.

##### Recording.
No recordings, but:

Screenshot w/ 3.2.5 or 3.2.6 (bugged):
![image](https://user-images.githubusercontent.com/3929498/105844721-f3eefd80-5fd9-11eb-8ba7-c6ba8ad17614.png)

Screenshot w/ 3.2.4 (correct, expected):
![image](https://user-images.githubusercontent.com/3929498/105844812-1bde6100-5fda-11eb-9b00-7cccb4a2ecc7.png)

**Comment by jmsche** [comment]
Here is a jsFiddle that's working (3.2.4): https://jsfiddle.net/5wo8y7du/
And here is a jsFiddle that's not working (3.2.6): https://jsfiddle.net/5wo8y7du/1/

As you can see, only the version of Froala Editor in Resources changed.

**Comment by MeghashreeAP** [comment]
Thank you for your feedback. 
The request has been reported to the product management team for evaluation and consideration for an upcoming release.

**Comment by jmsche** [comment]
@MeghashreeAP thank you.

I hope this will be fixed in the v3 branch?

**Comment by jmsche** [comment]
FYI it's still not working with latest v4.0.12: https://jsfiddle.net/u3amzxf4/

**Comment by ilyaskarim** [comment]
The fontAwesomeSets object key has been slightly adjusted after V3.2.5, In order to configure the font set, You'll need to define the option as fontAwesome5Sets, Please take a  look at this working demo: 
https://jsfiddle.net/ilyasfroaal/xdfk6cpj/2/.
