### ISSUE TITLE
font awesome not working on Froala 3.2.6.

### ISSUE THREAD

**Issue by manttih** [froala/wysiwyg-editor#4157]
##### Expected behavior.
Font Awesome Icon should be inserted at cursor position when clicking it on popup

##### Actual behavior.
Nothing happens. Icon isn't inserted and the popup remains open

##### Steps to reproduce the problem.
go to Froala website: https://froala.com/wysiwyg-editor/inline/ or https://froala.com/wysiwyg-editor/. Try to insert icon from Fontawesome. The toolbar opens as it should, but when you click the icon, nothing happens

##### Editor version.
3.2.6.

##### OS.
Windows 10

##### Browser.
Firefox / Chrome

##### Recording.
(A recording showing how to reproduce the problem)

**Comment by NoSoup4you2** [comment]
Is there an update on this or just another case where the dev team of froala breaks things and then ignores them for years to come

**Comment by MeghashreeAP** [comment]
Thank you for your feedback.
This issue is not reproducible on v4.0.9 branch.

**Comment by NoSoup4you2** [comment]
Wow it took a year to address this bug, worst support ever.

**Comment by MeghashreeAP** [comment]
Thanks for your feedback.
This issue is not reproducible or have been found to be fixed on the latest Froala release v4.0.8.
Can you please upgrade and check?

**Comment by NoSoup4you2** [comment]
This is the typical response from MeghashreeAP and reflects the support skills at Froala. You might have fixed it in current release but not in the 3.2.6 one as it was even reproducible at the time on your website via the provided demo.

**Comment by ilyaskarim** [comment]
Fixed in V3.2.6-1
