### ISSUE TITLE
Cursor jumps to another editor instance

### ISSUE THREAD

**Issue by petrinecp** [froala/wysiwyg-editor#4158]
##### Expected behavior.
Cursor stays in the instance where the user clicked.

##### Actual behavior.
Cursor jumps to another editor instance when user clicks to empty new line.

##### Steps to reproduce the problem.
1. Add two instance of Froala editor on page both with `toolbarInline: true` and `toolbarVisibleWithoutSelection: true` and initialize the editors on text where there is an empty line
2. After initialization/page load, click inside the empty line
3. The cursor and toolbar briefly appears in the instance where user clicked but after a second the cursor jumps to the next instance

See [jsFiddle](https://jsfiddle.net/47n9bfrh/).

##### Editor version.
3.2.6

##### OS.
Windows 10

##### Browser.
Chrome Version 88.0.4324.104 (Official Build) (64-bit)

**Comment by petrinecp** [comment]
Still present on v2.3.7
https://jsfiddle.net/oq8k709b/

![froala-cursor-jump](https://user-images.githubusercontent.com/5637849/121526629-da36db80-c9f9-11eb-8ac9-9df8fbf9aeae.gif)

**Comment by MeghashreeAP** [comment]
Thank you for your feedback.
This issue is not reproducible on latest branch.

**Comment by MeghashreeAP** [comment]
Thank you for your feedback.
This issue is not reproducible on latest branch.

**Comment by petrinecp** [comment]
Yes this issue was fixed in 4.0.8.
