### ISSUE TITLE
Position of dialog popup is incorrect on scroll

### ISSUE THREAD

**Issue by EugeCos** [froala/wysiwyg-editor#4159]
##### Expected behavior.
Dialog popup to remain within editor boundaries on vertical scroll.

##### Actual behavior.
Position of dialog popup appears to be sticky to page body.

##### Steps to reproduce the problem.
1. Add an image / video / link. 
2. Click on it for Edit popup to open.
3. Scroll up or down using a pad / mouse scroll wheel.

Adding `scrollableContainer` with id of the parent that holds the Editor did not help. 

##### Editor version.
3.2.6

##### OS.
Windows 10

##### Browser.
Chrome

##### Recording.
![1](https://user-images.githubusercontent.com/31284726/106522420-b690e100-64ad-11eb-83c7-537260310b38.gif)

**Comment by EugeCos** [comment]
Resolved by adding id of parent wrapper to `scrollabeContainer`.

**Comment by mrugankalondhe** [comment]
@EugeCos I am running into the same issue, could you please post a snippet of your code. I am not following of how you resolved it. Thanks!
