### ISSUE TITLE
How do you disable iOS pop up menu?

### ISSUE THREAD

**Issue by adamgins** [froala/wysiwyg-editor#416]
HI,

we have Froala competing with iOS pop menus which does not allow you to select text properly. For example:

![image](https://cloud.githubusercontent.com/assets/7233741/5952630/52188332-a7cf-11e4-82d5-f458c362d0c4.png)

It seems similar to 
https://github.com/froala/wysiwyg-editor/issues/247

Is there some option to disable this or some other approach, pls?

**Comment by stefanneculai** [comment]
Unfortunately, it's impossible to disable the iOS menu. Apple doesn't allow that.
