### ISSUE TITLE
editor.format.removeStyle() in IE11 cannot remove styling when entire paragraph is selected

### ISSUE THREAD

**Issue by weimingw** [froala/wysiwyg-editor#4161]
The editor.format.removeStyle() method does not correctly remove style for IE11 when the entire paragraph is selected

##### Expected behavior.
When the entire paragraph is selected, calling editor.format.removeStyle() will remove styling for the style given (in my example, font-family)

##### Actual behavior.
It applies null to the style instead, e.g. font-family: null;

##### Steps to reproduce the problem.
See it here: https://codepen.io/weimingw/pen/PobqvbV
For an IE11 accessible version: https://cdpn.io/weimingw/debug/PobqvbV/NjkYzGqYmbpM
1. Add content to the editor
2. Select the entire paragraph. Apply styling to the paragraph. (Click Add Style)
3. Call editor.format.removeStyle() on the style applied. (Click Remove Style)

##### Editor version.
3.2.6

##### OS.
Windows 10

##### Browser.
IE11

##### Recording.
https://user-images.githubusercontent.com/7664881/106683278-13a59900-6579-11eb-80b6-9cb831bdb454.mp4

**Comment by MeghashreeAP** [comment]
Thank you for your feedback.
This issue is not reproducible on v4.0.9 branch.

**Comment by MeghashreeAP** [comment]
Thank you for your feedback.
This issue is not reproducible on latest branch.

**Comment by ilyaskarim** [comment]
Issue is not reproducible on latest version, Hence closing the issue
