### ISSUE TITLE
Remove css from Headers (H1,H2)

### ISSUE THREAD

**Issue by limitisthesky** [froala/wysiwyg-editor#4162]
##### Expected behavior.
Change the text to headings level for example H1, H2
Save the text
Edit the text again and change the heading text to "Normal" 
That shall remove heading tags and any css inside header tag

##### Actual behavior.
Change the text to headings level-1  H1
Save the text
Edit the text again and change the heading text to "Normal" or another header H2, H3 etc
Nothing happens, size of the text is not changing

**Comment by AkshayCM** [comment]
Thank you for your feedback.
This issue is not reproducible on v4.0.9 branch.

**Comment by MeghashreeAP** [comment]
Thank you for your feedback.
This issue is not reproducible on latest branch.

**Comment by ilyaskarim** [comment]
Issue is not reproducible on latest
