### ISSUE TITLE
extract html with inline styles instead of classes

### ISSUE THREAD

**Issue by gisheri** [froala/wysiwyg-editor#418]
In the docs I cannot find a method to extract the html with inline styles. If people use this editor to setup an email, is there a solution they are using? Thanks.

**Comment by philfreo** [comment]
You might want to use something like Premailer 

http://premailer.dialect.ca
https://github.com/premailer/premailer

**Comment by philfreo** [comment]
I'm using Froala for html email also, though I haven't yet cared about anything that rely on classes (not supporting image alignment, etc.). If I were I'd probably go with something like Premailer.

**Comment by stefanneculai** [comment]
https://editor.froala.com/options#useClasses converts image classes to inline style. Shoukd be what you're looking for.

**Comment by philfreo** [comment]
Oh cool. Not sure what classes @gisheri is talking about by I may try out this option at some point :+1:

**Comment by gisheri** [comment]
Thank you. That worked perfectly. I appreciate the help
