### ISSUE TITLE
Page position jumps around when adding a new line on iOS Safari or Chrome

### ISSUE THREAD

**Issue by nratter** [froala/wysiwyg-editor#4184]
I've tested this at https://froala.com/wysiwyg-editor by typing in the WYSIWYG editor on that page using Safari and Chrome on iOS. I'm not sure what version of the wysiwyg-editor is running at that URL, but 3.2.6-1 is the latest when this issue was created. About every other time you hit the return button to produce a new line, the screen position moves up and the input cursor is out of view. We'd like to purchase a license for Froala but this bug is preventing us from putting it in production. Please let me know if there are any workarounds in the meantime.

ios 14.4

Loom: https://www.loom.com/share/833e481fd31f424b934e60afe8744c78

Thanks!

**Comment by manttih** [comment]
This is an issue also at least on Firefox, editor version is the latest (3.2.6.). When I hit enter enough times to create paragraphs (inline editor), the view starts to jump at the top. It is deeply annoying and hope this will be fixed asap.

**Comment by AkshayCM** [comment]
Thanks for your feedback.
This issue is not reproducible or have been found to be fixed on the latest Froala release v4.0.8. Can you please upgrade and check?

**Comment by nratter** [comment]
@AkshayCM I'll upgrade on Tuesday and check and report back. Thanks!

**Comment by nratter** [comment]
> Thanks for your feedback. This issue is not reproducible or have been found to be fixed on the latest Froala release v4.0.8. Can you please upgrade and check?

I'll check on Tuesday 2/8/22 and report back. Thanks!
