### ISSUE TITLE
Indentation creates list

### ISSUE THREAD

**Issue by kishorethecoder** [froala/wysiwyg-editor#4186]
##### Expected behavior.
Indentation should not create the list

##### Actual behavior.
Indentation creating the list

##### Steps to reproduce the problem.

1. Go to https://froala.com/wysiwyg-editor
2. Add some lines of data
3. Click on Increase Indent Option
4. see the list is created for normal data

##### Editor version.
Latest

##### Browser.
Chrome

##### Recording.
For more details, view this [video](https://www.awesomescreenshot.com/video/3012270?key=62e03ef47e1101fa9fc5fb551737d480)

**Comment by shnigi** [comment]
Can confirm I have the same bug.

**Comment by HiHub-Online** [comment]
Is there any news about this bug?
The latest updates are very annoying with a lot of bugs in the existing functionality

**Comment by MeghashreeAP** [comment]
Thank you for your feedback.
This issue is not reproducible on latest branch.

**Comment by ledicana** [comment]
This isn't fixed completely, not even in the version 4.0.9. If you first apply the indent and then the list option, there are multiple issues:
1. The indent button is deactivated, as I suppose it should be. But if you click multiple times on outdent option, the indent button will be activated again.
2. If you then click on the indent button, the existing list is wrapped in another list. 

The errors happen also in the official demo on the Froala site.

**Comment by vidal7** [comment]
I can confirm that @ledicana bug is still present in 4.0.15 but not in 4.0.5.
