### ISSUE TITLE
list-style-position: inside causes an extra blank line if list contains nested paragraphs

### ISSUE THREAD

**Issue by earshinov** [froala/wysiwyg-editor#4190]
Demo document, just to give you something to experiment with:
https://docs.google.com/document/d/1m4VoDq0rV08o6LqG376wb8JfBW0MwNCqzEvxDEZBPPA/edit

### Repro steps

1. Copy the list from the Google Docs document

![image](https://user-images.githubusercontent.com/52021/111031119-ffc24200-8416-11eb-8c81-83f300655f91.png)

2. Open Froala example https://froala.com/wysiwyg-editor/examples/live-code-preview/

3. Paste the list into Froala

Expected behavior:
- After paste, the list in Froala should look like the list in Google Docs

Actual behavior:
- There are extra blank lines

![image](https://user-images.githubusercontent.com/52021/111031110-f33de980-8416-11eb-8fb0-e2707cc9c5c1.png)

### Editor version

Reproducible in latest release (3.2.6-1)

### Environment

- Windows 10 x64 version 1909
- Google Chrome 89.0.4389.82

### Error cause and possible fix

Blank lines are caused by the following style defined in Froala (`froala-editor/css/froala_style.min.css`):

```
.fr-view ul,.fr-view ol{list-style-position:inside}
```

which, in presence of a nested paragraph, makes the bullet point be placed on its own line.

A possible fix would be to replace this style with `list-style-position: outside` (the browser default). I am not sure why Froala opted in for `inside` in the first place.

### Severity

Because the problem lies in CSS and not in the HTML content, the only way for the user to get rid of the blank lines is to retype everything from scratch, which is far from great experience.

### Related issues

- Possibly, https://github.com/froala/wysiwyg-editor/issues/3093

**Comment by MeghashreeAP** [comment]
Thanks for your feedback.
This issue is not reproducible or have been found to be fixed on the latest Froala release v4.0.8.
Can you please upgrade and check?

**Comment by earshinov** [comment]
I can confirm that this issue is fixed in 4.0.9.

Here is what the pasted document looks like in our installation of Froala:
![image](https://user-images.githubusercontent.com/52021/152974090-7c6e6bc4-cd4f-4aec-b605-b4c43e1e6170.png)
