### ISSUE TITLE
table in div element

### ISSUE THREAD

**Issue by kaniansky** [froala/wysiwyg-editor#4191]
### Expected behavior.
Table editing popup should appear

### Actual behavior.
An error is thrown with no table editing popup

### Steps to reproduce the problem.
1. Use [Froala editor with a table plugin](https://froala.com/wysiwyg-editor/examples/full-featured/)
2. Edit source to have `table` element within `div` element. E.g:
```
<div>
	<table>
		<tr>
			<td>test</td>
		</tr>
	</table>
</div>
```
3. Click inside the table

### Editor version.
3.2.6-1

**Comment by kaniansky** [comment]
I just found out this is a duplicate of https://github.com/froala/wysiwyg-editor/issues/4155

**Comment by earshinov** [comment]
@kaniansky , I think it's better to close this ticket then. There are enough open tickets in this repo, and having duplicates makes it worse. Don't rely on Froala developers to close the ticket for you, they hardly ever read their own GitHub.
