### ISSUE TITLE
videoEditButtons without 'autoplay' and 'videoReplace' crashed popup

### ISSUE THREAD

**Issue by BoyeMagnus** [froala/wysiwyg-editor#4196]
##### Expected behavior.
https://froala.com/wysiwyg-editor/docs/options/#videoEditButtons
Video edit button won't work without containing 'autoplay' and 'videoReplace'
When not containing it, then it will throw js error.

##### Actual behavior.
It's expected to work without setting 'autoplay' and 'videoReplace'

##### Steps to reproduce the problem.
1. Add editor with video. 
2. Add: `videoEditButtons: ['videoDisplay', 'videoRemove']` to the config.
3. Click on a video to edit it, now it'll throw an error and not show the popup

##### Editor version.
3.2.6-1

##### OS.
MacOSX

##### Browser.
Chrome Version 89.0.4389.90

##### Recording.
(A recording showing how to reproduce the problem)
![image](https://user-images.githubusercontent.com/24491343/111707567-955d3780-8844-11eb-9e88-b50978689b30.png)

Formatted min js file here. It checks for autoplay + some id:
![image](https://user-images.githubusercontent.com/24491343/111707642-bb82d780-8844-11eb-899a-df967b176dca.png)

**Comment by szymczdm** [comment]
Same issue. The code should really check for the existence of those buttons before attempting to grab their style.

**Comment by BoyeMagnus** [comment]
Resolved by updating
