### ISSUE TITLE
Regression in 3.2.6-1: `table.edit` popup no longer shows when several cells are selected

### ISSUE THREAD

**Issue by earshinov** [froala/wysiwyg-editor#4199]
**Demo**

Please see CodeSandbox:
  - Froala v3.2.6: https://codesandbox.io/s/angular-froala-table-326-c676k?file=/src/app/model/default-content.ts:0-2134 - ok
  - Froala v3.2.6-1: https://codesandbox.io/s/angular-froala-table-3261-keelo?file=/src/app/model/default-content.ts - not ok

**Repro steps**
  1. Select several cells:
 
![image](https://user-images.githubusercontent.com/52021/112049098-3a875100-8b
60-11eb-8fa2-5314a55cacf2.png)

**Expected behavior**
  - Table properties popup should appear:

![image](https://user-images.githubusercontent.com/52021/112049188-5854b600-8b60-11eb-9f86-36a5751375ca.png)

**Actual behavior**
  - The popup appears in v3.2.6, but not in v3.2.6-1

**Version information**

Browser: Google Chrome 89.0.4389.90
Froala: regression in 3.2.6-1

![froala diff](https://user-images.githubusercontent.com/52021/112049347-8f2acc00-8b60-11eb-9c0d-b0c072112055.png)

**Comment by kaniansky** [comment]
Duplicate of #4155, #4191, #4198 and #4197

**Comment by earshinov** [comment]
@kaniansky , I don't think it's a duplicate. In the case I describe in this issue there is no tag around the table, and no `Uncaught TypeError: Cannot read property 'length' of undefined` exception.

**Comment by earshinov** [comment]
Also, this only happen in v3.2.6-1, which rules out #4155 at least.

**Comment by beatrixmorar** [comment]
This seems to be a duplicate of #4206 
Is there some kind of workaround to make this work with v3.2.6-1? Or is there any information from Froala, when should we expect a fix for this?

**Comment by earshinov** [comment]
@beatrixmorar , here is what Froala Support replied (we have a paid license):

> I've submitted the bug to the dev-team but a timeframe for a fix for this issue is not yet been established.

We chose to roll back to 3.2.6.

**Comment by AkshayCM** [comment]
Thanks for your feedback.
This issue is not reproducible or have been found to be fixed on the latest Froala release v4.0.8. Can you please upgrade and check?

**Comment by earshinov** [comment]
I can confirm that this issue is fixed in 4.0.9

**Comment by pmasekito** [comment]
I think this is back in 4.2.
