### ISSUE TITLE
Not save empty textarea

### ISSUE THREAD

**Issue by GomDani** [froala/wysiwyg-editor#420]
When paragraphy is true and save empty editor in DB, save `&lt;p&gt;&lt;br&gt;&lt;/p&gt;`

Is possible to remove this when editor is empty?

**Comment by stefanneculai** [comment]
It shouldn't happen on the master version. Have you tried it?

**Comment by stefanneculai** [comment]
There is a fix committed few days ago 3f376e1bd548c4d0f87c10b95ffddd4d847c7e0b.

**Comment by GomDani** [comment]
I try and is OK. Previously I downloaded from https://editor.froala.com/.

Thanks.
