### ISSUE TITLE
Cannot format multiple table cells with mouse drag

### ISSUE THREAD

**Issue by phixle-** [froala/wysiwyg-editor#4206]
##### Expected behavior.
Drag select marks multiple cells and on mouseup display formatting popup.

##### Actual behavior.
Popup does not appear when drag selecting.

##### Steps to reproduce the problem.
1. Click and hold one cell.
2. Drag over other cells to select them.
3. Release mouse click.

##### Editor version.
3.2.6-1

##### OS.
macOS Cataline Version 10.15.7

##### Browser.
Google Chrome Version 88.0.4324.150

##### Recording.

https://user-images.githubusercontent.com/8505946/113152108-126db100-9236-11eb-8202-1a2330cc6f1d.mov

##### Comment
This worked in version 3.1.1.

It works correctly when the code `var f=u.selection.element().parentElement.getAttribute("contenteditable");f&&"false"===f?g[e].removeClass("fr-active"):g[e].addClass("fr-active")` is replaced by `g[e].addClass("fr-active")`.

**Comment by AkshayCM** [comment]
Thank you for your feedback.
This issue is not reproducible on v4.0.9 branch.

**Comment by AkshayCM** [comment]
Thanks for your feedback.
This issue is not reproducible on the latest branch.

**Comment by phixle-** [comment]
Hi! This issue is not present in upgraded version!
