### ISSUE TITLE
<object data="javascript:..."> XSS is not sanitized 

### ISSUE THREAD

**Issue by flaffyyeti** [froala/wysiwyg-editor#4219]
When <object data="javascript:..."> it is included in source view. It should be sanitized to prevent JavaScript execution.

On current https://froala.com/wysiwyg-editor/ page, the issue could be reproduced on Firefox browser. 

Browser.
Firefox 79.0

Recording
![froala_xss](https://user-images.githubusercontent.com/31208791/115876364-e5847680-a44e-11eb-87cf-c734b5da592f.gif)

**Comment by AkshayCM** [comment]
Thank you for your feedback. The request has been reported to the product management team for evaluation and consideration for an upcoming release.

**Comment by skazis** [comment]
Hi, what's the progress with this bug? Security audits do not like this.

@AkshayCM - what did the management team concluded?

**Comment by ilyaskarim** [comment]
You'll need to include the domPurify library in order to sanitize the HTML, please see: https://jsfiddle.net/shashikantu7/hu20xo4d/2/.
