### ISSUE TITLE
Form inputs are stripped out when the editor is empty

### ISSUE THREAD

**Issue by devmondo** [froala/wysiwyg-editor#422]
hi, 
if i want to put this either by code or in html mode it gets stripped out even though in the docs it is mentioned that textarea is allowed tag! i even went a step a head and added textarea manually to allowed tags

```
 <textarea id="content-preview" value.bind="content" name="content-preview"></textarea>
```

thanks in advanced

**Comment by stefanneculai** [comment]
I tried that on the master version and on our website and it doesn't happen. Please make sure you use the latest version.

**Comment by devmondo** [comment]
thank you but it does not work, 

i downloaded latest master an here is my code

```
 this.editableArea.editable({inlineMode: false, allowedTags: ["p", "h1", "h2", "h3", "h4", "textarea","custom", "h6"],beautifyCode: false});
```

and if i paste this in html mode or even in wisiwig mode it get stripped out
```
<custom user.two-way="content"></custom>
````

or this 
```
 <textarea id="content-preview" value.bind="content" name="content-preview"></textarea>
```

**Comment by stefanneculai** [comment]
I checked again and indeed it seems to happen, BUT ONLY when the editor is empty.
