### ISSUE TITLE
Indentation convert the element into a list

### ISSUE THREAD

**Issue by mounir-ul** [froala/wysiwyg-editor#4220]
##### Expected behavior.
The indent option should either add a class or a style attribute to the selected element
`<p style="margin-left: 20px;">SOME TEXT</p>`

##### Actual behavior.
The indent option wraps the selected element on a bulleted list
`<ul><li style="list-style-type: none;"><ul><li><p style="margin-left: 20px;">SOME TEXT</p></li></ul></li></ul>`

##### Steps to reproduce the problem.
1.	Go to https://froala.com/wysiwyg-editor
2.	Add some lines of data
3.	Click on Increase Indent option

##### Editor version.
v3.2.3 and above

##### Browser.
All major browsers

##### Recording.
https://www.awesomescreenshot.com/video/3521214

**Comment by kishorethecoder** [comment]
#4186, same issue

**Comment by AkshayCM** [comment]
Thanks for your feedback.
This issue is not reproducible on the latest branch.
