### ISSUE TITLE
Issue when restoring saved formatted text

### ISSUE THREAD

**Issue by dh-fallen** [froala/wysiwyg-editor#423]
I am trying to integrate the Froala Editor v1.2.5 within my html projet, which use KnockoutJS for two way binding purposes : I have written a custom binding accordingly : 

```
// custom binding
ko.bindingHandlers.froalaEditor = {
    init: function (element, valueAccessor, allBindings) {
        var options = {
            inlineMode: false,
            alwaysBlank: false
        };
        $(element).editable(options);
        $(element).on('editable.contentChanged', function (e, editor) {
            var html = editor.getHTML();
            observable = valueAccessor();
            observable(html);
        });

        // handle disposal (if KO removed by the template binding)
        ko.utils.domNodeDisposal.addDisposeCallback(element, function () {
            $(element).editable("destroy");
        });
    },
    update: function (element, valueAccessor) {
        var value = ko.utils.unwrapObservable(valueAccessor());
        if (value !== null && $(element).editable("getHTML") !== value) {
            $(element).editable("setHTML", value);
        }
    }
}
```

The setup works fine, but when I'm using formatting options such as text color or size, the generated HTML looks odd : 

`<p><span style="current: 0; font-size: 13px;"><span style="findByProperty: function (prop, value) {	for(var i = 0 ; i < this.length ; i++) {		if (this[i][prop] === value) {			return this[i];		}	}}; next: function () {    if (!((this.current + 1) in this)) return false;    return this[++this.current];}; prev: function () {    if (!((this.current - 1) in this)) return false;    return this[--this.current];}; removeIf: function (callback) {	var i = this.length;	while (i--) {		if (callback(this[i], i)) {			this.splice(i, 1);		}	}}; swapItems: function (a, b) {	this[a] = this.splice(b, 1, this[a])[0];	return this;};">test</span></span></p>`

And when i'm trying to restore such content into the editor in the update callback with $(element).editable("setHTML", value), my browser seems to enter an infinite loop and does not respond. 

I am willing to use the editor in a commercial website, and therefore to purchase a licence ... but only if i'm able to make things works in my particular context.

Thanks a lot.
Camille L.

**Comment by stefanneculai** [comment]
Could you please make a jsFiddle?

**Comment by dh-fallen** [comment]
I have made one : http://jsfiddle.net/camlaborde/7z4be2rt/1/

But I'm not able to reproduce my issue : the generated html seems fine when I change font size ... It's strange, in my application, i can't see the "Unlicensed Froala Editor" as well.

**Comment by stefanneculai** [comment]
The "Unlicensed Froala Editor" doesn't appear on localhost, that's why you don't see it. However that doesn't affect the way the editor works.

I believe you have some other code that affects this somehow. Since that works on jsFiddle, I don't believe that the issues you're getting are related to the editor. If you could reproduce it on jsFiddle or send a link to your application we can investigate it further (if you don't want to put the link here you could contact us via http://editor.froala.com/contact as well).

**Comment by dh-fallen** [comment]
I have reproduce the issue on jsfiddle : http://jsfiddle.net/camlaborde/7z4be2rt/4/
To reproduce it, just change the text size.
It seems that the issue is caused by adding new functions to the Array prototype...

**Comment by stefanneculai** [comment]
Thanks. We'll investigate shortly.
