### ISSUE TITLE
[SOLVED] Uploading image return error code 3, in the console 405 (Method Not Allowed)

### ISSUE THREAD

**Issue by MadCatLab** [froala/wysiwyg-editor#4230]
**Javascript:**
`
new FroalaEditor('div#froalaEditor', {
        placeholderText: '',

        imageUploadMethod: 'POST',

        imageUploadURL: '/BE_HDUpload',

        imageUploadParam: 'file',
        imageUploadParams: {
            id: 'my_editor'
        },
        events: {
            'image.beforeUpload': function (images) {
                // Return false if you want to stop the image upload.
            },
            'image.uploaded': function (response) {
                // Image was uploaded to the server.
            },
            'image.inserted': function ($img, response) {
                // Image was inserted in the editor.
            },
            'image.replaced': function ($img, response) {
                // Image was replaced in the editor.
            },
            'image.error': function (error, response) {
                if (error.code == 1) { alert("Bad link"); }

                else if (error.code == 2) { alert("No link in upload response."); }

                else if (error.code == 3) { alert("Error during image upload."); }

                else if (error.code == 4) { alert("Parsing response failed."); }
 
                else if (error.code == 5) { alert("Image too text-large."); }

                else if (error.code == 6) { alert("Invalid image type."); }

                else if (error.code == 7) { alert("Image can be uploaded only to same domain in IE 8 and IE 9."); }

                // Response contains the original server response to the request if available.
            }
        },

        fileUploadURL: '/BE_HDUpload',
        charCountercount: false,
        heightMin: 100,
        attribution: false,
        pastePlain: true,
        
        toolbarButtons: ['fullscreen', 'undo', 'redo', '|', 'bold', 'italic', 'underline', '|', 'align', 'formatOL', 'formatUL', '|', 'insertLink', 'insertImage', 'embedly', 'insertFile', '|', 'emoticons', '|']
    })
`

**Backend:**
`
public partial class Upload : Page
{
    protected void Page_Load(object sender, EventArgs e)
    {
        if (Request.Files["file"] != null)
        {
            HttpPostedFile MyFile = Request.Files["file"];

            // Setting location to upload files
            string TargetLocation = Server.MapPath("~/Files/");

            try
            {
                if (MyFile.ContentLength > 0)
                {
                    // Get File Extension
                    string Extension = Path.GetExtension(MyFile.FileName);

                    //Determining file name. You can format it as you wish.
                    string FileName = Path.GetFileName(MyFile.FileName);

                    // Generate random name.
                    FileName = Guid.NewGuid().ToString().Substring(0, 8);

                    // Determining file size.
                    int FileSize = MyFile.ContentLength;

                    // Creating a byte array corresponding to file size.
                    byte[] FileByteArray = new byte[FileSize];

                    // Basic validation for file extension
                    //string[] AllowedExtension = { ".gif", ".jpeg", ".jpg", ".png", ".svg", ".blob" };

                    // Basic validation for mime type
                    //string[] AllowedMimeType = { "image/gif", "image/jpeg", "image/pjpeg", "image/x-png", "image/png", "image/svg+xml" };

                    //if (AllowedExtension.Contains(Extension) && AllowedMimeType.Contains(MimeMapping.GetMimeMapping(MyFile.FileName)))
                    //{
                        // Posted file is being pushed into byte array.
                        MyFile.InputStream.Read(FileByteArray, 0, FileSize);

                        // Uploading properly formatted file to server.
                        MyFile.SaveAs(TargetLocation + FileName + Extension);

                        string json = "";
                        Hashtable resp = new Hashtable();
                        string urlPath = MapURL(TargetLocation) + FileName + Extension;

                        // Make the response an json object
                        resp.Add("link", urlPath);
                        json = JsonConvert.SerializeObject(resp);

                        // Clear and send the response back to the browser.
                        Response.Clear();
                        Response.ContentType = "application/json; charset=utf-8";
                        Response.Write(json);
                        Response.End();
                    //}
                    //else
                    //{
                    //    // Handle upload errors.
                    //}
                }
            }

            catch (Exception ex)
            {
                // Handle errors
            }
        }
    }

    // Convert file path to url
    // http://stackoverflow.com/questions/16007/how-do-i-convert-a-file-path-to-a-url-in-asp-net
    private string MapURL(string path)
    {
        string appPath = Server.MapPath("/").ToLower();
        return string.Format("/{0}", path.ToLower().Replace(appPath, "").Replace(@"\", "/"));
    }
} `

Here's the error from Chrome console:
![Cattura1](https://user-images.githubusercontent.com/80025149/117842433-37663280-b27e-11eb-9e05-d407cf55de76.PNG)

Thank you in advance for your help.

**Comment by Krisell** [comment]
This is your server (listening at `localhost:60733`) that doesn't allow `POST` requests to `/BE_HDUpload`, I don't think this has anything to do with Froala.

**Comment by MadCatLab** [comment]
My fault: wrong url! -.-''
Thanks for your answer.
