### ISSUE TITLE
Custom insertHTML buttons

### ISSUE THREAD

**Issue by sabanaqvi** [froala/wysiwyg-editor#424]
I have the need to make a double underline button. I tried making a custom button that does an insertHTML with the span tag with style='border-bottom:double black' added around it. This works great until I select another word in the same paragraph and try to apply any common style like bold or italics to it. It removes my double underline styling. How can I avoid this from happening?

**Comment by stefanneculai** [comment]
If you can make a jsFiddle we can definitely check it.

**Comment by sabanaqvi** [comment]
I seem to have fixed the problem. Instead of using a style attribute on my span, I applied a class instead and that seems to keep the custom styling in a paragraph no matter what other styles i apply within it.
