### ISSUE TITLE
Table Edit options not showing under list

### ISSUE THREAD

**Issue by kishorethecoder** [froala/wysiwyg-editor#4249]
##### Expected behavior.
When you click on a Table cell, it should show the Edit option

##### Actual behavior.
When Table is added under the list, the edit option is not working

##### Steps to reproduce the problem.
Go to https://froala.com/wysiwyg-editor/

1. Add the table
2. click on the table cell, it showing edit options
3. Now add the list
4. insert table into the list
5. click on the table cell, it's not showing any options

##### Editor version.
latest

##### Recording.
https://www.awesomescreenshot.com/video/3946825

**Comment by AkshayCM** [comment]
Thanks for your feedback.
This issue is not reproducible or have been found to be fixed on the latest Froala release v4.0.8. Can you please upgrade and check?
