### ISSUE TITLE
NS_ERROR_FAILURE

### ISSUE THREAD

**Issue by imktks** [froala/wysiwyg-editor#426]
Hello, i am formating a block of text in froala and then im adding extra styling to it programmatically, by detecting its parentNode. Even though in Chrome, Opera, it works fine, in Firefox when i remove that formatting and try to apply one new, i am receiving
NS_ERROR_FAILURE:
...fyCenter",title:"Align Center",icon:"fa fa-align-center"},{cmd:"justifyRight",ti... 

Any possible solution ? Thank you

**Comment by stefanneculai** [comment]
Please make a jsFiddle.

**Comment by imktks** [comment]
I finally think that it is not editor's fail. Firefox is performing an abnormal action that results in causing that error. In case i find something related to Froala i will reopen the issue.
Sorry for the inconvenience.
