### ISSUE TITLE
enter: ENTER_BR broken?

### ISSUE THREAD

**Issue by qu0cster** [froala/wysiwyg-editor#4264]
I am trying to update from version 3.1.1 to 3.2.7.  FroalaEditor.ENTER_BR in Version 3.2.7 is not  behaving like it was.  It is still wrapping with &lt;p> when enter.

##### Expected behavior.
Test
&lt;br>

##### Actual behavior.
&lt;p>TEST&lt;/p>
&lt;p>&lt;br>&lt;/p>

##### Steps to reproduce the problem.
Initialize Froala v3.2.7 with "enter: FroalaEditor.ENTER_BR"
You can also see it in the demo: https://froala.com/wysiwyg-editor/examples/enter/ go down to EnterBR demo type press enter and inspect

##### Editor version.
v3.2.7

##### OS.
windows 10

##### Browser.
chrome

v3.1.1 behavior
![image](https://user-images.githubusercontent.com/5314630/121538018-7220cf00-c9d2-11eb-9426-fdcec9261b39.png)

v3.2.7 behavior
![image](https://user-images.githubusercontent.com/5314630/121538158-8d8bda00-c9d2-11eb-8b49-c40f4ac0d85a.png)

**Comment by jokel81** [comment]
Same for us, coming from 3.2.2 ...

**Comment by EnochChoi** [comment]
The same is true of 4.0.1.

**Comment by jtrain** [comment]
As a work around try setting the `enter` option to `null`. e.g.

<img width="1392" alt="image" src="https://user-images.githubusercontent.com/706148/122304805-2b3e5680-cf49-11eb-960f-3a1e1e82b0de.png">

This mimics the behaviour Froala used in previous versions.

**Comment by quoc-t-le** [comment]
> As a work around try setting the `enter` option to `null`. e.g.
> 
> <img alt="image" width="1392" src="https://user-images.githubusercontent.com/706148/122304805-2b3e5680-cf49-11eb-960f-3a1e1e82b0de.png">
> 
> This mimics the behaviour Froala used in previous versions.
> 
> (edit) this may introduce `<undefined>` tag surrounding your text and might not be a suitable option

yeah I found that out when I read their change log. Their change log mention Enter_BR not ENTER_BR. so I attempted to change the casing.  "Enter_BR" doesnt exists so it behave like setting it null (undefined) haha.  But yeah, I am waiting for a fix so I don't have to deal with the <undefined> tags that would come back and hunt me

**Comment by ernestwp** [comment]
looks like BR option is just flat out broken. When I hit enter in the example then it creates a new line. 
![image](https://user-images.githubusercontent.com/75757996/125340747-b243dc00-e307-11eb-8f5a-be43042812df.png)

**Comment by cfreear** [comment]
Its worth pointing out that the froala example page is also demonstrating this bug:

[https://froala.com/wysiwyg-editor/examples/enter/](https://froala.com/wysiwyg-editor/examples/enter/)

It would be great if we could get someone at froala to respond to this.

**Comment by DerekJDev** [comment]
Any update on this?

**Comment by simonwilsher** [comment]
Reverted to 3.6.2-1 (last working version) until this issue is fixed

**Comment by quoc-t-le** [comment]
> Reverted to 3.2.6-1 (last working version) until this issue is fixed

so close; I actually need 3.2.7 for the hidden fix on ol/ul coloring/formatting

**Comment by cfreear** [comment]
[4.0.4](https://github.com/froala/wysiwyg-editor/releases/tag/v4.0.4) has fixed this

**Comment by qu0cster** [comment]
4.0.4 did fixed the issue; https://froala.com/wysiwyg-editor/examples/enter/

**Comment by RiabininDmitriy** [comment]
the same issue
