### ISSUE TITLE
Table editing popup doesn't appear when selecting multiple cells

### ISSUE THREAD

**Issue by johnnyoshika** [froala/wysiwyg-editor#4282]
##### Expected behavior.

This table editing popup should appear when multiple cells are selected:
![image](https://user-images.githubusercontent.com/504505/124333467-284a8500-db49-11eb-9185-9121f6aeab72.png)

##### Actual behavior.

In a newly inserted table, editing popup doesn't appear when multiple cells are selected.

Fiddle: https://jsfiddle.net/johnny_examind/gp3txo8y/8/

##### Steps to reproduce the problem.

1) Insert a new table
2) Select multiple cells

##### Editor version.

4.0.1 and 4.0.2

##### OS.

Windows 10

##### Browser.

Chrome

##### Recording.

https://recordit.co/TWoo7DTeGK

**Comment by sava128** [comment]
@johnnyoshika Hi, we're having the same issue, did you find a way to work around this?

**Comment by johnnyoshika** [comment]
@sava128 no 🙁

**Comment by MeghashreeAP** [comment]
Thanks for your feedback.
This issue is not reproducible or have been found to be fixed on the latest Froala release v4.0.8.
Can you please upgrade and check?

**Comment by sava128** [comment]
> Thanks for your feedback. This issue is not reproducible or have been found to be fixed on the latest Froala release v4.0.8. Can you please upgrade and check?

Upgrading to [v4.0.5](https://github.com/froala/wysiwyg-editor/releases/tag/v4.0.5) seemed to solve the issue.

**Comment by johnnyoshika** [comment]
Confirmed that it works in v4.0.9
