### ISSUE TITLE
Image cant be upload to my server

### ISSUE THREAD

**Issue by weblounge** [froala/wysiwyg-editor#429]
Hello,

I want to upload image to my server instead of http://i.froala.com/ server. i am already use below code as per your docs and examples, but its cant be working. please let me know ASAP.

// Set the image upload parameter.
imageUploadParam: 'image_param',

// Set the image upload URL.
imageUploadURL: '/upload_image',

// Additional upload params.
imageUploadParams: {id: 'my_editor'}

**Comment by stefanneculai** [comment]
You're doing something wrong, that's why it doesn't work. **We use this repo for bug tracking, not for offering support. For support you should use http://editor.froala.com/contact.**
