### ISSUE TITLE
Editor options that toggles html tags (bold, italic, underline...) removes inline styles like font-size and font-family

### ISSUE THREAD

**Issue by AbanoubSameh** [froala/wysiwyg-editor#4298]
##### Expected behavior.
the selected text shouldn't lose the inline style and it should keep the font-size as it was before applying texting style like bold

##### Actual behavior.
the selected text loses the inline styles (including the font-size) and gets back to the default font-size.

##### Steps to reproduce the problem.
- In the editor, select a text and change font-size to 40px
- Make the selected text bold
- Remove bold.

It happens not only with bold but any option that uses format.toggle; like underline, italic etc...
I found that format.toggle when removing HTML Tag (like `<strong>`) it also removes the inline styles for the main element which resetting the font-size.
This only happens on V4.0.4 and working just fine on V4.0.3

##### Editor version.
V4.0.4

##### OS.
MacOS

##### Browser.
Google Chrome

##### Recording.

https://user-images.githubusercontent.com/38143846/130620026-fc15c470-882a-4243-8023-376124efe4b4.mov

**Comment by AbanoubSameh** [comment]
I've added a video from Froala's official website with the issue, any idea how to fix this or any suggestions??

**Comment by niewicz** [comment]
Any updates on this issue? Is it going to be fixed?

**Comment by AbanoubSameh** [comment]
Fixed in version 4.0.6
