### ISSUE TITLE
Custom Default Font Family

### ISSUE THREAD

**Issue by dh-fallen** [froala/wysiwyg-editor#430]
Hello,

Is there a way to define a default font family in the editor ? The font will be selected by default in the font family combobox on editor opening.

Thanks for your help
C. Laborde

**Comment by stefanneculai** [comment]
**First of all, please read the [README](https://github.com/froala/wysiwyg-editor#reporting-issues). We use this repo mainly for bug tracking and not for support.**

Regarding your question, you can add in your CSS a rule for `.froala-element` selector and set the font-family you want for it. If that font is also in the font family dropdown it will be selected when you use the dropdown.
