### ISSUE TITLE
Need examples on your site to describe how to include a non-youtube or vimeo video

### ISSUE THREAD

**Issue by schart01** [froala/wysiwyg-editor#431]
I have a user that wants to point to an MP4 video that is in a CDN and embed that video on their page using the Froala editor.  Obviously your insert video button doesn't accept a straight MP4 file for playing, it needs to be wrapped with embedded code.   It would be good for your site to give examples on how to do that for "normal" non-techie users.

**Comment by stefanneculai** [comment]
Here you go http://www.w3schools.com/html/html5_video.asp
