### ISSUE TITLE
Newline replaced with empty string, not a space

### ISSUE THREAD

**Issue by wojcikstefan** [froala/wysiwyg-editor#432]
See the fiddle: http://jsfiddle.net/u4z7d9fv/

A newline in HTML should create a space between "automatically" and "pay".

cc @philfreo

**Comment by stefanneculai** [comment]
Actually, that is not an issue. New lines are replaced with accordingly with `<br/>` only when they are inside a `<pre>` tag. If you put in HTML new lines they won't be replaced with new lines. In textareas new lines work, but the editor is not designed that way.

**Comment by wojcikstefan** [comment]
Hi @stefanneculai! I agree newlines should only be replaced by  `<br/>` if they're inside a `<pre>` tag. However, I still think there should be a space there. See http://jsfiddle.net/49bm6jxu/. It still displays "some text", not "sometext".

**Comment by philfreo** [comment]
I think http://jsfiddle.net/49bm6jxu/1/ is a better example of what @wojcikstefan is trying to say

**Comment by stefanneculai** [comment]
Thanks for clarifying this. :-)
