### ISSUE TITLE
Upload Video returns error 4 "Parsing response failed."

### ISSUE THREAD

**Issue by bpautsch** [froala/wysiwyg-editor#4334]
##### Expected behavior.
Video should load on web page after upload completes.

##### Actual behavior.
Receiving error code "4" with message "Parsing response failed.".

##### Steps to reproduce the problem.
This code was created several years ago and updated as we upgraded Froala versions. We have 1,000's of customers uploading images and videos daily. Videos are more rarely uploaded and customers typically reference YouTube/Vimeo URLs so we haven't seen his problem before, but we can easily replicate it (see video link below).

When the upload is submitted (not by URL or code), it uploads to a C# HTTPHandler (same handler is used for images and videos). Images work perfectly. The code saves the MP4 file and returns a valid JSON response (same response as images), but the editor says there's a parsing error. I tried rewriting the response code to return different content types or write JSON differently, but the result is always the same and always errors.

Please see the screenshot below where I write the responses/errors to the console on events "video.uploaded" and "video.error".

![video-upload-error-4](https://user-images.githubusercontent.com/2838210/134391577-7098526b-b0a4-4b23-8bf7-be3e36123328.png)

##### Editor version.
3.2.7

##### OS.
Windows

##### Browser.
Chrome (latest)

##### Recording.
https://www.loom.com/share/6931bd77f32d45f48589a2233a3d8054

**Comment by AkshayCM** [comment]
Thank you for your feedback. The request has been reported to the product management team for evaluation and consideration for an upcoming release.

**Comment by bpautsch** [comment]
This appears to be fixed.
