### ISSUE TITLE
Is there an option to specify the amazon cloudfront domain? 

### ISSUE THREAD

**Issue by lionellei** [froala/wysiwyg-editor#437]
I didn't see the option being available in the documentation, is it even supported?

**Comment by lionellei** [comment]
By the way, does it support other cloud besides S3?

**Comment by stefanneculai** [comment]
There is no option to set the amazon Cloudfront domain. However you should be able to use https://github.com/froala/wysiwyg-editor/issues/404#issuecomment-70906962 to upload to S3 directly from the editor and then change the URL in the callback. Only S3 is supported for the moment.

**Comment by stefanneculai** [comment]
I am closing this due to lack of response.

**Comment by p1Machado** [comment]
I now this issue is old, but I want to show how I did to upload a imagem and insert it with cloudfront.

Using the event .on('froalaEditor.image.beforeUpload', function (e, editor, images), I did the upload by myself and retrieved the object key. Then used editor.image.insert(cloudfront_object_url) to let Froala do his thing with the image. Last return false to stop the Froala standard upload flow.

**Comment by webexpert4rv** [comment]
+1

**Comment by siasjustin** [comment]
@p1Machado this is really cool and I am trying to do the same thing and looking all over the internet for this answer, but can you explain how you are setting up what is the filekey? Also, any way to know what your policy_attachment  and signature_attachment are?

**Comment by p1Machado** [comment]
My strategy for generating the filekey was a mix of the {user_id}/{object content's hash}. If I remember, guess it was a MD5 hash.

The policy and signature is required for AWS S3. Which is storing the objects.

**Comment by montegoulding** [comment]
> There is no option to set the amazon Cloudfront domain. However you should be able to use [#404 (comment)](https://github.com/froala/wysiwyg-editor/issues/404#issuecomment-70906962) to upload to S3 directly from the editor and then change the URL in the callback. Only S3 is supported for the moment.

@stefanneculai Is it possible to get some documentation about the callback you mention?
