### ISSUE TITLE
False triggering of tribute.js mention feature when we start with @userName.

### ISSUE THREAD

**Issue by sumancrest0001** [froala/wysiwyg-editor#4379]
##### Expected behavior.
I am using Froala text editor with tribute.js to implement the mentioning feature. It should not falsely trigger the tribute.js mention feature.

##### Actual behavior.
If I start writing in the editor with @mentionName then it will falsely trigger the tribute.js mentioning whenever I paste a link with ctrl+v and remove all the content written. If I remove @ from the mention (For example userName instead of @userName) then there will be no false trigger.

##### Steps to reproduce the problem.
[Link to jsfiddle](https://jsfiddle.net/suman0001/m92834tf/2/)
##### Editor version.
version 4.0.5
##### OS.
Linux, ubuntu 18.04 64bit

##### Browser.
chrome

##### Recording.
I used the demo example provided by [Froala editor](https://froala.com/wysiwyg-editor/examples/tribute-js/) and added '@'+ in the selectTemplate to ensure that @ symbol with mentioned name.
[(A recording showing how to reproduce the problem)](https://www.loom.com/share/020fdb571d334f2e876fdff209919dc1)

**Comment by ilyaskarim** [comment]
This seems to be an issue with the tribute template you are working with, Please replace the selectTemplate with: 
`'<span class="fr-deletable fr-tribute">' +item.original.key + '</a></span>';`
