### ISSUE TITLE
Font Size Issue ( Froala Editor to Outlook Compose Editor)

### ISSUE THREAD

**Issue by karuppasamydevsync** [froala/wysiwyg-editor#4401]
Issue happening in font size the text transferred from ( https://froala.com/online-html-editor/ ) to outlook  - compose

Video :- https://drive.google.com/file/d/1TkVUbHRyyzOJiP22p34Y1YtJbZaDoJl4/view

Thanks!

**Comment by ilyaskarim** [comment]
@karuppasamydevsync Please take a look at this option to configure this behaviour: https://froala.com/wysiwyg-editor/docs/options/#fontSizeUnit
