### ISSUE TITLE
Order list OR Unorder list style indents the text, but does not render a visible order or unordered list Icon

### ISSUE THREAD

**Issue by mhassanedev** [froala/wysiwyg-editor#4412]
##### Expected behavior.
Order list OR Unorder list style show with **respective Icon**.

##### Actual behavior.
Order list OR Unorder list style **does not** show respective Icon.

##### Steps to reproduce the problem.
1) Open Froala Editor and type some text e.g: "This is some text".
2) Place cursor after **is** then press enter.
3) Then select **some text** and apply order list or unordered list.

**Here is jsFiddle link:**
https://jsfiddle.net/mbwoqLyv/2/

##### Editor version.
4.0.9

##### OS.
Windows 10

##### Browser.
Chrome Version 89.0.4389.90 (Official Build) (64-bit)

##### Recording.
![Bullet Point issue --27472](https://user-images.githubusercontent.com/67260588/155115047-ab1177d4-19d1-4758-8643-ff0c3e3b9248.gif)

**Comment by ilyaskarim** [comment]
Hi There, This is not an issue with the Editor. You have some custom styles applied on the list item which prevents the editor styles from applying. Please see the screenshot below for the same: 
![image](https://user-images.githubusercontent.com/42450390/167676142-c00315db-0b5b-46db-9692-bcfae927a32d.png)
