### ISSUE TITLE
Copy paste emoticon does not copy the emoticon correctly when using emoticon as images

### ISSUE THREAD

**Issue by manoelneto** [froala/wysiwyg-editor#4415]
##### Expected behavior.
Copy the emotion correctly

##### Actual behavior.
the emoticon looks shrank after being paste

##### Steps to reproduce the problem.

* With blank editor
* Insert an emoticon
* copy and paste it

##### Editor version.
`"froala-editor": "4.0.6",` but its also happening in the emoticons documentation page

##### OS.
MacOs 12.0

##### Browser.
Chrome 98.0.4758.102

##### Recording.
https://www.loom.com/share/750d1d1555e24dd1918e66248af152c9

**Comment by soy-andrey-semyonov** [comment]
Looks like the class attribute is being stripped from the code you paste. 
The workaround is removing "class" from **pasteDeniedAttrs** option:

pasteDeniedAttrs: ['id']

https://froala.com/wysiwyg-editor/docs/options/#pasteDeniedAttrs

**Comment by manoelneto** [comment]
thanks

**Comment by iruvingu** [comment]
[soy-andrey-semyonov](https://github.com/soy-andrey-semyonov) thanks x2
