### ISSUE TITLE
Linking an individual image isn't working properly

### ISSUE THREAD

**Issue by philfreo** [froala/wysiwyg-editor#442]
Try to link the Twitter logo only to some URL. Then toggle to the HTML and you'll see the HTML is wrong.

http://jsfiddle.net/u4z7d9fv/

**Comment by stefanneculai** [comment]
I can't understand what exactly is wrong or how to replicate it. Could you please provide more details?

**Comment by philfreo** [comment]
Sorry - I included the wrong JS fiddle.

http://jsfiddle.net/dh9z26u4/

1. click twitter image
2. make it a link
3. look at the html -- the link tag is wrapped around all the images instead of just the one

**Comment by philfreo** [comment]
This definitely still a problem here. Try adding a separate link to for each of the social media icons. Then flip to the HTML and back and see if the HTML makes sense to you.

Also, I think the CSS/font paths are broken in the latest master?

**Comment by stefanneculai** [comment]
OK. It's an issue there for sure, the image order seems to be changed somehow.

We decided to remove the Font Awesome from the files because it can be included from CDNJS for example. We did the same with jQuery. It looks that we haven't removed the 2 CSS files.
