### ISSUE TITLE
Image box resize misaligned 

### ISSUE THREAD

**Issue by NordicLight** [froala/wysiwyg-editor#4426]
##### Expected behavior.
We are upgrading from version 2 to version 4 and in the new version the image resize frame is misaligned if fullPage equals true (please see picture). In version 2 this is working fine independent on the fullPage option.

 editor = new FroalaEditor('#froala-editor', {
        fullPage: true,
        iframeStyleFiles: ['https://cdn.jsdelivr.net/npm/froala-editor@4.0.9/css/froala_style.min.css']
    });

The blue resize box seems to be always misaligned with some 20px so is there an element we can add a simple css styling to fix this?

##### Actual behavior.
The blue resize box should wrap the image

##### Steps to reproduce the problem.
Unfortunately we cannot recreate this in JSFiddle. Our solution is running within a iFrame from Atlassian so it could be that this causes the problem.

##### Editor version.
4.09 

##### Browser.
Chrome latest

<img width="616" alt="Screenshot 2022-03-11 at 08 58 05" src="https://user-images.githubusercontent.com/9700899/157827370-45757997-0e00-4c41-a2fa-cfa6bc10a3ff.png">

**Comment by NordicLight** [comment]
After beeing in contact with support the fix is to add below css

 .fr-image-resizer {
    margin-top:40px;
 }

**Comment by NordicLight** [comment]
After beeing in contact with support the fix is to add below css

.fr-image-resizer {
margin-top:40px;
}

**Comment by offlead** [comment]
The margin-top of 40px is only working on wider viewports. If the viewport has been sized down narrower, the resizer shifts upwards more. It seems like the top value is miscalculated, or is being affected by something.

<img width="1894" alt="Screen Shot 2022-06-08 at 1 02 23 PM" src="https://user-images.githubusercontent.com/3578159/172697075-25de49ed-5794-4c9c-a61d-54670c29274a.png">

<img width="1867" alt="Screen Shot 2022-06-08 at 1 03 25 PM" src="https://user-images.githubusercontent.com/3578159/172697117-c31dbd92-2d03-470e-9b2c-0a8b7a1d9d84.png">
