### ISSUE TITLE
Block Style copied to new line...

### ISSUE THREAD

**Issue by JetSetWebDesign** [froala/wysiwyg-editor#444]
I have a block style called 'bordered' enabled for the h2 tag.  If I add that style to the h2 tag, it works as expected and adds the class of 'bordered'.  The problem is that when I press ENTER to start a new paragraph, the block style 'bordered' is copied down to the paragraph tag.  Like this...

```html
<h2 class="bordered">Some text.</h2>
<p class="bordered">Other text.</p>
```

Is there a way to disable this feature?  Or is it a bug?  I can go in and edit the HTML but this doesn't work for my clients who have no idea how to code.  Thanks!

**Comment by stefanneculai** [comment]
Actually this is the way it was implemented. You are right, the class shouldn't be copied. Last commit fixes it.
