### ISSUE TITLE
html.getSelected() returns undefined

### ISSUE THREAD

**Issue by michael-koch787** [froala/wysiwyg-editor#4444]
##### Expected behavior.
`html.getSelected()` returns selected string

##### Actual behavior.
`undefined` is returned

##### Steps to reproduce the problem.
See [jsFiddle](https://jsfiddle.net/3ko0fgeq/).
Set html content via 'set html'-button.
Check `html.getSelected()` return by clicking 'get selection'-button.

##### Editor version.
4.0.10

##### OS.
Windows 10

##### Browser.
Chrome 100.0.4896.127

**Comment by maximesahagian** [comment]
Hey @michael-koch787 

Did you find a solution? I get the same issue when I select more than 1 paragraph

**Comment by michael-koch787** [comment]
@maximesahagian 
Seems to be fixed as of version 4.0.15.
