### ISSUE TITLE
absolute url

### ISSUE THREAD

**Issue by alex-petrea** [froala/wysiwyg-editor#445]
Hi
I was wondering if there's any option that after image upload the image source will be `<img src="/uploads/image.jpg" />` rather than `<img src="http://example.com/uploads/image.jpg" />` ?
Or maybe there is and I can't find it because I have lots of content that it's added on localhost and when I upload it to production I'll have to manually change the links

Any suggestions?

Thank you

**Comment by stefanneculai** [comment]
The image SRC will be the one that you pass in the image upload request. If you return the URL without `http://example.com` the path will be as you want.

**Comment by cbielich** [comment]
Am I to understand passing the full http url here will produce the full path?

`$response = FroalaEditor_Image::upload('https://www.example.com/upload/123/');`

as apposed to this only producing the absolute path?

`$response = FroalaEditor_Image::upload('/upload/123/');`

**Comment by stefanneculai** [comment]
No, `FroalaEditor_Image::upload` is designed to return the absolute path. For returning the full url, please follow https://www.froala.com/wysiwyg-editor/docs/server/php/image-upload.
