### ISSUE TITLE
Allow only one visible inline instance

### ISSUE THREAD

**Issue by kristoftorfs** [froala/wysiwyg-editor#446]
Hello, I'm currently evaluating Froala editor for our custom CMS. I have to say, it is simply amazing! I have one small issue though (which may not be so mainstream, but is applicable to us).

We only allow our clients to edit small blocks of text on every page to keep the estethics of our websites as our designers intended. For this purpose I am currently testing with the inline mode of Froala.

When I set alwaysVisible to true there are times when there are two (or more) instances of the toolbar visible which may or may not overlap. Could it be possible to make it so that when one editor's toolbar is shown, all others get hidden?

Another option (perhaps even simpler) would be to implement show and hide events, this way we can do it manually.

**Comment by stefanneculai** [comment]
This is how the editor works by default. If you could provide a page where we test and the steps to replicate it, we can investigate.

**Comment by kristoftorfs** [comment]
When trying to create a quick demo page I noticed this issue only occurs when using an iframe. For regular usage once another instance gets shown, all others are hidden.

The demo is located at http://kristoftorfs.github.io/wysiwyg-editor. If you click on the title you'll get the toolbar for its editor. If you then click somewhere within the main contents you'll get the toolbar for that editor, but the other one stays visible.

**Comment by kristoftorfs** [comment]
Wonderful! Need to evaluate a few more things, but at this time there's a 99% chance we'll be licensing this.
