### ISSUE TITLE
Publish unminified source on bower/npm

### ISSUE THREAD

**Issue by dbackeus** [froala/wysiwyg-editor#447]
For paying users would be nice if we could get unminified sources via bower or npm.

I don't actually know how to accomplish this myself. But am hoping there might be similar solutions to rubys bundler where you can add a private gemserver as source or link a private github repo using a generated authentication key.

**Comment by stefanneculai** [comment]
There are few options for that. We might add that in the future.

However, I don't see a reason why you'd want to get the unminified sources via bower or npm instead of downloading directly from our website.

**Comment by dbackeus** [comment]
Since we're already managing all js via bower/npm it should be obvious that we don't want to make an exception to the rule as that would break the conventional development workflow (informing all developers how to sign in, download, unpack, check in sources in a vendor dir etc).

Reason we want to use unminified sources in general is because it helps debugging within the dev environment and can make it much more straight forward to understand and hook into Froala code when making extensions/plugins etc.

**Comment by stefanneculai** [comment]
I'll get back with a comment as soon as we'll create the packages.

**Comment by philfreo** [comment]
a +1 for a more automated way to get the source code. Would still prefer some git access since I frequently have to run non-released versions to get bug fixes and there's no easy way to do that now. Wish I could just `git pull`.

**Comment by stefanneculai** [comment]
Will do that shortly :-)

**Comment by dbackeus** [comment]
Thanks for following up!

We ended up using your wysiwyg-rails gem today. So we wouldn't mind if you'd make an unminified version of that as well.

**Comment by gonsfx** [comment]
I'm trying to get this integrated into an app that manages all of its dependencies with npm and browserify.

Trying to do so, i ran into several errors because with my browserify-shim config which are really hard to figure out because of the minified source from the npm module.

Is there a way to get the unminified source without a license to test that out?

**Comment by stefanneculai** [comment]
Unminified source codes are available only under Advanced and OEM licenses. No exception is made.

**Comment by gonsfx** [comment]
So if we buy a license and find out we can't integrate the editor with our workflow and toolset, there's no way to get a refund?

**Comment by stefanneculai** [comment]
The editor (minified code) can be downloaded at any time and tested before actually purchasing a license. The license fee is one time payment and it is non refundable.

**Comment by shaneparsons** [comment]
I see the unminified CSS is now available via NPM, however it'd be great if you could do the same with the JS.

With all my dependencies being managed by NPM, I really don't want to have to download the files seperately.

**Comment by jpgilchrist** [comment]
Has there been an update on this? We would like the same thing. I don't want to go out and download and copy/paste unminified code every update. I'd rather just bump my bower.json file's version numbers. Possibly an authenticated git repository with our paid account credentials?

**Comment by stefanneculai** [comment]
No, there is no update on this yet and it's very unlikely to have that implemented because it would result in additional costs for the license. The editor license is one time payment while there are monthly costs for that. For example, on Github with the new plans for a private repo on Froala organization there would be a cost of $9/month for each user. That is $108/year and for that price most of the users would prefer to download the unminified JS once per month from their account.

**Comment by jpgilchrist** [comment]
@stefanneculai  BitBucket has free git repository hosting.

**Comment by stefanneculai** [comment]
Hmm.. am I missing something? https://bitbucket.org/product/pricing

**Comment by benosman** [comment]
I too would love to have a private repo I could download from.

@stefanneculai - on bitbucket you would still need a paid account, but would work out a lot cheaper than github. e.g. they have 50 / 100 / unlimited user packs, which spread between the users would work out quite reasonable. Of course there would need some changes to your billing system.

One other option is GitLab.com which offers free private repos with unlimited collaborators:
https://about.gitlab.com/gitlab-com/

**Comment by stefanneculai** [comment]
@benosman thanks for letting us know about Bitbucket. Gitlab looks like a good alternative. 👍

**Comment by stavinopolis** [comment]
why not just upload the unminified from the site to your own private repo?

**Comment by JSteunou** [comment]
@stefanneculai gitlab is a really nice alternative. Using gitlab self hosted, it rocks.

**Comment by roddds** [comment]
Almost a year later, I would like to see this option made possible too, especially now that loaders like webpack are becoming more common.

**Comment by jpgilchrist** [comment]
Something else that you could do is to use your own private repository and have the unminified version available through a scoped npm module. For example Fontawesome5 does a really good job with this. Take a look at how they implement paid vs. free content. Your free version could be built off of this existing github repo, and a paid version could be built off a private version.

**Comment by stefanneculai** [comment]
@jpgilchrist thanks for the suggestion.
