### ISSUE TITLE
4.0.12 issue with the wordPaste plugin

### ISSUE THREAD

**Issue by martinovicd** [froala/wysiwyg-editor#4470]
##### Expected behavior.
Hi guys. There is an issue in the latest release with the wordPaste plugin

##### Steps to reproduce the problem.
1. Copy text from the docx file
2. Paste it here https://jsfiddle.net/qnxa4zkj/
4. Uncomment the option ie remove wordPaste plugin
5. Paste text again

You can also change the editor release in CDN's to see the difference

##### Editor version.
4.0.12

##### OS.
Windows 10

##### Browser.
All

##### Recording.
![image](https://user-images.githubusercontent.com/47521142/175936214-a654f24d-440d-4f02-9790-435f45330046.png)

**Comment by ilyaskarim** [comment]
The fix will be available in the next editor release V4.0.13. Thank you for your patience
