### ISSUE TITLE
Toolbar options disabled when select table column from keyboard keys And Unable to Copy and paste multiple cell as well

### ISSUE THREAD

**Issue by mhassanedev** [froala/wysiwyg-editor#4472]
##### Expected behavior.
Toolbar should be enabled when select multiple columns by pressing the shift key and Arrow keys

##### Actual behavior.
Toolbar is disabled by select multiple columns by pressing the shift key and Arrow keys.

##### Steps to reproduce the problem.
1). Initialize Froala editor.
2). Create a table from the table option in the toolbar.
3). Try to select the column by pressing the shift key and Arrow keys.

##### Scenario 2 Expected behavior.
Copied cells should be paste with data.

##### Actual behavior.
Unable to paste copied cells.

##### Steps to reproduce the problem.
1). Initialize Froala editor.
2). Create a table from the table option in the toolbar.
3). Try to select the column by pressing the shift key and Arrow keys.
4). Select multiple cell and copy it.
5). Paste the copied cell.

##### Editor version.
Froala editor version "4.0.12"

##### OS.
Windows 10

##### Browser.
Chrome Browser

##### Recording.
![18577-Scenario-2](https://user-images.githubusercontent.com/67260588/176255692-e860474b-359c-4411-9791-37525ec9e478.gif)

**Comment by ilyaskarim** [comment]
These features are already on our roadmap, and upvoting them will help our team get them sooner in the editor.
Make sure to upvote and leave any feedback you may have for these features:
https://wysiwyg-editor-roadmap.froala.com/boards/feature-requests/3568. 
https://wysiwyg-editor-roadmap.froala.com/boards/feature-requests/3567.
