### ISSUE TITLE
Cannot read property 'idx' of undefined

### ISSUE THREAD

**Issue by rtcoms** [froala/wysiwyg-editor#448]
We are using froala with a licence key.

Getting this error on one of our pages. We are getting this only on one single page and at many other places it is working fine .

stacktrace:
---------------------

TypeError: Cannot read property 'idx' of undefined
t.Editable.mergeNodes
t.Editable.cleanOutput
t.Editable.cleanify
e.setHTML
...
...
t.fn.editable
Froala.t.initialize

**Comment by stefanneculai** [comment]
Could you please send the HTML you're using?

**Comment by stefanneculai** [comment]
It looks that you're using an older version. I am saying that because `mergeNodes` method doesn't exists anymore. Could you please use master the version from this repo?

**Comment by rtcoms** [comment]
We are using froala_editor v1.2.5 . Is there any new version released after that ?

Can't really provide access to the page as this page is accessed only after user authentication .  

Also this page is for editing entities . And we are facing this issue only while a editing a particular entity, for all other entities , editor is working fine. So html is same , because there is only one field which  contains rich text .

**Comment by stefanneculai** [comment]
Yes, 1.2.6.

**Comment by rtcoms** [comment]
Found the issue. 

One of our content editor copied some content from Microsoft Word to froala editor.  Content copied from  word doc is causing some issue . If possible I will try to give that word doc .

**Comment by stefanneculai** [comment]
Yes, we'd need the document, Operating System and browser used.

**Also, please open a different issue for each bug and close this issue if the problem doesn't exist in the latest version.**
