### ISSUE TITLE
Table cell color not applied on whole cell

### ISSUE THREAD

**Issue by alirazaedev** [froala/wysiwyg-editor#4488]
##### Expected behavior.
(table cell color should apply on whole table cell)

##### Actual behavior.
(Table cell color not applied on whole cell)

##### Steps to reproduce the problem.
(
1)create a table
2) apply cell style individually on cell
observe cell border color not applied on whole cell
below is the fiddle link
https://jsfiddle.net/k98sq4cb/
)

##### Editor version.
4.0.12

##### OS.
(OS name and version here)

##### Browser.
(Browser name an version here)

##### Recording.
(A recording showing how to reproduce the problem 

https://user-images.githubusercontent.com/39520368/181029802-a725b76a-5107-4a0a-9860-61bf2537ac55.mp4

)

**Comment by ilyaskarim** [comment]
Please review the following working demo: https://jsfiddle.net/ilyasfroaal/kqe8xt3c/8/.

**Comment by alirazaedev** [comment]
Hi Ilyas thanks for reply 
we have also table custom styles that end user can set from which we also have a double table style and user also can set width of table border.
 Here is the css of both table style 
1) .fr-view table.fr-double-borders td,.fr-view table.fr-double-borders th { border-style: double; }
2) .fr-view table.fr-three-borders-width td, .fr-view table.fr-three-borders-width th { border-width: 3pt; }

2nd we have also table custom cell style, in custom cell styles we define only table cell border color , 

so we can not defined table style(double) with cell style any other solution

**Comment by ilyaskarim** [comment]
Fix suggested: https://jsfiddle.net/ilyasfroaal/xt35e1vq/10/.
