### ISSUE TITLE
Popup Placement Incorrect

### ISSUE THREAD

**Issue by thaoula** [froala/wysiwyg-editor#451]
Hi Guys,

I seem to be having an issue with popup placement. This occurs when the item is a the bottom of the page and when scrolling.

I have attached an example.

Expected
![expected](https://cloud.githubusercontent.com/assets/349133/6343670/d303cb2a-bc40-11e4-98c4-8338cac08c27.png)

Wrong 
![wrong](https://cloud.githubusercontent.com/assets/349133/6343663/bd864174-bc40-11e4-814a-c6a1f69a222c.png)

**Comment by stefanneculai** [comment]
I believe that you should use https://editor.froala.com/options#scrollableContainer
