### ISSUE TITLE
NextJS Gives Error

### ISSUE THREAD

**Issue by ragokan** [froala/wysiwyg-editor#4512]
##### Expected behavior.
I actually expected it to work without any error.

##### Actual behavior.
It gave two errors. 
- `Uncaught TypeError: Cannot read properties of undefined (reading 'on')`
- `Uncaught RangeError: Maximum call stack size exceeded
    at String.split (<anonymous>)
    at Object.u [as on] (froala_editor.min.js?35e6:7:30715)
    at c.value (index.js?84cb:1:7489)
    at editorInitialized.config.events.initialized (index.js?84cb:1:5490)`

##### Steps to reproduce the problem.
- I followed this setup: https://froala.com/wysiwyg-editor/docs/framework-plugins/react/
- I set up webpack config in next.config.js just like the doc above shows.
- When I start the app, I get the errors above.

![image](https://user-images.githubusercontent.com/63511519/188976534-499ceb53-3b64-483d-8b02-9bf8968d62d0.png)
Also the editor looks like this.

##### Editor version.
4.0.14

##### OS.
MacOS Monterey

##### Browser.
Chrome and Safari

**Comment by flex-kwoncheol** [comment]
Did you solve this problem?

**Comment by ragokan** [comment]
> Did you solve this problem?

With NextJS 13 and client only components, I think it is solved

**Comment by Stonehyung** [comment]
how!! i dint use nextjs 13 ,  i use next js 13
