### ISSUE TITLE
Links in pasted text are corrupted in Safari

### ISSUE THREAD

**Issue by em77** [froala/wysiwyg-editor#4515]
##### Expected behavior.
Copy/pasting text that includes links should behave the same in all browsers and should be preserved and formatted the same as from where it was copied.

##### Actual behavior.
The expected behavior does not occur in Safari. The links are corrupted.

##### Steps to reproduce the problem.
Simply make some text in an editor (like Google Docs) with a link included and copy/paste it into the demo editor on Chrome and Safari.

You can get it to work properly in Safari by including some plugins but excluding the `url` plugin. If you include no plugins, the problem still happens. The problem also happens if the only plugin included is the `linkStyles` one ([example](https://froala.com/wysiwyg-editor/examples/link-styles/)). I'm still trying to narrow down with what settings the problem occurs and when it doesn't but it seems very much related to the `url` plugin which is maybe being included in the background when using `linkStyles` which would explain it being broken using that as well? I would disable the `url` plugin in our app if it didn't provide such expected behavior from users (automatically turning raw urls into links to those same urls). This behavior is practically required at this point for an online text editor.

#### Chrome:
<img width="530" alt="Screen Shot 2022-09-13 at 10 08 10 AM" src="https://user-images.githubusercontent.com/7835870/189923592-55e2d2bb-a15d-4295-a6f2-72314d7991ba.png">

#### Safari:
<img width="442" alt="Screen Shot 2022-09-13 at 10 08 37 AM" src="https://user-images.githubusercontent.com/7835870/189923684-0ae16afc-4c58-4daa-9cef-570d86e5bcc9.png">

##### Editor version.
4.0.14

##### OS.
Mac 12.5.1

##### Browser.
Chrome 105.0.5195.102
Safari 15.6.1

##### Recording.
The steps above and screenshots should adequately describe the problem and how to reproduce it.

**Comment by essmahr** [comment]
We are also running into this. Much like @em77, dropping the link plugin is a no-go for us.

**Comment by essmahr** [comment]
I've confirmed that this bug was introduced with v4.0.13, I can't reproduce with v4.0.12: https://codesandbox.io/s/froala-core-sandbox-forked-qxtnc0?file=/index.html

**Comment by em77** [comment]
@essmahr Thanks for figuring that out. I requested the code for the past few versions from froala support and that helped me narrow down the problem which is a single typo on one line which I've opened a PR to fix in #4519. Not sure how long it'll take for this to get into a new release. If you're aware of an active admin on this repo, feel free to do a mention of them on the PR.

**Comment by em77** [comment]
@essmahr You are right, it doesn't seem to be referring to the option `pastePlain`. I've closed the PR and I'm not sure how much more I'll be able to personally dig into this issue. Hopefully it gets some attention from the froala devs.

**Comment by em77** [comment]
BTW if you write into froala support they will send you the unminified source code for any versions you want to look at.

**Comment by em77** [comment]
This issue is fixed in the [latest release](https://github.com/froala/wysiwyg-editor/releases/tag/v4.0.16).
