### ISSUE TITLE
Brightcove video embed code not working

### ISSUE THREAD

**Issue by meandkareem** [froala/wysiwyg-editor#455]
hi I used this embed code and after I added all custom allowed attribute and tags I still can see that class attribute is removed from object tag 

```html
<object id="myExperience4078586909001" class="BrightcoveExperience">
  <param name="bgcolor" value="#FFFFFF" />
  <param name="width" value="486" />
  <param name="height" value="412" />
  <param name="playerID" value="2929190247001" />
  <param name="playerKey" value="AQ~~,AAACoBBX_ek~,b0TExq8IExYqldDc8TwjmLrpCzaFEATo" />
  <param name="isVid" value="true" />
  <param name="dynamicStreaming" value="true" />
  <param name="@videoPlayer" value="4078586909001" />
</object>
```

I need class attribute because of brightcove js.

**Comment by stefanneculai** [comment]
Probably you have not added class in `videoAllowedAttrs`.
https://editor.froala.com/options#videoAllowedAttrs

**Comment by meandkareem** [comment]
Yes I did

**Comment by meandkareem** [comment]
videoAllowedAttrs: ['src', 'width', 'height', 'frameborder', 'allowfullscreen', 'webkitallowfullscreen', 'mozallowfullscreen', 'href', 'target', 'id', 'controls', 'value','name','bgcolor','playerID','playerKey','isVid','dynamicStreaming','@videoPlayer', 'class']

**Comment by stefanneculai** [comment]
With `videoAllowedAttrs: ['src', 'width', 'height', 'frameborder', 'allowfullscreen', 'webkitallowfullscreen', 'mozallowfullscreen', 'href', 'target', 'id', 'controls', 'value','name', 'class']` it works fine.

**Comment by meandkareem** [comment]
worked now .. my bad sorry about it.  tnx for such a awesome editor.
