### ISSUE TITLE
Possibility to manipulate after image/file upload

### ISSUE THREAD

**Issue by slaven-ii** [froala/wysiwyg-editor#456]
There is no possibility to change html of the uploaded image/file. Or to not insert it in editor.

Scenario:

I would like to upload picture/file using standard way, but after the image/file is uploaded i wan't to add it as "attachment" outside the editor itself (using possible event)

**Comment by dianaprajescu** [comment]
There's already an event for this. Please see: https://editor.froala.com/events#imageInserted

**Comment by slaven-ii** [comment]
Yes but that is after the image is inserted in the editor, i wan't to disable inserting the image in editor, and place it somewhere else

**Comment by dianaprajescu** [comment]
Yes, it is after the image was inserted. It works like  this because "Insert Image" is design to insert an image in the editor. We haven't thought about using "Insert Image" to insert an image somewhere else. We'll talk about it and let you know our conclusion.
