### ISSUE TITLE
Media Manager : Custom imagesLoadParams ?

### ISSUE THREAD

**Issue by FletcherPink** [froala/wysiwyg-editor#458]
Hello,
Thanks for your great tool. Complete and easy to use : perfect !

I created two custom buttons who call each the "showMediaManager" method. Now i need to specify different "imagesLoadParams" for each of this two buttons and listen each of them.

Is there a way to do this ?
Thanks a lot.

**Comment by stefanneculai** [comment]
You should set the `imagesLoadParams` before calling the `showMediaManager`. The images are reloaded each time you hit the button and this way you'd pass to the server the params that you want.
