### ISSUE TITLE
Disabling keyboard shortcuts not working

### ISSUE THREAD

**Issue by elikem** [froala/wysiwyg-editor#460]
```
...
.editable({
  inlineMode: false,
  buttons: [],
  shortcuts: false
)}
...
```

If I understand the documentation correctly. Setting option shortcuts to false should disable all keyboard shortcuts.

I am still able to do things like bold and italics from the keyboard. I'm on OS X 10.10 Chrome.

I want to completely disable formatting when the user inputs text.

**Comment by stefanneculai** [comment]
Actually, it is working as it should. Setting the option `shortcuts: false` is leaving the browser default behaviour. In Chrome, the default behaviour is to make them bold and italic. Firefox shows bookmarks when CTRL + B is used for instance.

If you want to disable browser default behaviour, then you should listen on the keydown event and do that.
