### ISSUE TITLE
Even with plainPaste:true, inline styles are pasted in

### ISSUE THREAD

**Issue by ryandury** [froala/wysiwyg-editor#463]
Any idea why plainPaste doesn't work? All other parameters seem to respond accordingly. When I remove plainPaste altogether, it pastes a header without font color. When I enable it, it pastes the header styled and with color.

**Comment by ryandury** [comment]
Any idea why plainPaste doesn't work? All other parameters seem to respond accordingly.  When I remove plainPaste altogether, it pastes a header without font color. When I enable it, it pastes the header styled and with color.

**Comment by stefanneculai** [comment]
If you'd provide the steps to replicate it, we can investigate it further.

**Comment by stefanneculai** [comment]
I'm closing this because we haven't got enough information.
