### ISSUE TITLE
Property in types missing: POPUP_TEMPLATES

### ISSUE THREAD

**Issue by gorenburg** [froala/wysiwyg-editor#4647]
If you follow this [guide](https://froala.com/wysiwyg-editor/docs/concepts/custom/popup/), FroalaEditor has `FroalaEditor.POPUP_TEMPLATES` object to assign plugin popup options, but it's missing from [types](https://github.com/froala/wysiwyg-editor/blob/master/index.d.ts) in the FroalaEditor v4.1 library

##### Expected behavior.
`FroalaEditor.POPUP_TEMPLATES['video.insert_popup'] = '[_INPUT_LAYER_]'`

##### Actual behavior.
`Property 'POPUP_TEMPLATES' does not exist` error

##### Steps to reproduce the problem.
```javascript
;(function (FroalaEditor) {
  FroalaEditor.POPUP_TEMPLATES['video.insert_popup'] = '[_INPUT_LAYER_]'
})(FroalaEditor)

```

##### Editor version.
4.1

**Comment by ilyaskarim** [comment]
Fix for this issue is being rolled out in V4.1.1: https://froala.com/wysiwyg-editor/changelog/#4.1.1
