### ISSUE TITLE
Link plugin fails if `iframe: true` and markdown plugin is not included

### ISSUE THREAD

**Issue by dcsaszar** [froala/wysiwyg-editor#4657]
##### Expected behavior.

* No console errors
* Can insert a link

##### Actual behavior.

* Console errors
* Can't insert a link

`Cannot read properties of undefined (reading 'isEnabled') at link.min.js`

##### Steps to reproduce the problem.

https://jsfiddle.net/403sjgtd/

* Require "froala_editor"
* Require "froala_editor/js/plugins/link.min" 
* Create the editor with the `iframe: true` option
* Click the text or type something
* Insert a link

##### Editor version.

4.1.0

##### OS.

MacOS 13.4.1 (c) (22F770820d)

##### Browser.

Chrome 115.0.5790.114 (x86_64)

##### Recording.

<img width="1239" alt="image" src="https://github.com/froala/wysiwyg-editor/assets/986170/391a8cdc-361d-4362-9f58-9a8df567a882">

**Comment by ArtyomMoiseev** [comment]
#4649  also has the same issue

**Comment by dcsaszar** [comment]
Oops, duplicate. Closing this one.

@ArtyomMoiseev thanks!
