### ISSUE TITLE
Got an SSL warning in production

### ISSUE THREAD

**Issue by michaelkoper** [froala/wysiwyg-editor#466]
Weird because I don't send anything to the froala servers but got an SSL warning in Chrome.

Warning in my console:

    Mixed Content: The page at 'https://my_url.com' was loaded over a secure connection, but contains a form which targets an insecure endpoint 'http://i.froala.com/upload'. This endpoint should be made available over a secure connection.

Something I can do here on my end?

Thanks!

**Comment by stefanneculai** [comment]
There are 4 options that upload to `i.froala.com` by default. You should make sure none of them is set `imageUploadURL`, `imagesLoadURL`, `pastedImagesUploadURL` and `fileUploadURL`.
