### ISSUE TITLE
SHIFT + Arrow Key Left doesn't expand selection

### ISSUE THREAD

**Issue by lepult** [froala/wysiwyg-editor#4669]
##### Expected behavior.
Pressing SHIFT + [Arrow Key] should expand your selection in the provided direction.

##### Actual behavior.
This only works properly when Pressing Arrow Key Right or Down + SHIFT. When pressing Arrow Key Left or Up + SHIFT, the cursor moves to the start of the selection and thus the selection is removed. It behaves as if only the Arrow Key is pressed.

##### Steps to reproduce the problem.

1. Place the cursor at some point in a text.
2. Select the letter to the left of the cursor by pressing SHIFT + Arrow Key Left.
3. Press SHIFT + Arrow Key Left again.

##### Editor version.
4.1.1 (it is reproducable on the [froala demo page](https://froala.com/wysiwyg-editor/demo/))

##### OS.
Windows 11

##### Browser.
Chrome, Edge, Firefox (I didn't test it on any other browsers)

**Comment by DerekJDev** [comment]
+1, I'm also having this issue.

**Comment by grogy** [comment]
We have the same problem with 4.1.0 version. Current version 4.1.1 in official page have the same issue.

Any progress from Froala team?

**Comment by OtikCzech** [comment]
+1 with 4.1.0

**Comment by lepult** [comment]
This issue appears to be resolved as of Froala Version 4.1.2
