### ISSUE TITLE
onBlur event does not fire if initOnClick=true and user first clicks into field

### ISSUE THREAD

**Issue by rjsmith** [froala/wysiwyg-editor#467]
If initOnClick=true, and a user initially clicks into a FE field, then tabs out of the field, the on-exit onBlur event does not fire.  However, if the user first tabs into the field, then tabs out, it works OK.

NB: Bug observed in v1.2.6

Look at [this MeteorPad](http://meteorpad.com/pad/Ye4PJgyDCgne3ySJi/FroalaEditor%20onBlur%20Bug) which illustrates the problem. Follow these instructions to reproduce  the problem:
1. Open a new browser window to: http://app-w4wksf6j.meteorpad.com/
2. Click on the first button
3. CLICK into field. Focus switches into the first FE field (with initOnClick=true).  onBlur is called.
4. Type something
5. Press Tab key to leave the field. 
6. onBlur is NOT triggered  **THIS IS THE BUG**
7. Refresh browser (to clear state of FE field)
8. Click on the first button
9. Click into first FE field.  Note that onBlur event does NOT trigger (inconsistent with tab case above, probably another bug)
10. Type some content
11. Press Tab key to exit the field.
12. onBlur is fired, and the entered text is printed in the messages list.

Then repeat steps 1 ...12 but using the 2nd FE field, which has initOnClick=false.  In all cases, the onBlur event fires as expected.

**Comment by stefanneculai** [comment]
I cannot replicate it. Please create a jsFiddle. The MeteoPad app works very slowly and it's hard to debug in it.

**Comment by rjsmith** [comment]
OK, please try this:

https://jsfiddle.net/rj_smith/pwgyr8b7/2/

**Comment by rjsmith** [comment]
Hi @stefanneculai , I would really appreciate if you could look at the jsFiddle and follow the steps to reproduce again.   The problem is reproduced by CLICKING into the field, doing an edit, then TABBING out of it.

https://jsfiddle.net/rj_smith/pwgyr8b7/2/

**Comment by stefanneculai** [comment]
What browser and OS are you using? I still can't replicate it.

**Comment by rjsmith** [comment]
I am using 0SX Yosemite v10.10.2.  I can replicate it using Chrome v41 and Safari 8.0.4.

I have just noticed that the problem does NOT occur if I use Firefox 36.0.4 on the same machine

**Comment by rjsmith** [comment]
Just created this screencast, hope it helps:

https://www.dropbox.com/s/sj5xcmkykuht3rg/FEBug467.mp4?dl=0

**Comment by stefanneculai** [comment]
I managed to replicate it. There will be a fix shortly. Thanks.
