### ISSUE TITLE
RTL text problem

### ISSUE THREAD

**Issue by Bahir** [froala/wysiwyg-editor#470]
If you enter a text using RTL kind languages for instance Hebrew:

a) the cursor stays at the right end of the line but the end is at left!
b) entered something in hebrew and having switch back to english and continue entering a text, english symbols appear to the begining of the line, not to the end of it
![screen shot 2015-03-10 at 14 44 04](https://cloud.githubusercontent.com/assets/1221047/6575069/eeeed35e-c733-11e4-9d70-c41cbd15d0e7.png)

![screen shot 2015-03-10 at 14 42 52](https://cloud.githubusercontent.com/assets/1221047/6575057/cfdfa358-c733-11e4-84db-70ea0cc7f4a0.png)

**Comment by stefanneculai** [comment]
There is no problem. By default the input has `ltr` direction and is expected to have the cursor at the end. If you want to type in `rtl` languages, then you should use the option [direction](https://editor.froala.com/options#direction) and set it to `rtl`.

There is already [an example](https://github.com/froala/wysiwyg-editor/blob/master/examples/direction_basic_mode.html#L52) for that. You can as well just include the [Hebrew language](https://github.com/froala/wysiwyg-editor/blob/master/js/langs/he.js) and it will work as you want. More details can also be found on [our article](https://editor.froala.com/languages) about languages.
