### ISSUE TITLE
Unlicensed Froala Editor

### ISSUE THREAD

**Issue by manojsethi** [froala/wysiwyg-editor#472]
I upgraded my froala editor from 1.1.6 to 1.2.6 and getting this error when I deployed on server. Please tell me solution to this. I am using froala editor for a non profit organization(BlackDogResearch).

Please suggest.

Thanks
Manoj

**Comment by stefanneculai** [comment]
You shall contact us via our website with more details.

**Comment by manojsethi** [comment]
I had already mailed the details through contact us form but didn't get any revert.
