### ISSUE TITLE
uniminified JS source code is missing

### ISSUE THREAD

**Issue by shime** [froala/wysiwyg-editor#473]
since you're including unminified and minified versions of CSS, it would be great if you could do the same thing with JS, instead of just including the minified version.

**Comment by stefanneculai** [comment]
Unminified JS is available only for Developer, Business and OEM licenses.

**Comment by shime** [comment]
how am I supposed to send patches upstream then? I'm experiencing a clash with your code when handling touchstart events...

**Comment by stefanneculai** [comment]
We don't accept pull requests for the code. If you find any issue you shall report it and we'll fix it at our end. We have this policy because accepting patches from other developers might introduce unexpected issues.
