### ISSUE TITLE
Issues with a paragraph inside a blockquote

### ISSUE THREAD

**Issue by yan-hoose** [froala/wysiwyg-editor#474]
First of all, thank you for the great editor. It is easy to use, works well and looks good!

However, I ran into an issue in regards to quoting a paragraph. I use the editor in a forum and when I want to quote other posts I run into an issue where I can't write a response because the quotes won't terminate after pressing enter. Here is a fiddle to demonstrate the issue: http://jsfiddle.net/5g4LLemL/2/

It basically boils down to when you are having a paragraph inside the blockquotes, you can't write a response to that quote because the quote won't terminate when I press enter. If there are no paragraphs inside the quotes, then pressing enter works as expected.

I tested with Firefox 36 and 38 and Chrome 41.

Is this expected or is it a bug? If I wanted the both examples in the fiddle to work the same (terminate quote after pressing enter) how would I go about doing it?

Thank you.

**Comment by stefanneculai** [comment]
We haven't thought of such cases. We'll fix it shortly.
