### ISSUE TITLE
Froala 4.2.1: `html.get()` returns an unexpected wrapper div

### ISSUE THREAD

**Issue by dcsaszar** [froala/wysiwyg-editor#4794]
Update: after reporting #4795 I realized the workaround is the same, so these two issues probably have the same underlying bug:

As a workaround, these options can be set:
```js
{
  fontFamilyDefaultSelection: "Font Family",
  fontSizeDefaultSelection: "Font Size",
}
```

##### Expected behavior.

```js
editor.html.set("<p>Foo</p>")
editor.html.get() === "<p>Foo</p>"
```

##### Actual behavior.

```js
editor.html.set("<p>Foo</p>")
editor.html.get() === "<div><p>Foo</p></div>"
```

##### Steps to reproduce the problem.

https://codepen.io/dcsaszar/pen/vYwpNJm
```html
<div id="froala"></div>
```
```js
import * as FroalaEditor from "froala-editor";

const element = document.getElementById("froala");
const editor = new FroalaEditor(element, {}, () => {
  editor.html.set("<p>Foo</p>")
  editor.html.get()
});
```

##### Editor version.

**4.2.1**

(it works as expected up to 4.2.0)

##### OS.

macOS 14.5 (23F79)

##### Browser.
Chrome  125.0.6422.142
##### Recording.

<img width="1511" alt="image" src="https://github.com/froala/wysiwyg-editor/assets/986170/89e5ba5f-175b-4d6a-a4dc-9474d1fc5943">

**Comment by AkshayAccolite** [comment]
This issue is fixed in PR - https://github.com/froala-labs/froala-editor-js-2/pull/5323
