### ISSUE TITLE
Image resizing not working Iphone ios8

### ISSUE THREAD

**Issue by monitorman62** [froala/wysiwyg-editor#480]
Trying to select image to resize in ios8 .
UI zooms in  and keyboard pops up unable to commence action.
![img_0314 3](https://cloud.githubusercontent.com/assets/11498337/6662441/bc25fda4-cc0f-11e4-98c1-f88f8e9ccc4d.png)

![img_0313](https://cloud.githubusercontent.com/assets/11498337/6662323/50016718-cc0e-11e4-92cf-6c44628d3dad.PNG)

**Comment by stefanneculai** [comment]
We cannot replicate it on http://editor.froala.com. Most probably you have few other things that interact with the editor and make it not to work properly.

**Comment by darkbluesun** [comment]
Stefan, I have been doing some testing today on http://editor.froala.com/ using the iPad that monitorman62 was using. Forget the UI zoom and keyboard popup (he was trying to pinch the image) - but it is VERY difficult with the iPad to grab the corners of the image so as to resize the image when using the inline editor. It seems to be a bit easier in the boxed editor at the top of the page - but still quick tricky.

**Comment by stefanneculai** [comment]
We'll try to increase the area of the handlers on smaller devices to make it easier to resize. The handlers are already bigger than on desktop so that they are easier to grab.
