### ISSUE TITLE
Froala 4.2.0: Double Pasting Issue with Multiple Froala Instances

### ISSUE THREAD

**Issue by za1x** [froala/wysiwyg-editor#4800]
**Description:**

I am experiencing an issue where pasting text into Froala editors results in the text being pasted twice. This occurs when there are at least two instances of the Froala editor on the same page. I have verified this behavior on my own implementation and also on Froala's own example pages.

![froala](https://github.com/froala/wysiwyg-editor/assets/73664375/7646f865-c609-4cc5-a3a5-27531addacd3)
![Screenshot_1](https://github.com/froala/wysiwyg-editor/assets/73664375/043b5d0e-ddf7-4c80-a9b5-a10954f965a1)

**Steps to Reproduce:**

Navigate to Froala's example page: **[Froala Editor Examples](https://froala.com/wysiwyg-editor/examples/inline-two-instances/)**
Ensure there are at least two instances of the Froala editor on the page.
Copy some text (e.g., from a Word document).
Paste the text into the first Froala editor instance - it pastes correctly.
Paste the same text into the second Froala editor instance - the text is pasted twice.

**Expected Behavior:**
The text should be pasted only once in all instances of the Froala editor.

**Actual Behavior:**
The text is pasted twice in the second (and subsequent) instances of the Froala editor.

**Additional Information:**

Froala Editor version: 4.2.0
Browser: Chrome 126.0.6478.127 
Operating System: Windows 10
Please let me know if you need any additional information or if there is a workaround for this issue.

Thank you!

**Comment by za1x** [comment]
This is a bug in the 'word_paste' plugin since Froala 4.2.0. Froala 4.1.4 does not have this issue.

**Comment by rpragesh** [comment]
I am also facing the same issue :(

Do we need to downgrade the version of Froala to 4.1.4 or is there any alternate solution for this?

**Comment by za1x** [comment]
@rpragesh You need to downgrade only word_paste plugin file to 4.1.4

**Comment by seastian** [comment]
Ran into the same issue, I fixed it by adding a unique id on the `docId` config, looks like it happens when two editors have the same config.

**Comment by TheAngryByrd** [comment]
> Ran into the same issue, I fixed it by adding a unique id on the docId config, looks like it happens when two editors have the same config.

This workaround works for me 👍

**Comment by YNDthn** [comment]
I am facing the same problem, but unfortunately the workaround with “docId” did not work. I also tried using the “paste.wordPaste” event directly, but that also failed. However, other “paste” events such as “paste.afterCleanup” work very well.
I urgently hope for a bugfix soon!

**Comment by FenPWysocki** [comment]
is this fixed in v 4.3.1 ?

**Comment by ilyaskarim** [comment]
FIxed in V4.3.1: https://froala.com/wysiwyg-editor/changelog/#4.3.1
