### ISSUE TITLE
Froala  4.2.1: Setting `fontSizeDefaultSelection` in the config results in multiple wrapper divs being added to content on subsequent edits

### ISSUE THREAD

**Issue by scottwilkin** [froala/wysiwyg-editor#4801]
##### Expected behavior.
When the editor is initialized on a text area containing content that has been previously formatted with the editor it should not add another wrapper div that sets the font-size inline on subsequent edits.

##### Actual behavior.
When editing content previously formatted with the editor multiple wrapping divs are being added to the content.

##### Steps to reproduce the problem.
With a configuration like seen in this fiddle: https://jsfiddle.net/t4csdhmn/2/ when editing the content subsequent occasions multiple wrapping font-size divs are being applied to the content see screen shot:

<img width="974" alt="Screenshot 2024-07-11 at 3 06 43 PM" src="https://github.com/froala/wysiwyg-editor/assets/3791609/a5e313be-1fcb-4232-b273-35fe3b22d02a">

##### Editor version.
4.2.1

##### OS.
macOS 13.6.2 (22G320)

##### Browser.
Version 126.0.6478.127 (Official Build) (arm64)

**Comment by scottwilkin** [comment]
If `fontSizeDefaultSelection` is disabled it doesn't try to add the wrapping div.

**Comment by hattapoglu** [comment]
Related to #4794 and #4795
