### ISSUE TITLE
ImageUpload with headers

### ISSUE THREAD

**Issue by kotmatpockuh** [froala/wysiwyg-editor#481]
https://editor.froala.com/server-integrations/php-image-upload

Hello. Could you please provide information:

how could i send authToken and some other headers in imageUpload code?

```
 $(function() {
    $('.selector').editable({
      // Set the image upload URL.
      imageUploadURL: '/upload_image.php',

      imageUploadParams: {id: "my_editor"}
    })
 });
```

params i see, but how to be with custom headers like authToken etc?

also it has issue here: https://github.com/froala/angular-froala/issues/13

please leave one where it is more suitable

**Comment by stefanneculai** [comment]
Please see https://github.com/froala/wysiwyg-editor/issues/287#issuecomment-63144315

**Comment by kotmatpockuh** [comment]
@stefanneculai 
great
but one last question: my response is like:

`{"Id":"5506bba46cc4bf0eb87e8785","Url":"http://****"}`

is it real to catch such response and display in media manager?

**Comment by stefanneculai** [comment]
We offer tech support only to users who have a license that includes support. If you have such a license please contact us via http://editor.froala.com/contact.
