### ISSUE TITLE
Special HTML entities are lost

### ISSUE THREAD

**Issue by frankrue** [froala/wysiwyg-editor#482]
Unless there is an option of which I am unaware (quite possible!), any special ampersand-style characters get lost in the editor. I've created a jsfiddle to show this, where the existing text includes `&ldquos;` and `&rdquos;` and an alert reveals the returned string from a `getHTML` call.

In the returned screen, the special characters are converted to their display equivalents. This wreaks havoc with a content management system I am building where such values are stored in a DB.

I can reproduce this in Chrome and Safari; I have no reason to believe it is browser-specific.

https://jsfiddle.net/eqsp2fww/3/

**Comment by stefanneculai** [comment]
See https://github.com/froala/wysiwyg-editor/issues/461.

**Comment by frankrue** [comment]
I was following that discussion, but it doesn't solve the problem. Ignore HTML tags inside of HTML for a moment, and simply use something as obvious as a decorative open and closing pair of double quotes (`&ldquos;` and `&rdquos;`) from my previous example.

Even if you put them into a froala editor based on a `<div></div>`, they are still returned incorrectly with the `getHTML` method.

"Well then just don't do that," isn't an option for a WYSIWYG editor in this example.

**Comment by philfreo** [comment]
I agree that something is wrong still. See a modified example http://jsfiddle.net/r4tLxL16/ which points to the latest master and shows how you'd expect it to work with a textarea

**Comment by philfreo** [comment]
Though @frankrue in your example the curly quotes _are_ still visible -- it's just that they are no longer HTML encoded, but it's not strictly necessary to html encode them. However if you try to use a `<` sign via `&lt;` there is a problem

**Comment by frankrue** [comment]
@philfreo Yes—my example is merely for ease, since 99% of designers building websites will choose a webfont and expect characters like a right single-quote (’) to be used in place of a straight tick (') in possessives within headlines and body copy. Using them as-is (no escaping) would require that every element in the pipeline be encoded exactly the same, which isn't always possible. For instance, on many webhosts, there is no option to choose encoding of a given table within MySQL. This is the case in my actual production environment. So when these characters are stored, then retrieved and then rendered in HTML, they are garbled and confused with other characters.

Obviously, your example shows a great deal more information and probably a better use-case for serious concern. That this issue and the other issue mentioned are closed is my objection. The statement by another user: "Seems like the easiest approach would be to avoid using a textarea and rely on getHTML for submitting data instead," is not really the solution, since it happens in a `<div></div>` as well.

If I'm not doing something correctly prior to initializing the editor that I could be doing differently, I'm also open to that. But most (uglier) competing WYSIWYG editors handle this without batting an eyelash.

I prefer to put my money in Froala, and have a gorgeous editor (hint, hint, @stefanneculai!).

**Comment by stefanneculai** [comment]
@philfreo As it is explained on https://github.com/froala/wysiwyg-editor/issues/461#issuecomment-82215158, simply browsers don't make any difference between `&lt;` and `<` in textareas. Maybe you still think that is an issue of the editor, but look at this example https://jsfiddle.net/op7ou7da/. It's impossible to tell which of the `< >` are text and which are from actual HTML code. Inside textareas, a `<` can come either from `<` or `&amp;`. That's why inside textareas, the text should be encoded like `&ampentity;`.

@frankrue My bad, I was not paying enough attention to the example. There will be an update for it shortly.

**Comment by philfreo** [comment]
Hmm ok I didn't realize it was valid HTML to have unescaped stuff like `<em>` directly inside a textarea. 

At a high level, would you agree that the following usage/workflow should always work without problem?

```
<textarea class="froala"><?php echo htmlspecialchars($html, ENT_QUOTES); ?></textarea>
```

where `$html` is the actual HTML that you'd expect to print on a webpage or in an html email? And besides exceptions for security reasons and allowedTags, etc., the editor should display all the content the same as if displayed on a webpage? And `getHTML()` should also return the same HTML that you started with?

**Comment by stefanneculai** [comment]
Yes, that is right. Right now other text characters than `>`, `<` and `&` are not escaped. We're working on a solution for that. Is there anything else that doesn't work as expected?

**Comment by philfreo** [comment]
Ok great. I realize now my jsfiddle example above doesn't make sense for the `<` character - I forgot an encoding.

**Comment by stefanneculai** [comment]
There is a new plugin for handling entities. We decided to implement this as a plugin because not everyone will want to have the entities encoded.

**Comment by frankrue** [comment]
@stefanneculai Awesome. Thanks!

**Comment by AlbertParale5** [comment]
### **`_****_`sad_sdsdssddsd_**er
