### ISSUE TITLE
Select image after imageAltset

### ISSUE THREAD

**Issue by FletcherPink** [froala/wysiwyg-editor#483]
I need to append some html in the p tag around image within the title just defined.
And… i can't…
I try to catch a selector in the editor instance object… but… i can't…
Then i thought "this tool is really well-think, there is necessarily a thing to do that".
So ? Is ther a way to do that ?
Thanks

**Comment by stefanneculai** [comment]
The event should have contained the `$img` object as well. Last commit fixes that and now the event is `editable.imageAltSet (e, editor, $img)`. Same applies for other image events such as imageFloatedLeft or imageFloatedRight.

**Comment by FletcherPink** [comment]
So fast ! ;-)
