### ISSUE TITLE
Copy/paste raw HTML broken

### ISSUE THREAD

**Issue by vahtel** [froala/wysiwyg-editor#484]
When you use a text editor like Sublime text or Textmate and try to copy/paste raw HTML it doesn't work. The editor inputs only empty lines. Example: try to paste the code:
```
<head>
<meta charset="UTF-8">
<meta name="description" content="Free Web tutorials">
<meta name="keywords" content="HTML,CSS,XML,JavaScript">
<meta name="author" content="Hege Refsnes">
</head>
```
to https://editor.froala.com .

It will work if you copy/paste it from a notepad or text editor that is in text mode. 

I suspect it has some thing to do with the paste buffers. The clipboardData can have text/plain and text/html buffers.
Maybe the editor should use only text/html when it comes from browser ?

Just as a reference, it somehow works here https://github.com/Voog/wysihtml

**Comment by stefanneculai** [comment]
I don't understand fully what you're asking. You're pasting the HTML in the text mode or in HTML mode?

**Comment by vahtel** [comment]
The HTML is copied in text mode, just as regular text. Open Sublime text, create new HTML file, add some HTML tags, try to paste the code (as text) to editor.

Another example, copying the raw text:
```
yyy<p>Text</p>zzz
```

Result in editor:
```
yyy

Text

zzz
```

Also tried setting plainPaste to true, didn't help.

**Comment by stefanneculai** [comment]
That's because you have the [paragraphy](https://editor.froala.com/options#paragraphy) option enabled. When this option is set to `true` empty lines are always wrapped in `P` tags. If you don't want this to happen, then you should disable it.

**Comment by vahtel** [comment]
No, it's something else. Here's a video to demo
![paste](https://cloud.githubusercontent.com/assets/396759/6739230/1818bb8e-ce80-11e4-81b9-bca7af9a8e7c.gif)

**Comment by stefanneculai** [comment]
Is this happening on the version from master? If yes, could you please send a link to the jsFiddle?

**Comment by vahtel** [comment]
Yes, latest from master.  https://jsfiddle.net/orqnzcs2/1/
As I mentioned it works when I copy it from Textedit, Mac (something like Notepad in Windows) or from email. I have tested with Sublime and Textmate code editors, those are broken. Also with Chrome and Safari browsers under Mac.

Working sample with Textedit:
![paste2](https://cloud.githubusercontent.com/assets/396759/6739525/c2bb9b3c-ce81-11e4-8173-cbe97f23905a.gif)



Something with paste buffers ?

It's been actually reported by some of our clients. Can't be just my machine.

**Comment by stefanneculai** [comment]
OK. I was able to replicate it. There will be a fix for it shortly. Thank you for all the details and the jsFiddle.

**Comment by hariskhan10** [comment]
there is no Paragraphy option, can u please explain which option you are talking about as I am facing the same issue, i dont want the <p> tag to be wrapped in empty text

**Comment by stefanneculai** [comment]
In V2, the `paragraphy` option was replaced by `enter`.

**Comment by hariskhan10** [comment]
dear @stefanneculai ,

thanks for the quick reply, but can you please tell me that if we dont want any tag to be wrapped with the simple text, what to do ... i mean can you please share the syntax. ?

**Comment by stefanneculai** [comment]
See https://www.froala.com/wysiwyg-editor/docs/examples/enter

**Comment by hariskhan10** [comment]
@stefanneculai  we cant have it empty ? i mean without any tag wrapping ?

**Comment by stefanneculai** [comment]
You should set it to `$.FroalaEditor.ENTER_BR`. That is explained in the link I gave you above.

**Comment by hariskhan10** [comment]
@stefanneculai  thank, i ll try it and get back to you if i face any problem.. thanks
