### ISSUE TITLE
Froala adds redundant <p> elements

### ISSUE THREAD

**Issue by Bahir** [froala/wysiwyg-editor#485]
To repeat:
0. Empty text
1. Enter to html editor
2. Write ```<p><ul><li>a</li></ul></p>```
3. Exit html editor
4. Enter html editor

What do we see insted of  ```<p><ul><li>a</li></ul></p>```?
```
<p><br>
</p>

<ul>
  <li>a</li>
</ul>

<p><br>
</p>
```

**Comment by stefanneculai** [comment]
The editor is designed not to allow `UL` inside `P`.
