### ISSUE TITLE
Error in latest master

### ISSUE THREAD

**Issue by philfreo** [froala/wysiwyg-editor#486]
still trying to upgrade to get several of the bug fixes

Just playing with the basics of editor in 2a1f96187cf6eee61ac30a6bcc5666881eeb0389 for 2 minutes leads to a javascript error :(

![screenshot 2015-03-20 12 05 24](https://cloud.githubusercontent.com/assets/97612/6758984/a34d0fc4-cef9-11e4-9c78-a13b88af7195.png)

I'm not exactly sure what's triggering it but I was just typing and using some of the basic options. If you can't figure it out let me know.

**Comment by stefanneculai** [comment]
The issue comes from a part of code that was not changed since the release of version 1.2.5. It seems to happen when you hit enter, but I can't replicate it in any way. Could you provide few more details about what you were doing?

**Comment by philfreo** [comment]
narrowed it down for you...

http://jsfiddle.net/obccw2d3/

paste this code in the html side
```
<ol>
  <li><strong>put your cursor at the end of this line and hit enter 5 times</strong></li>
</ol>
<strong></strong><br>
<strong></strong><br>
<strong><em></em></strong><br>
```

then follow its instructions

**Comment by stefanneculai** [comment]
Thank you for the steps to replicate it. That helped a lot.
