### ISSUE TITLE
Insert image popup doesnt hide. So it call 'hidePopups'.

### ISSUE THREAD

**Issue by medibasecojp** [froala/wysiwyg-editor#487]
I want to insert the image as base64.So I use the beforeImageUpload event.

example)
---------------------------------------------------------------------------------------------------------------
$(".selector").editable({
  // some settings
}).on('editable.beforeImageUpload', function (e, editor, images) {
  $(images[0]).each(function(){
    var file = $(this)[0];
    var fr = new FileReader;
    fr.onload = function(event) {
      var html    = '<img class="fr-fil fr-dib" src="'+event.target.result+'" width="300">';
      $(".selector").froala('insertHTML', html, true);
    };
    fr.readAsDataURL(file);
  })

  $(".selector").froala('hidePopups');
  return false;  // Dont send file to server
});
---------------------------------------------------------------------------------------------------------------

it return false, because it doesnt send file to server.
And then Insert image popuup doesnt hide. So it call 'hidePopups'.
Then it remains a part of popuup.

![remain](https://cloud.githubusercontent.com/assets/11019792/6763185/23f60fac-cfb5-11e4-89a8-89c386469608.png)

**Comment by stefanneculai** [comment]
There is no issue from the editor, but you're not using this right. We use this repo for bug tracking, not for offering support. Please read https://github.com/froala/wysiwyg-editor#reporting-issues
