### ISSUE TITLE
writeLink and no-follow

### ISSUE THREAD

**Issue by FletcherPink** [froala/wysiwyg-editor#489]
I found a pretty bug:

     $('.editor').editable("writeLink", 'http://www.example.com/link' , name, "class", true, false);

wil generate:

    <a class="class" href="http://www.example.com/link" rel="nofollow" target="_blank">My link</a>

and this:

     $('.editor').editable("writeLink", 'http://www.example.com/link' , name, "class", true, true);

will generate too:

    <a class="class" href="http://www.example.com/link" rel="nofollow" target="_blank">My link</a>

The no-follow rel still be there.
Thanks

**Comment by stefanneculai** [comment]
https://github.com/froala/wysiwyg-editor/commit/1198e835674410e9443548d88b285c4165cb380a removed the nofollow option from the `writeLink` method and now the parameters looks like this `(url, text, cls, blank, attrs)` where `attrs` is an object that contains the attribute name and it's value `{title: 'Amazing link', rel: 'nofollow'}`.

**Comment by FletcherPink** [comment]
;-) Niiiiice !
