### ISSUE TITLE
Custom button dropdown

### ISSUE THREAD

**Issue by kerryusry** [froala/wysiwyg-editor#49]
Allow a method of building a custom dropdown like font selector and a callback for what to do with the selection. Similar to Redactor add dropdown.

http://imperavi.com/redactor/examples/dropdown/

Example use case I am building an email template editor and want to select from a list  of mustache template keys that would get dropped into the editor, like {{ first_name }} {{ last_name }}.

**Comment by newmesiss** [comment]
Is this functional, is it already implemented, and in what part of the documentation?

**Comment by stefanneculai** [comment]
@newmesiss sure, https://www.froala.com/wysiwyg-editor/examples/custom-dropdown.
