### ISSUE TITLE
Failed to read the 'contentDocument' property from 'HTMLIFrameElement'

### ISSUE THREAD

**Issue by manojsethi** [froala/wysiwyg-editor#490]
Hello I recently upgraded froala editor version and getting error when I add a video to it.
" Failed to read the 'contentDocument' property from 'HTMLIFrameElement': Blocked a frame with origin "http://www.example.com" from accessing a frame with origin "http://www.youtube.com".  The frame requesting access has a protocol of "http", the frame being accessed has a protocol of "https". Protocols must match." 

I am using <iframe height="315" src="//youtube.com/embed/SXmVym6L8dw?list=PLAC325451207E3105" width="560"></iframe> as embedded html.

Please suggest.

**Comment by stefanneculai** [comment]
You're embedding code that is loaded over `http` and your page is `https`. The protocol should match in order not to give such error. It's not because of the editor.

**Comment by manojsethi** [comment]
It's working fine with older version of the editor. Then why this unexpected behavior after updation?

**Comment by stefanneculai** [comment]
We haven't made any changes recently to how the embedded html is inserted or update it in any way.

**Comment by manojsethi** [comment]
Okay Thanks for the quick update, I will look into the cause and update if any solution found.
