### ISSUE TITLE
Append image/link popup to scrollable container 

### ISSUE THREAD

**Issue by kotmatpockuh** [froala/wysiwyg-editor#492]
For example: in config i try to code, that all popup's are attached to `.froala-wrapper.f-basic`, but then i didn't see any popup, even if i try to change z-index etc...

so: i append such code in config:

    editorClass: "my-custom-class",
    scrollableContainer: '.my-custom-class'

and any popup is displayed (case when froala editor is in bootstrap modal with fixed editor height)

you could try it here https://editor.froala.com/ if you set editor height to fixable, and uploading very tall image: with image popup position is something wrong. Screenshot: http://prntscr.com/6krb77

Take a look at this. Thank you.

also JFYI: wysiwyg must sanitize { } values to... No symbols { and } stayed in code.

**Comment by stefanneculai** [comment]
Please provide few more details about *wysiwyg must sanitize { } values to... No symbols { and } stayed in code*.

**Comment by kotmatpockuh** [comment]
For example i go here: https://editor.froala.com/

and paste there in html mode this content: 

http://pastebin.com/RNvJdzbv

then i go on view mode, than back in html and see: there is such line of code:

` <a data-nav-handler="{"` if somebody is using angular (as in my case): it could cause sanitize error's when trying to display this code, so it would be better on copy-paste to remove such code from editor, as style attributes do. 

is it clear? or more details?

**Comment by stefanneculai** [comment]
Which is the original HTML that you put in there?
