### ISSUE TITLE
Pasting copy over existing copy creates bookmarking empty paragraphs

### ISSUE THREAD

**Issue by wleklinski** [froala/wysiwyg-editor#494]
*Steps to Reproduce*
1. Copy "Lorem ipsum dolor sit amet, consectetur adipiscing elit." to your clipboard.
2. Open an editor that has existing content (like [the homepage editor](http://editor.froala.com) for example)
3. Click into the editor and `select all`
4. Paste clipboard copy

*Expected Result*
Expected markup is `<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>`.

*Actual Result*
Markup contains paragraph tags on the top and bottom of the pasted content. Using the Froala homepage editor the resulting markup is:

    <p style="text-align: center;"><br>
    </p>
    
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
    
    <p><br>
    </p>

*Additional Information*
I experienced the above bug in Chrome Canary, Chrome, & Opera. Safari experienced a similar bug, though the bottom `p` was not present. Worked in FF. Did not test IE.

**Comment by stefanneculai** [comment]
Thanks for all the details. There will be a fix shortly.

**Comment by stefanneculai** [comment]
Fixed https://github.com/froala/wysiwyg-editor/commit/c2fbdd2815ffc1a8c7c88e70ddddfc155e2972e9.

**Comment by wleklinski** [comment]
Thanks @stefanneculai. Great work!
