### ISSUE TITLE
added the purchased key but unlicensed red label still there

### ISSUE THREAD

**Issue by bilal186** [froala/wysiwyg-editor#495]
<script>
  $.Editable.DEFAULTS.key = 'ACTIVATION_KEY';
</script>

I have added this code after editor JS files

**Comment by stefanneculai** [comment]
You shall contact us via our website: http://editor.froala.com/contact.

**Comment by stefanneculai** [comment]
It looks that the email you provided was incorrect. Please contact me directly on `stefan@froala.com`.
