### ISSUE TITLE
Sanitize { }

### ISSUE THREAD

**Issue by stefanneculai** [froala/wysiwyg-editor#496]
No symbols { and } stayed in code. More details on https://github.com/froala/wysiwyg-editor/issues/492#issuecomment-85998974.

**Comment by kotmatpockuh** [comment]
I put there original html from eurosport via copypaste, original code i post from here: 

http://www.eurosport.com/football/premier-league/2014-2015/paper-round-arsenal-ready-to-move-on-smalling_sto4652969/story.shtml

or code directrly what i get from froala: http://pastebin.com/RNvJdzbv

**Comment by stefanneculai** [comment]
We have investigated this and it looks like there was something processed badly on the initial paste. Could you please let us know what browser are you using and if you are using the plainPaste option?

**Comment by stefanneculai** [comment]
I am closing this issue due to lack of communication.
