### ISSUE TITLE
Inline editor goes out of focus when the the whole div is selected

### ISSUE THREAD

**Issue by Eshaswini** [froala/wysiwyg-editor#497]
When all the content of the div is selected using cmd+A or ctrl+A and if the div has a scroll, the inline Froala editor goes out of focus if the text is too long as it tries to append the editor at the end of text. If the user explicitly selects the whole text then this issue is not seen.

**Comment by stefanneculai** [comment]
Fixed b3b7c1e57e38323d281e0b1a579fddd3f813720f
