### ISSUE TITLE
Insert image full size, not 300px

### ISSUE THREAD

**Issue by adilsonb** [froala/wysiwyg-editor#498]
When I insert an image it is always displayed with 300px.

Is there any easy way to view the image in full size after inserting an image?

Because the only way I can do that is going on "Show HTML" and manually remove the width = "300" image of the line.

One option would be the image of the check box there is a "Full Size Image" button.

Another alternative would be an option to set it to Froala settings.

Congratulations for the excellent editor, I am using for local testing, but plan to buy the developer version.

**Comment by stefanneculai** [comment]
https://editor.froala.com/options#defaultImageWidth

**Comment by clodal** [comment]
Updated link: https://www.froala.com/wysiwyg-editor/docs/options#imageDefaultWidth

**Comment by aiddroid** [comment]
Is there any way to insert an image with full size? Or display from the server-side's response? an example:
```javascript
{link:"/some-upload-folder/myimage.jpg", width:400, height:300}
```

**Comment by aiddroid** [comment]
@adilsonb  You can use imageDefaultWidth in image.min.js like this
```javascript
new FroalaEditor('.selector', {
  imageDefaultWidth: 0
});
```
Sets the default width of the image when it is inserted in the rich text editor. Setting it to 0 will not set any width(Just with full size).
