### ISSUE TITLE
MathJax fails inside froala box

### ISSUE THREAD

**Issue by Bahir** [froala/wysiwyg-editor#499]
Any MathJax notation inside of froala editing box, 
for instance, \[\frac{a}b\] causes [MathJax Processing Error].

Outside froala, MathJax renders with no error.

**Comment by stefanneculai** [comment]
Please create a JSfiddle for it, otherwise we can't test it.

**Comment by Bahir** [comment]
https://jsfiddle.net/Marxy/hxxn9ftq/16/
