### ISSUE TITLE
Pasting Image from Clipboard goes to Froala Site

### ISSUE THREAD

**Issue by zielinskin** [froala/wysiwyg-editor#502]
The code used for the editor:   
       j$('#foo').editable({inlineMode: false, image_param: 'bar', imageUploadURL: '/foobar/...', imageUploadParams: {...}});

Works when uploading an image from the image button directly on editor, but when pasting image from clipboard, Froala site is used.

![image](https://cloud.githubusercontent.com/assets/11666160/6849123/371e982c-d39f-11e4-98c1-6598004180ad.png)

vs

![image](https://cloud.githubusercontent.com/assets/11666160/6849223/de127c98-d39f-11e4-9167-8a298ef6b184.png)

**Comment by stefanneculai** [comment]
Please read https://editor.froala.com/options#pastedImagesUploadURL.
