### ISSUE TITLE
Pasting images with imageUpload: false

### ISSUE THREAD

**Issue by philfreo** [froala/wysiwyg-editor#503]
I'm using these settings:

```
                defaultImageTitle: '',
                defaultImageWidth: 0,
                imageUpload: false,
                buttons: [
                    'bold', 'italic', 'insertOrderedList', 'insertUnorderedList', 'createLink', 'insertImage', 'html'
                ],
                imageButtons: ['linkImage', 'removeImage'],
```

When pasting an image it does this:

![screenshot 2015-03-26 10 38 43](https://cloud.githubusercontent.com/assets/97612/6852823/4f0b126c-d3a4-11e4-83ca-031d36327efc.png)

The UI kinda freezes like this for a while. If I save the page and come back and look at the HTML it has the base64 encoded version:

```
<img class="fr-dii fr-fin" src="data:image/png;base64,iVBORw0KGgoA.... (clipped) ....lFTkSuQmCC">
```

I'm actually fine with the base64 version (I _don't_ currently want it to use any uploadURL) but could you look into the UI issue of freezing and showing "Uploading image"?

**Comment by philfreo** [comment]
:+1:

**Comment by cybervanes** [comment]
Philfreo, can you please share your script on how you were able to save images in bas64?

**Comment by philfreo** [comment]
Froala did that automatically. But it was problematic in our case (since some email clients don't like receiving images this way). Overall you should probably use the Image Upload feature of Froala instead.

**Comment by cybervanes** [comment]
Alright cool thanks for the reply! I'm trying to figure a way to save the images to iOS. The search continues!
