### ISSUE TITLE
Buttons do not click, keyboards shortcuts are OK

### ISSUE THREAD

**Issue by luis888** [froala/wysiwyg-editor#505]
I am testing the use of frola editor for the first time, everything works OK including shortcuts, but not the toolbar buttons, they show they are clicked by blinking but do not stay in blue and does not trigger anything.
I am using jquery-2.1.3.js because of other dependencies, is froala tested with this latest version ?
I tried with <textarea and <div with same problem
I tried with the latest frola build to day 29/3/2105
thank you for your help
regards
luis

<script type="application/javascript" src="jquery-2.1.3/jquery-2.1.3.js"></script>
<script type="application/javascript" src="app_framework/2.1/jq.appframework.js" data-ver="1"></script>
         <script type="application/javascript" src="js/index_user_scripts.js"></script>
        <script type="application/javascript" src="libsup/spin.js"></script>
       <script type="application/javascript" src="appframework-2.2/plugins/af.css3animate.js"></script>
        <script type="application/javascript" src="appframework-2.2/plugins/af.scroller.js"></script>
             <script src="froala_editor_1.2.6/js/froala_editor.min.js"></script>

$(function() {
                    $("#"+i+ champsTablesShema[numTable][i]).editable({
                        inlineMode: false,
                    })
                });

**Comment by stefanneculai** [comment]
https://jsfiddle.net/gqg86mbe/ uses jQuery 2.1.0 and it works without problems. There shouldn't be any problems with version 2.1.3. I believe that you have some other JS that prevents the editor to work as it should.
