### ISSUE TITLE
Issue with maxWidth for editor box

### ISSUE THREAD

**Issue by giangvy1011** [froala/wysiwyg-editor#506]
Hi,

There is maxWidth option which we can set to px but can not set to %. I am using responsive col from bootstrap. When the screen resized, the editor box can not resize accordingly.

Im using desktop and and set col-md-8 and i left width option empty (which is auto) but the editor box is just half width of the column.

Is there anyway to overcome this?

**Comment by stefanneculai** [comment]
There is no maxWidth option.
