### ISSUE TITLE
insertHTML for pre seems to remove line breaks

### ISSUE THREAD

**Issue by MartinGentleman** [froala/wysiwyg-editor#507]
*Environment*
Ubuntu Firefox/Chrome
Froala 1.2.6.

*Context*
I am trying to implement custom button to support SyntaxHighlighter.
I am using this code to insert code:
$('#insert_btn').click(function () {
    var lang = $("#code_lang").val();
    var code = $("#code_area").val();
    code = code.replace(/\s+$/, ""); // rtrim
    code = $('<span/>').text(code).html(); // encode        
	
    var htmlCode = "<pre class='brush: " + lang.toLowerCase() + "'>" + code + "</pre></div>";
    var codeBlock = "<div align='left' dir='ltr'>" + htmlCode + "</div><br/>";
    $("#page-contents").editable("restoreSelection");
    $("#page-contents").editable("insertHTML", codeBlock);
    $("#page-contents").editable("saveUndoStep");
    codeModal.remove();
});

*Issue*
When the code is inserted it seems visually to be formated correctly but as soon as I switch to HTML code preview it removes linebreaking of the pre inserted code. The same when I try to save it immediately.
When I try to insert the code in html editing and switch back it keeps only the first line and all else is gone.
The only steps that seem to work are inserting pre and then writing the code line by line in visual editor.

**Comment by stefanneculai** [comment]
Is that happening with the master version? If so, could you please make a jsFiddle for it?

**Comment by MartinGentleman** [comment]
I am using public 1.2.6 version, which should be the latest

*jsfiddle:* https://jsfiddle.net/7b8a1L2k/1/

*Steps to reproduce:*
- click the dollar button
- insert multilined source code
- observe the code was inserted correctly and you can view it with line breaks
- click </> button for html view
- observe line breaks gone

the same is for saving the content, line breaks disapear
