### ISSUE TITLE
Set width of editor box

### ISSUE THREAD

**Issue by giangvy1011** [froala/wysiwyg-editor#508]
HI,

I don't set width of editor box (which is auto) because i would like it auto resize according to parent element.

The problem is this, while other input field are 100% width of parent, the froala editor box is just half width. Why is it? How can i fix this problem. Just to remind you that, i don't want to set width to a fixed pixel because it won't adapt with responsive purpose.

Please have a look of this picture
![froala-1](https://cloud.githubusercontent.com/assets/9975901/6902905/ff65f290-d740-11e4-8c36-c81a84c5f1d3.png)

**Comment by stefanneculai** [comment]
The editor box doesn't has any width set and it takes the width of the parent element. Probably you have a CSS rule that prevents that from happening. It's not an issue of the editor but something from your CSS for sure.
