### ISSUE TITLE
The raw saveParams option is being passed to jQuery instead of the results evaluated on the fly

### ISSUE THREAD

**Issue by fyneworks** [froala/wysiwyg-editor#509]
An image is worth a thousand words right?

![image](https://cloud.githubusercontent.com/assets/3658719/6921920/a451fd84-d7bf-11e4-9eab-e2b89a9a1463.png)

Is there a private repo where I can submit pull requests and help with the development?

**Comment by stefanneculai** [comment]
We don't accept direct PR, but I did the changes you spotted and fixed it in the last commit. Thank you!

**Comment by fyneworks** [comment]
Swift! Thanks :-)
