### ISSUE TITLE
Fullscreen Usability enhancement

### ISSUE THREAD

**Issue by benjaminfunk** [froala/wysiwyg-editor#511]
My usability test has determined the following problem.

If the user is in fullscreen mode they try to close the fullscreen by pressing the back button from the browser. All content is lost! Would be create if there are a confirm dialog before the fullscreen is leaved via browser back or some other actions except the fullscreen button. Full customizable of course ;)

**Comment by stefanneculai** [comment]
I don't see any reason for implementing in the editor a mechanism to check when the page is left. The action of leaving the page is not related to the editor, but to how the page itself works. If someone wants such a behaviour, he should implement it separate of the editor and check if there is any content unsaved and display a popup to the user.
