### ISSUE TITLE
Alert when image size is too large

### ISSUE THREAD

**Issue by lebart** [froala/wysiwyg-editor#512]
Hi, 

Is there a way to alert the user when he is trying to upload a too large image and when maxImageSize is set?

**Comment by stefanneculai** [comment]
See error code 5. https://editor.froala.com/concepts/image-upload

**Comment by lebart** [comment]
Thanks, 

I completely forget to check the 'concepts' section of the docs! 
Maybe it could be useful to link this in the options section near  'imageUpload' ?
