### ISSUE TITLE
Suggestion : About RTL and LTR

### ISSUE THREAD

**Issue by MajidCS** [froala/wysiwyg-editor#514]
Hi there ,
Can you make support RTL automatic , I mean when person change a keyboard to RTL , writing is direct change from right to left .
This makes it more flexible

Thank you,

**Comment by devmondo** [comment]
:+1:

**Comment by stefanneculai** [comment]
Last commit allows the text to have the direction auto. However, it is not possible to detect that and change the toolbar accordingly.
