### ISSUE TITLE
CopyPaste Text from ms doc: Cannot read property 'tagName' of undefined

### ISSUE THREAD

**Issue by kotmatpockuh** [froala/wysiwyg-editor#515]
Hello. I try to copy-paste to editor (in froala main demo page) text from doc file, but i get this error:

`Uncaught TypeError: Cannot read property 'tagName' of undefined` 

and full error trace (when i run it local):

```
Uncaught TypeError: Cannot read property 'tagName' of undefined lists.min.js:6 a.Editable.indentLifroala_editor.min.js:6 (anonymous function)jquery.js:512 jQuery.extend.proxy.proxyjquery.js:374 jQuery.extend.eachjquery.js:139 jQuery.fn.jQuery.eachfroala_editor.min.js:6 b.processPastefroala_editor.min.js:6 (anonymous function)jquery.js:512 jQuery.extend.proxy.proxyjquery.js:4430 jQuery.event.dispatchjquery.js:4116 jQuery.event.add.elemData.handle
```

file which i try to import:

`https://dl.dropboxusercontent.com/u/59666091/web_application_security_policy.docx`

and part of text which i try to import is such:

http://prntscr.com/6r2nwz

http://prntscr.com/6r2oit

**Comment by kotmatpockuh** [comment]
also i get `froala_editor.min.js:9 Uncaught TypeError: Cannot read property 'split' of undefined`

when copypaste this text: http://blog.hirerabbit.com/5-terrific-examples-of-company-social-media-policies/  and click on image to align it

**Comment by kotmatpockuh** [comment]
as very very fast hotfix there could be such modifications in code:

```
a.Editable.prototype.indentLi = function(b) {
      var c = b.parents("ul, ol");
      if (typeof c !== 'undefined' && c.length !== 0){
        d = c.get(0).tagName.toLowerCase();
      }
      else{
      	d = 'ul';
      }
```

but sometimes i will loose list style and order... just that i will not have exception, when app crashes

**Comment by stefanneculai** [comment]
Could you please try the master version and let me know if you experience the same issue? It seems to work fine to me with the master version.

**Comment by kotmatpockuh** [comment]
@stefanneculai  ok, will try
just that bower get 1.2.6 version... seems that i will need to import manually

**Comment by kotmatpockuh** [comment]
reproduced with 1.2.7 and lists plugin:

http://embed.plnkr.co/FQMXXVVRcBwyv5oLKWcT/preview

here is video how i done it:

https://dl.dropboxusercontent.com/u/59666091/CapturedMovie007_converted.avi

**Comment by stefanneculai** [comment]
Thank you for all the details. We'll fix it shortly.

**Comment by cpf70851** [comment]
hello. the same issue appear for me...

could you please fix it today asap?

**Comment by kotmatpockuh** [comment]
all is ok, except one strange behaviour...

my bower:

```
....
"overrides": {
    "angular-froala": {
      "main": [
        "src/angular-froala.js",
        "src/froala-sanitize.js"
      ],
      "dependencies": {
        "FroalaWysiwygEditor": "master",
        "angular": "~1.2.22"
      }
    },
    "FroalaWysiwygEditor": {
      "version": "master",
      "main": [
        "css/froala_editor.min.css",
        "css/froala_content.min.css",
        "css/froala_style.min.css",
        "css/font-awesome.min.css",
        "fonts/fontawesome-webfont.eot",
        "fonts/fontawesome-webfont.svg",
        "fonts/fontawesome-webfont.ttf",
        "fonts/fontawesome-webfont.woff",
        "js/froala_editor.min.js",
        "js/plugins/block_styles.min.js",
        "js/plugins/font_family.min.js",
        "js/plugins/font_size.min.js",
        "js/plugins/char_counter.min.js",
        "js/plugins/file_upload.min.js",
        "js/plugins/lists.min.js"
      ]
    }
  }
...
```

and i see that versin is still 1.2.6 but not master version...

maybe you could advice, what i do wrong?

**Comment by stefanneculai** [comment]
We update the bower version to the latest version from Github only when an official release is made. For the moment version 1.2.7 is under development.

**Comment by kotmatpockuh** [comment]
hm... but how use 1.2.6 with latest commit?
and when ~ will be release?

**Comment by stefanneculai** [comment]
http://stackoverflow.com/questions/20196707/can-i-add-a-git-repository-to-my-bower-json explains how to include with bower from Github.

We don't have a release date set yet for the new version.
