### ISSUE TITLE
Using Froala inside jquery mobile popup - url-fields inaccessible

### ISSUE THREAD

**Issue by mcskelle** [froala/wysiwyg-editor#518]
When using froala inside a jquery mobile popup (div with data-role="popup"), the url fields in "insert image" and "insert link" are inaccessible in chrome 41 and newest firefox. IE 11 works fine. 
When foala is used outside popup, it works fine in all three.

Ideas?

Inside popup-div: http://radnu.dk/editor1.html

Inside normal div: http://radnu.dk/editor2.html

**Comment by stefanneculai** [comment]
Probably that is because the popups appear outside of the `ui-page` element. Setting the option [scrollableContainer](https://editor.froala.com/options#scrollableContainer) to the `ui-page` might fix your issue.

**Comment by mcskelle** [comment]
Perfect!. The popup-div has to be set with scrollableContainer during initialization of Froala, like this:

scrollableContainer: "#YourSelector"

Thanks alot - keep up the good work :-)
