### ISSUE TITLE
Issue with single line breaks

### ISSUE THREAD

**Issue by rwaters71** [froala/wysiwyg-editor#520]
It is not trivial to use single ``<br>`` line breaks in Froala currently, bellow is an example.
Let's assume you have the following code, and you want to combine both paragraphs into one, and retain the original single-line ``<br>`` separation of all lines inside. 
```
<p>Line 1</p>
<p>Line 2<br>
Line3<br>
Line4<br>
Line5</p>
```
There is no easy way to retain the single line breaks in WYSIWYG mode. 
If you place the cursor at the end of "Line 1", and try to combine it with the second paragraph, you'd hit SHIFT+ENTER to add a ``<br>`` element, then DEL to delete the extra line below cursor, Froala will not only delete the beginning of the second paragraph, but it would also replace the ``<br>`` element at the end of Line 2 with ``</p>`` I believe it should retain all following ``<br>`` elements without editing the second paragraph until after Line 5, as was originally intended by the user.
Currently, you'd have to repeat the "move to end of line, hit SHIFT+ENTER, hit DEL" process at the end of each line to restore all the original single-line ``<br>`` breaks in the second paragraph.

Similarly, if you have the cursor at the beginning of line 2 in the above code and hit BACKSPACE to bring it up at the end of Line 1, Froala introduces a new ``<p>`` element after Line 2, replacing the original single line break. IMHO the original formatting by the user should remain.

**Comment by stefanneculai** [comment]
That is indeed an issue which will be fixed in the version 2.0.0.

**Comment by stefanneculai** [comment]
Should be fixed on master.
