### ISSUE TITLE
Changing font color/size/font causes error with Ember.js

### ISSUE THREAD

**Issue by Shak-eah** [froala/wysiwyg-editor#521]
Hello, 

My team is current using froala's editor 1.2.5 as a document editor. Whenever I select a piece of text - say "testing" and change it's color to any color, or try to change the font, or even change the font size, I get an error. For instance, when I tried to change the color of the word 'testing' to red, I got this:

get(this, 'length')) throw new EmberError(OUT_OF_RANGE_EXCEPTION); this.replace(idx, 0, [object]); return this; }; invoke: function (methodName) { var args, ret = Ember.A(); if (arguments.length>1) args = a_slice.call(arguments, 1); this.forEach(function(x, idx) { var method = x && x[methodName]; if ('function' === typeof method) { ret[idx] = args ? apply(x, method, args) : x[methodName](); } }, this); return ret; }; isAny: function (key, value) { return this.any(apply(this, iter, arguments)); }; isEvery: function (key, value) { return this.every(apply(this, iter, arguments)); }; mapBy: function (key) { return this.map(function(next) { return get(next, key); }); }; mapProperty: function (key) { return this.map(function(next) { return get(next, key); }); }; nextObject: function (idx) { return this.objectAt(idx); }; notifyPropertyChange: function (keyName) { this.propertyWillChange(keyName); this.propertyDidChange(keyName); return this; }; objectAt: function superWrapper() { var ret, sup = this && this.__nextSuper; if(this) { this.__nextSuper = superFunc; } ret = apply(this, func, arguments); if(this) { this.__nextSuper = sup; } return ret; }; objectsAt: function (indexes) { var self = this; return map(indexes, function(idx) { return self.objectAt(idx); }); }; observersForKey: function (keyName) { return observersFor(this, keyName); }; popObject: function () { var len = get(this, 'length'); if (len === 0) return null; var ret = this.objectAt(len-1); this.removeAt(len-1, 1); return ret; }; propertyDidChange: function (keyName) { propertyDidChange(this, keyName); return this; }; propertyWillChange: function (keyName) { propertyWillChange(this, keyName); return this; }; pushObject: function (obj) { this.insertAt(get(this, 'length'), obj); return obj; }; pushObjects: function (objects) { if (!(Enumerable.detect(objects) || isArray(objects))) { throw new TypeError("Must pass Ember.Enumerable to Ember.MutableArray#pushObjects"); } this.replace(get(this, 'length'), 0, objects); return this; }; reject: function (callback, target) { return this.filter(function() { return !(apply(target, callback, arguments)); }); }; rejectBy: function (key, value) { var exactValue = function(item) { return get(item, key) === value; }, hasValue = function(item) { return !!get(item, key); }, use = (arguments.length === 2 ? exactValue : hasValue); return this.reject(use); }; rejectProperty: function (key, value) { var exactValue = function(item) { return get(item, key) === value; }, hasValue = function(item) { return !!get(item, key); }, use = (arguments.length === 2 ? exactValue : hasValue); return this.reject(use); }; removeAmt = addAmt = -1; } else { if (removeAmt === undefined) removeAmt=-1; if (addAmt === undefined) addAmt=-1; } // Make sure the @each proxy is set up if anyone is observing @each if (isWatching(this, '@each')) { get(this, '@each'); } sendEvent(this, '@array: before', [this, startIdx, removeAmt, addAmt]); removeAmt = addAmt = -1; } else { if (removeAmt === undefined) removeAmt=-1; if (addAmt === undefined) addAmt=-1; } var adding, lim; if (startIdx>=0 && addAmt>=0 && get(this, 'hasEnumerableObservers')) { adding = []; lim = startIdx+addAmt; for(var idx=startIdx;idx= get(this, 'length'))) { throw new EmberError(OUT_OF_RANGE_EXCEPTION); } // fast case if (len === undefined) len = 1; this.replace(start, len, EMPTY); } return this; }; removeEnumerableObserver: function (target, opts) { var willChange = (opts && opts.willChange) || 'enumerableWillChange', didChange = (opts && opts.didChange) || 'enumerableDidChange'; var hasObservers = get(this, 'hasEnumerableObservers'); if (hasObservers) propertyWillChange(this, 'hasEnumerableObservers'); removeListener(this, '@enumerable:before', target, willChange); removeListener(this, '@enumerable:change', target, didChange); if (hasObservers) propertyDidChange(this, 'hasEnumerableObservers'); return this; }; removeObject: function (obj) { var loc = get(this, 'length') || 0; while(--loc >= 0) { var curObject = this.objectAt(loc); if (curObject === obj) this.removeAt(loc); } return this; }; removeObjects: function (objects) { beginPropertyChanges(this); for (var i = objects.length - 1; i >= 0; i--) { this.removeObject(objects[i]); } endPropertyChanges(this); return this;       }; removeObserver: function (key, target, method) { removeObserver(this, key, target, method); }; replace: function (idx, amt, objects) { if (this.isFrozen) throw FROZEN_ERROR; // if we replaced exactly the same number of items, then pass only the // replaced range. Otherwise, pass the full remaining array length // since everything has shifted var len = objects ? get(objects, 'length') : 0; this.arrayContentWillChange(idx, amt, len); if (len === 0) { this.splice(idx, amt); } else { replace(this, idx, amt, objects); } this.arrayContentDidChange(idx, amt, len); return this; }; return this; }; addObjects: function (objects) { beginPropertyChanges(this); return this; }; cacheFor: function (keyName) { return cacheFor(this, keyName); return this; }; enumerableContentDidChange: function (removing, adding) { var removeCnt, addCnt, hasDelta; return this; }; everyBy: function (key, value) { return this.every(apply(this, iter, arguments)); reverseObjects: function () { var len = get(this, 'length'); if (len === 0) return this; var objects = this.toArray().reverse(); this.replace(0, len, objects); return this; }; set: function (keyName, value) { set(this, keyName, value); return this; }; setEach: function (key, value) { return this.forEach(function(item) { set(item, key, value); }); }; setObjects: function (objects) { if (objects.length === 0) return this.clear(); var len = get(this, 'length'); this.replace(0, len, objects); return this; }; setProperties: function (hash) { return setProperties(this, hash); }; shiftObject: function () { if (get(this, 'length') === 0) return null; var ret = this.objectAt(0); this.removeAt(0); return ret; }; someProperty: function (key, value) { return this.any(apply(this, iter, arguments)); }; sortBy: function () { var sortKeys = arguments; return this.toArray().sort(function(a, b){ for(var i = 0; i < sortKeys.length; i++) { var key = sortKeys[i], propA = get(a, key), propB = get(b, key); // return 1 or -1 else continue to the next sortKey var compareValue = compare(propA, propB); if (compareValue) { return compareValue; } } return 0; }); }; toArray: function () { var ret = Ember.A(); this.forEach(function(o, idx) { ret[idx] = o; }); return ret; }; toggleProperty: function (keyName) { set(this, keyName, !get(this, keyName)); return get(this, keyName); }; uniq: function () { var ret = Ember.A(); this.forEach(function(k) { if (indexOf(ret, k)<0) ret.push(k); }); return ret; }; unknownProperty: function (key, value) { var ret;// = this.reducedProperty(key, value) ; if ((value !== undefined) && ret === undefined) { ret = this[key] = value; } return ret ; }; unshiftObject: function (obj) { this.insertAt(0, obj); return obj; }; unshiftObjects: function (objects) { this.replace(0, 0, objects); return this; }; var hasObservers = get(this, 'hasArrayObservers'); if (!hasObservers) propertyWillChange(this, 'hasArrayObservers'); addListener(this, '@array: before', target, willChange); var hasObservers = get(this, 'hasEnumerableObservers'); if (!hasObservers) propertyWillChange(this, 'hasEnumerableObservers'); addListener(this, '@enumerable: before', target, willChange); var length = get(this, 'length'), cachedFirst = cacheFor(this, 'firstObject'), cachedLast = cacheFor(this, 'lastObject'); if (this.objectAt(0) !== cachedFirst) { propertyWillChange(this, 'firstObject'); propertyDidChange(this, 'firstObject'); } if (this.objectAt(length-1) !== cachedLast) { propertyWillChange(this, 'lastObject'); propertyDidChange(this, 'lastObject'); } return this; }; arrayContentWillChange: function (startIdx, removeAmt, addAmt) { // if no args are passed assume everything changes if (startIdx===undefined) { startIdx = 0; var removing, lim; if (startIdx>=0 && removeAmt>=0 && get(this, 'hasEnumerableObservers')) { removing = []; lim = startIdx+removeAmt; for(var idx=startIdx;idx get(this, 'length')) throw new EmberError(OUT_OF_RANGE_EXCEPTION); this.replace(idx, 0, [object]); return this; }; invoke: function (methodName) { var args, ret = Ember.A(); if (arguments.length>1) args = a_slice.call(arguments, 1); this.forEach(function(x, idx) { var method = x && x[methodName]; if ('function' === typeof method) { ret[idx] = args ? apply(x, method, args) : x[methodName](); } }, this); return ret; }; isAny: function (key, value) { return this.any(apply(this, iter, arguments)); }; isEvery: function (key, value) { return this.every(apply(this, iter, arguments)); }; mapBy: function (key) { return this.map(function(next) { return get(next, key); }); }; mapProperty: function (key) { return this.map(function(next) { return get(next, key); }); }; nextObject: function (idx) { return this.objectAt(idx); }; notifyPropertyChange: function (keyName) { this.propertyWillChange(keyName); this.propertyDidChange(keyName); return this; }; objectAt: function superWrapper() { var ret, sup = this && this.__nextSuper; if(this) { this.__nextSuper = superFunc; } ret = apply(this, func, arguments); if(this) { this.__nextSuper = sup; } return ret; }; objectsAt: function (indexes) { var self = this; return map(indexes, function(idx) { return self.objectAt(idx); }); }; observersForKey: function (keyName) { return observersFor(this, keyName); }; popObject: function () { var len = get(this, 'length'); if (len === 0) return null; var ret = this.objectAt(len-1); this.removeAt(len-1, 1); return ret; }; propertyDidChange: function (keyName) { propertyDidChange(this, keyName); return this; }; propertyWillChange: function (keyName) { propertyWillChange(this, keyName); return this; }; pushObject: function (obj) { this.insertAt(get(this, 'length'), obj); return obj; }; pushObjects: function (objects) { if (!(Enumerable.detect(objects) || isArray(objects))) { throw new TypeError("Must pass Ember.Enumerable to Ember.MutableArray#pushObjects"); } this.replace(get(this, 'length'), 0, objects); return this; }; reject: function (callback, target) { return this.filter(function() { return !(apply(target, callback, arguments)); }); }; rejectBy: function (key, value) { var exactValue = function(item) { return get(item, key) === value; }, hasValue = function(item) { return !!get(item, key); }, use = (arguments.length === 2 ? exactValue : hasValue); return this.reject(use); }; rejectProperty: function (key, value) { var exactValue = function(item) { return get(item, key) === value; }, hasValue = function(item) { return !!get(item, key); }, use = (arguments.length === 2 ? exactValue : hasValue); return this.reject(use); }; removeArrayObserver: function (target, opts) { var willChange = (opts && opts.willChange) || 'arrayWillChange', didChange = (opts && opts.didChange) || 'arrayDidChange'; var hasObservers = get(this, 'hasArrayObservers'); if (hasObservers) propertyWillChange(this, 'hasArrayObservers'); removeListener(this, '@array:before', target, willChange); removeListener(this, '@array:change', target, didChange); if (hasObservers) propertyDidChange(this, 'hasArrayObservers'); return this; }; removeAt: function (start, len) { if ('number' === typeof start) { if ((start < 0) || (start >= get(this, 'length'))) { throw new EmberError(OUT_OF_RANGE_EXCEPTION); } // fast case if (len === undefined) len = 1; this.replace(start, len, EMPTY); } return this; }; removeEnumerableObserver: function (target, opts) { var willChange = (opts && opts.willChange) || 'enumerableWillChange', didChange = (opts && opts.didChange) || 'enumerableDidChange'; var hasObservers = get(this, 'hasEnumerableObservers'); if (hasObservers) propertyWillChange(this, 'hasEnumerableObservers'); removeListener(this, '@enumerable:before', target, willChange); removeListener(this, '@enumerable:change', target, didChange); if (hasObservers) propertyDidChange(this, 'hasEnumerableObservers'); return this; }; removeObject: function (obj) { var loc = get(this, 'length') || 0; while(--loc >= 0) { var curObject = this.objectAt(loc); if (curObject === obj) this.removeAt(loc); } return this; }; removeObjects: function (objects) { beginPropertyChanges(this); for (var i = objects.length - 1; i >= 0; i--) { this.removeObject(objects[i]); } endPropertyChanges(this); return this;       }; removeObserver: function (key, target, method) { removeObserver(this, key, target, method); }; replace: function (idx, amt, objects) { if (this.isFrozen) throw FROZEN_ERROR; // if we replaced exactly the same number of items, then pass only the // replaced range. Otherwise, pass the full remaining array length // since everything has shifted var len = objects ? get(objects, 'length') : 0; this.arrayContentWillChange(idx, amt, len); if (len === 0) { this.splice(idx, amt); } else { replace(this, idx, amt, objects); } this.arrayContentDidChange(idx, amt, len); return this; }; reverseObjects: function () { var len = get(this, 'length'); if (len === 0) return this; var objects = this.toArray().reverse(); this.replace(0, len, objects); return this; }; set: function (keyName, value) { set(this, keyName, value); return this; }; setEach: function (key, value) { return this.forEach(function(item) { set(item, key, value); }); }; setObjects: function (objects) { if (objects.length === 0) return this.clear(); var len = get(this, 'length'); this.replace(0, len, objects); return this; }; setProperties: function (hash) { return setProperties(this, hash); }; shiftObject: function () { if (get(this, 'length') === 0) return null; var ret = this.objectAt(0); this.removeAt(0); return ret; }; someProperty: function (key, value) { return this.any(apply(this, iter, arguments)); }; sortBy: function () {         var sortKeys = arguments; return this.toArray().sort(function(a, b){ for(var i = 0; i < sortKeys.length; i++) { var key = sortKeys[i], propA = get(a, key), propB = get(b, key); // return 1 or -1 else continue to the next sortKey var compareValue = compare(propA, propB); if (compareValue) { return compareValue; } } return 0; }); }; toArray: function () { var ret = Ember.A(); this.forEach(function(o, idx) { ret[idx] = o; }); return ret; }; toggleProperty: function (keyName) { set(this, keyName, !get(this, keyName)); return get(this, keyName); }; uniq: function () { var ret = Ember.A(); this.forEach(function(k) { if (indexOf(ret, k)<0) ret.push(k); }); return ret; }; unknownProperty: function (key, value) { var ret;// = this.reducedProperty(key, value) ; if ((value !== undefined) && ret === undefined) { ret = this[key] = value; } return ret ; }; unshiftObject: function (obj) {         this.insertAt(0, obj); return obj; }; unshiftObjects: function (objects) { this.replace(0, 0, objects); return this; }; without: function (value) { if (!this.contains(value)) return this; // nothing to do var ret = Ember.A(); this.forEach(function(k) { if (k !== value) ret[ret.length] = k; }) ; return ret ; };">testing

The funny thing is, though, this entire error block now has the correct formatting and replaces the word 'testing' inside the editor. For instance, in this, the entire block is red, just like we need it to be, like so:

![screen shot 2015-04-14 at 3 49 59 pm](https://cloud.githubusercontent.com/assets/4359715/7145954/f8745bc4-e2bd-11e4-8b39-1bb872b6ad3b.png)

My ember portion shows no errors; I wonder if:

1. froala is incompatible with Ember.js?
2. you know why this issue has come up?
3. there is any way to follow the sequence of actions from selecting a piece of text to applying the color in order to debug?

**Comment by stefanneculai** [comment]
The is no reason why it wouldn't be compatible with Ember.js. If you can reproduce the issue with the master version and create a jsFiddle for it we can definitely check it further.
