### ISSUE TITLE
TypeError: this.hideImageWrapper is not a function

### ISSUE THREAD

**Issue by alfakini** [froala/wysiwyg-editor#522]
I am using froala 1.2.6. Below you can find the source of the bug. When I use `b` instead of ` this` on line 2218 things work as expected.

![froala_editor_min_js](https://cloud.githubusercontent.com/assets/4171/7159848/8bd6a582-e35b-11e4-924d-5e966f7a8454.png)

In the unminified froala_editor.js, the error is on line 6772 `this.hideImageWrapper(true);` that probably should be `that.hideImageWrapper(true);`.

**Comment by digggggggggg** [comment]
I also had to submit a bug report with a screenshot. Wondering is there is a better way that paying devs can contribute to the project. A private repo / invitation only?

**Comment by stefanneculai** [comment]
@alfakini eace9bac7f6d787f208704780bd2bcd79c255264 already fixes it.

@digggggggggg for the moment the development process is not opened.

**Comment by alfakini** [comment]
Hey @stefanneculai when we will see this fix on cdnjs? Thanks

**Comment by stefanneculai** [comment]
As soon as the new release is made, in the first part of May.
