### ISSUE TITLE
Problem to display Lists 

### ISSUE THREAD

**Issue by MorphosysCL** [froala/wysiwyg-editor#525]
Hello:

I realize that there is a problem when you put the editor inside LI tabs, due to the tabs are list itself, when you try to open align, orderlist, unorderlist, etc. it doesn't apear.

The only way to solve the problem is to open a pop up to edit

**Comment by stefanneculai** [comment]
Are you using the master version?

**Comment by stefanneculai** [comment]
@MorphosysCL could you please let us know if you experience this with the master version? If yes, then could you also make a jsFiddle?
