### ISSUE TITLE
backColorsDisabled doesn't works ?

### ISSUE THREAD

**Issue by FletcherPink** [froala/wysiwyg-editor#526]
It seems that "backColorsDisabled" has no effect.

    backColorsDisabled: true,

Am I wrong ?

**Comment by stefanneculai** [comment]
In version 1.2.7, that option has been removed and the following option should be used instead:

```js
colorGroups: [
      {
        text: 'Text',
        cmd: 'foreColor'
      },
      {
        text: 'Background',
        cmd: 'backColor'
      }
    ],

**Comment by FletcherPink** [comment]
I love your speed of response and reactivity. Thanx !
