### ISSUE TITLE
Can't remove bold styling

### ISSUE THREAD

**Issue by digisquid** [froala/wysiwyg-editor#527]
I've just installed version 1.2.6 of Froala Editor (unlicensed while I'm testing in development environment) and it all seems to be working fine, but I've noticed a problem with toggling bold on and off. I can turn it on fine, but I can't turn it off again. The bold button doesn't highlight blue like the italic, underline and strikethrough buttons do, and the only way to turn it off is to manually remove the `<strong>` tags in the HTML editor.

I couldn't see it as an existing issue. Any ideas?

**Comment by stefanneculai** [comment]
Could you please make a jsFiddle for it?

**Comment by digisquid** [comment]
I made a jsFiddle and it was working fine, so started cutting chunks of code out to see what was causing it and narrowed it down to one of my stylesheets where I was using a different font-family for `strong` and `b` to avoid faux-bold.

Removing that style definition fixed the problem.
