### ISSUE TITLE
Replacing text with uploaded file name

### ISSUE THREAD

**Issue by AuHau** [froala/wysiwyg-editor#528]
Hey there,

I encountered small issue with uploading documents in your Editor.
When I select some text and then I upload some file, the selected text is replaced with the file name, which is not desired. What I would expect is that the selected text will become a link to the uploaded file. 

Currently there is small workaround, where you upload the file and then rewrite the file name to desired text, but this is not really user-friendly...

Do you think it will be possible to fix this in future?

**Comment by stefanneculai** [comment]
There might be persons who would prefer to have the name inserted. We'll add an option for setting this.

**Comment by AuHau** [comment]
True, sounds good!
