### ISSUE TITLE
imageResize

### ISSUE THREAD

**Issue by FletcherPink** [froala/wysiwyg-editor#529]
Hello,
Is ther a way to control image after imageResizeEnd ?
Something like this : 

    $('.selector').on('editable.imageResizeEnd', function (e, editor, img) {
    if(img.width() < 300){ ...
    });
Thank You

**Comment by michaelkoper** [comment]
+1

This is the same issue I am having at the moment. I would like to add attributes to the image url after insert.

**Comment by FletcherPink** [comment]
For this, use:

    .on('editable.imageInserted', function (e, editor, img) {

        img.css('border','2px solid red');

    })

;-)

**Comment by michaelkoper** [comment]
Thanks @FletcherPink but that isn't what I need. I use cloudinary for my images and they have a service that auto scales the images when the width and height is in the url. So the images would never scale down.

**Comment by FletcherPink** [comment]
Can't you change src ?

    img.attr('src','newSrc');

**Comment by michaelkoper** [comment]
Yes I can, but I would like to do that after resizing. As I don't have any problems with the initial width.

**Comment by FletcherPink** [comment]
Ok. I'm a bit long to understand. So we have the same issue. ;-) Welcome to the club. 

I already try something like

    $('.selector').on('editable.imageResizeEnd', function (e, editor, img) {
        $('.froala-class img').each(function(){
            if(img.width() < 300){ ...
        });
    });

But without effect… Perhaps i made something wrong. However i prefer a native function…
So i wait for the answer.

**Comment by stefanneculai** [comment]
The `imageResizeEnd` doesn't pass the `img` as parameter. We'll update the event to pass the `img` as well.

**Comment by michaelkoper** [comment]
Nice one Stefan :+1:

**Comment by stefanneculai** [comment]
See https://github.com/froala/wysiwyg-editor/blob/master/examples/events/imageResize.html for an example.
