### ISSUE TITLE
Initialize callback on editor

### ISSUE THREAD

**Issue by jonchay** [froala/wysiwyg-editor#53]
There are a lot of callbacks for events, is there one for when the editor has finished initializing and returns the editor instance?

**Comment by evpozdniakov** [comment]
Two things.

1. I noticed, data parameter was renamed. Now you can get editor instance by ```$('.selector').data('froala.editor')```
2. Reconfiguring editor is a common task. It would be better to add an API method for that. Or at least a method to get editor instance, in order to prevent further renaming (see above).

**Comment by stefanneculai** [comment]
@evpozdniakov indeed, that is a good suggestion.
