### ISSUE TITLE
Froala editor does auto removing all image styles and adding css class "fr-fir"

### ISSUE THREAD

**Issue by emredagli** [froala/wysiwyg-editor#531]
Hello,
I have a content like that:

&lt;img alt=&quot;&quot; height=&quot;190&quot; src=&quot;https://....png&quot; style=&quot;float: right; margin-right: 10px;&quot; width=&quot;148&quot;&gt; Some Other contents

After floala editor open I lost style of that image and I have new class "fr-fir" 
I want to get same image html on getting "$(...).editable('getHTML')"
Is it possible?

Thanks a lot.

NOT: I don't use toolbar so I do not need any image related feature. And I am using following config:

            inlineMode: false,
            buttons: ['html'],
            paragraphy: false,
            theme: 'gray',
            minHeight: 120,
            allowStyle: true,
            allowScript: true,
            beautifyCode: false,
            formatTags: [],
            linkText: true,
            noFollow: false,
            plainPaste: true,
            useClasses: false,
            imageTitle: false,
            blockStyles: {
                'img': {}
            }

**Comment by stefanneculai** [comment]
Could you please try the master version? It should work fine on the master version.

**Comment by stefanneculai** [comment]
I am closing this issue due to lack of response.
