### ISSUE TITLE
imageUploadURL server response data

### ISSUE THREAD

**Issue by sunstorymvp** [froala/wysiwyg-editor#532]
Hi!
Can i change how to parse response from the server which handles file uploads?

e.g. parse image link from this response:
```javascript
{
  "files": [{
    "name": ...,
    "size": ...,
    "type": ...,
    "error": ...,
    "path": ...,
    "url": ...
  }]
}
```
Problem is that i can't change the response.

**Comment by stefanneculai** [comment]
It is not possible at this point. We're currently developing the version 2.0 that will have a special option for that.

**Comment by superevanzhu** [comment]
froala 's version is 2.5.0 now,but i can't find the option for that.@stefanneculai

**Comment by kotmatpockuh** [comment]
@stefanneculai  any news?

**Comment by stefanneculai** [comment]
[image.uploaded](https://www.froala.com/wysiwyg-editor/docs/events#image.uploaded) event can be used in V2 for parsing a custom response from the server and insert that image.

**Comment by kotmatpockuh** [comment]
But first of all is fired error callback - it's not necessary in many cases with custom response...

**Comment by stefanneculai** [comment]
You could either pass `"link": ""` so that the error is not triggered, or use the same param from `image.error` event. It is not documented, but the response is there as well.

**Comment by kotmatpockuh** [comment]
@stefanneculai 
You could either pass "link": ""
sorry, where should i pass it?

**Comment by stefanneculai** [comment]
In the server response. We use this repo for bug tracking only. We offer tech support under the Advanced and OEM license via email. Please contact us there for extending the editor.
