### ISSUE TITLE
Skype plugin adds nasty code in phone numbers

### ISSUE THREAD

**Issue by michaelkoper** [froala/wysiwyg-editor#534]
Hi,

First of all, I totally understand if this issue get closed right away. I had 2 customers complaining about this so far, and the thing is that the Windows Skype plugin sucks. It adds nasty code in **editable** divs where it shouldn't be added. Would be awesome if this can get solved with the editor. But again, totally understand when this get ignored :-)

Here is an example about the horror:

https://www.dropbox.com/s/mdj3okgdf381d3v/Schermafbeelding%202015-04-24%20om%2019.50.26.png?dl=0

**Comment by digggggggggg** [comment]
Shouldn't this be down to developers to solve in their own implementation? Surely the editor can't be responsible for working around every browser add on that makes changes to the markup. What about adblockrs that remove social network markup for example?

**Comment by stefanneculai** [comment]
You could filter that using the `getHTML` event https://github.com/froala/wysiwyg-editor/blob/master/examples/events/getHTML.html.
