### ISSUE TITLE
Problem to display Lists element to one line

### ISSUE THREAD

**Issue by Arkadiy-Sedelnikov** [froala/wysiwyg-editor#535]
On the LI tag Instead of spaces are nbsp
![froala com_wysiwyg-editor](https://cloud.githubusercontent.com/assets/1139656/7344934/d7280746-ece9-11e4-8bc3-0d333ce94857.png)

**Comment by stefanneculai** [comment]
This was fixed on the master version.

**Comment by Arkadiy-Sedelnikov** [comment]
https://github.com/froala/wysiwyg-editor/issues/535
