### ISSUE TITLE
Problem with line breaks jump

### ISSUE THREAD

**Issue by Bahir** [froala/wysiwyg-editor#536]
Replay:

a. Enter HTML mode.
b. Write
```
1. <img src=""><br>
2. <img src=""><br>
3. <img src=""><br>
```
c. Enter editor mode.
d. Back enter HTML mode.

Contents magickally changed to
```
1. <br>
<img class="fr-dii fr-fin" src="">2. <br>
<img class="fr-dii fr-fin" src="">3. <br>
<img class="fr-dii fr-fin" src="">
```

This means ```<br>``` jumped from end of line to the begining...

**Comment by stefanneculai** [comment]
I cannot reproduce it on the master version. Have you tried the master version?

**Comment by Bahir** [comment]
On the master it is not. How can I can receive new developer version 'cause I have the license payed.
But at the customers area is still 1.2.6.

**Comment by stefanneculai** [comment]
The version 1.2.7 will be available on Bower and other plugins only when the it gets officially released. The only way would be to download it from here and include it manually.
