### ISSUE TITLE
not the correct code in the list <li></li>

### ISSUE THREAD

**Issue by joomline** [froala/wysiwyg-editor#538]
Is replaced with a space on `&nbsp;` when writing text in lists `<li></li>`.

Example
http://prntscr.com/6z3lwo

Html code editor
http://prntscr.com/6z3m4h

Why is it bad?
The browser may break html. Due to the fact that the browser interprets this line as one long word.

example of such code
http://prntscr.com/6z3obd

**Comment by stefanneculai** [comment]
It is fixed on the master version from https://github.com/froala/wysiwyg-editor

**Comment by Arkadiy-Sedelnikov** [comment]
How stable master branch? If we can apply the script to the repository in the plugin or it can lead to additional errors?

**Comment by stefanneculai** [comment]
We have automated tests that are always ran before updating the repo. There are users who use the version from there.

**Comment by Arkadiy-Sedelnikov** [comment]
Well, then take the scripts from the repository.  You can close this issue.
