### ISSUE TITLE
Inline image

### ISSUE THREAD

**Issue by joomline** [froala/wysiwyg-editor#539]
This is not a bug, it's a question about image editing.
If you edit the image have the ability to do inline image.

http://prntscr.com/6z3t7d

However, the image just stamped the class it with one hand comfortably, but on the other hand requires a connection to the front a separate css file.

http://prntscr.com/6z3tym

I would like in place of the class to insert ready-made styles may have missed something in the documentation. Is it possible to do?

**Comment by stefanneculai** [comment]
Using CSS classes is better for SEO purposes and it is much cleaner. We'll keep using classes.
