### ISSUE TITLE
Clicking the insert image link doesn't work

### ISSUE THREAD

**Issue by inexuscore** [froala/wysiwyg-editor#54]
Hi, thanks for the great work, Froala is simply awesome.
I'm having a weird problem though, i am using Froala in an ASP.NET MVC application and everything works as expected. after uploading an image the return URL is fine and the newly saved image appears in the editor. but i can only 'drop' my images into the popup dialog, when i click the 'Drop image or click here' link nothing happens, the File Upload dialog doesn't show up. it appears that this problem only occurs in FireFox and IE, using Google Chrome everything works perfectly. I'm using FF 29 and IE 11 on Windows 8.1.

I checked the documentation online and examined your example files but i wasn't able to figure out what might be causing this problem.

I also tested my web page on several web browsers and the results were all the same.
I would appreciate it if you could check into this and help me out.

Sincerely

**Comment by pmalliak** [comment]
Thank you, inexuscore that fixed it! I had the same problem in all browsers using OS X. It was fine on windows.

**Comment by inexuscore** [comment]
@pmalliak sure thing, glad I could help.

**Comment by jspitzberg** [comment]
Similar issue: Materialize framework was setting input[type="file"] to display:none. Thanks for pointing me in the right direction.
