### ISSUE TITLE
Specify the width of the image in percent

### ISSUE THREAD

**Issue by joomline** [froala/wysiwyg-editor#540]
In the plugin image editing is not possible to specify width in pixels or percentage, it is sometimes required for typesetting articles.
Is it possible to add configuration settings images where you can set the width of the image?
For many users it is not convenient to use the mode for editing source code, so set the width to 100%.
http://prntscr.com/6z3v99

**Comment by stefanneculai** [comment]
Done in v2.0.0-rc.1.
