### ISSUE TITLE
image not displayed in editor after uploading image

### ISSUE THREAD

**Issue by lavanyau** [froala/wysiwyg-editor#541]
hi,
      $(function(){
          $('#edit').editable({inlineMode: false, imagesLoadURL: "http://demo.web24solutions.com/editor/examples/uploads",
      imageUploadURL: 'http://demo.web24solutions.com/editor/examples/upload.php'})

        $('form').submit(function () {
          console.log($(this).find('textarea').val());
          return false;
        })
		// Getter.
var imagesLoadURL = $('#edit').editable('option', 'imagesLoadURL');

// Setter.
$('#edit').editable('option', 'imagesLoadURL', 'http://demo.web24solutions.com/editor/examples/uploads');

      });

this is my script 

images are uploaded into upload folder but it not showing in editor preview

can you please help me

**Comment by stefanneculai** [comment]
We use this repo only for bug tracking. If you have a license that includes support, please contact us via our website. Thank you.

**Comment by kasaiee** [comment]
I have this issue too

**Comment by kasaiee** [comment]
I solved this by commenting my url conf
```
urlpatterns = [
    url(r'^$', views.index, name='index'),   
#    url(r'^froala_editor/', include('froala_editor.urls')),
]
```
