### ISSUE TITLE
defaultImageAlignment breaks image display style

### ISSUE THREAD

**Issue by rtcoms** [froala/wysiwyg-editor#546]
In out app we don't want users to write text beside image or upload images side by side. the default style for image display is block . Although this works only defaultImageAlginment is 'center' .

 If I set defaultImageAlginment: "left"  or from froala editor ui I change the alignment, I am able to write text beside image .

**Comment by stefanneculai** [comment]
Are you using the master version or an older version?

**Comment by rtcoms** [comment]
We are using 1.2.5. Let me try latest version and give an update

**Comment by rtcoms** [comment]
Issue is corrected ni version 1.2.6
