### ISSUE TITLE
Can't paste HTML into Show HTML textbox when plainPaste: true

### ISSUE THREAD

**Issue by ghaydarov** [froala/wysiwyg-editor#548]
Hello, 

Thanks for this great editor. I have this issue. I want to most of the pasted stuff to be plain text and get rid of formatting. But I also want to add external html to my editor.  Is there Add HTML Code feature that would safely let me add any html and keep formatting? 

How should I accomplish this?

I use Set HTML to insert certain snippets, however, I need to be able to insert any HTML when I intend to do so and also keep default behaviour in plainPaste mode.

Thanks!

**Comment by stefanneculai** [comment]
In the HTML view, the copied text will always be pasted as plain text and that cannot be changed. For pasting in the editing mode, you can listen to the `beforePaste` event and handle pasting the way you want.
