### ISSUE TITLE
Post paste cleanup hook

### ISSUE THREAD

**Issue by benosman** [froala/wysiwyg-editor#549]
I've just purchased Froala, and i'm very impressed so far.

On my site it involves pasting material from various sources (websites, word documents etc) often with inconsistent formatting.

So far in my testing Froala does a very good job of cleaning up the html after pasting, however often it leaves some blank paragraphs (e.g. `<p>&nbsp;</p>`) and i'd like to fix this to save manually editing each time.

I noticed the paste cleanup hook in #195, which I thought could work for me, but due to the diverse nature of the source content, it would be much easier to write a regexp for the already cleaned up data.

I see there is an afterpaste event, but i'd rather not use that as I need to get and set the html from the editor and it would likely involve a visual flash as it pastes it and then the blank paragraphs get removed.

So, ideally i'd like another hook just the same as onPaste, after the clean process and just before the html is inserted into the editor.

**Comment by stefanneculai** [comment]
We'd need few more details so that we can clean it by default.
- what browser are you using?
- where are you copying from?
- are you using plainPaste?

**Comment by benosman** [comment]
I'm having these issues using Firefox & Chrome on OSX. I'm not using plainPaste as i'd like to keep bold / italic / underline formatting intact.

To give an example, when pasting from most blogspot sites they have double spacing issues.

http://googleblog.blogspot.com/2015/05/doing-more-on-diversity.html

Copying and pasting a few paragraphs from there results in  `<p><br></p>` between paragraphs.

It's obviously because they use two `<br>` tags to signify a new paragraph rather than a `<p>` tag.  I do understand though that in some cases stripping these may be undesirable so that's why i was looking to be able to adjust to my site's requirements.

**Comment by aops** [comment]
I still have this issue on latest editor.

**Comment by theyak** [comment]
I still have this issue in latest version. Except it pastes as <div><br></div><div><br></div>.
