### ISSUE TITLE
Uneditable element inside editor

### ISSUE THREAD

**Issue by ctekin** [froala/wysiwyg-editor#551]
Is there any way to have uneditable elements inside the editor? Sort of like the `uneditableContainerClassname` option in [Voog/wysihtml](https://github.com/Voog/wysihtml)? If not, how would I go about implementing it via a plugin?

**Comment by stefanneculai** [comment]
You can add the attribute `contenteditable="false"` to those elements that you don't want to edit. The version 2.0.0 will come with a more advanced mechanism builtin for that.

**Comment by Smashr** [comment]
Hey Stefan,

Did the advanced mechanism for the uneditable areas come to fruition ? I'm looking for an option in the Docs but can't seem to find it.

Thanks.

**Comment by ndimatteo** [comment]
@stefanneculai is there any more documentation on this sort of thing? We are also trying to insert some special html into the editor that we'd like the user to not be able to edit (ie: a preformatted form), however when this attribute is used the item can't be deleted or moved. So it's essentially "stuck" where it was inserted unless you go into the code editor and manually remove.

Not really user-friendly or intuitive that way :/
