### ISSUE TITLE
Pasting problems from Addy Osmani's JavaScript book

### ISSUE THREAD

**Issue by dandv** [froala/wysiwyg-editor#552]
1. Copy some text+code from http://addyosmani.com/resources/essentialjsdesignpatterns/book/

    ![image](https://cloud.githubusercontent.com/assets/33569/7525112/d371cbc6-f4d4-11e4-95d6-e6fd45a6f4cc.png)

2. Paste in Froala

![image](https://cloud.githubusercontent.com/assets/33569/7525107/c70e5c8c-f4d4-11e4-9b3a-97f268c196d0.png)

By comparison, in [CLEditor](http://premiumsoftware.net/cleditor/):

![image](https://cloud.githubusercontent.com/assets/33569/7528519/167b19aa-f4f7-11e4-8989-3ce17e021b08.png)

**Comment by stefanneculai** [comment]
Last commit adds the new lines that were missing. The fact that the rest of the style is not copied is not an issue. CLEditor keeps all the inline style from the original site which is a total no from us.

**Comment by dandv** [comment]
Thanks Stefan. Has https://www.froala.com/wysiwyg-editor/customize been updated by any chance? Would be nice to see how the text pastes now in the demo.

**Comment by stefanneculai** [comment]
We're updating the website version as soon as we make the release of the version 1.2.7. That will be for sure during next week.

**Comment by dandv** [comment]
Just checking if the site has been updated. Now the line numbers are more in-synch (though not perfectly aligned), but the syntax highlight is gone:

![image](https://cloud.githubusercontent.com/assets/33569/7880703/f6a27676-05b0-11e5-840a-9c5666a94af9.png)

Is this a limitation as you mentioned [earlier](https://github.com/froala/wysiwyg-editor/issues/552#issuecomment-100199127) and unlikely to get fixed? In other words, is this the most that Froala plans to do in order to support pasting rich content?

**Comment by stefanneculai** [comment]
We're currently working on an improved version for the editor 2.0.0. The new version will have better cleaning algorithms and options for keeping inline styles if someone may want that.
