### ISSUE TITLE
Need a setting that disables the url-encoding in attributes.

### ISSUE THREAD

**Issue by Arkadiy-Sedelnikov** [froala/wysiwyg-editor#553]
When you save article, the href attribute of the tag is encoded in a url encoded. It sometimes interferes with work, for example in the case when I write a template 
`<a href="[URL]" style="font-weight: bold;">View and reply on [SITENAME]</a> `
brackets in the href attribute of the url-encoded and break the template. Need a setting that disables the url-encoding in attributes.

**Comment by stefanneculai** [comment]
Disabling it may introduce XSS vulnerabilities and its not recommended. It would be better to pass such variables differently such as starting with an underscore.

**Comment by Arkadiy-Sedelnikov** [comment]
It's other people's templates, and I can't affect their syntax.  	
Besides I'm not asking to remove the coding, and now you can give the configuration I will use in trusted sites and do not apply dangerous.

**Comment by stefanneculai** [comment]
Adding an option for that might introduce vulnerabilities, because anyone can change the option using the JS console. You could do the following if you want to disable that:

```js
$.Editable.prototype.sanitizeURL = function (url) {
    return url;
}

**Comment by Arkadiy-Sedelnikov** [comment]
Thanks, I'll apply it in the admin panel, there is no danger, but from the
front will work as usual.

2015-05-08 15:37 GMT+06:00 Stefan Neculai <notifications@github.com>:

> Adding an option for that might introduce vulnerabilities, because anyone
> can change the option using the JS console. You could do the following if
> you want to disable that:
>
> $.Editable.prototype.sanitizeURL = function (url) {
>     return url;
> }
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/froala/wysiwyg-editor/issues/553#issuecomment-100173740>
> .
>



-- 
С уважением, Аркадий Седельников.

**Comment by JoshLedgard** [comment]
Hi - Is there a good way to do this same sort of override in the 2.0 branch?

**Comment by fyneworks** [comment]
See https://github.com/froala/wysiwyg-editor/issues/1235
