### ISSUE TITLE
selfClosingTags <br> into <br />

### ISSUE THREAD

**Issue by quangv** [froala/wysiwyg-editor#554]
Is there a way to force closing tags? I need to turn `<br>` into `<br />`

... I tried option `selfClosingTags: []` but that just seems to not allow `br` tags at all.

Reason is, I need all tags to having closing slash. So `<img>` would also need to be `<img />` etc.

Thanks!

**Comment by stefanneculai** [comment]
The editor is outputing the HTML according to the HTML5 specs. However, you can use the getHTML event and make the changes you need using a RegEx.
