### ISSUE TITLE
Bootstrap modal: could not copy-paste text in ie10 - 11

### ISSUE THREAD

**Issue by kotmatpockuh** [froala/wysiwyg-editor#555]
Hello. What i mean you could check here:

http://embed.plnkr.co/0eUe4bXma84BNZwzKebn/preview

(yes, i didn't use angular-ui for some big reasons)

*steps to reproduce:*

go to link http://embed.plnkr.co/0eUe4bXma84BNZwzKebn/preview
enter some text 
select some text
copy this text
try to copypaste this text in ie
as result i see new `<br>` tags but no content is copied.

seems that something is not working...

but in other browsers all is ok

also for some reasons when i try to copy from ie and paste to chrome i get additional tags from head of the app like:

```
<p><br>
</p>
<!-- Place favicon.ico and apple-touch-icon.png in the root directory -->
<p><br>
</p>
<!-- build:css(.) styles/vendor.css -->
<p><br>
</p>
<!-- bower:css -->
<p><br>
</p>
<!-- endbower -->
<p><br>
</p>
<!-- endbuild -->
<p><br>
</p>
<!-- build:css(.tmp) styles/main.css -->
<p><br>
</p>
<!-- endbuild -->
<p><br>
</p>
<!-- ngRepeat: (routeCtrl, cssUrl) in routeStyles -->
<p><br>
</p>
```

replaces from here: https://github.com/froala/angular-froala/issues/18

**Comment by stefanneculai** [comment]
Last commit fixes it. Those comments appear because they are copied in the clipboard.
