### ISSUE TITLE
<i> replaces <em>

### ISSUE THREAD

**Issue by joomline** [froala/wysiwyg-editor#556]
In the editor there is a small problem with automatic replacement tags.
The editor automatically replaces the `<i>` on the` <em>`, which is very bad. The fact that all of the font icon using the `<i>` default.
It is very strong can interfere with the work in edit mode code.

**Comment by viocassel** [comment]
+1

**Comment by stefanneculai** [comment]
The last commit adds in the option `iconClasses` which is an array with the classes for the icons. Its default value is `['fa-']`.
