### ISSUE TITLE
Outdenting list results in incorrect markup

### ISSUE THREAD

**Issue by mwtorkowski** [froala/wysiwyg-editor#558]
Tested on latest Chrome on froala 1.7.2.
First screenshot shows list and relevant markup - caret is placed after "c" item.
![selection_261](https://cloud.githubusercontent.com/assets/6072390/7680512/72103b4c-fd67-11e4-9c62-b3c9d4c7e2b0.png)

Second screenshot - editor and relevant markup after using either SHIFT + TAB shortcut, or "outdent" button from the toolbar. Item "d" and surrounding "ol" element is now child of new LI item, instead of being nested inside "c".
![selection_262](https://cloud.githubusercontent.com/assets/6072390/7680535/c37c5d44-fd67-11e4-8d69-a846305439d2.png)

**Comment by stefanneculai** [comment]
I can confirm the issue. We'll fix it in a few days.
