### ISSUE TITLE
Font Resize

### ISSUE THREAD

**Issue by cybricks** [froala/wysiwyg-editor#562]
Want the font size to reduce once it reaches the max height of the textbox. And increase when text is removed.

Basically text should take up the entire height and width and resize according to the size of textarea

I have a script for this which i use on normal textareas. 

```js
<script>
      $('#Text11').keypress(function(){
          if ( $(this).get(0).scrollHeight > $(this).height() ) {
              $(this).css('font-size', '-=1');
          }

          if ($.trim($('textarea').val()).length <= 0)
          {
            $(this).css('font-size', '14px');
          } 
      });
</script>

**Comment by stefanneculai** [comment]
We use this repo for bug reporting and not for support. Please read https://github.com/froala/wysiwyg-editor#reporting-issues.
