### ISSUE TITLE
Whitespace validation

### ISSUE THREAD

**Issue by kotmatpockuh** [froala/wysiwyg-editor#564]
Hello.

It's seems to be a bug...

For example in wysiwyg mode i enter some whitespaces, but textarea is with the require, minlength tags.

But it turns to be valid. If i turn into html mode i see: 

```html
<p> &nbsp; ...  </p>. 
```

So, maybe there are ways of solving this to invalid validation?

**Comment by stefanneculai** [comment]
It's not an issue, but adding `&nbsp;` is necessary to make the whitespaces appear.
