### ISSUE TITLE
XSS bug

### ISSUE THREAD

**Issue by hiperlouro** [froala/wysiwyg-editor#565]
I was testing out froala and came to this bug:

If I open the insert link popup, type 

`http://#<script>alert("This should not be shown!");</script>`

and __press enter__, the javascript is executed.
The version used to test this was the latest (1.2.7).

**Comment by VeeeneX** [comment]
This isn't XSS Bug, because it's silly to trust client. You need to clean xss on server side rather than in client side.

**Comment by stefanneculai** [comment]
Last commit fixes it. 

@VeeeneX that is perfectly right, but the editor should clean XSS as well. Indeed, it is recommended to make a XSS clean on the server, because client might send it bad HTML using the JS console.

**Comment by hiperlouro** [comment]
Thanks.
@VeeeneX , yes, the code is being cleaned on the server side, but I think this behaviour should not be permitted on the client side as well.

**Comment by VeeeneX** [comment]
@stefanneculai Tes, it's useful :+1: , if it outputs less bad code 
@hiperlouro Yes, good mention
