### ISSUE TITLE
Block styles to <li>

### ISSUE THREAD

**Issue by Arkadiy-Sedelnikov** [froala/wysiwyg-editor#567]
`blockStyles: {
    'li': {
      'test': 'Class 1'
    }
  }`
instead of `<li class="test">` prescribe `<li><p class="test">`

**Comment by stefanneculai** [comment]
The `blockStyles` is not designed to work for li, but only for the content inside. Version 2.0.0 will come with options for setting class to `li` as well.

**Comment by Arkadiy-Sedelnikov** [comment]
OK, thanks.
