### ISSUE TITLE
Have you mention plugin?

### ISSUE THREAD

**Issue by YadrovSergey** [froala/wysiwyg-editor#569]
Have you mention plugin?

**Comment by stefanneculai** [comment]
You can use At.js https://github.com/ichord/At.js/tree/master.

**Comment by aligajani** [comment]
Hey @stefanneculai , need your insight.

```
                     {{ Form::textarea('text', '', array('id' => 'edit', 'class' => 'form-control', 'placeholder' => 'Your words go here..', 'data-parsley-required' => 'true', 'data-parsley-trigger' => 'change', 'data-parsley-minlength' => '10', 'size' => '60x10')) }}

```

I initialize Froala using ('#edit').editable but At.js won't show up. It shows up on a normal textarea without Froala though. Is Froala doing something weird to not allow At.js to function properly. I am using a Froala version from 2014 Dec

**Comment by stefanneculai** [comment]
If you can provide a jsFiddle we can definitely look into it.

**Comment by aligajani** [comment]
Fixed it folks, was a race condition.

Used this `$('#edit').on('editable.initialized', function (e, editor) {`
