### ISSUE TITLE
Text inputs on popovers don't focus when placed in bootstrap modal

### ISSUE THREAD

**Issue by dubvfan87** [froala/wysiwyg-editor#570]
I'm seeing a strange behavior on tool popups when placing froala in a modal. See attached image.

When I hover over the text box I get the correct cursor icon, but can't focus on it to enter any input. Oddly enough the checkbox in that form works fine.

I thought maybe it was a z-index issue so I played with the indexes a bit using the chrome dev tools, but still was unable to get it to focus. I can try and create a fiddle if the developers would find this useful.

![screen shot 2015-05-25 at 1 22 37 pm](https://cloud.githubusercontent.com/assets/1103667/7800344/df8db256-02e1-11e5-9630-8ee52044cb78.png)

**Comment by brownstoneacademy** [comment]
I am having the same issue and have never been able to fix the issue my self.

**Comment by stefanneculai** [comment]
@dubvfan87 @brownstoneacademy could you please confirm that you're using the master version?

**Comment by dubvfan87** [comment]
I'm currently using version 1.2.7. I will try using master here in a sec.

**Comment by dubvfan87** [comment]
I've just tested it with master, the issue is still there.

**Comment by stefanneculai** [comment]
@dubvfan87 could you please check 0336377657b2b0120940737d4b352ac3017f47db and let me know if it fixes the issue? Thanks!

**Comment by dubvfan87** [comment]
That appears to have fixed it: http://jsfiddle.net/dubvfan87/52VtD/11610/
