### ISSUE TITLE
Append parameters to $.post on image upload with $.ajaxPrefilter not working

### ISSUE THREAD

**Issue by agarhy** [froala/wysiwyg-editor#571]
Hi, I'm trying to append CSRF tokens to image upload post, but seems $.ajaxPrefilter is not working on image upload.

here is the filter i use to append params to all $.post requests but seems not called on image upload

```javascript
$.ajaxPrefilter(function (options, originalOptions, jqXHR) {
    if (options.type.toLowerCase() === "post") {
        // add leading ampersand if `data` is non-empty
        options.data += options.data ? "&" : "";
        // add _token entry
            options.data += csrf_token_name + "=" + csrf_token_value;
    }
});
```
Any idea how this can be accomplished ?

**Comment by stefanneculai** [comment]
It is not working because image upload is not using `$.post`. However, you can pass the CSRF tokens through https://www.froala.com/wysiwyg-editor/docs/options#imageUploadParams.

**Comment by agarhy** [comment]
I wanted to make the json key of imageUploadParams dynamic, so i used following method
```javascript
.on('editable.beforeImageUpload', function (e, editor, images) {
        editor.options.imageUploadParams[csrf_token_name]=csrf_token_value;        
    })
```
and it works now.. 
Thanks for help.

**Comment by atomoc** [comment]
@agarhy What is contained in the variable csrf_token_name?

**Comment by imtiazmahbub** [comment]
> @agarhy What is contained in the variable csrf_token_name?

Must be this:
`Yii::$app->request->getCsrfToken()`

**Comment by mra-dev** [comment]
@agarhy 
https://github.com/froala/wysiwyg-editor/issues/571#issuecomment-109294137
Nice approach.

I used this code in AlpineJS Library:

`init() {
        this.module.editor.opts.imageUploadParams._token = "shits"
    }`


which `this.module.editor` is just a nested data set in alpine export object:

`export default () => ({
        module: {
                editor: new FroalaEditor(......)
        }
})`
