### ISSUE TITLE
Ignore escape html code string in textarea when loading

### ISSUE THREAD

**Issue by magisters-org** [froala/wysiwyg-editor#572]
Hello. Let's take a look. This string hase been recorded from editor to database: <pre>&lt;html&gt;&lt;/html&gt;</pre>
So, when editor is loaded in textarea with this content, i don't see anything, because editor interprets this code like an html markup, not a escaped symbols. When we load this content in froala used with div, i see:
<pre>&lt;html&gt;&lt;/html&gt;</pre>
Sorry for my bad english, but i think you understand me.

**Comment by stefanneculai** [comment]
Inside textareas  HTML entities should be escaped. See https://github.com/froala/wysiwyg-editor/issues/482#issuecomment-83714915.
