### ISSUE TITLE
Table columns resize too aggressively while typing

### ISSUE THREAD

**Issue by dandv** [froala/wysiwyg-editor#573]
Same bug as in [Summernote](https://github.com/summernote/summernote/issues/1113), [CKEditor](http://dev.ckeditor.com/ticket/13340), and [AlloyEditor](https://github.com/liferay/alloy-editor/issues/223).

Is Froala based on CKEditor?

By comparison, Google Docs and [Textbox.io](http://textbox.io/demo/) offer a more consistent table editing experience.

![google doc table behaves normally](https://cloud.githubusercontent.com/assets/33569/7901026/734d1310-0729-11e5-859b-cb97c0b241e1.gif)

**Comment by stefanneculai** [comment]
We have already addressed this issue in the version 2.0.0. In fact we've rebuilt from ground the table tool in the new version. And no, Froala is not based on CKEditor only that there is no width set to the table cell and that's why it resizes while you type.

**Comment by stefanneculai** [comment]
Improved in v2.0.0-rc.1.
