### ISSUE TITLE
Support for browserify

### ISSUE THREAD

**Issue by Avnerus** [froala/wysiwyg-editor#574]
Dear Froala,
I'm writing a framework plugin ([RiotJS](https://github.com/muut/riotjs/)) for the wysiwyg editor and I want to bundle it using Browserify.
However, bundling the minified editor raises the following exception:
```
TypeError: b is undefined
...n typeof a===b}var f,g,h,i="2.7.1",j={},k=b.documentElement,l="modernizr",m=b.cr...
```
It's a bit difficult to track down the problem with the minified code, but I noticed that in the call to ```window.WYSIWYGModernizr``` I can replace the arguments from:
````
(this, this.document)
````
to
````
(this, document)
```
And it solves the issue.
Can you take a look?
My integration project is here:
https://github.com/ListnPlay/riot-froala
You can run it using:
```npm run demo```
Thanks!

/Avner

**Comment by thaliemuk** [comment]
i also have the same problem
 can you fix it please.

thank you

**Comment by gonsfx** [comment]
Same here.

Trying to integrate it into an app that uses npm and browserify for all dependencies. Adding a browserify-shim to the `package.json` results in:

```
Uncaught TypeError: Cannot read property 'documentElement' of undefined
```

in `window.WYSIWYGModernizr`, because the `this` and `this.document` arguments given to the function seem to be off.
