### ISSUE TITLE
Froala remove all <br>'s from <pre> when editor loaded

### ISSUE THREAD

**Issue by magisters-org** [froala/wysiwyg-editor#575]
When i writing code in 'pre', froala add 'br' when i press enter. After saving editor results in database i have html markup with 'br'-tags in 'pre'.
And when i try add this content in editor before loading the page
(like this: <?=$post['post_text']?>)
all 'br'-tags will be removed from 'pre'-tags in viewport. Why is this happening? froala_editor v1.2.8

Sorry for my bad english, but i think you understand me.

**Comment by stefanneculai** [comment]
How are you saving the content of the editor to the DB? It should not send `<br>` tags inside `<pre>`.

**Comment by magisters-org** [comment]
I use jQuery ($('.froala-view').html()).

**Comment by stefanneculai** [comment]
You're not using it right. Please see https://froala.com/wysiwyg-editor/docs/examples/getHTML.

**Comment by magisters-org** [comment]
My problem is resolved. Thank You!
