### ISSUE TITLE
Set focus to text size list when open

### ISSUE THREAD

**Issue by hiperlouro** [froala/wysiwyg-editor#579]
On Froala 1.2.7:

When I open the list of text size I must select the size it using the mouse. 
Shouldn't the focus be on the font size list so that the user could select using the cursor and confirming pressing the enter key?

**Comment by stefanneculai** [comment]
That's a nice enhancement, but it is not designed to work this way.

**Comment by stefanneculai** [comment]
Done in v2.0.0-rc.1.
