### ISSUE TITLE
Set focus and cursor programmatically on the editor

### ISSUE THREAD

**Issue by analuisamartins** [froala/wysiwyg-editor#58]
Hi,

How do I set focus programmatically on the editor?
I'm trying something like this:

element.find('.oc-froala-editor').data('fa.editable').$element.focus(); 

The editor box is focused but the cursor at the beginning does not show up.

I also tried: 

element.editable('setSelection', element.find('.froala-element').get(0), 0);

but not working.

What I'm doing wrong?

Thanks.

**Comment by kotmatpockuh** [comment]
@analuisamartins  please share your code)
