### ISSUE TITLE
Fullscreen + Image Toolbar Offset

### ISSUE THREAD

**Issue by katzsimon** [froala/wysiwyg-editor#581]
When the editor is in fullscreen and you have scrolled down some what (the more you scroll down the worse the offset seems to be), if you then click on an image the image toolbar appears higher up, out of site and offset from the image.

If you take the editor out of fullscreen, the image toolbar appears where it should at the image.

**Comment by kotmatpockuh** [comment]
the same appears to me in popup

**Comment by katzsimon** [comment]
Here is an example from the current latest code that still shows the problem.

Go into full screen and you can click on each of the image as you scroll down and you can see where the image toolbar appears (you probably need to scroll up to see the toolbar for the last image). It does the same for me on Chrome and Firefox on Windows.

http://skatz.co.za/froala-fullscreen-imagetoolbar/examples/fullscreen.html

**Comment by stefanneculai** [comment]
The problem seems to happen only after a certain amount of scroll. I've reopened the issue and we'll review it.

**Comment by kotmatpockuh** [comment]
as for me: i enter many times 'enter' so that my textarea is very tall (mush taller than body), and then it appears (i do not use fullscreen)

**Comment by kotmatpockuh** [comment]
could i know when you ~ will take a look?

**Comment by kotmatpockuh** [comment]
very-very hotfix):

```
a.Editable.prototype.showByCoordinates = function(a, b) {...
...
var c = this.$document.find('.froala-view');
var wrH = this.$document.find('.froala-wrapper');
b = c.height() - wrH.height() + 40;

```
