### ISSUE TITLE
Slow performance with large amounts of text

### ISSUE THREAD

**Issue by NeilMeredith** [froala/wysiwyg-editor#582]
I am experiencing extremely slow performance with large amounts of text in the editor.  There is a significant lag between typing new words and then appearing in the editor.  

I created this JsFiddle [as a sample] (https://jsfiddle.net/v9mtqzdd/3/).  It has about 13k words just to make the issue obvious, but I see issues long before this - around 4 or 5k words.

Is there any way to improve performance for larger amounts of text?

**Comment by stefanneculai** [comment]
We're working on a new release 2.0 and we have already addressed this issue. It will be available very shortly.

**Comment by NeilMeredith** [comment]
Ok great!  Any idea when the 2.0 release will come out?

**Comment by stefanneculai** [comment]
We don't have a specific release date, but it will be in the following weeks.

**Comment by NeilMeredith** [comment]
Ok.  If I purchase the editor and start using it before the 2.0 release, will everything be backward compatible when I upgrade to 2.0?

**Comment by stefanneculai** [comment]
Yes, all HTML generated in version 1.* will be compatible with version 2.0.

**Comment by kotmatpockuh** [comment]
2.0: any news?

**Comment by stefanneculai** [comment]
We're writing the migration guide from v1 to v2 right now and it will be published on our website as soon as we finish to write it. Sorry to keep you guys waiting.

**Comment by stefanneculai** [comment]
Should be fixed on master.
