### ISSUE TITLE
A Bug In Froala Samples

### ISSUE THREAD

**Issue by mirsaeedii** [froala/wysiwyg-editor#584]
There is an Example section in Froala.Com! It seems that we have a bug in the "RTL LTR Direction Buttons" part with the following address: https://www.froala.com/wysiwyg-editor/docs/examples/rtl-ltr-custom-button

In the changeDirection function, the line after the loop is:

var element = divs[i];

but it should be:

var element = elements[i];

The second point i want to mention is that what is the goal of head function which is wrapping the entire scripts in this example?

**Comment by stefanneculai** [comment]
Fixed. Thanks for pointing that out.

The `head` was an error on our side. It should be `$` instead. We correct it as well.
