### ISSUE TITLE
area tag is not working in editor

### ISSUE THREAD

**Issue by Seshuthokala** [froala/wysiwyg-editor#587]
How to work with "area" tag in editor while i try to write these tags it always changes it to "p" tag.

**Comment by stefanneculai** [comment]
Could you please provide the steps to reproduce the issue?

**Comment by Seshuthokala** [comment]
Here is sample code
I copy pasted this code in HTML view and saved the content 
<map name="Map" id="Map">
  <area shape="circle" coords="517,33,20" href="https://www.facebook.com" target="_blank" alt="" />
  <area shape="circle" coords="567,34,19" href="https://www.linkedin.com" target="_blank" alt="" />
  <area shape="circle" coords="620,34,19" href="https://twitter.come" target="_blank" alt="" />
  </map>

if i reopen the content it changes to 
<map name="Map" id="Map"></map>

remaining all content disappears.

**Comment by stefanneculai** [comment]
That's because you have not added `area` to the [selfClosingTags](https://www.froala.com/wysiwyg-editor/docs/options#selfClosingTags) option.
