### ISSUE TITLE
Is it possible to convert a plain text link with <a> tag?

### ISSUE THREAD

**Issue by aligajani** [froala/wysiwyg-editor#589]
So if I have https://google.com, I want it to be <a href="https://google.com">link</a>

**Comment by stefanneculai** [comment]
The URLs plugin is what you're looking for https://www.froala.com/wysiwyg-editor/docs/plugins

**Comment by aligajani** [comment]
Where's the download link Stefan?

On Fri, Jun 19, 2015 at 3:08 PM, Stefan Neculai <notifications@github.com>
wrote:

> The URLs plugin is what you're looking for
> https://www.froala.com/wysiwyg-editor/docs/plugins
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/froala/wysiwyg-editor/issues/589#issuecomment-113526051>
> .
>



-- 


Ali Gajani
Founder at Mr. Geek
www.mrgeek.me
www.aligajani.com

**Comment by stefanneculai** [comment]
The plugins can be found inside the downloaded archive `js/plugins`.

**Comment by aligajani** [comment]
neat, lovely.

On Fri, Jun 19, 2015 at 3:45 PM, Stefan Neculai <notifications@github.com>
wrote:

> The plugins can be found inside the downloaded archive js/plugins.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/froala/wysiwyg-editor/issues/589#issuecomment-113535605>
> .
>



-- 


Ali Gajani
Founder at Mr. Geek
www.mrgeek.me
www.aligajani.com
