### ISSUE TITLE
After delete image position cursor is at the begining of text

### ISSUE THREAD

**Issue by kotmatpockuh** [froala/wysiwyg-editor#591]
For example so i delete image:

http://prntscr.com/7jukuh

and after delete cursor is here: 

http://prntscr.com/7jukwe

but cursor must be in the deleted position...

**Comment by stefanneculai** [comment]
Could you please let us know what browser are you using?

**Comment by kotmatpockuh** [comment]
any news?

**Comment by stefanneculai** [comment]
Should be fixed on master.

**Comment by kotmatpockuh** [comment]
still is not fixed in v1
yes, i know that this is fixed in v2, but v2 still have a lot of issues, and i need to fix it in v1
is it real to catch image position cursor in method: afterRemoveImage or similar?

**Comment by stefanneculai** [comment]
@kotmatpockuh V2 has fixed many issues that were present in V1 and the current issues that are opened are minor ones that happen only in certain situations and they will be fixed in the following days as well.
