### ISSUE TITLE
Changing Text Size in a Table causes new Table to be inserted randomly

### ISSUE THREAD

**Issue by smenchions** [froala/wysiwyg-editor#592]
We are using Version 1.2.7 of Froala and when you change the size or color of the text in a table a new table seems to be created once you press enter multiple times. 

To replicate this error:

- go to your basic example on the website
- create a table with 1 column and 4 rows
- add some text like kjfhsdkjfhsdkjfhsdkjdfh
- select all the text and change its size to be larger in px.
- press enter multiple times with the cursor at the end of the newly enlarged text
- New rows or new tables will appear inside the row you typed the text into. 

![froalaerror](https://cloud.githubusercontent.com/assets/472997/8289101/344b9ec2-18cf-11e5-8750-e7ea225f4acb.PNG)

**Comment by stefanneculai** [comment]
Should be fixed on master.
