### ISSUE TITLE
Spellcheck attribute not working

### ISSUE THREAD

**Issue by pritps** [froala/wysiwyg-editor#593]
I am trying to enable spellcheck in the editor using the following code:

$(function() {
    $("textarea.rich_formatting").editable({
        inlineMode: false,
      buttons: ["undo", "redo" , "sep", "fontSize", "formatBlock", "sep", "bold", "italic", "underline", "sep", "insertOrderedList", "insertUnorderedList", "html"],
      placeholder: "",
 simpleAmpersand: true, 
spellcheck: true
  });
});

However, this is not working. When I inspect the editor element in google chrome, I noticed that the spellcheck attribute is set to false, even though I have specified true in my javascript. Thus, I tried to change that attribute dynamically through the inspection tool, and the spellcheck feature is now enabled and working.

**Comment by stefanneculai** [comment]
I have just checked and it is working fine. There is no problem in the master verion.
