### ISSUE TITLE
add ability to draggeble toolbar 

### ISSUE THREAD

**Issue by thaliemuk** [froala/wysiwyg-editor#595]
allow the editor to be initialized at inline mode always visible, but allow the toolbar to be dragged around the page.
this way bugs of locating the toolbar will no logner be relevant.
and the user will have a good user experience because that could always has it's toolbar in sight.
this feature is very commom in text editors

**Comment by stefanneculai** [comment]
As I already told you by email *we don't have any plans on implementing it, however you can use the source code and extend the toolbar behaviour for your needs*.
