### ISSUE TITLE
initOnClick Query

### ISSUE THREAD

**Issue by neerajjoshi** [froala/wysiwyg-editor#596]
Hi,

I am using the free version of Froala editor using the files provided in git hub. I have 3 divs in my page and have setting as below :-
{
     inlineMode: false,
	  initOnClick: true,
	  buttons: ['undo', 'redo' , 'sep', 'bold', 'italic', 'underline','html','fullscreen'],
	  toolbarFixed: false,
}
when I click on first div it bind editor with it and same for other div but I want that when I click on another div it remove the inline editor from others div changing them to their original state (that is div with out froala toolbar and highlighting ) and when click on non froala editor convert it to inline editor

Thanks

**Comment by stefanneculai** [comment]
You should use `inlineMode: true` if you want such a thing. 

Also, please notice that there is no free version and you have to purchase a license in order to use the editor.

**Comment by neerajjoshi** [comment]
Hello Team,

Thanks for your response .

I want to give Froala editor reference to my client so that he can purchase it but first i want to test it to check whether it meet our requirements or not so I make a clone from github . In my page I have 30-40 divs which I want to convert in to editor on click and as per documentation 

" Init on click improves the page performance by initializing only the basic code when the page is loaded and the rest of the code when clicking in the editable area. It is highly recommended to use this option if you have more rich text editors on the same page. "

there for I use initOnClick:true and  inlineMode: false else my page gets hang .

I just want to know is there a way if we use initOnClick:true then only one div have editable setting at a time like inlinemode :true.

Thanks

**Comment by stefanneculai** [comment]
As I said in the last message, you can do that by using `inlineMode: true`. Moreover, you can use the idea from http://debuggable.com/posts/run-intense-js-without-freezing-the-browser:480f4dd6-f864-4f72-ae16-41cccbdd56cb to initialize multiple editors without having the browser freeze.
