### ISSUE TITLE
List bold style bug

### ISSUE THREAD

**Issue by kotmatpockuh** [froala/wysiwyg-editor#597]
For example i create a num. list:

http://prntscr.com/7ljls5

i select all text (ctrl+a) and make it bold:

http://prntscr.com/7ljlux

only text is bold, numbers are still un-bold.

**Comment by stefanneculai** [comment]
Bold is designed to change the text, not other elements. The numbers before list items are not text and browsers do not allow to simply change the list item numbers to bold.
