### ISSUE TITLE
Color picker is not showing up on the editor

### ISSUE THREAD

**Issue by ghaydarov** [froala/wysiwyg-editor#598]
I am using froala in rails app and Color Picker is not showing up. I have every plugin listed like below and I hadded this config. Any ideas? Thanks!

colors: [
'#15E67F', '#E3DE8C', '#D8A076', '#D83762', '#76B6D8', 'REMOVE',
'#1C7A90', '#249CB8', '#4ABED9', '#FBD75B', '#FBE571', '#FFFFFF'
],

  // How many colors on a line.
  colorsStep: 6,
//= require jquery
//= require jquery-ui
//= require jquery_ujs
//= require froala_editor.min.js
//= require plugins/block_styles.min.js
//= require plugins/colors.min.js
//= require plugins/media_manager.min.js
//= require plugins/tables.min.js
//= require plugins/video.min.js
//= require plugins/font_family.min.js
//= require plugins/font_size.min.js
//= require plugins/file_upload.min.js
//= require plugins/lists.min.js
//= require plugins/char_counter.min.js
//= require plugins/fullscreen.min.js
//= require plugins/urls.min.js
//= require plugins/inline_styles.min.js
//= require froala.js

**Comment by stefanneculai** [comment]
Please do not SPAM. Since you have already opened an issue on https://github.com/froala/wysiwyg-rails/issues/20 it's enough.

**Comment by ghaydarov** [comment]
OK sorry about that. I wasn't sure if I had to use original editor or gem. Thanks!
