### ISSUE TITLE
Alert user to leaving the page with unsaved text in the editor

### ISSUE THREAD

**Issue by elikem** [froala/wysiwyg-editor#601]
Is there a way to alert the user leaving the page without saving? 
This reminds them to save before leaving if they forgot to save.

**Comment by stefanneculai** [comment]
You could listen to the [afterSave](https://www.froala.com/wysiwyg-editor/docs/events#afterSave) and [contentChanged](https://www.froala.com/wysiwyg-editor/docs/events#contentChanged) event and if any `contentChanged` event is triggered between 2 save requests then there are unsaved changes.
