### ISSUE TITLE
ctrl+enter in code block doesn't change the HTML

### ISSUE THREAD

**Issue by chr22** [froala/wysiwyg-editor#602]
If I insert a "code" block in your editor on this page: https://www.froala.com/wysiwyg-editor and push enter, then the cursor will leave the codeblock, but if I push ctrl+enter, it looks like a get a newline, but the HTML isnt really changed, so if i enter "HTML mode" and switches back to "wysiwyg mode" again the new lines is gone.

1. Write three lines
![1](https://cloud.githubusercontent.com/assets/3649594/8521905/00ea470c-23e9-11e5-9750-2283ee1d58a2.JPG)

2. Open HTML Mode
![2](https://cloud.githubusercontent.com/assets/3649594/8521906/038d5e72-23e9-11e5-835c-dc041144940a.JPG)

3. Close HTML mode
![3](https://cloud.githubusercontent.com/assets/3649594/8521907/05eed9e8-23e9-11e5-9893-62a44b123134.JPG)

**Comment by stefanneculai** [comment]
Could you please let me know what browser are you using?

**Comment by chr22** [comment]
Chrome v.45

**Comment by chr22** [comment]
IE 11 and Firefox v38 doesn't have the problem

**Comment by stefanneculai** [comment]
Could also please let me know what OS are you using?

**Comment by chr22** [comment]
Windows 8.1

**Comment by chr22** [comment]
Both Chrome and Windows is 64bit
