### ISSUE TITLE
Delete button will change formatting if content changes line

### ISSUE THREAD

**Issue by chr22** [froala/wysiwyg-editor#603]
1. Empty line above content
![1](https://cloud.githubusercontent.com/assets/3649594/8521967/8cb8207e-23e9-11e5-89c5-e9f45da83be0.JPG)

2. Push delete button and formatting is changed
![2](https://cloud.githubusercontent.com/assets/3649594/8521970/8f2093fa-23e9-11e5-8594-ca318bc2d4ca.JPG)

**Comment by stefanneculai** [comment]
That's the way it should work.
