### ISSUE TITLE
Feature request - Dropdown where selection can be seen when closed

### ISSUE THREAD

**Issue by chr22** [froala/wysiwyg-editor#604]
It would be nice if we could make custom dropdowns like the ones Google Drive uses, as seen on the pictures below, where the selection can be seen without opening the dropdown.
It would also be nice if some of your standard buttons used as well (maybe optional?).

![1](https://cloud.githubusercontent.com/assets/3649594/8522055/8046d6f4-23ea-11e5-9721-98039d44f4ef.JPG)

![2](https://cloud.githubusercontent.com/assets/3649594/8522057/8258594a-23ea-11e5-9f21-580a405a56cc.JPG)

**Comment by lc3t35** [comment]
+1, I've started to study that with a customized blockstyle plugin, but I'm stuck to replace the icon by the text. Instead of
````
<button tabindex="-1" type="button" data-name="blockStyle" class="fr-trigger" title="Style"><i class="fa fa-magic"></i></button><ul class="fr-dropdown-menu fr-block-style"></ul>
````
I would like to have 
````
<button tabindex="-1" type="button" data-name="blockStyle" class="fr-trigger" title="Style"><a href="#" data-toggle="dropdown">Normal text<i class="icon-arrow"></i></a></button><ul class="fr-dropdown-menu fr-block-style"></ul>
````
A little help from froala would be appreciated ;)

**Comment by lc3t35** [comment]
Hi @stefanneculai, could you please give some tips/examples so we can work on this plugin ? thank you.

**Comment by stefanneculai** [comment]
Version 2.0 will come with an option for that.

**Comment by chr22** [comment]
THANK YOU!

**Comment by lc3t35** [comment]
Uh ? Can't wait version 2.0 (except if it's delivered in less than 1 month, which could be an acceptable waiting time) !!! Please just give some clues and we'll do that ...

**Comment by stefanneculai** [comment]
Yes, v2.0 will come with this feature. It will be released by the end of August.

**Comment by lc3t35** [comment]
Wonderful ! Just 2 weeks to wait... (please don't forget the documentation).  Thank you @stefanneculai

**Comment by stefanneculai** [comment]
Option added in v2.0.0-rc.1.

**Comment by lc3t35** [comment]
@stefanneculai thank you , could you please give an example for using the new html function ?
````
  // If present, the options property will be ignored.
  // It can be used to define a custom HTML for the dropdown.
  html: function () {
    // The current context is the editor instance.
    return '';
  },
````

**Comment by stefanneculai** [comment]
There are builtin options for that, please see https://github.com/froala/wysiwyg-editor/blob/master/html/show_selection.html#L130. 

The html property allows you to set any custom HTML in the dropdown.
