### ISSUE TITLE
Feature request - shift+tab to outdent

### ISSUE THREAD

**Issue by chr22** [froala/wysiwyg-editor#605]
It would be nice if you could use "shift+tab" to outdent after you have indented with "tab".

This is the behavior we are used to from other text editors.

**Comment by stefanneculai** [comment]
There is a different shortcut for that (https://www.froala.com/wysiwyg-editor/shortcuts): 
Ctrl + ] or ⌘ Cmd + ]
Indents the current paragraph.

However, shortcuts can be changed.

**Comment by chr22** [comment]
Yes I have seen that, but the problem is that you can't use that with a danish keyboard layout because the "]" is accessed by pressing "alt+9" and you can't combine those shortcuts.
