### ISSUE TITLE
showInsertImage - doesn't work

### ISSUE THREAD

**Issue by josepaternina** [froala/wysiwyg-editor#606]
Hi

I've tried even in the console and doesn't work, but I try other methods like ***setHTML*** and works

https://www.froala.com/wysiwyg-editor/docs/methods#showInsertImage

>Shows the insert image popup.
_Invoke the method inside the rich text editor_:
```
$('.selector').editable('showInsertImage');
```

I Only want trigger the image popup from an external button 

![image of froala popup]
(http://photouploads.com/images/7a785f.png)

PD: I appreciate a live example (codepen, fiddle, jsbin, etc)

Thanks.

**Comment by stefanneculai** [comment]
The `showInsertImage` changes the content of the popup to show the insert image content. In order to actually show the popup, you also have to call the [showByCoordinates](https://www.froala.com/wysiwyg-editor/docs/methods#) method which places the popup at the desired position.
