### ISSUE TITLE
Image Selector and Video Editor not editable in Android 4.4.2 Webview - Ionic app

### ISSUE THREAD

**Issue by santoshv98** [froala/wysiwyg-editor#607]
Tested on Android 4.4.2 using an Ionic Application and found that "Drop Image" doesn't respond to touch events as well as 'Enter URL' for the image.

What do we do to get this touch responsive? My hunch is that the solution would be similar to the one mentioned below in another thread, but couldn't figure out the element that I need to apply the styling:

  .froala-box, .froala-box .froala-wrapper.f-basic {
    -webkit-user-select: text !important;
    -moz-user-select: text !important;
    -ms-user-select: text !important;
    user-select: text !important;
  }

**Comment by stefanneculai** [comment]
It might be something from Ionic. On our tests this works fine.
