### ISSUE TITLE
Inline editor popup disappears when opening at the bottom of the screen

### ISSUE THREAD

**Issue by hiperlouro** [froala/wysiwyg-editor#608]
When editing text with inline mode on, if the edited text is on the bottom of the screen, the toolbar popup disappears below the window bottom.

The correct behaviour should be toolbar the popup to be on the upper side of the cursor instead of the lower side as it is usually.
![inlinepopup](https://cloud.githubusercontent.com/assets/3466596/8654495/863f08f4-2982-11e5-96fe-4eae5b6aea10.png)

**Comment by stefanneculai** [comment]
Should be fixed on master.
