### ISSUE TITLE
blockTags doesn't list the defaults in documentation

### ISSUE THREAD

**Issue by KenStipek** [froala/wysiwyg-editor#609]
Which are:
```
    blockTags: {
      n: 'Normal',
      blockquote: 'Quote',
      pre: 'Code',
      h1: 'Heading 1',
      h2: 'Heading 2',
      h3: 'Heading 3',
      h4: 'Heading 4',
      h5: 'Heading 5',
      h6: 'Heading 6'
    }
```

https://www.froala.com/wysiwyg-editor/docs/options#blockTags

**Comment by stefanneculai** [comment]
Hi Ken! Yes, that is true and we have not put there the default option mainly because of the small space for default option. There will an update on that during August that will fix this.
