### ISSUE TITLE
Multiple levels for ul/li

### ISSUE THREAD

**Issue by connect-technologies** [froala/wysiwyg-editor#610]
Hi,
I'm using the editor for a while now (licenced).

Is it able to add multiple levels of ul/li lists?

thanks,

christopher

**Comment by connect-technologies** [comment]
I found it now:
Make a ul/li element, press "return" for a new line and then "TAB" to start a new level.
Perhaps it should be documented somewhere?

chris

**Comment by stefanneculai** [comment]
The list can also be indented by hitting the indent button from the toolbar. Most of the editors indent using TAB and it's most like a default thing.
