### ISSUE TITLE
Beatifull scrollbar

### ISSUE THREAD

**Issue by kotmatpockuh** [froala/wysiwyg-editor#611]
Is it real: somehow to append (for example this: https://github.com/mattbalmer/mb-scrollbar) to froala text editor?

**Comment by stefanneculai** [comment]
The editor doesn't has any built-in scrollbar. If you want to use a custom scrollbar, then the element you should set the scrollbar on is `$(selector).data('fa.editable').$wrapper`.

**Comment by kotmatpockuh** [comment]
whats the analogue for **$(selector).data('fa.editable').$wrapper** in v2.* ?

**Comment by stefanneculai** [comment]
`$(selector).data('fa.editable').$wp`
