### ISSUE TITLE
Paste lists from Word 

### ISSUE THREAD

**Issue by scottmessinger** [froala/wysiwyg-editor#612]
Hi! I'm really enjoying froala, but the lack of list support from Word is a struggle. Both TinyMCE and CKEditor both convert Word's crazy list syntax into `<ul>` or `<ol>` lists. The code to do this isn't trivial, however:

**CKEditor**: https://github.com/ckeditor/ckeditor-dev/blob/f1961b0a77228f30f3f4b0b1e98e82881859ef85/plugins/pastefromword/filter/default.js
**TinyMCE**: https://github.com/tinymce/tinymce/blob/06ee9aae2cbe765ce265e77771833b3d936e3920/js/tinymce/plugins/paste/classes/WordFilter.js

As seen by the sheer number of lines of code (and complex nested ifs), it's a hard problem. However, I'd really love to see Froala support paste from Word as well as TinyMCE and CKEditor do. Hopefully, the feature can be added to the roadmap once 2.0 ships.

**Comment by stefanneculai** [comment]
Hi Scott! The current Word support is acceptable for most of the users. We might create later on a separate plugin for advanced Word paste, but we can't promise anything about that.
