### ISSUE TITLE
Bug trying to resize picture when video is in place.

### ISSUE THREAD

**Issue by hajrice** [froala/wysiwyg-editor#614]
Hi

The editor seems to somehow break once there's a video/iframe code and pictures.

can't resize pictures

Any ideas ?

**Comment by stefanneculai** [comment]
Could you please make a JSFiddle for that? Also, are you using the latest version of the editor?

**Comment by stefanneculai** [comment]
We cannot replicate this. I am closing this until we received the steps to replicate it.
