### ISSUE TITLE
unordered list in a blockquote

### ISSUE THREAD

**Issue by connect-technologies** [froala/wysiwyg-editor#618]
Dear froala Team,

I tried to put an unordered list in a blockquote block.
But I only get a lot of blockquotes in a list.

any ideas how to do this?
thanks
christopher

**Comment by stefanneculai** [comment]
Hi Christopher! In the current version the editor is designed to include blockquote inside list. Considering how emails work, I believe it would be good to include list inside blockquote not otherwise. We'll discuss about that.

**Comment by stefanneculai** [comment]
Done in v2.0.0-rc.1.
