### ISSUE TITLE
Inline styles and CSS classes have been removed after pasted

### ISSUE THREAD

**Issue by mackwan84** [froala/wysiwyg-editor#619]
Here is the my configuration of the editor: 
```
{
    inlineMode: false,
    minHeight: '250px',
    language: 'zh_cn',
    allowedAttrs: ['title', 'href', 'alt', 'src', 'style', 'class'],
    defaultVideoAlignment: 'left',
    textNearVideo: false,
    defaultImageAlignment: 'left',
    defaultImageWidth: 720,
    textNearImage: false,
    imageButtons: ['display', 'align', 'linkImage', 'replaceImage']
}
```

Here is the html I would like to copy

```html
<p class="apple" style="color: red">Apple</p>
<p class="boy" style="color: blue">Boy</p>
```

**Comment by stefanneculai** [comment]
Inline styles, classes and ids are removed when pasting. Version 2.0 will have more control for that. See https://github.com/froala/wysiwyg-editor/issues/552#issuecomment-106766541 for more details.

**Comment by ibtisamniche-vteams** [comment]
Hi!
Our froala editor version is greater than 2 and when I copy rich text that contains bold sentences from google docs to froala the text is not preserved and it shows the bold text in same format instead of showing into bold.
Can you tell why is that happening and what's the solution.

**Comment by stefanneculai** [comment]
@ibtisamniche-vteams please see https://github.com/froala/wysiwyg-editor/issues/2545#issuecomment-363143440.
