### ISSUE TITLE
Element (div, a, other tags) duplicates when hitting return / enter within text that is not in a paragraph.

### ISSUE THREAD

**Issue by Smashr** [froala/wysiwyg-editor#620]
When the cursor is placed in a block of text and return/enter is pressed to divide the block into two blocks/paragraphs the containing element (div, a, p, etc) duplicates with all its classes and other attributes.

Although this is expected behaviour when the text is wrapped in `<p>` tags. If I were to move my cursor anywhere in the text and hit return, it should altomatically create two `<p>` tags.

So this line:

    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum consequat, orci ac laoreet cursus, dolor sem luctus lorem, eget consequat magna felis a magna.</p>

changes to :

    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
    <p>Vestibulum consequat, orci ac laoreet cursus, dolor sem luctus lorem, eget consequat magna felis a magna.</p>

but if there is any other element like an anchor tag or a div, this duplication should not occur.

Curretly this line:

    <div class="some classes here etc" contenteditable="true" otherattributes="etc">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum consequat, orci ac laoreet cursus, dolor sem luctus lorem, eget consequat magna felis a magna.</div>

changes to :

    <div class="some classes here etc" contenteditable="true" otherattributes="etc">Lorem ipsum dolor sit amet, consectetur adipiscing elit.</div>
    <div class="some classes here etc" contenteditable="true" otherattributes="etc">Vestibulum consequat, orci ac laoreet cursus, dolor sem luctus lorem, eget consequat magna felis a magna.</div>

but should change to :

    <div class="some classes here etc" contenteditable="true" otherattributes="etc">
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
    <p>Vestibulum consequat, orci ac laoreet cursus, dolor sem luctus lorem, eget consequat magna felis a magna.</p>
    </div>

Similarly a link(anchor) tag:

    <a class="button" href="http://">Learn More</a>

Changes to:

    <a class="button" href="http://">Learn</a>
     <a class="button" href="http://">More</a>

resulting in two buttons.

I'm sure all tags behave in the same way. When only the paragraph tag should behave in this way. For all other tags, a paragraph tag should be wrapped around the text, and at the point where return/enter was pressed.

**Comment by stefanneculai** [comment]
The editor behaviour is the correct one. If you hit enter at the middle of a tag it should split the current tag in two. Only when you are at the end of a tag it should not be spliced.

**Comment by Smashr** [comment]
Is there a way to disable this behaviour in a way that the current tag is not spliced and instead the content is wrapped in a paragraph tag before it is spliced ?

**Comment by stefanneculai** [comment]
You'd have to override the method `$.Editable.prototype.handleEnter` and make it work the way you want.

**Comment by Smashr** [comment]
Great, Thank you for the help. I'll look into it. :)

**Comment by Smashr** [comment]
I personally think that this is great for list items and paragraphs. But for any other items, particularly divs and buttons (a tags) that are styled it does not work very well. Duplicates the buttons into two, duplicates content boxes etc.

A user's intention is to split the text block only (add a paragraph / split the block into paragraphs) by hitting return. For now I'll just wrap 'p' tags around any text nodes not directly within 'p' tags before the editor is initialised on the content.

**Comment by icandothat2** [comment]
@Smashr  I figured out how to get what you're looking for I think. I was having a similar issue where I was adding some bootstrap styled rows/cols to a contenteditable div. When I added the <div class='row'> it got set to contenteditable=true automatically. Setting it to false after it's added to the DOM stopped the problem of splitting the col divs on user hitting "enter".
