### ISSUE TITLE
Editing content within anchor 'a' tag

### ISSUE THREAD

**Issue by Smashr** [froala/wysiwyg-editor#621]
It seems to be almost impossible for a user to edit content within links / 'a' tags.

This is best explained by a video. http://vid.me/8cWv

Video shows several attempts of a user trying to edit text in a button (which is a link 'a' tag). Attempting to change "More Info" to "Buy Now".

I believe there are a few different issues here. It is very obvious when links are styled, and less obvious when links are plain text, but even with plain text links this happens. No arrow keys or return / enter key was used when recording the video.

Issue 1: Link pop-up makes it impossible to place cursor within link.

Issue 2: Link text editing within the link pop-up does not really work.

Issue 3: When text is selected within link and user starts to type, only the first character is left inside the link tag and the rest of the string is typed outside.

Issue 4: Normal Froala toolbar usually does not open, so formatting cannot be added / changed within the link tag.

It would also be nice if there was an option to disable automatic link pop-up when a link is clicked. A normal toolbar should appear with the link pop-up showing only when the link icon is clicked within the normal toolbar. This would allow for easy formatting and content editing within the link tag.

**Comment by stefanneculai** [comment]
That is a limitation in version 1.*. Version 2 will fix that.

**Comment by Smashr** [comment]
awesome ... looking forward to 2.0.0 :)

**Comment by stefanneculai** [comment]
Should be fixed on master.
