### ISSUE TITLE
Scripts get removed from Froala source mode if there is no other content in the froala

### ISSUE THREAD

**Issue by gulasensei** [froala/wysiwyg-editor#623]
*Note*: If there is any non-script content in the Froala editor the scripts do not get removed
The issue is only reproducible with `<script>` tag and with its src attribute, code without the src do not get removed e.g.: `<script>alert("!")</script>`

*Steps to reproduce*:

1. Delete every content from Froala
2. Switch to Froala’s source mode 
3. Insert the following script in it:
`<script src="//code.jquery.com/jquery-1.11.2.min.js"></script>`
`<script src="//code.jquery.com/jquery-migrate-1.2.1.min.js"></script>`
4. Switch to Edit mode
5. Switch to Source mode again 

*Actual results*:
5. Script get removed

*Expected results*:
5. Froala should contain the previously inserted script

**Comment by ravi3592** [comment]
I am also facing the same issue

**Comment by stefanneculai** [comment]
Should be fixed on master.
