### ISSUE TITLE
No additional content can be inserted into Froala editor after the user started with inserting a video

### ISSUE THREAD

**Issue by gulasensei** [froala/wysiwyg-editor#624]
*Note*:The issue has a workaround: Type text into the Froala before insert a video
The issue is reproducible both with youtube and vimeo videos
The issue is not reproducible on Firefox and IE11
The issue is reproducible on Chrome, Safari (Tested with MAC and iPhone 5S), Android browser
Under IE10 inserting image and video is possible and only actual step 3 is reproducible

*Steps to reproduce*:

1. Delete every content from Froala
2. Insert a video into Froala (e.g.: https://www.youtube.com/watch?v=FgBl7I6bIV8)
3. Try to type into Froala
4. Try to insert a video into Froala
5. Try to insert an image into Frola

*Actual results*:
3-4-5: No additional content can be inserted into the Froala, after the user started with inserting a video

*Expected results*:
3-4-5: Adding additional content should be possible even if the user starts with adding a video at first

**Comment by stefanneculai** [comment]
We're aware of this. Same thing can be reproduces with tables and this behaviour will be improved in version 2.0.

**Comment by stefanneculai** [comment]
Should be fixed on master.
