### ISSUE TITLE
Bold, italic and underlined format options cannot be selected at the same time if Froala text area is empty

### ISSUE THREAD

**Issue by Mark5217** [froala/wysiwyg-editor#625]
Note: If text is present in the text area the three formats can be selected at the same time

Steps to reproduce:
1. Click on the bold format while Froala text area is empty
2. Click italic option
3. Click underlined option
4. Clicked striked through format option

Actual result:
4. The the three format option cannot be slected at the same time if there is no text in Froala’s text area

Expected results:
4. All three options should be selectable at the same time even if no text is peresent in the text area

**Comment by stefanneculai** [comment]
Should be fixed on master.
