### ISSUE TITLE
It is difficult to paste data into froala editor on mobile devices if froala editor area is empty

### ISSUE THREAD

**Issue by gulasensei** [froala/wysiwyg-editor#626]
*Note:*
The issue  is reproduced on mobile devices only. IPhone 6, Samsung Galaxy S5, Samsung Galaxy S3 mini are used.

*Steps to reproduce*:
Try to copy-paste any text into the Froala editor with devices

*Actual results*:
The paste option appears sometimes and then disappears so that user is not able to paste a copied text.

*Expected results*:
The paste option should be available for the user if to release the froala editor area as soon as paste option appears.

**Comment by stefanneculai** [comment]
Should be fixed on master.
