### ISSUE TITLE
Froala image URL is inserted into Froala's textfield 

### ISSUE THREAD

**Issue by Mark5217** [froala/wysiwyg-editor#627]
Steps to reproduce:
1. Insert an image
2. Define a URL for the image (http://xyz.com)
3. Click Ok
4. Click the image container that contains the image (click next to the image)
5. Click Ok on the link popup

Actual result:
5. The image has been deleted and the image’s url is inserted

Expected results:
5. The images defined URL should not be inserted and the image should not be removed

**Comment by stefanneculai** [comment]
Could you please let me know what browser are you using?

**Comment by Mark5217** [comment]
I'm using Chrome. 
Other browsers do not seem to be affected.
