### ISSUE TITLE
Insert video pop-up in Froala get disappeared after tapping on one of its field

### ISSUE THREAD

**Issue by gulasensei** [froala/wysiwyg-editor#628]
*Note*: The issue can be reproduced only if the focus is not in the Froala editor before step 1 
The issue is reproducible with Chrome on Nexus 7 and Android browser (tested with Samsung Galaxy S4)
Safari is not affected
Insert Image-Enter URL option of Froala is also affected

*Steps to reproduce*:
1. Tap on the Insert video option of the Froala editor
2. Tap on one of the fields of the Insert video pop-up

*Actual results*:
2. The insert video pop-up lose the focus and get disappeared

*Expected results*:
2. The pop-up should be displayed permanently, with an active cursor in the tapped field

**Comment by stefanneculai** [comment]
Should be fixed on master.
