### ISSUE TITLE
<Style> tag disappear after switching between RTE view modes

### ISSUE THREAD

**Issue by gulasensei** [froala/wysiwyg-editor#629]
*Steps to reproduce*:
1. Insert the following code into the Froala editor in source mode:
`<style> mark {color: red;} </style>
<mark>Something</mark>`
2. Switch back to edit mode
3. Switch back to source mode

*Actual results*:
3. `<style> mark {color: red;} </style>` get disappeared

*Expected results*:
3. `<style> mark {color: red;} </style>` should be displayed

**Comment by stefanneculai** [comment]
By default the `style` tag is not allowed in the editor. You should enable it: https://www.froala.com/wysiwyg-editor/docs/options#allowStyle.
