### ISSUE TITLE
User is not able to specify title and link for just uploaded image on mobil

### ISSUE THREAD

**Issue by gulasensei** [froala/wysiwyg-editor#630]
*Note*: Use Samsung Galaxy S3 mini, S5.

*Step to reproduce*:
1. Click on [Insert image] item on toolbar.
2. Drop the image.
3. Try to specify title, link for the image.

*Expected Results*: 
3. User should be able to specify title and link for just uploaded image.

*Actual Results*: 
3. User cannot add a link or title to the image because popup disappears if to click into the title or link address field and virtual keyboard appears.

**Comment by stefanneculai** [comment]
Same with #628.
