### ISSUE TITLE
Video is impossible to select if inserted via source mode

### ISSUE THREAD

**Issue by Mark5217** [froala/wysiwyg-editor#631]
1. Insert the following video via source mode:
`<object width="640" height="390">
 <param name="movie"         value="https://www.youtube.com/v/M7lc1UVf-VE?version=3&autoplay=1"></param>
 <param name="allowScriptAccess" value="always"></param>
 <embed src="https://www.youtube.com/v/M7lc1UVf-VE?version=3&autoplay=0"
        type="application/x-shockwave-flash"
        allowscriptaccess="always"
        width="640" height="390"></embed>
</object>`
2. Turn off source mode
3. Try to select the video

Actual result: Embed video is not selectable. Video can be played and if inserted with an Iframe it is selectable.

Expected result: The video should be selectable

**Comment by mrdougwright** [comment]
Having the same issue. Reverting to embed the video through the WIZYWIG until resolved.

**Comment by stefanneculai** [comment]
The editor recognises iframes and uses those as videos. By default, Youtube is embedding `iframe` not `object`.
