### ISSUE TITLE
HTML entities being unencoded

### ISSUE THREAD

**Issue by okohll** [froala/wysiwyg-editor#632]
1) switch to code view
2) enter some HTML entities, such as

`&nbsp; &bull; &ast; &lt;`

3) switch to WYSIWYG view, then back to code view again

Some of the HTML entities will be replaced by actual characters, whilst others remain entities. For the above examples, `&nbsp; `and `&lt;` remain as entities whereas `&bull;` and `&ast;` get transformed into a bullet and asterisk respectively.

Ideally, any entities that you manually enter will be left as they are and not transformed.

**Comment by stefanneculai** [comment]
There is a plugin for entities (https://github.com/froala/wysiwyg-editor/blob/master/js/plugins/entities.min.js) and you should use that one if you want to have the bullet/asterisk chars as html entities.

**Comment by okohll** [comment]
Excellent, thanks for the quick response.

The entities plugin isn't mentioned on https://www.froala.com/wysiwyg-editor/docs/plugins (perhaps because it's not a plugin with a button?), FYI that's why I missed it.

**Comment by stefanneculai** [comment]
Indeed it is missed. We'll include it shortly.
