### ISSUE TITLE
CSS style of enclosing HTML element not copied when you press enter.

### ISSUE THREAD

**Issue by mattj256** [froala/wysiwyg-editor#633]
Step 1. Go to HTML source mode, delete everything and replace with this:
```
<div style="background-color: #888888;"> 
Test
<br/>
Test2 
<br/>
Test3
</div>
```
![b](https://cloud.githubusercontent.com/assets/5423966/8919482/aa65455c-348d-11e5-993c-c940538e8a66.png)

Step 2. Go back to normal editing mode.
Step 3. Position cursor after "test2".
Step 4. Press enter/return. (looks correct) 
Step 5. Press enter/return. (There's a white background.  I expected gray background.)

![a](https://cloud.githubusercontent.com/assets/5423966/8919466/8b90acf2-348d-11e5-99dc-fa91932914e5.png)

This is the resulting HTML:
```
<div style="background-color: #888888;">  Test <br>
   Test2  </div>

<p><br>
</p>

<div style="background-color: #888888;"><br>
   Test3 </div>
```

I tried experimenting with turning paragraphy on and off.  The behavior changes a bit but there's a bug in both versions.  If paragraphy is turned off, the background should certainly be gray.  With paragraphy on I still think the background should be gray but that's more open to interpretation.

**Comment by stefanneculai** [comment]
That is the correct behaviour. When you hit enter for the first time, it will break the initial `div` into two `div` elements. The 2nd enter is made at the beginning of a `div` and it should add an empty line above it.
