### ISSUE TITLE
Theme classes not applied until after click on initOnClick: true

### ISSUE THREAD

**Issue by codymorrison** [froala/wysiwyg-editor#634]
This may be intended behavior, but as it currently stands, theme classes are not applied until after initialization if you have ```initOnClick: true``` set. This may be problematic if you rely on your theme for specific styles.

Before init: 

```html
<form>
  <div class="froala-box">
    <div class="froala-editor">
```

After init:
```html
<form>
  <div class="froala-box custom-theme">
    <div class="froala-editor custom-theme">
```

**Comment by stefanneculai** [comment]
I assume you're relying on style for the editor box?
