### ISSUE TITLE
Focus cursor will pair the beginning

### ISSUE THREAD

**Issue by sudeste** [froala/wysiwyg-editor#635]
Froala  1.2.8
inlineMode :  true,

I created a custom button, which opens a modal window, something like the code below.

But when for example I click the modal window or in any element, Froala editor loses focus. Thus, by adding the image chosen in modal, the image is added at the beginning of the content block, not in the course of position location.

```
myButton: {
    title: 'Open modal',
    icon: {
        type: 'font',
        value: 'fa fa-cloud'
    },
    callback: function () {
        
        var focused = $(this.$box);                
        open_my_modal();
        
        var href = 'pages/modal?edit='+focused.attr('id');
        $('#my-modal').find('.content').load(href);
        
    },
    refresh: function () {}
}
```

I do not know who can understand. The case is that when the cursor loses focus, I can not go back to the courses in the exact position he was in. The external content is added at the beginning of the content.
Switch for example do this:

```
var focused  = $('#element_id');
modal.find(':button').click(function(event) {
              
    var script = $('#thirdparty').val();
    focused.editable('setHTML', script, true); // This is added at the beginning of the content, but i want to be added is that where the cursor was focused at the opening of  Froala WYSIWYG HTML Editor.
});
```
I've tried some methods like below, but not work.

```
focused.editable('showByCoordinates', 69, 581.1833343505859);
```

**Comment by stefanneculai** [comment]
You have to store the selection using `saveSelectionByMarkers` when you open the modal and then restore the selection using `restoreSelectionByMarkers` before inserting the HTML. Also, you should probably use `insertHTML` instead of `setHTML`.

**Comment by sudeste** [comment]
Sorry, This does not work or I did not understand the purpose.

I made a new test, and realized that if you click any area of the modal Froala Editor loses focus and gone. But if I click again in the content area, as with modal open it loads the external content at the given location. (but I have to do two tasks, which is bad.)

I want to add content where the position of the course was started in the click of the mouse.

By using for example the code:
```
var focused = $(this.$box);
var markers = focused.editable('saveSelectionByMarkers');
```
It returns something like below. There's nothing to do with it.
```
<div id="edit-25vctfh1vl2" class="editable froala-box">
```

When I try something like this (within the callback button code.), undefined return.
```
this.saveSelectionByMarkers() // return undefined.
```
When I try something like this, it returns an error. I have many editors on a page.
```
$('.editable').editable('saveSelectionByMarkers'); // error TypeError: s is undefined
```

**Comment by sudeste** [comment]
sorry,
now I understand how it works.
Thanks.

**Comment by intellisense** [comment]
@stefanneculai Can you provide an example? Below code doesn't work for me, the `$('.add-media-editor').trigger('click');` invokes the modal, but when I close the modal the editor does not have any focus.

```
$.FroalaEditor.DefineIcon('add_media', {NAME: 'camera'});
    $.FroalaEditor.RegisterCommand('add_media', {
      title: 'Add Media',
      focus: true,
      undo: false,
      refreshAfterCallback: false,
      callback: function () {
        this.selection.save();
        $('.add-media-editor').trigger('click');
        this.selection.restore();
      }
    });
```

**Comment by intellisense** [comment]
Nevermind figured it out. The `selection.restore` should happen just before inserting content e.g.

```
$('#editor').froalaEditor('selection.restore');
$('#editor').froalaEditor('link.insert', 'https://google.com', 'Google', {'target': '_blank'});
```

Thanks!

**Comment by jwhitmarsh** [comment]
Can someone update this for V2 please? How do we get the cursor position now?

**Comment by stefanneculai** [comment]
@jwhitmarsh You can save the current selection using `selection.save` and restore it with `selection.restore`. https://www.froala.com/wysiwyg-editor/examples/selection

**Comment by jwhitmarsh** [comment]
@stefanneculai thank you so much!
