### ISSUE TITLE
Inserting Merge Fields / Custom Dropdown to insert text

### ISSUE THREAD

**Issue by enkodellc** [froala/wysiwyg-editor#636]
I am just starting with Froala wysiwyg through angular-froala and it seems pretty powerful. My goal is to have a custom dropdown to insert merge fields / predefined tokens. I would like to use a key value pair, display a key and inject the value into the editor.

I was able to create a custom dropdown and insert static text into my editor. Is there anyone who can help me pass these key / pairs into the control to make it a dynamic dropdownlist? Maybe a new plugin is needed to do this?

**Comment by enkodellc** [comment]
@stefanneculai?  I started to build a plugin but if you have any insight on this it would be greatly appreciated.  It would be nice to view some of the plugins code before minification for more examples. 

Any tips on how to pass data to the directive / froala to be used in a plugin?

**Comment by stefanneculai** [comment]
I don't really understand what exactly you're trying to achieve. Could you offer more details?

The unminified plugins are available under the Advanced/OEM license.

**Comment by enkodellc** [comment]
I want to be able to have a dropdown that when they select one of the items in the dropdown it injects text at the cursor. I have a predefined list of merge fields that users can insert the document they are creating.  So if they select "Company" merge field from the custom dropdown my code will insert "[[Company]]" for the user in the textarea at the cursor position. Later in my code I will replace the "[[Company]]" with another field.

The trick is the merge fields are different for each user as they can create their own merge fields so I want to be able to send the list of merge fields once the editor is created. Thanks.

**Comment by enkodellc** [comment]
If I buy the Advanced / OEM license and I cannot get the functionality to work and will not use the control can I get a refund? I see you offer 30% discount to people who create plugins but it seems by not supplying examples you are inhibiting development of new plugins.

**Comment by stefanneculai** [comment]
You could create the list object based on the use that is logged in and then just pass it to the custom dropdown. We've had users doing the same thing. Have your read https://www.froala.com/wysiwyg-editor/docs/examples/custom-dropdown?

We can definitely help you via email as part of the support included in the Advanced/OEM license. The license fee is one time payment and it is not refundable. Indeed, we offer a 30% discount, but only to new  plugins for frameworks or major contributions to the existing ones.

**Comment by enkodellc** [comment]
Thanks I am not the greatest JS developer. I just refactored your font-size plugin and injected the js code within my controller then passed my merge fields as a scope and it worked... I will test it out a bit more now that I can do what I want and see if I can get my team on board with this versus textAngular.

**Comment by enkodellc** [comment]
Posting my code for others:  
*Note $scope.tokens is angular and represents a string array
```
		!function (a) {
			a.Editable.prototype.refreshMerge = function () {},
				a.Editable.commands = a.extend(a.Editable.commands, {
					merge: {
						title: "Merge Fields",
						icon: "fa fa-tasks",
						refreshOnShow: a.Editable.prototype.refreshMerge,
						tokens: $scope.tokens,
						undo: !0,
						callback: function (a, b) {
							this.insertHTML('[[' + b + ']]');
						},
						callbackWithoutSelection: function (a, b) {
							this.insertHTML('[[' + b + ']]');
						}
					}
				}), a.Editable.prototype.command_dispatcher = a.extend(a.Editable.prototype.command_dispatcher, {
				merge: function (a) {
					var b = this.buildDropdownMerge(a);
					var c = this.buildDropdownButton(a, b);
					return c
				}
			}), a.Editable.prototype.buildDropdownMerge = function (a) {
				var tokenList = '';
				for (var c = 0; c < a.tokens.length; c++) {
					tokenList += '<li data-cmd="' + a.cmd + '" data-val="' + a.tokens[c] + '"><a href="#"><span>' + a.tokens[c] + '</span></a></li>';
				}
				return '<ul class="fr-dropdown-menu">' + tokenList + '</ul>';
			}
		}(jQuery);
```

**Comment by stefanneculai** [comment]
:+1:
