### ISSUE TITLE
'sep' when inlineMode=true creates an hr tag

### ISSUE THREAD

**Issue by enkodellc** [froala/wysiwyg-editor#637]
When utilizing a custom toolbar when inlineMode=true and using 'sep' creates an hr tag. This is inconsistent as when inlineMode=false the 'sep' creates a vertical separator. 

You can view my test case http://mean.enkode.io 

The top editor has options:
```
		$scope.options = {
			placeholder : 'My Placeholder',
			inlineMode: true,
			initOnClick: true,
			alwaysVisible: true,
			plainPaste: true,
			spellcheck: true,
			buttons: ['merge', 'bold', 'sep', 'italic', 'underline', 'strikeThrough', 'insertUnorderedList', 'insertOrderedList','redo', 'undo', 'removeFormat',
				'subscript', 'superscript', 'fontSize', 'createLink', 'outdent', 'indent', 'formatBlock'
			]
		};
```
The bottom editor has options
```
		$scope.options2 = {
			placeholder : 'My Placeholder',
			inlineMode: false,
			plainPaste: true,
			spellcheck: true,
			buttons: ['merge', 'bold', 'sep', 'italic', 'underline', 'strikeThrough', 'insertUnorderedList', 'insertOrderedList','redo', 'undo', 'removeFormat',
				'subscript', 'superscript', 'fontSize', 'createLink', 'outdent', 'indent', 'formatBlock'
			]
		};
```

**Comment by stefanneculai** [comment]
That is the intention. In inline mode, sep creates a new line. That is explained in docs as well: https://www.froala.com/wysiwyg-editor/docs/options#buttons

**Comment by enkodellc** [comment]
I will write some css to overwrite the hr then.  Just my opinion but this inconsistent behavior seems counter intuitive. Would be cleaner if there was a predefined button for vertical separator and a different one for new line / hr. Thanks for the response.
