### ISSUE TITLE
Setting FormatTags options does not affect FormatBlock dropdown.

### ISSUE THREAD

**Issue by enkodellc** [froala/wysiwyg-editor#638]
I am having some difficulty setting the formatTags.  I do not see any changes in the FormatBlock dropdown. Am I missing something? My goal is to remove the h1, h2... tags.

Example here: http://mean.enkode.io/ 

```
		$scope.options = {
			placeholder : 'My Placeholder',
			inlineMode: true,
			initOnClick: true,
			alwaysVisible: true,
			plainPaste: true,
			spellcheck: true,
			formatTags: ['p','pre','blockquote'],
			buttons: ['merge', 'bold', 'sep', 'italic', 'underline', 'strikeThrough', 'insertUnorderedList', 'insertOrderedList','redo', 'undo', 'removeFormat',
				'subscript', 'superscript', 'fontSize', 'createLink', 'outdent', 'indent', 'formatBlock'
			]
		};
```
*Note I am using Angular-Froala

**Comment by stefanneculai** [comment]
What you should use is the [blockTags option](https://github.com/froala/wysiwyg-editor/blob/master/examples/block_tags.html#L56). The `formatTags` option is used to specify what tags you want to be formatted inside the HTML view.

**Comment by enkodellc** [comment]
Great thanks, I knew I must have been missing something. Love the control so far.
