### ISSUE TITLE
Missing undo-Event

### ISSUE THREAD

**Issue by Chaaph** [froala/wysiwyg-editor#639]
Hi,

It seems to me, that the undo-Event isn't triggered or at least its listener aren't called. 
Instead only the contentChanged-listener are called after the undo
When you trigger the event manually it works just fine.

https://jsfiddle.net/1151vb68/10/ (use the short-cut for undo - too lazy for css)

Did i make any mistake or does this just not work?

Greets
Chaaph

**Comment by stefanneculai** [comment]
It's a mistake in our documentation. The `undo` event is now `afterUndo` and there is a similar event called `beforeUndo`.

**Comment by spectralsun** [comment]
Is this event in the editor? I can't find documentation on it anywhere.

**Comment by jwhitmarsh** [comment]
Is this answer still accurate?

**Comment by stefanneculai** [comment]
The undo event can be take using the `commands.after` event in V2.
