### ISSUE TITLE
toolbarFixed with fixed jquery mobile header?

### ISSUE THREAD

**Issue by connect-technologies** [froala/wysiwyg-editor#640]
Hi,

im building my new homepage with jquery mobile and I have a fixed header there.
I tried to fix your toolbar with:

inline-mode:false,
toolbarFixed:false

but it still scrolls.
Any ideas?

thanks
christopher

**Comment by stefanneculai** [comment]
With `toolbarFixed` set to `false`, the toolbar will remain at the top of the screen when you scroll. There is also an example on our website for that: https://www.froala.com/wysiwyg-editor/docs/examples/fluid-toolbar.

However, there might be something from jquery mobile that prevents it from working fine. If you can provide a page where you have this problem we can definitely look into it.

**Comment by connect-technologies** [comment]
Hi Stefan,
could you please check this jsfiddle:
http://jsfiddle.net/jh7dwcjv/7/
Perhaps you can fix it.
thanks

**Comment by stefanneculai** [comment]
I don't see any problem when I open only the example (https://jsfiddle.net/jh7dwcjv/7/embedded/result/). The toolbar is staying at the top of the page.

**Comment by connect-technologies** [comment]
Hi Stefan,
I made a testpage for the still open problem:
http://froala.connect-technologies.de/
please try..
thanks
christopher

**Comment by stefanneculai** [comment]
That's because parent tags have the CSS property `overflow-x: hidden`. We're using the CSS property `position: sticky` and it works fine only when parents don't have overflow hidden.

**Comment by connect-technologies** [comment]
Yeah!

that is nice! Now it works.
ha, so easy ... :)

thanks
