### ISSUE TITLE
Closing the link editor will move the cursor to the beginning of the content when using Firefox

### ISSUE THREAD

**Issue by nicklasmeramedia** [froala/wysiwyg-editor#641]
When using **Firefox** and closing the link editor (aborting the edit) the cursor will move to the start of the the editor content instead of selecting the link text (as done in Chrome/IE). The cursor may also move to the end of the content depending on the content that exists in the editor.

**Firefox:**
![1](https://cloud.githubusercontent.com/assets/2184273/9114617/086ca472-3c5b-11e5-852e-42c16d698802.JPG)
![2](https://cloud.githubusercontent.com/assets/2184273/9114618/0a2c0974-3c5b-11e5-9cb5-4a242eb75447.JPG)

**Chrome/Internet Explorer:**
![3](https://cloud.githubusercontent.com/assets/2184273/9114676/5a438ec8-3c5b-11e5-9c5f-38b4c7ee8edd.JPG)
![4](https://cloud.githubusercontent.com/assets/2184273/9114677/5bbb8d82-3c5b-11e5-83ce-c6afd7993b3a.JPG)

**Comment by stefanneculai** [comment]
Should be fixed on master.
