### ISSUE TITLE
How I can upload images on Imgur

### ISSUE THREAD

**Issue by MajidCS** [froala/wysiwyg-editor#642]
Hi,

Is froala supports upload on imgur.com ?

**Comment by stefanneculai** [comment]
There is no default option to upload to Imgur. However, you could intercept the image upload (https://www.froala.com/wysiwyg-editor/docs/events#beforeImageUpload) and then do the upload to Imgur on your own.

**Comment by Maxhou00** [comment]
For those who will found this issue. I have created a plugin for uploading image on imgur 
https://github.com/Maxhou00/froala-imgur
