### ISSUE TITLE
Upload multiple images

### ISSUE THREAD

**Issue by whoknowwhat** [froala/wysiwyg-editor#643]
Can I upload multiple images at once with default image insert feature?
If not, do you have a scheduled update for this feature?

Thank you.

**Comment by stefanneculai** [comment]
Only one image can be uploaded at a time. At this moment, uploading multiple images is not on our roadmap.

**Comment by ltullman** [comment]
We have just had a customer request for this.  Has your roadmap changed since August as far as adding this feature?

**Comment by sanjay-parmar-tatva** [comment]
Hi All, I have solved multiple image upload issue manually.

please find attached image.min.js and replace it with floara editor image.min.js.

it's work fine for me. And let me know if you have any issue so ill update it base on your requirement.
Please change image.min.txt to image.min.js.

[image.min.txt](https://github.com/froala/wysiwyg-editor/files/961527/image.min.txt)

Thanks.
Sanjay Parmar

**Comment by GDanielRG** [comment]
@sanjay-parmar-tatva  can you contact me for having that js? danyrod94@gmail.com

**Comment by heymexa** [comment]
For resolve this problem I have developed the plugin - [Images Multi Upload](https://github.com/heymexa/froala-images-multi-upload)

The plugin uses options from *image.js* plugin and allows to send many images to the server.

Enjoy!
