### ISSUE TITLE
JQuery modal, cannot focus on input fields.

### ISSUE THREAD

**Issue by ricanontherun** [froala/wysiwyg-editor#644]
Bootstrap modals presented a similar issue, and a fix was released. Whenever Froala is contained in a JQuery modal, form input fields do not receive focus when clicked.

**Comment by stefanneculai** [comment]
Could you please make a jsFiddle?

**Comment by stefanneculai** [comment]
This problem is no longer present in V2. We have also added an example for it: https://github.com/froala/wysiwyg-editor/blob/master/html/jquery_ui/modal.html.
