### ISSUE TITLE
Setting pasteImage to false and browser console error when pasting

### ISSUE THREAD

**Issue by eddcvjm** [froala/wysiwyg-editor#645]
On Froala 1.2.8:

Setting pasteImage: false to disable pasting image from clipboard results in a browser console error when pasting on certain conditions.

Steps to reproduce:

1º In an external editor create a text followed by an image and then followed by text, like the following example:

Text before image
![image](https://cloud.githubusercontent.com/assets/13676411/9203249/eb6fabb6-404d-11e5-8ace-002694a52370.png)
Text after image

2º Copy all
3º Paste on froala editor on a web application

Expected result:
 - Only the text is pasted
 - No errors on browser

Actual result:
 - Only text is pasted
 - The following browser console error is returned:
SEC7111: HTTPS security is compromised by file:///C:/Users/VLADIM~1/AppData/Local/Temp/msohtmlclip1/01/clip_image001.png

Thanks

**Comment by stefanneculai** [comment]
What browser are you using? Could you please provide a jsFiddle for it?

**Comment by eddcvjm** [comment]
It's possible to reproduce the issue on the froala site: https://www.froala.com/wysiwyg-editor/docs/examples

The issue happens on chrome (Versão 44.0.2403.155 m) and on IE11

In the froala site (https://www.froala.com/wysiwyg-editor/docs/examples) only the inlineMode is set, so the value for pasteImage setting is the default -> true 

Steps to reproduce

1º In an external editor create a text followed by an image and then followed by text, like the following example:

Text before image
![image](https://cloud.githubusercontent.com/assets/13676411/9360351/a830dbcc-468d-11e5-80df-571403bafd76.png)
Text after image

2º Copy all
3º Paste on froala editor on a web application

Actual result
 - Only text is pasted (even with the pastImage as true
 - The following browser console error is returned
![image](https://cloud.githubusercontent.com/assets/13676411/9360314/73953656-468d-11e5-9d43-6e57eb3add5f.png)


Additional note: 
If we try to copy and paste only the image, everything works ok.

Thanks

**Comment by stefanneculai** [comment]
When a HTML page is opened in the browser without a server, then images might get copied from their local path. This results in an error when HTTPS is being used. The way browser handles coping only one image and image with text is different. 

Last commit adds in the option `pasteAllowLocalImages` which is disabled by default. That will prevent pasting in local content.
