### ISSUE TITLE
When the text is centre aligned, the indent less icon does not work as expected

### ISSUE THREAD

**Issue by eddcvjm** [froala/wysiwyg-editor#646]
The following scenarios were tested on the froala site: https://www.froala.com/wysiwyg-editor/docs/examples

Scenario 1

 - Type a text
 - From the Alignment dropdown, click Align Centre
 - Click the Indent More icon

   Expected result
    - The text is centered and then an indent is added

   The corresponding final HTML would look like the following:
      
![image](https://cloud.githubusercontent.com/assets/13676411/9228966/d52dbba2-4112-11e5-82b5-ad5d268008b5.png)

      Actual result
      - As expected -> No problems

Scenario 2

 - Type a text
 - From the Alignment dropdown, click Align Centre
 - Click the Indent More icon
 - Click the Indent More icon a second time

   Expected result
    - The text is centered and then an indent is added (twice the value in scenario 1)

   The corresponding final HTML would look like the following:
        
![image](https://cloud.githubusercontent.com/assets/13676411/9228984/e4d59f20-4112-11e5-84f2-0472a506cdb4.png)

       Actual result
       - As expected -> No problems

Scenario 3

 - Type a text
 - From the Alignment dropdown, click Align Centre
 - Click the Indent More icon
 - Click the Indent More icon a second time
 - Click the Indent Less icon

   Expected result
    - The text is centered and then an indent is added (twice the value in scenario 1) and then removed one indentation when Indent Less icon is clicked

   The corresponding final HTML would look like the following:
       
![image](https://cloud.githubusercontent.com/assets/13676411/9228996/f470b2a8-4112-11e5-8bcf-39d406964481.png)

      Actual result
      - As expected -> No problems

Scenario 4

 - Type a text
 - From the Alignment dropdown, click Align Centre
 - Click the Indent More icon
 - Click the Indent More icon a second time
 - Click the Indent Less icon
 - Click the Indent Less icon a second time

   Expected result
    - The text is centered and then an indent is added (twice the value in scenario 1) and then removed the indentation (also twice)

   The corresponding final HTML would look like the following:
      <p style="text-align: center;">Example text</p>

      Actual result
      - The center alignment is also removed

   The corresponding final HTML looks like the following:
       
![image](https://cloud.githubusercontent.com/assets/13676411/9229005/014520b8-4113-11e5-837b-cda2cab0ffed.png)

Conclusion:
 - When no indentation exists, if we click on Indent Less icon, the alignment style is also removed

**Comment by stefanneculai** [comment]
Should be fixed on master.
