### ISSUE TITLE
hidePopups does not hide a toolbar fully

### ISSUE THREAD

**Issue by o4u** [froala/wysiwyg-editor#647]
I experience an issue in v1.2.8.
Text editor in inline mode. alwaysVisible is false.
When hidePopups is called in the code it does not hide the arrow and a part of a left border of a toolbar. It does not depend which toolbar is: a text one or an image one.
```javascript
$('selector').editable('hidePopups');
```

Will you fix this in a new version 2.0 (maybe it does not exist there already), or you will still support v1.x.x and deploy fixes for it?

Thank you.

**Comment by stefanneculai** [comment]
You should also call the [hide](https://www.froala.com/wysiwyg-editor/docs/methods#hide) method if you want to hide everything.

**Comment by o4u** [comment]
Ok, thank you.
Maybe you would tell me if I need to call anything else when I clear a selection. I expect that call of a 'clearSelection' method will clear a selection from image too.
So, I selected an image, then clicked on the custom button in the image toolbar where function in a callback executes:
```javascript
$('selector').editable('clearSelection');
```
But the image is still selected (there is still a border around it).
Thank you for your time.

**Comment by stefanneculai** [comment]
It's not documented, but there is a method called `closeImageMode`.
