### ISSUE TITLE
Spacing issue when applying multiple styles

### ISSUE THREAD

**Issue by eddcvjm** [froala/wysiwyg-editor#648]
The following scenario was tested on the froala site: https://www.froala.com/wysiwyg-editor/docs/examples

Steps to reproduce:
1 - Type the following text on the editor
          "Test spacing italic bold"
2 - Apply style italic to the word "italic"
3 - Remove italic from the space between the word "italic" and the word "bold"
4 - Apply style bold to the word "bold"
5 - Press button "Show HTML"

        The resulting html is 
![image](https://cloud.githubusercontent.com/assets/13676411/9310168/09713ae6-4506-11e5-835c-c44761897169.png)

There is a space between the words "italic" and "bold" which is correct

6 - Press button "Show HTML" again
The space between the words "italic" and "bold" is removed, which is not correct

Thanks

**Comment by stefanneculai** [comment]
Should be fixed on master.
