### ISSUE TITLE
Format Block icon keeps styling previously applyed (font size/font family)

### ISSUE THREAD

**Issue by eddcvjm** [froala/wysiwyg-editor#649]
The following scenario was tested on the froala site: https://www.froala.com/wysiwyg-editor/docs/examples

Steps to reproduce:
1 - Enter text
2 - Apply font size and font family styles to the text
3 - Highlight the text, click the Format Block icon and select any of the "Heading" styles

Expected result:
 - The style applyed on step 2 is removed and the heading style is applyed

Actual result:
 - The size of the heading style is applyed but the font size and family remains the same applyed on step 2

Thanks

**Comment by stefanneculai** [comment]
This is the intended behaviour. When you change the block format it should not change the styles within the block.

**Comment by eddcvjm** [comment]
Considering as an example that an "heading" in the format block option has it's own styling defined, if we wanted to apply it while applying the heading (meaning removing the previous styling and applying the heading in it's total definition), is it possible to customize the "format block" button?
Something like:
 - remove format on block
 - format block
If yes, is it possible to provide an example on how to do so?

**Comment by stefanneculai** [comment]
If you want such a behaviour then you should override the `$.Editable.prototype.formatBlock` method to work the way you want. However, it is not something your users would probably expect to because all text editing apps work this way.
