### ISSUE TITLE
When using froala with angular the textarea cannot be resized

### ISSUE THREAD

**Issue by dudzik** [froala/wysiwyg-editor#650]
When I want to use froala or angular with textarea everything works fine so those two usages are correct: 
\<textarea ng-model="sometext"></textarea>
\<textarea froala="richTextOptions"></textarea>

When I want to use froala <b>with</b> angular, there is no possibility to resize it, so this does not work:
\<textarea froala="richTextOptions" ng-model="sometext"></textarea>

**Comment by stefanneculai** [comment]
The editor cannot be resized. You can set a height for it or doesn't set any height and the editor size will automatically grow.

**Comment by dennyjohnk** [comment]
@stefanneculai How to set minimum height ?

**Comment by stefanneculai** [comment]
https://www.froala.com/wysiwyg-editor/docs/options#heightMin
