### ISSUE TITLE
Indentation is lost when pasting

### ISSUE THREAD

**Issue by eddcvjm** [froala/wysiwyg-editor#652]
Hi,
The following scenario was tested on the froala site: https://www.froala.com/wysiwyg-editor/docs/examples

Steps to reproduce:

1. In froala editor type a text an apply "Indent More"
2. Select the text and copy it
3. Paste in the next line

Expected result:
 - The pasted text keeps the original indentation

Actual result:
 - The pasted text looses indentation

Thanks

**Comment by stefanneculai** [comment]
Duplicate of #612.

**Comment by stefanneculai** [comment]
Should be fixed on master.
