### ISSUE TITLE
Froala crashes

### ISSUE THREAD

**Issue by fru** [froala/wysiwyg-editor#653]
Hey,
when the html contains the following html comment: `<!--<link rel=\"stylesheet\" href=\"/cms/css/print.css\" type=\"text/css\" media=\"print\">-->` the browser crashes (Unresponsive until the process is killed). This is reproducible by pasting that comment into the html editor and switching back to the wysiwyg view. This is happening in both Browsers I tested it with, IE 11 and Chrome. This html is generated by a legacy system, so we unfortunately can't sanitize the html. We use the latest Version of the Froala Editor. This also reproducible in the Editor hosted on the Froala Website.

**Comment by YannLeBihan** [comment]
If it can be of any help : this also happens on Chrome for Mac, but not on Safari. Safari won't even retain the snippet when switching back to wysiwyg view, as if some sort of sanitizing was performed in the background.

**Comment by stefanneculai** [comment]
We're aware of this and it is fixed in v2.

**Comment by fru** [comment]
Be disabled comments (Option allowComments) that seems to stop this behaviour.

**Comment by stefanneculai** [comment]
Should be fixed on master.
