### ISSUE TITLE
Problems editing newsletter templates

### ISSUE THREAD

**Issue by pedrowebcomum** [froala/wysiwyg-editor#654]
We are using Version 1.2.9 of Froala and when we use tables on a newsletter template, it seems to completely destroy the layout of the template inside the editor.

Example:

![image](https://cloud.githubusercontent.com/assets/12413929/9385115/7d68d2f4-474c-11e5-9267-106de095fef5.jpg)

When it should actually look like this

![image2](https://cloud.githubusercontent.com/assets/12413929/9385138/a77538d0-474c-11e5-8908-4f66df4a933d.jpg)

Is there any ETA on a fix for this issue?

Thanks in advance

**Comment by stefanneculai** [comment]
V2 will come with builtin support for editing email templates. https://www.froala.com/blog/the-final-sprint-for-v2

**Comment by stefanneculai** [comment]
Improved in version 2.0.0-rc.1. If you want to edit email templates without problems, then you should enable the fullPage option and set the imageIframeStyle, tableIframeStyle and videoIframeStyle to `''`. There will be a detailed article about that on our website soon.

**Comment by cmnstmntmn** [comment]
@stefanneculai i could not find the article. is it somewhere?
