### ISSUE TITLE
Pasting from Excel doesn't behave consistently

### ISSUE THREAD

**Issue by eddcvjm** [froala/wysiwyg-editor#655]
Hi,
The following scenario was tested on the froala site: https://www.froala.com/wysiwyg-editor/docs/examples

Steps to reproduce:
1-Fill some cells on an Excel spreadsheet, similar to the following one
     ![image](https://cloud.githubusercontent.com/assets/13676411/9385706/d248501c-474f-11e5-83ed-5a5f3318c483.png)
2-Copy from Excel and paste on Froala
     ![image](https://cloud.githubusercontent.com/assets/13676411/9385934/f51074c0-4750-11e5-8816-f47bd468e40f.png)

We can see that extra characteres are added after the table

3-Repeat step2
![image](https://cloud.githubusercontent.com/assets/13676411/9385963/2271301c-4751-11e5-98d5-b4cb6f0f3964.png)

We can see that extra characteres are added after the table (but different from the first paste

Thanks

**Comment by stefanneculai** [comment]
Should be fixed on master.
