### ISSUE TITLE
Pasting from Excel with links on cells removes the table formating

### ISSUE THREAD

**Issue by eddcvjm** [froala/wysiwyg-editor#656]
Hi,
The following scenario was tested on the froala site: https://www.froala.com/wysiwyg-editor/docs/examples

Steps to reproduce:
1- Fill some cells on an Excel spreadsheet, similar to the following one
![image](https://cloud.githubusercontent.com/assets/13676411/9386072/bfd3d8fa-4751-11e5-9bca-e8557e76363f.png)
2-Copy from Excel and paste on Froala
![image](https://cloud.githubusercontent.com/assets/13676411/9386086/d9c4c49a-4751-11e5-9913-d10b5516e64f.png)

The table is lost. Only the content is pasted.

Thanks

**Comment by stefanneculai** [comment]
Could you please send us an Excel file on which that happens? We couldn't replicate this.

Also, could you please mention the OS and browser you're using?

**Comment by eddcvjm** [comment]
Hi,

The browser is IE11 or Chrome running on Windows 8.1

In attachment the excel file used as a source for the example provided
(lines 23 and 24)


Thanks

2015-08-24 12:20 GMT+01:00 Stefan Neculai <notifications@github.com>:

**Comment by stefanneculai** [comment]
Should be fixed on master.
