### ISSUE TITLE
Image upload error hadleing

### ISSUE THREAD

**Issue by evpozdniakov** [froala/wysiwyg-editor#657]
Lets say, there is an error happened server side while saving an image, e.g. user session has expired. In this case server will send back an error with status 401 and json:
```
{"message": "Session expired", "code": 1000}
```

The problem is there is no way to access JSON data: code is always **3** and message is **Error during file upload**.

I figured out, that the message might be send with **error** key, but I didn't found way to send the code.

![1](https://cloud.githubusercontent.com/assets/1109345/9392268/c20b421e-4749-11e5-8626-fafb739d123c.png)

![2](https://cloud.githubusercontent.com/assets/1109345/9392272/c74f067a-4749-11e5-834c-48dbd9a4d35e.png)

**Comment by stefanneculai** [comment]
It's documented on [https://www.froala.com/wysiwyg-editor/docs/concepts/image-upload](https://www.froala.com/wysiwyg-editor/docs/concepts/image-upload):

Returning a JSON with an error field will throw an error with the custom message contained. E.g. `{ error: 'My custom error message.' }`

**Comment by evpozdniakov** [comment]
So there is no way to send back the error code?

**Comment by stefanneculai** [comment]
You could return a stringifyed JSON and then convert it into the handler. So, your response would be {error: "{"code":1000,"message":"Your message"}"}.

**Comment by evpozdniakov** [comment]
I'm going to use this approach. Thank you for the workaround!

**Comment by sureshy02** [comment]
I am able to upload image to my local server. getting response as {"link":"/uploads/abc.png"} , but in browser console  GET http://localhost:4000/uploads/abc.png 404 (Not Found) Error code is 1.

**Comment by stefanneculai** [comment]
@sureshy02 most likely the path is incorrect. You should be able to access the image URL in browser: http://localhost:4000/uploads/abc.png.
