### ISSUE TITLE
Custom error message for copy-pasted images.

### ISSUE THREAD

**Issue by evpozdniakov** [froala/wysiwyg-editor#658]
Found out that the proposed solution ```{ "error" : "My custom error message." }``` works fine for uploaded images but doesn't work for copy-pasted onces.

![4](https://cloud.githubusercontent.com/assets/1109345/9395214/33ee500e-475b-11e5-8250-93de7c6d9c5f.png)

![3](https://cloud.githubusercontent.com/assets/1109345/9395196/1594e47e-475b-11e5-8cf4-addc74c8a2a3.png)

**Comment by stefanneculai** [comment]
I can confirm this is an issue.

**Comment by stefanneculai** [comment]
In v2 this is no longer a problem.
