### ISSUE TITLE
When pasting a Table from MS Word font size and family is lost

### ISSUE THREAD

**Issue by eddcvjm** [froala/wysiwyg-editor#659]
Hi,
The following scenario was tested on the froala site: https://www.froala.com/wysiwyg-editor/docs/examples

Steps to reproduce:
1- On MS word create a table like the following one, where Cell 2-2 has a bigger font size and Cell 2-3 has a different font family

![image](https://cloud.githubusercontent.com/assets/13676411/9406303/3d844758-47f7-11e5-8315-704cfdcd4e29.png)
2- Paste on Froala editor
![image](https://cloud.githubusercontent.com/assets/13676411/9406312/565ee08a-47f7-11e5-9b6a-f63378a9b63e.png)

Expected result:
-Original font size and family are kept on all table cells

Actual result
 - Font size on cell 2-2 is lost
 - Font family on cell 2-3 is lost

Thanks

**Comment by stefanneculai** [comment]
On paste the editor is removing the style attributes. It is not an issue, but this was implemented on purpose.
