### ISSUE TITLE
show/hide wont work in initOnClick

### ISSUE THREAD

**Issue by souvik79** [froala/wysiwyg-editor#663]
Hi,

I know that hide() only works in inlinemode:true, but i want to make it also work with initOnClick.

Could you please let me know how to make it work?

it should work.. as we have multiple froala editor in a page and we cannot make open all at the same page.

regards
SouvikB

**Comment by stefanneculai** [comment]
As the documentation says, the hide method only works for the inlineMode. In basic mode you should use the `destroy` method if you want to hide the toolbar and other editor elements.
