### ISSUE TITLE
In IE 9 removing unordered or orderered list formatting merges items into a single line

### ISSUE THREAD

**Issue by jmangelo** [froala/wysiwyg-editor#664]
In IE 9 with an editor configured with `paragraphy: false` removing formatting from an ordered or unordered list merges the individual list items into a single line.

Steps to reproduce:
1. Create a list with items named A, B and C
2. Select the entire list
3. Remove the list formatting

Expected result (one item per line, without list formatting):
```
A
B
C
```

Actual result (all items merged into a single line):
```
ABC
```

**Comment by stefanneculai** [comment]
V2 no longer supports IE9, therefore I am closing this one.
