### ISSUE TITLE
'Indent more' applied several times makes the text disapear beyond the editor width without horizontal scroll bar

### ISSUE THREAD

**Issue by eddcvjm** [froala/wysiwyg-editor#665]
Hi,
The following scenario was tested on the froala site: https://www.froala.com/wysiwyg-editor/docs/examples

Windows 8.1 - IE11 and Chrome

When we type a text, then position the cursor at the begining of the line and then click indent more several times, the text is moved to the right, which is ok. But at a certain moment, the 'margin-left' that is added at each indent more, make the text disapear on the right of the editor, and no horizontal scroll bar is available.

Steps to reproduce:
-Type any text
-Place the cursor at the begining of the line
-Click indent more button several times

The text disapears on the right and no horizontal scroll bar is available

Thanks

**Comment by stefanneculai** [comment]
This is no longer happening in V2.
