### ISSUE TITLE
Pasting issues from Microsoft word to froala using IE9

### ISSUE THREAD

**Issue by eddcvjm** [froala/wysiwyg-editor#666]
Hi,
The following scenario was tested on Windows 7 - IE9

Steps to reproduce:
1 - As a source use microsoft word a create text like in the following image:
![image](https://cloud.githubusercontent.com/assets/13676411/9527362/985c6928-4ce6-11e5-8458-ed766dacf81e.png)
2 - Copy all text
3 - Paste on froala editor

Expected result:
 - The content and styles are displayed successfully

Actual result:
 - Strikethough pastes as follows: This isstrikethrough

       (the space between 'is' and 'strikethrough' was removed)
 

 - Numbering pastes as follows -> there are spacing issues for 1 and 3. On the second numbered item, there is no space between the 'g' character and the digit 2

1.  Numbering 1
2. Numbering2
3.  Numbering 3
 
 - Text with justify icon pastes as follows: "TextJustified. In order for the justify property to work, it is required that twoor more lines of text are entered"

    (the space between 'two' and 'or' was removed)
 
 - Bulleted List pastes as follows -> the space between the 's' character and the digit is removed

·         Bullets1
·         Bullets2
·         Bullets3

Thanks

**Comment by stefanneculai** [comment]
Could you please send us the document you're copying from so that we can check?

**Comment by eddcvjm** [comment]
Ok,

Here it is


Thanks.

2015-08-28 16:18 GMT+01:00 Stefan Neculai <notifications@github.com>:

**Comment by stefanneculai** [comment]
It looks there is no link to the doc in the last comment. Could you please send us a link from where to download the document? Github doesn't allow to attach files directly here.

**Comment by chrisdavies** [comment]
Our users are complaining of similar problems. Pasting from word "produces odd spacing that can only be removed by going into the raw HTML editor and editing the markup itself".

I was able to reproduce by:

- Going here: https://onedrive.live.com/
- Create a new (default, blank) document
- Add a header
- Add a few paragraphs
- Add some bullet points and paragraphs following the bullet list
- Copy it all and paste into a Froala editor
- Try deleting the odd spacing, etc.

**Comment by chrisdavies** [comment]
I've attached the document that I used. I think a sufficient, and relatively simple workaround would be to simply scrub it of all odd styles and not necessarily attempt a pixel-perfect paste behavior. Few online editors accomplish the latter.

Here's a prototype of the former: http://jsbin.com/depaji/1/edit?js,output

It handles pasting the attached document well.

**Comment by chrisdavies** [comment]
Just realized GitHub didn't let me attach... Here's a link:

https://onedrive.live.com/redir?resid=A23382EBDC142D8!3659&authkey=!AC3urS3PE9tVOiw&ithint=file%2cdocx

**Comment by stefanneculai** [comment]
V2 no longer supports IE9, therefore I am closing this one.
