### ISSUE TITLE
froala loses certain formating when I try to reedit

### ISSUE THREAD

**Issue by sabinem** [froala/wysiwyg-editor#667]
I can format everything fine the first time and it shows on my website, but when I reopen the text in the editor, some of the formating such as the color is gone. Can you please help me. What is going wrong here?
<img width="947" alt="bildschirmfoto 2015-08-28 um 11 07 15" src="https://cloud.githubusercontent.com/assets/5292683/9542943/41f16cd4-4d75-11e5-9123-68f6877a40b4.png">
<img width="1018" alt="bildschirmfoto 2015-08-28 um 11 11 50" src="https://cloud.githubusercontent.com/assets/5292683/9543046/df32b070-4d75-11e5-82b7-2a6cc86db01a.png">
This is what my source code looks like, when I reopen the text in the edit form:
<img width="1057" alt="bildschirmfoto 2015-08-28 um 11 16 04" src="https://cloud.githubusercontent.com/assets/5292683/9543086/41fcb3cc-4d76-11e5-8910-4a2179b1e1d2.png">

**Comment by stefanneculai** [comment]
Hi Sabine! Could you please send the HTML (in text, not picture) that you use when you reinitialize the editor just that we can give it a try?

**Comment by sabinem** [comment]
Hello Stefan, thank you very much for your quick answer. I actually figured
it out myself in the meantime, but good to know that your response-time is
so fast.
       with kind regards
           Sabine

On Fri, Aug 28, 2015 at 5:17 PM, Stefan Neculai <notifications@github.com>
wrote:

> Hi Sabine! Could you please send the HTML (in text, not picture) that you
> use when you reinitialize the editor just that we can give it a try?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/froala/wysiwyg-editor/issues/667#issuecomment-135802674>
> .
>



-- 
Sabine Maennel
Leimbachstr. 223
8041 Zürich
Tel. +41 (0) 43 53 778 74
Mathematikerin / Softwareingenieurin
sabine.maennel@gmail.com
Startup: http://mentoki.com
Facebook: https://www.facebook.com/internetteachers
