### ISSUE TITLE
"use strict" breaks the code

### ISSUE THREAD

**Issue by Va1** [froala/wysiwyg-editor#670]
I've noticed the fact that adding "use strict" before the script even in provided examples breaks everything. This is quite annoying as nowdays people often use things like Babel, which adds "use strict" for every module while bundling (this is kinda JS standard).

Can you provide a "use strict"-compatible build?

Thank you.

**Comment by stefanneculai** [comment]
The unminified JS sources which are available under the Advanced/OEM licenses are "use strict" compatible. There is no point to have "use strict" in minified JS.
