### ISSUE TITLE
Table cell highlight is incorrect at times

### ISSUE THREAD

**Issue by mwtorkowski** [froala/wysiwyg-editor#672]
As seen on picture below - sometimes when dealing with tables with merge cells, blue highlight is wrong, no to mention at times there's some "ghosting" - blue highlight is partly there for previously highlighted cells (it goes away after moving mouse around). Ubuntu, Chrome 44, editor on https://www.froala.com/wysiwyg-editor/v2.0 page.

![selection_500](https://cloud.githubusercontent.com/assets/6072390/9577732/33be7b90-4fe4-11e5-9b82-8c939d120929.png)

**Comment by stefanneculai** [comment]
We know about this and it is not an editor issue, but a Chromium one: https://code.google.com/p/chromium/issues/detail?id=356132. Hopefully, they will fix it soon.
