### ISSUE TITLE
TAB doesn't seem to be an option anymore to indent / outdent list items

### ISSUE THREAD

**Issue by mwtorkowski** [froala/wysiwyg-editor#673]
Ubuntu, Chrome 44, editor at https://www.froala.com/wysiwyg-editor/v2.0
I tried to press tab, in hope to indent list item - nothing happened.

**Comment by masseuro** [comment]
Same with chrome and firefox on macosX

Tab give the focus of the next focusable element in the page (link, ...)

**Comment by masseuro** [comment]
Ok for me this is only when tab option doesn't have 0.

Not a bug.
