### ISSUE TITLE
In doc, some old event editable.* 

### ISSUE THREAD

**Issue by masseuro** [froala/wysiwyg-editor#674]
In this page https://www.froala.com/wysiwyg-editor/v2.0/docs/events

All off events are old event "editable.*" instead of "froalaEditor.*"

<img width="662" alt="capture d ecran 2015-08-31 a 15 54 15" src="https://cloud.githubusercontent.com/assets/131135/9580256/a2f27548-4ff8-11e5-88f2-9f5338cd9911.png">

**Comment by stefanneculai** [comment]
Fixed.
