### ISSUE TITLE
When pasting text from Word that contains links, the resulting html is not allways correct

### ISSUE THREAD

**Issue by eddcvjm** [froala/wysiwyg-editor#675]
Froala version 1.2.8

SO: Windows 8.1
Browser: IE11

Issue 1:
 - When pasting text from Word that contains links, if we implement some code on the "afterPaste" event, after executing .editable('setHTML', .... if we get the HTML from the editor through .editable('getHTML') the </a> tag is missing

 - Was unable to reproduce this specific issue in jsFiddle, but in our froala integration it occours 

Issue 2:
 - If the link is more complex, having part of the display text as bold, we can see that the resulting text is not correct

http://jsfiddle.net/Lp8rwhpy/80/

On Word
![image](https://cloud.githubusercontent.com/assets/13676411/9583654/9640a976-5004-11e5-80e1-c68fa0bb1707.png)

On Froala after paste
![image](https://cloud.githubusercontent.com/assets/13676411/9583681/b3cdf37c-5004-11e5-8ee3-5d201625c028.png)
"Trying good link" should not be underlined

Thanks

**Comment by stefanneculai** [comment]
For issues related to v1, please use https://github.com/froala/wysiwyg-editor-v1.
