### ISSUE TITLE
Popover on website under button

### ISSUE THREAD

**Issue by philfreo** [froala/wysiwyg-editor#676]
Not sure if it's a core editor issue or just your demo site

![screenshot 2015-08-31 14 50 09](https://cloud.githubusercontent.com/assets/97612/9591336/99fdc392-4fef-11e5-8a67-7a8d45ffbcd4.png)

**Comment by stefanneculai** [comment]
It's only a issue from our website.

**Comment by stefanneculai** [comment]
Fixed.
