### ISSUE TITLE
Minor UI padding issue in dropdowns

### ISSUE THREAD

**Issue by philfreo** [froala/wysiwyg-editor#678]
You either have too much left padding on your dropdown items, or not enough right padding

![screenshot 2015-08-31 14 54 05](https://cloud.githubusercontent.com/assets/97612/9591426/25b506d4-4ff0-11e5-95ec-f9ba24e08dc9.png)

**Comment by stefanneculai** [comment]
That's the way MacOS displays the scrollbar.

**Comment by philfreo** [comment]
... So? If it looks bad on OS X that's a Froala CSS issue IMO

**Comment by stefanneculai** [comment]
If you look at the browser scrollbar, then you'll see it appears the same way as on our dropdowns: over the content and with an opacity. Indeed, it is possible to change that via CSS, but this is the way every scrollbar works starting with OS X Lion and we believe that the default behaviour shouldn't be overridden in this case.
