### ISSUE TITLE
Fixed Toolbar example doesn't work 

### ISSUE THREAD

**Issue by philfreo** [froala/wysiwyg-editor#682]
Couldn't get the floating/fixed toolbar example to work in Safari on this page - couldn't get a vertical scrollbar inside Froala editor at all and when I made the text long enough to create a browser vertical toolbar and scrolled down, the toolbar didn't follow

https://www.froala.com/wysiwyg-editor/v2.0/docs/examples/fluid-toolbar

**Comment by stefanneculai** [comment]
By default the editor has toolbar sticky at the top now. This example shows how to make toolbar not sticky anymore.
