### ISSUE TITLE
Font Awesome - 4.3.0 or 4.4.0

### ISSUE THREAD

**Issue by ayush** [froala/wysiwyg-editor#684]
From https://www.froala.com/wysiwyg-editor/v2.0/docs

![screen shot 2015-08-31 at 10 46 23 pm](https://cloud.githubusercontent.com/assets/188701/9597047/41ff17f2-5032-11e5-8bcc-e6eafc58f052.png)

**Comment by stefanneculai** [comment]
Fixed.
