### ISSUE TITLE
Regression with blockStyles

### ISSUE THREAD

**Issue by masseuro** [froala/wysiwyg-editor#686]
Not a bug, but maybe need some add in the migration doc.
blockStyles don't do the same work as paragraphStyles

V1.*
```
blockStyles: {
    'p': {
      'class1': 'Class 1',
      'class2': 'Class 2'
    },
    'h1': {
      'class3': 'Class 3',
      'class4': 'Class 4'
    }
  }
```

V2.*
```
paragraphStyles: {
    class1: 'Class 1',
    class2: 'Class 2',
    class3: 'Class 3'
  }
```

So I couldn't have specific class by tag

**Comment by stefanneculai** [comment]
Updated.

**Comment by leifcr** [comment]
Any plan to revive the blockStyles behaviour, since it was a great feature.

Example
´´´
blockStyles : {
    'default':
    {
      'lead':         'lead',
      'text-muted':   'muted',
      'text-primary': 'primary',
      'text-success': 'success',
      'text-info':    'info',
      'text-warning': 'warning',
      'text-danger':  'danger'
    },
    'blockqoute':
    {
      'bs-callout-primary': 'primary',
      'bs-callout-success': 'success',
      'bs-callout-info':    'info',
      'bs-callout-muted':   'muted',
      'bs-callout-warning': 'warning',
      'bs-callout-danger':  'danger'
    },
    'div':
    {
       'row': 'row (cannot be a row)',
       'col-md-3': '3 col',
       'col-md-6': '6 col',
       'col-md-12': '12 col'
    },
}
´´´

Where default could apply for all kinds of elements, while blockqoute and div would only apply for that context.

This might be beyond the scope of froala?

**Comment by stefanneculai** [comment]
Hi Leif! No, we'll not make it like in V1. We believe it is not user friendly to have different options in the dropdown depending on what the current paragraph is.

**Comment by leifcr** [comment]
@stefanneculai Thanks for the quick feedback. I actually agree that is not user friendly, and those features belong elsewhere in an webapp.
