### ISSUE TITLE
Doc: missing 'px' in heightMin

### ISSUE THREAD

**Issue by connect-technologies** [froala/wysiwyg-editor#687]
Is it right to write the heightMin without a 'px' like in
https://www.froala.com/wysiwyg-editor/v2.0/docs/options#heightMin
?

I only get the right height with: heightMin:'200px'

christopher

**Comment by stefanneculai** [comment]
https://www.froala.com/wysiwyg-editor/v2.0/docs/examples/adjustable-height

**Comment by connect-technologies** [comment]
ahh..

without the '

please update the docs
thanks

**Comment by dianaprajescu** [comment]
Docs have been updated.
