### ISSUE TITLE
Doc: "insertLink" and "insertTable" button names

### ISSUE THREAD

**Issue by ldiebold** [froala/wysiwyg-editor#688]
toolbarButtons only worked with the names "insertLink" and "insertTable" when setting custom buttons.

docs has them written as "table" and "createLink"

Luke

**Comment by masseuro** [comment]
thx ! finally find why my table button doesn't appear :)

**Comment by connect-technologies** [comment]
jeah! thanks for this tipp!

**Comment by stefanneculai** [comment]
Fixed.
