### ISSUE TITLE
Delete image example page still exists in v2 docs

### ISSUE THREAD

**Issue by mufac** [froala/wysiwyg-editor#692]
This page:

https://www.froala.com/wysiwyg-editor/v2.0/docs/server-integrations/php-delete-image

Should probably be changed since deleting images is no longer supported by the editor - at least that's what I'm assuming as "imageDeleteParams" now says: "Deleting image is out of the editor's scope." in the migration guide.

**Comment by stefanneculai** [comment]
The delete image in PHP was updated to reflect a way we recommend to delete image. If you'll look at the example, you'll see that we suggest to make an AJAX request.

**Comment by mufac** [comment]
Ah, sorry you're right, my mistake!
