### ISSUE TITLE
First option in choose link doesn't work

### ISSUE THREAD

**Issue by mufac** [froala/wysiwyg-editor#694]
In the link editing options there is a magnifying glass with 'choose link'. Selecting google or facebook update the link below but choosing the first option 'froala' does nothing.

Google Chrome Version 44.0.2403.157 (64-bit)
OSX 10.10.5

**Comment by connect-technologies** [comment]
Error:
TypeError: d is undefined



AND:
the linkList should be empty on default as well.
https://www.froala.com/wysiwyg-editor/v2.0/docs/options#linkList

**Comment by stefanneculai** [comment]
@connect-technologies If you don't want linkList to appear then it should be removed from the `linkInsertButtons` option.
