### ISSUE TITLE
FeatureRequest: add cite attr for blockquotes

### ISSUE THREAD

**Issue by connect-technologies** [froala/wysiwyg-editor#695]
Hi,

it whould be nice to have a cite attr popup for blockquotes.
http://www.w3schools.com/tags/att_blockquote_cite.asp

thanks

christopher

**Comment by stefanneculai** [comment]
Hi Christopher. Thank you for your feature request suggestion, we'll take into consideration. I am closing this for now because we don't accept feature request here on Github anymore and we want to make keep this repo only for bug tracking.
