### ISSUE TITLE
Paragraphing in blockquotes

### ISSUE THREAD

**Issue by connect-technologies** [froala/wysiwyg-editor#696]
Hi,

thanks a lot for the new feature for ul-lists in blockquotes. That really is a great improvement!

But.... :)

when I hit 'enter' in a quote / blockquote I can't add a paragraph in the blockquote itself, it just adds a new paragraph outside the quote. (also with shift+enter). Is this intended, or a bug?

thanks

update:
... this is really not good.
Forces me not to update to v2 on the productive systems right now.

**Comment by stefanneculai** [comment]
This is the way it should work. We've tried several email clients among which GMail and OSX Mail and this is the correct behaviour.

**Comment by connect-technologies** [comment]
but this is not a email client for 'quoting a reply' (where your method is used) ...

its a texteditor and the default behavior guide should be other texteditors (like word, tinyMCE ...). And they make it that way.
How am I supposed to write a long quote im my article without ever making a linebreak?
Please: Your editor is cool, but this a real issue for my clients. They want to write texts, not answer emails.

**Comment by stefanneculai** [comment]
We have lots of customers who asked for quotes to work the way they are implemented now. Also, we believe that it's more naturally to have it this way because usually you don't edit text within quotes (quotes should keep something someone else said without changes). For the moment, we'll leave the quote behaviour like this and if we get negative feedback about it we'll consider adding an option.

**Comment by mnichols** [comment]
I'd agree with @connect-technologies that the inability to continue a blockquote after carriage return is inadequate. People _type_ quotes into an editor so it isn't a matter of "editing the quote" but rather trying to format it the way it was written/spoken. Longer quotes would naturally have paragraphs and so on. I am able to _paste_ a quote having paragraphs into the editor but of course quotes arent always from digital media where that is possible. Why not permit Shift+Enter to insert a carriage return inside the quote?

**Comment by connect-technologies** [comment]
You can Format the Text first and Quote it in the End.... Not nice, but it works
