### ISSUE TITLE
Editor incorrectly highlights bold, italic and underline buttons

### ISSUE THREAD

**Issue by euangoddard** [froala/wysiwyg-editor#697]
Can be reproduced [here](https://www.froala.com/wysiwyg-editor/v2.0/docs/examples/basic)

To reproduce:

1. Enter some text
1. Highlight the text
1. Click either *B* or *I* or *U* buttons in the toolbar (NB keyboard shortcuts can be used as well)

What happens: the text is formatted correctly, but all the *B*, *I*, *U* buttons are highlighted regardless of which control was chosen. If you deselect the text and reselect it the correct button is selected.

Expected behaviour: only the button corresponding to the selected format is highlighted.

Affected browsers: Chrome Version 44.0.2403.157 (64-bit) for Linux. Firefox seems to be unaffected

**Comment by stefanneculai** [comment]
We cannot reproduce it. Could you please send a video with that?

**Comment by euangoddard** [comment]
I'll have to find some video capture software, but will send the video when I've done it. I could do a series of screenshots as well if that helps

**Comment by stefanneculai** [comment]
We cannot replicate it in Windows or MacOS. Might be something related to Linux only. What distribution are you using?

**Comment by euangoddard** [comment]
I'm using Ubuntu Gnome 14.04. I've tested it on OSX and it works fine as you say!

This is what the editor looks like immediately after step 3 on my computer.

![screenshot from 2015-09-04 17 10 40](https://cloud.githubusercontent.com/assets/412672/9688583/eca2e042-5327-11e5-9810-826cc24d290c.png)

**Comment by stefanneculai** [comment]
@euangoddard would it be possible for you to recheck it now on our website and let us know if the issue is still there? Thanks.

**Comment by euangoddard** [comment]
Just checked and it's ficed!
