### ISSUE TITLE
Deleting single character word also removes preceding space

### ISSUE THREAD

**Issue by mufac** [froala/wysiwyg-editor#698]
To reproduce:
* Type the string "This is a" into the editor (without the quotes)
* Now hit the backspace key to remove the "a"
* Now type another character, say "b"

_What should happen_

The string should say "This is b"

_What does happen_

The string says "This isb". E.g. deleting a word that is only one character long also removes the space before it.

This doesn't happen in version 1 of the editor.

Google Chrome Version 44.0.2403.157 (64-bit)
OSX 10.10.5

**Comment by masseuro** [comment]
only if it's the last word of a paragraph, maybe a trim do too much work

**Comment by mufac** [comment]
Yes only at the end. You also get the problem with a longer word if you delete the characters one at a time.
So type "This is a word" [DEL][DEL][DEL][DEL] "different word" ends up as "This is adifferent word".
