### ISSUE TITLE
Inconsistent behaviour when manually setting video dimensions

### ISSUE THREAD

**Issue by mufac** [froala/wysiwyg-editor#701]
With images when you use the 'change size' option you can enter only one of width or height and it will automatically calculate the right value for the other one based on the image shape.

However this feature doesn't seem to work for videos - if you specify both it works but when you only give one it doesn't get the shape right.

Google Chrome Version 44.0.2403.157 (64-bit)
OSX 10.10.5

**Comment by stefanneculai** [comment]
The video is using an iframe and the video providers (Youtube, Vimeo, etc.) require to have both attributes specified.
