### ISSUE TITLE
Usability issue with link URL label

### ISSUE THREAD

**Issue by mufac** [froala/wysiwyg-editor#702]
In most form elements when you start entering data into a text field you move the placeholder and convert it to a label. It's a nice touch, but it causes a bit of a usability issue in the 'insert link' dialog.

The URL field has a placeholder of 'http://'. So when I start entering text in there it puts a blue 'http://' above the field. This is quite confusing if you've pasted in a link which already contains http because it looks like it's going to be prefixed to the field. Also the fact that http:// is blue makes it look a bit like a link.

Maybe just me, but I think you might be better off using URL as the label to avoid confusion.

**Comment by stefanneculai** [comment]
We'll have to discuss about this.
