### ISSUE TITLE
usability issue with image/file upload progress bar

### ISSUE THREAD

**Issue by mufac** [froala/wysiwyg-editor#704]
When uploading an image the progress bar has three states:
* Preparing to upload
* Uploading
* Loading image
The issue is that during the first and the last states you use a 'knightrider' style back-and-forth animation. Since the progress bar isn't in these states for long it can have the effect of making it look like the progress is moving backwards. I think a mac style 'diagonal stripes' effect would be less confusing.

I can upload a video of the effect if you're not sure what I mean.

**Comment by stefanneculai** [comment]
We have adopted a Material Design like aspect for it and we're trying to keep it as simple as possible. It might look a bit strange at the beginning but users will get used with it very shortly.

**Comment by mufac** [comment]
I wouldn't underestimate how much trust in the system is dependent on it behaving in a way that you expect it to. Perhaps clarity over what is happening is more important than flashy animations.

But of course, it is for you to decide. Here is the video so you can see what I mean:

https://www.youtube.com/watch?v=K3Vg3JbrfJY
