### ISSUE TITLE
Incorrect docs or missing event image.afterRemove

### ISSUE THREAD

**Issue by mufac** [froala/wysiwyg-editor#706]
The documentation here:

https://www.froala.com/wysiwyg-editor/v2.0/docs/server-integrations/php-delete-image

says that you should use the 'froalaEditor.image.afterRemove' event to delete images from the server when they are removed from the editor window.

However the documentation here:

https://www.froala.com/wysiwyg-editor/v2.0/docs/events

Doesn't include an image.afterRemove event (though there is an image.beforeRemove event). In my testing I was unable to get the image.afterRemove event to fire.

I think either:
1. The first link is wrong and should say image.beforeRemove
2. The second link is missing the documentation and there is also a bug with the image.afterRemove event.

**Comment by stefanneculai** [comment]
It's a documentation issue. The event afterRemove was renamed to removed.

**Comment by stefanneculai** [comment]
Fixed.
