### ISSUE TITLE
Incorrect class in Getting Started Docs?

### ISSUE THREAD

**Issue by cgallarno** [froala/wysiwyg-editor#711]
In the "Display Edited Content" section of Getting Started, The docs say to use the class "froala-view" but I have noticed that it is `fr-view` not `froala-view` to get styles to be applied.

![](https://photos-1.dropbox.com/t/2/AADGow1ZAimuD1lbzKVyo091tKbUy98Ntzo5bKJNYedNWQ/12/780474/png/32x32/1/1441238400/0/2/Screenshot%202015-09-02%2016.58.01.png/CLrRLyABIAIgAyAEIAUgBiAHKAEoAigDKAc/j2NGWg3ehpykRQyyoqXxnUz5RSzrv37wO1EMEXVBa_c?size=1280x960&size_mode=2)

**Comment by stefanneculai** [comment]
Fixed.
