### ISSUE TITLE
Inline Toolbar + Fullscreen issues

### ISSUE THREAD

**Issue by joeworkman** [froala/wysiwyg-editor#714]
If you set the toolbar to be inline and you go into Full screen edit mode, the styles are all messed up.

**Comment by stefanneculai** [comment]
In v2 fullscreen is no longer available for inline toolbar. It doesn't make sense for us to use the inline toolbar and fullscreen at the same time.

**Comment by sjoerdvisscher** [comment]
Can I explain how it makes sense? They are a perfect match even! The inline toolbar works great if your  input area is narrow and a fixed toolbar would only have room for a handful of buttons. But in that situation the fullscreen mode is perfect too, to have more room to see what you're typing!

I agree, it would be better to switch to a fixed toolbar when you go to fullscreen mode, and back to the inline toolbar when you go out of fullscreen mode, but as far as I know, you can't do that with the API?
