### ISSUE TITLE
Request: enter mode option for P + br

### ISSUE THREAD

**Issue by joeworkman** [froala/wysiwyg-editor#716]
I would love this behavior.

* One enter key press = `<br>`
* Two or more enter key press = `<p>`

This would really bring the best of both worlds.

**Comment by connect-technologies** [comment]
`<br>` = SHIFT + enter
`<p>` = enter
It's like everywhere else...

**Comment by stefanneculai** [comment]
As @connect-technologies said this is the way everyone is using it and how all the apps work.
