### ISSUE TITLE
How can I disable auto-save

### ISSUE THREAD

**Issue by joeworkman** [froala/wysiwyg-editor#717]
There does not seem to be an option for this.

**Comment by joeworkman** [comment]
Also, ⌘S is definitely being hijacked by the editor but it does not seem to trigger a save. What is it supposed to do?

**Comment by joeworkman** [comment]
I figured out that is used for strikethrough. Time to figure out how to override that

**Comment by stefanneculai** [comment]
Updated on https://www.froala.com/wysiwyg-editor/v2.0/docs/options#saveInterval. Not documented yet, but you can use the following to override the shortcut: `$.FroalaEditor.RegisterShortcut(222, 'save');`
