### ISSUE TITLE
froalaEditor is not a function

### ISSUE THREAD

**Issue by redeyes1357** [froala/wysiwyg-editor#720]
I've been trying for a while now to set up the editor for the 2.0 version but whenever I do all I get is froalaEditor is not a function. If I use the old one than I get a editable is not a function.

I've made sure all the files have been included and this is the code I'm using (key obviously excluded) to initialize it:

       <textarea id="editor" name="content"></textarea>

       <script>
	      $(function() {
	                $('#editor').froalaEditor({key:'XXXXXXXXXXX'});
	            });
       </script>

Thank you for any help that can be provided.

**Comment by connect-technologies** [comment]
see my issue:
https://github.com/froala/wysiwyg-editor/issues/685

It's $.FroalaEditor.DEFAULTS.key ='' now

**Comment by stefanneculai** [comment]
That's right.

**Comment by redeyes1357** [comment]
Thanks! I also figured out that I had to use jQuery instead of $ since it was with Wordpress.
