### ISSUE TITLE
Cannot click on Dropdown buttons when add jQuery-UI library.

### ISSUE THREAD

**Issue by largeden** [froala/wysiwyg-editor#721]
Hi,
Cannot click on Dropdown buttons when add jQuery-UI library.

```javascript
<script src="//code.jquery.com/ui/1.11.3/jquery-ui.min.js"></script>
```
test version: 1.11.0 ~ 1.11.3

ver: wysiwyg-editor 2.0.0-rc.1
OS: windows, osx, centos7 (all)
Browser: all

**Comment by sepster** [comment]
I have the same problem with jQuery-UI and Froala.

I noticed that if you click the same dropdown button twice (doesn't need to be double click) then the click works. Of course this isn't an acceptable solution to the problem, but just mentioning it if this helps in debugging the problem.

**Comment by stefanneculai** [comment]
Could you please make a jsFiddle?

**Comment by largeden** [comment]
http://jsfiddle.net/largeden/Lp8rwhpy/85/

Please clicking the font size button.

**Comment by stefanneculai** [comment]
It works fine to me in the jsFiddle you sent.

**Comment by largeden** [comment]
@stefanneculai 

https://www.dropbox.com/s/nx5q01po6rizfco/froala2.0.0_test.mov?dl=0

OSX 10.10.5
Safari 8.0.8 (10600.8.9)

**Comment by stefanneculai** [comment]
OK. I see now.
