### ISSUE TITLE
Placeholder missing

### ISSUE THREAD

**Issue by connect-technologies** [froala/wysiwyg-editor#723]
I can't add a placeholder-text for a textarea. There is always "Type something".

**Comment by stefanneculai** [comment]
You have to use the option `placeholderText`: https://www.froala.com/wysiwyg-editor/v2.0/docs/options#placeholderText

**Comment by connect-technologies** [comment]
Thanks for this info,
but....
i have about 100 different textareas on that page (populated from database for different input fields) and i really don't want to add a placeholderText in the call definition for each ID. Is there a real reason why not to take the html5 placeholder attr?

**Comment by stefanneculai** [comment]
Last commit is reintroducing this feature. Setting the `placeholderText` option to `null` will use the textarea's placeholder if available.
