### ISSUE TITLE
Link text on predefined link list

### ISSUE THREAD

**Issue by manttih** [froala/wysiwyg-editor#725]
If I select a link from predefined list, also the link text is updated. I don't think this is wanted, and I can't seem to find an option to disable this auto update. Also, the prefix should be updated according to linkAutoPrefix (which I have as '', because I have all pages on current site in the predefined list). Windows 7, Firefox 40.0.3.

**Comment by stefanneculai** [comment]
Last commit adds the possibility to have a property `displayText` which would be used only to display the name in the dropdown, but not update the text.

The prefix is added when you insert the link, not when you choose it from the dropdown list. We couldn't identify any issue about this.

**Comment by felixroos** [comment]
Hello!
Thank you for this new property, which also solved my problem.
It still has a little bug:
![froalalinkbug](https://cloud.githubusercontent.com/assets/12023032/13808064/8b356eee-eb64-11e5-94a8-60f41b379094.gif)
When hyperlinking marked text, the marked text disappears from the text input as soon as the custom link (with displayText) is selected.
After saving, the text input is filled again.
