### ISSUE TITLE
disableRightClick

### ISSUE THREAD

**Issue by manttih** [froala/wysiwyg-editor#726]
A HUGE usability issue seems to be, that disableRightClick doesn't open the editor anymore on right mouse click. For instance, if I want to add an image, I need to enter some text and select it before I can add an image... I don't want to use toolbarVisibleWithoutSelection, because then I can't see everything at once. Windows 7, Firefox 40.0.3.

**Comment by stefanneculai** [comment]
We believe that having to use right click to edit the content is not user friendly. We have designed everything to work only by using the left click so that there is no learning curve for the end users. If we'll get negative feedback for this, we might add the possibility to open the editor using right click.

**Comment by manttih** [comment]
I don't think there is no need to use right click (as the editor does open anyways by selecting text). But it would be very nice possibility, as inserting image gets lot easier with right mouse click :).

**Comment by stefanneculai** [comment]
You could also use [shortcuts](https://www.froala.com/wysiwyg-editor/v2.0/shortcuts) to bring the editor in: CTRL/CMD + E.

**Comment by manttih** [comment]
Hello!

 

I implemented my own right-click –function (with on mouseup). Thanks anyways J

 

Best Regards

 

-------------------------------------------------

Matti Hautaniemi

matti.hautaniemi@mainossynergia.com

040 724 0806

Mainostoimisto Synergia

 

 

 

Lähettäjä: Stefan Neculai [mailto:notifications@github.com] 
Lähetetty: 23. syyskuuta 2015 17:26
Vastaanottaja: froala/wysiwyg-editor
Kopio: manttih
Aihe: Re: [wysiwyg-editor] disableRightClick (#726)

 

You could also use shortcuts <https://www.froala.com/wysiwyg-editor/v2.0/shortcuts>  to bring the editor in: CTRL/CMD + E.

**Comment by stefanneculai** [comment]
Hi @manttih! You have won a T-Shirt as part of [our contest](https://www.froala.com/blog/froala-editor-v2-contest-winners). Could you add your email address to your Github profile so that we can reach you? Thanks!

**Comment by manttih** [comment]
Hello!

 

Oh, ok – great! J I added email to my Github profile.

 

-------------------------------------------------

Matti Hautaniemi

matti.hautaniemi@mainossynergia.com

040 724 0806

Mainostoimisto Synergia

 

 

 

Lähettäjä: Stefan Neculai [mailto:notifications@github.com] 
Lähetetty: 7. lokakuuta 2015 19:26
Vastaanottaja: froala/wysiwyg-editor
Kopio: manttih
Aihe: Re: [wysiwyg-editor] disableRightClick (#726)

 

Hi @manttih <https://github.com/manttih> ! You have won a T-Shirt as part of our contest <https://www.froala.com/blog/froala-editor-v2-contest-winners> . Could you add your email address to your Github profile so that we can reach you? Thanks!
