### ISSUE TITLE
Concerning tables

### ISSUE THREAD

**Issue by manttih** [froala/wysiwyg-editor#727]
There doesn't seem to be a way to align cell (left, right, center, only top, middle, bottom). Also, it would be great if user could add custom hex code in colors (such as #cccccc) by a text field. Windows 7, Firefox 40.0.3.

**Comment by stefanneculai** [comment]
You can use the toolbar main buttons to align the cells. I will mark this as an enhancement so maybe we'll add an option in the table toolbar.

**Comment by manttih** [comment]
Ok, great - this works fine. I thought it would add the alignment to a paragraph or span, but it does indeed align the cell itself. Thanks!

**Comment by stefanneculai** [comment]
The toolbar button should be used. If anyone wants an horizontal alignment option in the table tool, then he could add it by using a custom button.
