### ISSUE TITLE
Inserted <br> into empty paragraph

### ISSUE THREAD

**Issue by fru** [froala/wysiwyg-editor#729]
When I put the following html into the froala html view:
```html
<p></p>
<p></p>
<p>Test</p>
```
`<br>` Tags are inserted into both empty p tags. Is this behaviour intentional? Can it be turned of?

**Comment by stefanneculai** [comment]
This is the intended behaviour and it can't be turned off. Empty paragraphs won't be displayed and that's why a `<br>` is added in.

**Comment by glebmachine** [comment]
So, how do i disallow to create empty paragraphs, then?

**Comment by stefanneculai** [comment]
@glebmachine because of the way the editing works in the `contenteditable` field that we're using as a base for allowing editing, having a BR tag inside a paragraph is the best way of keeping consistent editing across different browsers.

**Comment by lostan** [comment]
@stefanneculai  ... allowing <br/> inside paragraphs causes serious problems to all plug-ins. 
<p> TEXT </br> TEXT2 </p> -> if I try to centralize only TEXT the effect confuses my client because both paragraphs are going to be centered!!! 
I think you could reconsider that choice

**Comment by lostan** [comment]
@stefanneculai ... allowing
inside paragraphs causes serious problems to all plug-ins.



> <p> TEXT </br> TEXT2 </p>
-> if I try to centralize only TEXT the effect confuses my client because both paragraphs are going to be centered!!! I think you could reconsider that choice

**Comment by andyflesner** [comment]
> This is the intended behaviour and it can't be turned off. Empty paragraphs won't be displayed and that's why a <br> is added in.

@stefanneculai How is this justification for inserting <br> tags? If the paragraph is empty, just don't do anything. This should, at the **very least**, be toggle-able.
