### ISSUE TITLE
linkConvertEmailAddress doesn't work

### ISSUE THREAD

**Issue by manttih** [froala/wysiwyg-editor#730]
It seems that linkConvertEmailAddress : true doesn't work. It wont add mailto: before the email-address. Tested with test.tester@test.com (it seems to work with test@test.com). Windows 7, Firefox 40.0.3.

**Comment by jgelens** [comment]
This is still broken for me (using 2.0.5) :(

**Comment by stefanneculai** [comment]
@jgelens What email address are you introducing?

**Comment by jgelens** [comment]
simple ones like test@test.com
I've double checked the settings, but that seems to be alright. auto converting normal links work too.
Is there a way I can debug this? I can't seem to find an example on the site either where this is enabled.

**Comment by stefanneculai** [comment]
This feature is designed to convert email addresses only when they are typed in the link popup, not in the editor itself.

**Comment by jgelens** [comment]
ah ok, that was not entirely clear to me. Thanks!
