### ISSUE TITLE
Pasting creates empty paragraphs

### ISSUE THREAD

**Issue by fru** [froala/wysiwyg-editor#731]
When I paste the following html into the "normal" editing mode of froala an empty paragraph is created.
```html
<div>Test</div>
<div>
	<div>
	   <label>Test</label>
	</div>
</div>
```
Is converted into (when pasted):
```html
<p>Test</p>

<p>  </p>
<label>Test</label>
```
This relates to #729.

**Comment by stefanneculai** [comment]
I have just tried to replicate this without success. Could you please let me know what browser and OS are you using? Also, it would be great if you could provide a place from where to copy the HTML.

Are you using V1 or V2?

**Comment by stefanneculai** [comment]
I'm closing this due to lack of response. If we'll get more info about it then we'll reopen it and check it.
