### ISSUE TITLE
Videos can't be pushed by pressing the ENTER button from the line before the video in Froala editor

### ISSUE THREAD

**Issue by judit-nahaj** [froala/wysiwyg-editor#732]
Note:
Both Youtube and Vimeo videos are affected
Steps to reproduce:
1. Navigate to an edit page which contains Froala Editor
2. Type some text into the editor (e.g.: "asd")
3. Insert a video into the Editor
4. Click on the text line before the video
5. Push the ENTER button
Actual results:
5. The cursor jumps to the next line after the inserted video
Expected results:
5. It should start a new line before the inserted video and the video should be moved down by one line

**Comment by stefanneculai** [comment]
Please let us know the browser and OS. Also, are you using V2 or V1?

**Comment by judit-nahaj** [comment]
1.2.8 and on Chrome, IE11, Firefox on Windows 7.

**Comment by stefanneculai** [comment]
This repo is used for V2. For V1 issues please use https://github.com/froala/wysiwyg-editor-v1.

**Comment by kotmatpockuh** [comment]
check this out: https://github.com/froala/wysiwyg-editor-v1/issues/20
