### ISSUE TITLE
Inline image slides down while editing the text around it in Froala Editor

### ISSUE THREAD

**Issue by judit-nahaj** [froala/wysiwyg-editor#733]
Steps to reproduce:
1. Type in some text
2. Select Numbered list Froala option
3. Insert an inline image
4. Type more text lines around the inline image
Actual results:
5. The inline image slides down on pushing the ENTER button while editing the text around the image
The text get misaligned around the image

Expected results:
5. The inline image should not slide down while editing the text around it
The text should not get misaligned around the image

**Comment by stefanneculai** [comment]
We cannot reproduce this. Could you please provide a video?

**Comment by judit-nahaj** [comment]
It might be only on our side, sorry!
