### ISSUE TITLE
Froala options can't be applied on selected text on Samsung Galaxy S3

### ISSUE THREAD

**Issue by judit-nahaj** [froala/wysiwyg-editor#734]
Note: Only Samsung Galaxy S3 is affected
Other devices are not affected (Tested with: iPhone 5S, Samsung Galaxy S3 mini, Samsung Galaxy S4, Nexus 7)

Steps to reproduce:
1. Type some text into Froala
2. Select the text
3. Chose one of the following functions: Bold, Italic, Underline, Insert link, Bulleted-, Numbered List

Actual results:
3. The chosen option does not applied on the selected text
Selected text looses the focus
Expected results:
3. The chosen Froala function should get executed on the selected text

**Comment by stefanneculai** [comment]
What browser are you using?

**Comment by judit-nahaj** [comment]
it vas on v1, on stock android browser

**Comment by stefanneculai** [comment]
Please use https://github.com/froala/wysiwyg-editor-v1 for V1.
