### ISSUE TITLE
Sticky toolbar is misplaced when editor is moved in the DOM

### ISSUE THREAD

**Issue by euangoddard** [froala/wysiwyg-editor#737]
I am creating a content editor which uses the Froala editor for rich text blocks. The user can rearrange the blocks of content but after the blocks have been moved, the editor miscalculates where the sticky toolbar should be (it uses the position of the editor before it was moved).

The moving in my case is handled by Angular (although I don't believe the issue is specific to Angular, but rather an issue with extracting a section of the DOM tree containing the editor and reinserting it at another point).

I can't see any method for the editor that I could call for it to perform a reinitialization of the sticky toolbar since I think this will be something to do manually at the point of DOM mutation. Without using a mutation observer in the editor code I think something like this is necessary for those wanting to move the editor around.

**Comment by stefanneculai** [comment]
Please provide a jsFiddle.

**Comment by euangoddard** [comment]
Sure thing. Is there a CDN version of Froala I can point JSFiddle to?

**Comment by euangoddard** [comment]
With the following markup:

```
<div id="parent">
  <div id="above">Above</div>
  <div id="editor"><textarea></textarea></div>
  <div id="below"></div>
</div>
```

Initialize the editor on `#editor textarea`, then do:

```
var editor = document.querySelector('#editor');
var parent = document.querySelector('#parent');

parent.removeChild(editor);
parent.appendChild(editor);
```

You'll need a big enough page to have scrolling, but the toolbar will be in the wrong place after the move.

**Comment by connect-technologies** [comment]
you can fork my jsfiddle http://jsfiddle.net/qx3uooj4/2/

**Comment by euangoddard** [comment]
I had to inline the editor code as Chrome was complaining about an incorrect MIME type. This fiddle: http://jsfiddle.net/e4fm47bn/3/ shows the issue when the editor is moved both up and down (more noticeable going down).

**Comment by stefanneculai** [comment]
@euangoddard Yes, there is a CDN version https://cdnjs.com/libraries/froala-editor/2.0.0-rc.1

**Comment by euangoddard** [comment]
@stefanneculai I managed to achieve this without needing that. See http://jsfiddle.net/e4fm47bn/3/ for details. I also suspect this issue will occur if the content above the editor changes in vertical height

**Comment by stefanneculai** [comment]
Last commit adds in the `position.refresh` method. After moving the editor if you call it, then everything will work as it should.

**Comment by euangoddard** [comment]
Thanks so much for this!
