### ISSUE TITLE
Link Insert duplicated

### ISSUE THREAD

**Issue by blpcastanheira** [froala/wysiwyg-editor#743]
The bug happens when the enter key is pressed after the link. Look for the gif below to see the duplicate element.

![linkcreateationbug](https://cloud.githubusercontent.com/assets/4196666/9876603/aecbb686-5b8d-11e5-8f66-c5cb222b1e05.gif)

**Comment by philfreo** [comment]
+1

**Comment by mnichols** [comment]
I am using froala 2.0.5 and getting this same behavior . Here is a link to a vid of me reproducing: http://padlet.com/mike3/m6mtyubpt7kp/wish/87083625

This duplication only happens when creating a link with text (full word or partial) at end of a line having a carriage return.

**Comment by mnichols** [comment]
@stefanneculai FYI I just confirmed this behavior occurs when `linkText:false` also except it actually inserts the url beside the original text.

**Comment by stefanneculai** [comment]
Last commit is fixing it. Could you check please?

**Comment by mnichols** [comment]
I pulled in `froala_editor.min.js` and `link.min.js` and see they are at 2.0.6, but I still see the same duplication behavior.
The `linkText:false` behavior is broken also, where it actually prepends the URL before the link text.

**Comment by stefanneculai** [comment]
What browser and OS are you using?

**Comment by mnichols** [comment]
I am on OSX El Capitan (10.11.2) with Chrome. I just confirmed that Firefox and Safari works just fine.

**Comment by stefanneculai** [comment]
@mnichols I believe you have not updated it. I just tested it and everything works fine in Chrome too.

**Comment by mnichols** [comment]
@stefanneculai Here is a screengrab of the FroalaVersion (v2.0.6) and the froala editor continuing to have a bug at end of line for links. It inserts the url text next to what should be the anchor text.
This is from master at the gh repo. Is there a dependency on some other plugin that I may be missing?

![froala-bug-chrome-osx](https://cloud.githubusercontent.com/assets/11275/12097519/4edfdc9a-b2d9-11e5-80f0-d6c4790c898c.jpg)

**Comment by stefanneculai** [comment]
@mnichols Could you please let me know the exact steps to reproduce it? Thank you.

**Comment by vaibhavsah** [comment]
1. Create an Image link. 
2. Place your cursor just after image. 
3. Press enter. 
4. Now the next blank line will also be a link.
5. Insert a Table. 
Now the table will also acts as a link. Click anywhere in table, it will show the link edit popup.
