### ISSUE TITLE
If I destroy a previously created editor and try to reinitialize, new editor doesn't show

### ISSUE THREAD

**Issue by andymilk** [froala/wysiwyg-editor#744]
I'm trying this:
    $('.froala').editable('destroy');

$('.options .froala').editable();

Since we're using AJAX, we often need to repopulate a page with a textarea and then initialize the editor, but if we don't destroy the previous editor, it creates multiple editors on the page (hidden divs).

How do we destroy and then re-enable?

**Comment by stefanneculai** [comment]
You should pass the same options that you pass initially when you reinitialize the editor. By default the editor has the option `inlineMode` enabled and you might not see the toolbar the way you want. 

PS: We're using this repo for V2 of the editor. For V1, please use https://github.com/froala/wysiwyg-editor-v1.

**Comment by andymilk** [comment]
Yes, we are using the same initializing code each time...

So we initialize with one set of code, destroy, and the reinitialize with
the same set of code and it doesn't work


On Wed, Sep 16, 2015 at 8:25 AM, Stefan Neculai <notifications@github.com>
wrote:

> You should pass the same options that you pass initially when you
> reinitialize the editor. By default the editor has the option inlineMode
> enabled and you might not see the toolbar the way you want.
>
> PS: We're using this repo for V2 of the editor. For V1, please use
> https://github.com/froala/wysiwyg-editor-v1.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/froala/wysiwyg-editor/issues/744#issuecomment-140726331>
> .
>



-- 
*****
617.290.8559
andymilk@gmail.com

**Comment by stefanneculai** [comment]
If you can create a jsFiddle to reproduce it, then we could definitely look over it.

**Comment by andymilk** [comment]
Hi Stefan,

Are there CDN links we can use for CSS and JS for froala?  I added our code
here but not sure how to include the external froala libraries:
https://jsfiddle.net/L7afc7rg/

Thanks,
Andy

On Wed, Sep 16, 2015 at 8:33 AM, Stefan Neculai <notifications@github.com>
wrote:

> If you can create a jsFiddle to reproduce it, then we could definitely
> look over it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/froala/wysiwyg-editor/issues/744#issuecomment-140728334>
> .
>



-- 
*****
617.290.8559
andymilk@gmail.com

**Comment by stefanneculai** [comment]
Sure: https://cdnjs.com/libraries/froala-editor <https://cdnjs.com/libraries/froala-editor>.

**Comment by andymilk** [comment]
Thanks - I've updated it but it's not initializing froala
https://jsfiddle.net/L7afc7rg/2/

On Wed, Sep 16, 2015 at 9:25 AM, Stefan Neculai <notifications@github.com>
wrote:

> Sure: https://cdnjs.com/libraries/froala-editor <
> https://cdnjs.com/libraries/froala-editor>.
>
> > On 16 Sep 2015, at 16:25, andymilk <notifications@github.com> wrote:
> >
> > Hi Stefan,
> >
> > Are there CDN links we can use for CSS and JS for froala? I added our
> code
> > here but not sure how to include the external froala libraries:
> > https://jsfiddle.net/L7afc7rg/
> >
> > Thanks,
> > Andy
> >
> > On Wed, Sep 16, 2015 at 8:33 AM, Stefan Neculai <
> notifications@github.com>
> > wrote:
> >
> > > If you can create a jsFiddle to reproduce it, then we could definitely
> > > look over it.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> https://github.com/froala/wysiwyg-editor/issues/744#issuecomment-140728334
> >
> > > .
> > >
> >
> >
> >
> > --
> > *****
> > 617.290.8559
> > andymilk@gmail.com
> > —
> > Reply to this email directly or view it on GitHub <
> https://github.com/froala/wysiwyg-editor/issues/744#issuecomment-140741370
> >.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/froala/wysiwyg-editor/issues/744#issuecomment-140741504>
> .
>



-- 
*****
617.290.8559
andymilk@gmail.com

**Comment by connect-technologies** [comment]
Any progress @andymilk ?

I'd like to ask a similar question:

I want to 'hide' the editor on blur, and reinitialize it onclick again.
How can I do this?
I made a fiddle:
http://jsfiddle.net/jh7dwcjv/

thanks

**Comment by stefanneculai** [comment]
@andymilk you're not including jQuery.

@connect-technologies You should reinitialize the editor again with initOnClick after destroy.

**Comment by connect-technologies** [comment]
@stefanneculai 
I'm sorry, but I don't understand how.
My textarea is gone after 'destroy', so my easy reinitialize doesn't fire ...

I tryed my best at:
http://jsfiddle.net/jh7dwcjv/4/

**Comment by stefanneculai** [comment]
@connect-technologies actually it's there but it's hidden. Indeed there is a problem with destroy. Could you please make a different issue for it?
