### ISSUE TITLE
The popup arrow alignment is wrong

### ISSUE THREAD

**Issue by blpcastanheira** [froala/wysiwyg-editor#745]
When you click on any of the icons a pop up opens. The arrow on the pop up that should point to the right icon is pointing to a wrong position. 

See the GIF below to better understand what is happening.

![arrow position](https://cloud.githubusercontent.com/assets/4196666/9885023/6cc21786-5bb9-11e5-8ae0-a9a5f534e10d.gif)

**Comment by stefanneculai** [comment]
When there is not enough space, to center the popup, the popups are moved to the left or to the right in order to fit the screen. I marked this as an `enhancement` to change the position of the arrow as well.

**Comment by blpcastanheira** [comment]
I assumed it's wrong because in Editor v1, the alignment works great.

Thank you!
