### ISSUE TITLE
iOS 8.4 scrolling issues

### ISSUE THREAD

**Issue by felskov** [froala/wysiwyg-editor#750]
When using safari on iOS 8.4, there seems to be quite a few issues with scrolling - I'm not sure if they're actually related, but I'm reporting all of them here anyway.

- While entering text, the window will not scroll along with the cursor - so if I input a lot of text or a lot of concurrent linebreaks, eventually the caret will be outside the viewport: ![out](https://cloud.githubusercontent.com/assets/1436954/9929579/ee2f87ac-5d2d-11e5-97d8-3e0433a63bb0.gif)

- If I start from inserting a few linebreaks, then the viewport will scroll up a bit when I actually start scrolling down. It's hard to explain, but I hope the following video explains what I mean: 
![out](https://cloud.githubusercontent.com/assets/1436954/9929725/f744e638-5d2e-11e5-9044-7a97f913c4a7.gif)

- When creating a list, the viewport scrolls up and leaves the caret plus the newly created list out of view. 
![out](https://cloud.githubusercontent.com/assets/1436954/9929829/98a3af50-5d2f-11e5-853f-dbe81f39d6b8.gif)

- Once a while, I cannot scroll to the bottom of the editor. It appears as if it's cropped at some point. Unfortunately, I've not been able to capture a video of this bug and it happens only sporadically. If I see this again, I'll attempt to get a video documenting the issue and gather as much relevant data about steps to reproduce and possible cause of the problem.

Please note that while the videoes are captured using the simulator, I've been able to reproduce all of these issues on an actual device as well.

**Comment by stefanneculai** [comment]
The first issue seems to happen only when no height is specified for the editor. We've managed to track it down to an iOS issue and we'll report it to Apple.

We've done some changes lately to the editor and according to our tests the other issues doesn't seem to happen anymore. Would it be possible for you test them again with the master version? Thank you.

**Comment by felskov** [comment]
Sure, but as I'm using webpack I'd prefer using the non-minified files. Is there any way to download rc3 sources at the current point?

**Comment by stefanneculai** [comment]
Please contact us through [our website](http://froala.com/wysiwyg-editor/contact) and we'll send them over to you.

**Comment by felskov** [comment]
I've not been able to reproduce the last 3 issues in the latest version.

**Comment by stefanneculai** [comment]
Thank you! Taking into consideration that the first one is an iOS problem, I am closing this issue.
