### ISSUE TITLE
Popups have no arrow on iOS 8.4 safari

### ISSUE THREAD

**Issue by felskov** [froala/wysiwyg-editor#753]
There is no arrow at the top of the popup for some reason:

<img width="247" alt="screen shot 2015-09-17 at 11 48 15" src="https://cloud.githubusercontent.com/assets/1436954/9930148/0956e72e-5d32-11e5-90ef-6449083870bc.png">

**Comment by stefanneculai** [comment]
This is done on purpose because there is necessary a lot of repositioning on mobile devices. The screen is simply too small to have enough room to place the arrow. I am closing this for now, however, we might review it together #745.
