### ISSUE TITLE
Inserting a table on touch-based devices

### ISSUE THREAD

**Issue by felskov** [froala/wysiwyg-editor#754]
Inserting a table does not work well on touch-based devices - it seems as if the popup for doing so has only been optimized for desktops, where you're using mouse-based events for interaction.

I think that this should be handled differently on touch-based devices. For instance by updating selected amount of cells on click and not inserting them until the user clicks an "OK / insert"-button - maybe something like this:

<img width="326" alt="screen shot 2015-09-17 at 12 04 18" src="https://cloud.githubusercontent.com/assets/1436954/9930489/522524aa-5d34-11e5-826d-82153c22f080.png">

**Comment by boynet** [comment]
I just created self made plugin that simply open a pop up with 2 input texts, one from rows one for cols and a insert button, a lot more comfortable and flexible. I think it should be the default behavior
![untitled](https://cloud.githubusercontent.com/assets/1615629/15113137/222910ec-15fb-11e6-92e3-34b2af3b8fab.jpg)

**Comment by stefanneculai** [comment]
@felskov @boynet thanks for the feedback. I am going to close this because it is more a feature request than an `enhancement`. Although this is an old issue opened here, it is still on our list marked as a `feature-request`
