### ISSUE TITLE
Autocorrect on iOS

### ISSUE THREAD

**Issue by felskov** [froala/wysiwyg-editor#756]
When disabling spellcheck, autocorrect and autocomplete should also be turned off on iOS.

**Comment by stefanneculai** [comment]
Last commit is adding `autocomplete="off" autocorrect="off" autocapitalize="off"` when spellcheck if off. However, there is an issue in iOS and on elements with contenteditable enabled these attributes are ignored. We've made a jsFiddle for it: http://jsfiddle.net/4ecxfxgr/. 

We'll report it to Apple so they have this into their attention.
