### ISSUE TITLE
Image manager inserts images at the top in Safari

### ISSUE THREAD

**Issue by felskov** [froala/wysiwyg-editor#757]
When using the image manager, the image will be inserted at the top of the contents, instead of the position of the caret. The issue can be reproduced in Safari version 8.0.7 (10600.7.12) on Mac OS X Yosemite 10.10.4.

![out](https://cloud.githubusercontent.com/assets/1436954/9932781/e2d01520-5d46-11e5-8cd9-b710b4089e3e.gif)

**Comment by stefanneculai** [comment]
Hi @felskov! You won a T-Shirt as part of [our contest](https://www.froala.com/blog/froala-editor-v2-contest-winners). Could you add your email address to your Github profile so that we can reach you? Thanks!

**Comment by felskov** [comment]
I've updated my public email :-)
