### ISSUE TITLE
Paragraph style is not working

### ISSUE THREAD

**Issue by LRAnimations** [froala/wysiwyg-editor#758]
In the downloaded files of froala editor v. 2.0.0 rc2 the paragraph style is not working.
It even doesn't work in the given example files.
I proofed all js and css files and there was no ".text-thin" attribute anywhere.
So consequently it is clear why it doesn't work at all.

**Comment by stefanneculai** [comment]
In the downloaded files, there is no CSS set for the classes added by paragraph style. I marked this as enhancement and we'll add some CSS just to make sure that it doesn't create any confusion.
