### ISSUE TITLE
Strangeness when hitting return

### ISSUE THREAD

**Issue by joeworkman** [froala/wysiwyg-editor#759]
Here are some steps to replicate an issue that I am having. 

1. Type in some text and then make is a Header 3 via the styles menu
2. Hit the return key
3. You should notice that the cursor is placed at the beginning of the text you just entered. 

However, when you start typing, the text is inserted into the correct location. You can keep replicating this but just typing a return and typing a new line. The cursor always starts at the previous line.

**Comment by joeworkman** [comment]
I figured out that this only happens when using `enter:$.FroalaEditor.ENTER_BR`

**Comment by stefanneculai** [comment]
What browser and OS are you using?

**Comment by joeworkman** [comment]
OS X 10.10 + Safari
