### ISSUE TITLE
Windows 7 Safari 5.1.7

### ISSUE THREAD

**Issue by manttih** [froala/wysiwyg-editor#761]
I'm not sure how often the combination of Windows + Safari (5.1.7) is used, but there seems to be a lot of problems with selection. I tested this also on your site (both normal / inline editor). When I click enter, the focus of the editor is lost, so I have to click the editor again before I can write another chapter. Also, the methods selection.save, selection.restore doesn't seem to work.

**Comment by stefanneculai** [comment]
We don't support Windows + Safari 5.1.7. Safari 5.1.7 is a browser that is way too old and many of the advanced things that the modern browsers permit cannot be achieved in it.

**Comment by manttih** [comment]
Hello!

 

Ok, Safari 5.1.7 was the latest I could find for Windows, so I guess this combination is not used that much . Thank you for the info!

 

-------------------------------------------------

Matti Hautaniemi

matti.hautaniemi@mainossynergia.com

040 724 0806

Mainostoimisto Synergia

 

 

 

Lähettäjä: Stefan Neculai [mailto:notifications@github.com] 
Lähetetty: 18. syyskuuta 2015 15:00
Vastaanottaja: froala/wysiwyg-editor
Kopio: manttih
Aihe: Re: [wysiwyg-editor] Windows 7 Safari 5.1.7 (#761)

 

We don't support Windows + Safari 5.1.7. Safari 5.1.7 is a browser that is way too old and many of the advanced things that the modern browsers permit cannot be achieved in it.
