### ISSUE TITLE
Highlight table only on two sides

### ISSUE THREAD

**Issue by chr22** [froala/wysiwyg-editor#765]
Table highlighting highlights all four sides of the cell when the cursor is in the cell, but when you leave the cell will it look like the picture below.
![highlighted](https://cloud.githubusercontent.com/assets/3649594/9955322/4da33572-5df0-11e5-90e5-9275312e6e68.PNG)

Windows 10 
Chrome 45

**Comment by stefanneculai** [comment]
Duplicate of #672.
