### ISSUE TITLE
Inline formatting bug on new paragraph

### ISSUE THREAD

**Issue by swolfod** [froala/wysiwyg-editor#766]
Take the example of the editor demo on the [Froala website](https://www.froala.com/wysiwyg-editor).

Focus at the end of a paragraph, click the 'bold' toolbar button to activate and type something, then hit enter, and continue type something in the new paragraph. The bold style is carried along to the content of the new paragraph, which is fine. However, if the user decides he doesn't need bold anymore, and he deleted the content in the new paragraph, hit bold button to remove the bold style, and type something again, he's gonna find that the bold style is still activated.

Besides, is there anyway to detect the current formatting status of the editor? I am trying to implement my own toolbar to control the behaviour of the editor but couldn't find anyway to know the current status of the editor.

**Comment by stefanneculai** [comment]
That has been fixed in v2 of the editor: https://www.froala.com/wysiwyg-editor/v2.0.

Please notice that we're using this repo for V2 of the editor. For V1, please use: https://github.com/froala/wysiwyg-editor-v1

**Comment by swolfod** [comment]
Now when the user hit backspace and delete all the text in the new paragraph, the formatting is automatically cleared. Is this by design? Not sure it is completely reasonable.

**Comment by stefanneculai** [comment]
We'll add an option for toggling this behaviour on and off. We've good feedback and arguments for both cases.

**Comment by stefanneculai** [comment]
@swolfod Last commit adds the option `keepFormatOnDelete` that can be used for getting the editor work that way.
