### ISSUE TITLE
Inserting link the the end of paragraph

### ISSUE THREAD

**Issue by swolfod** [froala/wysiwyg-editor#767]
Focus the cursor at the end of a paragraph, or select some text toward the end of a paragraph, then call 'link.insert' method. Text is inserted but not a link.

Issues happens when using the 'Insert Link' toolbar button too. If click the button while the cursor is at then end of a paragraph and insert a link, although a link will be inserted, it is not selected after inserting  as done when inserting at other position, and the popup is not closed.

**Comment by stefanneculai** [comment]
This has already been fixed on master few days ago.
