### ISSUE TITLE
Disabling popups

### ISSUE THREAD

**Issue by swolfod** [froala/wysiwyg-editor#770]
It would be nice to be able to config which popups needs to be shown. For example, I would like to use the image plugin to insert images in the content, but would rather not having the 'edit image' popup shown whenever a image is selected.

**Comment by stefanneculai** [comment]
We haven't had any such requests so far. I am closing this, but if there will be feedback for it then we might add such an option. For the moment you could modify the image plugin and make it work the way you want.
