### ISSUE TITLE
v2 regression of #334

### ISSUE THREAD

**Issue by philfreo** [froala/wysiwyg-editor#772]
see #334

http://jsfiddle.net/2vh34drm/

<img width="307" alt="screenshot 2015-09-20 11 14 29" src="https://cloud.githubusercontent.com/assets/97612/9982210/cbe04594-5f88-11e5-9cc4-7dc8c9106b85.png">

do you have unit tests from v1 that are carrying over to v2? I've just begun testing it and am worried that I've found a couple regressions already.

**Comment by stefanneculai** [comment]
Yes, we still have the tests. Although it has similar behaviour the root cause is different.
