### ISSUE TITLE
v2 Code view textarea issues

### ISSUE THREAD

**Issue by philfreo** [froala/wysiwyg-editor#773]
http://jsfiddle.net/2vh34drm/1/

Click html button

<img width="443" alt="screenshot 2015-09-20 11 33 11" src="https://cloud.githubusercontent.com/assets/97612/9982287/6d7abc70-5f8b-11e5-9dbc-2dbc59bee217.png">

**Comment by KrisCoulson** [comment]
Also noticed a similar issue when editor is initialized through a javascript call and when initialized with "initOnClick: true"

**Comment by benjaminfunk** [comment]
Have the same problem. All my textboxes are display block. The code_view doesnt overwrite it. Maybe its better to set inline via JS

**Comment by stefanneculai** [comment]
Actually it's not an issue. You're not including the CSS file for code view. http://jsfiddle.net/2vh34drm/2/
