### ISSUE TITLE
v2 regression of #332 with removal of 'scrollableContainer' option

### ISSUE THREAD

**Issue by philfreo** [froala/wysiwyg-editor#774]
#332 is broken again for me in v2 and it seems like the "scrollableContainer" option was removed without a replacement?

**Comment by stefanneculai** [comment]
In RC1 there was no need for scrollableContainer option. I believe there are some changes made during RC2 that require this option to be added again.

**Comment by stefanneculai** [comment]
Last commit is adding back the `scrollableContainer` option because it is necessary.
