### ISSUE TITLE
cursor functions not updating placeholder

### ISSUE THREAD

**Issue by swolfod** [froala/wysiwyg-editor#776]
If the content is updated by calling cursor methods such as cursor.enter or cursor.backspace, the placeholder text won't appear / disappear accordingly until next mouse/keyboard action.

**Comment by stefanneculai** [comment]
You should call the [placeholder.refresh](https://www.froala.com/wysiwyg-editor/v2.0/docs/methods#placeholder.refresh) method after that if you want to update it.
