### ISSUE TITLE
Postponed configuration doesn't work.

### ISSUE THREAD

**Issue by evpozdniakov** [froala/wysiwyg-editor#778]
I need to configure image upload parameters after editor has been initialized. The editor ignores them.

Here the code example which illustrates the issue:
```
$(selector).froalaEditor({
	imageUploadURL:   url,
	imageUploadParam: 'imageName',
	imageUploadParams: { foo: 'bar' }
});

// asynchronous stuff

$(selector).froalaEditor({
	imageUploadParam: 'originalImageName',
	imageUploadParams: { abc: 'DEF' }
});
```

As you can see below, parameters were not overridden.

![fro](https://cloud.githubusercontent.com/assets/1109345/10021887/2a419634-6118-11e5-8c4b-f01a3b6f758b.png)

**Comment by stefanneculai** [comment]
The editor was not designed to work that way. After the editor is initialized you can set such options using the following code:
```js
$(selector).data('froala.editor').opts.imageUploadParam = 'originalImageName';
$(selector).data('froala.editor').opts.imageUploadParams = { abc: 'DEF' };
```

**Comment by evpozdniakov** [comment]
OK, thank you. In our case it works that way because we use single editor for many contexts. We think, removing and creating new editor after changing context is more expensive. (Btw, this approach worked fine in Froala v1.)

**Comment by stefanneculai** [comment]
We've changed some things in V2 and removed part of the code that was allowing that in order to reduce the library size. It's actually faster the way I specified above and we'll write an article on our website about it in the following weeks.
