### ISSUE TITLE
When you bold selected text, other commands become active.

### ISSUE THREAD

**Issue by evpozdniakov** [froala/wysiwyg-editor#779]
I was able to reproduce the issue in Chrome and Opera. Other browsers seem to be OK.

![fro2](https://cloud.githubusercontent.com/assets/1109345/10022171/75195600-6119-11e5-95b6-04cff139435e.png)

**Comment by stefanneculai** [comment]
Same with #697. Could you please let us know the OS too?

**Comment by evpozdniakov** [comment]
Sorry, didn't see your question. In my case Windows 10. Thank you.

**Comment by stefanneculai** [comment]
@evpozdniakov Thank you. We'll look over it.

**Comment by stefanneculai** [comment]
It seems to be something that is somehow happening only on our website because of the font we're using. Could you download the editor and give it a try locally to see if you have the same issue?

**Comment by evpozdniakov** [comment]
Not sure. Actually, I noticed the issue after upgrade Froala to v2.0. At the beginning I thought I didn't do the upgrade properly, but then I downloaded fresh zip package from your git and reproduced the issue in one of examples. I did the screen shot of your site just for better illustration.

**Comment by stefanneculai** [comment]
That is odd because we can reproduce it only on our website, not locally. We'll check it further, however if you can provide any additional details that would be great.

**Comment by stefanneculai** [comment]
@evpozdniakov would it be possible for you to recheck it now on our website and let us know if the issue is still there? Thanks.

**Comment by evpozdniakov** [comment]
The issue has gone! Thank you (:

![image](https://cloud.githubusercontent.com/assets/1109345/10855503/5b26389a-7f18-11e5-88b3-2a7f418ce01e.png)
