### ISSUE TITLE
tooltip conflict with zIndex option

### ISSUE THREAD

**Issue by benjaminfunk** [froala/wysiwyg-editor#781]
If i change the zIndex option of the editor the tooltip are invisible because they get the same zIndex value as the editor itself

**Comment by benjaminfunk** [comment]
same problem with the image gallery modal

**Comment by stefanneculai** [comment]
We have an example where we're setting this and couldn't replicate it: https://github.com/froala/wysiwyg-editor/blob/master/html/two_instances.html. Could you please make a jsFiddle?

**Comment by benjaminfunk** [comment]
The problem only happens when zIndex is 9998 or higher cause the tooltip zIndex in the css file is 9997. I though if i change the zIndex option that all possible layer will update incrementally ;)

**Comment by stefanneculai** [comment]
Max zIndex value allowed is 9995. We'll update docs for that.

**Comment by stefanneculai** [comment]
Let's keep this opened unless we update docs.

**Comment by stefanneculai** [comment]
Updated.

**Comment by reberinformatik** [comment]
The problem with 9995 max is, that bootstrap modal uses 10050 as z-Index. And forcing the bootstrap modal doesn't seem like a good idea. Could you increase the maximum possible value?
`bootstrap.css-4.0.0, 
.modal {
  position: fixed;
  top: 0;
  right: 0;
  bottom: 0;
  left: 0;
  z-index: 1050;
  display: none;
  overflow: hidden;
  outline: 0;
}`

**Comment by stefanneculai** [comment]
@reberinformatik Thanks for letting us know about this. We'll update it.
