### ISSUE TITLE
Pasting removes the inline styles event though the allowStyles option is set to true.

### ISSUE THREAD

**Issue by hiperlouro** [froala/wysiwyg-editor#784]
When I try to paste formatted text that has inline styles, froala removes them regardless of the value in the allowStyles option.

I searched the source and found that in the processPaste function, when it calls the clean function it uses the following code:
```javascript
clean_html = this.clean(pastedFrag, false, true);
```

Shouldn't this line be calling something like this:

```javascript
clean_html = this.clean(pastedFrag, false, !this.options.allowStyle);
```

Note: I'm using version 1.2.8

**Comment by stefanneculai** [comment]
For v1, please use https://github.com/froala/wysiwyg-editor-v1. In v1, the style is removed on paste. If you are looking for more control, then that can be done only in v2, through the [pasteDeniedAttrs](https://www.froala.com/wysiwyg-editor/v2.0/docs/options#pasteDeniedAttrs) option.
