### ISSUE TITLE
Image Clipboard Copy error

### ISSUE THREAD

**Issue by largeden** [froala/wysiwyg-editor#785]
Image Clipboard Copy error
(Drag and Drop is not a problem.)

https://www.dropbox.com/s/cnqd5xfp3zjb4wh/froala_image_clipboard_error.mov?dl=0
http://jsfiddle.net/43pvo33k/7/
OS X 10.10.5
Firefox
Chrome
Safari

It seems there is a problem with the process below.

editor.events.on('paste.before', _clipboardPaste);
editor.events.on('paste.beforeCleanup', _clipboardPasteCleanup);
editor.events.on('paste.after', _uploadPastedImages);

#### firefox clipboardPasteCleanup()
```html
<img data-fr-image-pasted="true" src="data:image/png;base64,iVBORw0KGgoAAAANSUhE[…]>
```
Profile icon image data is not the image data.

#### Safari Chrome
not uploading...

**Comment by stefanneculai** [comment]
That's the way clipboard works and there is nothing it can be done. When you copy the file in Firefox, the browser clipboard receives the file icon, while Chrome and Safari receive the filename.
