### ISSUE TITLE
User manual errors in the v2.0 Get Started

### ISSUE THREAD

**Issue by largeden** [froala/wysiwyg-editor#787]
Hi, froala editor developers.

Now it was among the contest on your website?
I did not know. :)

https://www.froala.com/wysiwyg-editor/v2.0/docs

It seems to have a slight mistake.
image.min.js must be declared before image_manager.min.js.
(The downloading sample files are no problem.)

```HTML
 <!-- Include Plugins. -->
...
  <script type="text/javascript" src="../js/plugins/image_manager.min.js"></script>
  <script type="text/javascript" src="../js/plugins/image.min.js"></script>
...
```

**Comment by stefanneculai** [comment]
Fixed.

**Comment by largeden** [comment]
Good! :p
