### ISSUE TITLE
Reinitialize after destroy on textareas

### ISSUE THREAD

**Issue by connect-technologies** [froala/wysiwyg-editor#788]
Reinitializing the editor after 'destroy' doesn't work on textareas.

Take a look at http://jsfiddle.net/jh7dwcjv/4/

On DIVs it works: http://jsfiddle.net/jh7dwcjv/5/

**Comment by connect-technologies** [comment]
thanks stefan for the quick fix ... but...
should it really be plain html-code in the textarea after destroy? After destroy I see all the tags instead of the rendered html. On divs, there is the rendered html.
see http://jsfiddle.net/jh7dwcjv/6/ with the new rc3

(I could use the div for sending data via form, but I thought I should stick to a textarea for compatibility)

**Comment by stefanneculai** [comment]
When you destroy the editor that was initialized on a textarea, that's the way it should work by adding in the textarea the HTML code as plain text. It is not possible to display HTML inside textareas.

**Comment by stefanneculai** [comment]
Hi @connect-technologies! You won a T-Shirt as part of [our contest](https://www.froala.com/blog/froala-editor-v2-contest-winners). Could you add your email address to your Github profile so that we can reach you? Thanks!
