### ISSUE TITLE
image.insert can't called at external button

### ISSUE THREAD

**Issue by farrrr** [froala/wysiwyg-editor#790]
I bind image.insert at external button. but nothing happen. and console error is "Uncaught TypeError: cannot read property 'find' of undefined.

I trace the code, and found it need click image button on toolbar, when the dialog is opened, the image.insert method works.when the dialog is closed, will caught errors.

**Comment by stefanneculai** [comment]
Could you please make a jsFiddle for it? Thank you.

**Comment by farrrr** [comment]
http://jsfiddle.net/far/dtntn0p9/1/

when click Insert Image button, will get error.
if I click the image button on the toolbar before I click insert image button, everything is okay.
