### ISSUE TITLE
Request font-family free

### ISSUE THREAD

**Issue by sudeste** [froala/wysiwyg-editor#792]
That may seem a useless request, but very useful if you want to add custom fonts.
For example, in a website you can add extra fonts as Google Fonts, and they want to carry on Froala-Editor.

I suggest adding in the "A" editor in "font family" an input text to paste a free font.

```
 <head>
    <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Tangerine">
      </head>
```
In Editor paste "Tangerine"
I can not think of another way to do it.

**Comment by stefanneculai** [comment]
It's not a common feature that everyone would use, therefore if you want such a behaviour then you could create a custom dropdown and create an option for it.
