### ISSUE TITLE
Paragraph Multiple Styles does not work

### ISSUE THREAD

**Issue by katzsimon** [froala/wysiwyg-editor#794]
Cannot select multiple styles, it will only select the last style and deselect the previous one.

Setting "paragraphMultipleStyles: true" does not seem to make a difference.

It seems to do this in your example too: https://www.froala.com/wysiwyg-editor/v2.0/docs/examples/paragraph-styles

**Comment by stefanneculai** [comment]
Already fixed in #741 .
