### ISSUE TITLE
There is a problem if you have a parent element of the P tag.

### ISSUE THREAD

**Issue by largeden** [froala/wysiwyg-editor#795]
froala editor behavior has found the difference with the other editors.

CKEditor
http://jsfiddle.net/B4yGJ/729/

Froala Editor (RC3 is the same look.)
http://jsfiddle.net/43pvo33k/13/

https://www.dropbox.com/s/12t2e0tqo0r9xsz/operations.mov?dl=0

Try performing the following operations.

- Click Enter at the beginning of the P tag
- Click Enter at the end of the P tag

**Comment by stefanneculai** [comment]
Last commit fixes it. On enter the editor is not carrying on the style for P, but this is made on purpose. See https://github.com/froala/wysiwyg-editor/issues/444.
