### ISSUE TITLE
&lt; parsing error

### ISSUE THREAD

**Issue by Bahir** [froala/wysiwyg-editor#797]
Try to enter this code in editor... 
It brakes the view.

```
<img alt="3(x+1)&lt;x+7" class="latex fr-fin fr-dii" src="http://cliparts.co/cliparts/Xpc/o9B/Xpco9BxTE.png" width="164">
```

**Comment by stefanneculai** [comment]
Could you please offer few more details? 
- What OS / browser are you using? 
- What version of the editor are you using?
- What are the steps to replicate the issue?

Thank you.

**Comment by Bahir** [comment]
Version is 1.2.6. All other does not matters.
But I'll give you the hint to solve the issue.

It will NOT brake parsing if you add spaces to "&lt;" as " &lt; " as follows
```
<img alt="3(x+1) &lt; x+7" class="latex fr-fin fr-dii" src="http://cliparts.co/cliparts/Xpc/o9B/Xpco9BxTE.png" width="164">
```

**Comment by stefanneculai** [comment]
We have just tried it and it has no problems in v1.2.8 or v2.0.0.

**Comment by Bahir** [comment]
Just downloaded 1.2.8 and tried it... 1.2.8 has the same issue.
Steps.
1. Enter in HTML mode
```<img alt="3(x+1)&lt;x+7" class="latex fr-fin fr-dii" src="http://cliparts.co/cliparts/Xpc/o9B/Xpco9BxTE.png" width="164">```
2. Back to editor mode. Everything is ok.
3. Save the code.
4. Open froala with the same code saved
```<img alt="3(x+1)&lt;x+7" class="latex fr-fin fr-dii" src="http://cliparts.co/cliparts/Xpc/o9B/Xpco9BxTE.png" width="164">```
5. We will see ```img alt="3(x+1)```

**Comment by stefanneculai** [comment]
Are you initiailizing the editor on a textarea?

**Comment by Bahir** [comment]
Yes

**Comment by stefanneculai** [comment]
Please see https://github.com/froala/wysiwyg-editor/issues/482#issuecomment-83714915. You should escape the entities from server side before adding HTML to the textarea.

**Comment by Bahir** [comment]
I receive this from server side already escaped

**Comment by stefanneculai** [comment]
Here is a jsFiddle for how the textarea should be initialized in V1: https://jsfiddle.net/323vtp76/. If you upgrade to v2, then that is no longer necessary.

**Comment by Bahir** [comment]
So it has to be prepended with additional &amp;
But iy does not answer why it worked if to quote ```&lt;``` with spaces (before and after).

I use paid version. When I could expect receiving the v2 package with sources?

**Comment by stefanneculai** [comment]
There is a problem in v1 when using `&lt;` inside attributes. Unfortunately, because of the v1 design that cannot be fixed right away.

You can download the source code for v2 at anytime by logging into your account. For now v2 is RC, but we'll get out of this phased during October.
