### ISSUE TITLE
Paste from Excel not creating a table.

### ISSUE THREAD

**Issue by brett-efchub** [froala/wysiwyg-editor#798]
When pasting from Excel it does not create a table.

![sshot](https://cloud.githubusercontent.com/assets/6212892/10195762/8db2210c-678f-11e5-8c76-01cc166cfacd.jpg)

efchub.com/assets/spreadsheet-paste-test.XLSX

**Comment by stefanneculai** [comment]
Could you please send us the file you're copying from?

**Comment by brett-efchub** [comment]
File is here:
http://efchub.com/assets/spreadsheet-paste-test.XLSX

**Comment by stefanneculai** [comment]
Could you please let us know the OS and browser you're using?

**Comment by brett-efchub** [comment]
Windows 10. Firefox 42.0b2.

**Comment by largeden** [comment]
I work well.

OSX 10.10.5
Firefox 41.0

**Comment by stefanneculai** [comment]
@largeden it might be just a Windows problem.

**Comment by benjaminfunk** [comment]
Its a windows/firefox problem. Windows + Chrome works well. Windows + Firefox not

**Comment by brett-efchub** [comment]
@benjaminfunk thanks for testing. Let's hope Mozilla solve this issue soon. Most of our clients use Firefox, so this is quite an issue for us.

**Comment by stefanneculai** [comment]
Firefox is having an issue indeed on Windows, but there is a workaround available and we added it.

**Comment by brett-efchub** [comment]
Many thanks Stefan. :-) Will test it again soon.
