### ISSUE TITLE
V2 removed the "customText" option

### ISSUE THREAD

**Issue by chr22** [froala/wysiwyg-editor#805]
I used the option "customText" to add shortcut text to the tooltips. It doesn't seem like there is a way to do that any more.

So that "Bold" becomes "Bold (Ctrl+B)" like traditional wysiwyg editors like MS Word and Google Docs.

**Comment by stefanneculai** [comment]
As the [migration guide](https://www.froala.com/wysiwyg-editor/v2.0/docs/migrate-from-v1#options) mentions: `To change any text from the editor's interface a language file should be used.`. You can create a custom file, like the translation ones and put the text you want to be displayed.

**Comment by chr22** [comment]
Thanks. I misunderstood that point. I thought that I had to use a predefined one.
