### ISSUE TITLE
Toolbar jumps when other textarea is resized

### ISSUE THREAD

**Issue by chr22** [froala/wysiwyg-editor#814]
If I have "stickyToolbar: true" and another textarea above Froala and resizes the textarea, then Froala's toolbar will stick to the top of the other textarea when i scroll.

The problem is in Chrome, Edge, IE and not in Firefox (haven't tried Safari).

[Here](http://codepen.io/chr22/pen/LpWNXq) is a CodePen that shows the problem.

Steps to reproduce:
1. resize the height of the textarea
2. scroll down 
3. see that the toolbar will stick to the top textarea

**Comment by stefanneculai** [comment]
Related to https://github.com/froala/wysiwyg-editor/issues/737#issuecomment-144336196.
