### ISSUE TITLE
Froala with entities.min.js plugin generates server requests at each keystroke

### ISSUE THREAD

**Issue by chr22** [froala/wysiwyg-editor#817]
If Froala is loaded with the entities plugin in Chrome and watch the Network tab, then i see multiple requests for images and other resources after each keystroke.

Steps to reproduce:
1. Load [this](http://codepen.io/chr22/pen/epvdyp?editors=101) CodePen in Chrome
2. Open developer tools
3. Switch to the Networks tab
4. Watch the number of requests as you type in froala

I don't see the error in Edge, IE or Firefox.

**Comment by stefanneculai** [comment]
We couldn't replicate it in anyway. Could you please provide more details?

**Comment by chr22** [comment]
Have you tried the CodePen demo?

In Chrome on Windows?

For me is it loading "favicon.ico" each time i stop typing.

**Comment by stefanneculai** [comment]
We've tried on OSX. We'll check on Windows as well.

**Comment by chr22** [comment]
Try reloading the CodePen after you opened developer tools.

**Comment by euangoddard** [comment]
I cannot reproduce this issue in Chrome 45 on Linux. However I have experienced very similar issues in that browser. On my machine every time I make a keystroke in the editor I get multiple HTTP requests for all the favicons on my site (it has a manifest.json which makes Chrome request these additional icons).

![screenshot from 2015-10-08 12 07 26](https://cloud.githubusercontent.com/assets/412672/10364664/3b342750-6db5-11e5-9fb6-743d9a957812.png)

If I had to guess I'd say that the editor is creating a hidden iframe to do some off-screen processing. In development I have cache rules for my favicons will not go into Chrome's cache so when Chrome sees a new page for the current domain it tries to get the favicons from the server.

I also don't have the entities script enabled in my version so I think that is a red herring.

**Comment by euangoddard** [comment]
I've been trying to debug this issue and added breakpoints in the Froala code for every time it interacts with or creates iframes and none of these seem to be the culprit for causing these requests.

**Comment by stefanneculai** [comment]
We'll be checking this issue during this week. It's on top of the list.

**Comment by euangoddard** [comment]
I can imagine so as it's very hard to reproduce and I'd also guess that without the cache disabled it will be unnoticeable. Thanks for the update

**Comment by stefanneculai** [comment]
Seems to be a Chrome issue: https://code.google.com/p/chromium/issues/detail?id=131567.
