### ISSUE TITLE
Custom styles for selected text

### ISSUE THREAD

**Issue by mrhanti** [froala/wysiwyg-editor#818]
As of version 2.0.0-rc2, It is only possible to set custom classes to a selected paragraph.
I think an option like setting custom CSS classes to selected text only would be very useful.
something like `paragraphFormatSelection` option for `paragraphSelection` option.

**Comment by connect-technologies** [comment]
Do you think  about https://www.froala.com/wysiwyg-editor/docs/options#inlineStyles
?

**Comment by mrhanti** [comment]
I think of something like `inlineStyles` but using classes instead of inline CSS styles.

**Comment by connect-technologies** [comment]
yes, that whoud be great.
Perhaps also add classes for tables?

**Comment by stefanneculai** [comment]
It's on our list and we might add it in a future minor release.

**Comment by Trapdafifou** [comment]
What is the ETA of this feature ?
