### ISSUE TITLE
RC3: Wrong z-index with fullscreen

### ISSUE THREAD

**Issue by marek-hanzal** [froala/wysiwyg-editor#821]
When using fullscreen plugin, `zindex` is wrongly used:
- toolbar has zindex 4
- fullscreen content has some 9990

when fullscreen (in ~plugin/fullscreen.css)
1. toolbar is not visible (solution: `.fr-box.fr-fullscreen { z-index: 3 !important }`)
2. background has no color, so underlaying content is visible (solution: `.fr-box .fr-wrapper { background-color: white; }`

**Comment by stefanneculai** [comment]
Are you experiencing it on [our website](https://www.froala.com/wysiwyg-editor/v2.0/docs/examples/fullscreen)? Also, could you please let us know what browser and OS are you using?

**Comment by marek-hanzal** [comment]
It was only in custom application (company's internal).

- Chrome 45, Windows 8.1

[Here](https://www.froala.com/wysiwyg-editor/v2.0/docs/examples/fullscreen) it works as expected (correctly) - Firefox 41.0.1 and Win 10.

I've looked into froala's CSS files, where Fullscreen has another z-index than inline toolbar (maybe that shows you - try inline toolbar and fullscreen).

**Comment by marek-hanzal** [comment]
Currently it seems to be working correctly without any further modifications (fixed in 2.0?).
