### ISSUE TITLE
RC3: fullscreen - query fullscreen state

### ISSUE THREAD

**Issue by marek-hanzal** [froala/wysiwyg-editor#823]
If there is option to call fullscreen toggle outside of Froala, there will be nice feature to:
- query fullscreen state
- enable/disable inline mode

Use case:
When **not** in fullscreen, show inline toolbar, but when toggle fullscreen, show top static toolbar (fixed).

**Comment by stefanneculai** [comment]
Last commit makes the `fullscreen.isActive` method public and could be used to check if in fullscreen mode. 

The inline toolbar is designed to edit the page inline and reflect the changes on the page like they are. It is a bit awkward to enter in fullscreen mode from inline.
