### ISSUE TITLE
Is customPopup really working?

### ISSUE THREAD

**Issue by connect-technologies** [froala/wysiwyg-editor#826]
I tried to implement a own popup and tried the code from https://www.froala.com/wysiwyg-editor/v2.0/docs/concepts/custom-popup
But I couldn't figure out, how it is done.

Are e.g. the $ for the javascript vars really right?
e.g.:
`// Get the popup object defined above.`
`var $popup = editor.popups.get('customPlugin.popup');`

**Comment by stefanneculai** [comment]
At the bottom of the [Custom Popup Concept](https://www.froala.com/wysiwyg-editor/v2.0/docs/concepts/custom-popup) there is the full code for the popup. As a convention we're using `$var_name` for variables that are jQuery objects.
