### ISSUE TITLE
Placeholder text gets bigger upon editor focus

### ISSUE THREAD

**Issue by philfreo** [froala/wysiwyg-editor#828]
Latest master.

Before focusing cursor into editor the placeholder text is a smaller font size than after.

HTML Before:

<img width="731" alt="screenshot 2015-10-06 22 48 03" src="https://cloud.githubusercontent.com/assets/97612/10327967/5e7da7ac-6c7c-11e5-85c9-fa56fa67a481.png">

HTML After:

<img width="746" alt="screenshot 2015-10-06 22 48 09" src="https://cloud.githubusercontent.com/assets/97612/10327970/62402324-6c7c-11e5-8a0f-5cc4c64edcfd.png">

I can't quickly reproduce this in a jsfiddle, but it does seem like a bug...

**Comment by philfreo** [comment]
Not easily... it's not live anywhere, but it's still happening on today's latest master. If you still can't figure it out let me know by email and I can setup a localhost tunnel for you.

**Comment by stefanneculai** [comment]
That would be great. If you don't want to make it public just email the details over to me.

**Comment by stefanneculai** [comment]
Just for reference, this issue happens when the editor is not in the DOM at the initialization time. As a fix, it is necessary to call `$('#edit').froalaEditor('placeholder.refresh');` after the editor gets in the DOM.
