### ISSUE TITLE
Windows 7 Chrome Hangul, Japanese language typing problems.

### ISSUE THREAD

**Issue by largeden** [froala/wysiwyg-editor#829]
This problem has been found in the image below RC3.

Windows 7 Chrome 45.0.2454.101 m
(Firefox is not a problem. and OS X Chrome is not a problem.)

https://www.dropbox.com/s/xel7ium8pwgsl4f/windows7_chrome.mov?dl=0

Test methods

1) Enter any key Korean.
2) Japanese Mode is difficult to explain.
- Make additional Japanese ROMAJI.
- following input key.
```
rensyuu + space x 3
```

The problem appears with the following functions.

froala_editor.min.js
_positionCaret()

Exactly it occurs in the following function.
getBoundingRect()

Improve the problem in Firefox, but I did not test well in other browsers.
I'm sorry.

**Comment by stefanneculai** [comment]
Last commit should fix it. Could you please give it a try and let us know if there is any other problem. Thank you!

**Comment by largeden** [comment]
@stefanneculai 

The problem has been resolved.
The remaining issue is only #806  :)

**Comment by stefanneculai** [comment]
Great! We're working on that issue.
