### ISSUE TITLE
Caret goes under toolbar when position:fixed and toolbarStickyOffset is non-zero

### ISSUE THREAD

**Issue by chrisdavies** [froala/wysiwyg-editor#834]
First, thanks for the awesome editor!

Browser: Chrome
Version: latest release of v2

Steps:

- Configure the toolbar to be fixed on scroll with a non-zero value for toolbarStickyOffset
- Scroll down so the toolbar is in position:fixed mode
- Use the up arrows (or make a mouse selection, dragging upwards) to put the caret under the toolbar

Expected: the caret cannot go under the toolbar, and the page should scroll about 1/2 way down the way it does in most editors
      
Actual: The caret can go under the toolbar, as seen below:

<img width="819" alt="screen shot 2015-10-07 at 4 16 47 pm" src="https://cloud.githubusercontent.com/assets/833377/10349883/db13870e-6d0e-11e5-93fc-9be4325e35af.png">

NOTE: I have a workaround using lots of window.getSelection and ranges and stuff, but it's complicated!

**Comment by stefanneculai** [comment]
Last commit fixes this. It's not working when selecting with mouse, but works fine when navigating with the arrow keys. It's the best we can get for now.
