### ISSUE TITLE
New link modal causes screen to jump/scroll unexpectedly

### ISSUE THREAD

**Issue by chrisdavies** [froala/wysiwyg-editor#835]
Browser: Chrome
Version: latest release of V2

Steps:

- Fixed toolbar with non-zero value for `toolbarStickyOffset` (not sure if this matters)
- Scroll down so the toolbar is fixed
- Select some text in the editor/contenteditable section
- Click the "new link" icon
- Instead of canceling, click somewhere else in the editor/contenteditable section

Expected: The caret goes wherever I clicked and the screen doesn't scroll

Actual: The editor jumps to the top

**Comment by stefanneculai** [comment]
What OS are you using? Also, are you using the master version?

**Comment by chrisdavies** [comment]
I am using OSX Yosimite.

As for the version, it is the version that can be found by clicking
"download" here:

https://www.froala.com/wysiwyg-editor/v2.0/pricing

Thanks!
-C-

**Comment by stefanneculai** [comment]
Could you please check it again on the master version? https://github.com/froala/wysiwyg-editor/archive/master.zip

**Comment by chrisdavies** [comment]
Yeah. Sorry for the delay. It sill happens.

**Comment by stefanneculai** [comment]
@chrisdavies Could you please make a video for it?

**Comment by chrisdavies** [comment]
Yup. I'll do it this weekend!

**Comment by chrisdavies** [comment]
Here you go:

https://www.youtube.com/watch?v=UfNriX56XIg
