### ISSUE TITLE
Placeholder text does not work as in the HTML5 spec

### ISSUE THREAD

**Issue by chrisdavies** [froala/wysiwyg-editor#837]
Browser: Chrome
Version: latest of v2

Per the spec:

> User agents should present this hint to the user, after having stripped line breaks from it, when the element's value is the empty string and the control is not focused (i.e., by displaying it inside a blank unfocused control).

When the Froala editor is in a form that has normal text elements, its placeholder is inconsistent with the rest of the form and causes a little confusion.

I'd suggest adding a `placeholderTextHideOnFocus` option or something.

Expected: When an element is focused, the placeholder text disappears

Actual: The placeholder text remains

**Comment by stefanneculai** [comment]
That's not how inputs work and you can try it on: http://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_input_placeholder.

**Comment by chrisdavies** [comment]
Ah. You are right. I'd written CSS which I had since forgotten about that makes our placeholder text work that way!
