### ISSUE TITLE
Popup for File(s)

### ISSUE THREAD

**Issue by dubcanada** [froala/wysiwyg-editor#839]
Hello,

Similar to Image & Link it would be nice if you clicked in a file link if it showed a popup with options similar to that of Image.

**Comment by stefanneculai** [comment]
We have in plan to create a file manager, however we don't have an estimate for it. 

PS: We use this repo for bug tracking only. For feature requests please contact us via our website: https://www.froala.com/wysiwyg-editor/contact. Thanks!
