### ISSUE TITLE
Froala removes CDN links

### ISSUE THREAD

**Issue by Mark5217** [froala/wysiwyg-editor#841]
Issue 1:
Origin saved code:
`<li><a href="https://www.xyz.com/company/xyz" title="xyz" style="url('https://scontent-frt3-1.xx.fbcdn.net/hphotos-xpa1/v/t1.0-9/12141586_10156224094495389_5588463691919449914_n.jpg?oh=8174dca323dceacfba924c1a7b413841&oe=56CB6271');">xyz</a></li>`

Actual result: An extra space is inserted into the style url after save: "style=
"url('https: //scontent-frt3-1.xx.fbcdn.net..."

Issue2:
Origin saved code with direct CDN link starting from '//':
`<li><a href="https://www.xyz.com/company/xyz" target="_blank" title="xyz" style="url('//scontent-frt3-1.xx.fbcdn.net/hphotos-xpa1/v/t1.0-9/12141586_10156224094495389_5588463691919449914_n.jpg?oh=8174dca323dceacfba924c1a7b413841&oe=56CB6271');">xyz</a></li>`

Actual result: style URL is missing after saving.

Issue3:
Origion saved code:
`<li><a href="https://www.xyz.com/company/xyz" target="_blank" title="xyz" style="background:url('https://scontent-frt3-1.xx.fbcdn.net/hphotos-xpa1/v/t1.0-9/12141586_10156224094495389_5588463691919449914_n.jpg?oh=8174dca323dceacfba924c1a7b413841&oe=56CB6271'');">xyz</a></li>`

Actual result: After saving or switching source mode off and on again "background:" is missing

**Comment by stefanneculai** [comment]
Are you using V2?

**Comment by Mark5217** [comment]
No I'm useing 1.2.8 .

**Comment by stefanneculai** [comment]
We're using this repo for V2. For V1 issues please use: https://github.com/froala/wysiwyg-editor-v1.
