### ISSUE TITLE
Froala 2.x Toolbar does not work in Firefox v34

### ISSUE THREAD

**Issue by chrisdavies** [froala/wysiwyg-editor#842]
OS: Mac OSX El Capitan
Browser: FireFox 34 (and I think it happened on a client machine running v 39)

I can edit the content (contenteditable shows up), but the toolbar never shows up.

This error is displaying in the browser console: `NS_ERROR_FAILURE`

We are trialing Froala to determine if we want to purchase, so I can't give you an accurate line-number for the error.

**Comment by stefanneculai** [comment]
We support `Firefox (Current - 1) and Current versions`. https://www.froala.com/wysiwyg-editor/v2.0/browsers

**Comment by thedotedge** [comment]
@stefanneculai do you plan to extend the supported version range? For example, it breaks with the same error on Firefox 39.0.3 -- which was just 3 months older then current at the time of writing.

**Comment by stefanneculai** [comment]
@chrisdavies @thedotedge are you getting this error on [our website](https://www.froala.com/wysiwyg-editor/)? I have just tried it in both v34 and v39 and I haven't seen any problem.

**Comment by thedotedge** [comment]
I can't reproduce it unfortunately since I don't have Linux environment easily accessible, but some of the users confirmed they are getting those errors with FF 38 and 39 on Linux.

**Comment by mnichols** [comment]
I'm getting toolbar on FF 42.0 on OSX El Capitan but many of the toolbar buttons do not show up, though I see them in the DOM tree. There is no error logged.

**Comment by stefanneculai** [comment]
@mnichols See https://github.com/froala/wysiwyg-editor/issues/843#issuecomment-146927282
