### ISSUE TITLE
Froala Editor V2 new toolbar buttons not shown on Chrome & Safari OSX Yosemite

### ISSUE THREAD

**Issue by rjsmith** [froala/wysiwyg-editor#843]
Steps to reproduce:
On a OSX Yosemite mac:

1. Open Chrome 45. Navigate to https://www.froala.com/wysiwyg-editor/v2.0/docs/examples/full-featured. Look at the toolbar. Missing some buttons including 'emoticons', 'inlineStyle', (see the javascript code below).

![chrome45](https://cloud.githubusercontent.com/assets/678653/10399338/fdd9b06e-6ea9-11e5-96f4-b32b70c4107e.png)

2. Open Safari 9. Navigate to https://www.froala.com/wysiwyg-editor/v2.0/docs/examples/full-featured. Look at the toolbar. Missing some buttons including 'emoticons', 'inlineStyle', (see the javascript code below).

3. Open Firefox 41. Navigate to https://www.froala.com/wysiwyg-editor/v2.0/docs/examples/full-featured. Look at the toolbar. All the missing buttons on the other 2 browsers now appear, and seem to work (e.g. emoticons can be added, :-) )
![firefox41](https://cloud.githubusercontent.com/assets/678653/10399343/058ff23c-6eaa-11e5-916e-e2f6434be16b.png)

**Comment by stefanneculai** [comment]
It scales the buttons list based on the screen size, that's why you don't see it. See https://www.froala.com/wysiwyg-editor/v2.0/docs/options#toolbarButtonsMD.

**Comment by rjsmith** [comment]
ah ok, I see.
So I just tried setting all four toolbarButton - related options to the same set of buttons, assuming this would give the same behaviour as V1, but the FE editor is still removing buttons on small sizes (but not applying the default XS / SM set). What is the logic determining this?

```javascript
      toolbarButtons: froalaEditorStandardButtons,
      toolbarButtonsMD: froalaEditorStandardButtons,
      toolbarButtonsSM: froalaEditorStandardButtons,
      toolbarButtonsXS: froalaEditorStandardButtons,
```

```javascript
froalaEditorStandardButtons = [
  "bold", "italic", "underline", "strikeThrough",
  "fontFamily", "fontSize", "emoticons",
  "|", "color", "paragraphFormat", "align", "formatOL", "formatUL", "outdent", "indent", "clearFormatting",
  "|", "insertLink", "insertTable", 
  "|", /*"undo", "redo",*/ "save"];
```

I get this series of toolbars at different widths:
![toolbarbuttonslarge](https://cloud.githubusercontent.com/assets/678653/10400540/41f652aa-6eb1-11e5-9913-70e9fe6da03a.png)
![toolbarbuttonsmedium](https://cloud.githubusercontent.com/assets/678653/10400538/41f0b110-6eb1-11e5-801b-ec2e78f58d1b.png)
![toolbarbuttonssmall](https://cloud.githubusercontent.com/assets/678653/10400539/41f48a7e-6eb1-11e5-8020-71b23e6297da.png)
![toolbarbuttonsextrasmall](https://cloud.githubusercontent.com/assets/678653/10400546/47d1a710-6eb1-11e5-8642-248c0573c425.png)

**Comment by stefanneculai** [comment]
You might be doing something wrong when passing the options. See: https://jsfiddle.net/094spee6/12/embedded/result/.

**Comment by rjsmith** [comment]
Oh that's interesting thanks. Might be an issue with froala:reactive .. thanks, will have another dig....

**Comment by rjsmith** [comment]
Doh! my mistake in my code elsewhere, sorry for wasting your time....

**Comment by mnichols** [comment]
@stefanneculai Thanks for this...I didnt think this is related to my problem on FF 42 since my code worked fine on Chrome, however I overlooked 'toolbarsButtonsSM' and probably FF has different conclusion about my browser size than Chrome. I am not sure how to make this more prominent in docs but I know it is a tricky bit to track down.
Here is relevant code that _does_ work on FF 42 in case anyone cares...it is lame coffeescript, sorry.
Note that I am using an inline toolbar here too. 
```
  render: ->
    
    toolbarButtons = [
          'bold'
        , 'italic'
        , 'underline'
        , 'strikeThrough'
        , 'quote'
        , 'insertLink'
        , 'clearFormatting'
        , '-'
        , 'paragraphFormat'
        , 'formatOL'
        , 'formatUL'
        , 'align'
        , 'indent'
        , 'outdent'
        , 'emoticons'
    ]

     inlineFroalaOptions = {
        key: @getApiKey()
        toolbarInline: true
        charCounterCount: false
        toolbarButtons: toolbarButtons
        toolbarButtonsMD: toolbarButtons
        toolbarButtonsSM: toolbarButtons
        toolbarButtonsXS: toolbarButtons
        htmlAllowedTags: ["code", "span", "label", "a", "br", "p", "b", "i", "del", "strike", "u", "blockquote", "mark", "cite", "small", "ul", "ol", "li", "hr", "dl", "dt", "dd", "sup", "sub", "big", "pre", "figure", "figcaption", "strong", "em", "table", "tr", "td", "th", "tbody", "thead", "tfoot", "h1", "h2", "h3", "h4", "h5", "h6"]
        toolbarVisibleWithoutSelection: true # keeps toolbar visible while typing
        zIndex: 9000 #toolbar and popups z-index; see _zindex.scss for other layers this must accommodate
        linkAlwaysNoFollow: true
        fontFamily: {
            'Oswald,sans-serif': 'Oswald'
            '\'Helvetica Neue\',sans-serif': 'Helvetica Neue'
            'Helvetica,sans-serif': 'Helvetica'
            'Arial,sans-serif': 'Arial'
        }
    }
```

    #inject a textarea to bind our editor to because synapse.
    @editorEl = $target = $('<textarea></textarea>')
    $target.addClass('body-editable-value')
    @$el.empty().append($target)
    $target.froalaEditor(inlineFroalaOptions)
    
```
