### ISSUE TITLE
Uncaught TypeError: Cannot read property 'hide' of undefined

### ISSUE THREAD

**Issue by santup** [froala/wysiwyg-editor#845]
In V2, I am trying to initialize editor on click of dom element then i am getting  
``` "Uncaught TypeError: Cannot read property 'hide' of undefined" ``` error in console. I am able to do it well in v1, but I want to use V2 for its more advanced options,methods and events. 

Sample Code is below:
html
```<h1>Toolbar Inline</h1>
<ul id='edit2'><li>Vivamus nec rutrum augue, pharetra faucibus purus. Maecenas non orci sagittis, vehicula lorem et, dignissim nunc.</li> </ul>```

JS
``` $(function(){
      $(document).off('click').on('click',function(e){
        var e = e || window.event;
        if (e.target){
            element = e.target;
        } 
        else if (e.srcElement) {
            element = e.srcElement;
        }
        $(element).froalaEditor({           
          toolbarInline: true,
          toolbarButtons: ['bold', 'italic', 'underline', 'strikeThrough', 'color', 'emoticons', '-', 'paragraphFormat', 'align', 'formatOL', 'formatUL', 'indent', 'outdent', '-', 'insertImage', 'insertLink', 'insertFile', 'insertVideo', 'undo', 'redo']   
        })
      })
```
I am getting popup like below picture, expecting inline-toolbar popup.
![inline](https://cloud.githubusercontent.com/assets/3683919/10417490/36369046-705b-11e5-9997-cc07e21b36ce.png)

Thank you in advance.

**Comment by stefanneculai** [comment]
In V2, the editor can be initialized on <div> and <textareas> elements and you will get the default editor. If it is initialized on another element, then the `editInPopup` option is enabled.

**Comment by santup** [comment]
Hi,
Thanks for your quick reply. But I am afraid I am not understanding it (something is missing!) 
In V2, the editor can be initialized on ..................... ?

**Comment by stefanneculai** [comment]
Sorry, I forgot to escape those: `<div>` and `<textarea>`.

**Comment by devmondo** [comment]
hi,
i am facing the same error, and sometimes we want to initialize it on ```h1``` element but keep advanced options, so is there a way to disable the popup mode ? i added ```editInPopup:false ``` to the options but it is not solving anything

thx in advanced.
