### ISSUE TITLE
image.upload / file.upload methods do not work?

### ISSUE THREAD

**Issue by voidale** [froala/wysiwyg-editor#849]
I'm trying to do the following:

`$().froalaEditor('image.upload', e.originalEvent.dataTransfer.files[0])` there is no error and nothing is uploaded what is wrong? I have configured amazon s3 uploads does it work with it? I'm trying to initiate upload when the files are being dropped on div with editor not available yet here is the code

	'drop .note-new': function (e, t) {
		e.preventDefault();
		e.stopImmediatePropagation();
		Froala.invokeFroalaEditor(t); // this initialize the editor before the upload
		console.log(e.originalEvent.dataTransfer.files); // i can see the file
		t.$('.note-new').froalaEditor('image.upload', e.originalEvent.dataTransfer.files[0]) // nothing happens
	},

**Comment by stefanneculai** [comment]
It looks there is a documentation problem on our website. You should call it: `t.$('.note-new').froalaEditor('image.upload', e.originalEvent.dataTransfer.files)`.

**Comment by stefanneculai** [comment]
We have updated the docs.

**Comment by voidale** [comment]
@stefanneculai I'm trying to upload images/files from external button is this possible? Invoking `image.upload` method throws an error `Cannot read property 'find' of undefined` looks like it's looking to invoke the popup? Can't I handle the the uploads with my custom inputs? Thanks.

**Comment by stefanneculai** [comment]
It looks like you don't have a button for inserting the image inside the editor toolbar and that's why the error is being thrown. Could you confirm that?

**Comment by voidale** [comment]
Hi Stefan, I'm trying to do this with external button not in froala.

**Comment by stefanneculai** [comment]
Please make a jsFiddle. We cannot reproduce it.

**Comment by stefanneculai** [comment]
We managed to replicate the issue. It is not necessary to call `$('#content').froalaEditor('popups.show', 'image.insert');`, you just have to use `$('#content').froalaEditor('image.upload', e.currentTarget.files);`.
