### ISSUE TITLE
API Feature: selection state (bold/italic/...)

### ISSUE THREAD

**Issue by marek-hanzal** [froala/wysiwyg-editor#850]
Selection := selection has position and can have zero length (which is only cursor position). (for this issue)

Currently there is no way, how to check current selection state.

Idea is:
`$('<selector>').froalaEditor('selection.properties')` which return array of string properties (or applied styles/classes).
e.g.
- **b** => `['bold']`
- **_b_** => `['bold', 'italic']`
- `<span class="some class here">...</span>` => `['class' => ['some', 'class', 'here']]`

Important is to translate common states into string representation (italic, bold, underline, strikes, ...).

**Comment by stefanneculai** [comment]
Thanks for the suggestion. However, we consider this as being out of the editor's context and there are not too many users who would use it. That can be easily implemented by someone who needs such a feature by using the `selection.element` method to get the current selection element and then checking the parent nodes for other properties.

**Comment by marek-hanzal** [comment]
Thanks for reply - soo.... it seems that it is **not** easy as its JavaScript, so there are maany incosistencies or it is relatively boilerplatish to query basic stuff like bold, italics, ...

**Comment by stefanneculai** [comment]
I put this on our TODO list and we'll see if there is a way we could add it in the editor, maybe as a different separate plugin.

**Comment by marek-hanzal** [comment]
Thank you. I was a little bad - document.queryCommandState partially works, but... it can be better.

I think that this is a general problem (not targeted to Froala) - some abstract layer to which one can put query and retrieve abstract node information...
