### ISSUE TITLE
froalaEditor.initialized is not fired

### ISSUE THREAD

**Issue by benjaminfunk** [froala/wysiwyg-editor#854]
```
jQuery('textarea.news-editable').froalaEditor(
{
	// ...
}).on('froalaEditor.initialized', function (objEvent, objEditor)
{
	alert(1);
});
```

The event initialized is not fired :( 

Edit: V2 RC3

**Comment by noyg** [comment]
@benjaminfunk what was the problem?

**Comment by stefanneculai** [comment]
The initialized event should be bind before initializing the editor.
```js
$(selector).on('froalaEditor.initialized', function (e, editor) {
}).froalaEditor();
```

**Comment by lmiller1990** [comment]
Just had this problem - might be nice to make this clear in the docs. Sorry for the bump @stefanneculai 

I'd be interested in making a PR with a small few updates, been using Froala heavily at my org and hit some gotchas. Do you accept docs PRs?

**Comment by stefanneculai** [comment]
@lmiller1990 we'll definitely make that clear in the docs. We don't accept PR to docs, however, if you could send any suggestions you have on https://www.froala.com/wysiwyg-editor/contact we can definitely add them. Thanks in advance.
