### ISSUE TITLE
V2 inserting table throws Reference Error: editor is not defined

### ISSUE THREAD

**Issue by rjsmith** [froala/wysiwyg-editor#859]
Steps to reproduce:
1. Go to https://www.froala.com/wysiwyg-editor/v2.0/docs/examples/full-featured
2. Use table toolbar button to insert a new table.
3. Observe the browser console, can see a reported error:

```
Uncaught ReferenceError: editor is not definede.FroalaEditor.RegisterCommand.callback @ application-86244d05714ffffcc283d3b82beac9ef.js:13n @ application-86244d05714ffffcc283d3b82beac9ef.js:6i @ application-86244d05714ffffcc283d3b82beac9ef.js:8a @ application-86244d05714ffffcc283d3b82beac9ef.js:8o @ application-86244d05714ffffcc283d3b82beac9ef.js:8f @ application-86244d05714ffffcc283d3b82beac9ef.js:7(anonymous function) @ application-86244d05714ffffcc283d3b82beac9ef.js:7at.event.dispatch @ application-86244d05714ffffcc283d3b82beac9ef.js:2at.event.add.m.handle @ application-86244d05714ffffcc283d3b82beac9ef.js:2
```

I think the error is on line 2319 in table.js ...

```javascript
editor.popups.hide('table.insert');
```
Should be `this.popups.hide('table.insert')` ?

**Comment by stefanneculai** [comment]
It was just a problem on our website not loading the correct editor version. This is not an issue in RC3.

**Comment by rjsmith** [comment]
@stefanneculai I see this issue in RC3, both in the code installed via the froala:meteor script, and in this jsfiddle using RC3 from cdn:

https://jsfiddle.net/rj_smith/658gcszz/embedded/result/

**Comment by stefanneculai** [comment]
Indeed, it was fixed just after the RC3 release #833.

**Comment by rjsmith** [comment]
ah. ok look forward to RC4!

**Comment by stefanneculai** [comment]
It won't be RC4, but production ready release. :-)
