### ISSUE TITLE
Tables plugin: ability to specify additional css classes on inserted <table> elements

### ISSUE THREAD

**Issue by rjsmith** [froala/wysiwyg-editor#860]
I want to be able to ensure that html tables inserted by users in a Froala Editor instance in my Bootstrap - styled application are also styled using Bootstrap table css classes.

As a workround in V1, I overrode the `$.FroalaEditable.prototype.insertTable` function to achieve this (as suggested by @stefanneculai), which worked well.

A simple `tableClass` option might work well (which can be set to a space - separated list of classes) so I can add `table table-striped table-bordered table-condensed`. 

In the short-term, could you propose a similar workround?

**Comment by stefanneculai** [comment]
You could override the insert table command and insert the table the way you want.

```js
$.FroalaEditor.RegisterCommand('insertTable', {
    title: 'Insert Table',
    undo: false,
    focus: true,
    refreshOnCallback: false,
    popup: true,
    callback: function () {
      if (!this.popups.isVisible('table.insert')) {
        this.table.showInsertPopup();
      }
      else {
        this.popups.hide('table.insert');
      }
    }
  });
```

**Comment by rjsmith** [comment]
Hi, the code you posted above is related to opening the insert table popup from the FE toolbar? I am OK with that feature .. it's just I want to add additional classes to the table element that is added to the html in this function in table.js:

```javascript
    /*
     * Insert table method.
     */
    function insert (rows, cols) {
      // Create table HTML.
      var table = '<table style="width: 100%;"><tbody>';
      var cell_width = 100 / cols;
      var i;
      var j;

      for (i = 0; i < rows; i++) {
        table += '<tr>';

        for (j = 0; j < cols; j++) {
          table += '<td style="width: ' + cell_width.toFixed(4) + '%;">';
          if (i === 0 && j === 0)table += $.FroalaEditor.MARKERS;
          table += '<br></td>';
        }
        table += '</tr>';
      }
      table += '</tbody></table>';

      editor.html.insert(table);

      // Update cursor position.
      editor.selection.restore()
    }

```

**Comment by stefanneculai** [comment]
Then you should change the `tableInsert` command.
```js
<script>
  $.FroalaEditor.RegisterCommand('tableInsert', {
    callback: function (cmd, rows, cols) {
      this.table.insert(rows, cols);
      this.popups.hide('table.insert');
    }
  });
</script>
```

**Comment by george-norris-salesforce** [comment]
But how to actually insert classes into table? Rows, cols are just number arguments. Is there a means to get a reference to the HTML before it is inserted and patch it with a class? @stefanneculai
