### ISSUE TITLE
Table break option in none froala tables

### ISSUE THREAD

**Issue by benjaminfunk** [froala/wysiwyg-editor#861]
The table break option appears on tables which are not inside the editor. Nevermind the editor has content or not

![froala-table-error](https://cloud.githubusercontent.com/assets/856290/10540873/58db150e-740c-11e5-83fc-fbd253e466a5.jpg)

**Comment by stefanneculai** [comment]
This looks like a possible issue, but we couldn't replicate it. Could you please make a jsFiddle?
