### ISSUE TITLE
Feature: commands.clearFormatting(force=false)

### ISSUE THREAD

**Issue by marek-hanzal** [froala/wysiwyg-editor#862]
Current method will not clean everything (so it is not much useful with external inlines).

Spans in given code will survive

```html
<p>
    <span class="cheche">Vestibulum&nbsp;</span>
    <span class="code">pellentesque</span> tellus sagittis,
    <span class="important">pulvinar</span> dui eget, sodales ip
	<br>sum.
</p>
```

It would be nice to have option which will force cleanup even when there are custom spans (preffered)/other elements (eventually).

**Comment by stefanneculai** [comment]
I am closing this as this is a feature-request and we don't keep them here anymore.
