### ISSUE TITLE
Wrong HTML edits.

### ISSUE THREAD

**Issue by gsabater** [froala/wysiwyg-editor#865]
Hello, i have been testing the editor in order to see if it fits my need before buying a license for it, and, even all the features look pretty awesome and might be the best WYSIWYG editor out there, i've found a specific scenario where i dont know if this behaviour is intended or if i'm missing some option, or its a bug.

Using the 2.0 RC3 version provided in the website, I wrapped with the editor some HTML code:
```HTML
<a href="#" class="image avatar"><img src="images/avatar.jpg" alt="" /></a>
<h1><strong>text</strong> lorem ipsum<br />
dolor sit amet. <a href="http://link.net">Link</a>.</h1>
```

The editor is just a < div > over the previous fragment, and when initialized, the editor automatically adds a < p > to the first link, completelly breaking the web layout.

Also, on the same topic of breaking layouts, the editor keeps adding margin-top and margin-bottom  (via class or via style) to images. Until now it has added fr-dii and fr-dib.

What should be the proper way to address those issues? I mainly want the editor in its [inline toolbar always visible](https://www.froala.com/wysiwyg-editor/v2.0/docs/examples/always-visible) mode, so our users can edit fragments of code in their profiles in  a simple way while keeping the layout intact. Is this editor recommended for this purpose? I have studied all methods and options, but i cannot see which could be the proper way to let the editor alter the text and image properties without breaking the DOM structure.

Thanks in advance

**Comment by stefanneculai** [comment]
You should use the enter and set it to `$.FroalaEditor.ENTER_BR` if you don't want to have the HTML wrapped into P tags. 

By default, the editor is adding a margin to images to that they look good when they are being edited. However you could change the CSS for that.

We use this repo for bug tracking. For tech questions please [contact us](https://www.froala.com/wysiwyg-editor/contact) via our website.
