### ISSUE TITLE
core.hasFocus method returning wrong status

### ISSUE THREAD

**Issue by swolfod** [froala/wysiwyg-editor#866]
I just upgraded to rc3 version of the editor, and it broke the Reactjs web app I am building.

After hours of debugging, I found out that it was because the `core.hasFocus` method in the froala_editor.js file was not returning the correct result and leaves orphaned markers in the DOM, which breaks the React virtual DOM. When I change it back to `editor.$el.is(":focus")` as it was in rc2, everything is working again.

I am not sure why the `core.hasFocus()` method is returning different result, and I am assuming it is a bug. For now I modified the method and make it returns `editor.$el.is(":focus")`. Please let me know if I am doing it wrong.

**Comment by stefanneculai** [comment]
Could you please test last commit and let me know if it fixes the problem? Thank you.

**Comment by swolfod** [comment]
No, it doesn't.

**Comment by stefanneculai** [comment]
Could you make a jsFiddle for it?

**Comment by stefanneculai** [comment]
@swolfod could you please make a jsFiddle for it? Thanks.

**Comment by swolfod** [comment]
Sorry for late responding. The latest commit did fix it, thx!
