### ISSUE TITLE
insertLink plugin toggle problems.

### ISSUE THREAD

**Issue by largeden** [froala/wysiwyg-editor#868]
Callback is not working properly in the following code.

Miss the typing but the cause does not return this.popups.isVisible ('link.insert').

```javascript
  // Register the font size command.
  $.FroalaEditor.DefineIcon('insertLink', { NAME: 'link' });
  $.FroalaEditor.RegisterShortcut(75, 'insertLink');
  $.FroalaEditor.RegisterCommand('insertLink', {
    title: 'Insert Link',
    undo: false,
    focus: true,
    refreshOnCallback: false,
    popup: true,
    callback: function () {
      if (!this.popups.isVisible('link..insert')) {
        this.link.showInsertPopup();
      }
      else {
        this.popups.hide('link..insert');
      }
    }
  })
```

**Comment by largeden** [comment]
@stefanneculai 
This problem was not fixed.

Last commit has been v2.0.0 rc3 and other operations.

popup button does not toggle
insertLink
insertImage
insertVideo
insertFile

popup button does toggle
color
table
emoticons

This should not toggle all the plugins will not function under operation.
this.popups.isVisible()

Is this correct view of the current operation?

**Comment by stefanneculai** [comment]
Last commit fixes it.

**Comment by largeden** [comment]
@stefanneculai 

Great! :)
