### ISSUE TITLE
Feature: onChange event

### ISSUE THREAD

**Issue by marek-hanzal** [froala/wysiwyg-editor#869]
If there is no other way (...DOMSubtreeModified...?), how to check if content was changed, it would be nice, if there will be onChange (content was updated) event, eventually onSelectionChange (selection was altered) event.

It must work even on textarea (...input in general) and on content editable DOM tree.

**Comment by stefanneculai** [comment]
There is already an event for that: https://www.froala.com/wysiwyg-editor/v2.0/docs/events#contentChanged. It does not uses the DOMSubtreeModified because that decreases a lot the performance.

**Comment by marek-hanzal** [comment]
Sorry, I've overlooked it. Thanks :)
