### ISSUE TITLE
How to render MathJax equations?

### ISSUE THREAD

**Issue by dongli** [froala/wysiwyg-editor#872]
We just tried Froala, which is a brilliant editor. One thing that is not perfect is we can not input MathJax equations more than one line. For example, we input such equations in LaTeX format:

```
\begin{eqnarray}
  x + y & = 1\\
  x - y & = 0
\end{eqnarray}
```

Froala gives us:

```
<p>\begin{eqnarray}</p>

<p>&nbsp; x + y &amp; = 1\\</p>

<p>&nbsp; x - y &amp; = 0</p>

<p>\end{eqnarray}</p>
```

This causes problem with MathJax! So what we can do here? How to tell Froala that this text block should not been manipulated?

**Comment by stefanneculai** [comment]
If you want to avoid having the text wrapped in `P` tags then you should put all the text inside a `DIV`.
