### ISSUE TITLE
How can i remove  title tag Content from editor

### ISSUE THREAD

**Issue by sreelalks** [froala/wysiwyg-editor#878]
When i  paste html code to froala editor and change code view to view mode then the title content displayed at the top. how can we remove that content.?

**Comment by stefanneculai** [comment]
Please let us know the steps to reproduce the problem.

**Comment by sreelalks** [comment]
first i click on a 'code view' button then paste my html code including doctype, html tag, body tag, and title tag. then click again on the button 'code view' now i can see design part but the top corner display text that is title of my inserted code. i need to remove that. plz help me.

**Comment by stefanneculai** [comment]
You can control that through: https://www.froala.com/wysiwyg-editor/v2.0/docs/options#htmlAllowedTags.

We use this repo for bug tracking and not for tech support. For support please contact us through our website.
