### ISSUE TITLE
IE drag&drop image area didn't work

### ISSUE THREAD

**Issue by kotmatpockuh** [froala/wysiwyg-editor#882]
In ie (both 10 and 11) didn't work image drop (only click on image browser upload works): in v1. In v2: cursor appear, and click on area didn't work: http://prntscr.com/8wlg9z

**Comment by stefanneculai** [comment]
Fixed in V2. 

For V1, please report any issue on https://github.com/froala/wysiwyg-editor-v1. We strive to keep the record of the issues separate for a better management. Thanks!
