### ISSUE TITLE
Feature request: Adding custom classes to inserted tables

### ISSUE THREAD

**Issue by ikurpis** [froala/wysiwyg-editor#886]
Hello, I just wanted to suggest a feature that is missing in my opinion and it was discussed only as workaround by changing ```tableInsert``` command.
Similar option like ```paragraphStyles``` and ```linkStyles``` should be implemented also for tables plugin (```tableStyles``` perharps).

For example, I use Froala Editor for custom CMS app, so it is really important to have a styling control over inserted elements.

I hope that devs will consider this feature.
Thank you

**Comment by stefanneculai** [comment]
Thanks for the suggestion. We don't accept feature requests here and we're keeping this repo as a bug tracker only. That can be easily achieved through a [custom dropdown](https://www.froala.com/wysiwyg-editor/v2.0/docs/concepts/custom-dropdown) as well.
