### ISSUE TITLE
Popups can overflow container

### ISSUE THREAD

**Issue by felskov** [froala/wysiwyg-editor#888]
When embedding the editor into a scrollable container, popups will render partially hidden (see screenshot) if they're far enough towards the end of the container.

<img width="639" alt="screen shot 2015-11-01 at 19 46 12" src="https://cloud.githubusercontent.com/assets/1436954/10870704/429f93f6-80d1-11e5-9ed0-4e9264ef58b3.png">

Tested using v2.0.0-rc3.

**Comment by felskov** [comment]
My bad - correctly specifying the "scrollableContainer"-option fixes this issue.

**Comment by kotmatpockuh** [comment]
@felskov 
what would be, if your container is very small? http://i.imgur.com/pOCqZdU.png
which element you set as scrollableContainer?

**Comment by felskov** [comment]
@kotmatpockuh I haven't actually tested this scenario, but it looks like you've found another issue with the editor.

@stefanneculai This could possibly be solved by allowing us to specify both a "scrollableContainer" and a "popupContainer"?

**Comment by kotmatpockuh** [comment]
@stefanneculai 
hey, do you approve, that changing of `scrollableContainer` option changes popup parent?
becouse i tested it in angularjs app - and nothing changed when i set another container...

**Comment by stefanneculai** [comment]
@kotmatpockuh could you make a jsFiddle for it?

**Comment by kotmatpockuh** [comment]
@stefanneculai maybe U have some fiddle with installed plugin, so i can change it a little bit?

**Comment by kotmatpockuh** [comment]
@stefanneculai 

http://plnkr.co/edit/FO9VDEEuAHHHZlV2K2zD?p=preview

popups are not appended to the body:

[! Image](http://i.imgur.com/DGNzSlm.png)

**Comment by stefanneculai** [comment]
The popups are appended to different elements depending on what triggers them:
- when a popup appear after using a toolbar button, it is appended to the toolbar.
- when a popup appear after clicking a link/image/video inside the editor for example, the popups are appended to the scrollable container.

**Comment by kotmatpockuh** [comment]
@stefanneculai is there any way to use all popups with body? (to view whole popup, not just part)?

**Comment by stefanneculai** [comment]
The editor is designed to append the popups this way for an enhanced experience while scrolling and we won't change that. However, you can set `overflow: visible;` in CSS for the elements the editor is in and this way the popups won't get cut.
