### ISSUE TITLE
Paste from Excel is now working in Firefox on Windows, but... no border lines?

### ISSUE THREAD

**Issue by brett-efchub** [froala/wysiwyg-editor#891]
Hello there

Thanks for fixing the issue of not being able to paste from Excel into Firefox on Windows. In testing whether it was fixed we found that border lines are not rendered when pasting from Word or Excel. We use the editor to generate an email and the recipient gets a table without lines.

This is on Windows7, Firefox 42, Office 2010.

The Excel test file: http://efchub.com/assets/Spreadsheet-paste-sample.xlsx
The Word test file: http://efchub.com/assets/MsWord-table-paste.docx

![a3fe5c5089ae8d877d0d0b94f586a692c229a579e439886095 pimgpsh_fullsize_distr](https://cloud.githubusercontent.com/assets/6212892/10882502/fbe67d1e-8173-11e5-8dee-5a223d96363f.png)

**Comment by stefanneculai** [comment]
Have you included the froala_style.min.css CSS file?

**Comment by brett-efchub** [comment]
Hi Stefan, just to give me a bit more info:

We using the editor to generate an email, therefore stylesheets don't apply.What would be awesome is when pasting and the spreadsheet had borders that the borders are applied to actual cells in the table.

Like: <td style="border: solid black 1px;"> 

That way when the email is sent, the table will be rendered correctly in our clients mail client.

**Comment by stefanneculai** [comment]
We're trying to remove the inline style as much as possible and we won't add such an option. You could include the CSS content from the froala_style.min.css in the HEAD of your email. See https://www.froala.com/wysiwyg-editor/v2.0/docs#frontend.
