### ISSUE TITLE
Paste image gives the error "Something went wrong. Please try again." when configured to use S3

### ISSUE THREAD

**Issue by chrisdavies** [froala/wysiwyg-editor#892]
It is not unlikely that this is an issue with my S3 configuration, but having some kind of diagnostic (via `console.log` or something) would be helpful, as I have no idea what is wrong (if anything) with my S3 configuration.

My Ruby code looks like this, in a helper class, and I have confirmed that the values coming out of `ConfigS3.config` are correct:

```ruby
def froala_s3_image_config
    s3_config = {
      region: 's3',
      bucket: ConfigS3.config['bucket'],
      keyStart: 'rte_attachments/',
      acl: 'public-read',
      accessKeyId: ConfigS3.config['aws_access_key_id']
    }

    policy = {
      expiration: 1.day.from_now.iso8601,
      conditions: [
        { bucket: s3_config[:bucket] },
        { acl: s3_config[:acl] },
        { success_action_status: '201' },
        { 'x-requested-with': 'xhr' },
        [ 'starts-with', '$key', s3_config[:keyStart] ],
        [ 'starts-with', '$Content-Type', '' ]
      ]
    }

    s3_config[:policy] = Base64.encode64(policy.to_json)
    s3_config[:signature] = Base64.encode64(
      OpenSSL::HMAC.digest(
        OpenSSL::Digest.new('sha1'),
        ConfigS3.config['aws_secret_access_key'],
        s3_config[:policy]
      )
    ).gsub("\n","")

    return s3_config.to_json
  end
```

And in my JavaScript, I have this, which I will eventually change for caching reasons, but I'm just trying to get it to work!

```js
imageUploadToS3: <%= froala_s3_image_config.html_safe %>,
```

Thanks in advance!

**Comment by chrisdavies** [comment]
I should note:

OSX (latest)
Chrome (latest)

I am getting an image via `Cmd + Ctrl + Shift + 4`, selecting some part of the screen, then pasting into the Froala editor.

**Comment by stefanneculai** [comment]
Are you using the V2 from the master of this repo? I have just tested it and it works fine for me.

**Comment by chrisdavies** [comment]
Ah. Today, when I went back in, I am seeing helpful errors in the developer
console. Either I somehow missed them yesterday, or something else was
wrong!

I should be able to dig into my configuration problems now. Sorry for the
false alarm.
