### ISSUE TITLE
Error: Permission denied to access property "nodeType"

### ISSUE THREAD

**Issue by sreelalks** [froala/wysiwyg-editor#894]
When i click "number input" field get this error,
![capture](https://cloud.githubusercontent.com/assets/8914381/10933861/9cd990ba-8301-11e5-9135-b869211767d2.PNG)
Can you please help me?

**Comment by stefanneculai** [comment]
Please send us more details. Where is the input field?

**Comment by sreelalks** [comment]
Thanks for ur reply,
I have a html page there is one input number type field when clicking on
the down arrow geting thos type error. Input field out side the froala
editor. Editor working perfectly but get this error. I think this is editor
prblm..
If u have any doubt plz reply me..
