### ISSUE TITLE
HTML Paste Issue

### ISSUE THREAD

**Issue by rblin081** [froala/wysiwyg-editor#896]
Pasting 

in the html view and switching back to editor freezes the application. Seems to break the regex in 
$.Editable.prototype.tagName.

**Comment by stefanneculai** [comment]
For V1 issues please use https://github.com/froala/wysiwyg-editor-v1. Also, please test the master version because we recently fixed such an issue.

**Comment by rblin081** [comment]
My company bought the license within the past month so we need 1.2.9
unminified, which doesn't seem to be available through the download portal.

**Comment by stefanneculai** [comment]
Unminified JS is available after an official release is made. There will be a new release for V1 in about 2 weeks.

**Comment by rblin081** [comment]
Sounds great, appreciate the response. Have a good day.
