### ISSUE TITLE
Allow for custom hex color to be added in color plugin

### ISSUE THREAD

**Issue by thomasgriffin** [froala/wysiwyg-editor#900]
Is there a way to give the user the ability to add a custom hex color via the color picker popup? I don't see it in the plugin, and I'm not sure how I would go about adding this feature. It should be available for both the text and background areas.

**Comment by stefanneculai** [comment]
No, if you want such a feature then you should implement it on your own. Thanks for the suggestion, but I will close it because we use this repo only for bug tracking.

**Comment by stefanneculai** [comment]
It got into the editor now: https://www.froala.com/wysiwyg-editor.
