### ISSUE TITLE
I can't delete image on server!

### ISSUE THREAD

**Issue by pig800509** [froala/wysiwyg-editor#901]
My Javascript code : 
$(function(){
	$("#edit").editable({
		inlineMode: false, 
		imageUpload: true, 
		imageUploadURL: 'upload_image.php',
		imageDeleteURL: 'delete_image.php'
	})
	.on('editable.afterRemoveImage', function (e, editor, $img) {
		editor.options.imageDeleteParams = {src: $img.attr('src')};
		editor.deleteImage($img);
	});
});

PHP : 
<?php
    $src = $_POST["src"];
    if (file_exists(getcwd() . $src)) {
      unlink(getcwd() . $src);
    }
?>

I did exactly same code in 
https://www.froala.com/wysiwyg-editor/docs/server-integrations/php-delete-image

I have tried $src = urldecode($_POST["src"]); It's not working .....
I only can upload image.
no error message appear on my chrome console.

**Comment by stefanneculai** [comment]
We offer tech support under the Advanced/OEM license via our website: https://www.froala.com/wysiwyg-editor/contact. If you have such a license please contact us there. Thank you.
