### ISSUE TITLE
destroy () without returning the element back to its pre-init state.

### ISSUE THREAD

**Issue by voidale** [froala/wysiwyg-editor#902]
This can be useful in meteor/react because the element will get updated automatically I need to destroy Froala without it doing anything. If it's not too hard to modify that function that can be great. Thanks Stefan!

**Comment by stefanneculai** [comment]
@voidale Is this a common behaviour of the destroy method?

**Comment by voidale** [comment]
@stefanneculai well I don't know, but it seems useful, I use 'html.get' to get the content and destroy froala. It makes sense if froala is used inside a popup as well possibly. I ended up just changing templates and it seems to work. This feature-request is just a suggestion if it's complicated you probably can avoid it. But if it's easy to allow us the users to choose if we to keep the content or destroy I see a lot of potentional. p.s thanks for the at.js work around !
