### ISSUE TITLE
froala v2 with at.js bug with "enter"

### ISSUE THREAD

**Issue by voidale** [froala/wysiwyg-editor#903]
@stefanneculai 
I found a working example with 1.2.8
http://jsfiddle.net/8myoLgLy/4/

But there is a problem with the same jsfiddle as above with v2  http://jsfiddle.net/b9r8kx9c/

specifing @ and clicking enter doesn't work right, something with the way enter is handled. Is it possible you guys can fix this? At.js seems like an awesome library and I would love to add it to the awesome Froala editor :)

Edit: updated latest at.js just in case http://jsfiddle.net/g3oL1yLq/

**Comment by stefanneculai** [comment]
Here is the updated JS for V2: http://jsfiddle.net/froala/qy5w5va7/.
