### ISSUE TITLE
Korean Typing problem.

### ISSUE THREAD

**Issue by largeden** [froala/wysiwyg-editor#904]
https://www.dropbox.com/s/5vfrjqf3hya3o1i/typing3.mov?dl=0

froala editor :  latest version commit.
OS/Browser : windows 7 / Chrome

I've found a new korean input problem in windows 7 chrome browser.

This problem appears from the commit version below.

https://github.com/froala/wysiwyg-editor/commit/ae1899de9701c2f279d68cfe5279e0ea33fcde8d

**Comment by stefanneculai** [comment]
Thanks. Could please you let us know the keys you're pressing on the QUERTY keyboard as usually?

**Comment by largeden** [comment]
Korean QUERTY mode.

Case 1.
ㄱ + ㅏ + ㄴ + ㅏ -> backspace x 3 ~
r + k + s + k -> backspace x 3 ~

Case  2.
ㄱ + ㅏ + ㄴ + ㅏ -> backspace x 1 -> space
r + k + s + k -> backspace x 1 -> space

**Comment by largeden** [comment]
@stefanneculai 
Great! 
I know all the Korean issue has been resolved.
Thanks. :p
