### ISSUE TITLE
"Quote" is not localized

### ISSUE THREAD

**Issue by cecilialam** [froala/wysiwyg-editor#906]
Hi,
I moved along the V2.0 editor toolbar and found out that "Quote" is not being localized. So does its dropdown menu. 
<img width="348" alt="screen shot 2015-11-09 at 2 34 17 pm" src="https://cloud.githubusercontent.com/assets/1245619/11044291/121ca196-86ef-11e5-97b3-2a24ef02f8ac.png">
<img width="391" alt="screen shot 2015-11-09 at 2 34 33 pm" src="https://cloud.githubusercontent.com/assets/1245619/11044292/121fe752-86ef-11e5-9eba-40bb96dd3a23.png">

I double checked with the language files and I cannot find the "Quote", "Increase" and "Decrease" strings.

Thanks and regards
Cecilia

**Comment by stefanneculai** [comment]
It is in the master version of the repo.

**Comment by cecilialam** [comment]
thanks. found it.
