### ISSUE TITLE
Image uploading to froala server gives 500

### ISSUE THREAD

**Issue by harshalkumar** [froala/wysiwyg-editor#907]
I have started getting following error all of a sudden while uploading an image since today morning . I am using i.froala.com/upload to temporary upload the image and downloading it at service side. Right now I am unable to do that due to following error 500 from froala server. 

Failed to load resource: the server responded with a status of 500 (Internal Server Error)
edit:1 XMLHttpRequest cannot load http://i.froala.com/upload. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://directpublishing-dev.highwire.org' is therefore not allowed access. The response had HTTP status code 500.

Thanks,
Harshal

**Comment by stefanneculai** [comment]
Images are stored on our servers only temporary and they might be deleted at anytime. If you're looking for a permanent storage solution then you should implement image upload to your own server. Please see: https://www.froala.com/wysiwyg-editor/v2.0/docs/concepts/image-upload
