### ISSUE TITLE
Typing text into <span class="fr-video">

### ISSUE THREAD

**Issue by felskov** [froala/wysiwyg-editor#908]
When inserting a video, you can actually type contents into the `<span class="fr-video">`-tag.

See the attached screendump, where some contents before and after the inserted video has been inserted into the fr-video container. This results in display inline / break text not working for this text.

<img width="1440" alt="screen shot 2015-11-10 at 13 47 15" src="https://cloud.githubusercontent.com/assets/1436954/11062729/96eb0e86-87b1-11e5-9bca-010c6719673c.png">

**Comment by stefanneculai** [comment]
It's fixed on master.
