### ISSUE TITLE
Feature Request: Line Height Option

### ISSUE THREAD

**Issue by shaneparsons** [froala/wysiwyg-editor#909]
I think it'd be awesome to have a `lineHeight` option, and I imagine it could work much like the `fontSize` option.

In the options would have to be an auto option (e.g. `fontSize * 1.2`), but other then that, the other defaults could be the result of the `fontSize` defaults `* 1.2` or whatever you have as the default currently.

This will be exceptionally helpful for tweaking the spacing after the headings if needed.

**Comment by stefanneculai** [comment]
Thanks for the suggestion Shane. It's already on our TODo list. We don't accept FR here anymore so I will close it for now.

**Comment by marshmeloo** [comment]
is lineHeight option implemented ?

**Comment by stefanneculai** [comment]
Not yet.

**Comment by traviscrampton** [comment]
how about now?

**Comment by stefanneculai** [comment]
@traviscrampton no, we don't have this feature added yet. Please follow [our changelog](https://www.froala.com/wysiwyg-editor/changelog) to find out when this will be implemented.

**Comment by nitinhayaran** [comment]
we can see what is implemented from changelog, but it'll really help if we could also see estimated timeline for such features.

**Comment by stefanneculai** [comment]
@nitinhayaran unfortunately, we cannot provide an ETA. This is because we are implementing new features based on how many request is there for them and this might change in a matter of days.

**Comment by nitinhayaran** [comment]
@stefanneculai in that case it might make sense to have feature request in github issues only and marked under milestones. 
You guys could always change it but as users of froala we'll also have better understanding on when a feature might come.

**Comment by stefanneculai** [comment]
Thank you for your suggestions however we keep this repo for bug tracking only.

**Comment by brianquirion** [comment]
@JonCatmull wrote a [Line Height Plugin](https://gist.github.com/JonCatmull/9ef6187b4162444b3e58fdcba90b3372) for Froala. You can import the script and use it directly.

**Comment by kaiogabgnell** [comment]
My solution, not the best way, but solved.

$('.your_class_editor').froalaEditor({
                            
                            // Define new inline styles.
                            inlineStyles: {
                              'Line height - 20px': 'line-height: 20px;',
                              'Line height - 22px': 'line-height: 22px;',
                              'Line height - 24px': 'line-height: 24px;',
                              'Line height - 26px': 'line-height: 26px;',
                              'Line height - 28px': 'line-height: 28px;',
                              'Line height - 30px': 'line-height: 30px;'
                            }
                          })

**Comment by kaiogabgnell** [comment]
My solution, not the best way, but solved.

`$('.ckeditor').froalaEditor({
                            
                            // Define new inline styles.
                            inlineStyles: {
                              'Line height - 20px': 'line-height: 20px;',
                              'Line height - 22px': 'line-height: 22px;',
                              'Line height - 24px': 'line-height: 24px;',
                              'Line height - 26px': 'line-height: 26px;',
                              'Line height - 28px': 'line-height: 28px;',
                              'Line height - 30px': 'line-height: 30px;'
                            }
                          })`

**Comment by kaiogabgnell** [comment]
My solution, not the best way, but solved


` $('.ckeditor').froalaEditor({
                            
                            // Define new inline styles.
                            inlineStyles: {
                              'Line height - 20px': 'line-height: 20px;',
                              'Line height - 22px': 'line-height: 22px;',
                              'Line height - 24px': 'line-height: 24px;',
                              'Line height - 26px': 'line-height: 26px;',
                              'Line height - 28px': 'line-height: 28px;',
                              'Line height - 30px': 'line-height: 30px;'
                            }
                          }) `

**Comment by kaiogabgnell** [comment]
My solution, not the best way, but solved

 $('.ckeditor').froalaEditor({

                        // Define new inline styles.
                        inlineStyles: {
                          'Line height - 20px': 'line-height: 20px;',
                          'Line height - 22px': 'line-height: 22px;',
                          'Line height - 24px': 'line-height: 24px;',
                          'Line height - 26px': 'line-height: 26px;',
                          'Line height - 28px': 'line-height: 28px;',
                          'Line height - 30px': 'line-height: 30px;'
                        }
                      })
