### ISSUE TITLE
Sticky toolbar inside scrollable parent

### ISSUE THREAD

**Issue by felskov** [froala/wysiwyg-editor#910]
The sticky toolbar doesn't work when embedded into a scrollable parent - there seems to be some issue calculating when to enable sticky positioning. I tested using the v2.0.0 release:

![untitled 1](https://cloud.githubusercontent.com/assets/1436954/11088660/481d35b4-8864-11e5-8c6b-8e192b6c134a.gif)

The video was recorded using a custom theme, but I was able to reproduce the same issue using the default theme.

**Comment by stefanneculai** [comment]
Could you please make a jsFiddle for it? According to our tests it is working correctly.

**Comment by felskov** [comment]
Sure thing - from what I can tell the issue with the toolbar "jumping" when sticky turns on is related to padding on the scrollable parent. I also believe it disappears when you've scrolled down the height of the scrollable parent, not the full height of the embedded contents.

jsFiddle here: https://jsfiddle.net/y6404fbj/

**Comment by felskov** [comment]
I've been testing on Chrome version 46.0.2490.80 (64-bit) on Mac OS X El Capitan 10.11.1.

**Comment by stefanneculai** [comment]
In the example you made on jsFiddle, you have set as scrollable container the editor itself. The scrollableContainer should be a parent of the element the editor is initialized on: https://jsfiddle.net/z0gjdzv9/.

Indeed, there is still a problem with the padding. We'll fix it shortly.

**Comment by felskov** [comment]
Apologies :-) We do have the editor embedded into another scrollable container on our site, guess I was in a hurry when making the fiddle. I can still reproduce the issue with the toolbar disappearing when scrolling far enough down in your updated fiddle.
