### ISSUE TITLE
Replacing images doesn't trigger froalaEditor.image.removed or pass the original replaced image in callback

### ISSUE THREAD

**Issue by jsonwen** [froala/wysiwyg-editor#911]
Froala editor : latest version commit.
OS/Browser : Mac OS X 10.10.5 / Chrome

When replacing images in Froala, there's no way finding about the image it replaced, making it impossible to delete the original file from the server.

I expected a callback with the original replaced image or the following events to be triggered:
- froalaEditor.image.removed
- froalaEditor.image.beforeRemove

http://recordit.co/juZ2zxzgLG

**Comment by stefanneculai** [comment]
With the last commit, the image replace state will be triggering the `image.removed` event.
