### ISSUE TITLE
The first setInterval process problems.

### ISSUE THREAD

**Issue by largeden** [froala/wysiwyg-editor#912]
save plugin

For example,
If you run the following methods.

```javascript
$(element).froalaEditor().ready({
    saved_content = $("load element").val();
    $(element).froalaEditor('html.set', saved_content);
});
```
If you remove all of the content in this state save event does not occur.

Sometimes, there is a case that does not remember the initial values of the editor contents.

This issue is resolved by changing as shown below.
```javascript
/*
 * Initialize.
 */
function _init () {
  if (editor.opts.saveInterval) {
    setTimeout(function () {
      _last_html = editor.html.get();
    }, 0);

    editor.events.on('contentChanged', _mightSave);
    editor.events.on('keydown', function () {
      clearTimeout(_timeout);
    })
  }
}
```

**Comment by stefanneculai** [comment]
After setting the HTML you should save the step in the undo stack (`undo.saveStep`). The saving mechanism is based on the undo stack.
