### ISSUE TITLE
tableCellMultipleStyles

### ISSUE THREAD

**Issue by trinzia** [froala/wysiwyg-editor#913]
I tried to make tableCellMultipleStyles = false.
This should make it so only one style is applied to the table cell?

But it looks like this:  `<td class="border1 border2 border3">Text</td>`.
I would like to make them toggle only one class.

My code:

      $('#edit').froalaEditor({
        tableResizerOffset: 10,
        enter: $.FroalaEditor.ENTER_DIV,
        height: 840,
        tableCellMultipleStyles: false,
        tableCellStyles: {
          'border1': 'Border 1',
          'border2': 'Border 2',
          'border3': 'Border 3'
        },
        toolbarButtons: ['bold', 'italic', 'underline', 'strikeThrough', '|', 'paragraphStyle', 'fontSize', 'align', 'color', '|', 'insertImage', 'insertTable', '|', 'undo', 'redo']
      });

Thanks!

**Comment by stefanneculai** [comment]
It's an error in the code. The option is `tableMultipleStyles` right now. We'll correct it and update to `tableCellMultipleStyles` shortly. Thanks.
