### ISSUE TITLE
Sticky toolbar - continuously setting sticky-on while scrolling

### ISSUE THREAD

**Issue by felskov** [froala/wysiwyg-editor#915]
Once sticky-on has been enabled, the className is continuously updated for the toolbar-class. This results in CSS-transitions not running before the user stops scrolling (tested in Chrome). I'm trying to add a box-shadow when the user scrolls down and the toolbar starts overlaying the content-area - please see the attached video, which I hope explains it:
![untitled](https://cloud.githubusercontent.com/assets/1436954/11120953/6c1dd820-8953-11e5-9acc-1784a283677e.gif)

**Comment by stefanneculai** [comment]
That is necessary because of #814.

**Comment by sebfindling** [comment]
I'm having this issue right now! What can I do to fix it?

**Comment by somazx** [comment]
@stefanneculai I'm seeing a similar issue in my environment. As the user scrolls, each scroll event toggles the fr-sticky-on/off class. This happens even when the toolbar hasn't yet reached the top of the page and results in the editor taking over the page and masking other elements. I don't see this same behaviour when I test it against the demo on the official Froala website. Presumably this is some bad interaction with my page's layout/css.

Any ideas what could contribute to this?

**Comment by stefanneculai** [comment]
See https://www.froala.com/blog/notice-of-chrome-browser-problem.

**Comment by alpha1988** [comment]
I also have this problem sometimes, but I have another one big problem in chrome.
I have placed the editor into my own modal window and when there are a lot of text in it and I am opening my modal window, the 'fr-sticky-on' class is adding for toolbar even if I not scrolling anything. And the toolbar is on the top of the window. But when text is not so huge and my popup is placed on the screen then 'toolbarSticky' works correctly.
Can you help me, what should I do to use 'Sticky' functionality in such case?

**Comment by stefanneculai** [comment]
@alpha1988 if you can make a jsFiddle we can look into it.

**Comment by alpha1988** [comment]
You know I can't repeat this situation on jsFiddle.
Maybe because I working with angular. And data has come after the 'froala' editor initialisation. And after that, the popup window had resized and the window had resized also, and this fact is initiated adding of 'sticky-on' class.
How do you think, can it be so ?

**Comment by stefanneculai** [comment]
Unfortunately, we cannot help you without a jsFiddle.
