### ISSUE TITLE
Missing emoticons

### ISSUE THREAD

**Issue by Lednerb** [froala/wysiwyg-editor#918]
I've installed the editor via bower and included all css and js files.

There are 2 emoticons missing in my list.
See screenshot below.

![missing_emoticons](https://cloud.githubusercontent.com/assets/2056876/11151306/a26dcd70-8a2c-11e5-9dfe-1e9afd345328.png)

**Comment by stefanneculai** [comment]
What browser/OS are you using?

**Comment by Lednerb** [comment]
Google Chrome v.46 on Ubuntu Linux 64 bit

same issue on Firefox v.42

**Comment by Lednerb** [comment]
Maybe it's caused by a missing font?
Can you add a free font to the project to ensure that the icons in the editor and later on the website will be the same, regardless if the user has the font installed?

**Comment by stefanneculai** [comment]
@Lednerb indeed, it is because of missing fonts in Ubuntu. We're using Unicode Emoji and would prefer not to include a font directly in the editor archive but rather use an external font which can be included like Google Fonts.

**Comment by PowerPalle** [comment]
I included both CSS and JS and the 'Button Emoticon' is not even showing. I have no idea as to why...

**Comment by stefanneculai** [comment]
@PowerPalle I believe your issue is related to the following options: 
https://www.froala.com/wysiwyg-editor/docs/options#toolbarButtonsMD
https://www.froala.com/wysiwyg-editor/docs/options#toolbarButtonsSM
https://www.froala.com/wysiwyg-editor/docs/options#toolbarButtonsXS

Most probably your browser size matches the MD size and it hides some buttons. To avoid this, make sure you put all the options to all screen sizes.

**Comment by Lednerb** [comment]
@PowerPalle that's right. Your script works fine. I've checked it.

You can fix the problem like @stefanneculai described it.

**Comment by PowerPalle** [comment]
Seems to be in the right direction since I am now able to see the missing buttons, while using the toolbarButtonsMD as a test. BUT, it does now honor the order in which the buttons are placed.

Furthermore, does the new method require that we use all four version of the toolbarButtonsXX or is there a default method which can be used regardless of screensize?

**Comment by PowerPalle** [comment]
Okay so I used all four toolbuttonsXX variations wth the same content and now it keeps the order of the buttons. Everything seems to work just fine. Thank you for all help. In my case all Smileys are there as well.

**Comment by nicolasbocquet** [comment]
Many emoticons missing on windows :

![untitled-1](https://cloud.githubusercontent.com/assets/3034108/12196054/ff3466ae-b5fb-11e5-8cc2-9a5fe3ee4043.png)

**Comment by stefanneculai** [comment]
@nicolasbocquet what OS version and browser are you using?

**Comment by stefanneculai** [comment]
With the last commit, now [Emoji One](http://emojione.com/) will be used as default for emoticons. It can be disabled through `emoticonsUseImage` option and use the system ones.

**Comment by Lednerb** [comment]
:+1: thanks for this update!

**Comment by flinn** [comment]
Really glad you guys integrated Emoji One -- This is awesome! I'm trying to determine how I can extend this to allow for ALL of the emojis that Emoji One currently offers, but I am having a difficult time with it... Any thoughts about the best way for me to implement that? I'd be happy to do the actual work and submit a PR afterwards. :+1:

**Comment by stefanneculai** [comment]
If you want to change the emoticons in the list you can find an example [here](https://www.froala.com/wysiwyg-editor/docs/examples/custom-emoticons) about how to do that. The code is the name of the emoticon. For example, if you want to use the [briefcase one](https://github.com/Ranks/emojione/blob/master/assets/png_512x512/1f4bc.png?raw=true), then you should use the code `1f4bc`.

**Comment by flinn** [comment]
Hey Stefan.. I was able to add a more robust list of emojis via this list of alpha codes (https://github.com/Ranks/emoji-alpha-codes), but displaying all of them in a "fr-popup" as one LONG list doesn't really provide a useful/intuitive UI. It also requires a great deal of memory and network bandwidth to be downloading and displaying all of them as images at once. I'm trying to mimic Slack's emoji implementation with tabs and a search box, as that is what my users are used to -- I'm not sure if this will be possible though.

I'd love it if Froala offered developers the flexibility to extend a feature like this, and I'd be happy to contribute this as an optional extension.

**Comment by furyscript** [comment]
With the options `emoticonsUseImage: true` when I press backspace to remove emoji, the cursor go over the emoji and it's not very good. At the moment i set option to `false` and using unicode system, but with Linux missing two emoji. Any ideas?
