### ISSUE TITLE
Translation not initialized for placeholder

### ISSUE THREAD

**Issue by Lednerb** [froala/wysiwyg-editor#919]
I've added the german translation to my editor but _onpageload_ the placeholder is still `Type something`.

When i click in and enter & remove some text, the placeholder is translated.

**Comment by stefanneculai** [comment]
Are you using the master version or an older version?

**Comment by Lednerb** [comment]
Actual master.

**Comment by connect-technologies** [comment]
https://github.com/froala/wysiwyg-editor/issues/883
:)

**Comment by connect-technologies** [comment]
thanks @Lednerb for the translations

**Comment by stefanneculai** [comment]
@Lednerb @connect-technologies could one of you make a jsFiddle, please?

**Comment by stefanneculai** [comment]
We're replicated it. No longer necessary.

**Comment by Lednerb** [comment]
@connect-technologies Gerngeschehen ;-)

@stefanneculai :+1:
