### ISSUE TITLE
Croatian translation

### ISSUE THREAD

**Issue by ikurpis** [froala/wysiwyg-editor#920]
Hello, I can provide help with correct Croatian translation for FE. This one is pretty much Google translate or similar, with many mistakes. I can do that this weekend.
Just tell me how to send a file. Or pull?

Thanks

**Comment by stefanneculai** [comment]
We don't merge PR directly here, so it is perfectly fine if you could email it over to me using the email from my [Github profile](https://github.com/ikurpis). Thanks :+1: .

**Comment by ikurpis** [comment]
I will email you directly, glad to help :)
