### ISSUE TITLE
Tab behaviour

### ISSUE THREAD

**Issue by chr22** [froala/wysiwyg-editor#924]
Your tab behaviour is still a little wonky.

If I press tab with the cursor before a word, then the word is indented but I can't outdent it again. Not with the outdent button or with shift+tab. Though backspace works.

If I press tab with the line selected, then I can outdent with the outdent button, shift+tab and backspace. But only to the place where I started indenting, not the start of the editor.

**Comment by stefanneculai** [comment]
Inserting tab at the beginning of a paragraph is different than indenting it. When you indent/outdent a paragraph the whole paragraph is being indented, while when you hit the TAB key at the beginning of the paragraph 4 spaces are inserted. Those can be outdented using the backspace key.
