### ISSUE TITLE
When imagePaste is false, image context toolbar does not show

### ISSUE THREAD

**Issue by chrisdavies** [froala/wysiwyg-editor#925]
When an image is nearly off screen, and you select it, then scroll the image into view, the image context toolbar does not show up.

This happens in the latest version of Chrome and FF on Mac (El Capitan).

Repro steps:

- Upload an image (via the toolbar image upload option)
- Deselect the image
- Scroll so that the bottom of the image is off the screen
- Select the image
- Scroll the image into view

Here's an example where I clicked the image when it was fully in view:

<img width="821" alt="screen shot 2015-11-16 at 3 46 45 pm" src="https://cloud.githubusercontent.com/assets/833377/11194296/423fdd4a-8c79-11e5-8c7d-bee0fffec558.png">

Here's an example when I clicked the image when its bottom was off the screen and then scrolled it into view:

<img width="797" alt="screen shot 2015-11-16 at 3 49 12 pm" src="https://cloud.githubusercontent.com/assets/833377/11194363/a30ecf64-8c79-11e5-940e-058b21755d52.png">

The editor is being initialized like this:

```js
var buttons = [
      'bold', 'italic' , '|',
      'paragraphFormat', '|',
      'align', '|',
      'formatOL', 'formatUL', '|',
      'outdent', 'indent', '|',
      'insertLink', 'blockquote', 'insertHR', 'filepicker', '|',
      'html'];

self.$editor.froalaEditor({
      heightMin: 200,
      theme: 'custom',
      codeMirror: true,
      imagePaste: false,
      codeMirrorOptions: {
        indentWithTabs: true,
        lineNumbers: true,
        lineWrapping: true,
        mode: 'text/html',
        tabMode: 'indent',
        tabSize: 2
      },
      toolbarStickyOffset: 100,
      toolbarButtonsMD: buttons,
      toolbarButtonsSM: buttons,
      toolbarButtonsXS: buttons,
      toolbarButtons: buttons,
      imageDefaultAlign: 'left',
      imageDefaultWidth: 0,
      imageEditButtons: [
        'imageAlign', 'imageRemove', '|',
        'imageLink', 'linkOpen', 'linkEdit', 'linkRemove'],
      linkAlwaysBlank: true,
      linkInsertButtons: ['linkBack'],
      linkEditButtons: ['linkOpen', 'linkEdit', 'linkRemove'],
      shortcutsEnabled: ['bold', 'italic', 'undo', 'redo'],
      paragraphFormat: {
        N: 'Normal',
        H1: 'Heading 1',
        H2: 'Heading 2',
        H3: 'Heading 3',
      }
    });
```

**Comment by chrisdavies** [comment]
I should note that these are the plugins I'm using:

```ruby
//= require froala/codemirror
//= require froala/modes/xml
//= require froala/froala_editor.min
//= require froala/plugins/align.min
//= require froala/plugins/image.min
//= require froala/plugins/line_breaker.min
//= require froala/plugins/link.min
//= require froala/plugins/lists.min
//= require froala/plugins/quote.min
//= require froala/plugins/paragraph_format.min
//= require froala/plugins/code_view.min
```

**Comment by stefanneculai** [comment]
Hi @chrisdavies, I have just tried to replicate this without success. The problem seems to be related to the scroll, not to the `imagePaste`. The only thing that `imagePaste` is doing is to prevent pasting image inside the editor and pretty much that's all it does.

Would it be possible for you to make a jsFiddle or maybe send me a link to the page where you have this problem? You could use my email address for that if you don't want to make it public.

Thanks.

**Comment by chrisdavies** [comment]
Hi Stefan. I agree. I tinkered with it more, and the imagePaste was a red herring. I'll see if I can set up a jsFiddle later today. Thanks!

**Comment by chrisdavies** [comment]
Ah. I got a repro. I had been doing an inspect element and hadn't seen the popup in the markup, but doing a `$('.fr-popup')` in the console showed that there was indeed a popup element. It was located somewhere I didn't expect, and was hidden due to a style!
