### ISSUE TITLE
Incompatibilty Of Image/File Uploader with jQuery Validation Plugin

### ISSUE THREAD

**Issue by mirsaeedi** [froala/wysiwyg-editor#926]
It seems there is some incompatibility issues with jQuery Validation Plugin. If you click on image or file uploader in a form with jQuery Validation enabled, then suddenly the 'valid' method of the form becomes unusable and generates following error on validation:

Cannot read property 'settings' of undefined(…)

Also note that after clicking on the image/file uploader the above error is generated too.

**Comment by stefanneculai** [comment]
Hi @mirsaeedi, would it be possible for you to try again with the latest commit? Thanks.

**Comment by stefanneculai** [comment]
I am closing this due to lack of response. It should be fixed in the commit 7643d4f anyway.
