### ISSUE TITLE
LinkStyles does not allow 2 class

### ISSUE THREAD

**Issue by sudeste** [froala/wysiwyg-editor#927]
Example:

```
linkStyles: {
                'btn': 'Default',
                'btn btn-white': 'Button white',
                'btn btn-black': 'Button black',
                'btn btn-blue': 'Button blue',
                'btn btn-red': 'Button red'
            },
```
and link "a"
```
<a class="btn btn-blue" href="index.html">How to</a>
```
Button to switch to "Button red". It erases the class "btn".
I'm using the "2.0.1" version. Version 1.2 did not occur this.

**Comment by stefanneculai** [comment]
The key of the linkStyles properties should be only one classname, not multiple ones. This is the way it is designed to work in V2.

**Comment by sudeste** [comment]
This is bad.
Have some method or event where can I change this?

**Comment by sudeste** [comment]
It's resolved with dropdown buttons. Thanks.
