### ISSUE TITLE
ReferenceError: nil is not defined

### ISSUE THREAD

**Issue by sreelalks** [froala/wysiwyg-editor#928]
When i clicked code view button in froala editor get this error message "ReferenceError: nil is not defined", can you please check attached screen shot. This issue comes in first page loading. 
I just try to fix this error using "return null;" instead of "return nil;" its working, but i don't know this is the correct way. Please help me.. 
![capture](https://cloud.githubusercontent.com/assets/8914381/11236555/7e851c38-8e00-11e5-8653-463adc75b243.PNG)

**Comment by stefanneculai** [comment]
This was fixed by a commit yesterday. Please use the master version.

**Comment by sreelalks** [comment]
Thank you Stefanneculai.
