### ISSUE TITLE
Resize image left and right align

### ISSUE THREAD

**Issue by sudeste** [froala/wysiwyg-editor#929]
I have a problem, in resize image when left and rigth align on.

Video example:
https://youtu.be/k6wwL7bBjh0

Froala 2.0.1
Chrome - Versão 46.0  (64-bit)
Firefox - 42.0  (64-bit)

**Comment by stefanneculai** [comment]
Can you reproduce thia on our website?

**Comment by sudeste** [comment]
Does not occur. It works perfect. I will try to update the source code.

**Comment by stefanneculai** [comment]
Make sure you have updated the image plugin as well. This looks like an isssur from two months ago.

**Comment by sudeste** [comment]
It seems that identified the problem.
This only occurs when an image does not have the class "fr-fin"

**Comment by stefanneculai** [comment]
I believe you're using some outdated CSS/JS. In the latest version we're never using the class `fr-fin`.

**Comment by sudeste** [comment]
Yes,
My system already has the CSS file "froala_content.css" version 1.2.8. There's no way I remove. And to just have "froala_style.css". Both are being added.

I do not know if that's the right way to solve, but the event "froalaEditor.image.inserted" can add one class "fr-fin" on the images.
