### ISSUE TITLE
Browserify, PLUGINS undefined

### ISSUE THREAD

**Issue by dsdenes** [froala/wysiwyg-editor#930]
"Uncaught TypeError: Cannot set property 'align' of undefined"

It's quite hard to debug the minimalized code, so I don't have a clue what could be the problem.
The stack uses Browserify and Gulp. I suppose from the code that if the module.export is defined then it tries to require jQuery into the actual scope. But not in the the case of plugins.

I've installed the npm version, but changed to the latest one from the master branch.

// index.js

require('node_modules/froala-editor/js/froala_editor.min.js');

// here throws the error, at "use strict";a.FroalaEditor.PLUGINS.align=function(b){funct
require('node_modules/froala-editor/js/plugins/align.min.js'); 

require('node_modules/froala-editor/js/plugins/colors.min.js');
require('node_modules/froala-editor/js/plugins/font_family.min.js');
require('node_modules/froala-editor/js/plugins/font_size.min.js');

**Comment by stefanneculai** [comment]
Are you using the latest master with the changes from today?

**Comment by dsdenes** [comment]
Thanks, the newest version has solved the problem. Some still remained, but I'll open a new case for them.
