### ISSUE TITLE
Browserify - Uncaught TypeError: $(...).froalaEditor is not a function

### ISSUE THREAD

**Issue by dsdenes** [froala/wysiwyg-editor#931]
Error: "Uncaught TypeError: $(...).froalaEditor is not a function"

The stack uses Browserify.

``` javascript

var $ = require('jquery');
require('node_modules/froala-editor/js/froala_editor.min.js');

$(function() {
  var $target = $('<div>').appendTo('body');
  $target.froalaEditor()
});
 
```

**Comment by stefanneculai** [comment]
Sorry, this took a bit longer to check. It's not an editor problem, but you're not requiring it correctly. You should also pass the jQuery variable like this:
`require('node_modules/froala-editor/js/froala_editor.min.js')($);`
