### ISSUE TITLE
imageManager options NumberOfColumns

### ISSUE THREAD

**Issue by sudeste** [froala/wysiwyg-editor#932]
I use the ImageManager to load an icon gallery, with many options.

Example:
[View image](http://postimg.org/image/5yv2mwy4h)

It would be interesting to have an option to choose the number of columns, and thus fit more pictures least one first screen.
- The images become smaller as well as 90px / 90px

**Comment by stefanneculai** [comment]
Thanks for the suggestion. I am closing this for now because we're using this repo only for bug tracking.
