### ISSUE TITLE
When CSS font-weight is over 500, .fr-active is set on Bold button

### ISSUE THREAD

**Issue by benjaminknox** [froala/wysiwyg-editor#937]
When the font-weight CSS is set above 500 the _Bold_ button shows as selected because of the `bold` command available to `execCommand`. http://www.w3.org/TR/2008/WD-html5-20080610/editing.html#command

See below:
![screen shot 2015-11-23 at 11 57 17 am](https://cloud.githubusercontent.com/assets/5668789/11351294/175c0598-91f3-11e5-9e69-df308bbba2cc.png)

This became a problem when our h tags were set to `font-weight: 700`, it confused one of our active users because they had not used the _Bold_ button to set the weight. 

It may be better to have the condition that highlights the _Bold_ button look for the html tag that the bold button wraps the text in, `STRONG` or `b` for instance.

**Comment by stefanneculai** [comment]
The editor is designed to reflect the state of what you actually see and not what is in the HTML. It is not correct to use only the HTML to check for the state and ignore the CSS.
