### ISSUE TITLE
Resize image with bordered

### ISSUE THREAD

**Issue by sudeste** [froala/wysiwyg-editor#938]
Resize image with bordered, it appears that a problem has.

Video example in froala editor site:
https://youtu.be/GlvenzORWeE

- Chrome - Versão 46.0.2490.86 (64-bit)

**Comment by trinzia** [comment]
Steps to reproduce (in your live demo):
- Apply the border
- Resize the image to smallest size 
- Try to drag it larger again.   

This works intermittently at best.  

Quickest temporary fix, replace border with outline.  Outline is not calculated in box model.
.fr-view img.fr-bordered {
    outline: solid 10px #CCC;
    outline-offset: -10px;
}
