### ISSUE TITLE
Table editing popup on touch devices

### ISSUE THREAD

**Issue by dave-buzzy** [froala/wysiwyg-editor#940]
The table editor popup appears disabled automatically on touch devices - yet other popups like the link editor still work. Is it possible to enable the table editor?

[Edit] I'm referring to the cell editing options - eg add row, add column etc as pictured here:
![screen shot 2015-11-25 at 11 39 38 am](https://cloud.githubusercontent.com/assets/8966637/11387792/5f1216a8-9369-11e5-9a9e-85fc225137a0.png)

**Comment by stefanneculai** [comment]
The table tool is not available on touch devises for the moment.

**Comment by ghedwards** [comment]
Is this now available?

**Comment by stefanneculai** [comment]
@ghedwards no.

**Comment by lovelyelfpop** [comment]
Still not available?
