### ISSUE TITLE
Could not typing Japanese proper via IME(Input Method Editor), after the text color change.

### ISSUE THREAD

**Issue by sato-train** [froala/wysiwyg-editor#941]
OS: Windows7 Ultimate SP1
Browser: Chrome(46.0.2490.86 m)
IME: Microsoft IME

it is reproducible at any time.

![capture](https://cloud.githubusercontent.com/assets/15088170/11412079/5d328392-941b-11e5-9d37-35ab2d609799.gif)

Keyboard: Japanese 109 Key Layout

![dsc_0106](https://cloud.githubusercontent.com/assets/15088170/11412285/8483cf84-941e-11e5-91c1-8736f1410499.png)

### Correct conversion steps  ###

1. press half-width, full-width key to enter IME mode
  pressed key : ① 
  text area shows nothing

2. type Hiragana "あ"
  pressed key : ② 
  text area shows: "あ"

3. type Hiragana "か"
  pressed key : ③
  text area shows: "あｋ"
  then pressed key : ②
  text area shows: "あか"

4. press speace key to convert from Hiragana "あか" to Kanji "赤"
  pressed key : ④
  text area shows: "赤"

5. press  enter key to determination
  pressed key : ⑤
  text area shows: "赤"

### problem  ###
* program ignores sequence step 3,4,5 when the text color reset.
* This happens at only first typing after the text color reset.

**Comment by sato-train** [comment]
@stefanneculai Hi, I'm facing same issue on iOS. Is there editor have different logic for iOS? if so, please be corresponding.

**Comment by stefanneculai** [comment]
@sato-train Is that reproducible on our website?

**Comment by sato-train** [comment]
@stefanneculai yes. I have attached  movie.
It can reproduce with Bold text.

**Comment by stefanneculai** [comment]
I believe Github does not support attaching videos here. Please upload it somewhere. 

Thank you.

**Comment by sato-train** [comment]
@stefanneculai I have appended it to comment area.

**Comment by stefanneculai** [comment]
Github is removing it.

**Comment by sato-train** [comment]
@stefanneculai ok. I will send it to you via email, thank you.
