### ISSUE TITLE
font-awesome dependency fixed

### ISSUE THREAD

**Issue by xtreamwayz** [froala/wysiwyg-editor#942]
The font-awesome dependency is fixed to 4.4.0. Upgrading all project packages with bower triggers a question all the time if I should use font-awesome 4.4.0 or 4.5.0.

```
Unable to find a suitable version for font-awesome, please choose one:
    1) font-awesome#4.4.0 which resolved to 4.4.0 and is required by froala-wysiwyg#2.0.1
    2) font-awesome#~4.5 which resolved to 4.5.0 and is required by <project-name>
```

I'm not sure if there is a reason to have this as a fixed version. Why not make 4.4.0 the minimum required version like is done for jquery?

```
    "dependencies": {
      "jquery": ">=1.11.0",
      "font-awesome": ">=4.4.0"
    }
```

**Comment by stefanneculai** [comment]
:+1:
