### ISSUE TITLE
can not control the initialization of the text color palette

### ISSUE THREAD

**Issue by sato-train** [froala/wysiwyg-editor#943]
Hi developers,

I would like to request for more controllable initialization about text color palette.
like:
```javascript
$(selector).froalaEditor({
  defaultTextColor: '#FF0000'
});
```
expected result as following:

![initcolor](https://cloud.githubusercontent.com/assets/15088170/11433937/20dc06aa-9508-11e5-96f2-2039d624b35b.gif)

Thank you

**Comment by stefanneculai** [comment]
Thanks for the suggestion. I am closing this because we don't accept feature-requests here and we use this repo for bug tracking only.

**Comment by sato-train** [comment]
Ok, thank you.
