### ISSUE TITLE
Feature: merged htmlAllowedAttrs

### ISSUE THREAD

**Issue by marek-hanzal** [froala/wysiwyg-editor#944]
When there is need to add custom attrs (like `data-` attr. support), one need to copy all current `htmlAllowedAttrs` and add own ones.

It would be nice to have something like `htmlMergeAllowedAttrs` (with better name) that will add custom attributes to default ones.

Or alternatively - some flag to enable `data-` attr support.

**Comment by stefanneculai** [comment]
Actually it's not necessary to copy all that list. You could do `$.FroalaEditor.DEFAULTS.htmlAllowedAttrs = $.merge($.FroalaEditor.DEFAULTS.htmlAllowedAttrs, [YOUR_LIST]);`.
