### ISSUE TITLE
IE Performance issues

### ISSUE THREAD

**Issue by GufCab** [froala/wysiwyg-editor#953]
In IE10, the editor starts performing very sluggishly when you hit more than ~100 lines of text. Better performance seen in Chrome. 

Tested on your site: [https://www.froala.com/wysiwyg-editor](https://www.froala.com/wysiwyg-editor)

With Windows 8.1 / Internet Explorer 11

**Comment by stefanneculai** [comment]
Is the performance difference when you type in http://jsfiddle.net/dd7e74fd/ the same text you put in the editor?

**Comment by GufCab** [comment]
Yes, there is no noticeable lag in your fiddle.

**Comment by stefanneculai** [comment]
Would it be possible to send us the text you're entering?

**Comment by GufCab** [comment]
Text:
http://pastebin.com/H4iPJQkF

I start seeing sluggy response around 5k characters on laptop (Intel Core i7-4500, 8 GB RAM (though RAM does not seem to be an issue at all)).

Tested on somewhat beefier desktop, the issue remains, but will not appear unless you add in a good deal more formatting or text.

**Comment by stefanneculai** [comment]
We have checked this further and the performance is being reduced by the browser spellcheck. If you turn off the [spellcheck option](https://www.froala.com/wysiwyg-editor/docs/options#spellcheck) there is no performance issue. Unfortunately, there is nothing that can be done to address this when the spellcheck is enabled.
