### ISSUE TITLE
Feature: Automatically being Ordered and Unordered Lists

### ISSUE THREAD

**Issue by GufCab** [froala/wysiwyg-editor#954]
In Microsoft Word, Google Docs and other wysiwyg editors, typing '1.' will begin an ordered list. 
The same goes for starting a line with '-' or '*' followed by a space.

This would be a nice feature for your great editor.

**Comment by stefanneculai** [comment]
Thanks. We don't accept feature-requests here because we use this repo as a bug tracker mainly. Therefore, I will close it for now.

**Comment by stefanneculai** [comment]
We've just put together a public roadmap with the most popular features. 😍 There you can vote your favorite one, provide feedback or make new suggestions: https://wysiwyg-editor-roadmap.froala.com/public.
