### ISSUE TITLE
Editor buffers the texts input

### ISSUE THREAD

**Issue by ericleethrinacia** [froala/wysiwyg-editor#956]
I've already addressed this in email but just want to leave it here for a record

The editor seems to buffer when the user types. By buffer I mean if one types just a bit faster, the editor slowly shows the characters that are just typed even you have done typing
I commented out keyup and contentChanged event in _init function at line 7191 to prevent this from happening but I was told that it wouldn't be good practice and I have noticed by doing so, the undo button didn't refresh itself after contentChanged. I was also told that it could be due to angular binding.

Thank you very much

**Comment by stefanneculai** [comment]
It's not an editor issue, but rather a problem from the angular-froala plugin. Please open this issue on the https://github.com/froala/angular-froala.
