### ISSUE TITLE
Unwanted <br> tag inserted after <!-- html comment -->

### ISSUE THREAD

**Issue by juanpablob** [froala/wysiwyg-editor#958]
Froala is inserting unwanted <br> tag after html comment. Don't know how to fix this. Is this a bug? Is there a way to turn off this behavior?

To be more clear, I will reproduce an example of the bug:

When I put this

```
<p>Paragraph lorem ipsum 1</p>
<p>Paragraph lorem ipsum 2</p>

<!-- Box Design 1 -->
<div class="box">
Box Content
</div>

<p>Paragraph lorem ipsum 3</p>
```
I get this
```
<p>Paragraph lorem ipsum 1</p>
<p>Paragraph lorem ipsum 2</p>

<!-- Box Design 1 --><br>
<div class="box">
Box Content
</div>

<p>Paragraph lorem ipsum 3</p>
```

Any ideas how to fix annoying behavior? Its driving me crazy.

**Comment by stefanneculai** [comment]
It's not happening on master. Most probably you're using an older version.

**Comment by juanpablob** [comment]
Is 2.0.1 tag release equal to master?

**Comment by stefanneculai** [comment]
The master version is the dev for 2.0.2, but it doesn't appear to happen in 2.0.1 neither. Are you experiencing this on [our website](https://www.froala.com/wysiwyg-editor/)?

**Comment by sz-tamas** [comment]
This bug still occurs in v2.1.0 when using table tags after html comments.

Input:
```html
<p>Paragraph lorem ipsum 1</p>

<p>Paragraph lorem ipsum 2</p>

<!-- Table Design 1 -->
<table class="box">
	<tbody>
		<tr>
			<td>Table Content</td>
		</tr>
	</tbody>
</table>

<p>Paragraph lorem ipsum 3</p>
```

Output:
```html
<p>Paragraph lorem ipsum 1</p>

<p>Paragraph lorem ipsum 2</p>
<!-- Table Design 1 -->
<br>

<table class="box">
	<tbody>
		<tr>
			<td>Table Content</td>
		</tr>
	</tbody>
</table>

<p>Paragraph lorem ipsum 3</p>
```
