### ISSUE TITLE
Inline toolbarVisibleWithoutSelection smoothing

### ISSUE THREAD

**Issue by mnichols** [froala/wysiwyg-editor#959]
I want to use the `toolbarVisibleWithoutSelection` option for my inline editor but users complain (and I agree) that the flashing toolbar while typing is distracting. The behavior is on the xample here too:
https://www.froala.com/wysiwyg-editor/docs/examples/always-visible.

Is there any suggestion on debouncing this behavior somehow to avoid this annoyance? I'd rather not take the bull by the horns and manually do my own key event throttling.

**Comment by stefanneculai** [comment]
What would be your suggestion? Hiding it while typing?

**Comment by timovanderzanden** [comment]
I agree. For us to purchase a license this is a must-have.

My suggestion would be to hide it while typing and to show it on click. From a usability point of view this should be the default behaviour for the inline editor, without `toolbarVisibleWithoutSelection`. I think our users would really be struggling to get the toolbar to show to insert images and lists, but I don't think the toolbar should be visible continuously while typing.

**Comment by stefanneculai** [comment]
@timovanderzanden indeed, it would be better to have `toolbarVisibleWithoutSelection` enabled by default and we got lots of feedback in this direction. Last commit does that.

**Comment by mnichols** [comment]
Thanks @stefanneculai !
