### ISSUE TITLE
strange icon appear after froala initiated

### ISSUE THREAD

**Issue by MeKarina** [froala/wysiwyg-editor#963]
i'm talking about this:
![screen shot 2015-12-07 at 12 52 21 pm](https://cloud.githubusercontent.com/assets/15459370/11620035/4fa7e2a2-9ce1-11e5-9b48-a3fbc4cf6526.jpg)

this always appear after froala initiated on a left corner below editor and disappear on mouse event...

**Comment by stefanneculai** [comment]
That's because you're not including the CSS style for the line breaker.
