### ISSUE TITLE
sanitizeURL breaks "javascript:" pseudo protocol in href attribute in my setup

### ISSUE THREAD

**Issue by MisterFreeze** [froala/wysiwyg-editor#964]
Hi!

Thanks for this lovely piece of software, I love it!

I'm trying to use the Froala editor for some form input fields on a whole page. Before instantiating the editor, I hide a menu bar and set its 'contenteditable' attribute to 'false'. In that menu bar, there are buttons that make use of the javascript pesueo-protocol ("javascript:") in their value of the href attribute. This get's translated to "javascript%3A" by the editor and a click on that button does not trigger the desired JS function anymore.

How could this behavior be avoided?

Best regards

**Comment by stefanneculai** [comment]
The editor is designed to do that in order to prevent XSS injection. It's better to have JS outside of the editor if you want to do such thing.

**Comment by MisterFreeze** [comment]
I totally agree on that separation of HTML and JS is desirable. That "javascript:" pseudo uri, however, would be present in non editor mode in that HTML. I do not see how removing it for the editor only would improve security. From what I understand input validation is a server-side issue. If a malicious javascript-tag was in the HTML before the editor is instantiated, it's probably too late already.

**Comment by MisterFreeze** [comment]
I tried to execute a JS function that toggles the Froala editor by adding a 'click' event listener to that DOM element. It seems that the event listener get's removed during editor initialization.
By "have JS outside of the editor", do you suggest that I should not put the menu bar DOM element outside the DOM tree on which Froala is initialized?

**Comment by stefanneculai** [comment]
The onclick property is being removed because it is not in the [htmlAllowedAttrs](https://www.froala.com/wysiwyg-editor/docs/options#htmlAllowedAttrs) option. The best way would be to have the JS outside of the editor and not allow users to type JS inside the editor.

**Comment by MisterFreeze** [comment]
Of course that JS code is in a `<script>` tag. Adding `onclick` to `htmlAllowedAttrs` did it. Thank you very much, @stefanneculai
