### ISSUE TITLE
Empty link list

### ISSUE THREAD

**Issue by mnichols** [froala/wysiwyg-editor#965]
1. the docs (https://www.froala.com/wysiwyg-editor/docs/options#linkList) indicate the link list is empty array by default, but it doesnt seem so (I see Google, Froala, and another one)
2. I want to disallow the creation of the search icon for link list entirely (users would never 'select' from a list of links on our app). But when I set `linkList: false` or `linkList: []` I still see the pulldown and magnifying glass, though it does nothing.

How do I remove the link list entirely without manually hiding it?

**Comment by stefanneculai** [comment]
You should change the [linkInsertButtons](https://www.froala.com/wysiwyg-editor/docs/options#linkInsertButtons) option.

**Comment by mnichols** [comment]
Of course! Sorry I didn't see that.
