### ISSUE TITLE
Issues with stickytoolbar combining with show/hide

### ISSUE THREAD

**Issue by yanivlllev** [froala/wysiwyg-editor#968]
I have 2 types of froala in my web app, 
one is inline, the other isn't - and what i need is to make the froala show when the user clicks on it, and hide it when he clicks out of it. i also need the toolbar to be sticky -128px Top.
The problem is that when i click inside the text, most of the times the froala shows in the middle of the screen like it's inline and not in the beginning of the text like it should, and it starts to "stick" only when i scroll. what's wrong?

These are the settings for this type:

initOnClick: true,
toolbarSticky: true,
toolbarStickyOffset: 128,
events : {
            'froalaEditor.focus' : function(e, editor) {
                editor.toolbar.show()
            },
            'froalaEditor.blur' : function(e, editor) {
                editor.toolbar.hide()
            }
        }

I also attached a GIF to show the problem.
![animation](https://cloud.githubusercontent.com/assets/12447235/11686857/1c37c2a0-9e8c-11e5-9293-fd92942d0b8c.gif)

**Comment by stefanneculai** [comment]
I have just checked this and it appears to work fine with the master version. Could you confirm you're using the master version?

**Comment by yanivlllev** [comment]
I checked and it seemed that using the master version, anyway, I ran bower update to the resources and now it works fine... thank you.

**Comment by stefanneculai** [comment]
OK. Thank you.
