### ISSUE TITLE
On switching to code view content is deleted [Firefox]

### ISSUE THREAD

**Issue by Lednerb** [froala/wysiwyg-editor#969]
Hello again.

When i'm switching to the code view on firefox my content gets deleted sometimes.
Maybe it's depends from the window size.

What is happening?
Here is a screencast of the problem.

![froala-deletes-content](https://cloud.githubusercontent.com/assets/2056876/11714103/ee20bbcc-9f37-11e5-90e1-b72974b067e8.gif)

**Comment by stefanneculai** [comment]
Are you using the master version? Could you please send us the HTML you are using?

**Comment by Lednerb** [comment]
I've installed the editor via bower. Version 2.0.0 is used.


```javascript
$('.froala-editor').froalaEditor({
            language: 'de',
            toolbarButtons: ['bold', 'italic', 'underline', '|', 'fontSize', 'color',  '|', 'paragraphFormat', 'align', 'formatOL', 'formatUL', 'outdent', 'indent', '|', 'insertHR', '|', 'insertLink', 'insertImage', 'insertVideo', 'insertFile', 'insertTable', '|', 'undo', 'redo', 'clearFormatting', '|', 'html'],
            heightMin: 300,
            linkAutoPrefix: '',
            fileUploadURL: '{{ route('admin.upload-files') }}',
            fileUploadParams: {
                _token: '{{ csrf_token() }}',
            },
            imageUploadURL: '{{ route('admin.upload-images') }}',
            imageUploadParams: {
                _token: '{{ csrf_token() }}',
            },
            imageManagerLoadURL: '/img/getAllImages',
            imageManagerDeleteURL: '/img/deleteImages',
            imageManagerDeleteParams: {
                _token: '{{ csrf_token() }}',
            },
            key: 'my-forala-key'
        });
```

HTML is just a simple textarea with class `froala-editor`, placeholder and `rows="4"` in a Bootstrap class called `form-group`.

**Comment by Lednerb** [comment]
Okay, i've just updated the Editor to the latest version and it seems to work correctly now.

If the issue occurs again, i will reopen here.
Thank you for your very fast response!

**Comment by stefanneculai** [comment]
Yes, this was a problem that was happening sometimes in V2.0.0, but it was fixed.
