### ISSUE TITLE
Formatting issues

### ISSUE THREAD

**Issue by jreboul** [froala/wysiwyg-editor#971]
Hi,
I'm struggling with a formatting issue.

Say, I have 2 paragraphs <p> separated by subtitle <h2>

![capture d ecran 2015-12-11 a 16 24 33](https://cloud.githubusercontent.com/assets/7972977/11747568/3b518452-a024-11e5-87f1-e7d52791ae0a.png)

![capture d ecran 2015-12-11 a 16 24 42](https://cloud.githubusercontent.com/assets/7972977/11747573/407f7ad8-a024-11e5-8617-ca22cb5ad881.png)

-When I delete the line before the <h2>, the subtitle reintegrates the 1st paragraph. So far so good. But when hitting enter to replace the subtitle where it belongs and formatting it to <h2> again a bunch of spans with styles are added, and I have no clue where they come from.

![capture d ecran 2015-12-11 a 16 26 00](https://cloud.githubusercontent.com/assets/7972977/11747602/7b564cc2-a024-11e5-80f1-8c7f60844bec.png)

The issue happens with a wide variety of preformats, including links. 

When you type delete at the beginning of a paragraph, it takes the format of what is before him. If it's a paragraph, it's ok, if it's a h1 or anything else, there's a probIem. I noticed this issue is even happening on the froala demo page !

Any help there ? Need more details ? Please let me know.

Thanks !

**Comment by stefanneculai** [comment]
This looks like you're using V1. Because of the way V1 was designed it's not possible to fix it, however that works without problems in V2. Please upgrade to V2 where the problem is fixed.

**Comment by jreboul** [comment]
ok thanks !
