### ISSUE TITLE
Selecting/Highlighting text after focus

### ISSUE THREAD

**Issue by albab** [froala/wysiwyg-editor#972]
Has anyone successfully been able to programmatically select the text inside an inline Froala editor after focusing on it? 

I got focus to work via ('.froala_editor').editable('focus') and I was thinking I could just call .select() on it afterwards but I can't for the life of me get it to work.

**Comment by stefanneculai** [comment]
Focus: https://www.froala.com/wysiwyg-editor/docs/methods#events.focus.
Missing from docs, but you can use `commands.selectAll` as a method to select everything.

**Comment by ConnorsFan** [comment]
Is commands.selectAll supposed to work in IE11? According to my tests in Windows, it works with Firefox and Chrome, but not with IE11.

**Comment by stefanneculai** [comment]
@ConnorsFan we're going to check.

**Comment by ConnorsFan** [comment]
Any news about commands.selectAll on Internet Explorer 11? It still does not work.

**Comment by ConnorsFan** [comment]
I found the problem. One of my CSS styles was setting 'user-select: none; -ms-user-select: none;' (and all other flavors of that attribute) on the rich text element and its descendants. That does not seem to affect the 'selectAll' command in Chrome and Firefox, but it prevents it from working in IE11 and Edge. My bad, sorry.

**Comment by prasad414** [comment]
Just in case if you are looking something like below.
https://jsfiddle.net/v2k4o9r7/3/

**Comment by JoeGarcia2** [comment]
How can you trigger this to select all text on load?  I have text being loaded via Ajax, but if it's white text on a white background, I'd like to auto select it so the editor doesn't look blank.
