### ISSUE TITLE
The cursor is not visible in the blank paragraph (enter key).

### ISSUE THREAD

**Issue by largeden** [froala/wysiwyg-editor#974]
Windows 7 + IE11(IE10)
editor test version: The latest version(At least v2.0.1)

https://www.dropbox.com/s/j44dnsg098mkndk/cursor.mov?dl=0

When you click with the mouse or the contents inside the paragraph problem is resolved.
Only it occurs in a key input process (enter, backspace).

**Comment by stefanneculai** [comment]
Should be fixed on master. Could you check?

**Comment by largeden** [comment]
@stefanneculai 
Thanks.
The Master version was solved. :)
