### ISSUE TITLE
Missing toolbar on iOs with inline mode

### ISSUE THREAD

**Issue by riccardomessineo** [froala/wysiwyg-editor#976]
Hi, 
  it seems like the bottom toolbar used in inline mode doesn't appear on iOs.
<img width="354" alt="schermata 2015-12-14 alle 10 23 40" src="https://cloud.githubusercontent.com/assets/10194398/11777180/d5456798-a24c-11e5-9dc3-45daf8d63b36.png">
<img width="332" alt="schermata 2015-12-14 alle 10 22 36" src="https://cloud.githubusercontent.com/assets/10194398/11777181/d54ab658-a24c-11e5-9aec-164e0583ccc6.png">

Is this a known bug? Will it be fixed?

Thank you,
Riccardo

**Comment by stefanneculai** [comment]
@riccardomessineo 0871736e5ec141019c79741ad1fe0905befa63c2 fixes it.
