### ISSUE TITLE
pasteDeniedAttrs doesn't work with table

### ISSUE THREAD

**Issue by masseuro** [froala/wysiwyg-editor#978]
Paste a table with attr style doesn't clean attr with pasteDeniedAttrs,

Same with htmlAllowAttrs

See the bug here https://jsfiddle.net/Lr9vt9xs/1/ (copy and paste the red table in the wysiwyg)
Result after paste <img width="551" alt="capture d ecran 2015-12-14 a 12 22 01" src="https://cloud.githubusercontent.com/assets/131135/11779676/12b515fa-a25d-11e5-9fc7-cb5b0c36e2d1.png">

**Comment by stefanneculai** [comment]
Are you using the master version?

**Comment by masseuro** [comment]
Not sure with this jsFiddle, i will update my js on jsFiddle. But same with release 2.0.3 in local

**Comment by masseuro** [comment]
Actually is 2.0.3

**Comment by stefanneculai** [comment]
Please try with master. We fixed a similar issue few days ago.

**Comment by masseuro** [comment]
Thx, this work fine http://codepen.io/masseuro/pen/rxOPGJ
