### ISSUE TITLE
Inline mode does not add <p> tags like regular mode

### ISSUE THREAD

**Issue by timovanderzanden** [froala/wysiwyg-editor#979]
In the default editor configuration the editor wraps text in `<p>` tags and when pressing enter, another `<p>` tag is added. However, in inline mode the behaviour is magically different. Text is not wrapped in `<p>` tags. When I add `<p><br></p>` as default value for the inline editor, it allows me to add text to the `<p>` tag initially, but when pressing backspace twice, the tag is removed and any new text is not wrapped in a `<p>` element.

One could argue if the difference in behaviour is as expected because of being in inline mode, but there is no option to circumvent the default behaviour. My suggestion would be to add an option that allows you to control if regular text is wrapped in `<p>` tags or not.

If there's already an option to control this behaviour, I haven't been able to find it and would like to hear how to use this.

**Comment by stefanneculai** [comment]
Please make a jsFiddle for it.

**Comment by timovanderzanden** [comment]
I just found out that the behaviour I described in my issue depends on the tag used on the original Froala element.

In our application we use `<data>` tags to define editable content in the page. We chose this tag because it doesn't break the DOM structure when applied to lists, spans or paragraphs. So the element is defined as follows. Froala is then initialized on `data-type="html"`. This tag does not automatically add `<p>` tags.

```html
<data data-type="html"></data>
```

When I use a `<div>` tag instead, it does add `<p>` tags. 

```html
<div data-type="html"></div>
```

Does Froala automatically adjust its behaviour based on the original element in the DOM?

**Comment by stefanneculai** [comment]
Yes, if inline mode is used and you initialize the editor on another tag than `DIV` then the ENTER_BR is automatically turned on.

**Comment by timovanderzanden** [comment]
I think the behaviour is not completely correct. I would like to suggest two possibilities.

1. A few tags that do support `p` tags, like `article` don't support the tags in the current configuration. I think a better option would be to reverse the behaviour and turn ENTER_BR on when the editor is initialized on a tag like `h1, h2, p, etc`. So default behaviour would be ENTER_P.

2. I have also noticed that there is no way to override this behaviour. We would prefer to be able to set the enter option ourselves when needed.

**Comment by stefanneculai** [comment]
Agreed that the editor should not change the enter behaviour.

**Comment by sreelalks** [comment]
And there is also some space issue. <P> tag have default margin(10px top and bottom). its display unwanted space between two paragraphs. This issue comes in inbox of gmail or other mailing services . can you change putting  <p> to <div>.
