### ISSUE TITLE
IE11 Korean Typing Problem.

### ISSUE THREAD

**Issue by largeden** [froala/wysiwyg-editor#980]
OS: Windows 7 later + IE11 (FF,chomre is not problem)
editor : github master version.

https://www.dropbox.com/s/1mdgisdgtt04med/IE11_typing.mov?dl=0

There is a Korean input problem when using the plugin below.
image.js
table.js

Test Step
```
걔계
r + O + r + P (Use the shift)
```
I think that this issue is related to the keydown event.
If you do not run the code below, the problem does not occur.
```javascript
// image.js function _init () {
editor.events.on('keydown', function (e) {
var key_code = e.which;
if ($current_image && (key_code == $.FroalaEditor.KEYCODE.BACKSPACE || key_code == $.FroalaEditor.KEYCODE.DELETE)) {
  e.preventDefault();
  remove();
  return false;
}

if ($current_image && key_code == $.FroalaEditor.KEYCODE.ESC) {
  _exitEdit(true);
  e.preventDefault();
  return false;
}

if ($current_image && !editor.keys.ctrlKey(e)) {
  e.preventDefault();
  return false;
}
}, true);
```

**Comment by stefanneculai** [comment]
Hi @largeden! Last commit should fix it. Could you please check? Thanks.

**Comment by largeden** [comment]
@stefanneculai 

Good! :+1: 
It has been resolved.
