### ISSUE TITLE
Dropping content on to the editor does not respect allowed tags rule

### ISSUE THREAD

**Issue by euangoddard** [froala/wysiwyg-editor#981]
## Steps to reproduce

1. Load an editor with a limited set of `htmlAllowedTags` configured (e.g. `['p', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6']`)
1. On the same page have some content which contains HTML elements outside (e.g. an image)
1. Select the image and drag and drop it into the editor

## Expected behaviour

The image element is rejected like when you paste copied HTML nodes into the editor

## Observed behaviour

No sanitizing is performed whatsoever (I have managed to drag `<input>` elements into the editor as well

## Affected browsers

- Chrome 47 on Linux, Window and OSX
- Firefox 42 on Windows and Linux (at least)

## Workaround

Call `preventDefault()` on the drop event in the editor. The problem with this is that any valid dropped nodes are also rejected.

**Comment by stefanneculai** [comment]
@euangoddard I have just tried this on Chrome 47 & OSX and I cannot reproduce it. Could you check with the master version?

**Comment by euangoddard** [comment]
I can try this, but has anything changed around the sanitization routine between 2.0.3 (which I'm using) and master?

**Comment by euangoddard** [comment]
I cannot reproduce this either on your example pages so I'll take a look at the configuration option to see if I can isolate what is fundamentally different between my config and those
