### ISSUE TITLE
The useClasses option does not properly inline image alignment styles

### ISSUE THREAD

**Issue by chrisdavies** [froala/wysiwyg-editor#982]
When the `useClasses` option is false, changing an image alignment does not produce inline-styles. For example, here is what I get when I try to right-align an image:

`style="cursor: pointer;" class="fr-dii fr-fir">`

So, it is putting some styles inline, but not the alignment itself.

Here is how I am initializing my editor:

```
var buttons = [
      'bold', 'italic' , '|',
      'paragraphFormat', '|',
      'align', '|',
      'formatOL', 'formatUL', '|',
      'outdent', 'indent', '|',
      'insertLink', 'blockquote', 'insertHR', 'filepicker', '|',
      'html'];

    self.$editor.froalaEditor({
      placeholderText: 'Whatevz...',
      heightMin: 200,
      theme: 'custom',
      codeMirror: true,
      imagePaste: false,
      useClasses: false,
      codeMirrorOptions: {
        indentWithTabs: true,
        lineNumbers: true,
        lineWrapping: true,
        mode: 'text/html',
        tabMode: 'indent',
        tabSize: 2
      },
      toolbarStickyOffset: 0,
      toolbarButtonsMD: buttons,
      toolbarButtonsSM: buttons,
      toolbarButtonsXS: buttons,
      toolbarButtons: buttons,
      imageDefaultAlign: 'left',
      imageDefaultWidth: 0,
      imageEditButtons: [
        'imageAlign', 'imageRemove', '|',
        'imageLink', 'linkOpen', 'linkEdit', 'linkRemove'],
      linkAlwaysBlank: true,
      linkInsertButtons: ['linkBack'],
      linkEditButtons: ['linkOpen', 'linkEdit', 'linkRemove'],
      shortcutsEnabled: ['bold', 'italic', 'undo', 'redo'],
      paragraphFormat: {
        N: 'Normal',
        H1: 'Heading 1',
        H2: 'Heading 2',
        H3: 'Heading 3',
      }
    });
```

Browser: Crome (latest) on Mac OSX (latest) using Froala 2.x

**Comment by stefanneculai** [comment]
Could you check this with version 2.0.5 (master)? Also, are you including any CSS style from remote locations over HTTPS?

**Comment by chrisdavies** [comment]
I just downloaded the latest, and yes, it occurs on that version. We are downloading FontAwesome from a remote location via HTTPS. And in production, we use CDNs. But on local, where I am getting a repro, only FontAwesome is on a CDN.

**Comment by stefanneculai** [comment]
Are you checking it using `html.get` or by toggling to code view?

**Comment by chrisdavies** [comment]
Code-view and also inspect element.

**Comment by stefanneculai** [comment]
In code-view and inspect element, the editor will use classes, but when you retrieve the HTML, it will convert them.

**Comment by chrisdavies** [comment]
Hm. That's not what I'm seeing. When I right-align and save an image, then view the resulting email, the image in the email has this markup:

```
<img src="the-url-to-the-image" style="z-index: 3; position: relative; overflow: auto; cursor: pointer;">
```

**Comment by chrisdavies** [comment]
Also, `html.get()` is what we are using to store the markup. I took a look at what it's giving, and it does not have alignment info in the style attribute.

**Comment by stefanneculai** [comment]
Could you make a jsFiddle to reproduce it?

**Comment by chrisdavies** [comment]
Will try. Give me a bit.

**Comment by stefanneculai** [comment]
Most probably it will be hard to make a jsFiddle with this option disabled. It might be easier if you could send me a link to a page where to check it. You can use the email from my profil if you don't want to make it public.

**Comment by chrisdavies** [comment]
Yeah. You're right. I'll put a zip file together for you.

**Comment by chrisdavies** [comment]
[froala-inline-styles-bug.zip](https://github.com/froala/wysiwyg-editor/files/61725/froala-inline-styles-bug.zip)

**Comment by chrisdavies** [comment]
I couldn't get it to even show image alignment options when I used 2.0.4, so maybe you can get that to work, but the same bug shows up in 2.0.3, and that version also properly showed image alignment options. Unzip the file and open the html file (I ran mine using a local python server, instructions are in the HTML file).

**Comment by stefanneculai** [comment]
There was a problem in 2.0.4 in few commits with the buttons not showing, but now it's fixed. We'll check the zip shortly.

**Comment by stefanneculai** [comment]
It's not working because you're include the CSS from CDN. You should include it from a location which is not remote. The CSS should be on the same server where you're page is and include it via absolute/relative path. It's a browser limitation which does not allow to read CSS properties from remote CSS styles.

It's best to use the V2.0.5 that we have released today. https://www.froala.com/wysiwyg-editor/changelog

**Comment by chrisdavies** [comment]
Yep. I can confirm this worked. Thanks!

**Comment by ChuchurroxD** [comment]
dkbgfnkñfdgñkfmñkmñmfdñgmfñmgkñfmgkmdgkmfdkgmdfkgmkdgmkfmgkfmdgkmfdgmfgmkfdmgkfdmgkdmfkgmfdkgmdgmfdmkfdg

**Comment by Suhas010** [comment]
**Will you please tell me?**
useClasses: true;
- Is it possible to include CSS from CDN?
- Is it allow to change image alignment?
if not what is the solution to this?

**Comment by stefanneculai** [comment]
@Suhas010 if you are using `useClasses: true`, then the editor uses classes for image alignment and other features. You can for sure include CSS from CDN and you can change the image alignment.

**Comment by Suhas010** [comment]
@stefanneculai 
thanks

**Comment by markedmondson** [comment]
@stefanneculai following up on:

> It's not working because you're include the CSS from CDN. You should include it from a location which is not remote. The CSS should be on the same server where you're page is and include it via absolute/relative path. It's a browser limitation which does not allow to read CSS properties from remote CSS styles.

Which is not _entirely_ true. If you give your CSS a CORS header allowing the requesting origin and add [a `crossorigin` attribute](https://www.w3.org/TR/html5/infrastructure.html#cors-settings-attribute) to the CSS link this does work (at least in Chrome 64+).

The tricky part (at least in my case) was getting that `Access-Control-Allow-Origin` header on the asset as it's served as a static asset from Rails through Cloudfront. I'll document the process someplace in case anyone else comes across it or should care...

**Comment by stefanneculai** [comment]
@markedmondson that is correct. Thanks for pointing this out.
