### ISSUE TITLE
Custom dropdown menu being cut by its parent

### ISSUE THREAD

**Issue by michaelkoper** [froala/wysiwyg-editor#983]
Hi

Not sure if this is fixable. Easier to explain with an image: https://cloudup.com/cdHjccDklHW

The problem is that the parent is smaller than the dropdown and its being cut.

Is there a solution for this? I don't see it.

**Comment by stefanneculai** [comment]
You should set the parent CSS `overflow: visible`.

**Comment by michaelkoper** [comment]
That fixed the issue, damn that was obvious! :(  

Thanks Stefan!
