### ISSUE TITLE
please add responsive for video

### ISSUE THREAD

**Issue by open2** [froala/wysiwyg-editor#985]
currently inserted youtube video has fixed width/height.
please add responsiveness for it.

here is a stackoverflow tip.
http://stackoverflow.com/questions/25228056/responsive-iframe-using-bootstrap

**Comment by stefanneculai** [comment]
We won't mix the editor with Bootstrap because not everyone is using it. However, you could use the [video.inserted event](https://www.froala.com/wysiwyg-editor/docs/events#video.inserted) to do that.

**Comment by raistlinthewiz** [comment]
I'm also up for this @stefanneculai , can we at lease get a sample usage example?

**Comment by stefanneculai** [comment]
The `video.inserted` event contains the video object. You should just set it's width.

**Comment by raistlinthewiz** [comment]
For future reference i'm adding this snipped here;

```
<div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
          <div class="embed-responsive embed-responsive-16by9">
                <iframe class="embed-responsive-item" src="//www.youtube.com/embed/gcigfyCcPSM" allowfullscreen></iframe>
         </div>
    </div>
</div>
```

**Comment by raistlinthewiz** [comment]
done! 

i managed it by myself;

```
            $('#editor').on('froalaEditor.video.inserted', function (e, editor, $video) {
                  var videoSource = $video.contents().get(0).src;
                  $video.html('<div class="row"><div class="col-xs-12 col-sm-12 col-md-12 col-lg-12"><div class="embed-responsive embed-responsive-16by9"><iframe class="embed-responsive-item" src="' + videoSource +'" frameborder="0" allowfullscreen></iframe></div></div></div>');
            });
```

**Comment by ayush** [comment]
Also see http://fitvidsjs.com

**Comment by 14falcons** [comment]
Simple css solution:

.fr-video{
    overflow:hidden !important;
    padding-bottom:56.25% !important;
    position:relative !important;
    height:0 !important;
}
.fr-video iframe{
    left:0 !important;
    top:0 !important;
    height:100% !important;
    width:100% !important;
    position:absolute !important;
}

**Comment by ahmedfeki** [comment]
> Simple css solution:
> 
> .fr-video{ overflow:hidden !important; padding-bottom:56.25% !important; position:relative !important; height:0 !important; } .fr-video iframe{ left:0 !important; top:0 !important; height:100% !important; width:100% !important; position:absolute !important; }

.desc .fr-video{
overflow:hidden !important;
padding-bottom:56.25% !important;
position:relative !important;
height:0 !important;
display:block; // I just added this because it's a span (inline)
}
.desc .fr-video iframe{
left:0 !important;
top:0 !important;
height:100% !important;
width:100% !important;
position:absolute !important;
}
