### ISSUE TITLE
Reversing the namespace

### ISSUE THREAD

**Issue by artsmc** [froala/wysiwyg-editor#986]
This is occurring in the ember editor but this really is a source issue:
$('.selector').on('froalaEditor.image.beforeUpload', callback(), this);
then inside callback I look for the namespace to return the event image.beforeUpload but it returns it in reverse: 
beforeUpload.image
That would be totally fine if that happen with every event but it does not. Can the namespace callback on each even be the same as the on function making the call.

**Comment by stefanneculai** [comment]
At a closer check it appears that jQuery is changing it. We'll fix it shortly.

**Comment by stefanneculai** [comment]
Closing this, because in ember we can do it differently and it's not necessary to change the event names in the editor itself.
