### ISSUE TITLE
image.beforeUpload param does not return image

### ISSUE THREAD

**Issue by artsmc** [froala/wysiwyg-editor#987]
Getting a strange return on images. I know the documentation says that it will return an array of images being uploaded, but the strange part is that you never upload more than one image and it returns an object with nothing in it. Even if the upload is successful
$('.selector').on('froalaEditor.image.beforeUpload', function (e, editor, images) {
 console.log(images)
});
/*OUTPUT
FileList {0: File}
*/

**Comment by artsmc** [comment]
re

**Comment by stefanneculai** [comment]
See https://github.com/froala/wysiwyg-editor/issues/399#issuecomment-70536920. I believe it's a confusion.
