### ISSUE TITLE
display edited content

### ISSUE THREAD

**Issue by benjibenji1** [froala/wysiwyg-editor#988]
hello 
i have installed fraola editor in my website and it's work fine but when i add content like 
http://google.com/
and when i display the edited content i see that 
 <p><a href="http://google.com/">http://google.com/</a></p>

**Comment by stefanneculai** [comment]
The URLS plugin is automatically converting links to `A` tags. If you don't want such behaviour then you should simply not include it.

By default the editor is wrapping the content into paragraphs. If you don't want to have them wrapped, then you should change the `enter` option.

**Comment by benjibenji1** [comment]
NO  when i display the edited content i see that 
![captureaa](https://cloud.githubusercontent.com/assets/16247977/11840259/b5619bc8-a3f4-11e5-8fb6-646faaf17fa2.PNG)

**Comment by stefanneculai** [comment]
When you're rendering the HTML, it is being displayed as string instead of HTML. You should mark is as safe to use so that is is displayed as HTML and not text.

**Comment by benjibenji1** [comment]
how can i make it displaying normally

**Comment by stefanneculai** [comment]
It depends on the Framework/Programming language you're using on server side. For example, in RoR you have html_safe helper for that.

**Comment by benjibenji1** [comment]
and in PHP ??

**Comment by stefanneculai** [comment]
In PHP it should display the HTML without problems, probably you're escaping it somehow. 

**We use this repo for bug tracking and not for support. We offer tech support under the Advanced/OEM license, therefore if you have such a license please contact us via our website.**

**Comment by benjibenji1** [comment]
ok thank you so much
