### ISSUE TITLE
Inline style margin gets filtered out

### ISSUE THREAD

**Issue by ericleethrinacia** [froala/wysiwyg-editor#991]
There is an issue regarding to inline style
In code view, if we copy and paste the code that looks something like
img src="" style="margin: 0 auto; width: 100%" 
Make a switch to text view and come back to code view
'margin: 0 auto' gets filtered out but 'width: 100%' stays

Typing out the line in the editor still results the same behavior
For some reason only margin gets filtered out

**Comment by ericleethrinacia** [comment]
Added !important then it stays
It was probably conflicting with the code you guys had that also applied margin

**Comment by ecuanaso** [comment]
I"m having the same issue whats the selector I have to add the !important for inline styling to work.
