### ISSUE TITLE
After Adding a Link in the Editor, Editor Scroll Snaps to the Top

### ISSUE THREAD

**Issue by benjaminknox** [froala/wysiwyg-editor#993]
When a link is added/updated in the editor, the editor scroll snaps back up to the top:

1) Click on the fullscreen example: https://www.froala.com/wysiwyg-editor/docs/examples/fullscreen
2) Click on the fullscreen button.
3) Paste in the lorem ipsum in the file attached.
[lorem-ipsum.txt](https://github.com/froala/wysiwyg-editor/files/67197/lorem-ipsum.txt)
4) Scroll below the visible height of the editor.
5) Create a link using the link button.
6) The screen should snap to the top.

**Comment by akhasanov** [comment]
+1
Very annoying option. Could you fix it please?
Thanks.
