### ISSUE TITLE
please add image roate for uploaded image

### ISSUE THREAD

**Issue by open2** [froala/wysiwyg-editor#996]
some photo uploaded 90 degree roated when image is uploaded in smart phone, 
please add 90 degress roate function.

http://stackoverflow.com/questions/20061774/rotate-an-image-in-image-source-in-html

**Comment by stefanneculai** [comment]
The editor is displaying the original image as it was taken. For the moment we don't have any tools for doing changes over the original image.

**Comment by aspire04** [comment]
This is helpful if you will add image rotate using exif.
