### ISSUE TITLE
Table vertical alignment is not selectable

### ISSUE THREAD

**Issue by Lednerb** [froala/wysiwyg-editor#997]
Hello again,

i'm using the latest version of the editor.
There is a bug by editing the vertical-alignment of a table cell.

When i try to change the option (top, center, bottom) nothing happens in the editor-view:

![vertical-alignment](https://cloud.githubusercontent.com/assets/2056876/11953310/6b52f93c-a89f-11e5-8cf6-1adf55da9798.png)

**Comment by Lednerb** [comment]
But the produced HTML-Code works well.

It seems to be only an editor-view-bug.

**Comment by stefanneculai** [comment]
If you have a cell on a row which doesn't have multiple lines then that's why you don't see any change.

**Comment by Lednerb** [comment]
Okay the screenshot is really bad.

I have 2 cells per row. In the first cell there is an image and in the second one there is some text.

In all cells there is content.

**Comment by stefanneculai** [comment]
Could you make the SS again?

**Comment by Lednerb** [comment]
![table-valign](https://cloud.githubusercontent.com/assets/2056876/11976560/9002e8a2-a979-11e5-902a-76910ae868ea.png)

**Comment by Lednerb** [comment]
The images are aligned to the top, but in the editor it's not correctly displayed.

**Comment by Lednerb** [comment]
That's the produced html code for the line "MOMO"

```html
<tr>
			<td style="width: 22.1574%; vertical-align: top;"><img class="fr-dib" src="/img/2fa0d5a2aed74e904b26aa104d4c56a6bcd75b66.jpg" style="width: 150px;">
				<br>
			</td>
			<td style="width: 77.6968%;"><span style="color: rgb(41, 105, 176);"><a href="https://tdn.slashdesign.it/de/inszenierungen-momo"><strong><span style="font-size: 18px;">MOMO</span>&nbsp;</strong>
				</a>
				<br><strong>nach Michael Ende</strong></span>
				<br><strong>f&uuml;r Familien, ab 10 Jahren, 150 Min. mit Pause</strong>
				<br>
				<br>
				<div style="text-align: justify;">Zeitdiebe wollen die Menschen dazu bringen, Zeit zu sparen wie Geld. Je mehr man aber versucht, Zeit zu sparen, desto &quot;k&uuml;rzer&quot; werden die Tage und Wochen. So hinterfragt Michael Ende unseren Umgang mit Zeit und Geld. Er setzt gegen die grauen Herren das M&auml;dchen Momo, die Schildkr&ouml;te Kassiopeia und Meister Hora, den geheimnisvollen Verwalter der Zeit.</div>
				<div style="text-align: right;"><a href="https://tdn.slashdesign.it/de/inszenierungen-momo"><span style="color: rgb(41, 105, 176);">mehr</span></a></div>
			</td>
		</tr>
```

**Comment by Lednerb** [comment]
Oh sorry that i wasted your time.

It's my fault. I have `vertical-align: middle !important` in an old part of the code... :-(
