### ISSUE TITLE
Links without http/https are being followed in the editor

### ISSUE THREAD

**Issue by Narzerus** [froala/wysiwyg-editor#999]
Hello, My company is using Froala (OEM license)

Because of the way I'm using Froala I'm requiring to insert links into the editor without `http` or `https` prefixing the URL.

I realized the editor apparently is not considering this case, causing it to allow the browser to follow links inside the editor text.

To reproduct:
- Go to HTML edit mode
- Add: `<a href="foo">Click here</a>`
- Go to normal edit mode
- Click in the link

Expected: Open edit options
Actual: Browser follows links

**Comment by stefanneculai** [comment]
Are you experiencing this on [our website](https://www.froala.com/wysiwyg-editor) as well?

**Comment by Narzerus** [comment]
Nopes, not in your browser... Could it be some specific plugin causing the issue?

**Comment by Narzerus** [comment]
Could you explain how is Froala preventing links from being followed in the editor? I have the uncompiled version so I could have a look and figure out what is it that conflicts with the default behavior

**Comment by stefanneculai** [comment]
Please contact us via [our website](https://www.froala.com/wysiwyg-editor/contact) for tech support included in the OEM license. Also, please make sure you're using the latest version.
